### ISSUE TITLE
Sparse Graph Laplacian- true divide issue

### ISSUE THREAD

**Issue by SvenPVoigt** [scipy/scipy#10006]
I was following this tutorial [scikit-learn sparse clustering](https://scikit-learn.org/stable/auto_examples/cluster/plot_coin_segmentation.html#sphx-glr-auto-examples-cluster-plot-coin-segmentation-py) when I ran into an issue.
This issue should be simple to solve. The laplacian of a sparse matrix in scipy is still using the old method of dividing and assigning for numpy arrays "ie A /= 2". However, this is deprecated when the inputs are ints and the outputs are floats, and instead should read something like "A = A/2".

For anyone facing similar issues: the problem can be avoided by casting the data of the input graph to float.

```
laplacian, dd = csgraph_laplacian(adjacency, normed=norm_laplacian, return_diag=True)
```

### Error message:

```
~/Packages/scikit-learn/sklearn/manifold/spectral_embedding_.py in spectral_embedding(adjacency, n_components, eigen_solver, random_state, eigen_tol, norm_laplacian, drop_first)
    237 
    238     laplacian, dd = csgraph_laplacian(adjacency, normed=norm_laplacian,
--> 239                                       return_diag=True)
    240     if (eigen_solver == 'arpack' or eigen_solver != 'lobpcg' and
    241        (not sparse.isspmatrix(laplacian) or n_nodes < 5 * n_components)):

~/miniconda3/envs/seg/lib/python3.7/site-packages/scipy/sparse/csgraph/_laplacian.py in laplacian(csgraph, normed, return_diag, use_out_degree)
     76     create_lap = _laplacian_sparse if isspmatrix(csgraph) else _laplacian_dense
     77     degree_axis = 1 if use_out_degree else 0
---> 78     lap, d = create_lap(csgraph, normed=normed, axis=degree_axis)
     79     if return_diag:
     80         return lap, d

~/miniconda3/envs/seg/lib/python3.7/site-packages/scipy/sparse/csgraph/_laplacian.py in _laplacian_sparse(graph, normed, axis)
     98         isolated_node_mask = (w == 0)
     99         w = np.where(isolated_node_mask, 1, np.sqrt(w))
--> 100         m.data /= w[m.row]
    101         m.data /= w[m.col]
    102         m.data *= -1

TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'B') according to the casting rule ''same_kind''
```

### Scipy/Numpy/Python version information:

1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)

**Comment by perimosocordiae** [comment]
The issue here isn't the in-place divide. The error comes from a dtype mismatch between the `m.data` array and the `w` array.

For related examples, see:
 - https://github.com/numpy/numpy/issues/6464
 - https://github.com/keras-team/keras/issues/8635#issuecomment-365136587

You can see the typecode -> type mappings here: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.typename.html

I wasn't able to replicate this error locally using the tutorial you linked to, so I'm not sure exactly why you're seeing this error. To work around the problem, you can convert your sparse matrix to a floating point type before computing the laplacian, using the `astype()` method.

The actual fix will require being more careful about dtypes in the `_laplacian_sparse` function.

**Comment by lobpcg** [comment]
Maybe I'll look into that after/if https://github.com/scipy/scipy/pull/15251 merges

**Comment by lobpcg** [comment]
#15391 provides a work-around for this issue, since no matrices are modified in #15391, so no scaling of the original matrix entries - if they were integer, they remain integer even for the normalized Laplacian.
