### ISSUE TITLE
Consider support for multivariate student-t distribution?

### ISSUE THREAD

**Issue by ktattan** [scipy/scipy#10042]
The [multivariate student-t distribution](https://en.wikipedia.org/wiki/Multivariate_t-distribution) is used extensively within academia, science and finance, primarily for its fatter tails (larger kurtosis) when compared to the normal distribution. This yields more rare events (random samples) that would almost never occur when sampling from a multivariate normal distribution.

The multivariate student-t can be expressed in terms of the [univariate chi-squared and multivariate normal](https://stackoverflow.com/a/41967819/4139143), or [univariate gamma and multivariate normal](https://stackoverflow.com/questions/29798795/multivariate-student-t-distribution-with-python). While these functions are very short and simple to write from scratch, having to maintain and test the function between different user applications just adds to overhead; in addition, these hand coded functions would not be fully optimized.

Therefore, I feel that scipy support of the multivariate student-t would greatly benefit the community. Thanks :)

**Comment by ev-br** [comment]
Pull requests welcome :-)

**Comment by gwgundersen** [comment]
I'd like to handle this. I've already implemented the method using SciPy's infrastructure (see here: https://github.com/gwgundersen/multivariate-t-distribution/blob/master/multivariatet.py) such as the `_PSD` class. I have a couple questions:

1. How should I test this? I tested the `pdf` function by manually comparing against MATLAB's implementation, but I assume SciPy has a more standard infra for this kind of thing. Also, how would I test the `rvs` function?
2. The CDF of the multivariate t-distribution has no closed-form solution. Should there simply be no `cdf` and `logcdf` functions or should they raise exceptions of type `NotImplementedError`?

**Comment by ktattan** [comment]
@gwgundersen That looks awesome. I'm not a moderator / contributor to scipy so I can only give my opinion, but here is how I would do this.

1. To test, yes maybe you can still test against matlab results for the multivariate-t. I have been using this bit of code from [here](https://stackoverflow.com/questions/29798795/multivariate-student-t-distribution-with-python) for the past year to generate rvs

```
def multivariate_t(mu, sigma, dof, m):
    """
    Produce m samples of d-dimensional multivariate t distribution
    
    Args:
        mu (numpy.ndarray): mean vector
        sigma (numpy.ndarray): scale matrix (covariance)
        dof (float): degrees of freedom
        m (int): # of samples to produce

    Returns:
        numpy.ndarray
    """
    d = len(sigma)
    g = np.tile(np.random.gamma(dof / 2 , 2 / dof, m), (d, 1)).T
    z = np.random.multivariate_normal(np.zeros(d),Sigma,M)
    return mu + z / np.sqrt(g)
```
as the multivariate-t can be expressed in terms of a gamma and normal distribution (or [chi-squared and normal](http://mathworld.wolfram.com/Studentst-Distribution.html)). So maybe you can also test against that bit of code.

2. As for the CDF, it seems the multivariate case isn't defined as you have said. But for the 1-d case it is defined in terms of the 2F1 hypergeometric function and gamma function, both of which are implemented in scipy.special [[1]](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.hyp2f1.html)[[2]](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gamma.html). For now it may be best to raise a `NotImplementedError` as you've said. What I have been doing is generating rvs samples using the code above and then using the already implemented 1-d `scipy.stats.t.cdf(samples)` to get the CDF which seems to work fine.

For 1-d cases, scipy has many methods for distributions e.g. `ppf`, `cdf`, `mean`, `std` etc. but for the one multivariate implemention, which is a normal distribution, it only has `pdf`, `logpdf`, `rvs` and `entropy`, so maybe it is enough to just implement these same methods for the multivariate-t.

**Comment by siddhantwahal** [comment]
Hi @gwgundersen,

Nice work! For testing, you can exploit some mathematical properties of the T-distribution:
1. When `df = 1`, the distribution is identical to the Cauchy distribution, so `multivariate_t.logpdf(x)`  and `cauchy.logpdf(x)` computed at some fixed `x` should be same.
2. When `df` is large, the distribution starts resembling a Gaussian distribution. Again, `multivariate_t.logpdf` should be close to `multivariate_normal.logpdf` (but won't be exactly equal).  Also, samples drawn from `multivariate_t.rvs` should be able to pass normality tests, such as the one [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.normaltest.html). I recommend testing a high `df` here, such as `df = 100_000`, in addition to the `df = np.inf` case, since the latter is handled explicitly in your code.
3. A simple, albeit brittle way to test `rvs` is to ensure that the mean and covariance of a large enough sample is close to its theoretical value. I say brittle because "large enough" and "close" are hard to estimate before writing the test. Remember that the covariance of the T-distribution is only defined when `df > 2`.

Hope this helps!

**Comment by josef-pkt** [comment]
about the cdf for multivariate t

There is code similar to the one scipy has for multivariate normal by genz. His normal cdf computation  in fortran are in scipy
http://www.math.wsu.edu/faculty/genz/homepage

As workaround because scipy doesn't have Genz's multivariate t code. I used the multivariate normal code and integrated with respect to chi (?) distribution
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/sandbox/distributions/multivariate.py#L66

There should also be some unit tests in the statsmodels sandbox that might be useful
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/sandbox/distributions/tests/test_multivariate.py

here's my ancient MVT class https://github.com/statsmodels/statsmodels/blob/master/statsmodels/sandbox/distributions/mv_normal.py#L1007

(for the normal case, scipy uses higher precision in the normal cdf computation than what I did)

BTW: R has an mvt package with Genz as coauthor AFAIR

**Comment by gwgundersen** [comment]
@ktattan, @siddhantwahal, @josef-pkt, thanks for the feedback. It's all very useful. I'm working on a PR now and will link to it when I push.

Does anyone (@ev-br?) know if I can perform a partial build of SciPy or run only some of the tests? Building and testing takes several minutes each, and it would be nice if I could make a modification to `_multivariate.py`, do a quick partial build, and then run the tests for just that module.

**Comment by ev-br** [comment]
A partial build, not easily. You can in principle selectively delete the parts of scipy which are not needed by the subpackage you're working on. Feels much more hassle than it's worth it, TBH.

Re: running subsets of tests: yes, certainly!
`python runtests.py -s subpackage` or `python -t path/to/test/file::test_name`

**Comment by andyfaff** [comment]
Should be `python runtests.py -t path/to/test/file::test_name`

Also you might be able to use `pip install -e .` which installs scipy in editable mode. So you can then make changes to pure python files, fire up an interpreter and test immediately. You can start the tests using `scipy.module.test()`

**Comment by gwgundersen** [comment]
Is there anything I need to do to get the PR reviewed or is it simply down to the core maintainers' time? I'm not sure what the typical time for a PR review is, but it's been a month and a half now.

**Comment by rgommers** [comment]
@gwgundersen your PR looks pretty good. It's indeed down to time from a maintainer with stats knowledge. I have added the 1.5.0 milestone, so we're sure not to forget before the next release.

> I'm not sure what the typical time for a PR review is, but it's been a month and a half now.

For complex PRs like this one, that's unfortunately not uncommon - SciPy is a complicated beast to maintain in evenings/weekends.

**Comment by gwgundersen** [comment]
Can anyone in this thread please help me get [this PR](https://github.com/scipy/scipy/pull/12582) in a stable state again? I believe the tests fail because the doc build fails because of [this inconsistency](https://github.com/scipy/scipy/blob/master/doc/Makefile#L68). In other words, I need to build SciPy locally and commit the updated version file, which will align the version numbers.

Assuming that's the correct issue, I can no longer [build SciPy from source](https://docs.scipy.org/doc/scipy/reference/dev/contributor/quickstart_mac.html#quickstart-mac). This linker command fails:

```bash
(scipy-dev) gwg:scipy gwg$ /usr/bin/gcc -bundle -undefined dynamic_lookup -L/Users/gwg/miniconda3/envs/scipy-dev/lib -arch x86_64 -L/Users/gwg/miniconda3/envs/scipy-dev/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/scipy/spatial/src/distance_wrap.o -L/Users/gwg/miniconda3/envs/scipy-dev/lib/python3.7/site-packages/numpy/core/lib -Lbuild/temp.macosx-10.9-x86_64-3.7 -lnpymath -o scipy/spatial/_distance_wrap.cpython-37m-darwin.so
```

with the following error:

```bash
ld: in /Users/gwg/miniconda3/envs/scipy-dev/lib/python3.7/site-packages/numpy/core/lib/libnpymath.a(npy_math.o), could not parse object file /Users/gwg/miniconda3/envs/scipy-dev/lib/python3.7/site-packages/numpy/core/lib/libnpymath.a(npy_math.o): 'Unknown attribute kind (61) (Producer: 'LLVM10.0.0' Reader: 'LLVM APPLE_1_1000.10.44.4_0')', using libLTO version 'LLVM version 10.0.0, (clang-1000.10.44.4)' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I _think_ the issue is related to the producer compiler being different from the reader compiler, since it says: "`Unknown attribute kind (61) (Producer: 'LLVM10.0.0' Reader: 'LLVM APPLE_1_1000.10.44.4_0')`". But I'm not sure how these are specified in the build process. My software versions are:

```
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I'm using macOS High Sierra 10.13.6.
