### ISSUE TITLE
possible to get a better error message when objective function returns an array?

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [scipy/scipy#10078]
When the user mistakenly supplies a function that returns an array (in my case, the code should have returned the sum of squares of the values in the array), `scipy.optimize.optimize` currently fails with the following unhelpful message:

   "ValueError: setting an array element with a sequence"

One way to provide a better error message is to modify `_approx_fprime_helper` as shown below:

    def _approx_fprime_helper(xk, f, epsilon, args=(), f0=None):
       """
       See ``approx_fprime``.  An optional initial function value arg is added.
       """
       if f0 is None:
           f0 = f(*((xk,) + args))
       grad = numpy.zeros((len(xk),), float)
       ei = numpy.zeros((len(xk),), float)

       for k in range(len(xk)):
           ei[k] = 1.0
           d = epsilon * ei

           try:
              grad[k]= (f(*((xk + d,) + args)) - f0) / d[k]
           except Exception as ex:
              raise ValueError("The user-provided objective function must return "
                "a scalar value.") from ex

           ei[k] = 0.0
       return grad

**Comment by WarrenWeckesser** [comment]
I've seen that error reported more than once on stackoverflow, too, so it would be nice if it could be handled with a more informative error message.  I don't think the proposed solution is what we want, because that would show the `ValueError` whenever the user's function raises an excepton of any kind.  For example, if the user's function raises `ZeroDivisionError: division by zero`, they would also see that `ValueError`, and that would just confuse the issue.

Instead, maybe something like this could be used (not tested):

        df = (f(*((xk + d,) + args)) - f0) / d[k]
        if not np.isscalar(df):
            raise ValueError("The user-provided objective function must return "
                             "a scalar value.")
        grad[k] = df

**Comment by Phillip-M-Feldman** [comment]
Warren,

I like your proposed solution.

Phillip
