### ISSUE TITLE
BUG: optimize: newton raises exception with complex x0

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#10103]
Here's an example where `newton` crashes unexpectedly (using scipy version `'1.4.0.dev0+b4bfa9d'`):

```
In [3]: from scipy.optimize import newton                                                                                                                            

In [4]: def f(z): 
   ...:     return z - 1 
   ...:                                                                                                                                                              

In [5]: newton(f, 1+1j)                                                                                                                                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-5306645b6b37> in <module>
----> 1 newton(f, 1+1j)

~/miniconda36/lib/python3.6/site-packages/scipy-1.4.0.dev0+b4bfa9d-py3.6-macosx-10.7-x86_64.egg/scipy/optimize/zeros.py in newton(func, x0, fprime, args, tol, maxiter, fprime2, x1, rtol, full_output, disp)
    323             eps = 1e-4
    324             p1 = x0 * (1 + eps)
--> 325             p1 += (eps if p1 >= 0 else -eps)
    326         q0 = func(p0, *args)
    327         funcalls += 1

TypeError: '>=' not supported between instances of 'complex' and 'int'
```

**Comment by pvanmulbregt** [comment]
This example calls `newton(f, x0)` with no `fprime` so the code backs off to using the secant method.
The example call provides only a single `x` value, so the code tries to construct a second value `p1`.
`p1` is a slightly scaled and shifted version of `x0`:  `p1 = (1+eps)*x0 + <offset>`
If `x0` is real positive, offsetting by `eps` is fine. If `x0` is negative, offsetting by `eps` would work against the scaling and could even result in `p1==x0`.  Hence the offsetting by `-eps` if `p1` is negative. `p1` being complex triggers the TypeError.
If I'm reading the history correctly, the code may have had this behavior since 2010 or earlier. 

The `optimize.root_scalar` method doesn't support this use case --- the user must provide two `x` values in order to invoke secant.

**Comment by WarrenWeckesser** [comment]
For what it's worth: if I change the line where the error is raised to

            p1 += (eps if p1.real >= 0 else -eps)

then all the `optimize` tests still pass, and my example works:

```
In [1]: from scipy.optimize import newton                                                                                                                            

In [2]: def f(z): 
   ...:     return z - 1 
   ...:                                                                                                                                                              

In [3]: newton(f, 1+1j)                                                                                                                                              
Out[3]: (1+5.0487097934133837e-29j)

In [4]: f(_)                                                                                                                                                         
Out[4]: 5.0487097934133837e-29j
```
I'm not recommending this change as the way to fix the bug, because I haven't investigated why that line is there in the first place.  It looks like a bit of a kludge put their to fix some special case. Indeed, if the line is simply removed, a couple tests fail.  But the quick fix does show that it should be easy to find a proper fix for this bug.

**Comment by pvanmulbregt** [comment]
Actually the change you show seems reasonable to me. @charris, any thoughts on why that line is there in the first place? 

I must admit that I don't particularly like the use case, finding the root of a function given one x-value by calling `newton(f, x0)`.  [I like boost's [bracket_and_solve_root](https://www.boost.org/doc/libs/1_70_0/libs/math/doc/html/math_toolkit/roots_noderiv/bracket_solve.html) approach better for that.]
And the [doc for newton](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.newton.html)  is perhaps a little vague as to what happens when prime is not provided.
```
x1 : float, optional
Another estimate of the zero that should be somewhere near the actual zero. Used if fprime is not provided.
```
I think I may have written that description of `x1`, and it may indeed imply that `x1` is needed `fprime` is not provided. But the code certainly has always supported not providing `x1`.  So we may have to support it a while longer and your modification seems safe and won't change any existing usage.

**Comment by charris** [comment]
I don't recall, but it looks like it attempts to increase the magnitude of `p1` by an absolute tolerance as well as a relative one. I think the possibility of complex was simply overlooked. If we had complex `sign` for complex `x/|x|`, then you could simply add that times eps, but zero might be a problem. The original goes back at least 8 years and was
```
        if x0 >= 0:
            p1 = x0*(1 + 1e-4) + 1e-4
        else:
            p1 = x0*(1 + 1e-4) - 1e-4
```
So one could do 
```
    p1 = (eps if x0 == 0 else x0 * (1 + eps) + eps * (x0 / abs(x0)))
```
But without remembering why I did it in the first place, I cannot say why it is needed.

**Comment by elvd** [comment]
Hello folks,

Came across this today after a google search. I was having a similar problem, i.e. `newton` was intermittently raising a `TypeError` when `x0` was complex.

Turns out that the exception was only raised for the built-in `complex` type which does not support comparisons to `int`. When I switched to using NumPy's `complex128` it all worked fine without any exceptions.

For reference, my SciPy version is `1.5.2`, NumPy is `1.19.2`, and Python is `3.6.13`.

**Comment by mbakker7** [comment]
I want to confirm that this works:

```
import numpy as np
from scipy.optimize import newton

def func(z):
    return 1 + z*z

newton(func, x0=np.complex128(1+1j), tol=1e-12)
```

But `x0=1+1j` still gives the error above (scipy 1.5.2). Great it works, but either the documentation should be changed to require `x0` to be `np.complex128`, or `x0` should be converted inside the function to `np.complex128` if it is regular `complex`.
