### ISSUE TITLE
LBFGS optimization restricted to bounded algorithm

### ISSUE THREAD

**Issue by cmglaze** [scipy/scipy#10218]
L-BFGS-B optimization algorithm appears to be restricted to using the constrained version algorithm (the "-B" part), which I'm guessing is a little slower than the unconstrained version (not sure if it's just overhead). More importantly, this means that even when the parameters are not bounded at all, Scipy's version has to create vectors of Nonetype, which unnecessarily takes up memory, esp. when models are big (like 50M parameters in my case).

What about making a separate LBFGS algorithm, or having that as an option in the same module?

### Reproducing code example:

```
Sample code to reproduce the problem
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by rgommers** [comment]
I remember someone else asked the same question at SciPy'19. Seems like a good idea.

In general: new optimization algorithms are always welcome if they add something over the existing local or global optimizers.

I'll close this, because we don't want to keep enhancement requests open as issues. PR welcome I'd say. As a separate algorithm seems better.
