### ISSUE TITLE
A bug in linear interpolation method of interp2d?

### ISSUE THREAD

**Issue by cometchaser** [scipy/scipy#10268]
Hi,

I was looking into how to use interp2d on a irrgular grid, when I found something weird:
I started first with an regular grid and I found an example, where the linear interpolation method can produce values above the maximum value of z. In my minimal example (see below) znew_3 has a maximum value of 11, where the maximum should be 10. 

Did I something wrong or is there a bug in the interpolation method?

```
import numpy as np
from scipy import interpolate

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
xx, yy = np.meshgrid(x, y)

z = np.array(
    [
        [0.0, 5.0, 4.0],
        [0.0, 10.0, 8.0],
        [0.0, 5.0, 4.0],
    ]
)

f_1 = interpolate.interp2d(xx, yy, z, kind="linear")
f_2 = interpolate.interp2d(x, y, z, kind="linear")
f_3 = interpolate.interp2d(np.ravel(xx), np.ravel(yy), np.ravel(z), kind="linear")

xnew = np.array([1, 2.1, 3])
ynew = np.array([4, 5, 6])

znew_1 = f_1(xnew, ynew)
znew_2 = f_2(xnew, ynew)
znew_3 = f_3(xnew, ynew)
```

### Scipy/Numpy/Python version information:
1.2.1 1.16.3 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

**Comment by jwd0023** [comment]
I tried out your example, and I also think it's giving incorrect results (f_1 and f_3 are incorrect, f_2 is correct).

I'd recommend either making your interpolators as you did in f_2, or use interpolate.griddata.

https://stackoverflow.com/a/37872172/7237695 discusses why *not* to use interp2d because it apparently just doesn't work. It also contains examples using the griddata I recommended above.

**Comment by jwd0023** [comment]
Also, if you want to make your example more minimal and easier to understand, you can just look at f_1(2.1, 5), f_2(2.1, 5), and f_3(2.1, 5) and see that only f_2 provides the correct answer.

**Comment by ev-br** [comment]
Indeed, `interp2d` solves two different mathematical problems depending on whether the input arguments have matching lengths or `z.size == x.size * y.size`. And neither of these modes actually guarantees that the interpolated results behaves as expected, that it is bilinear in data. In short, the FITPACK knot selection algorithm may insert spline knots away from the data; with this, the result is not unique and FITPACK returns *some* function which satisfies the interpolation conditions. In fact, it does unless it failed to satisfy the interpolation conditions, in which case it returns something else.

https://scipy.github.io/devdocs/tutorial/interpolate/smoothing_splines.html#d-smoothing-splines has a discussion of the two interpolation modes, and https://gist.github.com/ev-br/8544371b40f414b7eaf3fe6217209bff contains an illustration of the difference between them. It also contains recommendations for what to use instead of `interp2d`. 

The latter is now deprecated in scipy 1.10 and will be removed in a future scipy version. This issue is one reason for the deprecation, in fact. 
Therefore, `interp2d` behavior will not be fixed, and users are advised to move to replacement routines, as discussed in the notebook from the previous paragraph.

I'm going to close the issue as a wontfix; feel free to keep discussing however.
