### ISSUE TITLE
Intermittent  test failure in _differential_evolution

### ISSUE THREAD

**Issue by peterbell10** [scipy/scipy#10279]
I have had the same test failure in `optimize._differential_evolution` several times while working on completely unrelated code. The test will pass and fail seemingly at random, even if running the test suite multiple times with no changes to any code.

### Error message:

<details>
<summary>scipy/optimize/tests/test__differential_evolution.py:665: AssertionError</summary>

```
______________________________ TestDifferentialEvolutionSolver.test_impossible_constraint ______________________________
[gw0] linux -- Python 3.7.1 /usr/bin/py
self = <scipy.optimize.tests.test__differential_evolution.TestDifferentialEvolutionSolver object at 0x7efffde4c7f0>
    def test_impossible_constraint(self):
        def constr_f(x):
            return np.array([x[0] + x[1]])
        nlc = NonlinearConstraint(constr_f, -np.inf, -1)
        solver = DifferentialEvolutionSolver(rosen, [(0, 2), (0, 2)],
                                             constraints=(nlc), popsize=3)
        # a UserWarning is issued because the 'trust-constr' polishing is
        # attempted on the least infeasible solution found.
        with warns(UserWarning):
            res = solver.solve()
>       assert_allclose(res.x, [0, 0], atol=1e-6)
E       AssertionError:
E       Not equal to tolerance rtol=1e-07, atol=1e-06
E
E       Mismatch: 50%
E       Max absolute difference: 7.48738823e-06
E       Max relative difference: inf
E        x: array([7.487388e-06, 1.110223e-16])
E        y: array([0, 0])
constr_f   = <function TestDifferentialEvolutionSolver.test_impossible_constraint.
<locals>.constr_f at 0x7f003891cbf8>
nlc        = <scipy.optimize._constraints.NonlinearConstraint object at 0x7efff5b7c6d8>
res        =            constr: [array([1.00000749])]
constr_violation: 1.0000074873882285
             fun: inf
    maxc... nfev: 1467
             nit: 1000
         success: False
               x: array([7.48738823e-06, 1.11022302e-16])
self       = <scipy.optimize.tests.test__differential_evolution.TestDifferentialEvolutionSolver object at 0x7efffde4c7f0>
solver     = <scipy.optimize._differentialevolution.DifferentialEvolutionSolver object at 0x7f00389b6198>
scipy/optimize/tests/test__differential_evolution.py:665: AssertionError  
```
</details>

### Scipy/Numpy/Python version information:
```
1.4.0.dev0+8b334af 1.16.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
I can reproduce this.  I don't recall seeing the error when I run the full test suite, but if I run just the differential evolution tests with

   $ python runtests.py -n -s optimize.tests.test__differential_evolution

I see the error most of the time.

**Comment by andyfaff** [comment]
This should be a straightforward fix, in that the test tolerance needs adjusting. The differential evolution solve is constrained to have the sum of both parameters be less than -1, but each parameter can be no less than 0. When the main part of the differential evolution solve finishes, both parameters will be very close to 0. The solver then tries to polish the solution using `trust-constr` (with the same impossible constraints/bounds). This process just tips the parameters less than 0. I'm not sure how far the `trust-constr` optimiser is permitted to go out of bounds here. That permitted error should be the `atol` parameter here. @mdhaber any thoughts on what it could be relaxed to, 1 or 2e-5?

The failure is intermittent is because the test is not seeded (and doesn't really need to be).

**Comment by mdhaber** [comment]
When skimming this it looked like a tolerance issue, too, in which case 1e-5 would be fine. But I'm not sure that we should rely on the local minimizer to return a point near the origin. It might be its tendency to minimize the residual, but is that guaranteed/documented? 

I guess I didn't look carefully at this test before, but if the test is checking that DE responds appropriately when the problem is infeasible, I'd suggest just turning the polishing off and checking for the appropriate status from DE. You might separately leave polish on and check for the appropriate status rather than a particular solution value.

**Comment by andyfaff** [comment]
> But I'm not sure that we should rely on the local minimizer to return a point near the origin. It might be its tendency to minimize the residual, but is that guaranteed/documented?

I just happened to make the lower bound for both parameters to be 0, I could've chosen 0.5. In that case trust-constr might've polished to e.g. `0.499xx`. L666, 667 check the overall status of an impossible polished differential evolution solve, L665 just checks that the `trust-constr` polishing doesn't go very far past a boundary. That line is probably not necessary, but I think I'll just adjust the test tolerance.

**Comment by andyfaff** [comment]
Turns out that 1e-5 wouldn't fix it either. When I use a seed the tol would need to be 1.52e-4. It's unclear to me from the [documentation](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-trustconstr.html) how much the bounds are allowed to be exceeded by.
I'm probably just going to remove the check on L665 at this point.
