### ISSUE TITLE
Broken imports

### ISSUE THREAD

**Issue by soerenwolfers** [scipy/scipy#10284]
### Reproducing code example:

```
import scipy.optimize
scipy.linalg.cholesky(1)` 
```

works but

```
import scipy
scipy.linalg.cholesky(1)
```

throws

 `AttributeError: module 'scipy' has no attribute 'linalg'`

I have always had to fiddle around with scipy imports but thought I just didn't fully understand python imports. The behavior above, however, convinced me that there is something fundamentally broken about scipy imports that is worth bringing to the attention of the developers. I am sure you can rationalize this behavior, but I don't think anyone from the outside would not consider this a bug.  (In my opinion, the second snippet should work and the first shouldn't, but any combination of working and not working would be better than the current one)

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
>>> 1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
Nothing is broken here @soerenwolfers. The one rule to understand is: import a submodule explicitly. That's all. This is explained in more detail in http://scipy.github.io/devdocs/api.html#guidelines-for-importing-functions-from-scipy

The reason your second example fails is because no submodules got imported at all.

Your first example just happens to work, but is not guaranteed to - so stick to explicit imports instead. The reason it does happen to work is that `optimize` relies on `linalg` and therefore imports it, which happens to make it available for you as well (that's how Python imports work).

**Comment by rgommers** [comment]
I'll close this, because there's nothing to fix here.

**Comment by patel-zeel** [comment]
This is too confusing. How does a novice user suppose to know that scipy doesn't work the way other packages do?
