### ISSUE TITLE
events in scipy.integrate.solve_ivp: How do I setup an events criteria?

### ISSUE THREAD

**Issue by deschenk** [scipy/scipy#10319]
In the following code, I simulate a parashoot in free fall. I want the simulation to stop at the ground (y = 0) or one point below. Currently, I have the problem, that the simulation terminates around y = 8.77... above 0. How can I set up the termination event?

Reproducing code example:
```
g = 10
k = 0.01

def para(t,Y):
    y1 = Y[0]
    y2 = Y[1]
    dy1_dt = y2
    dy2_dt = -g + k*y2**2
    return [dy1_dt,dy2_dt]

def hit_ground(t, Y): return Y[0]


import numpy as np
tend = 40
time = np.linspace(0,tend,100)
tspan = (0, tend)

Y0 = [1000,0]

from scipy.integrate import solve_ivp
hit_ground.terminal = True
Y = solve_ivp(para,tspan,Y0,events=hit_ground,t_eval=time)

if Y.status == 1:
    print('Success, termination event occured.')
if Y.status == 0:
    print('Success, t end reached.')

plt.plot(Y.t,Y.y[0,:],'k-',label='Y')
plt.plot(Y.t,Y.y[1,:],'r-',label='dY/dt')
plt.xlabel('Time')
plt.ylabel('Hight')
plt.legend()
plt.grid()
plt.xlim(0,Y.t[-1]+5) 
```

**Comment by MatthewFlamm** [comment]
Definitely not the expected result.  Using `t_eval` with `events` causes the event time point to not be appended to the result as you found out.  I suggest until this is fixed that you remove `t_eval` from the call to `solve_ivp` and use `dense_output=True` and then generate your `y` values at `t_eval ` using the returned `sol` attribute.

**Comment by jkunimune15** [comment]
For very long and complex simulations, `dense_output` is not always a possibility, as it increases the memory usage considerably. I think that given that a terminal event will prevent `solution.t` from being equivalent to `t_eval` anyway, it would not be unreasonable to include the terminal event time in `solution.t`. Either that, or the `y_events` could be returned along with `t_events`, so that you can easily append the terminal state onto `solution.y` if needed.

**Comment by nmayorov** [comment]
After #10672 merged, the `solve_ivp` result contains `y_events` for corresponding `t_events`.

@deschenk feel free to reopen if you think that it is not properly resolved.
