### ISSUE TITLE
ambiguous behaviour of disp=True and callback on differential_evolution

### ISSUE THREAD

**Issue by ggrrll** [scipy/scipy#10325]
Hi, 

I am writing as I cannot understand how the display of continuous progress works.
-- this is somehow related to #6019 and #9410  and follows from [this SO post](https://stackoverflow.com/questions/16739065/how-to-display-progress-of-scipy-optimize-function#comment99859382_47171025) -- 

I cannot really share my code, but basically I am using this simple callback:
```
def cb_fun(par,convergence=1):
    global nfeval
    print('nfeval:',nfeval,'parameters:',par)
    nfeval +=1
```

In some runs I have the intermediate results displayed , while in other not.
Furthermore, when it's showed, it happens that for long time `differential_evolution` doesn't return anything  for hours, while sometimes I see an 'avalanche' of saved intermediated results...

(I am storing the results in a file, with something like `python3.7 my_script.py > my_results.txt  2>&1 &`)

Do you have 

Thanks for your help

**Comment by andyfaff** [comment]
For `differential_evolution` the `disp` option [prints a message](https://github.com/scipy/scipy/blob/v1.3.0/scipy/optimize/_differentialevolution.py#L705) containing the evaluated objective function every iteration.

If a `callback` function is provided then it is called on [**every** iteration](https://github.com/scipy/scipy/blob/v1.3.0/scipy/optimize/_differentialevolution.py#L771)

The following code snippet shows that the callback is being evaluated at each step. Note that the number of iterations reported from the `Callback` object during and after the run, and the `OptimizeResult` are the same.

```
class Callback(object):
    def __init__(self):
        self.nit = 0

    def __call__(self, par, convergence=0):
        self.nit += 1
        print(self.nit, par)

from scipy.optimize import rosen, differential_evolution
bounds = [(0,2), (0, 2), (0, 2), (0, 2), (0, 2)]
c = Callback()
result = differential_evolution(rosen, bounds, callback=c, tol=0.1)
print(c.nit)
print(result)
```

gives

```
1 [0.44295789 0.47653778 0.61702421 0.53456641 0.29708364]
2 [1.03766421 1.01113318 1.04854346 0.89248086 0.68132351]
<snip>
580 [1. 1. 1. 1. 1.]
581 [1. 1. 1. 1. 1.]
581
     fun: 0.0
 message: 'Optimization terminated successfully.'
    nfev: 43656
     nit: 581
 success: True
       x: array([1., 1., 1., 1., 1.])
```

I'm guessing that the avalanche of results you see from time to time is due to file buffering, Python doesn't necessarily write to the file immediately, you have to flush to get that.

**Comment by ggrrll** [comment]
ok thanks -- I will check out the flushing (which I've just discovered -- thanks)
