### ISSUE TITLE
NEP 18 support for sparse matrices

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#10362]
It would be good to add support for [NEP 18]( https://www.numpy.org/neps/nep-0018-array-function-protocol.html ) to SciPy sparse matrices. This would allow arbitrary NumPy operations (like `np.concatenate`) to be used with SciPy sparse matrices. Should also improve reusability of NumPy based codes with SciPy sparse matrices.

cc @pentschev

**Comment by rgommers** [comment]
That would require a lot of functions to be implemented. E.g. `concatenate`, `std` don't exist for sparse matrices. So it can be done, but what set of functions needs to be supported?

**Comment by perimosocordiae** [comment]
@pv has more direct experience, but I believe the consensus is that NEP 18 cannot apply to scipy.sparse matrices for the same reason it can't apply to numpy.matrix objects: they fundamentally don't follow the ndarray API.

The most noticeable example is the behavior of __mul__, but the inconsistencies are manyfold. Unfortunately, this means user code dealing with these objects cannot simply treat them like duck arrays.

There are ongoing efforts to provide a sparse ndarray-like that is compatible, however: pydata/sparse is actively being developed, though I'm not aware if it implements NEP 18 yet.

**Comment by jakirkham** [comment]
Good question @rgommers. Will look into that and get back to you.

Thanks for the info, @perimosocordiae. It would be good to hear more people's thoughts on this.

Yes Sparse implements NEP 18. This was added in [the recent release, 0.7.0]( https://sparse.pydata.org/en/0.7.0/changelog.html#id1 ). Though as the library itself is still under development. So there may occasionally be NumPy-like functions that are missed there. We've been working with them to build this out further.

Is the long term strategy to eventually replace the sparse arrays in SciPy with the functionality supplied by Sparse?

**Comment by rgommers** [comment]
> Is the long term strategy to eventually replace the sparse arrays in SciPy with the functionality supplied by Sparse?

http://scipy.github.io/devdocs/roadmap.html#implement-sparse-arrays-in-addition-to-sparse-matrices

**Comment by rgommers** [comment]
> That would require a lot of functions to be implemented

Perhaps not necessarily. From https://github.com/numpy/numpy/pull/12005#discussion_r219684436 by @shoyer: _a project like `scipy.sparse` might define a starter `__array_function__` that returns (almost) always returns `NotImplemented`, just as a way to guarantee that scipy matrices don't get inadvertently coerced into numpy arrays._ That could be a good idea.

> The most noticeable example is the behavior of `__mul__`, but the inconsistencies are manyfold. Unfortunately, this means user code dealing with these objects cannot simply treat them like duck arrays.

It would be possible to raise an error in `spmatrix.__array_function__` unless the input is 2-D, to guard against this.

**Comment by shoyer** [comment]
`__array_function__` doesn't require any invariants about the implementation of numpy functions -- it just gives you a way to implement them.

`scipy.sparse` already implements `__array__` by raising `TypeError`, so I think it would be *very* safe to add a minimal `__array_function__` method that returns `NotImplemented`, and to start implementing NumPy functions one at a time. Right now pretty much any NumPy function will raise an error when called on a sparse matrix, because they end up calling `__array__` (via `np.asarray()`).

It's less clear if this would *useful*, given the API differences between `scipy.sparse` and NumPy. There's no way they would be compatible from a duck-typing perspective. But certainly this would be *safe*.

**Comment by rgommers** [comment]
> `scipy.sparse` already implements `__array__` by raising `TypeError`, 

IIRC this has been discussed, but it's not been implemented:
```
>>> from scipy import sparse                                                                   
>>> s = sparse.csr_matrix((3, 4))                                                              
>>> np.asarray(s)                                                                              
array(<3x4 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>, dtype=object)
>>> np.mean(s)                                                                                 
0.0
>>> np.__version__                                                                             
'1.17.3'
>>> import scipy; scipy.__version__                                                            
'1.2.1'
```
In current master, `__array__` is still not defined.

> so I think it would be _very_ safe to add a minimal `__array_function__` method that returns `NotImplemented`, 

It would be a backwards compat break. Starting to raise `TypeError` more may actually be a good thing, but "very safe" it isn't I'd say.

> It's less clear if this would _useful_, given the API differences between `scipy.sparse` and NumPy. There's no way they would be compatible from a duck-typing perspective. But certainly this would be _safe_.

Not all that useful probably. Also, the effort is probably simply better spent improving `pydata/sparse` - there's a lot to do there still in terms of implementing NumPy-compatible functions.

**Comment by rgommers** [comment]
I had a look at this again. Making `__array__` raise `TypeError` won't work, because right now using ufuncs on sparse matrices works via object arrays. From https://github.com/scipy/scipy/pull/7349#issuecomment-298080973:

_The failures introduced here are due to that unary ufuncs *used* to work (via the object array + attribute lookup path). I'm not certain it's possible vs backward compatibility to add `__array_ufunc__ = None` to sparse matrices. In particular, numpy's refusal to deal with `+=` in this case is probably a dealbreaker. So as I said earlier, `__array_ufunc__` is irrelevant for scipy's sparse matrices._

Note: unary ufuncs work again, perhaps it was temporarily broken at the time that comment was made. 

I tried adding `def __array__(self): raise TypeError` and that resulted in 68 failures in the test suite, and the code looked fine - it really did rely correcty on object array wrapping.

So I think we can close this issue - we can't really change anything in a way that's useful.
