### ISSUE TITLE
lil_martix build multi thread not work, but multi process work

### ISSUE THREAD

**Issue by wanghaoyu1** [scipy/scipy#10367]
My issue is 

  we need to build a big lil martix  by insert every single item , it's so slow, so i use multi thread to solve it, first i create a lil every thread then transfer to csr and combine to a big csr.

   but we find multi thread still slow , and my  machine cpu used about 15%,then i change the code to use multi process instead of multi thread , it's so fast, and cpu always 100%

  but now i need to solve communication between different process , i use queue ,but it's slow

  can you tell me how to solve it? thank you!

**Comment by perimosocordiae** [comment]
The poor performance with threads is likely due to GIL contention. There's not much we can do about that.

I would recommend not using LIL format as an intermediate step, but rather keeping track of the row and column indices for each point you want to insert. If you accumulate three arrays (row indices, column indices, and data values) then it's quite efficient to create a CSR matrix directly. You can also construct these arrays in parallel processes that write them to disk, and finally read all the chunks and assemble the matrix.
