### ISSUE TITLE
`splder` is incompatible with `splprep`

### ISSUE THREAD

**Issue by q-wertz** [scipy/scipy#10389]
I stumbled into the same issue as described here: [Stackoverflow](https://stackoverflow.com/questions/56357436/spline-in-3d-can-not-be-differentiated-due-to-an-attributeerror/56852144#56852144).
At the moment I try to circumvent this error by using the workaround described there.

### Reproducing code example:
```Python
import numpy as np
from scipy import interpolate

points = np.random.rand(10,2) * 10

(tck, u), fp, ier, msg = interpolate.splprep(points.T, s=0, k=3, full_output=True)

# Calculate derivative
spline_der = interpolate.splder(tck, n=1)
```

### Error message:
```
Traceback (most recent call last):
  File "/snap/pycharm-community/132/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/snap/pycharm-community/132/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/132/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/132/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/clemens/VCS/gpstracksimulator/test.py", line 19, in <module>
    spline_der = interpolate.splder(tck, n=1)
  File "/home/clemens/VCS/PythonVenv/GPSTrackSimulator/lib/python3.7/site-packages/scipy/interpolate/fitpack.py", line 657, in splder
    return _impl.splder(tck, n)
  File "/home/clemens/VCS/PythonVenv/GPSTrackSimulator/lib/python3.7/site-packages/scipy/interpolate/_fitpack_impl.py", line 1206, in splder
    sh = (slice(None),) + ((None,)*len(c.shape[1:]))
AttributeError: 'list' object has no attribute 'shape'
```

### Scipy/Numpy/Python version information:
```
Scipy: 1.3.0
Numpy: 1.16.4
Python: 3.7
```

**Comment by ev-br** [comment]
Prefer using `make_interp_spline` / `BSpline` objects in new code, these should work fine with n-D coefficient arrays.

**Comment by q-wertz** [comment]
Thank you for the comment. I tried to use `BSpline` before (but in a probably wrong way by trying to generate it from the output of `splprep`), but there I also stumble into quite strange errors (or is the output of `splprep` not compatible to the `BSpline` class?
```Python
import numpy as np
from scipy import interpolate

points = np.concatenate((np.linspace(0.0, 5.0, 20, endpoint=True).reshape(20, 1), np.full((20, 1), 5.0) + np.random.rand(20, 1)), axis=1)

(tck, u), fp, ier, msg = interpolate.splprep(points.T, s=0, k=3, full_output=True)

t = np.array(tck[0])
c = np.array(tck[1])
k = tck[2]

bspline = interpolate.BSpline(t, c, k)
```

### Error message:
```
Traceback (most recent call last):
  File "/snap/pycharm-community/132/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/snap/pycharm-community/132/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/132/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/132/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/clemens/VCS/gpstracksimulator/test.py", line 17, in <module>
    bspline = interpolate.BSpline(t, c, k)
  File "/home/clemens/VCS/PythonVenv/GPSTrackSimulator/lib/python3.7/site-packages/scipy/interpolate/_bsplines.py", line 223, in __init__
    raise ValueError("Knots, coefficients and degree are inconsistent.")
ValueError: Knots, coefficients and degree are inconsistent.
```

I will try using `make_interp_spline`.

**Comment by ev-br** [comment]
The main issue here is that indeed, `splprep` returns the coefficients as a list of arrays, and this is inconsistent with `splder`. As noted at SO, `splev` can evaluate derivatives, and `splev` *is* consistent with both `splrep` and `splprep`. (please file a bug if you find a counterexample).

This is a known wart, and it's frozen by backwards compatibility.

-----------------

An alternative is to avoid `splprep(..., s=0)` entirely and use `make_interp_spline`. Here's an example of replicating the `splprep` outputs. First let's make sense out of the `splprep` output:

```
# start with the OP example
import numpy as np
from scipy import interpolate

points = np.random.rand(10,2) * 10

(tck, u), fp, ier, msg = interpolate.splprep(points.T, s=0, k=3, full_output=True)

# check the meaning of the `u` array: evaluation of the spline at `u`
# gives back the original points (up to a list/transpose)

xy = interpolate.splev(u, tck)
xy = np.asarray(xy)
np.allclose(xy.T, points)
```

Next, let's replicate it without `splprep`.  First, build the `u` array: the curve is represented parametrically, and `u` is essentially an approximation for the arc length. Other parametrizations are possible, but here let's stick to what `splprep` does. Translating the pseudocode from the splprep doc page,

```
vv = np.sum((points[1:, :] - points[:-1, :])**2, axis=1)
vv = np.sqrt(vv).cumsum()
vv/= vv[-1]
vv = np.r_[0, vv]

# check: 
np.allclose(u, vv)
```

Now, interpolate along the parametric curve: `points` vs `vv`:

```
spl = interpolate.make_interp_spline(vv, points)

# check spl.t vs knots from splPrep
spl.t - tck[0]
```

The result, `spl`, is a `BSpline` object which you can evaluate, differentiate etc in a usual way:

```
np.allclose(points, spl(vv))

# differentiate
spl_derivative = spl.derivative(vv)
```

------------------------------------------------------------------

Finally, since this is confusing and does show up every now and then, some explanation could in principle be added to e.g. `scipy.interpolate` tutorial (https://docs.scipy.org/doc/scipy/reference/tutorial/interpolate.html). Help is wanted and appreciated. Perspective of someone who is relatively new to it would be especially helpful.

**Comment by ev-br** [comment]
Since this is an API wart which is not going to be fixed, I'm going to close the issue. Thanks for reporting it @q-wertz
