### ISSUE TITLE
BFGS / L-BFGS-B Calling objective one extra time

### ISSUE THREAD

**Issue by aaronsnoswell** [scipy/scipy#10385]
Thanks for the amazing library!

My issue is about what I believe is a bug in the BFGS optimizer implementation. When calling `scipy.optimize.minimze(method='bfgs')`, Scipy always calls my objective function with the exact same parameter vector the first two times. This seems unnecessary as it wastes a good few minutes computing the exact same thing.

[Stack Overflow link](https://stackoverflow.com/questions/56828860/scipy-optimize-minimize-with-bfgs-objective-called-twice-with-same-parameter-ve/56831844#56831844). It appears that this same problem was previously reported in #4076, then fixed in https://github.com/scipy/scipy/pull/4083, but now appears to be back?

### Reproducing code example:
```python
from scipy.optimize import minimize

def obj_jac(x):
    """Return objective value and jacobian value wrt. x"""
    print(x)
    return 10*x**2, 20*x

minimize(obj_jac, -100, method='bfgs', jac=True, tol=1e-7)
```

Output;

```bash
[-100.]
[-100.]
[-98.99]
[-94.95]
[-78.79]
[-30.17904355]
[-3.55271368e-15]
```

### Scipy/Numpy/Python version information:
```
1.2.1 1.16.3 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

I'm on Windows 10 64 bit. If someone can help me identify the relevant area of the bfgs implementation code, I'm happy to work up a PR to fix this.

**Comment by ewmoore** [comment]
I think you can move one line in the function [_minimize_bfgs](https://github.com/scipy/scipy/blob/df6b808d4399b29b46e18b04e7e458862c0ce194/scipy/optimize/optimize.py#L965).  In the section copied below (starting on line 1004), moving the `gfk = myfprime(x0)` line to immediately after the `old_fval = f(x0)` line appears to fix this issue for me. 
```
    gfk = myfprime(x0)
    k = 0
    N = len(x0)
    I = numpy.eye(N, dtype=int)
    Hk = I


    # Sets the initial step guess to dx ~ 1
    old_fval = f(x0)
    old_old_fval = old_fval + np.linalg.norm(gfk) / 2
```

This is is sufficient to fix the issue since the `MemoizeJac` object that wraps the object and jacobian function only caches the jacobian value and not the objective function value.  If the jacobian is evaluated after the objective this works fine.  Otherwise you get this double evaluation.

Since this will be the second time this is fixed probably worth thinking about how to write a test for this scenario that can be run across all of the minimization methods.

Looking forward to your PR!

**Comment by aaronsnoswell** [comment]
I see you beat me to it! Thanks!
