### ISSUE TITLE
DOC: Instructions for adding a new stats distribution

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#10386]
The procedure for adding a new statistics distribution doesn't appear to be in the doc.  The process may be complicated enough that it should be.  Here is what it was at some recent time in the past, but it may have changed already.
The question is: Does this information belong in the Development Doc Overhaul gh-10286, or somewhere else?

How to create a new continuous distribution `XXXXX` (discrete is similar).
* See if it already been implemented (that saves a lot of effort)
    * It may have been implemented with a different name.
    * It may have been implemented with a different parameterization (shape parameters).
    * It may be a specialization of a more general family of distributions.
* Find an already existing distribution similar to `XXXXX`.  Use its code as a template for  `XXXXX`.
* Read the doctstring for class `rv_continuous`.
* Write the new code, insert it into `scipy/stats/_continuous_distns.py`.
    * Does the distribution have infinite support?  If not, need to specify left or right endpoints `a`, `b`.  If the support depends upon the shape parameters, need to implement `_get_support`.
    * If `ppf` is expensive relative to `pdf`, consider setting `momtype`.
* Add the name to the listing in the docstring of `scipy/stats/__init__.py`.
* Add the name and a good set of example shape parameters to the `distcont` list in `scipy/stats/_distr_params.py`.
* Add the name to the `dists` list at the top of `scipy/stats/tests/test_distributions.py`. 
* Add any specific tests to `scipy/stats/tests/test_distributions.py`.
* Run and pass the tests.
* Add a tutorial  `doc/source/tutorial/stats/continuous_XXXXX.rst`
* Add entry to `doc/source/tutorial/stats/continuous.rst`.
* Update the # distributions in the example code in `doc/source/tutorial/stats.rst`.
* Build the documentation successfully.

### Scipy/Numpy/Python version information:
```
1.3.0.dev0+c61c989 1.16.0 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
this is a very good idea, thanks @pvanmulbregt.

**Comment by mdhaber** [comment]
Sounds great. I think once #10286 is merged you can put this somewhere in [Editing SciPy](https://13759-1460385-gh.circle-artifacts.com/0/html-scipyorg/dev/contributor/contributor_toc.html#editing-scipy).  

You also mentioned adding something for `scipy.special`. I noticed there are already some notes about that in the [Core Developer Documentation](https://13759-1460385-gh.circle-artifacts.com/0/html-scipyorg/dev/core-dev/index.html#module-specific-instructions). If you write a step-by-step procedure, perhaps try to capture those thoughts in your document so they can be removed from the Core Developer Guide (since they will be explicit enough for new contributors).

As for exactly where in the [Editing SciPy](https://13759-1460385-gh.circle-artifacts.com/0/html-scipyorg/dev/contributor/contributor_toc.html#editing-scipy) section this stuff should go, maybe a single new document for both of these? Perhaps titled "Adding New Methods, Functions, and Classes"? Initially, that could be a single document with sections for `scipy.special` and `scipy.stats`. I know some things about `scipy.optimize` I could add. Eventually, if it gets too long, it can be subdivided into separate documents.

If that sounds good, then perhaps follow as an example the [core-dev](https://github.com/mdhaber/scipy/tree/dev_doc_overhaul/doc/source/dev/core-dev) documentation. All the sections of a single document, `index.rst`, are written as separate `.rst.inc` files, and all of them are in a subfolder `core-dev` of `scipy/doc/source/dev`. I'm not sure if this was necessary for the Core Developer guide, but in your case, this sort of organization would make it really easy to split everything to appear separately (if desired in the future).
