### ISSUE TITLE
Hyperu nan result

### ISSUE THREAD

**Issue by Leimad** [scipy/scipy#10402]
The hyperu function from ```scipy.special``` returns 'nan' in a range where it should actually have a well defined value. One can check for example via the mpmath implementation.

### Reproducing code example:

```
import numpy as np
from scipy.special import hyperu
r = np.linspace(0.1,20,10)
hyperu(2,2,-2*r)
# array([       nan,        nan,        nan,        nan,        nan,
#             nan, 0.00151786, 0.0011037 , 0.00083868, 0.00065886])
```

### Scipy/Numpy/Python version information:

```
1.2.1 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by person142** [comment]
This is a problem with our wrapper. `hyperu` has a branch cut along the negative x-axis (see e.g. https://dlmf.nist.gov/13.2#E6), and the implementation we use is for real values only. So really we should always return `nan` for `x < 0` since that's outside of the real domain of the function. This is supported in the underlying Fortran source, whose documentation says:

```fortran
C       **********************************

        SUBROUTINE CHGU(A,B,X,HU,MD,ISFER)
C
C       =======================================================
C       Purpose: Compute the confluent hypergeometric function
C                U(a,b,x)
C       Input  : a  --- Parameter
C                b  --- Parameter
C                x  --- Argument  ( x > 0 )
C       Output:  HU --- U(a,b,x)
C                MD --- Method code
C                ISFER --- Error flag
C       Routines called:
C            (1) CHGUS for small x ( MD=1 )
C            (2) CHGUL for large x ( MD=2 )
C            (3) CHGUBI for integer b ( MD=3 )
C            (4) CHGUIT for numerical integration ( MD=4 )
C       =======================================================
C
```

**Comment by michaelerule** [comment]
Hi guys, 

The ancestral Fortran may be undefined for negative real x, but it seems like other implementations *do* choose a default branch for this function. 

Wolfram alpha returns the following, for example

    HypergeometricU[-1  ,1/2,-1/2] = -1
    HypergeometricU[-1/2,1/2,-1/2] = 0.7071067811865475j

I ran into this issue while trying to use scipy to numerically check the [citation needed] general expressions for moments and absolute moments of the normal distribution [on Wikipedia](https://en.wikipedia.org/wiki/Normal_distribution#Moments).

So: it seems 
- It is not impossible to choose a meaningful value of `hyperu` for at least *some* inputs outside the domain of the current implementation. 
- Some applications, however rare, could benefit from having the domain of `hyperu` thusly extended.
- Other computational environments (Wolfram language) *do* support a broader domain for `hyperu`

The python package `mpmath` [*does* support](https://mpmath.org/doc/current/functions/bessel.html#mpmath.hyperu) an extended domain for `hyperu`, which means a Python reference implementation is already available. 

At perhaps the expense of code size / dependencies / maintainability, a ham-fisted solution could be to fall back to a variant of the (presumably slower) `mpmath` implementations for inputs where `scipy.special.hyperu` is broken, rather than return NaN?
