### ISSUE TITLE
update macOS wheel naming

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#10485]
see https://github.com/matthew-brett/multibuild/pull/242#issuecomment-512991657

**Comment by rgommers** [comment]
This needs fixing I think, but it can wait till after 1.4.0rc1

**Comment by tylerjereddy** [comment]
I think I need to prioritize this matter soon, especially if it is related to #10917, which is also affecting our `scipy-wheels` repo.

In short, we've been pinning MacOS Python 3.7 SciPy builds to an older commit of the multibuild submodule to prevent a SciPy build failure with output like `ar: build/temp.macosx-10.6-intel-3.7/libsuperlu_src.a: Inappropriate file type or format`.

That pinning is no longer valid in the wheels repo because of the release of pip version 20 and related fixes requiring a bump in multibuild: https://github.com/MacPython/scipy-wheels/pull/65 Well, I suppose I could try to pin to an older pip for a while for that matrix entry, but perhaps the time has come to properly fix this.

**Comment by tylerjereddy** [comment]
With the merging of https://github.com/MacPython/scipy-wheels/pull/66, the MacOS wheels should have the appropriate naming in `1.5.x` series. If we want it for `1.4.2` I'd have to do some careful wheels repo backporting.

**Comment by rgommers** [comment]
We won't backport the fix anymore. Current wheel names are like `scipy-1.6.0-cp37-cp37m-macosx_10_9_x86_64.whl` which is fine. Closing.
