### ISSUE TITLE
ndimage.gaussian_filter provide axis option

### ISSUE THREAD

**Issue by YubinXie** [scipy/scipy#10554]
**Is your feature request related to a problem? Please describe.**
I have a stacked array of 2d images, which is a 3d array. I want to use ndimage.gaussian_filter for each 2d image in the array. However, current method does 3d gaussian, which I did not realize at the beginning. 

**Describe the solution you'd like**
Will the Scipy provides an option for axis and dimension in ndimage.gaussian_filter? It would be much more convenient and faster than doing it a loop. Thanks!

**Comment by tuelwer** [comment]
I had the same problem, but was able to work around it by setting `sigma` to a tuple of standard deviations (instead of a single float) and fixing the standard deviation for the color channel dimension to 0: 
```python3
import numpy as np
import scipy.ndimage

#  create test image with shape (2, 2, 2), first channel is color channel dimension
img = np.stack([np.zeros((2,2)), np.ones((2,2))])

# per default this function applies blur over all axes
print(scipy.ndimage.gaussian_filter(img, sigma=1)) 
# output
#[[[0.35438556 0.35438556]
#  [0.35438556 0.35438556]]
#
# [[0.64561444 0.64561444]
#  [0.64561444 0.64561444]]]

# only apply filter to the second and third axis
print(scipy.ndimage.gaussian_filter(img, sigma=(0,1,1))) 
# output:
#[[[0. 0.]
#  [0. 0.]]
#
# [[1. 1.]
#  [1. 1.]]]
```
However, I agree that an argument to specify the axis would be useful. The default behavior of this function is surprising and quite unintuitive.

**Comment by grlee77** [comment]
This would be a fairly straightforward feature to add at the Python level without needing to modify the underlying ndimage C code. It would basically be updating `sigma` for the users to insert 0 for any axes not to be filtered. 

I would mainly be in favor if we could provide the same API across most (all?) filtering/morphology functions. e.g. similar logic can be used in many of the other functions (e.g. expand a kernel to size 1 on any unfiltered indices for convolution functions).

**Comment by grlee77** [comment]
Here is a related previous discussion: https://github.com/scipy/scipy/issues/12997#issuecomment-811268933

**Comment by mdhaber** [comment]
There was also a request in https://github.com/scipy/scipy/issues/16191#issuecomment-1144781807. i'd be happy to review. If the signatures are consistent enough, would you consider using a decorator to do the work?

**Comment by grlee77** [comment]
> If the signatures are consistent enough, would you consider using a decorator to do the work (iterating over slices of the ndarray and calling the function on each slice) or would the approach you suggested be much more efficient?

For a common case such as an RGB or RGBA image with a small channel axis, the iteration based approach would be fine, but I think In the general case it will likely be more efficient to do things in a single call rather than iterating over any non-filtered axes so any loops get applied at the C level. I haven't thought too much yet about whether some common utility function(s) or a decorator based approach might be preferable, but I would think either is possible.

**Comment by grlee77** [comment]
Let me try and put something together today and then I will link here for discussion.

**Comment by mdhaber** [comment]
OK. It's probably worth trying both because then the one you don't choose could be used for writing unit tests.
