### ISSUE TITLE
Rename `sum` ndimage function

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#10593]
[The `scipy.ndimage` function `sum`]( https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.sum.html#scipy.ndimage.sum ) overlaps with [the Python builtin `sum`]( https://docs.python.org/3/library/functions.html#sum ). This can cause issues both within code trying to implement this `scipy.ndimage` function (like if it needs the builtin `sum`) and can cause issues in downstream user code should they import `sum` (like `from scipy.ndimage import sum`). It would preferable to rename this function to something that does not overlap with the Python builtin (like `summation`, `sum_by_labels`, ...?).

cc @jni @GenevieveBuckley

**Comment by larsoner** [comment]
Agreed this is problematic.

Rather than rename I'd prefer an alias:
```
def sum_by_label(...):
    ...

sum = sum_by_labels
```
And we update the docs to refer to the new name. It's backward compatible with old code that way.

**Comment by jakirkham** [comment]
Yeah that seems like a reasonable path forward.

Would we want to start warning with the old function name?

**Comment by larsoner** [comment]
It's probably not worth it because there is little cost to keeping the old name around.

**Comment by WarrenWeckesser** [comment]
Wouldn't the point of creating a new name be to deprecate the old one?  If not, why not just live with the old one?

**Comment by larsoner** [comment]
> Wouldn't the point of creating a new name be to deprecate the old one?

The main point in my mind is to make it so that people can do:
```
from scipy.ndimage import sum_labels
```
instead of what we have now:
```
# bad for overwriting builtin
from scipy.ndimage import sum
# bad for scientific Python ecosystem consistency
from scipy.ndimage import sum as sum_labels
```
Fixing this would be my priority.

Leaving `sum` in the namespace comes at little cost (mostly just the `sum = sum_labels` line). Removing `sum` from the namespace, on the other hand, has costs in terms of users who have old code. This does not seem worth it to me.

Leaving `sum` in also is not great for consistency, but 1) having `sum` and `sum_labels` is still better than everyone having their own `from scipy.ndimage import sum as ...` line with different names, and 2) we can just let `sum` die off on its own.

That being said, if people really like the idea of deprecation I can live with it.

**Comment by rgommers** [comment]
+1 for adding an alias. This is one of the more often used builtins, and adding an alias has few costs. Nice reasoning @larsoner

**Comment by rgommers** [comment]
none of these "uses a builtin name" are defects by the way, removed the label

**Comment by larsoner** [comment]
> none of these "uses a builtin name" are defects by the way, removed the label

I'll have to create a "pet peeve" label and add it then :)

**Comment by rgommers** [comment]
no objections and a couple of +1's, let's call this decided. @jakirkham can we tempt you to open a PR?
