### ISSUE TITLE
DOC/WEB: special: Strange indentation for some functions.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#10642]
In the online documentation, the list of "Faster versions of common Bessel Functions" is indented 16 or so characters, unlike the rest of the functions.  Take a look at https://docs.scipy.org/doc/scipy/reference/special.html#bessel-functions

That web page is generated by Sphinx from the module docstring in https://github.com/scipy/scipy/blob/master/scipy/special/__init__.py.  I don't see anything obviously different in the section on the faster Bessel functions.

**Comment by ilayn** [comment]
They look suspiciously tabbed though.

**Comment by larsoner** [comment]
The cause is the table not being big enough to fill the space and sphinx using `align-center` by default, see:

https://github.com/sphinx-doc/sphinx/pull/6341
https://github.com/sphinx-doc/sphinx/issues/4550

The solution is probably to build with Sphinx 2.1+ and add some CSS to fix it. I'll see if it's easy enough.

**Comment by larsoner** [comment]
PR to `scipy/scipy` forthcoming to actually fix this :)
