### ISSUE TITLE
create a <scipy.stats._continuous_distns.truncbeta_gen> i.e. truncated beta distribution

### ISSUE THREAD

**Issue by kadereub** [scipy/scipy#10651]
The inclusion of a *truncated beta distribution* would make random variable generation a lot simpler when attempting to restrict the variable over an interval [a, b]. As well as provide comfort around the results.

> The beta distribution has been applied to model the behavior of random variables limited to intervals of finite length in a wide variety of disciplines.

I thought of replicating the current [truncnorm](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.truncnorm.html)  object, in terms of structure. 
I think it is well laid out and will make the integration with the overall `scipy` package simple.

However, the various methods would need to be setup differently to match that of the beta distribution. 
As an example the `ppf ` would not need to consider cases where a < 0, i.e. could 

```python

def _ppf(self, q, a, b):
    ans = self._get_betas(a, b)
    _na, _nb = ans[:2]
    ppf =  _beta_ppf(q*_nb + _na*(1.0-q)))
    return ppf

```

![truncated_beta_ppf](https://user-images.githubusercontent.com/31546506/62925985-6864bb00-bdab-11e9-9078-5761aadce7c7.PNG)

It's not overly complicated to create this functionality oneself. I could not find any existing `python` packages with this functionality included. However if this were to be a part of the `scipy` package it would avoid having to code up the `pdf, cdf, pdf` and `moments` calculations and provide some comfort that the results have *had a second eye check.*

**Comment by ev-br** [comment]
PR welcome, I'd say.

**Comment by kadereub** [comment]
Cool! Will get going on that PR.

**Comment by kadereub** [comment]
Was hoping to get in on *Hacktoberfest* , but I think this feature is redundant considering the `loc` and `scale` functionality of the current `beta` function. After doing some further work a simple use of these parameters allows you to achieve the same results:

Say for an Interval [a,b] where a = 0.2 and b = 0.9 and and alpha=0.7, beta=0.9.

We find for a `scale` = (b-a) = 0.7, and loc = a = 0.2, the distribution is suitably truncated:

```
import numpy as np
from scipy import stats
x = np.linspace(0.01, 0.99, 1000) 
tst = stats.beta(0.7, 0.9, 0.2, (0.9 - 0.2)).ppf(x) 
plt.plot(x, tst) 
plt.show()
```
![beta_trunc_example](https://user-images.githubusercontent.com/31546506/66702065-5ba50a80-ecfb-11e9-98fe-40419aacad69.png)

There is a [good paper](https://arxiv.org/pdf/1303.5597.pdf) which uses this truncated standard beta distribution. In equation 28 we can find the mean for this truncated distribution as: 

`mu = (alpha*b + beta*a) / (alpha + beta) = 0.50625`

This is the same result as the below which further confirms the above usage.

```
In [50]: stats.beta(alpha, beta, 0.2, (0.9 - 0.2)).stats("m")                                                                     
Out[50]: array(0.50625)
```

**Is it not worth adding an example in the [docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.beta.html) highlighting this functionality ?** If so could rename the issue...

**Comment by sethtroisi** [comment]
@ev-br Do you think it's worth mentioning in the documentation? If so are there other examples of use-a-dist-to-simulate-b-dist I can copy the style of?

**Comment by ev-br** [comment]
I think so. IIRC `rice` has some discussion of this sort.

**Comment by mdhaber** [comment]
There are some distributions, like `rice`, that include additional documentation about parameterization of the distribution.
<img width="434" alt="image" src="https://user-images.githubusercontent.com/6570539/166447579-9818393b-5f94-4275-a8b7-69bd9427abe4.png">

But the suggestion above is not distribution-specific: any `scipy` distribution with finite support (e.g. `powerlaw`) can change the support using `loc` and `scale` in the way described. Aside from `uniform`, this is not the same as "truncating" the distribution. By contrast, a truncated distribution has the same PDF of the parent distribution over the truncated support aside from a normalizing constant.

Since the author was satisfied with shifting/scaling the support and did not need a true truncated beta distribution, I think it would be reasonable to just close this issue. Two other thoughts:
- create a new issue for a general truncated distribution feature. I'd be happy to open a PR in the main repo that would resolve this issue (mdhaber/scipy#75) if there is someone interested in reviewing it.
- Mention in the [after_notes](https://github.com/scipy/scipy/blob/2204e3a39c0d6c2d5292eaeae1a752e5565d9eb9/scipy/stats/_distn_infrastructure.py#L207-L215) of distributions with finite support how the support can be scaled and shifted with `loc` and `scale`. (Personally, I'm -0.5 on this.)

@ev-br @sethtroisi With that in mind, any updates in opinion here?

**Comment by ev-br** [comment]
My only comment would be that in some cases we might mention e.g. 
https://github.com/phobson/paramnormal for reparametrizations of distributions. But this is distriburion-specific anyway, so need to be addressed on a case-by-case basis. And this has nothing to do with the issue at hand, so I'll stop :-)

**Comment by mdhaber** [comment]
Ok. I'll go ahead and close this then. Please reopen if I misunderstood.
