### ISSUE TITLE
BUG: Travis 3.5 build is broken

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#10676]
All PRs are failing with a segfault:

https://travis-ci.org/scipy/scipy/jobs/572579066
https://travis-ci.org/scipy/scipy/jobs/572698988

Not sure what the problem is, but this gives us something to tag until we fix it.

**Comment by pv** [comment]
https://github.com/scipy/scipy/pull/10644 seems to have been the first commit to fail.

**Comment by larsoner** [comment]
Indeed, I already tried reverting it in #10677 and the same failure occurred, so I think it's just coincidence

**Comment by tylerjereddy** [comment]
A new pytest release was propagated through the channels just a few hours ago--I bet it is that. Things that were changed to deprecation warnings in 4.x have now been hard removed, and there are a bunch of such hard removals, so that strikes me as a strong candidate for investigation -- let me open a PR to pin for the time being maybe.
