### ISSUE TITLE
Add Brownian/Distance Correlation to scipy.stats

### ISSUE THREAD

**Issue by CompRhys** [scipy/scipy#10680]
Hello I would like to request that the [distance correlation](https://en.wikipedia.org/wiki/Distance_correlation) be added alongside other correation metrics such as pearson's correlation. I believe this would be useful for other users as the distance correlation was designed to address some of the deficiencies of the Pearson correlation, namely that it can easily be zero for dependent variables.

The library [dcor](https://github.com/vnmabus/dcor) implements the distance correlation but does not return p-vaues as is standard within the pearsonr, spearmanr and kendalltau implementations in scipy.stats meaning that it cannot be directly substituted into scipy based workflows

**Comment by rgommers** [comment]
Distance correlation would be a good addition to `scipy.stats` I believe. That said, `dcor` seems fairly complete and well-maintained, so that's already a good option. Perhaps making `dcor` return things in the same format as `stats.pearsonr` et al. is an option?

@vnmabus as the `dcor` author, what's your opinion on this request?

**Comment by rgommers** [comment]
Thanks @vnmabus. 

> The easier solution would be to add a new function to the dcor package with the same interface as the others.

I agree.

We indeed don't want to depend on `dcor` (even not optionally). 

I'll let others weigh in on whether copying an implementation from `dcor` is desirable; my vote would be -0.5
