### ISSUE TITLE
MAINT: Simplify CircleCI doc build viewing

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#10706]
I got a bit annoyed at how long it took to look at CircleCI artifcats (click Details, maybe login, click Artifacts, wait for it to populate, find `index.html` and click) so I wrote a little [GitHub app](https://github.com/apps/circleci-artifacts-redirector/) that monitors the CircleCI status updates, and once the `build_docs` run completes gives a direct link to the root HTML doc. See for example the CircleCI statuses here:

https://github.com/mne-tools/mne-python/pull/6690

If this seems like something useful for SciPy, @pv if you can install the app for the SciPy repo (just permissions for `scipy/scipy` if you want) then I can make a quick PR to enable it. I don't have org-level permissions so I can't enable the app on my own.

**Comment by larsoner** [comment]
cc @WarrenWeckesser this will also prevent you from needing to give CircleCI all your info :)

**Comment by rgommers** [comment]
Ooh nice, without the app commenting, just in the CI integrations dropdown, I like it.

Cc @Shekharrajak - this is similar to the Surge deployment for built docs that you were going to work on. Perhaps that's even nicer, because it will have better URLs, but I'd be perfectly happy with this as well. Perhaps you can have a look at this, and push forward whichever approach you prefer for the `numpy.org` repo?

**Comment by larsoner** [comment]
@rgommers if you can install the app I can open a PR to demonstrate, we can always remove it if people don't like it

**Comment by rgommers** [comment]
Installed, with access to `scipy`, `scipy.org` and `scipy-articles` repos.

**Comment by mdhaber** [comment]
This is great! I'll update Rendering Documentation documentation accordingly in gh-10687.
