### ISSUE TITLE
Building scipy with MKL/VisualC++/GFortran

### ISSUE THREAD

**Issue by bartoli** [scipy/scipy#10736]
Here is a report of the issues i encountered, when building scipy. Hopefully scripts can be adjusted to work around them?

Scipy version was 1.3.x
MKL version was 2019.x
C Compiler was Visual studio 2015
Fortran compiler was MingW GFortran 
Numpy was 1.16.x

The first issue was for the quadpack extension. when building the dll from the fortran files in integrate/quadpack/*.f, there was un unresolved error to dgtsv_, which is a lapack symbol, in dqc25f.f.
That dll is configured by Configuration.add_library(), so lapack options are not passed to it at all. So I am not sure how your build scripts manage to find that symbol from openblas or an other library in your build procedure.
In my case, i had to modify distutils to add a way to pass arguments to the final gfortran linking command, to be able to add the mkl library to the command line after the list of object files.
A cleaner workaround would be to be able to pass extra optional info to add_library(), to add librares and library dirs, and integrate/setup.py could add lapack info into those aruments?

Second issue was that because of that link (to mkl_rt.lib), the .def file generated by fortran for the dll contained the symbols
__IMPORT_DESCRIPTOR_mkl_rt @19 DATA
__NULL_IMPORT_DESCRIPTOR @20 DATA
Which caused LNK1127 when linking the pyd with the lib file that had been generated from the .def
To workaround this, i had to modify gnu.py in _link_wrapper_lib(), so before the generation of the .lib from the .def, such lines are filtered out. Since the method is suppoed to return a MSVC-compatible lib, i think this could be integrated

Last issue is for the g77 abi wrapper dll, which is built instead of a dummy one, if mkl is in the libraries.
With that combination of gfortran/MSVC, fortran and C objects can't be linked in the same library. Distutils tried to build a library with only the fortran sources for the _fblas extension, and obviously failed with unresolved symbols to the C sources.
For now, to workaround this, i modified needs_g77_abi_wrapper() to always return false..
For a cleaner one, i guess fortran and C would have to be split in two dlls instead of one for all extensions that need that wrapper.

I have an additional issue when i try to build a 32-bit version of the extension. For some reason, the 32-bit build adds  gfortran.lib gcc.lib mingw32.lib mingwex.lib to some link commands that the 64-bit build does not. I can see at the start of the build, the copies of libgfortran.a and libgcc.a in gfortran.linb and gcc.lib, but this is not done for mingw32.lib and mingwex.lib. Manually copying those two others, i still get an unresolved error to _fprintf. Not sure if i will insist on building on that platform.

**Comment by ilayn** [comment]
Is there any particular reason why you don't use vc 2019? Community edition is sufficient.

**Comment by bartoli** [comment]
For consistency between all the libraries used by a project, so we know exactly what are their dependencies. Everything is custom built with the same compiler and runtime library (python, numpy, scipy, other native libraries python depends on,..).

**Comment by pv** [comment]
MSVC+gfortran with MKL on Windows has not been tested, and it's a wonder it works at all. The issues you are facing should be addressed in `numpy.distutils` --- Scipy itself doesn't do much build customization vs. this compiler combination.

Configuration.add_library does not build a dll, just either a static library or a loose collection of object files. The dlls are built just before linking the pyd extension, so the information about lapack is known at that time.

**Comment by pv** [comment]
For `needs_g77_abi_wrapper` --- if the MKL in question doesn't need the wrappers, then that's fine and perhaps the check could be made smarter --- but if it does you'll likely see incorrect results or crashes.

The C/Fortran linking issue for the wrappers in this compiler combination is problematic, because distutils is a bit problematic here --- you'd need two C compilers in the same project and a way to indicate which compiler to use for which files, and I'm not immediately sure how it copes with that. The wrappers might also be rewritten with F2003 iso-c bindings.

The support for MSVC+gfortran in numpy.distutils is unfortunately currently a nasty hack with several limitations. I imagine well-tested patches to numpy.distutils (or scipy, for the applicable parts) cleaning up the situation would be welcome.

**Comment by rgommers** [comment]
It seems like there's nothing to do here. Conda-forge took over the Gfortran + MSVC hack, and in practice it works. I think we'll be living with it for a long time. 

For MKL I'd say: you simply must use the Intel Fortran compiler on Windows if you use MKL.

Let's close this, because there's nothing to change in SciPy.
