### ISSUE TITLE
sparse matrix definition

### ISSUE THREAD

**Issue by asetGem** [scipy/scipy#10760]
I do not know how scipy.sparse is implemented, and I have a practical question.

**Context :**
I have a lower triangular matrix, with potentially some '0' in the lower triangle.
I am currently considering it as a sparse matrix, and create it with `mat = dok_matrix((line, col), dbtype=float)`, and then filling with `mat[i,j]=n`
Then, I save it using `scipy.sparse.save_npz(file, dok_matrix.tocoo())`, because save_npz does not accept dok format.
When I want to load this matrix, I use `mat = scipy.sparse.load_npz(file).todok()`, in order to get back my matrix in dok format.

**Question:**
So, my question is from which matrix sparsity is it relevant to use the scipy.sparse module?
Do you think this is the most efficient way to do with this matrix type? Is there a more efficient way to deal with such a matrix?

Thanks!

**Comment by perimosocordiae** [comment]
The approach you described will certainly work fine. It's hard to say how to make things more efficient without knowing how you'll be using this matrix, but I have a few generic points:

 * Assembling the matrix one element at a time is convenient but slow. If this is a bottleneck for you, consider keeping track of `i`, `j`, and `n` in separate arrays during construction and then creating the sparse matrix in one shot in COO/CSR/CSC format via their constructors.
 * There's no format specifically for triangular matrices, probably because a sparsity factor of 0.5 isn't that impactful. Depending on your use-case, a regular numpy array may be faster and use less RAM.
 * DOK format is nice for adding/deleting entries, but slow for most everything else.

Finally, a meta-comment: questions like these may get more attention if you ask them on StackOverflow or the mailing list. Github issues are mostly used for bug reports and feature requests.
