### ISSUE TITLE
Weird sample variance when creating a lognromal sample with pre-defined mean and variance

### ISSUE THREAD

**Issue by gustavoem** [scipy/scipy#10801]
I have been working with lognormal distributions as a proposal distribution for some MCMC routines which require the proposal distribution to have some **pre-defined sample mean and variance**, `m` and `v`, respectively. Considering that I'm using ```scipy.stat.lognorm``` to generate a sample from the proposal distribution, I have to define `mu` and `sigma^2`, parameters of the underlying normal distribution. 

I've determined `mu` and `sigma^2` using the relations: `mu=ln(m / sqrt(1 + v / m^2))` and `sigma^2 = ln(1 + v / m^2)`. This relation is easy to derive and its also on the Wikipedia article about the [Lognormal distribution](https://en.wikipedia.org/wiki/Log-normal_distribution#Notation).

This has worked when `m >= 1`, however when `m < 1` the variance of the generated sample becomes smaller than it was supposed to be (`v`) and I am not sure why.

**To reproduce this behaviour**, I ran the code
```python
def get_underlying_normal_params(m, v):
    m2 = m * m
    nrm_mean = np.log(m2 / np.sqrt(v + m2))
    nrm_var = np.log((v + m2) / m2)
    return nrm_mean, nrm_var


lognrm_mean = 1e-5
lognrm_var = 10
norm_mean, norm_var = get_underlying_normal_params(lognrm_mean, \
        lognrm_var)
sample = [lognorm.rvs(scale=np.exp(norm_mean), s=np.sqrt(norm_var)) \
        for _ in range(50000)]
print("Sample mean: ", statistics.mean(sample))
print("Sample variance: ", statistics.variance(sample))
```

the produced output is:
```
Sample mean:  1.3404377964314877e-06
Sample variance:  5.009857166696648e-09
```
We can see then, that the created sample has variance ~5e-9, far from the desired variance, 10.

If however, I run the same code setting ```lognrm_mean = 1```, the output is:

```
Sample mean:  1.0077730236251317
Sample variance:  9.250922743416222
```
And now the sample variance is actually close to the desired variance.

**Why was I able to pre-determine the variance of the sample on the second case but not on the first case?**

I am not sure that what I did is conceptually correct, but I suspect that this could have been caused by floating point errors; if that was the case, does anyone have an idea of how to investigate further?

**Comment by chrisb83** [comment]
Hi,

I did not check your description in detail but maybe the following hint in the documentation helps:

> A common parametrization for a lognormal random variable Y is in terms of the mean, mu, and standard deviation, sigma, of the unique normally distributed random variable X such that exp(X) = Y. This parametrization corresponds to setting s = sigma and scale = exp(mu).

**Comment by gustavoem** [comment]
Hi!

Thanks for the reply! I was aware of this detail, so I think that is not the issue. You can see that I have addressed this possible issue in the line:
```python
sample = [lognorm.rvs(scale=np.exp(norm_mean), s=np.sqrt(norm_var)) \
        for _ in range(50000)]
```

**Comment by chrisb83** [comment]
The SciPy lognorm variable X(s) corresponds to the one on Wikipedia with s=Sigma and mu=0.
You can adjust s to match your desired variance of 10 solving the formula of the variance given on Wikipedia for sigma. it should give you a value of ~1.144

`lognorm(1.144).var() # 9.99955146185357`

Now you can use `loc` to shift X(s) to get the desired mean by considering loc + X(s). Note that shifting does not affect the variance. The mean of `X(1.144)` is:

`lognorm(1.144).mean() #1.9239262116984597`

So take `loc = 1e-5 - 1.9239262116984597`.
```
x = lognorm.rvs(s=1.144, loc=loc, random_state=1234, size=int(1e6))
x.mean() # 0.0009755198570579801
x.var() # 9.943471830901856
```

I hope that helps. Closing as there seems to be no issue.

**Comment by gustavoem** [comment]
Thank you, but I needed to generate positive numbers, and the loc parameter allows the distribution to have negative numbers with non-zero pdf. 

I guess this could work if I change my application to allow negative numbers with small probability.

**Comment by chrisb83** [comment]
You are right, the above approach gives you a shifted lognormal distribution but you are looking for a random variable that can be written as `exp(sigma*N + mu)` where N is standard normal.

If you use the scale parameter, you get the following random variable in SciPy:

`scale * exp(s*N) = exp(log(scale) + s*N)`, i.e. mu = log(scale) and s = sigma as stated in the documentation.

```
m = 1e-5
v = 10

mu = np.log(m/np.sqrt(1+v/m**2)) # -24.2
sigma = np.sqrt(np.log(1+v/m**2)) # 5.0

scale = np.exp(mu)
s = sigma

# mean and var are as expected
lognorm(s=s, scale=scale).mean() # 9.99999999999998e-06
lognorm(s=s, scale=scale).var() # 9.999999999999947
```

Note that these are quite extreme parameters for mu and sigma. If you sample from them, the empirical var is indeed not close to 10. (as you observed before)

```
x = lognorm.rvs(s=s, scale=scale, random_state=1234, size=int(1e7))
x.var() # 0.000248654531158192
```

I don't know if this is due to numerical issues or if you need more samples for such parameters.

So let me reopen the issue… I don't have time to investigate it at the moment

**Comment by mdhaber** [comment]
I've traced the numbers through the random variate generation and I'm not seeing evidence of a loss of precision or other numerical issue. 

We get the same sort of thing with `np.random`:
```python3
rng = np.random.default_rng(8932598345)
x = rng.lognormal(mu, sigma, size=int(1e7))
x.var()  # 0.00024264448171329683 != 10
```

Most convincing to me that this is not due to a bug in SciPy/NumPy is that the mean and standard deviation of the log of the random variates are as expected.
```
y = np.log(x)
y.mean()  # -24.177120820652654 ~ -24.2
y.std()  # 5.032397460979327 ~ 5
```

So if the formulas for the required normal mean and variance are correct, it seems that the "problem" is inherent; that is, the distribution of the sample variance is unfavorable, and as @chrisb83 suggested, we've need (lots) more samples to observe sample variance closer to the population variance.

Come to think of it, we have observed a related issue before in gh-15723, in which `lognorm` and `gibrat` (special case of `lognorm` with `s=1`) were two distributions that failed the sample variance test.

Perhaps @rkern, @josef-pkt, or @steppi have deeper thoughts here?

Either way, I think this can be closed. Please feel free to reopen if I've missed something.
