### ISSUE TITLE
Extend Anderson Darling to cover Weibull distribution

### ISSUE THREAD

**Issue by lesshaste** [scipy/scipy#10829]
**Is your feature request related to a problem? Please describe.**

The current scipy.stats implementation of Anderson Darling only covers {‘norm’,’expon’,’logistic’,’gumbel’,’gumbel_l’, gumbel_r’, ‘extreme1’}.  However according to https://www.itl.nist.gov/div898/handbook/eda/section3/eda35e.htm tables of critical values are also available for the Weibull distribution.  In R , gofstat implements these tests https://www.rdocumentation.org/packages/fitdistrplus/versions/1.0-14/topics/gofstat

**Describe the solution you'd like**

Extend Anderson Darling to cover the Weibull distribution

**Describe alternatives you've considered**

**Additional context (e.g. screenshots)**

**Comment by josef-pkt** [comment]
I found https://www.fpl.fs.fed.us/documnts/fplrp/fplrp493.pdf
an older 1989 working paper with 2 parameter and 3 parameter Weibull distribution

has also an approximation formula for the 3 parameter Weibull that depends on the shape parameter

cross-ref to statsmodels question https://github.com/statsmodels/statsmodels/issues/6135

**Comment by lesshaste** [comment]
Just a note to clarify that the scipy and statsmodels question are not the same.  The statsmodels question is for when the parameters are unknown.  Statsmodels already handles this case for expon and norm unlike scipy.

**Comment by josef-pkt** [comment]
`scipy.stats.anderson` also estimates the parameters, loc and scale, 
The only difference is that statsmodels has better approximation for the distribution of the test statistic for expon and norm and computes also p-values.

Right now I don't remember what there is for AD with known parameters, it has the same critical values for all Null distributions, AFAIR.
Does scipy have the ks_test analogue for AD with known parameters?

**Comment by mdhaber** [comment]
> Just a note to clarify that the scipy and statsmodels question are not the same. The statsmodels question is for when the parameters are unknown.

@josef-pkt answered:
> scipy.stats.anderson also estimates the parameters, loc and scale,

which is accurate, but I thought I'd add that SciPy's [documentation for `anderson`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.anderson.html) states:
> Anderson-Darling test for data coming from a _particular_ distribution.

If "particular" means a distribution with known parameters rather than a family of distributions, this is not strictly accurate, and I think it's the source of some confusion. At least for normality tests, [SciPy's critical values](https://github.com/scipy/scipy/blob/4cf21e753cf937d1c6c2d2a0e372fbc1dbbeea81/scipy/stats/_morestats.py#L1769) are those from [Stephens 1974](https://www.jstor.org/stable/pdf/2286009.pdf?casa_token=xDJeBEdg68wAAAAA:gpph9nAJqlneUV3iFdL8GWJ7YW_qj3UHMcsWlkXl-3P9fhHdQvVkYtFJv77BupdtMVnjDlQudmO1DRVDMFTqUahrhUIlElWUqb_wDBNa_-IUMKMebg) for when the parameters of the distribution are *unknown* (Table 1.3).

> The only difference is that statsmodels has better approximation for the distribution of the test statistic for expon and norm and computes also p-values.

I would agree that SciPy's critical values are not very accurate. For example, other papers have reported different critical values and interpolation methods that agree better with Monte Carlo simulation.

> Right now I don't remember what there is for AD with known parameters, it has the same critical values for all Null distributions, AFAIR.

The k-sample extension of the test doesn't depend on the distribution being tested, but I think it matters for the one-sample test.

> Does scipy have the ks_test analogue for AD with known parameters?

I'm not sure I understand the question, but here is a comparison of the two tests:

1. `ks_1samp` assumes the distribution is known exactly (all parameters are known), `anderson` (as implemented) assumes that all are unknown.
2. Both use statistics that compare the empirical CDF, but `anderson`'s statistic looks sensitive to all sorts of differences, whereas the KS statistic is simple, probably so that the null distribution of the statistic is easy to calculate.

---

There are a lot of ideas that come out of a study of this issue. Here are my thoughts for a plan forward.

1. SciPy's Weibull distributions should override the `fit` method. That's tracked in gh-11782. Until that's done, I don't think it makes sense to extend `anderson` for Weibull in particular, because it seems unnecessary to maintain custom code in `anderson` to do fitting. (That said, I'm open to extending `anderson` to work with _any_ distribution; see #3/4 below.)
2. `norm.fit` uses the MLE for `scale`: `scale = np.sqrt(((data - loc)**2).mean())`. `anderson` currently fits using the less biased `s = np.std(x, ddof=1, axis=0)`. I think `fit` is OK because it's supposed to be MLE, but I think we should add a note to `anderson` that it fits the normal distribution using the corrected sample standard deviation rather than MLE.
3. Both `ks_1samp` and `anderson` would benefit from a parameter that allows the user to specify whether the distribution is known exactly or whether the parameters are estimated - or better, the user could separately specify the distribution family (e.g. `stats.norm`) and which parameters are known (e.g. `known_params = {'loc': 0}`).
  a. The default for `ks_1samp` is that the parameters are exactly known, but if the parameters are unknown, it becomes Lilliefor's test if the distribution is normal, and the same idea can be extended to other distributions.
  b. The defaults of `anderson` is that the parameters are estimated, but we should also be able to do the version of the test in which parameters are known.
4. We can keep the existing behavior where desired, but a lot of new functionality can be added quite easily with general code using `monte_carlo_test`. 
  a. When the distribution is known exactly, it would be very fast to approximate `anderson` *p*-values on the fly using `monte_carlo_test` for any distribution with a fast `cdf`. These test can still be used when the parameters are unknown, in my opinion, but it will have low power.
  b. When the distribution is not known exactly, we can still calculate *p*-values on the fly using `monte_carlo_test`, but it requires fitting the distribution to each Monte Carlo sample. This can be reasonably fast for most distributions with an overridden `fit` method, and almost as fast as the case when the distribution is known exactly if we can vectorize the `fit` calculations. It could still be useful (when there is no alternative), albeit slow, even when we need to rely on numerical optimization for fitting.

Here's a rough example of what I have in mind, although it would need to be worked into the existing interface.

<details>

```python3
import numpy as np

from scipy import stats

def anderson(x, family, known_params={}):

    known_fit_params = {'f' + param: val for param, val in known_params.items()}

    dist = None
    try:
        fit_params = family.fit(x, **known_fit_params)
        dist = family(*fit_params)
        statistic_dist = None
    except (ValueError, RuntimeError):  # "All parameters fixed. There is nothing to optimize."
        dist = family(**known_params)
        statistic_dist = dist

    def statistic(x, dist=statistic_dist):
        """Compute the Anderson-Darling statistic A^2"""

        # If any parameters are unknown, fit a distribution to the data
        if dist is None:  # otherwise dist from above is used
            params = family.fit(x, **known_fit_params)
            dist = family(*params)

        # compute A^2
        x = np.sort(x)
        n = len(x)
        i = np.arange(1, n+1)
        Si = (2*i - 1)/n * (dist.logcdf(x) + dist.logsf(x[::-1]))
        S = np.sum(Si)
        return -n - S

    res = stats.monte_carlo_test(sample=x, rvs=dist.rvs, statistic=statistic,
                                 alternative='greater')
    return res.statistic, res.pvalue

x = np.array([148, 154, 158, 160, 161, 162, 166, 170, 182, 195, 236])

res = anderson(x, stats.rayleigh)
print(res)
```

Ideas for improvement:
* `statistic` can be vectorized when all parameters are known
* guesses can be provided (possibly from the original fit) to speed up optimization when `fit` isn't overridden
* 
</details>

**Comment by mdhaber** [comment]
@lesshaste @Phillip-M-Feldman @nayefahmad I'm mentioning you because you seem to have some experience with the Weibull distribution. 

How often do you use the Weibull distribution for shape parameter < 1 (i.e. when the PDF looks like a decaying exponential)? 

I think https://github.com/scipy/scipy/pull/12787 would close this issue for shape parameter > 1, but there are difficulties when the data lead to small values of the shape parameter (or the data is generated from Weibull with a small underlying value of the shape parameter).
