### ISSUE TITLE
accuracy of computation

### ISSUE THREAD

**Issue by sheerluck** [scipy/scipy#10890]
My issue is about https://docs.scipy.org/doc/scipy/reference/tutorial/integrate.html

#### Reproducing code example:

```
import scipy.integrate as integrate
import scipy.special as special
integrate.quad(lambda x: special.jv(2.5,x), 0, 4.5)
```

#### Result in tutorial:

```
(1.1178179380783249, 7.8663172481899801e-09)
```
#### Actual result:

```
(1.1178179380783246, 7.866317250224184e-09)
```

#### Scipy/Numpy/Python version information:
```
scipy.__version__  1.4.0.dev0+Unknown
numpy.__version__ 1.16.5
sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by tylerjereddy** [comment]
What's the issue here? The numbers look very close--are you saying that when you run the code in the docstring & outside of the docstring **on the same machine** you get different answers with each?

Is it documented somewhere that the results of these calculations should not differ by those amounts when executed in different environments or on different machines?

**Comment by ev-br** [comment]
The difference is smaller than the reported error (that's the second value of the result). And the difference is of the order of the machine epsilon, so it's really the same number.
