### ISSUE TITLE
Nakagami fitting doesn't converge  (scipy.stats)

### ISSUE THREAD

**Issue by lucasschlichting** [scipy/scipy#10908]
Hi guys, 

I'm trying use scipy.stats to analyses communication channels, basically I'm calculating "rayleigh" and "nakagami" distributions to some RSSI measurements.
The most cases both distribution fit converge, but some times an issue is occurring to distribution fit for nakagami, the shape (or "mu") return a strange value.

The example below I have 5000  samples and the nakagami distribution return mu=17.63, I set this same data in matlab and return mu=4.
Measurements
https://imgur.com/l1eYgsP

nakagami pdf
https://imgur.com/RZJIweT

Anyone have an ideia about what happen?

thanks

**Comment by tylerjereddy** [comment]
You may have better luck with usage questions on i.e., StackOverflow, along with a minimum working example.

**Comment by jjerphan** [comment]
@lucasschlichting: is your problem still present?

**Comment by lucasschlichting** [comment]
Hi @jjerphan, yes

**Comment by lucasschlichting** [comment]
Hi @jjerphan, yes it does.

I created a [repository](https://github.com/lucasschlichting/scripts-pathloss-fading) that contains two scripts, the named [ExperimentoFading](https://github.com/lucasschlichting/scripts-pathloss-fading/blob/master/ExperimentoFading.ipynb) is the one I had issue. If you wanna try reproduce, the folder called "data" have three samples caught up from a real experiment about communication fading. the first one converges, the second one doesn't. I've created a fit based on this [report](https://ieeexplore.ieee.org/document/996038) to check the values, so either values calculated by scipy nakagami lib mine moments function should be close, but for example in [sample2](https://github.com/lucasschlichting/scripts-pathloss-fading/blob/master/data/sample2.txt) we get a big different.

Thanks.

**Comment by jjerphan** [comment]
Hi @lucasschlichting,

Thank you for your answer.
Can you come up with a minimal working example?

Thank you.

**Comment by lucasschlichting** [comment]
Hi @jjerphan, sorry to be so long to answer.

The aim of this script is to estimate the fading(Strength power variation in wireless communication systems) distribution of a communication channel. So we capture the [RSSI](https://en.wikipedia.org/wiki/Received_signal_strength_indication) with an embedded instrument, the payload is exact the samples. then basically I'm using pandas to filter the last column that is RSSI.
After filter we calculate the fading, we use Rayleigh and Nakagami distributions, to see the variation behavior of that channel and "m" of Nakagmi tells us how good is the channel.

1.  We input the data: https://imgur.com/PSCzhdN

2.  Filter the last column: https://imgur.com/em8Utj4

3. Plot the variations(blue) between the average(red): https://imgur.com/0ILEGRy

4. we calculate the fading(variation of average power): https://imgur.com/mpUmcqF

5. Fit and plot Rayleigh distribution: https://imgur.com/OrvrmRO

6. Fit Nakagami (here I implemented the fit from that [report](https://ieeexplore.ieee.org/document/996038) to compare the fit from Scipy Nakagami lib): https://imgur.com/6lN6vcm

7. finally plot Nakagami choosing one of the values fitted.: https://imgur.com/undefined

How we can see the fit for these samples, is very different. if we use Matlab to fit we get m~=4

I realize that if we have a few abrupt variations this issue is most common.

**Comment by sodaBitters** [comment]
I've also encountered this issue with the Nakagami fit - below is a simple example where it does not converge. Let me know if I can help in any way.

`a,b,c = scipy.stats.nakagami.fit(BELOW_DATA)`

It returns a few `RuntimeWarnings` and the resulting PDF is incorrect.... plotted using:
`plt.hist(BELOW_DATA, density=1)`
`dist = stats.nakagami(a,b,c)`
`plt.plot(np.linspace(-10, 70, 1000), dist.pdf(np.linspace(-10, 70, 1000)))`

array([34.85352 , 40.244015, 33.327774, 33.38671 , 38.889988, 48.170616,
       37.35796 , 36.931713, 31.33673 , 32.997395, 39.225002, 40.899612,
       34.3356  , 38.420677, 39.356686, 34.48843 , 42.157673, 38.26396 ,
       32.909546, 38.352047, 39.871906, 37.21753 , 34.40818 , 27.953384,
       32.03979 , 42.65722 , 55.498985, 34.355274, 48.83406 , 49.183556,
       37.038677, 46.56471 , 34.050434, 37.150345, 40.138954, 36.287395,
       49.436726, 35.631348, 30.646479, 33.673355, 42.396313, 38.65615 ,
       40.81687 , 34.44051 , 36.11141 , 39.70682 , 35.50506 , 32.173683,
       40.111214, 34.635376, 47.040794, 40.198147, 32.407345, 36.95832 ,
       34.68888 , 40.846107, 46.212223, 36.80449 , 39.766586, 42.394684,
       34.393036, 34.55419 , 39.32924 , 37.2723  , 34.080868, 33.91943 ,
       45.732224, 49.002888, 37.137   , 36.235313, 35.55437 , 43.882713,
       46.08311 , 32.540543, 28.251713, 41.1369  , 37.062042, 36.178913,
       36.20213 , 37.737236, 40.35584 , 45.156445, 36.926697, 36.585358,
       40.19868 , 32.806194, 43.702553, 32.368706, 30.475779, 40.057358,
       39.11504 , 35.763794, 39.721123, 34.099556, 33.976734, 41.066757,
       29.934776, 39.65433 , 40.92844 , 41.08059 , 32.966496, 38.67284 ,
       41.509632, 39.566162, 38.396667, 32.96559 , 36.52904 , 50.559673,
       37.947952, 43.032806, 45.296196, 33.419174, 37.844807, 37.519794,
       40.30262 , 39.63318 , 37.278156, 43.31975 , 33.952194, 34.115402,
       34.234142, 33.71543 , 42.689053, 42.5598  , 34.75893 , 47.746952,
       46.583748, 42.075188, 40.606865, 42.103664, 46.460724, 30.577326,
       38.26781 , 33.29049 , 35.811504, 36.40837 , 36.7905  , 39.193478,
       33.123577, 34.14775 , 33.38313 , 32.612274, 35.450623, 37.54964 ,
       38.93965 , 30.405289, 33.38397 , 43.271244, 41.655525, 33.104717,
       27.874151, 37.588223, 33.097706, 37.691555, 33.48039 , 34.062775,
       35.88681 , 34.28646 , 42.48908 , 29.056149, 35.883633, 35.657948,
       39.243298, 37.0106  , 40.705402, 28.039505, 34.950268, 40.91345 ,
       43.9687  , 43.846054, 36.68691 , 43.70271 , 35.280766, 43.827045,
       38.68056 , 34.525494, 41.060513, 33.20255 , 32.629395, 38.18805 ,
       35.824253, 33.20238 , 45.1024  , 46.412167, 32.784798, 35.3753  ,
       38.64177 , 36.473732, 32.88031 , 32.135185, 36.146088, 35.340992,
       37.564682, 50.246494, 34.321022, 38.023083, 41.030563, 36.198795,
       37.433277, 36.54378 , 27.701206, 33.013973, 40.600735, 35.075333,
       37.95572 , 34.756554, 30.048496, 34.769062, 37.86967 , 42.082962,
       39.544865, 38.462696, 39.46167 , 40.950623, 39.777283, 38.618008,
       38.30507 , 53.49027 , 37.999386, 35.09001 , 39.162334, 42.906666,
       33.242004, 46.131073, 33.578953, 38.481247, 29.660536, 36.82245 ,
       32.74162 , 32.628143, 33.744186, 49.306637, 43.422424, 34.94902 ,
       47.762993, 30.962717, 32.264217, 33.050995, 37.349216, 38.626316,
       44.080677, 36.39444 , 46.01969 , 33.069843, 39.74367 , 34.768913,
       36.89247 ], dtype=float32)

**Comment by WarrenWeckesser** [comment]
@sodaBitters, thanks, it is very helpful to have a concrete example.

Currently `nakagami` is a "minimalist" implementation.  The `fit()` method uses a generic optimization routine to fit the three parameters to the data.  It looks like it doesn't make a good enough initial estimate of the parameters for the numerical optimization routine to converge to the correct MLE.

Eventually we'll make the `fit()` method smarter.  For now, a possible work-around is to override the initial guess of the parameters.  With your data, I get a result that looks reasonable by using `loc=data.mean()` and `scale=data.var()`.   (The `loc` and `scale` parameters of `fit()` are the initial guess for these paramters.  An initial guess for the shape parameter can be given as the second positional argument.  If not given, it will use the default value 1, which is a good enough guess in this case.)

In the following , your data is stored in the array `data`:
```
In [106]: p = nakagami.fit(data, loc=data.mean(), scale=data.var())             

In [107]: p                                                                     
Out[107]: (1.6137291735075188, 25.821260967368353, 12.983502093549847)
```

The following commands generate a histogram and a plot of the PDF of the fitted distribution:
```
In [108]: hist(data, density=True, bins=16, alpha=0.5)                          
Out[108]: 
(array([0.01398183, 0.01864246, 0.03728492, 0.10253342, 0.06990915,
        0.08622128, 0.07923037, 0.05592732, 0.03495465, 0.01864244,
        0.02796366, 0.00932122, 0.01398183, 0.00233031, 0.0023303 ,
        0.0023303 ]),
 array([27.701206, 29.438568, 31.175928, 32.91329 , 34.65065 , 36.388012,
        38.125374, 39.862736, 41.600098, 43.337456, 45.074818, 46.81218 ,
        48.54954 , 50.286903, 52.02426 , 53.761623, 55.498985],
       dtype=float32),
 <a list of 16 Patch objects>)

In [109]: plot(x, nakagami.pdf(x, *p), 'k')                                     
Out[109]: [<matplotlib.lines.Line2D at 0x1a20439450>]
```
![Figure_1](https://user-images.githubusercontent.com/321463/96224818-28c0d280-0f5e-11eb-8b34-1fef827ef7b2.png)

**Comment by jjerphan** [comment]
The estimate of Nakagami returned by fit can completely be off in some configurations:
```python
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> from scipy.stats import nakagami
>>> samples = nakagami.rvs(size=100, nu=1.6, loc=25.0, scale=13, random_state=1337)
>>> nakagami.fit(samples)
(0.0253790867232635, 26.862845727959254, 1.9070255006770171)
```
@WarrenWeckesser has a good point: providing the mean and standard deviation for the loc and scale helps with the estimation.
```python
>>> nakagami.fit(samples, loc=samples.mean(), scale=samples.var())
(1.743924994784647, 24.545404245954416, 13.664193433404588)
```

Generally, the initial estimates are computed in a similar fashion via `rv_continuous._fitstart` which is not overridden in the case of Nakagami. Thus parameters are estimated using the support of the distribution via `rv_continuous._fit_loc_scale_support`, which is not robust in this case.

One way to have a stable estimation would be to overwrite `_fitstart` for `nakagami_gen` and add parametrised tests because there aren't any.

**Comment by chrisb83** [comment]
Reopened: the MLE estimate is still not reliable in a lot of cases, see gh-15360

**Comment by mdhaber** [comment]
Although `nakagami`'s fit method can certainly be improved, the situation is not as dire as reports would suggest.

In `main`, with @sodaBitters data:

<details>

```python3
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

x = np.array([34.85352 , 40.244015, 33.327774, 33.38671 , 38.889988, 48.170616,
37.35796 , 36.931713, 31.33673 , 32.997395, 39.225002, 40.899612,
34.3356 , 38.420677, 39.356686, 34.48843 , 42.157673, 38.26396 ,
32.909546, 38.352047, 39.871906, 37.21753 , 34.40818 , 27.953384,
32.03979 , 42.65722 , 55.498985, 34.355274, 48.83406 , 49.183556,
37.038677, 46.56471 , 34.050434, 37.150345, 40.138954, 36.287395,
49.436726, 35.631348, 30.646479, 33.673355, 42.396313, 38.65615 ,
40.81687 , 34.44051 , 36.11141 , 39.70682 , 35.50506 , 32.173683,
40.111214, 34.635376, 47.040794, 40.198147, 32.407345, 36.95832 ,
34.68888 , 40.846107, 46.212223, 36.80449 , 39.766586, 42.394684,
34.393036, 34.55419 , 39.32924 , 37.2723 , 34.080868, 33.91943 ,
45.732224, 49.002888, 37.137 , 36.235313, 35.55437 , 43.882713,
46.08311 , 32.540543, 28.251713, 41.1369 , 37.062042, 36.178913,
36.20213 , 37.737236, 40.35584 , 45.156445, 36.926697, 36.585358,
40.19868 , 32.806194, 43.702553, 32.368706, 30.475779, 40.057358,
39.11504 , 35.763794, 39.721123, 34.099556, 33.976734, 41.066757,
29.934776, 39.65433 , 40.92844 , 41.08059 , 32.966496, 38.67284 ,
41.509632, 39.566162, 38.396667, 32.96559 , 36.52904 , 50.559673,
37.947952, 43.032806, 45.296196, 33.419174, 37.844807, 37.519794,
40.30262 , 39.63318 , 37.278156, 43.31975 , 33.952194, 34.115402,
34.234142, 33.71543 , 42.689053, 42.5598 , 34.75893 , 47.746952,
46.583748, 42.075188, 40.606865, 42.103664, 46.460724, 30.577326,
38.26781 , 33.29049 , 35.811504, 36.40837 , 36.7905 , 39.193478,
33.123577, 34.14775 , 33.38313 , 32.612274, 35.450623, 37.54964 ,
38.93965 , 30.405289, 33.38397 , 43.271244, 41.655525, 33.104717,
27.874151, 37.588223, 33.097706, 37.691555, 33.48039 , 34.062775,
35.88681 , 34.28646 , 42.48908 , 29.056149, 35.883633, 35.657948,
39.243298, 37.0106 , 40.705402, 28.039505, 34.950268, 40.91345 ,
43.9687 , 43.846054, 36.68691 , 43.70271 , 35.280766, 43.827045,
38.68056 , 34.525494, 41.060513, 33.20255 , 32.629395, 38.18805 ,
35.824253, 33.20238 , 45.1024 , 46.412167, 32.784798, 35.3753 ,
38.64177 , 36.473732, 32.88031 , 32.135185, 36.146088, 35.340992,
37.564682, 50.246494, 34.321022, 38.023083, 41.030563, 36.198795,
37.433277, 36.54378 , 27.701206, 33.013973, 40.600735, 35.075333,
37.95572 , 34.756554, 30.048496, 34.769062, 37.86967 , 42.082962,
39.544865, 38.462696, 39.46167 , 40.950623, 39.777283, 38.618008,
38.30507 , 53.49027 , 37.999386, 35.09001 , 39.162334, 42.906666,
33.242004, 46.131073, 33.578953, 38.481247, 29.660536, 36.82245 ,
32.74162 , 32.628143, 33.744186, 49.306637, 43.422424, 34.94902 ,
47.762993, 30.962717, 32.264217, 33.050995, 37.349216, 38.626316,
44.080677, 36.39444 , 46.01969 , 33.069843, 39.74367 , 34.768913,
36.89247 ], dtype=np.float32)

plt.hist(x, density=True, bins=20)
a,b,c = stats.nakagami.fit(x)
dist = stats.nakagami(a,b,c)
plt.plot(np.linspace(-10, 70, 1000), dist.pdf(np.linspace(-10, 70, 1000)))
```

![image](https://user-images.githubusercontent.com/6570539/153669474-2185305c-846f-4086-b224-98d8ed2b6dff.png)

</details>

I think we fixed the problem with @jjerphan's example in gh-13396. `nakagami.rvs` has changed since then, and we still get a good fit:

<details>

```python3
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

x = stats.nakagami.rvs(size=100, nu=1.6, loc=25.0, scale=13, random_state=1337)
plt.hist(x, density=True, bins=20)
a,b,c = stats.nakagami.fit(x)
dist = stats.nakagami(a,b,c)
plt.plot(np.linspace(10, 70, 1000), dist.pdf(np.linspace(10, 70, 1000)))
a, b, c  # (1.4087264104860842, 26.922668622940762, 11.044961991454768)
```

![image](https://user-images.githubusercontent.com/6570539/153669854-ee41aea5-dfdb-442b-805a-6b0d312c44fe.png)

</details>

Test failures were reported in gh-15360. Investigating more carefully, this is more of a problem with the test than with the fit. Here is code that illustrates one of the failures.

<details>

```python3
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

v, u, s = 2.5, 10, 20
x = stats.nakagami.rvs(size=100, nu=v, loc=u, scale=s, random_state=1337)
plt.hist(x, density=True, bins=20)

res = stats.nakagami.fit(x)  # (1191.9716538996727, -365.8807923337205, 394.8732242250576)
dist = stats.nakagami(*res)

grid = np.linspace(np.min(x), np.max(x), 1000)
pdf = dist.pdf(grid)
plt.plot(grid, pdf)
```

</details>

The test fails because the fit parameters:
```python3
res = stats.nakagami.fit(x)  # (1191.9716538996727, -365.8807923337205, 394.8732242250576)
```
are very different than the parameters used to generate the data:
```python3
v, u, s  # (2.5, 10, 20)
```

Yet the MLE fit has done its job:
```python3
stats.nakagami.nnlf((v, u, s), x)  # 317.3082922597364
stats.nakagami.nnlf(res, x)  # 316.1429534501842
```

The negative log-likelihood function at the fit result is lower - and therefore "better" according to maximum likelihood estimation - than at the original parameters. 

Having `loc` and `scale` provided by `rv_continuous` is great for some distributions, but not for others. For high values of `nu`, Nakagami is one of the latter cases because it's almost over-parameterized That is, you can get nearly the same shape distribution with very different values of the parameters.

To illustrate, this is what the negative log-likelihood function looks like in the neighborhood of the original parameters from the example above (as a function of `nu`/`v` and `loc`/`u` with `scale` at its [analytical optimum](https://github.com/scipy/scipy/pull/13396#discussion_r559246415)).

![image](https://user-images.githubusercontent.com/6570539/153672047-53b2e54a-dab6-4267-8142-94a9d63d6d67.png)

The blue point is located at the values used to generate the data; the orange point corresponds with the lowest value of the NLLF in the domain of the plot. They both lie in a valley that snakes around, gradually decreasing the NLLF as `nu` increases and `loc` decreases.  If we extend the domain of the plot:

![image](https://user-images.githubusercontent.com/6570539/153672364-e186a14e-18e4-4617-b660-fee473d2c674.png)

To close this issue, I'd suggest the following:
* Add notes to the documentation about the [standard Nakagami parameterization](https://en.wikipedia.org/wiki/Nakagami_distribution). Mention that the standard parameterization in terms of `m` and `Omega` is the same as ours with `nu = m`, `scale = np.sqrt(Omega)`, and `loc = 0`.
* Mention that for best `fit` results, users should fix `loc` - probably at 0.
* Consider additional adjustments to `_fitstart`. For instance, we might want to back off the guess of the location away from `np.min(x)` (which, although the exact optimum for sufficiently small `nu`, is at its upper bound and on the verge of being inconsistent with the data). We also might be able to provide a better guess of the shape parameter (see e.g. [here](https://ieeexplore.ieee.org/document/913153)).
* Override the default `fit` method when `loc` or `nu` are fixed. In either case, we have an analytical solution for the `scale`, and we can solve the first-order necessary condition for the remaining parameter with `root_scalar`.

We may still be able to improve `fit` when `loc` and `nu` are both free, but it may not be as badly broken as it might seem, and there is lower hanging fruit.

**Comment by mdhaber** [comment]
This is being tracked in gh-11782, so I'll go ahead and close this one.
