### ISSUE TITLE
Typo in docstring for `Rotation.from_euler`

### ISSUE THREAD

**Issue by agoose77** [scipy/scipy#10984]
My issue is about a typo in `Rotation.from_euler`: https://github.com/scipy/scipy/blob/master/scipy/spatial/transform/rotation.py#L709

The docstring should read 

> Rotations in 3 dimensions can be represented by a __sequence__ of 3

not 

> Rotations in 3 dimensions can be represented by a __sequece__ of 3

**Comment by mkg33** [comment]
Thanks for pointing it out, @agoose77!

**Comment by rgommers** [comment]
@mkg33 thanks for fixing this! 

A small hint for next time: in the commit message that fixes things (and/or the PR description), you want to put `Closes gh-10984`. Then when the PR gets merged, the issue gets auto-closed. If you close the issue by hand and we don't merge the PR for whatever reason, the bug report gets lost.

No need to make any changes now, since I'm going to merge your PR as soon as CI is green.

**Comment by mkg33** [comment]
@rgommers Thanks, I'll keep that in mind! Oh, I thought that putting 'Closes #10984' was the right way. So much to learn :-)

**Comment by rgommers** [comment]
`#` works too, but we try to use `gh-` because it's then clear it's a GitHub issue. We still have `#xxxx` references to Trac (our pre-GitHub bug tracker) floating around, and who knows - maybe in 10 years from now we won't be on GitHub anymore.

**Comment by mkg33** [comment]
Makes perfect sense.
