### ISSUE TITLE
`binned_statistic_2d` flips x/y coordinates in result

### ISSUE THREAD

**Issue by ahalota** [scipy/scipy#11011]
The shape of stats.binned_statistics_2d does not match up properly with what is described as x/y in the docstring. It seems to be flipped along x/y axis (although the x_edge and y_edge results are as expected).

#### Reproducing code example:
```
xs = [-1.5, 0.5, 1.5, 1.75]
ys = [ 1,-1, 1, 1]

xBin = 4
yBin = 2

xMin = -2
yMin = -2
xMax = 2
yMax = 2

counts = stats.binned_statistic_2d(xs,ys,None,
     statistic='count',
     bins=[xBin,yBin],
     range=[[xMin,xMax],[yMin,yMax]])
 ```

**Leads to this output:**

**counts**
```
 BinnedStatistic2dResult(
   statistic=array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.]]), 
x_edge=array([-2., -1.,  0.,  1.,  2.]), 
y_edge=array([-2.,  0.,  2.]), 
binnumber=array([ 6, 13, 18, 18], 
dtype=int64))
```
**counts.statistic.shape** 
```
(4,2)
```

**Expected Result**
I'd expect the actual result to be what I get by running counts.statistic.transpose() on the given result:
```
array([[0., 0., 1., 0.],
       [1., 0., 0., 2.]])
```

With a shape = `(2,4)`

```

#### Scipy/Numpy/Python version information:
```
1.3.1 1.16.4 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
I don't see a mismatch between the output of the function and the documentation. 

You provided `bins=[xBin,yBin],` in your example:
![image](https://user-images.githubusercontent.com/6570539/158497262-30966f73-bddb-4a88-8d09-a5810f848183.png)

This is interpreted as `nx, ny = bins`, so `nx = xBin`, `ny = yBin`:
![image](https://user-images.githubusercontent.com/6570539/158497186-6625b61f-142b-444e-99ae-2203d4223c29.png)

The documentation says that the `statistic` output will be of shape `(nx, ny)`:
![image](https://user-images.githubusercontent.com/6570539/158497224-5f36d4f0-9662-4a91-933a-c4069c6bded8.png)

```python3
(xBin, yBin) == counts.statistic.shape # True
```

Screenshots are from the 1.3.1 documentation because that is the version reported. It is the same current main, though.

Please correct me if I've misunderstood. 
@tirthasheshpatel would you check me? am I having a bad day? : )

**Comment by tirthasheshpatel** [comment]
@mdhaber I verified with the [1.3.1 docs ](https://docs.scipy.org/doc/scipy-1.3.1/reference/generated/scipy.stats.binned_statistic_2d.html#scipy.stats.binned_statistic_2d)and the outputs seem to align with it as shown in your screenshot so I would also consider this closed.
