### ISSUE TITLE
rv_discrete.interval returning wrong values for alpha = 1

### ISSUE THREAD

**Issue by bentheiii** [scipy/scipy#11026]
Scipy's rv_discrete.interval method, it appears that the lower bound is decreased by 1 when the alpha is set to exactly 1 (as far as I can tell, this is the most reliable way to get a generic rv's support's minimum)

#### Reproducing code example:

```
from scipy.stats import bernoulli  # also tested with randint and binom

rv = bernoulli(0.5)

print(rv.interval(1))  # expected (0,1), got (-1,1)
```

#### Scipy/Numpy/Python version information:

1.3.1 1.17.3 sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)

**Comment by fuglede** [comment]
According to the documentation, `interval`, produces a

> Confidence interval with equal areas around the median.

Here, presumably, "equal areas" means "equal mass".

If you use the definition that a *median* of a random variable $X$ is any number $m$ satisfying $P(X \geq m) \geq \frac{1}{2}$, $P(X \leq m) \geq \frac{1}{2}$, then the medians of `rv` are all numbers $0 < m < 1$. Then the above definition of course depends on the value of $m$, but in this particular case, any interval $[x, y]$ with $x \leq 0$, $y \geq 1$ will work according to the definition, and in particular $[-1, 1]$ is one such interval (as is $[0, 1]$); why would you expect $[0, 1]$ instead? It has one nice property of being the intersection of all intervals with the given property.

Now for some reason `rv.median()` produces 0, and with that as a definition, *no* interval satisfies the condition in the documentation of `interval`, so following that, nothing should really be returned at all. But maybe then (without having consulted the implementation), $[-1, 1]$ is given since it happens to be symmetric around 0, and some weird notion of "area" is at play. That doesn't explain why `bernoulli.interval(0.999, 0.5)` produces `(0.0, 1.0)` though.

This is really an issue of the documentation being unclear, both in the case of `interval` and `median`.

**Comment by josef-pkt** [comment]
`interval` is defined in terms of tail probabilities with at least the given coverage.

In the discrete case, if we need to include the lower bound, then the value is set to one lower (-1).

I always had problems with this, it's not intuitive and I don't remember it unless I go through the argument again.

The main reason is that `cdf` is defined as closed on the right, and `sf` as open on the left
i.e. cdf: Prob(x <= 0) > 0, or sf: Prob(x > 0) < 1
but cdf: Prob(x <= -1) == 0, or sf: Prob(x > -1) == 1

I don't think we can change this, because current computation with discrete distributions depend on this definition. AFAIR.

**Comment by fuglede** [comment]
@josef-pkt Are you saying that the intervals produced by `interval` are open? Then its outputs are even more wrong in this case (so if other parts of `scipy.stats` depend on them, that should also be problematic). Or perhaps include the upper bound but not the lower? In any case, that really should be spelled out in the docs as well.

**Comment by josef-pkt** [comment]
AFAIR, cdf and similar for discrete distributions are used in hypothesis tests for discrete data.
Those are verified in their results, so they use the current behavior correctly.

The main point in the definition is `Prob(x in A) >= coverage` rate

I don't remember or I'm not sure whether the interval is open on the left and closed on the right
i.e. Prob(x in A) = Prob(a < x <= b) = cdf(b) - cdf(a)

My guess would be that the usual definition for confidence intervals uses closed on both sides, based on the computation in related usage, i.e Prob(x in A) = cdf(b) - cdf(a - 1)

I haven't looked at this in the long time, so I don't remember details
`interval` was added later to the distributions, and I worked more with cdf and sf, e.g.
https://github.com/scipy/scipy/issues/2384

a quick check in statsmodels, for binom_test version I also only use cdf and sf.
I use `interval` only for continuous distributions.

So `interval` might not actually be used in followup code. 

In distributions like poisson, the interval can be in the interior for the sample space, That can be used to check the definition for other cases than coverage=1

**Comment by josef-pkt** [comment]
I'm not sure interval for discrete distributions has been systematically reviewed, I don't think I ever did.

searching issues for "interval discrete"

#9706 docstring for interval
#10317 nbinom, poisson example seems to return 0 as lower endpoint, and not -1
#9762 (closed) poisson seems to include endpoints, argument Prob(x in A) = cdf(b) - cdf(a - 1)

----

There is a BUG for prob=1, I guess in some special case handling
```
stats.bernoulli.interval(1-1e-14, 0.5)
(0.0, 1.0)
```

same for poisson
```
stats.poisson.interval(1, 0.5)
(-1.0, inf)
stats.poisson.interval(1, 0)
(-1.0, inf)
stats.poisson.interval(0.999, 0.001)
(0.0, 1.0)
```

**Comment by josef-pkt** [comment]
So, `interval` follows standard definition with closed interval on both sides

for discrete distributions 
`A = {x: a <= x <= b)`
`Prob(x in A) = cdf(b) - cdf(a - 1) >= coverage rate`

**Comment by fuglede** [comment]
Again, though, if you require that both end points of the interval be in the support, you will most likely not even have an interval with equal support on both sides on a median.

**Comment by mdhaber** [comment]
@WarrenWeckesser @mckib2 might this be another one for Boostinator?

**Comment by mckib2** [comment]
@mdhaber Boost agrees with SciPy in all the cases discussed above, namely:
```
median: 0.0
interval(1): (-1.0, 1.0)
interval(.999): (0.0, 1.0)
interval(1-1e-14): (0.0, 1.0)
```

**Comment by mdhaber** [comment]
> this is the most reliable way to get a generic rv's support's minimum

I think `support` is the most reliable way to get the minimum. At some point we changed it so that it works as expected for frozen distributions, too.

Suppose `dist` is a frozen distribution and `a, b = dist.support()`. For all discrete distributions, the 100% confidence interval will be `a-1, b`. This is because `interval` is implemented (reasonably, I think) as `ppf(p_tail, 1-p_tail)`, where `p_tail=(1-confidence)/2`, and `dist.ppf(0) = a-1`. Whether the latter is the best convention or not may be debateable: R's `pbinom(0, 10, 0.5) = 0`, whereas Boost's 100% Bernoulli interval agrees with SciPy. In any case, it is what SciPy does right now, so I propose to resolve this issue by documenting this (and testing it).

**Comment by h-vetinari** [comment]
I agree with many of the comments above that this is surprising and not ideal - why `-1` and not `-0.5`, `-10`, `-inf`, etc.? TBH, I don't see the reason to subtract anything from the lower bound of support for `ppf(0)`.

Unfortunately this has existed almost since the dawn of time - I went 20 years back the git history, and even before the stats module was [changed](https://github.com/scipy/scipy/commit/13cb6445db0b29532d7c8ab312e37b4ac538332a) to use classes, there were `vals-1` everywhere for the discrete distribution.

Still, I tend to think that fixing cruft and inconsistent/surprising behaviour is beneficial even if entrenched...

**Comment by mdhaber** [comment]
Please see rationale for our `ppf(0)` behavior in gh-15967.
