### ISSUE TITLE
linalg.eigh generalized eigenvalue problem call to LAPACK DSYTRD returns error for n >= 32.767

### ISSUE THREAD

**Issue by Schleuss94** [scipy/scipy#11080]
Hi all,

for my research project I have to deal with very high dimensional dense generalized eigenvalue problems and try to solve them with scipy.linalg.eigh.
Everytime the dimensions of the matrices exceed 32.766 x 32.766 the function returns an error.

#### The following example is sufficient to reproduce the error:

```
import numpy as np
import scipy.sparse
import scipy.linalg

n = 32.767
a = np.random.rand(n,n)
a = a.T.dot(a) + scipy.sparse.identity(n)     # ensure that matrix is sym. pos. def.
b = np.random.rand(n,n)
b = b.T.dot(b) + scipy.sparse.identity(n)
scipy.linalg.eigh(a,b)

```

Warning: This example uses a LOT of RAM but is the smallest possible error example.

#### Error message:

```
 ** On entry to DSYTRD parameter number  9 had an illegal value
Segmentation fault (core dumped)
```

#### Scipy/Numpy/Python version information:

```
1.3.2 1.17.4 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

Since LAPACK returns that the 9th parameter has an illegal value I suppose that there might be an error in the scipy call to the LAPACK function.

Thank you very much for your efforts in advance!

Best regards

**Comment by ilayn** [comment]
Yes that's because LWORK is 32 bit signed integer. So you cannot use more than that to allocate address. However your optimal block size is probably more than 2 and hence you get a result that overflows the 32bit integer. See LWORK definition [here](http://www.netlib.org/lapack/explore-html/d3/db6/group__double_s_ycomputational_gaefcd0b153f8e0c36b510af4364a12cd2.html).

Unless you use somehow a long integer fortran compiled lapack, you can't get passed that value. Unfortunately there is nothing for us to do on that front.
