### ISSUE TITLE
scipy.interpolate.interp1d can not handle datetime64

### ISSUE THREAD

**Issue by mbakker7** [scipy/scipy#11093]
The `interp1d` function of `scipy.interpolate` can not handle `datetime64` arrays, while there is initially no error message, and the fix seems easy (docs state that input should be real values, so that is correct)

#### Reproducing code example:
```
import numpy as np
from scipy.interpolate import interp1d
d1 = np.datetime64('2019-01-01')
d2 = np.datetime64('2019-01-03')
xp = np.array([d1, d2])
yp = np.array([1, 3])
x = np.datetime64('2019-01-02')
f = interp1d(xp, yp)  # no error message
f(x)  # now error appears
```
Error message: `TypeError: invalid type promotion`
But this works fine and seems easy to implement:
```
f = interp1d(xp.astype('float64'), yp)
f(x.astype('float64'))
```
So why not allow `datetime64` input and do the conversion inside `interp1d`?

**Comment by ev-br** [comment]
The issue is that `xp` remains `np.datetime` while `x` gets converted to `float` in the call to `_asarray_validated` inside `interp1d.__call__`. Hence an invalid type promotion error in trying to do mixed arithmetics between `datetime64[D]` and `float`.

There are two possible ways out:

- convert the `xp` argument to `interp1d.__init__` to float. 
If this is done, this will need to be tested for all interp1d interpolation kinds, and for a variety of `datetime` variants. E.g., what happens if `xp.dtype` is `datetime64[D]` (days) and `x.dtype` is `datetime64[ms]` (milliseconds)?
I suspect that alone would not be enough, the next request would be to account for business days.

- simply document that `interp1d` only accepts floats. 
This way, it's up to the user to properly convert datetime objects must be converted to ints or floats.

I'm leaning towards the second option TBH.

**Comment by mbakker7** [comment]
I would prefer to do the first option, if possible. To me, it sounds like
testing wether numpy correctly converts all its possible flavors of
datetime64 correctly to floats. If they are converted correctly, interp1d
would work. So why the doubt about numpy's conversion capabilities?

**Comment by ev-br** [comment]
Numpy converts a single datetime object correctly, yes. However,

```
In [23]: x, x.dtype                                                                                                                                                             
Out[23]: (numpy.datetime64('2019-01-02'), dtype('<M8[D]'))

In [24]: x1 = np.asarray(x, dtype='datetime64[m]')                                                                                                                              

In [25]: x.astype(float)                                                                                                                                                        
Out[25]: 17898.0

In [26]: x1.astype(float)                                                                                                                                                       
Out[26]: array(25773120.)
```

So if you (or someone else) sends a PR with datatime handling, this needs to be extensively tested.

**Comment by mbakker7** [comment]
Howbout `interp1d` stores the dtype of the array. Then when the function that `interp1d` is called, it requires the same dtype? At least then all is consistent. Too easy?
Right now it accepts certain dtypes when `interp1d` is called, but the function that `interp1d` returns does not accept the same dtype. That seems odd.

**Comment by AtsushiSakai** [comment]
> simply document that interp1d only accepts floats.
IMO, this is good idea. It might be able to close #12222
