### ISSUE TITLE
Wrong confidence interval for binomial distribution with p=0

### ISSUE THREAD

**Issue by diepala** [scipy/scipy#11134]
The confidence interval returned by the binomial distribution is incorrect when p=0. The result should be (0, 0), but it returns (n-1, 0) which is not a valid interval.

#### Reproducing code example:

```
import scipy.stats
print(scipy.stats.binom.interval(alpha=0.95, n=10, p=0))
```

#### Output:
```
(9.0, 0.0)
```

#### Expected Output:
```
(0.0, 0.0)
```

#### Scipy/Numpy/Python version information:
```         
1.3.3 1.17.2 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by reidarkind** [comment]
Took a look at your issue, since it at first glance looked as it could be connected to mine (#11132) - but seems they aren't after all.

Don't have a solution, but I see that the wrong result comes from 
`scipy.special.bdtrik`.

The interval method uses the ppf method, which again uses the _ppf method:
```
def _ppf(self, q, n, p):
    vals = ceil(special.bdtrik(q, n, p))
    vals1 = np.maximum(vals - 1, 0)
    temp = special.bdtr(vals1, n, p)
    return np.where(temp >= q, vals1, vals)
```

In fact, in your example the bdtrik returns 10, and then the _ppf subtracts 1. 
Code example:
```
from numpy import asarray
from scipy import special

alpha = asarray([0.95])
q1 = (1.0 - alpha) / 2
print(special.bdtrik(q1, 10, 0))
```

(Changing the last line to `print(special.bdtrik(q1, 10, 0.00001))` gives 0 as a result.)

See [documentation on bdtrik](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.bdtrik.html)

, which again refers to: [Formula 26.5.24 of [1] is used to reduce the binomial distribution to the cumulative incomplete beta distribution](http://people.math.sfu.ca/~cbm/aands/abramowitz_and_stegun.pdf)


Looks like bdtrik is made in cython, but cannot find the source in the repo..

**Comment by fuglede** [comment]
See also #11026 and the references in there.

**Comment by mdhaber** [comment]
@mckib2 Boostinator?

**Comment by mckib2** [comment]
@mdhaber Boost does the right thing here:
```
The correct answer for interval of binom(p=0) is (0, 0):
    scipy_binom: (9.0, 0.0)
    boost_binom: (0.0, 0.0)
```
