### ISSUE TITLE
Add wrapper for ?tbtrs

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#11190]
See [NumFOCUS Small Development Grant Proposal 2019 Round 3 proposal](https://www.dropbox.com/s/i24h3j2osol56uf/Small%20Development%20Grant%20-%20LAPACK%20%20%28Condensed%29.pdf?dl=0) for background.

Add wrapper for [?tbtrs](http://www.netlib.org/lapack/explore-html/da/dba/group__double_o_t_h_e_rcomputational_gaadacbb4c29e9604acd77ada4963827c5.html#gaadacbb4c29e9604acd77ada4963827c5).

Existing [wrapper](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lapack.dtrtrs.html) for [?trtrs](http://www.netlib.org/lapack/explore-html/da/dba/group__double_o_t_h_e_rcomputational_ga7068947990361e55177155d044435a5c.html) located in [scipy/linalg/flapack_other.pyf.src](https://github.com/scipy/scipy/blob/master/scipy/linalg/flapack_other.pyf.src) provides some guidance. 

Suggested signature:
```
! x, info  = tbtrs(ab, b, uplo="U", trans="N", diag="N", overwrite_b=0)
```
(`kd` can be determined based on number of rows of `A` and `N` is number of columns, right?)
Signature above _does not_ follow example of [dtrtrs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lapack.dtrtrs.html), which renamed some of the arguments and converts from character inputs to integers  (why?). Following that, it would look like:
```
! x, info  = tbtrs(ab, b, lower=0, trans=0, unitdiag=0, overwrite_b=0)
```
Should we follow the SciPy precedent, or stay closer to the original Fortran interface? @ilayn?

Test idea:

- Generate random matrix `A`
- Generate random solution `x`
- Generate `b` from `A@x`
- Solve using `?tbtrs`
- Compare solution from `?tbtrs` against known `x`

Be sure to perform similar tests for the different `trans` options.
Also test for singular matrix and for incorrect/incompatible array sizes.

Also: implement examples from the [NAG manual](https://www.nag.com/numeric/fl/nagdoc_latest/html/f07/f07vef.html) as additional tests.

**Comment by Kai-Striega** [comment]
> ! x, info  = tbtrs(a, b, uplo="U", trans="N", diag="N", overwrite_b=0)

:+1: the signature looks good.

> which renamed some of the arguments and converts from character inputs to integers (why?)

I don't think there is any particular reason, perhaps its treated as some kind of enumeration? Either way I think that SciPy should follow the original signature unless a good reason **not** to do so comes up.

On a side note, would you mind if I work through this one on my own? While I am getting quicker with the wrappers I think it would be good for me to go through (at least) one from start to finish.

**Comment by ilayn** [comment]
Lapack vars are better in my opinion. So that people also can read about them in lapack docs.

I don't think you can retrieve `kd` from the rest.

**Comment by mdhaber** [comment]
> On a side note, would you mind if I work through this one on my own?

Sure. What have we been doing that you don't want us to do?

**Comment by Kai-Striega** [comment]
@mdhaber so far, not too much. It's just in case you want to start writing the tests first, but let's get the other two done for first.

**Comment by Kai-Striega** [comment]
I've done some work on this locally and I think we need to change how we pass the matrix `A`. The cause of the issue comes from the fact that `?tbtrs` accepts a matrix `AB` not `A`. `AB` represents the same system as `A` but uses the fact that `A` is a triangular band matrix to store the data more efficiently by storing one "band" per row [1].  It is possible to convert `A` to `AB` but requires explicitly passing `kd`. 

I think there are two ways to go forward from here:

1. Explicitly accept `ab`.
2. Accept `a` and `kd` then convert to `ab` inside the callstatement.

Of the two my preference is (1). This way we maintain parity with the LAPACK documentation, keep the wrapper simpler by not converting the matrix and avoid the increased memory footprint. The cost of doing this is that the user would need to understand the required structure of the matrix, rather than naively passing the entire matrix.


[1] Using the matrix from the [NAG](https://www.nag.com/numeric/fl/nagdoc_latest/html/f07/f07vef.html) example the matrix `A`

```
[-4.16   0      0     0 ]
[-2.25 4.78     0     0 ]
[0       5.86  6.32   0 ]
[0       0    -4.82 0.16]
```

Would convert to the `AB` matrix:

```
[-4.16 4.78  6.32 0.16]
[-2.25 5.86 -4.82   0  ]
```

**Comment by mdhaber** [comment]
1 is what I intended.

**Comment by Kai-Striega** [comment]
That's what I thought, but I'd rather put it up for the discussion. I've got the NAG examples passing and I'll be working on the randomised tests today/tomorrow, so I should have a PR ready early next week.

**Comment by mdhaber** [comment]
@swallan
