### ISSUE TITLE
linprog: remove_sparse_redundancy redundancy slow

### ISSUE THREAD

**Issue by hakeemo** [scipy/scipy#11215]
In _remove_redundancy_sparse, spsolve is repeatedly called within a loop. 
`pi = scipy.sparse.linalg.spsolve(B.transpose(), e).reshape(-1, 1)`
Since B does not change, it would be a lot faster to have an LU factorization outside of the loop

**Comment by mdhaber** [comment]
@hakeemo thanks for suggestions about `linprog`. 

You're right that there may be many iterations in which `B` doesn't change, and on those iterations it might be more efficient to re-use an old factorization. There are two reasons this might not have been implemented:

* For dense matrices, I remember that `scipy.linalg.solve` appeared to cache the factorization and it was actually faster in most cases tested to call `solve` repeatedly than to re-use a factorization explicitly. Shouldn't assume that is true for SuperLU, though.
* More likely is that since the real plan was to _update_ a factorization (see `_remove_redundancy_dense`) rather than factorize from scratch every time, this part simply wasn't optimized much after I ran into trouble with SuperLU (see gh-7700).

There is now a workaround for gh-7700, so it would be great to revisit this.

**Comment by hakeemo** [comment]
@mdhaber  Would it make sense to first compute the rank of the matrix using svd in order to see if there is any work that needs to be done before running the algorithm in the remove_redundancy function ?

**Comment by mdhaber** [comment]
The rank is computed before about redundancy removal algorithms run. I think the code for that is in `_presolve` in `_linprog_util.py`. I suppose that hints at another potential optimization - abort this algorithm after the expected number of redundancies have been detected.

**Comment by hakeemo** [comment]
Right. I missed that. However from my understanding of the code, that is only done for dense matrices. For sparse matrices it is kept as a TODO in the code.

**Comment by mdhaber** [comment]
Oh right. I don't think SciPy has a sparse rank check that is faster than this. `scipy.sparse.linalg.svds` has an option for finding small magnitude singular values but in practice convergence is very poor.
