### ISSUE TITLE
solve_ivp does not complete for simple stiff ODE

### ISSUE THREAD

**Issue by moorepants** [scipy/scipy#11274]
My issue is about ...

Julia posted these benchmarks for differential equations and found that `solve_ivp` doesn't seem to complete for the Rober stiff equations:

https://github.com/JuliaDiffEq/SciPyDiffEq.jl#test-problem-failures

`odeint` handles it as expected:

```
from scipy.integrate import odeint                                                                                 
def rober(t,u):
  k1 = 0.04
  k2 = 3e7
  k3 = 1e4
  y1, y2, y3 = u
  dy1 = -k1*y1+k3*y2*y3
  dy2 =  k1*y1-k2*y2*y2-k3*y2*y3
  dy3 =  k2*y2*y2
  return [dy1,dy2,dy3]

u0  = [1.0,0.0,0.0]                                          

import numpy as np                                           

tspan = np.linspace(0.0, 1e5)                                

rober_swap = lambda u, t: rober(t, u)                        

odeint(rober_swap, u0, tspan)
```

#### Reproducing code example:

```
Sample code to reproduce the problem
from scipy.integrate import solve_ivp
def rober(t,u):
  k1 = 0.04
  k2 = 3e7
  k3 = 1e4
  y1, y2, y3 = u
  dy1 = -k1*y1+k3*y2*y3
  dy2 =  k1*y1-k2*y2*y2-k3*y2*y3
  dy3 =  k2*y2*y2
  return [dy1,dy2,dy3]

u0  = [1.0,0.0,0.0]
tspan = (0.0,1e5)
solve_ivp(rober,tspan,u0,t_eval = [0.0,1e5])
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by themowski** [comment]
Note that the default solution method for `solve_ivp` is `RK45`, which is not recommended for stiff problems. From the docs for `solve_ivp`:

>Explicit Runge-Kutta methods (‘RK23’, ‘RK45’, ‘DOP853’) should be used for non-stiff problems and implicit methods (‘Radau’, ‘BDF’) for stiff problems [9]. Among Runge-Kutta methods, ‘DOP853’ is recommended for solving with high precision (low values of rtol and atol).
>If not sure, first try to run ‘RK45’. If it makes unusually many iterations, diverges, or fails, your problem is likely to be stiff and you should use ‘Radau’ or ‘BDF’. ‘LSODA’ can also be a good universal choice, but it might be somewhat less convenient to work with as it wraps old Fortran code.

Unless I'm not understanding something, this is 100% user error on behalf of the Julia folks: they know beforehand that the problem is stiff, so they should be specifying either `method="Radau"` or `method="BDF"`.

Trying that myself with the supplied snippet, these were my results (which completed more or less instantly):

```python
# Omitting setup code from workable example
>>> solve_ivp(rober,tspan,u0,t_eval = [0.0,1e5], method="BDF")
  message: 'The solver successfully reached the end of the integration interval.'
     nfev: 269
     njev: 9
      nlu: 38
      sol: None
   status: 0
  success: True
        t: array([     0., 100000.])
 t_events: None
        y: array([[1.00000000e+00, 1.78956631e-02],
       [0.00000000e+00, 7.28708070e-08],
       [0.00000000e+00, 9.82104264e-01]])
>>> solve_ivp(rober,tspan,u0,t_eval = [0.0,1e5], method="Radau")
  message: 'The solver successfully reached the end of the integration interval.'
     nfev: 391
     njev: 22
      nlu: 94
      sol: None
   status: 0
  success: True
        t: array([     0., 100000.])
 t_events: None
        y: array([[1.00000000e+00, 1.78655751e-02],
       [0.00000000e+00, 7.27460807e-08],
       [0.00000000e+00, 9.82134353e-01]])
```

I don't know that those answers are correct (the linked repo's docs don't say what the expected answers are), but the runs completed, and the answers are very close to each other. The sample code provided above (without the `method` specified) did not complete within a minute so I killed it.

I did this test with Python 3.6.8 on Windows 10 with SciPy 1.1.0. My machine has a Core i7-7820HQ and 16 GB RAM.

All that said... maybe a future version of SciPy could provide a `solve_stiff_ivp` function that just wraps `solve_ivp` with one of the recommended methods (and possibly only accepts Radau/BDF as methods)? It's certainly redundant, but perhaps it would help guide users to the correct functionality in situations like the one presented.

**Comment by ChrisRackauckas** [comment]
That explains a lot. I thought the default was LSODA in both `odeint` and `solve_ivp`. I'll fix up the benchmarks once I get back to a computer with a MATLAB license.

**Comment by moorepants** [comment]
@themowski Thank you for the explanation. I'm going to close this issue.

**Comment by denis-bz** [comment]
5 years later, this plot on [scicomp.stack](https://scicomp.stackexchange.com/questions/42613/need-help-to-fully-understand-scipys-odeints-reported-step-sizes-eval-times/44925#44925) shows that playing pinball with ODE solvers / atol / rtol is silly,
miles away from an interactive display-and-control app.
