### ISSUE TITLE
scipy.sparse.linalg.svds (v1.4.1) on singular matrix does not give vh vectors in null space

### ISSUE THREAD

**Issue by horacepan** [scipy/scipy#11406]
I am trying to use scipy's sparse [svds](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.svds.html) to compute the nullspace of a matrix by grabbing the smallest singular values with the `which='SM'` option. However, as shown in the code snippet below, the resulting rows of the `vh`  matrix are not in the null space of the input matrix. This is not a problem in the non-sparse [svd](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html#scipy.linalg.svd). Any ideas on why this happens?

Reproducing Code ex:
```
import numpy as np
import scipy.sparse as sparse
from scipy.linalg import null_space, svd
from scipy.sparse.linalg import svds

# create a 10x10 singular matrix with a 4-dim null space
dim = 4
size = 10
x = np.random.random((size, size-dim))
y = x[:, :dim] * np.random.random(dim)
mat = np.hstack((x, y))

nz = null_space(mat)
print('Null space vectors:', nz.shape)
assert nz.shape[1] == dim

# use non-sparse svd
u, s, vh = svd(mat)
print(f'Last {dim} singular values are 0:', np.allclose(s[-dim:], 0))
print('Smallest right singular vectors in null space:', np.allclose(mat @ vh[-dim:, :].T, 0))

# Smallest singular values should be 0
sp_mat = sparse.coo_matrix(mat)
su, ss, svh = svds(sp_mat, k=dim, which='SM')
print(f'Last {dim} singular values are 0:', np.allclose(ss, 0))
print('Smallest singular vectors via svds in null space:', np.allclose(sp_mat @ svh.T, 0))
```

Output:
```
Null space vectors: (10, 4)
Last 4 singular values are 0: True
Smallest right singular vectors in null space: True
Last 4 singular values are 0: False
Smallest singular vectors via svds in null space: False
```

Package version info:
scipy: 1.4.1
numpy: 1.16.2

**Comment by mdhaber** [comment]
Can you show what your last 4 singular values/vectors are for the sparse computation?
I'm actually getting a `nan`:
```
ss
Out[4]: array([           nan, 6.20188284e-18, 3.17654477e-16, 2.30408497e-09])
```

**Comment by mdhaber** [comment]
I have had trouble with sparse SVD, too. For some algorithms, convergence issues would be expected when the near-zero eigenvalues are close to zero and far from the largest magnitude eigenvalue.

**Comment by mdhaber** [comment]
`solver="lobpcg"` has trouble, too:
```
>>> su, ss, svh = svds(sp_mat, k=dim, which='SM', solver='lobpcg')
>>> print(f'Last {dim} singular values are 0:', np.allclose(ss, 0))
Last 4 singular values are 0: False
>>> print('Smallest singular vectors via svds in null space:', np.allclose(sp_mat @ svh.T, 0))
Smallest singular vectors via svds in null space: False
```
Thoughts, @lobpcg?

**Comment by horacepan** [comment]
Thanks for taking a look @mdhaber, much appreciated!
Yea I don't think I've been seeing NaNs but maybe I've just gotten lucky with my small examples. If the sparse svd does converge in this example I should definitely be getting right singular vectors in the null space of the matrix, right?

Here's the singular values when I run this with a `np.random.seed(10)`
```
Full singular values from np.linalg.svd [4.60087784e+00 1.58061463e+00 1.10190392e+00 9.13466205e-01
 8.09910563e-01 3.16629133e-01 1.72734726e-16 9.63879770e-17
 6.00837644e-17 4.30273294e-17]
Smallest 4 singular values from sparse.linalg.svds [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.25649964e-08]
```
Notebook link for repro: https://colab.research.google.com/drive/1JohaL9DOKnvT2tyZQG7QTY5Fc4wb7-7J

**Comment by mdhaber** [comment]
On my machine I'm still getting a `NAN` with `np.random.seed(10)`.

> If the sparse svd does converge in this example I should definitely be getting right singular vectors in the null space of the matrix, right?

That's my understanding, too. On Colab, the last of those isn't even normalized. If you normalize it, they're orthogonal, but yeah, not spanning the nullspace.

On Colab, `solver="lobpcg"` produces the expected result. That is,
```
su, ss, svh = svds(sp_mat, k=4, which='SM', solver="lobpcg")
#print(f'Last {dim} singular values are 0:', np.allclose(ss, 0))
print(f'Smallest {dim} singular vectors via svds in null space:', np.allclose(sp_mat @ svh.T, 0, atol=1e-4))
print(f'Smallest {dim} singular values from sparse.linalg.svds', ss)
```
produces:
```
Smallest 4 singular vectors via svds in null space: True
Smallest 4 singular values from sparse.linalg.svds [3.07073982e-08 3.07073982e-08 3.07073982e-08 3.07073982e-08]
```

**Comment by lobpcg** [comment]
A few notes: 
1) for this setup, dim = 4, size = 10, LOBPCG internally simply defaults to a dense eigensolver even for sparse matrices, so it should probably not be the trouble point.
2) Only one set of singular vectors, `su` or `svh`, is actually computed in svds - the choice is made depending on the size of the matrix. The second set is generated afterwards from the first set by multiplying by the matrix. For zero singular values, this latter procedure is evidently problematic, trying to get, e.g. a left singular vector by multiplying the right singular vector by basically zero. It is done using some tricky heuristics that depends on the machine epsilon (possibly platform dependent?).   
3) Since the matrix is square in this example, one can use the following work around, computing the singular vectors first for `mat` and then again but for `mat.T` and each time only keep the set which is actually correct.  Assuming that my conjecture above is correct, that at least one of the sets, `su` or `svh`, should be accurate...

**Comment by mdhaber** [comment]
Thanks @lobpcg!
@horacepan Unfortunately I can't fix this now (or any time soon), but I hope this workaround is helpful.

**Comment by lobpcg** [comment]
@horacepan - I probably was the last one making significant changes to svsd, but I have not touched this part of the code, where the second set of singular vectors is generated afterwards from the first set of singular vectors by multiplying by the matrix. This part of the code surely looks strange, may be not easy to change. I have not tested the code specifically with (nearly) zero singular values. 
But I am not surprised if it has issues. It should probably be broken even for very small-size (like 3x3) diagonal matrices... 

I do not have time to look into this now, unfortunately.  It also may be not so simple to fix.

**Comment by lobpcg** [comment]
There appear to be multiple issues in svds related to computing singular values for (nearly) zero singular values. E.g., it appears totally broken for either sparse or dense mat =
```
[[0 0]
 [0 1]]
```

**Comment by horacepan** [comment]
Ah, I see, and of course no worries! I've been using a workaround to avoid using sparse svd in my code. Thanks for taking a look and for sharing your insight @lobpcg :)

**Comment by lobpcg** [comment]
https://github.com/scipy/scipy/pull/11829 should probably resolve this issue

**Comment by lobpcg** [comment]
Mysteriously, the test suggested here still fails in
https://github.com/scipy/scipy/pull/11829
too for absolutely no good reason. I have added it as a unit test in https://github.com/evgueni-ovtchinnikov/scipy/blob/fix-svds/scipy/sparse/linalg/_eigen/tests/test_svds.py
but have to comment out line 777 for the test to pass.

It's an example where the smallest requested singular values are all nearly zeros, very well separated from the rest. The failure is that all the right singular vectors are completely wrong for absolutely no good reason both with ARPACK and LOBPCG as solvers for the normal eigenvalue problem. LOBPCG in this 10x10 case with 4 eigenvalues requested simply calls the dense solver, so the eigenvectors must be correct, since the singular values are indeed computed as almost 0 as they should be.

I have spend a couple of days debugging and still could not find what goes wrong. Could someone else please have a look?

**Comment by tylerjereddy** [comment]
> Mysteriously, the test suggested here still fails in

Is that still the case? Let me know if this issue needs to be reopened--we can always adjust the final `1.9.0` release notes during the release candidate testing stages.

**Comment by lobpcg** [comment]
@tylerjereddy To my recollection, https://github.com/scipy/scipy/pull/11829 does not close this issue completely, since one of the sets of singular vectors, left of right, depending on the matrix shape may still be wrong and, e.g., is not checked by the unit test that I have written to incorporate the example in this issue into that PR. 

I have no setup to double-check this myself with https://github.com/scipy/scipy/pull/11829 being merged and refer instead for advice to @evgueni-ovtchinnikov - the author of the PR, whether this issue can now be closed or should remain open for another attack, may be at least checking and issuing a warning that some of the output vectors may be inaccurate.

**Comment by lobpcg** [comment]
@evgueni-ovtchinnikov could you please check whether this issue is fully resolved or not with your merged https://github.com/scipy/scipy/pull/11829 ?

**Comment by evgueni-ovtchinnikov** [comment]
@lobpcg no it is actually not because `svds` for some weird reason transposes square matrices. Consequently, in the case at hand it accurately computes the left singular vectors, but right singular vectors cannot be computed accurately because singular values are too small (machine zero). This was part of the reason I was trying to compute both kinds of singular vectors accurately, and what I did worked for square matrices actually, in particular for #11406. The easiest way to get #11406 closed is to replace `if n > m` in line 255 of `_svds.py` with `n >= m`, although I suspect some tests might fail.

**Comment by lobpcg** [comment]
@tylerjereddy please reopen the issue. It is still not fully resolved.

**Comment by lobpcg** [comment]
@evgueni-ovtchinnikov FYI, the bug here (still present in https://github.com/scipy/scipy/pull/11829) apparently was that the eigenvectors that enter the RR postprocessing were not orthonormal (which is now fixed in gh-16712) i.e., unrelated to singular values being too small in RR.
