### ISSUE TITLE
Performance of cg is worse when running on multiple threads

### ISSUE THREAD

**Issue by ma-sadeghi** [scipy/scipy#11410]
When I run the following code snippet using `export MKL_NUM_THREADS=1`, `cg` runtime is ~ 35 sec. However, when I increase the number of threads to 2, the runtime is ~ 37 sec. I wonder why the runtime increases. I expected to see a speed up, maybe not 2x, but close to 1.5x. Am I missing something?

PS. The code snippet is basically the discretized form of the 2D Poisson equation, with 6,250,000 unknowns.

#### Reproducing code example:
```
from time import time
import scipy as sp
from pyamg.gallery import poisson

n = 2500
A = poisson((n, n), spacing=1.0, format='csr')
b = sp.zeros(A.shape[0])
b[0] = 1.0

t0 = time()
x, _ = sp.sparse.linalg.cg(A, b)
print(time() - t0)
```
#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.3.1 1.17.2 sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
```

**Comment by lambe** [comment]
Most of the computational work in CG (and similar methods) is in the multiplication `Av` for some vector `v`. That operation is likely single-threaded in your code, which is why the performance gets worse. You increase the overhead cost with another thread that ends up not doing anything.

I don't know how `pyamg` implements matrix-vector multiplication, but that's the first place to start.

**Comment by lobpcg** [comment]
It's unclear if MKL has not been installed so that `export MKL_NUM_THREADS=1` or in MS Windows `setx MKL_NUM_THREADS 1` may have no effect. 

The Reproducing code example gives error as posted and requires editing to run.

Finally, and most importantly, the `CG` code has been newly rewritten as a part of https://github.com/scipy/scipy/pull/18488 more recently. 

The issue thus can be safely closed, I think.

**Comment by ilayn** [comment]
Let's come back to this when there is more information provided. Thanks all.
