### ISSUE TITLE
ENH: linalg?: Public function to identify independent/dependent rows/columns

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#11414]
In #11245 it was suggested that the functionality of the private redundancy removal routines used for `scipy.optimize.linprog` be exposed publically. 

Given a matrix, the function would identify a set of `k` independent rows/columns, where `k` is the rank of the matrix. An example use case is to remove redundant rows from a linear system to reveal a smaller but equivalent linear system.

- I'd suggest a single function in `scipy.linalg` (unless there is a more appropriate home) 
- A `method` argument would expose algorithms based on SVD, interpolative decomposition, and a pivot-based algorithm. Default `"pivot"`; alternatives `"id"` and `"svd"`. 
- The function would return a logical array in which ones corresponding with the independent rows. It's a one-liner from this to the use cases I can think of.
- Optionally, the user can pass in the matrix rank `k` to save a bit of time. For some methods this would allow the algorithm to terminate early; for others it obviates the need to call `np.matrix_rank` at the outset.
- Optionally, the user can pass in the right hand side `b` of a linear system. Along with identifying independent rows, the routine can identify whether there are RHS values that make the system inconsistent.

Possible signature:
```
independent = independent_rows(A, method='pivot', k=None, b=None)
```

Questions:

- What are the use cases? Is this functionality worth exposing?
- Should the function work on rows or columns by default?
- Should there be an option for controlling whether the function looks for rows vs columns, or should the user just transpose the input?
- Is there a need to return the linear combination of independent rows that produces the dependent rows? What should that output be called?
- Should this live in `linalg` or somewhere else?
- Do you agree that the function should return a logical array?
- What should the function be called?

@josef-pkt

**Comment by mdhaber** [comment]
A few posts that suggest this would fill a need:
https://stackoverflow.com/questions/28816627/how-to-find-linearly-independent-rows-from-a-matrix
https://math.stackexchange.com/questions/2416786/finding-a-redundant-equation-in-a-system-of-linear-simultaneous-equations
https://stackoverflow.com/questions/17527396/eliminate-redundant-equations-from-linear-system
https://www.mathworks.com/matlabcentral/answers/108835-how-to-get-only-linearly-independent-rows-in-a-matrix-or-to-remove-linear-dependency-b-w-rows-in-a-m

**Comment by ilayn** [comment]
Rank deficiency is already a difficult problem. My view is that as long as it is not failproof we shouldn't add any functionality that would break more than it fixes

**Comment by josef-pkt** [comment]
nothing is fail proof
np.linalg.matrix_rank and pinv have problems in some range of values (around rcond=1e-15 in the pinv case).
However, they are still very useful and heavily used in statsmodels.

**Comment by ilayn** [comment]
I would love to see a working example first before we dissect the possibilities.

**Comment by josef-pkt** [comment]
My guess was that if it works for scipy.optimize, then it should also work well enough for statsmodels and similar libraries.
However, I didn't try to figure out what the underlying algorithm does.

**Comment by pv** [comment]
Points that I think would be useful to understand first: (i) stability of dropping columns vs. picking orthonormal basis for null space complement e.g. from SVD in general, (ii) numerical stability of the particular algorithms that achieve it, (iii) what are use cases where you really want to drop columns instead of just picking a better basis? I understand this is done in linprog, but I don't know the precise reason why.

**Comment by josef-pkt** [comment]
to (iii)
In statistics application, many users prefer to drop columns or rows for easier interpretation of the remaining columns or rows which refer to the original space instead of some other linear basis.

For example, R and Stata automatically drop variables in a regression if there is perfect (at some numerical threshold) collinearity. statsmodels and sk-learn use SVD or pinv.
statsmodels still has open issues to provide the option of automatically dropping redundant/collinear columns.

statsmodels doesn't have anything yet to check linear/affine constraints given by users. Stata prints a warning (or raises?) if redundant constraints are provided.

Even if statsmodels doesn't do any dropping of rows or columns automatically, it is useful to have functions that can tell users which variables/rows/columns cause problems and tell them which they should drop.
e.g. stackoverflow recipe by Ann Archibald using qr for identifying collinear columns to drop.

However, I have several functions that are internal to statsmodels that use SVD to get a non-singular basis and the basis for the null space. I understand the linalg for that better, but this is for cases where the user does not see what basis is used in the internal computations or where the basis doesn't matter.

**Comment by ilayn** [comment]
The typical way to do this is a simple Arnoldi iteration. I already have something that does a similar "pick independent cols" problem 

https://github.com/ilayn/harold/blob/master/harold/_system_props.py#L151-L261

But again, this is sensitive to tolerance pickup and it is not that straightforward to adjust properly. Also for rectangular arrays it needs a bit more care. What I am concerned about is the users relying too much on this without setting a sensible tolerance value hence we need to do that a bit more carefully and that would open a can of worms ala pinv, pinvh etc.

**Comment by mdhaber** [comment]
Since redundancy removal came up in gh-12954, it reminded me of your questions here @pv. I'm not sure I can answer i) or ii), but I sat on a response to your third question:
> (iii) what are use cases where you really want to drop columns/rows instead of just picking a better basis? I understand this is done in linprog, but I don't know the precise reason why.

At the time, I thought the answer was that the inequality constraints make a basis change difficult. Was I thinking clearly or is there an easy way to do this?

**Comment by pv** [comment]
I was thinking that eliminating `A x = b` via SVD , you get `x = x_0 + V2 z` where `z` is the new variable. Then, the elementwise ineq. constraint `B x <= b_ub` becomes `(B V2) z <= b_ub - B x_0`, which has the same form as before but with new b_ub, B. But I guess linprog also has the bound constraints `lb <= x <= ub` and those can't be mapped like this.

**Comment by mdhaber** [comment]
Oops I think that's what I meant. In standard form, there's just Ax = b and x > 0. You can change the basis, but I don't know how to do that while keeping all the decision variables positive.
