### ISSUE TITLE
Allow Fortran 2003?

### ISSUE THREAD

**Issue by person142** [scipy/scipy#11421]
I believe we currently try to not go past Fortran 95. Features of the 2003 standard that are of particular interest to us include:

- Better C interop
- IEEE arithmetic module

At this point:

- gfortran supports (almost?) all of the 2003 standard, and certainly the parts we care about (https://gcc.gnu.org/wiki/Fortran2003Status)
- ifort supports the 2003 standard (https://software.intel.com/en-us/articles/intel-fortran-compiler-support-for-fortran-language-standards)
- flang also appears to support the 2003 standard (https://github.com/flang-compiler/flang/wiki)

So perhaps we are safe allowing code that targets Fortran 2003?

**Comment by rgommers** [comment]
What about `f2py` support though? I imagine it will "just work" for some features, but not for all.

**Comment by person142** [comment]
> What about f2py support though?

Ah that's a good point. Maybe we could figure out a subset of features that are ok; e.g. IEEE arithmetic shouldn't affect any function signatures, so that should be one of the cases where `f2py` just works. I only wanted to use ISO C binding for the cases where we don't use `f2py` (e.g. to simplify code like this https://github.com/scipy/scipy/blob/master/scipy/special/specfun_wrappers.c#L12), so if we stick to that as a guideline we might be ok too.

**Comment by pv** [comment]
I think the main problem is manylinux1, as that is probably what limits the gfortran version. IIUC, that is stuck in gfortran 4.8 (which has iso_c_bindings but no ieee_arithmetic).

For other Fortran compilers, I'd guess we can assume users have reasonably new ones installed.

**Comment by person142** [comment]
At what point do we get to move to manylinux2010? That appears to be at 8.3.1; this is what I get in their docker images:

```
# gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-8/root/usr --mandir=/opt/rh/devtoolset-8/root/usr/share/man --infodir=/opt/rh/devtoolset-8/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-8.3.1-20190311/obj-x86_64-redhat-linux/isl-install --disable-libmpx --with-mpc=/builddir/build/BUILD/gcc-8.3.1-20190311/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)
```

**Comment by pv** [comment]
In principle we could bump the manylinux version already in Scipy 1.5 I think. IIUC, multibuild supports it, so if all goes well it might not be complicated.

CentOS 5 was EOL'd in 2017, so I doubt there are real-world compatibility constraints that keep us at manylinux1. However, also manylinux2010 will be in similar situation this year, so we might also consider manylinux2014, which seems to get finalized ["soon"](https://github.com/pypa/manylinux/issues/338). However, it won't be in time for Scipy 1.5.

It also seems the manylinux versioning will become a [rolling one](https://www.python.org/dev/peps/pep-0600/) in future, but I guess we don't want to wait for that to be done.

**Comment by matthew-brett** [comment]
Multibuild does support newer Manylinux versions.

I guess we have no strong reason not to move to manylinux2010 now, and then manyliinux2014 in a year or so - is that right?

**Comment by pv** [comment]
I guess pip support is one question here. Do various Linux distros ship new enough pip versions for manylinux2010?

**Comment by andyfaff** [comment]
It should be easy to update pip though, it's harder to build the entire package though.

**Comment by matthew-brett** [comment]
Pip supports

* manylinux2010 from v19.0 (2019-01-22)
* manylinux2014 from v19.3 (2019-10-14)

See: https://pip.pypa.io/en/stable/news

I don't have a good feeling for how up-to-date people's Pips are - is
that something we can get from BigQuery?

**Comment by leofang** [comment]
@beckermr just curious: Is the fortran compiler on conda OK with this move?

**Comment by beckermr** [comment]
conda ships gfortran 4.7.3 on osx and linux (and that is only on conda-forge). The version for osx on defaults is even older. 

Looking at the status page linked above, I think conda would have to update in order to build with fortran 2003.

This is possible, but is a lot of work.

**Comment by pv** [comment]
Ok, manylinux2010 is on gfortran 7 (i386) or 8 (x86_64). In practice, also latest gfortran doesn't have all the f2003 corners implemented, so it'll be a subset defined by a gfortran version in any case.

Debian/Ubuntu are still at pip 18 and RHEL/Centos at pip 9 (?), so users would need to do upgrade pip first.

**Comment by rgommers** [comment]
I don't think you can do `pip upgrade pip` on a Linux package managed installed `pip` (permissions issue). It's kind of problematic. `python -m ensurepip --upgrade` also has permissions issues.

**Comment by matthew-brett** [comment]
I personally always go `--user`, with `python -m pip install --user -U pip` and I make sure I have `~/.local/bin` on my PATH.

**Comment by pv** [comment]
~/.local/bin also doesn't necessarily need to be on path, if /usr/bin/pip doesn't use pkg_resources (e.g. on Fedora/Debian).

**Comment by matthew-brett** [comment]
@pv - Ralf and I had this discussion before - I don't use `venv` myself now unless I'm controlling dependencies during development.   I used to use it all the time.  So, personally, I'd only give the `venv` advice to someone intending to spend most of their time developing.

**Comment by andyfaff** [comment]
If the Fortran tooling for windows and macOS is going to be better if we advance to more recent compilers then that would be a compelling reason to move (to 2010) for me. Linux distros typically have good tooling, so if the OS is stuck in the dark ages it's typically going to be easier for them to build packages rather than rely on pip installs.

**Comment by rgommers** [comment]
Here we don't need to give any advice I think, this is not our install docs page. The reality is that there are many tools like `venv`, `virtualenv`, `poetry`, etc. that are popular. We don't have to recommend for or against them here; the issue is that we cannot give reliably advice for upgrading `pip` that won't break any such tools/workflows.

**Comment by ilayn** [comment]
> Here we don't need to give any advice I think, this is not our install docs page.

`--user` flag is also the advice we give for numpy/scipy installation so it is still inline with the generic workflow. In my opinion, it should be their problem and not ours since pip is _the_ central tool for python.

**Comment by pv** [comment]
I think this will have little impact on windows/osx, since for them you need 3rd party compiler in any case, so generally you always have fairly recent gfortran if you have gfortran. The issue with linux is just the manylinux build environment, whose prebuilt Docker images have old compilers. Maybe possible to upgrade within manylinux1, but not straightforward.

The pip version issue is perhaps a reason to wait until the manylinux2xxxx support is more mainstream.

**Comment by person142** [comment]
Ok, so given the _immediate_ use cases (fixing https://github.com/scipy/scipy/issues/11339 in a neat way, which can also be dealt with in other ways), it sounds like it's worth waiting on Fortran 2003. To be revisited at a later date.

**Comment by h-vetinari** [comment]
> @person142: To be revisited at a later date.

Why close this issue then? There are clearly good reasons to upgrade Fortran compatibility, and this issue could serve as a good reminder/tracker of that.

I also don't think that the manylinux1-issue is really that relevant anymore (as mentioned above already, it's quite trivial to move to manylinux2010, and pip supports that for more than a year already; so do the other installers like venv, virtualenv, poetry).

Perhaps the biggest challenge would be for the conda folks to upgrade gcc from 7 to 8 (across all their build chains), but still, this issue seems eminently within reach, IMO.
