### ISSUE TITLE
Documentation on SHGO inequality constraints appears contradictory

### ISSUE THREAD

**Issue by jjramsey** [scipy/scipy#11428]
In the argument list for `shgo` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.shgo.html) describing **constraints**, it reads as follows:

```
g(x) <= 0 applied as g : R^n -> R^m
```

This would imply that `g(x)` should be non-positive in order to satisfy the constraint. However, the cattle-feed example in the documentation indicates that the functions for the inequality constraints should be non-*negative*, with `g1(x)` and `g2(x)` explicitly indicated as being `>= 0`.

To make things even more confusing, in the same cattle-feed example, the values of `g1(x)` and `g2(x)` at the minimizing value `res.x` are shown to be *negative*, implying that the constraints aren't satisfied.

**Comment by rgommers** [comment]
Thanks for the report @jjramsey. @Stefan-Endres could you please have a look at this one?

**Comment by Stefan-Endres** [comment]
I've made a quick pull request to fix this issue in the documentation.

**Comment by rgommers** [comment]
Thanks!

**Comment by jjramsey** [comment]
I noticed something else in the cattle-feed example. If `iters=3` is *not* used as an argument to `shgo`, then the result is both significantly different *and* satisfies the inequality constraints. Running this:

```python
res_no_min_iters = shgo(f, bounds, constraints=cons)
print(res_no_min_iters)
print((g1(res_no_min_iters.x), g2(res_no_min_iters.x), h1(res_no_min_iters.x)))
```
gets me this:

```
fun: 31.775000000003956
    funl: array([31.775     , 33.64749063])
 message: 'Optimization terminated successfully.'
    nfev: 107
     nit: 2
   nlfev: 95
   nlhev: 0
   nljev: 9
 success: True
       x: array([5.00000000e-01, 1.47838423e-13, 5.00000000e-01, 0.00000000e+00])
      xl: array([[5.00000000e-01, 1.47838423e-13, 5.00000000e-01, 0.00000000e+00],
       [5.00000000e-01, 5.00000000e-01, 8.05522433e-02, 1.19900078e-01]])
(1.700000000000828, 2.1506267357081095, 1.4788170688007085e-13)
```

Technically, the equality constraint is violated, but `h1(res_no_min_iters.x)` is still pretty close to zero. This constraint is actually violated more by the "correct" answer `x_correct = (0.6355216, -0.12e-11, 0.3127019, 0.05177655)`; `h1(x_correct)` is `4.999879998912604e-08`, which may be why the SHGO algorithm preferred a slightly higher value for the objective function (i.e. 31.775 instead of 29.894378.)

**Comment by Stefan-Endres** [comment]
@jjramsey This is normal behaviour since by default shgo only does one iteration if no `iters` or other stopping criteria is specified (see the documentation under the options dict for built in stopping criteria that can be specified depending on your needs). By default the algorithm terminates after the specified number of iterations (`iters` arg) is completed (unless you supply other information to the algorithm a black optimization problem theoretically has no stopping criterion.

More iterations --> higher chance of finding the global optimum at an increased computational cost.

I think this is not well explained in the documentation nor the tutorial since we get a lot of e-mails with similar questions. In literature it is common practice to specify the objective function value at the global minimum, but this is rarely known in practice (for example the true global minimum of an error function is rarely close to zero in many applications) hence the more versatile stopping criteria that you can supply to shgo.

In any case I think it is more appropriate to detail this in a tutorial rather than the documentation so that the latter can remain concise.

With respect to the constraints of the local solver being close to, but not precisely zero: it boils down to a similar question of performance vs. numerical precision, the default local solver [SLSQP](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-slsqp.html) has a maximum number of iterations and tolerance built in. In applications where higher numerical precision is needed this can be increased by the user. The arguments passed to the local solver by shgo can be specified using the ` minimizer_kwargs ` argument to shgo.
