### ISSUE TITLE
Numerical stability of distributions: Add log_p as argument to all distributions?

### ISSUE THREAD

**Issue by Hoeze** [scipy/scipy#11465]
Hi, I got a problem with the numerical stability when quantile-mapping a negative binomial distribution.
Example code:
```python3
def cdf(X, r, mu):
    log_1p = np.log(r) - np.log(mu + r)
    return special.betainc(r, 1. + X, np.exp(log_1p))

stats.norm.ppf(cdf(X, r, mu))
```

Result:
![image](https://user-images.githubusercontent.com/1200058/73658558-d4f2af80-4694-11ea-9aa7-c458a6e81ff6.png)

Even while using `float64`, the numerical precision is not high enough to properly calculate z-scores above ~ 8.

The solution to this problem would (probably) be to add the possibility to provide `log_p` values to the distributions like done in e.g. `R`.

Do you have other ideas how to solve this problem?

**Comment by chrisb83** [comment]
`rv_continuous` has a method `logcdf`:
 https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.logcdf.html#scipy.stats.rv_continuous.logcdf

same for `rv_discrete`, so the functionality is available

```
stats.norm.logcdf(25) # -3.056696706382561e-138
np.log(stats.norm.cdf(25)) # 0.0
```

But it needs to be implemented for each distribution, otherwise the default uses log(cdf) which loses precision.

From your example, I am not sure which distribution you are look at.

**Comment by Hoeze** [comment]
> I guess nbinom, it does not have a specific implementation of logcdf. Do you know if a closed form solution is available?

Yes, exactly. SciPy had a different parametrization than I needed and was not really compatible with xarray, so I applied some algebra and wrote my own negative binomial class:
<details>

```python3
class NegativeBinomial:
    r"""
    Negative binomial distribution.
    This class supports re-parameterising, sampling and calculation of
    probabilities of negative binomial distributed data.
    """

    mean: np.ndarray
    # variance: np.ndarray
    # p: np.ndarray
    r: np.ndarray

    @classmethod
    def mme(cls, data, axis=0):
        r"""
        Fit a Negative Binomial distribution to `data`.
        Uses the closed-form Method-of-Moments to estimate the dispersion.

        :param data: The data
        :param axis: Axis along which the distributions are provided
        :return: `NegativeBinomial` object

        """
        mean = np.mean(data, axis=axis)
        variance = np.mean(np.square(data - mean), axis=axis)

        return cls(mean=mean, variance=variance)

    def __init__(self, r=None, variance=None, p=None, mean=None):
        if r is not None:
            if variance is not None:
                raise ValueError("Must pass either shape 'r' or variance, but not both")

            if p is not None:
                if mean is not None:
                    raise ValueError("Must pass either probs or means, but not both")

                mean = p * r / (1 - p)
                # variance = mean / (1 - p)

            elif mean is not None:
                if p is not None:
                    raise ValueError("Must pass either probs or means, but not both")

                # p = mean / (r + mean)
                # variance = mean + (np.square(mean) / r)

            else:
                raise ValueError("Must pass probs or means")

        elif variance is not None:
            if r is not None:
                raise ValueError("Must pass either shape 'r' or variance, but not both")

            if p is not None:
                if mean is not None:
                    raise ValueError("Must pass either probs or means, but not both")

                mean = variance * (1 - p)
                r = mean * mean / (variance - mean)

            elif mean is not None:
                if p is not None:
                    raise ValueError("Must pass either probs or means, but not both")

                # p = 1 - (mean / variance)
                r = mean * mean / (variance - mean)
            else:
                raise ValueError("Must pass probs or means")
        else:
            raise ValueError("Must pass shape 'r' or variance")

        self.mean = mean
        # self.variance = variance
        # self.p = p
        self.r = r

    @property
    def variance(self):
        return self.mean + (np.square(self.mean) / self.r)

    @property
    def p(self):
        return self.mean / (self.r + self.mean)

    @property
    def log_p(self):
        return np.log(self.mean) - np.log(self.r + self.mean)

    @property
    def log_1p(self):
        return np.log(self.r) - np.log(self.r + self.mean)

    def sample(self, size=None):
        """
        Sample from all distributions data of size `size`.
        :param size: The size
        :return: numpy array containing sampled data
        """
        # numpy uses an alternative parametrization
        # see also https://en.wikipedia.org/wiki/Negative_binomial_distribution#Alternative_formulations
        random_data = np.random.negative_binomial(
            n=self.r,
            p=1 - self.p,
            size=size
        )
        return random_data

    def prob(self, X):
        """
        Calculate the probability of each value in `X` given this distribution
        :param X: The data
        :return: numpy array of probabilitites
        """
        # p = self.p
        # r = self.r
        # return scipy.stats.nbinom(n=r, p=1 - p).pmf(X)
        # return binom(X + r - 1, X) * np.power(p, X) * np.power(1 - p, r)
        return np.exp(self.log_prob(X))

    def log_prob(self, X):
        """
        Calculate the log-probability of each value in `X` given this distribution
        :param X: The data
        :return: numpy array of log-probabilitites
        """
        mu = self.mean
        r = self.r

        # min_p = np.nextafter(0, 1, dtype=self.p.dtype)
        # max_p = np.nextafter(1, 0, dtype=self.p.dtype)
        # log_p = np.fmin(log_p, max_p)
        # log_p = np.fmax(log_p, min_p)

        # broadcasting
        if xr and isinstance(mu, xr.DataArray) and isinstance(r, xr.DataArray) and isinstance(X, xr.DataArray):
            mu, r, X = xr.align(mu, r, X)
        else:
            mu, r, X = np.broadcast_arrays(mu, r, X)

        div = np.log(r + mu)
        log_p = np.log(mu) - div
        log_1p = np.log(r) - div

        # return scipy.stats.nbinom(n=r, p=1 - p).logpmf(X)
        coeff = gammaln(r + X) - gammaln(X + 1) - gammaln(r)
        # return coeff + r * np.log(1 - p) + X * np.log(p)
        return coeff + r * log_1p + X * log_p

    def cdf(self, X):
        r = self.r
        log_1p = self.log_1p

        # broadcasting
        if xr and isinstance(log_1p, xr.DataArray) and isinstance(r, xr.DataArray) and isinstance(X, xr.DataArray):
            log_1p, r, X = xr.align(log_1p, r, X)
        else:
            log_1p, r, X = np.broadcast_arrays(log_1p, r, X)

        return betainc(r, 1. + X, np.exp(log_1p))
```

</details>

However, I was not smart enough to solve betainc for `log_p` parametrization; 
in other words: I have no clue :sweat_smile: 

Though, there seem to be some solutions.
At least one could borrow from R's solution:
https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/nmath/pbeta.c#L69
https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/nmath/toms708.c#L510

**Comment by pv** [comment]
Right, but do you have a bug report or not? This is an issue tracker for bug reports.

**Comment by Hoeze** [comment]
@pv Excuse me please, I should have clarified that.

My feature request contains multiple parts:
1) have the beta-distribution accepting log(x) as input:
`beta(a, b, log_x = log(p))`
2) return log(beta(a, b, log_x)):
`log_q = scipy.stats.logbeta(a, b, log_x=log(p))`
3) have the normal-distribution's PPF accept log(q) as input:
`zscore = scipy.stats.norm.ppf(log_q=log_q)`

**Comment by rgommers** [comment]
>     1. have the beta-distribution accepting log(x) as input

A `log_x` input is odd, I don't understand why you can't use `logpdf(x)` and `logcdf(x)`?

If the numerical precision of those methods is not enough, that needs fixing - but that would be the exact same code you propose to add I'd think.

>     3\. have the normal-distribution's PPF accept log(q) as input:

this seems very ad-hoc. perhaps we could benefit from adding a `logppf` method to all distributions? think of this as something that needs design consistency, not just solving your particular problem

**Comment by Hoeze** [comment]
> > ```
> > 1. have the beta-distribution accepting log(x) as input
> > ```
> 
> A `log_x` input is odd, I don't understand why you can't use `logpdf(x)` and `logcdf(x)`?
> 

`x` is in the range of `[0,1]`, right?

----------
In the end, what I would like to obtain is an equivalent to the following R example:
```R
cdf = pnbinom(mu=10, size=20, q=120, log.p=TRUE)
cdf
[1] -1.24009e-38
zscore = qnorm(cdf, log.p=TRUE)
zscore
[1] 12.94585
```
Currently, doing this with SciPy results in +inf since:
1) scipy negative binomal has no parameterization with `mu`. This could be simply adapted using the NegativeBinomial class I provided above
2) scipy betainc function is not as accurate as the `bratio` version here:
https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/nmath/pnbinom.c#L69-L84
3) the normal-distribution's PPF does not have a `log=True` option

**Comment by mdhaber** [comment]
Hi @Hoeze. Can you provide complete, but minimal (not your whole `NegativeBinomial` class) SciPy code you would use to perform the equivalent of 
```R
cdf = pnbinom(mu=10, size=20, q=120, log.p=TRUE)
```
from R? 

In response to item 1 from your last comment: we avoid re-parameterizations, but we can mention other common parameterizations in the documentation. Please suggest what you would like to be added to the [`nbinom` documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.nbinom.html) about the alternative parameterization, and please provide a reference.

**Comment by mdhaber** [comment]
@Hoeze One thing that might help is that 
```python3
norm.ppf(p) = -norm.ppf(-np.log(p))
```
For values of `p` close to 1.
```python3
-norm.ppf(-1 * -1.24009e-38)
```
produces:
```
12.945845345334703
```
I think it's just an approximation, but it seems to be a very good one.

**Comment by mdhaber** [comment]
@rgommers you wrote:

> >     3\. have the normal-distribution's PPF accept log(q) as input:

> this seems very ad-hoc. perhaps we could benefit from adding a `logppf` method to all distributions? think of this as something that needs design consistency, not just solving your particular problem

Just to be clear, would `logppf` return the log of the `ppf`? That is what the name `logppf` suggests to me, as `logpmf` and `logcdf` return the log of the `pmf` and log of the `cdf`, respectively.

Or do you mean that `logppf` would be the inverse function of `logcdf`, which is what @Hoeze wants to be able to do?

@Hoeze this means that another way to solve #3 of your problem is that since `norm` has a nice `logcdf` implementation, you can do:
```python3
log_p = -1.24009e-38
from scipy.stats import norm
from scipy.optimize import newton
def f(x, log_p):
    return norm.logcdf(x) - log_p
newton(f, args=(log_p,), x0 = 1, maxiter=1000)
```
which prints:
```
12.945845345334702
```

**Comment by mdhaber** [comment]
@Hoeze let me try to summarize, since there is a lot here.

- [ ] "scipy negative binomal has no parameterization with mu. This could be simply adapted using the NegativeBinomial class I provided above"

You want to be able to use a `mu`/`alpha`parameterization of `nbinom`. This is being addressed by improving the documentation of `nbinom`; see gh-13292. We avoid providing alternate parameterizations of existing distributions. If you are interested in improving SciPy distributions, please see [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.html) for information about subclassing `rv_continuous`. There is also some important information [here](http://scipy.github.io/devdocs/dev/contributor/adding_new.html#adding-new).

- [ ] "scipy betainc function is not as accurate as the bratio version here:"

You want a more accurate `betainc` function. I didn't look too closely because that appears to be source code for R. Most R source code is GPL licensed, so we can't refer to it, as SciPy is distributed under a BSD license. 

I'm assuming you mention `betainc` because you are trying to calculate the `cdf` of the `nbinom` distribution, e.g. you wrote:
```R
cdf = pnbinom(mu=10, size=20, q=120, log.p=TRUE)
```
Correct me if I'm wrong, but I don't think what you are really after is a more accurate `betainc` function. You are asking for an implementation of the _log_ of the incomplete beta function. The CDF of `nbinom` with these inputs (that is, `n=size`, `p = size/(size+mu)`) is too close to `1` to be resolved with double precision. That is why you've specified `log.p=TRUE` there, so that R returns the log of the probability, so what you really are asking for is for `nbinom` to have a good `logcdf` implementation, right?

- [ ] "the normal-distribution's PPF does not have a log.p=True option"

More generally, you want a way to calculate the inverse of the `logcdf` method of distributions, right?

- [ ] "have the beta-distribution accepting log(x) as input"

The example:
> beta(a, b, log_x = log(p))

You seem to be asking for a way to provide inputs to the `beta` distribution that are very close to 0 or 1, right?

Depending on how close to 1 you need to go, these might help.

For the PDF, you can use the identity:
`beta.pdf(x, a, b) = beta.pdf(1-x, b, a)`
so that you can provide an argument close to zero instead.

For the CDF:
`beta.cdf(x, a, b) = beta.sf(1-x, b, a)`

I am guessing this will get you a lot closer to what you're asking for since `float`  can represent numbers much closer to zero than to 1. Does this do what you need?

- [ ] "return log(beta(a, b, log_x)):"

There is already a `logpmf` implementation for the `beta` distribution, so I think you are looking for a `logcdf` implementation (of course, one that has a way of accepting arguments that are very nearly 0 or 1).

**Comment by Hoeze** [comment]
Hi @mdhaber, thanks for all your investigation and happy new year :)

> I'm assuming you mention `betainc` because you are trying to calculate the `cdf` of the `nbinom` distribution, e.g. you wrote:
> 
> ```r
> cdf = pnbinom(mu=10, size=20, q=120, log.p=TRUE)
> ```
> 
> Correct me if I'm wrong, but I don't think what you are really after is a more accurate `betainc` function. You are asking for an implementation of the _log_ of the incomplete beta function. The CDF of `nbinom` with these inputs (that is, `n=size`, `p = size/(size+mu)`) is too close to `1` to be resolved with double precision. That is why you've specified `log.p=TRUE` there, so that R returns the log of the probability, so what you really are asking for is for `nbinom` to have a good `logcdf` implementation, right?

Yes, that's exactly what I'm searching for :+1: 

As you noticed, I tried to solve this issue with my own implementation of the negative binomial class that I posted above.
The reason I failed was because betainc was not precise enough for values of `p` close to 1, in contrast to the R implementation:
```python
    def cdf(self, X):
        [...]
        return betainc(r, 1. + X, np.exp(log_1p))
```
----
Now, assuming I do have a correct value of `logcdf(NB(mu, r, X))`:

>     * [ ]  You wrote: "the normal-distribution's PPF does not have a log.p=True option" and "have the normal-distribution's PPF accept log(q) as input:"
> 
> 
> More generally, you want a way to calculate the inverse of the `logcdf` method of distributions, right?

Yes, by passing the `logcdf` of another distribution to the inverse of the standard distribution's logcdf, I can easily obtain z-scores of any distribution.

**Comment by mdhaber** [comment]
>> so what you really are asking for is for `nbinom` to have a good `logcdf` implementation, right?
> Yes, that's exactly what I'm searching for 👍

OK. Since `nbinom.cdf(k, n, p)` is implemented as
```
special.betainc(n, floor(k)+1, p)
``` 
we can use can use the symmetry of `betainc` as described for `beta.cdf` above to implement the `logcdf`:
```
np.log1p(-sc.betainc(np.floor(k + 1), n, 1-p))
```
