### ISSUE TITLE
performance of binned_statistics_2d 100x slowdown from 1.3.2 to 1.4.0

### ISSUE THREAD

**Issue by octavius37** [scipy/scipy#11468]
My issue is about the performance of scipy.stats.binned_statistic_2d going from 1.3.2 to 1.4.0. 

The function performs hugely worse in calculating the std, so much so that we can't use version 1.4.0. I've seen that the calculation has changed because of #10126, and it looks like for good reason, but is there a way we can use the old calculation?

#### Reproducing code example and timeit results:
```
import scipy.stats
import numpy as np

inp = np.random.rand(9999).reshape(3,3333)*200

subbin_x_edges = np.arange(0, 200, dtype=np.float32)
subbin_y_edges = np.arange(0, 200, dtype=np.float64)

%%timeit
stat='std'
binned_stat, _, _, binnumbers = scipy.stats.binned_statistic_2d(
    inp[0], inp[1], values=inp[2], statistic=stat,
    bins=[subbin_x_edges, subbin_y_edges], expand_binnumbers=True)
```

Scipy 1.3.2
```
1.25 ms ± 5.87 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

Scipy 1.4.0
```
122 ms ± 1.98 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

#### Scipy/Numpy/Python version information:
Scipy 1.4.0 
Numpy 1.18.1 
sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)

My system: 
Ubuntu 18.04.3 LTS
Memory: 15.5GiB
Processor: Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8
Graphics: GeForce GTX 1050/PCIe/SSE2
OS type: 64-bit

Have confirmed this issue exists on MacOSX as well.

Thank you for your time
-->

**Comment by rlucas7** [comment]
Hi @octavius37, 
I wrote the PR that slowed down this code. The numpy `std` method is indeed slow.
I had considered a single pass algorithm like [Welford's](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Welford's_online_algorithm) or one of the related single pass methods. Indeed I'd still like to implement Welford, or one of those-either here or numpy. That solution approach would require a bit more effort than using the `np.std` function and I wanted to get something working, favoring correctness over (runtime) speed. If we did use a Welford type approach, it could be done in numpy (if the maintainers over there were open to that) or here in Scipy. If the online approach went into numpy-and was fast enough-then no change would be required here. I'm less familiar with the internals of numpy to be able to comment on which approach is preferred although I'd guess the preference would be to implement an "online" variance calculation here in SciPy rather than numpy. 

I wouldn't recommend using the old way unless you are sure on your end that you will have inputs which are numerically stable, i.e. small mean value relative to variance. I'd guess this is a difficult assumption to be certain of and the only way I know of to check is to do the standard deviation calculations.

The `binned_statistic_dd` function, like many scipy functions will accept a statistic that has a callable here is a simple example using a counting function. 

```
>>> import scipy.stats
>>> import numpy as np

>>> def count(x):
...     flatcount = len(x)
...     return flatcount
... 
>>> callable(count) # returns true
True

>>> scipy.stats.binned_statistic_2d([1, 2, 1, 2, 4], np.arange(5), [1, 2, 1, 2, 4], statistic=count, bins=2)
BinnedStatistic2dResult(statistic=array([[2., 2.],
       [0., 1.]]), x_edge=array([1. , 2.5, 4. ]), y_edge=array([0., 2., 4.]), binnumber=array([ 5,  5,  6,  6, 10]))
>>> scipy.stats.binned_statistic_2d([1, 2, 1, 2, 4], np.arange(5), [1, 2, 1, 2, 4], statistic='count', bins=2)
BinnedStatistic2dResult(statistic=array([[2., 2.],
       [0., 1.]]), x_edge=array([1. , 2.5, 4. ]), y_edge=array([0., 2., 4.]), binnumber=array([ 5,  5,  6,  6, 10]))
``
you can see that both return the same counts. You can write your own function if you like that calculates a standard deviation if you like, however the sum of squares method is not numerically stable so I'd caution the use of that formula. We don't have any good test examples of passing in a callable to these functions either, having a test case would be a good means of illustration of passing in callables. 

We can use this issue as a placeholder for considering an online variance calculation (or an alternate implementation that is faster than numpy's `std` and is also numerically stable.

**Comment by octavius37** [comment]
Hi Lucas,
Thank you for your explanation and the work you've done. I'm going to look into implementing Welford's algorithm and post back here if I make any progress worth having a look at :).

**Comment by octavius37** [comment]
A small update:

Unfortunately we've decided to go back to the pre 1.4.0 version for now. We've checked our input values and they are numerically stable for this implementation. I did try to implement an online algorithm and use that as the statistic callable, however the way the statistic callable works is not compatible with that because it calls the function for every bin and for every value row (from binned_statistic_dd):

```
elif callable(statistic):
    with np.errstate(invalid='ignore'), suppress_warnings() as sup:
            sup.filter(RuntimeWarning)
            try:
                null = statistic([])
            except Exception:
                null = np.nan
        result.fill(null)
        for i in np.unique(binnumbers):
            for vv in xrange(Vdim):
                result[vv, i] = statistic(values[vv, binnumbers == i])
```

It might be worth giving the user the option to calculate the result with the binnumbers and values as input instead of iterating over all bins.
