### ISSUE TITLE
scipy.signal.lfilter on Windows runs on single core

### ISSUE THREAD

**Issue by konradci** [scipy/scipy#11471]
The lfilter method from scipy.signal on Linux (or even Windows Subsystem for Linux)
runs on all cores, implementation on Windows runs on single core only.
This results in great slowdown on Windows 
When run on the same machine:
WLS 3.6.8; 18 cores --> 10.3 [s]
WIN10 3.6.8; 18 cores --> 47.4 [s]
WIN10 3.8.1; 18 cores --> 47.9 [s]

#### Reproducing code example:

```
import time
from numpy import cos, sin, pi, absolute, arange
from scipy.signal import kaiserord, lfilter, firwin, freqz


#------------------------------------------------
# Create a signal for demonstration.
#------------------------------------------------

sample_rate = 24000.0
nsamples = 240000
t = arange(nsamples) / sample_rate
x = cos(2*pi*0.5*t) + 0.2*sin(2*pi*2.5*t+0.1) + \
        0.2*sin(2*pi*15.3*t) + 0.1*sin(2*pi*16.7*t + 0.1) + \
            0.1*sin(2*pi*23.45*t+.8)


#------------------------------------------------
# Create a FIR filter and apply it to x.
#------------------------------------------------

# The Nyquist rate of the signal.
nyq_rate = sample_rate / 2.0

# The desired width of the transition from pass to stop,
# relative to the Nyquist rate.  We'll design the filter
# with a 5 Hz transition width.
width = 5.0/nyq_rate

# The desired attenuation in the stop band, in dB.
ripple_db = 60.0

# Compute the order and Kaiser parameter for the FIR filter.
N, beta = kaiserord(ripple_db, width)

# The cutoff frequency of the filter.
cutoff_hz = 10.0

# Use firwin with a Kaiser window to create a lowpass FIR filter.
taps = firwin(N, cutoff_hz/nyq_rate, window=('kaiser', beta))

# Use lfilter to filter x with the FIR filter.
t0 = time.time()
filtered_x = lfilter(taps, 1.0, x)
tel = time.time() - t0

# print timing info
print('Elapsed time {:5.1f} [s]'.format(tel))
```

#### Error message:

no error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

#### Scipy/Numpy/Python version information:

WSL:      1.4.1 1.18.1 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
WIN10:  1.4.1 1.18.1 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
WIN10:  1.4.1 1.18.1 sys.version_info(major=3, minor=8, micro=1, releaselevel='final', serial=0)

**Comment by ewmoore** [comment]
For FIR filters, `signal.lfilter` ultimately calls `numpy.convolve`.  It looks like your linux numpy installs are not using the built-in code for `convolve`, but are probably calling something from MKL.  Where did you get numpy?

**Comment by ewmoore** [comment]
I'm sorry, I think I may have been mistaken earlier.  `np.convolve` becomes a series of dot products for when both arrays are long enough.  I suspect that you are seeing a difference in the BLAS configuration between your windows installs and your linux installs.  You could look at the output of `np.show_config()` to try and track this down.   

Perhaps someone who knows what the differences in BLAS between pypi numpy windows and linux wheels are can comment.  I know that in the past, windows wheels used ATLAS while the manylinux1 wheels used openblas (as indicated [here](https://numpy.org/doc/1.18/dev/releasing.html#how-to-prepare-a-release)), which would explain what you are seeing.  

If this is the issue, then you'll need to install numpy on windows such that it uses a multithreaded BLAS for convolution.  One option is probably installing via conda rather than pip.

**Comment by konradci** [comment]
Yes, as a matter of fact after installation via conda it works much much better. I'm puzzled by this...
