### ISSUE TITLE
Canonical Docker Image for SciPy in Alpine?

### ISSUE THREAD

**Issue by iMerica** [scipy/scipy#11518]
Hi,

Is there an official/semi-official base image I can use to run Scipy in Alpine? I'm happy to use this as the base image (`e.g. FROM scipy-alpine:python-3.8.1`)

Thank you,

Michael

**Comment by rgommers** [comment]
Hi @iMerica, there's not - we don't maintain any Docker images. For Alpine there's a normal package repo (https://pkgs.alpinelinux.org/packages?name=+%09py3-scipy&branch=edge), and it should be easy to build your own Docker image.

I'll close this, because the question is answered and there's no bug.
