### ISSUE TITLE
Zero-row removal in linprog presolve occurs too early

### ISSUE THREAD

**Issue by janvle** [scipy/scipy#11515]
I'm` porting a Matlab project to Python. An issue I run into is that the presolve routine in _linprog_util.py creates new zero-rows in A_eq after zero-rows have been removed (line 612 in the current source). This results in a warning, not in a failing optimization, but it is still good to avoid. The reference Andersen & Andersen removes zero-rows and zero-columns as a last step. Wouldn't that be better?

Reprocing the warning:
`import numpy`
`import scipy.optimize`

`A_eq = numpy.array([[1,1,0,0],[0,1,1,2]])`
`b_eq = numpy.array([0,2])`
`bounds = [(0,0),(0,0),(0,10),(0,10)]`
`c = numpy.array([1,1,1,1])`

`res = scipy.optimize.linprog(c=c,A_eq=A_eq,b_eq=b_eq,bounds=bounds)`

The first two variables have equal lower and upper bounds, so they are actually fixed. Removing them from A_eq results in a top row with only zeroes. This row is not removed.

Output:
`__main__:12: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.`
`>>> res`
`     con: array([ 0.00000000e+00, -7.21867011e-12])`
`     fun: 1.0000000000042668`
` message: 'Optimization terminated successfully.'`
`     nit: 5`
`   slack: array([], dtype=float64)`
`  status: 0`
` success: True`
`       x: array([0.00000000e+00, 0.00000000e+00, 1.31500834e-12, 1.00000000e+00])`

**Comment by mdhaber** [comment]
The warning is from the redundancy removal routine. It removes the zero rows before running the main algorithm. The warning is incorrect in this case, though. 
Ultimately this will be fixed by running presolve repeatedly until nothing new happens (as the paper also recommends). I don't remember exactly why, but I remember it will take a bit of work to do correctly so it has sat on the back burner for a while. This is extra reason to fix it.
Thanks for bringing it up @janvle !

**Comment by janvle** [comment]
Thanks. If you could point me to the details of this 'bit of work to do correctly', I might be able to contribute.

**Comment by mdhaber** [comment]
Wow, that would be great. Well, as you mention, the Andersen & Andersen paper is the reference, and they suggest running presolve iteratively until nothing changes. I only remember that at the time I was finishing the presolve code, I wasn't super happy with how the structure turned out and I felt that it was not going to be very easy to make it iterative. You are welcome to try!

Two things I think I would (personally) refactor at the same time as making this enhancement:

- I would add the ability for `linprog` to accept `bounds` as a NumPy array (either `n` x 2 or 2 x `n`) while maintaining the option to provide a list of tuples (for backwards compatibility). Regardless, I would immediately convert the bounds to an `n` x 2 array and never change them back to the original format. (I don't remember why, but for some reason I ended up converting to arrays and back to tuples in `_presolve` and then I convert to arrays again  `_postsolve`.)
- I would at least make the name of the `undo` variable more descriptive, but also reconsider whether a list of tuples is really the best data type and whether additional information should be stored in there to make postsolve easier.

Most of the code you'd need to look at is in `_presolve` and `_postsolve` in `_linprog_util.py`, but it looks like `_get_Abc` also uses `undo` and `bounds` a bit. All of the solvers themselves have access to these variables (wrapped up in `postsolve_args`), but I don't think they do much with them other than passing them to `_postsolve` in order to generate an `OptimizeResult` for the callback function or when the algorithm terminates. So I don't think you will need to touch `_linprog_ip.py`, `_linprog_rs.py`, or `_linprog_simplex.py`, and any chances to `_linprog.py` would probably be tiny.

Thanks for taking a look!
