### ISSUE TITLE
No Doc String Shown

### ISSUE THREAD

**Issue by geyang** [scipy/scipy#11578]
I searched briefly for similar issues but could not find any. So here it is:

```python
from scipy import stats

p = stats.binom(...
```

in pyCharm, binom shows no documentation in the pop up except a link to the root of the doc page.

<img width="412" alt="Screenshot 2020-02-23 10 37 57" src="https://user-images.githubusercontent.com/630490/75117688-982d2f00-5628-11ea-9064-04c740ac3cae.png">

**Comment by episodeyang** [comment]
okay it looks like `pmf` also does not have a doc string:

![Screenshot 2020-02-23 19 24 23](https://user-images.githubusercontent.com/630490/75127130-37c2df80-5672-11ea-8739-c7bec299e980.png)

**Comment by episodeyang** [comment]
Not sure how useful this doc string is. It would be really nice if the actual doc string shows, because the context switching cost of using `?` in jupyter is already quite high.

<img width="894" alt="Screenshot 2020-02-25 12 00 45" src="https://user-images.githubusercontent.com/630490/75282881-9f8a3f00-57c6-11ea-9358-73ffb95c01b6.png">

**Comment by mdhaber** [comment]
@geyang Thanks for your patience. It sounds like you want the help for `binom` and its methods to show information specific to `binom`, especially listing the shape parameters particular to this distribution. Is that right? Here are specific responses:

---

>in pyCharm, binom shows no documentation in the pop up except a link to the root of the doc page.

I can't reproduce that in Spyder, but I would agree that the information is not particularly helpful.

![image](https://user-images.githubusercontent.com/6570539/101659526-047ff000-39fb-11eb-860c-5a2033e16b28.png )

> Looks like pmf also does not have a doc string:

As you show, there is _a_ doc string. But if you mean that it does not include enough information about the particular distribution, I would agree.

![image](https://user-images.githubusercontent.com/6570539/101659829-50cb3000-39fb-11eb-973d-7da13e8d7c4b.png)

> It looks like the arguments are specified as positional arguments?

Yes, well, it turns out you _can_ use keyword arguments if you know the name of the parameters, but you have to look at the rendered documentation for that.

![image](https://user-images.githubusercontent.com/6570539/101660207-c2a37980-39fb-11eb-8a1f-634df8fc5815.png)

So you can use them positionally if you know the order, or you can use them as keyords if you know the variable names:

![image](https://user-images.githubusercontent.com/6570539/101660523-2168f300-39fc-11eb-8d26-327e21b266ae.png)

> Not sure how useful this doc string is. 

I'd agree that it's not enough to use the particular distribution.

> It would be really nice if the actual doc string shows, because the context switching cost of using ? in jupyter is already quite high.

I think you mean that:

- You consider the docstring in the image to be the "actual doc string", albeit not very useful
- You want that "actual doc string" to show _in the pop-up_ so you don't have to use `?`. Is that right?

**Comment by geyang** [comment]
Thank you for your reply @mdhaber! The docstrings are not showing up in PyCharm as shown below. I think this might have something to do with how the code acts as an interface as opposed to actual implementation. The test helper method does show in the doc pop up.

<img width="1020" alt="Screen Shot 2020-12-09 at 9 26 16 AM" src="https://user-images.githubusercontent.com/630490/101665259-9db20500-3a01-11eb-8356-52528b4c5d28.png">

<img width="946" alt="Screen Shot 2020-12-09 at 9 26 24 AM" src="https://user-images.githubusercontent.com/630490/101665255-9c80d800-3a01-11eb-8a3f-b9be4f5470d9.png">

> > It would be really nice if the actual doc string shows, because the context switching cost of using ? in jupyter is already quite high.
> I think you mean that:
> - You consider the docstring in the image to be the "actual doc string", albeit not very useful
> - You want that "actual doc string" to show in the pop-up so you don't have to use ?. Is that right?

**Yes! both of these are correct!**

I was not being clear earlier.

Here is a comparison of the "two docstrings" shown in Jupyter vs iPython console: 

<img width="816" alt="Screen Shot 2020-12-09 at 9 36 48 AM" src="https://user-images.githubusercontent.com/630490/101665679-23ce4b80-3a02-11eb-9c76-b6705fd22054.png">

**Comment by mdhaber** [comment]
Do you agree that gh-10328 is essentially the same issue?

**Comment by geyang** [comment]
> Do you agree that [gh-10328](https://github.com/scipy/scipy/issues/10328) is essentially the same issue? 


Oh I did not realize that the `?stats.beta.pdf` docstring is the generic docstring. That actually sounds worse.

These are essentially the same issue.

> It's really not IDE specific; it's more a matter of the fact that the docstrings are for the generic `rv_continuous` class and its methods, right?

Uhm this is where I am confused: it looks IDE specific, because `spyder` does resolve the docstring correctly, according to your example above?

**Comment by mdhaber** [comment]
> it looks IDE-specific because spyder does resolve the docstring correctly, according to your example above?

Oh, OK, you mean that for distribution class docstring (e.g. `binom`), Spyder shows something that pretends to be meaningful:
![image](https://user-images.githubusercontent.com/6570539/101672559-e15d3c80-3a0a-11eb-942a-30bc0f6ee53c.png)

whereas PyCharm is just showing:
![image](https://user-images.githubusercontent.com/6570539/101671854-f08fba80-3a09-11eb-8e45-906171342351.png)

Yes, the actual implementation code is in `binom_gen`, not `binom`, so maybe that is confusing PyCharm. But to be honest, even what Spyder is showing for the `binom` docstring is not actually `binom`-specific; it probably is just dropping the distribution name into something generic.

In any case, I think all of this should be considered together. Maybe we should close this and add to gh-10328 that when we come up with a way to tailor the documentation to the distribution, the solution should be tested on a few IDEs (not just the rendered documentation)?

**Comment by geyang** [comment]
> In any case, I think all of this should be considered together. Maybe we should close this and add to gh-10328 that when we come up with a way to tailor the documentation to the distribution, the solution should be tested on a few IDEs (not just the rendered documentation)?

Thanks, sounds good to me!

**Comment by ilayn** [comment]
Probably we should start looking into custom decorators that shoots for a trade-off between us (maintainers) and for users' convenience. It's a bit too much automation in my opinion. I'd love to have a look at it but so little time so much to do.

**Comment by geyang** [comment]
pytorch and other libraries had similar issues caused by different reasons,
and there are standard ways to specify these doc strings to work with IDE’s
static analysis.

IMO this is more of an oversight, but right, so much to do and so little
time!

Best
