### ISSUE TITLE
gabor filter and PCA whitening in ndimage

### ISSUE THREAD

**Issue by ryanlu41** [scipy/scipy#11583]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add nd Gabor filters and PCA whitening to the current processing functions in ndimage. The gabor filter would allow for more image processing of higher dimensional images, since most implementations are restricted to 2 dimensions.

**Describe alternatives you've considered**

**Additional context (e.g. screenshots)**

**Comment by rgommers** [comment]
Hi @ryanlu41 thanks for this idea. Seems like we missed replying to this, sorry about that. My main question is what's different in the implementation of the PR you just submitted compared to what's in scikit-image ([code](https://github.com/scikit-image/scikit-image/blob/master/skimage/filters/_gabor.py), [doc](https://scikit-image.org/docs/dev/auto_examples/features_detection/plot_gabor.html))? It seems very similar, and while a Gabor filter makes sense to add to the available `ndimage` filters, it would be good to have a reason to add this here instead of telling users to simply use it from scikit-image.

**Comment by rgommers** [comment]
And the same question for PCA whitening - I haven't checked other libraries, what's out there already? E.g. we don't have PCA, scikit-learn does.

**Comment by ryanlu41** [comment]
No worries! Re: first question, the scikit-image PR only works for 2D images, while the implementation that we made can be used for any number of dimensions.

For the second question, I think scikit-learn and Keras have PCA whitening, but after I made the issue, I also felt that it didn't really fit (sorry, I should have updated this issue). I did not include it in my PR

**Comment by rgommers** [comment]
> No worries! Re: first question, the scikit-image PR only works for 2D images, while the implementation that we made can be used for any number of dimensions.

Oh yes, seeing that now. That seems to be in need of generalizing in scikit-image - @jni I thought everything was n-D already? Any opinion on this issue and linked PR?

**Comment by jni** [comment]
> @jni I thought everything was n-D already?

Since I [appointed myself](https://github.com/scikit-image/scikit-image/pull/1038#issuecomment-47189573) Guardian of the Dimensions :crossed_swords: :ice_cube:  at scikit-image 6 years ago, I've tried to make sure (almost) all PRs are nD or at least 3D. But there is plenty of code from before that time that is 2D-only. =) 

We also have a stalled PR at scikit-image/scikit-image#2739 with nD Gabor filters, but this code looks much simpler. If SciPy doesn't want them we do! =) I must admit I know very little about Gabor filters and even less about nD Gabor filters, so I can't quickly comment about the correctness of it.

**Comment by ilayn** [comment]
> If SciPy doesn't want them we do! =)

Not not wanting but your servant humbly thinks that this is more suited to scikit-image your dimensionness.

**Comment by ryanlu41** [comment]
Sounds good! I've done some previous work with converting 3D stuff in scikit-image, I'd be happy to move this PR over there.

**Comment by rgommers** [comment]
That sounds like the right outcome to me as well, so I'll close this.

Thanks for working on this @ryanlu41!
