### ISSUE TITLE
scipy.spatial.cKDTree construction slow for some datasets

### ISSUE THREAD

**Issue by 99991** [scipy/scipy#11595]
Construction of `scipy.spatial.cKDTree` takes `O(n^2)` time instead of `O(n log n)` time on some datasets. In my particular case, I have feature vectors derived from image pixels combined with pixel coordinates.

When running the code below with the attached image (does not happen with all images!), the construction time of `cKDTree` on random feature vectors will barely increase at all, while the running time on the pixel color/coordinate feature vectors will increase dramatically:

![plot](https://user-images.githubusercontent.com/18725165/75335502-e2f9b180-5889-11ea-985d-413484afef9b.png)

sklearn seems to have had [a similar issue](https://github.com/scikit-learn/scikit-learn/pull/11103), maybe they are related.

#### Reproducing code example:

```Python3
import numpy as np, scipy.spatial, time
from PIL import Image

for size in np.int32(np.sqrt(np.linspace(1e4, 1e6))):
    # create some fancy feature vectors
    image = np.array(Image.open('image.png').resize((size, size))) / 255.0
    h, w, d = image.shape
    x = np.arange(w)
    y = np.arange(h)
    x, y = np.meshgrid(x, y)
    feature_vector = np.stack([
        image[:, :, 0].flatten(),
        image[:, :, 1].flatten(),
        image[:, :, 2].flatten(),
        x.flatten() / np.sqrt(w * w + h * h),
        y.flatten() / np.sqrt(w * w + h * h),
    ], axis=1)
    
    # benchmark cKDTree on random feature vectors
    print("\nfeature_vector.shape = ", feature_vector.shape)
    t = time.perf_counter()
    scipy.spatial.cKDTree(np.random.rand(*feature_vector.shape))
    dt = time.perf_counter() - t
    print("random  vectors: %f seconds" % dt)
    
    # benchmark cKDTree on actual feature vectors
    t = time.perf_counter()
    scipy.spatial.cKDTree(feature_vector)
    dt = time.perf_counter() - t
    print("feature vectors: %f seconds" % dt)
```

#### Output
```
[...]

feature_vector.shape =  (454276, 5)
random  vectors: 0.428372 seconds
feature vectors: 68.148406 seconds

[Stopped manually]
```

#### Scipy/Numpy/Python version information:
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

#### Input Image:

![image.png](https://user-images.githubusercontent.com/18725165/75333855-29014600-5887-11ea-9ffd-a2157e138e0a.png)

**Comment by scidam** [comment]
As @99991 mentioned above, this issue is related to the similar one in Scikit-Learn and could be fixed by slightly adapted version of the [solution](https://github.com/scikit-learn/scikit-learn/pull/11103) proposed for Scikit-Learn. I have replaced partial quicksort algorithm (worst complexity O(n^2)) originally used for build KD-trees with the intro-select algorithm (worst complexity O( n log n)) which is a part of the C++ standard library.
These are benchmarks:

1) quicksort-based implementation (original)
![output](https://user-images.githubusercontent.com/1312343/76189364-3541b780-6226-11ea-879e-4a0718563a1b.png)


2) intro-select algorithm
![output](https://user-images.githubusercontent.com/1312343/76189378-3bd02f00-6226-11ea-91da-1fe67b4ba414.png)

**Comment by sturlamolden** [comment]
This is due to balancing of the kd-tree. Set ```balanced_tree=False``` when constructing cKDTree with large datasets. When set to False, the kd-tree will be built using the sliding midpoint rule rather than partial sort. It will slightly impair search performance, but construction will be faster.

**Comment by sturlamolden** [comment]
SciPy did not use ```std::nth_element``` because we had to support a compiler that only had C++98. As it stands noe it is OK to use STL from C++11.
