### ISSUE TITLE
BUG/ENH: distribution.ncf with nc=0 returns nan

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#11660]
I'm trying to compute the power of some hypothesis tests and ncf doesn't work for nc=0

I guess there is a restriction that the noncentrality parameter has to be > 0. 

```
stats.ncf.cdf(0.3, 3, 46, 1e-13), stats.ncf.cdf(0.3, 3, 46, 0), stats.f.cdf(0.3, 3, 46)
(0.17478806588166607, nan, 0.17478806588166626)


stats.ncf.ppf(0.5, 3, 46, 1e-13), stats.ncf.ppf(0.5, 3, 46, 0), stats.f.ppf(0.5, 3, 46)
(0.8004834302870418, nan, 0.8004834302870619)
```

The underlying methods look fine:

```
stats.ncf._cdf(0.3, 3, 46, 1e-13), stats.ncf._cdf(0.3, 3, 46, 0), stats.f._cdf(0.3, 3, 46)
(0.17478806588166607, 0.17478806588166607, 0.17478806588166626)

stats.ncf._ppf(0.5, 3, 46, 1e-13), stats.ncf._ppf(0.5, 3, 46, 0), stats.f._ppf(0.5, 3, 46)
(0.8004834302870418, 0.8004834302870418, 0.8004834302870619)

import scipy
scipy.__version__
'1.3.0'
```

**Comment by WarrenWeckesser** [comment]
Let's call it a bug.  It seems reasonable to expect the distribution to return correct values for the edge case when the edge case is well-defined.

**Comment by scidam** [comment]
> I guess there is a restriction that the noncentrality parameter has to be > 0.

This is because [ncf_gen](https://github.com/scidam/scipy/blob/bb3d45051604c2969754862f7416bbd3a151c7d0/scipy/stats/_continuous_distns.py#L5731) class doesn't override ` _argchecks` method (otherwise `rv_continous._argchecks` is used and it checks if all args are positive. It should be overridden as it is done for, e.g., [non-central chi2](https://github.com/scidam/scipy/blob/bb3d45051604c2969754862f7416bbd3a151c7d0/scipy/stats/_continuous_distns.py#L5696). 

To fix it, just append to `ncf_gen`:

    def _argcheck(self, df1, df2, nc):
        return (df1 > 0) & (df2 > 0) & (nc >= 0)

**Comment by WarrenWeckesser** [comment]
@scidam, if you are interested in working on this, a pull request would be welcome!

It would need a unit test two or two to check that a PDF or CDF value computed with nc = 0 agreed with the F distribution.
