### ISSUE TITLE
Speed up scipy functions performance using multi_processing/multi_threading

### ISSUE THREAD

**Issue by EverLookNeverSee** [scipy/scipy#11681]
I have an idea about speed up functions performance (cpu bound) using either multiprocessing or multi-threading.
According to the conversations i had with @rgommers , providing support for multiprocessing with scipy functions can be done. for example [differential_evolution (using `workers` keyword)](https://github.com/scipy/scipy/blob/13cf23a09d88dfee81f8df6e79b194aa762c32cf/scipy/optimize/_differentialevolution.py#L22)
It would be nice if we can build a multiprocessor system that can generate parallelized instance of functions.

Thoughts?

**Comment by rgommers** [comment]
@EverLookNeverSee the description of this issue is too vague to be useful I'm afraid. 

We have already agreed on the `workers` pattern, and if you look into it you'll see that the machinery for it is reusable. So for functions where it makes sense, e.g. other functions in `optimize`, you can make a concrete proposal for doing that and start implementing. gh-9428 (for `optimize.brute`) is an example you can follow.

**Comment by EverLookNeverSee** [comment]
@rgommers I have no problem with **workers pattern** or **process pools** , i.e. functions that we can subdivide their parameters into workers.
I meant functions that we can not apply techniques above on their parameters such as [khatri_rao matrix product](https://github.com/scipy/scipy/blob/13cf23a09d88dfee81f8df6e79b194aa762c32cf/scipy/linalg/matfuncs.py#L672) in which parameters are two arrays.

**Comment by rgommers** [comment]
For something like `khatri_rao` there's nothing to parallelize at the SciPy level, all it is is a few numpy calls.

**Comment by EverLookNeverSee** [comment]
Thanks @rgommers for your valuable tips.

**Comment by rgommers** [comment]
I'll close this, since there's no specific issue, we'll put the general "we'd like performance improvements" on the roadmap.
