### ISSUE TITLE
solve_ivp fails to solve with non-zero initial time, large parameters, and methods other than LSODA

### ISSUE THREAD

**Issue by breedlun** [scipy/scipy#11698]
As the title says, `scipy.integrate.solve_ivp` fail to solve with a non-zero initial time, large parameters, and methods other than LSODA.  Remove any one of those conditions and it solves.

Here is an ODE that demonstrates the problem.
```
import numpy as np
import scipy.integrate

c_0 = np.array([1.0e6])

def ode(t, y):
    c = y[0]
    cdot = C / c
    RHS = np.array([cdot])
    return(RHS)
```
Attempting to integrate from a non-zero initial time fails to solve.  For example,
```
C = 1e50
t_span = (1.0, 2.0)
ivp_sol = scipy.integrate.solve_ivp(ode, t_span, c_0, method = 'Radau')
print(ivp_sol.message)
```
prints the following to the screen
```
Required step size is less than spacing between numbers.
```
Attempting to integrate from a zero initial time or with a smaller value of `C` runs fine.  For example,
```
C = 1e50
t_span = (0.0, 2.0)
ivp_sol = scipy.integrate.solve_ivp(ode, t_span, c_0, method = 'Radau')
print(ivp_sol.message)

C = 1e25
t_span = (1.0, 2.0)
ivp_sol = scipy.integrate.solve_ivp(ode, t_span, c_0, method = 'Radau')
print(ivp_sol.message)
```
prints the following to the screen
```
The solver successfully reached the end of the integration interval.
The solver successfully reached the end of the integration interval.
```
This problem seems to involve all methods, except for LSODA, although LSODA still complains about small step sizes.  Running 
```
C = 1e50
t_span = (1.0, 2.0)
ivp_sol = scipy.integrate.solve_ivp(ode, t_span, c_0, method = 'LSODA')
print(ivp_sol.message)
```
results in several warnings like
```
lsoda--  warning..internal t (=r1) and h (=r2) are��
       such that in the machine, t + h = t on the next step  
       (h = step size). solver will continue anyway��
      in above,  r1 =  0.1000000000000D+01   r2 =  0.3162277663331D-39
```
but it completes with
```
The solver successfully reached the end of the integration interval.
```
It’s not surprising that some methods might work better than others for stiff problems, but it should not matter if the initial time is zero or not.

Here are my version numbers.
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```
produces
```
('1.2.1', '1.16.4', sys.version_info(major=2, minor=7, micro=16, releaselevel='final', serial=0))
```

**Comment by laurent90git** [comment]
Hi,
I think this the expected behaviour. In your case, you are solving:
dy/dt = C/y,
whose analytical solution is y = sqrt( y0^2 + 2*C*(t-t0) ).
You have set C so high that the system explodes with respect to the numerical accuracy achievable with double precision.
The eigenvalue of your system is the derivative of C/y with respect to y, which reads -C/y^2, which will be enormous while evolving nonlinearly with y ! The starting transient is very abrupt !

The error estimation used to adapt the step size will therefore always find a high value for the error estimate, each time lowering the time step until, at one point, the time steps is less than 1e-16*t, i.e. it would lead to t+dt=t at machine accuracy...
Scipy native solvers have been implemented such that they raise an error when this happens.
LSODA is able to pursue the integration, however still gives you a warning that the computed solution may not make any sense.

Why this this happen for t0=1 and not for t0=0 ? Well 0+dt=dt, so the solver never detects an issue with machine accuracy and manages to integrate everything up to the final desired time, but by then the solution evolves much more slowly.
If you start from t0=1, then the solver finds that, to achieve a precise enough solution, it must use dt<1e-16, therefore causing the issue mentionned previsouly.

There is no real remedy in this, I am afraid. The only idea I have would be to use an L-stable method like Radau (which relaxes the fast transient easily), but with a L-stable error estimate. This is the case in Hairer's Fortran Radau5, but it may not be the case in Scipy's implementation of Radau.

**Comment by breedlun** [comment]
@laurent90git, I appreciate your thorough reply.  

Yes, I realize this is a very stiff problem when y is close to zero, but that is the initial value problem I need to solve for my application.

Thank you for pointing out that t+dt=t when abs(t)>epsilon, where epsilon is machine precision, yet t+dt=dt when t=0.  I had not thought of it that way before.  

You said there is no remedy for this issue, but I have had success with integrating starting at an initial time of zero and then adding back the non-zero initial time to the solution afterwards.  The following code 
```
import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

C = 1e30
def ode(t, y):
    return C / y
y0 = np.array([1.0e6])

ti = 10.0 # initial time
tf = ti + 1.0 #final time

#Numerical solution
sol = solve_ivp(fun=ode, t_span=(ti-ti, tf-ti), y0=y0, rtol=1e-3, atol=1e-3,
                method='Radau', vectorized=True)
print(sol.message)
t = sol.t + ti

#Analytical solution
y_a = np.sqrt( y0**2.0 + 2 * C * (sol.t) )

fig, ax = plt.subplots(2,1,sharex=True, dpi=300)
ax[0].plot(t, sol.y[0,:], marker='.', label = 'numerical soln')
ax[0].plot(t, y_a, marker='.', label = 'analytical soln')
ax[0].grid()
ax[0].set_ylabel('y')
ax[0].legend()
ax[1].grid()
ax[1].set_ylabel('relative error')
ax[-1].set_xlabel('t (s)')
ax[1].plot(t, np.abs(sol.y[0,:] - y_a) / y_a, marker='.', linestyle='')
```
produces the following plot
![scipy_integrate_issue_fig1](https://user-images.githubusercontent.com/4099759/98488537-13e70000-21e7-11eb-9e34-82400029c75e.png)
which shows the relative error is acceptably small.  This approach is fine for my application, but I suppose it is not general enough to warrant incorporating some variant of this approach into scipy.integrate.solve_ivp().
