### ISSUE TITLE
Unexpected return from poch when evaluating limit

### ISSUE THREAD

**Issue by jacksonvanover** [scipy/scipy#11717]
When evaluating the limit approaching negative infinity for z>0, `poch` consistently returns `-0.0`. I'm not entirely certain what the appropriate return is in this case, but 0 is certainly unexpected. Based on the definition in terms of the gamma function, I'd guess that the limit  approaches negative infinity, though mpmath and GSL don't support such an operation. They return NaN and throw an exception respectively.

#### Reproducing code example:

```
>>> for i in range(10):
...     print(special.poch(i,np.NINF))
... 
0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
>>> for i in range(10):
...     print(mpmath.rf(i,np.NINF))
... 
0.0
nan
nan
nan
nan
nan
nan
nan
nan
nan
```

#### Scipy/Numpy/Python version information:
```
1.4.1 1.17.4 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
If $-\infty$ were an integer, it sounds like `inf` would be the appropriate result. But if the argument is not an integer, the gamma function approaches zero for large magnitude negative arguments. In fact, Wolfram Alpha (and Mathematica, [apparently](https://math.stackexchange.com/questions/3932511/why-do-mathematica-and-wolframalpha-say-gamma-infty-0)) give
```math
\lim_{n \rightarrow -\infty}(n) = 0
```
which would make SciPy correct here, if we don't mind the negative sign. 

There have been discussions about whether `np.inf` should be considered to be an integer on the basis that all floats of sufficiently large magnitude are integers, but that is definitely not universal. 

I know there is a plan to open a meta-issue about special function edge cases at some point, so this will be reconsidered then. In the meantime, I think it's safe to close since it's been several years without reaction or comment to the original post, but feel free to re-open if this is a particularly important edge case @steppi.
