### ISSUE TITLE
Option to set jac=True in `optimize.least_squares` (mirror `optimize.minimize` behavior)

### ISSUE THREAD

**Issue by tinosulzer** [scipy/scipy#11779]
`optimize.minimize` has the option of setting `jac=True`: "If jac is a Boolean and is True, fun is assumed to return the gradient along with the objective function"

There doesn't seem to be an equivalent in `optimize.least_squares`. Could this be added? If not, is the recommended approach just to create two separate functions, one which returns the value and the other the jacobian?

**Comment by nmayorov** [comment]
This option is absent, because the function may be evaluated several times per iterations, whereas the Jacobian only once. Thus it's probably better to separate function and Jacobian evaluation.

I think it's not a big problem to separate evaluations and it might save computation time (but I understand it's not always the case).

Can I close this?

**Comment by nmayorov** [comment]
Closing this. Feel free to repoen.
