### ISSUE TITLE
ENH: stats: more analytical formulas for fitting distributions to data

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#11782]
In the [CZI Proposal](https://warrenweckesser.github.io/czi/scipy-2019-czi-proposal-revised.pdf), we wrote:

> The continuous distributions in SciPy all have a method for fitting the distribution to data using
the method of maximum likelihood estimation (MLE). The proposed enhancements are:
> * Where possible, use an analytical formula rather than numerical optimization for greater
speed and accuracy
...

This is part of our effort to address the [roadmap item](https://docs.scipy.org/doc/scipy/reference/roadmap.html#statistics-enhancements) "Improve the options for fitting a probability distribution to data".

One of the best sources I've found (via a [NIST Engineering Statistics Handbook](https://www.itl.nist.gov/div898/handbook/eda/section3/eda366.htm)) is the Parameter Estimation sections from:
[Evans, Hastings, and Peacock (2000), _Statistical Distributions_, 3rd. Ed., John Wiley and Sons.](http://personalpages.to.infn.it/~zaninett/pdf/statistical-distributions.pdf)

Any other sources that are easily accessible?

Also, for method of moments (gh-11695), I could write a program that tries to solve for fitting formulas (from the formulas for the moments) using SymPy.  I don't think that would work as well for MLE, though. Might not even get anything new for MM.

Given the formulas, this should be pretty straightforward work: just override the `fit` methods of the distributions defined in  `/scipy/stats/_continuous_distns.py`, following existing examples (e.g. `beta_gen`) for extending documentation and any other conventions. For tests, I suppose we could mainly compare against the generic implementation. In cases where the generic implementation isn't working very well, we could check the partial derivatives of the likelihood function?

If you have any thoughts / words of wisdom before we get started, please let us know here.

@fletcheaston @swallan I think this is next.

_Update:_
@swallan @WarrenWeckesser A simple but really useful script for generating first-order conditions is [here](https://gist.github.com/mdhaber/1861b0c967e315e0830b347e988b3a27). Now it can (sometimes) solve for a variable in terms of the rest.

|  **Continuous distributions** | **Current status of fit override** | **Page Number of MLE (Evans)** |
| :---: | :--- | ---: |
|  laplace | merged: gh-11988, good | 124 |
|  rayleigh | merged: gh-12097, gh-17090, good | 175 |
|  logistic | merged: gh-12738, gh-17117, gh-18177, almost good, but should use `root_scalar` | 130 |
|  pareto | merged gh-15567, good | 149 |
|  invgauss, wald | merged: gh-12514, further investigation needed| 121 |
|  gumbel_r, gumbel_l | merged: gh-12737, good | 101 |
|  powerlaw | merged: gh-13053, good | 159 |
|  nakagami | see gh-10908| - |
|  vonmises | merged: gh-17585, gh-18013, gh-18128. Almost good; see gh-18128. | 192 |
|  weibull_min, weibull_max | see gh-11806 | 196 |
| asymmetric laplace | awaiting PR | [notes](https://www.dropbox.com/s/4tyrqjr6708yhh1/MLE%20-%20Asymmetric%20Laplace.pdf?dl=0) |
| genextreme | see gh-10446 | - | 

Other distributions that have overridden `fit` method:
`norm` - looks good, nothing to do here
`beta` - investigate fitting `loc` and `scale`? Adjust inequality conditions for `FitDataError`.
`expon` - works perfectly, AFAICT
`weibull_min` - should implement analytical solution when `loc` is fixed
`gamma` - look into fitting when `loc` is not fixed. Adjust inequality conditions for `FitDataError`.
`lognorm` - merged: gh-16839; works quite well. I'd rather not work on it more, but others are welcome to.
`uniform` - works perfectly, AFAICT

**Comment by swallan** [comment]
@mdhaber Some of the Parameter Estimation sections from _Evans, Hastings, and Peacock (2000), Statistical Distributions_  say that the parameters are the solutions to a system of equations. 

For example, in the Logistics Distributions (Section 28.3): 
<a href="https://imgbb.com/"><img src="https://i.ibb.co/KNHy3nt/Screen-Shot-2020-04-22-at-4-04-47-PM.png" alt="Screen-Shot-2020-04-22-at-4-04-47-PM" border="0"></a>

Should I only pay attention to sections that provide explicit formulas to derive the shape/location parameters, or is there a way to solve this type of system?

**Comment by mdhaber** [comment]
Take note of those. It can be easier to solve a system than the original optimization problem.

**Comment by swallan** [comment]
There are several distributions already in SciPy that could have MLE fit methods added based on the documentation from the Evans, Hastings, and Peacock textbook:  
[scipy stats.xlsx](https://github.com/scipy/scipy/files/4646752/scipy.stats.xlsx)
Sorry if a excel file is not ideal to upload for this, it didn't look easy to format it as a table for markdown.

I didn't see a ton of use of the term "method of moments" so I haven't fully documented other methods of estimation yet.

**Comment by rlucas7** [comment]
Hi Sam, 
Thanks for putting this together. 

Fwiw MLE tends to be favored by statistics community for various reasons so you’ll see them more commonly mentioned. 

For MLE sometimes you can get an estimator via EM as well. You can find one if your distribution can be represented as a mixture, either continuous or discrete. 

Here is explanation I wrote recently about this: 

https://stats.stackexchange.com/a/466873

In the case you can find such a representation, you can also use as a means of efficient r.v. Generation, simulate mixture rv then simulate next rv in your graph with first rv places as the value, repeat for each draw. 

So if your documenting and find a mixture relationship, you’ve probably found two uses. 

Sincerely, 

-Lucas Roberts

**Comment by grlee77** [comment]
> Sorry if a excel file is not ideal to upload for this, it didn't look easy to format it as a table for markdown.

That seems fine, but for potential future use [recent releases of Pandas can export tables in Markdown](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_markdown.html)

**Comment by swallan** [comment]
> for potential future use [recent releases of Pandas can export tables in Markdown](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_markdown.html)

Thanks for the tip, @grlee77

**Comment by swallan** [comment]
We may keep track of the progress of this issue with this list of pull requests:
|  Continuous distributions                                   | Current status of fit override   |   Page Number of MLE (Evans) | other notes                        |
|-----------------------------------------------------------|:---------------------------------|-----------------------------:|:-----------------------------------|
|  laplace                                                    | #11988                           |                          124 |                                 |
|  rayleigh                                                   | #12097                           |                          175 |                                 |
|  genlogistic                                                |                               |                          130 |                                 |
|  pareto                                                     |                               |                          149 |                                 |
|  powerlaw                                                   |                               |                          159 | has matching moments               |
|   vonmises                                                   |                               |                          192 |                                 |
|                                                           |                               |                           |                                 |
|   **Will Require Further Investigation to Cnsure Compatability** |                               |                           |                                 |
|   gumbel_l                                                   |                               |                          101 | related to genextreme and gumbel_r |
| genextreme                                                 |                               |                          101 |                                 |
| gumbel_r                                                   |                               |                          101 |                                 |
| invgauss                                                   |                               |                          121 | related to wald                    |
| wald                                                       |                               |                          121 |                                 |
| weibull_max                                                |                               |                          196 | related to weibull min             |
|  weibull_min                                                |                               |                          196 |                                 |

I still need to look into how these related but distinct distributions will work with the definitions found in the text.

**Comment by mdhaber** [comment]
Thanks, Sam!

**Comment by huard** [comment]
Don't know if this is in scope, but L-moments parameters estimates are[ often more robust to outliers](https://doi.org/10.1111/j.2517-6161.1990.tb01775.x), especially for extreme value distributions. There is an existing implementation in the [`lmoments3`](https://github.com/OpenHydrology/lmoments3) package, but it does not seem to be maintained anymore. Having this functionality in scipy would be great and a lot of people in the hydrological sciences would be grateful. 

Note that [fortran code is available](http://ftp.uni-bayreuth.de/math/statlib/general/lmoments) and googling turns up a couple of wrappers.

**Comment by WarrenWeckesser** [comment]
@huard, L-moments would be a great addition.  We considered including this in our CZI proposal, but we already had enough to do without it.

**Comment by monocongo** [comment]
Here is a module for [L-moments](https://github.com/monocongo/climate_indices/blob/master/src/climate_indices/lmoments.py)

**Comment by swallan** [comment]
There are several distributions in SciPy whose PDFs match that of the Evans textbook, but the given maximum likelihood estimates do not provide a good guess based on my observation and comparison with log-likelihood calculations.


`scipy.stats.powerlaw`
![Screen Shot 2020-07-13 at 10 35 31 PM](https://user-images.githubusercontent.com/44255917/87388188-2b73ec00-c559-11ea-9938-07110d185eea.png)

This is the MLE given for shape `c` in the textbook (`a` in scipy.)
<img width="269" alt="Screen Shot 2020-07-13 at 10 35 56 PM" src="https://user-images.githubusercontent.com/44255917/87388215-39c20800-c559-11ea-96d7-11d357fa89eb.png">

```
import numpy as np
from scipy.stats import powerlaw

data = powerlaw.rvs(a=1.5, scale=3, size=10000)

a = len(data) / (np.sum(np.log(data)))


args = [data, (powerlaw._fitstart(data), )]
func = powerlaw._reduce_func(args, {})[1]

mle = powerlaw.fit(data, fa=a)
opt = powerlaw.fit(data)

print(a)
print(opt)
print(func(opt, data) - func(mle, data))
```
results in 

=> `2.2951735969907996`
=> `(1.4981329611989254, 0.007238375787595926, 2.9926593757680857)`
=> `-433.6743531238026`


Negative difference of the log likelihood indicates that it is not a good fit, which makes sense since the shape `a` that was created with the MLE is not close to the expected `a`, 1.5. 


`scipy.stats.vonmises`
<img width="526" alt="Screen Shot 2020-07-13 at 10 54 02 PM" src="https://user-images.githubusercontent.com/44255917/87389537-bfdf4e00-c55b-11ea-8d3c-14ba881f79e4.png">

And we are given the MLE for the location, `a`:
<img width="633" alt="Screen Shot 2020-07-13 at 10 53 01 PM" src="https://user-images.githubusercontent.com/44255917/87389446-9d4d3500-c55b-11ea-88e9-868d8950c4b5.png">

However this estimate is much worse than the default optimizer:
```
import numpy as np
from scipy.stats import vonmises

data = vonmises.rvs(kappa=2, loc=2, scale=1, size=100)

a = np.arctan(
    np.sum(np.sin(data)) /
    np.sum(np.cos(data))
    )

mle = vonmises.fit(data, floc=a)
opt = vonmises.fit(data)

args = [data, (vonmises._fitstart(data), )]
func = vonmises._reduce_func(args, {})[1]

print(mle)
print(opt)
print(func(opt,data) - (func(mle, data)))
```
=>
```
(0.7097792398327256, -1.21691026300755, 0.47757754771381733)
(1.517470770406523, 2.145220714568419, 1.376472083641273e-35)
-7883.697993409623
```
The data was created with a `loc` of 2, but a is `-1.2169...`.

**Comment by mdhaber** [comment]
@swallan I wrote some code to help derive the first-order conditions for MLE. 

I plugged in the pdf of the powerlaw distribution using the notation in the book and get this output:
![image](https://user-images.githubusercontent.com/6570539/97269021-152d2b80-17ea-11eb-812c-f507ebd3c760.png)

Those derivatives equal zero at critical points. Solving the second one for c, I see two omissions in the formula given by the book.
- there should be a negative sign
- x_i needs to be divided by b

Here's an update to your code:
```
import numpy as np
from scipy.stats import powerlaw

np.random.seed(12)
scale  =3
data = powerlaw.rvs(a=1.5, scale=3, size=10000)

a = -len(data) / (np.sum(np.log(data/scale)))


args = [data, (powerlaw._fitstart(data), )]
func = powerlaw._reduce_func(args, {})[1]

mle = powerlaw.fit(data, fa=a)
opt = powerlaw.fit(data)

print(a)
print(opt)
print(func(opt, data) - func(mle, data))
```
prints
```
1.505896207715652
(1.7277164581361997, -0.1642901635441375, 3.1642133311355245)
94.20666782387707
```
Usually the default fit method gets a better objective, actually, but at least the value of a is always close to what it should be.

**Comment by mdhaber** [comment]
For von Mises, there's nothing wrong with the formula. You just needed to use arctan2.
```
import numpy as np
from scipy.stats import vonmises

np.random.seed(9)
data = vonmises.rvs(kappa=2, loc=2, scale=1, size=100)

a = np.arctan2(
    np.sum(np.sin(data)),
    np.sum(np.cos(data))
    )

mle = vonmises.fit(data, floc=a)
opt = vonmises.fit(data)

args = [data, (vonmises._fitstart(data), )]
func = vonmises._reduce_func(args, {})[1]

print(mle)
print(opt)
print(func(opt,data) - (func(mle, data)))
```
prints:
```
(1.4209176118306086, 2.0857610265575404, 3.976067874882936e-31)
(1.733333333170029, 1.835804809404621, 3.779079569992055e-30)
215.89894443765752
```
Again, the fit is not always better, but the parameters are always reasonably close to what they should be.

**Comment by mdhaber** [comment]
@swallan note that in the code snippets above, I fixed the parameters at the values used to generate the random variates. e.g.
```
scale = 3
loc = 2
data = powerlaw.rvs(a=1.5, scale=scale, loc=loc, size=10000)

# I didn't change loc or scale after generating the data
# I'm using them as my fixed values to calculate the shape
a = -len(data) / (np.sum(np.log((data-loc)/scale)))
```

The formulae are still valid even if loc and scale are fixed at different values. E.g. if I do 
```
...
scale = 4
loc = 1.3
a = -len(data) / (np.sum(np.log((data-loc)/scale)))
...
```
then I get the output
```
[1.8648278776216605, 1.3, 4]
(1.8648437500000021, 1.3, 4)
3.622226358857006e-07
```

You might notice then that for some values:
```
scale = 3.1
loc = 1.6
a = -len(data) / (np.sum(np.log((data-loc)/scale)))
```
you get output that suggests that the analytical solution is not as good as the numerically optimized one:
```
[2.30702272670952, 1.6, 3.1]
(1.9406250000000023, 1.6, 3.1)
-135.47177179157734  # objective function for analytical solution is worse?
```
This happens because the first-order conditions on the MLE are derived without considering the domain of the distribution's PDF, and they can return MLE parameters that would cause the data to be out of the domain. Strictly speaking, the analytical MLE parameters do maximize the log-likelihood function of the distribution, but SciPy's `_reduce_func` is only equal to the log-likelihood function when the data is inside the domain. `_reduce_func` introduces a penalty when the parameters are such that data is outside the domain.

We already ran into this sort of thing with one distribution, right? Do you remember which it was?

**Comment by mdhaber** [comment]
@swallan for powerlaw:
```
np.random.seed(1)
a = 5
s = 15
u = 3.5
data = powerlaw.rvs(a=a, scale=s, loc=u, size=10000)

a, u2, s2 = powerlaw.fit(data, fa=a)
print("Default fit errors: ", u2-u, s2-s)


def f(u):
    N = len(data)
    s = np.max(data)-u
    res = (a-1)*np.sum(1/(u-data))+N*a/s
    return res


u_min = -1000  # I'm still trying to figure out a theoretical lower bound
u_max = np.min(data) - 0.0000001  # epsilon less than np.min(data)
u3 = root_scalar(f, bracket=[u_min, u_max]).root
s3 = np.max(data) - u3

print("Custom fit errors: ", u3-u, s3-s)
```

**Comment by WarrenWeckesser** [comment]
I added some notes about MLE for the power law distribution to [mlenotes.html](https://warrenweckesser.github.io/notes/mlenotes.html).  Some of the notes reiterate @mdhaber's comments from above.  Earlier, @mdhaber said

> I think it means you really need to fix the scale to get a maximum likelihood estimate

I think something like this is necessary, but I think it is the location that should be required to be fixed.  This set of requirements should always have a well-defined result:


* The location *must* be fixed, and the given location must be strictly less than `min(x)`.

* If the `scale` is not fixed, the MLE for `scale` is

      scale = max(x) - loc

  @mdhaber said this above, and I also make the argument for this in my notes.

  (If the `scale` *is* fixed, we require `scale >= max(x) - loc`.  Otherwise there is a data point that is not in the support of the distribution.)

* If the shape `a` is not fixed, it is given by formula shown above in @mdhaber's sympy calculations (and in the notes that I put online).

**Comment by mdhaber** [comment]
@WarrenWeckesser some of this is in my code above. I no longer think that the location or scale must be fixed; the optima seem well defined based on the support of the distribution. I haven't written up the notes formally, but the code above efficiently calculates both the optimal scale and location given the shape. Since I already worked it out, I think we should talk before you spend too much time on it.

**Comment by swallan** [comment]
Thanks @WarrenWeckesser @mdhaber, I've had a busy week but will be adding this soon.

**Comment by WarrenWeckesser** [comment]
I've gone through the power law equations again.  Below are some notes about the issues that come up, but first I should note two things:

1. The shape parameter `a` is only required to be positive; it can be less than 1.  There is a plot in Forbes, et al, that shows the PDF for the shape being 0.5.  I only point this out because in one of our in-person conversations, I recall saying (or at least thinking) that the parameter was restricted to being greater than 1; that was not correct.  This introduces a complication, because in the three cases `0 < a < 1`, `a == 1` and `a > 1`, the PDFs are qualitatively very different.
2. @mdhaber's comments about the domain of the MLE optimization problem are important.  The support of the distribution is `loc < x <= loc + scale`, and we require that the provided data be in the support, which imposes boundary constraints on the parameters.

   (Just like many other distributions, if the user provides fixed parameters that constrain the support, and also provides data that is outside the support, `fit` must raise a `FitDataError`, because the user is asking for an impossible calculation.)

   So we know the following:
   * `loc` cannot exceed `min(data)`.
   * `loc + scale` cannot be less than `max(data)`.
   * Those conditions impy that the absolute smallest that `scale` can be is `max(data) - min(data)`, which  can only occur if `loc = min(data)`.

   These conditions are boundaries for the optimization problem.  We've seen earlier that the first order conditions lead to some strange conditions, but in general, using the first order conditions for an optimization problem is only valid in the interior of the domain.  One has to consider the boundary separately.

I mentioned [these notes](https://warrenweckesser.github.io/notes/mlenotes.html) before; I've updated them recently.  Only look at those notes for the nicely rendered expressions for the likelihood and log-likelihood functions at the top of the document; ignore the rest of the what I wrote there.  (In those notes,  I use `a` for the shape, μ for the location, and σ for the scale.)  

Suppose all three parameters are free.  In the likelihood function, the scale only shows up in the denominator.  If all the other terms in the likelihood function are finite and nonzero, we can make the likelihood larger by making the scale smaller.  For the MLE, we make the scale as small as possible, which is `max(data) - min(data)`.  That implies that the location must equal the minimum of the data, `loc = min(data)`.  This is a problem, because this is exactly the case where the terms in the big product in the likelihood function are not finite and nonzero.

Suppose `loc = min(data)`.  If `a > 1`, the PDF at `x = min(data)` is then 0.  In other words, trying to set `loc = min(data)` removes the `x` value `min(data)` from the support, and forces the likelihood function to be identically zero.  This breaks an assumption of MLE that the PDF of each data point is nonzero.  If `0 < a < 1`, the term `(min(x) - loc)**(a - 1)` in the likelihood function results in division by zero, so the PDF is not defined there.  (If we try to pretend that infinity is simply a very big number and we allow `loc = min(data)` as the estimate, then the shape parameter `a` is left undetermined, since any value of `a > 0` still gives an infinite likelihood function.)

To ensure that the MLE problem is well-defined, we could impose the constraint that `loc` *must* be fixed, and the fixed value must be strictly less than `min(data)`.  Then the problem is well-defined.

Does fixing a different parameter result in a well-defined MLE problem?  Fixing just the shape does not, because the argument above still applies.

What if just the scale is fixed, with `scale > max(data) - min(data)`?  Then the MLE for the location depends on whether `0 < a < 1` or `a > 1` (and we don't know which case holds a priori):
* If `0 < a < 1`, we maximize the likelihood by making the location as large as possible, so `loc = min(data)`--but this results in the same problem described above.
* If `a > 1`, we maximize the likelihood by making the location as small as possible, so `loc = max(data) - scale`.   This gives a solution, but we had to know `a > 1` to get it.

I guess the code *could* accept the case where just the scale is fixed, and then set `loc = max(data) - scale`.  Then it would use the formula for `a` derived from the first order condition.  But if this results in `a < 1`, the solution is not correct, and the code would have to generate an error stating that the data appears to be in a regime where the MLE is not well-defined (and perhaps suggest fixing the location instead of or in addition to the scale).

So to ensure that we're providing a solution to a well-defined MLE problem, at minimum it looks like we need to require that either the location is fixed (and the value is less than `min(data)`), or the scale is fixed (and the value is greater than `max(data) - min(data)`).  In the latter case, if the shape `a` is fixed, we require that `a > 1`. if the shape is not fixed, then we have to check that when the shape calculated (using the formula derived from the first order condition), it is greater than 1.

**Comment by mdhaber** [comment]
@swallan for Weibull the conditions are:
(whenever shape is free)
![image](https://user-images.githubusercontent.com/6570539/99549513-93569b00-296e-11eb-988c-04718a2581e0.png)

(whenever scale is free)
![image](https://user-images.githubusercontent.com/6570539/99549644-ba14d180-296e-11eb-9d63-10091c21194b.png)

(whenever location is free)
![image](https://user-images.githubusercontent.com/6570539/99549718-cf89fb80-296e-11eb-8263-2e6a6ee55067.png)

**Comment by mdhaber** [comment]
Re: powerlaw

 >So to ensure that we're providing a solution to a well-defined MLE problem, at minimum it looks like we need to require that either the location is fixed (and the value is less than min(data)), or the scale is fixed (and the value is greater than max(data) - min(data)).

At least for a > 1, I'm certain there can be a well-defined solution, as I wrote above. Here's a (terrible) plot of the log-likelihood function for data generated with shape = 5, loc = 3.5, scale = 15.

![image](https://user-images.githubusercontent.com/6570539/100053990-067c6900-2dd6-11eb-92aa-575e619ad597.png)

The blue line is `loc = np.min(data)` and the orange line is `sigma = np.max(data) - loc`. All points outside the feasible region were assigned a value 0. You can't easily tell from the plot where the maximum is, but you can tell it occurs on the line `sigma = np.max(data) - loc`. You can find it using the method of Lagrange multipliers for constrained optimization. The condition is that the gradient of the objective is aligned with the constraint normal, and that's what the [code above](https://github.com/scipy/scipy/issues/11782#issuecomment-721518694) solves.  There were 1000 data points here, and for that the MLE of the location is 3.26 and the scale is 15.23. For 10000 data points, I get 3.46 and 15.04, so very close.

I haven't studied the shape < 1 case analytically, but it looks like for shape = 0.5, loc = 3.5, scale = 15, it is also well-defined, and the solution is at the intersection of those two lines - so even easier to compute.

![image](https://user-images.githubusercontent.com/6570539/100055262-670ca580-2dd8-11eb-85aa-076524eb1b67.png)

![image](https://user-images.githubusercontent.com/6570539/100055919-8b1cb680-2dd9-11eb-8e38-ad0abb94bb54.png)
This is true, but the argument that leads to it is only valid for the shape < 1 case.  But the closer we get to that line, the higher the LL function, so it seems that a supremum exists, and that's good enough for me. I think it's better to return a point that's very close to that intersection than to require that the user provide one of the parameters.

Please let's talk in real-time to discuss this further. (It's not efficient to type everything or to duplicate work, and we don't have time to spare!)

**Comment by WarrenWeckesser** [comment]
Thanks @mdhaber, I found I was mistaken about the power-law MLE for the case a > 1.  I was decoupling the behavior of the location and scale parameters too much, and reached an incorrect conclusion. The only conclusion that I should have drawn is the one that you stated earlier: if we know a > 1, then the location and scale must satisfy the constraint `loc + scale - max(data) = 0`.  That's the orange line in your plots.

The case 0 < a < 1 is still problematical; I edited [my notes](https://warrenweckesser.github.io/notes/mlenotes.html) with a few comments about this.

**Comment by jjerphan** [comment]
Hi all,

As I started #13396, I discovered this issue and potential improvements for MLE. I'd be happy to help improve this part of scipy.stats.

Can I freely pick remaining distributions and submit analytical ML estimators implementations? Or do you have specific guidelines or tasks attributions? 🙂

**Comment by mdhaber** [comment]
The [table ](https://github.com/scipy/scipy/issues/11782#issuecomment-633188975) above lists the ones we had planned based on what we had found in [this reference](http://personalpages.to.infn.it/~zaninett/pdf/statistical-distributions.pdf).

That said, as we went through we found that since SciPy's parameterization always has `scale` and `loc`, we frequently have to derive the conditions ourselves, and the reference just gave us hints at which distributions it's worth trying for. I wrote a little script that helps a bit with that, if you're interested.

@swallan had you started on von Mises? If not, that would be a good one for @jjerphan.

@lispsil said he was interested in Weibull. (gh-12787). `exponweibull` is another one I've seen an issue about (gh-11806).

Otherwise, any distribution is fair game., I think.

**Comment by swallan** [comment]
> 
> 
> @swallan had you started on a PR for von Mises? If not, that would be a good one for @jjerphan. There are some notes about it [above](https://github.com/scipy/scipy/issues/11782#issuecomment-717078131).
> 


@mdhaber I haven't formally started it yet / written anything so it's fair game

**Comment by mdhaber** [comment]
Oh, @jjerphan I remembered that I wrote out notes for the Asymmetric Laplace distribution:
https://www.dropbox.com/s/4tyrqjr6708yhh1/MLE%20-%20Asymmetric%20Laplace.pdf?dl=0

I think that would be another good one as everything to be done is laid out explicitly there in the "Computation" section. It's possible there is an error in a formula there, but I imagine they will be identified and fixed once they are implemented.

**Comment by jjerphan** [comment]
> I think that would be another good one as everything to be done is laid out explicitly there in the "Computation" section. It's possible there is an error in a formula there, but I imagine they will be identified and fixed once they are implemented.

I guess we can cook something similar to the references notes for Nakagami. Would this layout (i.e a subsection for the analytical derivation of the MLE in the distribution's page in the tutorials) be suitable to you?

**Comment by jjerphan** [comment]
> > @swallan had you started on a PR for von Mises? If not, that would be a good one for @jjerphan. There are some notes about it [above](https://github.com/scipy/scipy/issues/11782#issuecomment-717078131).
> 
> @mdhaber I haven't formally started it yet / written anything so it's fair game

OK, thanks. I'll start with that.

**Comment by jjerphan** [comment]
If you are interested, I am looking for a second reviewer for #13396 (which relates to this issue). 🙂

**Comment by mdhaber** [comment]
Adding `truncweibull_min` as a candidate for possible `fit` override. See gh-9974.

**Comment by mdhaber** [comment]
Improved `fit` has been requested for `genextreme`, too (gh-10446). Since it generalizes gumbel, weibull, and invweibull, perhaps we can use the progress toward fitting those to fit `genextreme`.

**Comment by mdhaber** [comment]
Improved fit has been requested for `truncnorm` (gh-16382).

**Comment by dschmitz89** [comment]
`vonmises` can be removed from the list since #17585. The fit is not analytic per se (requires root finding) but is very fast and stable.

**Comment by dschmitz89** [comment]
After the last iterations `vonmises` should be good now. I will try to look into `gamma`/`beta` soon.
