### ISSUE TITLE
trapz distribution mean computed using single precision

### ISSUE THREAD

**Issue by pkienzle** [scipy/scipy#11795]
The trapezoidal distribution from scipy stats is computing mean with single precision.

Consider the distribution with c=1/3, d=5/6, loc=-3, scale=6 which corresponds to a=-3, b=-1, c=2, d=3 using the parameterization for the generalized trapezoidal distribution from van Dorn, et al.  Using the formula for mean from [wikipedia](https://en.wikipedia.org/wiki/Trapezoidal_distribution) (which is equivalent to the van Dorn formula) the result should be:
```
    1/3 [(d^3 - c^3)/(d-c) - (b^3 - a^3)/(b-a)] / (d + c - b -  a)
    = 1/3 [(27 - 8)/1 - (-1 + 27)/2] / (3 + 2 + 1 + 3)
    = 1/3 [19 - 13] / 9 = 2/9
    = 0.222222222222222
```
However, trapz.mean is returning 0.22222222240802791, which corresponds to a single precision calculation.

#### Reproducing code example:

```
from scipy.stats import trapz
trapz.mean(1/3, 5/6, -3, 6)
```

#### Scipy/Numpy/Python version information:

```
1.4.1 1.17.4 sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
```

**Comment by andyfaff** [comment]
The issue is that the trapezoidal distribution does not override the `_stats` (or `_munp`) methods from [`rv_continuous`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.html#scipy.stats.rv_continuous). Therefore all the statistics calculated by the trapz distribution use the super class method which works everything out with numerical integration.

See:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.html#scipy.stats.rv_continuous

Any PR's are welcome.

**Comment by mdhaber** [comment]
Ditto. (Beat me to it.) @pkienzle would you be interested in implementing this?

**Comment by andyfaff** [comment]
The `norm._stats` method is:

```
def _stats(self):
    return 0.0, 1.0, 0.0, 0.0
```

which are `mu, mu2, g1, g2` for the distribution. Which I think are:
```
'm' = mean,
'v' = variance,
's' = (Fisher's) skew,
'k' = (Fisher's) kurtosis.
```

Those values then get transformed by the scale/loc values.

**Comment by mdhaber** [comment]
Yes, it looks like the way to implement this would be to override the `_stats` method in `gen_trapz`. But as @andyfaff says, the values returned get transformed by the `scale` and `loc` in `rv_continuous.stats`, so I think the values returned by `_stats` need to correspond with with `loc=0` and `scale=1`. Also, there's a bit of algebra to determine the relationships between the variables in Wikipedia and those in ScIPy. 

From the documentation:
> The trapezoidal distribution can be represented with an up-sloping line from `loc` to (`loc + c*scale`)

So `loc` has the same meaning as _a_ in the Wikipedia article, and therefore you would have to substitute _a_=0 into the formulas from Wikipedia.

> then constant to (`loc + d*scale`) and then downsloping from (`loc + d*scale`) to (`loc+scale`).

`loc+scale` is the same as _d_ in the Wikipedia article, so I think you would have to substitute _d_=1 into the Wikipedia formula.

Finally,  _b_ in the Wikipedia article corresponds with `loc + c*scale = c` in SciPy, and _c_ in the Wikipedia article corresponds with `loc + d*scale = d` in SciPy. A bit confusing since the letters in Wikipedia correspond with different letters in SciPy.

Does that look right?

**Comment by pkienzle** [comment]
Yes.  Rewritten with primed variables for wikipedia and unprimed variables for scipy, just to make it clear.

scipy to wikipedia:
```
    a' = loc
    b' = loc + c*scale
    c' = loc + d*scale
    d' = loc + scale
```
wikipedia to scipy:
```
    loc = a'
    scale = d' - a'
    c = (b' - loc)/scale = (b' - a') / (d' - a')
    d = (c' - loc)/scale = (c' - a') / (d' - a')
```

It may be useful to say in the scipy docs that:

>  `loc` is the left point of the base of the trapezoid, `scale` is the width of the base,  and `c` and `d` are the positions in [0, 1] of the top relative to the base.

I found the parameters much easier to work with once I realized this.

van Dorn et al. only wrote down the equations for `E[X]` and `E[X^2]`, so there will be a bit of work required to get `E[X^3]` and `E[X^4]` required to compute `s` and `k`. It is very tempting to look at the pattern for `E[X]` and `E[X^2]` and guess the form for the next two without going through the algebra.

**Comment by mdhaber** [comment]
They can probably be found in another reference. I'll look when I get home. If it's too much work, you can also return `None`, and they will be calculated the same way they are now.

**Comment by andyfaff** [comment]
(everything needs to vectorise)

**Comment by pkienzle** [comment]
Okay, I confirmed with wolfram alpha that the pattern continues through the third and fourth absolute moment, with:
```
E[X^(k-2)] = h/(k(k-1))  [ (d^k - c^k)/(d - c)  -  (b^k - a^k)/(b-a) ]
```
with height of the flat to defined by `2/h = (d+c) - (b+a)`. 

There's probably a simple enough proof of this, but I didn't find it in google scholar when searching the literature which cites van Dorp.

**Comment by pkienzle** [comment]
Done.  The proof was indeed simple enough.  I also threw in the entropy calculation because they happened to have it on the page, and confirmed that the values for stats and entropy correspond to the values returned by the existing scipy, at least to the first 7 digits.  I threw in the example above as a test case, as well as the boundary problems where cancellation leads to divide by zero.
