### ISSUE TITLE
chi2.ppf results Matlab vs Scipy

### ISSUE THREAD

**Issue by jorikdima** [scipy/scipy#11825]
I noticed different results for non central Chi square distribution between Matlab and Scipy.  Specifically I see the difference in chi2.ppf function.

#### Reproducing code example:

Scipy
```
print(chi2.ppf(0.1, 10, loc=1))
```
gives 5.865182051925328

but in matlab 
```
ncx2inv(0.1, 10, 1)
```
gives 5.3658

For central Chi2 results are matched. My simulations show that Matlab results are correct. Maybe there is different definition of non centrality parameter in Scipy that in Matlab?
I assume that loc = df * mean(x)**2

#### Scipy/Numpy/Python version information:
 1.4.1 1.18.2 sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)

**Comment by josef-pkt** [comment]
using loc shifts the support of the distribution, that's not non-central chisquare

you need to use stats.ncx2

**Comment by jorikdima** [comment]
Wow, thanks. Then I would say the description is confusing. I couldn't imagine that this is not non centrality parameter. My understanding was that chi2 is a general chi2 distribution and when loc is 0 - it's the central one, when not - non-central, since central is just a special case of non central.

**Comment by josef-pkt** [comment]
All continuous scipy distributions are loc-scale families, there is nothing specific to chi2

loc and scale just shift and rescale the random variable or distribution
`y = (x - loc) / scale`

**Comment by jorikdima** [comment]
Ok. Then I close it. That was my misunderstanding. Sorry. With ncx2 everything works.

**Comment by matthew-brett** [comment]
Maybe it's worth a note in the Chi2 function documentation?

**Comment by josef-pkt** [comment]
maybe a See Also, but otherwise this should be "understood"
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2.html
mentions loc scale shifts already

similar relationship applies to all non-central distributions, t, F, chi2

(Related aside: 
Some of the old literature was using mean-shifted central distributions as approximations to non-central distributions, when the latter were not easily available in computer programs.
I just ran into several of those articles. It makes it difficult to understand why they are using a specific approximation, i.e. whether they are real improvements or just compensate for the lack of not using the noncentral version.

Just use the non-central distributions, that's why we have them.
)

**Comment by jorikdima** [comment]
Well... I admit it was my fault that I took loc parameter for non centrality.
But at the same time the question is: could it be someone else or just me? :) Let's follow my path.
Basically I needed information about chi2 distribution and its ppf function in numpy. I goggled it and I found that Scipy provides it. I needed both central and non central. I saw a distribution just called chi2. Obviously that should work for central distribution. At the same time I saw loc parameter and it's default value 0. And I saw a note 

> The probability density above is defined in the “standardized” form. To shift and/or scale the distribution use the loc and scale parameters. Specifically, chi2.pdf(x, df, loc, scale) is identically equivalent to chi2.pdf(y, df) / scale with y = (x - loc) / scale.

That what misled me. loc really looks like non centrality parameter for me. And it seemed like it's general (non central chi2 distribution) which converges to central one when loc is zero. I don't know if I am the only one or not. And after that I even didn't think about trying to find real non central chi2. It was my first time I worked with stats module in scipy and I had no idea that there is some parent distribution and all sub-classes also have this loc/scale parameters and they have nothing to do with non centrality here. I spent two days with my equations and couldn't realize why it gives me wrong result until I implemented it in Matlab and saw that everything matches except this one.
I really don't want to make (and can't) any decisions here about adding some notes in the Doc (now it's clear that nothing works wrong, nothing to fix). I just show you my story. Can't anyone else be confused?
Thanks

**Comment by josef-pkt** [comment]
However you found ncx2 in matlab. 
Is it only the unusual `loc` that was confusing in scipy compared to matlab?

I would rename ncx2 to ncchi2 to match chi2, instead of the "matlab" name. (An `x` ain't no `chi`.)
I leave it up to the current maintainers to decide whether and how the docstring can be improved, a `See Also` to point to the non-central versions would help.

Otherwise, **my** opinion is that users need to do their homework and docs cannot clarify all the confusion that might show up, for example in stackoverflow, especially if the docs would then get so long that nobody reads them anymore.

(When I'm working on a new topic, then I always get confused about something and need to check the details to see that I get what I actually want (*). But often this is only a one-time investment and next time that information would be redundant or noise. 
One advantage of stackoverflow is that google often provides the appropriate answer as one of the top search results. And I do that search more often than reading docs.

(*) example for verifying results: 
scipy special function for ncf can solve for the non-centrality parameter. That's a nice feature because we don't need do the root finding ourselves. Given that I never used that before for ncf, I did some examples from the literature to check that scipy.special produces the expected results. 
It works great and saves me the struggle with root finding in this case.
https://github.com/statsmodels/statsmodels/pull/6526/files#diff-26abd2f0b72810fe723fb299c04911e9R201
The disadvantage is that it is then just a one-liner and the function is mostly docstring :)
)

**Comment by ev-br** [comment]
> I really don't want to make (and can't) any decisions here about adding some notes in the Doc (now it's clear that nothing works wrong, nothing to fix). I just show you my story. Can't anyone else be confused?

Any suggestions on how to improve the docs here? 
User input is *very* welcome!

And if you could do a PR with the edit, that'd be even better

**Comment by WarrenWeckesser** [comment]
@jorikdima, the confusion is completely understandable.  Thanks for explaining your situation so clearly.

We can definitely improve the documentation.  At a minimum, the `chi2` docs should have a 'See Also' section that links to `ncx2`.  An additional note about `chi2` vs `ncx2` could be helpful, too.

@jorikdima, if you are interested in contributing such a change, it would be welcome, just let us know.  If not, we can add something pretty quickly.

**Comment by jorikdima** [comment]
I totally agree with @josef-pkt that:
> users need to do their homework and docs cannot clarify all the confusion that might show up, for example in stackoverflow, especially if the docs would then get so long that nobody reads them anymore.

I would just add one simple sentence in the beginning, like:
> A **central** chi-squared continuous random variable. **A non central chi-squared continuous random variable can be found here [link to ncx2].**

Just a link at the beginning can immediately hint a reader that for a non central distribution he needs to go somewhere else.
Maybe we could add one simple and short comment in the end of the Notes section. Like:
> **loc is not a non centrality parameter here.**

Assume the last one may sound too pulled up to my personal case :)
And I think that if we agreed to do doc changes it should be done for all pairs of central/non central distributions like t, F, chi.. what else scipy has classes for.
