### ISSUE TITLE
MAINT: remove character encoding check in CI?

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#11925]
This showed up recently in a PR: https://github.com/scipy/scipy/pull/11862#issuecomment-618704394

We added a character  encoding check to our CI in 2018 to guard against broken Python 2.7 wheels: https://github.com/scipy/scipy/pull/9615

The issue was very annoying, and caused  us to have to do an extra release or two because 2.7 wheels would be reported unusable *after* release: https://github.com/scipy/scipy/issues/9606

If we are *sure* we no longer need it, then we can remove this from CI? Unicode/encoding stuff is tricky and I'm not an expert, but probably 2.x only issue right?

**Comment by pv** [comment]
Unicode has lots of stuff and part of it invisible (non-breaking spaces, etc.) that will fail to print properly under some conditions, and I think there is reason to not want to allow that in the source code. (In the case encountered in that PR, the non-ASCII characters also probably were not intentionally inserted.)

**Comment by tylerjereddy** [comment]
That's fair, just thought I'd bring it up because Matt pinged me about in the cross-linked PR.

**Comment by WarrenWeckesser** [comment]
(I just commented over in https://github.com/scipy/scipy/pull/9615, but now I see I should have commented here, in the open issue.)

In a comment in https://github.com/scipy/scipy/pull/9615, I asked about removing the check. @rgommers  suggested looking into how programs such as ipython handle Unicode characters in docstrings.  Since then there has been some work in NumPy that looks relevant.

Over in https://github.com/numpy/numpy/pull/15666, @rossbar added the use of Unicode characters in the string representation of NumPy's polynomial.  It turns out that using Unicode in a Windows terminal can cause problems; see the discussion starting at https://github.com/numpy/numpy/pull/15666#issuecomment-601327484.  The problem is that the font used by the terminal might not support the Unicode characters being used.

**Comment by ev-br** [comment]
(My POV might be old-fashioned and/or outdated), but I'd much rather keep sticking to base latin ASCII in the source code.

**Comment by WarrenWeckesser** [comment]
In https://github.com/scipy/scipy/pull/12393, I replace the grep-based check for non-ASCII characters with a python script.  The script will show the exact position in the file of any offending characters.

The new script emulates the existing grep-based check.  In particular, if the source code has a PEP-263-compliant comment that specifies the encoding for the file, the file is not checked for non-ASCII characters.   That made sense for the original purpose of the check, but now that behavior is questionable.  We can still end up with unwanted Unicode characters (e.g. non-breaking spaces) in any file that has such an encoding comment.  That is, to make a file pass the check on TravisCI, just add `# -*- coding: utf-8 -*-` to beginning of the file.  So I think the current check is too crude.  (And in Python 3, we really shouldn't be cluttering our source code with redundant encoding comments.)

The question then is how should the check be refined?  Here's one idea: have a black list of disallowed Unicode characters that includes any non-printing Unicode characters (e.g. U+0080 - U+00A0), the zero-width space U+200B, etc. Also, we might prefer that an ASCII hyphen be used instead of the Unicode en-dash and em-dash characters, which often end up in the "References" section of docstrings when the text is cut-and-pasted from a PDF file.  Other special cases can be easily incorporated into the script, and once the code is set up, we can refine the black list as needed.

What do you think?

@ev-br, we already have many uses of Unicode characters outside of the latin-1 character set, so I suspect it is too late to try to restrict the code to latin-1 characters only.  But that case could also be handled with the updated check.

**Comment by ev-br** [comment]
> we already have many uses of Unicode characters outside of the latin-1 character set, so I suspect it is too late to try to restrict the code to latin-1 characters only.

Agreed, we can I think treat this like we do with other style violations: tolerate existing code, avoid large-scale cleanups, check new code :-).

The main distinction I think is that unicode in docstrings is mostly OK. Even though I'd much rather minimize it even there. (Non-unicode terminals still are not extinct, sadly)

**Comment by WarrenWeckesser** [comment]
The number of distinct non-ASCII characters that we currently have in the source code isn't that big.  If we ignore the dash-like characters that I propose removing in https://github.com/scipy/scipy/pull/12399, we have...

In docstrings:

    '®' U+00AE
    'é' U+00E9  ("Fréchet")
    'λ' U+03BB
    '’' U+2019
    '┌' U+250C, '┘' U+2518, etc. (box drawing characters)

In comments:

    'π' U+03C0
    'ω' U+03C9
    '∫' U+222B
    '≠' U+2260

In a string in code (in `io/matlab/test/test_mio.py`; see my comment about this here: https://github.com/scipy/scipy/pull/12393#issuecomment-647152960):

    'Ã' U+00C3
    '¶' U+00B6

The code in https://github.com/scipy/scipy/pull/12393 can be modified to flag any occurrences of Unicode characters in a black list, or to allow only those characters from a white list.  A very conservative approach is to use the above list as the white list (and I would even drop  '’' (U+2019)), and then grow the white list as needed.  In fact, since this is probably the most conservative approach, I'll modify https://github.com/scipy/scipy/pull/12393 to use the limited white list, and we can iterate from there.

**Comment by rlucas7** [comment]
+1 on *removing* U+2019 from whitelist.

I think that one creeps in from notes app on macs, e.g. you compose text or copy it via a note to code. 

Sincerely, 

-Lucas Roberts

**Comment by WarrenWeckesser** [comment]
@rlucas7, agreed.  I left it off the white list in the update of https://github.com/scipy/scipy/pull/12393

**Comment by WarrenWeckesser** [comment]
A quick summary of my pull requests related to this issue:
* https://github.com/scipy/scipy/pull/12399  cleans up a few unwanted instances of Unicode characters currently in the code.
* https://github.com/scipy/scipy/pull/12404 fixes the declared encoding of `test_mio.py`, so it matches the actual UTF-8 bytes that occur in the file.
* https://github.com/scipy/scipy/pull/12393 implements the new check for Unicode characters that will run as part of CI to ensure that new unwanted Unicode characters are not added to the code.

**Comment by WarrenWeckesser** [comment]
Closed by https://github.com/scipy/scipy/pull/12393.

**Comment by jowagner** [comment]
Related reading:
* Boucher and Anderson (2021) [Trojan Source: Invisible Vulnerabilities](https://www.trojansource.codes/trojan-source.pdf)
