### ISSUE TITLE
Generalize the Nakagami-m to introduce the spread parameter Ω

### ISSUE THREAD

**Issue by jjerphan** [scipy/scipy#11932]
**Is your feature request related to a problem? Please describe.**

The [Nakagami-m distribution](https://en.wikipedia.org/wiki/Nakagami_distribution) is implemented under the `nakagami_gen` that extends `rv_continuous`.

https://github.com/scipy/scipy/blob/88b9e702d9fad080a40040e61b75e964a7df5c80/scipy/stats/_continuous_distns.py#L5647-L5689

However the shape parameter Ω isn't settable via this interface and implicitly defaults to one.

**Describe the solution you'd like**

Generalize the Nakagami-m to introduce the shape parameter Ω

**Describe alternatives you've considered**

 - Modify `nakagami_gen` interface and implementation to handle Ω with retrocompatibility, or
 - Keep `nakagami_gen` as it is and introduce a new `rv_continuous` which generalizes `nakagami_gen` to handle Ω

I can implement this feature with @h-sdl.

**Comment by josef-pkt** [comment]
Based on a quick look on the wikipedia page

omega corresponds to the scale parameter: `Omega = scale**2`

**Comment by jjerphan** [comment]
I made a mistake: it is the spread parameter.

Which alternative would you recommend?

**Comment by josef-pkt** [comment]
I don't see anything to do.
scipy nakagami is just a reparameterization of the one in the wikipedia page, but has additional a loc parameter to shift the distribution. (3-parameter family instead of 2-parameters)

There is currently no support for simple reparameterization. 
That is left to the user, i.e. just use square and square-root to switch parameterization.

(in analogy: `scale` corresponds to the standard deviation, `omega` to the variance in normal distribution)

**Comment by jjerphan** [comment]
That's clear, I haven't seen this distribution under this parametrisation.

Thank you for your answer.
