### ISSUE TITLE
CI: Occasionally macOS jobs run by github actions are cancelled.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#12016]
We currently use github actions to run the test suite on macOS with three different Python versions. For the last couple days, one or more of these jobs is mysteriously cancelled.  As I write this, two examples are

* https://github.com/scipy/scipy/pull/12010 (The PR has been merged, but if you click on the red x next to the commit hash `4d210e6`, you'll see that two macOS tests were cancelled.) 
* <strike>https://github.com/scipy/scipy/pull/12013</strike> (The tests were rerun, and they all passed.)

I've seen the cancellations happen on PRs and on the tests that run on the master branch, but they don't always occur. Sometimes all three macOS jobs run to completion.  In some cases, I've restarted the jobs, and they all then passed.  In other cases, restarting ended up with another cancellation.

I also reported this on the mailing list: https://mail.python.org/pipermail/scipy-dev/2020-May/024143.html

I'm not sure if these folks can respond to every ping they get on github, but it's worth a shot: ping @chrispat, @lkillgore, @vtbassmatt

**Comment by jGaboardi** [comment]
Not sure if this is related, but I have also been experiencing stalled/hanging/cancelled builds for [more than a month](https://github.com/pysal/spaghetti/pull/453#issuecomment-604072960). It appears to happen with macOS most of the time but also with Windows, and varies by build environment and Python version (seemingly) randomly. I opened a [ticket in the GH Community Forum](https://github.community/t5/GitHub-Actions/Hanging-builds-in-matrix/m-p/51880#M8345) and initially received support, but haven't heard anything back since then.

**Comment by WarrenWeckesser** [comment]
This hasn't occurred for a few days, so I'm assuming the issue has been quietly resolved.  Closing.

**Comment by LilithHafner** [comment]
Still getting this issue
https://github.com/LilithHafner/UpdateJulia.jl/actions/runs/1529228017/attempts/2
