### ISSUE TITLE
Function stats.binom_test Returning Incorrect Results

### ISSUE THREAD

**Issue by kleban31** [scipy/scipy#12074]
#### Description
The _stats.binom_test_ function doesn't seem to produce correct results every time.

**Examples:**
In the following example, I am trying to find the probability of 2 successes out of 3 trials where each trial has a 70% chance of success. 
* Expected Result: 0.441
* Function Returns 1.0
```
[In] stats.binom_test(x=2,n=3,p=0.7)
[Out] 1.0
```

In the following example, I am trying to find the probability of 2 successes out of 5 trials where each trial has an 80% chance of success. 
* Expected Value: 0.0512
* Function Returns 0.0579
```
[In] stats.binom_test(x=2,n=5,p=.8)
[Out] 0.057919999999999965
```

#### Scipy/Numpy/Python version information:

* Python Version: 3.7.6
* Numpy Version: 1.18.1
* Scipy Version: 1.4.1
```
[In] import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)

[Out] 1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

#### Other Info:
* Python installed through Anaconda
* Executing this code through terminal
  * Python accessed through terminal using command line "python"
  * Python version 3.7.6 is displayed upon doing this
* OS:  MacOS Catalina 10.15.4

**Comment by WarrenWeckesser** [comment]
@kleban31, `binom_test` implements a two-sided test.  Depending on your familiarity with the test, that might be enough to answer your question.  If not, read on...

The value returned by `binom_test(x, n, p)` is the probability that a sample from the [binomial distribution](https://en.wikipedia.org/wiki/Binomial_distribution) would be "at least as extreme as" `x`. Because the binomial distribution is unimodal, we can say that the two-sided p-value for `x` is the sum of all the probabilities `p(k)`, k = 0, 1, 2, ..., n, that are less than or equal to `p(x)`.

This is might be easier to see with a plot.  The following shows the probability mass function of the binomial distribution for n=8 and p=0.57.  The green bars show the probabilities that contribute to the p-value returned by `binom_test(3, n=8, p=0.57)`.  In this case, the values that are at least as extreme as x=3 are 0, 1, 2, 3, 7, and 8.  The sum of each of their corresponding probabilities is 0.30192; that is the p-value returned by the binomial test.

![k3n8p0 57](https://user-images.githubusercontent.com/321463/81485783-cd0b5400-921d-11ea-9991-e45ba0fa0ed4.png)

Here's the plot for your second example, with x=2, n=5 and p=0.8.  In this case, the only values that as at least as extreme as x=2 are 0, 1 and 2.

![k2n5p0 8](https://user-images.githubusercontent.com/321463/81485802-faf09880-921d-11ea-8364-26ab38421dc3.png)

In your first example, with x=2, n=3 and p=0.7, x=2 happens to be the mode of the distribution: all the values are at least as extreme as x=2.  In the plot, all the bars are green, and the p-value given by the binomial test is 1.

![k2n3p0 7](https://user-images.githubusercontent.com/321463/81485845-689cc480-921e-11ea-9e8f-28607a702157.png)

**Comment by WarrenWeckesser** [comment]
> In the following example, I am trying to find the probability of 2 successes out of 3 trials where each trial has a 70% chance of success.

To find this probability, don't use `binom_test`.  You want the probability mass function, which is provided by the `pmf` method of the SciPy distribution `scipy.stats.binom`:

```
In [81]: from scipy.stats import binom                                          

In [82]: binom.pmf(2, 3, 0.7)                                                   
Out[82]: 0.44099999999999995
```

**Comment by WarrenWeckesser** [comment]
I'm closing the issue, but @kleban31, don't hesitate to ask if you have any questions.

**Comment by kleban31** [comment]
Ooooh, makes sense. Thanks for your quick response and thorough
explanation. This really helps!
