### ISSUE TITLE
`axis` option for `stats.tmean` do not appear to be working as expected

### ISSUE THREAD

**Issue by jtstanley** [scipy/scipy#12106]
My issue is about (see title)

#### Reproducing code example:

```
import scipy as sp
import numpy as np

r = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

print(sp.stats.tmean(r, axis=1))
print(sp.stats.tstd(r, axis=1))
```
Output:
```
2.0
[0. 0. 0.]
```

Expectation:
```
[1.0, 2.0, 3.0]
[0., 0., 0.]
```

#### Scipy/Numpy/Python version information:
```
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
@jtstanley, thanks for the report. That's a bug. `tmean` is ignoring the `axis` argument.

**Comment by siddhantwahal** [comment]
Hello!

There seem to be two issues with `tmean`. 

1. First, as @jtstanley pointed out, it ignores `axis` if no `limits` are provided. The culprit here is this line, where `axis` has been forced to `None`: 
```
if limits is None:
        return np.mean(a, None)
```

2. If `limits` is not `None`, then this happens:
```
    am = _mask_to_limits(a.ravel(), limits, inclusive)
```
The array is forcibly `ravel`-ed, and consequently, the `axis` keyword loses any meaning. 

Both fixes seem simple -- change `np.mean(a, None)` to `np.mean(a, axis)` for (1), and removing the call to `ravel`, filling missing entries with `np.nan`, and then using  `np.nanmean(am, axis)` for (2) (this is exactly what's done in `tvar`). 

I'm happy to make both changes an open a PR if no one else is working on this.

**Comment by rgommers** [comment]
Thanks @siddhantwahal, please go for it!

**Comment by mdhaber** [comment]
Another example of this is in gh-9770. Please check that any resolution of this issue addresses the example there, too.
