### ISSUE TITLE
Using the SLSQP Solver for linear problems from a scientific point of view

### ISSUE THREAD

**Issue by annebierhoff** [scipy/scipy#12215]
Currently, I am solving a minimization problem with the SLSQP solver in scipy.

```
from scipy.optimize import minimize
import numpy as np

def OF(x0, v_1, v_2, v_3, v_4):
  value_to_minimize = 0.0
  for i in range(0, len(v_1)):
    value_to_minimize += np.abs(v_1[i] - (v_2[i] * x0[0] + v_3[i] * x0[1] + v_4[i] * x0[2]))
  return value_to_minimize

if __name__ == '__main__':
  x0 = np.array([0, 0, 0])
  v_1 = np.random.randint(10, size = 10000)
  v_2 = np.random.randint(10, size = 10000)
  v_3 = np.random.randint(10, size = 10000)
  v_4 = np.random.randint(10, size = 10000)

  minx0 = np.repeat(0, [len(x0)] , axis = 0)
  maxx0 = np.repeat(np.inf, [len(x0)] , axis = 0)
  bounds = tuple(zip(minx0, maxx0))

  cons = {'type':'eq', 'fun':lambda x0: 1 - sum(x0)}
  res_cons = minimize(OF, x0, (v_1, v_2, v_3, v_4), bounds = bounds, constraints=cons, method='SLSQP')
```

The solution works well, but I was wondering about the following question:
Since the solver can also solve nonlinear optimization problems, would a different approach be recommended from a scientific point of view for such a simple linear problem?

**Comment by ilayn** [comment]
Hi @annebierhoff I'm not sure what you mean by scientific method. But your problem is an LP with only positivity constraints. So you can use linear programming solvers. Note that we exclusively use this repo for bugs and feature requests. So usage questions are most welcome on the mailing list or you can ask it on various StackOverflow and satellite networks.

**Comment by ilayn** [comment]
I'll close this but feel free to add more remarks as you wish.
