### ISSUE TITLE
Why `quad` and `quad_vec` have different defaults?

### ISSUE THREAD

**Issue by vnmabus** [scipy/scipy#12216]
Reviewing the documentation of these two methods, it surprised me that they have different default values. As an example, the `limit` parameter (which, BTW is undocumented in `quad_vec`), has a default value of 50 in `quad` and 10000 in `quad_vec`. Is there a reason for them not to be the same?

**Comment by mdhaber** [comment]
`quad_vec` was added in gh-9642. It doesn't appear that the defaults were discussed. I think this resolves the query.

Perhaps the author and reviewer (@pv and @ev-br) can shed further light on this, but I'll close in the meantime because the defaults are unlikely to be changed (to avoid backward compatibility issues) without a strong case for doing so.
