### ISSUE TITLE
least_square slower with sparse jacobian than dense jacobian

### ISSUE THREAD

**Issue by Didou09** [scipy/scipy#12257]
#### Context (scipy 1.4.1)
* I need to compute a least_square solution to a 2d problem.
* The solution is modulated, in one of the dimensions, by Bsplines, which have a compact support and allow for a sparse jacobian.
* Before implementing the whole 2d problem, I test it in 1d to determine the best algorithms
* So I basically re-implement 1d Univariate Bspline fitting using only least_squares()
* I have to use least_square because the 2d problem will use it
* I provide the jacobian as a callable, and trying with dense and sparse version I find that the trf algorithm is faster with a dense jacobian than with a sparse one.

#### I guess it is due to the fact that:
* dense jacobian => trf solver = ''exact' => solve_lsq_trust_region
* sparse jacobian => trf_solver = 'lsmr' => solve_trust_region_2d()

So surprisingly, using a sparse matrix calls a more complex 2d solving algorithm.

Any idea how to fix what looks like a performance issue ?

I guesse the bottom question is why does a sparse matrix force the use of solver='lsmr' ?

**Comment by nmayorov** [comment]
I'm a bit confused. I will try to highlights points which should clarify things for me and for you.

1. I didn't get a relationship between your "2d problem" and "solve_trust_region_2d". The latter solves the reduced trust region problem in 2 dimensions, as opposed to solving the trust problem in the original space (dimension equal to the number of variables).
2. If your problem is not very large (number of residuals * number of variables is not very large) you can use dense Jacobian and "exact" solver. If it works faster for you, why worry?
3. Sparse matrix forces use of 'lsmr' solver because we can't convert it to a dense matrix and compute required factorizations. If you want "exact" solver, you need to explicitly represent it as dense yourself.

Has anything become more clear to you now?

**Comment by mdhaber** [comment]
I take it that the response offered above resolved the issue, so closing.
