### ISSUE TITLE
Query - LAPACK subroutines signature file

### ISSUE THREAD

**Issue by EverLookNeverSee** [scipy/scipy#12274]
Hi @mdhaber @ilayn 
I have a question about lapack signature files. For example in scipy/linalg/flapack_gen.pyf.src we have a subroutine signature as below:
![signature_getc2](https://user-images.githubusercontent.com/57490926/83322228-27bb2d00-a26b-11ea-8bd1-730da1254813.png)
I built a signature file for sgetc2 and also read wiki page, but i did not get why did we use **int i;** and **for(i=0;i<n;–ipiv[i],–jpiv[i++]);** in callstatement?

**Comment by ilayn** [comment]
That's from older wrappers. Because Fortran arrays are 1-indexed and Python is 0-indexed. What happens here after finishing up the fortran call indices are being converted to 0-indexed indices. We try not to do these anymore because often you pass these to another Fortran routine and you have to once again convert to 1-indexed indices. 

This in particular, is going through ipiv and jpiv arrays and subtracting 1 from each entry in place.

**Comment by EverLookNeverSee** [comment]
> That's from older wrappers. Because Fortran arrays are 1-indexed and Python is 0-indexed. What happens here after finishing up the fortran call indices are being converted to 0-indexed indices. We try not to do these anymore because often you pass these to another Fortran routine and you have to once again convert to 1-indexed indices.
> 
> This in particular, is going through ipiv and jpiv arrays and subtracting 1 from each entry in place with a for loop (int i is for declaring the type of the loop variable).

Thank you @ilayn
