### ISSUE TITLE
API: stats.chisquare: must observed and expected frequencies add to same total?

### ISSUE THREAD

**Issue by sam-data-guy** [scipy/scipy#12282]
The function scipy.stats.chisquare performs the chi-square test on a vector of observed and expected frequencies.  For the test to make sens, the observed and expected frequency vectors must sum to the same total, otherwise the result is nonsense since the inputs are incompatible.  So there are two options: either an error should be thrown if they do not, or f_exp need to be rescaled so they sum to the total of f_obs.  The first is probably better, or the second with a warning thrown.

#### Reproducing code example:

```
# In the following example, one vector is an exact multiple of the other.
# this means that the observed and expected frequencies are exactly
# proportional.  This should give a p-value of 1 (not significant at all).  
# Instead, you get the following:
from scipy.stats import chisquare
chisquare(f_obs=[10,20], f_exp=[30,60])

# Power_divergenceResult(statistic=40.0, pvalue=2.5396285894708634e-10)
# the statistic of 40 is calculated as following, which directly follows the 
# formula.  This is then plugged into a chi squared distribution to get a 
#p-value of close to 0, which is the opposite of the significance you should
# get.
# ((10-30)**2 /30) + ((20-60)** 2 / 60) = 40

# Instead, here is what should happen
import numpy as np
fobs = np.array([10,20])
fexp = np.array([30,60])
# adjust the totals
# gives array([10., 20.]), the same as observed
fexp = fexp * (np.sum(fobs)/np.sum(fexp)) 
chisquare(f_obs=fobs, f_exp=fexp)
# the correct result
# Power_divergenceResult(statistic=0.0, pvalue=1.0)
```

#### Scipy/Numpy/Python version information:
```
1.4.1 1.18.4 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
The two proposed changes sound reasonable to me and I can implement either. A third option, if this is a "feature", would be to change nothing about the way the test functions but to document why the test is performed the way it is. I don't have an informed opinion.

**Comment by sam-data-guy** [comment]
As I said, the test output is nonsensical since the inputs are incompatible because the test requires them to sum to the same total.  It seems to me that the fact it has been programmed this way is a defect from the beginning.   The third option you note amounts to simply documenting the fact that the test does not work as expected, and leaving the user to discover the mistake.  I mean, it does do a chi square calculation but if the inputs are not compatible it is not a real test.  I think having a warning or note thrown is best, if you are concerned about backwards compatibility.  For instance, the anderson_darling test throws a note about p-value truncation (which I frankly think is silly as well, but what the heck).  But I really think you should think about correcting it in some way (perhaps deprecating the function and using a new one), otherwise you run the risk of perpetuating the error in the future.  Furthermore, it shouldn't be up to the user to make sure that their inputs are legal, particularly since not everyone knows better.

**Comment by josef-pkt** [comment]
AFAIR, what I do in statsmodels in a similar case is raise an exception if sums differs by more than a numeric small number, or rescale if sums differ but `expected` has values between 0 and 1.
The second case allows that expected values can be defined as probabilities or relative frequencies.

Different sums of integer values is ambiguous and rescaling cannot be done in a safe way, i.e. we don't know which to rescale, unless we want to second guess which mistake the user made or what the user really meant.

Disclaimer: I haven't looked at the scipy functions in a long time.

**Comment by HDembinski** [comment]
AFAIU hanging this was a mistake. The chi-square test as described on Wikipedia https://en.wikipedia.org/wiki/Chi-squared_test does not require that the sum of the observations is equal to the sum of expectations. It is derived on the Wikipedia under the assumption that sum(x) == sum(m), but even without enforcing this condition, if the x are sampled from the m, the statistic has a chi-square distribution in the asymptotic limit. The original implementation was correct and breaking everyone's code that relied on the previous behavior is not great.

**Comment by HDembinski** [comment]
The new test that checks `sum(f_obs) == sum(f_exp)` also slows down the whole function.

**Comment by sam-data-guy** [comment]
Look, I'm really sorry, but you are completely incorrect.  Let's go to the
Wikipedia page you cite, which I believe I have mentioned above.  When you
go to the relevant section, this says that the sum of the m_i's, which are
the expected counts for each category level i, must equal the sum of the
observed values x_i.  The test only makes sense because it is assumed a
total of "n" counts are observed.  Yes, it's true that one may test a
vector of observed counts versus a vector of expected counts where they do
not equal each other, but you have to then adjust them so they DO sum to
the same total.  If you believe that this requirement does not exist,
please show me the evidence you are relying on.  Otherwise, because your
function currently outputs a p-value (which implies the inputs are
compatible) when they are not, you are misleading your users.
Now, I'd be interested to hear specifics on how this is messing up people's
results, since if the results were invalid when the inputs are
incompatible, this is how the function should have behaved in the first
place.

[image: image.png]

**Comment by mdhaber** [comment]
I think this may be useful to illustrate @sam-data-guy's point. I'll leave interpretation up to someone else.

```
import numpy as np
from scipy.stats import chisquare, chi2
from scipy.stats import randint
import matplotlib.pyplot as plt

# samples will be drawn from a given discrete distribution.
a, b = 0, 10
dist = randint(a, b)
bins = np.linspace(a, b, (b-a)+1)

# Determine the expected frequency in each category
N_exp_nominal = 5000
f_exp = (dist.pmf(bins[:-1]) * N_exp_nominal).astype(int)
N_exp = np.sum(f_exp)  # expected number of observations total

# Repeatedly draw samples of size N_obs from the same distribution and
# calculate the test statistic. 
N_obs = N_exp
N_samples = 100000
stats = []
for i in range(N_samples):
    rvs = dist.rvs(size=N_obs)          # take a random sample
    f_obs, _ = np.histogram(rvs, bins)  # compute the observed frequencies
    stat, p = chisquare(f_obs, f_exp)   # compute the test statistic
    stats.append(stat)        
stats = np.asarray(stats)

# The asymptotic distribution of the test statistic
# is chi2 with df = number of categories - 1.
# Plot the empirical distribution against the asymptotic distribution.
df = len(f_obs) - 1
plt.hist(stats, bins=50, density=True)
x = np.linspace(0, np.max(stats), 100)
plt.plot(x, chi2(df=df).pdf(x))
plt.legend([f'empirical distribution, {N_samples} samples', 
            'asymptotic distribution'])
plt.xlabel('statistic')
plt.ylabel('probability density')
```
When `N_obs = N_exp`:
![image](https://user-images.githubusercontent.com/6570539/123858319-39408f80-d8d8-11eb-9c4f-aa0e3f28d1da.png)

When `N_obs = N_exp + 100`
![image](https://user-images.githubusercontent.com/6570539/123858502-74db5980-d8d8-11eb-9ff6-5c147d13c187.png)

**Comment by sam-data-guy** [comment]
Thank you, this clearly shows that the distribution does not match the chi
square when the frequencies do not sum to the same value.  I agree with the
earlier comment that the check is useful for identifying user mistakes,
where a "mistake" is using frequencies for mis-matched features. As you
illustrate, however, a "mistake" can also be not adjusting the feature
totals when the user is analyzing the same feature; a "mistake" can simply
be the user not formatting the input correctly, and since you did not check
for that, it needed to be fixed.

**Comment by josef-pkt** [comment]
If the aggregate numbers don't agree, then the Null should be rejected, so the distribution should not be the same as under the Null hypothesis.

My original test case in statsmodels that failed with new scipy was truncating probabilities for Poisson. sum of expected probabilities was in the range of 1 - 1e-5. In that case the truncated "measure" was close enough to the empirical counts that the null was not rejected.
The truncated distribution that ignores the left out probability is a good approximation to the empirical distribution according to the chisquare test. The chisquare test should have rejected the null hypothesis if the neglected probability is "large".

But that's a non-standard interpretation of chisquare test. Preventing user error is more important.

**Comment by sam-data-guy** [comment]
No, again, you are making a mistake.  If the sums don't agree, you can't
perform the test; this is not the same as saying you reject the null.  This
is like saying if you get the question "is this apple the father of this
sofa", you should answer "no" (i.e. reject the null with a p-value) rather
than saying "the question is x the father of y is not valid when x is an
apple and y is a sofa".  The answer "no" implies that the evaluation was
actually taken place.
Again, look at Matt's graphs that show that the distribution calculated
does not match up with the theoretical distribution (chi square) when the
sums don't match.  It has already been decided this issue is closed and
resolved as I explained before.  I'm not sure why you guys keep on raising
the same argument that has been addressed in the earlier threads and has
been decided.

**Comment by josef-pkt** [comment]
>  "is this apple the father of this sofa", you should answer "no"

correct, NO is the correct answer. The apple is not the father of the sofa. 
The father of the sofa is a bench. (Unless the sofa is made out of fruits.)

In many cases, hypothesis test reject on other deviations of the null than the simple stated hypothesis.
In this case, the test statistic just compares counts. The distribution of the test statistic is derived under the null hypothesis that counts agree. Any deviation from that will reject the null if the deviation is large enough.

> the distribution calculated does not match up with the theoretical distribution (chi square) when the sums don't match.

They are not supposed to match because the null hypothesis of equal counts doesn't hold, the empirical distribution corresponds to some alternative.

(in the two sample case, I guess it would be conditional versus unconditional comparison)

(IIRC: take kruskall-wallis two sample comparison
If the two distribution are symmetric or the distribution are shift alternatives, then the hypothesis is rejected if medians or location are not the same. 
If distributions can differ arbitrarily, then rejection the null only means that the two distributions are not the same, but doesn't say anything directly about location/mean/median.
The test statistic is derived under the Null that the distributions are the same. Any large deviation from that will lead to rejection of the Null.
)

I tried to look at two sample chisquare test, but didn't get far
https://www.itl.nist.gov/div898/software/dataplot/refman1/auxillar/chi2samp.htm

**Comment by sam-data-guy** [comment]
No, I'm sorry. you are incorrect.  Statistical tests have various
requirements on the inputs.  In this case, the requirement on the inputs is
that the sums of the frequencies are equal and > 0.  If that is not
satisfied, the test cannot be performed.  This is an initial examination of
the legality of the inputs.  You are correct that the answer is "no" but
statistical tests output a probability which is calculated under a
statistical distribution.  You can't say "the apple is not the father of
the sofa because the p-value is ___".  You have to say the inputs are not
valid.  In another example, the frequencies to be calculated must be valid
frequencies, each >= 0.   A negative number is not a valid value.  You are
arguing that the chi square receiving two inputs (3,6,3) vs (-1, -7, -9)
should be evaluated, rather than saying that the second input is invalid.
The Kruskall Wallis test you cite is in no way supporting your argument.
Here you have two samples, but there is no restriction on the sizes, they
don't have to be the same as each other.  It doesn't matter how the
distributions differ, as long as the inputs are valid (e.g., you can't
calculate a deviation where one sample is numeric and the other consists of
letters "A", "B", "C"), then it can perform the calculation.  The same is
not true of the chi square test.
I've answered this question many times above, and it is accepted.  If you
have any questions please contact the people above (Matt etc.).  You said
you looked at the chisquare test but didn't get very far.  If you don't
understand this test, then you probably shouldn't be jumping in at this
point once we have already addressed the issues.  If you want to look it
up, go to wikipedia and look at this section.  The expected values m_i and
observed x_i must both be valid on their own (each >= 0) and sum to the
same.

[image: image.png]

**Comment by sam-data-guy** [comment]
Hi Matt, if the issue is closed and you agree with me, is there a way to
prevent other latecomers who don't properly understand the problem from
continuing to comment on this in email? Unless I should just ignore them.

**Comment by mdhaber** [comment]
I think you, @josef-pkt, and I all agree that the appropriate behavior here is to raise an error when the sums of `f_obs` and `f_exp` are not the same, because the test is no longer useful for its intended purpose: testing a difference between the shapes of the underlying distributions. 

>  Unless I should just ignore them.

Probably, unless something substantially different comes up. Otherwise, I don't know if there's any more for us to say.

**Comment by josef-pkt** [comment]
https://hometone.com/apple-sofa-steve-jobs-craving-heavens.html

:)

**Comment by petrelharp** [comment]
There are perfectly good situations where the chi-squared test is valid even if the observed and expected don't sum to the same thing. For instance, if `x[i]` is Poisson with mean `a[i]`, then `sum( (x - a)**2 / a )` is asymptotically chi-squared (i.e., the agreement is better the bigger all the entries of `a` are). However, `sum(x)` will usually not equal `sum(a)`.

But, maybe this is a UI issue, not a statistical issue - often if someone passes in observed and expected vectors that don't match in sum, then they're likely making a mistake, since (maybe?) the usual use case for chi-squared is having equal sums? I would have voted to not make this change, in any case, but haven't thought through the bigger picture.

**Comment by petrelharp** [comment]
Makes sense. If you'd like to open a new issue about this, tag me and I'll add some support.

**Comment by petrelharp** [comment]
True! The way R deals with this is to throw a warning if the minimum count is smaller than something.

**Comment by mdhaber** [comment]
@petrelharp Thanks for providing this example. It's a shame this was not available three years ago!

I can confirm that under the null hypothesis that the `f_obs[i]` are observations of Poisson distributions with expected values `f_exp[i]`, the empirical distribution of the chisquare statistic appears to match a chi-squared distribution with `len(f_exp)` degrees of freedom. Therefore, one could perform a valid test of _this_ null hypothesis using `scipy.stats.chisquare` with `ddof = -1`.

<details>

(locally disabled the error in order to run this test)

```python3
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

rng = np.random.default_rng(238459349658245693)

# Simulate the empirical distribution of the test statistic under the null
# hypothesis that `f_obs[i]` is drawn from a Poisson distribution with mean
# `f_exp[i]`.
f_exp = rng.uniform(1000, 2000, size=10)
X = stats.poisson(f_exp)
N_samples = 100000
f_obs = X.rvs(size=(N_samples, len(f_exp)), random_state=rng)
edist, _ = stats.chisquare(f_obs, f_exp, axis=-1)   # compute the test statistic

# Under the null hypothesis, the asymptotic distribution of the test statistic
# is chi2 with df = number of categories - 1 - ddof.
# Plot the empirical distribution against the asymptotic distribution.
ddof = -1
df = len(f_exp) - 1 - ddof
x = np.linspace(0, np.max(edist), 100)
plt.plot(x, stats.chi2(df=df).pdf(x))
plt.hist(edist, bins=50, density=True)
plt.legend(['asymptotic distribution', f'empirical distribution, {N_samples} samples'])
plt.xlabel('statistic')
plt.ylabel('probability density')
plt.xlabel('statistic')
plt.ylabel('probability density')
plt.show()
```

</details>

However, I do not think this null hypothesis is equivalent to the null hypothesis indicated in the documentation of [`scipy.stats.chisquare`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chisquare.html).

> The chi-square test tests the null hypothesis that the categorical data has the given frequencies.

So I would suggest that the function is not simply _wrong_ to implement the check: unless `sum(f_obs)` is close to `sum(f_exp)`, the p-value would not accurately approximate the probability under the documented null hypothesis of observing a sample with such an extreme value of the statistic. This is illustrated by the simulation in https://github.com/scipy/scipy/issues/12282#issuecomment-870870310.

> But, maybe this is a UI issue, not a statistical issue - often if someone passes in observed and expected vectors that don't match in sum, then they're likely making a mistake, since (maybe?) the usual use case for chi-squared is having equal sums? I would have voted to not make this change, in any case, but haven't thought through the bigger picture.

Yes! Even users who have come to report this "bug" have had the observed and expected sums unequal by accident, e.g. https://github.com/scipy/scipy/issues/14298#issuecomment-1031901653. The main argument against the error so far has been that the null distribution holds whether or not the observed and expected frequencies have the same sum (e.g. https://github.com/scipy/scipy/issues/14298#issuecomment-869187738), but it was unclear how to reconcile this assertion with simulation (https://github.com/scipy/scipy/issues/12282#issuecomment-870870310).

However, now there seems to be a use case for the function that does not require `sum(f_exp) == sum(f_obs)`, so we can consider changing the documentation and interface to allow this sort of test. @sam-data-guy @WarrenWeckesser @josef-pkt thoughts in light of this information?

**Comment by josef-pkt** [comment]
I did not go through all the details.

It looks to me that this is a different hypothesis test that also uses a asymptotic chisquare distribution.
`stats chisquare` and `power divergence` are GOF test for distributions with finite support (finite number of cells).
The aggregation is over cells or support points.

There are many other hypothesis tests where the test statistics are asymptotically chisquare distributed that don't fit into the (gof) "chisquare_test" case.

> For instance, if x[i] is Poisson with mean a[i], then sum( (x - a)**2 / a ) is asymptotically chi-squared

This looks to me like a dispersion test for Poisson and not a test on observed frequencies.
AFAIR, misusing `stats.chisquare` here only works for poisson because variance is equal to mean. It would not work for other distributions (denominator would be another function of `a`).

For example
statsmodels has several excess dispersion tests for Poisson regression and separate tests to compare observed with expected frequencies:
https://www.statsmodels.org/dev/examples/notebooks/generated/postestimation_poisson.html#Diagnostic

IMO, `stats.chisquare` should stay restricted to the gof chisquare test based on frequencies, and in that case observed and expected frequencies have to match.

(A generic test for test statistics that are asymptotically chisquare distributed would be possible. However it's not very useful if the user still has to provide the computation for the test statistic and provide the degrees of freedom. Similar would apply for generic tests that are asymptotically normal, t or F distributed. It would be mainly helper functions for the surrounding code like input and output handling.
)

**Comment by mdhaber** [comment]
> It looks to me that this is a different hypothesis test that also uses a asymptotic chisquare distribution.

Yes. It tests a different null hypothesis. 

> There are many other hypothesis tests where the test statistics are asymptotically chisquare distributed that don't fit into the (gof) "chisquare_test" case.

Of course. We have some in SciPy.

> It would not work for other distributions

Not in general, no. 

> A generic test for test statistics that are asymptotically chisquare distributed would be possible. However it's not very useful if the user still has to provide the computation for the test statistic and provide the degrees of freedom...

We wouldn't do that. There is not much value added. We have talked about having a standard framework like this internally rather than every test re-inventing the wheel , and have added infrastructure over time, but we would not offer it publicly. 

The difference here is that both the statistic and the null distribution are essentially the same. Even the argument names `f_obs` and `f_exp` might make sense (if the frequency `f` is taken to be the number of events that occur within an internal of time...). The only difference is the `ddof`, which is already available as a parameter.

> IMO, stats.chisquare should stay restricted to the gof chisquare test based on frequencies

OK, opinion noted. Thanks!

**Comment by josef-pkt** [comment]
> The difference here is that both the statistic and the null distribution are essentially the same. Even the argument names f_obs and f_exp might make sense (if the frequency f is taken to be the number of events that occur within an internal of time...). The only difference is the ddof, which is already offered as a parameter.

The derivation and explanation is completely different.
e.g.

I think chisquare docstring should specify that it is **Pearson** chisquare test.

AFAICS, the above test for Poisson is based on a squared z-test for the mean.
It's not a GOF test, i.e. it does not test the distribution itself.

A rewritten docstring to include this case sound messy.
("BTW, the test can also be used for Poisson mean test", I guess assuming a[i] is specified by the null hypothesis)

**Comment by mdhaber** [comment]
> It's not a GOF test, i.e. it does not test the distribution itself.

I haven't seen any claims to the contrary. Why do you mention it?

> A rewritten docstring to include this case sound messy.

It would appear as a single sentence in the notes. 

Note that (founded or not) there have been more complaints about this error message than pretty much any issue I've seen. I'm +0.75 on a change because while it would formally acknowledge that the same function can be used for a very different and quite specific purpose, this is what many users seem to want.

**Comment by HDembinski** [comment]
> AFAICS, the above test for Poisson is based on a squared z-test for the mean. It's not a GOF test, i.e. it does not test the distribution itself.

It is a gof test if you have Poisson distributed observations `a` and a model which predicts their expectation values `x`. Tests like this are common in particle physics, where almost all experiments are fundamentally counting experiments. We observe outcomes that can be put in categories that have given fixed frequencies, but the total number of outcomes is also unknown and random, because we run our experiments for a fixed time rather than until a fixed number of outcomes is collected. Mathematically, this means one has to fold a Poisson for the total number of outcomes with a multinomial distribution, which reduces to a Poisson distribution for each individual outcome (which is nice, because Poisson is much easier to handle than multinomial).

**Comment by josef-pkt** [comment]
How does the poisson arrival rate enter the test?
The arrival rate goes away when we use multinomial (poisson conditional on total count), but not when we go the other direction.

AFAICS after some literature search, you still need some adjustment or normalization, either of expected or observed counts.

Also based on some references that I only skimmed, there is a bias in the total number of counts using Pearson or Neyman chisquare test (but I did not try to figure out the details. It's very difficult for me to find references with the background statistical theory for the poisson histogram case.)

Also it **seems to me** that it is still only a test for the conditional distribution, and not a test that includes the poisson arrival assumption. (gof for the conditional distribution, but not gof for the multivariate count distribution.)

(But I'm giving up on this after 2 to 3 hours of literature search without finding specific answers.)

**Comment by petrelharp** [comment]
I don't have the energy for a length discussion here, but here's a few points:

1. Pearson's chi-squared test is an approximate test, meaning that the distribution of the test statistic is only asymptotically chi-squared, as the sample size goes to infinity. I don't know of any reason (other than I guess historical priority?) that makes extracting a p-value from the chi-squared statistic for Multinomial counts with known total more correct than doing the same thing for Poisson counts. Both are approximate, valid, and useful.

2. Consider the test applied to the Poisson case: conditional on the total number of observations, the partition of observations into categories is Multinomial. So, a way to use `stats.chisquare` and avoid the error would be to renormalize the expected counts so they sum to the total number of observed counts. This is a slightly different test statistic, but I'd be pretty sure it's equivalent in practice.

3. On the docstring:

>   The chi-square test tests the null hypothesis that the categorical data has the given frequencies.

I don't think we should look to this docstring as the definitive account for what this function should do, because as written it doesn't literally make sense. (That sounds too harsh - I totally know what it means, and writing docs is hard.) We're not testing whether the data "has" the given frequencies - there's only one set of frequencies the data has, and that's just their frequencies - we're testing whether the (hypothesis is reasonable that) the data came from a Multinomial distribution with the given frequencies.

4. The way [R handles this](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/chisq.test.html) (which I'd put a very strong prior on being the Right Way to Do It) is that if you're doing a goodness-of-fit test you pass in not expected counts but a vector of frequencies it expects to sum to 1; so to do the Poisson case you'd do like `chisq.test(x, p=x_means, rescale.p=TRUE)`; if you do this then it rescales `x_means` to sum to 1 for you, which is equivalent to doing the procedure I describe in (2) above.

So, I guess another proposal (and consistent with what R does) would be to have an option that rescales the expected counts so their sum equals the observed counts (and defaults to False).  (Maybe this got proposed above and I missed it; sorry if so.)

**Comment by HDembinski** [comment]
I agree with @petrelharp that the chi-squared test is approximate for categorical data which follows a multinomial distribution and is also approximate for independently Poisson distributed data. In either case, the test statistic is only asymptotically chi-square distributed. That means applications of this test to both kinds of data are equally valid.

A priori, I **doubt** that normalizing the observed frequencies to 1 prior to computing the test statistic is improving the rate of convergence. Perhaps that is true, but I would like to see at least empirical proof in some toy experiments, because theoretically it is not obvious to me.

Details:

For the test to be exact, the residuals $(O_i - E_i)^2/(V_i)$ must me independently standard normally distributed, where O is the observation, E is the expectation, and V is the true variance of O. These conditions are violated in different ways for multinomial data (observed frequencies of categorical data) and Poisson distributed data in finite samples.

Application to multinomial distributed data (observed frequencies):
* $V_i$ is not known, we replace it with $E_i = N p_i$, which is not even asymptotically equal to the expected variance $N p_i (1 - p_i)$ for multinomially distributed data. Instead, we compensate for the missing factor $(1 - p_i)$ by comparing the test statistic with the chi-square distribution for K - 1, if we have K categories.
* The residuals are not independent, because of the constraint $\sum O_i = N$. The covariance for two categories i and j is $-N p_i p_j$.
* Even if we had the correct $V_i$, the distribution of the residuals is not normally distributed if the sample size is finite.

Application to Poisson distributed data:
* $V_i$ is not known either, we replace it again with $E_i$, the expectation of the Poisson distribution. This time, we actually use the expected variance, and we don't have to compensate for correlations or missing factors in the variance, so we use K instead of K-1 when we compare the test statistic with the chi-square distribution.
* The residual are indeed independent of each other. The covariance of observations in different categories is zero.
* The distribution of the residuals is not normally distributed if the sample size is finite.

From that analysis, I don't see why always normalizing the input to frequencies would fare better in this test.

**Comment by HDembinski** [comment]
Related: I recently studied how quickly different asymptotically chi-square distributed test statistics converge to the asymptotic limit in toy experiments on Poisson distributed data [here](https://hdembinski.github.io/posts/gof_test_statistic.html)

**Comment by josef-pkt** [comment]
> Although practicality beats purity

I think now a keyword option for the poisson case without the equal total frequencies would be okay.
(something like equal total frequencies only holds in expectation, AFAIU)

**Comment by mdhaber** [comment]
```
f_sum_check : bool, default: True
    Whether to perform a check that `sum(f_obs) - sum(f_exp) == 0`. If True, raise an error when the relative difference exceeds `1e-8`.
```
Somewhere in the notes: 
```
This function may also be used to test the null hypothesis that ``f_obs[i]`` is Poisson-distributed with expectation ``f_exp[i]``. In this case, set ``ddof=-1`` and ``f_sum_check=False``.
```
?

**Comment by josef-pkt** [comment]
@HDembinski 

> Application to multinomial distributed data (observed frequencies):

to the derivation:
The proof for multinomial chisquare test takes the covariance between cells/bins into account
see the above math.stackexchange link
https://math.stackexchange.com/questions/839940/proof-of-pearsons-chi-squared-test

that is, the Pearson chisquare test is derived using the correlated multivariate version of the chisquare distributed test statistic, and not under independence as in the Poisson case.


I'm not clear anymore what the suggestion here is

- allow a Poisson derived chisquare test (unequal total counts) additional to standard Pearson chisquare test
- automatically impose that total counts are equal by possibly adjusting expected to the total observed count (as in R)

AFAIR we discussed the second option before and rejected it because it hides programming mistakes
Currently it is assumed that the user adjusts expectations so that total counts match.

My current standard usage is based on the probabilities pmf, and using observed N (conditioning on it).
`expected = pmf * observed.sum()`

(The bugs that I had in the past was that pmf.sum() < 1 because of truncation of upper tail in, for example, Poisson and similar when doing gof test that data is poisson distributed.)

**Comment by josef-pkt** [comment]
One more background to conditional test, e.g. conditional on total observed counts as in Pearson chisquare

The most common reason for using conditional hypothesis tests is to remove the effect of a nuisance parameter, so the test statistic is not affected by needing assumption for or having to estimate the nuisance parameter.

In this case
The Poisson version depends on the total poisson arrival rate. So expected frequencies depend also on the estimation of or prior information  about the poisson rate. If it has to be estimated, then it is an additional source of uncertainty.

The multinomial Pearson chisquare test does not depend on any arrival rate, random total sample size, so it is agnostic to how that was generated in the test sample.

(For binomial counts and similar, there is literature and debates whether conditional or unconditional hypothesis tests are "better".)

**Comment by mdhaber** [comment]
> I'm not clear anymore what the suggestion here...

I'd expect auto-normalizing counts is going to be even more contentious based on previous discussions, so I'd suggest that we leave that alone here.

The concrete suggestion is to add https://github.com/scipy/scipy/issues/12282#issuecomment-2405176728.

**Comment by josef-pkt** [comment]
(kind of interesting)

looking a bit at the simulations and iminuit

The last part of https://hdembinski.github.io/posts/gof_test_statistic.html
shows that the test is sensitive to having a good estimate of the average or total arrival rate.

This is not a problem if the overall sample size is large (and an appropriate estimator is used). But I guess it will be a lot more noisy in small total samples (e.g. rare events where sample size might be very small)

(aside I found a related 2015 statsmodels issue for histogram fitting)

```
        m = Minuit(lambda mu: cost.chi2(n, mu ** 0.5, mu), mu=mu)
        m.migrad()
        assert m.valid
        yp.append(m.fval)
```

estimating overall parameters (that depend on total count N) is not possible with current scipy chisquare because N has to match.

aside
https://scikit-hep.org/iminuit/reference.html#iminuit.cost.poisson_chi2
states that `sum(mu) == sum(n)`
which AFAICS is not imposed and cannot or does not need to hold for fitting mu with this cost.

AFAICS the simulations never impose `sum(mu) == sum(n)`, it only holds in expectation.
AFAIR, this sum constraint would hold for the poisson MLE estimate for mu.

**Comment by HDembinski** [comment]
Thank you for reading my write-up.
* In my study, I never impose `sum(mu) == sum(n)`, it only holds in expectation. Even so, Pearson's test statistic works extremely well, even for an experiment where the average count per category is 1, so the distribution of the observations in each category is not normal at all, but I am using lots of categories in that experiment. That Pearson's chi-square still works so well surprised me quite a bit, but I guess it can be expected due to the central limit theorem.
* I compute the test statistics exactly like they are defined in the beginning of the article. Since I am considering a counting experiment where the total number of events is a random variable, I do not compute frequencies at all, I just compare the observed counts with the expected counts per bin, but that is mathematically the same as $(O - p N)^2/pN$. They are then compared to a chi-square distribution with $m$ degrees of freedom, where $m$ is the number of categories. In those toy examples, where I estimate a parameter (the Poisson rate for a category), I use $m - 1$.
* You are right that having an unbiased estimation is important. One can show that the maximum-likelihood estimator is unbiased even for finite samples if the model is linear, that is not the case if you use Pearson's or Neyman's statistic (shown here https://inspirehep.net/literature/1683309).

> aside
https://scikit-hep.org/iminuit/reference.html#iminuit.cost.poisson_chi2
states that sum(mu) == sum(n)

That is not written in the docs.

**Comment by josef-pkt** [comment]
This reminds me of the discussion we had for fixing residual scale in linear or nonlinear regression in physics, astronomy, ...

In the regression with fixed constant, chi2 assumes that also the variance (of measurement, observation or model) is correctly specified by the model.

In the context here, chi2 assumes that the total arrival rate (random N) is correctly specified (or can be efficiently estimated).
as far as I now understand:
The standard pearson chi2 is a gof test for the distribution (sum to 1).
while using the poisson model for chisquare test is a hypothesis test for the count "measure" (not adding up to 1) which includes assumptions about arrival rate distribution.

This discussion was pretty helpful to me.

aside not clear to me:
Does the usage of count chisquare rely on the poisson assumption?
For example what happens if the arrival distribution is Negative Binomial with over dispersion compare to Poisson.
The average and total arrival rate can still be consistently estimated with Poisson.
But I guess that the excess dispersion will distort the chisquare statistic for counts.
However, I'm not sure the multinomial chisquare tests works either because the distribution of independent NB bin counts conditional on N is not multinomial, AFAICS. (Or bin counts are not independent of each other anymore if conditional distribution is multinomial, i.e. we also need to give  up independence across bins in the counts.)

**Comment by josef-pkt** [comment]
@mdhaber 

I think your proposal is fine https://github.com/scipy/scipy/issues/12282#issuecomment-2405176728
Maybe keyword can be shortened to `sum_check`.
A bit more information about the poisson case might be useful in the docstring, but I don't have a strong opinion.

**Comment by mdhaber** [comment]
@HDembinski do you have a reference that the distribution of the Pearson statistic is chi-squared with $N$ (rather than $N-1$) degrees of freedom? I understand that this is the case when the variance of the Poisson distributions is not estimated; I'm looking for a reference for the documentation.

**Comment by HDembinski** [comment]
I don't have a reference at hand, but it follows from the derivation for Poisson distributed data, which one can do analog to [the derivation for multinomial data](https://math.stackexchange.com/questions/839940/proof-of-pearsons-chi-squared-test) that @josef-pkt posted.

I will mostly follow the notation of that proof, but note that it makes a mistake in using the same letter $n$ for the number of categories and the total number of events. I will use $N$ for the **total number of expected counts**. In a Poisson experiment, the total number of events is a Poisson distributed random number around $N$.

In a counting experiment where observations $O_i$ are Poisson distributed, and $Z_i = \frac{(O_i - E_i)^2}{E_i}$, the $Z$ are standard normal in the asymptotic limit. The covariance matrix $\Sigma$ of the $Z$ vector is the identity matrix. In the original Pearson notation, we would replace $E_i$ with $N p_i$, $N = \sum_i E_i$ and $p_i  = E_i/N$.

Since $\Sigma$ is the identity matrix, the number of eigenvalues is $n$, not $n-1$, a consequence of the lack of correlations. In case of multinomial data, one can predict one of the observations if ones know all the others, from the constraint $\sum_i O_i = N$. That's not possible if all $O_i$ are Poisson distributed.

The rest is trivial: $f(Z) = Z_1^2 + \dots + Z_n^2$ is chi-square distributed with $n$ degrees of freedom, this follows directly from the definition of the chi-square distribution.

**Comment by HDembinski** [comment]
@mdhaber Since you probably do not want to put a proof into the docs, you could cite the Wikipedia article on degrees of freedom
https://en.wikipedia.org/wiki/Degrees_of_freedom_(statistics)
or Fisher who discusses this subject for a contingency table (I got the reference from the Wikipedia article)
https://www.jstor.org/stable/2340521?origin=crossref

**Comment by HDembinski** [comment]
> aside not clear to me:
> Does the usage of count chisquare rely on the poisson assumption?

Yes, because the Poisson assumption allows us to know the expected variance of the counts in each category and because it becomes normal in the asymptotic limit. We need both.

However, it does *not* depend on the distribution which puts events randomly into categories. That can be anything, as long as those outcomes are identically and independently distributed (i.i.d.). That's why the chi-square test is so widely useful, it is distribution-free wrt that process. Under the i.i.d. assumption, there are only two options, you either have a Poisson distribution per category if you experimental design does not fix the total number of counts, or you have a multinomial distribution if you experimental design does fix the total number of counts.

> For example what happens if the arrival distribution is Negative Binomial with over dispersion compare to Poisson.

That cannot happen in practice (see above), but if it would then the chi-square would be inadequate, because the $Z_i$ are then not even asymptotically standard normal.

**Comment by petrelharp** [comment]
>  For example what happens if the arrival distribution is Negative Binomial with over dispersion compare to Poisson.

I think the generic recommendation for cases where the total number of observations is from some other distribution would be to scale the total expected counts to match the observed expected counts, so we're back to the fixed-total-size case. (That's probably just as good in practice for Poisson as well; the proposed option to allow these to differ is for convenience and to avoid confusion.)

**Comment by HDembinski** [comment]
@petrelharp I agree to the first part, but if the total number of events is actually Poisson distributed, as it always is in particle physics at least, I think that **not** doing the normalization helps the test statistic to converge to the asymptotic regime, because one is adding one more random number compared to the normalized case. That effect may be small, but it should be there.

**Comment by josef-pkt** [comment]
> because one is adding one more random number compared to the normalized case. That effect may be small, but it should be there.

but it is also adding (at least) one more parameter, so the general direction does not look clear to me from theoretical reasons (again depending on how well the extra parameter is estimated).

**Comment by HDembinski** [comment]
That should have a neutral effect.
