### ISSUE TITLE
ndimage.rotate deletes values

### ISSUE THREAD

**Issue by himat** [scipy/scipy#12300]
My issue is about https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.rotate.html

#### Reproducing code example:

```
import numpy as np

B = np.ones((3,3,3)) * 2.33
outB = scipy.ndimage.rotate(B, 180, axes=(1,2))
```

Output:
```
>>> B
array([[[2.33, 2.33, 2.33],
        [2.33, 2.33, 2.33],
        [2.33, 2.33, 2.33]],

       [[2.33, 2.33, 2.33],
        [2.33, 2.33, 2.33],
        [2.33, 2.33, 2.33]],

       [[2.33, 2.33, 2.33],
        [2.33, 2.33, 2.33],
        [2.33, 2.33, 2.33]]])
>>> outB
array([[[2.33, 2.33, 0.  ],
        [2.33, 2.33, 2.33],
        [2.33, 2.33, 0.  ]],

       [[2.33, 2.33, 0.  ],
        [2.33, 2.33, 2.33],
        [2.33, 2.33, 0.  ]],

       [[2.33, 2.33, 0.  ],
        [2.33, 2.33, 2.33],
        [2.33, 2.33, 0.  ]]])

```
Rotating 0 degrees works fine, but doing it 180 just deletes those corner values every single time for some reason?

#### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.4.1 1.18.4 sys.version_info(major=3, minor=6, micro=10, releaselevel='final', serial=0)
```

**Comment by rfezzani** [comment]
@himat, this is mainly caused by round off errors: [internally](https://github.com/scipy/scipy/blob/v1.5.2/scipy/ndimage/interpolation.py#L741), `ndimage.rotate` uses the sinus of the angle, which is supposed in your example to be 0, but in practice is not:
```python
>>> np.sin(np.deg2rad(180))
1.2246467991473532e-16
```
Moreover, the default `"constant"` boundary mode doesn't help you here. You may "fix" your issue if you change boundary handling mode from `"constant"` to `"reflect"` or `"nearest"`:
```python
>>> from scipy import ndimage as ndi
>>> import numpy as np
>>> 
>>> B = np.ones((3,3,3)) * 2.33
>>> outB = scipy.ndimage.rotate(B, 180, axes=(1,2), mode='reflect')
>>> outB
array([[[2.33, 2.33, 2.33],
        [2.33, 2.33, 2.33],
        [2.33, 2.33, 2.33]],

       [[2.33, 2.33, 2.33],
        [2.33, 2.33, 2.33],
        [2.33, 2.33, 2.33]],

       [[2.33, 2.33, 2.33],
        [2.33, 2.33, 2.33],
        [2.33, 2.33, 2.33]]])
```

**Comment by himat** [comment]
@rfezzani so should I just always use mode='reflect' or are there times when I shouldn't do that?

**Comment by rfezzani** [comment]
It depends on your images, but `"constant"`  is usually not a good choice unless your images are surrounded by a constant value. My preference goes usually to `"nearest"` mode :slightly_smiling_face:.

**Comment by grlee77** [comment]
In the upcoming SciPy 1.6 release, #12721 should fix the small numerical errors for multiples of 90 degree rotations pointed out by @rfezzani.

There is also a proposed "grid-constant" mode in #12776 which would interpolate between the edge values and the constant background, which would also have avoided the issue here if used in place of "constant".
