### ISSUE TITLE
Add nan_policy to stats.zmap

### ISSUE THREAD

**Issue by chrism2671** [scipy/scipy#12403]
`stats.zscore` has a `nan_policy`. `stats.zmap`, being an almost identical function, should probably have the same option.

As an alternative, it might be better to refactor `zscore` in terms of `zmap`, as I think `zscore(x) == zmap(x, x)`.

**Comment by WarrenWeckesser** [comment]
@mdhaber, I see you added this to the list of stats issues to watch.  After working on `zscore` recently, I started looking at `zmap`.  As @chrism2671 pointed out, we can refactor the code so that all the work currently in `zscore` can be done in `zmap` instead, and `zscore` will just call `zmap`.  I'll have a PR for this pretty quickly.

**Comment by WarrenWeckesser** [comment]
I added a note about this enhancement to the [release notes](https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.7.0).
