### ISSUE TITLE
The `whiten` function is racially insensitive needs to be renamed.

### ISSUE THREAD

**Issue by juliusfrost** [scipy/scipy#12446]
The particular method I am pointing to:
https://github.com/scipy/scipy/blob/4c0fd79391e3b2ec2738bf85bb5dab366dcd12e4/scipy/cluster/vq.py#L84-L137

This method serves to normalize inputs before being passed to clustering algorithms. Other methods suggest to use this method first before clustering such as in [k-means](https://github.com/scipy/scipy/blob/4c0fd79391e3b2ec2738bf85bb5dab366dcd12e4/scipy/cluster/vq.py#L316-L458). However, the `whiten` function should be renamed as it does not accurately represent the definition of this function. It is ambiguous and `whiten` does not give users a good understanding that it will make features unit variance. Given current times, a function name like this is racially insensitive. It implies that 'whitening' is 'good' or 'normal' and promotes racial inequality even if implicitly or unintentionally. Even if the term has academically historical meaning, it was most likely arbitrarily decided at conception and must go. 
Therefore, I ask for the community to discuss alternative names and familiarize themselves with common racial microaggressions like this. As a solution, I propose to 1. rename this function to an alternative decided by the community, 2. have the `whiten` function deprecated and redirect to the new function, 3. in the deprecation message, state the reason of deprecation and promote awareness of racial inequality in its message, 4. remove all references to `whiten` function such as in [k-means](https://github.com/scipy/scipy/blob/4c0fd79391e3b2ec2738bf85bb5dab366dcd12e4/scipy/cluster/vq.py#L316-L458) which can be seen through this [search](https://docs.scipy.org/doc/scipy/reference/search.html?q=whiten&check_keywords=yes&area=default).

**Comment by ilayn** [comment]
We had a similar PR before about blacklist and whitelist and we support all of them but this one comes from colored noise as in white noise (similar to light spectrum where spectrum is uniform). There is no black noise exists. 

So let's keep this to things that actually applies. We shouldn't ban the word white, we need to remove the bad connotation.

**Comment by WarrenWeckesser** [comment]
> However, the whiten function should be renamed as it does not accurately represent the definition of this function. It is ambiguous and whiten does not give users a good understanding that it will make features unit variance. 

The terminology "whitening" and the related "white noise" have a well-established meanings:
* [Whitening transformation](https://en.wikipedia.org/wiki/Whitening_transformation)
* [White noise](https://en.wikipedia.org/wiki/White_noise)

**Comment by juliusfrost** [comment]
If unwilling to change the name, there is significant headroom to clarify this in the function documentation. Please consider putting more effort towards a more inclusive environment.

**Comment by matthew-brett** [comment]
@juliusfrost - can you give some idea of what you mean by clarification?   Do you just mean something like " ... whitening (in the sense of white noise)"?

**Comment by ilayn** [comment]
I am also not enjoying this implied guilt to be honest. We are not unwilling to change the name. It just doesn't apply. I would like to see what this headroom is and what can be done. Pull requests are welcome.

**Comment by JesseLivezey** [comment]
An unrelated reason to change the name is that, as far as I can tell, this function does not implement whitening. It looks like it normalizes the features (in the sense of per-feature standard deviation). "Whitening" typically means scaling the singular values of the feature matrix (or eigenvalues of the covariance) to all be 1. This flat eigenvalue spectrum is where the analogy to flattening the power spectrum comes from.

For instance, this is what is done in sklearn's PCA. Just rescaling the features, which is what is happening here, is not whitening.

**Comment by josef-pkt** [comment]
whitening is a pretty generic technical term
In statsmodels we use it to remove correlation and heteroscedasticity (unequal variances) in linear models.
We don't have yet "whitening" and "recoloring" as a methods for some statistics. (first remove correlation, then process, than add it back in.)

**Comment by rgommers** [comment]
> Please consider putting more effort towards a more inclusive environment.

Thanks for asking about this @juliusfrost. I - and I believe most/all SciPy maintainers and regular contributors - definitely desire to make SciPy a project that feels inclusive and welcoming to everyone.

I think most replies so far correctly point out that the `whiten` functions doesn't fall in the category of problematic usages of white/black where "white" implies "good" / "allowed" and "black" implies "bad" / "disallowed". That said, there may be cases that do fall in that category, such as "blacklist". And indeed, I did find one piece of code that uses "blacklist". 

I've seen two sets of opinions expressed by Black people on this bigger discussion of racially loaded terminology (paraphrasing):
1. There are bigger fish to fry - in a time of mass protest and people being physically harmed and arrested, do you need to worry about wording *right now*?
2. These terms have always bothered me, and they should go - that does not prevent any other actions.

Both are of course valid feelings/opinions. I didn't look at these terms in our code base over the past couple of weeks because of (1), but now that the issue has been brought up let's just audit the code base and remove the terms because of (2). I just did that, and I did find "blacklist" usage that can be removed, and no "whitelist" or other problematic "black"/"white" usage. Nor "slave", although of course we have "master" as the default branch name just like the vast majority of other projects.

Here are the next steps I'd like to take:
1. Clarify the docstring of `whiten` in a new PR to close this issue.
2. Move the technical points brought up here about "does this function really implement whitening" to a new issue.
3. Remove the use of "blacklist" in a new PR.
4. Delay dealing with or discussion of changing the default branch from "master" to "main" in our repos. Rationale: this is less clearcut _and is a lot of work_ (e.g. our 290 open PRs against master may all become unmergeable). If GitHub really follows through with making the change and other projects do this renaming on a larger scale, then we will revisit - but now does not seem like the right time.

**Comment by rgommers** [comment]
Okay, I did all those things. Follow-up on potential improvements for `kmeans` with whitening as in "rescale and decorrelate" in gh-12453.

**Comment by rgommers** [comment]
Thanks for the input everyone! If there's things regarding problematic naming I missed, please comment here (or feel free to ping me privately). For follow-up on the technical part of `whiten` / `kmeans`, please use gh-12453.

**Comment by juliusfrost** [comment]
Thank you @rgommers for addressing my concern and many others. Then steps you took mean a great deal to the community and I really appreciate it!

**Comment by hmaarrfk** [comment]
> This flat eigenvalue spectrum is where the analogy to flattening the power spectrum comes from.

To complete the analogy and potentially the historical perspective, in physics, a "white", or uniform, spectrum of light, gives you a color that looks white:
https://en.wikipedia.org/wiki/White#White_light
