### ISSUE TITLE
SciPy 1.9 exception in LSQSphereBivariateSpline

### ISSUE THREAD

**Issue by mrJean1** [scipy/scipy#12469]
The issue is an exception in `SciPy` 1.9.0 which did not occur in earlier versions of `SciPy` ...

```
File "~/PyGeodesy/pygeodesy/heights.py", line ...
    self._ev = scipy.interpolate.LSQSphereBivariateSpline(..., eps=EPS, w=w).ev
 File "~/Library/Python/3.8/lib/python/site-packages/scipy/interpolate/fitpack2.py", line 1549, in __init__
    if w is not None and not (w >= 0.0).all():
TypeError: '>=' not supported between instances of 'list' and 'float'
```
Variable `w` is a list of `float`s ...
 ```
w = [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
```
The exception is due to ...
```
(w >= 0.0).all()
```

**Comment by WarrenWeckesser** [comment]
@mrJean1 thanks for reporting the issue.

It looks like the problem was introduced in https://github.com/scipy/scipy/pull/11736, where additional input validation was added.  The code in `LSQSphereBivariateSpline.__init__()` needs to wrap the inputs with `np.asarray` (e.g. `theta = np.asarray(theta)`) before an expression such as `(0.0 <= theta).all()` is evaluated.

**Comment by mrJean1** [comment]
It is a regression test in [PyGeodesy](https://github.com/mrJean1/PyGeodesy) package upgraded to SciPy 1.9.

**Comment by AtsushiSakai** [comment]
I'm sorry it looks like that my PR #11736 has problems. I will try to fix it.
