### ISSUE TITLE
Scipy Stats distribution benchmarking with other tools

### ISSUE THREAD

**Issue by digitalgemba** [scipy/scipy#12475]
In reference to #12332 , I was trying to compare scipy.stats with the existing software's I have been using. I find discrepancy.  Checked for distribution Rayleigh it was not matching remotely , but to find discrepancy when checking for normal distribution also was surprise.

```
data=[ 2.47228483, -0.29230493,  1.10220029, -0.08600626, -0.37459144, 1.1133235 , -1.82607583,  0.30408785,  0.23567051, -0.0787982 ,-0.24842409, -0.4910925 ,  0.54093486,  0.42452263, -0.02905802,-1.59983977, -1.48241349,  0.67292231,  0.63338949,  0.74185299,-0.45523805,  1.97666648, -0.54898413, -0.56239325,  0.86495812,0.32010477, -1.45307645, -2.51155492, -0.47665564, -0.60190097]

loc,scale=norm.fit(data)
norm.ppf(.50000,loc=loc,scale=scale)
norm.ppf(.00135,loc=loc,scale=scale)
norm.ppf(.99865,loc=loc,scale=scale)
```

As I compare this with other software

![image](https://user-images.githubusercontent.com/66455284/86388639-c4ca1500-bcb2-11ea-8bdb-7e8036f04fdc.png)

Now, where am I going wrong ?

**Comment by WarrenWeckesser** [comment]
`norm.fit()` computes the maximum likelihood estimate (MLE) of the parameters.  You can find the formulas for these estimates at https://en.wikipedia.org/wiki/Normal_distribution#Estimation_of_parameters, and you can easily implement them yourself:

```
In [45]: loc = np.mean(data)

In [46]: scale = np.std(data)

In [47]: loc, scale
Out[47]: (-0.057182977, 1.0601867237129745)
``` 
With these parameter values, we get the results that you show above for the PPF:
```
In [48]: from scipy.stats import norm

In [49]: norm.ppf([0.00135, 0.5, 0.99865], loc, scale)
Out[49]: array([-3.23771876, -0.05718298,  3.1233528 ])
```

Apparently, your Software A and Software B estimate the scale as the *sample* standard deviation of the data--that is, they estimate the scale as the square root of the unbiased estimate of the variance, in which the sum of the squared differences is divided by n-1 instead of n ("Bessel's correction").  You can reproduce this calculation by adding the argument `ddof=1` in the call to `np.std`:

```
In [50]: scale1 = np.std(data, ddof=1)

In [51]: scale1
Out[51]: 1.0783108865596311
```
When this value is used as the estimate of the scale to compute the PPF, the values appear to match the values that you show for Software A and Software B:
```
In [52]: norm.ppf([0.00135, 0.5, 0.99865], loc, scale1)
Out[52]: array([-3.29209083, -0.05718298,  3.17772487])
```
So the difference appears to be in how the scale is estimated. SciPy computes the true MLE, while your Software A and Software B apparently compute the square root of the unbiased sample variance.

Neither result is "wrong".  They are just based on different assumptions.

**Comment by digitalgemba** [comment]
@WarrenWeckesser  
Thanks for the quick and patient  reply.
This was OK for normal distribution. But what is wrong here ?

`data=[0.44292,1.357525,1.900116,0.311004,1.102482,0.558844,0.876003,0.332232,1.262005,1.665766,2.549179,0.24646,0.863003,0.818202,1.984925,0.1489,1.06224,1.299509,0.51641,0.576224,0.920096,1.247763,1.891024,0.630022,0.619264,0.314076,2.098563,0.353651,1.503388,2.979388,1.262727,0.229489,2.249203,0.717882,0.49549,1.743599,0.727911,0.591069,3.28511,2.271326,1.33965,0.099717,1.776226,1.855509,1.952697,1.631046,0.87993,1.643881,1.413064,1.339372,1.746343,0.751736,2.314,1.466445,0.756237,1.009805,2.005607,1.048581,1.599348,1.062822]`

1. Manual Calculations (From Wikipedia)
```
x =((((data)**2).sum())/(2*len(data)))**0.5
1.0058001631077038

n=1
y=((4**n)*(math.factorial(n))*(math.factorial(n-1))*(n**0.5))/(math.factorial(2*n)*((math.pi)**0.5))
1.1283791670955126

sigma=x*y
1.1349239503120014
```
Median(Manual Calculations) : **1.336270833890**

2. Scipy Calculations

```
loc,scale=rayleigh.fit(data)
rayleigh.median(loc=loc,scale=scale)
```
Median (Scipy) : **1.1633470405523323**


3.Software B: Median = **1.35806**

Why difference in values ?


2> How does scipy.stats define Offset ( when the pdf is zero for distributions like Rayleigh , Foldnorm) ?

**Comment by WarrenWeckesser** [comment]
> Why difference in values ?

You haven't told us what "Software B" is, and you haven't shown how you used Software B get that value of the median.  We have no idea what assumptions are made by Software B in its calculations.  For example, does Software B use a two-parameter Rayleigh distribution like SciPy does?  Note that the Rayleigh distribution on wikipedia has just one parameter, σ, which corresponds to the `scale` parameter in `rayleigh`.  `rayleigh` in SciPy also has a `loc` (i.e. location) parameter.  To get the SciPy calculation to match your manual calculation, you must fix the location parameter to be 0:

```
In [24]: rayleigh.fit(data, floc=0)                                                                                      
Out[24]: (0, 1.0057800610116858)
```

The scale is the second value.  It does not match the manual calculation exactly, because of (normal) imprecision in the numerical optimization routine.  (Note that work is in progress to make `rayleigh.fit` use the explicit formula: https://github.com/scipy/scipy/pull/12097. When that is completed, we expect the `fit` method will provide more accurate results.)

> How does scipy.stats define Offset 

I think what you are referring to is, in fact, the `loc` (i.e. location) parameter.  This is simply another parameter in all the continuous distributions in SciPy.  It is just a translation along the `x` (i.e. quantile) axis of the PDF.

**Comment by digitalgemba** [comment]
Thanks for the feedback. 


1. As per **NIST manual** , https://www.itl.nist.gov/div898/handbook/eda/section3/eda3669.htm, mentions parameter estimation for scale and shape. 

```
shape,loc,scale=lognorm.fit(data,floc=0)
print(shape,loc,scale)

0.3757333642446184 0.0 1.424025217070406

np.log(scale)

0.35348752144984646
```
Manual Calculations

```
muhat=(np.log(data)).sum()/(len(data))
sigmahat=np.sqrt((np.square(np.log(data)-muhat).sum())/(len(data)))
print(muhat,sigmahat)

0.35348752144984646 0.3757333642446184
```

And it matches!

2. **Evans, Hastings, and Peacock**  Statistical Distributions, 4th. Ed., John Wiley and Sons. do not discuss on location parameter.


_**My Question**_

- How does scipy estimate location parameter for lognormal ? 
- References for estimation method.

**Comment by mdhaber** [comment]
> How does scipy estimate location parameter for lognormal ?

If the location parameter is fixed, SciPy does not use a formula; instead it resorts to numerical optimization. It uses `optimize.fmin` to find the values of `loc`, `scale`, and `shape` such that the negative of the log-likelihood is minimized. Results may vary because it is not guaranteed to find a global minimum; at best it can hope to find a local minimum, which may or may not be the global minimum.

> References for estimation method.

Information about numerical optimization in SciPy is here.
https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html

For more information, please see [_continuous_distns.py](https://github.com/scipy/scipy/blob/master/scipy/stats/_continuous_distns.py) for the `fit` method in `class lognorm_gen`, and [_distn_infrastructure.py](https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py) (search for `def fit`) for the numerical optimization.
