### ISSUE TITLE
signal.firls should default to fs=1

### ISSUE THREAD

**Issue by GregoryEAllen** [scipy/scipy#12481]
`signal.firls` has been changed to default to `fs=2`. It previously defaulted to `fs=1` (when I contributed it), but at some point `firls` got significantly rewritten and `fs` changed. 

The convention throughout is `fs=1`. See `signal.bilinear`, `signal.remez`, `signal.welch`, `signal.csd`, etc.

This is a behavior-changing difference, but it is undoing what was a behavior-changing difference. I discovered it when it broke previously working code.

**Comment by larsoner** [comment]
Argh, that's not good. @GregoryEAllen when did you notice this behavior change? Possibly when upgrading from <= 0.19 to >= 1.0?A quick look at [git blame](https://github.com/scipy/scipy/blame/master/scipy/signal/fir_filter_design.py#L966) makes it seem like https://github.com/scipy/scipy/commit/355938450f4e4a72794899f509b83eb1951c84d6 / #7814 was the culprit, but this was in even 1.0 from almost 3 years ago. Other more recent changes are just to make the `linalg.solve` more robust, so it seems like this change is at least 3 years old.

Given that `firls` only appeared 4 years ago and this bug was introduced 3 years ago, I'd be hesitant to change its behavior since either way someone's code will be broken, and at least on `master` hopefully the behavior is consistent with all other functions.

**Comment by skresearcher** [comment]
It looks like `firls` never had `fs=1` when it was released. `firls` was initially released in #5989 with `nyq=1`, which effectively makes `fs=2`. #5989 was based off of @GregoryEAllen's PR #4836, which had `fs=1` but was never merged.

**Comment by larsoner** [comment]
Ahh okay, so `firls` in SciPy always had `fs=2` effectively, so indeed we shouldn't change it.

Quoting https://github.com/scipy/scipy/pull/7814#issue-138582451:

> For the FIR filter design functions firls, firwin and firwin2, the default is nyq=1.0 (equivalent to fs=2), while for remez the default is Hz=1 (i.e. fs=1). The functions that currently already use fs all have the default fs=1. Changing the default for the FIR design functions would be a much more disruptive change.

I think the cost of changing these to all be consistent is probably not worth the deprecation cycle. But if the consensus becomes that we should, we can reopen this and re-title it, or just have a new issue for it.
