### ISSUE TITLE
Picture rotated 180 degrees and rotated -180 degrees should be consistent

### ISSUE THREAD

**Issue by Lee-nju** [scipy/scipy#12543]
Regarding the picture, I think that no matter where the center of rotation is, the result after rotating 180 degrees and rotating -180 degrees should be the same, that is, the obtained two-dimensional matrix should be consistent, but the result does not seem to be the case.

#### Reproducing code example:

```
from scipy import ndimage, misc
import matplotlib.pyplot as plt
fig = plt.figure(figsize=(10, 3))
ax1, ax2, ax3 = fig.subplots(1, 3)
img = misc.ascent()

img_180 = ndimage.rotate(img, 180)
img_reverse_180 = ndimage.rotate(img, -180)
ax1.imshow(img, cmap='gray')
ax1.set_axis_off()
ax2.imshow(img_180, cmap='gray')
ax2.set_axis_off()
ax3.imshow(img_reverse_180, cmap='gray')
ax3.set_axis_off()
fig.set_tight_layout(True)
plt.show()
print(img.shape)
print(img_180.shape)
print(img_reverse_180.shape)
print(img_180 == img_reverse_180)
```
![image](https://user-images.githubusercontent.com/43922456/87447649-69424480-c62d-11ea-985c-a0c0ae7714b9.png)

#### Error message:

```
(512, 512)
(512, 512)
(512, 512)
[[ True  True  True ... False False False]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [False  True  True ...  True  True False]
 [False  True  True ...  True  True False]
 [False  True  True ... False False  True]]
  ...
```

#### Scipy/Numpy/Python version information:

import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.5.0 1.18.5 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)

**Comment by grlee77** [comment]
Thank you for reporting the issue,

This seems to be a floating point precision issue. Internally, the flip angle is converted to radians and a rotation matrix is formed.  The true value for the sine of 180 (or -180) should be zero, but the internal code converts to radians with finite precision.

`np.sin(np.deg2rad(180))` gives a value of 1.22464e-16 for +180 but -1.22464e-16 for -180. I think this precision issue is leading to the small numerical difference in the result.

I think the only way around this would be to add some custom code path for angles that are multiples of 90 degrees, but I'm not sure it is worth complicating this function for that. There is an existing NumPy function called `rot90` that implements rotations by multiples of 90 degrees. `rot90` is also more efficient than the more general `ndimage.rotate` because it can rely on only transpose and/or flipping operations without any need for interpolation. 

You can verify `rot90` gives a consistent result for +180 or -180 by adding the following to your example above:

```Python
import numpy as np
assert np.all(np.rot90(img, 2) == np.rot90(img, -2))
```

**Comment by ewmoore** [comment]
If that's the full issue, does switching to using `special.sindg` and `special.cosdg` resolve this?  
```
In [1]: import numpy as np

In [2]: from scipy import special

In [3]: np.sin(np.deg2rad([180, -180]))
Out[3]: array([ 1.2246468e-16, -1.2246468e-16])

In [4]: special.sindg([180, -180])
Out[4]: array([-0.,  0.])

In [5]: np.cos(np.deg2rad([90, 270]))
Out[5]: array([ 6.1232340e-17, -1.8369702e-16])

In [6]: special.cosdg([90, 270])
Out[6]: array([-0.,  0.])
```

**Comment by ewmoore** [comment]
See gh-12721.   Using `special.sindg` seems to work at least for the case here.

**Comment by Lee-nju** [comment]
Thank you very much!


开 2020年8月15日 在 上午3:57:54, Eric Moore (notifications@github.com) 写到:

See gh-12721. Using special.sindg seems to work at least for the case here.

**Comment by Lee-nju** [comment]
Thank you for your detailed explanation and the code just works!


开 2020年8月15日 在 上午1:54:32, Gregory R. Lee (notifications@github.com) 写到:

Thank you for reporting the issue,

This seems to be a floating point precision issue. Internally, the flip angle is converted to radians and a rotation matrix is formed. The true value for the sine of 180 (or -180) should be zero, but the internal code converts to radians with finite precision.

np.sin(np.deg2rad(180)) gives a value of 1.22464e-16 for +180 but -1.22464e-16 for -180. I think this precision issue is leading to the small numerical difference in the result.

I think the only way around this would be to add some custom code path for angles that are multiples of 90 degrees, but I'm not sure it is worth complicating this function for that. There is an existing NumPy function called rot90 that implements rotations by multiples of 90 degrees. rot90 is also more efficient than the more general ndimage.rotate because it can rely on only transpose and/or flipping operations without any need for interpolation.

You can verify rot90 gives a consistent result for +180 or -180 by adding the following to your example above:

import numpy as np
assert np.all(np.rot90(img, 2) == np.rot90(img, -2))
