### ISSUE TITLE
scipy.linalg.interpolative.estimate_rank is quite unreliable

### ISSUE THREAD

**Issue by touqir14** [scipy/scipy#12593]
Even though the [documentation](https://scipy.github.io/devdocs/generated/scipy.linalg.interpolative.estimate_rank.html#scipy.linalg.interpolative.estimate_rank) of ```scipy.linalg.interpolative.estimate_rank``` states "If A is of type numpy.ndarray, then the output rank is typically about 8 higher than the actual numerical rank.", the following code snippet highlights its unreliability:

```python
import numpy as np
from scipy.linalg import interpolative

def ID_ranks(shape, runs, eps):
    np.random.seed(0)
    for i in range(runs):
        A = np.random.rand(shape[0], shape[1])
        Ap = A @ A.T
        estimated_rank = interpolative.estimate_rank(Ap, eps)
        print("True rank:", min(shape), "Estimated rank from Interpolative Decomposition:", estimated_rank)

ID_ranks([100,52], 10, 1e-13)
ID_ranks([1000,500], 10, 1e-13)
```
For the 100x52 case, ID's output is always 100 and this is the case for every row value >= 52. For the 1000x500 case, ID's output is always 1000 and this is the case for every row value >= 500. No matter how small ```eps``` I set, the results are always the same.

**Comment by ilayn** [comment]
You have to set `eps` higher not smaller; try something like 0.001 or something higher. There must be an expression of what `eps` should be taken as a sensible value somewhere but I can't remember it. However this eps is not the smallest SV cutoff value as in `matrix_rank` so you have to take that into account. And

**Comment by touqir14** [comment]
I see. Tried out multiple larger eps values to get the estimated rank to be close enough to the true rank and it seems the sweet spot is quite narrow. Also, this sweet spot noticeably moves around as the true rank is varied. What does this eps actually represent?

**Comment by ilayn** [comment]
If I remember correctly it should be the reflected vector norm under Householder trafo scaled by maximum singular value.

**Comment by ilayn** [comment]
I checked this once again and I think this is unfortunately inherent to the algorithm that one has to have a good guess of where the rank cutoff should lie. In the examples the numbers of the array are huge hence 1e-13 is driving the algorithm to quit under the impression that the array is full rank since the pivot never goes below that number. But choosing larger eps as you noted leads to a somewhat acceptable result. 

I suggested to close this issue in the linked PR but feel free to object if you think there is a way to remedy this situation.
