### ISSUE TITLE
sparse SVD cutoff

### ISSUE THREAD

**Issue by ogauthe** [scipy/scipy#12629]
Hello,

[scipy.sparse.linalg.svds](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.svds.html#scipy.sparse.linalg.svds) introduces a cutoff in singular values. Values smaller than `eps*f*largest_singular_value` are replaced by zero,   where `eps` is the machine precision value of the datatype of the input and `f ` is `1e3` for single precision and `1e6` for double precision (hence `cond = 2.220446049250313e-10` for double and `cond = 0.00011920928955078125` for single precision). This is done at https://github.com/scipy/scipy/blob/v1.5.2/scipy/sparse/linalg/eigen/arpack/arpack.py#L1875-L1879.

First problem is this feature is not documented. Second is these values are not that small and are hard-coded: it is not possible to change them. They appear to come from [scipy.linalg.pinvh](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.pinvh.html), however there the cutoff is documented and can be specified. There is a `tol` argument in the API that is used to compute the eigenvalues of `A.H @ A` but has no effect on the cutoff.

I think `tol` could also be used as a cutoff for the singular values as well as a parameter for `eigsh`, or else a `cond` keyword argument could be added.

**Comment by ilayn** [comment]
They are coming from #3719 but `pinvh` recently got changed to more variable expression. Apparently I missed those hardcoded values at the time. But the pinvh cutoff values come from the dense algebra conventions. Sparse arrays don't follow these conventions and I don't know from the top of my head a good source for these values. Maybe Gilbert's or Tim Davis' books have something?

**Comment by gauthe** [comment]
I am not familiar with this literature. I took a quick look at Tim Davis's book, it does not address SVD and I saw nothing about some norm convention.

I note that PR #11829 already deals with small singular values handling. As far as I understand it it should remove the need of a cutoff.

**Comment by ilayn** [comment]
I am not sure how a sparse function can be replaced by its dense counterpart in #11829 . We need to make sure that it doesn't get choked on large arrays.

**Comment by denis-bz** [comment]
[Numerical Recipes p. 795](http://apps.nrbook.com/empanel/index.html?pg=795) says
> A plausible answer to the question "how small is small ?" is to edit in this fashion all singular values whose ratio to the largest is less than 𝑁 (problem size) times the machine precision 

I'd suggest  `max( N, 1e6 ) eps` > 2e-10 with `verbose=1` to print how many got trimmed.
See also [how-much-regularization-to-add-to-make-svd-stable](https://scicomp.stackexchange.com/questions/26763/how-much-regularization-to-add-to-make-svd-stable) on scicomp.stack.

**Comment by ilayn** [comment]
That rule of thumb applies to the dense arrays. Sparse arrays have significantly less arithmetic operations hence needs a different cut-off value.

**Comment by denis-bz** [comment]
@ilayn, why ? Trimming is applied to the spectrum (singular values), and sparse A / dense A.A  have exactly the same spectrum. Or would you have an example where they differ ?

**Comment by ilayn** [comment]
The typical threshold value `max(m, n)*eps` is coming from the error bounds for floating point operations but in sparse arrays you don't perform that many operations if the array has only 1000 nnz entries and the array is a million by million. So having a million in that bound is too conservative.

**Comment by denis-bz** [comment]
@ilayn, could you point me to some real (not random) test cases on the web, with A . AT 10k x 10k or 20k x 20k or so ?  Thanks

**Comment by ilayn** [comment]
@denis-bz What do you mean by "real (not random)" and what is the test we want to have?

**Comment by mgoldeli** [comment]
Please add an option to "scipy.sparse.linalg.svds" to set the "cutoff" parameter to zero or please give the option not the use this cutting off option in svds function. This option is something we need for our python package "pyFBS". We are working on a new filter implementation based on truncated singular value decomposition, so svds. Since "scipy.sparse.linalg.svds" is a very strong tool for calculating a subset of singular values, we are also using it integrated with our python package. But, we need the option which allows us to set the cutoff parameter to zero. I do not want to use the "sophisticated detection of small eigenvalues from pinvh", which is used by "scipy.sparse.linalg.svds" automatically. Please make it used-defined or give the user the option to not use this cutting off the singular values.

**Comment by mgoldeli** [comment]
As I already explained in [#16210](https://github.com/scipy/scipy/issues/16210), I think it is necessary to have this **"cutoff = 0"** option (or a similar implementation) also **for the "arpack" algorithm** 

We have already the matlab implementation of our new svds based filter. **In matlab with svds command**, we are able to **get all the singular values without cutting off the smallest singular values** (Matlab also uses in svds the Arpack algorithm as default). Also **with svds of scipy**, we are able to **get all the singular values, only if we set the cutoff value manually to zero. (Hard-Coded)** Due to this automatic/not-user-defined cutting off of the smallest singular values in svds of scipy, we can not keep the quality level of our new filter implementation. 

That's why, I think this cutoff variable should be user-defined. With this enhancement, scipy will serve the option for its users to have consistent results with matlab, which is a high reliable reference software for such applications like svds.

**Comment by denis-bz** [comment]
Hi @mgoldeli,
[scipy.sparse.linalg.svds](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.svds.html) has a `tol` parameter, default 0 -- is that what you're using ?
How do you check the accuracy of eigvals / eigvecs ?
(Bytheway, _svds.py does
```
eigvals, eigvec = eigsh(XH_X, k=k, tol=tol ** 2, maxiter=maxiter, ncv=ncv, which=which, v0=v0)  # tol**2 ?
...
# Use the sophisticated detection of small eigenvalues from pinvh ...
```

**Comment by lobpcg** [comment]
Please have a look at https://github.com/scipy/scipy/pull/11829# that attempts to solve this issue and adds several new unit tests specifically for small singular values.

Just setting "cutoff = 0" does not pass these unit tests, so is not a proper fix for all cases, even if it works for some. 

@mgoldeli I am looking at the MATLAB 2021b svds code now. They no longer use ARPACK in svds as far as I can see.

**Comment by mgoldeli** [comment]
Thank you for the quick replies. 

Okay. Apparently, making the cutoff parameter user-definable will cause another issues in the code. I can understand that. 

@denis-bz I am using the tol = 0 all the time.

**Comment by denis-bz** [comment]
`eigsh( XH_X, k=k, which="SM" ... )` is not a good approach for small singular values, because
1) they're squared, so σ < 1e-6  =>  σ² < 1e-12, down in the noise
2) see [finding-smallest-eigenvectors-of-large-sparse-matrix-over-100x-slower-in-scipy than Octave](https://stackoverflow.com/questions/59416098/finding-smallest-eigenvectors-of-large-sparse-matrix-over-100x-slower-in-scipy/60042695#60042695) on SO

@mgoldeli, can you tell us a bit about your problem -- how big, σ_min, σ_max -- or point to similar problems on the web ?
Thanks

**Comment by lobpcg** [comment]
> `eigsh( XH_X, k=k, which="SM" ... )` is not a good approach for small singular values, because
> 
> 1. they're squared, so σ < 1e-6  =>  σ² < 1e-12, down in the noise
> 2. see [finding-smallest-eigenvectors-of-large-sparse-matrix-over-100x-slower-in-scipy than Octave](https://stackoverflow.com/questions/59416098/finding-smallest-eigenvectors-of-large-sparse-matrix-over-100x-slower-in-scipy/60042695#60042695) on SO

@denis-bz I am unsure about relevance of your link to finding the smallest eigenvalues?

**Comment by mgoldeli** [comment]
> 



> `eigsh( XH_X, k=k, which="SM" ... )` is not a good approach for small singular values, because
> 
> 1. they're squared, so σ < 1e-6  =>  σ² < 1e-12, down in the noise
> 2. see [finding-smallest-eigenvectors-of-large-sparse-matrix-over-100x-slower-in-scipy than Octave](https://stackoverflow.com/questions/59416098/finding-smallest-eigenvectors-of-large-sparse-matrix-over-100x-slower-in-scipy/60042695#60042695) on SO
> 
> @mgoldeli, can you tell us a bit about your problem -- how big, σ_min, σ_max -- or point to similar problems on the web ? Thanks

@denis-bz Yes sure.

1) These are my **eigvals** in ths **svds function**:

![image](https://user-images.githubusercontent.com/33000961/169564842-80eb7509-b8e6-4b23-9a5d-82a8bea2ccfd.png)

2) Then my **cutoff value** is calculated as **4727.6**

![image](https://user-images.githubusercontent.com/33000961/169565233-64c02320-1631-473c-b859-a6f4045bd5d3.png)

3) Due to this cutoff feature, my **smallest 4 singular values are set to zero,** which are **66.7, 51, 38.5, 28**. In order to show this issue easier, I added a new variable into svds code which is **"slarge_WihoutCutoff"**

![image](https://user-images.githubusercontent.com/33000961/169566595-3293c763-308f-43eb-b821-7ad5992a0d5b.png)

4) Actually, I wanted to get also these 4 smallest singular values in the **output s** of the **svds function**. But, I can't get them **because of this cutoff parameter**, which is bigger than my smallest 4 singular values.

I hope, with this example it is much more easier to understand the issue that I want to point out here.

**Comment by ilayn** [comment]
Those tolerances are clearly bad and `pinv`, `pinvh` already steered away from these hardcoded values. So we need to fix them. There is no doubt about that. However, I think you would be better off by using the dense arithmetic anyways if you are looking for **all** singular values since it wouldn't make any sense to rely on those small values that are coming from sparse algorithms. 

Cutoff value is supposed to give you a handle to define the threshold to assume from where the noise roughly starts. Hence our initial discussion on how to define sparse noise floor. The `(n, m)*X*eps` is the numerical standard for anything dense where X is typically 100 or 1000. This is to account for `O(n**3)`-ish floating point error build up. In sparse arrays these numbers might be too high since we don't do operations on zero elements (or shouldn't) thus entrywise numerical buildup should be taken lower. But due to sparse computation accuracy there might be more uncertainty coming in by the approx. solvers. 

That particular threshold needs to be defined here. And it is not a random number that can be left to all users since not all `sparse` users are well-trained in these hence the defaults matter immensely. We have to first get those values and then the threshold parts are comparatively easier to implement.

**Comment by lobpcg** [comment]
@mgoldeli could you please run your code in https://github.com/scipy/scipy/pull/16240 to check if it fixes your problem?

**Comment by mgoldeli** [comment]
@lobpcg Hey Andrew, 
Yes, it solves the issue. So, I can get my last 4 singular values as I want in the output 's'.That's good.
But, doesn't this new svds implementation increase the computational time?

For the documentation, I am uploading the data that I used in the example above.
[Issue_svds.zip](https://github.com/scipy/scipy/files/8791825/Issue_svds.zip)

**Comment by lobpcg** [comment]
> @lobpcg Hey Andrew, 
> Yes, it solves the issue. So, I can get my last 4 singular values (smallest) as I want in the output 's'. That's good.
> But, doesn't this new svds implementation increase the computational time?
> 
> For the documentation, I am uploading the data that I used in the example above.
> [Issue_svds.zip](https://github.com/scipy/scipy/files/8791825/Issue_svds.zip)
> 
> 

Thanks for checking! The time increase should be insignificant. If you can time yourself please post the results. There is no memory increase. 

I have no setup to run locally myself at the moment so cannot time.

**Comment by mgoldeli** [comment]
I made a quick test with 1000 and 2000 loops by calling the svds code. 1. Results are the times of the original svds code and 2. results are times of the svds code in https://github.com/scipy/scipy/pull/16240

1. Results with original svds code
![image](https://user-images.githubusercontent.com/33000961/170856421-d708c575-4d05-4253-8b7c-61675850405b.png)

2. Results with the svds code in https://github.com/scipy/scipy/pull/16240
![image](https://user-images.githubusercontent.com/33000961/170856551-0999c080-d219-4291-9180-98cfcd683974.png)

**Comment by lobpcg** [comment]
@mgoldeli thanks very much for timing! The time increase is larger than I have anticipated.
 
Let me ping the author @evgueni-ovtchinnikov of the original PR https://github.com/scipy/scipy/pull/11829 where my https://github.com/scipy/scipy/pull/16240 is copied from hoping that he might be able to investigate if this is normal for your data posted as https://github.com/scipy/scipy/files/8791825/Issue_svds.zip

**Comment by evgueni-ovtchinnikov** [comment]
@mgoldeli @lobpcg the time increase is substantial because the matrix `Data` in `Issue_svds.zip` is too small - just 4000 by 24.

With such a small size, there is hardly any point in using `svds` rather that much more robust and accurate `svd` - on my laptop 1000 `svds` calls took 2.14 sec and 1000 `svd` calls 2.7 sec.

Actually, `svds` becomes much more efficient than `svd` if `min(data.shape) >> k`, in which case the extra cost of the new more reliable `svds` becomes negligible.

**Comment by ogauthe** [comment]
For what it's worth, I have been running a similar post-processing for some time for reasonably large dense matrices. A typical run computes `k=100` eigenvectors out of `ncv=300` generated Lanczos vectors of a (20k, 20k) matrix with `eigsh`, then calls `svd(A @ eigvec)`.

Time spent in `scipy.linalg.svd` is less than 0.2% of the time spent in `eigsh`, so in such a case the additional cost is negligible.
