### ISSUE TITLE
typo in help(scipy.interpolate.spline)

### ISSUE THREAD

**Issue by wubinbai** [scipy/scipy#12683]
My issue is about typo in help(scipy.interpolate.spline)

#### Reproducing code example:

```
help(scipy.interpolate.spline)
```

#### Error message:(Correct should be BSpline)

```
Help on function spline in module numpy.lib.utils:

spline(*args, **kwds)
    `spline` is deprecated!
    spline is deprecated in scipy 0.19.0, use Bspline class instead.

```

#### Scipy/Numpy/Python version information:
```
1.2.1 1.18.2 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)

(scipy,numpy,sys)
```

**Comment by tylerjereddy** [comment]
I think SciPy `1.2.1`  is old enough that we're not likely to fix the typo (only major bugs/security issues for a release series that old I think)--in recent releases I see `AttributeError: module 'scipy.interpolate' has no attribute 'spline'`, so presumably the deprecation cycle has since finished and the attribute has been removed.

**Comment by ev-br** [comment]
Yup, this has been removed in 1.3.0 (https://docs.scipy.org/doc/scipy/reference/release.1.3.0.html#backwards-incompatible-changes).
Let's close the issue, there is not much more to do here. Thanks anyway @wubinbai --- there's lots of things to fix, help's most welcome!
