### ISSUE TITLE
AttributeError: module 'scipy' has no attribute '_lib'

### ISSUE THREAD

**Issue by kianhongT** [scipy/scipy#12722]
Hello, I encounter the following error for Scipy. Does anyone know the reason? Tks.

~\anaconda3\envs\env_backtrader\lib\site-packages\scipy\_lib\_threadsafety.py in decorate(self, func)
     43             with self:
     44                 return func(*a, **kw)
---> 45         return scipy._lib.decorator.decorate(func, caller)
     46 
     47 

AttributeError: module 'scipy' has no attribute '_lib'

**Comment by rgommers** [comment]
`scipy_lib_threadsafety.py` is not a file that's present in SciPy, and apparently it's buggy. You will have to figure out how that got there and how it's called. 

It may be a case of `import scipy._lib` missing there.

**Comment by kianhongT** [comment]
@rgommers tks.

**Comment by peterbell10** [comment]
@rgommers check out the issue with the formatting fixed. `scipy\_lib\_threadsafety.py` comes out as one word in markdown because windows uses \\ as the directory seperator.

The line of code that's failing is here:
https://github.com/scipy/scipy/blob/2ed8169c5c4c9181cd38a52db614c692eb802c15/scipy/_lib/_threadsafety.py#L45

But the correct includes are definitely there at the top of the file, so I can't see why it would fail.

**Comment by rgommers** [comment]
> comes out as one word in markdown because windows uses \ as the directory seperator.

arghh

> But the correct imports are definitely there at the top of the file, so I can't see why it would fail.

Yes maybe an install issue or something, or off-label use somehow (embedded interpreter or whatever).

@kianhongT if you want a better guess you'll need to give us more details, like how you installed SciPy and the code you're running to trigger this issue.

**Comment by kianhongT** [comment]
@rgommers @peterbell10 I'm unable to debug the error so I uninstalled and re-installed everything again. Then I ran the code and it worked. haha. Many thanks for your input, guys.
