### ISSUE TITLE
scipy.signal.spectrogram cannot handle complex signal well

### ISSUE THREAD

**Issue by ZHANGGU** [scipy/scipy#12750]
scipy.signal.spectrogram, scipy version 1.3.2

1. based on the web example https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.spectrogram.html
2. the signal is changed to a complex signal with carrier -25000 Hz, and it returns correct spectrogram (correct spectro)
3. if the signal is changed to a complex signal with carrier 25000 Hz, and it does not return correct spectrogram (blank spectro)

**if the signal is a frequency seeping signal, from negative to plus in frequency, it shows strange.** as we would like to show the base band complex signal time variations.

####################repeatable code as below

from scipy import signal
import matplotlib.pyplot as plt
import numpy as np

fs = 100e3
N = 100e3
amp = 2 * np.sqrt(2)
noise_power = 0.01 * fs / 2
time = np.arange(N) / float(fs)

rx_carrier_frq = -25000
rx_carrier1 = np.exp(2j*np.pi*(rx_carrier_frq*time))
f1, t1, Sxx1 = signal.spectrogram((rx_carrier1), fs, scaling='spectrum')
plt.pcolormesh(t1, f1, (Sxx1), shading='gouraud')
plt.ylabel('Frequency [Hz]')
plt.xlabel('Time [sec]')
plt.show(block=False)
plt.tight_layout()

**Comment by e-q** [comment]
Since you are using a complex input signal, you should receive a warning that the `return_onesided` keyword argument is set to `False`. As the final example in the documentation page that you linked to notes, for the case of two sided spectrograms you should use the `fftshift` function to set the frequency and spectrogram arrays in the ordering that `pcolormesh` expects.
