### ISSUE TITLE
ndimage.fourier_ellipsoid segmentation fault

### ISSUE THREAD

**Issue by jasonzutty** [scipy/scipy#12763]
On Scipy 1.5.2. Tested on mac and linux:

```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> x = np.ones((1,128))
>>> from scipy import ndimage
>>> ndimage.fourier_ellipsoid(x,3)
Segmentation fault (core dumped)
```

It does work fine if x is defined to be a 2x128 instead of 1x128.
I also tried to reduce the size to a 1 and keep it as a 1x128, still segfaulted in this case.

**Comment by ianthomas23** [comment]
This problem originates in the C file `ni_fourier.c`:

https://github.com/scipy/scipy/blob/2850365e2e447b8e4c1d5ede5193afa5bc682804/scipy/ndimage/src/ni_fourier.c#L227-L229

For each dimension in the `input` array that has a size greater than 1 it allocates a buffer to store calculations. If the size of the dimension is 1 (or 0) it does not do so and the corresponding `params[kk]` is left as a null pointer. A segmentation fault occurs when this null pointer is subsequently deferenced.

Because of the explicit check that the dimension size is `> 1` it looks like the code is not expecting such values. Hence the fix is to check for dimension sizes less than 2 and fail gracefully rather than cause a segmentation fault. I am happy to submit a PR to do this.
