### ISSUE TITLE
Confusing documentation of scipy.stats.weightedtau

### ISSUE THREAD

**Issue by stde** [scipy/scipy#12778]
The usage of weightedtau is to use two arrays of scores.  That means higher values indicate a lower (better) rank.

In the [description ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.weightedtau.html) it says 

"Note that if you are computing the weighted \tau  on arrays of ranks, rather than of scores (i.e., a larger value implies a lower rank) you must negate the ranks, so that elements of higher rank are associated with a larger value."

1. If "lower rank" means "the value of the rank is lower -> the candidate is good"  then the second part of this sentence is wrong.  Negating the  ranks implies that elements of higher ranks (e.g. Rank 100) will be associated with a smaller (-100) value compared to elements of a  lower rank(e.g Rank 10), that will be associated with a larger (-10) value.

2. If "lower rank" means "the value of the rank is high -> the candidate is bad" then the first part of this sentence is wrong.  A large score  then would imply a higher rank.

**Comment by mdhaber** [comment]
@stde I interpreted the quoted sentence according to your interpretation 1 because of the part that says "a larger value implies a lower rank". So if a larger value/score is considered "good", then in your words, "the value of the rank is lower -> the candidate is good".

But SciPy doesn't follow the convention that "a larger value implies a lower rank":

```
from scipy.stats import rankdata
import numpy as np
x = np.arange(10)
print(rankdata(x))
```
```
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
```

So a low value (0) corresponds with a low rank (1) and high value (9) corresponds with a high rank (10).

@vigna Thanks for contributing `weightedtau`. I see you [already noted](https://github.com/scipy/scipy/pull/6763#issuecomment-264697001) some of the confusion surrounding the word "rank". Could you comment on this issue?

**Comment by vigna** [comment]
Yes, eternally source of confusion :).

In point (1), "higher hanks" (Rank 100) is exactly the opposite of the meaning of rank. The documentation is correct—a high rank (e.g., first) is expressed by a lower value (e.g., 0). Ranks are ordinals: first, second, third..., usually expressed as integers, say, 0, 1, 2,... The smaller the value, the higher the rank.

Scores are reals:  5.2, 1.3, 0.5, etc. The larger the value, the higher the rank induced by sorting.

The standard way to get from score to ranks is indirect sorting by decreasing value. If you want to convert from ranks to scores, you just negate the rank values. So ranks expressed as 0, 1, 2, ... become scores 0, -1, -2, ... and element with a higher rank now have a larger score.

I'm thinking of how to make this clearer. Maybe something like

"Note that if you are computing the weighted \tau on arrays of ranks (integers representing a relative ordinal position of importance, with smaller integers corresponding to greater importance), rather than of scores (reals representing absolute importance, with larger values corresponding to greater importance) you must negate the ranks, thus obtaining a score vector in which more important elements are associated with a larger value."

**Comment by mdhaber** [comment]
I see. I like that your suggestion avoids using the words "high rank" to mean "low rank value".

I would include it as-is, but [in SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rankdata.html#scipy.stats.rankdata) and [commonly in the context of statistics](https://en.wikipedia.org/wiki/Ranking#:~:text=In%20statistics%2C%20ranking%20is%20the,3%2C%201%20and%204%20respectively.), high magnitude (greater importance) scores turn into _high_ magnitude/large integer ranks, so larger integers correspond to greater importance. This is opposite your definition of rank, in which "smaller integers corresponding to greater importance", right? 

So if users had previously used e.g. `rankdata` to rank their scores, and if they chose to use `weightedtau` on these ranks rather than the raw scores, they actually _should not_ negate them because large integer ranks already correspond with large scores in the raw data. No?

**Comment by vigna** [comment]
Er... actually, it says

"In these examples, the ranks are assigned to values in ascending order. (In some other cases, descending ranks are used.)"

The general meaning of "rank" in that Wikipedia entry is exactly the one I am using. In fact, it all depends on the interpretation of scores.

I think that the easiest solution is to delete those four lines. The fact that internally in the computation there's a notion of rank is immaterial—that's part of the mathematical definition. Those four lines were there to help people using arrays of ranks in the general meaning, but if in statistics you think it is more common to use the other way let's just eliminate those four lines—they try to solve a problem that does not even exist. People can just pass ranks in the SciPy sense and everything will work out fine.

**Comment by vigna** [comment]
Looking again at the documentation, I would certainly eliminate those lines, but then the documentation for the parameter `rank` must be amended, as indeed it is different to what SciPy users are used to.

**Comment by vigna** [comment]
Please have a look at https://github.com/scipy/scipy/pull/13224 . Seems enough clear to me, but I'm biased.

**Comment by stde** [comment]
@vigna : Just to wrap this up in my mind:  My misunderstanding of the documentation was that in "Note that if you are computing the weighted \tau on arrays of ranks, rather than of scores (i.e., a larger value implies a lower rank) [..]"

I thought the statement in the bracket refers to the relationship between scores (values) and ranks "larger score -> lower rank".  Whereas what it actually meant was  "for the integer representing the rank, the higher integer the worse".

Because otherwise (if it would define the relationship between scores and ranks) your statement  "The documentation is correct—a high rank (e.g., first) is expressed by a lower value (e.g., 0)"  would contradict what is written in the bracket.

**Comment by vigna** [comment]
Exactly, the "value" in parentheses is the value representing the rank. It is convoluted, I know, not a native speaker here. 🤷🏻‍♂️

**Comment by mdhaber** [comment]
Closed by gh-13224
