### ISSUE TITLE
scipy.signal.sosfilt demands writeable filter coefficients array

### ISSUE THREAD

**Issue by tjb900** [scipy/scipy#12905]
It seems that sosfilt thinks it requires write access to the filter coefficients array in order to run - which seems counterintuitive to me (and, if it's true that we actually write to the coefficients, this would imply locking requirements when using these filtering operations to filter several arrays in parallel - which also seems bad).

I don't think it actually writes to them though.  Seems like a very similar issue to https://github.com/glotzerlab/freud/issues/244, which refers to this:

https://github.com/cython/cython/issues/1605

#### Reproducing code example:

```
import numpy as np
import scipy.signal


example_filter_sos = scipy.signal.butter(4, 0.3, output="sos")

example_filter_sos_ro = example_filter_sos.view()
example_filter_sos_ro.flags.writeable = False

x = np.zeros([1000])
xro = x.view()
xro.flags.writeable = False

# simple usage works
y = scipy.signal.sosfilt(example_filter_sos, x)
# and a read only data buffer works
y2 = scipy.signal.sosfilt(example_filter_sos, xro)
# but a read-only filter coefficient buffer fails
y3 = scipy.signal.sosfilt(example_filter_sos_ro, x)
```

#### Error message:

```
Traceback (most recent call last):
  File "repro.py", line 16, in <module>
    y3 = scipy.signal.sosfilt(example_filter_sos_ro, x)
  File "/redacted/env/lib/python3.8/site-packages/scipy/signal/signaltools.py", line 4067, in sosfilt
    _sosfilt(sos, x, zi)
  File "_sosfilt.pyx", line 24, in scipy.signal._sosfilt._sosfilt
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

#### Scipy/Numpy/Python version information:
```
1.5.2 1.19.1 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

**Comment by roryyorke** [comment]
I had a look at fixing this in `_sosfilt.pyx` using the `const` keyword [1], but I hit something that looks a lot like cython/cython#3783 (using Cython 0.29.21, Python 3.8, Scipy 474dc2273).  According to discussion at the Cython issue, this has been fixed for Cython 3.0, which hasn't been released.

A simple alternative would be to change sosfilt (the Python function) to pass _sosfilt a copy of the coefficients; this is probably not *too* terrible, since I imagine the coefficient array wouldn't normally be all that big, but I think it would be better to wait for a fix to Cython.

[1] https://cython.readthedocs.io/en/stable/src/userguide/memoryviews.html#read-only-views

**Comment by ilayn** [comment]
Argh this one again. This is an unfortunate feat of Cython both documented in the docs (also for v3) https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html#read-only-views (last sentence) and also what @roryyorke linked to. We can instead use a template and add `const` to every type separately as a last resort.

Since we are making a copy of signal data and paying the price anyways, we can also copy the coefficients which should be much cheaper. I've recently made some speed-up improvements to it in #13087 hence the cost should be negligible . 

Why should filter coefficients be read-only is something I think I didn't quite understand though since we are not touching and won't be a thousand entries anyways so we can always work with a copy.

**Comment by headtr1ck** [comment]
Same thing happens for `scipy.signal.peak_widths`.

**Comment by ev-br** [comment]
Both `sosfilt` and `peak_widths` appear to have been fixed, at least in the main branch (to become scipy 1.11).

```
In [2]: import numpy as np

In [3]: from scipy import signal

In [4]: filter = signal.butter(4, 0.3, output='sos')

In [5]: x = np.zeros([100])

In [6]: x.flags.writeable = False

In [7]: x.flags
Out[7]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [8]: signal.sosfilt(filter, x)
Out[8]: 
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### peak_widths

In [9]: x = np.linspace(0, 6 * np.pi, 1000)
   ...: x = np.sin(x) + 0.6 * np.sin(2.6 * x)

In [10]: x.flags.writeable = False

In [13]: signal.peak_widths(x, [0, 1])
<ipython-input-13-c8ae25383107>:1: PeakPropertyWarning: some peaks have a prominence of 0
  signal.peak_widths(x, [0, 1])
<ipython-input-13-c8ae25383107>:1: PeakPropertyWarning: some peaks have a width of 0
  signal.peak_widths(x, [0, 1])
Out[13]: 
(array([0., 0.]),
 array([0.        , 0.04829024]),
 array([0., 1.]),
 array([0., 1.]))

In [14]: import scipy

In [15]: scipy.__version__
Out[15]: '1.11.0.dev0+2035.08fb077'
```
