### ISSUE TITLE
DOC: optimize.least_squares: better name for default `loss`?

### ISSUE THREAD

**Issue by SebastianoCurreli** [scipy/scipy#12973]
Hi everybody,
And thank you all for the great job.
I've a question about how `curve_fit()` solves least squares problems when boundaries are provided.  
Specifically, reading the docs here (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html) it is explicitly said:
"Use non-linear least squares to fit a function, f, to data."
However, and please correct me if I'm wrong, if the problem involves boundaries, the function calls `least_squares()`, that according to the docs (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html#scipy.optimize.least_squares) by default has `method='trf'` and `loss='linear'`, therefore the problem is addressed as "a standard least-squares problem".
So, if I understood correctly, by default in `curve_fit()` if we don't pass an alternative loss function supported by `least_squares()` we are treating a case of a standard linear least squares.
If this is the case, IMHO the docs of  `curve_fit()` would be more precise if rephrased as:
"Use linear least squares to fit a function, f, to data. Supports non-linear least squares."

**Comment by mdhaber** [comment]
'linear'/'nonlinear' in the context of `curve_fit` appears to refer to `f` being a linear/nonlinear function of the parameters, not the "loss function" used by `least_squares`. From Wikipedia, for example:

> Non-linear least squares is the form of least squares analysis used to fit a set of m observations with a model that is non-linear in n unknown parameters (m ≥ n).

In the context of `least_squares`, 'linear'/'nonlinear'  appears to refer to `func` being a linear/nonlinear function of the parameters. However, you're right that `least_squares` has a `loss` parameter, too, for which the default is named "linear". There could probably be a better name, unless this is commonly used in the field. Without research, I would have thought that "identity" would be a better name, because the loss function (functional?) is equal to `func`.

The action I'd suggest here is to research loss functions commonly used in least squares minimization and see if there is another common name for `rho(fun(x))==fun(x)`.

@steppi this might be an easy question for you. Is what I wrote accurate, and do you know of a different name for the "linear" loss function of `least_squares`?

**Comment by steppi** [comment]
> @steppi this might be an easy question for you. Is what I wrote accurate, and do you know of a different name for the "linear" loss function of `least_squares`?

I looked at the docstring for `least_squares`. It might be using a naming convention I'm not familiar with. I've always thought that loss function and cost function are synonymous, see the Wikipedia article for [Loss function](https://en.wikipedia.org/wiki/Loss_function) for instance. In some contexts loss function is taken to be a function of one variable, and cost function the sum of the losses over all data points.

 In `least_squares`, it seems loss function is being used for the function $\rho$ and cost function for 

$$F = \frac{1}{2} \sum_i \rho\left(f_i^2\right)$$

(where the $f_i$ are residuals.)

So that the residuals are squared before being fed to the "loss" function.

Take `"huber"` for instance. In the `least_squares` documentation we have

$$
\rho(z) =
    \begin{cases}
        z & \text{if } z \leq 1\\
        2\sqrt{z} - 1 & \text{otherwise}
    \end{cases}
$$

but typically Huber would refer to

\l(z) =
    \begin{cases}
        z^2 & \text{if } z \leq 1\\
        2\|z\right| - 1 & \text{otherwise}
    \end{cases}
$$


See [Wikipedia](https://en.wikipedia.org/wiki/Huber_loss) again for instance. Note that the Wikipedia article includes an extra parameter $\delta$ which `least_squares` sets to 1. There's also an extra factor of $\frac{1]{2} which `least_squares` includes in the cost function.

I think what's going on is that $\rho$ is not really supposed to be the loss function, but to specify it in such a way that makes the connection to regular least squares clear for all of the included losses. The analog of `"huber"`, `"soft_l1"`, etc. isn't `"linear"`, it's `"l2"`, and I think that would be a better name for the `loss` option corresponding to ordinary least squares.

**Comment by mdhaber** [comment]
I think see. Let me see if I can paraphrase the conclusion:

The strings that are accepted by `loss` were selected  to correspond with the overall "loss function"; they are not descriptions of `rho`. Therefore, even though `rho(x) = x` is an identity operation, `'l2'` is a better name for `rho(x) = x` because it leads to an L2 loss function.

**Comment by steppi** [comment]
> The strings that are accepted by `loss` were selected to correspond with the overall "loss function"; they are not descriptions of `rho`. Therefore, even though `rho(x) = x` is an identity operation, `'l2'` is a better name for `rho(x) = x` than `'identity'` because it leads to an L2 loss function. And `'l2'` is a better name than `'linear'` because `'linear'` describes neither `rho` nor the loss function.

Right, every string besides `'linear'` refers to the overall cost function, not `rho`. I think `'l2'` would be a better name because it follows the same convention as `'soft_l1'`, `'huber'`, etc.



> (Would ["quadratic"](https://en.wikipedia.org/wiki/Loss_function#Quadratic_loss_function) also work?)

Yes, that seems fine to me.


> But on the other hand, the function name is `least_squares`. With that in mind, maybe `loss` should describe what is done _with the squared errors_. In that case, `'linear'` makes some sense : the loss function is a linear combination of the squares of the errors (with all coefficients 1)?

Yes, in isolation it makes sense. It just doesn't follow the same convention as the other strings, which all describe the overall cost function. I think that's a little confusing, although maybe it's not worth spending the effort to change things.

**Comment by mdhaber** [comment]
Thanks. If it comes up again, we'll consider changing something. For now, it says "'linear'...Gives a standard least-squares problem", which is clear enough, whatever "linear" is supposed to refer to. So I'll go ahead and close.
