### ISSUE TITLE
least_squares broken with float32

### ISSUE THREAD

**Issue by dschwoerer** [scipy/scipy#12991]
`optimize.least_squares` doesn't work reliably with float32. Changing the dtype to float64 (or removing it) yields the expected result.

#### Reproducing code example:
```
import matplotlib.pyplot as plt
import numpy as np
from scipy import optimize

x = np.linspace(0, 1, 100).astype("float32")
y = np.random.random(100).astype("float32")


def func(p, x):
    return p[0] + p[1] * x


def err(p, x, y):
    return func(p, x) - y


res = optimize.least_squares(err, [-1.0, -1.0], args=(x, y))
plt.plot(x, y, "x")
plt.plot(x, func(res.x, x))
plt.show()
```

#### Error message:
No error is raised, just the fit does not converge.

#### Scipy/Numpy/Python version information:

```
1.5.3 1.18.4 sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
```

**Comment by dschwoerer** [comment]
Some additional infos:
It terminates with message "`gtol` termination condition is satisfied."

If I set `gtol=None` I get the following output:

```
~/.local/lib/python3.8/site-packages/scipy/optimize/_lsq/common.py:113: RuntimeWarning: invalid value encountered in true_divide
  p_norm = norm(suf / denom)
~/.local/lib/python3.8/site-packages/scipy/optimize/_lsq/common.py:115: RuntimeWarning: invalid value encountered in true_divide
  phi_prime = -np.sum(suf ** 2 / denom**3) / p_norm
The maximum number of function evaluations is exceeded.
```

**Comment by andyfaff** [comment]
This arises because of floating point issues in the numerical differentation of the user function. The initial gradient (J0) of `err` is computed [here](https://github.com/scipy/scipy/blob/master/scipy/optimize/_lsq/least_squares.py#L884). Your `err` function returns `np.float32` arrays, but the default step size for the numerical differentiation is [worked out on the assumption one is using np.float64](https://github.com/scipy/scipy/blob/master/scipy/optimize/_numdiff.py#L111). This step size is too small, and so when one takes a small step `dx` all the `df` are 0. Therefore the initial Jacobian is all zeros, a consequence of working with too small an EPS for the floating point size.

```
>>> from scipy.optimize._numdiff import approx_derivative
>>> # I trimmed the output array 
>>> approx_derivative(err, [-1.0, -1.0], method='2-point', args=(x, y))
array([[-0., -0.],
       [-0., -0.],
       [-0., -0.],
...
       [-0., -0.],
       [-0., -0.],
       [-0., -0.]])
```
This causes the premature termination of the minimisation ([here](https://github.com/scipy/scipy/blob/master/scipy/optimize/_lsq/trf.py#L452)).
Note that if one uses `leastsq` I think the correct EPS is calculated using an [appropriate value for the floating point size](https://github.com/scipy/scipy/blob/master/scipy/optimize/minpack.py#L417).

Wherever possible I always recommend that people work with float64 data because of these issues.

Possible improvements:
1. Improve the documentation to point out that this kind of issue exists when one is working with FP arithmetic.
2. Change `_numdiff` so that it uses the correct step size for the dtype.
