### ISSUE TITLE
Question on gaussian window

### ISSUE THREAD

**Issue by darrencl** [scipy/scipy#13003]
Hi, I am trying to compare my project which uses `scipy.signals.window` library to this NMR processing tool called [MNova](https://mestrelab.com/software/mnova/). I can see that the gaussian window function accepts `std` argument, however in MNova it seems to accept other parameter with GB [Hz] unit (I have no idea what it is since I'm not signal processing expert), see below screenshot.

![image](https://user-images.githubusercontent.com/21291776/97255421-4e05e880-185c-11eb-9a42-eeddbaa9814a.png)

My question is, how can I translate that parameter to std (or the other way around) so I can get comparable result?

Any help would be appreciated! :)

**Comment by ilayn** [comment]
Hi @darrencl . You would probably get more answers if you try Stackoverflow networks like https://chemistry.stackexchange.com/ and others since we deal with the library problems, bugs etc. on this repository

But quick googling shows that they use the following definition 

![image](https://user-images.githubusercontent.com/1303842/97265334-c356c680-1826-11eb-9c4e-1536a6b1edb4.png)

So maybe you can combine https://en.wikipedia.org/wiki/Window_function#Gaussian_window and http://scipy.github.io/devdocs/generated/scipy.signal.windows.gaussian.html to arrive at a meaningful result. GB sounds like Gaussian Beam but cannot make much from that screenshot alone.
