### ISSUE TITLE
The error handling when installing SciPy 1.5.3 on Python 3.9 is problematic

### ISSUE THREAD

**Issue by justinkterry** [scipy/scipy#13027]
So I've been working on a PR adding Python 3.9 support to a library I maintain, as are a lot of people right now. When Travis tried to install SciPy, I got this completely uninformative and absolutely giant error message: https://pastebin.com/ZaQsAvLR

Surely there's a more sensible way to handle this. If my understanding is correct, this is done by having `python_requires=">=3.6"`, be `python_requires=">=3.6, <3.9"` in setup.py. This also just makes more sense in general because libraries as large as SciPy never natively support never versions of Python, like a simple library like python-chess might. I'm happy to do a little PR for this unless people see something wrong with it.

**Comment by andyfaff** [comment]
We're in the middle of the process making 3.9 wheels at the moment. Indeed we've been building scipy for 3.9 during CI for at least 6 months now. The error message you see is because you haven't got blas setup correctly, so the build process can't proceed.
Here's how we setup dependencies for testing 3.9 on Linux at the moment: https://github.com/scipy/scipy/blob/master/.github/workflows/bleedingedge.yml#L32. You should only need `libatlas-base-dev liblapack-dev gfortran` (on Ubuntu).

I'd say the error message isn't totally uninformative, but it could be clarified.

**Comment by andyfaff** [comment]
Does your CI run work now that wheels for 3.9 are available?

**Comment by justinkterry** [comment]
Yes, thank you. It's still unclear to me why you don't specify a maximum python version for SciPy though, given that there's a negligible chance of SciPy functioning with a new Python release without modification. This would dramatically improve error message quality. I can do a tiny PR for it if desired.

**Comment by tylerjereddy** [comment]
@justinkterry 

> It's still unclear to me why you don't specify a maximum python version for SciPy though, given that there's a negligible chance of SciPy functioning with a new Python release without modification.

There's a pretty high chance of it working in an environment that is designed for source builds. The vast majority of our Python 3.9 CI additions were just "add it to the matrix and it works."

That said, there's a PR/proposal related to this exact topic here: gh-12862

Perhaps reading through that will give you an idea of some of the challenges/complexities behind the scenes, and you can make suggestions there if you want.
