### ISSUE TITLE
CI: Travis CI has been completely disabled for SciPy (no credits left)

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#13109]
Please be extremely cautious merging MRs into `master` as Travis CI has been completely disabled for SciPy and does not show up as a red or green mark in our testing matrix. This timing is a little unfortunate, just days before the planned branching of `1.6.0`. We're going to have to migrate the jobs to other services.

Here's what I see in our Travis page:

![image](https://user-images.githubusercontent.com/7903078/99887527-560a3b80-2c02-11eb-8ece-304dcb729d25.png)

![image](https://user-images.githubusercontent.com/7903078/99887557-88b43400-2c02-11eb-8678-a7e3bc85bfe1.png)

**Comment by charris** [comment]
I'd be willing to throw some money at the problem if there is a longer term plan to fix it.

**Comment by mojca** [comment]
Note that you may always request additional free credits. If you just need that for release, it might solve the immediate problem and then you have enough time to migrate afterwards.

Azure and GitHub Actions still offer a much better service for free anyway.

**Comment by ilayn** [comment]
> I'd be willing to throw some money at the problem if there is a longer term plan to fix it.

Same here. I'd rather keep paid TravisCI instead of moving away from it.

**Comment by tylerjereddy** [comment]
> Azure and GitHub Actions still offer a much better service for free anyway.

A bit tricky to deal with some of the architectures like ARM64 (we release wheels for that now) and ppc64le (we don't release wheels for that yet).

I reached out to Travis CI support and NumFOCUS for advice.

**Comment by rgommers** [comment]
> and ppc64le (we don't release wheels for that yet).

We may want to not do that for the coming release. If it's clear we can keep free TravisCI for `ppc64le` support then yes, but otherwise why make our lives difficult for a platform with a very small user base. I'd say that if free CI is not available, `ppc64le` (and `s390x`) goes back to the same support status as AIX et al. - we take patches, but that's all.

**Comment by tylerjereddy** [comment]
The basic response I got from NumFOCUS is that something might be possible with CircleCI or Azure, but I didn't get the impression we'd be able to work something out with Travis team anytime soon.

Travis CI team has not responded to my inquiry from Sunday afternoon.

The paid plans are pretty gruesome as I noted here: https://github.com/numpy/numpy/issues/17824#issuecomment-732567438

**Comment by rgommers** [comment]
@tylerjereddy it looks like multiple people want to help out with moving CI jobs (at least @ilayn and @mattip offered recently), we just need to organize it. Not sure if you already started on some of the pieces or have a plan? If so, maybe you can post a list of which jobs need to be moved where (main repo and `scipy-wheels`), and then people can comment when they're picking up a part of that?

**Comment by tylerjereddy** [comment]
@mattip, @ilayn if you'd like to help migrate a job or two off of Travis that would be great

I've moved a few already, but the only ongoing one I currently have is: https://github.com/scipy/scipy/pull/13117

As you can see there, I've basically been deleting the Travis CI matrix entries as I replace them in another service. If you do start working on one, maybe just comment here or in the matching wheels repo issue ( https://github.com/MacPython/scipy-wheels/issues/106 ) as appropriate so we can avoid duplication of effort.

**Comment by tylerjereddy** [comment]
I suspect we'll just drop ppc64le for now. For ARM64, shippable probably won't suffice for SciPy, maybe the drone service that OpenBLAS uses for ARM testing, not sure. Anyway, even ignoring the "exotic" architectures there's plenty of plain amd64 migrations to do between the two repos.

**Comment by edelsohn** [comment]
Travis CI has replied to IBM that they provide free additional credits to any project that requests them.  Has anyone asked Travis CI (not sponsored project, just a request for more credits)?

**Comment by ilayn** [comment]
Where do you prefer to take the matrix entries to? Are we balancing them out or doesn't matter between GH actions and Azure pipelines?

**Comment by rgommers** [comment]
> Travis CI has replied to IBM that they provide free additional credits to any project that requests them. Has anyone asked Travis CI (not sponsored project, just a request for more credits)?

They're not being very truthful or realistic there. Multiple requests from SciPy and other NumFOCUS projects have gone unanswered. And the one case I know of who did get extra credits (Astropy), it ran out within the same week. Which is not worth bothering with.

You also see it from the increments they're talking about, both what you can request and the $15 ones; it's all basically a few to max a few dozen PRs/commits, depending on how many jobs you have.

The message is clear: the party is over, time to migrate or be willing to pay a lot of money. Which we really can't blame them for - TravisCI has been extremely generous to open source for many years. But now they've decided they're done.

I'm thinking we *may* want to keep `aarch64` there for a while at least, because it was quite hard to make wheel builds for that platform work without timing out. Anything else is probably "move or drop".

**Comment by rgommers** [comment]
Or at best, add a weekly or monthly cron job for more exotic platforms.

**Comment by rgommers** [comment]
Also, the travisci.org to travisci.com move was unfortunately - the `.org` still runs just fine for other projects (even if the build queue is backed up) - till the end of the year I believe.

**Comment by larsoner** [comment]
> Also, the travisci.org to travisci.com move was unfortunate

Argh, sorry about that. Didn't expect this to be an issue :(

**Comment by rgommers** [comment]
Double checked the blog, they did post a follow-up on open source: https://blog.travis-ci.com/oss-announcement. There's zero details, but maybe they are changing tack based on the amount of complaints/requests.

**Comment by charris** [comment]
> The message is clear: the party is over

I suspect they were bleeding money. Was the privilege abused? Don't know, but in my experience anything that can be abused will be. There are lots of people out there cleverer than me :) That said, the transition has not been handled well and now they are probably overloaded with requests.

**Comment by rgommers** [comment]
Not sure we posted the calculation anywhere:
- The last SciPy build on travisci.com that ran took 3 hrs 38 min = 218 min in total
- Free credits are 10K credits == 1000 min on Linux (Windows is 2x more expensive, macOS 5x more)
- So we can build 4-5 commits (which is <1 PR to completion) on the free credit
- Then we need to buy $15 increments, for 25K credits
- So the price is at least $3 per PR. Actually likely 2x-3x more given that there are PRs that triggers dozens of CI runs, hard to estimate exactly. Handwavy estimate: $5 - $10
- Last month we had 75 merged PRs. So $375 - $750 / month.
- I'm ignoring builds on master and maintaince branches, or the separate wheel build repo. Those are smaller, maybe add ~20% total or so.

We could actually come up with that money, but given that migrating is not all that hard it seems like we're better off just migrating.

**Comment by charris** [comment]
> but given that migrating is not all that hard it seems like we're better off just migrating.

I'm not convinced that any of the free services will be as reliable as a payed service, especially for services starting small. Note that we lost rackspace last summer, and if Anaconda gets squeezed they may put on their green shades and take a closer look at providing us disk space. At some point we will probably need to make services part of our fundraising efforts.

**Comment by rgommers** [comment]
> At some point we will probably need to make services part of our fundraising efforts.

Maybe, but we've got a bunch of options still. Given how hard (and painful) it is to raise funds, I'd rather postpone that decision until it's clear we have little choice. Or we become a whole lot richer:)

**Comment by ilayn** [comment]
To be honest, they(TravisCI) have been providing an outstanding service (think about the PR rate we have and our ~10 entry matrix) so I wouldn't blame them just for the sake of making money which is still quite fine since they are a commercial company.

As far as I heard there were some attempts to do cryptocurrency ops and other questionable uses through repos. Are those self-claimed marketing tricks? I have no way to find out but in any case, it is obvious that we are out of our safezone now. So maybe we need to sit down and think about striking a mutually beneficial deal with 3rd parties instead of just migrating from one place to the other as they slowly shrink in numbers.

**Comment by mojca** [comment]
The move from Travis wasn't really unexpected:
* https://news.ycombinator.com/item?id=19218036
* https://news.ycombinator.com/item?id=18978251

I'm an outsider here, but if you expect to have to pay $1k/month, wouldn't it be cheaper (and definitely better in the long run) to spend that money buying your own infrastructure (and potentially share it with some other projects like numpy etc.)? You don't really need a super fast network connectivity or public IPs for that, you just need to pay the electricity bill and do some software maintenance (and of course security is on you then).

At the moment GitHub Actions and Azure (still) offer an excellent service. With one of the player offering free services leaving the market, their generous free offer may one day become more limited, but I don't expect Microsoft or GitHub to just go extinct.

I'm participating in two other OSS projects and we both have our own build infrastructure, mainly because we set it up before Travis came around, but also because we needed more flexibility than what Travis offers, a wider range of operating systems/architectures (ancient macOS versions, other operating systems like Solaris, FreeBSD, OpenBSD, linux running on ARM, ...), and the 50-minute timeout on Travis was often not sufficient. If we have a job that needs a day to complete ... well, we let it run until it's done, while any other service will kill that.

**Comment by ilayn** [comment]
@mojca Acquisition doesn't mean monetization per se. We are typing these on GitHub that triggered massive panic and anger when bought by Microsoft. So that's not the main topic. Also maintaining an infra with proper security is a full-time DevOps job and I don't think any of us can afford that.

**Comment by mojca** [comment]
It wasn't as much about the acquisition as it was about firing plenty of (senior) developers.

**Comment by rgommers** [comment]
> wouldn't it be cheaper (and definitely better in the long run) to spend that money buying your own infrastructure

Nope, definitely not going there. Maintaining hardware + CI setup like Jenkins is extremely expensive in terms of maintainer time/load, and more fragile. I'm not sure if you were around in the pre-TravisCI days, but it was very painful and there's no way I want to ever go back to that unless we have serious funding for someone to maintain all that (and even then, only if we really have no other choice). I'd happily pay $1k/month if our only other option was DIY with Jenkins et al.

**Comment by matthew-brett** [comment]
If we had 1K / month of developer / devops time, and perhaps some support
across multiple projects, would that not be enough to keep such a system
running?

Indeed, Buildbot etc were time consuming, when I was maintaining for our
Nipy projects, but much less than 1K / month time-consuming.

**Comment by rgommers** [comment]
Employing a good full-time CI engineer costs on the order of $200k/yr in North America / Europe. So a quick calculation ($1k/month * 12 months / $200k/yr * 35 hrs/wk productive time) says that engineer gets 2.1 hrs/wk for buying/provisioning hardware (let's ignore the cost of that), setting up a CI system, dealing with something like Terraform to make sure it stays up, responding to new issues, etc.

Even ignoring the other downsides like introducing a single point (person) of failure, and the difficulty of finding the right person to employ for a small fraction of their time, I'd say it's highly unlikely that it's going to all be doable with 1-2 hrs/wk.

CI services do provide a lot of value.

**Comment by matthew-brett** [comment]
Well - sure - but I don't think we have to think purely in terms of full commercial costs for time, at least.   Just for example, here we're spending lots of highly skilled developer time switching between CI platforms, and working out how to run CI for more obscure operating systems and architectures.

**Comment by mattip** [comment]
Many of those hours would need to be spent even if we had our own CI machines. Updating multibuild, handling new versions of OS and new architectures, updating the CI software are project-level tasks no matter who the CI provider.

I think we should continue the policy of migrating what we can.

I did reach out to travis ci for credits for scipy and numpy with an eye to the non-x86 architectures. I will report progress if I hear back from them.

**Comment by rgommers** [comment]
> Well - sure - but I don't think we have to think purely in terms of full commercial costs for time

We do, because by building a DIY solution we're taking away the option to do it collectively. Anyone can tweak some yaml files for TravisCI, and many people tend to pitch in. If it becomes custom, it's going to land on one person, or max a couple of people. 

The `aarch64` build for example, which was by far the hardest one to add, was added by a new volunteer. That's simply not going to happen if we change to something that's not a hosted service.

**Comment by ilayn** [comment]
Security and webhooks are sufficient for me to choose the payment option. But anyways, since we are not doing it, we don't need to discuss the hypothetical situation. 

@tylerjereddy Where do we take the Travis entries to? Azure or GitHub actions? If you don't have a preference I'll choose Azure since it is slightly less bad in terms of config options. I start missing Travis already 😢

**Comment by tylerjereddy** [comment]
So far I've just migrated to Azure because I'm more familiar with. We may want to "load balance" a bit with GitHub actions in terms of straining the parallel limits.

**Comment by rgommers** [comment]
+1 for load balancing. That's what I was asking about, a list for which jobs go where.

**Comment by andyfaff** [comment]
I can definitely help out with GitHub actions, it's reasonably straightforward to target that.

While we do this refactor I think we should consider how the wheels multibuild process occurs, and whether we stick with the current approach on Travis, or make the wheels on azure/ghactions.

**Comment by ilayn** [comment]
@andyfaff Can you help me with #13136 for example? Doesn't seem like it is firing by itself. Should I do something extra?

**Comment by rgommers** [comment]
> While we do this refactor I think we should consider how the wheels multibuild process occurs, and whether we stick with the current approach on Travis, or make the wheels on azure/ghactions

We just got some extra credits for that repo (and all of MacPython), so that'd be the last part to touch probably.

**Comment by gerrith3** [comment]
Were you guys able to request more credits from Travis successfully?  If not, let me know and I'll try to help, although getting the request filed via support.travis-ci.com is the right way to get these requests logged.

**Comment by rgommers** [comment]
Thanks for asking @gerrith3. We didn't yet receive any credits. We by now migrated most jobs away, and only have ARM64 and PowerPC left, which we cannot move anywhere so would really like to get running again.

> If not, let me know and I'll try to help, although getting the request filed via support.travis-ci.com is the right way to get these requests logged.

Thanks. We sent several request in various ways, also in combination with NumPy and MacPython (who both did get credits already). I'm not sure if we used support.travis-ci.com - @tylerjereddy did you do that? If not, I'm happy to open a new one there.

@gerrith3 help would very much be appreciated.

**Comment by mattip** [comment]
I sent a mail on 24/11 to support@travis-ci.com asking for credits for 4 projects in this order:

https://travis-ci.com/github/scipy/scipy
https://travis-ci.com/github/numpy/numpy
https://travis-ci.com/github/MacPython/scipy-wheels
https://travis-ci.com/github/MacPython/numpy-wheels

**Comment by mattip** [comment]
... and I just submitted to the support.travis-ci.com website as well.

**Comment by mattip** [comment]
I got an answer that 400,000 credits have been added. Whoever is the admin for scipy on travis-ci.com, do you see them at https://travis-ci.com/organizations/scipy/plan?

**Comment by tylerjereddy** [comment]
Yes, I heard back from Travis and they said what you said. The new credits are visible (see below):

![Screen Shot 2020-12-01 at 6 42 15 AM](https://user-images.githubusercontent.com/7903078/100748504-a02cb300-33a0-11eb-8233-f317c3895f02.png)

**Comment by gerrith3** [comment]
Hey @mattip I just pinged Travis folks to look at those you pasted above to make sure they were flowing through the queue.  They have had a bit of backlog in the service queue but as you can see, they are trying to take this very seriously.

**Comment by h-vetinari** [comment]
Needs to be re-milestoned

**Comment by mdhaber** [comment]
We no longer use TravisCI, so I think this can be closed.
