### ISSUE TITLE
stats: statistical test result object?

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#13118]
There are several recent PRs featuring new functions for statistical tests:
- A new binomial test function (gh-12603)
- Page's L (gh-12531)
- Somers' D (gh-12653)
- Alexander-Govern (gh-12873)
- Tukey-Kramer (gh-13002)
- Cramer-von-Mises (gh-11119, merged)

The new `make_tuple_bunch` (gh-12323) is for adding new outputs to existing tests in a backwards compatible way, but **what should the new functions return**?

To finish gh-11119 without needing to make this decision, `cramervonmises` returns a bare-bones `CramerVonMisesResult`:
```
class CramerVonMisesResult:
    def __init__(self, statistic, pvalue):
        self.statistic = statistic
        self.pvalue = pvalue

    def __repr__(self):
        return (f"{self.__class__.__name__}(statistic={self.statistic}, "
                f"pvalue={self.pvalue})")
```
I'm not sure the decision about supporting Python 3.6 was made yet then (is it official?), but the same behavior could have been achieved with `make_dataclass`.

This suggests a few questions.

1. Should there be a class like [`OptimizeResult`](https://github.com/scipy/scipy/blob/06f51e32837b4f78f2630701091cd98ff4c6ddf7/scipy/optimize/optimize.py#L82), say, `StatsTestResult`, that takes care of some of the common behavior, or should we use `make_dataclass`? Or should each test make it's own unrelated custom class? What behavior would we want this class to take care of? For instance, `OptimizeResult` is a subclass of `dict` but includes a `__getattr__` that allows accessing elements as if they were fields.
2. Should fields `statistic` and `pvalue` be standard names of the fields (where applicable) or should the name of the statistic be more specific?

The new `BinomTestResult` currently returned by `binomtest` (gh-12603) brings a few other questions to mind.

3. A relatively expensive calculation that is related but not required by the binomial test is calculation of a confidence interval of the proportion of successes. Currently, a method for performing that test is included in the `BinomTestResult` so that it is easy for the user to follow up a `binomtest` with calculation of the confidence interval, but it does not take time if it is not required. Do we agree that this is a good compromise between performing the CI calculation within `binomtest` and making the CI calculation a totally separate function?
4. How much information about the test that was performed should be returned in the result? Currently, `BinomTestResult` includes (beside `pvalue`)  much of the user's input, including `k`, `n`, and `alternative`. Should it include more of what the user entered (e.g. the proportion of successes of the null hypothesis), or only what it needs to retain for performing follow-up calculations (e.g. confidence interval).

@WarrenWeckesser please feel free to edit this directly

**Comment by rgommers** [comment]
In gh-13462 @mdhaber says: _"We may need something for statistical tests results in the public API, though, because it is beginning to look natural for the returned objects to have methods rather than just contain data."_

I'm not sure that requires the `*Return` classes to be in the public API. Being part of the public API implies that users can sensibly interact with them directly. I don't think that's the case here - all that should be happening is that an instance of the class gets returned to the user, who can then use that. The user should not be instantiating the class, apply `isinstance` checks to it, subclass it, or anything else they could sensibly do with public classes.

**Comment by mdhaber** [comment]
Where do we document its methods?

**Comment by rgommers** [comment]
Depends on how extensive the docs are I'd say. Even if we do it on a separate page, we can convince Sphinx to render that without putting it in the public API.

**Comment by mdhaber** [comment]
That would be fine. The distinction is that there but listed in the main page, and they're not in` __all__` so they can't be imported as easily, right? 

I agree that users shouldn't need to instantiate one. The idea is just that as tests get more capable, they may want to return more complex objects that would benefit from separate documentation (linked from the page of the test function) to allow the use of numpydoc formatting features for methods, returns, etc... (Or if there's some way of doing that on the test function page itself, I've not found it in my experience with `optimize`/`OptimizeResult`.)

If in remember correctly, putting `BinomTestResult` on the main page wasn't the original plan. @WarrenWeckesser , you would have been happy without it being listed there, no? And was putting it in `__all__` related to that?

**Comment by WarrenWeckesser** [comment]
I don't mind removing the result classes from the top-level `stats` namespace, but we still want these documented in the online API docs somehow.

The current online docs for `binomtest` look pretty good. In the "Returns" section of the docstring at http://scipy.github.io/devdocs/generated/scipy.stats.binomtest.html, `BinomTestResult` is a link to http://scipy.github.io/devdocs/generated/scipy.stats.BinomTestResult.html#scipy.stats.BinomTestResult, which documents the attributes and methods of the class. In particular, there is a link for the `proportion_ci` method, http://scipy.github.io/devdocs/generated/scipy.stats.BinomTestResult.proportion_ci.html#scipy.stats.BinomTestResult.proportion_ci.  It would be nice if we can maintain something close to this after we remove `BinomTestResult` from the `scipy.stats` namespace.

As an experiment, in the [pull request for the relative risk function](https://github.com/scipy/scipy/pull/13048), I tried to make the documentation of the return value of `relative_risk` as close to the style of that of `binomtest` as I could.  Not surprisingly,  some compromises are necessary.  Instead of using `` `RelativeRiskResult` `` in the docstring to generate a link to the documentation of `RelativeRiskResult`,  I used `` `~scipy.stats._result_classes.RelativeRiskResult` ``.  The tilde tells Sphinx to show only the last part of the name in the rendered HTML.  `_result_classes` is a private module that will be populated with result class names.  See the PR, including the recent commit messages, for more details.

**Comment by rgommers** [comment]
> The current online docs for `binomtest` look pretty good.

I agree that looks good. The duplication of docs between the `Results` section and the `BinomTestResult` is slightly odd, but removing it from `Results` wouldn't be better. And I also wouldn't try using substitution for now; if the duplication gets bad we could use `@docfiller` later.

>  It would be nice if we can maintain something close to this after we remove `BinomTestResult` from the `scipy.stats` namespace.

That should be possible using `:hidden:`, as I commented on https://github.com/scipy/scipy/pull/13048#issuecomment-787071216

>  I used `` `~scipy.stats._result_classes.RelativeRiskResult` ``. The tilde tells Sphinx to show only the last part of the name in the rendered HTML. `_result_classes` is a private module that will be populated with result class names.

That makes sense, a longer link in the source seems like a fair price to pay, and it won't show up in the html docs.

**Comment by mdhaber** [comment]
I think we decided that statistical tests can return objects that have methods. We don't have to make the classes part of the public API (e.g. listed on the main `stats` documentation page and included in `__all__`), but we can link documentation for the classes from the documentation for the statistical tests. Otherwise, there was not much interest in this issue, so I'll go ahead and close it.
