### ISSUE TITLE
Why do some RV.rvs(1) functions return arrays while others return floats? 

### ISSUE THREAD

**Issue by alexlenail** [scipy/scipy#13171]
Is this intended behavior? 

#### Reproducing code example:
```
>>> scipy.stats.norm().rvs(1), scipy.stats.multivariate_normal().rvs(1)
array, float
```

#### Scipy/Numpy/Python version information:
```
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by rkern** [comment]
Both return arrays for me on scipy 1.4.1.

```
[~]
|12> import scipy

[~]
|13> scipy.__version__
'1.4.1'

[~]
|14> from scipy import stats

[~]
|15> stats.norm().rvs(1)
array([-1.23192364])

[~]
|16> stats.norm().rvs(1)
array([-0.17702427])
```

Can you copy-and-paste the precise inputs and outputs that demonstrate the behavior?

**Comment by rkern** [comment]
If you saw a previous comment from me hit your inbox, please ignore it, as it was complete nonsense that I've deleted.

`multivariate_normal`, being a multivariate distribution, implements a lot of the same interface of the univariate distributions, but doesn't actually share much implementation with them. As such, the logic for determining the shape of the output of an `rvs()` draw is a little different. In particular, it squeezes the shape of the output (i.e. dropping any part of the shape that is `1`), I assume to get the effect of returning an N-vector when just `rvs()` (no `size` argument) is called. This would be to match the behavior of `norm.rvs()` (again, no `size` argument), which returns a scalar. However, the implementer of `multivariate_normal` didn't take into account the case where the user explicitly requested `size=1`, which should return an array of length `1` with the contents of a single draw to be consistent with the behavior of the univariate distributions, in my opinion. I would consider this a bug, but perhaps one that will have to be lived with since it's been in the wild for so long.

**Comment by alexlenail** [comment]
Thanks for that thorough look through, @rkern. I hadn't realized I could do `.rvs()` instead of '.rvs(1)` so I'll switch to that (instead of `.rvs(1)[0]` for `norm()`)

Just to provide more context, the issue that brought me here was actually the following: 

```
>>> A = scipy.stats.norm()
>>> B = scipy.stats.multivariate_normal(np.zeros(5), np.eye(5))

>>> a = A.rvs(1)
>>> b = B.rvs(1)

>>> A.pdf(a), B.pdf(b)
array, float
```

**Comment by mdhaber** [comment]
Thanks for reporting this @alexlenail. It looks like this answered your question. Would you consider the issue closed or would you like us to change something in a backwards compatible way (e.g. mention in documentation)?

**Comment by alexlenail** [comment]
@mdhaber I'm satisfied as is. @rkern ?

**Comment by mdhaber** [comment]
OK, thanks @alexlenail. It sounded to me like @rkern thought we would need to live with this, so I'll close. If someone thinks this deserves more discussion, please re-open and add the "need-decision" label.
