### ISSUE TITLE
Errors made by scipy.optimize.linprog

### ISSUE THREAD

**Issue by Jiahui-Li** [scipy/scipy#13200]
I was solving this linear programming problem:
![image](https://user-images.githubusercontent.com/54797304/101165391-8a094600-3671-11eb-9c7c-86db0b931e31.png)

The function "linprog" failed to do that with a message "There is a linear combination of rows of A_eq that results in zero, suggesting a redundant constraint. However the same linear combination of b_eq is nonzero, suggesting that the constraints conflict and the problem is infeasible."

I check the error described in this message manually, but found this message was just wrong. I also solved this problem successfully using CVXPY and PuLP packages with same parameters. 

In addition, I solved the dual problem using "linprog". The interesting thing was it could give a correct solution to the dual problem.

```
# Define parameters
m = 3
n = 3

p = np.array([7000, 12400, 7100])
q = np.array([13700, 5800, 7000])

C = np.array([[20, 15, 12],
              [14, 12, 10],
              [17, 12, 11]])

# Vectorlize matrix C
C_vec = C.reshape((m*n, 1), order='F')

# Construct matrix A by Kronecker product
A1 = np.kron(np.ones((1, n)), np.identity(m))
A2 = np.kron(np.identity(n), np.ones((1, m)))
A = np.vstack([A1, A2])

# Construct vector b
b = np.hstack([p, q])

# Solve the primal problem
res = linprog(C_vec, A_eq=A, b_eq=b, method='Revised simplex')

#Print results of the primal problem
print("results of the primal problem")
print("message:", res.message)
print("nit:", res.nit)
print("fun:", res.fun)
print("X:", res.x.reshape((m,n), order='F'))
print("--------------------")

# Solve the dual problem
res_d = linprog(-b, A_ub=A.T, b_ub=C_vec, bounds=[(None, None)]*(m+n), method='Revised simplex')

#Print results of the dual problem
print("results of the dual problem")
print("message:", res_d.message)
print("nit:", res_d.nit)
print("fun:", res_d.fun)
print("u:", res_d.x[:m])
print("v:", res_d.x[-n:])
```
Results are
![image](https://user-images.githubusercontent.com/54797304/101167598-1f5a0980-3675-11eb-8592-083761c44e1f.png)
![image](https://user-images.githubusercontent.com/54797304/101167617-297c0800-3675-11eb-9eca-041932d4cb60.png)

Here, A and b are:
![image](https://user-images.githubusercontent.com/54797304/101167382-c1c5bd00-3674-11eb-9fb4-8edf7444b31c.png)

```


#### Scipy/Numpy/Python version information:
<!-- You can simply run the following and paste the result in a code block
```
1.5.2 1.19.4 sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
```
-->

**Comment by ilayn** [comment]
Indeed this might be a numerical precision issue because the example satisfies the regularity 

```python
>>> [-1,-1,-1,1,1,1] @ np.hstack([A, b[:, None]])
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

**Comment by mdhaber** [comment]
Thanks for reporting it. It is a tolerance issue in one of the redundancy removal routines. The matrix is singular, and the routine has identified redundant rows. It checks to see if the `b` vector is compatible, but the tolerance is too tight, so it thinks it isn't. (Same as gh-10038, gh-10349. It's tricky to find tolerances that work for all problems.) Anyway, no harm in loosening it. I will submit a PR shortly.

In the meantime, you can pass `options={'rr': False}` to turn the redundancy removal off, and the problem solves fine. In SciPy 1.6.0 you will be able to choose one of three redundancy remoal routines e.g. `{'rr_method': 'SVD'}`, `{'rr_method': 'pivot'}`, `{'rr_method': 'ID'}` (where only SVD has the problem here), and there will be two more methods that will be much faster for large problems: `method='highs-ds'` and `method='highs-ipm'`; they have their own redundancy removal checks that don't have this problem.
