### ISSUE TITLE
Incorrect values for .a and .b (min and max) for scipy.stats.uniform with non-default args

### ISSUE THREAD

**Issue by reinhold-willcox** [scipy/scipy#13225]
My issue is about the definition of the attributes a and b (corresponding to min and max) for the scipy.stats.uniform distribution. These appear to always return 0 and 1 respectively, corresponding to the default values, regardless of the arguments.

#### Reproducing code example:

```
import scipy.stats as ss
x = ss.uniform(loc=5, scale=5)
print(x.a)  # 0.0
print(x.b)  # 1.0
```

The correct values should be 5.0 and 10.0. 

#### Scipy/Numpy/Python version information:
```
1.5.4 1.18.2 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
I can't tell if that was an oversight or if it is (for some reason) intentional. Can you point to where in the documentation you learned about the `a` and `b` attributes?

**Comment by mdhaber** [comment]
The funny thing is that the initializer of the frozen distribution calls:

```
class rv_frozen(object):

    def __init__(self, dist, *args, **kwds):
        self.args = args
        self.kwds = kwds

        # create a new instance
        self.dist = dist.__class__(**dist._updated_ctor_param())

        shapes, _, _ = self.dist._parse_args(*args, **kwds)
        self.a, self.b = self.dist._get_support(*shapes)
```
but
```
    def _get_support(self, *args):
        """Return the support of the (unscaled, unshifted) distribution.
```
I wonder if this is intentional to call `_get_support` or if it should be calling `support`.

**Comment by pvanmulbregt** [comment]
I'm not convinced that this is a defect. 
`a` and `b` are actually not publicly documented attributes of the distribution object.  Ideally I'd prefer that they have names `_a` and `_b` to make clear they are private.
The support does depend (sometimes non-trivially) on the shape parameters, so the provided `a` and `b` are just a hint, which happens to be all that is needed for many families (e.g. `uniform`, 'beta`).  Using `a` and `b` directly bypasses that logic, and won't work for many distributions.

The `support()` method is public and takes care of all the `loc`/`scale` specifications, as well as any other shape.  Can this method be used instead of the direct access?

**Comment by mdhaber** [comment]
> a and b are actually not publicly documented attributes of the distribution object

Unfortunately, they are documented in [`rv_continuous`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.html) and [`rv_discrete`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_discrete.html).

 > Using a and b directly bypasses that logic, and won't work for many distributions.
The support() method is public and takes care of all the loc/scale specifications, as well as any other shape.

That's why I use the `support()` method, instead of `_get_support()`, to set `a` and `b` when the distribution is frozen. It calculates the actual support based on the shape, loc, and scale, and that will never change since the distribution is frozen.

> Can this method be used instead of the direct access?
I agree from a development perspective that having users call a function is preferable, since we have the flexibility to improve the implementation in a way that's transparent to the users. But since `a` and `b` are public, and since user's apparently use them, I think they should be set by `support` rather than `_get_support()`.

**Comment by pvanmulbregt** [comment]
> Unfortunately, they are documented in [rv_continuous](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.html) and [rv_discrete](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_discrete.html) , so they are public.

Those links refer to _input parameters_ of the `rv_continuous` base class initializer, which are indeed public.  But the `a` and `b` _attributes_ of the initialized object are not documented in the public API, only the _methods_ are in those same links.  Some of the input parameters are stored, but even then not all those are stored under the same name as the input parameter.

**Comment by WarrenWeckesser** [comment]
I'd love to get rid of `.a` and `.b` for the regular (i.e. nonfrozen) distributions, especially since they don't work for distributions where the support depends on the shape parameters (e.g. genextreme, genhalflogistic, genpareto, kappa4, pearson3,  truncexpon, truncnorm, tukeylambda and maybe others).  We might be able to convert these to properties, and generate a deprecation warning whenever one is read, but I don't know how widely these are used in the wild, so I don't know how disruptive that would be.

**Comment by mdhaber** [comment]
@pvanmulbregt 
>  But the a and b attributes of the initialized object are not documented in the public API, only the methods are in those same links.

The attributes are mentioned in the "Subclassing" section at that link.

**Comment by pvanmulbregt** [comment]
This block does occur in the Notes section, and does mention `self.a`.

> For most of the scipy.stats distributions, the support interval doesn’t depend on the shape parameters. `x` being in the support interval is equivalent to `self.a <= x <= self.b`. If either of the endpoints of the support do depend on the shape parameters, then i) the distribution must implement the `_get_support` method; and ii) those dependent endpoints must be omitted from the distribution’s call to the `rv_continuous` initializer.

But just below that are the Attributes and Methods sections, and the only Attribute listed is `random_state`.

I would argue that being in the Notes section alone does not make the `a` attribute  public.

I had a similar thought as Warren on making them properties, or using `__getattr__` to call `support()` and take the appropriate endpoint whilst issuing a warning. But that could also be confusing, as the value of `a` returned under such a scheme is not necessarily the `a` that was used to initialize.

**Comment by mdhaber** [comment]
@reinhold-willcox it sounds like `a` and `b` were really supposed to be private attributes. Since the way they work now is acceptable to the developers, the proposed fix in gh-13228 is not going to be merged, so I will close this issue, too. Sorry I couldn't be of more help! Please use the `support` method in new code.
