### ISSUE TITLE
Problem in linear constraints of Differential Evolution. All the elements of population is getting rejected

### ISSUE THREAD

**Issue by raiuli** [scipy/scipy#13246]
I am using scipy differential evolution. I have to set the following linear constraints. 
0<x1+x2+x3+x4<=1. 
x2+x3=1. 
I have set the following matrix A=[0 1 1 0] B=[1]. 
linear_constraint = LinearConstraint(A,B,B,True). 
I have also set lower and upper bound to 0 and1. 
However, during each iteration, the output of the objective function is InF, whereas the differential evolution is not calling the objective function. It seems all the elements of the population is getting rejected. All the individual of the population is getting rejected due to constraints violation.

If I  try separately to generate the population with a same number of individual using numpy.random.uniform . There are few individuals which satisfy the condition.

Can anyone suggest what is wrong? My Scipy version is 1.5.4 and python 3.7.

Thanks in advances..

**Comment by andyfaff** [comment]
Please supply a minimal working example with which we can reproduce the issue. When creating this example please use a seed so that we can reproduce exactly what your computer does.

Note, there are several tests examining non-linear and linear constraints, hopefully our testing is fairly comprehensive of this functionality (starting around https://github.com/scipy/scipy/blob/master/scipy/optimize/tests/test__differential_evolution.py#L785)

**Comment by andyfaff** [comment]
Bear in mind I am not an expert in LinearConstraint specification at all. But I think your constraint specification isn't correct you need to be doing something along the lines of:

```
A = np.array([[1.0, 1.0, 1.0, 1.0],
                        [0.0, 1.0, 1.0, 0.0]])
LinearConstraint(A, [0.0, 1.0], [1.0, 1.0])
```
