### ISSUE TITLE
**kwargs for optimize.root_scalar and alike

### ISSUE THREAD

**Issue by sphh** [scipy/scipy#13258]
**Is your feature request related to a problem? Please describe.**

I want to find the root of a function, which takes keyword arguments.

**Describe the solution you'd like**

Add a `kwargs` argument to the optimize routines, which are passed on to the function, which should be minimized or whose root should be found:
```python3
def f(x, a, b=0, c=0):
    return a * x**b + c

def find_root(a, **kwargs):
    scipy.optimize.root_scalar(f, args=(a,), kwargs=kwargs, method='secant', x0=-0.5, x1=0.5)

find_root(1)
find_root(1, b=2)
find_root(1, c=-1)
find_root(1, b=2, c=-1)
```

Are there any reasons, why this is not implemented?

**Describe alternatives you've considered**

I tried to pass the keywords as part of the `args` argument, but since I want to use the function `f` also from outside the `find_root` function, this becomes quite awkward.

**Comment by mdhaber** [comment]
Probably the thought was to simplify the number of arguments in the API. You can do what you're looking for by wrapping your function, though.
```
def f(x, a, b=0, c=0):
    return a * x**b + c

def wrapped_f(x, a, kwargs):
    return f(x, a, **kwargs)

def find_root(a, **kwargs):
    return scipy.optimize.root_scalar(wrapped_f, args=(a, kwargs), method='secant', x0=-0.5, x1=0.5)
```
I don't have a strong opinion either way about whether we should add something for kwd arguments.

**Comment by sphh** [comment]
That wrapping is a really good idea. Could this be added to the documentation, if it will be decided against adding `kwargs` to `scipy.optimize`?

**Comment by mdhaber** [comment]
Perhaps. Let's see what others think.

**Comment by mdhaber** [comment]
@tupui Most optimizers (and other functions that accept callables as inputs) don't have a `kwargs` argument. Is there anything to do about that?
* I don't think we want to add `kwargs` to every one of these functions (personally, I wish `args` were not an argument to practically every function that accepts a callable). 
* Regarding https://github.com/scipy/scipy/issues/13258#issuecomment-747728861, I don't think that `root_scalar` deserves a note or an example about this any more than `root`, `minimize`, or `curve_fit` do. 
* For that matter, I don't think it's more important to document it for `optimize` than `stats` (e.g. `bootstrap`, `permutation_test`) or `integrate` (`solve_ivp`, `quad`), and I don't think we'd want to add it to the tutorial of every subpackage. 

Do we want to add it to the introduction to the tutorial, or rely on users to know these sorts of Python features? 
What do you think?

**Comment by tupui** [comment]
I am also not a fan of allowing `args` (and `kwargs` as well). I would prefer if we did not allow that at all and instead showed in a tutorial how to use a wrapper, partial or something else.

**Comment by mdhaber** [comment]
Thanks. I've added an example in gh-17674.

**Comment by WarrenWeckesser** [comment]
We had a conversation about the use of `args` for `scipy.integrate.solve_ivp` back in 2018-2019: https://github.com/scipy/scipy/issues/8352.  We ended up enhancing `solve_ivp` with the `args` parameter.  

The [argument that I made there](https://github.com/scipy/scipy/issues/8352#issuecomment-443539907) for the use of `args` was that, outside of a first course in DEs, almost *every* system of differential equations that our users will solve will have parameters.  The same is true for most optimization and root-finding  problems.  In the examples used in an introductory text or course on numerical methods, additional parameters just obscure the pedagogy, but once you are beyond the educational material and into solving "real" problems, systems *with* parameters are the usual case, and systems without parameters are the exception.

Without an `args` parameter, almost every user will have to create a wrapper (with a lambda or an explicit `def`) that puts the extra parameters in a closure.  A wrapper will be needed for the main user-defined function, and for any additional functions (such as Jacobian derivatives, Hessians, event functions, etc).  Since the point of a library is to make life easier for our users, the `args` parameter is a natural feature to provide.  We should continue to support it.

Currently, where `args` is used, it is limited to positional arguments.  I understand the reluctance to create another parameter for keyword arguments.  Before rejecting this outright, it might be helpful to consider alternatives that allow keyword parameters to be given without a new parameter, and without requiring that the user create a wrapper.  Off the top of my head: in addition to a sequence of positional parameters, `args` could accept an object, say an instance of a class called `Args`, that has `.args` and `.kwargs` attributes.  So the call of `root_scalar` in the example above would be something like

    kwargs = {'b': 2, 'c': -1}
    result = root_scalar(wrapped_f, args=Args(args=(a,), kwargs=kwargs), [...])

There are probably other equally simple API solutions to the problem.

**Comment by tupui** [comment]
I see the argument for args and such, but as a user I always need to go to the doc because this is handled differently in different libraries (some will accept a param args with a list, others a dict, or some unpacking, the list goes on and on). So IMHO we are not really helping that much.

**Comment by WarrenWeckesser** [comment]
> So IMHO we are not really helping that much.

Read the comments over in https://github.com/scipy/scipy/issues/8352.  Many users report that `args` *is* helpful.

> So to me, if we do want to add some parameters, we must be consistent and change this in one go.

Yes, definitely.  The handling of an `args` parameter should be consistent throughout the scipy code.

> Going with one function at a time (and it's deprecation cycle) is just annoying for users (and us).

Whether or not a deprecation cycle is required depends on the API that is adopted.  My suggestion above does not require any deprecation.

**Comment by tupui** [comment]
Sure it's an opinionated piece. Does not make it a ground truth about how things should be.

I am not saying it does not bring value, I am saying it will still require users to poke around to know how to do things and use the feature (even more true until we have a uniform API).

Knowing how to use the features of the language you are coding with should not be "too much" of our concern. There are great packages like FastAPI that go a long way using more advanced features to have a cleaner API. Yes it requires users to understand a bit more how Python works, but in the end people seem to be happy.
