### ISSUE TITLE
Typing for scipy.spatial

### ISSUE THREAD

**Issue by dair-targ** [scipy/scipy#13299]
**Is your feature request related to a problem? Please describe.**
It would be great to have typing for spatial (e.g. Voronoi) as some fields are undocumented (e.g. ridge_dict), and some are not detected by IDE introspection (e.g. vertices).

**Describe the solution you'd like**
Add typing to `scipy/spatial/qhull.py` *-or-* add stubs if the `qhull.py` heavily depends on C code.

**Describe alternatives you've considered**
Add typing stubs outside of scipy - that would be time-consuming and hard to maintain if spatial (or qhull) change or add API.

**Additional context (e.g. screenshots)**
(none)

**Comment by rgommers** [comment]
There is no `qhull.py`, it's Cython code. Adding type annotations directly in Cython code seems to be possible (http://docs.cython.org/en/latest/src/tutorial/pure.html#pep-484-type-annotations), but it seems a little unusual and I'd expect some problems like conflicts with the regular way of typing parameters in Cython. 

If someone wants to try the inline thing please do, but otherwise adding type stubs is the way to go. A PR for that would be very welcome. Annotations should use `numpy.typing` as discussed in https://github.com/scipy/scipy/pull/10844#issuecomment-752194177.
