### ISSUE TITLE
ENH: Desire for joint distribution factory

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#13343]
I was wondering if you would be interested in having a general class to construct joint distributions?

I often want to construct a joint distribution and sample from it. There are 2 cases: *(i)* marginals are independants; *(ii)* there is a dependency. The dependency can be modelled using a copula. Although the copula are not here, it is simple to construct using existing ingredients. And there are quite some libraries out there with code we could borrow (ex. https://github.com/blent-ai/pycopula)

I propose something in this direction:

```python
import numpy as np
from scipy import stats

class GaussianCopula:
    def __init__(self, mean=None, cov=1):
        self.density = stats.norm()
        self.mv_density = stats.multivariate_normal(mean=mean, cov=cov)

    def random(self, n):
        x = self.mv_density.rvs(size=n)
        return self.density.cdf(x)

class JointDistribution:
    def __init__(self, dists, copula=None, seed=None):
        self.rng = np.random.default_rng(seed)
        self.dists = dists
        self.copula = copula
        self.d = len(self.dists)

    def random(self, n):
        if self.copula is None:
           # this means marginals are independents
            sample = self.rng.random((n, self.d))
        else:
            sample = self.copula.random(n)
    
        for i, dist in enumerate(dists):
            sample[:, i] = dist.ppf(0.5 + (1 - 1e-10) * (sample[:, i] - 0.5))
        return sample
```

And you can use it as:
```python
dists = [stats.gamma(2), stats.norm]
copula = GaussianCopula(mean=[0, 0], cov=[[1., 0.5], 
                                          [0.5, 1.]])
joint_dist = JointDistribution(dists, copula)
sample = joint_dist.random(512)
```

![Sampling joint distribution](https://user-images.githubusercontent.com/23188539/103550550-59ebd780-4ea9-11eb-9fb0-ff11de5b6815.png)

**Comment by rkern** [comment]
When code exists in other packages, I usually don't see a big need to absorb them into scipy. It seems like `pycopula` could use some more tooling to use `scipy.stats` distribution objects as marginals, but that can be contributed to `pycopula`. [Others](https://github.com/sdv-dev/Copulas) already use `scipy.stats` distribution objects.

**Comment by tupui** [comment]
> When code exists in other packages, I usually don't see a big need to absorb them into scipy. It seems like `pycopula` could use some more tooling to use `scipy.stats` distribution objects as marginals, but that can be contributed to `pycopula`. [Others](https://github.com/sdv-dev/Copulas) already use `scipy.stats` distribution objects.

The thing is that to find this package, you need to know that you want a *copula*. I was at least a years in a PhD working with joint distributions before knowing it existed (I had always independence assumptions). IMO there is a need to have a way to construct joint distribution and in terms of user story I find it odd that I would need to install an extra package for this. There are tons of 1d distributions, a few of n-d but no way to mix distributions.

**Comment by josef-pkt** [comment]
I think copulas by itself are a bit boring. To make them useful requires a lot more surrounding and usage code, e.g. for fitting copulas. That fits better in specialized packages.
(I have had the plain copulas without extras in the statsmodels sandbox for 10 years or so.)

What scipy could and should provide is more support for these kind of methods, e.g. I have been waiting for a long time for the cdf of the multivariate t distribution, as complement to current scipy multivariate normal cdf (based on old Fortran code).
License compatible code is available in other languages, e.g. matlab or Fortran.

pycopula seems to only allow bivariate t-copula with numerical integration.
sdv-dev\copulas looks good from the outside, but only mentions t-distribution for the univariate distribution.

(in statsmodels I'm using 1-dim numerical integration of the multivariate normal cdf for the cdf of the multivariate t)

**Comment by rkern** [comment]
Using copulas correctly to model multivariate distributions does require the specialized knowledge about copulas. I would not want to paper over that specialized knowledge with a generic API for "joint distributions with correlations". Bad things have happened in the past when people did this. [Really bad.](https://www.wired.com/2009/02/wp-quant/)

**Comment by josef-pkt** [comment]
I was using that wired article for teaching a long time ago. And would have like t-copula has heavy tail alternaive.

However, I'm partially changing my mind

I think scipy.stats could have GaussianCopula as a special multivariate distribution. (Although I haven't looked at recent changes in scipy.stats for that)

@tupui is talking about general or industrial applications. We don't have to add only things that cannot be misused by finance and extreme value (theory) users.
I was using the equivalent of a gaussian copula sometimes in experimental code or just to create some multivariate random numbers. A long time ago I also answered stackoverflow questions for that.

I haven't looked at copulas in some time and don't know which methods for a multivariate copula distribution could be easily supplied, besides `rvs`.

**Comment by josef-pkt** [comment]
a bit more background

sdv-dev/Copulas includes vine copulas

When I was looking at copulas around 10 years ago, it was gaussian as the only multivariate (>2) case and all others only for bivariate case. t-copula requires numerically good cdf and is not as easy to work with.
(Without mvt-cdf, and with only bivariate copulas I thought the general use cases of copulas where to limited.)

Since then, vine and nested copula construction extended pairwise copulas to the multivariate (>2) case. That requires a lot of additional work. (and I wasn't interested enough anymore to do more than read a few articles.)

**Comment by tupui** [comment]
> Using copulas correctly to model multivariate distributions does require the specialized knowledge about copulas. I would not want to paper over that specialized knowledge with a generic API for "joint distributions with correlations". Bad things have happened in the past when people did this. [Really bad.](https://www.wired.com/2009/02/wp-quant/)

Sure copula requires some knowledge, but you could still omit this and don't consider any correlation. Which in an industrial context is still very useful (in the cases I had to deal with, you simply have no way to get the copula). As for the crisis some argue it's not copulas fault but correlation: http://samueldwatts.com/wp-content/uploads/2016/08/Watts-Gaussian-Copula_Financial_Crisis.pdf. In any case, I don't thing this is really relevant. With any tool you can do nasty things 😅

**Comment by tupui** [comment]
> I think copulas by itself are a bit boring. To make them useful requires a lot more surrounding and usage code, e.g. for fitting copulas. That fits better in specialized packages.

Sure, but I had the feeling fitting methods would be too much here if there were no wish for copula in general.

> (I have had the plain copulas without extras in the statsmodels sandbox for 10 years or so.)

But then do you think this could fit in statsmodels? Not saying it should absolutely fit anywhere 😄 
I just think that having a simple way to mix distributions is missing in one of the "big packages".

**Comment by josef-pkt** [comment]
@tupui I'm not sure what the "uncorrelated" use case is

Isn't a gaussian copula with zero correlation just a collection of independent univariate distributions?

I'm not sure, because I have only seen cases where we want correlation in the copula to have dependent or correlated random variables

**Comment by tupui** [comment]
> @tupui I'm not sure what the "uncorrelated" use case is
> 
> Isn't a gaussian copula with zero correlation just a collection of independent univariate distributions?

It is yes, in the code I was just avoiding to deal with the copula in this case.

> I'm not sure, because I have only seen cases where we want correlation in the copula to have dependent or correlated random variables

I can talk for things I experienced in a sensitivity analysis context. When you have a physical system you are trying to model with different input variables and some output. If you look at some simple flood modelling: flow rate and coefficient of friction of the river at the input and water level at the output. We can assume that the flow rate is gaussian distributed, but for the friction coefficient we often don't know anything and assume it's uniform. Still we want to do a joint distribution to sample from and maybe construct a surrogate model using some Polynomial Chaos for instance. In this context, there is no need of a copula (because we have no clue or not enough data to calculate).
In an industrial context like this (I also did some work in aeronautic and it's the same), it is already hard to get a PDF, so a copula...

**Comment by rkern** [comment]
If one isn't using a copula to model the dependence between these variates, then I don't see what `JointDistribution` is doing that requires special infrastructure. Users can (and should) call `.rvs()` on the separate distribution objects.

**Comment by josef-pkt** [comment]
But then do you think this could fit in statsmodels? 

Yes it fits in statsmodels, but it requires work especially on unit tests.
https://github.com/statsmodels/statsmodels/issues/4046

statsmodels also provides general statistical tools that don't have much internal use yet.
The internal use of copulas would be multivariate model and extreme value models. We are still behind in multivariate models, and I stopped looking at extreme value theory at about the same time as copulas.

The main messy but important part of copulas is that we can construct complex dependence structures. Gaussian copulas don't have tail dependence, so we need other copulas when we are interested in extreme risk.
But for regular, non-tail usage, gaussian copulas should cover most cases.
However, this might be important in flood modelling because floods are an "extreme event". i.e. often requires extreme value theory, AFAIK.

I was looking at copulas mainly in the context of risk analysis and extreme value theory.

@rkern outside gaussian distribution, no-correlation does not imply independence, e.g. uncorrelated mv-t still has dependence :)
(I got messed up once by this when writing unit tests, and had to ask on stats.stackexchange)

**Comment by rkern** [comment]
> We don't have to add only things that cannot be misused by finance and extreme value (theory) users.

> With any tool you can do nasty things

To be clear, I'm not opposed to copulas per se, or even implementing them in `scipy.stats`. But I don't think we should wrap them up in an interface avoids the terminology or presents them as "the default way to model joint distributions". And I think that significant tooling is needed around copulas (fitting, evaluating the fit, providing a variety of copulas, etc.) that really do deserve space in their own package. And since those packages exist, I don't feel a strong need to absorb them into scipy.

> outside gaussian distribution, no-correlation does not imply independence, e.g. uncorrelated mv-t still has dependence :)

Indeed, but independent marginal distributions appears to be what `JointDistribution` is proposing to implement.

**Comment by tupui** [comment]
> If one isn't using a copula to model the dependence between these variates, then I don't see what `JointDistribution` is doing that requires special infrastructure. Users can (and should) call `.rvs()` on the separate distribution objects.

> Indeed, but independent marginal distributions appears to be what `JointDistribution` is proposing to implement.

Yes it is. And I would argue that even something as simple as that is not trivial for everyone. Sure it is just a matter of calling the inverse CDF. But I can tell you that I had to explain this so many times to people working with PDF everyday. Lots of people just have no clue this is even possible really. There are quite some tutorials and questions out there showing this.
It's like the ddof in the variance, dead simple and yet almost all the time misused.

**Comment by tupui** [comment]
@rkern We can move the discussion to `statsmodels` and close this issue if you would prefer?

**Comment by rkern** [comment]
> Sure it is just a matter of calling the inverse CDF. 

If you're not using a copula and instead joining independent marginal distributions, you should use the `.rvs()` methods of each marginal distribution separately. Inverting the CDF of a distribution is only a backup for when no other algorithm exists for the marginal distributions. It's usually numerically inaccurate and slow.

> Lots of people just have no clue this is even possible really.

Some problems are best solved with tutorials and documentation rather than APIs. I think this is one of them.

> We can move the discussion to `statsmodels` and close this issue if you would prefer?

Sure.

**Comment by tupui** [comment]
> > Sure it is just a matter of calling the inverse CDF. 
> 
> 
> 
> If you're not using a copula and instead joining independent marginal distributions, you should use the `.rvs()` methods of each marginal distribution separately. Inverting the CDF of a distribution is only a backup for when no other algorithm exists for the marginal distributions. It's usually numerically inaccurate and slow.
> 

Sure, I should have said I was also considering that you can already have your own sample uniformly distributed. I had the QMC samplers in mind. This was some small MVP I wrote.
