### ISSUE TITLE
scipy.spatial.transform.Rotation object can not be deepcopied in v1.6.0 anymore

### ISSUE THREAD

**Issue by cosama** [scipy/scipy#13358]
It looks like a change in `scipy.spatial.transform.Rotation` in the most recent version `v1.6.0` does break the ability to `deepcopy` the respective object. It worked in previous versions.

#### Reproducing code example:

```
from scipy.spatial.transform import Rotation
import copy
copy.deepcopy(Rotation([1, 0, 0, 0]))
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.7/copy.py", line 275, in _reconstruct
    y = func(*args)
  File "/usr/lib64/python3.7/copy.py", line 274, in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
  File "/usr/lib64/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.7/copy.py", line 221, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib64/python3.7/copy.py", line 221, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib64/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
  File "stringsource", line 2, in View.MemoryView._memoryviewslice.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

#### Scipy/Numpy/Python version information:
```
1.6.0 1.19.5 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)
```
The bug seems to be present also on other versions of python. I found it in 3.8 as well.

**Comment by AtsushiSakai** [comment]
Might be related that the "spatial.transform.rotation" was cythonized in #12286

**Comment by t-kurtke** [comment]
Might be obvious but I'd like to add that this also breaks pickling. Are there no tests for this kind of stuff?

**Comment by tylerjereddy** [comment]
We definitely do not have tests that all SciPy objects can be serialized/deepcopied/pickled, though we do generally try quite hard to remain backwards-compatible in behavior within the bounds of the volunteer effort.

I can gently ping @nmayorov for their thoughts on desired behavior here before I'd want to dive in myself.

**Comment by andyfaff** [comment]
Pickling is vital for multiprocessing. During development of a class I'd say a key test would be to check for pickleability.

**Comment by tylerjereddy** [comment]
On the other hand, if we ultimately expand to providing `workers` arguments to many class methods as we expand our parallel support, the basis for using multiprocessing on something already using multiprocessing may be less clear.

Seems like case-by-case basis. Anyway, I don't have a strong view here--I'd just prefer to hear Nikolay's thoughts first.

**Comment by tylerjereddy** [comment]
Also, classes focused on file handling would likely be tricky for serialization.

**Comment by andyfaff** [comment]
@tylerjereddy I can provide an example here. I use many different frozen `stats.rv_continuous` objects to represent variable priors in a Markov Chain Monte Carlo analysis. The model (containing lots of those distribution objects) is setup in a master process, and I then use multiprocessing to parallelise sampling. It's vital that the stats objects are pickleable so that the model can be dispatched to those processes. Thus, it's often not scipy that's being asked to carry out the parallelisation, it's at a higher level. Support for parallelisation is not only developing ways of parallelising code within scipy (e.g. `workers`), it's also working to make sure that other code can use it in a parallel manner. One aspect to this involves being able to pickle objects (apart from the impossible, like file-handles).

**Comment by tylerjereddy** [comment]
@andyfaff Yes, I understand that people use more than one core with SciPy functions sometimes. I'd just like not to be too harsh on the generalization--perhaps occasionally methods will have nice optimizations related to generators or memory usage patterns and folks might be able to work around that intelligently in their own workflow anyway by carefully deciding what to send from the main process.

Indeed, Cython will sometimes automatically disable pickling of certain objects to discourage usage in i.e., multiprocessing because of the exceptionally high overhead or complications with memory pointers. I believe this was true for classes containing structures at least a while ago. I agree we should emphasize usability in parallel workflows, but I don't agree that we should blindly patch all cases where a low-level acceleration tool is making decisions about what should be serialized.

In this case, it may be as easy as adding ` @cython.auto_pickle(True)`, but I don't know offhand if the tradeoffs will be expensive from an overhead standpoint. If memoryviews or C/C++ objects/pointers are involved, serialiazation may be substantially more difficult I think and perhaps not always worth our effort.

Hopefully this particular case is a straightforward fix though.

**Comment by ev-br** [comment]
A mechanical fix is indeed straightforward, https://github.com/scipy/scipy/pull/13425, but more real-life testing would be welcome. I suspect OP wanted deepcopying for some reason, can you check gh-13425 fixes your use case @cosama ?
Also a multiprocessing run would be also welcome.

**Comment by cosama** [comment]
@ev-br Thank you so much for providing a fix. I tested your merge request and it works. I had also a quick look at your tests and they definitely cover my use-case. Would be great if this could get in by the next release. I think this will also help to show what is necessary to allow this to work for other classes within `scipy`. I was a bit lost here, not knowing much of the internals of `cython`.

**Comment by AKuederle** [comment]
Just as an additional note: As this breaks pickeling, it also breaks hashing using `joblib` and hence, the provided Cashing and Parallel processing functionality.
