### ISSUE TITLE
`if rtol < _rtol / 4` should be changed?

### ISSUE THREAD

**Issue by jamadagni** [scipy/scipy#13407]
Hello. This is wrt this line:

https://github.com/scipy/scipy/blob/ab1c0907fe9255582397db04592d6066745018d3/scipy/optimize/zeros.py#L1351

Note that the next line reads:

`raise ValueError("rtol too small (%g < %g)" % (rtol, _rtol))`

… whereas the test is for `rtol < _rtol / 4` and not `rtol < _rtol`.

As I note that in all earlier root finding methods than TOMS748 the test only reads `rtol < _rtol`, I believe this should be the same for TOMS748 also. I am not sure why the `/ 4` exists.

As I read in [the Boost documentation](https://www.boost.org/doc/libs/1_75_0/libs/math/doc/html/math_toolkit/roots_noderiv/root_termination.html) that tolerances below 4 epsilon aren't practical to achieve, and `_rtol` is actually `4 * eps`, I believe `rtol < _rtol` is the correct test.

Please clarify the documentation or error message string if not.

Thanks.

**Comment by mdhaber** [comment]
@pvanmulbregt it looks like the minimum `rtol` of TOMS748 has been `_rtol / 4` since the first commit of gh-8876. Do you remember where that came from, t hat is, why it was not `_rtol` like the other bracketing root finders?

**Comment by pvanmulbregt** [comment]
Agree that the ValueError message doesn't match the actual test performed.    
I don't recall why `toms748` allows the user to specify a lower tolerance than `_rtol`. The default value of the `rtol` keyword is `_rtol`. It may have been due to an initial implementation using `np.info(float).eps` and then switching it to use `_rtol` before the PR was finalized.  All the tests in `test_zeros.py` pass in `rtol = 4 * finfo(float).eps`.
The tolerance check performed in `toms748` is `np.isclose`, which isn't exactly the same as the one referred to in the Boost documentation.  Boost uses `rtol` and "<", whereas `np.isclose` uses both `xtol` and `rtol` and the "<=" comparison.

**Comment by mdhaber** [comment]
Thanks @pvanmulbregt! (We've missed you!)

I created gh-17687 to correct the error message. I also demonstrated that `rtol = eps` can reduce the residual compared to `rtol = 4*eps`, so it is reasonable to allow the user to try it. Care to take a look? It's a one-line change aside from the test, so it shouldn't take too long!
