### ISSUE TITLE
10,000 times speedup for generating random numbers from the cosine distribution

### ISSUE THREAD

**Issue by ivv101** [scipy/scipy#13417]
I've been trying to simulate an inhomogeneous Poisson point process with an oscillating intensity function and 
scipy.stats.cosine.rvs has been extremely slow (1 minute for 60,000 events). I implemented the [inverse transform sampling method](https://en.wikipedia.org/wiki/Inverse_transform_sampling): to get a random variate x from a distribution f we generate a random q from [0,1) and then find x from cdf(f)(x) = q. Seems to be much faster.

```
import scipy.stats
import numpy as np

def cosine_rvs(n):
    
    x = np.linspace(-np.pi, np.pi, 1000)
    q = (np.pi + x + np.sin(x)) / (2 * np.pi)        
    rv = np.interp(np.random.rand(n), q, x) 
        
    return rv    

# testing
n = 20_000
%time rv_fast = cosine_rvs(n)
%time rv_slow = scipy.stats.cosine.rvs(size=n) 
scipy.stats.ks_2samp(rv_slow, rv_fast) 
```

**Comment by WarrenWeckesser** [comment]
FYI: There is another open pull request to improve the cosine distribution here: https://github.com/scipy/scipy/pull/10170

**Comment by mdhaber** [comment]
Thanks @ivv101. Inverse transform sampling is the default behavior unless the distribution defines an `_rvs` method. The problem is that the cosine distribution does not currently have a `ppf` method. Once that is implemented (e.g. using your expression for the inverse CDF) the `rvs` method will perform inverse transform sampling much faster. gh-10170 will take care of this and more.

**Comment by mdhaber** [comment]
I thought I'd also mention that a similar idea for numerically inverting the CDF using interpolation is in gh-13319, in case you're interested.

**Comment by ev-br** [comment]
Also an ancient attempt, linking mostly for the discussion in that PR: https://github.com/scipy/scipy/pull/3103
