### ISSUE TITLE
BUG: skew for empty array raises

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#13410]
statsmodels has a test failure with unreleased scipy, which looks like a backwards incompatible change in scipy.

I don't have a master version of scipy, so I cannot verify this.

with old scipy
```
>>> stats.skew([])
nan
```

my guess is with scipy master this raises

```
        with np.errstate(all='ignore'):
>           zero = (m2 <= (np.finfo(m2.dtype).resolution * a.mean(axis))**2)
E           AttributeError: 'float' object has no attribute 'dtype'
```

m2 comes from a call to moment: `m2 = moment(a, 2, axis)`

aside: I'm not really familiar with this part of statsmodels. The unit tests uses pandas dataframe that has a column with only nans and does dropna before calling (`apply`) our function which then calls scipy skew.

If someone can verify this, otherwise I have to go more thoroughly through the statsmodels code (and learn pandas apply)

**Comment by josef-pkt** [comment]
AFAICS

np.nan is float causes the problem because it doesn't have a dtype

```
>>> type(np.nan)
<class 'float'>
>>> type(stats.moment([]))
<class 'float'>
>>> type(stats.moment([np.nan]))
<class 'numpy.float64'>
```

my python environment is at scipy.__version__ '1.3.0'

**Comment by mdhaber** [comment]
Looks like we added this in gh-13254. Good to catch it now!

@peterbell10 thoughts on the best way to fix it?

**Comment by peterbell10** [comment]
Interestingly gh-13388 actually fixes `skew` and `kurtosis`. But only because it avoids  the `moment` code which returns the `np.nan`:
https://github.com/scipy/scipy/blob/bab1925319d80ba11928c9a3985781c310b3a1b7/scipy/stats/stats.py#L1031-L1036

I would argue this code is wrong though; it should preserve input's scalar type and not indiscriminately return `float`. It also returns the wrong shape, completely ignoring the `axis` argument. I'll make a PR making `moment` more consistent.
