### ISSUE TITLE
linear_sum_assignment - support for matrices with more than 2^31 elements

### ISSUE THREAD

**Issue by AdeelK93** [scipy/scipy#13421]
The `linear_sum_assignment` function is super useful and really fast! Thank you!
Unfortunately I'm encountering a crash with matrices that have more than 2^31 elements, and I've tried on MacOS and Linux.
Is this a surmountable problem? Is there a way to support big matrices like this one? Really appreciate it!

#### Code that works (40k * 40k)
```python
from scipy.sparse import random
from scipy.optimize import linear_sum_assignment

m = random(40000, 40000, density=0.05).toarray()
print("array ready")
solution = linear_sum_assignment(m)
print("LSA solved")
```

#### Code that breaks (50k * 50k)
```python
from scipy.sparse import random
from scipy.optimize import linear_sum_assignment

m = random(50000, 50000, density=0.05).toarray()
print("array ready")
solution = linear_sum_assignment(m)
print("LSA solved")
```

#### Error message:
```
libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector
```

#### Scipy/Numpy/Python version information:
```
1.6.0 1.19.5 sys.version_info(major=3, minor=8, micro=7, releaselevel='final', serial=0)
```

**Comment by mckib2** [comment]
Hi @AdeelK93 , this might be due to a downcasting from `npy_intp` to `int` [here](https://github.com/scipy/scipy/blob/4fd523c6df445cdf5dc61f6018a81abd3422ffec/scipy/optimize/_lsap_module.c#L59).  The laptop I'm working on right now doesn't have enough memory to store these arrays, but I can try with a larger machine

**Comment by fuglede** [comment]
Would `scipy.sparse.csgraph.min_weight_full_bipartite_matching` do the job for you? That's the sparse equivalent of `linear_sum_assignment`.

**Comment by AdeelK93** [comment]
Thank you @mckib2b ! Really appreciate it.

@fuglede unfortunately `min_weight_full_bipartite_matching` gives me a ValueError with the sparse rectangular matrices I'm working with, as that function requires full matching. I could not figure out a way to reduce my matrix to only include full matches, something `linear_sum_assignment` seems to be quite good at.

**Comment by fuglede** [comment]
@AdeelK93 `linear_sum_assignment` does have that exact same requirement; without it, results tend to be fairly trivial. For instance, if all costs are positive, and you don't require anything about the matching, then the empty matching is optimal.

See also [this test](https://github.com/scipy/scipy/blob/04b48ecb57e580304a106c111eccedbfc83dc1bc/scipy/optimize/tests/test_linear_assignment.py#L71) which tests that one method fails if and only if the other method fails.

So they truly are on-the-nose equivalent. Now, your comment seems to suggest that you have an input for which one fails but the other doesn't. So that's a bug: Either, `min_weight_full_bipartite_matching` has erroneously detected infeasibility, or `linear_sum_assignment` has failed to do so. Would you be able to share your input in a separate issue?

**Comment by AdeelK93** [comment]
Thank you for the very thoughtful response. I believe `linear_sum_assignment` is failing to detect infeasibility, but it's pretty straightforward to work around. I'd much rather filter out the infeasible results than get the error!

Since I happen to be maximizing cost, the 0s actually are exactly what I want. I've spent some time this past week verifying these results on paper and they appear to be correct for me. But for someone minimizing cost, I can see how this can be an issue.

This is how I filter out infeasible results from `linear_sum_assignment`, and how `min_weight_full_bipartite_matching` returns an error. Would you like me to file a new issue this?

```python
import numpy as np
import pandas as pd
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import min_weight_full_bipartite_matching
from scipy.optimize import linear_sum_assignment

# my input dataset
df = pd.DataFrame.from_records([(1,0,1),(1,1,1),(1,2,2),(2,1,2)], columns = ["rows","cols","scores"])
print(df)

# convert df into coo_matrix
row  = df.rows.values
col  = df.cols.values
data = df.scores.values
m = coo_matrix((data, (row, col)))
print(m.toarray())


# linear sum assignment works!
solution = linear_sum_assignment(m.toarray(), maximize=True)

# you'll note that some of these assignments are invalid
solution_df = pd.DataFrame(np.column_stack(solution), columns=['rows','cols'])
print(solution_df)
# gotta filter them out and eliminate that [0,0] pair
valid_solution_df = df.set_index(['rows','cols']).merge(solution_df.set_index(['rows','cols']), on = ['rows','cols'], how='inner')
print(valid_solution_df)

# but min_weight_full_bipartite_matching does not work with this
min_weight_full_bipartite_matching(m, maximize=True)
```

**Comment by fuglede** [comment]
@AdeelK93: Thanks for the complete example. In your example, both are working as expected, exactly because zeros are not interpreted by `linear_sum_assignment` as missing edges, but rather low-cost edges. The intended way to represent missing edges while using `maximize=True` is to use negative infinity. Doing so, you get the expected error for `linear_sum_assignment` as well:

```
In [7]: m
Out[7]:
array([[-inf, -inf, -inf],
       [  1.,   1.,   2.],
       [-inf,   2., -inf]])

In [9]: linear_sum_assignment(m, maximize=True)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-d3a71ea8f22a> in <module>
----> 1 linear_sum_assignment(m, maximize=True)

c:\users\sorfj\miniconda3\lib\site-packages\scipy\optimize\_lsap.py in linear_sum_assignment(cost_matrix, maximize)
    103         return (b[indices], a[indices])
    104     else:
--> 105         return _lsap_module.calculate_assignment(cost_matrix)

ValueError: cost matrix is infeasible
```

Note also that depending on your actual inputs, using zeros as an approximation of missing edges might be error prone: It is possible to create an example where a full matching that does not involve zeros _does_ exist, but for which the inclusion of zeros end up causing zero-weight (i.e. non-existent) edges to be part of the matching. A simple example is

```
[[1 2]
 [x 1]]
 ```

Here, using `-np.inf` will give you the expected (unique) matching, but using `0` will give you an otherwise infeasible solution, even though a feasible one exists:

```
In [13]: linear_sum_assignment([[1, 2], [-np.inf, 1]], maximize=True)
Out[13]: (array([0, 1], dtype=int64), array([0, 1], dtype=int64))

In [14]: linear_sum_assignment([[1, 2], [0, 1]], maximize=True)
Out[14]: (array([0, 1], dtype=int64), array([1, 0], dtype=int64))
```

**Comment by AdeelK93** [comment]
That's a great example, and a scenario I'll need to think through more.

In my particular case, I'm trying to find the best 1-to-1 pairing between two sets, where it's perfectly acceptable to not find such a pair, as optimized by the costs. The cost I'm using here is a score (from a separate model I've got) going from 0 to n, where 0 is not a good pair at all, and n is an excellent pair.

Since I define 0 as a bad pair in my scoring model, I think it's appropriate for me to equivalently define missing edges as 0. Though I like your suggestion about using a large negative number as well (or alternately, adding a large positive intercept number to my initial sparse matrix). I'll certainly be experimenting with that.

**Comment by AdeelK93** [comment]
Thank you for the super quick resolution of this @mckib2 ! I've managed to compile the version off of GitHub, and the fixes are working great for me!
