### ISSUE TITLE
scipy.sparse.csr_matrix.dot(x,x.transpose()) gives a matrix (2x2) instead of a scalar value (inside a matrix 1x1) when x is a numpy array of shape 1x2 

### ISSUE THREAD

**Issue by dbreu** [scipy/scipy#13439]
When using the scipy.sparse.csr_matrix.dot function to perform a scalarproduct between two numpy arrays it results in a matrix instead of a scalar value. This also happens if the numpy arrays where previously reshaped to be of dimension (1,'length of vector'). 
I could furthermore find this problem in the csc_matrix and coo_matrix classes. But I only exclusively tested these two, so the other sparse matrix classes could be affected too.

#### Reproducing code example:

```
import numpy as np
import scipy.sparse as sp

x = np.array([1,0]).reshape(1,2)
print(x.shape,x.transpose().shape)
print(sp.csr_matrix.dot(x,x.transpose()).shape)
print(sp.csr_matrix.dot(x,x.transpose()))
```

#### Output:

```
(1, 2) (2, 1)
(2, 2)
[[1 0]
 [0 0]]
``` 

#### Scipy/Numpy/Python version information:

```
1.6.0 1.19.5 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)
```

**Comment by perimosocordiae** [comment]
You're calling the `dot` *method* of the CSR/CSC matrix class as if it were a free function, which only happens to almost-work by accident.

The dot method for these types is implemented simply:

```
def dot(self, other):
    return self * other
```

because scipy.sparse matrices follow the numpy.matrix convention of treating the multiplication operator as a matrix product. So when you pass two numpy.ndarray objects to this function, you're effectively calling `x * x.T`, which is a broadcasted outer product and thus produces a 2x2 result.

So this isn't a bug, but rather a quirk of the way Python methods work. If you want to do actual sparse matrix products, try:

```
s = sp.csr_matrix(x)
s.dot(s.T)
```
