### ISSUE TITLE
Broadcasting multivariate PDFs fails parameter validation

### ISSUE THREAD

**Issue by multimeric** [scipy/scipy#13450]
The stats functions, such as `pdf()` are supposed to support broadcasting. So, for example, say we want to evaluate the PDF of two different multivariate RVs in one function call (this is a trivial example with no covariance terms):
<img src=
"https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+X+%5Csim+MVN%28%5Cbegin%7Bbmatrix%7D1%261%5Cend%7Bbmatrix%7D%2C%5Cbegin%7Bbmatrix%7D1%260%5C%5C%0A0%261%5Cend%7Bbmatrix%7D%29" 
alt="X \sim MVN(\begin{bmatrix}1&1\end{bmatrix},\begin{bmatrix}1&0\\
0&1\end{bmatrix})">
<img src=
"https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+Y+%5Csim+MVN%28%5Cbegin%7Bbmatrix%7D2%262%5Cend%7Bbmatrix%7D%2C%5Cbegin%7Bbmatrix%7D1%260%5C%5C%0A0%261%5Cend%7Bbmatrix%7D%29" 
alt="Y \sim MVN(\begin{bmatrix}2&2\end{bmatrix},\begin{bmatrix}1&0\\
0&1\end{bmatrix})">

#### Reproducing code example:

```python
import numpy as np
from scipy.stats import multivariate_normal as mvn

# We have some observations from both RVs, which can be combined into a `(2, 2)` matrix
x_sample = [2, 3]
y_sample = [3, 4]

# Define the RVs
x_mean = [1, 1]
x_cov = np.identity(2)

y_mean = [2, 2]
y_cov = np.identity(2)

# Now, we want to evaluate the probability of these observations, so we stack RVs along the first axis
probs = mvn.pdf(
    x = [x_sample, y_sample],
    mean = [x_mean, y_mean],
    cov = [x_cov, y_cov]
)
```
However this raises the exception below: `ValueError: Array 'mean' must be a vector of length 4.`

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/michael/Storage2/miniconda3/lib/python3.8/site-packages/scipy/stats/_multivariate.py", line 523, in pdf
    dim, mean, cov = self._process_parameters(None, mean, cov)
  File "/media/michael/Storage2/miniconda3/lib/python3.8/site-packages/scipy/stats/_multivariate.py", line 410, in _process_parameters
    raise ValueError("Array 'mean' must be a vector of length %d." %
ValueError: Array 'mean' must be a vector of length 4.
```

#### Discussion

In my opinion, the offending line is here, although this behaviour is replicated in many places for different distributions: https://github.com/scipy/scipy/blob/8538cc9040a46bdf5000509d49c35a8b6cfcdc28/scipy/stats/_multivariate.py#L391

Why does it make sense to assume that the dimensionality of the RV here is the *size* of the total mean array? The size, being the total number of elements across all dimensions, can grow arbitrarily as you add more RVs. The actual dimensionality here is obviously 2.

Further, to explain why I think this is a bug, note that the documentation makes it clear that you can and should be able to stack univariate RVs, which produces results equivalent to two separate calls to the PDF function: https://docs.scipy.org/doc/scipy/reference/tutorial/stats.html#broadcasting.

Now, observe how this does work separately for the multivariate case:
```python
x_prob = mvn.pdf(
    x = x_sample,
    mean = x_mean,
    cov = x_cov
)
y_prob = mvn.pdf(
    x = y_sample,
    mean = y_mean,
    cov = y_cov
)
```

But, as noted above, while you can stack univariate RVs, you cannot do the same with multivariate RVs.

#### Scipy/Numpy/Python version information:
```
1.5.4 1.19.4 sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)
```

**Comment by TMiguelT** [comment]
Happy to fix this, I'm just waiting for some confirmation that this is indeed a bug.

**Comment by mdhaber** [comment]
Hi @TMiguelT, thanks for reporting this. I can't provide a definitive answer, but I'll do my best until a more experience stats maintainer can step in.

I don't think these are intended to be vectorized, yet. It looks to me like `dim = mean.size` is not the only thing you'd need to change if you wanted to vectorize these. A few thoughts:

- As you note, univariate distributions support nd broadcasting, but that doesn't tell us much about how the multivariate distributions will work. They do not inherit from `rv_continuous` under the hood. (The multivariate distributions actually inherit very little from their superclass.)
- Also, if I remember correctly, the covariance matrix will need to be factorized for many of these operations, and I don't know that there's a nice vectorized way of writing that (other than an explicit for loop). 
- If they were supposed to be vectorized, everything should probably be stacked along a third axis. As you have it now, when you turn your inputs into arrays, the covariance matrices get stacked along a third axis, but the mean gets stacked along the second. That would get inconvenient if this were to generalize to N-d.
- I haven't dug too deeply into this, but the `_process_parameters` function looks like it intends for 2d covariance. For instance, `Array 'cov' must be at most two-dimensional` appears there.

So my guess is that this is an enhancement request rather than a bug. We can label it as such if you'd like?  Other maintainers, please correct me if I misunderstood the code.

**Comment by TMiguelT** [comment]
Hi @mdhaber. I take your point, it doesn't explicitly actually state that multivariate distributions work with broadcasting.

In the short term I wonder if this can still be considered a bug, just because the documentation could be misunderstood. The page I linked to is a general tutorial for the stats module, which discusses univariate and multivariate distributions alike. The comment on broadcasting seems to apply to the entire module when it evidently does not.

In the long term, yes I suppose this is a feature request. I can open that as a new issue if that's clearer to you. The way I might envisage this working is actually stacked along the *first* axis, although I'm no expert here. The reason I say this axis is because other `numpy` functions that accept a stack of matricies assume they are stacked in this way. For example, [`numpy.linalg.inv`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html), which can take an `n x d x d` stack of matricies. Of course broadcasting won't automatically work with this dimensionality, because the mean vector will be `n x d` which doesn't align properly, but we could `numpy.expand` another dimension into this vector, making it `n x d x 1` (same for the `x` vector, etc), which will then broadcast correctly.

**Comment by mdhaber** [comment]
> The way I might envisage this working is actually stacked along the first axis, although I'm no expert here

Sorry, instead of "third axis", let me say "axis 0". That's what I meant, and I think that's what you meant by "first axis"?

> For example, numpy.linalg.inv, which can take an n x d x d stack of matrices.

I see. I didn't know about that. I don't think the `scipy.linalg` functions do that right now, though. It looks like most of the uses of `scipy.linalg` in the multivariate distributions could conceivably be replaced by the NumPy versions (although perhaps there are other reasons not to), or perhaps the SciPy versions could be vectorized - but it's looking like some deep changes.

> but we could numpy.expand another dimension into this vector, making it n x d x 1 (same for the x vector, etc), which will then broadcast correctly.

Of course, I'm just not sure that's the right way to go. I guess I'm not really sure what is, though. 

> In the short term I wonder if this can still be considered a bug, just because the documentation could be misunderstood.

Sure, I think we'd welcome a documentation clarification PR. 

> I can open that as a new issue if that's clearer to you.

Nope, no need. This issue can serve as the enhancement request.

**Comment by TMiguelT** [comment]
Yes, sorry. I meant the first axis that you index.

I might make an attempt at clarifying the documentation. But beyond that I'll wait for some approval before I think about implementing broadcasting here.

**Comment by Erotemic** [comment]
I think I have a related issue. I was going to post a new issue, but it seems tied to this, so let me know if you think this would be better as a separate issue.

When I make a simple multivariate normal, I get an unexpected shape if my input only has one row:

```python
            import scipy.stats

            # When I create a simple 2D normal distribution
            rv = scipy.stats.multivariate_normal(mean=[0, 0], cov=[1, 1])

            # When I send in a single 2D point, I correctly get a scalar result.
            x = [0, 0]
            result = rv.pdf(x)
            assert result.shape == tuple()

            # When I send in multiple 2D points, I correctly get an array of results
            x = [
                [0, 0],
                [1, 1]
            ]
            result = rv.pdf(x)
            assert result.shape == (2,)

            # However, when I send in a single 2D point encapsulated in an
            # array, I incorrectly get a scalar result.
            x = [
                [0, 0],
            ]
            result = rv.pdf(x)
            assert result.shape == (1,), 'failure'
```

This is a problem because if I send in a list of points, I expect to get a list of results back. I found a bugged edge case in my code because when my list of inputs was length 1, instead of getting back a list (and subsequently being able to use the same logic for any other number of points) I got back a scalar, which I now have to handle as a special case.

**Comment by mdhaber** [comment]
Yes @Erotemic, looks like gh-7689 is the problem with that code. I see you've posted there; thanks!

**Comment by mdhaber** [comment]
This is still a problem, but it is being tracked in gh-16278.
