### ISSUE TITLE
Too many warnings and results objects in public API for scipy.stats

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#13462]
When working on gh-13461, I noticed these new objects listed on the overview page for `scipy.stats`:

- `BinomTestResult`
- `F_onewayConstantInputWarning`
- `F_onewayBadInputSizesWarning`
- `PearsonRConstantInputWarning`
- `PearsonRNearConstantInputWarning`
- `SpearmanRConstantInputWarning`

That doesn't look good, the warnings are too detailed and this is way too much to add to the public API. I think what should happen here is:

- Remove `BinomTest` from the public API, and don't add any other `*Result` classes. Just don't add them to `__all__` dicts.
- Create one or a few useful warnings, e.g. just `StatisticalTestWarning` as the top-level (or only public) warning, and create warnings like `ConstantInputWarning` that inherit from it.
- Treat these things like other additions to the public API - I cannot remember any discussion about adding them.

Cc @WarrenWeckesser and @mdhaber.

**Comment by mdhaber** [comment]
I've re-opened gh-13118 about what statistical tests should return, and I'll send a note to the mailing list this time. We may need something for statistical tests results in the public API, though, because it is beginning to look natural for the returned objects to have methods rather than just contain data.

I don't know anything about the rest, but I agree that the list could probably be trimmed to just a superclass warning.

**Comment by rlucas7** [comment]
RE: too many warnings

The spearman warning `SpearmanRConstantInputWarning` I put in PR:
https://github.com/scipy/scipy/pull/11225  

The reasoning for separate warnings we're discussed in Warren's original PR:
https://github.com/scipy/scipy/pull/9562#issuecomment-481457819 
and further down in that pr with comments from several of us. 

Actually in that PR @chrisb83 had suggested a more generic constant input warning :)  

Spearman calculates correlations on ranks so doesn't have the floating point issues that pearson can sometimes encounter. That being said, because of 0 vs non-zero variances impacting lots of statistical calculations-and many of them being on fp numbers-I'd be in favor of two generic warnings: 

(1) Constant input warning 
(2) Near constant intput

The anova calculations will be subject to having these same sorts of issues too but those are fairly recent additions so have less exposure I'd guess.

Also, the Warnings for pearson have been out for 2 or 3 release cycles now, is it safe to consider these defects? (e.g. no deprecation cycle)

**Comment by rgommers** [comment]
Thanks for digging up that history @rlucas7. 

> That being said, because of 0 vs non-zero variances impacting lots of statistical calculations-and many of them being on fp numbers-I'd be in favor of two generic warnings:
> 
> (1) Constant input warning
> (2) Near constant intput

That makes sense. We can even inherit from those to make the emitted warnings more specific if desired (`SpearmanRConstantInputWarning` is fine), but it does not really make sense to me to put that many warnings in the public API.

**Comment by rgommers** [comment]
> I've re-opened [gh-13118](https://github.com/scipy/scipy/issues/13118) about what statistical tests should return, and I'll send a note to the mailing list this time. We may need something for statistical tests results in the public API, though, because it is beginning to look natural for the returned objects to have methods rather than just contain data.

Okay let's move this part of the discussion to that issue then, and keep this one for the warnings.
