### ISSUE TITLE
The correct root for test APS13 is 0

### ISSUE THREAD

**Issue by jamadagni** [scipy/scipy#13554]
https://github.com/scipy/scipy/blob/4fe52aed1ea375c2aa7a2a6b634787c9abdf32e3/scipy/optimize/_tstutils.py#L490

Methinks the correct root for this function is 0 and not some small positive number because it is defined that way:

https://github.com/scipy/scipy/blob/4fe52aed1ea375c2aa7a2a6b634787c9abdf32e3/scipy/optimize/_tstutils.py#L323-L324

**Comment by mdhaber** [comment]
Any number smaller than about `3.8e-02` is a root of the function as it is expressed in the code.
```python3
aps13_f(1.54720911915117165e-02)  # 0
```
So `1.54720911915117165e-02` is a valid root.

That said, there is no harm in changing this. There is nothing special about the root `1.54720911915117165e-02`. It is not the largest number that results in a (code) function value of zero, nor is it the root of the underlying mathematical function. And tests still pass because if the computed root is not close to the reference root, the test checks whether the function value is zero at the computed root. Might as well change it to the root of the underlying mathematical function.
