### ISSUE TITLE
BUG: Newton-CG does not handle HessianUpdateStrategy

### ISSUE THREAD

**Issue by jonas-eschle** [scipy/scipy#13557]
Two things:
- the jacobian, if a string is given, is not accepted. This happens in `_minimize.py`, line 557:
```
elif (jac in FD_METHODS and
      meth in ['trust-constr', 'bfgs', 'cg', 'l-bfgs-b', 'tnc']):
```
should be (` 'newton-cg'` added)
```
elif (jac in FD_METHODS and
      meth in ['trust-constr', 'bfgs', 'cg', 'newton-cg', 'l-bfgs-b', 'tnc']):
```
Apart from that, it fails as well with some odd reason as BFGS is now a callable.

#### Reproducing code example:
```
from scipy.optimize import minimize, BFGS

hess = BFGS
minimize(lambda x: x[0] * x[1], [1, 2], method='Newton-CG', jac='cs', hess=BFGS)

```

**Comment by tupui** [comment]
Linked to #13524 .

Thanks for noticing these. You seems to have ideas about how to solve some of the problems. Would you be willing to do a PR?

**Comment by andyfaff** [comment]
The documentation for the jac keyword says:

> Methods ‘Newton-CG’, ‘trust-ncg’, ‘dogleg’, ‘trust-exact’, and ‘trust-krylov’ require that either a callable be supplied, or that fun return the objective and gradient

In other words '2-point', '3-point', 'cs' are not accepted for the jac keyword, as these cause the gradient to be estimated with finite-differences. This is because the Newton-CG method doesn't want to estimate both the grad and hess with finite-differences.

BFGS is a class that implements a HessianUpdateStrategy. It's not not callable, you need to instantiate it, `BFGS()`.

Note that the docstring for hess has historically been cloudy for the hess keyword and this is being made clearer in #15019. This PR is also adding the possibility for using HessianUpdateStrategy for the hessian for Newton-CG.

After that PR is merged this will be possible:

```
from scipy.optimize import minimize, rosen, rosen_der, BFGS
minimize(rosen, [1, 2], method='Newton-CG', jac=rosen_der, hess=BFGS())
```

**Comment by jonas-eschle** [comment]
> BFGS is a class that implements a HessianUpdateStrategy. It's not not callable, you need to instantiate it, BFGS().

Thanks, that was a typo in the issue (the effect is the same).

> After that PR is merged this will be possible:

Great, many thanks for that (and sorry for not responding earlier, it slipped through my radar)

More generally, would it be possible to keep the issue open _until_ it is resolved? Just to keep the bookkeeping correct (also, it's better to let the OP close the issue because they [can re-open in case it's not resolved](https://github.com/isaacs/github/issues/583))

**Comment by tupui** [comment]
> More generally, would it be possible to keep the issue open _until_ it is resolved? Just to keep the bookkeeping correct (also, it's better to let the OP close the issue because they [can re-open in case it's not resolved](https://github.com/isaacs/github/issues/583))

On closing issues, we don't have strong rules but this is left to maintainers judgement. Issues linked to PRs are in any case closed automatically.

While some project don't like to comment on closed issues and refuse to reply, it's not the case here. You are welcomed to add additional information and we can re-open later if needed 😃

**Comment by andyfaff** [comment]
The original issue was using finite difference keywords with newton-cg, that was never allowed. This was the reason for closing

**Comment by jonas-eschle** [comment]
I see, thanks a lot!
