### ISSUE TITLE
Why stats one sample t test result is not correct?

### ISSUE THREAD

**Issue by zengqing1** [scipy/scipy#13708]
When I used the scipy.stats.ttest_1samp() for one sample t test , I got some error results.  The ttest_1samp() function got t=1.22. But when I used the t test one sample formula directly, I got t=1.29.  And I can not find why it was .

#### Reproducing code example:
```
import numpy as np
import scipy.stats as sts

x = 3.59,2.66,3.89,2.23,1.61,2.94,1.96,3.68,1.54,2.59

sts.ttest_1samp(x, popmean=3)
#Ttest_1sampResult(statistic=-1.2285981915148954, pvalue=0.2503790104923504)

#use the t test formula directly to compute
# t= (x-mu)/( std/ sqrt(n) )
(np.mean(x)-3)/np.std(x)*np.sqrt(10)
#-1.2950562047836085
```

#### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
#1.6.1 1.20.1 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
```

**Comment by Vedant1parekh** [comment]
May i solve this issue?

**Comment by matthew-brett** [comment]
@Vedant1parekh - this isn't really an issue - it's just that @zengqing1 was not (I think) aware that `np.std` uses n as the denominator by default ("population" standard deviation) instead of n - 1 ("sample" standard deviation).

To get the behavior you @zengqing1 were expecting:

```
[ins] In [5]: (np.mean(x)-3)/np.std(x, ddof=1)*np.sqrt(10)                                                             
Out[5]: -1.2285981915148954
```

Check the documentation for `np.std`.
