### ISSUE TITLE
scipy.stats.norm does not support Pandas 1.2 FloatDtype

### ISSUE THREAD

**Issue by Achilles2308** [scipy/scipy#13729]
My issue is about that scipy.stats.norm function does not support the newly introduced pd.Float64Dtype() from pandas 1.2. Therefore it cannot handle empty values (pd.NA) and the series needs to be cast right now as a float dtype to properly work which is not ideal.

#### Reproducing code example:

```
import pandas as pd
from scipy.stats import norm

series = pd.Series([2.0, -2.5, pd.NA], dtype=pd.Float64Dtype())
norm.pdf(series)
```

#### Error message:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\XXX\AppData\Local\pypoetry\Cache\virtualenvs\XXX-w19Rd76b-py3.9\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 1837, in pdf
    cond1 = self._support_mask(x, *args) & (scale > 0)
  File "C:\Users\XXX\AppData\Local\pypoetry\Cache\virtualenvs\XXX-w19Rd76b-py3.9\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 964, in _support_mask
    return (a <= x) & (x <= b)
  File "pandas\_libs\missing.pyx", line 360, in pandas._libs.missing.NAType.__bool__
TypeError: boolean value of NA is ambiguous
```

#### Scipy/Numpy/Python version information:
 1.6.1 1.20.1 sys.version_info(major=3, minor=9, micro=1, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
Why not converting to np.Nan for float values?

**Comment by tupui** [comment]
IMO this should be handled on Pandas side as the conversion to a NumPy array is not well done.

```python
series.to_numpy()
# array([2.0, -2.5, <NA>], dtype=object)
norm.pdf()
#TypeError: boolean value of NA is ambiguous
```

**Comment by andyfaff** [comment]
@Achilles2308, the workflow for what's happening here:

1. `series` is [converted to an array](https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L1866). This conversion results in a numpy array with `dtype=object`.
2. This array is then checked whether it's in the [distribution support](https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L984).
3. This fails because:
```
>>> series > -np.inf
0    True
1    True
2    <NA>
dtype: boolean
>>> np.asarray(series) > -np.inf
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-718493e0aea5> in <module>
----> 1 np.asarray(series) > -np.inf

pandas/_libs/missing.pyx in pandas._libs.missing.NAType.__bool__()

TypeError: boolean value of NA is ambiguous
```
We have to do the `np.asarray` call in order to know that we're handling numpy-like arrays. The less/greater than check fails for datatype `pandas._libs.missing.NAType`.

A proper conversion needs to happen before `series` is handed to `norm.pdf`, possibly by converting to NaN for missing values. However, that might be up to you, because it probably doesn't make sense to do that conversion in the pandas `series.to_numpy` call either.

**Comment by jaspersival** [comment]
Thanks for looking into it. I have reported this issue now also on the pandas Github [](https://github.com/pandas-dev/pandas/issues/40630)
