### ISSUE TITLE
Error in Contributing guide - Hacking.rst.txt

### ISSUE THREAD

**Issue by Suraj1199** [scipy/scipy#13742]
The Links in Contibuting guide file, Hacking.rst.txt, are not redirecting to their corresponding resource site. The problem occurs with links having prefix `:ref:` and in one case `:doc:`.

**Comment by tupui** [comment]
Hi, you are talking about this https://docs.scipy.org/doc/scipy/reference/hacking.html correct?

Which link is not working on your side? And which browser, version, os are you using? Because on my side I have all links working I think.

Also, you could look at here if the error you have is still there https://28085-1460385-gh.circle-artifacts.com/0/html-scipyorg/dev/index.html

If not we can close the issue.

**Comment by WarrenWeckesser** [comment]
I suspect @Suraj1199 is looking at the file on github: https://github.com/scipy/scipy/blob/master/HACKING.rst.txt

@Suraj1199, that file is the "source code" for the documentation.  To read the docs, use the [rendered documentation](https://docs.scipy.org/doc/scipy/reference/hacking.html) that @tupui pointed to.

**Comment by Suraj1199** [comment]
@WarrenWeckesser you are right , I was talking about the file [HACKING.rst.txt](https://github.com/scipy/scipy/blob/master/HACKING.rst.txt). @tupui Thanks for referring rendered documentation.
