### ISSUE TITLE
Scipy.optimize x0 out of bounds when it is within bounds.

### ISSUE THREAD

**Issue by tprodanov** [scipy/scipy#13740]
This error is the same as in #11403 and #13556, but here I have a concrete example when the error occurs.

The error is as stated, `scipy.optimize.minimize` raises an error that says that `x0` is out of bounds, when it is within bounds.
Additionally, I checked that `minimize` throws the error after multiple iterations, so it is not about `x0` at all.

#### Reproducing code example:
First, you need to download `emissions.npy` from [here](https://dl.dropboxusercontent.com/s/9jab8cjnhgrihkl/emissions.npy).

```python
#!/usr/bin/env python3

import scipy
import scipy.optimize
import numpy as np
import sys

print('Python version:', sys.version_info)
print('Scipy version: ', scipy.__version__)
print('Numpy version: ', np.__version__)

with open('emissions.npy', 'rb') as f:
    emission_matrix = np.load(f)

def minus_lik(fractions):
    fractions -= scipy.special.logsumexp(fractions)
    return -np.sum(scipy.special.logsumexp(fractions[:, np.newaxis] + emission_matrix, axis=0))

n_rows = emission_matrix.shape[0]
x0 = np.full(n_rows, -np.log(n_rows))
bounds = np.zeros((n_rows, 2))
bounds[:, 0] = np.log(1e-5)
assert np.all(bounds[:, 0] < x0) and np.all(x0 < bounds[:, 1])

sol = scipy.optimize.minimize(minus_lik, x0=x0, bounds=bounds, method='L-BFGS-B')
```

#### Error message:
```
Traceback (most recent call last):
  File "./test.py", line 25, in <module>
    sol = scipy.optimize.minimize(minus_lik, x0=x0, bounds=bounds, method='L-BFGS-B')
  File "/home/timofey/.miniconda3/envs/py37/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 620, in minimize
    callback=callback, **options)
  File "/home/timofey/.miniconda3/envs/py37/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 360, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/timofey/.miniconda3/envs/py37/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 261, in fun_and_grad
    self._update_grad()
  File "/home/timofey/.miniconda3/envs/py37/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 231, in _update_grad
    self._update_grad_impl()
  File "/home/timofey/.miniconda3/envs/py37/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 152, in update_grad
    **finite_diff_options)
  File "/home/timofey/.miniconda3/envs/py37/lib/python3.7/site-packages/scipy/optimize/_numdiff.py", line 451, in approx_derivative
    raise ValueError("`x0` violates bound constraints.")
ValueError: `x0` violates bound constraints.
```

#### Scipy/Numpy/Python version information:
```
Python version: sys.version_info(major=3, minor=7, micro=10, releaselevel='final', serial=0)
Scipy version:  1.6.1
Numpy version:  1.19.2
```

**Comment by andyfaff** [comment]
This issue is similar in concept to #11403. This is where the external minimiser code, in this case the [L-BFGS-B Fortran code](https://github.com/scipy/scipy/blob/master/scipy/optimize/lbfgsb_src/lbfgsb.f) is asking for a gradient to be evaluated for a parameter position (`x`) that lies outside the bounds.

In #11403 the problem was being experienced with SLSQP. There the `x` vector was only very slightly outside the bounds, by a couple of ULP, so it made sense to clip the values to the bounds.
For this system the `x` vector is outside the bounds by a reasonably long way (-11.66 vs -11.51), and I'm not sure that clipping would be a reasonable thing to do. Clipping would result in a gradient being evaluated at a place quite different where the minimizer thinks the `x` vector is. I do not know why the Fortran code does not obey the bounds on the system.

@tprodanov I suggest in the meantime that you use a non-gradient based minimiser, such as `differential_evolution`, which will obey the bounds. The example you give here is pathological because of all the logarithmic terms that are being used. You'll note that most of the parameter values want to butt up against the lower bound:
```
>>> scipy.optimize.differential_evolution(minus_lik, bounds)
     fun: 68.41405438082069
     jac: array([ 4.03588241e-04,  4.03588241e-04,  3.89377387e-04,  2.28794742e-04,
        4.54747313e-05,  8.52651288e-06, -4.02451406e-03,  6.39488409e-05,
        1.90425437e-04,  3.09796607e-04,  3.75166533e-04,  3.96482814e-04,
        4.02167155e-04,  4.03588241e-04,  4.03588241e-04])
 message: 'Optimization terminated successfully.'
    nfev: 4626
     nit: 17
 success: True
       x: array([-11.51292546, -11.51292546, -11.51292546, -11.51292546,
       -11.51292546,  -1.79765146,   0.        , -11.51292546,
       -11.51292546, -11.51292546, -11.51292546, -11.51292546,
       -11.51292546, -11.51292546, -11.51292546])
```

**Comment by andyfaff** [comment]
@tprodanov, the issue with your example is that you're modifying the input array. I don't typically do that in my work, and it's not a thing that I've seen many other people do/report before.

This should work:
```
def minus_lik(fractions):
    inp = np.copy(fractions)
    inp -= scipy.special.logsumexp(fractions)
    return -np.sum(scipy.special.logsumexp(inp[:, np.newaxis] + emission_matrix, axis=0))
```
We might think of sending a copy of the array to the user function to prevent this.

**Comment by tprodanov** [comment]
Ah, yes, for some reason I did not think about that. Thank you!
