### ISSUE TITLE
The scipy online documentation returns 404 constantly

### ISSUE THREAD

**Issue by JoshuaGhost** [scipy/scipy#13779]
I can go into [the main page of the scipy project](https://www.scipy.org/#). However when i try to check the documentation for the SciPy package through this [link](https://docs.scipy.org/doc/scipy/reference/#), it returns *404 page not found* constantly.

**Comment by kozmaz87** [comment]
Yup was just about to drop the same in.

**Comment by jakevdp** [comment]
This appears to also be affecting documentation builds that use intersphinx to connect to scipy:
```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.scipy.org/doc/scipy/reference/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://docs.scipy.org/doc/scipy/reference/objects.inv
```

**Comment by ilayn** [comment]
Ooops looks like docs are down... I'll check

**Comment by rainwoodman** [comment]
I am also affected.

**Comment by rgommers** [comment]
Yep aware of it, the disk was out of space and our sysadmin is reshuffling things. Fingers crossed it's back soon.

**Comment by warrickball** [comment]
It was down for me too but is back up as of a few minutes ago.

**Comment by rgommers** [comment]
Phew, fixed.

**Comment by rgommers** [comment]
For the record, the issue was when switching over to a larger mount volume, the two directories that serve `scipy.org` and `docs.scipy.org` (which are separate sites) ended up under `/srv/srv/` rather than `/srv/`. It's a mystery to me why `scipy.org` still worked. Anyway, stuff moved back to the correct locations now.

**Comment by rainwoodman** [comment]
Thanks for the fix!

**Comment by JoshuaGhost** [comment]
Thanks a lot for the fix. Now it works totally.

**Comment by tomar-abhijeet** [comment]
[https://www.google.com/search?q=scipy.interpolate.poly.from+spline&rlz=1C1CHBF_enIN803IN803&oq=sc&aqs=chrome.2.69i60j69i59l3j69i57j69i60l3.1807j0j7&sourceid=chrome&ie=UTF-8](Search Results) not opening, returns error 404. Is it down again?

**Comment by msmdev** [comment]
I have the same issue with intersphinx (can't reach 'https://docs.scipy.org/doc/numpy/objects.inv):
``
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.scipy.org/doc/numpy/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">')
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.scipy.org/doc/scipy/reference/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: ')
``

**Comment by melissawm** [comment]
@msmdev if you are looking to use the NumPy intersphinx URL this has moved to https://numpy.org/doc/stable/objects.inv

For SciPy see #15545

**Comment by msmdev** [comment]
@melissawm: this and #15545 solved my problem - thank you very much!
