### ISSUE TITLE
BUG: chi2_contingency with Yates correction

### ISSUE THREAD

**Issue by c-foschi** [scipy/scipy#13875]
It seems Yates correction alters the result of the test badly. This is particularly urgent as `correction` is true by default.

```
>>> import numpy as np
>>> from scipy import stats
>>> X= np.array([[1573, 3], [4, 0]])
>>> stats.chi2_contingency(X, correction= False)
(0.007628698067718375, 0.9303993377521388, 1, array([[1.57300759e+03, 2.99240506e+00],
       [3.99240506e+00, 7.59493671e-03]]))
>>> stats.chi2_contingency(X)
(32.0661727862559, 1.4900942749544931e-08, 1, array([[1.57300759e+03, 2.99240506e+00],
       [3.99240506e+00, 7.59493671e-03]]))
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.6.2 1.20.1 sys.version_info(major=3, minor=9, micro=1, releaselevel='final', serial=0)
```
Note that Yates correction should *increase* the p-value, not turn a value of almost 1 into another that's nearly 0.
I tried this with scipy 1.6.2 in my pc, but I originally spotted the issue in a Linux server from my client.

**Comment by scidam** [comment]
I just tested your example in R and got the same results. chisq.test returns the same p-value in both cases. It is well known that chi-square don't work well when contingency table includes values less 5, but you can use `fisher_exact` test (at least, if you plan to consider only 2x2 cases). Why didn't you use `fisher_exact` test?

**Comment by c-foschi** [comment]
Don't know if we have the same version of R, but this is what it gives to me (warnings omitted for brevity):
```
> chisq.test(matrix(c(1573, 3, 4, 0), ncol= 2), correct= F)

	Pearson's Chi-squared test

data:  matrix(c(1573, 4, 3, 0), ncol = 2)
X-squared = 0.0076287, df = 1, p-value = 0.9304
> chisq.test(matrix(c(1573, 4, 3, 0), ncol= 2))

	Pearson's Chi-squared test with Yates' continuity correction

data:  matrix(c(1573, 3, 4, 0), ncol = 2)
X-squared = 1.4515e-24, df = 1, p-value = 1
```

You can see that Yates' correction doesn't increase the p-value.

**Comment by scidam** [comment]
Oh, sorry, I looked at dof instead of p-value; you are totally right, we shouldn't get small p-values here. 
This issue comes from different implementations of Yates' correction in `scipy.stats`:
https://github.com/scipy/scipy/blob/374e5bfec63e530c34514a08d9311352138182f3/scipy/stats/contingency.py#L290
and [R](https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/library/stats/R/chisq.test.R#L94):

`YATES <- min(0.5, abs(x-E))`

and, finally, chi2-statistic is computed as follows:
`STATISTIC <- sum((abs(x - E) - YATES)^2 / E)`

So, if we change 
`observed = observed + 0.5 * np.sign(expected - observed) `
to 
` observed = observed + np.minimum(0.5, np.abs(observed - expected)) * np.sign(expected - observed) `
we get desired result.

**Comment by WarrenWeckesser** [comment]
(@scidam's comment arrived just as I was finishing this comment...)

I see the problem.  The SciPy correction calculation is

    observed = observed + 0.5 * np.sign(expected - observed)

So wherever `expected > observed`, `observed` is increased by 0.5, and wherever `expected < observed`, `observed` is decreased by 0.5.  When the absolute difference between `expected` and `observed` is greater than 0.5, this adjustment moves the observed values towards the expected values (and therefore increases the p-value).

The problem occurs when the absolute difference between `expected` and `observed` is less 0.5 but is not 0.  Then the adjustment by 0.5 is too big--the adjusted observed value will be further from the expected value than the original observed value.

The adjustment used by the R function `chisq.test` is the minimum of 0.5 and `abs(expected - observed)`.  In effect, the adjustment made to an observed value that is within 0.5 of the expected value is to set the observed value equal to the expected value.

**Comment by rgommers** [comment]
> I see the problem. The SciPy correction calculation is

@WarrenWeckesser if you haven't looked at gh-13906 and gh-13916 yet, please don't - that contains a fix based on R (GPL) code. That's why we had to close those PRs. @scidam did a great job fixing the bug and adding a unit test, but we cannot use it. And @tupui and I reviewed that first PR, so we cannot write the fix anymore either.

You have already understood the problem, if you could submit your fix that would be really helpful.

**Comment by tupui** [comment]
A side note on Yates' correction, I am reading here https://onlinelibrary.wiley.com/doi/pdf/10.1002/sim.3531 that it should not be used anymore:

> Anyway, it should be noted that Yates’ correction (11) for Pearson’s chi-squared test assumes that all the marginal sums n+=(n1+,n2+,n+1,n+2) are fixed, which makes it a valid approximation to an exact conditional test. This correction reduces the numerical value of the test statistic, and hence reduces the power and significance level of the test, making it overly conservative [6]. We agree with authors who state that Yates’ correction should no longer be used [4, 6, 25].

We (I will do a PR) should at least add a note in the description of the parameter.

**Comment by tylerjereddy** [comment]
It sounds like there might be some action needed here--I'll leave the milestone for now, it may need to get checked during the rc phase? Otherwise, just bump the milestone for me

**Comment by mdhaber** [comment]
>  It could be a special block in the note section for instance. What do you think?

Sounds reasonable but deserves a separate issue. 

Whether or not to use the Yates correction is also a separate issue. 

@tylerjereddy I think _this_ issue is just waiting for a review of gh-13925.

**Comment by tylerjereddy** [comment]
Should be fixed by gh-13925, which I've just merged with a backport label .
