### ISSUE TITLE
fftfreq uses numpy module as example

### ISSUE THREAD

**Issue by gajrajgchouhan** [scipy/scipy#13887]
For documentation of [scipy.fft.fftfreq](https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.fftfreq.html) the example uses numpy's fft module. Shouldn't it use the scipy one ? 

```python
signal = np.array([-2, 8, 6, 4, 1, 0, 3, 5], dtype=float)
fourier = np.fft.fft(signal)
n = signal.size
timestep = 0.1
freq = np.fft.fftfreq(n, d=timestep)
freq
```

**Comment by WarrenWeckesser** [comment]
Your question is reasonable, but it turns out that the names `fftfreq`, `rfftfreq`, `fftshift`, and `ifftshift` in the `scipy.fft` namespace  are just aliases of the corresponding functions in `numpy.fft`.

If we want to fix this, we could create actual implementations in `scipy.fft` and give the functions SciPy-based docstrings.  The actual implementation for each function could be a one-liner that passes all its arguments to the NumPy version.

An alternative is to deprecate the SciPy versions of  `fftfreq`, `rfftfreq`, `fftshift`, and `ifftshift`, and update the SciPy documentation to refer to NumPy for these functions.

**Comment by tupui** [comment]
If we don't plan to add extra features compared to NumPy's implementation, +1 for the deprecation.

**Comment by peterbell10** [comment]
-1 for deprecation. We want `scipy.fft` to be more or less a drop-in replacement for `np.fft`. Removing functions is working against that goal.

Ideally we could have our own docstring, but I don't think there's any way to do so without adding runtime overhead which I don't think is worth it. As a middle ground, I could add such a wrapper when `_SCIPY_BUILDING_DOC` is defined so the rendered sphinx docs say `scipy.fft` but the runtime docs would still say `np.fft`

**Comment by lucascolley** [comment]
This **superset** claim from the [NumPy docs](https://numpy.org/doc/stable/reference/routines.fft.html) is something to keep in mind if the functions were deprecated.

> The SciPy module [scipy.fft](https://docs.scipy.org/doc/scipy/reference/fft.html#module-scipy.fft) is a more comprehensive superset of numpy.fft, which includes only a basic set of routines.

**Comment by rkern** [comment]
There was a complicated relationship between `numpy` and `scipy` around `numpy`'s early (pre-)releases. It was originally called `scipy_core`, and it was envisaged that one would treat what is now `numpy` as a kind of easily-installed, minimal subset of the full `scipy`. The vision was that if you were depending some feature in the full `scipy` anyways, you would just import and work with `scipy` and not touch `scipy_core/numpy`. I think that's where this statement originates.

The relationship between `numpy` and `scipy` has shaken out differently in the intervening decade, and we don't have to be beholden to that statement, given proper amounts of deprecation (possibly more than required by our global policy given the long history). We've already deprecated some of the other remnants of that superset notion (like `scipy.array` and friends).

I'm not particularly arguing in favor of taking that path, just providing some of the historical context to that statement. It's possible that, even detached from that original, broader motivation, we still want `scipy.fft` to be a superset of `numpy.fft`, but I'd poll the current devs rather than relying on that bit in the docs.

**Comment by tupui** [comment]
Thank you @rkern for shedding some lights and perspective 🙇 

@lucascolley do you want to poll the mailing list on the topic? That could be an interesting side project for you? We can discuss that further 😃

**Comment by charris** [comment]
The main difference between numpy and scipy fft used to be that scipy used the Fortran version of fftpack and supported 32 bit floats whereas numpy used a partial C translation. With the new fft code, numpy uses C, scipy C++, Along the way, the two implementations also  diverged in the way real to complex transforms were stored, scipy had the original algorithmic form where the (real) Nyquist coefficient was stored in the complex component of the (real) zero frequency coefficient, whereas numpy appended it to the result array consistent with the other frequencies.  I believe that discrepancy is fixed. I'm not sure where the other differences stand or what we want to do about them. There are (were?) also similar differences in the linear algebra module.

The array_api work will hopefully bring some unity.
