### ISSUE TITLE
Inverse of Log CDF of Normal Distribution

### ISSUE THREAD

**Issue by steppi** [scipy/scipy#13923]
**Is your feature request related to a problem? Please describe.**
We were interested in calculating z-scores associated to log p-values in the situation where log(p) can be very small.
The naive solution of applying `scipy.special.ndtri(numpy.exp(log_p))` fails when log_p < ~-745 due to underflow.

**Describe the solution you'd like**
In the underlying C code for `scipy.special.ndtri` found [here](https://github.com/scipy/scipy/blob/master/scipy/special/cephes/ndtri.c
),  when p is very small the approximation used for  `ndtri(p)` is an expression in `sqrt(-2*log(p))`. This formula could then
be applied directly to calculate the inverse of the Log CDF of the normal distribution for very small log(p). A function could be written which exponentiates `log_p` and then uses the existing `ndtri` implementation on the exponentiated value, except for when `log_p` is very small, in which case the rational approximation in `sqrt(-2*log_p)` can be applied directly. Preferably this could be done in C or Cython for performance reasons.

**Describe alternatives you've considered**

We've already implemented this approach in Python and applied it in our research. A code snippet can be found below. Would there be interest in adding such a solution to scipy through a C extension? If so, I'd be happy to submit a PR, though it may be several weeks before I have the free time to do so. In the mean time, if anyone else has an interest in adding this that would be great too.

```python
import numpy as np
from scipy.special import ndtri
from numpy.polynomial import Polynomial
from scipy._lib._util import _lazywhere


_P2 = Polynomial([3.23774891776946035970,
                  6.91522889068984211695,
                  3.93881025292474443415,
                  1.33303460815807542389E0,
                  2.01485389549179081538e-1,
                  1.23716634817820021358e-2,
                  3.01581553508235416007e-4,
                  2.65806974686737550832e-6,
                  6.23974539184983293730e-9])

_Q2 = Polynomial([1.00000000000000000000,
                  6.02427039364742014255,
                  3.67983563856160859403,
                  1.37702099489081330271,
                  2.16236993594496635890e-1,
                  1.34204006088543189037e-2,
                  3.28014464682127739104e-4,
                  2.89247864745380683936e-6,
                  6.79019408009981274425e-9])


def log_ndtri_small_p(log_p):
    """Approximation to inverse log CDF normal for log_p <= -32"""
    x = np.sqrt(-2.0 * log_p)
    x0 = x - np.log(x) / x
    z = 1 / x
    x1 = z * _P2(z)/_Q2(z)
    return x1 - x0
    
    
def log_ndtri(log_p):
    output =  _lazywhere(log_p > -32, [log_p],
                         lambda x: ndtri(np.exp(x)), f2=log_ndtri_small_p)
    # If input is scalar, convert result to scalar
    if not isinstance(log_p, np.ndarray):
        output = output.item()
    return output`
```

**Additional context (e.g. screenshots)**

**Comment by mdhaber** [comment]
This sounds useful to me. Another thing that has been needed in two contexts (e.g. gh-13218, gh-13732) is to accurately calculate the log of a difference in the normal CDF evaluated at different points, e.g.:
```python3
import numpy as np
from scipy.special import ndtr
np.log(ndtr(-37.5) - ndtr(-37.6))  # -707.6926042717773
np.log(ndtr(-37.7) - ndtr(-37.8))  # -inf
```
Any insight there?

**Comment by steppi** [comment]
This is actually something I've needed to solve before as well. I found a simple solution in this set of [lecture notes]( https://www3.nd.edu/~dchiang/teaching/nlp/2018/notes/chapter2v1.pdf).

If p > q then

`log(p - q) = log(p) + log(1 - exp(log(p) - log(q))`

so that we can express `log(p - q)` in terms of `log(p)` and `log(q)`

We can then do something like

```python
import numpy as np
from scipy.special import log_ndtr


def log_diff(log_p, log_q):
    return log_p + np.log(1 - np.exp(log_q - log_p))
```

And then the above could be calculated as

```python
log_diff(log_ndtr(-37.5), log_ndtr(-37.6)  # -707.6926042717773
log_diff(log_ndtr(-37.7), log_ndtr(-37.8)  # -715.2174432032357
```

**Comment by mdhaber** [comment]
That's is really helpful! Thanks! 
@DominicChm could you try this out?

**Comment by steppi** [comment]
Happy to help :)

**Comment by steppi** [comment]
@mdhaber I put together a Cython implementation of `log_ndtri`. It didn't take as long I'd anticipated. The process for adding and registering new special functions is very convenient. I followed #11313 to see how it's done. It remains to add tests, benchmarking, and proper documentation. I saw in these [guidelines](https://docs.scipy.org/doc/scipy/reference/hacking.html#hacking) that all new features should be discussed in the scipy-dev mailing list. Should I make a thread there before doing any further work?

**Comment by mdhaber** [comment]
Yes, all new functions should be brought up on the mailing list. I think it fits squarely in our realm, so i don't imagine people will not want to have it. One thing there might be discussion about is the name. It isn't the same as `log(ndtri(x))`, right? It's `ndtri(log(x))`, no? The `log` prefix would seem to indicate the former, so `ndtri_log` might be more appropriate unless there is precedent otherwise. 

This may have been requested specifically before:
https://github.com/scipy/scipy/issues/11465#issuecomment-583020013

If you agree that's what the user was asking for, it might be a good thing to mention to the mailing list that you had the same need, so it's not so uncommon. R distributions sometimes accept log inputs too.

**Comment by steppi** [comment]
Thanks, that sounds good. I actually dithered for a bit between `log_ndtri` and `ndtri_log`. My final reasoning was `ndtri` is the inverse of `ndtr`, so `log_ndtri` is the inverse of `log_ndtr`.  `ndtri_log` does seem less confusing though. It looks like this is one of the things the user in #11465 was asking for. Ill bring that up in the mailing list. I haven't found a solution to getting good precision when p ~ 1 and log(p) ~ 0 though, which is something that user was also interested in. For the future, should I go directly to the mailing list instead of raising an issue here?

**Comment by mdhaber** [comment]
Yes, you're right. `ndtri_exp`? I don't know anymore : ) maybe suggest a few names and see what resonates with people.

I think it's reasonable to start with an issue and get a little feedback like you did here before posting to the mailing list. For example, I think we identified that the mailing list post should ask for feedback on the name. You can also encourage people to come to the issue on GH for discussion rather than having the discussion itself via email.

Sometimes, if I'm pretty sure the feature is desired, I'll go ahead and get the PR in good shape and even submit that, so that the mailing list post is mostly to attract reviewers.

So the order is what makes sense to you - but if you want to limit the possibility of writing code that won't be accepted, then yes, posting early is a good idea.

**Comment by ev-br** [comment]
FWIW, there is `log_ndtr` is `_faddeeva.cxx`

**Comment by steppi** [comment]
@ev-br Yes, the existence of `log_ndtr` is what made me think `log_ndtri` could potentially be an acceptable name for its inverse, analogous to `ndtr` vs `ndtri`.

**Comment by mdhaber** [comment]
It makes sense, it's just tough to know whether it's `(log_ndtr)i` or `log_(ndtri)`. Might be best to pick a name that is either unambiguous or makes people think enough to look it up.

**Comment by mdhaber** [comment]
From your mailing list post: 

> I've checked just now and it appears that the Julia function applies the same technique I propose 

You may know this already, but it can't hurt to mention - please check licenses before looking at other open-source code. Looks like [StatsFuns](https://github.com/JuliaStats/StatsFuns.jl/blob/master/LICENSE.md) is MIT-licensed, which should be compatible with SciPy's BSD license, but we steer clear of most R code because that tends to be GPL.

**Comment by steppi** [comment]
@mdhaber Thanks, that's good to know. I actually didn't realize it could be an issue even for investigating the naming conventions other software has used for classes of functions. I'll definitely be more cautious in the future.

**Comment by mdhaber** [comment]
Looking at signatures and documentation is fine. But the comment "Julia function applies the same technique I propose", suggested to me that you looked at the source code. Maybe not, but then I'd suggest to be more explicit about how you knew (e.g. documentation says).

**Comment by steppi** [comment]
I understand. My knowledge came from the following comment in their source file. Knowing now that their code is license compatible, I've found that they actually use a different rational approximation from that in the cephes library. 

# norminvcdf & norminvlogcdf implementation
#
#   Rational approximations for the inverse cdf and its logarithm, from:
#
#   Wichura, M.J. (1988) Algorithm AS 241: The Percentage Points of the Normal Distribution
#   Journal of the Royal Statistical Society. Series C (Applied Statistics), Vol. 37, No. 3, pp. 477-484
#
```
