### ISSUE TITLE
signal.cwt introduces a shift in the data

### ISSUE THREAD

**Issue by chris-simpson** [scipy/scipy#13962]
`signal.cwt` performs a convolution with a wavelet function. If the array representing the wavelet function has an even number of elements (which is almost always the case with the current code), an unwanted half-pixel shift is introduced.

#### Reproducing code example:

```
>>> x = np.zeros((50,))
>>> x[25] = 1
>>> x[23:28]
array([0., 0., 1., 0., 0.])

>>> y = signal.cwt(x, signal.ricker, [2])[0]
>>> y[23:28]
array([-0.15794172,  0.20253479,  0.55727104,  0.55727104,  0.20253479])
```

The peak is now between pixels 25 and 26, rather than at 25. The same happens if _any_ width is used.

The solution to this appears to be to ensure that the array representing the wavelet transform has an odd number of pixels, i.e., replace

```
N = np.min([10 * width, len(data)])
```

(which will usually return an even number, unless `len(data)` is odd and `width` is large), with something like

```
N = int(np.min([10 * width, len(data)])) // 2 * 2 - 1
```

#### Scipy/Numpy/Python version information:

scipy v1.5.2
numpy v1.19.2
sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)

**Comment by quantsnus** [comment]
@chris-simpson, Do you like to put this fix into a pull request? I would try do so otherwise, but would be my first time. I had a lot of trouble with this issue and finally came to the same conclusion, that N is not set correctly. However, your fix is better than mine. It was setting N to a sufficiently large number from the beginning. I'd rather like to see yours in the library.

In my application I like to get the frequency and phase of a signal over time. If one checks for medium to high frequencies relative to nyquist limit (-> small widths) with high resolution (-> small width steps) the shift of half a sample hurts and is discontinous in the output while varying the widths. Especially when extracting the phase, even a small shift is severe.

I condensed this into another example to further illustrate why I think this is ciritical.

```python
t = np.linspace(0,1,100)
twopi = 2*np.pi
s = np.sin((twopi*25*(1+0.05*np.sin(twopi*2*t)))*t)
widths = np.linspace(2, 5, 100)
cwt = scipy.signal.cwt(s, scipy.signal.morlet2, widths)
```
The signal is constructed to have fast enough variations in frequency that the glitches are visible in the plot:
![scipy_cwt](https://user-images.githubusercontent.com/25102059/126762031-09374fa1-e836-4022-8892-f571ba03984e.png)

When applying the proposed fix to set N to uneven numbers, this looks smooth as expected:
![scipy_cwt_fixed](https://user-images.githubusercontent.com/25102059/126762049-456ccf07-d8a9-4867-8b96-3b5aae0e908b.png)

**Comment by ev-br** [comment]
cwt is deprecated in scipy 1.12. Thanks all.
