### ISSUE TITLE
ks_2samp throws `RuntimeWarning: overflow encountered in double_scalars`

### ISSUE THREAD

**Issue by Chris-Kimmel** [scipy/scipy#14019]
Hiya all. My code's throwing a `RuntimeWarning` for a floating-point overflow. Thought I'd better share.

#### Reproducing code example:
```python
import pickle
import pandas as pd
from scipy.stats import ks_2samp

# version info
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info, end='\n\n')

path = 'example_data.csv'
df = pd.read_csv(path)

print(df.head(), end='\n\n')
print(df.dset.value_counts(), end='\n\n')

sample_1 = df.loc[df.dset == 1, 'measurement']
sample_2 = df.loc[df.dset == 2, 'measurement']
s, p = ks_2samp(sample_1, sample_2, alternative='less') # throws RuntimeWarning
print(s, p, end='\n\n')
```

#### Output (including warning message):
```
1.6.0 1.19.2 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)

                                read_id  measurement  dset
0  0153c115-d84e-4b6a-81ad-25dcf938b078     0.352588     1
1  01919874-2479-4f42-9bc6-dafbfa71460f     0.420933     1
2  0192782e-41ab-453f-ad86-69b3bcffa82a     0.151604     1
3  01c229ec-d609-4a96-8c98-9e935b013ab1     0.238302     1
4  01d5f369-fc79-47ab-b71a-20f3825f485b     0.589941     1

1    881
2    369
Name: dset, dtype: int64

0.27017216823700585 2.5700040154944468e-17

/users/PAS1405/kimmel/.conda/envs/sci-computing-env/lib/python3.7/site-packages/scipy/stats/stats.py:6659: RuntimeWarning: overflow encountered in double_scalars
  num_paths += term
/users/PAS1405/kimmel/.conda/envs/sci-computing-env/lib/python3.7/site-packages/scipy/stats/stats.py:6656: RuntimeWarning: overflow encountered in double_scalars
  term = B[j] * bin
```

The lines of scipy code that throw the warnings (or at least, their equivalents in version 6.3) are here:
https://github.com/scipy/scipy/blob/14af6145d0402a9cac45ef7db8dcad78f023517e/scipy/stats/stats.py#L7155-L7162

I attached my Conda environment.yaml file ([env.txt](https://github.com/scipy/scipy/files/6453040/env.txt)) as well as a CSV of the data that's giving me trouble ([example_data.txt](https://github.com/scipy/scipy/files/6453058/example_data.txt)).

Is the output of `ks_2samp` trustworthy in this case?

Thanks,
~Chris

**Comment by V0lantis** [comment]
Hello Chris, 

Could you try your code on the master branch ? I tried on my machine (on master), and I wasn't able to reproduce the warning.

**Comment by mdhaber** [comment]
I can reproduce this in `main` on my machine.

Whether the results are "trustworthy" depend on your needs. The statistic is accurate, but the p-value is not exact. 

The overflow occurs because the sample sizes are very large. The warnings don't explain what happens, but after the overflow, the function switches from attempting the exact calculation to performing an asymptotic calculation, which tend to become accurate as sample sizes increase. In this case, I would trust that exact the p-value is on the order of 1e-17 because the two-sided exact test does not have trouble:

```
> ks_2samp(sample_1, sample_2, alternative='two-sided', mode='exact')
KstestResult(statistic=0.27017216823700585, pvalue=3.246909807766347e-17)
```

One thing that should be done to consider this issue resolved is to improve the selection of exact vs asymptotic test and to show the appropriate warnings when things go wrong. There is some funny logic in the code. For instance:

https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/stats/_stats_py.py#L7425-L7431

Why should this warning only appear if the user requested the exact method? In your case, it would have been better if you had been informed that the p-value was from the asymptotic method.

It would be even better if the exact calculation could be extended to even larger samples like in gh-14432. (But there is no shortage of enhancement requests like this, and personally, I would prioritize fixing major bugs and adding exact p-values for other important tests over computing exact one-sided p-values for large samples here.)
