### ISSUE TITLE
custom linkage function in scipy.cluster.hierarchy.linkage

### ISSUE THREAD

**Issue by diepala** [scipy/scipy#14042]
It would be useful to be able to customize the linkage function of `scipy.cluster.hierarchy.linkage`. At the moment, the argument `method` only supports predefined linkage functions.

For example, the `method` argument could also accept functions that compute the distance between two clusters.
The functions it should accept should have a signature like `f(u: np.array, v: np.array) -> float` where `u` and `v` are two clusters, each one being a matrix containing the data points in the cluster.

The reason this is useful is that sometimes it is needed a cluster distance function that not only takes into account the distance between pairs of points. Obviously, this is only valid when the argument `y` of `scipy.cluster.hierarchy.linkage` is a sequence of samples.

**Comment by rgommers** [comment]
This request seems to be based on a misunderstanding. Linkage functions return arrays and don't have a signature like that. From both the description and the signature it seems clear that you want a custom _distance_ metric rather than a custom _linkage_ function. 

It's already possible to use any distance metric you want. The first input to the function, `y`, can be either a 2-D or a 1-D array. In the latter case, it is already the output of a distance function calculation (e.g., `pdist`). So you can perform your own distance computation and then feed the result into `linkage`.

There doesn't seem to be anything to do here, so I will close this issue.
