### ISSUE TITLE
scipy.optimize.linprog interior-point method gives incorrect value/solution

### ISSUE THREAD

**Issue by hexken** [scipy/scipy#14115]
The interior-point method is giving different results than all other methods, which give consistent results.

In particular, with method='interior-point' I am getting:
```
res.x = [7.38194004e-12 1.74855713e+00 4.63915830e+00 1.14204404e+00]
res.fun = -3.4279130645131772e-09
```
but with simplex, revised simplex, and highs, I am getting:
```
res.x = [0. 1. 2. 0.]
res.fun = 1.1944667477337134e-11
```
which seems to match up with my expected results.

Reproducing code:
```
import numpy as np
from scipy.optimize import linprog

C = np.array([[1, 3, 2], [1, 1, 2]])
k, n = C.shape
A = np.array([[1, 1, 1]])
b = np.array([1])
w = np.array([0, 2])
e = np.ones(k)


upper = np.hstack((-C.T, A.T, -A.T))
lower = np.hstack((e, np.zeros(A.shape[0]), np.zeros(A.shape[0])))
A_ub = np.vstack((upper, lower))
b_ub = np.hstack((np.zeros(n), np.ones(1)))

c = np.hstack((-w, b, -b))
print(A_ub, b_ub, c)
res = linprog(c, A_ub=-A_ub, b_ub=-b_ub, method='interior-point')
print(res.x)
print(res.fun)
res = linprog(c, A_ub=-A_ub, b_ub=-b_ub, method='revised simplex')
print(res.x)
print(res.fun)
```

Version information:
```
Scipy 1.6.3
Python 3.8.10
Numpy 1.19.2
```

**Comment by mdhaber** [comment]
Since `e` is not defined, I can't run your code to check.
Unless the solution returned by interior point is violating a constraint, this is not a bug. My guess is that your problem may not have a unique solution. In these cases, interior-point typically will not converge to the same solution as the others.

**Comment by hexken** [comment]
> Since `e` is not defined, I can't run your code to check.
> Unless the solution returned by interior point is violating a constraint (by more than some small numerical tolerance), this is not a bug. My guess is that your problem may not have a unique solution. In these cases, interior-point typically will not converge to the same solution as the others.

I have added the definition of e. I originally thought the system had a unique solution, but now I am not so sure. I will look into it some more when time permits.

**Comment by mdhaber** [comment]
With `method='interior-point', non-negativity constraint is satisfied:
```
res.x  # array([7.38194367e-12, 1.74855806e+00, 4.63916064e+00, 1.14204451e+00])
```
There is non-negative slack (within a small tolerance):
```
(-b_ub) - (-A_ub)@res.x  # array([ 1.74855806e+00,  1.74855806e+00, -3.44851947e-09,  7.48558064e-01])
```
And the objective function is just as low (a little lower, probably due to tiny violation of third inequality constraint).
So it looks like there are multiple solutions.
I'll go ahead and close, but please re-open if you still think there is a bug.
