### ISSUE TITLE
minor suggestion

### ISSUE THREAD

**Issue by Emoshe** [scipy/scipy#14114]
The function vectorize1 has:
    if vec_func:
        def vfunc(x):
            return func(x, *args)

Simpler to have
    if vec_func:
        vfunc = func

**Comment by mdhaber** [comment]
Thanks @Emoshe. Noted, but this is not something that we would change unless it is part of some other enhancement or bug fix - especially since it doesn't appear to be a public function. If I'm mistaken, please point me to the documentation. In the meantime, I'll go ahead and close this, but please feel free to re-open if this is a bug report or enhancement request.
