### ISSUE TITLE
Add gels lapack_driver to lstsq

### ISSUE THREAD

**Issue by vnmabus** [scipy/scipy#14123]
**Is your feature request related to a problem? Please describe.**
In #7316 the possibility of adding the `lapack_driver` gels to `lstsq` was mentioned, but at the end it wasn't done. Thus, there is yet no driver in scipy for `lstsq` that uses a QR decomposition, as far as I know.

Note that other libraries like PyTorch provide that functionality, so it is doable.

**Describe the solution you'd like**
A new `lapack_driver` gels for `lstsq` that uses QR decomposition.

**Comment by ilayn** [comment]
The driver is there but hasn't been added to `lstsq` function as a valid option. This is mainly due to the fact that `?gels` routines assumes full rank `A` and otherwise fails, and in a all-purpose function this might cause some trouble for the users. 

`?gelsy` uses QR decomposition and is a more general version and you can use gelsy option to select that

**Comment by vnmabus** [comment]
Ok, thank you for your quick response! I now understand the reasoning for not including it, so I think the issue can be closed.
