### ISSUE TITLE
Cholesky decomposition and non positive-definite matrix

### ISSUE THREAD

**Issue by decadenza** [scipy/scipy#14134]
System configuration
- Python 3.9.1
- Scipy 1.6.0

Issue:
scipy.linalg.cholesky provides a solution even when the input matrix is not positive-definite.

Example:
```
import numpy as np
from scipy.linalg import cholesky

np.set_printoptions(precision=16)
A = np.array([[ 6.7768504406861214e+10, -5.1181297184799976e+09, -5.8762464676856367e+13],
 [-5.1181297184799967e+09,  1.5963884740838235e+11, -1.9144237778256950e+14],
 [-5.8762464676856367e+13, -1.9144237778256950e+14,  2.9188609076234259e+17]])
 
print("Determinant", np.linalg.det(A))
print("Eigenvalues", np.linalg.eigvals(A))

L = cholesky(A, lower=True)

A_bis = L @ L.T

print("Is equal", np.array_equal(A,A_bis))
print("Is close", np.allclose(A,A_bis,rtol=0,atol=1e-3))
```

The output is:
```
Determinant 0.0
Eigenvalues [ 2.918862281557095e+17  9.001398464165211e+10 -3.960408184047992e-02]
Is equal False
Is close False
```

As you can see, the A matrix is not positive-definite, hence no decomposition is possible.
The decomposition provided is not a valid decomposition, however the algorithm does not raise an error.

Is the problem connected to some numerical issues? I wasn't able to understand the source code.

**Comment by tupui** [comment]
Then, do I get correctly that there is no issue and this could be closed?

**Comment by decadenza** [comment]
From @ilayn, if I understood correctly, this is due to numerical overflow.
However, I think that the issue is there: no warning/error is raised in any way, potentially leading to wrong results.

In my application, for example, the above error caused a wrong stereo image rectification and took me days to find this. I cannot "stay away" from `[eps, 1/eps]` as this depends on camera positions (and perfectly legitimate ones).

As a workaround now I need to do a check to see if `np.allclose(A, L @ L.T, rtol=0, atol=1e-3)` after decomposition and raise an error if `False`. But it's a dirty fix as, in my humble opinion, an error should be raised when `A` is not positive-definite as Cholesky decomposition does not exist **by definition**.

References: [https://en.wikipedia.org/wiki/Cholesky_decomposition](Cholesky decomposition)

**Comment by ilayn** [comment]
No my apologies, I didn't mean numerical overflow. This is basically very natural and happens to all floating point operations. When your matrix has very large numbers they dominate the precision and the smaller parts often gets noisy. 

In your `np.allclose` test it is not very likely that in any computation you'll get that much precision for example take this simple, admittedly dummy step

```
>>> z = np.random.rand(3,3)
>>> np.allclose(A, np.linalg.inv(z) @ (z@ A), rtol=0., atol=1e-3)
False
```
Ideally just a simple almost-identity matrix multiplication should not cause an issue but because your insignificant bits are changing and since the numbers are of order ~1e10, it is too difficult to get 1e-3 precision. This will always be a problem if you don't scale down your data or use a different precision offering platform.

**Comment by ilayn** [comment]
Regarding your positive definiteness comment if you use a bit more specialized version of the eigenvalue computation 

```python
import scipy.linalg as la
la.eigvalsh(A)
Out[27]: array([2.97697754e+01, 9.00139847e+10, 2.91886228e+17])
```

so it is positive definite. But again one of them is tiny compared to the others.

**Comment by tupui** [comment]
We seem to have similar issues often. @ilayn do we have a section in the doc talking about numerical precision and ways to work around it? If not, I think this would be useful.

**Comment by decadenza** [comment]
Thanks for the explanation.
Indeed, `la.eigvalsh(A)` and `np.linalg.eigvals(A)` provide different results (should I consider `la.eigvalsh` more accurate?).

Anyway, what sort of control would you do to ensure that the decomposition is legitimate?
I mean, in an operation environment I want to be sure that L is the actual decomposition.

Something like:
```
from scipy.linalg import cholesky

def cholenskyAccurate(A):
    L = cholesky(A, lower=True)
    # DO SOME CHECK HERE
    if ok:
         return L
    else:
         raise ValueError("Inaccurate decomposition...")
```

**Comment by ilayn** [comment]
Cholesky is probably as accurate as it can be and you don't need to test it per se since it is pretty much battle-tested over decades. It's not a guarantee of anything but it is very unlikely that you hit a bug in 3x3 matrices.

 It is the reconstruction that you can't recover back, at the level of precision you want. Not to be pedantic of course but this is unfortunately how floating point numbers work. So a typical numerical error bound in array computations is the product of size of the matrix size of its contents and the precision of the datatype you are working with scaled with some heuristics number.

I would typically use `atol=100*max(m,n)*np.linalg.norm(A, 1)` as a generic atol value if you want recover the test.

**Comment by decadenza** [comment]
Thanks @ilayn. I am indeed sure that the function is "battle-tested".
The algorithm I am dealing with still fails because of this imperfect decomposition (it is used to find an intial guess and a wrong initial guess here causes divergence).

In the end I am using a check like this:
```
from scipy.linalg import cholesky

def cholenskyAccurate(A):
    L = cholesky(A, lower=True)
    if np.allclose(A, L @ L.T, rtol=0, atol=1e-3):
         return L
    else:
         raise ValueError("Precision loss in Cholesky decomposition.")
```
I cannot allow a loss of precision and it is necessary to raise an error for my application, otherwise I end up with wrong solutions.

Thanks. Closing.
