### ISSUE TITLE
Add option for terminating solver after n events

### ISSUE THREAD

**Issue by arichar6** [scipy/scipy#14176]
The [IVP solver in scipy](https://github.com/scipy/scipy/blob/2c72ae27e59e64f47d64bf65800a291ff972df86/scipy/integrate/_ivp/ivp.py#L156) is a flexible and useful initial value solver. One feature that I greatly appreciate is the ability for the solver to locate "events", and allow those events to be "terminal" (i.e., the integrator will stop when an event is found).

It would be really useful if the event handler in this solver could be extended so that the integration will stop after some number of "events" occurs. So instead of only having two options (_not terminal_ and _terminal at the first event_), the user would then be able to specify something like _terminal after n events_.

**Comment by drhagen** [comment]
This sounds like a good feature to me. One thing to note is that the current `terminal` behavior is equivalent to terminating after 1 event, so the most appropriate API would be deprecating `terminal` as an attribute on the event and replacing it with `max_events` or some similar name with a default of `inf`.

This would be a somewhat disruptive deprecation, but the deprecation period could be very long because it is not particularly bad to have these features side-by-side. In the interim, I would propose that setting both `terminal` and `max_events` would be an error. Setting `terminal=True` would be equivalent to `max_events=1`.

**Comment by mdhaber** [comment]
On the other hand, there have been other requests for `solve_ivp` to get a callback interface. Could the user set `terminal` to `False` and count occurrences in the callback, then use the callback to terminate when desired? This would be more flexible, and it gives even more reason to add a callback.
