### ISSUE TITLE
better description of solveh_banded limitations

### ISSUE THREAD

**Issue by nedlrichards** [scipy/scipy#14198]
Related to the discussion in the original pull request for linalg.solveh_banded, #4373, the solver requires additional constraints on the matrix compared to linalg.solve and linalg.solve_banded.

The routine solveh_banded requires leading minors of the matrix A in the equation A * x = b be positive definite. I do not understand this requirement at all, so I can not begin to delve into the linear algebra discussion. This requirement is very confusing as it stands, however, because it is not raised in very similar solvers that it is meant to supersede.

In an ideal world, I would like to help relax this requirement to be more in line with the other solvers. I do not know how to go about this as it stands. At a minimum, could we work on a more informative error message that mentions the other solvers may still work in situations where solveh_banded fails?

Here is an example of an error that is raised in an application finding eigenvectors from eigenvalues by inverse iteration

```
import numpy as np
from scipy.linalg import solve, solveh_banded, solve_banded

numz = 105
d = np.full(numz, -1.9964864348874727)
C = np.diag(d) + np.diag(np.ones(numz - 1), k=1) + np.diag(np.ones(numz - 1), k=-1)

# first iteration to find eigen-vector
phi_test = np.ones(numz)
phi1 = solve(C, phi_test)

C_b = np.ones((3, numz))
C_b[1, :] = d
phi2 = solve_banded((1, 1), C_b, phi_test)

C_h = np.ones((2, numz))
C_h[1, :] = d
phi3 = solveh_banded(C_h, phi_test)
```

**Comment by ilayn** [comment]
It is because Thomas' algorithm (that these routines perform) is stable only for those cases that is diagonally dominant and pos def. hence the LAPACK names ptsv and pbsv for the underlying routines. But there is no tridiagonal solvers for symmetric /hermitian matrices since then you are 

But in hindsight, this is a mistake on our side that we shouldn't have named it so. For now you can use the `linalg.lapack.?gbsv` for banded and `linalg.lapack.?gtsv` for tridiagonal matrices. Since the complexity is O(n) in general for tridiagonals, symmetricity/hermitianness would not make any substantial difference here since partial pivoted LU will take care of the structure. (I think!!). Same applies for the banded case. But remains to be benchmarked. 

I am not sure how to change the function after so many years without breaking things.

**Comment by nedlrichards** [comment]
Thank you for the response, it is also helpful to know about the option of using lapack functions. After reading the documentation more closely, the first line does mention the positive definite requirement. I will think about how I would change the documentation, and try to come up with a suggestion that highlights the additional distinction between solve_banded and solveh_banded of a "diagonally dominant and positive definite" matrix.

**Comment by ilayn** [comment]
Ah yes I am stupid. You can use directly `solve_banded` for banded matrices. Can't say it's perfect but it is at least a nice Python function that does what it says on the tin.
