### ISSUE TITLE
#scipy channel in Libera.Chat IRC network

### ISSUE THREAD

**Issue by Arfrever** [scipy/scipy#14239]
After collapse of Freenode started on 2021-05-19 ([1](https://en.wikipedia.org/wiki/Freenode#Ownership_change_and_conflict), [2](https://lwn.net/Articles/856543/), [3](https://lwn.net/Articles/857140/)) (with latest event being [dropping of databases of channels and users](https://www.devever.net/~hl/freenode_suicide) on 2021-06-15), I registered `#scipy` channel in [Libera.Chat IRC network](https://libera.chat/).

I want to transfer ownership of `#scipy` channel to SciPy project.
Which persons are members of governing body of SciPy project? Please include IRC usernames in answer.

https://www.scipy.org/scipylib/mailing-lists.html#irc will also need to be updated.

**Comment by tupui** [comment]
This would need to be discussed on the mailing list. Could you send an email here?

We recently had talks (you can search the mailing list for this) about having a space on Discourse, Slack and such. I am not sure about this new platform though.

**Comment by person142** [comment]
@tupui note that IRC isn't really a "new" platform; the `#scipy` channel on Freenode was in use for a long time (Maybe @pv was an owner?) At a certain point we made some of the more active community members opers and let them moderate because nobody on the core team was up for it. (Somewhere there is a mailing list discussion about this...)

I have no idea how active that channel was before everyone started moving to Libera Chat though-I haven't joined it for a few years now.

**Comment by tupui** [comment]
> @tupui note that IRC isn't really a "new" platform; the `#scipy` channel on Freenode was in use for a long time

I have seen this indeed, still as we had a long discussion on the mailing list (https://mail.python.org/pipermail/scipy-dev/2021-May/024824.html), I think it would be better to send an email (as it's the way now for such big decisions).

Freenode is like Gitter, Slack, Discourse or any other chat but with less moderation tools as far as I know. On my side, I would not advise for it. Still we can do some name squatting and redirect to preferred platforms. As other suggested, we should not have to many mediums as to not split the community. So one chat would be enough.

**Comment by ilayn** [comment]
Freenode just had a global meltdown so Libera.chat is the target where people are flocking to. And probably things are being set up from scratch. Hence thanks for the reservation and offer @Arfrever, much appreciated. 

We are not using too much (even none? ) since there are not many users active there. If @pv, @rgommers and @ev-br or any other IRC-capable core devs can take over the channel credentials I think that would be sufficient. It would probably go stale there in the new home tough.

**Comment by rgommers** [comment]
I am definitely not capable:) Also, I think IRC is a thing of the ancient past, so I'm happy to let it die. If there are still hardcore users that value having a `#scipy` channel on Libera, that sounds perfectly fine, but I don't think it should be an official project thing.

**Comment by ev-br** [comment]
> am definitely not capable

Same here, sorry

**Comment by pv** [comment]
Official channel would need someone to moderate. I don't really have the time. Some people volunteered for the old channel years back and maybe they're still interested, but can't find the mailing list thread about that right now.

**Comment by ilayn** [comment]
I found an issue from two years back where Pauli mentions again a few years prior to that https://github.com/scipy/scipy.org/issues/308

That means we really have no IRC presence and whatever it was is now gone after Freenode "suicide" described in the link in the original post.

**Comment by tupui** [comment]
Some feedback since this was opened. This is my very personal opinion and I do not mean to hold the ground truth.

I have been connected for 2-3 weeks almost straight and tried to ask questions and engage a bit.  , but I found the experience quite depressing in general. Since there is not really a history (you still can get disconnected from time to time even with a client like LimeChat, or I did not configure this well as after a few days it sometimes get reseted...), you send messages in the air and just hope that someone is there to reply. Otherwize, well it's just lost. I don't find this very engaging and also since you cannot search the history, you just expose yourself to answer the same things forever.

Based on these, I would not recommend this experience to anyone... The initial configuration is also a big blocker for me.

**Comment by rgommers** [comment]
Thanks for trying @tupui. Looks like we should just delete the text about IRC from https://www.scipy.org/scipylib/mailing-lists.html#irc and then close this issue.

**Comment by tupui** [comment]
Ok, I opened a PR for that.

**Comment by tupui** [comment]
Closing as we now removed the IRC section. Thanks everyone!
