### ISSUE TITLE
How to call scipy in C++?

### ISSUE THREAD

**Issue by xjcvip007** [scipy/scipy#14252]
**Is your feature request related to a problem? Please describe.**
I searched for a long time about the question, but there is no exact question.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Pybind11?

**Additional context (e.g. screenshots)**

**Comment by ilayn** [comment]
This question is better suited for Stackoverflow or similar sites since we only consider SciPy related bugs and features. Your question is a generic Python call from C/C++ and there are many solutions existing on google. Pybind11 is calling C/C++ from Python 

https://www.codeproject.com/Articles/820116/Embedding-Python-program-in-a-C-Cplusplus-code
https://stackoverflow.com/questions/3286448/calling-a-python-method-from-c-c-and-extracting-its-return-value
https://sites.northwestern.edu/yihanzhang/2019/08/22/how-to-invoke-python-function-from-c/

and many more.

**Comment by xjcvip007** [comment]
Thanks for you quick reply!
