### ISSUE TITLE
cython_blas does not use const in signatures

### ISSUE THREAD

**Issue by david-cortes** [scipy/scipy#14262]
Usually, BLAS interfaces for C use function signatures with const qualifiers - examples:
```c
void F77_daxpy( FINT, const double *, const double *, FINT, double *, FINT);
```
```c
F77_NAME(daxpy)(const int *n, const double *da,
		const double *dx, const int *incx,
		double *dy, const int *incy);
```

However, the Cython `pxd` file for `cython_blas` generates the function signatures **without** `const` qualifier:
```python
cdef void daxpy(int *n, d *da, d *dx, int *incx, d *dy, int *incy) nogil
```

Which makes it harder to wrap into existing programs if they are using `const`.

**Comment by rgommers** [comment]
That seems like a good idea to add. Thanks for the suggestion @david-cortes.

**Comment by sturlamolden** [comment]
Cython did not support the ```const``` qualifier when these wrappers were written. That is the reason it is omitted. It does now, however, so we can use it.

**Comment by sturlamolden** [comment]
It is not difficult to use the wrappers in the presence of ```const``` data though. We just have to write a tiny inline wrapper function that e.g. uses a C++ ```const_cast``` operator to cast away the constness. In Cython ```const_cast``` can be made available using the statement
```from libcpp.cast import const_cast```
When we do this the overhead in the generated machine code is exactly zero, as the C++ compiler will optimize away the wrapper.

**Comment by sturlamolden** [comment]
Basically we can work around const like this, which is not difficult, just a bit tedious:

```
from scipy.linalg.cython_blas cimport daxpy
from libcpp.cast cimport const_cast

cdef inline void const_daxpy(const int *n, const double *da,
		const double *dx, const int *incx,
		double *dy, const int *incy) nogil:
    cdef: 
        double *tda, *tdx
        double  *tn, *tincx, *tincy
    tda = const_cast[double*](da)
    tdx = const_cast[double*](dx)
    tn = const_cast[int*](n)
    tincx = const_cast[int*](incx)
    tincy = const_cast[int*](incy)
    daxpy(tn, tda, tdx, tincx, dy, tincy)
```

**Comment by sturlamolden** [comment]
And if we instead use Cython to generate C, it is

```cython
from scipy.linalg.cython_blas cimport daxpy

cdef inline void const_daxpy(const int *n, const double *da,
		const double *dx, const int *incx,
		double *dy, const int *incy) nogil:
    cdef: 
        double *tda, *tdx
        int *tn, *tincx, *tincy
    tda = <double*>(da)
    tdx = <double*>(dx)
    tn = <int*>(n)
    tincx = <int*>(incx)
    tincy = <int*>(incy)
    daxpy(tn, tda, tdx, tincx, dy, tincy)
```

**Comment by david-cortes** [comment]
I assume the module is calling these functions from a dynamically-linked BLAS library, which already has them with `const`.

Shouldn't it be enough with just adding `const` in the `extern` declarations and in the script that generates the exported .pxd?

**Comment by lorentzenchr** [comment]
Is a PR welcome that adds the `const` qualifier? Or is it more complicated with backwards compatibility issues?

**Comment by sturlamolden** [comment]
It should be ok. The compiler will cast ```T *``` to ```const T *``` but not the other way around. It is the absence of ```const``` that cause the problems (i.e. requiring an explicit ```const_cast``` of ```const T *``` to ```T *``` when calling BLAS). Adding ```const``` qualifier to the prototypes can be done with imunity. It will only help to solve problems.

**Comment by sturlamolden** [comment]
https://www.damnyouautocorrect.com
I know we have a pandemic and all, but impunity is not immunity…

**Comment by lorentzenchr** [comment]
Looking a bit deeper, adding `const` qualifier seems tricky. The Cython interface is generated automatically by `_cython_signature_generator.py` which inspects at the BLAS fortran files. The problem then arises because there are 2 different routines:
- routines that do not modify arguments like `ddot(const int, n, const double *x, const int incx, const double *y, const int incy)`, i.e. all arguments can be declared const. See [MKL C reference cblas_?dot](https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-c/top/blas-and-sparse-blas-routines/blas-routines/blas-level-1-routines-and-functions/cblas-dot.html)
- routines that modify an argument like `daxpy(const int n, const double a, const double *x, const int incx, double *y, const int incy)`,i.e. argument `y` is modified inplace. See [MKL C reference cblas_?axpy](https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-c/top/blas-and-sparse-blas-routines/blas-routines/blas-level-1-routines-and-functions/cblas-axpy.html)

Does someone has a good idea how to do that distinction automatically rather than listing them manually (which would obfuscate `_cython_signature_generator.py`)? It seems save to assume that if the return type is not void than all arguments can be declared const.

**Comment by ev-br** [comment]
The reference implementation only seems to list intent in the docs (which is not surprising since `intent(in, out) ` qualifiers are fortran 90 only. So I guess it's easiest to list it manually.

**Comment by sturlamolden** [comment]
Yeah, it is not a trivial problem. The constness is declared in the CBLAS and LAPACKE headers, but ```cython_blas``` and ```cython_lapack``` expose the ABI of the Fortran 77 routines rather than the official C interface. If you parse down the CBLAS and LAPACE headers, you should be able to interfere the constness in the corresponding Fortran routines from the C signatures.

Arguably we might doing this the wrong way and should perhaps just leave ```cython_blas``` and ```cython_lapack``` as they are. After all, there are no concept of const arrays in Fortran 77. Instead the subroutines in BLAS and LAPACK have comments that tell if input will be altered or not. I think the more correct solution would be to create two new modules, ```cython_cblas``` and ```cython_lapacke```, that expose the official C interface of BLAS and LAPACK. The constness would follow naturally as it is already declared manually in the official C headers.

**Comment by ilayn** [comment]
> I think the more correct solution would be to create two new modules, cython_cblas and cython_lapacke, that expose the official C interface of BLAS and LAPACK. The constness would follow naturally as it is already declared manually in the official C headers.

This would also make things easier for C contiguous arrays which we are jumping multiple hoops for and losing no-nnegligible performance.

**Comment by david-cortes** [comment]
BTW the non-cblas C headers (which are F77 wrappers) from MKL, OpenBLAS, BLIS, and R’s blas do come with `const`: https://github.com/wch/r-source/blob/79298c499218846d14500255efd622b5021c10ec/src/include/R_ext/BLAS.h

But then I guess the `const`ness would either have to be specified manually, or determined from some automated parser plus a reference header from a specific implementation like OpenBLAS.

**Comment by hoodmane** [comment]
In Pyodide's build process, we get a few compile errors related to `const` inconsistency in signatures so we have add a simple patch. I wonder if this would help.

**Comment by lorentzenchr** [comment]
> I think the more correct solution would be to create two new modules, cython_cblas and cython_lapacke, that expose the official C interface of BLAS and LAPACK. The constness would follow naturally as it is already declared manually in the official C headers.

IIUC, a PR would "just" need to copy over those 2 header files from blas and lapack? But from which version? How do deal with `lapack_manual_wrappers`, `blas_exclusions` and `lapack_exclusions` in the file `_cython_signature_generator.py`?

**Comment by lysnikolaou** [comment]
Ηey everyone! I plan to tackle this issue in the next days and I’d like a quick sanity check on a grob plan.

First of all, here's my understanding of the current pipeline to generate the Cython`pxd`:
- `scipy/linalg/_cython_signature_generator.py` generates `scipy/linalg/cython_blas_signatures.txt`
- The signatures in the txt file are then used to generate `cython_blas.pxd` and company from `scipy/linalg/_generate_pyx.py`
- Question: Is my understanding correct that the fortran symbols, used in `scipy/linalg/_cython_signature_generator.py`, are from LAPACK 3.4.0?

A grob plan of what I think is a sensible way going forward is:
- Use CBLAS headers to parse the function signatures and generate `scipy/linalg/cython_blas_signatures.txt`
- Make any necessary transformations in `scipy/linalg/_generate_pyx.py` in order to be able to read the new signatures (not sure if needed)
- Question: If this makes sense, should we be using the [LAPACK 3.7.1 headers](https://github.com/Reference-LAPACK/lapack/blob/v3.7.1/CBLAS/include/cblas.h) (according to [the toolchain roadmap](https://docs.scipy.org/doc/scipy/dev/toolchain.html#other-libraries)). What if there are differences with the current list of exported symbols in `scipy.linalg.blas`? Should the list remain the same?

**Comment by rgommers** [comment]
> Question: Is my understanding correct that the fortran symbols, used in `scipy/linalg/_cython_signature_generator.py`, are from LAPACK 3.4.0?

Yes, that looks correct - with the minor note that the routines that were removed in LAPACK 3.6.0 are not included in `cython_lapack_signatures.txt`, that should have been taken care of by commit 0528f14.


> Use CBLAS headers to parse the function signatures and generate `scipy/linalg/cython_blas_signatures.txt`

I'm not sure about that. The `cython_signature_generator.py` script uses the Fortran headers and the Netlib BLAS/LAPACK sources. That script should already do the right thing, mostly. Maybe enhancing that script by fishing const arguments from CBLAS/LAPACKE headers would be easier than starting from scratch? Really not sure though, and the script is <200 LoC so maybe it's not too bad to change it completely.

> Question: If this makes sense, should we be using the [LAPACK 3.7.1 headers](https://github.com/Reference-LAPACK/lapack/blob/v3.7.1/CBLAS/include/cblas.h) (according to [the toolchain roadmap](https://docs.scipy.org/doc/scipy/dev/toolchain.html#other-libraries)). What if there are differences with the current list of exported symbols in `scipy.linalg.blas`? Should the list remain the same?

Using LAPACK 3.7.1 sounds good. It may drag in some new routines, and that'd be a good thing. If there are other differences that show up, then not sure - it depends on what those would look like.

**Comment by rgommers** [comment]
This caused some breakage in scikit-learn; still a bit fuzzy what's happening or what to do about it, but folks who were interested in this issue may want to follow gh-18377.

**Comment by sturlamolden** [comment]
> This caused some breakage in scikit-learn; still a bit fuzzy what's happening or what to do about it, but folks who were interested in this issue may want to follow [gh-18377](https://github.com/scipy/scipy/issues/18377).

Fortran 77 has no concept of a const, so why did we do this? 

CBLAS does have const in the API, though, but that is a C API.

**Comment by rkern** [comment]
Because of the way Cython interprets what is an acceptable `ndarray` to pass to those arguments. Without `const`, Cython checks the writable flag and forbids read-only `ndarray`s. Adding `const` (is supposed to) just tell Cython to allow either read-only or writable `ndarray`s. So we check manually whether the specific subroutine is expecting to write to the passed array, and if not, then we should add the `const`.

**Comment by ilayn** [comment]
> This solution is not ideal, yet it allows support for read-only data while using implementations of BLAS as exposed to SciPy.

Yes indeed but we would have appreciated a ping here too since now this is tying our hands from downstream. Please let us know if you have such needs so that we can fix it here instead of each library rolling out their diverging behaviors.

**Comment by jjerphan** [comment]
> Please let us know if you have such needs so that we can fix it here instead of each library rolling out their diverging behaviors.

Initially, I would have thought that introducing `const`-qualifiers would have helped removing the work-around that we are using (hence my :+1:-react to this issue); but since https://github.com/scipy/scipy/pull/18247 came with unexpected disruption, I am not sure that the introduction of `const`-qualifiers is helpful anymore.

If interfaces prior https://github.com/scipy/scipy/pull/18247 cannot be overloaded with the ones https://github.com/scipy/scipy/pull/18247 introduces, then I do not see how we can maintain compatibility without having subsequent versions of SciPy and downstream libraries be tight (to me this is hardly practicable). :confused: 

What do you think?

**Comment by david-cortes** [comment]
> While I think that `const` must be present, this changes the signature and will make working with different version of SciPy and downstream libraries impossible.
> 
> For instance, in scikit-learn's case:
> 
> * currently, it won't be possible to use scikit-learn<=1.2.2 with SciPy>1.10.1.
> * alternatively, if scikit-learn adapts its codebase for these new changes in SciPy, it won't be possible to use the scikit-learn>1.2.2 with SciPy<=1.10.1
> 
> Before #18247, [scikit-learn's Cython implementations have been casting `const T *` to `T *`](https://github.com/scikit-learn/scikit-learn/blob/188267212cb5459bfba947c9ece083c0b5f63518/sklearn/metrics/_pairwise_distances_reduction/_middle_term_computer.pyx.tp#L434-L438). This solution is not ideal, yet it allows support for read-only data while using implementations of BLAS as exposed to SciPy.

Isn't this a compile-time-only issue? If I'm understanding it correctly, as long as scikit-learn is installed from a binary wheel, there shouldn't be any issues with running it alongside a scipy version having or not having these const qualifiers, since this is C-style linkage.

**Comment by jjerphan** [comment]
Unfortunately, we face issue which aren't compile-time issues, as reported by https://github.com/scikit-learn/scikit-learn/issues/26290.

**Comment by ilayn** [comment]
> I am not sure that the introduction of const-qualifiers is helpful anymore.

We definitely need this even for SciPy. sklearn also can rebuild the wheels or backport these changes. So I am not sure why you are considering that this is a block only for SciPy. This is an ABI issue and has no code changes required.

> Unfortunately, we face issue which aren't compile-time issues

Compile time issue is a tricky one so please don't give up just yet. That only means the nightly build of downstream is having problems. You can also build with new SciPy without your own modifications on sklearn side. I am still curious if a new build with new SciPy will have issues with old SciPy because they shouldn't have conflicts. What you have right now is just the CI result.

**Comment by jjerphan** [comment]
> C does not prevent us from passing `T *` to a function expecting `const T *`. That requires no cast. Even if you cast `const T *` to `T *`, it should still compile even though your `T *` is passed to `const T *`.

That's right, but the converse is not true: C prevents us from passing `const T*`  to `T*` which was the case with the previous Cython interfaces (that's the reason we originally needed this cast).

**Comment by sturlamolden** [comment]
> > C does not prevent us from passing `T *` to a function expecting `const T *`. That requires no cast. Even if you cast `const T *` to `T *`, it should still compile even though your `T *` is passed to `const T *`.
> 
> That's right, but the converse is not true: C prevents us from passing `const T*` to `T*` which was the case with the previous Cython interfaces (that's the reason we originally needed this cast).
> 
> Might this case be a reason for Cython to have runtime checks on signatures?

After the cast, ```T *``` (formed by the cast) is passed to ```const T *``` (the new signature) and this is disallowed by Cython. What we have here is Cython type checking at odds with the semantics of C and C++. This has to be regarded a bug in Cython. It should not disallow semantics that C and C++ allow.
