### ISSUE TITLE
scipy.stats.rv_continuous.fit not able to fit data

### ISSUE THREAD

**Issue by arpitjain305** [scipy/scipy#14290]
I have discrete & normalized (by z-scores) univariate data, which looks like it should fit well with an exponential-family distribution such as one of 'beta', 'expon', 'gamma', 'lognorm', 'pearson3', 'triang', 'uniform', 'weibull_min', 'weibull_max'. 

I am using  `scipy.stats.rv_continuous.fit` to fit the data without any additional args. However, the KS-test statistics I am getting for each of the fitted distributions are very poor/high, with a consistent zero p_value. Is there something additional I need to pass in order to get a good fit?

**Comment by mdhaber** [comment]
Passing a good guess of the parameters can help. For instance, the next positional arguments after the data are treated as guesses for the shape parameters, and you can pass `loc` and `scale` to guess the location and scale. Fixing parameters you know (e.g. passing keywords `floc`, `fscale`) can also really help. Some of those distributions you mention have analytical formulas implemented for the fits, although some require one of the parameters to be fixed to use it (instead of three default numerical optimization).
But can you post your data (or example data that hasc the same problem) and the complete code so we can run it and see what is going on?

**Comment by rgommers** [comment]
No follow-up, so I will close this issue.
