### ISSUE TITLE
Jaccard distance greater than 1 if elements are strings

### ISSUE THREAD

**Issue by ubalklen** [scipy/scipy#14304]
```
>python
Python 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy 
>>> scipy.__version__
'1.6.2'
>>> from scipy.spatial.distance import jaccard
>>> jaccard([1, 0, 0], [0, 1, 0])
1.0
>>> jaccard(["A", "B", "B"], ["B", "A", "B"])
FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  nonzero = np.bitwise_or(u != 0, v != 0)
2.
```

**Comment by jakevdp** [comment]
Thanks for the report - the jaccard similarity is intended for use with boolean arrays (as mentioned in the [doc string](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.jaccard.html)), and its behavior with other input types is ill-defined.

It may be better if the function returned a `ValueError` in this case, rather than returning an ill-defined value. But in the meantime, stick with boolean inputs and the function should work as expected.

**Comment by yacth** [comment]
Hi @jakevdp  I am trying to solve the issue by adding a check up to see if we have a 1-D boolean array.
But it seems that in the tests, it is testing multi-dimentional arrays as well.
