### ISSUE TITLE
Strange output of `binned_statistic_dd` with `statistic=sum` 

### ISSUE THREAD

**Issue by Bilokin** [scipy/scipy#14332]
Hello,

my issue is about the output of the `binned_statistic_dd` with `statistic=sum` argument, which is should be the same as the output of the numpy `histogram` function , but in some cases it is not. 
I found that if the given array contains values very close to the bin edge, for example 0.99999999 and bin edge is 1, then these entries migrate to the previous bin somehow. 

Could you please tell me if I do something wrong in the example below?

#### Reproducing code example:
```
import scipy.stats as st
import matplotlib.pyplot as plt
import numpy as np
arr = []
size = 8
for i in range(size):
    arr += [1-0.1**i]
bins = np.linspace(0,1,10)
hist_dd = st.binned_statistic_dd(arr, 
                              np.ones(len(arr)), bins=[bins],
                              statistic='sum')
plt.hist(arr, bins=bins, label='hist')
plt.plot(np.linspace(0.05,0.95,9), hist_dd[0], marker='o', label='binned_statistic_dd')
plt.legend()
plt.show()
```

#### Scipy/Numpy/Python version information:
1.7.0 1.21.0 sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)

**Comment by charlotte12l** [comment]
It is caused by these lines in `_bin_numbers(sample, nbin, edges, dedges)` (stats/_binned_statistics). It is used to put the values equal to the rightmost bin to be counted in the last bin, e.g. if  `arr` is `[0.0, 0.9, 0.99, 0.999, 0.9999, 0.99999,  0.999999, 0.9999999, 1]`,  then after np.digitize, `sampBin` is `[ 1  9  9  9  9  9  9  9 10]`. The following code can put the arr `1` from bin `10` to bin `9` as we expected, but because `decimal` is only 6. After np.round,  it would also put `0.9999999` from the right bin `9` to bin `8` mistakenly. 

```
    Dlen, Ndim = sample.shape

    sampBin = [
        np.digitize(sample[:, i], edges[i])
        for i in range(Ndim)
    ]
    # Using `digitize`, values that fall on an edge are put in the right bin.
    # For the rightmost bin, we want values equal to the right
    # edge to be counted in the last bin, and not as an outlier.
    for i in range(Ndim):
        # Find the rounding precision
        dedges_min = dedges[i].min()
        if dedges_min == 0:
            raise ValueError('The smallest edge difference is numerically 0.')
        decimal = int(-np.log10(dedges_min)) + 6
        # Find which points are on the rightmost edge.
        on_edge = np.where(np.around(sample[:, i], decimal) ==
                           np.around(edges[i][-1], decimal))[0]
        # Shift these points one bin to the left.
        sampBin[i][on_edge] -= 1

```
