### ISSUE TITLE
scipy.stats.lognorm.expect fails when ub set 'too high'

### ISSUE THREAD

**Issue by goduckie** [scipy/scipy#14347]
The result of `scipy.stats.lognorm.expect` becomes incorrect when the `ub` is set arbitrarily high.  The point at which it fails is related to the parameters, but I have not work out how.

```
  import scipy.stats
  ln = scipy.stats.lognorm( s=0.194, loc=0.0, scale=0.066)
  
  #as expected, small variation
  [ln.mean(),
  ln.expect(),
  ln.expect(lb=0, ub=np.inf),
  ln.expect(lb=0, ub=200)]
  
  >> [0.06725374751277746, 0.06725374751277748, 0.06725374751277748, 0.06725374751277752]

  #incorrect result
  ln.expect(lb=0, ub=201)

  >> 6.773470891792449e-09

```

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```
-->1.6.0 1.19.5 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by tirthasheshpatel** [comment]
From [this SO thread](https://stackoverflow.com/a/30913920/10177420), 

> The reason here is that your function is only very strongly peaked in a very small region of your integration region and is effectively zero everywhere else, quad never finds this peak and thus only see's the integrand being zero.

`expect` uses `integrate.quad` to calculate the expected values. It fails in this case because of a very narrow peak in your integration region. As the answer on SO suggests, you can pass a keyword argument `points` to integrate the peak region separately.

As far as distributions in SciPy are concerned, you can separately integrate at tails by passing a `points` keyword to the `expect` method (you can also pass other arguments that `integrate.quad` accepts by passing them as keyword arguments to the `expect` method):

```python
from scipy import stats

s = 0.194
scale = 0.066
ln = stats.lognorm( s=s, loc=0.0, scale=scale)
tol = 1e-10
res = ln.expect(lb=0, ub=201, points=[ln.ppf(tol), ln.isf(tol)])
print(res)
``` 

gives:

```none
0.06725374748942425
```

as you would expect. As this is not a bug in SciPy but a numerical issue, I think it can be safely closed. Feel free to reopen if you think it is a bug and/or needs to be discussed more.
