### ISSUE TITLE
Parameter curve fitting through a part of fixed points

### ISSUE THREAD

**Issue by huang229** [scipy/scipy#14366]
Through the parameter curve fitting of some fixed points. I would like to ask if there is an implementation interface for this function, thank you.

**Comment by rkern** [comment]
We ask that usage questions go to the [mailing list](https://www.scipy.org/scipylib/mailing-lists.html) or StackOverflow. You may need to describe your request more completely.

In particular, I don't know what you mean by "fixed points". We have, for example, [`curve_fit()`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html) which does nonlinear least squares optimization to fit parametric curves to data points, allowing some error. On the other hand, [`scipy.interpolate`](https://docs.scipy.org/doc/scipy/reference/interpolate.html) has several different ways to exactly fit spline curves to data points.

I am going to close this since this isn't a bug report or feature request. If you need some clarification about what I said, you can continue to reply to this closed issue, but I do recommend asking on the mailing list or StackOverflow. Thanks!

**Comment by huang229** [comment]
Thank you very much for your reply. 
I have 20 two-dimensional coordinates, labeled 0 to 19. Because there is a case that one variable x corresponds to more than one y value, we have to use the curve fitting method with point sequence requirement. And some of these points are fixed points, which must pass through, and the other points can not pass through. I didn't find the corresponding function method.
The order of 20 points is as follows:
 (x,      y,  label)     label=1 Indicates that the point is a fixed point.
1454 1213 0 
1427 1190 0
1378 1131 0 
1327 1092 0 
1288 1080 0 
1229 1064 0 
1153 1051 1 
1153 1051 1 
1207 1046 0 
1290 1049 0 
1339 1049 0 
1383 1041 0 
1415 1041 0 
1454 1062 0 
1491 1077 1 
1491 1077 1 
1474 1085 0 
1469 1121 1 
1484 1154 0 
1498 1190 1
