### ISSUE TITLE
`ttest_ind` for two sampled distributions with the same single unique value

### ISSUE THREAD

**Issue by jiajiexiao** [scipy/scipy#14418]
Hi Scipy development community, I am observing some wired behaviors/results when calling `scipy.stats.ttest_ind` to conduct t-tests for two sampled distributions with the same unique single value. For example, input 1 is a vector with 10 values of 0.01 (i.e. `[0.01]*10`), while input 2 is a vector with 20 values of 0.01 (i.e. `[0.01]*20`). I expect `scipy.stats.ttest_ind` to return `nan` values for the `statistic` and `pvalue` as the t static is undefined due to zero variances in those sampled distributions. However, I am seeing some interesting different results as shown in the code example below:

#### Reproducing code example:

``` python
>>> import scipy; print(scipy.__version__)
1.6.3
>>> from scipy.stats import ttest_ind
>>> ttest_ind([3.1086244592868925e-09]*693, [3.1086244592868925e-09]*139)
Ttest_indResult(statistic=-5.745532660713074, pvalue=1.2861485699869727e-08)
>>> ttest_ind([3.10862446e-09]*693, [3.10862446e-09]*139)
Ttest_indResult(statistic=nan, pvalue=nan)
>>> ttest_ind([3.1086244592868925e-09]*693, [3.1086244592868925e-09]*693)
Ttest_indResult(statistic=0.0, pvalue=1.0)
>>> ttest_ind([3.1086244592868925e-09]*139, [3.1086244592868925e-09]*139)
Ttest_indResult(statistic=0.0, pvalue=1.0)
>>> ttest_ind([1.0000e-01]*10, [1.0000e-01]*10)
Ttest_indResult(statistic=nan, pvalue=nan)
>>> ttest_ind([1.0000e-02]*10, [1.0000e-02]*10)
Ttest_indResult(statistic=0.0, pvalue=1.0)
>>> ttest_ind([0.04]*10, [0.04]*10)
Ttest_indResult(statistic=0.0, pvalue=1.0)
>>> ttest_ind([0.04]*10, [0.04]*30)
Ttest_indResult(statistic=-5.338539126015656, pvalue=4.591739995593669e-06)
>>> ttest_ind([0.06]*10, [0.06]*30)
Ttest_indResult(statistic=0.0, pvalue=1.0)
>>> ttest_ind([0.06]*10, [0.06]*10)
Ttest_indResult(statistic=0.0, pvalue=1.0)
```

I wonder if anyone can help me understand the results in the above example better. Or should I suspect if there is any bug? 

#### Scipy/Numpy/Python version information:
``` python
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```
--> 
``` python
1.6.3 1.18.5 sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
The results produced by `ttest_ind` here are not all correct, so you can say there is a bug in that it is not very careful with degenerate input. There are a lot of stats functions like this for which edge cases like this produce unusual results. When implemented directly, the usual formulas don't always play well with finite precision arithmetic. These are not necessarily cause for concern for more typical inputs. I'm curious whether you ran into these cases with actual data or if you were just trying to test the function?

**Comment by jiajiexiao** [comment]
@mdhaber many thanks for your quick reply and investigation. This makes a lot of sense now. I encountered the issue as described above in some real applications of actual data. I was confused about the inconsistent outputs from the `ttest_ind` thus shared minimum working examples that can reproduce the same wired behaviors. 

Yeah, that is a harder question about how we could add a patch. Even Python itself has [floating-point errors ](https://docs.python.org/3/tutorial/floatingpoint.html). The patch you described seems to me an effective and probably the easiest way to ensure the `nan` results we want since there is no need to be dependent on the third party. I am happy to commit such a patch if needed.

**Comment by mdhaber** [comment]
> I encountered the issue as described above in some real applications of actual data.

You could also consider a permutation test using the difference between means as the statistic. In the cases above, the distance between means would be 0, and the p-value (probability of an equally extreme value of the statistic by chance under the null hypothesis that all the observations were randomly sampled from the same underlying distribution) would be 1.

> Yeah, that is a harder question about how we could add a patch.

I don't necessarily recommend the patch I wrote above because yes, this is one manifestation of a more general problem with floating point errors. Even if we handle the case of exact equality, there is a family of edge cases that this doesn't cover. For instance:
```
> ttest_ind([x, y]*10, [x, y]*17)
Ttest_indResult(statistic=-1.4239631980538456e-15, pvalue=0.948)
```
should return 
```
Ttest_indResult(statistic=0.0, pvalue=1.0)
```
Testing for exact equality of sample doesn't cover that. Maybe there is a simple fix for all such cases, maybe not. In any case, because this is part of a larger family of problems, I hesitate to implement a partial fix.

If you'd like to help with this, I'd suggest searching our repo on GitHub for similar problems. I don't remember whether gh-13254 will help, but it's a similar sort of issue, and I imagine there are others.
