### ISSUE TITLE
percentileofscore and multidimensional array

### ISSUE THREAD

**Issue by pmh722** [scipy/scipy#14421]
scipy.stats.percentileofscore seems to implicitly assume that input array "a" is a one dimensional vector. When it encounters a multidimensional matrix input, it seemingly calculates the percentile of each dimension, and SUMS them, resulting in a percentile that is potentially greater than 100? 

This behaviors surprised me. I would have expected either 1) broadcasting (get back an array of percentiles), 2) reduction (get back the percentile as if the array were one dimensional), or 3) an error. My vote would be for (1), but any would be preferable to summing the percentiles.

#### Reproducing code example:

```
import numpy as np
from scipy import stats
foo = np.array([[1,2,3,4],[2,3,4,5]])
bar = stats.percentileofscore(foo, 2)
print(bar) #125
```

**Comment by rkern** [comment]
The bug is that the denominator is computed as `n = len(a)`. If it were just `n = a.size`, I think the rest of the code would just work.

**Comment by rkern** [comment]
Well, as Option 2, at any rate.

**Comment by rkern** [comment]
Option 1 shouldn't be too hard, either. The computations all rely `np.count_nonzero()`, which accepts an `axis=` argument. You could probably just add `axis=None` to `percentileofscore()` and pass it through, computing the correct `n` in each case.

Since its compatriot function `scoreatpercentile()` already takes an `axis` argument, we should probably do that here too.

**Comment by mdhaber** [comment]
Vectorization of `percentileofscore` is already going on in gh-13572.
I would appreciate some help with a decision about `scoreatpercentile` in gh-13382.

**Comment by mdhaber** [comment]
We'll address this as part of gh-14651.
