### ISSUE TITLE
One bug, one mistake and one refactorization proposal for the Secant method implemented in scipy.optimize.zeros.py

### ISSUE THREAD

**Issue by GuidoTerraBleeker** [scipy/scipy#14486]
My issue is about the implementation of the Secant method in scipy.optimize.zeros.py (within the newton() function).

I am new to GitHub and versioning/pull requests etcetera, so please accept my apologies if I bring this in the wrong way. I am in the process of writing a tutorial on using several scipy submodules (for a course I teach on Scientific Programming) and noticed that `scipy.optimize.root_scalar()` produced different results than the Secant method that I had implemented myself to illustrate the steps. Even worse: `.root_scalar()` reported that the method converged even for the example in which it clearly diverges to -infinity. Hence I took a look at the source code (downloaded from 
https://github.com/scipy/scipy/blob/master/scipy/optimize/zeros.py on Tuesday, July 27, 2021).

1. I found the bug erroneously setting `sol.flag` to `'converged'`: this seems to be a basic typo/copy-past error: `_ECONVERGED` should be replaced by `_ECONVERR` on line 344.
2. I also saw that the code includes some tests on `abs(q0)` versus `abs(q1)`. On lines 346-349, these tests seem to be completely redundant as the formulas used in either case are completely equivalent and should yield the same results (up to truncation errors).
3. On lines 330-331 (which are the cause of the difference between my results and those from `.root_scalar()`), I do see what the programmer was trying to do, but he/she seems to have made a mistake: I'm pretty sure the condition should be `if abs(q1) > abs(q0):` instead of `if abs(q1) < abs(q0):` to make `(p1,q1)` be the "better" (in the sense that `q1` is closer to zero) pair of the two initial guesses. However, if this correction/reordering would really be appropriate (*which I don't think it necessarily is in general; In fact, I can come up with a scenario in which it would be worse*), it would make more sense to implement that correction within the iteration loop (choosing the one(s) from `q0`, `q1` and possibly the newest `f(p)` that are closest to zero). I may be wrong, but I guess that's what the programmer had in mind with lines 346-349, but as I wrote above, those lines seem senseless anyway (*unless it is really just about truncation errors; I'm not really an expert on that, but as far as I can tell, the extra test is not worth it*).

#### Reproducing code example:

A minimal example illustrating the most fundamental bug is the following:
```
def lhs(x):
    return x * np.exp(-x*x) - 0.07

optim.root_scalar(lhs, method='secant', x0 = -0.15, x1 = 1.0 )
```

#### Error message:

Actually, the issue is not so much that I get an error message, but rather that I don't. For the initial conditions as specified, the Secant method is supposed to diverge to -infinity. Indeed, the `sol.root` that is reported at `-288782083.8727057` is in line with this divergence. However, `sol.flag` is erroneously set to `'converged'` and `sol.converged` to `True`.

```
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\zeros.py:343: RuntimeWarning: Tolerance of -577564088.0186934 reached.
  warnings.warn(msg, RuntimeWarning)
Out[33]: 
      converged: True
           flag: 'converged'
 function_calls: 10
     iterations: 9
           root: -288782083.8727057
```

#### Scipy/Numpy/Python version information:

```
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

#### Proposed solution:
My proposal is:
1. correct the bug on line 344, replacing `_ECONVERGED` by `_ECONVERR`
2. remove all tests relating to `abs(q0)` versus `abs(q1)` as they just take up time and don't necessarily improve performance, replacing the formula for the next iterate by one that applies in either case.

I have already made these changes and include the relevant section below, so someone could copy-paste it right into the source code, replacing lines 317-356 (*I could also provide a ZIP-file with the code already inserted into zeros.py, and some of my tests, if that would be more convenient*):

```
        # Secant method
        # validate input argument x1
        if x1 is not None:
            if x1 == x0:
                raise ValueError("x1 and x0 must be different")
            p1 = x1
        else: # or use default shift
            eps = 1e-4
            p1 = x0 * (1 + eps)
            p1 += (eps if p1 >= 0 else -eps)
        # evaluate function values q0,q1 at p0,p1
        q0 = func(p0, *args)
        funcalls += 1
        q1 = func(p1, *args)
        funcalls += 1

        for itr in range(maxiter):
            if q1 == q0:
                # Exceptional case: failure to converge due to equal func vals
                # (also catches divergence to infinity or NaN)
                if p1 != p0:
                    msg = "Tolerance of %s reached." % (p1 - p0)
                    if disp:
                        msg += (
                            " Failed to converge after %d iterations, value is %s."
                            % (itr + 1, p1))
                        raise RuntimeError(msg)
                    warnings.warn(msg, RuntimeWarning)
                p = (p1 + p0) / 2.0
                return _results_select(
                    full_output, (p, funcalls, itr + 1, _ECONVERR))
            else:
                # Normal case: next iteration step
                p = p1 + q1 * (p1 - p0) / (q0 - q1)

            # converged to solution within tolerance:
            if np.isclose(p, p1, rtol=rtol, atol=tol):
                return _results_select(
                    full_output, (p, funcalls, itr + 1, _ECONVERGED))

            # prepare for next iteration step, renaming new iterates as current
            p0, q0 = p1, q1
            p1 = p
            q1 = func(p1, *args)
            funcalls += 1
```

P.S. Thinking about it further: I can imagine one reason why the "redundant" check in lines 346-349 might be on purpose after all: because of the effect of truncation errors when dividing by the small number `q0 - q1` (I am a mathematician, not a computer scientist, so truncation errors are not really my field of expertise). However, with the (few) tests) that I did, I did not see any significant differences as a result of changing this line. In the `_array_newton()` function `p = p1 + q1 * (p1 - p0) / (q0 - q1)` is used as well.

In any case, the first point, replacing `_ECONVERGED` by `_ECONVERR` on line 344, still stands. And the reordering of the initial guesses on line 330-331, doesn't necessarily improve things in general at all, by one iteration only at best, so that had better be left to the caller of the method anyway, IMHO.

**Comment by tupui** [comment]
Thanks for the detailed report @GuidoTerraBleeker! This might explain why in #14453 the convergence was also wrongly reported.

**Comment by GuidoTerraBleeker** [comment]
> Thanks for the detailed report @GuidoTerraBleeker! This might explain why in #14453 the convergence was also wrongly reported.

Thanks for the feedback. And yes, it looks like that issue in #14453 is caused by the same thing. I'm curious to hear the developer's take on this.

**Comment by AvivBarnea** [comment]
`root_scalar` also wrongly converges on non-zero constant functions. For example:
```python
>>> root_scalar(lambda x: 5., x0=6., x1=8.)
      converged: True
           flag: 'converged'
 function_calls: 2
     iterations: 1
           root: 7.0
```
It does, however raise a `RuntimeWarning`, while reporting erroneously a `converged` flag.

**Comment by mhvwerts** [comment]
This issue is perhaps related to issue #6379, about a problem with the secant method in `scipy.optimize.newton()`. I am not sure if `scipy.optimize.root_scalar()` discussed here uses the same code as `scipy.optimize.newton()`. 
Both routines offer the secant method and the Newton method for root finding, which is somewhat confusing to me.

**Comment by mdhaber** [comment]
@GuidoTerraBleeker I'd suggest including links to the lines of code because line numbers change as the code is updated.

![image](https://user-images.githubusercontent.com/6570539/209464765-0a189e54-fe86-4d38-bf19-6b52e59bfbcc.png)

---

For 1, I believe the lines in question are:
https://github.com/scipy/scipy/blob/de80faf9d3480b9dbb9b888568b64499e0e70c19/scipy/optimize/_zeros_py.py#L337-L351

I agree that the method should terminate with an error status if the two function values are identical at different argument values. What should happen when the two arguments values are nearly identical probably depends on the resolution of gh-6379.

For 2, I think the lines in question are:
https://github.com/scipy/scipy/blob/de80faf9d3480b9dbb9b888568b64499e0e70c19/scipy/optimize/_zeros_py.py#L353-L356
Looking at git blame, I traced this back to https://github.com/scipy/scipy/pull/8890/files#r199328023. It is a finite precision arithmetic thing, so unless it can be shown that the author's logic was incorrect, we should not change this.

For 3, I think the lines in question are:
https://github.com/scipy/scipy/blob/de80faf9d3480b9dbb9b888568b64499e0e70c19/scipy/optimize/_zeros_py.py#L337-L338

This was also added in gh-8890. Presumably there was a reason for it. It was written by a maintainer and reviewed by a maintainer and another contributor. Without strong evidence that it should be removed, I don't think it is a sufficient reason to keep this issue open. The methods implemented in SciPy need to be based on published work, but they don't always follow them exactly; sometimes enhancements are added. You're welcome to contribute a PR with the change, but if I were reviewing it, I would ask for evidence that it is substantially detrimental to users.

@mhvwerts This seems different from gh-6379. That example returns because of:
![image](https://user-images.githubusercontent.com/6570539/209464767-440434ec-3e0f-44a4-a414-71d2b2b9f199.png)

@AvivBarnea thanks for that MWE. That is another instance of this problem.

**Comment by mdhaber** [comment]
@pvanmulbregt Thanks for your time recently! I thought I should also bring this issue to your attention. Please see the top post (https://github.com/scipy/scipy/issues/14486#issue-954027556).  
I'm addressing item 1 in gh-17660 (and it would be great if you could review that). I suggested in my previous post that items 2 and 3 don't need to be changed to close this issue, but your opinion as the author would be appreciated.
