### ISSUE TITLE
scipy.signal.filter_design.zpk2sos doctests fail (values different in arrays)

### ISSUE THREAD

**Issue by ThomasLecocq** [scipy/scipy#14584]
My issue is about the doctests of ``scipy.signal.filter_design.zpk2sos`` which fail.

The issue was identified when running the CI on ObsPy, for which we had backported ``zpk2sos`` originally (https://github.com/obspy/obspy/issues/2865), it didn't happen with scipy 1.6.3 and it appeared first with 1.7.0. 

#### Error message:
Running doctests on scipy 1.7.0 installed via conda on Win64:

```python
**********************************************************************
File "C:/Users/thlec/Miniconda3/envs/ms2/Lib/site-packages/scipy/signal/filter_design.py", line 1379, in zpk2sos
Failed example:
    sos[:, :3]
Expected:
    array([[ 0.0014154 ,  0.00248707,  0.0014154 ],
           [ 1.        ,  0.72965193,  1.        ],
           [ 1.        ,  0.17594966,  1.        ]])
Got:
    array([[0.0014152 , 0.00248677, 0.0014152 ],
           [1.        , 0.72976874, 1.        ],
           [1.        , 0.17607852, 1.        ]])

**********************************************************************
File "C:/Users/thlec/Miniconda3/envs/ms2/Lib/site-packages/scipy/signal/filter_design.py", line 1389, in zpk2sos
Failed example:
    sos[:, 3:]
Expected:
    array([[ 1.        , -1.32543251,  0.46989499],
           [ 1.        , -1.26117915,  0.6262586 ],
           [ 1.        , -1.25707217,  0.86199667]])
Got:
    array([[ 1.        , -1.32544025,  0.46989976],
           [ 1.        , -1.26118294,  0.62625924],
           [ 1.        , -1.2570723 ,  0.8619958 ]])
```

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.7.0 1.21.1 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
```

**Comment by ThomasLecocq** [comment]
Would this be linked to changes in ``ellip`` ? https://github.com/scipy/scipy/pull/12438 ?

**Comment by roryyorke** [comment]
This is very is likely due to #12438 which changed the elliptical coefficient computation.  I've plotted the frequency responses of the two filters in your second comment, and they're essentially identical (not too surprising, since the zpk values are very close).

I'm afraid I didn't pick this up at the time; I guess doctests are not part of the Scipy CI?  I just ran

```
python -m doctest $(python -c 'from scipy.signal import filter_design; print(filter_design.__file__)')
```

and I got 262 failures with Scipy 1.6.3, including a whitespace difference in this very zpk2sos example (due to newer numpy?  I've got 1.20.3 in that venv), so I guess the doctests are a bit out of date.  zpk2sos doctest failure:

```
File "/home/rory/miniconda3/envs/work/lib/python3.9/site-packages/scipy/signal/filter_design.py", line 1378, in filter_design.zpk2sos
Failed example:
    sos[:, :3]
Expected:
    array([[ 0.0014154 ,  0.00248707,  0.0014154 ],
           [ 1.        ,  0.72965193,  1.        ],
           [ 1.        ,  0.17594966,  1.        ]])
Got:
    array([[0.0014154 , 0.00248707, 0.0014154 ],
           [1.        , 0.72965193, 1.        ],
           [1.        , 0.17594966, 1.        ]])
```

FWIW, most of the doctest failures are to do with plotting, where doctest expects "nothing", but is surprised by reprs of various Matplotlib objects.

Anyway, I think the doc test should be fixed by either updating the results to match the 1.7.1 values; or, perhaps better, by replacing the `ellip` call with specific z, p, k arrays.

My final two  cents: if doctests aren't part of Scipy CI, I can't see them staying current.

**Comment by tylerjereddy** [comment]
> My final two cents: if doctests aren't part of Scipy CI, I can't see them staying current.

I think you may be misunderstanding how we test our documentation perhaps, or maybe you do understand but you are referring to `doctest` proper instead of what we do?

We, and many other scientific Python projects, have shims around the conventional doctest machinery for a variety of reasons, one of which is the whitespace nightmare you touch on, but there are many other reasons.

If you'd like to see how we test our docs you can look at `tools.xrage/refguide_check.py`. Indeed, the explanation at the start of that module includes the statement:

> ... [we do not aim to have scipy docstrings doctestable!] ...

That said, we do take the quality and ability to reliably execute SciPy docstrings pretty seriously I'd say, and certainly is running in CI (`git grep -E 'refguide'`)

**Comment by ev-br** [comment]
> python -m doctest $(python -c 'from scipy.signal import filter_design; print(filter_design.__file__)')

You want `python runtests.py --refguide-check -s signal`.

**Comment by roryyorke** [comment]
Ah-ha!  Thanks for taking the time to explain, I wasn't aware of how Scipy tested documentation.

I was referring to Ye Olde doctest.  After looking at the ObsPy issue, my guess is that ObsPy copies bits of Scipy code into their project, and then run doctest on their whole codebase.

Is it worth updating the doctest example in Scipy?

**Comment by ThomasLecocq** [comment]
Thanks a bunch for your comments, it's useful for me to understand the underlying test machinery !

>After looking at the ObsPy issue, my guess is that ObsPy copies bits of Scipy code into their project, and then run doctest on their whole codebase.

This is exact, we originally copied (back ported) the function in order to support (very very) old versions of scipy.

This said, indeed, the values returned for the example in the docstring are different due to changes in #12438 ; as @roryyorke said, in the end the filter constructed from the z, p & k values is very similar (as their respective values are identical down to the 4th or 5th decimal). So I suppose updating the output values in the docstring is the way to go ?

**Comment by tylerjereddy** [comment]
> So I suppose updating the output values in the docstring is the way to go ?

I think Warren just did what you suggested--let us know if you still have issues with the latest version on `main`.
