### ISSUE TITLE
BUG: Unable to install h5py when scipy 1.7.1 egg file is present

### ISSUE THREAD

**Issue by winash12** [scipy/scipy#14652]
### Reproducing Code Example

I am installing h5py-3.4 using python3.8 setup.py install on Ubuntu 20.04 LTS and I am running into this issue - https://github.com/h5py/h5py/issues/1955 . When I remove pythran and scipy 1.7.1 egg files the installation of h5py-3.4 proceeds just fine. There maybe an issue of compatibility I am not entirely sure. For now it is not a problem since all are installed fine by just ordering the install in this way - a) Install Cython b) Install numpy c) install h5py d) install pythran and scipy . But I would like to know if there is a solution or a bug on your side.

### Error message

```shell
File "/usr/local/lib/python3.8/dist-packages/pythran-0.9.12.post1-py3.8.egg/pythran/tables.py", line 4547, in save_arguments
    save_arguments(module_name + (elem,), signature)
  File "/usr/local/lib/python3.8/dist-packages/pythran-0.9.12.post1-py3.8.egg/pythran/tables.py", line 4551, in save_arguments
    themodule = __import__(".".join(module_name))
  File "/usr/local/lib/python3.8/dist-packages/scipy-1.7.1-py3.8-linux-x86_64.egg/scipy/special/__init__.py", line 643, in <module>
    from . import _ufuncs
  File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

### SciPy/NumPy/Python version information

1.7.1/1.21.2/3.8

**Comment by rgommers** [comment]
https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp does explain it. It's unrelated to Pythran or SciPy, it's due to building with a certain numpy version and then finding another version at runtime. Not entirely clear which combination of versions is the issue, but it has to do with https://github.com/numpy/numpy/pull/16938#issuecomment-789987915.

I'll close this, since there's nothing we can do about it here. Just following the advice in the SO issue will work. Thanks for the report @winash12
