### ISSUE TITLE
Issue: .rvs failing due to brentq

### ISSUE THREAD

**Issue by aknewlon** [scipy/scipy#14679]
### Please describe your issue.

I have created a distribution using rv_continuous. I am attempting to use .rvs to get a random variate from this distribution. However, it keeps failing with error message "ValueError: f(a) and f(b) must have different signs" coming from the call to brentq in _ppf_single. I understand the brent method and have read through the source code, but am unsure how to resolve this issue since I cannot edit .rvs to avoid this error.

**Comment by rkern** [comment]
If you want to customize the random number generation for your distribution, you [provide a method named `_rvs()`](https://docs.scipy.org/doc/scipy-1.7.0/reference/generated/scipy.stats.rv_continuous.html) (much like the `_pdf()` and other methods that you supplied to define your distribution). If you are using scipy 1.7.0+, please take a look at [`NumericalInverseHermite`](https://docs.scipy.org/doc/scipy-1.7.0/reference/generated/scipy.stats.NumericalInverseHermite.html) for a good, efficient procedure to implement `_rvs()` without having to do much more than you already have.

**Comment by mdhaber** [comment]
If you try to use `NumericalInverseHermite` and run into trouble with your distribution's `ppf`/`isf` methods, which are used once to figure out the domain, please see [here](https://github.com/scipy/scipy/issues/14568#issuecomment-906602863).

From the information given, this sounds like a usage question rather than a bug report. Unfortunately, we don't have the bandwidth to support those here. Please consider posting on stackoverflow for that. In the meantime, I'm closing the issue, but if you do have a bug or enhancement (maybe documentation) request once you resolve your issue, please re-open.
