### ISSUE TITLE
ENH: let lagrange().coefficients have predictable length

### ISSUE THREAD

**Issue by nschloe** [scipy/scipy#14681]
### Is your feature request related to a problem? Please describe.

When creating a Lagrange polynomial, the number of points generally equals the polynomial order+1, equals the number of the polynomial coefficients:
```python
from scipy.interpolate import lagrange

x = [0.0, 1.0]
y = [0.5, 0.7]
poly = lagrange(x, y)
print(poly.coeffs)
```
```
[0.2 0.5]
```
If the Lagrange polynomial happens to be of lesser order, the number of coefficients reduces, too:
```python
# otherwise same as above
y = [0.5, 0.5]
```
```python
[0.5]
```
This poses problems in various applications, e.g., when trying to feed multiple Lagrange polynomials into [PPoly](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.PPoly.html#scipy.interpolate.PPoly). 

### Describe the solution you'd like.

It'd be great if the number of coefficients could be set to a fixed value, e.g., 2:
```python
poly = lagrange(x, y)
print(poly.coeffs(2))
```
```python
[0.0, 0.5]
```

**Comment by ev-br** [comment]
It would be nice indeed, but I don't believe this is doable. Trimming zero coefficients seems to be a feature of `np.poly1d` objects:

```
In [1]: from numpy import poly1d

In [2]: p1 = poly1d([0.5])

In [3]: p2 = poly1d([0, 0.5])

In [4]: p2.coef
Out[4]: array([0.5])

In [5]: p1 == p2
Out[5]: True
```

Looking at the source, https://github.com/numpy/numpy/blob/v1.22.0/numpy/lib/polynomial.py#L1245, there is this `trim_zeros` call, which comes from https://github.com/numpy/numpy/blob/v1.22.0/numpy/lib/function_base.py#L1776 --- and it just converts `[0, 0.5]` from your example back to `[0.5]`.

So what are the options for `scipy.interpolate.lagrange` then:

- stop depending on `np.poly1d`, change the class of the object `largange` constructs. This is certainly tempting :-), but it's a backcompat break and it's certainly too late for this in the lifecycle of this function. 
- replace `lagrange` with a better implementation and interface. In principle doable, with a normal deprecation cycle: add a new function, deprecate the old one, remove after two releases. I personally think it's too much hassle, but if you want to do the legwork, fine. cross-ref https://github.com/scipy/scipy/issues/6173.
- add an extra attribute to the return value of `lagrange`, and keep the zeros in it. This is essentially what https://github.com/scipy/scipy/pull/14774 suggested to do. Technically, this is very simple and straightforward, but ISTM this sort of preprocessing --- essentially a loop over the polynomials from the OP example --- can be more readily implemented in user code, e.g just before feeding  coefficients into PPoly. 
This is IMO safer and more straightforward overall then tacking it onto `lagrange(x, y)` result and risking inconsistencies down the line because no user code knows about this attribute and nobody preserves it in poly1d operations etc.

All in all, let's keep track of possible rewrites of `lagrange` in gh-6173 and close this request as a wontfix.
