### ISSUE TITLE
BUG: Incorrect residual graph in scipy.sparse.csgraph.maximum_flow

### ISSUE THREAD

**Issue by navyamehta** [scipy/scipy#14731]
### Describe your issue.

Consider the reproducing example below. This seems to be the incorrect residual graph from the flow. 1-2 has a 5 capacity, 2-3 has a 1 capacity and 3-0 has a 1 capacity. So, while the flow_value is 1 from 1-0 (which is correctly returned), the residual for 1-2 should be 4. Any insight on this is appreciated! 

### Reproducing Code Example

```python
from scipy.sparse.csgraph import maximum_flow
from scipy.sparse import csr_matrix
matrix = [[0,10,10,0],[0,0,5,0],[0,0,0,1],[1,0,0,0]]
obj = maximum_flow(csr_matrix(matrix), 1, 0)
obj.residual.toarray()
```

### Error message

```shell
array([[ 0,  0,  0, -1],
       [ 0,  0,  1,  0],
       [ 0, -1,  0,  1],
       [ 1,  0, -1,  0]], dtype=int32)
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)

**Comment by Kai-Striega** [comment]
Version 1.8 will add an additional ``method`` argument. The residual matrix is the same for both methods. Perhaps some who has worked on this could take a look?

**Comment by fuglede** [comment]
You're right, this seems like an instance of incorrect, or at the very least very misleading, naming: The map you're looking at is the flow, and the residual network would be the one whose capacity is the difference between the original capacities and the flow,

```
>>> matrix - obj.residual.toarray()
array([[ 0, 10, 10,  1],
       [ 0,  0,  4,  0],
       [ 0,  1,  0,  0],
       [ 0,  0,  1,  0]])
```

A nice little sanity-check being that this one has no flow:

```
>>> maximum_flow(csr_matrix(matrix - obj.residual.toarray()), 1, 0)
MaximumFlowResult with value of 0
```

So that's pretty confusing indeed. Maybe enough to warrant a renaming + deprecation cycle?
