### ISSUE TITLE
BUG: wrong weights of the 7-point gauss rule in QUADPACK: dqk15w.f

### ISSUE THREAD

**Issue by adamadanandy** [scipy/scipy#14807]
### Describe your issue.

QUADPACK: dqk15w.f: line #103, wrong weights of the 7-point gauss rule
The weights of wg should be the same as "dqk15.f":
#103: "0.3818300505051889d+00", should be changed to "0.3818300505051189d+00".
This is a historical typo that commonly exists in every code that embeds netlib-quadpack, which does not necessarily produce an actual numerical error in the calculation of the error of the quadrature using the Gauss-Kronrod rule.

### Reproducing Code Example

```python
c     dqk15: #80-#83
      data wg  (  1) / 0.1294849661 6886969327 0611432679 082 d0 /
      data wg  (  2) / 0.2797053914 8927666790 1467771423 780 d0 /
      data wg  (  3) / 0.3818300505 0511894495 0369775488 975 d0 /
      data wg  (  4) / 0.4179591836 7346938775 5102040816 327 d0 /
c     dqk15i: #97-#104
      data wg(1) / 0.0d0 /
      data wg(2) / 0.1294849661 6886969327 0611432679 082d0 /
      data wg(3) / 0.0d0 /
      data wg(4) / 0.2797053914 8927666790 1467771423 780d0 /
      data wg(5) / 0.0d0 /
      data wg(6) / 0.3818300505 0511894495 0369775488 975d0 /
      data wg(7) / 0.0d0 /
      data wg(8) / 0.4179591836 7346938775 5102040816 327d0 /
c     dqk15w: #101-#103
      data wg(1),wg(2),wg(3),wg(4)/
     *     0.1294849661688697d+00,    0.2797053914892767d+00,
     *     0.3818300505051889d+00,    0.4179591836734694d+00/
```

### Error message

```shell
no error message
```

### SciPy/NumPy/Python version information

Any Version

**Comment by adamadanandy** [comment]
Submitted pull request: #14808

**Comment by ev-br** [comment]
Is there a reference for the values or a discussion (as you say it's a historic typo, it should have surely been discussed somewhere?)

**Comment by andyfaff** [comment]
@ev-br the locations and weights of a 7-point Gaussian quadrature are:
```
>>> import scipy.special
>>> l, w = scipy.special.p_roots(7)
>>> print(w[2])
0.38183005050511876
```
This would indicate that there's a typo in the existing code.

**Comment by andyfaff** [comment]
https://www.advanpix.com/2011/11/07/gauss-kronrod-quadrature-nodes-weights/#Tabulated_Gauss-Kronrod_weights_and_abscissae tabulates the GK7-15 to 34 dp.

**Comment by ilayn** [comment]
@langou I know this is a stretch for you but is there a way to actually fix this upstream?

**Comment by adamadanandy** [comment]
> Is there a reference for the values or a discussion (as you say it's a historic typo, it should have surely been discussed somewhere?)

@ev-br 
The textbook written analytic expression of points of Gauss-Legendre quadrature is given by the zero points of Legendre polynomials, denoted by P_n(x), with weights given by:

$$w_i=2(1-x_i^2)^{-1}P^\prime_n(x_i)^{-2}$$

with x_i the i-th root of P_n(x).
Here is the solution of weight, calculated with n=7, with 100 sig. fig., (2nd term is the one with typo):

```
0.4179591836734693877551020408163265306122448979591836734693877551020408163265306122448979591836734694,
0.3818300505051189449503697754889751338783650835338627347510834510307055464341297083486846593440448015,
0.2797053914892766679014677714237795824869250652265987645370140326936188104305626768132409429011976188,
0.1294849661688696932706114326790820183285874022599466639772086387246552349720423087156254181629208451.
```

**Comment by langou** [comment]
Thanks for letting me know of the issue in Netlib/Quadpack. 

To follow up on ``how do we know if these are the good numbers``, the weights were also given with 33 decimals and were ``evaluated with 80 decimal digit arithmetic by l. w. fullerton,
c bell labs, nov. 1981.`` See: https://www.netlib.org/quadpack/dqk15.f
Also, the QK15, DQK15, QK15I and DQK15I subroutines are using the correct value.

I'll try to fix the DQK15W subroutine available 
http://www.netlib.org/quadpack/dqk15w.f
and give an update when done.

For information, the 32-bit version of the code, QK15W, has the same issue:
http://www.netlib.org/quadpack/qk15w.f
So I'll correct that as well.

Julien.

**Comment by langou** [comment]
As a side comment, I must say that I am fascinated by these typos. 

There is a typo as well in ARPACK96/SRC/zgetv0.f line 368 where the number sqrt(2)/2 is written as 0.717. (Instead of 0.7071.) (Same thing for s, c, and d precision.)

Then this number, I believe, was passed on to PETSc, and in version 3.5.2, 
petsc-3.5.2/src/ksp/ksp/impls/gmres/borthog2.c
line 90, PETSc was using 1.0286. (which, I believe, was coming from 0.717 through some algebra like (2*0.717)**2/2   ). However (2*( sqrt(2)/2 ) )**2/2 should have simply been 1. So PETSc was using 1.0286 when it should have been using 1.

I just checked and PETSc 3.16.0 is now correctly using 1. (I reported the issue a while back to the PETSc developer.)

Anyhow, these typos fascinate me.

**Comment by charris** [comment]
> Anyhow, these typos fascinate me.

Reminds me of an incorrect citation (Herzberg something) that was propagated in many papers.  It seems that none of the authors actually consulted the original work, they just copied the citation :)

**Comment by langou** [comment]
The two files below should have been correctly updated. Feel welcome to check. (Do not forget to refresh the browser.)
http://www.netlib.org/quadpack/qk15w.f
http://www.netlib.org/quadpack/dqk15w.f
Thanks to @julielangou for the upload.
Happy to do more modifications as needed. Just let us know. Thanks for the bug report. Julien.

**Comment by ilayn** [comment]
Thanks a lot @langou @julienlangou. We really appreciate the swift action.

**Comment by ev-br** [comment]
OK, I merged gh-14808 with the fix, thanks all for spotting the typo, for verifying the fix and for upstreaming the fix (great to know that there *is* upstream for netlib/quadpack!)

Speaking of typos, I wonder how you spotted it @adamadanandy :-)

**Comment by adamadanandy** [comment]
I was trying to use the quadpack to calculate the Fourier transformation with sin and cos as weight function simultaneously. In the mean time, I found that the quadpack and cquadpack gives different error estimation, which leads me to find this typo.
PS. The difference in the error estimation of quadpack and cquadpack is still a mystery, does anyone have some idea?
PS. Does any one know any numerical quadrature library that can perform the numerical integral for complex integrands? I'm eagerly searching for these libraries, and many thanks.

**Comment by adamadanandy** [comment]
> > Does any one know any numerical quadrature library that can perform the numerical integral for complex integrands? I'm eagerly searching for these libraries, and many thanks.
> 
> https://pypi.org/project/quadpy/

Many thanks!

**Comment by ilayn** [comment]
@certik Would it be possible for quadpack to live in https://github.com/fortran-lang ? 

@langou Would you be interested in allowing quadpack to live there? 

Please feel free to say no, since I'm just checking.

**Comment by ilayn** [comment]
Ah I knew it was somewhere there relevant discussion https://github.com/fortran-lang/fpm-registry/issues/43

**Comment by langou** [comment]
"@langou Would you be interested in allowing quadpack to live there?" Thanks for asking. I do not have a say in the matter. (I cannot allow, I cannot not allow.) I have access to netlib.org and can help, but these are not my software. That being said, I think the four authors would be happy to see the software strive and continue its life. The software was written at a time when COPYRIGHT and LICENSE were not common. So it is understandable that the software does not have appropriate COPYRIGHT and LICENSE. I think we have to defer to what we think the authors would have wanted. I think they wanted the software in the public domain and did not have the tool to make this happen as we would do nowadays. If we want to remove QUAPACK from netlib so that it lives somewhere else, I would have to ask the netlib folks what they think about this, please follow up with me if you want me to ask. In the meantime, I am happy to push updates to the netlib code.

**Comment by xecej4** [comment]
@langou:

Please note that there are copies of the Quadpack subroutines in the Slatec directory, and those copies still contain the errors reported in this thread. The files are as follows:

     https://www.netlib.org/slatec/src/dqk15w.f
     https://www.netlib.org/slatec/src/qk15w.f

Searching for the string 3818300 in each of those files will show the line with the error.

**Comment by xecej4** [comment]
> @ev-br the locations and weights of a 7-point Gaussian quadrature are:
> 
> ```
> >>> import scipy.special
> >>> l, w = scipy.special.p_roots(7)
> >>> print(w[2])
> 0.38183005050511876
> ```
> 
> This would indicate that there's a typo in the existing code.

Curiously, the last two digits of the result given above are **still incorrect**. They should be 94 rather than 76, as you can see from https://github.com/scipy/scipy/issues/14807#issuecomment-934387003 . I am only a casual Python user, so I leave it to others to ask whether this error in scipy needs fixing.

**Comment by langou** [comment]
> @xecej4 wrote: "Please note that there are copies of the Quadpack subroutines in the Netlib Slatec directory, and those copies still contain the errors reported in this thread. The files are as follows:
https://www.netlib.org/slatec/src/dqk15w.f
https://www.netlib.org/slatec/src/qk15w.f

Thanks. These two files should now be corrected on Netlib. Thanks for letting me know.

**Comment by xecej4** [comment]
@langou, thanks for taking on the burden of making these corrections.
