### ISSUE TITLE
do CDF inversion methods have to be public?

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#14830]
@chrisb83, @mdhaber, @tirthasheshpatel I had completely missed the API changes to add `NumericalInverseHermite` and other public classes listed in http://scipy.github.io/devdocs/reference/stats.html#random-variate-generation-cdf-inversion. Was that discussed on the mailing list, and do these things have to be public?

My impression is that it's a complex API that is quite unlike other APIs in `scipy.stats`. They take distribution objects that are not the regular `stats` distributions:

_An instance of a class with `pdf` and `dpdf` methods._

It looks to me at first glance that this should be private infrastructure which supports improved RVS generation in the regular distribution classes?

**Comment by rgommers** [comment]
Ah I found gh-14600 which is related. There's too much there and in linked PR for me to digest right now. The functionality looks great, but the API (even just the class names) seems like it's in need of making more uniform, unifying under a single class, or making private.

**Comment by tirthasheshpatel** [comment]
> Was that discussed on the mailing list

I sent [this mail](https://mail.python.org/archives/list/scipy-dev@python.org/thread/PFNVBQT2YYEAMW3NBWJHV5L2FKQBBF7N/) in the mailing lists that briefly discusses the API while working on gh-14215. There were no comments/objections so I and @chrisb83 decided to merge the PR.

> and do these things have to be public?

Yes, the point of providing multiple generators is to let the user choose the appropriate one to sample from a non-standard distribution not present in `scipy.stats`.

> My impression is that it's a complex API that is quite unlike other APIs in `scipy.stats`. They take distribution objects that are not the regular `stats` distributions:

They do support the regular `scipy.stats` distributions but there are three reasons why they don't integrate well:

1. Some generators require the derivative of the PDF which is not present in `scipy.stats` distributions.
2. As UNU.RAN calls the distribution functions (like `pdf`, `dpdf`, `cdf`) in a non-vectorized manner, the cost of evaluating the vectorized `pdf` and `cdf` methods of `scipy.stats` distributions is too high. Moreover, these methods have a costly validation step which further increases the computation cost unnecessarily. This makes setup and sometimes sampling significantly slow.
3. Some generators don't require the normalizing contact of the PDF method. So, setup and sampling are faster with distributions that don't compute the normalizing constant for each call to the PDF method.

This is why the use of `scipy.stats` distributions is discouraged in the documentation. This does make the API atypical and harder to use but I and @chrisb83 have worked on [several tutorials](http://scipy.github.io/devdocs/tutorial/stats/sampling.html#generators-in-scipy-stats) and [detailed API documentation](http://scipy.github.io/devdocs/reference/stats.html#random-variate-generation-cdf-inversion) that hopefully assuage this complexity.

> It looks to me at first glance that this should be private infrastructure which supports improved RVS generation in the regular distribution classes?

Apart from speeding up the RVS method, another primary use of this API is to sample from distributions _not_ present in `scipy.stats`. That is why a public API makes sense.

> but the API (even just the class names) seems like it's in need of making more uniform, unifying under a single class, or making private

I and @chrisb83 did discuss providing a higher-level function or a class that unifies the functionality but observed that it is as easy or easier to just call the constructor of the generator we want to use.

**Comment by chrisb83** [comment]
Hi Ralph,

making these methods public was the main purpose of the GSoC project (https://summerofcode.withgoogle.com/projects/#5912428874825728):

> The goal of this project is to provide an object-oriented interface for methods present in UNU.RAN to sample from univariate continuous and discrete distributions using NumPy’s BitGenerator as the Uniform Random Number Sampler (URNG).

I am pretty sure the scope of the project was also discussed on the mailing list. I hope there was no misunderstanding.

While these methods are indeed relatively advanced, they provide some very useful functionality and let the user have full control of the parameters. I think @tupui already mentioned that there is demand for such methods in the QMC community.

Improving the sampling of the existing distributions in `rv_continuous` is on our TODO list. In addition to the difficulties described by Tirth, it also requires more thought about how to integrate this: for example, if you want to sample a Gamma distribution with different shape parameters, e.g. [0.5, 1.8], you need two generators (one for each shape parameter). Depending on the value of the parameter, you might even need different methods to create the generator (e.g., maybe `NumericalInversePolynomial` for one and `NumericalInverseHermite` for the other). And for unfrozen distributions, you probably cannot use this approach anyways since it is not clear how to store the generators and creating them from scratch every time will be very inefficient.

**Comment by rgommers** [comment]
Thanks for the feedback and pointers @tirthasheshpatel, @chrisb83 and @tupui! I apologize not grasping this till now - Tirth's GSoC project was so productive that I was't able to follow along much beyond trying to help with some of the integration aspects.

I'll try to find some time to go through the tutorials in detail. Maybe it's a matter of naming, or of a unifying class - not sure yet. It's just that the API looks a little off (sorry if that's vague), and something like `stats.NumericalInversePolynomial` is not a great name - there's no connection to random sampling, without more context I'd think this is more related to `numpy.polynomial` or `scipy.interpolate`.

**Comment by rgommers** [comment]
Hmm, `NumericalInverseHermite` is already released in 1.7.0 (https://github.com/scipy/scipy/pull/13319). The name isn't great, but at least its signature is easy to understand:
```python
def __init__(self, dist, *, tol=1e-12, max_intervals=100000)
```
Some of the newer classes have way too many parameters, e.g.:
```
TransformedDensityRejection(dist, mode=None, center=None, *, domain=None, c=- 0.5,
                            construction_points=30, variant='ps', use_dars=True,
                            max_squeeze_hat_ratio=0.99, max_intervals=100, guide_factor=2, random_state=None)
```

**Comment by chrisb83** [comment]
@rgommers if you have time, could you let us know your thoughts on how to proceed with gh-14717 (`NaiveRatioUniforms`) and gh-14703 (`NumericalInverseHermite`). We recently asked about these PRs on the mailing list. Tirth and I planned to get them into the 1.8.0 release. Thank you!

**Comment by tirthasheshpatel** [comment]
> I think there's two main options:

I also think the other option of moving the methods in a `stats.sampling` submodule would be better than trying to unify the classes. 

> At a minimum we should figure out which are the ones that have the most influence over algorithm performance, and move the rest to a `method_options` keyword to hide them to some extent. Better would be to get rid of as many as possible.

Agreed.

> For 1.8.0, should we try to move the less important ones to a dictionary `method_options` as an temporary solution?

I think if we do this, we would be stuck with `method_options` for backward compatibility. Let's see what UNU.RAN authors say. I think, meanwhile, `Runuran` seems like a good guide to which parameters the authors consider more influential. Even if we end up with fewer parameters, we can change that later but not vice versa. I will look into which parameters `Runuran` methods provide and change the API accordingly. Does that sound good, @chrisb83 @rgommers?

**Comment by tirthasheshpatel** [comment]
> For QMC, what I don't like with the current direction this is taking is that from a user perspective you don't know which class can handle QMC. `qrvs` is only available for now in `NumericalInverseHermite`. @chrisb83 @tirthasheshpatel is this intentional or just an omission (in cases where we could have `qrvs`)?

We could provide `qrvs` for inversion methods. The reason we didn't do this is there's already a lot to figure out about the API and UI. Also, we can always add more features later on but would be stuck with a UI due to backward compatibility.

**Comment by rgommers** [comment]
> Even if we end up with fewer parameters, we can change that later but not vice versa. I will look into which parameters `Runuran` methods provide and change the API accordingly. Does that sound good, @chrisb83 @rgommers?

This sounds good to me, the reasoning seems correct. Some parameters may be permanently hidden because they don't do much or are too hard to interpret, others can be re-enabled later.

> I also think the other option of moving the methods in a `stats.random_sampling` submodule would be better than trying to unify the classes.

Looks like we're on the same page here then. Maybe now is a good time to make a separate proposal on the mailing list about this, to ensure everyone agrees this is the way to go?

**Comment by chrisb83** [comment]
> rvs_ratio_uniforms seems to be a problem as well, it does a very similar thing to NaiveRatioUniforms as far as I can tell from the docs - it should probably also be deprecated

Yes,  NaiveRatioUniforms offers the same functionality as a special case using the common interface that Tirth implemented .We  initially wanted to deprecate `rvs_ratio_uniforms` after adding NaiveRatioUniforms. We then decided to wait since the former is still faster (about 6x if I remember correctly). We can still deprecate it right away in my view. For a lot of distributions, NumericalInverseHermite or NumericalInversePolynomial offer faster alternatives.

**Comment by tirthasheshpatel** [comment]
I am starting to shift all the methods to a new subsubmodule. I was thinking of naming it `sampling` so these methods can be imported from `scipy.stats.sampling`. @rgommers Does that sound good?

**Comment by tupui** [comment]
On one hand this seems like a good idea to make this submodule, but then we could argue that QMC could be part of it since it's also about sampling.

On the other hand, do we want users to have a submodule for that? I thought maybe this would be integrated in the distribution API. Although both things are not incompatible.

Before doing anything, what would you said about discussing the future of the module in general and what we want it to look like. This would help us answer this question. What about we make a call or something like that with all people interested in stats?

**Comment by rgommers** [comment]
`sampling` doesn't seem unreasonable. `random_sampling` could work too, to be more explicit. It'd be good to ping on the mailing list to get enough input.

> On the other hand, do we want users to have a submodule for that? I thought maybe this would be integrated in the distribution API. Although both things are not incompatible.

That was my initial feedback in this issue, but after the discussion I think @tirthasheshpatel and @chrisb83 made convincing arguments for why it does not fit into the `stats` distributions.

> Before doing anything, what would you said about discussing the future of the module in general and what we want it to look like.

See gh-14600 for the current plan for UNU.RAN based sampling methods. That's the current scope, so the question is if there's more or not.

**Comment by tupui** [comment]
> That was my initial feedback in this issue, but after the discussion I think @tirthasheshpatel and @chrisb83 made convincing arguments for why it does not fit into the `stats` distributions.

My understanding was that the functionalities would be useful for experts so it might be interesting to make them public. But this could also be part of the distributions. I will have another read 😅

> See gh-14600 for the current plan for UNU.RAN based sampling methods. That's the current scope, so the question is if there's more or not.

Yes I am more talking in general for `scipy.stats`.

**Comment by chrisb83** [comment]
> `sampling` doesn't seem unreasonable. `random_sampling` could work too, to be more explicit. It'd be good to ping on the mailing list to get enough input.

We thought `sampling` might be enough since `stats` should already imply "random" :) Let's ask on the mailing list @tirthasheshpatel could you take care of that?

> See gh-14600 for the current plan for UNU.RAN based sampling methods. That's the current scope, so the question is if there's more or not.

Note that for now, we just plan to add `SimpleRatioUniforms` on top of the functionality we already implemented. Then we should have good coverage of different methods to create generators for most univariate / discrete distributions. We will also think about how to better integrate the methods into `rv_continuous` to speed up some of the `rvs` methods but that will take some more time.

**Comment by tirthasheshpatel** [comment]
> could you take care of that?

Sure, I will write to the mailing list tomorrow.
