### ISSUE TITLE
BUG: scipy.optimize.bracket sometimes fails silently

### ISSUE THREAD

**Issue by jacksonloper** [scipy/scipy#14858]
### Describe your issue.

Sometimes scipy.optimize.bracket fails to find a bracket (e.g. see example below).  Thats probably ok.  There are some weird functions out there.  But at least one of the following should probably be true

- scipy.optimize.bracket should throw an exception if it fails
- functions that use scipy.optimize.bracket (e.g. brent) should be aware that it might return an invalid bracket

Otherwise you can have people using functions like brent and getting answers that don't make sense.

### Reproducing Code Example

```python
import scipy.optimize
import numpy

def f(x):
    return x**2 if ((-1<x)&(x<1)) else 100.0
brack=scipy.optimize.bracket(f,-1,1)[:3]

# this isn't a valid bracket
print(brack)  # <-- (-1, 1, 4.2360679999999995) 
# f(-1)=f(1)=f(4.23)=100, so thats not a valid bracket.
# valid bracket should have f(a) > f(b) < f(c)

# now if you ask brent to find a bracket for you,
# it calls scipy.optimize.bracket, gets an invalid bracket (namely -1,1,4.23)
# tries to use this invalid bracket, and yields a nonsense answer 
print(scipy.optimize.brent(f,brack=(-1,1)))  # <--4.23, not the argmin

# though if you explicitly tell brent to use this brack
# it will notice that it is a  Bad Bracket
print(scipy.optimize.brent(f,brack=brack)) # <-- raises ValueError (as it should)
```

BTW I'm not entirely sure what the right definition of "failure" is.   If f(xa)=f(xb)<f(xc) then it seems to me that this is actually still a useable bracket.  But my 1d optimization intuitions have failed me before.

### Error message

```shell
No problematic error messages.  The problem is the lack of error messages :).
```

### SciPy/NumPy/Python version information

1.7.1 1.19.5 sys.version_info(major=3, minor=9, micro=6, releaselevel='final', serial=0)

**Comment by AtsushiSakai** [comment]
I think the problem is that `optimize.bracket` does not check the results whether the results satisfies " f(xa) > f(xb) < f(xc)" or not here.
https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/optimize/optimize.py#L2661-L2667


I came up with two options to fix the issue:
[Option 1]
Throwing exception here if the results do not satisfy " f(xa) > f(xb) < f(xc)" like "optimize.brent" and "optimize.golden".
But this might break someone's code (backward compatibility).

[Option 2]
Update the doc that the objective function criteria from " f(xa) > f(xb) < f(xc)" to " f(xa) >= f(xb) <= f(xc)".
