### ISSUE TITLE
ENH: LLL lattice basis reduction

### ISSUE THREAD

**Issue by lesshaste** [scipy/scipy#14866]
### Is your feature request related to a problem? Please describe.

Currently there seems to be no [LLL](https://en.wikipedia.org/wiki/Lenstra%E2%80%93Lenstra%E2%80%93Lov%C3%A1sz_lattice_basis_reduction_algorithm) implementation in any of the standard Python libraries. It is available in sagemath however.

### Describe the solution you'd like.

There are a small number of implementations on github. E.g https://github.com/orisano/olll/blob/master/olll.py . As scipy already has Gram Schmidt orthogonalization (via scipy.linalg.qr) an implementation in scipy would hopefully not be too hard.  

### Describe alternatives you've considered.

An alternative is to use sagemath but that comes with complications for the rest of the code.

**Comment by lesshaste** [comment]
An option is to wrap http://flintlib.org/sphinx/index.html which is what I believe sage does.

**Comment by ilayn** [comment]
Exactly and that's what folks at SymPy are set out to do https://labs.quansight.org/blog/2021/08/czi-eoss4-grants-at-quansight-labs/ which is why I mentioned it in the first place.

@oscarbenjamin @asmeurer is this something you would like to tackle?

**Comment by charris** [comment]
> I am not sure if there is any demand for this

I once used the LLL algorithm along with the Hermite normal form to solve a problem, Those sorts of algorithms really need support for arbitrary precision integers and maybe rationals, so tend more towards symbolic math. It might be one of those things that people don't know they want.

**Comment by charris** [comment]
> I just merged sympy/sympy#22233 by which adds a hermite_normal_form function to SymPy:

Neat. It would be useful to offer the full factorization: UR, where U is unimodular and R is integer upper triangular, the analog of the QR factorization for reals. The U is needed for solving some problems. Note that many of these functions can be generalized to the rationals.

**Comment by lesshaste** [comment]
Interestingly, LLL can be used to compute the Hermite normal form as well https://projecteuclid.org/journals/experimental-mathematics/volume-7/issue-2/Extended-GCD-and-Hermite-normal-form-algorithms-via-lattice-basis/em/1048515660.full

**Comment by skieffer** [comment]
I would certainly like to have LLL available in SymPy. If it can be brought in via Flint, that's great. Even then it might be nice to also have a Python implementation in SymPy itself (for users who hadn't installed Flint), and this may be something I would try to work on in the future.

Unfortunately, at the moment I couldn't put this (or the suggested improvements to Hermite) on the near horizon, as I have so many other things that have to be worked on first. I'll keep it in mind though.

**Comment by Vozec** [comment]
Here is my LLL implementation based on [this pseudocode](https://en.wikipedia.org/wiki/Lenstra–Lenstra–Lovász_lattice_base_reduction_algorithm)
```python
# https://en.wikipedia.org/wiki/Lenstra–Lenstra–Lovász_lattice_base_reduction_algorithm
def LLL(base, delta=0.75):
	mu = lambda i, j: O[j].dot(base[i]) / O[j].dot(O[j])
	if type(base) == MutableDenseMatrix:
		base = [base.row(i) for i in range(base.rows)]

	O = GramSchmidt(base)
	k = 1
	while k < len(base):		
		for j in range(k-1, -1, -1):
			mu_kj = mu(k, j)
			if abs(mu_kj) > 0.5:
				base[k] = base[k] - base[j] * round(mu_kj)				
				O = GramSchmidt(base)

		if O[k].dot(O[k]) >= (delta - mu(k, k-1)**2) * O[k-1].dot(O[k-1]):
			k += 1
		else:
			base[k], base[k - 1] = base[k - 1], base[k]
			O = GramSchmidt(base)		
			k = max(k - 1, 1)

	return Matrix(base)

M = Matrix([
    [1, 1, 1 ], 
    [-1, 0, 2], 
    [3, 5, 6],
])
pprint(M)
L = LLL(M)
pprint(L)
```

**Comment by skieffer** [comment]
LLL was added to sympy earlier this year. (Sorry, didn't think to note it here at the time.)
The unit tests here:

https://github.com/sympy/sympy/blob/master/sympy/polys/matrices/tests/test_lll.py

should give an idea of how to use it.

**Comment by oscarbenjamin** [comment]
I don't remember what the situation with SymPy 1.12 is and I'm also not sure exactly what this will look like with SymPy 1.13 but with the current SymPy master branch the situation is that you can compute LLL using DomainMatrix and that the `Matrix.to_DM()` method will convert a Matrix to a DomainMatrix so you can do it like this:
```python
In [1]: M = Matrix([[1, 0, 0, 0, -20160],
   ...:             [0, 1, 0, 0, 33768],
   ...:             [0, 0, 1, 0, 39578],
   ...:             [0, 0, 0, 1, 47757]])

In [2]: M.to_DM()
Out[2]: DomainMatrix({0: {0: 1, 4: -20160}, 1: {1: 1, 4: 33768}, 2: {2: 1, 4: 39578}, 3: {3: 1, 4: 47757}}, (4, 5), ZZ)

In [3]: M.to_DM().lll()
Out[3]: DomainMatrix({0: {0: 10, 1: -3, 2: -2, 3: 8, 4: -4}, 1: {0: 3, 1: -9, 2: 8, 3: 1, 4: -11}, 2: {0: -3, 1: 13, 2: -9, 3: -3, 4: -9}, 3: {0: -12, 1: -7, 2: -11, 3: 9, 4: -1}}, (4, 5), ZZ)

In [4]: M.to_DM().lll().to_Matrix()
Out[4]:
⎡10   -3  -2   8   -4 ⎤
⎢                     ⎥
⎢ 3   -9   8   1   -11⎥
⎢                     ⎥
⎢-3   13  -9   -3  -9 ⎥
⎢                     ⎥
⎣-12  -7  -11  9   -1 ⎦
```
What is currently missing is just a `Matrix.lll` method that would just need to perform those steps so users can compute LLL without needing to do any conversions explicitly. That is an easy change though:
```python
def lll(self):
     return self.to_DM().lll().to_Matrix()
```

The recently resurrected python-flint project wraps the Flint library which has a faster C implementation of LLL (the algorithm is faster as well as the implementation). That would be most suitable for someone who just wants to use the algorithm rather than use it in the context of using SymPy. You can `pip/conda install python-flint` and then:
```python
In [1]: import flint

In [2]: M = flint.fmpz_mat([[1, 0, 0, 0, -20160],
   ...:             [0, 1, 0, 0, 33768],
   ...:             [0, 0, 1, 0, 39578],
   ...:             [0, 0, 0, 1, 47757]])

In [3]: M
Out[3]:
[1, 0, 0, 0, -20160]
[0, 1, 0, 0,  33768]
[0, 0, 1, 0,  39578]
[0, 0, 0, 1,  47757]

In [4]: M.lll()
Out[4]:
[10, -3, -2,  8,  -4]
[ 3, -9,  8,  1, -11]
[-3, 13, -9, -3,  -9]
[12,  7, 11, -9,   1]
```
As of current SymPy master if python-flint is installed and the environment variable `SYMPY_GROUND_TYPES=flint` is set then SymPy's `DomainMatrix.lll` method will use python-flint's `fmpz_mat.lll` method under the hood:
```python
$ SYMPY_GROUND_TYPES=flint isympy
...
In [2]: M = Matrix([[1, 0, 0, 0, -20160],
   ...:             [0, 1, 0, 0, 33768],
   ...:             [0, 0, 1, 0, 39578],
   ...:             [0, 0, 0, 1, 47757]])

In [4]: type(M._rep.to_dense().rep.rep)
Out[4]: flint._flint.fmpz_mat
```
https://github.com/sympy/sympy/pull/25495

It is possible that the requirement to set the environment variable explicitly might be removed by the time of the SymPy 1.13 release but if that does not happen in 1.13 it will almost certainly happen in a future release.

It is unlikely that NumPy/SciPy would be able to offer any improvement over Flint/SymPy for algorithms like LLL which do really require arbitrary precision integers and not e.g. `np.int64` in order to be generally useful. From a broader scientific/mathematical Python perspective I am not sure what else could be done to improve the situation (beyond what I described above) except perhaps improving interoperability between sympy/python-flint and numpy so that it is easier to do things like convert a numpy array to a python-flint matrix. Perhaps also SciPy could detect if python-flint is installed and then provide an easy way to use it with numpy arrays or something but possibly `dtype=object` would be needed to accommodate large integers.

**Comment by ilayn** [comment]
I think overall, since there are quite comprehensive alternatives as noted above, this is not a feature that should live in SciPy since it would be a average implementation for a specialized algorithm. General userbase won't benefit from it and the actual users seeking for this feature will not be satisfied with floating point results. Hence I'll just put this at rest for now, not to stop the discussion but take it out from open issues.

**Comment by oscarbenjamin** [comment]
If anyone is interested in looking at or improving the SymPy algorithm then it can be found here:
https://github.com/sympy/sympy/blob/067e0eaf90158c6b0ef6be14c32d9d9ccd97985b/sympy/polys/matrices/lll.py#L9-L86

The PR introducing it was https://github.com/sympy/sympy/pull/24572 by @erdos4d and has discussions about the algorithm and what might potentially make it faster.

The Flint code for this is here:
https://github.com/flintlib/flint2/tree/trunk/src/fmpz_lll

The Flint code will be used by python-flint and ultimately by SymPy if python-flint is installed (the dependency of SymPy on python-flint will always be optional).

**Comment by Vozec** [comment]
Another thing that would be interesting would be to support LLL in QQ and not just in ZZ.

/usr/local/lib/python3.11/dist-packages/sympy/polys/matrices/lll.py, line 15

A BKZ implementation would also be welcome in future updates.

**Comment by oscarbenjamin** [comment]
> Another thing that would be interesting would be to support LLL in QQ and not just in ZZ.

It would be better to discuss this in a SymPy issue rather than here in the SciPy repo.
