### ISSUE TITLE
Question: Seemingly unused, non-working script `isolve/tests/demo_lgres.py`

### ISSUE THREAD

**Issue by rossbar** [scipy/scipy#14922]
I just wanted to draw attention to this test file which is not run as part of the automated test suite as it is prefixed with `demo_` instead of `test_`.

The script doesn't run because it's pointing to an obsolete ftp URL as a data source. FWIW you can get the script running by simply replacing the `ftp` with `https`, but I was just curious whether the inclusion of this file in the test suite was intentional given that it seems a bit out of place (it is indeed more of demo than a test).

**Comment by scholtzan** [comment]
Interested in picking this up

**Comment by RafaelPinto** [comment]
Since SciPy lectures or cookbook are no longer maintained, it makes sense to turn this file into a blog post through [Scientific-Python.org](https://blog.scientific-python.org/) or as a tutorial.

Perhaps linking said tutorial to the methods used? ([scipy.sparse.linalg.gmres](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.gmres.html), [scipy.sparse.linalg.lgmres](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lgmres.html) )

**Comment by ev-br** [comment]
> Since SciPy lectures ... are no longer maintained

Are they not? 

(Turning a bit rotting demo into a scipy lecture or a tutorial is definitely a big +1 anyway)
