### ISSUE TITLE
ENH: stats: multivariate_t should support broadcasting

### ISSUE THREAD

**Issue by tirthasheshpatel** [scipy/scipy#14958]
### Describe your issue.

`multivariate_t` doesn't support broadcasting w.r.t the `df` parameter.

### Reproducing Code Example

```python
from scipy.stats import multivariate_t

# pdf, logpdf, and rvs all fail.
# below is an example of the pdf method.
multivariate_t.pdf(x=0., df=[1., 2.])
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tirthasheshpatel/Desktop/scipy_source/scipy/stats/_multivariate.py", line 3991, in logpdf
    dim, loc, shape, df = self._process_parameters(loc, shape, df)
  File "/home/tirthasheshpatel/Desktop/scipy_source/scipy/stats/_multivariate.py", line 4155, in _process_parameters
    elif df <= 0:
TypeError: '<=' not supported between instances of 'list' and 'int'
```

### SciPy/NumPy/Python version information

1.8.0.dev0+1841.4442c95 1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
I'd suggest that we consider vectorization of multivariate distributions to be an enhancement _for now_ as there is very limited multivariate infrastructure. `df` is correctly documented as accepting a `float` rather than an array, and it will be challenging to vectorize some parameters of the multivariate distributions (e.g. shape matrix), so I'd suggest that we not require it right now.

**Comment by mdhaber** [comment]
Thanks @tirthasheshpatel . If it sounds good to you, let's track the general issue of this type in gh-16278.
