### ISSUE TITLE
ENH: Solving linear programs with few nonzero variables

### ISSUE THREAD

**Issue by erelsgl** [scipy/scipy#14957]
Given a linear program with m constraints, if the program has an optimal solution, then it has an optimal [basic feasible solution](https://en.wikipedia.org/wiki/Basic_feasible_solution), in which at most m variables are non-zero. 

The Simplex method always finds such an optimal basic feasible solution, but its worst-case run-time is not polynomial.

Given an optimal solution of a linear program, is it possible with the existing tools in `scipy.optimize.linprog` to find an optimal *basic feasible* solution, in polynomial time?
If not, I think it would be a useful addition, as in some cases it is important to have a solution with few nonzeros.

**Comment by mdhaber** [comment]
It's possible that highs-ipm does. @jajhall is crossover polynomial time?
@erelsgl are you solving problems that experience worst-case computational complexity?

**Comment by erelsgl** [comment]
@mdhaber I try simplex too, but I would also like to have an algorithm with guaranteed polynomial time.

**Comment by erelsgl** [comment]
@jajhall Do you mean by using the Python interface here? https://github.com/ERGO-Code/HiGHS

**Comment by jajhall** [comment]
> @mdhaber I try simplex too, but I would also like to have an algorithm with guaranteed polynomial time.

Why? 

In not using simplex because, theoretically, it has exponential complexity, you may be shutting the door to the best way of achieving your goal - if that is to get to a basic solution with few nonzeros.

One feature of simplex is that the algorithm could be modified to search the space of non-unique solutions for ones with small numbers of nonzeros.

**Comment by jajhall** [comment]
> @jajhall Do you mean by using the Python interface here? https://github.com/ERGO-Code/HiGHS

Yes

**Comment by jajhall** [comment]
> > @jajhall Do you mean by using the Python interface here? https://github.com/ERGO-Code/HiGHS
> 
> Yes

I should add that this rudimentary Python interface is soon extended.

**Comment by erelsgl** [comment]
In any case, I think it can be useful to add to `linprog` an explicit parameter asking for a solution with few nonzeros. Some users may be interested in such a solution, but may not know the details of the various solvers.

**Comment by jajhall** [comment]
I doubt whether there is sufficient interest to justify a special parameter, @mdhaber ?

**Comment by mdhaber** [comment]
@erelsgl originally asked for "an optimal basic feasible solution" because "at most m variables are non-zero". If I understand correctly, all `linprog` methods except `"interior-point"` provide this already. 

The original post also asks for this to be done in polynomial time. It looks like there _are_ polynomial time algorithms for doing so (e.g. interior-point followed by the algorithm in [Megiddo 1990](http://theory.stanford.edu/~megiddo/pdf/primdual.pdf) or similar):
![image](https://user-images.githubusercontent.com/6570539/139742160-71c4a47d-73a9-4737-a97a-bf289a69be3b.png)
but it sounds like none of the `linprog` methods are guaranteed to produce an optimal BFS in polynomial time as-written. I've been one of the primary maintainers `linprog` for the past few years, and I'm not really interested in new custom linear programming work. My plan is to rely on HiGHS for this stuff going forward. So if HiGHS were to add a polynomial-time crossover routine, we might support. If not, I don't think I'd write it or be interested in reviewing it.

Now it sounds like we're talking about adding an additional option for `linprog` to return not just the _first_ optimal BFS found, but to iterate through non-unique optimal BFSs to find one with fewer nonzeros. (Note that the way HiGHS would do this right now wouldn't be polynomial time, because the first optimal BFS is not guaranteed to be found in polynomial time, so it sounds like we're setting that requirement aside.) I don't think we should add a parameter for iterating through non-unique solutions to `linprog` (even though I wrote "add a routine for finding ALL basic optimal solutions to a given problem" in gh-9269). There is talk about a more [advanced interface](https://github.com/scipy/scipy/issues/14455#issuecomment-901487576) for things like warmstarting and resolving after small changes to the problem. Perhaps features for iterating through the non-unique solutions would fit into this interface - but not in `linprog` itself, I don't think.

**Comment by jajhall** [comment]
Thanks. I know that the original post wanted a guarantee of polynomial time. I was trying to explain that chasing such guarantees within an implementation is pointless, and may get in the way of finding a solution to a practical problem.

Specifically, there's still no merit in asking for a guarantee of polynomial time when implementations of the simplex algorithm run in polynomial time for all practical purposes - unless they stall/cycle due to degeneracy. The latter is the "risk" with using implementations of the simplex algorithm, not the worst-case complexity. Conversely, from an interior point standpoint, in theory the algorithm may guarantee to find an optimal solution in polynomial time, but implementations can fail for various reasons, and crossover to a basic solution can stall because it reverts to the simplex algorithm.

**Comment by erelsgl** [comment]
> (even though I wrote "add a routine for finding ALL basic optimal solutions to a given problem" in [gh-9269](https://github.com/scipy/scipy/issues/9269)). 

This actually seems like a very useful addition. What is its status?

**Comment by mdhaber** [comment]
I meant that even though I wrote that then, i no longer anticipate it being done with `linprog`. That could be done with a more advanced interface (see https://github.com/scipy/scipy/issues/14455#issuecomment-901487576), though. The status is that it's an idea.

**Comment by erelsgl** [comment]
Suppose I have an application that requires an optimal basic feasible solution (BFS). It is clearer to write this requirement as an argument to linprog:

    linprog(..., return_basic_feasible_solution=true)

than to mention the method and trust the user to know that this particular method works returns a BFS:

    linprog(..., method=simplex)

**Comment by mdhaber** [comment]
@erelsgl gh-15512 will deprecate the old methods that didn't return a basic solution. 
Re: the rest, SciPy provides "fundamental algorithms". Some of the ideas here sound like they could be useful, but I don't think algorithms that implement them are considered fundamental, so I'll go ahead and close this one. Some of the ideas are still tracked in gh-9269.
