### ISSUE TITLE
BUG: in function scipy.stats.ttest_ind if equal_var = False, wrong test statistic used

### ISSUE THREAD

**Issue by Cluckenstein** [scipy/scipy#14976]
### Describe your issue.

In the scipy.stats.ttest_ind if equal_var = False a Welch test is performed as described in https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html#r3566833beaa2-2
but the test statistic in the function uses the formula (Y_1-Y_2)\sqrt(s_1^2/(N_1-1)+s_2^2/(N_2-1)) instead of the correct one stated in the Wikipedia, which is also mentioned in the link above  (Y_1-Y_2)/sqrt(s_1^2/N_1 + s_2^2/N_2).
Y_i is the mean of group i,s_i is the std of group i and N_i is the number of values of group i.

### Reproducing Code Example

```python
from scipy import stats
import numpy as np
a = [1,2,3,4,5]
b = [2,3,4,5,12]

mean_a = np.mean(a)
mean_b = np.mean(b)
var_a = np.var(a)
var_b = np.var(b)
manual_statistic = (mean_a - mean_b)/np.sqrt(var_a/len(a) + var_b/len(b))
print(manual_statistic)
print(stats.ttest_ind(a,b, equal_var = False))
```

### Error message

```shell
No message just note that the value is inccorect, output is 
-1.2892198850808625
Ttest_indResult(statistic=-1.1531133203941102, pvalue=0.2987148023687565)
```

### SciPy/NumPy/Python version information

1.7.1 scipy and all versions of numpy

**Comment by josef-pkt** [comment]
AFAIR from a long time ago

You need one 1/ n and 1 / (n-1) for standard error of a mean

np..var has default ddof=0
so you need the -1 in the manual_statistic computation

or alternative is to use ddof=1 in np.var

```
var_a = np.var(a)
var_b = np.var(b)
manual_statistic = (mean_a - mean_b)/np.sqrt(var_a/len(a) + var_b/len(b))
```

**Comment by Cluckenstein** [comment]
> AFAIR from a long time ago
> 
> You need one 1/ n and one 1 / (n-1) for standard error of a mean
> 
> np..var has default ddof=0 so you need the -1 in the manual_statistic computation
> 
> or alternative is to use ddof=1 in np.var
> 
> ```
> var_a = np.var(a)
> var_b = np.var(b)
> manual_statistic = (mean_a - mean_b)/np.sqrt(var_a/len(a) + var_b/len(b))
> ```

According to the literature, the test does not need the -1 bias correction, that is the whole point. We use the real np.var and not the bias corrected with -1. Hence the used test statisitc is incorrect.

**Comment by Cluckenstein** [comment]
Again, it is standard in the degrees of freedom, but NOT in the Welch statisitic itself. The formula is just plain wrong as also stated in the wikipedia article, the manual mentions. This is also not some opinion, rather than the accepted literature.

**Comment by josef-pkt** [comment]
```
> options(digits=16)
> t.test(a, b, alternative="two.sided", var.equal=FALSE)

        Welch Two Sample t-test

data:  a and b
t = -1.1531133203941, df = 5.2423834770911, p-value = 0.2987148023688
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -7.036933359542902  2.636933359542902
sample estimates:
mean of x mean of y 
      3.0       5.2 
```

pvalue scipy (and statsmodels) 0.2987148023687565

I guess we were reading different literature then.
AFAICS, Wikipedia page doesn't say anything about how `s_i` is calculated

**Comment by mdhaber** [comment]
> AFAICS, Wikipedia page doesn't say anything about how s_i is calculated

It does not. It says:
![image](https://user-images.githubusercontent.com/6570539/158080675-8cb91bca-4c05-4a33-ae1c-dd9941bc3e0c.png)

and does not explicitly specify whether the sample standard deviation is corrected or uncorrected. Later, however, it does state:

![image](https://user-images.githubusercontent.com/6570539/158081339-eb104a17-7270-45e6-9c57-7626ed09acbe.png)

which suggests that `n_i - 1` should be used in the standard error estimate, since presumably it's the square root of the variance estimate.

---

@Cluckenstein you wrote that
>  the test statistic in the function uses the formula (Y_1-Y_2)\sqrt(s_1^2/(N_1-1)+s_2^2/(N_2-1))

Here is the code, though:
https://github.com/scipy/scipy/blob/da64f8ca0ef2353b59994e7e37ecee4e67a9b1d3/scipy/stats/_stats_py.py#L5934-L5944

I wonder if you are confusing `df` and `denom`?

---

If it's not as simple as that, there are three places where `n_i` appears in the calculation somehow, so let's look at each one.

1. In the degree of freedom calculation in 5938, there is an explicit `n_i - 1` in the denominator. This agrees with Wikipedia, which states that
![image](https://user-images.githubusercontent.com/6570539/158081931-1b96b001-5dcc-440e-bc84-e7ccae082f75.png)
and 
![image](https://user-images.githubusercontent.com/6570539/158081339-eb104a17-7270-45e6-9c57-7626ed09acbe.png)
In Welch's original paper, this is Equation 26.
![image](https://user-images.githubusercontent.com/6570539/158081756-ad652c2e-ca8c-499f-a8b1-64ea86eebab2.png)
where previously
![image](https://user-images.githubusercontent.com/6570539/158081920-0ba2a6f5-2b30-4c74-8a38-8662b66f0586.png)
and
![image](https://user-images.githubusercontent.com/6570539/158081982-d860fe59-6338-42fb-9037-91f639fd286a.png)
![image](https://user-images.githubusercontent.com/6570539/158081992-5fca48df-5f7e-4ac2-afb4-6d042b7ed337.png)

3. In the denominator of the test statistic (5935-5936), `n_i` is used to calculate the square of the standard error.  This agrees with Wikipedia, which states that
![image](https://user-images.githubusercontent.com/6570539/158081411-76e33231-4659-4237-b041-ca2c44020a0d.png)
and with Welch's original paper Equation 25.
![image](https://user-images.githubusercontent.com/6570539/158081768-58d1cee0-9ffc-43e5-810d-03b3fe4c8be8.png)

4. The number of degrees of freedom to use in the standard error / variance calculation is the only thing left. In `ttest_ind`, we use `np.var` with `ddof=1`, so the variance is calculated with `n_i - 1`. Based on Wikipedia's comment about "the degrees of freedom associated with the i-th variance estimate.", I would think that is correct. Alternatively, from Welch's original paper:
![image](https://user-images.githubusercontent.com/6570539/158082078-e8c97ba6-62cb-4ce7-a498-c6d2a009ba57.png)

AFAICT, we agree with Welch's original paper, Wikipedia, and R, so I'm going to close this one. Please let me know if I've missed something @Cluckenstein, and if so, please carefully point out the discrepancy between the literature and code (similar to how I've attempted to demonstrate their consistency).
