### ISSUE TITLE
BUG: contradicting description in mannwhitneyu test

### ISSUE THREAD

**Issue by rita-palfine-cko** [scipy/scipy#14970]
### Describe your issue.

The description provided for the `alternative` is contradicting itself. For instance, the explanation for `less` is phrased that "the distribution underlying x is stochastically `less` than the distribution underlying y", but the mathematical formula following is stating the relationship in the other way: `i.e. F(u) > G(u) for all u.`

It would be clearer to state that for `less`: the H0 hypothesis is that the distribution underlying `x` is stochastically greater than the distribution underlying `y`, F(u) >= G(u)* for all *u*. The H1 hypothesis is that the distribution underlying `x` is stochastically less than the distribution underlying `y`, F(u) < G(u).
This would reflect how the test is working.

Similar update should be made to the `greater` explanation as well.

### Reproducing Code Example

```python
Input:
sample1 = [10 for i in range(100)]
sample2 = [20 for i in range(100)]
mannwhitneyu(x = sample1, y = sample2, alternative='less')

Output:
MannwhitneyuResult(statistic=0.0, pvalue=1.7608079411973e-45)
```

### Error message

```shell
No error message related to this issue.
```

### SciPy/NumPy/Python version information

1.7.1 1.20.1 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
I understand the confusion, but the direction of the inequality is correct as-written. Remember that *F* and *G* are the *cumulative distribution functions* underlying the variables. The math of stochastic ordering is not always familiar, so maybe the solution is to rewrite the mathematical statement in terms of the PDFs, which has more immediately intuitive notation. Would that work?

We could add the null hypothesis, too. But regardless of alternative, the null hypothesis is that the two distributions are identical (i.e. CDFs are equal for all x). The calculation of the *p*-value depends on that. Would that be good?

**Comment by rita-palfine-cko** [comment]
Oh! NO, I didn't realise that F and G are the cumulative distribution function, although it is clearly written. Thank you for calling my attention to it.

I noticed that there is an explanation of this at the ks_2samp test, which might be a consensus solution, so no need to rephrase, but add some explanation to be super clear. 
"Note that the alternative hypotheses describe the CDFs of the underlying distributions, not the observed values. For example, suppose x1 ~ F and x2 ~ G. If F(x) > G(x) for all x, the values in x1 tend to be less than those in x2."

This also leads me to another question, if I may: these two tests are using the alternative "less" in the opposite way. Or am I missing something again? 
It would be great to use them consistently, where the H1 hypothesis means F(u) > G(u) where F and G are cumulative distribution functions. I am very interested in your view! Thanks a lot in advance!

**Comment by mdhaber** [comment]
Yes, I added that note in gh-13188 to resolve similar confusion about `ks_2samp`. I don't have much time to review or submit PRs now, but I wouldn't block such an addition to MWU. I wouldn't really want to be involved in it, though, because it involves formatting math, and there tends to be more contention about how best to do that than one would expect.

> This also leads me to another question, if I may: these two tests are using the alternative "less" in the opposite way. Or am I missing something again?

That's true. But I can see the reason for it. Certainly `mannwhitneyu`'s convention is intuitive; e.g. alternative "less" means that the random variable underlying `x` "tends to be less" than the one underlying `y`. Most SciPy hypothesis tests are like that. I think that is much more common to think about most tests in terms of the random variables than in terms of the CDFs underlying the data. We just add the bit about the CDFs to make the meaning of "stochastically less" precise in terms of concepts that users are probably familiar with. But `ks_2samp` is naturally thought of in terms of the CDFs underlying the data rather than the random variables. For example, on Wikipedia

> "The Kolmogorov–Smirnov statistic quantifies a distance between the empirical distribution function of the sample and the cumulative distribution function of the reference distribution, or between the empirical distribution functions of two samples." 

So for `ks_2samp`, having "less" correspond with the alternative "F(x) < G(x) for at least one x" makes some sense. Since there is some rationale behind the way it is, there would need to be a lot of support to make a backwards-incompatible change.

**Comment by rita-palfine-cko** [comment]
Thank you for the clarification. This was very helpful! I see your point how the different formulations makes sense. One has to pay careful attention what 'less' means in each test.
