### ISSUE TITLE
ENH: Avoid unnecessary function evaluations if guess is already in tolerance (scipy.optimize.newton)

### ISSUE THREAD

**Issue by kcharlie2** [scipy/scipy#15006]
### Is your feature request related to a problem? Please describe.

If the initial guess `x0` in `scipy.newton.optimize` results in an answer within tolerance, execution still continues, resulting in additional function calls. 

The example below result in 3 function calls.

```
def func(x):
    return x

out = scipy.optimize.newton(func, 0, full_output=True)

print(out[1].function_calls)
>> 3
```

### Describe the solution you'd like.

The initial guess could be checked for convergence before additional function calls to save time. 

In the above example (secant method with no `x1` input), there is no need to perform the second call to the evaluation function, which appears to be done just for getting the finite difference. I'm not sure why the 3rd call is needed.

Ideally this would work when `x0` is an array. If it worked with Newton and Halley methods (specifying `fprime` and `fprime2`) that'd be nice as well.

**Comment by tupui** [comment]
Hi @kcharlie2, thanks for the proposal.

I would argue that you should not call an optimize function in your code if you already have a satisfactory solution. In the end calling these optimizers generate quite some overhead over a simple comparison like that since they are doing more things. Let see what others think.

**Comment by andyfaff** [comment]
The condition for convergence *isn't* when `func(x)` is close to zero (`np.isclose(func(x), 0, atol=tol, rtol=rtol)`). Rather the condition for convergence is when `x` generated by successive iterations are within a tolerance: [`np.isclose(p, p0, rtol=rtol, atol=tol)`](https://github.com/scipy/scipy/blob/d7fa27f0c4a33b6e4f7bafec6605961428ca6523/scipy/optimize/_zeros_py.py#L357). Therefore I think it's unavoidable that there are going to be a minimum number of iterations, you have to go at least once through the iteration loop in order to be able to compare those values.

Where you under the impression that the `tol` and `rtol` keywords referred to how close `func(x)` was to zero? If so, then there may be potential to make that clearer.

**Comment by kcharlie2** [comment]
> The condition for convergence _isn't_ when `func(x)` is close to zero (`np.isclose(func(x), 0, atol=tol, rtol=rtol)`). Rather the condition for convergence is when `x` generated by successive iterations are within a tolerance: [`np.isclose(p, p0, rtol=rtol, atol=tol)`](https://github.com/scipy/scipy/blob/d7fa27f0c4a33b6e4f7bafec6605961428ca6523/scipy/optimize/_zeros_py.py#L357). Therefore I think it's unavoidable that there are going to be a minimum number of iterations, you have to go at least once through the iteration loop in order to be able to compare those values.
> 
> Where you under the impression that the `tol` and `rtol` keywords referred to how close `func(x)` was to zero? If so, then there may be potential to make that clearer.

The default relative tolerance is 0.0, in which case only the first solution is needed when checking for convergence, not the second - the `np.isclose` comparison becomes strictly absolute since the newton iteration is searching for zeros. I'm not sure I understand see why there couldn't be a check for convergence after the first function evaluation when rtol=0.

As @tupui pointed out, I think the actual issue is if it's worth the time savings. In my use-case I am performing newton iteration on thousands of sets of data. The function evaluation is very expensive but iteration converges quickly, Only ~half of the cases actually need the iteration, but I cannot determine before hand which ones need iteration. Adding an initial check myself before calling newton significantly increases the total time since it does not help reduce the number of calls when the solution needs iteration.

**Comment by tupui** [comment]
Why not using a cache (LRU for instance) for your function? This way repeated calls would be free.

**Comment by andyfaff** [comment]
caching is not straightforward when a function argument is an array with floating point numbers. It is possible (e.g. joblib does this), but the cache lookup does add overhead. Still, if the function evaluation is very expensive then it may still be worth it.

> I'm not sure I understand see why there couldn't be a check for convergence after the first function evaluation when rtol=0.

@kcharlie2, if I understand correctly, you want a convergence check that will halt if it's within a set tolerance of zero?

**Comment by tupui** [comment]
> caching is not straightforward when a function argument is an array with floating point numbers. It is possible (e.g. joblib does this), but the cache lookup does add overhead. Still, if the function evaluation is very expensive then it may still be worth it.

Yes, it really depends on the problem. Even with complex inputs, you should be able to construct a custom hashing function.
