### ISSUE TITLE
scipy.linalg.qr with pivoting=True should return P as (N,N) permutation array instead of (N,) array

### ISSUE THREAD

**Issue by klim-** [scipy/scipy#15021]
I am a bit surprised why `scipy.linalg.qr` with `pivoting=True` returns `P` as an array of shape (N,) instead of a proper two dimensional array of shape (N,N) just like `scipy.linalg.lu` does. This way I could quickly test if `A = P.T@Q@R` just like I can test `A=P@L@U`. Is there any reason for this inconsistency?

**Comment by ilayn** [comment]
Probably historical. But as shown in the examples you can still do `np.allclose(A[:, P], (q @ r))`.

**Comment by klim-** [comment]
Thank you for the quick feedback. This is exactly what I am doing, but what if I needed P for further matrix computations?

**Comment by ilayn** [comment]
You can use it on an identity matrix to shuffle the columns or rows depending on which side you want it

**Comment by ilayn** [comment]
You can use it on an identity matrix to shuffle the columns or rows depending on which side you want it

**Comment by klim-** [comment]
The issue was more about consistency, but thank you anyway.

**Comment by ilayn** [comment]
I'd argue in this case that LU is the odd one since it is a waste of n**2 array just to provide sorting keys. I see how this can be unintuitive when you have plenty of memory but nevertheless having an array of n instead of n**2 is efficiency wise should be prefferred. I agree nevertheless we have a historical inconsistency across linalg functions.

**Comment by v0dro** [comment]
I do agree with @klim- that 1D array is a bit of surprise and that one has to look at the code samples to understand how the pivots can be used. Maybe the docs can be enhanced with a separate example that generates a pivot matrix from this array and multiplies that with the Q and R?

@rgommers I think this issue can be closed for the following reasons:

* This change will cause backwards compatibility issues (I myself have a lot of code using pivoted QR that relies on the P being a single array).
*  Returning a NxN matrix is memory inefficient.
* LAPACK functions such `dgeqp3` that return pivot arrays also return 1D arrays.

**Comment by rgommers** [comment]
> Maybe the docs can be enhanced with a separate example that generates a pivot matrix from this array and multiplies that with the Q and R?

This is the right suggestion to close the issue I think. We indeed shouldn't make any backwards incompatible changes here.

**Comment by ilayn** [comment]
I am still considering this since most software has the option [`Outputform`](https://www.mathworks.com/help/matlab/ref/qr.html?s_tid=srchtitle_qr_1#d123e1168024) as a switch between 1d perm vs 2d full permutation array. It is not a very difficult thing to implement but what we will definitely not do is to choose one that would break code.

**Comment by ilayn** [comment]
Now `linalg.lu` also has an option to return similar 1D permutation indices, hence it should be a more coherent catalogue now.
