### ISSUE TITLE
BUG: sparse.dok_matrix.fromkeys method totally nonfunctional

### ISSUE THREAD

**Issue by brsr** [scipy/scipy#15039]
### Describe your issue.

The `fromkeys` method of `sparse.dok_matrix` returns an error. If it is called in the form `scipy.sparse.dok_matrix.fromkeys(keys, values=1)` it throws `TypeError: dok_matrix.fromkeys() takes no keyword arguments`. If called as `scipy.sparse.dok_matrix.fromkeys(keys)` or `scipy.sparse.dok_matrix.fromkeys(keys, 1)`
it throws `TypeError: __init__() missing 1 required positional argument: 'arg1'`. The content of `keys` and `values` do not seem to matter.

The first error contradicts [the documentation for the method](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.dok_matrix.fromkeys.html#scipy.sparse.dok_matrix.fromkeys), which seems to have been inherited from [the docs for Python dicts](https://docs.python.org/3.9/library/stdtypes.html#dict.fromkeys). The two disagree on whether `values` is a positional or keyword argument.

### Reproducing Code Example

```python
import scipy
edges = [(0,1),(1,2),(2,0)]
scipy.sparse.dok_matrix.fromkeys(edges, values=1)
scipy.sparse.dok_matrix.fromkeys(edges, 1)
scipy.sparse.dok_matrix.fromkeys(edges)
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: dok_matrix.fromkeys() takes no keyword arguments

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'arg1'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'arg1'
```

### SciPy/NumPy/Python version information

1.7.2 1.21.4 sys.version_info(major=3, minor=9, micro=8, releaselevel='final', serial=0)

**Comment by perimosocordiae** [comment]
This is a side-effect of the `dok_matrix` object inheriting from the `dict` builtin:
https://github.com/scipy/scipy/blob/b4b606600faf8c780968e244e11b69f0f3ba00fe/scipy/sparse/_dok.py#L23

Note that `dict.fromkeys` doesn't accept keyword arguments, so that's consistent. The other errors (referring to `arg1`) are related to how the builtin `dict.fromkeys` function calls the `__init__` method of its associated class:
`dok_matrix.__init__(self, arg1, shape=None, dtype=None, copy=False)`

I think if we were to re-create the DOK format we'd avoid subclassing from `dict`, but that's not something we can easily change now. As a workaround, you can get the desired behavior like this:

```python
scipy.sparse.dok_matrix(dict.fromkeys(edges, 1))
```

**Comment by perimosocordiae** [comment]
One way to address this issue might be to override the `fromkeys` classmethod and have it return a NotImplementedError that points users toward the above workaround.

**Comment by brsr** [comment]
Rather than throwing an error, why not define the method `scipy.sparse.dok_matrix.fromkeys(*args, **kwargs)` to be `return scipy.sparse.dok_matrix(dict.fromkeys(*args, **kwargs))` ?

**Comment by perimosocordiae** [comment]
Yeah, that works as well. Though I'd prefer to match the signature of `dict.fromkeys` rather than using `*args, **kwargs`.

**Comment by brsr** [comment]
Actually, I should have tried it first:
```
>>> scipy.sparse.dok_matrix(dict.fromkeys(edges, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/scipy/sparse/dok.py", line 101, in __init__
    raise TypeError('Expected rank <=2 dense array or matrix.')
TypeError: Expected rank <=2 dense array or matrix.
```

**Comment by perimosocordiae** [comment]
Here's an implementation that should work:

```python
@classmethod
def fromkeys(cls, iterable, value=1):
    d = dict.fromkeys(iterable, value)
    num_rows = 1+ max(k[0] for k in d.keys())
    num_cols = 1 + max(k[1] for k in d.keys())
    result = cls.__init__((num_rows, num_cols))
    result._update(d)
    return result
```

**Comment by yoch** [comment]
As @brsr pointed out, `scipy.sparse.dok_matrix(dict.fromkeys(edges, 1))` doesn't work because we cannot initialize `dok_matrix` directly with a `dict` (this seems a bit strange to me because it's quite natural to do so).

@perimosocordiae 
Your implementation above seems right, why it's still not implemented like that in production?

**Comment by perimosocordiae** [comment]
No reason that I'm aware of. Feel free to open a PR!
