### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [scipy/scipy#15057]
### Is your feature request related to a problem? Please describe.

:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

### Describe the solution you'd like.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/SciPy/lokal -name '*.py')
```

### Additional context

[Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13)

**Comment by rkern** [comment]
Personally, I'm not particularly interested in a broad, semi-automated conversion of these statements. Augmented assignment has existed for most of scipy's lifetime, so many, if not most, opportunities that a tool might find are places where the author had the chance to use them and decided not to, either because it was not worthwhile or because the in-place semantics were to be avoided in those places.

**Comment by tupui** [comment]
Closing this. Cf https://github.com/PyCQA/pylint/issues/5174
