### ISSUE TITLE
On the summation of some multivariate normal distributions 

### ISSUE THREAD

**Issue by tensor-tensor** [scipy/scipy#15063]
### Describe your issue.

How can one adds up two `multivariate_normal` objects in `scipy`? None of the following tries work.

### Reproducing Code Example

```python
from scipy.stats import multivariate_normal

Z0 = multivariate_normal([1,2], [[2,0],[0,2]])
Z1 = multivariate_normal([1.1,2.2], [[2.1,0],[0,4.1]])

# First try:
Z = Z0 + Z1

# Second try:
Z = sum(Z0,Z1)
```

### Error message

```shell
# The error associated with the first try:

TypeError: unsupported operand type(s) for +: 'multivariate_normal_frozen' and 'multivariate_normal_frozen'

# The error associated with the second try:

TypeError: 'multivariate_normal_frozen' object is not iterable
```

### SciPy/NumPy/Python version information

1.3.1 1.19.5 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

**Comment by tensor-tensor** [comment]
It seems that I was just supposed to call `pdf()` after each distribution instance, say,

`Z = Z0.pdf() + Z2.pdf()`.

**Comment by mdhaber** [comment]
I'm guessing you are trying to model the sum of two normally distributed random variables. `Z = Z0.pdf() + Z2.pdf()` will raise an error because `pdf` needs an argument, but even with that fixed, you wouldn't get the PDF of the distribution you seem to want. Issues here on the GitHub repo are for bug reports and enhancement requests, but this is more of a usage question, so I'd suggest posting your question on Stack Overflow
