### ISSUE TITLE
Request: convert signal.lsim to Cython

### ISSUE THREAD

**Issue by L-Ron-GitHubbard** [scipy/scipy#15070]
Inspecting the signal.lsim source, I noticed that lsim uses a python for loop at [line 2142](https://github.com/scipy/scipy/blob/b3d84bd4c7b050d7768e57e7d2c942ae7efaae2f/scipy/signal/_ltisys.py#L2142) to iterate over all the time steps of the signal.

This seems like a great candidate for speed-up with Cython. 

Profiling my own simulation code shows that lsim is by far the biggest performance bottleneck. I suspect that this will be true for most users of lsim.

Perhaps it is worth converting _ltisys.py entirely to Cython. There are quite a few python for loops in it, and several of those are in functions likely to be bottlenecks in signal processing applications.

**Comment by ilayn** [comment]
Indeed it can speed up a bit with Cython possibly using `?gemv` with inline addition `alpha*A*x + beta*y` but nevertheless it will continue to be the slowest part of the code due to the repeated nature of the problem.

**Comment by L-Ron-GitHubbard** [comment]
>  nevertheless it will continue to be the slowest part of the code due to the repeated nature of the problem.

Agreed. But please note this is also the place where even a small speed-up can substantially improve overall execution time.

If anyone is going to benchmark the current versus an optimized implementation, please also consider also the case of user code with repeated calls to lsim. 

Reason: Depending on the type of simulation problem, it is not always possible to pass a long signal into lsim. Sometimes there is no other way but to repeatedly simulate responses to short input signals. 
If the typical useage is to, say, simulate once a 10s long input signal sampled at 10kHz. Please consider also the case of simulating 100 times a 0.1s long input signal sampled at 10kHz. (The latter is again 10s in total, just cut into 100 segments.)

**Comment by ilayn** [comment]
For the latter, you can enhance your B and C arrays (yes making them 100x100) and simulate all at once due to linearity. But keep in mind that matrix multiplication is already floored to the metal by BLAS calls on NumPy side, and we are talking about removing some overhead around that BLAS call. 

You can try a small implementation with Cython, only that for loop, not even changing the code but just letting it Cython-compiled. That difference would be the Python overhead. The other overhead is the NumPy spending to take the array to low-level to perform the `?gemv` call. 

What I am trying to get at, I guess, is that, even though this is python for loop and on paper it is slow, if the matrix multiplication is dominating, there will be a tiny unimpressive win for the effort that would go in. Hence size matters a lot.

**Comment by rgommers** [comment]
Thanks for the suggestion and following up on it @L-Ron-GitHubbard. Agreed this can be closed.
