### ISSUE TITLE
BUG: scipy.optimize.minimize() does not report lowest energy visited.

### ISSUE THREAD

**Issue by tpstps** [scipy/scipy#15089]
### Describe your issue.

Hi,

I use `scipy.optimize.minimize()` (`method='Powell'`) and pass "the best" value of `x`  as  `x0` to it.

**OBSERVATION:**
I can see that `scipy.optimize.minimize()` calls my function with that value. In the end this value is **not**  used  when passing back the result to the caller of `scipy.optimize.minimize()`.

**EXPECTATION**
I would expect that this best value is passed back to the caller of `scipy.optimize.minimize()`

### Reproducing Code Example

```python
import scipy.optimize


def myFunc(x):
    if x == 17:
        myReturn = -10
        print("x, myReturn=", x, myReturn, '<==================== I would expect that this result will be passed back to the caller of scipy.optimize.minimize()')
    else:
        myReturn = -7
        print("x, myReturn=", x, myReturn)
    return myReturn


if __name__ == '__main__':
    import sys, scipy, numpy;

    print(scipy.__version__, numpy.__version__, sys.version_info)
    x0 = 17
    dummy = False
    optimizingResult = scipy.optimize.minimize(myFunc, x0, bounds=[(-100, 100)], method='Powell')
    print("optimizingResult=\n", optimizingResult)
```

### Error message

```shell
1.7.2 1.21.4 sys.version_info(major=3, minor=8, micro=7, releaselevel='final', serial=0)
x, myReturn= [17.] -10 <==================== I would expect that this result will be passed back to the caller of scipy.optimize.minimize()
x, myReturn= [-23.60679775] -7
x, myReturn= [23.60679775] -7
x, myReturn= [52.7864045] -7
x, myReturn= [70.82039325] -7
x, myReturn= [81.96601125] -7
x, myReturn= [88.854382] -7
x, myReturn= [93.11162925] -7
x, myReturn= [95.74275275] -7
x, myReturn= [97.3688765] -7
x, myReturn= [98.37387625] -7
x, myReturn= [98.99500025] -7
x, myReturn= [99.378876] -7
x, myReturn= [99.61612425] -7
x, myReturn= [99.76275174] -7
x, myReturn= [99.85337251] -7
x, myReturn= [99.90937923] -7
x, myReturn= [99.94399328] -7
x, myReturn= [99.96538595] -7
x, myReturn= [99.97860734] -7
x, myReturn= [99.98677861] -7
x, myReturn= [99.99182873] -7
x, myReturn= [99.99494988] -7
x, myReturn= [99.99687885] -7
x, myReturn= [99.99807102] -7
x, myReturn= [99.99880783] -7
x, myReturn= [99.9992632] -7
x, myReturn= [99.99954463] -7
x, myReturn= [99.99971857] -7
x, myReturn= [99.99982606] -7
x, myReturn= [99.9998925] -7
x, myReturn= [99.99993356] -7
optimizingResult=
    direc: array([[1.]])
     fun: array(-7)
 message: 'Optimization terminated successfully.'
    nfev: 32
     nit: 1
  status: 0
 success: True
       x: array([99.99993356])
```

### SciPy/NumPy/Python version information

1.7.2 1.21.4 sys.version_info(major=3, minor=8, micro=7, releaselevel='final', serial=0)

**Comment by andyfaff** [comment]
This problem is pathological, returning only two possible values. Nearly all the methods in `minimize` would have an issue with this problem because they're designed to use finite differences to figure out where an improved solution is. I would say that no minimiser would be able to solve this problem if you didn't start off at the best solution, because the equality comparison of floats would lead to a vanishingly small probability of finding the minimum.
Having said that I do understand the importance of returning the best solution found so far, see #12111 and #12120. The first issue discusses the subtleties of tracking the best solution found so far. The second implements a test (for a continuous system). However, it's not necessarily a straightforward fix, or even desired (e.g. the best found solution may not satisfy a constraint).

**Comment by andyfaff** [comment]
Needs decision label because of the subtleties of returning the lowest found energy, as outlined in #12111. 
E.g. the minimiser might evaluate fun-->jac-->fun, but the finite difference check in jac visits an `x` with a slightly lower `fun(x)` then the final fun. However, a tolerance might then be met (`fatol`, `frtol`), so the final `x` isn't iterated further. Hence the best `x` isn't reported, but a close location.

My gut feeling is to not report the lowest energy if it's found during other steps involved during a minimisation, therefore closing this issue.

The MWE reported in this issue is pathological, and wouldn't be a reason to keep the issue open by itself.

**Comment by tupui** [comment]
I understand your arguments, still we could store this information somewhere. If a solver found a better solution (which respects any constraints, tol, etc.) during an intermediary step, it would not be hard to at least return it since we have a callback mechanism in place, no?

I agree that stopping or not the optimizer would not be trivial. But definitely something we should consider. There is really a need for costly functions to optimize as much as we can function calls.

**Comment by tpstps** [comment]
Hi,

I commented in [ MAINT: ScalarFunction remember best_x #15099](https://github.com/scipy/scipy/pull/15099 )  about a bug in that pull request.

**Comment by andyfaff** [comment]
@tpstps there wasn't a bug introduced in #15099, the issue you mention there is unrelated.

**Comment by tpstps** [comment]
@andyfaff , 

ok, I understand. 

Shall I create a new ticket for that issue or will you take care for it independently?

**Comment by tpstps** [comment]
Thanks, so the issue probably is [BUG: bounded L-BFGS-B doesn't work with a scalar. #15228 ](https://github.com/scipy/scipy/issues/15228), isn't it?
