### ISSUE TITLE
How to solve a BVP whith known parameters?

### ISSUE THREAD

**Issue by KennethGrimes** [scipy/scipy#15163]
Hello everybody,

First of all thanks to the team that implemented solve_bvp()

I need to solve a boundary value problem (BVP) of second order, where the equation depends on several know parameters, which are geometric parameters and material constants. I would like to solve this equation for several combination of values of the known parameters.  How is it possible to do this using solve_bvp()?

I am thinkg along the lines of the "args" parameter in solve_ivp()

In case my question is unclear, imagine I want to solve the Bratu equation from solve_bvp() documentation for several values of "k", without having to each time change the value of k in the function "fun(x,y)". How can this be accomplished?

Many thanks in advance!

**Comment by Patol75** [comment]
I am wondering if the following is what you mean:
```
import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import solve_bvp


def fun(x, y):
    return np.vstack((y[1], -1 * np.exp(y[0]),
                      y[3], -2 * np.exp(y[2])))


def bc(ya, yb):
    return np.array([ya[0], yb[0],
                     ya[2], yb[2]])


x = np.linspace(0, 1, 5)
y = np.zeros((4, x.size))
sol = solve_bvp(fun, bc, x, y)
x_plot = np.linspace(0, 1, 100)
y_plot_1, y_plot_2 = sol.sol(x_plot)[[0, 2]]
plt.plot(x_plot, y_plot_1, label='y_1')
plt.plot(x_plot, y_plot_2, label='y_2')
plt.legend()
plt.xlabel("x")
plt.ylabel("y")
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/23244688/146658771-753801a0-7948-4887-b6ac-b52b38f8a1af.png)
I have not passed the two different values of `k` as a parameter `p` because it would require additional boundary conditions, which I do not know about. But, if you know the form of the additional boundary conditions, then you can generalise the above to implement as many `k` as you want. This assumes that the above is correct.

**Comment by mdhaber** [comment]
That works, but here is a solution that requires less copy-paste for many `k`:

```python3
import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import solve_bvp


def fun(x, y, k):
    return [y[1], -k * np.exp(y[0])]


def bc(ya, yb, k):
    return np.array([ya[0], yb[0]])


k = 1
x = np.linspace(0, 1, 5)
y = np.zeros((2, x.size))
sol = solve_bvp(lambda x, y: fun(x, y, k), 
                lambda x, y: bc(x, y, k), 
                x, y)
x_plot = np.linspace(0, 1, 100)
y_plot_1 = sol.sol(x_plot)[0]
plt.plot(x_plot, y_plot_1, label='y_1')
plt.legend()
plt.xlabel("x")
plt.ylabel("y")
plt.show()
```

Of course, instead of `lambda`s, you can just `def` wrapper functions.

Since this is phrased as a question, I'd suggest stackoverflow for future usage questions like this; we use GitHub for enhancement requests and bug reports. If you'd like to submit this as an enhancement request, please do so in a new issue so that we can preserve the history of this one.
