### ISSUE TITLE
SVD inconsistency for sparse matrix with LOBPCG

### ISSUE THREAD

**Issue by zmoitier** [scipy/scipy#15170]
# SVD inconsistency for sparse matrix with LOBPCG

Computing singular values using the solver LOBPCG, with a different number of singular values ask, is not stable in the sense that it produce different values.

To be more precise, take the sparse matrix:
```python
import numpy as np
from scipy.sparse import diags
from scipy.sparse.linalg import svds

mat_size = 128
mat_diag = np.full(mat_size, -2)
mat_hors_diag = np.full(mat_size - 1, 1)
mat = diags((mat_hors_diag, mat_diag, mat_hors_diag), (-1, 0, 1))
```
Then, I will compute the 16 largest (`LM`) and smallest (`SM`) singular values of the matrix using either the solver `arpack` or `lobpcg`. I will do this two times by first asking for the 16 `LM`/`SM` and then for the 32 `LM`/`SM` singular values and compare the 16 `LM`/`SM` from these two computations. We should get that the difference between the two is close to machine precision.

First, as a reference, the 16 `LM` singular values with `arpack`:
```python
>>> svd_16 = svds(mat, k=16, which="LM", return_singular_vectors=False, solver="arpack")
>>> svd_32 = svds(mat, k=32, which="LM", return_singular_vectors=False, solver="arpack")
>>> print(np.abs(svd_16-svd_32[-16:]).max())
3.552713678800501e-15
```
The maximum of the difference is close to machine precision, that is good.

Then the 16 `LM` singular values with `lobpcg`:
```python
>>> svd_16 = svds(mat, k=16, which="LM", return_singular_vectors=False, solver="lobpcg")
>>> svd_32 = svds(mat, k=32, which="LM", return_singular_vectors=False, solver="lobpcg")
>>> print(np.abs(svd_16-svd_32[-16:]).max())
1.1664855303905597e-08
```
We have lost half the precision.

And the `SM` version with `lobpcg`:
```python
>>> svd_16 = svds(mat, k=16, which="SM", return_singular_vectors=False, solver="lobpcg")
>>> svd_32 = svds(mat, k=32, which="SM", return_singular_vectors=False, solver="lobpcg")
>>> print(np.abs(svd_16-svd_32[:16]).max())
0.03882329852828505
```
It is even worse. I did not put the `SM` result with `arpack` as it does not converge in that case.

To track how this behaves with respect the matrix size, I made a plot of those maximum differences with respect to the matrix size (see [svd_scipy.pdf](https://github.com/scipy/scipy/files/7669069/svd_scipy.pdf)). We can see that the `LM Arpack` stay close to machine precision that good. However, the `LM`/`SM` with `LOBPCG` curve seem good for small matrix size but at a matrix size of 80, they have a jump and a big one for the `SM` version.

---

Additional information:
- This behavior does not seem to depend on the values in the matrix neither if they are real nor complex.
- The matrix size for which the jump occurs depend on the number of singular values ask (here 16/32).
- SciPy/NumPy/Python version information
    ```python
    >>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
    1.7.3 1.21.4 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)
    ```

---

Code for the plot:
```python
import matplotlib.pyplot as plt
import numpy as np
from scipy.sparse import diags
from scipy.sparse.linalg import svds


def matrix(mat_size):
    mat_diag = np.full(mat_size, -2)
    mat_hors_diag = np.full(mat_size - 1, 1)
    return diags((mat_hors_diag, mat_diag, mat_hors_diag), (-1, 0, 1))


def LM_Arpack(mat_size):
    mat = matrix(mat_size)
    svd_16 = svds(mat, k=16, which="LM", return_singular_vectors=False, solver="arpack")
    svd_32 = svds(mat, k=32, which="LM", return_singular_vectors=False, solver="arpack")
    return np.abs(svd_16 - svd_32[-16:]).max()


def LM_LOBPCG(mat_size):
    mat = matrix(mat_size)
    svd_16 = svds(mat, k=16, which="LM", return_singular_vectors=False, solver="lobpcg")
    svd_32 = svds(mat, k=32, which="LM", return_singular_vectors=False, solver="lobpcg")
    return np.abs(svd_16 - svd_32[-16:]).max()


def SM_LOBPCG(mat_size):
    mat = matrix(mat_size)
    svd_16 = svds(mat, k=16, which="SM", return_singular_vectors=False, solver="lobpcg")
    svd_32 = svds(mat, k=32, which="SM", return_singular_vectors=False, solver="lobpcg")
    return np.abs(svd_16 - svd_32[:16]).max()


N = np.arange(33, 129)
lm_arpack = [LM_Arpack(mat_size) for mat_size in N]
lm_lobpcg = [LM_LOBPCG(mat_size) for mat_size in N]
sm_lobpcg = [SM_LOBPCG(mat_size) for mat_size in N]

fig, ax = plt.subplots(constrained_layout=True)

ax.semilogy(N, lm_arpack, ".--", label="LM Arpack")
ax.semilogy(N, lm_lobpcg, "+--", label="LM LOBPCG")
ax.semilogy(N, sm_lobpcg, "x--", label="SM LOBPCG")

ax.grid(True)
ax.set_xlabel("matrix size", fontsize=15)
ax.set_ylabel("difference", fontsize=15)
ax.legend(loc=2, fontsize=15)

plt.show()
```

**Comment by lobpcg** [comment]
Thanks for raising the issue! Here are some explanations of the observed behavior:

For the smallest singular values, svds itself has problems that hopefully get resolved with https://github.com/scipy/scipy/pull/11829

For the largest singular values in your tests svds probably hits the undocumented inconsistency in the default values of maxit in arpack and lobpcg, as well as the default tolerance, which svds does not even allow to set and propagate to the solvers. The default  default tolerance in lobpcg is  n*sqrt(eps), which is much larger than the default in arpack that attempts to be the utmost accurate. 

Another undocumented in svds feature of lobpcg is that for small matrix sizes lobpcg does not bother to run instead converting sparse matrices into dense and calling a dense solver which gives machine precision accuracy - that's why you see the jump in accuracy as you increase the matrix size.  It's documented in lobpcg docstring, but not in svds.

So testing lobpcg for small size matrices is meaningless. For large size matrices, you can try varying maxit, which is defaulted to 20 in https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/_eigen/lobpcg/lobpcg.py . That should probably resolve the big difference that you observe.

**Comment by zmoitier** [comment]
Thank you for the explanation. It does seem that increasing `maxiter` allows to recover the double precision for the `LM` case and at least go to single precision in the `SM` case.

**Comment by lobpcg** [comment]
Thanks for confirming. The single precision tolerance is the lobpcg default for double precision calculation, which is consistent with your results. Please keep the issue open to motivate at least improving the svds documentation.


________________________________

**Comment by zmoitier** [comment]
I am wandering why `maxiter` default is a constant, would it be better if it depend on the size of the matrix.

**Comment by lobpcg** [comment]
It's related to the distribution of the eigenvalues and the quality of the initial approximation, rather than the size of the matrix. It's chosen intentionally low, and the latest revision of lobpcg gives a warning if the chosen tolerance is not met, to attract attention of a user to its importance .

**Comment by zmoitier** [comment]
That would be a nice addition because I first try to increase the Krylov dimension but that did not works and I did not think about maxiter.

**Comment by lobpcg** [comment]
@zmoitier It appears that the issue has been resolved and could be closed?

**Comment by zmoitier** [comment]
Yes, it does. Thanks for letting me know.
