### ISSUE TITLE
REL: Should `LICENSE.txt` be copyrighted to 2021/22?

### ISSUE THREAD

**Issue by Kai-Striega** [scipy/scipy#15282]
### Describe your issue.

The file https://github.com/scipy/scipy/blob/master/LICENSE.txt lists the current copyright status as "Copyright (c) 2001-2002 Enthought, Inc.  2003-2019, SciPy Developers." does this need to be updated to 2021/22 or has the copyright changed since then?

**Comment by rgommers** [comment]
yes indeed - want to open a PR for that?

**Comment by Kai-Striega** [comment]
Yes. I'll get it done. However I might wait until 2022 that way I'll only need to open a single PR

**Comment by tupui** [comment]
According to this https://hynek.me/til/copyright-years/ we could also drop the end year.

**Comment by rkern** [comment]
I think his analysis is wrong, though, at least for US law. His footnote points to why. He keeps updating the end year of the copyright notice on his blog as a whole because he keeps publishing more articles. We keep adding code to `numpy`. New code added today is seeing its "first publication" in 2022, so a [US-Code-compliant](https://www.law.cornell.edu/uscode/text/17/401) copyright declaration would have to have 2022 (contra the article, for a continuously modified compilation work like `numpy`, the _initial_ date is the one that's optional).

Of course, nothing _forces_ us to have a date (or for that matter, a copyright declaration at all), but a well-formed copyright declaration is good license hygiene and helps preserve a few legal options (in the US). If it's restrained to just the `LICENSE.txt` file rather than splatted on every code file, then it's a very minimal burden.

**Comment by tupui** [comment]
ok but what about Google and Netflix? I checked some of their pinned repo and they all just have the start date. I would assume they had this checked by their lawyers.
(To be clear, I am not against adding the end date, just for the discussion and my understanding).

**Comment by rkern** [comment]
I generally don't look to the actions of large companies as touchstones for correct (or conservative) legal reasoning. We don't actually have their legal team's legal reasoning in front of us, only what they decided to _do_. Legal teams give you options, and then you act on those options, accepting a certain set of compromises balancing the legal consequences outlined by your legal team with other aspects of your business. They have their own goals, resources, and risk profiles that are distinct from ours. They have large teams of lawyers and systems in place (e.g. contributor agreements, copyright registration, employee activity tracking, etc.) that give them more options to defend their rights in court if they need to. We don't have those same resources. Those legal teams could well have given a legal reasoning reading the US Code the same way that I do, but the company still decided to trade for easier the management of the date knowing that their other investments would help them more.

Again, nothing forces anyone to have a complete and conforming copyright declaration. Our work is copyrighted when we create it whether or not we slap on a copyright declaration; that's not a concern. It just preserves a few options when going to court (it helps put the onus on the copyright infringer to prove some things rather than us having to prove things, but only a little bit). For those large companies, those options aren't important compared to what they are getting from their other investments in legal teams and formal procedures.

For us, they are also probably unimportant, especially given our very liberal license. For that matter, I also don't _really_ care about removing the end date (or opting for Microsoft's `<start_year> to present` approach). But I do care about doing it for the right reasons, and that article (which I've seen before, so I've had this verbiage all prepared) has, I think, all the wrong reasons. Both a misreading of the relevant law (IMO) and dubious "the Big Guys do it, so it's legally correct" reasoning.
