### ISSUE TITLE
RFC: unify all developer CLI tools

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#15489]
We have accumulated a _lot_ of dev automation tools, and our homegrown `runtests.py` CLI which is slightly clumsy. Here is an overview:
- `runtests.py` - and its sibling `dev.py` for Meson
- `doc/Makefile` - build docs and upload them
- `pavement.py` - uses Paver for some release tasks
- `tox.ini` - contains `flake8` and `pycodestyle` config, we don't use Tox itself anymore
- `tools/authors.py` / `tools/gh_lists.py` / `tools/download-wheels.py` release scripts
-  tasks for which we have no CLI, just docs that we hope people read before doing the thing they need:
    - dev environment setup - `apt-get xxx && pip install yyy` or `conda env create -n environment.yml`
    - `git` - for a lot of things, but with submodules it is getting less intuitive
    - `docker` - for Gitpod config, see `tools/docker_dev`
    - `act` - for running GitHub Actions jobs locally

Many of these things are badly maintained or only half in use. `runtests.py` has been the best maintained so far, but it's not ideal because task dependencies are manually dealt with in `if args.some_task: ...` logic.

**Proposal**: let's create a new and more ergonomic CLI for all development tools.

Ideally it has these properties:
- Completeness: we have all normal/recurring development tasks implemented in it
- Conciseness: (for example) `do bench` instead of `python runtests.py --bench`
- Self-documenting: it should be easy to read the CLI implementation and figure out what actual commands are being run (or maybe the CLI can print the command)
- Hierarchical: if there are a number of docs-related tasks, they should be discoverable and runnable like: `do doc build`, `do doc show`, `do doc upload`, etc. Same for CI and release tasks; top-level tasks should be for regular contributions/development
- Genericity: it should make as few assumptions as possible (e.g., don't assume you're developing in a virtualenv), it should be implemented in a way where the non-SciPy-specific parts can be reused in other projects that use `pytest`/`asv`/`meson`/`sphinx`, and it should work in harmony with the tools it wraps so one can use those directly

There will be tools where it doesn't make sense to wrap them (e.g., [gh](https://cli.github.com/)) however it would be great if those tools could be made discoverable as well so it doesn't take new contributors years to find out about all of them.

I don't have a proposal (yet) for which framework or task runner to use. There are many. It looks like we need a straightforward task runner that understands dependencies between tasks and makes it easy to implement a CLI. Something like:

- [Airflow](https://airflow.apache.org/docs/apache-airflow/stable/index.html)
- [Celery](https://docs.celeryproject.org/en/stable/index.html)
- [doit](https://pydoit.org/contents.html)
- [Invoke](https://www.pyinvoke.org/)

Ones that I know of but aren't good choices: Paver (obsolete), Fabric (superceded by Invoke), Luigi (superceded by Airflow), Tox/Nox (they insist on environment activation/updates for every task).

Airflow is on the complicated (but powerful) side, `doit` is on the simple side. I don't have a lot of experience with any of these tools, so don't have a good sense for the features vs. simplicity tradeoff or other pros/cons. Suggestions very welcome.

**Comment by tylerjereddy** [comment]
There's also stuff like `openblas_support.py` and `refguide_check.py`. I'm not taking any particular side, but a detailed discussion might also consider the merits of avoiding "mega-tools" in favor of [Unix Philosopy](https://en.wikipedia.org/wiki/Unix_philosophy):

> Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".

If say the NumPy *and* SciPy core teams can both be convinced that something like this is needed, that might help establish confidence that we're not building our own little magical thing. If both projects were to be convinced, where might the tool reside?

**Comment by tupui** [comment]
For completeness, in the list we can add
* [Click](https://click.palletsprojects.com/en/8.0.x/)
* [Typer](https://typer.tiangolo.com)

And what about an unpopular option, `make`? BUT, it must be simple without wizardry.

Otherwise `doit` is the new cool kid in town and looks indeed cool. If we make it simple, it could also be plugged with [Gooey](https://github.com/chriskiehl/Gooey) to make a GUI. 

No matter the solution we select, I think it's important we keep it simple so that we use and update it. If you need to sit down and dig into it to make some adjustment, it will likely not happen.

**Comment by andyfaff** [comment]
(side question - what's the invocation for running the lint check locally?)

**Comment by mdhaber** [comment]
`python tools/lint_diff.py`. Accepts `--files scipy/optimize/test_linprog.py` etc..

**Comment by rgommers** [comment]
> If say the NumPy _and_ SciPy core teams can both be convinced that something like this is needed, that might help establish confidence that we're not building our own little magical thing. If both projects were to be convinced, where might the tool reside?

If there's a generic part, it could live under the numpy or scipy org, doesn't really matter to me. That may be minor though, I'm not sure how separable it is into its own repo (my guess is it won't be). It's more a pattern that can be synced. But well, TBD.

> I'm not taking any particular side, but a detailed discussion might also consider the merits of avoiding "mega-tools" in favor of [Unix Philosopy](https://en.wikipedia.org/wiki/Unix_philosophy):

I don't think it'll be a mega-tool, we won't get rid of (e.g.) `refguide_check.py` or `authors.py`. We just make it more discoverable and with a uniform interface. This is a real problem - most maintainers can't even keep track of all the scripts and tools we have, and contributors have no chance at all to find it all.



> For completeness, in the list we can add [Click](https://click.palletsprojects.com/en/8.0.x/), [Typer](https://typer.tiangolo.com)

Interesting question. From what I can tell these are kind of different (more like "`argparse` on steroids" than "a modern `make`"). I'm thinking the task runner is the more important part, but having a polished CLI will be quite nice as well. I also just saw the announcement of [rich-cli](https://github.com/Textualize/rich-cli), which is in the same bucket as Click and Typer it looks like, and `rich` is wildly popular right now (it's even in `pip` 22.0).

> And what about an unpopular option, `make`?

Can I just say "no" without further comment?

> No matter the solution we select, I think it's important we keep it simple so that we use and update it. If you need to sit down and dig into it to make some adjustment, it will likely not happen.

Agreed.

I wanted to get some initial feedback, and the questions helped trigger some ideas. Maybe the next step is to build a small prototype to get a better sense for how much room for improvement there is.

**Comment by tupui** [comment]
> Interesting question. From what I can tell these are kind of different (more like "`argparse` on steroids" than "a modern `make`"). I'm thinking the task runner is the more important part, but having a polished CLI will be quite nice as well. I also just saw the announcement of [rich-cli](https://github.com/Textualize/rich-cli), which is in the same bucket as Click and Typer it looks like, and `rich` is wildly popular right now (it's even in `pip` 22.0).

Seeing rich-cli now! Looks nice.

> > And what about an unpopular option, `make`?
> 
> Can I just say "no" without further comment?

😅 sure, I trust your judgment.

> I wanted to get some initial feedback, and the questions helped trigger some ideas. Maybe the next step is to build a small prototype to get a better sense for how much room for improvement there is.

Once we have a requirement list, I could help with that if wanted. I think that would be on scope with what I could do.

**Comment by eli-schwartz** [comment]
Given SciPy is committing to Meson + ninja, any unpopular `make` option should realistically be automatically superseded in favor of ninja, which is essentially "`make` except no pattern rules, use a ninja generator".

Specifically, you could create meson.build `run_target()`s or `alias_target()`s for each tool tied to convenient target names instead of script file paths.

It does of course support depending on built targets (and other run_targets), but the discoverability of targets would be hindered by tab completion of ninja listing tons of buildable files in among the handful of tool names. I guess you could add another tool called `ninja help` -> `./tools/help.py` to print some kind of guidance. Although that may be trying too hard to shoehorn ninja into working.

Anyway, `make` has a superset of the reasons why `ninja` might not be strictly appealing, on top of requiring both `make` and `ninja` which feels... bizarre.

**Comment by ilayn** [comment]
I am in favor of such CLI but I think much of the mystery comes from the undocumented "clever" code. Otherwise we can always pick a DAG and be done with it. But the clever code has so many "refactored" pieces that doesn't make any sense to a person who is coming in with fresh gray-matter. Hence I agree with all points but "Genericity" and I'd say let others shoot their own feet. I think much of the clever code is a result of that grand but unrealistic goal making the code way too abstract than necessary. 

And please let `make` and if possible `cmake` die, it is long overdue. Seemingly nobody is compiling this many wild pieces into one wheel on every possible architecture thus contrary to whatever some die-hard proponent might say, I am willing to die on that hill.

**Comment by matthew-brett** [comment]
@eli-schwartz - just checking I didn't miss anything - but am I right in saying that using `run_target` or `alias_target` will mean that we end up typing something like:

```
meson compile refguide_check
```

or similar?

**Comment by andyfaff** [comment]
> Many of these things are badly maintained or only half in use. runtests.py has been the best maintained so far, but it's not ideal because task dependencies are manually dealt with in if args.some_task: ... logic.

I'd be willing to bet that the overwhelming majority of interactions with scripts will be people wanting to:

- build scipy, so `python dev.py --build-only` (or historically `pip install .`)
- use `runtests.py` to run tests.

If this thesis is true, then the majority of our time should be getting the functionality in `runtests.py`/`dev.py` to be smooth sailing. In addition, if the majority of time is spent using a single script then it may not justify a big do-it-all tool.

The other tools are mainly used by devs, and cleaning those tools up may not give as much a return as one would suppose.

However, these points fade into the background if someone wants to spend time creating the replacement tooling.

**Comment by eli-schwartz** [comment]
@matthew-brett

Yes.

**Comment by stefanv** [comment]
I'm looking at rich-cli, and it doesn't look like a fancy argparser; more like a highlighter of sorts?

Here's another one: https://github.com/google/python-fire

**Comment by tupui** [comment]
> Here's another one: [google/python-fire](https://github.com/google/python-fire)

For various reasons, I would not build any long term project based on any GG technology 😅

**Comment by tylerjereddy** [comment]
I've always found the Rust community [`cargo` tool](https://doc.rust-lang.org/cargo/index.html) to be pretty ergonomic. From uploading packages/releases to compiling, linting, building docs, running (doc) tests, etc.

A single abstracted tool with its own thorough maintenance and documentation is probably bigger than our scope, though some aspects of the design may merit emulation.

**Comment by ev-br** [comment]
Just tried `$ python do.py doc`. Works great! 
A minor gripe is that it ends with
```
dumping object inventory... done
build succeeded.

The HTML pages are in build/html-scipyorg.

Build finished. The HTML pages are in build/html-scipyorg.
```
and it took me a while to figure out it's not `scipy/build` (that's meson/ninja stuff) but `scipy/doc/build`. The path relative to `doc/` was natural in the previous workflow, which has `cd doc && make html-scipyorg`, but I'd rather not even remember that that even existed :-).

**Comment by rgommers** [comment]
> A minor gripe is that it ends with

I'll get rid of that last line in the Makefile, it's duplicate anyway. The lines above it come from Sphinx, so we can't remove them. Instead, we should end with a new message. @schettino72 I'm trying to add it, but I'm not sure how - the [pydoit docs on delayed task creation](https://pydoit.org/task-creation.html?highlight=actions#delayed-task-creation) don't show how to add a message to this doc build command after it is done:
```python
    def task_meta(...):
        ...
        return {
            'actions': [
                # move to doc/ so local scipy does not get imported
                (f'cd doc; env PYTHONPATH="{dirs.site}" '
                 f'make {" ".join(make_params)} {targets}'),
            ],
            'task_dep': task_dep,
            'io': {'capture': False},
        }
```
Is it possible to append a message?

**Comment by rgommers** [comment]
Ah, easy enough - thanks!

**Comment by HDembinski** [comment]
I found this thread as a first-time contributor, who struggles with the fact that the developer docs recommend to run `python dev.py lint` but this command does not do the same as python tools/lint_diff.py. Wouldn't it be useful for first-timers if the two should do the same?

Besides, `python dev.py lint` takes a good while to run and shows stuff unrelated to me.

**Comment by HDembinski** [comment]
It would also be more developer-friendly if `python dev.py test` would forward all arguments to pytest. I missing `-k` from pytest and `--pdb` in particular.

`python dev.py test -t scipy.stats.tests.test_multivariate::TestConditionalTable`

is quite a mouthful to write compared to (theoretically) `python dev.py test -k TestConditionalTable`

**Comment by HDembinski** [comment]
Excellent, thank you for the hint. Now that I look at the docus for dev.py test, I see that this was actually documented and I just missed it. Sorry for the noise! 🤦

**Comment by ev-br** [comment]
I think it would be nice to have something like `$ python dev.py lint -b main` to run `$ python tools/lint_diff --branch main`.

As a data point, I was just earlier today looking into the azure yml file to find out the CI linting invocation.

**Comment by tupui** [comment]
On the linting part, at the risk of repeating myself, I really think it would be better to rely on pre-commit hooks so we don't have to care anymore. We keep circling around the matter and saying *it's not worth it since we don't have styling discussions*, but it seems like we do and it does take more maintenance time than it should.

**Comment by stefanv** [comment]
I've started working on a tool that generalizes `dev.py` across projects. It's not as fancy as SciPy's version, but it is configurable, and does the basic build, install, shell, etc. Next step is to add custom scripts, and once that's ready any project will be able to customize it fully.

However, after writing this first version, I've come to the same conclusion as @andyfaff: the tool is not really necessary *once we get Meson to do in-place developer wheels*. Once we can do that, workflows can be standardized across projects:

**developer install**: `pip install -e .`
**wheel install**: `pip install . --no-build-isolation`
**testing**: `pytest --pyargs modulename`

But, this really *does* require implementing the Meson-built developer wheels (as I discussed with @eli-schwartz), because developers depend on in-place installations for fast edit-test cycles. FWIW, while the current SciPy approach (setting the PYTHONPATH) is workable for most of us, those who use Advanced(TM) IDEs struggle, since the IDEs expect the build product to live alongside the code. I'm not 100% sure whether the developer wheels will address that, although it might.

(With "developer wheels" I mean: build into a target directory by symlinking all unmodified files, and adding in compiled products.)

**Comment by stefanv** [comment]
> After having been forced to use pre-commit in a few other projects recently, I now have an opinion: it's a really bad experience. It typically doesn't work out of the box, it doesn't work with conda-forge at all, and it tends to point at lots of forks of tools of random individuals I don't know (but have to trust). If folks who like it want to add pre-commit to make their lives easier, sure. But to require it seems like a nonstarter.

I was surprised to read this! My experience has been quite the opposite: install the hook, commit twice (since code gets reformatted on the first commit), and forget about it. Compare that to the experience of working on SciPy: commit, wait for CI to fail, commit again, etc.

Either way, I don't think we have to *force* anyone to use it. As long as we use `pre-commit` to do the CI run, those who like it can run it locally, and the rest can use the CI to check their code the way it currently does.

A recommendation by @jarrodmillman that I like: only use linting tools that can auto-fix. Otherwise, it becomes a frustrating contributing experience (where you have to work hard to satisfy the linter, instead of the linter helping you).

**Comment by ev-br** [comment]
ISTM there are two separate discussions here, as long as using these hooks is optional (and I'm rather strongly into them being optional):

- evangelizing (is that a word?) their use --- sounds like a blog post with instructions would be a helpful first step
- how to simplify and streamline user experience for those who are not using them. In that vein, a command-line improvement to ti fix the "wait for the CI to fail" part of https://github.com/scipy/scipy/issues/15489#issuecomment-1281170323 would be helpful.

My 2c

**Comment by stefanv** [comment]
>     * evangelizing (is that a word?) their use --- sounds like a blog post with instructions would be a helpful first step

I'm not sure how much there is to communicate here.

```
pip install pre-commit
pre-commit install  # do this once
```

Then just continue to develop as usual. When you commit, some checks will be done. If they fail, formatting fixes will be made to your code, and you commit the resulting files.

**Comment by stefanv** [comment]
Oh, forgot to mention, the simple generalized version of `dev.py` is at https://github.com/scientific-python/dev.py.  It's very alpha, but feel free to check it out.  I'll probably implement external hooks today.

**Comment by rgommers** [comment]
> > It typically doesn't work out of the box, it doesn't work with conda-forge at all
> 
> Do you refer to having to install the hooks? Or that the hooks install in their own venv? I don't see how that's a problem.

No, literally what I said: despite multiple tries, I did not get it to work at all, after following both project instructions and the pre-commit docs. So I'm back to debug by CI, except projects using pre-commit also have the annoying habit of turning on a ton of very picky checkers, so things like not alphabetically ordering imports or using double instead of string quotes is now an unnecessary CI error.

I think the problem was that a venv need a base interpreter, and it doesn't work well if the only Python available is an unusual one (to pre-commit) like a conda-installed one. 

> However, after writing this first version, I've come to the same conclusion as @andyfaff: the tool is not really necessary _once we get Meson to do in-place developer wheels_. Once we can do that, workflows can be standardized across projects:

I'm not sure I agree. Part of the problem the CLI is addressing is that everything is discoverable. It's one interface, rather than 10+. If you go back to everyone needing to know `pytest`, `asv`, `mypy`, `sphinx`, linters, and a bunch of one-off scripts - that's not a good thing.

Not every project is as complex as SciPy and needs as many things, but we have enough evidence that even maintainers don't know all the interfaces needed in the old way of doing things.

**Comment by stefanv** [comment]
> Not every project is as complex as SciPy and needs as many things, but we have enough evidence that even maintainers don't know all the interfaces needed in the old way of doing things.

Well, here's a first attempt at a generic solution then: https://github.com/scientific-python/dev.py

(I finished implementing custom hooks.)

Take a look and let me know what you think. It's not as full-featured as the SciPy one, but hopefully a simple, clean, generalizable start for other projects to adapt.  I've used it to build and test scikit-image, and It Works (TM).

The built-in build commands only work for Meson-based projects ATM (but, of course, a project can write their own hooks that use setuptools instead).

**Comment by eli-schwartz** [comment]
BTW I tend to agree with @rgommers about pre-commit being annoying and painful to deal with, from a slightly different perspective.

I don't love tools that try to create even more venvs for me, when I have perfectly good versions of these tools available in a managed system python that keeps very much up to date for me, and even does something that PyPI cannot do, and in fact basically removed support for, which is codesigning (no, having the PyPI website itself generate error-detecting checksums is not the same as codesigning; PyPI never really offered codesigning as a first-class feature, but it used to display PGP signatures, and that got removed since "only distros use it". Meanwhile, we are at 9 years and counting for PEP 458 deployment, which only covers the minimum security model, securing software immediately after upload to PyPI -- end to end security is still a draft PEP). And people who use pre-commit tend to use tons of projects I've never heard of, by *people* I've never heard of, which I would rather not use unless I've put in much more effort than it is worth to investigate the trustworthiness of running these peoples' software. I can't get the software from my distro that I *do* trust, and, half the time (I'm sure conda has the same problem) I cannot even check if people I trust do in turn trust said project.

So actually I don't use pre-commit, but just wait for CI to fail. Then pre-commit running in the cloud decides to append to my PR, messing up my clean commit history with "fixup" commits that don't survive local iteration. :D

What it amounts to, then, is yet another way to run a linter in CI, then apply recommendations locally. But this particular way of running a linter in CI is... really noisy. In the sense that there are repositories where there are weekly or more commits that just update the pre-commit configuration, usually submitted by bots, and, sometimes, that means a project which seems to be regularly committed to, until you realize that every commit for the past 4 months is just pre-commit configuration commits.

This makes me feel like pre-commit is just a bad idea, implemented inelegantly, and my opinion on the service as a whole just tanked.

You don't even need it. It's reasonably trivial to implement a git-pre-commit hook that simply runs a command such as `python dev.py ...`. My private implementation doesn't mess with the current working directory (staging and *hopefully* restoring uncommitted changes), which, while implemented badly, is the only interesting feature I see in pre-commit.

...

Contrast that to "just install the latest version of flake8, pylint, and mypy in CI, and twice a year fix the failing CI when a new version of the linter learns to complain about something new by default". In practice, at least for meson, that only really tends to happen with mypy.

I have once or twice pondered trying to do for our linter runs, what we do for OS tests. Which is to have a dedicated workflow that runs once a week, tries to build fresh docker containers with updated OS runtimes, and the latest versions of various dependencies, run the testsuite in those docker containers, and then if everything passes, upload the fresh docker container to the docker hub. These images are then used to run Pull Request CI using the latest versions of all dependencies that definitely passed CI on git master. If the images fail to build, this might be a temporary failure or indicate something is actually broken/incompatible with newer versions of $WHATEVER, and that can be investigated at leisure without interrupting normal development.

Hooking something like that up for the linter runs never really felt worth it for me because of the low risk of regressions, but of course YMMV. I do think if you DO want pinned linters, the approach as a whole is ***significantly*** more pleasant than dealing with that noise in constantly drip-fed micro updates to the main repo. You literally don't have to do ANYTHING, and you automatically get the advantage of being able to test PRs using the latest version of the linter that also cleanly passes on git master.

**Comment by stefanv** [comment]
> Meanwhile, we are at 9 years and counting for PEP 458 deployment, which only covers the minimum security model, securing software immediately after upload to PyPI -- end to end security is still a draft PEP).

Security in the Python ecosystem is a major concern.

> So actually I don't use pre-commit, but just wait for CI to fail. Then pre-commit running in the cloud decides to append to my PR, messing up my clean commit history with "fixup" commits that don't survive local iteration. :D

I don't think tools should be making commits on your behalf, ever!

> What it amounts to, then, is yet another way to run a linter in CI, then apply recommendations locally.

The idea, really, is the other way around: to be able to run whatever is run on CI locally.  You don't need pre-commit to do that, `dev.py` or whatever other avenue you choose would be fine. Having it as a pre-commit hook is very convenient, though.

> But this particular way of running a linter in CI is... really noisy. In the sense that there are repositories where there are weekly or more commits that just update the pre-commit configuration, usually submitted by bots
...
> This makes me feel like pre-commit is just a bad idea, implemented inelegantly, and my opinion on the service as a whole just tanked.

I agree that regularly updating linter configs is a dumb idea, and we shouldn't do that! But I also don't think we should blame the tool for the crazy things people do.

> Contrast that to "just install the latest version of flake8, pylint, and mypy in CI, and twice a year fix the failing CI when a new version of the linter learns to complain about something new by default". In practice, at least for meson, that only really tends to happen with mypy.

This is exactly what pre-commit automates. And I don't see how your security concern is addressed by this method: you're installing the same software as pre-commit would into an isolated environment, except into your default development environment? 

> I have once or twice pondered trying to do for our linter runs, what we do for OS tests. Which is to have a dedicated workflow that runs once a week, tries to build fresh docker containers with updated OS runtimes, and the latest versions of various dependencies, run the testsuite in those docker containers, and then if everything passes, upload the fresh docker container to the docker hub. These images are then used to run Pull Request CI using the latest versions of all dependencies that definitely passed CI on git master. If the images fail to build, this might be a temporary failure or indicate something is actually broken/incompatible with newer versions of $WHATEVER, and that can be investigated at leisure without interrupting normal development.

I'm curious whether you've tried https://github.com/nektos/act.  I wish we could run Windows images on Linux; that would *really* help things along!

[This tmate action](https://github.com/mxschmitt/action-tmate) is the best alternative I've found so far.

FWIW, re: the pre-commit comments, my gentle pushback is just that—some points to think about. I am not too invested in changing the linting system, but would like to see an easy way to get `python runtests.py --pep8 --mypy`—applied only to the diff—into a pre-commit hook. Maybe that option already exists?

**Comment by eli-schwartz** [comment]
> I agree that regularly updating linter configs is a dumb idea, and we shouldn't do that! But I also don't think we should blame the tool for the crazy things people do.

Well, but pre-commit's design is that the version tag to use is inherently part of the per-linter config.

And also, the same Github App (https://pre-commit.ci) that checks out your repo and runs pre-commit in order to submit CI statuses, also submits those (weekly) PRs to update the linter config.

The *only* options it seems to offer are whether you want to get those PRs weekly, monthly, or quarterly. Setting the target branch to empty doesn't mean disable the auto-update, it means target the default branch.

So IMHO it's impossible to use it sensibly unless you *only* use it locally. But the point is to run the same thing locally as well as in CI... might as well investigate allowing dev.py to run as a git-pre-commit hook instead.

> This is exactly what pre-commit automates. And I don't see how your security concern is addressed by this method: you're installing the same software as pre-commit would into an isolated environment, except into your default development environment?

Yes, but importantly, I can opt into making that default development environment use a package manager such as apt, pacman, rpm, or conda, which have solved the supply chain security issue and which I already trust for the vast majority of the software on my system. So I know that the connection between me and ~~PyPI~~ the Linux distro repository was not intercepted by malware, and that's a whole class of worries I just... don't even need to think about.

> I am not too invested in changing the linting system, but would like to see an easy way to get `python runtests.py --pep8 --mypy`—applied only to the diff—into a pre-commit hook. Maybe that option already exists?

This fairly Meson-specific script in .git/hooks/pre-commit might serve as inspiration for the general approach:
```bash
#!/bin/bash

mapfile -d '' changed < <(git diff --cached --name-only -z --diff-filter=ACM mesonbuild/'*.py')

# create a temporary copy of what would get committed, without unstaged modifications
workdir=$GIT_DIR/.pre-commit-workdir
fakecommit=$(git commit-tree -p HEAD $(git write-tree) -m ...)

if ! [[ -d $workdir ]]; then
    git clone -qns "$GIT_DIR" "$workdir" || exit
fi

unset "${!GIT_@}"
cd "$workdir"
git checkout -q $fakecommit

# run a couple of repo-specific lints; if any of them fail, remember that, and set an overall hook failure status
ret=0

flake8 "${changed[@]}" || ret=1
pylint "${changed[@]}" || ret=1
./run_mypy.py "${changed[@]}" || ret=1

exit $ret
```

Because I wrote this to run linters only, it's a safe assumption that I don't need cached state such as configured build directories. In theory, some people do run build+test cycles in their pre-commit hooks, personally I do not see such value for that.

> I'm curious whether you've tried https://github.com/nektos/act. I wish we could run Windows images on Linux; that would _really_ help things along!
> 
> [This tmate action](https://github.com/mxschmitt/action-tmate) is the best alternative I've found so far.

I tried it once or twice, it's pretty cool. But I'm also very fond of https://man.sr.ht/builds.sr.ht/ -- which automatically exposes ***any*** failing build via ssh, limited to the actor. It doesn't provide Windows images either, though.

> FWIW, re: the pre-commit comments, my gentle pushback is just that—some points to think about. I am not too invested in changing the linting system, but would like to see an easy way to get `python runtests.py --pep8 --mypy`—applied only to the diff—into a pre-commit hook. Maybe that option already exists?

`flake8 --diff` exists, but it is deprecated and slated for removal, because it doesn't detect new lint issues that are triggered by the diff, but appear elsewhere in the file. It's probably not required unless you're incrementally fixing a codebase -- running on all files produces correct results, and running only on modified files produces correct results faster.

> **EDIT:** I thought the answer might be `python dev.py lint`, which says ":dash: run flake8, and check PEP 8 compliance on branch diff", but when I run it on a checked out main branch, it still returns a bunch of errors (and unfortunately also does not auto-fix anything).

Not all linters can auto-format a fix, IIRC flake8 has rejected suggestions to implement such a thing because it's too complex to get correct.

**Comment by stefanv** [comment]
> Well, but pre-commit's design is that the version tag to use is inherently part of the per-linter config.

I think there's some confusion here between the Github app (which I haven't seen used in any of our projects) and the tool (https://pre-commit.com/).

> Yes, but importantly, I can opt into making that default development environment use a package manager such as apt, pacman, rpm, or conda, which have solved the supply chain security issue and which I already trust for the vast majority of the software on my system. So I know that the connection between me and ~PyPI~ the Linux distro repository was not intercepted by malware, and that's a whole class of worries I just... don't even need to think about.

This could be a good feature to add to pre-commit: see if the current environment satisfies the required dependencies, and fail otherwise.

> This fairly Meson-specific script in .git/hooks/pre-commit might serve as inspiration for the general approach:

:pray: 

> `flake8 --diff` exists, but it is deprecated and slated for removal, because it doesn't detect new lint issues that are triggered by the diff, but appear elsewhere in the file. It's probably not required unless you're incrementally fixing a codebase -- running on all files produces correct results, and running only on modified files produces correct results faster.

For SciPy, the time to run on the total repo is unfortunately non-trivial:

```
python dev.py lint  71.94s user 0.97s system 968% cpu 7.526 total
```

**Comment by stefanv** [comment]
Thanks @eli-schwartz, I got it working for SciPy!

```bash
#!/bin/bash

mapfile -d '' changed < <(git diff --cached --name-only -z --diff-filter=ACM -- '*.py')

# create a temporary copy of what would get committed, without unstaged modifications
GIT_DIR=${GIT_DIR:-.git}
workdir=$GIT_DIR/.pre-commit-workdir
fakecommit=$(git commit-tree -p HEAD $(git write-tree) -m ...)

if ! [[ -d $workdir ]]; then
    echo $workdir
    git clone -qns "$GIT_DIR" "$workdir" || exit
fi

unset "${!GIT_@}"
cd "$workdir"
git checkout -q $fakecommit

# run a couple of repo-specific lints; if any of them fail, remember that, and set an overall hook failure status
ret=0

echo -e "** pre-commit linter **\n"
flake8 --config=tools/lint_diff.ini "${changed[@]}" || ret=1

if [[ $ret -ne 0 ]]; then
    echo -e "\n!! Linting failed; please make fixes, \`git add\` files, and re-commit."
fi
exit $ret
```

It runs on any file touched (not just the diff on those files).

To install as a pre-commit hook:

```
ln -s $PWD/pre-commit.sh .git/hooks/pre-commit
```

**Comment by HDembinski** [comment]
> `python dev.py` lint`should also run`flake8`, but for the PEP8 part should be the same. Can you point to a branch where you see one failing but the other passing?

Sorry, I don't have a clean reproducer, but I think this patch here 
https://github.com/scipy/scipy/pull/17237/commits/0545e5e0c3e6601e584e3afda88a8df0cec74795
was a change that I made after `python dev.py lint` gave me no complains (about my new code), but `python tools/lint_diff.py` run by the CI job found those issues. I haven't looked into the implementation, but these two commands apparently do not apply the same rules.

**Comment by rgommers** [comment]
I am inclined to close this issue, since the initial RFC was accepted and fully implemented. We now have at least two new discussions going on, one about a change needed in `dev.py lint` and one about git hooks / pre-commit. Unless there are objections, I'm going to move those things to two new separate issues.

**Comment by stefanv** [comment]
> I am inclined to close this issue, since the initial RFC was accepted and fully implemented. We now have at least two new discussions going on, one about a change needed in `dev.py lint` and one about git hooks / pre-commit. Unless there are objections, I'm going to move those things to two new separate issues.

Makes sense, thanks!

**Comment by rgommers** [comment]
Okay that took me a while - I will close this issue now. I opened gh-17434 to follow up on the potential issue with `lint`. I'm not opening a new issue for pre-commit, because there's too much back and forth there that I don't know how to summarize (or if there's anything in particular that is actionable). If that does need follow-up, it would be great if someone can take that action.


After re-reading the recent comments to be able to open a new issue, I did want to expand on the below comments. Also because I saw scikit-learn devs just make the same wrong assumption / misconception of what this CLI is about - and it's fairly core to the whole point of writing the CLI in the first place:

> > However, after writing this first version, I've come to the same conclusion as @andyfaff: the tool is not really necessary _once we get Meson to do in-place developer wheels_. Once we can do that, workflows can be standardized across projects:
> 
> I'm not sure I agree. Part of the problem the CLI is addressing is that everything is discoverable. It's one interface, rather than 10+. If you go back to everyone needing to know `pytest`, `asv`, `mypy`, `sphinx`, linters, and a bunch of one-off scripts - that's not a good thing.

It is extremely helpful for all commands, and the options they each take, to be in a single place and self-documenting with `--help`. I know I still cannot remember all the obscure invocations one only occasionally does, like getting the durations of slowest tests or building with gcov or Asan. So I'm fairly sure most contributors don't know either - and often won't even realize such things are possible. Therefore:

1. The CLI exposes those things (and in a better way than a ton of outdated html docs do), and
2. It shows the commands that it wraps, so that it actually teaches folks the CLIs of the underlying tools as they go, rather than obscuring them. That way they can dig in further if and when they are ready:

```bash
$ python dev.py build
💻  meson setup /home/rgommers/code/scipy/build --prefix /home/rgommers/code/scipy/build-install

...
💻  ninja -C /home/rgommers/code/scipy/build

...
💻  meson install -C build --only-changed
```

**Comment by stefanv** [comment]
@rgommers What do you think of adding the pre-commit hook above into the repo with instructions for those who want to lint before committing?

**Comment by rgommers** [comment]
Can it turn into a `tools/lint_diff.py` improvement? I'm not against adding a pre-commit hook for those folks that want to use it, but it's not a good idea to make it do anything but call out to the tools that are used in the recommended development workflow(s).
