### ISSUE TITLE
BUG: scipy.stats.powerlaw, why should x ∈ (0,1)? x can exceed 1

### ISSUE THREAD

**Issue by xiasummer** [scipy/scipy#15541]
### Describe your issue.

In current version scipy 1.5.3, I'm generating samples and I find that when x exceed 1, the powerlaw pdf is suddenly 0, I think you must have miss read the powerlaw distribution, it is defined on x > 0 area, not between 0 and 1.

### Reproducing Code Example

```python
a=0.5
powerlaw.pdf(x=0.99, a=a)
powerlaw.pdf(x=1.0, a=a)
powerlaw.pdf(x=1.01, a=a)
```
```


### Error message

```shell
Simply return 0 when x > 1.0
```

### SciPy/NumPy/Python version information

version scipy 1.5.3

**Comment by WarrenWeckesser** [comment]
@xiasummer, take another look at the [documentation](https://scipy.github.io/devdocs/reference/generated/scipy.stats.powerlaw.html).  The distribution implemented by `scipy.stats.powerlaw` *is*, in fact, supported on [0, 1] (assuming that the `loc` and `scale` parameters have their default values 0 and 1, respectively).

If you want a distribution with a power-law PDF that is supported on [1, ∞), you can use [`scipy.stats.pareto`](https://scipy.github.io/devdocs/reference/generated/scipy.stats.pareto.html).

It is impossible for a distribution with a power-law PDF to be supported on [0, ∞), because, depending on the power, the integral of the PDF diverges at x=0 or as x → ∞.

**Comment by tupui** [comment]
I think we could improve a bit the documentation then.

**Comment by NamamiShanker** [comment]
Hey @WarrenWeckesser, I was trying to solve this issue. The documentation clearly states that `loc` and `scale` parameters can scale and shift the distribution in the way you showed. Should we add an example like above in the doc for better understanding?

**Comment by tupui** [comment]
@NamamiShanker documentation improvement are always welcomed, feel free to open a PR to clarify things.

**Comment by mdhaber** [comment]
I would consider this closed if we mentioned that other power law type distributions are available, and link to them in "see also". I don't think this warrants overriding the default distribution documentation. That could also be improved, perhaps, but that would be a separate issue.
