### ISSUE TITLE
WEB/DOC: Docs for 1.8.0 release seem to be missing

### ISSUE THREAD

**Issue by phofl** [scipy/scipy#15540]
https://docs.scipy.org/doc/scipy/reference/

returns a 404 - not found. I think this should return the newest docs?

**Comment by tylerjereddy** [comment]
True, first this will have to be merged: https://github.com/scipy/docs.scipy.org/pull/60
Then, there's another update step.
Then, after that, things may still be broken because of the issue pinned here: https://github.com/scipy/scipy/issues/14267

So, it may be a little bit before things are working "just right." I'd suggest confining most discussion to the above issue perhaps.

**Comment by phofl** [comment]
Thx, I think we can close this then? Missed the pinned issue :(

**Comment by skirpichev** [comment]
@tupui, please reopen the issue.  Docs are incomplete, e.g. objects.inv is missing.

**Comment by tupui** [comment]
> @tupui, please reopen the issue.  Docs are incomplete, e.g. objects.inv is missing.

As we said above, we are well aware of issues and they are all related to the same thing. All these extra issues are creating noise and more more work for us (especially Tyler). Hence I will keep it close and let Tyler reopen if he does need it.
