### ISSUE TITLE
BENCH/CI:  Benchmark timeout

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#15568]
Benchmarks are reliably timing out half way (at a different point). 

This is the first commit which is failing in the history. But there is no link with the changes.

https://github.com/scipy/scipy/commit/3134ab622b09d5d9bfd34c7aabbf8b92a8497723

**Comment by rgommers** [comment]
Can't sleep, so having a look at the daily failure emails. Benchmarks job was last passing on `main` on Feb 4th and failing on Feb 8th:

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/98330/154592086-0ded5f81-15c4-4851-acfd-e7d48067654c.png">

This was the time span of the ASV `0.5` and `0.5.1` releases. Apparently something else broke in `0.5` (see gh-15536) that was fixed in `0.5.1` - but not this timeout issue.

This is probably the same as Pandas is seeing, as reported in https://github.com/airspeed-velocity/asv/issues/1026. Let's keep an eye on that, and pin in the meantime.
