### ISSUE TITLE
ENH: optimize: maintain user dtype

### ISSUE THREAD

**Issue by paulestano** [scipy/scipy#15602]
### Is your feature request related to a problem? Please describe.

The functions defined in `optimize/_differentiable_functions.py` all cast the inputs to float64 before evaluation. This is a problem if you want to work at an arbitrarily chosen precision format or change the precision format dynamically to speed up computation. Moreover these casts generates a significant overhead if the inputs in purposely not already in float64. 

### Describe the solution you'd like.

Remove all the the (useless) calls to `astype(float)` from `optimize/_differentiable_functions.py `

### Describe alternatives you've considered.

Add a param allowing to keep the format provided by the user

### Additional context (e.g. screenshots, GIFs)

NA

**Comment by andyfaff** [comment]
All the code in `_differentiable_functions` is part of the private API that's used to support `optimize` (you can't import by `from scipy.optimize import ScalarFunction`), none of the functions are public. External code should not really be using them, or relying on them to remain the same.

Rather the question might be "why doesn't this `minimize` method respect the float width of my `x0` array". The answer to that is varied. Frequently minimisers are compiled code which means they need to work with float64. Others rely on double precision for estimating gradients, etc. Most of them would require double precision to work properly.

**Comment by paulesta55** [comment]
>All the code in _differentiable_functions is part of the private API that's used to support optimize (you can't import by from scipy.optimize import ScalarFunction), none of the functions are public. External code should not really be using them, or relying on them to remain the same.

Yes but it still heavily impacts a public API (optimizers): this private API is used in lots of Public API because it's wrapping calls to gradients and objective functions. I might have poorly explained it but a simple look at the source code of any optimizers like trust-region ones, makes it clear that any inputs to this optimizers is then casted in float64.

> Frequently minimisers are compiled code which means they need to work with float64. Others rely on double precision for estimating gradients, etc. Most of them would require double precision to work properly.

Erm, no: this overusage of float64 is a thing only in scipy. Lots of modern optimization libraries such as all the deep learning frameworks use single precision by default or sometimes even lower in order to optimize the throughput. I get that scipy runs on CPU so the constraints are different but still: memory-wise it's aweful!
Finally compiled code can obviously handle dynamic typing if well written...

**Comment by tupui** [comment]
A note on:

> Moreover, compiled code can obviously handle dynamic typing if well written...

Yes but it's more maintenance/knowledge to have and also can produce larger binaries. But if you have concrete solutions, we are happy to evaluate them.

**Comment by andyfaff** [comment]
For `minimize` what is the biggest set of parameters that you envisage will be used? Even at the million parameter mark one is only talking about 8Mb instead of 4 Mb, which is miniscule in RAM terms.

I'm not saying that one shouldn't be thoughtful about creating code that respects float width, it's just that I've not heard noise where using supplying float64 to the objective function has really caused issues.

If you look at [Nelder-Mead](https://github.com/scipy/scipy/blob/main/scipy/optimize/_optimize.py#L635), the code there should respect float width. However, it's just not sane to start modifying code in e.g. [SLSQP](https://github.com/scipy/scipy/blob/main/scipy/optimize/slsqp/slsqp_optmz.f) to do the same thing.

We always welcome people willing to help improve optimize, so if you know how to implement the kinds of changes you'd like to see (and evidence for there being performance penalties), then please help to improve the library.
