### ISSUE TITLE
BUG: scipy.special.hyperu(a,b,x) gives wrong values for a close to 0 and b=1, x close to zero

### ISSUE THREAD

**Issue by matthias-baur** [scipy/scipy#15650]
### Describe your issue.

Hello,

I noticed that the special function hyperu(a,b,x) gives output values that are extremely off for some x close to 0, when a is close to 0 and b=1.
In the code example below, I compared the values with mpmath's hyperu. For a certain interval of input values x the output is off by several magnitudes (in this example the errors appear near x=0.01). I see no such errors for a's that are separated sufficiently from 0, e.g. |a|>0.5.

### Reproducing Code Example

```python
import numpy as np
import scipy
import matplotlib.pyplot as plt
import scipy.special
from mpmath import *

a = 0.1
x = np.linspace(0.001,0.05,1001)
y1 = np.zeros((1001,))
y2 = np.zeros((1001,))

for k in range(len(x)):
    y1[k] = scipy.special.hyperu(a,1,x[k])
    y2[k] = mp.hyperu(a,1,x[k])

print(scipy.special.hyperu(a,1,0.01))
print(mp.hyperu(a,1,0.01))

plt.plot(x,y1,'r')
plt.plot(x,y2,'b')
plt.show()
```

### Error message

```shell
no error message, just a miscalculation
```

### SciPy/NumPy/Python version information

('1.1.0', '1.16.2', sys.version_info(major=2, minor=7, micro=16, releaselevel='final', serial=0))

**Comment by matthias-baur** [comment]
upgraded versions:
1.7.3 1.21.5 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

don't appear to give correct results either

**Comment by steppi** [comment]
Hi @matthias-baur, thanks for the bug report. I haven't looked into the details yet, but we're aware that there are some problems with the hypergeometric function implementations in `scipy/special/specfun/specfun.f`. Numerical evaluation of hypergeometric functions involves handling a patchwork of special cases.  We're in the process of re-implementing SciPy's hypergeometric functions in Cython one special case at a time, falling back to the original Fortran implementations for cases that aren't handled yet. I've been working on this for the past 6 months, focusing on the Gaussian hypergeometric function `hyp2f1`, but it's a slow process due to limited spare time on my part. I plan to start working on fixing any problems that may exist in  `hyperu` and would hope to have some fixes ready for version 1.9.

**Comment by matthias-baur** [comment]
Thanks, that's good to hear! I hope this bug can be sorted out without too much hassle.

**Comment by mdhaber** [comment]
I looked into this a bit. Here's what the $\log_{10}$ of the error looks like as a function of $\log_{10}a$ and $\log_{10}z$ at $b=1$.

<details>

```python3
import numpy as np
from mpmath import mp
from scipy import special
import matplotlib.pyplot as plt

def relative_error(res, ref):
    return np.where(res != ref, abs(res - ref) / abs(ref), 0)

@np.vectorize
def hyperu_ref(a, b, z):
    return float(mp.hyperu(a, b, z))

def plot(res, ref):
    err = relative_error(res, ref)
    logerr = np.log10(err)
    logerr[logerr < -15] = -15
    plt.contourf(np.log10(a).ravel(), np.log10(z).ravel(),
                 logerr, cmap='viridis')
    plt.xlabel("log10(a)")
    plt.ylabel("log10(z)")
    # plt.title(title)
    plt.colorbar()
    plt.show()

a = np.logspace(-16, 0, 30)
b = 1
z = np.logspace(-16, 0, 25)[:, np.newaxis]

res = special.hyperu(a, b, z)
ref = hyperu_ref(a, b, z)
plot(res, ref)
```

</details>

<img width="875" alt="image" src="https://github.com/user-attachments/assets/e51c7e1a-970e-4597-bbab-659153529c8f">

The plot looks similar when we replace $a$ with $-a$. Note that the relative error outside the problem region is extremely low, like `1e-14`.

$b = 1$ appears to have a special implementation because if we make it $b = 1 + 10^{-15}$, we get a totally different plot.

<img width="772" alt="image" src="https://github.com/user-attachments/assets/dfe328a2-3745-4b84-a111-5b4ae877f58b">

That error is not great either, but that's a different story.

It would be ideal to fix `hyperu` everywhere, but that's a tall order, and it may take some time. In the meantime, we could patch the problem for $b=1$ when $z < 1$ and $|a| < 1$ using [DLMF 13.3.7](https://dlmf.nist.gov/13.3).

```python3
def hyperu_b1(a, b, z):
    # Using DLMF Recurrence Relation 13.3.7
    a = a + 1
    return -(b - 2*a - z)*special.hyperu(a, b, z) - a*(a-b+1)*special.hyperu(a+1, b, z)
```

The problem goes away, and the error is on par with what it should be for the usual $b=1$ case.

<img width="809" alt="image" src="https://github.com/user-attachments/assets/217c97ac-4af1-45c8-b90b-a5ce55d215b7">

**Comment by steppi** [comment]
Thanks @mdhaber! Very helpful. I'll follow up this week with a PR with your fix.
