### ISSUE TITLE
ENH: Implement `multivariate_normal.fit`

### ISSUE THREAD

**Issue by KOLANICH** [scipy/scipy#15676]
### Is your feature request related to a problem? Please describe.

`multivariate_normal.fit` is not available, but is trivial to implement.

### Describe the solution you'd like.

Should be available.

### Describe alternatives you've considered.

Doing it yourself. It is inconvenient.

### Additional context (e.g. screenshots, GIFs)

```python
def fitGaussian(points):
    m = np.mean(points, axis=0)
    ms = points - m
    c = ms.T @ ms / (len(points) - 1)
    return scipy.stats.multivariate_normal(mean=m, cov=c)
```

**Comment by mdhaber** [comment]
This sounds reasonable. Multivariate distributions do not have a lot of shared functionality, so I think it's OK if this is only defined for `multivariate_normal` initially. 

Not that the univariate `fit` interface is perfect, but it is what we have, so I think the interface of a multivariate `fit` method should be similar. One thing is that it should return a tuple of the resulting location and scale rather than a frozen distributio. Also, if it were to match univariate `fit`, it would accept `fmean` and `fcov` to fix one parameter or the other. In that case, would `c` as calculated above still be the optimal covariance matrix if I were to fix the mean with ` floc`? (and would `m` still the optimal mean if I were to specify `fcov`?)

**Comment by KOLANICH** [comment]
>One thing is that it should return a tuple of the resulting mean and covariance rather than a frozen distribution.

Mean is available as a property of the distribution object, so is covariance matrix.

>In that case, would c as calculated above still be the optimal covariance matrix if I were to fix the mean with floc? (and would m still the optimal mean if I were to specify fcov?)

You have raised the right issue. I'm not even sure it makes any sense to fix the parameters to any value other than true distribution parameter (garbage in - garbage out). So if we assumme that the parameters provided are true, then they are the same we compute ourselves, then there should be no problem to skip their computation and just use the provided ones.

For mean I'm pretty sure that it would be optimal because covariance only squeezes and rotates the distribution, and because mean is a prereq to MLE covariance.

For covariance I'm not so sure.

https://scikit-learn.org/stable/modules/covariance.html should be related.

**Comment by KOLANICH** [comment]
Thanks for the clarification.

>maybe initially we just don't allow the user to fix either (don't accept fmean or fcov).

Good idea.

**Comment by ev-br** [comment]
Poking around shows something called `cov_object`:

```
In [19]: x = np.linspace(0, 5, 10, endpoint=False)
    ...: frozen = multivariate_normal(mean=2.5, cov=0.5)

In [20]: dir(frozen)
Out[20]: 
['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_dist',
 'abseps',
 'allow_singular',
 'cdf',
 'cov_object',
 'dim',
 'entropy',
 'logcdf',
 'logpdf',
 'maxpts',
 'mean',
 'pdf',
 'random_state',
 'releps',
 'rvs']

In [21]: frozen.cov_object.covariance
Out[21]: array([[0.5]])
```

**Comment by KOLANICH** [comment]
Thanks everyone involved into implementing this.
