### ISSUE TITLE
BUG: Extra entries in __all__/dir(...)

### ISSUE THREAD

**Issue by Carreau** [scipy/scipy#15719]
### Describe your issue.

It seem like the following entries in `__all__` are extraneous as they don't exists in the corresponding submodules.

This seem to come after the recent 1.8 refactor. It look like the point was to:
either fails is the name is not in `__all__` with a good explanation message, 
or have a shim with a warning to change imports. 

Unfortunately we end up with the warning and the attribute error, without the better error message.

### Reproducing Code Example

```python
import importlib
mod_attr  = [
    ('scipy.linalg.basic','decomp'),
    ('scipy.linalg.basic','decomp_svd'),
    ('scipy.interpolate.fitpack2','fitpack'),
    ('scipy.interpolate.interpolate','fitpack'),
    ('scipy.sparse.compressed','asmatrix'),
    ('scipy.sparse.compressed','dia_matrix'),
    ('scipy.sparse.compressed','matrix'),
    ('scipy.sparse.coo','matrix'),
    ('scipy.sparse.dia','matrix'),
    ('scipy.sparse.lil','asmatrix')]
import warnings
warnings.filterwarnings('ignore')

for mod_name, attr in  mod_attr:
    mod = importlib.import_module(mod_name)
    print(attr in dir(mod), hasattr(mod, attr)) # all print True, False should either be True/True, or False/False.
```

### Error message

```shell
N/A attribute error in another project that inspects arbitrary modules.
```

### SciPy/NumPy/Python version information

1.9.0.dev0+1646.defbc28 1.22.3 sys.version_info(major=3, minor=10, micro=2, releaselevel='final', serial=0), (Mars 8th, defbc282bcedc777bdd65951653bbe66e560a8ea)

**Comment by Carreau** [comment]
It's unclear to me in each case if a shim is missing, or the entry should be removed from ``__all__``, otherwise I would have sent a pull-request.

**Comment by ilayn** [comment]
Indeed they shouldn't be in that list, at least for linalg parts. Probably we missed them in #15105, 

@Smit-create can you please confirm?

**Comment by rgommers** [comment]
This is a very minor thing with no real-world consequences I think. The `__all__` lists were autogenerated, and those items actually were in the namespaces. Let's take one example: `('scipy.interpolate.fitpack2', 'fitpack'),`
```
>>> from scipy import interpolate
>>> interpolate.fitpack2.fitpack
<module 'scipy.interpolate.fitpack' from '/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/scipy/interpolate/fitpack.py'>
>>> interpolate.fitpack
<module 'scipy.interpolate.fitpack' from '/home/rgommers/anaconda3/envs/dev/lib/python3.9/site-packages/scipy/interpolate/fitpack.py'>
```

So: 
- `interpolate.fitpack` is a private module, now renamed to `interpolate._fitpack`
- `fitpack2` is the same, now `_fitpack2`
- `interpolate.fitpack2.fitpack` is doubly-private. having it in `__all__` is defensible but not necessary, since (a) it's highly unlikely someone would access it like that, and (b) the warning will not be pointing anywhere useful because there's nothing public to use instead in 1.8.0

Removing some entries as done in gh-15766 is fine, doing nothing would be fine too.
