### ISSUE TITLE
DEP: change default of atol in `scipy.sparse.linalg.*`

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15738]
https://github.com/scipy/scipy/pull/8400 promised to change the default of `atol` in `scipy.sparse.linalg.gcrotmk` and has been raising a DeprecationWarning for 4 years. Let's do what needs to be changed to get rid of the warning.

CC @pv

**Comment by h-vetinari** [comment]
Actually, this [applies](https://github.com/scipy/scipy/blame/v1.8.0/scipy/sparse/linalg/_isolve/iterative.py#L95-L102) to many more functions in `scipy.sparse.linalg`.

**Comment by jvsqzj** [comment]
I'd like to give this a go as my first contribution to open source.

I'm currently compiling my scipydev environment on macOS

**Comment by h-vetinari** [comment]
> I'd like to give this a go as my first contribution to open source.

Go for it! 🥳 

Please take note that there are several separate python files in https://github.com/scipy/scipy/tree/v1.8.0/scipy/sparse/linalg/_isolve where this needs to be adapted; not just in the implementation, but also in the docstrings.

**Comment by jvsqzj** [comment]
Sure. I have reproduced the DeprecationWarning. 

I see there is already a method called _get_atol() in iterative.py, which also contains a very similar deprecation warning that can be triggered by other functions. The objective would be to get rid of all of these, from what I read.

Here is a [first draft](https://github.com/scipy/scipy/pull/16050/files) of a quick fix to remove the deprecation warning from this first function call. 

Please do let me know if you think a similar approach would be good for the other affected methods:

```
_get_atol()
gmres()
lgmres()
```
I kindly appreciate any feedback you may have.

**Comment by h-vetinari** [comment]
> Please do let me know if you think a similar approach would be good for the other affected methods:
> 
> ```
> _get_atol()
> gmres()
> lgmres()
> ```

Yes! :)

Everywhere in `sparse/linalg/_isolve` where you find `atol` as deprecated.

**Comment by h-vetinari** [comment]
@pv 
You added the following warning to the docstrings of `atol` (in #8400):
```
        .. warning::
           The default value for `atol` will be changed in a future release.
           For future compatibility, specify `atol` explicitly.
```

Since we're [trying](https://github.com/scipy/scipy/pull/16050) to execute this deprecation (including the change in default value), could you share what you had in mind as the new default? IMO the only reasonable things would be `atol=0` (as any fixed scale might not be adapted to the scale of the problem at hand), but maybe I'm missing something?

**Comment by h-vetinari** [comment]
Ping @pv, if you could let us know about what the default for `atol` was intended to be...

**Comment by j-bowhay** [comment]
@h-vetinari see https://github.com/scipy/scipy/pull/8400#issue-296133417

> In the future, we may want to change the default behavior to atol=0.

**Comment by h-vetinari** [comment]
Yeah, I had seen that, but thought that getting confirmation would be easier. 😅 

But fair enough, should be good to proceed with atol=0.

**Comment by h-vetinari** [comment]
1.10 was released, resetting the milestone to 1.11

**Comment by ilayn** [comment]
To all involved, see the PR above for addressing this for (only) **iterative** solvers for now. There are probably details that I am missing hence please help me identify the issues a bit better in case I misunderstood. 

Currently, we have the following situation; 

We have a `tol` and a strange looking `atol` keywords. What internally happens is that all the inputs are now passed to a helper function called `get_atol`

https://github.com/scipy/scipy/blob/maintenance/1.10.x/scipy/sparse/linalg/_isolve/iterative.py#L78-L116

 1. User didn't provide `atol` then it first maps to `None` and that causes a warning and internally `atol` becomes `legacy`. This means:
   a. `tol` value is checked against the residual norm `Ax - b`. Note that matvec operation is costly. If the residual norm is already less than `tol` we exit.
   b. Then `b` norm is checked against 0. Since `tol*norm(b)` won't do any good we return `tol`
   c. And the typical case is to return `tol*norm(b)`.  
 2. User passed `legacy` all the same as above except the warning.
 3. If `atol` is actually set to something, then we return `max(atol, tol*norm(b))`. Why `max` is used I don't understand. 

Typically, `atol`, `rtol` pair is used as `tol = atol + rtol*<some metric>`. This is more or less what everybody expects from this pair and their naming is chosen to reflect this. But I'm a bit lost in all the issues I could read. 

What I propose is the following, 

 1. Make default `atol=0.`
 2. If `atol` is set to string, fire a warning saying this is going away in version 1.13 (hence make the current deprecation on a definite schedule). These are the users probably wanted to keep old behavior. Document how it can be done to match old behavior via `atol`, `rtol`. 
 3. Introduce a new keyword `rtol` and map current `tol` to `rtol`. Set `tol=None` as the default to weed out the ones who actually set `tol` value and fire deprecation warnings for them to use `rtol`. 
 4. Use the formula `tol = atol + rtol*norm(b)`

@rc : Ping for the memory lane
@jvsqzj for syncing this behavior with `gcrotmk`, and `lgmres`

**Comment by tylerjereddy** [comment]
I see some detailed discussion, but I also have limited bandwidth as the release manager so I'm going to bump the milestone to accommodate the imminent branching on May 29th. If you have some fix ready before then, feel free to merge/adjust back.

**Comment by h-vetinari** [comment]
This will happen in the context of https://github.com/scipy/scipy/pull/18488, which already targets 1.12 👍

**Comment by j-bowhay** [comment]
@ilayn @h-vetinari can this be closed?

**Comment by h-vetinari** [comment]
IMO would be OK to close, but I leave the final decision to @ilayn

**Comment by ilayn** [comment]
Sorry forgot to read this. Thanks all.

**Comment by lucascolley** [comment]
context for the reopening: https://github.com/scipy/scipy/pull/16050#issuecomment-1839610984

**Comment by h-vetinari** [comment]
Copying that context here:
> https://github.com/scipy/scipy/pull/18488 did not touch gcrotmk and lmgres [...]

So those are still outstanding here. It's a pity we missed this, would have been good to do this in the same cycle. Perhaps if we're fast, a PR could still be backported before GA...

**Comment by lucascolley** [comment]
> Perhaps if we're fast, a PR could still be backported before GA...

How is gh-16050 looking? want to trigger CI?

**Comment by h-vetinari** [comment]
> How is [gh-16050](https://github.com/scipy/scipy/pull/16050) looking? want to trigger CI?

I merged main there, but I don't think anymore that it's the right approach. It directly switches to errors if `atol` is not a float, whereas for the other functions we've introduced extensive warnings around that (see `_get_atol`).

**Comment by h-vetinari** [comment]
Opened a PR to clean things up, hopefully still for 1.12: #19702. Note that `minres` / `tfqmr` had also not been fixed yet (handled in that PR), and that `lsmr` and `lsqr` need deeper changes: #19704.
