### ISSUE TITLE
DEP: remove tol from `NumericalInverseHermite`

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15749]
Deprecated in https://github.com/scipy/scipy/pull/14703, warning does not [mention](https://github.com/scipy/scipy/blob/v1.8.0/scipy/stats/_unuran/unuran_wrapper.pyx.templ#L1717-L1719) a timeframe. Maybe the warning should be sharpened? Tentatively adding to 1.10 milestone.

CC @tirthasheshpatel

**Comment by tirthasheshpatel** [comment]
Thanks for noticing @h-vetinari!

There is a (huge) cleanup pending for UNU.RAN. I am working on that (PR coming soon) and will include this as a part of the cleanup.

**Comment by tirthasheshpatel** [comment]
There are two more deprecations in stats module:

- `max_intervals` keyword for the `NumericalInverseHermite` method has been deprecated and will be removed in 1.10.0.
- `NumericalInverseHermite` method has been deprecated from the `scipy.stats` namespace and shifted to `scipy.stats.sampling`


Since there could be more of these in the future, an issue for each seems a bit too much (maybe start an issue to track all the deprecations in a module). Another alternative I'd propose is to add these to a wiki page: more manageable and less noise in the issue tracker. What do you think @rgommers @tylerjereddy @h-vetinari?

**Comment by h-vetinari** [comment]
> Since there could be more of these in the future, an issue for each seems a bit too much (maybe start an issue to track all the deprecations in a module?)

That's exactly what I was doing when I got called away. 😅 
I think it'd be good to have one for discussions about deprecation policy generally.

I'm fine with grouping things into issues where they make sense, but I don't think too coarse issues help, and the wiki isn't visible enough for my taste. IMO these issues need to be milestoned (i.e. where people look regularly), and tagged - where appropriate - with a "good first issue label".

But if people don't agree, I'll certainly stop - I just thought I'd do a trawl for DeprecationWarnings and file reminders for ourselves. 🙃

**Comment by tirthasheshpatel** [comment]
Reopening this since #16198 only addresses the sharpen the warning part of the issue. The deprecation still needs to be executed later.

**Comment by h-vetinari** [comment]
Just noticed that #15083 introduced another deprecation for `NumericalInverseHermite` that doesn't have a timeline yet:
```python
class NumericalInverseHermite:
    @_deprecated(
        "NumericalInverseHermite has been deprecated from `scipy.stats`. "
        " To use `NumericalInverseHermite`, import/use it from "
        "`scipy.stats.sampling` module instead. "
        "i.e. `from scipy.stats.sampling import NumericalInverseHermite`"
    )
    def __init__(self, *args, **kwargs):
```

**Comment by h-vetinari** [comment]
> Just noticed that #15083 introduced another deprecation for `NumericalInverseHermite` that doesn't have a timeline yet:

Sharpened that deprecation in #16257 to mention removal in Scipy 1.10.

**Comment by tirthasheshpatel** [comment]
Thanks @h-vetinari
