### ISSUE TITLE
Running 1.5.2 on Apple M1 / ARM64

### ISSUE THREAD

**Issue by jtlz2** [scipy/scipy#15767]
When running an AWS SAM Lambda locally on my Mac M1, I receive the following error:

`Unable to import module '...': /var/task/scipy/linalg/_fblas.cpython-37m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned`

Our workaround [on intel] is to pin `scipy==1.5.2` (see https://github.com/scipy/scipy/issues/12975#issuecomment-1065013153).

But a binary for that version is not available anywhere as far as I can see. So

(a) Do you know where I can find such a binary?
(b) Failing that, does anyone have robust steps to build from source under ARM?
(c) Is there another workaround?

Many thanks in particular to @rgommers for your assistance here! :)

**Comment by rgommers** [comment]
Thanks for the report @jtlz2. We'll need some more details to make sense of this I think. Most importantly, can you give more details on AWS SAM Lambda? Is this a Docker image or something else, where do you obtain it from, how did you install SciPy within that environment, etc.?

"Running 1.5.2 on Apple M1 / ARM64" doesn't make sense, because that version of SciPy is simply too old and did not support arm64 macOS at all. 1.7.3 is the first version that does. But I suspect that you don't actually need arm64 SciPy binaries (wheels) here, since your error message is for a Linux wheel. So you're running some Linux version on macOS.

**Comment by rgommers** [comment]
I'll close this for lack of follow-up, and because it looks like there is nothing in scipy to resolve. Please do comment if you think there is a fix to make.
