### ISSUE TITLE
DOC: helper function to seed examples

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#15852]
Currently we are rewriting `rng = np.random.default_rng()` so that a common seed is used in the background:

https://github.com/scipy/scipy/blob/78ff9f16c4619759fc59f1e1813900738db8d7d2/scipy/_lib/_util.py#L548-L556

From https://github.com/scipy/scipy/pull/14182#issuecomment-855318533:

We should document that somewhere in the development docs, and expose that example seed somewhere so docstring writers have an easy way to write those examples. So I can write

```python
>>> from scipy._lib.docstrings import doc_rng
>>> rng = doc_rng()
>>> # My example follows
```

Which is easy to change to 

```python
>>> rng = np.random.default_rng()
>>> # My example follows
```

when copying into the docstring.

---

Or even simpler if we manage to render something different, we can just do:

```python
>>> rng = np.random.default_rng("any seed")
>>> # My example follows
```

And get back

```python
>>> rng = np.random.default_rng()
>>> # My example follows
```
Simpler.

**Comment by tupui** [comment]
Actually this is easy to change when the example is being run during the doctests. But I don't know how to change the rendering itself. I don't know what can be wrapped here.

**Comment by tupui** [comment]
I think I can mock what Sphinx is getting from numpydoc here https://github.com/numpy/numpydoc/blob/fe95e8b9332ed4ebc154db08b00232f5f67f9330/numpydoc/docscrape_sphinx.py#L340

**Comment by tupui** [comment]
I got this!! Started to play with mocks and others, but in the end it's way simpler than that:

```python
# put this at the end of doc/source/conf.py.
# And I suppose we can just put this in utils (or elsewhere to have a better name)

from numpydoc.docscrape_sphinx import SphinxDocString

def side_effect(func):
    def _wrapped(*args, **kwargs):
        res = func(*args, **kwargs)

        lines = []
        for line in res:
            if "np.random.default_rng" in line:
                prefix = line.split(">>>")[0]
                # just putting some random value to see it change in the doc
                line = f"{prefix}>>> rng = np.random.default_rng(66666666)"
            lines.append(line)

        return lines
    return _wrapped

SphinxDocString._str_examples = side_effect(SphinxDocString._str_examples)
```

If we do this, we can put the seed we want in the source, but the rendered doc will just display the fake thing. So the rendered example is using this. BUT, doctests would use the value you set (we need to remove the current doctest wrapper).

@mdhaber what do you think??

**Comment by mdhaber** [comment]
To make sure I understand: We would write examples like:
```
rng = np.random.default_rng(90783456987345690)
```
and that's how they would be executed in the refguide check, but the rendered documentation would look like:
> ```
> rng = np.random.default_rng()
> ```

**Comment by tupui** [comment]
A lengthier explanation for completeness and if someone else stop by.

The examples are run twice:

1. doc building: this renders the doc and make the HTML. The examples are run but we don't validate anything. Build might even pass if the code is wrong/malformed. From playing around, the code is just run for plotting purposes. So no plot, no run.
2. doctests: this is the refguide check part. Here we run the examples and check the output.

We don't want seed in the HTML: `rng = np.random.default_rng()`. And we need a seed for doctests. Hence, at leat one overwrite is needed to switch the behaviour.

Right now the switch is on the doctest side. It works, but not convenient for devs as we need to go find the seed value used for doctests.

A better experience could be to do the switch on the rendering side. i.e. put a seed in the example, anything the dev wants, and overwrite this for rendering the doc with `rng = np.random.default_rng()`.

(Since we already have the first way, we would have both ways at the same time. Can be done with little to no adjustments)

**Comment by mdhaber** [comment]
There are four parts to this, I think:
1. We get to write examples with whatever seed we want - I'm for it!
2. The doctests run with whatever seed we specify - I'm for it!
3. The code in the documentation renders with `default_rng()` - it has the usual pros and cons - good to encourage use of no seed when reproducibility is not needed, unfortunate that it confuses users that "what you see is not what you get". But this is the status quo; so no complaints about this PR from that perspective.
4. The numbers rendered in the documentation are generated with `default_rng()` - I think this would prevent me from using randomly-generated data in examples because without care, there's a chance that the data will not tell the story I had in mind. A lot of examples that we had to adjust when we switched to the current system would need to be adjusted again so that the text makes sense regardless of what numbers render. And like the transition to the current system, I think we'll forget to adjust many of these, which will probably lead to bug reports. So I'm less enthusiastic about this part.

If we can change this so the numbers rendered in the documentation are generated with the seed specified by the developer rather than the `default_rng()` shown, I'd be all for it!

**Comment by tupui** [comment]
Points 1 to 3 ok, but not 4 😃 Sorry I think my writing might have been confusing (also because I was not sure at first). Numbers shown in the doc are not "generated" at all. It's just showing what we write as text. So I think it ticks all the boxes?

**Comment by mdhaber** [comment]
OK, so if I write:

```python3
>>> rng = np.random.default_rng(34509823468726)
>>> rng.random()
1.23456789
```

Then the user will see:
```python3
>>> rng = np.random.default_rng()
>>> rng.random()
1.23456789
```
?

**Comment by tupui** [comment]
Yep that's how it works with this solution 😃

Ok then I will put this somewhere write a bit of doc and make sure the combination with our current thing is ok (I.e. it should only pick up statements without seed and use cistom seeds when present).
