### ISSUE TITLE
pip install failing on M1 mac

### ISSUE THREAD

**Issue by AlexTholen314** [scipy/scipy#15861]
I'm trying to use pip to install scipy (python 3.10.2 and two different commands as visible in the terminal output) and I get a litany of errors instead of it actually installing. I don't quite know what more information would be desired - I'm on Big Sur on a 2020 M1 if that helps.

[Terminal Saved Output.txt](https://github.com/scipy/scipy/files/8343493/Terminal.Saved.Output.txt)

**Comment by tupui** [comment]
Hi @AlexTholen314, thank you for reporting. I think you are not getting the wheel because you are on Big Sur and not Monterey. The wheel is `scipy-1.8.0-cp310-cp310-macosx_12_0_arm64.whl`. When the wheel is not available, you need to have a few more things installed in your environment (compilers as seen in the error message, see our contributor documentation for details).

**Comment by rgommers** [comment]
That answer is correct, and there's not much we can do here - this is just one of those cases where users may get a build from source when they don't expect it. That build can work, but of course more often than not it won't because dependencies are missing. I'll close the issue, because there is nothing to do here.
