### ISSUE TITLE
Missing degree of freedom parameter in return value from `stats.ttest_ind`

### ISSUE THREAD

**Issue by LeBarbouze** [scipy/scipy#15906]
I should mention first that this is an enhancement request rather than a bug issue.

The return type of the [`stats.ttest_ind`](https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/stats/_stats_py.py#L5944) function, testing for equal means two samples, comprises the t statistic and its associated p value. However, the degree of freedom parameter, computed in the function to estimate the p value from the t statistic, is missing in the return type, although it could be useful to the user (it is to me for instance).

In the [distantly related issue](https://github.com/scipy/scipy/issues/9485), the issue author points out to the [R function performing the t test](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/t.test) (factorized in one function instead of 3 functions, depending on function arguments). Efforts could be combined to factorize the functions and enhance the return type by getting inspired by the R function (other values could be useful for the user).

**Comment by mdhaber** [comment]
> I just skimmed through the codebase and I understand that backward compatibility would not be trivial

It actually is trivial (now) to maintain backward compatibility. The bunch object works just like a `NamedTuple` (e.g. can be unpacked as a tuple) for all the attributes already included, but we can add additional attributes. 

@tirthasheshpatel What do you think? Shall we convert the returned object into a bunch and add `df` as an attribute?

**Comment by tirthasheshpatel** [comment]
> What do you think? Shall we convert the returned object into a bunch and add `df` as an attribute?

Returning a df attribute sounds good (although it does complicate the API a bit since it doesn't apply to all tests as you mentioned, adding it across all t-tests mitigates the issue). R's `t.test` and `cor.test` (with method `pearson`) also give the df of the null distribution in the output so worth considering returning a df field in `pearsonr` too (if and when we add it in t-tests).

**Comment by mdhaber** [comment]
Ok, sounds reasonable. @LeBarbouze would you like to submit a PR?

**Comment by LeBarbouze** [comment]
@mdhaber I'd be interested but I am not sure I will find time in the coming weeks. I will try my best to find a slot in the coming month or so.  It'd be a first time for me (looking now at https://scipy.github.io/devdocs/dev/hacking.html and https://scipy.github.io/devdocs/dev/dev_quickstart.html#dev-quickstart), I'll get back here if I need further guidance. Of course if someone else does it in the mean time, just mention it here so that I don't duplicate the effort.

**Comment by alexscott-ff** [comment]
@mdhaber is there an issue specifically tracking adding the confidence interval in the return of `ttest`? Or is it generally just part of the much larger gh-9485?

**Comment by mdhaber** [comment]
I don't think so. Personally, I don't think we need an issue to track it, because confidence intervals for all of our hypothesis tests is on my mind pretty frequently. Ideally, I'd like to wait until I can write the hypothesis test infrastructure I've proposed elsewhere so that all the hypothesis tests don't have to reinvent the wheel.
On the other hand, it would probably be worthwhile to get these into the t-tests because it's so fundamental. I submitted gh-16835 to get that started.

**Comment by alexscott-ff** [comment]
@mdhaber thanks for the info and definitely don't rush it on my account! Understand if you want to wait to do it all at once in a larger refactor to bring those t-tests into one. Agree though it's a pretty fundamental thing to want to have :)

If you do go forward with gh-16835, will that cover `ttest_ind` as well? Or that will be follow-on work?

**Comment by mdhaber** [comment]
It would be a follow-up. I expect `ttest_ind` is the is the most important t-test function, but it is probably the most challenging to get right because `ttest_ind` has options for performing many different variations of the t-test. (Besides equal and unequal variances, it does trimmed mean and permutation-based version of the test.) If we want the confidence interval to somehow respect those options, it is more work. So I thought I'd start simple, and consider others once we get that right.

**Comment by alexscott-ff** [comment]
Makes sense! Thanks for the follow up. Yeah I was wondering about the complexity of the permutation test and such. Definitely a lot of work with those additional options and after a quick perusal, maybe not clear agreed upon solutions (I'll let you know if I find one). So the iterative approach sounds like the right one..

**Comment by mdhaber** [comment]
A permutation test CI can be calculated as the maximum and minimum shifts that can be applied to one of the samples before the permutation hypothesis test would begin to be rejected at `p=1-confidence_level`. I'm not sure we really want to implement that, though. Thinking again, though - we'll want `confidence_interval` to be a method rather than just returned by the test, so actually it doesn't necessarily need to respect all the same options.

**Comment by alexscott-ff** [comment]
Ah, that makes sense (I think..). FWIW this was one of the better things I found (along with the links to the papers by Ernst, Garthwaite and Ngyuen): https://stats.stackexchange.com/questions/409376/how-to-calculate-a-permutation-confidence-interval

**Comment by mdhaber** [comment]
Yeah, I ran accross the abstract mentioned there:
 
> The OP links to an abstract by Tableman, Nguyen, and Ernst (2014), who mentioned a method for permutation CIs but didn't actually describe it in their abstract.

and I also noticed that the method was not actually described there. Thanks for finding it!

Note that we need to be careful not to use the R code in the poster you linked; just the ideas (or look at Nguyen's thesis). It sounds like it is an excerpt from a package, which is probably GPL licensed, and therefore not compatible with SciPy's license.

**Comment by alexscott-ff** [comment]
It actually seems to be MIT licensed: https://github.com/ColbyStatSvyRsch/CIPerm/blob/master/LICENSE.md but maybe your point still stands.

**Comment by mdhaber** [comment]
Oh, great. No, that's compatible. R code is usually GPL.

**Comment by mocquin** [comment]
> The return type of the [`stats.ttest_ind`](https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/stats/_stats_py.py#L5944) function, testing for equal means two samples, comprises the t statistic and its associated p value. However, the degree of freedom parameter, computed in the function to estimate the p value from the t statistic, is missing in the return type, although it could be useful to the user (it is to me for instance).

+1 

I would also add as evoked above a ''.confidence_interval" method for `ttest_ind`.

**Comment by mdhaber** [comment]
The holdup here is that `ttest_ind` has evolved a complicated API, and we cannot easily provide a confidence interval for all combinations of options. We can raise a `NotImplementedError` as needed, but wading through all this is somewhat tedious. I'll take a look shortly and suggest a plan.
