### ISSUE TITLE
ENH: optimize: object-oriented interface to HiGHS

### ISSUE THREAD

**Issue by mkoeppe** [scipy/scipy#15915]
### Is your feature request related to a problem? Please describe.

Functions `Highs::getBasicVariables`, `Highs::getReducedRow` and `Highs::getReducedColumn` (https://github.com/ERGO-Code/HiGHS/issues/525#issuecomment-1086217397) are currently not exposed through scipy's Cython interface to HiGHS.

### Describe alternatives you've considered.

Using the pybind11-based HiGHS interface that is being developed by the HiGHS project. https://github.com/ERGO-Code/HiGHS/issues/525#issuecomment-1086217397

### Additional context (e.g. screenshots, GIFs)

https://trac.sagemath.org/ticket/32282

**Comment by mckib2** [comment]
Hi @mkoeppe, I just opened gh-16491 to address this.  Is the pxd declaration all that's required or is there any additional interface that needs implemented?

**Comment by mckib2** [comment]
I now understand -- I think we are toying with the idea of exposing stateful LP/MIP solvers that would preserve the underlying `Highs` instance that would make these available on-demand without needing to pack the `OptimizeResult` with everything anyone might want/need.  Would an object-oriented interface like this accomplish what you need?

**Comment by mkoeppe** [comment]
Yes, that's exactly what I had in mind.

**Comment by mdhaber** [comment]
@mckib2 can you post your thoughts about SciPy's object-oriented interface to HiGHS in this issue?

**Comment by mckib2** [comment]
@mdhaber Apologies for the delay, here are my current set of notes for the object-oriented interface.  All that are interested, please chime in!  As more work goes on in https://github.com/mckib2/scipy/tree/high-py-c-api I'll add a clearer description of the current prototype interface.

**Goals**
- Identify workflows and back-out features
- Sketch interfaces that provide desired features
- Nominal general interfaces, not necessarily specific
- Get feedback on all!

**Use cases, workflows**
- One problem
    - Shared milp, linprog use-cases
- Many independent problems
    - No warm starts required
    - Use solver in single thread (or solver per thread/process) to solve many problems
- Iterative problems
    - Parameters of a single solver/problem are updated iteratively
- Long-running problems
    - Progress reporting desirable to ensure iterative solutions converging
    - Warm-starts for failed attempts, iterative parameter optimization
- Child problems
    - Each problem solved generates multiple child problems to be solved
    - Copy, modify parent problem
- Chained problem solving
    - Multi-chain (concurrent chains with inter-chain dependencies)
    - Difficult nodes in chain (frequent starts/stops mid-chain)
- Large search front
    - Start many solvers, stop all when at least one solution is returned or meets criteria
    - Start many solvers on relaxed problem, pause some if promising solution identified to solve harder problem, resume other solvers to find diverse or better solutions

**Features**
- Persistent solver instances
- Warm start capability
- Problem parameter modification (coefficients, constraints bounds)
- Solver parameter modification
- Runtime parameter modifications (?)
- Synchronous/asynchronous runtime feedback mechanisms
- Easily constructed, copied solver objects
- Pausable/Cancelable

![image](https://user-images.githubusercontent.com/28734319/226162454-7f6095a9-ef30-465e-ae6b-b5a234ccc98b.png)

**Solver: Object**
- SciPy interface abstraction over optimization library
- Solver execution models
    - Blocking execution
        - "What you might expect"
        - No Stop/Cancel/Pause action support
    - Non-blocking execution
        - Similar to, extends GAMS’ [async execution](https://www.gams.com/latest/docs/UG_GamsCall.html#UG_DollarExecute) to “coroutine-like” execution
        - Only way to feasibly support Pause/Cancel actions
        - Solver runs in thread (or [C++20 coroutine](https://en.cppreference.com/w/cpp/language/coroutines))
        - SciPy-specific checks in HiGHS (probably at each iteration) to see if pause/stop/cancel issued
            - See upstream [GH discussion](https://github.com/ERGO-Code/HiGHS/discussions/860)
        - Non-blocking Start/Solve action, blocking Stop/Cancel/Pause actions
    - Concurrency/thread-safety
        - Should expect to be run under multithreading, multiprocessing
        - E.g., "Get Status" action can happen at any time
- Tasks
    - Investigate possibilities/workarounds for non-blocking execution policy using HiGHS
    
**Solver lifecycle: Construction**
- Setup, initialize underlying optimization library objects
- (calls Initialization)

Milp-like ctor arguments:
```python
class Solver:
    def __init__(self, c, integrality, bounds, constraints, options):
        self._initialize(c, integrality, bounds, constraints, options)
```

![image](https://user-images.githubusercontent.com/28734319/226162470-d24a3c08-4aa6-4789-9238-493173c3a887.png)


**Solver lifecycle: Initialization**
- Accomplished on construction
- Initial "Problem" handed to Solver
    - Linear coefficients
    - Linear constraints
    - Bounds
    - Solver parameters
- Problem represented in federated linprog-style, no explicit "Problem" class

milp-like arguments:
```python
solver._initialize(c, integrality, bounds, constraints, options)
```

**Solver lifecycle: Destruction**
- No special considerations, all HiGHS objects on stack

**Solver action: Solve/Start/Wait**
- Blocking execution model
    - Default behavior
    - Starts solver in current thread with copy of current parameters
- Non-blocking execution model
    - Imagine matplotlib-like: plt.show(block=False)
    - Kicks off non-blocking solve thread/process with copy of current parameters
    - Wait() action must be invoked to "join" solver thread

**Solver action: Start/Pause/Cancel** 
- Non-blocking execution model only
- No-latency Pause/Cancel may not be possible
- Use cases:
    - Pause solver pool while single known-hard problem is solved
    - Found feasible solution in solver pool, cancel everything else
    - Pause to synchronously update parameters between multiple solvers
    - May be required to Stop or Pause unconditionally before updating parameters

**Solver action: Get Status**
- Synchronous report of current solver info
- Potentially includes
    - Current solution, feasibility information
    - Iteration/node progress

**Solver action: (Un-)register callback**
- Asynchronous report of current solver info
- Includes all information reported by Get Status action
- Would require SciPy-specific hooks or upstreaming callback feature

**Solver action: Update Parameter**
- Update one or more Solver/Problem parameters
- Next Solve/Start action will be warm started if possible
- Tasks:
    - Investigate support for "hot-swapping" parameters in HiGHS unknown

**Solver action: Copy**
- Deep copy of Solver/Problem parameters


**Special Cases**
- To avoid Python overhead, perform all ctor/init and solve actions in C++ at once
- Replicates existing SciPy optimize interfaces for LP/MIP
- Tasks
    - Benchmark C++ monolith implementations vs Python wrapper over OO interface to verify performance uplift

**Comment by rgommers** [comment]
> As more work goes on in https://github.com/mckib2/scipy/tree/high-py-c-api

Engineering-focused question: if HiGHS now comes with a `pybind11`-based Python API, why can't that be used instead of writing yet another set of bindings?

**Comment by mckib2** [comment]
> Engineering-focused question: if HiGHS now comes with a `pybind11`-based Python API, why can't that be used instead of writing yet another set of bindings?

Here's my assessment of what I've seen of their pybind11-based library (as an admitted non-user):
- `pyomo` dependency
- uses `setuptools`
- HiGHS libraries are not built as part of their build system, [integration is suspect](https://github.com/ERGO-Code/HiGHS/issues/1180)
- notes anaconda as an unsupported environment (https://github.com/ERGO-Code/HiGHS/issues/1119)
- appears to be missing features (e.g., https://github.com/ERGO-Code/HiGHS/issues/969)

None of these are necessarily a deal-breaker, but might include cycles spent upstreaming which seem to take longer for Python as there is only a single dedicated maintainer for that effort.

**Comment by mdhaber** [comment]
The proposal looks great to me. A few questions:
- Can we start with the blocking execution model and add the non-blocking model after (at least the SciPy API parts)?
- I had been (maybe incorrectly) that the blocking interface will work like the [`OdeSolver`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.OdeSolver.html#scipy.integrate.OdeSolver)s: we would tell the solver to take steps in a Python loop rather than just telling it to start and only hear back from it once the problem is solved. Is that not right?
- I think "Update Parameter" is one of the most important features. For instance, after successfully solving a problem, the user might wish to swap out a constraint and re-solve. "Investigate support for "hot-swapping" parameters in HiGHS unknown" raised some questions. I have some guesses, but how do we define "hot-swapping" here? Presumably the example I just gave is not "hot-swapping" (rather it is a "warm start")? What problem parameters does HiGHS allow the user to change and get a warm start?

**Comment by mckib2** [comment]
> The proposal looks great to me. A few questions:
> 
>     1. Can we start with the blocking execution model and add the non-blocking model after (at least the SciPy API parts)?

Yes, this seems like the easiest route to me.

>     2. I had been (maybe incorrectly) that the blocking interface will work like the [`OdeSolver`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.OdeSolver.html#scipy.integrate.OdeSolver)s: we would tell the solver to take steps in a Python loop rather than just telling it to start and only hear back from it once the problem is solved. Is that not right?

This is not what I had in mind.  "Blocking" in the sense I'm using above would be the default behavior for `linprog` and `milp` -- it blocks the current thread until execution is completed and some solution (in success or failure) is returned to the user.  Single stepping (`maxiter=1`) seems not as useful as a default behavior, but single or batch stepping could be achieved by setting the `maxiter` to the desired amount and warm-starting after that.  I believe the previous progress would be preserved if the solver object isn't destructed/reinitialized even if a solution is not found (would need to test though).

>     3. I think "Update Parameter" is one of the most important features. For instance, after successfully solving a problem, the user might wish to swap out a constraint and re-solve. "Investigate support for "hot-swapping" parameters in HiGHS unknown" raised some questions. I have some guesses, but how do we define "hot-swapping" here? Presumably the example I just gave is not "hot-swapping" (rather it is a "warm start")? What problem parameters does HiGHS allow the user to change and get a warm start?

I was making a distinction (perhaps unhelpfully) between "warm-start" and "hot-swapping".  Warm-start would be where a previous solution/basis/state is available for the solver to start from somewhere without having to resolve.  Hot-swapping would be changing the (probably only solver) parameters while the solver is running, e.g., if the solver is taking longer than expected, change `maxiter` to something lower without having to stop it, change the parameters, and restart.  I'm fairly sure HiGHS won't let you do that, but if some variables can be made atomic, then it may be possible.  Hot-swapping is not a high priority feature, just a possible use-case that came out of brainstorming

**Comment by mdhaber** [comment]
I think this all makes sense now. The distinction is useful, and I think I understood what you had in mind, I just wanted to make sure. 

I was thinking we might both (independently) write down a vision of the SciPy API and then compare notes. Do you think that is a good next step?

**Comment by fuglede** [comment]
Ended up here because I was also curious for the reasoning behind having two sets of bindings. :)

> Here's my assessment of what I've seen of their pybind11-based library (as an admitted non-user):
> 
>     * `pyomo` dependency

That one is redundant; https://github.com/ERGO-Code/HiGHS/issues/1022

>     * uses `setuptools`
> 
>     * HiGHS libraries are not built as part of their build system, [integration is suspect](https://github.com/ERGO-Code/HiGHS/issues/1180)
> 
>     * appears to be missing features (e.g., [Highspy - support assigning vartypes  ERGO-Code/HiGHS#969](https://github.com/ERGO-Code/HiGHS/issues/969))
> 
> 
>     * notes anaconda as an unsupported environment ([ImportError for `highspy` ERGO-Code/HiGHS#1119](https://github.com/ERGO-Code/HiGHS/issues/1119))

See also hardcoded build logic in `pyproject.toml`; I've built `highspy` myself and did find myself fiddling more with `LD_LIBRARY_PATH` (and conflicting system/conda `libstdc++` versions) that I'd like to. I'm wondering if it wouldn't be for the benefit of everybody if someone could with SciPy-like experience in building binary-based wheels could offer their expertise to tidy up `highspy` as well, to the point of being able to rely on that directly? The wrapper in `highspy` is small enough that a rewrite is feasible if necessary.

**Comment by rgommers** [comment]
> I'm wondering if it wouldn't be for the benefit of everybody if someone could with SciPy-like experience in building binary-based wheels could offer their expertise to tidy up `highspy` as well, to the point of being able to rely on that directly?

That does seem logical. We'd still vendor it because HiGHS is too unstable to have as an actual external dependency. But if we could reuse their Python bindings directly rather than having everything separate, that seems like a potential win for both projects.

**Comment by mdhaber** [comment]
@rgommers @HaoZeke Is there still a need for SciPy to offer an object oriented interface, or can the HiGHS Python bindings be used directly?

**Comment by HaoZeke** [comment]
> @rgommers @HaoZeke Is there still a need for SciPy to offer an object oriented interface, or can the HiGHS Python bindings be used directly?

There is a modeling API for `highspy` which is a WIP (https://github.com/ERGO-Code/HiGHS/pull/1405) and I think that essentially provides the functionality requested (hot-starts, stateful solvers), however, `linprog` would still need to be redesigned for it, currently the interface between `highs(py)` and `linprog` is such that the problem is constructed and passed through to `highspy`, taking back only the solution, in a pretty black-box manner.

As for whether SciPy's `linprog` interface needs to support OOP approaches, or if we can assume users will use `highspy` if they need additional functionality.. I am not sure I can answer since I don't know much about the community requirements / desires w.r.t. `linprog`.

**Comment by rgommers** [comment]
> I am not sure I can answer since I don't know much about the community requirements / desires w.r.t. `linprog`.

Same here, not sure. Either way, I think finishing off the switch-over to the `highspy` bindings in SciPy and waiting to see if there are significant usability gaps in `highspy` or other experience-based rationale for designing a class-based interface in `scipy.optimize` shows up would make sense to me.

**Comment by fuglede** [comment]
Some scattered thoughts:

Already in its current form, `highspy` also provides some amount of access to the state of the solver (for instance, one thing I found useful was having [readBasis/writeBasis](https://github.com/ERGO-Code/HiGHS/pull/1264) available in `highspy`, which enables sharing solver state across process boundaries).

If any of this would be relevant in SciPy, I think it would be if we could provide zero-overhead abstractions to some of the functionality that's already available, but even then, I imagine that that would quickly become very HiGHS-specific and might as well live in `highspy` itself: IMO, the main value-adds of `linprog` over `highspy` at the moment are the small things, not having to manually convert inequality constraints to equality constraints, the fact that CSC arrays are the native citizens of `highspy`, so you can draw on what's already available in `scipy.sparse`, and most importantly that it's all zero-overhead: (Very) high-level libraries like PuLP/PyOMO are super useful for experimentation but very often you run into the issue that generating and passing state to the underlying solver becomes the bottleneck, with relatively short time spent by the solver itself. (I found it quite curious, for instance, that only rather recently did Gurobi add a feature to pass LPs as sparse arrays instead of having to go through their modelling API.)

And even if the more stateful operations were available here, we would still want the stateless one to be available: When you don't need stateful operations, using them adds a good deal of overhead (compare e.g. the first few rows of the "SciPy (defaults)"/"highspy (defaults)" columns in [this benchmark](https://github.com/ERGO-Code/HiGHS/discussions/1198#discussioncomment-5647505)); I've had use cases where I'll creatively switch between stateless `linprog` and stateful `highspy` based on model size. If one could do something it that domain, I think that would be useful, but even then, probably `highspy` itself (or HiGHS, really) would be a better home for any improvements.

So that's all if all we care about is performance (which is the main reason for preferring SciPy over e.g. PuLP/PyOMO at the moment). Another value-add could be if it's possible to design a (preferably zero-overhead) API that caters to a broader set of users: My impression is that things like PuLP/PyOMO are more accessible than the lower-level APIs in SciPy or `highspy`; to the point where some users would find it difficult to go to a lower level even when performance requirements ask for it. Now I don't think you want SciPy to compete with PuLP/PyOMO directly (right?), but if something could be done to introduce a broader class of users to the higher-performance lower-level APIs somehow, then that could be good.

**Comment by carlosgmartin** [comment]
Would it be possible to modify the implementation of [`linprog(method='highs')`](https://docs.scipy.org/doc/scipy/reference/optimize.linprog-highs.html) so that it can use the `x0` argument as a warm start?
