### ISSUE TITLE
BUG: scipy.stats.beta and bernoulli fails with float32 inputs

### ISSUE THREAD

**Issue by thibaut-kobold** [scipy/scipy#15961]
### Describe your issue.

Some `scipy.stats` distribution, such as `beta` and `bernoulli` fail to compute statistical values (such as `median`, `var`, etc.) when the input is in a float32 format. The error does not occur with float64 (but we care about memory on our end).

The error varies if the float32 inputs are whole numbers (like `2.` or `3.`), which causes a NaN return, or decimal numbers (like `2.1` or `3.14`), which results in an tiny number of ~1e-20.

From debugging, our suspect is that the boost library is causing the problem.

The issue arises on an Intel Mac, with the code running in a docker container.

### Reproducing Code Example

```python
from scipy.stats import beta, bernoulli
import numpy as np

#create float64 input
a64 = np.array(2,dtype=float)
b64 = np.array(3,dtype=float)

#create float32 input
a32 = np.array(2,dtype=np.float32)
b32 = np.array(3,dtype=np.float32)

# those appears the same
assert a64 == a32

# defining the functions work
beta64 = beta(a64,b64)
beta32 = beta(a32,b32)

# getting statistical value for 64 works
print("beta true value: ", beta(a64,b64).mean())

# but fails for 32 (NaN outcome)
print("beta fails with float32, integer numbers inputs; outcome: ", beta(a32,b32).mean())

# using decimal numbers also change the outcome (irrealistic, wrong tiny number, with overflow warning)
a32_dec = np.array(2.1,dtype=np.float32)
b32_dec = np.array(3.14,dtype=np.float32)
print("beta fails with float32, decimal numbers inputs; outcome: ", beta(a32_dec,b32_dec).mean())

#demonstration with Bernoulli
p = 0.33
print("Bernoulli: true value is {}; outcome is {}".format(p, bernoulli(np.array(p,dtype=np.float32)).mean()))
```

### Error message

```shell
beta true value:  0.4
beta fails with float32, integer numbers inputs; outcome: nan 
beta fails with float32, decimal numbers inputs; outcome: -5.421010862427522e-20
Bernoulli: true value is 0.33; outcome is 0.0

### error for integer values as float32
/usr/local/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py:628: RuntimeWarning: invalid value encountered in _beta_mean
  _boost._beta_mean(a, b),
/usr/local/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py:629: RuntimeWarning: invalid value encountered in _beta_variance
  _boost._beta_variance(a, b),
/usr/local/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py:630: RuntimeWarning: invalid value encountered in _beta_skewness
  _boost._beta_skewness(a, b),
/usr/local/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py:631: RuntimeWarning: invalid value encountered in _beta_kurtosis_excess
  _boost._beta_kurtosis_excess(a, b))

### error for decimal float32 values
/usr/local/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py:629: RuntimeWarning: overflow encountered in _beta_variance
  _boost._beta_variance(a, b),
/usr/local/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py:631: RuntimeWarning: overflow encountered in _beta_kurtosis_excess
  _boost._beta_kurtosis_excess(a, b))
```

### SciPy/NumPy/Python version information

1.7.1 1.21.5 sys.version_info(major=3, minor=9, micro=10, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Could you provide more information about your OS? I can't reproduce this; 32-bit works fine on my machine.

**Comment by mdhaber** [comment]
Yes, I can reproduce this:
```
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro10,2
  Processor Name:	Intel Core i5
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB
  Boot ROM Version:	286.0.0.0.0
```
macOS High Sierra 10.13.6 (17G14042)

@mckib2 Does this happen on the mini?

**Comment by thibaut-kobold** [comment]
thanks for the hep. I am on MacOS Monterey 12.3.1 (21E258), but running the code in a docker container.

**Comment by WarrenWeckesser** [comment]
I can reproduce this on Linux machine, running Python 3.10.1 and a development version of numpy. All of the boost-based ufuncs in `stats` appear to have a problem with `np.float32`.

```
In [1]: import platform
   ...: 
   ...: platform.platform()
Out[1]: 'Linux-5.16.19-76051619-generic-x86_64-with-glibc2.34'

In [2]: import sys
   ...: 
   ...: sys.version
Out[2]: '3.10.1 (main, Jan 14 2022, 02:27:20) [GCC 11.2.0]'

In [3]: import numpy as np

In [4]: np.__version__
Out[4]: '1.23.0.dev0+1087.g0eaa40db3'

In [5]: import scipy

In [6]: scipy.__version__
Out[6]: '1.9.0.dev0+1961.b9183eb'

In [7]: from scipy.stats import _boost

In [8]: typ = np.float32

In [9]: _boost._beta_mean(typ(1.5), typ(2.5))
<ipython-input-9-e0a92b18c829>:1: RuntimeWarning: invalid value encountered in _beta_mean
  _boost._beta_mean(typ(1.5), typ(2.5))
Out[9]: nan

In [10]: _boost._beta_isf(typ(0.5), typ(1.5), typ(2.5))
Out[10]: nan

In [11]: _boost._ncf_mean(typ(10), typ(12), typ(2.5))
Out[11]: nan
```
With types `np.float64`, the functions work as expected:
```
In [12]: typ = np.float64

In [13]: _boost._beta_mean(typ(1.5), typ(2.5))
Out[13]: 0.375

In [14]: _boost._beta_isf(typ(0.5), typ(1.5), typ(2.5))
Out[14]: 0.35245227987713096

In [15]: _boost._ncf_mean(typ(10), typ(12), typ(2.5))
Out[15]: 1.5
```

**Comment by WarrenWeckesser** [comment]
I think something is not working as expected in this block of code in [scipy/stats/_boost/include/Templated_PyUFunc.hpp](https://github.com/scipy/scipy/blob/a8b7c3216c0e8d6dc832d01d3e3dd92919279303/scipy/stats/_boost/include/Templated_PyUFunc.hpp):

https://github.com/scipy/scipy/blob/a8b7c3216c0e8d6dc832d01d3e3dd92919279303/scipy/stats/_boost/include/Templated_PyUFunc.hpp#L10-L27

This code is only used when the C++14 standard is used.  If I build SciPy with, for example,

```
CPPFLAGS=-std=c++11 python3 dev.py -b
```
the examples given earlier in this issue return the expected values.  For example,

```
In [18]: from scipy.stats import _boost

In [19]: typ = np.float32

In [20]: _boost._beta_mean(typ(1.5), typ(2.5))
Out[20]: 0.375

In [21]: _boost._beta_isf(typ(0.5), typ(1.5), typ(2.5))
Out[21]: 0.35245228

In [22]: _boost._ncf_mean(typ(10), typ(12), typ(2.5))
Out[22]: 1.5

```

I'm looking into what the actual problem is, but I need to spend a little more time with my C++ books.  @mckib2, the problem might turn out to be obvious to you, so if you get a chance to take a look and see how to fix it, go right ahead!

If we are going to support conditional C++ code like this, where the code that is compiled depends on which standard is used, we need tests in CI to cover all the C++ language standards that we support.  Alternatively, we could pick a reasonable standard, and ensure that our C++ code is always compiled with *exactly* that standard.

Clearly, a fix should include tests with `float32` inputs.  Or should it?  Currently, almost all the code that implements the distribution methods assumes that the calculations are done with `float64`.  If you pass `float32` arrays to `stats.gamma.cdf()` or `stats.beta.isf()`, the output will be `float64`.  So having the underlying ufuncs handle `float32` might save a few CPU cycles--assuming the inputs make it to the ufunc calls as `float32`--but eventually the output is converted to `float64`. For users, it might be confusing to have `float64` results and yet have lost precision because some calculations were done with `float32` first.  Until we can be sure that `float32` inputs will remain `float32` throughout the calculations, it might better to always cast the input to `float64`.

**Comment by WarrenWeckesser** [comment]
I found the problem; it is in this line:

https://github.com/scipy/scipy/blob/a8b7c3216c0e8d6dc832d01d3e3dd92919279303/scipy/stats/_boost/include/Templated_PyUFunc.hpp#L24

Some context:
* `func` is the function that does the calculation associated with the ufunc.  For the cases handled by this ufunc generation code, `func` will be a function that accepts a certain number of `RealType` inputs, and returns a `RealType` value.
* `inputs` is an array of pointers to the input values that we want to pass to `func`.  For example, if `func` takes 3 arguments, we want `result = func(*inputs[0], *inputs[1], *inputs[2])`.
* `Is` is a variadic template parameter pack; the way this function is templated, `Is` is effectively the sequence of numbers 0, 1, ..., N-1, where N is the number of input arguments of `func`.
* The line of code shown above casts `func` to a function type that returns a `RealType` and that has *variadic* input.  C++ sees the reinterpreted function as one that accepts a variable number of arguments.  The reinterpreted function is called with the argument `*inputs[Is] ...`, which, in effect, splats the array into separate arguments; if `inputs` has length 3, `*inputs[Is] ...` acts like `*inputs[0], *inputs[1], *inputs[2]`,  which is exactly what we want.

The problem is the casting of `func` to a variadic function.  As noted [here](https://en.cppreference.com/w/cpp/language/variadic_arguments), *"`float` arguments are converted to `double` as in [floating-point promotion](https://en.cppreference.com/w/cpp/language/implicit_conversion#Floating-point_promotion)"*.  So when `RealType` is `float`, the arguments are cast to `double` before being past to `func`.  `func` expects `float` arguments; hilarity ensues.

The simplest solution seems to be to remove the C++14 code.  I spent a little time trying to find an elegant fix, but I just ended up with variations of the C++11 version.  For the sake of expediency, I submitted a PR to remove the C++14 version of the code: https://github.com/scipy/scipy/pull/16185.  If anyone can provide an alternative PR with a solution for the C++14 code, I will be happy to close my PR.

**Comment by thibaut-kobold** [comment]
Many thanks @WarrenWeckesser for your work on this issue.

Maybe I can also offer a little context for when this issue appeared:
- I was working with [Xarray](https://docs.xarray.dev/en/stable/), coupled with Dask for bigger than memory computation.
- As such, for memory efficiency, `float32` is often the format of choice, such as here: [Xarray / Dask example](https://examples.dask.org/xarray.html)

**Comment by WarrenWeckesser** [comment]
Generating incorrect results with the common case of `float32` input is bad, so I have added this to the 1.9 milestone.  The fix in https://github.com/scipy/scipy/pull/16185 is actually pretty simple, so we should be able to get this issue wrapped up in time for the branching of 1.9 next week.

**Comment by rgommers** [comment]
> Until we can be sure that `float32` inputs will remain `float32` throughout the calculations, it might better to always cast the input to `float64`.

This makes sense. In addition, I think we may not want to support `float32` at all in `stats`, other than "cast to float64 at the start of the calculation, produce results, cast output back to float32". It's hard to assess accuracy loss for `float32` for stats algorithms, there's little value in this feature for users, and it's hard to write tests.

**Comment by mdhaber** [comment]
> there's little value in this feature for users

What about when working with GPUs?

**Comment by rgommers** [comment]
That's not what I would expect. `float32` (or even `float16`) works well for deep learning because the nature of the application is such that you can get away with very low-precision results for individual function calls. Outside of deep learning that's much less likely to be true. And even in deep learning libraries you have functions that have internal accumulator dtypes with higher precision for some operations (in particular, statistical reductions like `sum`).
