### ISSUE TITLE
ENH: Implement a function computing a mesh for a function

### ISSUE THREAD

**Issue by KOLANICH** [scipy/scipy#15976]
### Is your feature request related to a problem? Please describe.

Wide range of problems can benefit from non-uniform meshes:
1. function approximation by storing points
2. differential equation solution using a method of finite differences
3. kernel density estimation using different bandwidth for each point
4. histograms with nonuniform bins

### Describe the solution you'd like.

1. The function is differentiated.
2. The modulus of the derivative is computed.
3. It is integrated and normalized to become a CDF
4. CDF is transformed into PPF via interpolation
5. A mesh is computed by transforming a uniform mesh into non-uniform via PPF.

It can be possible to recursive refine the approximation.

### Describe alternatives you've considered.

No.

### Additional context (e.g. screenshots, GIFs)

https://github.com/KOLANICH-libs/StatsUtils.py/blob/master/StatsUtils/hist.py is an impl

**Comment by rkern** [comment]
Do you have references in the literature for this procedure?

**Comment by KOLANICH** [comment]
>Do you have references in the literature for this procedure?

No, but the method is so obvious that I strongly suspect that I have reinvented a wheel. It'd be nice if someone remembered its name.

**Comment by rkern** [comment]
A literature reference is less about proving that someone has done it before than to see an exploration of the merits of the procedure against each of these use case, comparing against alternatives and showing the tradeoffs for the different tuning parameters involved. I don't know of any theory that connects histogram binning to adaptive gridding for finite differencing (though it's possible there is one somewhere) that would make this procedure good for both of them.

We appreciate the suggestion, but in the absence of such a reference, I think this is out of scope for `scipy`.

**Comment by KOLANICH** [comment]
>I don't know of any theory that connects histogram binning to adaptive gridding for finite differencing (though it's possible there is one somewhere) that would make this procedure good for both of them.

`hist` is just a file name because for now I use this method only for hists within that lib, because it is calles `StatsUtils`. I have not modularized the methkd yet into an another lib.

The idea is that if we have a function `f` being approximated (all of the mentioned applications can be considered a numerical approximation of some function `f`), an interval `[x_i; x_{i+1}]`, and `Y_i = f(X_i)` where `x_i ≥ X_i ≥ x_{i+1}`, then error `ΔΥ(x) = |df(x)/dx| ΔX(i) ≤ |df(x)/dx| * (x_{i+1} - x_i)`. If we take `h_i = x_{i+1} - x_i = α(n) / |df(x)/dx|` where `α(n)` is some constant depending on count of points `n` and some global properties of the function being approximated, then the approximation error in each point is bounded by `α(n)`.

**Comment by rkern** [comment]
I mentioned histogram binning and gridding for finite differencing because you explicitly listed those two as use cases.

The main problem with following up on this suggestion is what it means to "differentiate" and "integrate" which "function"s. We don't have symbolic or autodiff facilities in scipy, so at some point someone has to either simply provide them (as in your use of this in gh-15977 for `scipy.stats` distributions that come with a `.pdf()` and `.cdf()`) or else someone will have to do the numerical evaluations using some already-available discretization.

For general function approximation by linearly-interpolated samples, I guess so? But that doesn't seem to me to be a standalone use case. Usually, you discretize to do something where the discretized version is more convenient; then other concerns with the algorithm for which you discretized come into play.

For finite difference meshes, you will find better tools available with the finite differencing packages that are out there. Nonuniform grids need more involvement with the governing equations and the time-stepping scheme than simply bounding the approximation error of one function evaluated over the 1D domain (the most important functions to approximate are the ones that you are integrating the PDE to find out).

As I mentioned in gh-15977, I don't think that feature is in-scope for scipy, so I'm not personally motivated by that use case for this functionality. This is the only clear-cut use for this procedure that I have seen.

I'm not at all clear on how this could be used to implement varying-bandwidth selection for a KDE. There are reasonably well-understood algorithms for such a thing, but I don't think this procedure plays any role with them. Packages with support for varying-bandwidth kernels (`scipy.stats` is not one of them) already implement those algorithms.

**Comment by KOLANICH** [comment]
>or else someone will have to do the numerical evaluations using some already-available discretization.

I guess it is this case. At least I currently use arrays of differences as the derivatives.

>I'm not at all clear on how this could be used to implement varying-bandwidth selection for a KDE.

It's true that it's not immediately clear what the formula must be in that case and it needs more research.

>As I mentioned in gh-15977, I don't think that feature is in-scope for scipy, so I'm not personally motivated by that use case for this functionality. 

>Usually, you discretize to do something where the discretized version is more convenient; then other concerns with the algorithm for which you discretized come into play.

OK. My use case was to make cool-looking histograms under plots of PDFs of fitted distributions, no serious requirements, just to have cool-looking pics where it is seen whether hists (well, I could have used my empirical dist class instead, and BTW the main use case for me to have `rv_empirical` was to make hists bins with it) match the fitted PDFs well or not. The method described IMHO did the job well.

**Comment by mdhaber** [comment]
@KOLANICH The new `fit` function returns an object with a `plot` method that currently produces a plot like this for a discrete distribution:
![image](https://user-images.githubusercontent.com/6570539/162853955-5151f2e2-22c7-4db6-a59d-e996013e22eb.png)

Do you think your idea could improve this sort of plot?

**Comment by KOLANICH** [comment]
It's cool to have this. For discrete distributions hist bins matching the values look OK. For continious distributions I'm not sure that hists are the best way to represent them, a PDF got via KDE can be more informative. But hists are familiar to everyone, so probably still should be used in addition. If I understand right, currently it uses a black-box optimizer for each distribution, even if MLEs are available in closed form for that dist. I think it should be done smarter. Params that can be estimated in closed form should be estimated that way. Also initial guesses can be estimated somehow in a closed form under some relaxed assumptions. You may want to look at how I have implemented it in `StatsUtils.dists` (`fitPDFMLE`, `fitPointsMLE`) [1](https://github.com/KOLANICH-libs/StatsUtils.py/blob/master/StatsUtils/dists/TruncatedNormal.py) [2](https://github.com/KOLANICH-libs/StatsUtils.py/blob/master/StatsUtils/dists/Normal.py) [3](https://github.com/KOLANICH-libs/StatsUtils.py/blob/master/StatsUtils/dists/MultivariateGaussian.py)

Also it may make sense to store the history of losses, so it can be plotted too.
