### ISSUE TITLE
BUG: scipy.integrate.odeint returns wrong values when derivative function overwrites y

### ISSUE THREAD

**Issue by Kfftfuftur** [scipy/scipy#16170]
### Describe your issue.

`odeint` supplies the original `y` vector to the derivative function so when the function writes the derivative directly into the vector it also overwrites the `y` vector in `odeint`. 

The function `derivative_1` from the code example overwrites `y` with the derivative. `odeint` doesnt seem to pass a copy of `y`, so its record is also overwritten. This only happens in the first time-step, after that `odeint` seems to properly pass copy's.

`derivative_2` produces the expected result since `y` is not overwritten,

### Reproducing Code Example

```python
from scipy.integrate import odeint

def derivative_1(y, t):
    y[0] = 1
    y[1] = 0
    return y

def derivative_2(y, t):
    return [1, 0]

y = [0, 1]
t = [0, 1, 2]

print(odeint(derivative_1, y, t)) # Produces wrong result.
print(odeint(derivative_2, y, t)) # Produces the expected result.
```

### Error message

```shell
There is no error message, but I cant submit this form without writing something into this field.
```

### SciPy/NumPy/Python version information

1.8.0 1.22.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by maicontibola** [comment]
This behavior probably occurs because of this piece of code in the [_odepack_py.py](https://github.com/scipy/scipy/blob/v1.8.1/scipy/integrate/_odepack_py.py#L239) file:
![image](https://user-images.githubusercontent.com/100963404/170153212-512cbd64-09de-4f5d-a912-6cc622e52e30.png)

I found in the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html#scipy.integrate.solve_ivp) the suggestion to use the function "solve_ivp". Maybe this function solve the problem.
![image](https://user-images.githubusercontent.com/100963404/170153832-95a1c425-7ef6-4288-9234-9dcdea63b8f4.png)
That's correct?

**Comment by WarrenWeckesser** [comment]
Sorry no one addressed this issue for so long.  I think most people's reactions would be "Well, don't do that!".  In fact, I propose that we make the arrays passed to the user functions *read-only*, so you *can't* do that.  I have submitted a pull request to implement this: https://github.com/scipy/scipy/pull/20803

**Comment by WarrenWeckesser** [comment]
gh-20803 could have worked to prevent users from modifying the arrays, but it could also break someone's existing code if they happen to have written their functions in Cython. So we won't pursue that approach, at least not in the short term.  Longer term, this is still the ideal solution.

I think the simplest thing we can do now is what I said above: tell users to not modify the arrays that are passed to their functions.  I would be fine with simply adding documentation to this effect in the `odeint` docstring, and calling it done.  This amounts to the "consenting adults" argument: we warned you, so if you modify the arrays anyway (either intentionally or because of a bug), you have to deal with the consequences.

A more radical change would be to copy the arrays before they are passed to the user.  But that adds overhead for a "feature" that no one should need, so it is not something that I am interested in seeing implemented.

**Comment by rgommers** [comment]
+1 for the doc change here, and agreed with not doing anything that adds extra overhead.
