### ISSUE TITLE
BUG: Memory leak in function `Py_FindObjects` due to new reference is not decreased (static analyzer report)

### ISSUE THREAD

**Issue by Snape3058** [scipy/scipy#16235]
1. A new reference is returned and assigned to `tuple`.
https://github.com/scipy/scipy/blob/8627df31ab07d66b438c7e5d5880e3f4d435f248/scipy/ndimage/src/nd_image.c#L888

2. Assume `tuple` is not NULL.
https://github.com/scipy/scipy/blob/8627df31ab07d66b438c7e5d5880e3f4d435f248/scipy/ndimage/src/nd_image.c#L889

3. Assume taking the true branch.
https://github.com/scipy/scipy/blob/8627df31ab07d66b438c7e5d5880e3f4d435f248/scipy/ndimage/src/nd_image.c#L897

4. Goto `exit`. `tuple` goes out-of-scope without decreasing the refcnt.
https://github.com/scipy/scipy/blob/8627df31ab07d66b438c7e5d5880e3f4d435f248/scipy/ndimage/src/nd_image.c#L899

Internal Report ID: c5db6d

---

NOTE: the local variable `tuple` declared here is never used apart from line 925.
https://github.com/scipy/scipy/blob/8627df31ab07d66b438c7e5d5880e3f4d435f248/scipy/ndimage/src/nd_image.c#L850

**Comment by rgommers** [comment]
Thanks for the clear report @Snape3058. gh-16397 contains a fix.

**Comment by rgommers** [comment]
This just got assigned a CVE: https://nvd.nist.gov/vuln/detail/CVE-2023-25399. There's a couple of problems with that:

1. It wasn't disclosed in private to us - as is best practice, and we have a way of doing it advertised in our README
2. It does not seem like a valid CVE:

  - The only way to trigger that memory leak is when calling `ndimage.find_objects`, at which point the caller already can execute arbitrary Python code - and then there are far more impactful things they can do than cause a small memory leak. 
  - This open issue tracks other reported and potential refcounting errors: gh-11142. In general, those are technically bugs but not security issues.
  - SciPy is _not_ designed to be exposed to untrusted users or untrusted data directly. This is the case for _any_ numerical Python package and the CPython interpreter itself - unless advertised otherwise. See the guidance in https://www.python.org/dev/security/ and https://numpy.org/devdocs/reference/security.html for example.

@Snape3058 did you apply for this CVE? If so, could you please not do that for any other issues before discussing with us in private first? CVEs, even if later deemed invalid, cause a large amount of work for us and for many of our users.

**Comment by Snape3058** [comment]
Sorry for the inconvenience that our team brought to this project.
I did not do this myself, but my mentor asked other teammates to apply for some CVE IDs for my confirmed bug reports.
I will forward your reply and let them know about the rules.
Apologize again for this.
My teammates will then get in contact with you and discuss this one.

**Comment by rgommers** [comment]
Thank you @Snape3058, much appreciated.

**Comment by nonsense-j** [comment]
> 

I apologize for the inconvenience caused by my personal negligence in applying this CVE. I misassessed the harmfulness of this vulnerability, and the problems you mentioned do exist. Here are some expected solutions to your problems:
1. For this issue, I will update this cve by rejecting assignment.
2. I wonder how I can disclose vulnerabilities in private to you. There is another issue I requested for cve at the same time though I labeled that it has been fixed. 
Really sorry again for causing that much work for you.

**Comment by rgommers** [comment]
Thank you @nonsense-j, that sounds good!

> I wonder how I can disclose vulnerabilities in private to you

As noted above, we have a link in our main README (which points to https://tidelift.com/docs/security). That said, now that we're already talking, it's easier to send me a private email directly - ralf.gommers@gmail.com
