### ISSUE TITLE
MAINT: wiki "ninja edits"

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#16301]
I guess this hasn't been an issue for SciPy recently, but I noticed some undesirable wiki edits showing up today (see below). I know another NumFOCUS project I work on ultimately had to restrict wiki edits to folks with push access, but this obviously would be at odds with the usefulness of public editing of release notes to avoid merge conflicts.

What else could we do--reverse undesirable edits and block the accounts, assuming the activity remains pretty light? If we could get the granularity of needing to have made a commit to the project to edit the wiki, that might be pretty slick, but don't think it is an option?

![image](https://user-images.githubusercontent.com/7903078/170846337-5e1bb462-8560-426c-a443-af00ea6e2969.png)

**Comment by tupui** [comment]
2 other options:
- Use another platform (hackmd for instance)
- we update the list as we go (scikit-learn, among others, is doing this)

**Comment by seberg** [comment]
Just FYI, they also edited the NumPy wiki, had hoped it was a one-off...

**Comment by tupui** [comment]
I could not rant on Twitter as they don't have an account but I posted something on LinkedIn where they have a page.

**Comment by rgommers** [comment]
For NumPy we ticked the `Restrict editing to users in teams with push access only` box. For SciPy we use the wiki more, in particular for release notes - so this is not as easy. But we could do the same, and simply ask people who can no longer edit it to suggest a release note entry on their PR, after which the maintainer copies it to the wiki. WDYT?

**Comment by tupui** [comment]
Or we just don’t use wiki for that. We can have a hackmd, or another service, for instance and restrict edit to people logged in. Vandalism might be easier to spot.

**Comment by rgommers** [comment]
Thanks @melissawm. I think for things that are very outdated and are actively unhelpful it'd be good to clean them up. In particular for the development hangouts that's true. The `scipy.signal` topic is indeed better in an issue.

I don't see the point in moving other things though, for example:
- the Accelerate page is quite important and has lots of incoming links, 
- the Windows 10 build page is actively being used right now and that does not belong in the docs in its current form (plus the wiki is just better for such ongoing dev notes to self / one collaborator),
- the Web service infra page is the best such overview we have, and its mostly up to date,

Moving things around is both extra work and breaks incoming links (we can't add redirects, or the page will still exist and then we haven't solved the actual "unwanted edits" problem).

Let's make this restricted only, it's a decent solution that takes about 30 seconds to do. There's no real downside other than 1-2 handfuls of edits per release that can no longer be made by people without any permissions.

> Or we just don’t use wiki for that. We can have a hackmd, or another service, for instance and restrict edit to people logged in. Vandalism might be easier to spot.

Not much different than the wiki, since that requires a login too? It's even the same login as for HackMD.
