### ISSUE TITLE
DOC: rvalue description is missing in stats.probplot

### ISSUE THREAD

**Issue by msat59** [scipy/scipy#16333]
The description of `rvalue` in `stats.probplot()` is missing.

```
def probplot(x, sparams=(), dist='norm', fit=True, plot=None, rvalue=False):
...
Parameters
    ----------
    x : array_like
        Sample/response data from which `probplot` creates the plot.
    sparams : tuple, optional
        Distribution-specific shape parameters (shape parameters plus location
        and scale).
    dist : str or stats.distributions instance, optional
        Distribution or distribution function name. The default is 'norm' for a
        normal probability plot.  Objects that look enough like a
        stats.distributions instance (i.e. they have a ``ppf`` method) are also
        accepted.
    fit : bool, optional
        Fit a least-squares regression (best-fit) line to the sample data if
        True (default).
    plot : object, optional
        If given, plots the quantiles.
        If given and `fit` is True, also plots the least squares fit.
        `plot` is an object that has to have methods "plot" and "text".
        The `matplotlib.pyplot` module or a Matplotlib Axes object can be used,
        or a custom object with the same methods.
        Default is None, which means that no plot is created.
    Returns
    -------
```

**Comment by tupui** [comment]
Hi @msat59, thank you for reporting. Would you like to make a PR?

**Comment by harivamsi9** [comment]
@tupui Can I contribute to this issue?

**Comment by tupui** [comment]
Hi @harivamsi9, yes of course since @msat59 did not reply. Thank you in advance 😃

**Comment by harivamsi9** [comment]
Thank you @tupui ,  I am getting mixed answers online on the rvalue.
Would you be able give me some info, or pointers, regarding it? so I can refer and PR this quick?

**Comment by mdhaber** [comment]
>  The function prints `r**2` which corresponds to the coefficient of determination.

@harivamsi9 the way you can tell is here:
https://github.com/scipy/scipy/blob/4cf21e753cf937d1c6c2d2a0e372fbc1dbbeea81/scipy/stats/_morestats.py#L616-L623

Above, `r` is returned by `linregress`.
https://github.com/scipy/scipy/blob/4cf21e753cf937d1c6c2d2a0e372fbc1dbbeea81/scipy/stats/_morestats.py#L603-L605

And you can read about `r` in the [`linregress` documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.linregress.html).

![image](https://user-images.githubusercontent.com/6570539/172383200-ca212c85-feff-4f31-9be4-73dd3e5a5555.png)

So a reasonable addition to the docstring would be:
```
    rvalue : bool, optional
        If `plot` is provided and `fit` is True, setting `rvalue` to True
        includes the coefficient of determination on the plot. 
        Default is False.
```
(My preference would be for the `True`s and `False`s to be enclosed in double-backticks throughout to render them in teletype because they refer to literals. But that is inconsistent in SciPy documentation, so I wouldn't ask for it to be changed in this function.)

---
Something else we should fix while we're at it is:
```
res = stats.probplot(x, plot=plt, fit=False, rvalue=True)
Traceback (most recent call last):

  File "C:\Users\matth\AppData\Local\Temp\ipykernel_19556\1053949826.py", line 1, in <module>
    res = stats.probplot(x, plot=plt, fit=False, rvalue=True)

  File "C:\Users\matth\Desktop\scipy\scipy\stats\_morestats.py", line 632, in probplot
    plot.text(posx, posy, "$R^2=%1.4f$" % r**2)

UnboundLocalError: local variable 'r' referenced before assignment
```
So I would change:
https://github.com/scipy/scipy/blob/4cf21e753cf937d1c6c2d2a0e372fbc1dbbeea81/scipy/stats/_morestats.py#L616
to 
```python
if fit and rvalue:
```
since it doesn't make much sense to show the coefficient of determination without the fit line.

**Comment by boatwrong** [comment]
Hey would it be okay if I contribute to this issue? I've got a pr ready

**Comment by harivamsi9** [comment]
Hey @boatwrong, mine is done.

**Comment by tupui** [comment]
@boatwrong we don't want people to compete and @harivamsi9 is still involved with this issue. There are plenty of other easy issues to tackle.

**Comment by boatwrong** [comment]
@tupui @harivamsi9  Sorry about that, thanks for the replies!

**Comment by harivamsi9** [comment]
[output.txt](https://github.com/scipy/scipy/files/8861829/output.txt)

**Comment by tupui** [comment]
Yes we've seen this issue. There are some dependencies conflicts on windows. I don't know how to fix this yet and don't have a windows machine to investigate.

Meanwhile, I suggest you either use WSL, another system, docker or gitpod. See our guides.
Note that for this particular PR, since there is mostly doc changes you could send a PR without locally testing.

**Comment by harivamsi9** [comment]
@tupui please check the PR, this is my first ever Open Source Contribution.
Thank you so much for helping me out.
