### ISSUE TITLE
ENH: stats: return bunches rather than plain tuples

### ISSUE THREAD

**Issue by JozsefKutas** [scipy/scipy#16364]
There's some old discussion here: https://github.com/scipy/scipy/issues/13118

At the moment, some statistical test functions in `scipy.stats` return plain result objects/dataclasses while some return namedtuples. In particular, this means that tuple unpacking works in some cases but not in others. For example, the following code is fine:

```python
from scipy import stats
rng = np.random.default_rng()
x = stats.norm.rvs(size=500, random_state=rng)
statistic, pvalue = stats.kstest(x, 'norm')
```

While the following code throws a type error:

```python
from scipy import stats
rng = np.random.default_rng()
x = stats.norm.rvs(size=500, random_state=rng)
statistic, pvalue = stats.cramervonmises(x, 'norm')
```

Would it make sense to change all results objects to namedtuples, so that unpacking and positional indexing works in all cases?

Also, `pearsonr` returns a plain tuple, but this seems to have been changed on the dev branch. In this case I think the `statistic` attribute should maybe be renamed `correlation` to be consistent with the other correlation functions (`kendalltau`, `spearmanr`, ...).

**Comment by tupui** [comment]
Hi @JozsefKutas, thank you for bringing this up again. We actually discussed this a few times recently and we want to go the other way, generalize returning objects. This is more maintainable as we can expand or deprecate things more easily with minimal code break on the user side.

**Comment by mdhaber** [comment]
To expand on what @tupui wrote: the return values of functions that currently return `tuple`s or `namedtuple`s are being converted into objects ("bunches") that can be unpacked like tuples, have attributes corresponding with those values like `namedtuple`s, and can also have _additional_ attributes and methods. This allows us to grow while maintaining backward compatibility.

For instance, in SciPy 1.9.0, `pearsonr` will be such an object, and it will also have a `confidence_interval` method. (See [here](http://scipy.github.io/devdocs/reference/generated/scipy.stats.pearsonr.html#scipy.stats.pearsonr).)

I agree with the idea of consistent naming, but which direction we should go is debatable. In gh-9307 (specifically [here](https://github.com/scipy/scipy/issues/9307#issuecomment-1032070343)) we have been discussing whether the correlation functions are so different from all the other reduction statistics that they deserve their own distinct vectorization behavior. I suspect that we can generalize that question to whether they also deserved their own distinct attribute name - `correlation` instead of the usual `statistic`. Either way, I agree we'll want to be able to access the statistic/correlation value using the same attribute name for all correlation functions. (Personally, I'd suggest that the statistic of all reduction functions, including the correlation functions, should be accessible as attribute `statistic`, though. Of course, we could expose it as both `correlation` _and_ `statistic`.)

**Comment by mdhaber** [comment]
Regarding this feature request, though: I think what we can offer to do is convert anything that is a _plain_ tuple to a bunch (which will behave like a namedtuple in the absence of new attributes). Would that address this issue @JosefKutas?

**Comment by JozsefKutas** [comment]
Yes, that sounds fine, thanks for the detailed explanation. Changing the naming of the correlation result object attributes to be more consistent with the other statistical test functions also seems useful.

**Comment by mdhaber** [comment]
I'll reopen this, since it's still a valid enhancement request.

**Comment by mdhaber** [comment]
@JozsefKutas would you like to help add these?

I made gh-16387 as an example. We could use help taking a look through all the stats functions for those that currently return a plain tuple and making similar for those.

**Comment by JozsefKutas** [comment]
Sure, I'd be happy to help. I'll check out your PR later and see what I can do.

**Comment by mdhaber** [comment]
That would be terrific. While you're looking, if you see any stats functions that don't have attributes `statistic` and `pvalue`, it would be good to note that, too. We might want to also go through and standardize - probably not actually removing the old attributes, but just adding `statistic`/`pvalue` and using those in the documentation.

**Comment by JozsefKutas** [comment]
OK, I'll keep that in mind.

**Comment by JozsefKutas** [comment]
I've gone through the correlation functions, statistical tests and contingency table functions.

The following functions return plain tuples:
- `fisher_exact`
- `chi2_contingency`
- `median_test`
- `mood`
- `siegelslopes`
- `theilslopes`

I've just submitted a pull request for `fisher_exact` - if the tests pass and everything looks OK, I can submit pull requests for the others.

Regarding missing statistics and pvalues:
- `spearmanr`, `pointbiserialr`, `kendalltau`, `weightedtau` and`somersd` are all missing `statistic` (it's currently `correlation`).
- `linregress`, `siegelslope` and `theilslope` are missing `statistic` and/or `pvalue`, but I don't think it's an issue.
- `multiscale_graphcorr` is missing `statistic` (it's currently `stat`).
- `anderson` and `anderson_ksamp` are both missing `pvalue`.
- `binomtest` is missing `statistic`.

One other inconsistency is that `anderson` takes a `dist` parameter, while `kstest` and `cramervonmises` take a `cdf` parameter.

**Comment by mdhaber** [comment]
Thank you for that list! I don't see any reason not to convert those first four plain-tuple returns to bunches as we've started in gh-16407 and gh-16387. 

`siegelslope` and `theilslopes` were recently taken care of in gh-16183. Here's a link to the development version of the documentation so you can see that: 
http://scipy.github.io/devdocs/reference/index.html
I agree that we can leave those and `linregress` alone.

I'd be in favor of adding `statistic`/`pvalue` as an alias for attributes of these functions:

- For `multiscale_graphcorr`, add `statistic` as an alias for `stat`.
- For `anderson` and `anderson_ksamp`, add `pvalue` as an alias for `significance_level`. (IIRC it's interpolated from tabulated values. I've thought about using `monte_carlo_test` to improve this - and written about that in some old issues - but that is on the backburner while we work through some more pressing consistency issues and bugs.)
- For `binomtest`, add `statistic` as an alias for `proportion_estimate`. 

The point is not to give the user multiple ways of doing things, but to introduce some consistency where there wasn't really a reason to deviate from the norm. 

The thing that I think is most likely to be controversial is adding `statistic` as an alias for `correlation` in the correlation functions.    Personally, I see more similarities than differences between these tests and other hypothesis tests, so I would prefer to add the alias to these, too.  We already started to go in this direction with [`pearsonr`](http://scipy.github.io/devdocs/reference/generated/scipy.stats.pearsonr.html#scipy.stats.pearsonr), which we changed from a tuple to a Bunch with attributes `statistic` and `pvalue` in gh-15586. As a compromise, I'd be willing to add `correlation` as an alias for `statistic` to `pearsonr`, too, so that all correlation functions are the same in that regard. Let's see what others think.

**Comment by mdhaber** [comment]
Tracking:

Bunchify:
- [x] combine_pvalues - gh-16387
- [ ] fisher_exact - gh-16407
- [ ] chi2_contingency
- [ ] median_test
- [ ] mood

Add Aliases:
- [ ] multiscale_graphcorr
- [ ] anderson 
- [ ] anderson_ksamp
- [ ] binomtest

If there is more support for unifying the correlation functions, I'll add that here.

**Comment by mdhaber** [comment]
@JozsefKutas would you be interested in continuing this by adding those aliases?

**Comment by JozsefKutas** [comment]
Sure, I'll add aliases for `multiscale_graphcorr` and `binomtest`.

I'm not sure about `anderson` and `anderson_ksamp`. Above you mention interpolation from tabulated values, but the functions currently just return arrrays of critical values at predefined significance levels. I'm not sure adding `pvalue` as an alias of `significance_level` makes sense here.

**Comment by mdhaber** [comment]
I plan to make both of them return p-values (you're right, I think only `anderson_ksamp` does now). I can take care of that then.

**Comment by tupui** [comment]
For the aliases. Should we deprecate the old names? I am not sure about keeping around 2 ways of doing things. E.g. in `distance.cdist` it's a mess with all the aliases.

**Comment by JozsefKutas** [comment]
I've added the alias for `binomtest`, which returns it's own results class.

Both `multiscale_graphcorr` and `anderson_ksamp` return namedtuples. I could use inheritance:

```python
class Anderson_ksampResult(namedtuple('Anderson_ksampResult',
                           ('statistic', 'critical_values', 'pvalue'))):
    __slots__ = ()
    @property
    def significance_level(self):
        return self.pvalue
```

This wouldn't work so well for bunchs as `__setattr__` bypasses the usual `AttributeError` for properties.

Another option might be to convert these objects to bunches, and add support for aliases in the `make_tuple_bunch` function.

**Comment by JozsefKutas** [comment]
I'll ignore `anderson`, though I did notice a couple of issues when looking at the code:
- Should `cdf` be allowed as an alternative parameter name (using the `_rename_parameter` decorator maybe) for `dist`? This would make `anderson` more consistent with `kstest`, `cramervonmises`, etc.
- The `ValueError` raised if the `dist` parameter is not recognised should probably mention `gumbel_l` and `gumbel_r`.

**Comment by mdhaber** [comment]
> Another option might be to convert these objects to bunches, and add support for aliases

I think you can convert them to bunches and just add the attribute manually after creating the object, e.g.
`res.statistic = res.stat`.

**Comment by JozsefKutas** [comment]
Thanks, I've added aliases for both result classes following that approach.

**Comment by mdhaber** [comment]
@JozsefKutas I added two more to the list above. I guess we missed the things in `scipy.stats.contingency` on the first pass. Anything else to add?

**Comment by JozsefKutas** [comment]
My bad, I didn't spot `contingency.crosstab`. We did `chi2_contingency` though - it's already on the list.

I think that should be it, but I only looked through the statistical test functions (anything under the correlation, statistical tests and contingency table sections in the docs). I just had a quick look, and there are a few other functions returning plain tuples:
- `bayes_mvs` (returns a tuple of namedtuples),
- some transformations: `boxcox` and `yeojohnson`,
- some plot-tests: `ppcc_plot`, `probplot`, `boxcox_normplot` and `yeojohnson_normplot`.

I'm not sure if modifying these is within the issue scope though.

I'll submit a PR for `contingency.crosstab`.

**Comment by mdhaber** [comment]
<facepalm>

Issue scope is up to you! 

Personally, I'm ok with leaving the rest out of it. There is hope of a consistent interface among the statistical test functions, but the rest is quite varied, so I'm happy to leave it alone for now.

**Comment by j-bowhay** [comment]
Is there anything actionable left for this issue?

**Comment by JozsefKutas** [comment]
Hi Jake,

Thanks for dealing with `crosstab` - I've had a busy month at work and didn't have the time to follow up on it.

Based on @mdhaber's response, I think I'll leave the other functions mentioned in my previous comment alone. I'm not sure if there's much value added by converting the result objects for those functions.

I think the only item that remains unresolved is what should be done with the correlation functions. I'm not sure what the plan is here - at the moment I think `pearsonr` uses `statistic`, while the others use `correlation`. Should aliases for `statistic` be added to the other correlation functions?

**Comment by mdhaber** [comment]
I think we should add `statistic` as an alias to all of them. There's no harm in it, since it's unlikely that a user would accidentally use that attribute name expecting something different, and I don't think we're reserving that name for some unforeseen functionality. Let's add it for consistency. And just to complete the job, add `correlation` as an alias in `pearsonr`. 
What do you think @tupui @tirthasheshpatel ?

**Comment by tupui** [comment]
+1 on this plan. I like the consistency here and to me the API should bend towards API usability vs technical accuracy for naming things to make things more inclusive/widely understandable.

**Comment by JozsefKutas** [comment]
OK, I should be able to do the correlation functions tomorrow then, unless @j-bowhay would prefer to.

**Comment by j-bowhay** [comment]
> OK, I should be able to do the correlation functions tomorrow then, unless @j-bowhay would prefer to.

Go for it, happy to have a look at the resulting pr

**Comment by JozsefKutas** [comment]
I've submitted PRs covering the correlation functions. I also changed some `mstats` functions where they were referenced by the `stats` functions, but otherwise didn't focus on them.

**Comment by JozsefKutas** [comment]
Thanks for the PR reviews. I've edited the 1.10 release notes wiki to mention the changes to the attribute naming. Unless there's anything I've missed, I think this issue can be closed.

**Comment by mdhaber** [comment]
Yup, I think that's everything we discussed, so I don't think we need to track this anymore. Thanks @JozsefKutas @tupui @j-bowhay!
