### ISSUE TITLE
BUG: interp2d does not return scalar as interp1d does

### ISSUE THREAD

**Issue by londumas** [scipy/scipy#16396]
### Describe your issue.

if given a scalar sp.interpolate.interp1d returns a scalar. I would expect the same kind of behavior for interp2d.

### Reproducing Code Example

```python
import numpy as np
import scipy as sp
import scipy.interpolate

seed = 42
size_x = 2
size_y = 3
test_number_x = 1.0
test_number_y = 2.0

np.random.seed(42)

x = np.random.random(size_x)
y = np.random.random(size_y)
z = np.random.random( (y.size, x.size) )

f = sp.interpolate.interp1d(x, z[0, :], bounds_error=False, fill_value=1.1)
res = f(test_number_x)
print(res, res.shape, type(res))

f = sp.interpolate.interp2d(x, y, z, bounds_error=False)
res = f(test_number_x, test_number_y)
print(res, res.shape, type(res))
```

### Error message

```shell
1.1 () <class 'numpy.ndarray'>
[0.05808361] (1,) <class 'numpy.ndarray'>
```

### SciPy/NumPy/Python version information

1.7.3 1.21.5 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @londumas, thank you for reporting. IMO we should not return scalars and the behaviour of `interp2d` is better. Then there is no difference calling with one or more values.

**Comment by WarrenWeckesser** [comment]
There is a bug here; the return value should probably always be a 2-D array.  The [docstring of the `__call__` method](https://scipy.github.io/devdocs/reference/generated/scipy.interpolate.interp2d.__call__.html) says that the inputs `x` and `y` are expected to be 1-D arrays, and the return value is a  "2-D array with shape (len(y), len(x))" [*].   There is no explicit statement of this, but the mental model that I get from that docstring is that scalar inputs (if not treated as an error) would be treated as 1-D arrays with length 1.  So I expect `f(1, 2)`, `f([1], 2)` and `f(1, [2])` to all return a 2-D array with shape (1, 1).

Alternatively, if a scalar is not implicitly cast to 1-D, then I would expected `f(1, 2)` to return a scalar, both `f([1], 2)` and `f(1, [2])` to return an arrays with shape (1,), and `f([1], [2])` to return an array with shape (1, 1).  Similarly I would expect `f(1, [1, 2, 3])` and `f([1, 2, 3], 1)` to return 1-D arrays with shape (3,), but that is not what currently happens:

```
In [10]: f(1, [1, 2, 3])
Out[10]: 
array([[0.05808361],
       [0.05808361],
       [0.05808361]])

In [11]: f([1, 2, 3], 1)
Out[11]: array([0.05808361, 0.05808361, 0.05808361])
```
The first result has shape (3, 1), but the second has shape (3,).  I suspect this breaks anyone's mental model for what *should* happen, so I have no problem calling that a bug.

If we didn't have to deal with backwards compatibility, I would just delete this `if` statement at the end of the `__call__` method of `interp2d`:

https://github.com/scipy/scipy/blob/69661a2490072e6c1a47d708a6802d6eeb53ff1a/scipy/interpolate/_interpolate.py#L313-L314

(I might also update the code so that `f([], [1, 2, 3])` *just works*, and returns an array with shape (0, 3), but that is a separate issue with much lower priority.)

I don't have a strong opinion about how to fix this while minimizing backwards incompatibility.  If we can say that *any* current behavior where the output is not 2-D is a bug, then the fix is easy, but I have no idea about how that would impact downstream projects and users.  The other alternative that makes the most sense to me is that output dimensions of inputs that were scalar are dropped.  (Note: this cannot be implemented with `np.squeeze`; the code would need to distinguish a scalar input from a 1-d input of length 1.)  This would imply that `f(1, 2)` returns a scalar, as @londumas expected.

-----

[*] Note: the `__call__` method is definitely *not* broadcasting its arguments.  Its behavior is a bit closer to the `outer` method of a ufunc, but it is not consistent with that API either.

**Comment by ev-br** [comment]
FWIW, I'd consider interp2d legacy (in a sense of Ralf's recent suggestion) or maybe even make a case to deprecate it in favor of the RegularGridInterpolator  (cf https://github.com/scipy/scipy/issues/7663#issuecomment-1153669263 though). The current interp2d behavior is... shall I say extravagant, in several ways.

**Comment by tupui** [comment]
Then what about we actually start the process for the next release?

cc @h-vetinari

**Comment by ev-br** [comment]
A suggestion to deprecate this should certainly go through the mailing list and should include a lot of justification (the interpolate project lists several open issues from the tracker, under the fitpack rubric). It may be a bad idea in the end or a scipy 2.0 type event.

**Comment by tupui** [comment]
If you say that `RegularGridInterpolator` should be preferred, we could at least start with recommending it in the doc of `interp`.

**Comment by ev-br** [comment]
Indeed! This is in the same project, under the doc rubric :-). Am planning to get to it soon (tm)

**Comment by ev-br** [comment]
Cross-ref an (at least superficially) similar change in scipy.stats:  https://github.com/scipy/scipy/issues/16418
Given how that one develops, I personally am even further leaning towards keeping interp2d warts be. 

@londumas  could you try using `RegularGridInterpolator` instead of `interp2d`? We'd be really interested in whether this works at all for your use case, what are the sticky points etc.

**Comment by ev-br** [comment]
`interp2d` is finally deprecated in scipy 1.10, gh-17180. This issue, and Warren's analysis specifically, was a last straw. If you are willing to put up with this deprecated thing *breaking anyone's mental model for what should happen*, you can keep doing it for a while until it is finally removed; otherwise consider switching to better, recommended interpolation routines.

I'm going to close this issue. Thanks @londumas for reporting this, thank you @WarrenWeckesser for the analysis!
