### ISSUE TITLE
BUG: breaking change: scipy.stats.mode returned value has changed shape without deprecation

### ISSUE THREAD

**Issue by ogrisel** [scipy/scipy#16418]
### Describe your issue.

The scikit-learn nightly CI started to fail because of a recent change in scipy `main`:

- https://github.com/scikit-learn/scikit-learn/pull/23633#issuecomment-1157406443

In scipy `main`:

```
import numpy as np
from scipy import stats

stats.mode(np.ones(3))[0]
```

returns `1.0` while previously it would return:

```
array([1.])
```

Maybe a deprecation cycle is needed for this change?

### Reproducing Code Example

```python
import numpy as np
import scipy

scipy.stats.mode(np.ones(3))[0][0]
```

### Error message

```shell
IndexError: invalid index to scalar variable.
```

### SciPy/NumPy/Python version information

1.10.0.dev0+0.df3fe4e 1.24.0.dev0+102.gb84a53df9 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
We could do a deprecation cycle, but please see the [mailing list post] (https://mail.python.org/archives/list/scipy-dev@python.org/thread/SOM7EJ3V4GFC2VPOB2EVDWU4POOW3CQY/#SOM7EJ3V4GFC2VPOB2EVDWU4POOW3CQY) and related issue gh-15423.

Previously, `mode` retained the dimension it acted along, unlike almost all (all?) other `scipy.stats` reduction operations. Due to the inconsistency, this behavior was considered a bug, so it changed without a deprecation cycle. A `keepdims` parameter was added to mitigate the change, but the default is currently `False`. The change will be documented in the 1.9.0 release notes (see gh-16248 - although it's in the enhancement section only right now; it would need to be added to the Backward Incompatible changes section).

We could make the default value `keepdims=True` for `mode` and raise a warning about a future change in behavior, but that will still probably break dependent library CI, and the changes required would be the same: apply `keepdims=True` or change indexing.

Opinions here? 

_Note before this is closed: even if we don't make a change in behavior here, we need to copy the release note entry about the change into the Backward Incompatibility section._

**Comment by ogrisel** [comment]
We can surely adapt the scikit-learn `main` branch to deal with either kind of returned values depending on the version of scipy so that scikit-learn 1.2 (in november) will be able to work with any scipy versions.

However as soon as scipy 1.9 is out, this will break the previously released scikit-learn 1.1.1 (and all previous scikit-learn versions) for our users. At this time, we do not plan to prepare a scikit-learn 1.1.2 bugifx release: the [1.1.2 milestone]([scikit-learn 1.1.2](https://github.com/scikit-learn/scikit-learn/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.1.2)) is currently empty.

I don't know if there will be other important bug fixes in scikit-learn soon, but I am a been reluctant to release 1.1.2 just to mitigate this problem.

**Comment by tupui** [comment]
> However as soon as scipy 1.9 is out, this will break the previously released scikit-learn 1.1.1 (and all previous scikit-learn versions) for our users.

I would argue that this is true for any big we are fixing without deprecating the wrong behavior first.

Still, if this function is vital for scikit-learn we still have time to adjust things. Otherwise users can still pin their version or update to latest scikit-learn.

**Comment by ogrisel** [comment]
> Otherwise users can still pin their version or update to latest scikit-learn.

If scipy 1.9 is released in the coming month, then 100 000's of users are likely to have broken pipelines in production or broken tutorial code in ML classes... Asking all of them to pin their versions of scipy until scikit-learn in 1.2 in November 2022 is not likely to be very helpful (most of students learning data science and Python don't even understand what pinning a version is do not even necessarily realize that scipy exists ;).

So in practice it will mean that we will release an anticipated scikit-learn 1.1.2 release just before scipy 1.9.0 is released to mitigate the problem.

But I scikit-learn is not the only project in this situation maybe it would be worth being conservative and introduce `keep_dims="warn"` that behave like `keep_dims=True` in 1.9 and that issues a `FutureWarning` that scipy 1.10 or 1.11 will change the default behavior to `keep_dims=False`.

**Comment by tupui** [comment]
That's why I am asking if this function is used in major parts of scikit-learn, hence completely breaking it. Or if it's just for a few minor functions.

**Comment by ogrisel** [comment]
It's only breaking in a missing value imputation tool (albeit with a non default parameter). I know that this tool is used in at least one introductory machine learning tutorial.

Also: https://github.com/search?q=SimpleImputer+most_frequent&type=code

But again we can release an anticipated scikit-learn 1.1.2 if change of behavior is only breaking scikit-learn. But it's likely that other code bases will be similarly impacted.

**Comment by mdhaber** [comment]
Looks like we didn't add `keepdims` actually (because <long explanation>). I'll add `keepdims` and make the default warn about the change.

**Comment by ogrisel** [comment]
Actually we will need to release scikit-learn 1.1.2 soon before numpy 1.24 is released anyways because of https://github.com/scikit-learn/scikit-learn/pull/23654.

So feel free to do as you prefer, independently of scikit-learn.

**Comment by mdhaber** [comment]
@ogrisel I opened gh-16429 to work on this. It reverts the changes of gh-15423 so that the default behavior of mode is to retain the axis it acts along (as it was), but warns that this will change in SciPy 1.11.0. It hastily adds a `keepdims` parameter, but the behavior in edge cases is not perfect. I wonder if it would work to just revert gh-15423 and warn about the changing behavior but not offer `keepdims`. Would that work for sckit-learn?

**Comment by ogrisel** [comment]
I just realized that #16429 was closed. So shall we close this issue as WONTFIX? If so we will do a compat release of scikit-learn to anticipate the next scipy release.

**Comment by tylerjereddy** [comment]
I guess we'll keep an eye on this as we edge closer to SciPy `1.9.0rc1`, especially if there are other projects impacted. Feel free to ping me directly as well since it helps me not miss discussions.

It sounds like the argument for the change is "bug fix" so no deprecation cycle needed to switch from 1-D array to scalar? If it truly is a bug fix, and not debatably something else, that would be consistent with normal policy I think. If it is unusually disruptive though, we can keep an eye on it if it really will be disruptive to hundreds of thousands of users without a scikit-learn shim.

**Comment by mdhaber** [comment]
> not debatably something else

To be fair, it is debatably something else. The behavior was a deliberate "feature" by the author of `stats.mode` - albeit one that disregarded the convention set by other reduction operations (e.g. `np.mean`, `np.var`, `stats.skew`). It doesn't give numerically incorrect results, and probably most existing users have found a workaround that breaks if we fix it without warning. So I can revive gh-16429 if desired.

**Comment by josef-pkt** [comment]
removing inconsistencies for functions that work otherwise correctly is NOT a bugfix if it breaks backwards compatibility.

It also broke a statsmodels function, although one that is not very heavily in use.

**Comment by tupui** [comment]
@josef-pkt as said before this was raised on the mailing list. It would have been more productive to raise your concerns when we asked for feedbacks... This was approved by 4 stats regular maintainers.

**Comment by mdhaber** [comment]
> removing inconsistencies for functions that work otherwise correctly

Should also mention function does not work correctly. There are several unambiguous bugs in 1.8.0, and this axis inconsistency is one of the things holding up the fixes.

**Comment by josef-pkt** [comment]
I never used `mode` in any of my code and didn't know statsmodels uses it.
There are too many changes in scipy.stats that might break backwards compatibility in some cases. I only look at the ones that look critical for my use cases.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mode.html
has an example where a one element array is returned.
So, this was a documented "feature".

Aside:
When nan policy was initially added, my definition of or instead of "propagate" was "don't check" which means behavior is undefined if there are nans and depends on the implementation details. And that is designed for the case when the user assures that there are no nans.

**Comment by ev-br** [comment]
Maybe, just maybe, the right thing to do is to revert the change in 1.9.0 and keep it in main to give downstream time to adapt?

**Comment by ogrisel** [comment]
Yes. If you also go the route of issuing a future warning we should also silence it in scikit-learn.

**Comment by jpl-jengelke** [comment]
There appears to be a **regression** with this issue in SciPy 1.11.1, see https://github.com/rzellem/EXOTIC/issues/1206.

Please reopen.
