### ISSUE TITLE
Is there any command in scipy to find eigen value and eigen vectors similar to Julia's Eigen without scaling the matrix?

### ISSUE THREAD

**Issue by Vishnu213** [scipy/scipy#16509]
This is the command in Julia with the scale option:
D,V=eigen(K; permute=true ,scale=false,sortby=nothing). 

Also in Matlab, we can carry out the similar operation using: eig(K, 'nobalance') command. 

Thank you in advance!

**Comment by ilayn** [comment]
In SciPy we shoot straight to `geev` routine from LAPACK with no possibility of intervening. Hence we don't have an option to turn it off anyways. But!

_No balancing_ was introduced because in certain cases balancing was causing problems and `eig` was doing worse than for the case working with original arrays. But since then (newer than version 3.6ish if I remember correctly) LAPACK implementations made it virtually impossible to hit those cases. So things are much better and we can use balancing without any concerns. You can read about it in this paper http://arxiv.org/abs/1401.5766v1

**Comment by Vishnu213** [comment]
Thanks a lot for your response and also for the nice paper @ilayn 
I understand your point on why 'no balance option' is not included in scipy package. I would like to know if there is any already available python command/package that can employ 'no balance option'? your suggestion will be really helpful. 
Look forward to your response.

**Comment by ilayn** [comment]
Anything that exposes `geevx` LAPACK routine would do. If you are familiar with Cython then you can import `geevx` from `scipy.linalg.cython_lapack` but this is not available in Python wrappers hence you must use Cython for it. 

Probably we should do it at some point.
