### ISSUE TITLE
BUG: API docs difficult to read in dark mode

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#16598]
### Describe your issue.

Testing out the dark mode for a recent PR, I found (subjectively) that the API was difficult to read in dark mode due to the yellowish background. The actual parameter docs etc. look fine.

Examples:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/40656107/178918954-c3d4ccec-1275-480d-b67d-1392b198ff0c.png">
<img width="494" alt="image" src="https://user-images.githubusercontent.com/40656107/178919077-0bae3ea3-696a-4853-a76d-3a5dab3d3844.png">

While not being a designer I guess that another color would be better for the dark mode.

### Reproducing Code Example

Browser: Chrome 103

### Error message

[Example Doc URL](https://output.circle-artifacts.com/output/job/dc086891-9efa-4dae-9d0a-d1e421147099/artifacts/0/html/reference/generated/scipy.stats.directionalmean.html#scipy.stats.directionalmean)

### SciPy/NumPy/Python version information

irrelevant

**Comment by tupui** [comment]
Ah right it's the highlights color. I will have a look 👀

**Comment by tupui** [comment]
I had a look and this is because we are using the same colours as NumPy for the body.

We want these 2 projects to have the same feel and this is why we originally went with the same colours. I could fix this by changing the contrast here and on NumPy (e.g. use `#939393`), but I am not a UX/UI/designer.

I propose to make a meeting with NumPy and SciPy to discuss what we want to do with colours and dark theme. This is not related to the theme itself as here we want to have our own colour scheme. Or you decide on a colour palette for NumPy and we follow here.

cc @seberg @isabela-pf @MarsBarLee @jarrodmillman

**Comment by rgommers** [comment]
I'd personally prefer to use the theme defaults for SciPy, because the theme is getting wide adoption. NumPy probably should do the same, but that's for the NumPy issue tracker.

**Comment by tupui** [comment]
Just opened a PR. If there are design/colours concerns, we can address these on the theme side. We have a good working relationship with the theme, they would be happy to get feedbacks on all that and would be happy to make changes for us.
