### ISSUE TITLE
DOC: Speeding up scipy with numba?

### ISSUE THREAD

**Issue by lazarcf** [scipy/scipy#16606]
### Is your feature request related to a problem? Please describe.

I've sped up our prediction function which simply compared a ~700 dimensional embedding against ~6000 others from 840ms to 36ms by first caching the embeddings as np.arrays and then just running numba on spatial.distance.cosine. this is at least a 11x speed improvement if you discount the list to np.array conversion. 

Has anyone considered integrating numba in scipy?

**Comment by ilayn** [comment]
@lazarcf Thank you for the analysis. We typically use Cython to systematically improve performance and occasionally fully C implementations. Cython is for maintainers a more common tool to use as we have more experience with it and we do have all the build mechanism for that. Numba would be a new dependency and we don't have any routes for handling Numba compiled code. 

Hence it leads to a much bigger discussion of accepting Numba as a new dependency and we would prefer first to see whether Cython would get us as far. This doesn't mean a no but it is a probably no until we have a stronger reason to do it. Let's see what others would say about it.

**Comment by melissawm** [comment]
Instead, would documentation (such as a tutorial) on how to do this be useful?

**Comment by lazarcf** [comment]
> Instead, would documentation (such as a tutorial) on how to do this be useful?

I would go as far as adding warnings when calling a function with a python list that will be converted to a np.array. Just caching my embeddings as np.arrays achieved a 2x speed improvement.

Also, yes, suggesting using numba in docs should help but I think there's still some work to be done about making numba easier to interface with scipy. My way of doing it was to simply copy the function implementation from scipy, adding the numba decorator on it (that's all you really need) and then making sure to "warm it up" by calling it a couple of times when the prediction service starts

**Comment by tupui** [comment]
FYI. If you don't need to touch the underlying implementation, you can decorate a function without having the copy/paste and add the decorator. Simply use the decorator as a function calling the function you want to decorate.

**Comment by rgommers** [comment]
>> Has anyone considered integrating numba in scipy?

> Hence it leads to a much bigger discussion of accepting Numba as a new dependency and we would prefer first to see whether Cython would get us as far. This doesn't mean a no but it is a probably no until we have a stronger reason to do it. Let's see what others would say about it.

This has been extensively discussed in the past, e.g.:
- mailing list thread [Numba as a dependency for SciPy?](https://mail.python.org/archives/list/scipy-dev@python.org/thread/6CXEWVQXZJ5HHQZFC6Q5PPWUHC3EXIN7/#6WI3CLCMMH73I6MPE3GDE4SX27U3RYTR)
- mailing list thread [Recent Numba updates of interest](https://mail.python.org/archives/list/scipy-dev@python.org/thread/UUH6YCCFTB5RPKBR2KHZYWUZK3WPAKZF/#UUH6YCCFTB5RPKBR2KHZYWUZK3WPAKZF)
- SciPy'21 presentation [Building SciPy kernels with Pythran](https://www.youtube.com/watch?v=6a9D9WL6ZjQ&t=2s)

Not much has changed since then. We won't be able to use Numba, the dependency is too heavy and not stable enough. 

> Also, yes, suggesting using numba in docs should help but I think there's still some work to be done about making numba easier to interface with scipy

See http://scipy.github.io/devdocs/dev/roadmap.html?highlight=numba#performance-improvements. Not much progress there though.

> FYI. If you don't need to touch the underlying implementation, you can decorate a function without having the copy/paste and add the decorator. Simply use the decorator as a function calling the function you want to decorate.

This may indeed work, depending on the implementation. It is not guaranteed to be broken by any new SciPy release, so I would not want to recommend this in the docs though.

**Comment by rgommers** [comment]
It's not clear to me that we should put anything in the SciPy documentation, or where. I'll leave this issue open to see if others have a good idea there. I did change the title and labels to a doc topic, since that's the only option on the table here.

**Comment by rgommers** [comment]
No more comments and this isn't actionable, so I will close this now. Thanks all.

Re docs, note that we do have a doc section on extending `ndimage` with Numba: http://scipy.github.io/devdocs/tutorial/ndimage.html#extending-scipy-ndimage-in-c. I don't think we'll add other docs.
