### ISSUE TITLE
bugs in boxcox transformation?

### ISSUE THREAD

**Issue by yoyohoho0221** [scipy/scipy#16674]
Hi there,
I recently tried to use boxcox transformation on my data, there's one wired result I got from the boxcox function.

Input data:
`data = [15013173, 15524598.84
            , 16145110.08, 16282314.86, 15850144.66
            , 15798809.06, 15893406.71
            , 16642285.24, 16673532.39
            , 15305571.37, 14797627.54
            , 15167733.04, 16111390.71
            , 15345859.54, 15099945.71
            , 15214866.11, 15859518.1, 17425665.02]`
Boxcox:
`trans, lam = boxcox(data)`

The output is `trans=[0.159572, 0.159572, 0.159572, 0.159572,... , 0.159572]`
The same value for all inputs, Why does it happen? Could you help?

**Comment by tupui** [comment]
Hi @yoyohoho0221, thank you for reporting. It seems like an optimization issue as if you manually set `lmbda` you will see non constant values. Did you try to play with the parameter `optimizer`? See the doc for more info https://scipy.github.io/devdocs/reference/generated/scipy.stats.boxcox.html and in the parameter's doc there are links to an example on how to use this param.

**Comment by WarrenWeckesser** [comment]
This is a numerical issue that arises with the Box-Cox transformation when the data has large values with low variance.  Note that the value of lambda is approximately -6.26676:
```
In [42]: from scipy.stats import boxcox

In [43]: data = np.array([15013173, 15524598.84 , 16145110.08, 16282314.86, 1585
    ...: 0144.66 , 15798809.06, 15893406.71 , 16642285.24, 16673532.39 , 1530557
    ...: 1.37, 14797627.54 , 15167733.04, 16111390.71 , 15345859.54, 15099945.71
    ...:  , 15214866.11, 15859518.1, 17425665.02])

In [44]: trans, lam = boxcox(data)

In [45]: lam
Out[45]: -6.266763727892708
```
Consider what happens when this value of lambda is used to transform your data with the Box-Cox formula `(y**lam - 1)/lam`.  First look at `y**lam`:
```
array([1.06351229e-45, 8.62133010e-46, 6.74388330e-46, 6.39556362e-46,
       7.56994829e-46, 7.72541877e-46, 7.44174057e-46, 5.57653642e-46,
       5.51136641e-46, 9.42422117e-46, 1.16439485e-45, 9.97394050e-46,
       6.83282264e-46, 9.27023793e-46, 1.02578761e-45, 9.78188534e-46,
       7.54195401e-46, 4.18000850e-46])
```
Those values are all very small.  In fact, they are all less than the [machine epsilon](https://en.wikipedia.org/wiki/Machine_epsilon) for 64 bit floating point values, so when these values are added to -1, the result is -1 in each case:
```
In [47]: data**lam - 1
Out[47]:
array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1.])
```
All the information about the variation in the original data has been lost.

For completeness, here's the last step, which gives the value that you observed.  Each value is -1/lambda:
```
In [48]: (data**lam - 1)/lam
Out[48]: 
array([0.159572, 0.159572, 0.159572, 0.159572, 0.159572, 0.159572,
       0.159572, 0.159572, 0.159572, 0.159572, 0.159572, 0.159572,
       0.159572, 0.159572, 0.159572, 0.159572, 0.159572, 0.159572])
```
Probably the best way to avoid this problem is to scale your data before passing it to `boxcox()`, perhaps by dividing through by its mean (which is a way to nondimensionalize the input), or by a sufficiently large constant (which is equivalent to changing the units in which your data are expressed).  For example,
```
In [52]: trans2, lam2 = boxcox(data/data.mean())

In [53]: lam2
Out[53]: -6.266765941303631

In [54]: trans2
Out[54]: 
array([-0.05900462, -0.01761648,  0.02096944,  0.02812822,  0.00399188,
        0.00079659,  0.00662684,  0.04496114,  0.04630054, -0.03411776,
       -0.07973835, -0.04541578,  0.01914153, -0.03095305, -0.05125132,
       -0.0414686 ,  0.00456722,  0.07366305])
```

**Comment by yoyohoho0221** [comment]
Thanks a lot for your kind and quick responses.
