### ISSUE TITLE
BUG: support for scipy.ctypeslib in version 1.9.0

### ISSUE THREAD

**Issue by JamesLYC88** [scipy/scipy#16775]
### Describe your issue.

When I use the software [liblinear](https://github.com/cjlin1/liblinear), I find an error when calling scipy.ctypeslib.asarray.
After some investigation, I find that scipy.ctypeslib acts normal in scipy==1.8.1 but produces an error in scipy==1.9.0.
Next, I try to call `python -Wd <command>` in scipy==1.8.1 but do not see any deprecation warning messages related to scipy.ctypeslib.
Is this a bug or does scipy==1.9.0 deprecate scipy.ctypeslib?
Further, if scipy.ctypeslib is not supported anymore, are there any alternative (equivalent) ways to call scipy.ctypeslib related functionality?

### Reproducing Code Example

```python
import scipy
scipy.__version__
from scipy import ctypeslib
```

### Error message

```shell
# successful example
>>> import scipy
>>> scipy.__version__
'1.8.1'
>>> from scipy import ctypeslib

# failed example
>>> import scipy
>>> scipy.__version__
'1.9.0'
>>> from scipy import ctypeslib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ctypeslib' from 'scipy' (XXX/lib/python3.8/site-packages/scipy/__init__.py)
```

### SciPy/NumPy/Python version information

1.9.0 1.22.4 sys.version_info(major=3, minor=8, micro=13, releaselevel='final', serial=0)

**Comment by rkern** [comment]
`ctypeslib` is actually from `numpy`. It is best to import it directly from there.

Mirroring all of the `numpy` symbols in the `scipy` namespace was an early design decision that we probably wouldn't make again. FWIW, I recommend only using `scipy` for the subpackages it explicitly provides and ignoring all of the stuff mirrored from `numpy`. Import `numpy` stuff from `numpy` directly.

The `numpy` mirrors were deprecated in #10290 (and the actual removal of `ctypeslib` and other modules imports from `numpy` in #15230, though that looks mostly incidental). Only functions got the deprecation warning treatment because it's hard to implement a deprecation of accessing a module, unlike calling a function.
