### ISSUE TITLE
BUG: Can't build 1.10 with mingw-w64 toolchain and numpy 1.21.6 in Python 3.10

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#16787]
### Describe your issue.

When trying to meson build Scipy 1.10 on Windows AMD64 with Python 3.10 and the mingw-w64 toolchain the build process:

- installs numpy 1.21.6
- all pyd files that try to link against npymath have this error in the build log 
```
2022-08-05T10:44:53.8879877Z   [910/1556] Linking target scipy/stats/_biasedurn.cp310-win_amd64.pyd
2022-08-05T10:44:53.8880183Z   Warning: corrupt .drectve at end of def file
2022-08-05T10:44:53.8880459Z   Warning: corrupt .drectve at end of def file
```
- those pyd files aren't loadable/importable.

this is probably related to https://github.com/MacPython/numpy-wheels/issues/145, https://github.com/numpy/numpy/issues/20880, https://github.com/numpy/numpy/issues/21629

Those issues arise from numpy wheels using a more recent version of vc142, which mingw isn't interoperable with.

### Reproducing Code Example

```python
a
```

### Error message

```shell
2022-08-05T10:44:53.8879877Z   [910/1556] Linking target scipy/stats/_biasedurn.cp310-win_amd64.pyd
2022-08-05T10:44:53.8880183Z   Warning: corrupt .drectve at end of def file
2022-08-05T10:44:53.8880459Z   Warning: corrupt .drectve at end of def file
```
 The error experienced during loading the PYD is:
```shell
ImportError: DLL load failed while importing _biasedurn: %1 is not a valid Win32 application.
```

### SciPy/NumPy/Python version information

Python 3.10, numpy-1.21.6, scipy 1.10

**Comment by andyfaff** [comment]
THis will entail changing the maximum numpy version for Python 3.10 to 1.21.4 for Windows AMD64.

**Comment by andyfaff** [comment]
@mattip @rgommers

**Comment by rgommers** [comment]
Thanks for the summary @andyfaff.
 
> This will entail changing the maximum numpy version for Python 3.10 to 1.21.4 for Windows AMD64.

Not the maximum version, just excluding numpy `1.21.6`, `1.22.0`, `1.22.1`. It's also specific to the wheels on PyPI (conda-forge numpy packages are fine) + building from source, so we don't need to forbid anything completely, we just need to pick a non-broken version in `pyproject.toml` and document carefully so we don't run into this again.

I'll open a PR.

**Comment by rgommers** [comment]
Okay, complication for 32-bit Python, there are only `1.21.6` and `1.22.3` wheels: https://github.com/scipy/oldest-supported-numpy/issues/45#issuecomment-1095824036. So we're missing the ones for `1.21.4-5`; fixing this issue is going to un-fix the 32-bit problem so we can't do it in `oldest-supported-numpy`, only in the SciPy `pyproject.toml`. That is fine for now because we don't yet have 32-bit Windows wheels with Meson (the compiler toolchain is still WIP).

@andyfaff you may also be interested in this bit of info: [this comment](https://github.com/scipy/oldest-supported-numpy/issues/45#issuecomment-1101463864) and the following ones: looks like we no longer have to worry about vendoring `msvcp140.dll`.
