### ISSUE TITLE
BUG: documentation error in scipy.signal.decimate

### ISSUE THREAD

**Issue by jdsahr** [scipy/scipy#16808]
### Describe your issue.

In

https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.decimate.html

The signature of decimate appears thus:

scipy.signal.decimate(x, q, n=None, ftype='iir', axis=- 1, zero_phase=True)

Note the stray "-" in 'axis=- 1'

### Reproducing Code Example

```python
This is is not a code bug; it is a documentation bug
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.2.1 1.20.1 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the issue, @jdsahr.  That is actually the result of a bug in sphinx: https://github.com/sphinx-doc/sphinx/issues/10550.  The bug was fixed in https://github.com/sphinx-doc/sphinx/pull/10551, and I think that should be included in Sphinx 5.1.0.  Something is not right in the list of [bugs fixed](https://www.sphinx-doc.org/en/master/changes.html#id35) for Sphinx 5.1.0; there is a entry that says "py domain: Fix spurious whitespace in unparsing various operators (+, -, ~, and **)", but the corresponding linked pull request doesn't match that.

Assuming the fix did make it into Sphinx 5.1.0, we'll only see an update to our web site when the docs are built with that version.

**Comment by WarrenWeckesser** [comment]
xref: https://github.com/scipy/scipy/issues/16385 is the same issue.
