### ISSUE TITLE
scipy.interpolate.interp2d to not create a mesgrid of two 1D arrays on __call__

### ISSUE THREAD

**Issue by Stoops-ML** [scipy/scipy#16812]
**Is your feature request related to a problem? Please describe.**
Calling the object created by scipy.interpolate.interp2d (an interpolator of a 2D grid) with two 1D arrays creates a 2D output. I assume the object is creating a meshgrid with the two 1D arrays, resulting in a 2D output of interpolated values. 

**Describe the solution you'd like**
I would like the option for the object not to create a meshgrid from the two 1D arrays, rather interpolate each pair of points individually.

**Describe alternatives you've considered**
I have had to use the scipy.interpolate.LinearNDInterpolator class that does not create a meshgrid from the input points. Further, as I am interpolating many points I cannot simply create the 2D matrix of interpolated values from scipy.interpolate.interp2d and take the diagonal due to RAM limitations.

**Comment by ev-br** [comment]
We are highly unlikely to add new features to interp2d--- this is a legacy function and is best avoided in new code. What to use instead depends on what you want to do. TBH, I'm not sure what you mean by *interpolate each pair of points individually*. 

If your 1D arrays, call them `x` and `y` define an unstructured set of points on a 2D plane, and you want to construct a surface, 
LinearNDInterpolator triangulates the points and interpolates that (so that each interpolated value is a linear combination of exactly three points from your arrays `x` and `y`). 

If you are constructing a *curve*  in 2D which passes through your points from `x` and `y`, you can use `splprep` or come up with a parametrization yourself and interpolate the parameter values vs `np.c_[x, y]`.

**Comment by Stoops-ML** [comment]
Okay, thanks for the quick response. I'll continue using the LinearNDInterpolator as it does the job well.

For completeness by *"interpolate each pair of points individually"* I meant the two 1D arrays used as inputs to the __call__ method of the interpolator object will be used to interpolate points without creating a meshgrid from the two arrays. As in the two 1D arrays `x` and `y` of lengths *n* would produce *n* interpolated points from the interpolator object, rather than producing a grid of *(n,n)* points from the object.

**Comment by ev-br** [comment]
Ok, this sounds just the use case for LinearNDInrerpolator/grid data. Glad to hear it works well. 

We won't be adding new functionality in interp2d, so I'll close this. Thanks for confirming that LinearNDInrerpolator works.
