### ISSUE TITLE
BUG: optimize.minimize backwards compatability in scipy 1.9

### ISSUE THREAD

**Issue by bwheelz36** [scipy/scipy#16898]
### Describe your issue.

Hi, we have [some code that works with scipy 1.8 but crashes 1.9](https://github.com/fmfn/BayesianOptimization/issues/350). An example to reproduce is below.
The issue arises in the code than transforms between the new/old bounds definition, but is actually related to the way x0 is defined. 

You can 'fix' this by changing `start` to `start = np.array([0.0])`. We can actually do this in our code too, but I wanted to check if this behavior is intentional or whether this lack of backward compatibility constitutes a bug? 

### Reproducing Code Example

```python
'''
example which will run on scipy 1.8 but not scipy 1.9
'''
from scipy.optimize import minimize
import numpy as np

def objective(x):
    return(x+10)**2

bounds = np.array([[-20, 20]])
start = np.array([0.0]).reshape(-1, 1)
res = minimize(objective, start, bounds=bounds, method="L-BFGS-B")
```

### Error message

```shell
TypeError: object of type 'Bounds' has no len()
```

### SciPy/NumPy/Python version information

1.8/1.9

**Comment by andyfaff** [comment]
At the start of `minimize` this code is called:
```
 x0 = np.atleast_1d(np.asarray(x0))
    if x0.ndim != 1:
        message = ('Use of `minimize` with `x0.ndim != 1` is deprecated. '
                   'Currently, singleton dimensions will be removed from '
                   '`x0`, but an error will be raised in SciPy 1.11.0.')
        warn(message, DeprecationWarning, stacklevel=2)
        x0 = np.squeeze(x0)
```
Because there is more than one dimension in `start` the array is squeezed. We do this squeeze because `minimize` is only designed to work with 1D arrays (problems are experienced with ndim > 1). You should've seen this `DeprecationWarning` when you ran your code.
When the code squeezes `np.array([[0.0]])` you end up with `np.array(0.0)`, which has shape `()`. When `x0.shape[0]` is requested an `IndexError` is raised, `IndexError: tuple index out of range`. I get a different error than you see.

We could fix scipy to make it back compatible by doing  `x0 = np.atleast_1d(np.squeeze(x0))`. However, as you can see from the code snippet above we're going to raise an Error if `x0.ndim > 1` in scipy 1.11. This probably makes it less important to make a 'fix' in scipy; can you fix the downstream code here?

**Comment by bwheelz36** [comment]
Hey, 
Yep I think we can fix in our code - just wanted to bring this to your attention in case it was unintentional. I will close the issue now :-)

**Comment by bwheelz36** [comment]
PS: We are running inside a catch warnings statement for various reasons, so I never saw the deprecation warning - that's on us obviously!

**Comment by andyfaff** [comment]
@mdhaber, do you think we should 'fix' this?

**Comment by mdhaber** [comment]
Hmm I do think this was an unintentional mistake on our part to remove _all_ the dimensions, so from that perspective, yes. We might be able to get it in 1.9.1. I can't push the buttons, but I can review quickly if it's the one-liner you described, @andyfaff.
