### ISSUE TITLE
BUG: scipy 1.7.3 wheels on PyPI require numpy<1.23 in contradiction with pyproject.toml and documentation

### ISSUE THREAD

**Issue by lesteve** [scipy/scipy#16964]
### Describe your issue.

I guess this is not a huge blocker but it does not match the documented supported numpy versions in https://docs.scipy.org/doc/scipy/dev/toolchain.html#numpy. For context we caught this issue in the scikit-learn CI where we were trying to build scikit-learn with the latest numpy and scipy versions from the conda `defaults` channel.

My understanding is that https://github.com/scipy/scipy/pull/14616 was meant to update the requirement to `numpy<1.24` for 1.7.2 and 1.7.3:
https://github.com/scipy/scipy/blob/e132a180363f48b672daa1da1f87df0c22623720/pyproject.toml#L53-L55

In practice, `pip install` errors when trying to install `numpy=1.23.*` and `scipy=1.7.*`.

If I download the wheel, for example this [one](https://files.pythonhosted.org/packages/0e/bd/50badd52af542bc9cbad515f55881578a7316dd53914e5993dcf0c70a937/scipy-1.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl) and look into `/scipy-1.7.3.dist-info/METADATA` `numpy<1.23` is required:
```
Requires-Dist: numpy (<1.23.0,>=1.16.5)
```

`setup.py` requires `numpy<1.23` for 1.7.3:
https://github.com/scipy/scipy/blob/59e6539cf80dc04b16b0f0ab52343381f0a7a2fa/setup.py#L551-L557

so somehow maybe `setup.py` wins in this case?

While I am at it `__init__.py` use `numpy<1.23` for issuing a warning:
https://github.com/scipy/scipy/blob/59e6539cf80dc04b16b0f0ab52343381f0a7a2fa/scipy/__init__.py#L141-L149

### Reproducing Code Example

```python
conda create -n test-env
conda activate test-env
pip install 'numpy==1.23.*' 'scipy==1.7.*'
```

### Error message

```shell
ERROR: Cannot install numpy==1.23.*, scipy==1.7.0, scipy==1.7.1, scipy==1.7.2 and scipy==1.7.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.23.*
    scipy 1.7.3 depends on numpy<1.23.0 and >=1.16.5
    The user requested numpy==1.23.*
    scipy 1.7.2 depends on numpy<1.23.0 and >=1.16.5
    The user requested numpy==1.23.*
    scipy 1.7.1 depends on numpy<1.23.0 and >=1.16.5
    The user requested numpy==1.23.*
    scipy 1.7.0 depends on numpy<1.23.0 and >=1.16.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### SciPy/NumPy/Python version information

N/A

**Comment by tylerjereddy** [comment]
This stuff is always "fun" for us to deal with. I spent a while poking around at more recent versions as well. For example, the latest stable release of SciPy (`1.9.1`) should use the `pyproject.toml` from here: https://github.com/scipy/scipy/blob/maintenance/1.9.x/pyproject.toml#L78. That has `"numpy>=1.18.5,<1.26.0"`.

But if I'm working in say a Python `3.10` `venv` and do i.e., `pip download -v scipy==1.9.1` the output includes `Collecting numpy<1.25.0,>=1.18.5`. So, the offset of `-1` on the NumPy versions vs. our intention will be repeated in the future if we don't change something.

Since the versions of SciPy up to and including `1.9.1` had wheels produced from the distutils backend instead of the new `meson` backend, I tried `pip wheel .` on the latest maintenance release branch to try using `meson` instead, and there `METADATA` looks correct for that particular field with `Requires-Dist: numpy<1.26.0,>=1.18.5` (though Python upper bounds were not supported via `meson` approach last time I checked). That said, `git grep -E -i "1\.25\.0"` does show results on latest maintenance branch:

```
scipy/__init__.py:    np_maxversion = '1.25.0'
setup.py:    np_maxversion = '1.25.0'
```

That comes from https://github.com/scipy/scipy/pull/16353. As you can see from the discussion there, because NumPy and SciPy have roughly overlapping release cycles every 6 months, it is easy to miss bumping the max version of NumPy we support. That wasn't the problem though, I don't think. It looks like I intentionally used `1.26.0` and `1.25.0` in the same PR, probably because in `pyproject.toml` the bound is `<`, while in `__init__.py` we use `>=`, so the max version needs to be 1 lower there. However, in `setup.py` `np_maxversion` uses `<` again, so it probably should have been `1.26.0` in two places and `1.25.0` in one place. Maybe, for the sanity of release manager and reviewers we should try to adjust the logic to require just 1 version in all 3 locations moving forward.

I'll see if I can reproduce locally with the `maintenance/1.7.x` branch and get better metadata with a `setup.py` version adjustment. I'm not sure that we'd issue another point release for that series at this point though, could encounter some weird stuff with ancient wheel rebuilds.

**Comment by tylerjereddy** [comment]
Actually, that's not right either.. I think the same NumPy version should just be used everywhere, though `np_maxversion` is a bad variable name I think, since it is actually "max + 1".

**Comment by tylerjereddy** [comment]
I'm almost certain the same +1 version fix used in the cross-linked PR would work on `1.7.x` as well, since `setup.py` clearly contains the `metadata` data structure used by `setup()`. Let me check with @rgommers to see how far back we may want to backport here if he agrees with this approach.

**Comment by tylerjereddy** [comment]
`1.8.x` looks "ok" to me with all 3 max NumPy versions matching, so `1.7.x` and `1.9.x` are the two questionable ones I think.

**Comment by lesteve** [comment]
> This stuff is always "fun" for us to deal with.

Hopefully this is not too much "fun" to deal with :sweat_smile:

**Comment by rgommers** [comment]
Ah, that is unfortunately. I'm looking forward to deleting `setup.py`, then we only have a single point of truth to deal with. 

I thought `pyproject.toml` would take precedence, and the `setup.py` content was only there for building with `python setup.py xxx`. But apparently not.

I think we'll merge the PR to fix it in `1.9.2`, and leave `1.7.x` for what it is - doing a new release just for this seems too much trouble, and it is a minor problem after all. Does that sound fine @tylerjereddy and @lesteve?

**Comment by lesteve** [comment]
> I think we'll merge the PR to fix it in `1.9.2`, and leave `1.7.x` for what it is - doing a new release just for this seems too much trouble, and it is a minor problem after all. Does that sound fine @tylerjereddy and @lesteve?

I think it is fine, I agree that doing another 1.7 release seems too much work for this.

Would it be worth updating https://docs.scipy.org/doc/scipy/dev/toolchain.html#numpy to have the correct versions supported for scipy 1.7 and 1.9? I can do a PR if that helps.

I think people using the conda `defaults` channel may hit this currently because the latest version on the conda `defaults` channel is scipy 1.7.3 and numpy 1.23.1, but I did not find too many questions about this on the internet. The only one I found is: https://stackoverflow.com/q/73072257.

**Comment by rgommers** [comment]
> Would it be worth updating https://docs.scipy.org/doc/scipy/dev/toolchain.html#numpy to have the correct versions supported for scipy 1.7 and 1.9? I can do a PR if that helps.

That seems useful, thanks.

> I think people using the conda `defaults` channel may hit this currently

That's only a warning, not an error at runtime - so that should not be much of a problem.

**Comment by lesteve** [comment]
- I opened https://github.com/scipy/scipy/pull/16975 to mention numpy support versions for 1.9.2
- for 1.7.2/3 this has already been fixed in https://github.com/scipy/scipy/pull/16766. This would be great if #16766 could be backported to the `maintenance/1.9.x` so that the stable doc is accurate
