### ISSUE TITLE
BUG: Build failure due to problems with shebang line in cythoner.py

### ISSUE THREAD

**Issue by JozsefKutas** [scipy/scipy#17020]
I ran into a problem running `dev.py` that appears to be caused by the shebang line `#!python3`  in the file `scipy/_build_utils/cythoner.py`. If I change it to `#!/usr/bin/env python` then the build works fine.

Most files in scipy with a shebang line use `#!/usr/bin/env python`. Only files in the `_build_utils` use `#!python3`.

Error message when running `python dev.py build`:

```shell
Meson build setup OK
💻  ninja -C /mnt/c/Users/Jozsef/OSS/scipy-test/build
ninja: Entering directory `/mnt/c/Users/Jozsef/OSS/scipy-test/build'
[3/1562] Generating 'scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so.p/_ccallback_c.c'.
FAILED: scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so.p/_ccallback_c.c
/mnt/c/Users/Jozsef/OSS/scipy-test/scipy/_build_utils/cythoner.py ../scipy/_lib/_ccallback_c.pyx scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so.p/_ccallback_c.c
/bin/sh: 1: /mnt/c/Users/Jozsef/OSS/scipy-test/scipy/_build_utils/cythoner.py: not found
[12/1562] Compiling C++ object scipy/_lib/_uarray/_uarray.cpython-310-x86_64-linux-gnu.so.p/_uarray_dispatch.cxx.o
ninja: build stopped: subcommand failed.
Build failed!
```

If I try running `cythoner.py` directly:

```shell
-bash: /mnt/c/Users/Jozsef/OSS/scipy-conda/scipy/_build_utils/cythoner.py: python3: bad interpreter: No such file or directory
```

I'm using conda with WSL (Ubuntu).

**Comment by rgommers** [comment]
Thanks for the report @JozsefKutas. We shouldn't be relying on shebang lines at all, let's fix this to make sure it uses the correct Python interpreter that was already detected by Meson.

**Comment by rgommers** [comment]
This turns out to be slightly annoying. In the below, the `find_program` version works but the `files` one does not:
```meson
cython_tree = declare_dependency(sources: _cython_tree)

cython_cli = find_program('_build_utils/cythoner.py')
invoke_cython = files('_build_utils/cythoner.py')

cython_gen = generator(py3,
  arguments : [invoke_cython, '@INPUT@', '@OUTPUT@'],
  output : '@BASENAME@.c',
  depends : _cython_tree)

cython_gen_cpp = generator(cython_cli,
  arguments : ['@INPUT@', '@OUTPUT@', '--cplus'],
  output : '@BASENAME@.cpp',
  depends : [_cython_tree])
```

The error is:
```
scipy/meson.build:216:0: ERROR: generator keyword argument 'arguments' was of type array[File | str] but should have been array[str] that cannot be empty
```

`generator` takes a single executable, and it seems hard to give it `py3 <source_root>/_build_utils/cythoner.py` where `py3` is the detected Python install from:
```meson
py_mod = import('python')
py3 = py_mod.find_installation()
```

`find_program` is the wrong thing to use, but it's not clear to me if there's a tweak to make this work - in lieu of changing `generator` to `custom_target` everywhere (which would be a lot of churn).

**Comment by rgommers** [comment]
I had a look at it some more. We're not using it wrong, the chapter on generators in The Meson Manual uses as its one example what we are doing:
```meson
idl_compiler = find_program('dsc_compiler.py')

g = generator(idl_compiler,
  output: ...
```
This seems like a design issue in Meson, relying on a shebang is a problem. Here we have a system that has `python` but not `python3`, and in gh-16937 we have an example of a system in the opposite situation (has `python3` but not `python`.

@JozsefKutas can you please confirm that you really don't have a `python3` executable at all? Or does changing the shebang to `#!/usr/bin/env python3` work too?

**Comment by rgommers** [comment]
The relevant Meson issue, with rules for shebang to use per platform, is https://github.com/mesonbuild/meson/issues/3911. 

> @JozsefKutas can you please confirm that you really don't have a `python3` executable at all? Or does changing the shebang to `#!/usr/bin/env python3` work too?

@JozsefKutas a ping on this, can you please check?

**Comment by JozsefKutas** [comment]
Hi, thanks for looking into this and I'm sorry for not responding earlier.

I've just tried with `#!/usr/bin/env python3` and the build runs without problems.

I can run `python3` in console without problems (both in and out of the conda scipy environment, and with completely deactivated), but for some reason it doesn't work with the shebang line (again, regardless of whether conda is activated or not). I've only encountered the problem in WSL.

**Comment by eli-schwartz** [comment]
The problem is that `#!foo` is an invalid shebang altogether, shebang lines are supposed to contain the full path to an executable (that executable can be the env program) plus optionally a single argument (e.g. a program that the env executable will search for on $PATH).

Attempting to run this program directly in any way results in failure -- no matter what system you use.

...

There's actually a more interesting issue. Meson's find_program implementation has a method called `_shebang_to_cmd()`, which is used if the command doesn't have the executable bit set (or on Windows, if the extension isn't in windows_exts). This checks the shebang using very rough heuristics to find a script interpreter, but not actually following the same rules that an OS kernel does. Namely, it special cases any shebang that *ends* with `python3`, even if it begins with nonsense such as the empty string, and runs via its own sys.executable which it knows satisfies "a python3".

This is why, usually, the cythoner.py script works fine. It is not marked executable in git, and thus isn't either executable in a git clone or an sdist. So Meson special cases it in find_program, and logs this:

```
Program _build_utils/cythoner.py found: YES (/usr/bin/python3 /tmp/scipy/scipy/_build_utils/cythoner.py)
```

Apparently, this is broken on WSL as it is somehow executable nonetheless, likely some quirk of WSL permissions. So Meson simply tries to run it directly.

**Comment by eli-schwartz** [comment]
> Thanks for the report @JozsefKutas. We shouldn't be relying on shebang lines at all, let's fix this to make sure it uses the correct Python interpreter that was already detected by Meson.

I am not entirely sure what this is trying to say, but I think it's probably wrong. This script uses pure barebones stdlib python, and does not care what python interpreter it is run with, since all it does is execute the shell command `cython`.

**Comment by rgommers** [comment]
Thanks @JozsefKutas and @eli-schwartz 

> > We shouldn't be relying on shebang lines at all, let's fix this to make sure it uses the correct Python interpreter that was already detected by Meson.
> 
> I am not entirely sure what this is trying to say, but I think it's probably wrong. This script uses pure barebones stdlib python, and does not care what python interpreter it is run with, since all it does is execute the shell command `cython`.

As you pointed out on https://github.com/mesonbuild/meson/issues/3911, `python3` is not supported by BSDs, and PEP 394 explains the details. That PEP states that it doesn't cover Windows, and also: _"When reinvoking the interpreter from a Python script, querying sys.executable to avoid hardcoded assumptions regarding the interpreter location remains the preferred approach."_ While a `meson.build` file is not a Python script, the same principle should apply. So what I mean is that finding the native Python interpreter once and passing that along is preferred, and more robust than relying on a shebang line. 

I wanted to do something like:
```meson
py_native = find_program('python3', native: true)

cython_gen = generator([py_native, '_build_utils/cythoner.py'], ...)
```
I just can't find a way to do this, because `generator` accepts only a single executable.

**Comment by eli-schwartz** [comment]
> As you pointed out on [mesonbuild/meson#3911](https://github.com/mesonbuild/meson/issues/3911), `python3` is not supported by BSDs, and PEP 394 explains the details.

No, the person that opened that Meson issue pointed that out... and I objected and pointed out that that is actually incorrect and BSDs *do* support `python3`.

PEP 394 requires them to do so, because they are Unix systems. However, the BSDs do this as an optional addon, which violates PEP 394's requirement for Unix systems.

> That PEP states that it doesn't cover Windows

Which is in large part the reason Meson reinterprets this.

> and also: _"When reinvoking the interpreter from a Python script, querying sys.executable to avoid hardcoded assumptions regarding the interpreter location remains the preferred approach."_ While a `meson.build` file is not a Python script, the same principle should apply.

TBH, independent of anything else, `meson.build` is a bad comparison, because Meson is *not* a python script, *and* it detects potentially multiple editions of python3, and runs some things (the python module) with one of them, and some things (command scripts) with another.

> more robust than relying on a shebang line

But in this case the shebang line is just there as a hint to Meson to tell Meson to reinvoke the script using *its* interpreter, even if that is different from the python module one. :D

**Comment by rgommers** [comment]
> But in this case the shebang line is just there as a hint to Meson to tell Meson to reinvoke the script using _its_ interpreter,

Ah okay, if that's the case then it's equivalent. Except it sounded like it may depend on whether we mark the script as executable or not. Which is fine now that we know, it should work I guess - but it's a little obscure.

Also we get configure output like:
```
Program _build_utils/cythoner.py found: YES (/Users/rgommers/mambaforge/envs/scipy-dev/bin/python3.9 /Users/rgommers/code/scipy/scipy/_build_utils/cythoner.py)
```
which is a little weird (I know it's found, it's in my source tree - and it's not a "program").

**Comment by eli-schwartz** [comment]
> Ah okay, if that's the case then it's equivalent. Except it sounded like it may depend on whether we mark the script as executable or not. Which is fine now that we know, it should work I guess - but it's a little obscure.

Basically, Meson "knows" it's supposed to be a runnable program because you said it should be usable via find_program(). But it cannot be run directly -- this is often, but not exclusively, the case on Windows. So Meson attempts to figure that out for you, and in the process it does what it does for `find_program('python3')` as well -- it handles a `python3` executable for you, gratis. This is mostly a convenience to Windows users, where python may not be installed, or may not be in PATH, but since Meson knows it has to have one (and ships with one in the .MSI installer) it can be sneakily helpful and just make that magically work as a last resort. If worst comes to worst, that will end up being `meson.exe runpython`.

If the script is executable, it is in theory supposed to be able to be executed directly -- and this too usually works, if you use `#!/usr/bin/env python3` as the PEP suggests.

> which is a little weird (I know it's found, it's in my source tree - and it's not a "program").

ISTR it was suggested somewhere, somehow, that find_program shouldn't bother logging when it converts a string into a found program object, if that string is pointing into the source tree.

(OTOH it does tell you what interpreter is used by the shebang detector?)

**Comment by rgommers** [comment]
> (OTOH it does tell you what interpreter is used by the shebang detector?)

Ah yes, that is potentially useful.

> [...] This is mostly a convenience to Windows users, where python may not be installed, or may not be in PATH, but since Meson knows it has to have one (and ships with one in the .MSI installer) it can be sneakily helpful and just make that magically work as a last resort.

This is a convincing argument. Okay, let's leave it all as is then. Thanks for the context @eli-schwartz

**Comment by rgommers** [comment]
@JozsefKutas commented on the related issue that the fix for him was related to line endings: 

_I ran into a similar issue when I first tried building scipy using WSL. I think that if you clone in Windows, git may alter line endings depending on the value of the `core.autocrlf` option in your git config. This changes the `python3` in the shebang line of `cythoner.py` to `python3\r`, which will break the build process. You should be able to avoid this by cloning in WSL._

_There's more explanation in [this blog post](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/)._

That is consistent with the newer report in gh-17338, where the issue was:
```
/usr/bin/env: ‘python3\r’: No such file or directory
```

Cloning outside of WSL and then running in WSL should be possible, so I'd consider this a bug. We do have `* text=auto` in `.gitattributes`, which seems like the right thing here. It seems to me like the interpretation of the shebang line must account for this possibility. @eli-schwartz would you agree?

**Comment by scottshambaugh** [comment]
Thank you @rgommers! After changing my config with `git config --global core.autocrlf input` and re-pulling the repository in WSL, I am no longer seeing this error. I think that until this bug is fixed I may run into issues if I try to mix development with the windows side, but at the moment I'm fully in WSL for dev work so this shouldn't be a problem.

**Comment by eli-schwartz** [comment]
> Cloning outside of WSL and then running in WSL should be possible, so I'd consider this a bug. We do have `* text=auto` in `.gitattributes`, which seems like the right thing here. It seems to me like the interpretation of the shebang line must account for this possibility. @eli-schwartz would you agree?

I am personally inclined to think that CRLF should be excluded from ever happening anywhere :D using proper line endings works even on Windows unless you're using, what, Notepad to edit them?

**Comment by h-vetinari** [comment]
What's the status of this issue? It was milestoned for a release long ago, I've removed that now.

**Comment by JozsefKutas** [comment]
The issue seems to be fixed, so I'll close it. I ran a search for a other shebang lines in the scipy repo and all of them have been changed to `#!/usr/bin/env python` or `#!/usr/bin/env python3`, which both work fine.
