### ISSUE TITLE
ENH: PPC64le Wheels

### ISSUE THREAD

**Issue by ax3l** [scipy/scipy#17054]
### Is your feature request related to a problem? Please describe.

On many leading supercomputers in the US, PowerPC is used. For example, Summit at OLCF and Sierra/Lassen at LLNL.

Installing scipy on those with pip currently needs to build from source.

### Describe the solution you'd like.

I saw you already publish arm64 wheels for Linux on pypi. Could you potentially also publish them for ppc64le?

In my projects, I use the free TravisCI PowerPC runners (no limit/credits) for these deployments via cibuildwheel.

### Describe alternatives you've considered.

We currently build ourselves from source, but SciPy builds are so long that they often get killed by runtime limits on shared/login nodes: https://github.com/ECP-WarpX/WarpX/issues/3415

### Additional context (e.g. screenshots, GIFs)

Re. downstream issue: https://github.com/ECP-WarpX/WarpX/issues/3415

**Comment by andyfaff** [comment]
There are a few issues with providing ppc64 wheels. Firstly, the providers of ppc64 CI infrastructure are limited. Whilst Travis does offer CI for that arch we would burn through any available credits quickly (leading to repeated emails to the provider to ask for more). We then need someone who is able to fix/maintain that arch. As archs become less popular the barrier becomes higher. I think the policy at the moment is to fix any obvious bugs, but not much more.

Would it be possible to have a centralised wheel repo in which you could store built wheels for future use? 

Are you sure that the build is being killed? It looks to me as if there may be an issue with the meson build at the end of the log file from the linked issue. @rgommers @eli-schwartz

**Comment by eli-schwartz** [comment]
> It looks to me as if there may be an issue with the meson build at the end of the log file from the linked issue.

It's a bit confusing, because the PEP 517 wheel builder:
- successfully configures meson
- starts running ninja to compile everything
- errors out with `g++: fatal error: Killed signal terminated program cc1plus`
- returns to the build backend, mesonpy, and emits an error about a missing PEP517 hook for `prepare_metadata_for_build_wheel`


The final error is confusing and weird with it, but it should be fixed in the next release of https://github.com/pypa/pep517/commit/91895aa6d4471bf57af7110061f1f79ce80e9b77

However, the original cause of the error flow is, indeed, that g++ having its worker process killed off by a signal.

**Comment by eli-schwartz** [comment]
> In my projects, I use the free TravisCI PowerPC runners (no limit/credits) for these deployments via cibuildwheel.

Is this a thing specific to PowerPC? Because I'm pretty sure these days there is indeed a credit limit for ordinary TravisCI runners. Lots of projects moved off of Travis for this reason, because it was no longer operating as an effective source of generously donated CI compute for FOSS.

**Comment by andyfaff** [comment]
I forgot to say that conda-forge has scipy binaries available, if you're allowed to use conda in your environment.

**Comment by tylerjereddy** [comment]
One other thing worth mentioning here is that since the SciPy release manager (me) works at another US National Lab, if there is a genuine need to provide such binaries and maintain such binaries more broadly for i.e., our supercomputers, perhaps Axel could send a polite email to the stakeholders at LANL just saying that it would be great if I could help with this effort. 

I'm supposed to get ~20 % time from LANL in the new financial year (~2 weeks away now?), but it may still help to have an explicit request from another National Lab to get things rolling right from the start.

As far as the credit situation with Travis, I had the same concern, but apparently they have a special "partner queue solution" for ppc64le that burns no credits and requires no credits at the start either: https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution

**Comment by eli-schwartz** [comment]
Aha. So it is indeed specific to PowerPC (or rather, separate from x86).

TIL.

**Comment by andyfaff** [comment]
It's also made more complicated because there are no available numpy wheels for this target, requiring extra build time. If ppc64 wheels are going to be a thing one would have to have numpy available first.

**Comment by rgommers** [comment]
> On many leading supercomputers in the US, PowerPC is used. For example, Summit at OLCF and Sierra/Lassen at LLNL.
> 
> Installing scipy on those with pip currently needs to build from source.

@ax3l serious question: if you are on a supercomputer, why don't you use something like Spack? Or otherwise conda-forge, which also supports ppc64le. Both are better than PyPI/wheels in so many ways, even if ppc64le wheels would be available.

This also reminded me of the [reducing effort spent on wheel builds?](https://mail.python.org/archives/list/numpy-discussion@python.org/message/46HT2SYDHBNLOC6N5RTXI7CN32YWIJWR/) thread. There's a long list of possible platforms we could build wheels for. It roughly looks like this to me:

For these platforms we have 1st class support and it's basically a given at this point that we should produce wheels:
- Windows: 
  - x86-64, 64-bit Python
- macOS:
  - x86-64
  - arm64
- Linux:
  - x86-64, manylinux (64-bit)
  - aarch64 manylinux

Then there are a lot of other platforms that users may want wheels for. Here is a list, roughly ordered by what I think is our priority for them (most likely to support first):
- Musl Linux: 64-bit x86-64 and aarch64
- 32-bit Python for Windows
- aarch64 Windows
- ppc64le Linux
- PyPy: x86-64 wheels for Linux, Windows and macOS
- s390x Linux
- 32-bit Python for Linux
- universal2 wheels for macOS
- AIX (no standard for that yet)

It's a long list - too long to feasibly support all of those, there's just too much overhead in dealing with CI, hosting of wheels, etc. I think Musl Linux is the only one that's close right now - it can be supported with limited effort within our current `cibuildwheel` on GitHub Actions right now. And we'll do 32-bit Python if the compiler toolchain issues get resolved. The rest is probably a bridge too far right now.

I will also note that 32-bit Python on Windows, ppc64le Linux and PyPy (partially) are supported by conda-forge.

**Comment by andyfaff** [comment]
This would make an excellent FAQ reply.

**Comment by ax3l** [comment]
> It looks to me as if there may be an issue with the meson build at the end of the log file from the linked issue.

No, SciPy builds well and at least the subset we use from it for 5years+ as no obvious bugs.
The error in the linked issue is a _timeout_ - SciPy builds so long that a watchdog on a shared system kills it. We can tell users to work around this by using exclusive compute nodes.

> Whilst Travis does offer CI for that arch we would burn through any available credits quickly (

PPC64le runs w/o credits, since IBM sponsors those. (see: `In my projects, I use the free TravisCI PowerPC runners (no limit/credits) for these deployments via cibuildwheel.`)

**Comment by ax3l** [comment]
> I forgot to say that conda-forge has scipy binaries available, if you're allowed to use conda in your environment.

That possible but cumbersome, since conda-forge will introduce its fully own compiler stack including own libc, lib(std)c++ et al. HPC systems provide specially tuned modules for vendor compilers, network libraries (e.g., MPI), math libraries etc. which one cannot combine with conda due to incompatibility of C++ Compilers and dependencies.

**Comment by ax3l** [comment]
> perhaps Axel could send a polite email to the stakeholders at LANL just saying that it would be great if I could help with this effort.

@tylerjereddy I will gladly do, thank you so much! I am mostly active and support [WarpX](https://warpx.readthedocs.io)/[BLAST](https://blast.lbl.gov/) users at OLCF, NERSC and LLNL right now - but we have a community at LANL as well. Can you recommend me a contact at LANL where this request would be best addressed to? :) (We can follow up on this thread by email as well if you like.)

**Comment by ax3l** [comment]
> It's also made more complicated because there are no available numpy wheels for this target, requiring extra build time. If ppc64 wheels are going to be a thing one would have to have numpy available first.

Oh no, dang.

> If you are on a supercomputer, why don't you use something like Spack?

Spack CI testing is relatively new, especially for the Python stack. I contribute a lot to it, but bootstrapping times w/o system binary cache support are very long for users so far (can be multiple hours to run a first Python script for realistic environments that we build). It simply was not stable or fast enough for me to rely on for anything else than my core C++ packages so far. I am optimistic this will change on the long term, if HPC centers provide things like Spack binary caches and [Spack Chains](https://spack.readthedocs.io/en/latest/chain.html). I give this input to centers periodically, have not seen it yet.

**Comment by rgommers** [comment]
> That possible but cumbersome, since conda-forge will introduce its fully own compiler stack including own libc, lib(std)c++ et al. HPC systems provide specially tuned modules for vendor compilers, system-tuned network libraries (e.g., MPI), math libraries etc. which one cannot combine with conda due to incompatibility of C++ Compilers and dependencies.

Conda-forge does not ship `libc`, it relies on the system one. It does indeed ship `lib(std)c++` though. But this argument would more or less equally apply to wheels (you get system `libstdc++`, but lose the choice of BLAS library in return).

> It simply was not stable or fast enough for me to rely on for anything else than my core C++ packages so far

Good to know. For the record, I am now a co-maintainer of SciPy and NumPy packages in Spack. And I'd personally much rather spend time on helping improve things there, rather than on more wheel build CI.

**Comment by ax3l** [comment]
> Conda-forge does not ship libc, it relies on the system one. It does indeed ship lib(std)c++ though.

Oh makes sense, thanks for clarifying.

> For the record, I am now a co-maintainer of SciPy and NumPy packages in Spack. And I'd personally much rather spend time on helping improve things there, rather than on more wheel build CI.

Awesome, that's totally something I prefer as well because ultimately I can get our whole Stack to build in a fully consistent and tuned manner. Then let me modernize a couple of our [HPC system instructions](https://warpx.readthedocs.io/en/latest/install/hpc.html#hpc-systems) to use Spack envs in the coming month and I'll open Spack issues if needed.
