### ISSUE TITLE
docs: unclear explanation of arguments in ks_2samp

### ISSUE THREAD

**Issue by bzip2** [scipy/scipy#17113]
In ks_2samp, how are data1 and data2 (the arguments) related to F(x) and G(x) in the explanations? Presumably, data1 is F(x) and data2 is G(x), but it would be useful if that were explicit.

**Comment by tupui** [comment]
Thank you for reporting @bzip2. Indeed we should clarify that when defining the parameters as it matters for the alternative. The note state, `x1 ~ F and x2 ~ G`. But it's implicit and also does not corresponds to `data1, data2`.

Would you like to make a PR?

**Comment by bzip2** [comment]
Hi.

Thanks for the reply. I'm going to close this ticket and include the contents in a bug report for ``ranksums`` and ``mannwhitneyu``. They reverse the null and alternative distributions in one-sided tests, which is the opposite of what the documentation for each of those functions claims.

**Comment by bzip2** [comment]
@mdhaber Please read this single continuous excerpt of the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html#scipy.stats.mannwhitneyu) of ``[mannwhitneyu]``. Briefly:

1. F(u) is ... underlying x
2. G(u) underlies y
3. ‘less’: the distribution underlying x is stochastically less than the distribution underlying y, i.e. F(u) > G(u) for all u.

Do you see the error? F < G, i.e., F > G.

Both ``ranksums`` and ``mannwhitneyu`` erroneously reverse the null and alternative. They produce the opposite of ``ks_2samp``. I'll post a brief example with my bug report. I suspect this happened because all three are poorly explained, in creatively different way. Why make everyone guess what "less" means? 

> ![image](https://user-images.githubusercontent.com/12174276/193685368-716627a2-eaaf-45a9-a7bf-f865b227a3f4.png)

**Comment by mdhaber** [comment]
> I suspect this happened because all three are poorly explained, in creatively different way

I'd suggest keeping the comments constructive if you want helpful feedback. At least two of them were carefully written to walk the line between mathematical correctness and understandability. It is tricky to satisfy everyone on the stats spectrum with the same descriptions. Perhaps the descriptions have failed at both, but we need to identify how to improve them rather than labeling them as "poorly explained".

> F < G, i.e., F > G.

i.e. means "that is", so as I sentence, I'm reading "$F < G$, that is, $F > G$". This seems like a contradiction, and I don't understand. Do you mean that "$F < G$ should be $F > G$" (or vice versa)? If so, that would be incorrect; the sign of the inequality is consistent with the preceding statement. I explained why above:

> This is accurate. It is a statement about the **CDFs**, not the **random variables**.

Let's restrict our attention to `mannwhitenyu` and `ks_2samp`, as I am not as familiar with the documentation of `ranksums`. It hasn't received as much attention as the others. Here is some code to explain:

---

```python3
# From the documentation of `mannwhitenyu`, the alternative hypothesis is:
# > ‘less’: the distribution underlying x is stochastically less 
# > than the distribution underlying y, i.e. F(u) > G(u) for all u.

import numpy as np
from scipy import stats

# Random variable X is "stochastically less" than Y 
X = stats.norm(loc = -1)
Y = stats.norm(loc = 0)

# CDFs are labeled F and G
F = X.cdf
G = Y.cdf

# At any given point, F(u) is *greater* than G(u)
u = np.linspace(-1, 1)
print(np.all(F(u) > G(u)))

# Generate Random Samples
x = X.rvs(size=100)
y = Y.rvs(size=100)

# Test with "alternative='less'". We expect small p-values
print(stats.mannwhitneyu(x, y, alternative='less').pvalue)  # 6.04289049848858e-12, for example

```

The part of the `mannwhitneyu` documentation that attempts to elucidate this is:
![image](https://user-images.githubusercontent.com/6570539/193699079-71e35c5b-7062-41b6-b9ce-63676f35919c.png)

---

For `ks_2samp`, yes, the meaning of the alternatives is reversed because "less" and "greater" are about the CDFs, not the random variables. We might prefer that they be consistent, but neither is wrong or right, and both decisions predate my time working on `stats`. As much as I try to unify the `stats` experience and sometimes break BC to do so, this would be a bit too fundamental to reverse before SciPy 2.0, IMO. 

```python3
# From the documentation of `ks_2samp`, the alternative hypothesis is:
# > less: The null hypothesis is that F(x) >= G(x) for all x; 
# the alternative is that F(x) < G(x) for at least one x.)
# Our random variables are consistent with the null hypothesis, 
# not the alternative, so we expect a large p-value
print(stats.ks_2samp(x, y, alternative='less').pvalue)  # 0.9900990099009901, for example
```

The part of the `ks_2samp` documentation that attempts to elucidate this is:
![image](https://user-images.githubusercontent.com/6570539/193699005-a1f1de98-ae84-4830-b89d-9de896715b3c.png)
