### ISSUE TITLE
BUG: logm sometimes raises ZeroDivisionError for matrices with zero norm

### ISSUE THREAD

**Issue by MichielCottaar** [scipy/scipy#17136]
### Describe your issue.

Running `scipy.linalg.logm` on a matrix with zero norm leads to inconsistent behaviour. For example, running
```python
logm(np.zeros((2, 2), dtype=int))
```
leads to the following result:
```
array([[-46.05170186,   0.        ],
       [  0.        , -46.05170186]])
```
with an appropriate warning  displayed ("logm result may be inaccurate, approximate err = inf"). 

However, the same matrix with floats leads to the ZeroDivisionError shown below. Note that this error actually occurs after the `logm` is calculated. The actual algorithm is consistent irrespective of data type. It happens while estimating the error of the algorithm (`errtest`).

I would suggest that the behaviour for the integer matrix is better. It would be easy to get that behaviour consistently across all zero-norm matrices: namely to check that `norm(A,1)` is zero before computing `errtest`. If `norm(A,1)` is zero `errtest` can be set to infinity (and the warning message will normally be displayed).

On a closely related note: I think returning an matrix of `NaN`s is a better behaviour for these zero-norm matrices (i.e., if  `errtest` is infinite) rather than the random numbers returned now.

### Reproducing Code Example

```python
from scipy.linalg import logm
import numpy as np
logm(np.zeros((2, 2), dtype=int))
logm(np.zeros((2, 2), dtype=float))
```

### Error message

```shell
ZeroDivisionError                         Traceback (most recent call last)
Cell In [7], line 1
----> 1 logm(np.zeros((2, 2), dtype=float))

File <python-dir>/python3.10/site-packages/scipy/linalg/_matfuncs.py:204, in logm(A, disp)
    202 errtol = 1000*eps
    203 #TODO use a better error approximation
--> 204 errest = norm(expm(F)-A,1) / norm(A,1)
    205 if disp:
    206     if not isfinite(errest) or errest >= errtol:

ZeroDivisionError: float division by zero
```

### SciPy/NumPy/Python version information

1.9.1 1.23.3 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

**Comment by MatteoRaso** [comment]
I did some playing around with the code, and apparently python gives a runtime warning when dtype = int and a ZeroDivisionError if dtype = float, even though the values for norm(expm(F)-A,1) and norm(A,1) are the exact same. Very weird.

**Comment by scidam** [comment]
The problem is due to different behavior of `np.linalg.norm` and `scipy.linalg.norm`.  To reproduce the problem just consider the following (if we use `norm` from scipy package): 
```python
from scipy.linalg import norm
>>> 0/norm(np.zeros((2,2), dtype=int), 1)
nan
>>> 0/norm(np.zeros((2,2), dtype=float), 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: float division by zero
```
and, if we use `norm` from `numpy` directly, we get the following:
```python
>>> 0/np.linalg.norm(np.zeros((2,2), dtype=int), 1)
nan
>>> 0/np.linalg.norm(np.zeros((2,2), dtype=float), 1)
nan
```

SciPy uses `blas` or `lapack` to compute matrix [norm ](https://github.com/scidam/scipy/blob/5be8bc48fe959e8f12d99495d0323f16c7d4ea4d/scipy/linalg/_misc.py#L17) and this yields to different types of results:

```python
>>> type(norm(np.zeros((2,2), dtype=float), 1))
<class 'float'>
>>> type(norm(np.zeros((2,2), dtype=int), 1))
<class 'numpy.float64'>
```

Actually, to handle this edge case I would add an extra check for non-zero norm (somewhere in [these lines](https://github.com/scidam/scipy/blob/5be8bc48fe959e8f12d99495d0323f16c7d4ea4d/scipy/linalg/_matfuncs.py#L204) of the code):
```python
if  np.allclose(norm(A, 1), 0):
    errest = np.inf
    F = np.empty_like(A)
    F.fill(np.nan)
else:
    errest = norm(expm(F) - A, 1) / norm(A, 1)
```

Also, function [_logm](https://github.com/scidam/scipy/blob/5be8bc48fe959e8f12d99495d0323f16c7d4ea4d/scipy/linalg/_matfuncs_inv_ssq.py#L857) uses check for matrix squareness.  The same check is performed in [this ](https://github.com/scidam/scipy/blob/5be8bc48fe959e8f12d99495d0323f16c7d4ea4d/scipy/linalg/_matfuncs.py#L197) line of code. Actually, we have a double check for matrix squareness in `logm` function.
