### ISSUE TITLE
BUG: CublicSpline gives redundant but nearly identical roots

### ISSUE THREAD

**Issue by syrte** [scipy/scipy#17261]
### Describe your issue.

In the following example with CubicSpline y=cos(x), I would naively expect a single root x=1 for cos(x)=1. However, it returns three nearly identical roots instead.
In another rare case where the curve is monotonic (I will provide the example when I get access to my data later), I also get two close roots, which only differ by 1e-16.

Is this expected or not? If yes, any good idea to search and remove such redundancy roots? Thanks.

### Reproducing Code Example

```python
import numpy as np
from scipy.interpolate import CubicSpline

x = np.linspace(-1, 1, 101)
y = cos(x)
f = CubicSpline(x, y)
rt = f.solve(1, extrapolate=False)
# array([-1.79965237e-07,  0.00000000e+00,  1.56105529e-16])
f(rt) - 1
# array([-1.62092562e-14,  0.00000000e+00,  0.00000000e+00])
```

### Error message

```shell
--
```

### SciPy/NumPy/Python version information

1.7.3 1.20.3 sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)

**Comment by ev-br** [comment]
While unfortunate, this is not entirely unexpected, especially given that you're asking it to find an extremum, with a zero derivative at a true root.

As `f(rt) -1` shows, all three values are technically legit. I don't believe there is a way to fix this in general. Some manual postprocessing may be required one way or another. Since the criteria for what is close and what is not are very much problem-dependent, and that once you have a criterion, filtering likely duplicates is not difficult, this kind of redundancy removal should live in the user code. 

All in all, this is a defect, yes; I'm however going to label it as technically infeasible to fix on the library level.

**Comment by syrte** [comment]
Thanks for the explanation!
