### ISSUE TITLE
BUG: winsorize nan_policy unexpected behavior

### ISSUE THREAD

**Issue by alexscott-ff** [scipy/scipy#17288]
### Describe your issue.

I would expect the two calls below to return the same result:

```python
import numpy as np
from scipy.stats.mstats import winsorize

# 20 total entries, but one is NaN, so with "omit", it should be 19.
winsorize(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, np.nan, 20]), limits=[0.1, 0.1], nan_policy="omit")
# 19 total entries (the number 19 is left out)
winsorize(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20]), limits=[0.1, 0.1], nan_policy="omit")
```

The first returns:
```sh
masked_array(data=[ 3.,  3.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
                   12., 13., 14., 15., 16., 17., 18., nan, 18.],
             mask=False,
       fill_value=1e+20)
```

The second:
```sh
masked_array(data=[ 2,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
                   15, 16, 17, 18, 18],
             mask=False,
       fill_value=999999)
```

The difference in float vs int is interesting as well.

I would expect the first call to instead produce:
```sh
masked_array(data=[ 2,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
                   15, 16, 17, 18, nan, 18],
             mask=False,
       fill_value=999999)
```

### Reproducing Code Example

```python
import numpy as np
from scipy.stats.mstats import winsorize

# 20 total entries, but one is NaN, so with "omit", it should be 19.
winsorize(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, np.nan, 20]), limits=[0.1, 0.1], nan_policy="omit")
# 19 total entries (the number 19 is left out)
winsorize(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20]), limits=[0.1, 0.1], nan_policy="omit")
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version information

1.9.3 1.23.4 sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)

**Comment by alexscott-ff** [comment]
@mdhaber thought maybe you'd know what's going on since you recently worked on fixing https://github.com/scipy/scipy/issues/16211 which I believe was just released

**Comment by alexscott-ff** [comment]
Here is a somewhat related example that is unintuitive (but maybe my interpretation of what this *should* do is wrong)..

```python
winsorize(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, np.nan, 20]), limits=[0.1, 0.1], nan_policy="propagate")
```
Returns:
```sh
masked_array(data=[ 2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
                   12., 13., 14., 15., 16., 17., 20., 20.],
             mask=False,
       fill_value=1e+20)
```

What does `"propagate"` actually mean? Is it referring to the `nan` values (propagate them into the calculation or final array) or to some calculated value that will be used to replace the `nan`? 

The docs give:

> ‘propagate’: allows nan values and may overwrite or propagate them

Which is pretty ambiguous :)

**Comment by mdhaber** [comment]
I'd have to think more carefully about what should happen with `'propagate'`, but my guess is that since we don't know what position a NaN would lie at in the ordered data, there is some uncertainty about the value to which outliers should be clipped and which are outliers. So I'd think that outliers would be clipped to NaN and we would have to treat as outliers all values that _could. by outliers, depending on the where the NaNs could be. Some values that are toward the center would probably not change. But again, I'd need to think through more carefully.

In practice many `'propagate'` `nan_policy` implementations just go through the calculation without paying special attention to NaNs, assuming that they will appear in the output where they should. This is usually correct, but not always. I haven't looked through the code carefully enough to see whether that's going on here, but the only references to "propagate" in [_mstats_basic.py](https://github.com/scipy/scipy/blob/v1.9.3/scipy/stats/_mstats_basic.py) are in the documentation, so any special handling is happening somewhere else (if at all) 

Issues with nanpolicy are not uncommon. I've added this issue to the list in gh-14651, and we'll track this bug there. We are making our way through it carefully. Even though we have a decorator now that tends to take care of most of the work, we don't want to apply it blindly and then realize that our fix isn't correct. So it takes some time. Thanks for your patience.

(Closing with "Close as not planned" as this is definitely _not_ completed. This is planned, but it is already tracked elsewhere.)

**Comment by alexscott-ff** [comment]
Gotchya, thanks @mdhaber ; will keep an eye on this.

I played around briefly with the code, and at least for the first issue (with `"omit"`), doing something like this seemed at least more right..

```python
# Move this up and decrement n based on nan count since we want to omit them from any calculations.
if contains_nan and nan_policy == 'omit':
    n = n - nan_count

if low_limit:
    if low_include:
        lowidx = int(low_limit * n)
    else:
        lowidx = np.round(low_limit * n).astype(int)
    a[idx[:lowidx]] = a[idx[lowidx]]
# Upper logic seems to be fine
# ...
``
