### ISSUE TITLE
BUG: scipy.linalg.eig is missing documentation on the orthogonality of eigenvectors

### ISSUE THREAD

**Issue by AlexiaNomena** [scipy/scipy#17300]
### Describe your issue.

Hello,

the documentation mentions that scipy.linalg.eig solves generalised eigenvalue problem of a square matrix.
But it does not necessarily produce orthogonal eigenvectors, e.g. symmetric real matrix I attached here ([test_array.txt](https://github.com/AlexiaNomena/Tests_Files/tree/main/scipy_linalg))

I would like to suggest to at least change the documentation to "non-symmetric" matrices instead of "ordinary or generalised

EDIT: The issue is rather on the orthogonality of the eigenvectors. The documentation should mention that `eigh` always computes orthogonal eigenvectors (if that is True) while `eig` does not necessarily do so

### Reproducing Code Example

```python
import pdb
import numpy as np
import scipy.linalg as splinalg

M = np.loadtxt("test_array.txt")

print("M is symmetric:", np.all(np.isclose(M, M.T))) ### test symmetry of M
M[np.isclose(M, np.zeros(M.shape))] = 0 # remove numerical zeros

E, U = splinalg.eigh(M) ### eigendecomposition for symmetric matrices
sort = False


Ec, Uc = splinalg.eig(M) ### eigendecomposition for general matrices
sortc = False   

if sort:
	E = np.real(E) # remove tiny imaginary parts (symmetric matrices have real eigenvalues)
	sort = np.argsort(E)[::-1] # descending order
	E = E[sort]
	U = U[:, sort]
	print("All eigenvalues are equal:", np.all(np.isclose(E, Ec))) # True
if sortc:
	Ec = np.real(E) # remove tiny imaginary parts (symmetric matrices have real eigenvalues)
	sortc = np.argsort(Ec)[::-1] # descending order
	Ec = Ec[sortc]
	Uc = Uc[:, sortc]
	print("All eigenvectors are equal:", np.all(np.isclose(U, Uc))) # False

print("eigh eigenvalues", E)

### Recovering M from Eigendecomposition ####
SS = np.sqrt(np.diag(E)) 
tX0 = np.real(U.dot(SS))
Gram = tX0.dot(tX0.T)
        
SSc = np.sqrt(np.diag(Ec)) 
tX0c = np.real(Uc.dot(SSc))
Gramc = tX0c.dot(tX0c.T)

### Test general decomposition ###
SSc2 = np.diag(Ec)
gMc = Uc.dot(SSc2.dot(splinalg.inv(Uc)))

print("Gram matrices are the same:", np.all(np.isclose(Gram,Gramc))) # False
print("sp.linalg.eigh recovers M:", np.all(np.isclose(Gram, M))) # True
print("sp.linalg.eig recovers M:", np.all(np.isclose(M, Gramc))) # False
print("sp.linalg.eig recovers M (general decomposition):", np.all(np.isclose(M, gMc))) # True

```

### Error message

```shell
M is symmetric: True
eigh eigenvalues [   0.           22.0865683    37.31990533   40.15032657   41.44211427
   42.22858225   42.9206473    43.55066949   43.96554338   44.45700434
   44.96375497   45.30847694   49.8142849    49.8142849    49.8142849
   49.8142849    49.8142849    49.8142849    49.8142849    49.8142849
   49.8142849    49.8142849    49.8142849    49.8142849    49.8142849
   49.8142849    49.8142849    49.8142849    49.8142849    49.8142849
   49.8142849    49.8142849    49.8142849    49.8142849    49.8142849
   49.8142849    49.8142849    49.8142849    49.8142849    49.8142849
   49.8142849    49.8142849    49.8142849    49.8142849    49.8142849
   49.8142849    49.8142849    49.8142849    49.8142849    49.8142849
   49.8142849    49.8142849    49.8142849    49.8142849    49.8142849
   49.8142849    49.8142849    49.8142849    49.8142849    49.8142849
   49.8142849    49.8142849    49.8142849    50.70736511   51.63337703
   53.10796584   53.67034273   53.82246955   54.85078408   55.65500791
   56.71016463   57.0178392    58.02958643   60.7358963    66.31964316
   77.75053236   80.70438303   84.68630203   94.02987113   96.31747861
  108.40075002  142.41016691 4181.29685039]
Gram matrices are the same: False
sp.linalg.eigh recovers M (iff orthogonal eigenvectors): True
sp.linalg.eig recovers M (iff orthogonal eigenvectors): False
sp.linalg.eig recovers M (general decomposition): True
```

### SciPy/NumPy/Python version information

1.7.3 1.21.5 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @AlexiaNomena thanks for reporting. Please don't share pickled or compressed files for security reasons. Most errors can be reproduced with small plain text data.

**Comment by WarrenWeckesser** [comment]
The issue can be reproduced with the matrix `M` created with

```
rng = np.random.default_rng(121263137472525314065)

d = np.diag([1, 2, 2])
v = special_ortho_group.rvs(len(d), random_state=rng)
M = v @ d @ splinalg.inv(v)
```

In fact, any symmetric matrix with repeated eigenvalues will likely reproduce the result.  Because `eig` does not "know" that the matrix is symmetric, it cannot gaurantee that the two eigenvectors associated with the repeated eigenvalue 2 will be orthogonal. In general, they won't be orthogonal.

@AlexiaNomena, can you modify your script to also print `E`?  I expect to see repeated values in there.

**Comment by ilayn** [comment]
Generalized problem means a matrix pair (A, B) is used so it is not relevant for this issue. Nonsymmetricity shouldn't matter as it is not typically a problem but for repeated eigenvalues you have to make sure the sorting is done carefully in case it hits a Jordan block due to precision issues. So typically you shouldn't sort them blindly or remove imaginary parts. If it is working without the sorting or the imaginary part removal then this is not an issue.

**Comment by AlexiaNomena** [comment]
> Hi @AlexiaNomena thanks for reporting. Please don't share pickled or compressed files for security reasons. Most errors can be reproduced with small plain text data.

@tupui Alright, thanks for the info, I changed it to a txt file

@WarrenWeckesser Thanks, there are indeed repeated eigenvalues (now printed). But I don't understand why you say that the bug is in my test script. My conclusion from this (and also from your symmetric matrix example) is that one should not use `eig` for symmetric matrices.

@ilayn Thanks, actually I forgot to mention that M is positive semi-definite and this is why I removed the imaginary part. Now, I run this without sorting or removing imaginary part, but it is still not working for `eig`. It's just that I interpreted  the term "generalized" as "for all" and this why I suggested to replace it, my simulation problem is already solved by using ` eigh`.

**Comment by WarrenWeckesser** [comment]
> My conclusion from this (and also from your symmetric matrix example) is that one should not use eig for symmetric matrices.

I think this is a question of expectations.  You might be expecting too much from `eig`.

If you know that your matrix is symmetric, and you expect the matrix of eigenvectors to be orthogonal, then you should use `eigh` instead of `eig`.  That is true.

Your comments, however, seem to suggest that you think something is *wrong* with `eig`.  In fact, the result returned by `eig` is not incorrect.  If you use `eig` instead of `eigh`, the eigenvectors associated with repeated eigenvalues will not (in general) be orthogonal (and therefore the matrix of eigenvectors will not be an orthogonal matrix), but they will still be valid eigenvectors.  Check the result with the eigenvalue equation, and you'll see that (other than normal numerical noise) the returned values do, in fact, solve the equation.  (For a single eigenvalue λᵢ, the equation is Avᵢ = λᵢvᵢ.  When written for the entire decomposition, the equation is AV = V diag({λᵢ}) where V is the matrix of eigenvectors.  Using the notation from the script, that would be `M @ Uc = Uc @ np.diag(Ec)`.)  For example,

```
In [72]: from scipy.linalg import eig

In [73]: M = np.loadtxt('test_array.txt')

In [74]: Ec, Uc = eig(M)

In [75]: np.allclose(M @ Uc, Uc @ np.diag(Ec))
Out[75]: True
```
So `eig` has returned a correct result. The result doesn't have the additional structure that you would get if you used `eigh`, but it is not wrong.

**Comment by AlexiaNomena** [comment]
> So `eig` has returned a correct result. The result doesn't have the additional structure that you would get if you used `eigh`, but it is not wrong.

@WarrenWeckesser thanks, you are right, I guess I didn't understand that orthogonality of eigenvectors was my real problem here. But still, it would be nice to have this information on the documentation, that `eigh` always computes orthogonal eigenvectors (if that is True) while `eig` does not necessarily do so.
