### ISSUE TITLE
DOC/QUERY: Gamma CDF

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#17339]
Looking into writing examples for some statistical functions in `special`, I noticed that there are essentially two functions for computing the CDF of a gamma distribution: [gdtr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gdtr.html) and [gammainc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gammainc.html). Both use a slightly different parametrisation. Interestingly, calling them directly is a lot faster than going via `stats.gamma.cdf`, especially if they only compute one value. See the script below.

My question is now: are there differences for the end user besides the parametrization between `gdtr` and `gammainc` that should be noted in the docs? If not, are there reasons to keep two functions for the same special mathematical function?

```python
from scipy.special import gdtr, gammainc
from scipy.stats import gamma
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 200, 500)
a, b = 0.5, 50
gamma_dist = gamma(b, scale=1/a)
print("timings array 1000 values")
%timeit -n 100 gamma_cdf = gamma_dist.cdf(x)
%timeit -n 100 cdf_gdtr = gdtr(a, b, x)
%timeit -n 100 cdf_gammainc = gammainc(b, a * x)
cdf_gammainc = gammainc(b, a * x)
gamma_cdf = gamma_dist.cdf(x)
cdf_gdtr = gdtr(a, b, x)
np.testing.assert_allclose(cdf_gammainc, cdf_gdtr)
np.testing.assert_allclose(gamma_cdf, cdf_gdtr)

print("timings 1 value")
testval = 100.
%timeit -n 1000 val = gamma_dist.cdf(testval)
%timeit -n 1000 val = gdtr(a, b, testval)
%timeit -n 1000 val = gammainc(b, a * testval)
plt.plot(x, gamma_cdf, label="stats.gamma(b, scale=1/a).cdf(x)", ls="dotted")
plt.plot(x, cdf_gammainc, label="special.gammainc(b, a*x)", ls="dashed")
plt.plot(x, cdf_gdtr, label="special.gdtr(a, b, x)", ls="dashdot")
plt.legend(frameon=False, loc="upper left")
plt.title("3 ways to compute the gamma cumulative distribution function")
plt.show()
```

Output on my machine:
```
timings array 1000 values
221 µs ± 32.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
106 µs ± 3.22 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
115 µs ± 5.45 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
timings 1 value
114 µs ± 6.38 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
2.44 µs ± 206 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
2.03 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

![image](https://user-images.githubusercontent.com/40656107/199913915-26d56d95-61e6-4317-a5c2-8f5376b9ad43.png)

**Comment by rkern** [comment]
`gammainc` implements the regularized incomplete Gamma function, which is a mathematical construct that exists independently of the Gamma probability distribution. The Gamma distribution just so happens to use that as its CDF. The incomplete Gamma function and the Gamma distribution CDF have different conventional parameterizations. `gdtr` uses `gammainc` under the covers. We inherited both of these and their friends from the Cephes library that implements a lot of the functions in `scipy.special`. They both have related functions (e.g. `gammaincc`, `gdtrix`, etc.), so both are worth keeping to have consistency with their family of functions and their conventional parameterizations (not to mention backwards compatibility).

They are both faster than `scipy.stats.gamma.cdf()` because the probability distribution framework has a fair bit of Python overhead to process the arguments while the `scipy.special` functions are straight C-implemented ufuncs.
