### ISSUE TITLE
BUG: Very minor issue ,  missing that line : 

### ISSUE THREAD

**Issue by Brumi-2021** [scipy/scipy#17347]
### Describe your issue.

Very minor issue reporting  ,

In the example of that scipy.signal.iirfilter
(https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.iirfilter.htm)

In the top import part , is just missing that line :

==>   "**import numpy as np**"

![image](https://user-images.githubusercontent.com/86470699/200080300-704a29ab-d51d-4d48-9bbf-a92f77d77263.png)
l
(Congratulations for that excellent  Python  filter development framework tool . Thanks for keeping updating it  !!!)

### Reproducing Code Example

```python
from scipy import signal
import matplotlib.pyplot as plt

b, a = signal.iirfilter(17, [2*np.pi*50, 2*np.pi*200], rs=60,
                        btype='band', analog=True, ftype='cheby2')
w, h = signal.freqs(b, a, 1000)
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.semilogx(w / (2*np.pi), 20 * np.log10(np.maximum(abs(h), 1e-5)))
ax.set_title('Chebyshev Type II bandpass frequency response')
ax.set_xlabel('Frequency [Hz]')
ax.set_ylabel('Amplitude [dB]')
ax.axis((10, 1000, -100, 10))
ax.grid(which='both', axis='both')
plt.show()
------------------

And in the top it should be : 

from scipy import signal
import numpy as np
import matplotlib.pyplot as plt
```

### Error message

```shell
Otherwise, we are getting that error  , when we try to execute and test the example.

"NameError                                 Traceback (most recent call last)
Cell In [2], line 1
----> 1 b, a = signal.iirfilter(17, [2*np.pi*50, 2*np.pi*200], rs=60,
      2                         btype='band', analog=True, ftype='cheby2')
      3 w, h = signal.freqs(b, a, 1000)
      4 fig = plt.figure()
NameError: name 'np' is not defined"
```

### SciPy/NumPy/Python version information

1.9.2 1.23.3 sys.version_info(major=3, minor=10, micro=8, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the issue, @Brumi-2021.  Earlier this year we adopted the policy of including `import numpy as np` in the docstrings; see https://github.com/scipy/scipy/issues/13049 for some of the details.   The docstring for `iirfilter` has already been fixed in the main development branch, and can be seen at https://scipy.github.io/devdocs/reference/generated/scipy.signal.iirfilter.html.  The few remaining docstring that are missing the import are shown in https://github.com/scipy/scipy/issues/16759 (assuming the script that searches for the missing imports hasn't missed some cases).

**Comment by Brumi-2021** [comment]
Thanks for so quick answering and clarify it .
Well I am new member, just learning about FIR / IIR  filter design in an embeded hardware, that is why i am reading your reference guide,  copying the examples into Jupyter qtconsole and trying to learn and practice from your good  examples !   Thanks .
