### ISSUE TITLE
No scipy-1.9.1-cp310-cp310-win32.whl found on PyPi

### ISSUE THREAD

**Issue by Olgidos** [scipy/scipy#17424]
### Is your feature request related to a problem? Please describe.

I need a 32 bit version for windows. And non is available on PyPi.

**Comment by andyfaff** [comment]
Sorry, no 32 bit wheels are available on windows, due to an incompatibility of 32 bit Fortran compilers with the new meson build system.  At the moment there is no real movement towards changing this situation, there's just not that much demand. Can you install an older wheel? Why is it necessary to install a 32 bit wheel?

**Comment by Olgidos** [comment]
Thanks for the answer, I am working with some legacy systems, which require python 32 bit. And we are currently using v3.10.. Maybe I can downgrade to 3.9.
