### ISSUE TITLE
BUG: Loading of scipy 1.8.1 fails after strip with ELF load command address/offset not properly aligned

### ISSUE THREAD

**Issue by dimidloc** [scipy/scipy#17438]
### Describe your issue.

After `strip`ing the scipy shared object, it no longer loads.
Similar to https://github.com/scipy/scipy/issues/12975 

### Reproducing Code Example

```python
mkvirtualenv -p python3.8 rasa
workon rasa
pip install rasa
python -c 'from rasa.core.agent import Agent, load_agent' # works
find /home/ubuntu/.virtualenvs/rasa/ -name '*.so' | xargs strip -s
python -c 'from rasa.core.agent import Agent, load_agent' 

ImportError: /home/ubuntu/.virtualenvs/rasa/lib/python3.8/site-packages/scipy/linalg/_fblas.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

### Error message

```shell
ImportError: /home/ubuntu/.virtualenvs/rasa/lib/python3.8/site-packages/scipy/linalg/_fblas.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

### SciPy/NumPy/Python version information

1.8.1

**Comment by andyfaff** [comment]
Having an import from `rasa` muddies the waters a little bit. in future examples you should just be able to do `python -c "import scipy.linalg._fblas"`.
- Would it be possible to explain why stripping the shared libraries is necessary? Is it something to do with https://github.com/scipy/scipy/pull/8451? I *believe*, but could be wrong, that the libraries are already stripped.
- Can you check for me if wheels from https://anaconda.org/scipy-wheels-nightly/scipy/files still have the same issue?

**Comment by andyfaff** [comment]
If I build a wheel built from `main` using Python3.10 on an `ubuntu:latest` image then the behaviour doesn't occur.

In contrast I can repeat the issue on the same image with scipy 1.9.3 and 1.8.1 wheels. However, the directory size changes very little when I strip. Is it actually worth stripping binaries if the size doesn't change at all?

If I install a `nightly` wheel from anaconda then the behaviour is still there. It might be because the build+tooling on the `manylinux2014` image is slightly incompatible with `strip` in `ubuntu:latest`.

My feeling is that unless there's a compelling reason for being able to strip an existing wheel that this issue should be closed.

**Comment by rgommers** [comment]
Yes, shared libraries in our wheels and conda-forge packages are already stripped - if not, that's a bug. Manual stripping can break things if done with the wrong flags.
