### ISSUE TITLE
BUG: Why is `logsumexp(inf + 4j) == inf - 2.35619449j`?

### ISSUE THREAD

**Issue by mfkasim1** [scipy/scipy#17586]
### Describe your issue.

For reduce operator like `logsumexp`, I expect to return the same element if the input is only 1 element.
However, when I put the input to `logsumexp` below, I didn't get the same element as the input:

```python
from scipy.special import logsumexp
print(logsumexp(float('inf') + 4j))  # inf-2.35619449j
print(logsumexp(-float('inf') + 4j))  # -inf+0j
```

I can understand the reasoning behind the last line above with `-inf` and why it returns `-inf + 0j`.
However, it's not clear to me where did the imaginary value of the `+inf` case comes from (i.e. `-2.35619449`)?

### Reproducing Code Example

```python
from scipy.special import logsumexp
print(logsumexp(float('inf') + 4j))  # inf-2.35619449j
print(logsumexp(-float('inf') + 4j))  # -inf+0j
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version information

1.9.3 1.21.6 sys.version_info(major=3, minor=9, micro=15, releaselevel='final', serial=0)

**Comment by freund** [comment]
`logsumexp` first calculates the exponential: $\exp(-\infty+4j) = \exp(-\infty)\exp(4j) = 0$. Then it calculates the logarithm: $\log 0 = -\infty$.

But with the other example, $\exp(+\infty+4j) = \exp(\infty)\exp(4j) = \exp(\infty)(\cos 4+(\sin 4)j) = -\infty-\infty j$ (because $\cos 4$ and $\sin 4$ are negative). In polar form, $-\infty-\infty j = \infty\exp(-\frac34\pi j)$, so $\log(-\infty-\infty j) = \log\infty-\frac34\pi j = \infty-\frac34\pi j$. And $-\frac34\pi \approx -2.35619449$. The complex logarithm is a multivalued function, but `np.log` gives the result whose imaginary part lies in $(-\pi, \pi]$.

**Comment by mdhaber** [comment]
Because $\log(\exp(\infty + 4i)) = \infty - 2.356194490192345i$, of course!

```
import numpy as np
np.log(np.exp(np.inf + 4j))
# np.complex128(inf-2.356194490192345j)
```
