### ISSUE TITLE
BUG: scipy.optimize.minimize does not work for np.float32

### ISSUE THREAD

**Issue by zhoulaifu** [scipy/scipy#17636]
### Describe your issue.

It seems scipy.optimize.minimize works well for this 64bit function `lambda x: np.float64(x)*np.float64(x)` but not for this 32bit one: `lambda x: np.float32(x)*np.float32(x)`. 

### Reproducing Code Example

```python
In [32]: g= lambda x: np.float64(x)*np.float64(x)
    
    In [33]: scipy.optimize.minimize(g,1)
    Out[33]:
          fun: 5.5507930986288555e-17
     hess_inv: array([[0.5]])
          jac: array([4.32220232e-13])
      message: 'Optimization terminated successfully.'
         nfev: 6
          nit: 2
         njev: 3
       status: 0
      success: True
            x: array([-7.45036449e-09])
    
    In [34]: h= lambda x: np.float32(x)*np.float32(x)
    
    In [35]: scipy.optimize.minimize(h,1)
    Out[35]:
          fun: 1.0
     hess_inv: array([[1]])
          jac: array([0.])
      message: 'Optimization terminated successfully.'
         nfev: 2
          nit: 0
         njev: 1
       status: 0
      success: True
            x: array([1.])
```

### Error message

```shell
See above.
```

### SciPy/NumPy/Python version information

1.9.0 1.22.4 sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @zhoulaifu, thank you for reporting. This is an interesting one, there is no error per se, the result is due to the fact that by default `minimize` will call `bfgs`. And if you have a look at the docstring of this function, you will see that there is a parameter `eps` which is used for numerical differentiation. This parameter is assuming double precision, hence too small when you have a single precision output.

To go around, adjust this value (here is just an example):

```python
minimize(h, 1, options=dict(eps=1e-2))

Out[8]: 
  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 2.499999391147867e-05
        x: [-5.000e-03]
      nit: 2
      jac: [ 9.095e-10]
 hess_inv: [[ 5.000e-01]]
     nfev: 6
     njev: 3
```

Besides a warning in the documentation of `minimize`, I am not sure if we can do anything more.

@andyfaff any recommendations here? Or should we just close this issue?

**Comment by andyfaff** [comment]
My recommendations are to stick with float64 whenever you're doing numerical differentiation. This will be to do with the errors involved with numerical differentiation of lower precision floating point numbers.

There is no fix to the code required. However, a general documentation guideline on using float32 vs float64 may be worthwhile, this is not an uncommon question.
