### ISSUE TITLE
Failed to install on Raspberry Pi (ARM) 32bit in 3.11.1

### ISSUE THREAD

**Issue by nod0n** [scipy/scipy#17670]
Hello

What I did:

1. I installed 3.11.1 with pyenv
2. Created a venv with 3.11.1
3. `pip install -r requirements.txt`
   ```
   numpy~=1.24.1
   pandas~=1.5.2
   influxdb~=5.3.1
   requests~=2.28.1
   flask~=2.2.2
   matplotlib~=3.6.2
   seaborn~=0.12.1
   scikit-learn~=1.2.0
   ```
4. `python -c 'from sklearn.model_selection import train_test_split'`:
   ```
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/sklearn/__init__.py", line 82, in <module>
       from .base import clone
     File "/home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/sklearn/base.py", line 17, in <module>
       from .utils import _IS_32BIT
     File "/home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 25, in <module>
       from .fixes import parse_version, threadpool_info
     File "/home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/sklearn/utils/fixes.py", line 19, in <module>
       import scipy.stats
     File "/home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/scipy/stats/__init__.py", line 467, in <module>
       from ._stats_py import *
     File "/home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/scipy/stats/_stats_py.py", line 46, in <module>
       from . import distributions
     File "/home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/scipy/stats/distributions.py", line 8, in <module>
       from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
     File "/home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
       from scipy import optimize
     File "/home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/scipy/__init__.py", line 211, in __getattr__
       return _importlib.import_module(f'scipy.{name}')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/home/fhnw/.pyenv/versions/3.11.1/lib/python3.11/importlib/__init__.py", line 126, in import_module
       return _bootstrap._gcd_import(name[level:], package, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/scipy/optimize/__init__.py", line 413, in <module>
       from ._linprog import linprog, linprog_verbose_callback
     File "/home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/scipy/optimize/_linprog.py", line 21, in <module>
       from ._linprog_highs import _linprog_highs
     File "/home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/scipy/optimize/_linprog_highs.py", line 20, in <module>
       from ._highs._highs_wrapper import _highs_wrapper
   ImportError: /home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-311-arm-linux-gnueabihf.so: undefined symbol: __atomic_compare_exchange_8
   ```

**Comment by tupui** [comment]
Hi @nod0n, thank you for reporting. Could you post the install log from pip (the section related to SciPy)? Which version is this installing?

**Comment by nod0n** [comment]
Hi @tupui, I hope this is what you need. If not, please let me know how I can provide what you need. ;)

Scipy: 1.9.3

`grep -i scipy pip_install_requirements_txt.log`:
[pip_scipy.log](https://github.com/scipy/scipy/files/10316018/pip_scipy.log)

full log: 
[pip_install_requirements_txt.log](https://github.com/scipy/scipy/files/10316019/pip_install_requirements_txt.log)

**Comment by tupui** [comment]
From the log it's using a wheel we are not shipping (normal since we don't provide wheels for this config), the first log would have been interesting to see. Building SciPy requires compilers to be installed. There are a few issues already about Raspberry Pi. e.g. #16784

**Comment by nod0n** [comment]
I'm installing python 3.11.1 on a second Pi. This time on a 64-bit Raspberry Pi OS (to see if it makes a difference). I'll provide the logs when I'm done (`pip install --log pip_install_requirements_txt.log -r requirements.txt`).

**Comment by rgommers** [comment]
There's another report of `_highs/_highs_wrapper.cpython-311-arm-linux-gnueabihf.so: undefined symbol: __atomic_compare_exchange_8` here: https://stackoverflow.com/questions/73766353/scipy-error-undefined-symbol-atomic-compare-exchange-8-when-using-ssim-func.

Other projects with similar issues:
- `grpc`: https://github.com/grpc/grpc/issues/25720. 
- `opencv: [opencv#15278](https://github.com/opencv/opencv/issues/15278) (issue), [opencv#15353](https://github.com/opencv/opencv/pull/15353), [opencv#15540](https://github.com/opencv/opencv/pull/15540) (PRs with fix)

The root cause is usage of `std::atomic` in Pocketfft, HiGHS and Boost, for which it looks like we do need a compile check in the build system to ensure we pull in `libatomic` on armv7 (not sure it's only that platform).

https://stackoverflow.com/questions/70084134/undefined-symbol-atomic-exchange-8 explains that that symbol was moved from `libgcc` to `libatomic`. Searching for `libatomic` in the issue tracker shows no other bug reports (a little surprising, given we've been using `std::atomic` for quite a while), and also that mingw automatically adds a `--enable-libatomic` flag. So it seems like armv7/raspbian gcc is the only compiler where this goes wrong.

**Comment by rgommers** [comment]
https://github.com/dask/distributed/issues/6824 shows the same issue; SciPy 1.8.1 apparently worked, probably because the wheels at https://www.piwheels.org/simple/scipy/ (where 1.8.1 is latest) are fine. Maybe due to `distutils` handling this, however I cannot find any trace of `-latomic` support in either `distutils` or `numpy.distutils`. So it can also be that this hasn't been a problem for piwheels yet because they used an older GCC version where the symbol was still present in `libgcc`. @bennuttall maybe you can comment on this?

Given that we don't have CI for armv7 and piwheels has an open issue for adding SciPy 1.9+ (https://github.com/piwheels/packages/issues/315), it's probably useful to help them update their SciPy wheels for 1.9.3 and 1.10.0.

**Comment by nod0n** [comment]
I could not reproduce the problem on a 64-bit Raspberry Pi. Everything works as expected on the same Pi with Raspberry Pi OS 64-bit!

**Comment by bennuttall** [comment]
That's because there's an aarch64 wheel on PyPI. piwheels builds armv7 wheels.

**Comment by rgommers** [comment]
@nod0n gh-17777 has a proposed fix. Could you please verify if that works for you?

**Comment by rgommers** [comment]
The gh-17777 fix is GCC-only. Which is okay as a temporary band-aid, but it looks like we're also going to have problems with Clang, if anyone would use that for 32-bit platforms - we'd need `compiler-rt`: https://clang.llvm.org/docs/Toolchain.html#atomics-library. Other compilers are likely to have similar issues. So I think we should consider this an issue in HiGHS and try to get it fixed upstream. The problem is probably not use of `std::atomic`, since that is widespread in Boost and other libraries as well, but incorrect data alignment for some usage somewhere in HiGHS.

**Comment by Qengineering** [comment]
Adding `-D OPENCV_FORCE_LIBATOMIC_COMPILER_CHECK=1` to cmake will solve the issue, for now. See pull [#24031](https://github.com/opencv/opencv/pull/24031).

**Comment by rgommers** [comment]
Eh, wrong repo @Qengineering? This isn't related to OpenCV or CMake directly, the SciPy build (which uses Meson) can fail directly with this problem, unrelated to OpenCV.
