### ISSUE TITLE
104 tests fail on aarch64 with `RuntimeWarning: invalid value encountered in cast`

### ISSUE THREAD

**Issue by ggardet** [scipy/scipy#17760]
### Describe your issue.

On openSUSE Tumbleweed, we have 104 tests fail on aarch64 with `RuntimeWarning: invalid value encountered in cast`.

### Reproducing Code Example

```python
Run test suite on openSUSE Tumbleweed aarch64.
```

### Error message

Full error log (too long for a copy/past as it is limited to 65536 char): https://paste.opensuse.org/pastes/b86ee07b9136

### SciPy/NumPy/Python version information

scipy 1.9.3, numpy 1.24.1

**Comment by tupui** [comment]
Thanks @ggardet, seems to be linked to this: https://numpy.org/devdocs/release/1.24.0-notes.html#numpy-now-gives-floating-point-errors-in-casts

**Comment by andyfaff** [comment]
That's interesting, because the issue doesn't arise in CI, https://cirrus-ci.com/task/5758309563629568, albeit with python310

**Comment by andyfaff** [comment]
Clarification, the issue doesn't arise in main, with numpy 1.24.1, with python3.10.

However, it does manifest in 1.9.3. #16403 is related and is the original issue for this problem. There were more issues uncovered at a later stage, #17630, for linux_aarch64. (note we've only had a `linux_aarch64` CI run for a short period of time). Those issues were fixed in >= 1.10 by PR #17634. However, the latter PR has not been backported to the 1.9.x branch.

@tylerjereddy, is it possible to backport the fixes in #17634 if we make another 1.9.x point release? If we're not going to be making another 1.9.x release then we should close this issue as wontfix.

@ggardet, thanks for reporting these test failures. You won't see the issues if you update to 1.10, but the fix has not yet been backported to the 1.9.x maintenance branch.

**Comment by rgommers** [comment]
I like @andyfaff's suggestion. The test failures themselves seem harmless, they're just warnings that get turned into errors by the test suite. So a new release specifically for this should not be necessary.

**Comment by tylerjereddy** [comment]
Ok, I added the label and a short comment over there

**Comment by ggardet** [comment]
> Clarification, the issue doesn't arise in main, with numpy 1.24.1, with python3.10.
> 
> However, it does manifest in 1.9.3. #16403 is related and is the original issue for this problem. There were more issues uncovered at a later stage, #17630, for linux_aarch64. (note we've only had a `linux_aarch64` CI run for a short period of time). Those issues were fixed in >= 1.10 by PR #17634. However, the latter PR has not been backported to the 1.9.x branch.
> 
> @tylerjereddy, is it possible to backport the fixes in #17634 if we make another 1.9.x point release? If we're not going to be making another 1.9.x release then we should close this issue as wontfix.
> 
> @ggardet, thanks for reporting these test failures. You won't see the issues if you update to 1.10, but the fix has not yet been backported to the 1.9.x maintenance branch.

Indeed, I updated to 1.10 release and the problem is gone. Thanks!

**Comment by tylerjereddy** [comment]
I'll close this issue--if we do have an accumulation of reasons to do another `1.9.x` point release, I'll aim to fix this while I'm at it, but it sounds like we won't rush another `1.9.x` just yet for these warnings alone--hopefully that's ok.
