### ISSUE TITLE
BUG: name of cython executable is hardcoded in _build_utils/cythoner.py

### ISSUE THREAD

**Issue by drew-parsons** [scipy/scipy#17808]
The meson build for scipy 1.10 doesn't use meson's in-built tools for cython.  That was removed from meson.build in PR #15407 , creating scipy/_build_utils/cythoner.py.

[cythoner.py](https://github.com/scipy/scipy/blob/93221522789d5d530b6655c89ad161fcd5c7afeb/scipy/_build_utils/cythoner.py#L20) hard-codes the name of the cython executable as 'cython'.  This is a problem on debian (ubuntu) systems for instance, where the executable is called cython3.

There is a similar configuration for the old setuptools build, in [tools/cythonize.py](https://github.com/scipy/scipy/blob/dde50595862a4f9cede24b5d1c86935c30f1f88a/tools/cythonize.py#L100).  But there the call to 'cython' is wrapped in a try block, and checks for Cython.Compiler inside python if the subprocess call to cython fails.

Should the same kind of try..except block that was used in  tools/cythonize.py be now used in scipy/_build_utils/cythoner.py ?

### Reproducing Code Example

```
python3 -m build
```

### Error message

```shell
[10/1620] Generating 'scipy/_lib/_test_deprecation_call.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_call.c'.
FAILED: scipy/_lib/_test_deprecation_call.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_call.c 
/usr/bin/python3 /home/drew/projects/python/build/scipy/scipy/_build_utils/cythoner.py ../../scipy/_lib/_test_deprecation_call.pyx scipy/_lib/_test_deprecation_call.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_call.c
Traceback (most recent call last):
  File "/home/drew/projects/python/build/scipy/scipy/_build_utils/cythoner.py", line 28, in <module>
    main()
  File "/home/drew/projects/python/build/scipy/scipy/_build_utils/cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cython'
```

### SciPy/NumPy/Python version information
```
$ python3 -c "import sys, numpy; print(numpy.__version__, sys.version_info)"
1.24.1 sys.version_info(major=3, minor=11, micro=1, releaselevel='final', serial=0)
```
Attempting to build scipy 1.10.0 on debian unstable.

**Comment by eli-schwartz** [comment]
@drew-parsons

> This is a problem on debian (ubuntu) systems for instance, where the executable is called cython3.

Aside -- maybe you know who to talk to so that Debian does not do this? It's totally wrong.

`cython` is a CLI executable that produces output files which work on both python2 and python3 -- there is utterly no reason to fork and diverge from upstream's documented command line interface by renaming binaries. Simply have the python3 package for the cython *library* install a cython *command*, and have the python2 package for the cython *library* refrain from installing the command.

This would make everyone's life simpler, especially since there isn't actually a python2 package in the first place.

It's really strange for Debian to arbitrarily rename CLI executables based on the major version of the programming language they happen to be written in.

That being said, Meson's builtin cython transpile support has a crude hack for this, so transitioning over to that would work. This is possible in Meson git master, since that adds support for transpile dependencies, but of course SciPy cannot depend on meson 1.0.99 (and it would then become un-packageable by Debian, anyway).

> Should the same kind of try..except block that was used in tools/cythonize.py be now used in scipy/_build_utils/cythoner.py ?

Probably not -- Meson doesn't assume that cython is installed in the same virtual environment that SciPy is being built in, it is after all a CLI tool. I don't think cythoner.py should either. Maybe it makes more sense to do this: #17810

**Comment by drew-parsons** [comment]
> Aside -- maybe you know who to talk to so that Debian does not do this? It's totally wrong.

It's a fair point.  It would have started historically trying to manage python2 and python3 with their separate respective cythons.  Actually a debian bug has already been raised, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=686045 (_10 years ago!_)

**Comment by drew-parsons** [comment]
#17810 should resolve this issue satisfactorily.

In principle the path of the compiler binary can be defined the [binaries] section in a native-build.ini file, cf. https://mesonbuild.com/Machine-files.html#binaries

**Comment by eli-schwartz** [comment]
> It's a fair point. It would have started historically trying to manage python2 and python3 with their separate respective cythons. Actually a debian bug has already been raised, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=686045 (_10 years ago!_)

Thanks! Fingers crossed that now that python2 is gone this will gain more traction. :)
