### ISSUE TITLE
BUG: stats.powerlaw.fit: raises OverflowError

### ISSUE THREAD

**Issue by kwinkunks** [scipy/scipy#17801]
### Describe your issue.

The code example runs without problem in `scipy` v1.9.3 but throws an overflow error in v1.10.0. I have not tried fitting all of the other distributions, but these work as expected: `['norm', 'cosine', 'expon', 'exponpow', 'gamma', 'gumbel_l', 'gumbel_r', 'triang', 'trapz', 'uniform']`.

### Reproducing Code Example

```python
import scipy.stats as ss

a = [0, 1, 2, 2, 3, 3, 3, 3, 4, 4, 5, 6]
*shape, μ, σ = ss.powerlaw.fit(a)
```

### Error message

```shell
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
Cell In[1], line 3
      1 import scipy.stats as ss
      2 a = [0, 1, 2, 2, 3, 3, 3, 3, 4, 4, 5, 6]
----> 3 *shape, μ, σ = ss.powerlaw.fit(a)

File /home/data1/bin/miniconda3/envs/redflag/lib/python3.10/site-packages/scipy/stats/_continuous_distns.py:7504, in powerlaw_gen.fit(self, data, *args, **kwds)
   7501 fit_shape_lt1 = fit_loc_scale_w_shape_lt_1()
   7502 ll_lt1 = penalized_nllf(fit_shape_lt1, data)
-> 7504 fit_shape_gt1 = fit_loc_scale_w_shape_gt_1()
   7505 ll_gt1 = penalized_nllf(fit_shape_gt1, data)
   7507 if ll_lt1 <= ll_gt1 and fit_shape_lt1[0] <= 1:

File /home/data1/bin/miniconda3/envs/redflag/lib/python3.10/site-packages/scipy/stats/_continuous_distns.py:7468, in powerlaw_gen.fit.<locals>.fit_loc_scale_w_shape_gt_1()
   7466 delta = (data.min() - rbrack)
   7467 while dL_dLocation_star(rbrack) > 0:
-> 7468     rbrack = data.min() - i * delta
   7469     i *= 2
   7471 def interval_contains_root(lbrack, rbrack):
   7472     # Check if the interval (lbrack, rbrack) contains the root.

OverflowError: int too large to convert to float
```

### SciPy/NumPy/Python version information

1.10.0 1.24.1 sys.version_info(major=3, minor=10, micro=8, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
I think we can just change `i *= 2` to `delta *= 2` and get rid of `i`. I'll open a PR.

**Comment by mdhaber** [comment]
I think changing `i *= 2` to `delta *= 2` and getting rid of `i` is useful, but it doesn't quite fix the problem.

The underlying issue here is that maximum likelihood estimation is breaking down. The maximum likelihood estimate of the shape parameters tends toward `loc = 0`, `shape=0`, and `scale=6`, and the corresponding likelihood tends toward infinity. We can see this by fixing the shape and letting it approach the minimum of the data.

```python3
-ss.powerlaw.nnlf(ss.powerlaw.fit(a, floc=-1e-1), a)  # log-likelihood: -21.693885069950376
-ss.powerlaw.nnlf(ss.powerlaw.fit(a, floc=-1e-10), a)  # log-likelihood: -12.91139541342906
-ss.powerlaw.nnlf(ss.powerlaw.fit(a, floc=-1e-100), a)  # log-likelihood: 170.3649416908315
-ss.powerlaw.nnlf(ss.powerlaw.fit(a, floc=-1e-200), a)  # log-likelihood: 392.54695265356656
```
This makes sense: the contribution to the likelihood due to the observation at `x = 0` is getting larger as the distribution approaches a spike concentrated `x = +0`. The contribution of the other observations are getting smaller, but due to the way likelihood is defined, the overall likelihood is still increasing. MLE is not perfect.

When the minimum of the data has large (1 or greater) magnitude, this is not much of a problem. We pick the location as `np.nextafter(x.min(), -np.inf)`, and this gives reasonable estimates for everything (although they are not strictly the MLE, which would have `loc = x.min()`). When the minimum of the data gets smaller than 1, the location is allowed to get closer to the minimum of the data, and equations start to blow up. In the case of `x.min() == 0 ` as we have here, the location is a subnormal number and things really break down.

I think the simplest "fix" would be to give an offset to the data before fitting, then subtracting that offset from the location after fitting. But we should also add a note in the documentation that when the shape is less than 1, the returned MLE is approximate and the exact MLE would be `loc =x.min()`,`shape = 0`, etc...
