### ISSUE TITLE
CI job with numpy nightly build failing on missing `_ArrayFunctionDispatcher.__code__`

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#17811]
See for example [this log](https://github.com/scipy/scipy/actions/runs/3946141515/jobs/6753635939). Lots of this:
```
AttributeError: 'numpy._ArrayFunctionDispatcher' object has no attribute '__code__'
```

Should be due to https://github.com/numpy/numpy/pull/23020 (Cc @seberg). There are two usages of  `__code__`:
```
 rg __code__
scipy/integrate/_quadrature.py
28:    g = types.FunctionType(f.__code__, f.__globals__, name=f.__name__,

scipy/interpolate/_rbf.py
193:               hasattr(self.function, '__code__'):
202:            argcount = val.__code__.co_argcount
```
Haven't checked yet what those do exactly, but either way this is a regression that's going to break already-released SciPy versions, so it should be fixed on the NumPy side.

**Comment by seberg** [comment]
So SciPy assumes that `numpy.trapz` and whatever functions are used in Rbf here are Python functions and not anything else (cython, ufunc, C).  Maybe we can feed a fake but working `__code__`...

**Comment by seberg** [comment]
Ah, so the rbf thing isn't a failure after all just a random grep!  It is just an (incorrect) use of `__code__` which has no relevance for the issue because it *always* failed in any case.

**Comment by rgommers** [comment]
gh-17827 reports that `import scipy.stats` fails with the numpy nightly. And judging by the number of incoming links here, we should fix this in `numpy` as soon as we can. Either that, or remove the nightlies with the problem from https://anaconda.org/scipy-wheels-nightly/numpy and stop uploading them to give us some time.

> Maybe we can feed a fake but working `__code__`...

How much work do you think that is? It seems useful, whatever fixes the problem here I'd say. The `integrate.trapezoid` usage is uninteresting, just a docstring manipulation. It breaks `import scipy.stats` though, so we need the patch in numpy to unbreak that. And at the same time, also remove that stuff in `scipy.integrate` or put a try-except around it.

**Comment by seberg** [comment]
@rgommers its already fixed in NumPy (effectively, someone has to press the green button and maybe wait for CI): https://github.com/numpy/numpy/pull/23034
(I had another fix yesterday, but it wasn't as good, so in that sense its good it wasn't merged ;))

I suspect SciPy should just make a new `def` for both versions (rather than just for the discouraged alias)?  You can use `functools.wraps` (and reset the `__name__` if that is necessary).

The other place that uses `__code__` should maybe have a try/except in some form, but already failed previously, because previously all of these NumPy functions used `*args` and registered as having 0 arguments in the code.

**Comment by rgommers** [comment]
Thanks! I merged your PR, and will have a look at opening a SciPy PR to close this issue.
