### ISSUE TITLE
BUG: scipy 1.5.4 and 1.10.0 return different p-values for same data

### ISSUE THREAD

**Issue by kdsjZh** [scipy/scipy#17821]
### Describe your issue.

Hello, I was calculating p-value for my evaluation results and I found that different version of scipy can return different p-value for the same set of data.

The scipy 1.5.4 and 1.10.0, which is the default version for ubuntu 18.04 and 20.04, return different mannwhitneyu p-value. I'm wondering which version is correct or both are wrong?

### Reproducing Code Example

```python
## demo code
import sys

from scipy.stats import mannwhitneyu
from scipy import mean

print(sys.version)

tor_flvmeta_cov = [994, 994, 994, 994, 994, 995, 994, 995, 994, 994]
ff_flvmeta_cov = [996, 996, 996, 996, 996, 996, 996, 996, 996, 996]
stats, pval = mannwhitneyu(ff_flvmeta_cov, tor_flvmeta_cov)

print(pval)
print(mean(tor_flvmeta_cov))
print(mean(ff_flvmeta_cov))

ff_xmllint_cov = [8109, 8040, 7874, 8256, 8103, 8067, 7887, 7909, 7915, 8133]
afl_xmllint_cov = [8210, 7513, 8205, 7836, 8208, 8201, 8383, 7279, 7563, 8004]
stats, pval = mannwhitneyu(ff_xmllint_cov, afl_xmllint_cov)

print(pval)
print(mean(afl_xmllint_cov))
print(mean(ff_xmllint_cov))
```

### Error message

```shell
version1:
    ubuntu 18.04 numpy-1.19.5 scipy-1.5.4 python3.6.9
    results: 1.6449684029324486e-05, 994.2, 996.0
             0.4849249884965778, 7940.2, 8029.3
version2:
    ubuntu 20.04 numpy-1.24.1 scipy-1.10.0 python3.8.10
    results: 3.28993680586491e-05, 994.2, 996.0
             1, 7940.2, 8029.3
```

### SciPy/NumPy/Python version information

numpy-1.19.5 scipy-1.5.4 python3.6.9 && numpy-1.24.1 scipy-1.10.0 python3.8.10

**Comment by mdhaber** [comment]
`mannwhitneyu` was rewritten for 1.7.0. It now produces exact p-values by default for small samples when there are no ties. The p-value in 1.5 was always an asymptotic approximation. Also in 1.5, which of two statistics was returned also depended on your data; now the choice of the two statistics is consistent.

That said, you have ties in your data, so in that case both p-values are approximate. I'll send code that computes an exact p-value shortly, but in short, neither is wrong. Approximations like this are commonly recommended in the literature, and the behavior is [documented](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html).

**Comment by tupui** [comment]
Then I suppose we can close the issue if the behaviour is documented and normal.

**Comment by mdhaber** [comment]
For the first data-set, the exact _one-sided_ p-value is $1 {20}\choose{10} = 5.412544112234515e-06 $ because the data are grouped in the unique way to produce the most extreme possible value of the statistic and there are ${20}\choose{10}$ ways to partition the data into the two groups. The exact two-sided p-value twice that ($1.082508822446903e-05$) because the distribution is symmetric about zero.

```python3
import numpy as np
from scipy import stats
tor_flvmeta_cov = [994, 994, 994, 994, 994, 995, 994, 995, 994, 994]
ff_flvmeta_cov = [996, 996, 996, 996, 996, 996, 996, 996, 996, 996]

def statistic(x, y, axis):
    return stats.mannwhitneyu(x, y, axis=axis, method='asymptotic').statistic

# stats, pval = mannwhitneyu(ff_flvmeta_cov, tor_flvmeta_cov)
res = stats.permutation_test((tor_flvmeta_cov, ff_flvmeta_cov), statistic,
                             permutation_type='independent', batch=1000,
                             n_resamples=200000)
# PermutationTestResult(statistic=0.0, pvalue=1.082508822446903e-05, ...)
```

For the second data set, the p-value produced in 1.10.0 is exact.
```python3
import numpy as np
from scipy import stats
ff_xmllint_cov = [8109, 8040, 7874, 8256, 8103, 8067, 7887, 7909, 7915, 8133]
afl_xmllint_cov = [8210, 7513, 8205, 7836, 8208, 8201, 8383, 7279, 7563, 8004]

def statistic(x, y, axis):
    return stats.mannwhitneyu(x, y, axis=axis, method='asymptotic').statistic

# stats, pval = mannwhitneyu(ff_flvmeta_cov, tor_flvmeta_cov)
res = stats.permutation_test((ff_xmllint_cov, afl_xmllint_cov), statistic,
                             permutation_type='independent', batch=1000,
                             n_resamples=200000)
```

The one-sided p-value is exactly $0.5147437701617268$. The distribution is symmetric about zero, so the two-sided p-value is twice that rounded down to 1. (I'm glossing over the fact that the distribution is discrete, and the "rounding" here is more appropriately explained by adding up probability mass in each tail.)

Note that the default alternative hypothesis in 1.5.0 was unusual:
![image](https://user-images.githubusercontent.com/6570539/213491330-858204b5-c522-43df-b3c7-8645ee680240.png)

so maybe I'll revise my statement: in 1.5.0 the p-value was not easy to interpret unless you specified `alternative` explicitly.

**Comment by mdhaber** [comment]
Just another tip: I noticed that in each dataset, the two samples have the same number of observations. Consider whether the observations should be treated as paired, in which case you could use `wilcoxon`.
