### ISSUE TITLE
ENH: Build macos universal2 package for python 3.11

### ISSUE THREAD

**Issue by CMengich** [scipy/scipy#17826]
### Is your feature request related to a problem? Please describe.

Previous versions of SciPy available on PyPI (The Python Package Index), had macos packages available on install that would work on both intel and apple silicon. For example, the last available version with this was scipy 1.9.1 with following wheel available on PyPI: scipy-1.9.1-cp310-cp310-macosx_12_0_universal2.macosx_10_9_x86_64.whl.

However, from version 1.9.2, with the introduction of packages compatible with python 3.11 and below, only separate x86_64 and aarch64 packages are available for macos.

The universal2 package was incredibly useful when building an application that could work on both systems.

### Describe the solution you'd like.

Instructions on how to build SciPy universal2 packages from source.

I have gone through the documentation, and haven't found information that could help with this.

A guide on the steps to build a SciPy universal2 package from source, in the manner as those distributed on SciPy versions 1.9.1 and below, would be much appreciated.

**Comment by andyfaff** [comment]
You have two options. The first is to use `delocate` to fuse two different architecture wheels together to make a universal wheel. The second option would be to build a universal wheel using e.g. cibuildwheel. With the latter you could use https://github.com/scipy/scipy/blob/main/ci/cirrus_wheels.yml as a guide. Universal wheels are much larger, which is why we don't make them. It's just easier for end users to use the appropriate wheel and make two applications.

**Comment by andyfaff** [comment]
At this point we probably won't make a universal wheel unless there is a compelling reason. The delocate documentation is fairly easy to use, so its probably not worth making a guide to universal wheel construction either.

**Comment by CMengich** [comment]
@andyfaff 
Used delocate to fuse the arm64 and x86_64 wheels successfully. Thanks for the guidance.
