### ISSUE TITLE
BUG: Constraint minimization with the truncated normal distribution

### ISSUE THREAD

**Issue by yhuang85** [scipy/scipy#17871]
### Describe your issue.

I try to approximate a probability distribution within a known bound using truncated normal distribution and the `minimize` function from `scipy.optimize`. But I run into the "Inequality constraints incompatible" issue although I am sure that the inequality constraints are satisfied.

### Reproducing Code Example

```python
from scipy.stats import truncnorm
from scipy.optimize import minimize

# Sample data
a, b, loc, scale = -1, 1, 0.5, 0.1
r = truncnorm.rvs(a, b, loc=loc, scale=scale, size=1000)

# Boundary condition (by absolute range instead of by how many deviations away)
xa = 0
xb = 1

def cost(params, r):
    return truncnorm.nnlf(params, r)

constraints = [
    {'type': 'ineq', 'fun': lambda params: params[2] + params[0] * params[3] - xa},
    {'type': 'ineq', 'fun': lambda params: xb - (params[2] + params[1] * params[3])},
]

init_params = (-0.5, 0.5, 0.3, 0.3)  # (a, b, loc, scale)

res = minimize(cost, init_params, args=(r,), constraints=constraints)
print(res)
```

### Error message

```shell
RuntimeWarning: invalid value encountered in subtract
  df = fun(x) - f0

 message: Inequality constraints incompatible
 success: False
  status: 4
     fun: inf
       x: [-5.000e-01  5.000e-01  3.000e-01  3.000e-01]
     nit: 1
     jac: [       nan        nan        nan        nan]
    nfev: 5
    njev: 1
```

### SciPy/NumPy/Python version information

1.10.0 1.24.1 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Hi @yhuang85. I'm not sure there's a new bug here, although it looks like gh-9439 plays a role. (I assume that is why you are using `optimize` rather than using the `fit` method of the distribution or `scipy.stats.fit`?) Note that if I evaluate the NLLF of `r` at the parameters you guessed:

```python3
import numpy as np
from scipy.stats import truncnorm

# Sample data
a, b, loc, scale = -1, 1, 0.5, 0.1
r = truncnorm.rvs(a, b, loc=loc, scale=scale, size=1000)
guess = (-0.5, 0.5, 0.3, 0.3)
truncnorm.nnlf(guess, r)  # inf
dist.pdf(r)  # has zeros because some points are outside the support of the distribution
```
There is definitely going to be a problem when you try to optimize. 

If the intent was for `constraints` to prevent this from happening, know that optimizers cannot guarantee that nonlinear inequality constraints will be satisfied at all iterations.

If you want to do this fitting manually, you'll need to add some condition to the objective function that prevents it from returning infinities.

**Comment by yhuang85** [comment]
Thank you @mdhaber for the answer. I also just realized that there are some infinities in it. Apparently I misunderstood the truncnorm, I thought the probability is forced to zero outside of certain range by the truncation, but not the domain of the distribution, i.e., it's still legitimate to pick a value at places where the probability is zero.

**Comment by mdhaber** [comment]
> I thought the probability is forced to zero outside of certain range by the truncation, but not the domain of the distribution

The support of the distribution _is_ the range specified by the truncation parameters, `loc`, and` scale`. 

> it's still legitimate to pick a value at places where the probability is zero.

By "pick a value at places where the probability is zero", do you mean "evaluate `nnlf` with the second argument `x` containing values outside the support of the distribution"? This is a "legitimate" thing to do, but the correct answer (the negative log-likelihood) is `inf`, and that is something that optimizers can't work with.

I think that the underlying issue is gh-9439 because it makes fitting `truncnorm` very difficult. It will be addressed as part of gh-15928, so I'll go ahead and close this issue. If you find that there is a different bug, please feel free to reopen.
