### ISSUE TITLE
ENH: scipy.signal.impinvar - Impulse invariant discretization of continuous transfer function

### ISSUE THREAD

**Issue by zolabar** [scipy/scipy#17935]
### scipy.signal.impinvar

With `scipy.signal.bilinear` I can 

transform a set of poles and zeros from the analog s-plane to the digital z-plane using Tustin’s method, which substitutes  fs*2*(z-1) / (z+1) for s, maintaining the shape of the frequency response.

see 

https://github.com/scipy/scipy/pull/17922

and 

https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.bilinear.html

However, if I want to preserve the impulse response, instead of the frequency response, then the impulse invaruiant method is better

https://en.wikipedia.org/wiki/Impulse_invariance

see also

https://github.com/sympy/sympy/discussions/24643

### Describe the solution you'd like.

In analogy to `scipy.signal.bilinear`  there could be `scipy.signal.impinvar`, like in matlab

https://de.mathworks.com/help/signal/ref/impinvar.html

 The tools for it are already in

https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.cont2discrete.html#scipy.signal.cont2discrete

as used by the control package in

https://python-control.readthedocs.io/en/latest/generated/control.sample_system.html

### Describe alternatives you've considered.

I implemented a symbolic version of impinvar via SymPy

https://github.com/sympy/sympy/discussions/24643

in analogy to

https://docs.sympy.org/dev/modules/physics/control/lti.html#sympy.physics.control.lti.bilinear

but it has its limitations.

**Comment by ilayn** [comment]
I'm not sure I understand the suggestion this is already available like you described in cont2discrete. Is there anything missing from that implementation?

Note that impulse invariant representation is mostly for educational purposes and don't have too much of a production value since you typically simulate systems in time domain and don't need any matchings enforced as such.

**Comment by zolabar** [comment]
> I'm not sure I understand the suggestion this is already available like you described in cont2discrete. Is there anything missing from that implementation?
> 
> Note that impulse invariant representation is mostly for educational purposes and don't have too much of a production value since you typically simulate systems in time domain and don't need any matchings enforced as such.

@ilayn , thank you for the feedback. Yes I saw 

https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.cont2discrete.html#scipy.signal.cont2discrete

however, the wrapped version of it in 

https://python-control.readthedocs.io/en/latest/generated/control.sample_system.html

was simpler for me to use, that is why I thought of "scipy.signal.impinvar".

> Note that impulse invariant representation is mostly for educational purposes and don't have too much of a production value since you typically simulate systems in time domain and don't need any matchings enforced as such.

As I understand in the time domain the integration scheme has to be chosen, which is equivalent from chosing a discretiszation, i.e.

blinear discretization leads to trapezoidal integration scheme in time domain
impinvar discretization leads to backward Euler integration scheme in time domain
etc...

As I understand also in productive projects one may have designed continuous filters that need to be discretized, in order to be implemented in the time domain.

How is your understanding? Thank you!

**Comment by ilayn** [comment]
What I meant is that if you need to have a choice about the integration scheme, which is a bit outdated to look at it as such, you can choose forward or backward euler or tustin that is available too. 

My recommendation is that you use time domain simulations directly such as https://python-control.readthedocs.io/en/latest/generated/control.impulse_response.html#control-impulse-response

impinvar, not only having a terrible name thanks to matlab, also is not reliable since partial fraction expansion is only possible for small systems (low order polynomials). Hence it doesn't have enough of a use case to have its own function in SciPy in my opinion.

**Comment by zolabar** [comment]
> 

@ilayn, thank you for the detailed answer, yes, I agree.

**Comment by zolabar** [comment]
@ilayn , I think that we can close this issue. One last thing, however, which control python package do you recommend? Are there further packages that I don't know? Thank you!

I know:

-  scipy.signal
- control
- sympy.physics.control.lti

**Comment by ilayn** [comment]
There is also `harold` that I am the author of. But unfortunately, I'm not finding any time to develop it further these days.

**Comment by zolabar** [comment]
> There is also `harold` that I am the author of. But unfortunately, I'm not finding any time to develop it further these days.

👍
