### ISSUE TITLE
ENH: Support nd-array for welch periodogram

### ISSUE THREAD

**Issue by mocquin** [scipy/scipy#18244]
### Is your feature request related to a problem? Please describe.

I would like to compute 3d-periodograms using Welch method, so I naturaly turned to [`scipy.signal.welch`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.welch.html), but the current interface only supports 1d array.

### Describe the solution you'd like.

I would a simple nd-welch function based on the current one, that could be used for example as :
`welch_nd(data_3d, nperseg=(10, 20, 30), noverlap=(5, 10, 15), axes=(0,1,2))`

The rest of the kwargs could be kept from current implementation (`window='hann', detrend='constant', return_onesided=True, scaling='density', average='mean'`)

### Describe alternatives you've considered.

Workaround I thought about but that do not fit my needs : 
- [Numpy allows for nd fft](https://numpy.org/doc/stable/reference/generated/numpy.fft.fftn.html) using fftn, but does not provide Welch algorithm.
- `scipy.signal.welch` cannot be applied sequentially along all axes because it returns a periodogram, not the raw fourier transform

**Comment by rkern** [comment]
I've never encountered an n-dimensional Welch's method. Part of the care of the design of Welch's method is dealing with the overlap between segments and how that interacts with the window function so that the points in the overlap can be reused but not overly reused. Extending this to greater dimensions will have issues in the corners. I do see people doing full multitaper and deriving appropriate orthogonal sequences of n-dimensional windows; that's a more principled approach that will likely work better.

If you do find a reference for an n-dimensional Welch's method, we can take a look at it. But I suspect that we won't do original research to derive one.

**Comment by rgommers** [comment]
No follow-up, so I'll close this. If someone posts a paper or other relevant info that would make clear exactly how to implement support for >1-dim arrays, we can reopen. Thanks both.
