### ISSUE TITLE
ImportError: scipy.special._ufuncs_cxx does not export expected C variable _export_faddeeva_erfc

### ISSUE THREAD

**Issue by Vidushi5** [scipy/scipy#18268]
I was trying to run a code and faced this error, I am new to this package, can someone help me resolve this?
![Screenshot from 2023-04-09 21-19-33 (1)](https://user-images.githubusercontent.com/17342268/230819207-33a1c619-879f-43fb-9b64-4517090e66b1.png)

ImportError: scipy.special._ufuncs_cxx does not export expected C variable _export_faddeeva_erfc

**Comment by tupui** [comment]
Hi @Vidushi5 thank you for reporting.

Could you please provide more information about your setup following our issue template?

We need to know how you installed Python, SciPy, NumPy, which versions, on which infrastructure.

Here I see it's colab but that's not very informative.

**Comment by tupui** [comment]
I had another look and saw you opened an issue in the repo where you found the notebook. I will close this issue for now as I don't think there is an issue with SciPy but rather with the environment creation and package management on Colab.

Feel free to comment back and if it turns out there is an issue with SciPy I will gladly re-open the issue. Thank you again for opening an issue on SciPy!
