### ISSUE TITLE
Question about usage of _MACHEPS

### ISSUE THREAD

**Issue by stepeos** [scipy/scipy#18388]
Hello,
i have trouble understanding this line https://github.com/scipy/scipy/blob/c1ed5ece8ffbf05356a22a8106affcd11bd3aee0/scipy/optimize/_differentialevolution.py#L947

From my understanding, it is used to avoid division by zero. Am I correct about this?
**If so**, then then shouldn't the machine epsilon be added outside after taking the absolute? So 
```
np.abs(np.mean(self.population_energies)) + _MACHEPS)
```
instead?

I was just trying to understand the convergence mechanism and thought I'd mention.

Thanks in advance! :)

**Comment by ChVeen** [comment]
Hi @stepeos,

yes, you got it right, this `+ _MACHEPS` mechanism prevents a _division by zero_ error.

In my humble opinion you even found a bug:
```
np.abs(np.mean(self.population_energies) + _MACHEPS)
```
Let's assume that the mean of the energies is `-_MACHEPS` since our function to be optimized has a negative optimum so the energies are negative too.
Then we have
```
  np.abs(np.mean(self.population_energies) + _MACHEPS)
= np.abs(-_MACHEPS + _MACHEPS)
= 0
```
This leads to a _division by zero_ error.
Thus, we must place the `_MACHEPS` outside:
```
  np.abs(np.mean(self.population_energies))  + _MACHEPS
= np.abs(-_MACHEPS) + _MACHEPS
= +_MACHEPS + _MACHEPS
= 2 * _MACHEPS
```
This prevents the _division by zero_ error since `_MACHEPS > 0`.

Since you found this bug, do you want to submit a PR with this little fix?
If not, then I can submit one, too.

**Comment by stepeos** [comment]
Awesome, thanks for the elaborate answer! I'll shoot a PR in a minute :)

**Comment by j-bowhay** [comment]
completed in 18392
