### ISSUE TITLE
ENH: add a callback feature to minimize_scalar and root_scalar

### ISSUE THREAD

**Issue by Vetri911** [scipy/scipy#18445]
In scipy.optimize.minimize_scalar(), there is an option to specify `xtol` (or `xatol` in the `bounded` method) in the `options` dictionary.   Would be nice to have a input that specifies a tolerance on the output such that when the optimizer approaches close to the result it concludes the optimization. 

ex. say you want to find the minimum of `f(x)`. The minimum is 0. Maybe I don't need the optimizer to drill down `f(x)` all the way down to say 1e-3, I'm satisfied with getting only as close as 1e-1 for my use because `f(x)` is a computationally expensive function and maybe I don't need that much accuracy

example code below, if my explanation is not clear:
```
def fun(x0):
    return x**2 -1

res = scipy.optimize.minimize_scalar(fun,options={"output_tol:1e-1"}
```
In this case `output_tol` would stop the optimizer when `res.fun` is within (-0.1,0.1). 

Edit: fixed errors pointed out by tupui

**Comment by tupui** [comment]
Thank you for reporting @Vetri911

I think you meant that the minimum is -1 and you would want the optimiser to stop when `x in [-0.1, 0.1]`.

So to have the tolerance on `x` and not `fun` right? I am not sure I get what you would want. Can you start by fixing your example?

**Comment by Vetri911** [comment]
@tupui apologies. fixed !

**Comment by tupui** [comment]
Thank you @Vetri911.

Are you suggesting to have control over the minimal discretisation on `x`? e.g. precision is at best `0.1` so you would only try -0.1, 0, 0.1, ... And you would still use as a stopping criterion the tolerance on the function evaluation itself.

**Comment by Vetri911** [comment]
The suggestion is to use the `output_tol` as a stopping criteria similar to what `xatol` does.

**Comment by tupui** [comment]
Ok sorry for my confusion here 👍

**Comment by mdhaber** [comment]
@Vetri911 there still seems to be some confusion here. 

> The minimum is 0... In this case `output_tol` would stop the optimizer when `res.fun` is within (-0.1,0.1).

The minimizer of your function is `x_opt = 0`, and the minimum is `f(x_opt) = -1`. I think the distinction matters here.

If `minimize_scalar` were to stop when "`res.fun` is within (-0.1,0.1)", this would not be close to a solution of the minimization problem. If you are trying to find the *root* of the function, then the appropriate function to use would be [`root_scalar`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.root_scalar.html).

---

There are many possible convergence criteria, including:
1. changes in `x`
2. changes in `f(x)`
3. difference between `f(x)` and the true minimum (assuming the true minimum is known, but note that `minimize_scalar` doesn't already know that)

All of these could be defined in either absolute or relative terms. Are you asking for one of these? 

Rather than adding arguments to accept values for all possible convergence criteria, I'd suggest adding a `callback` interface to `minimize_scalar` as there is in `minimize`. This would allow you to use whatever termination criterion you wish to stop the optimization. How does that sound?

**Comment by Vetri911** [comment]
@mdhaber you are right. I didn't not realize the distinction between a `root_solver` and a `minimizer`.  I've been using the wrong function. `root_scalar` is what I should have been using. 

In my case I'm usually optimizing to a target value so the minimum is always 0. I reviewed the `callback` feature in  'minimize()` and that interface  would satisfy my ask and looks like `root_scalar` does not have the `callback` feature.

**Comment by mdhaber** [comment]
`root_scalar` is more reliable for findiong the root of functions that *cross* zero, so `minimize_scalar` still might be the right function for the job if the minimum barely touches zero.

In any case, we can consider this to be a request for a `callback` interface in `root_scalar` and `minimize_scalar`. The new method being developed for `root_scalar`, Chandrupatla's algorithm, will have a `callback` interface, and it would not be too hard to add one to the other Python methods. I think it is feasible to add a `callback` interface to the `minimize_scalar` methods, too.

**Comment by Vetri911** [comment]
Thank you for talking through this with me!
