### ISSUE TITLE
optimize.minimize ftol not working

### ISSUE THREAD

**Issue by James-Ilosta** [scipy/scipy#18478]
I'm using the following function: 
result=optim.minimize(fun,x0,method='SLSQP',options={'eps': 0.0001, 'ftol': 1000},bounds=[(0,0.01)],args=(file,)).

Fun is a normalized costing function that produces values of about 1.28e-4. I've tried values of ftol ranging from 1000-1e-4 and the optimizer doesn't converge. I can't understand why. From the documentation, xtol can't be set, so this can't be the reason for this. I'm not sure if this is an error to do with the minimize function or whether this is me misusing the function.

**Comment by mdhaber** [comment]
@James-Ilosta I would suggest starting by posting this question on [Stack Overflow](https://stackoverflow.com/questions/tagged/scipy). You will probably get better help there, since this sounds like to it could be a usage question, but this is a forum for bug reports and enhancement requests. 

Please consider posting there with some additional information:
- Have you tried solving the problem with the default tolerances? Other `method`s? 
- Is the objective function smooth? 
- How many variables are there?

If possible, I'd also suggest posting the complete code so that others can help debug.

If you determine that this is a bug, please come back here and post code that reproduces the problem.

**Comment by melissawm** [comment]
Hi @James-Ilosta - I will close as we are unable to reproduce with the information provided, but feel free to reopen if you can give a minimal reproducible example (mwe). Cheers!
