### ISSUE TITLE
CI: occasional failure of `test_minimum_spanning_tree`

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#18494]
Popped up recently in unrelated PRs, at least [here](https://github.com/scipy/scipy/pull/17697#issuecomment-1555959365) and [here](https://github.com/scipy/scipy/pull/18475). In both cases this happened in the "Linux Meson tests / Meson build (3.11, false)" job.

```
__________________________ test_minimum_spanning_tree __________________________
[gw1] linux -- Python 3.11.3 /opt/hostedtoolcache/Python/3.11.3/x64/bin/python
scipy/sparse/csgraph/tests/test_spanning_tree.py:30: in test_minimum_spanning_tree
    npt.assert_array_equal(mintree.toarray(), expected,
        csgraph    = <5x5 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>
        expected   = array([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])
        graph      = array([[0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 8, 5],
       [0, 0, 8, 0, 1],
       [0, 0, 5, 1, 0]])
        mintree    = <5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>
/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/contextlib.py:81: in inner
    return func(*args, **kwds)
E   AssertionError: 
E   Arrays are not equal
E   Incorrect spanning tree found.
E   Mismatched elements: 4 / 25 (16%)
E   Max absolute difference: 5.
E   Max relative difference: 1.
E    x: array([[0., 1., 0., 0., 0.],
E          [0., 0., 0., 0., 0.],
E          [0., 0., 0., 0., 0.],...
E    y: array([[0, 1, 0, 0, 0],
E          [0, 0, 0, 0, 0],
E          [0, 0, 0, 0, 5],...
        args       = (<built-in function eq>, array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
      ...ray([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]]))
        func       = <function assert_array_compare at 0x7fdcdc52ede0>
        kwds       = {'err_msg': 'Incorrect spanning tree found.', 'header': 'Arrays are not equal', 'strict': False, 'verbose': True}
        self       = <contextlib._GeneratorContextManager object at 0x7fdcdc291090>
```

**Comment by WarrenWeckesser** [comment]
For easy reference, the relevant part of the test is https://github.com/scipy/scipy/blob/458cc70c8ba3a00daf3f3ad1d98695b95a894c45/scipy/sparse/csgraph/tests/test_spanning_tree.py#L9-L31

The error log doesn't show the array that was actually computed--we only see the first three rows of the result of `mintree.toarray()`.

It looks like the test expects `minimum_spanning_tree(csgraph)` to fill in only the upper triangular part of the (sparse) adjacency matrix of the result, but I don't know if the code guarantees that behavior.  If not, it might be necessary to convert `mintree` to the full adjacency matrix for the undirected minimum spanning tree graph, and then compare it to full version of the expected matrix:

```
     expected_full = [[0,1,0,0,0], 
                      [1,0,0,0,0], 
                      [0,0,0,0,5], 
                      [0,0,0,0,1], 
                      [0,0,5,1,0]] 
```

Ping @jakevdp--I know its been more than 10 years since you added the minimum spanning tree code, but if you have a moment, could you take a look?

**Comment by WarrenWeckesser** [comment]
Over in https://github.com/scipy/scipy/pull/17697, I added `mintree_array = mintree.toarray()` to the test. As I suspected, for some reason on that platform the array generated by `minimum_spanning_tree(csgraph)` is

```
mintree_array = array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 5., 1., 0.]])
```
It is putting the entries for the edges of the second disconnected component of the result in the *lower* part of the adjacency matrix.

I don't know if this is a bug, or an acceptable result that wasn't considered when the test was written.
