### ISSUE TITLE
DOC: scipy.integrate.cumulative_trapezoid initial clarification

### ISSUE THREAD

**Issue by zerothi** [scipy/scipy#18588]
### Issue with current documentation:

Currently it is stated that the `initial` argument of `scipy.integrate.cumulative_trapezoid` is inserted as the resulting array of the cumulative integration.

However, I would have expected a cumulative function to add the `initial` to *all* values (since it is part of the cumulative function).

However, this is not clear from the documentation.

### Idea or request for content:

I can see that this may really break things, to I would suggest to add a small example clarifying the `initial` argument:

```python
from scipy.integrate import cumulative_trapezoid

print(cumulative_trapezoid([0, 1], dx=1, initial=2))
```
which yields `[2.   0.5]`

To get the initial in a cumulative fashion one should do:
```python
print(cumulative_trapezoid([0, 1], dx=1, initial=0)+2)
```
which yields `[2.   2.5]`

**Comment by j-bowhay** [comment]
Thanks @zerothi this will hopefully be fixed in #18219

**Comment by zerothi** [comment]
Great! Thanks for this!

**Comment by zerothi** [comment]
I see #18219 deprecated the use of `initial!=0` I would then argue that cumulative methods would incorporate the `initial` value as an addition to all values?
The current API breaks backwards compatibility, and having this I think is clearer.

**Comment by j-bowhay** [comment]
This was discussed on the mailing list here: https://mail.python.org/archives/list/scipy-dev@python.org/thread/5UYCLPVODQJRMMXCUQA5DNPBOIBKAJPK/
Not sure I follow what you mean about backwards compatibility

**Comment by nmadura** [comment]
I was just bit by this using current scipy. I expected initial to act as more than array padding. Having it act only as array padding seems counter-intuitive.
Additionally when I provided it a none-0 value it worked fine, but provided me the following output
![image](https://github.com/scipy/scipy/assets/1625899/feb778fb-9f3a-449e-9d10-b490f5547def)

**Comment by zerothi** [comment]
@nmadura yes, this will first enter in 1.12, so as of now you are stuck with the manual workaround `func(..., initial=0) + offset`, no other way, also this will ensure your code will work past 1.12.

**Comment by alphaparrot** [comment]
I recognize that the ship on this question may have sailed, but I'm only just getting here now (because 1.14 breaks backwards compatibility by deprecating the scipy.integrate.cumtrapz function name, itself something that makes little sense to me given the ubiquity of integration in scientific computing and numpy.cumsum as the upstream legacy of scipy.integrate.cumtrapz). 

As a scientist, the behaviour that the `initial` keyword has in 1.14 is wrong and makes little sense outside of adding a bit of convenience for programmers, and in 1.15 it will technically cease being wrong but it will still make little scientific and mathematical sense. The OP on this issue and the initiator of the linked mailing list thread have also indicated this. The previous behaviour was wrong, but that means the proposed fix should be to make the result behave as expected. Yes, this would break backwards compatibility for anyone using a nonzero initial value. So does the current change coming in 1.15. However, as established here and in many other places, the current behaviour with nonzero initial value is wrong, unexpected, and likely a fair number of people who _use_ a nonzero initial value currently are getting unexpected behaviour (who knows how many bugs abound in current code as a result). And clearly, breaking backwards compatibility in 1.15 isn't the end of the world, as 1.14 demonstrates and as this change indicates. 

I get the argument that throwing an error is less bad as a breaking change than changing numeric behaviour, but **the current numeric behaviour with nonzero `initial` is a bug**, as far as math and science is concerned. Isn't fixing a bug, and allowing this function to behave the way the documentation _seems_ to indicate it ought to, better than restricting its functionality in favour of not breaking code that was likely wrong anyway? For everyone using zero as the initial value, it breaks nothing. For everyone expecting that this sets the initial value of an integral, and therefore acts as a constant offset, their code suddenly works as expected.

Also, as a note, your average scientific programmer is not subscribed to the mailing lists of all libraries they use in code that they write for scientific objectives. Nobody has time for the volume of emails that entails. The mailing list discussion that precipitated #18219 seems to have been a discussion between two people. Perhaps we should not use brief discussions like that as the sole deliberation process for breaking changes (the same thing happened with the f2py changes in numpy 2.0, which were also pretty severely breaking for backwards compatibility), especially when the mailing list is hardly the most visible place for changes in code behaviour. Most of us are only aware of changes when they show up in the documentation, when we happen to check the documentation. Perhaps for something as fundamental and ubiquitous as integration, when backwards-compatibility-breaking changes are being considered, that possibility should be advertised on the documentation with a link to some way to weigh in, so the users who will be affected can add their two cents--with a comment period long enough that at least some people will see it.

**Comment by ilayn** [comment]
@alphaparrot First of all, apologies for throwing a wrench to your workflow. However, we also have our own strong reasoning as you put your own above. 

First, scipy maintainers are almost all scientists too so that does not add much to anything. Being scientist does not make you immune to the tools and the necessary maintenance duties they require, just like your lab equipment will not let you get away with it. If you use your software, regardless of the language or toolchain you use, you **must** maintain it. This particular change has been issuing warnings for two versions. So if you miss the deprecation news they should show up on your code if you did not purposefully silence them. Since, clearly, you are using them then it should have been popping up somewhere someway.

We are doing lots of deprecations sometimes spanning 4, 5 versions and regardless of the time period we squeeze in between deprecation and removals, we always get complaints. This is a balance game we must participate if we are to improve the situation.


> Also, as a note, your average scientific programmer is not subscribed to the mailing lists of all libraries they use in code that they write for scientific objectives. Nobody has time for the volume of emails that entails. The mailing list discussion that precipitated https://github.com/scipy/scipy/pull/18219 seems to have been a discussion between two people.

[snip]

> Perhaps for something as fundamental and ubiquitous as integration, when backwards-compatibility-breaking changes are being considered, that possibility should be advertised on the documentation with a link to some way to weigh in, so the users who will be affected can add their two cents--with a comment period long enough that at least some people will see it.

If you don't have time, then regardless of the platform, you will miss them too. So you are already breaking the contract and we have no way to reach out to you and warnings clearly don't work. Then how do you recommend we reach out to you? This is a genuine question not just us but every open source maintainer is struggling with because folks just use things until it breaks and then we are just an irresponsible closed circle randomly breaking people, not thinking straight about users.

If the fix here does not make sense to you, please open a new issue and make your case and probably folks will have a look at it and maybe explain it better. If documentation is insufficient we can clarify better.

**Comment by ilayn** [comment]
And for the naming, it was a discussion that came from outside telling us in English, these names have bad connotations, I did not think twice about these names as I am not a native speaker, but US speakers made a strong case similar to "thirst trap" and we don't see why it should not be changed even though at the time I was on the "why are we changing?" side. I don't know where to draw the line but this change did not seem like a big change in fact it is more obvious what it is doing. 

Old names are from the 8.3 filename era and that's why they are abbreviated as such but we don't have that restriction anymore. So we don't need to squeeze names into limited punch cards.

**Comment by zerothi** [comment]
@alphaparrot while I kind of share your complaint, I also have to acknowledge @ilayn and the rest of the devs for maintaining this project.

1. Making decisions, one way or the other will always hurt somebody. There can be good arguments for both sides of the aisle, but ultimately it has to be the devs choices.
2. Being a dev is really hard. The most important thing a dev does, is to make these decisions, it may be annoying, but it at least shows commitment to the community, and also, a forward moving state of the project. Post-poning, or making the decision to *not* make a decision is worse IMHO!
3. I think this *could* revised when hitting 1.40, or perhaps in 2.0. The current deprecation will take some time before the old behaviour is fully converted, and then one can do a 2nd round of inquiries. While I agree that the behaviour is still sub-optimal, the change that was decided was the least invasive (because it forced an error, and one would not get regressions). So all-in-all I think this is the best middleground.

I'll close as this is already fixed.
