### ISSUE TITLE
CI, BUG: Cirrus wheel upload fails on maintenance branch

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#18597]
See: https://cirrus-ci.com/build/4827956036501504

`failing at upload stage: [miniconda.sh](http://miniconda.sh/): line 29: HOME: unbound variable`

**Comment by tylerjereddy** [comment]
I may opt for manual artifact download in RC1

**Comment by andyfaff** [comment]
It looks like the nightly builds haven't been uploaded for the CirrusCI runs for 3.5 months! The cause is probably due to the same error from the log message above.
The issue is that the `HOME` environment variable isn't set in the Linux container. I'm submitting a PR to address this, hopefully it'll fix everything up. However, I'll only know if it works when the cron job runs, or if you backport it to the release branch and satisfy:
```if [[ "$COMMIT_MSG" == *"[wheel build]"* ]] && [[ $CIRRUS_BRANCH == maintenance* ]]; then```
