### ISSUE TITLE
BUG: SciPy 1.11.0rc1 not buildable on PPC due to boost submodule

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#18600]
Trying to build rc1 for conda-forge in https://github.com/conda-forge/scipy-feedstock/pull/235, things are looking pretty OK with two exceptions. I'll open another issue for the OSX test failures, but on ppc, the build already fails during compilation:
```
../scipy/_lib/boost_math/include/boost/math/tools/promotion.hpp:140:27: error: static assertion failed: Sorry, but this platform does not have sufficient long double support for the special functions to be reliably implemented.
  140 |          static_assert((0 == std::is_same<type, long double>::value), "Sorry, but this platform does not have sufficient long double support for the special functions to be reliably implemented.");
      |                        ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The boostorg/math submodule (or some recent update thereof) seems to contain a static_assert that unconditionally fails compilation on PPC (or maybe we can toggle off the long double support on PPC?)

PPC is our "most niche" platform, but it's still a hard compilation error on a long-standing arch in conda-forge, so I'm tentatively milestoning this for 1.11.

CC @mckib2 @mdhaber @rgommers @tylerjereddy

**Comment by mborland** [comment]
Do you know which long double format your version of PPC64LE is running (e.g. ibm128 or float128)?

**Comment by h-vetinari** [comment]
I don't actually... It's actually running through QEMU 7.2 on x64 agent. How would I be able to find that out?

**Comment by mborland** [comment]
Is there a way to output `LDBL_MANT_DIG` in your config information. Here's the info on the transition: https://developers.redhat.com/articles/2023/05/16/benefits-fedora-38-long-double-transition-ppc64le#. I'll look through the runner and see if I can find anything.

**Comment by h-vetinari** [comment]
> Here's the info on the transition: https://developers.redhat.com/articles/2023/05/16/benefits-fedora-38-long-double-transition-ppc64le#

Then it's almost certainly the IBM one. We're not on anything nearly as new as Fedora 36 (rather, something like CentOS 7).

PS. Thanks a lot for taking a look at this so quickly, much appreciated!

**Comment by jzmaddock** [comment]
If you look at the backtrace you'll see that you are explicitly calling the pdf on `binomial_distribution<long double>`, so if it's a regression I would say it's at your end.  Probably ;)

BTW the reason we treat this as an error is that "double double"'s cause all kinds of issues in some of our code - it's simply not possible to reason about their behaviour in a sensible way because they have a "discontinuous" representation, this is reflected in their value for `numeric_limits<long double>::epsilon()` which is typically `numeric_limits<double>::min()`.  This is technically correct in that it's the smallest value you can add to 1 and effect a change, but functionally useless in any other sense.

So... my contention has always been that it's just too much work to make these types function correctly inside Boost.Math, but I'm happy to be proved wrong!

**Comment by rgommers** [comment]
> So... my contention has always been that it's just too much work to make these types function correctly inside Boost.Math, but I'm happy to be proved wrong!

I completely agree, and I'd like to remove `long double` support from SciPy (and NumPy) completely. It's not very useful, and full of problems implementation/maintenance-wise. We just can't rip it out with zero notice unfortunately, so we should try to solve the problem here. gh-16185 already took a pragmatic approach in not supporting `long double` on Windows (it'd be 64-bit anyway there).

**Comment by mckib2** [comment]
https://github.com/scipy/scipy/blob/ec22c5587f32198758435964697b08d4e8c4119f/scipy/stats/_boost/include/code_gen.py#L189

Looks like we generate a `NPY_LONGDOUBLE` override on all platform except Windows.  Seems like there's an easy fix to remove the long double code generation -- can we do this without a deprecation cycle?  Seems like we're accidentally supporting this at this point

**Comment by h-vetinari** [comment]
Thanks for everyone's input! I tested @mckib2's #18630 in https://github.com/conda-forge/scipy-feedstock/pull/235 and compilation on PPC now passes. 🥳

If we need to keep `long double` for a while longer (if only to deprecate it), then we could easily restrict that patch to PPC (either here or downstream in conda-forge).
