### ISSUE TITLE
ENH: Consistency in degrees of freedom calculation for stats functions

### ISSUE THREAD

**Issue by JacobGlennAyers** [scipy/scipy#18731]
### Is your feature request related to a problem? Please describe.

In scipy.stats.chisquare, we are given the option to pass in a ddof. However, I see that the function internally calculates the degrees of freedom as it relates to generating the test statistic. However, when we want to generate the critical value, we must calculate the degrees of freedom ourselves.

### Describe the solution you'd like.

It would be nice to synchronize these two functions to make the degrees of freedom a bit more manageable. Maybe have an option to perform the comparison between the two in order to return a boolean would be nice.

### Describe alternatives you've considered.

Maybe have the internally calculate chisquare degrees of freedom as a returned value, so that it could be fed directly into the critical value calculation.

### Additional context (e.g. screenshots, GIFs)

N/A

**Comment by JacobGlennAyers** [comment]
I will note now that this may be redundant since the p-value is returned, which can be compared to whatever confidence level you have, which leaves the degrees of freedom as an intrinsic variable.

**Comment by mdhaber** [comment]
> It would be nice to synchronize these two functions to make the degrees of freedom a bit more manageable. Maybe have an option to perform the comparison between the two in order to return a boolean would be nice.

Only one function, `scipy.stats.chisquare`, is mentioned explicitly. What is the other function? Do you mean the `sf` method of the `chi2` distribution?

> Maybe have the internally calculate chisquare degrees of freedom as a returned value, so that it could be fed directly into the critical value calculation.

We could return the number of degrees of freedom, and if you still want to see this, please email the [mailing list](https://svn.scipy.org/scipylib/mailing-lists.html) because it would require changing the public API. We do this for some other statistical tests, e.g. [`ttest_1samp`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_1samp.html) returns `df`. However, the calculation for `chisquare` is trivial: $n - 1 - \delta$, where $n$ is the number of categories (e.g. `len(f_exp)` if `f_exp` is 1D and not masked) and $\delta$ is `ddof`, which is provided by the user. So personally, I don't feel that it's missing if we're trying to strike a balance between API complexity and meeting all possible needs.

> I will note now that this may be redundant since the p-value is returned, which can be compared to whatever confidence level you have,

Yes. We don't typically provide special support for computing critical values of a statistic because the p-value is typically sufficient to assess the significance of a test, and it does not require the user to provide their threshold for significance.

**Comment by JacobGlennAyers** [comment]
Correct, I was referring to the sf chi2 function. I believe that this was just a problem unique to my scenario where I was doing chi2 testing after normalizing histogram bins [0,1], so it suddenly became non-trivial to know what exactly happened to the degrees of freedom. For my particular case, I have found a satisfactory solution.

**Comment by JacobGlennAyers** [comment]
If anyone runs into the same problem, either use the p_value directly to compare against your alpha value or in a scenario where you really want to directly compare the test statistic from chisquare and the critical value from the chi2.ppf, then make sure that you use the relative counts for each class rather than trying to normalize [0,1]. This will require you to make sure that your observed and expected counts are equal, unless your dataset is massive. From there, you have to manually calculate the degrees of freedom as @mdhaber described above with n-1-ddof.
