### ISSUE TITLE
BUG: scipy.special.factorial2(-1) returns 0 instead of 1

### ISSUE THREAD

**Issue by pjknowles** [scipy/scipy#18813]
### Describe your issue.

According to, for example, https://mathworld.wolfram.com/DoubleFactorial.html , the extension of the double factorial function to negative arguments should make factorial2(-1) equal to 1.  This was the behaviour of `scipy.special.factorial2()` in SciPy 1.10, but in 1.11.1 the function returns zero, for both `exact=True` and `exact=False`.

### Reproducing Code Example

```python
from scipy.special import factorial2
print(factorial2(-1)
```

### Error message

```shell
python -c 'from scipy.special import factorial2; print(factorial2(-1))'
0
```

### SciPy/NumPy/Python version and system information

```shell
python -c 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()'
1.11.1 1.25.0 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /home/peterk/miniconda3/envs/scipy/include
    lib directory: /home/peterk/miniconda3/envs/scipy/lib
    name: blas
    openblas configuration: unknown
    pc file directory: /home/peterk/miniconda3/envs/scipy/lib/pkgconfig
    version: 3.9.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /home/peterk/miniconda3/envs/scipy/include
    lib directory: /home/peterk/miniconda3/envs/scipy/lib
    name: lapack
    openblas configuration: unknown
    pc file directory: /home/peterk/miniconda3/envs/scipy/lib/pkgconfig
    version: 3.9.0
  pybind11:
    detection method: pkgconfig
    include directory: /home/peterk/miniconda3/envs/scipy/include
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: /home/conda/feedstock_root/build_artifacts/scipy-split_1687995550978/_build_env/bin/x86_64-conda-linux-gnu-cc
    linker: ld.bfd
    name: gcc
    version: 12.3.0
  c++:
    commands: /home/conda/feedstock_root/build_artifacts/scipy-split_1687995550978/_build_env/bin/x86_64-conda-linux-gnu-c++
    linker: ld.bfd
    name: gcc
    version: 12.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.35
  fortran:
    commands: /home/conda/feedstock_root/build_artifacts/scipy-split_1687995550978/_build_env/bin/x86_64-conda-linux-gnu-gfortran
    linker: ld.bfd
    name: gcc
    version: 12.3.0
  pythran:
    include directory: ../../../_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /home/peterk/miniconda3/envs/scipy/bin/python
  version: '3.11'
```

**Comment by tupui** [comment]
Hi @pjknowles, thank you for reporting. This is expected, see this comment from @h-vetinari https://github.com/scipy/scipy/issues/15600#issuecomment-1074910868

Maybe we should add a bit more in the documentation??

**Comment by h-vetinari** [comment]
This is indeed intentional. There are different ways to define the recursion (anchored in 0..k or -k..-1), and for negative values, returning 1 is at best inconsistent, already with its fundamental definition, but even moreso with the other factorial functions, floating arguments, etc.

@tupui already referenced the exact comment I would have quoted for this.

There's another aspect of this in the larger scheme of #15600 and its successor issue - we want to distinguish different extensions of the factorial functions (e.g. there's an extension into the complex numbers for `factorial2`), and the default extension - corresponding to the current behaviour - will be `'zero'`. This is obviously more self-explanatory than whatever factorial2 was doing prior to 1.11.

I'm sorry if this causes any inconvenience, but this was a deliberate change to clean up the wildly inconsistent potpourri of behaviour we had before.

**Comment by pjknowles** [comment]
Well, backward compatibility is a valuable thing, and I would not have wasted half an hour chasing an unexpected regression if it had applied here. Improved documentation would be relevant only if it had been in place when I wrote my code, not when this scipy function was changed to do something else.  As it happens, this particular use of` factorial2(-1)` arises at the edge of a sequence, and it must be a common usual use to expect that it returns 1 not 0. If you really don't want to support the obvious desirable definition of n!! for negative integer, it would be better to throw an exception rather than return zero which would not arise from any reasonable mathematical definition, eg in terms of Gamma. Now my code has the edge case explicitly coded, introducing complexity for no good reason. Why not adopt the convention that if a function changes its meaning, it is renamed, and the old one retained? I am now quite nervous to take anything new from scipy because of this event.

**Comment by tupui** [comment]
@pjknowles Backward compatibility is taken very seriously (look at [our tracking issue.](https://github.com/scipy/scipy/issues/15765))

> Why not adopt the convention that if a function changes its meaning, it is renamed, and the old one retained?

Our current policy is to raise a deprecation warning and leave 2 releases until the change happen.

That being said, in case of a bug, or when we think something should really be changed, we can decide to directly fix something. In the end, it's up to the maintainer's judgement.

**Comment by h-vetinari** [comment]
> Well, backward compatibility is a valuable thing

I agree, and we generally do warn in advance of noticeable behaviour changes. But like any rule there are borderline cases, and if we need to formally deprecate every theoretically observable behaviour change, development would grind to a halt.

In this case, it was a borderline decision, but since there were already behaviour changes in the factorial functions (like around 0dim arrays, which had previously already been treated as bug fixes without deprecation), we went ahead and pulled the trigger.

Sorry for the breakage.

> If you really don't want to support the obvious desirable definition of n!! for negative integer,

What's "obvious" here is subjective - it may be better for your recursion, but it's worse in other ways.



> Improved documentation would be relevant only if it had been in place when I wrote my code

Actually, the documentation used to say that negative values return 0, until https://github.com/scipy/scipy/commit/6c4a1970e36a75556ea228a85b77bcea1188092a, when the documentation was (IMO unfortunately) adapted to match the implementation, rather than the other way around. Unfortunately, #15841 had gotten stuck long enough for this to make it into a release.

> I am now quite nervous to take anything new from scipy because of this event.

You are welcome to join the maintenance efforts here and make your voice heard in the discussions here. I would have been open to formally deprecate the behaviour change, but as it happened, everyone who participated was fine with the approach taken.

**Comment by tupui** [comment]
I don't think there is much actionable task we want to have with this issue. Closing for now.
