### ISSUE TITLE
BUG: scipy-1.11.z.tar.gz file missing in 1.11.z releases

### ISSUE THREAD

**Issue by psimovec** [scipy/scipy#18877]
### Describe your issue.

I want to create an update for python3-scipy fedora package, but source code with initialized submodules is missing for 1.11.z release: https://github.com/scipy/scipy/releases/download/v1.11.1/scipy-1.11.1.tar.gz 
It was present in previous releases. Is it intentionally ommited? 

As a workaround for testing  I have cloned the repo, initialized the submodules myself and created the tarball myself.

### Reproducing Code Example

```python
exists: https://github.com/scipy/scipy/releases/download/v1.10.1/scipy-1.10.1.tar.gz 
does not exist: https://github.com/scipy/scipy/releases/download/v1.11.1/scipy-1.11.1.tar.gz
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version and system information

```shell
scipy-1.11.1
```

**Comment by tylerjereddy** [comment]
It was not intentional, let me see what I can do about it.

**Comment by tylerjereddy** [comment]
`scipy-1.11.1.tar.gz` should now be available on the appropriate GitHub release page--it will have a newer timestamp than the other assets, but should otherwise be "ok--" I used the same version of Cython and NumPy that were used to produce the rest of the assets there.

If it looks "ok" to you, feel free to close the ticket.

**Comment by psimovec** [comment]
Thank you! Different timestamp is not an issue.
