### ISSUE TITLE
ENH: adding pre-commit to the repository

### ISSUE THREAD

**Issue by RobPasMue** [scipy/scipy#18895]
### Is your feature request related to a problem? Please describe.

[``pre-commit``](https://pre-commit.com/) is a simple tool that allows you to maintain a common style throughout your library. I'm pretty sure most of the maintainers and developers within SciPy have seen this tool around. I was surprised to see that it wasn't implemented in the SciPy repository. I'd be happy to implement it!

Some interesting hooks are:

[github.com/pre-commit/pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks)
* ``check-json`` - checks json files for parseable syntax.
* ``check-shebang-scripts-are-executable`` - ensures that (non-binary) files with a shebang are executable.
* ``pretty-format-json`` - sets a standard for formatting json files.
* ``check-merge-conflict`` - checks for files that contain merge conflict strings.
* ``check-toml`` - checks toml files for parseable syntax.
* ``check-xml`` - checks xml files for parseable syntax.
* ``check-yaml`` - checks yaml files for parseable syntax.
* ``debug-statements`` - checks for debugger imports and py37+ `breakpoint()` calls in python source.
* ``destroyed-symlinks`` - detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
* ``double-quote-string-fixer`` - replaces double quoted strings with single quoted strings.
* ``end-of-file-fixer`` - ensures that a file is either empty, or ends with one newline.
* ``mixed-line-ending`` - replaces or checks mixed line ending.
* ``name-tests-test`` - verifies that test files are named correctly.

* ``requirements-txt-fixer`` - sorts entries in requirements.txt.

* ``trailing-whitespace`` - trims trailing whitespace.

You could also integrate other tools like ``isort``, ``black``, ``codespell`` and so on... 

Even more, you could integrate with [pre-commit.ci](https://pre-commit.ci/) so that it runs pre-commit for you as part of the workflows.

### Describe the solution you'd like.

Implementing a ``.pre-commit-config.yaml`` file with the above hooks, or a subset of them.

### Describe alternatives you've considered.

I don't know of any other alternatives, sorry. I just think it is a good way of ensuring consistency.

**Comment by j-bowhay** [comment]
We actually do have https://github.com/scipy/scipy/blob/main/tools/pre-commit-hook.py although we don't use the pre-commit tool itself

**Comment by RobPasMue** [comment]
Oh! I wasn't aware of this in fact. Maybe adding the pre-commit config file and using this hook might be enough in that case. I just wanted to suggest some additional hooks in case you were interested in them :)

**Comment by tupui** [comment]
Hi @RobPasMue, yes I am afraid that we had this discussion very recently and the conclusion lead to Stéfan basically re-implementing pre-commit. For the record I would like to use pre-commit, but I think it's too early to propose this again. Hence I would propose to close your PR.

**Comment by RobPasMue** [comment]
Sure no problem at all! Let me close the issue in that case!

**Comment by stefanv** [comment]
> if Stéfan or someone else could share why conclusion was "to re-implement", I am curious to hear.

IIRC, @eli-schwartz had security concerns with external packages being installed by pre-commit. And @rgommers had trouble getting pre-commit to run in his conda environments. Now, there is a hook for those who want it:

The script is here, if you want to take a look: https://github.com/scipy/scipy/blob/main/tools/pre-commit-hook.py

It does a checkout of the staging area into a temporary directory and lints that.

I don't think it would hurt to add a pre-commit.yaml in case others want to use it (I'd certainly use it)?

**Comment by eli-schwartz** [comment]
> IIRC, @eli-schwartz had security concerns with external packages being installed by pre-commit.

On a personal level, I have existing mechanisms to install various tools -- my linux distro, which does cryptographic verification of software that has a security policy (I know that PyPI decided to cease that, but PyPI isn't the only way to release source code) and TOFU backed by a distro cryptographic integrity chain for the rest. It is not vulnerable to typosquatting, MiTM, or similar. A distro package also means that the software is both popular and has been usually vetted to some extent. Packages that contain compiled extensions have been independently built from source code and are usually [reproducible](https://reproducible-builds.org/).

If the software isn't packaged, how do I even know it's trustworthy to use? Many projects aren't necessarily careful about this, and will add any software that seems useful without looking too closely into how it's developed. Sometimes they don't consider it a large risk... because they expect those tools to get run automatically in github CI, which is already sandboxed in a VM run by a big company and has not been granted any API tokens capable of causing damage.

git pre-commit has existed for a long, long, long time. The python-pre-commit project that people often confuse with pre-commit the technology, does not seem to support any tooling model other than "go freshly clone the software, pinned to some old version, and install a private copy specific to this git repository", which makes it hard for me to consider. Both because it asks me to circumvent my usual security policies, and because frankly if I'm going to run a linting tool I would like to use the most recent version regardless of whether some bot has updated it.

I also have had a lot of bad experiences with pre-commit.ci specifically, because it's very common for me to go look at a project and see that it's been recently developed, and then on closer inspection it turns out that after paging through four or five pages worth of commits trying to find the last human-authored commit -- every commit for the last year has just been pre-commit.ci bumping version numbers in the pre-commit-config.yaml again and again, and auto-merging it when CI passes. This isn't unique to pre-commit.ci, to be fair, because dependabot has the same issue.


If other people find python-pre-commit to be helpful, then I guess "whatever floats your boat" -- but I am determined to never use it myself unless some major design issues are rethought, and if a project's developer tooling requires it then I guess I won't use that developer tooling and just submit PRs with fingers crossed.

And if I notice commits authored by the bot are prominent in the commit logs, then I'll just walk away. The correct way to handle upgrading versions for CI tooling is to bake the tool versions into e.g. a docker container used for running tests (this is also handy because then you don't spend half an hour installing software on every CI run) and have a scheduled job automatically rebuild that at regular intervals, check that the tests still pass, and deploy a new container. Contributors can just always download the latest version of the tools themselves, and write new code that avoids newly-added lint checks.

**Comment by rgommers** [comment]
> every commit for the last year has just been pre-commit.ci bumping version numbers in the pre-commit-config.yaml again and again, and auto-merging it when CI passes. This isn't unique to pre-commit.ci, to be fair, because dependabot has the same issue.

Thanks for the detailed explanation - I agree with all that, and in particular with the point quoted here.

> The correct way to handle upgrading versions for CI tooling is to bake the tool versions into e.g. a docker container used for running tests (this is also handy because then you don't spend half an hour installing software on every CI run) and have a scheduled job automatically rebuild that at regular intervals, check that the tests still pass, and deploy a new container.

This is also work to maintain, but agreed that's a lot nicer. It would indeed also help with `gfortran`, `openblas`, etc. which are some of our most important dependencies and Python tooling cannot know about.

> I don't think it would hurt to add a pre-commit.yaml in case others want to use it (I'd certainly use it)?

No objection if it's useful to you, but please keep it minimal and applied to the diff in commits from the dev that is using it locally only. If it's again something that wants to "fix" things like single vs. double quotes, that'll just be extra noise.

**Comment by stefanv** [comment]
I think pre-commit should just run the same linter as CI. That should be uncontroversial, and no one is forced to use it just because the configuration is there.
