### ISSUE TITLE
ENH: Provide casting function to sparse arrays

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [scipy/scipy#18918]
### Is your feature request related to a problem? Please describe.

Sorry if this already exists, but I didn't see it.  Most if not all of the sparse [functions](https://docs.scipy.org/doc/scipy/reference/sparse.html) still return sparse matrices.   I have higher level algorithm code that uses matrix-vector products and helper functions that create sparse arrays and matrices.  It would be nice for the higher level code if I could restrict the helper function return values to be sparse arrays.  I currently can't do that because the helper functions use things like `sparse.block_diag()` and `sparse.eye()`.  The consequence for higher level code is that it needs to cast all `todense()` calls inside `np.asarray()`.

Example:
```python
x: np.ndarray
G: sparse.spmatrix
Qinv: sparse.spmatrix
updates: np.ndarray = G @ x
root_Qinv: np.matrix = np.linalg.cholesky(Qinv.todense())
standardized_updates: np.matrix = root_Qinv @ updates

stats.kstest(standardized_updates.flatten(), stats.norm.cdf)
# error because flatten() doesn't work on numpy matrix
```

### Describe the solution you'd like.

```python
def to_sparray(sparse_thing):
    if isinstance(sparse_matrix, scipy.sparse.sparray):
        # Probably needs to be idemptotent for forwards compatibility
        return sparse_thing
   elif isinstance(sparse_thing, scipy.sparse.csr_matrix):
        # convert to csr_array
   # all other cases
```

This would allow me to push all the array-vs-matrix code into the lower level functions, rather than handling among the linear algebra whenever I need a dense array.
### Describe alternatives you've considered.

A) Add a kwarg to allow all sparse matrix creation functions to return a sparse array instead, if possible.  However, this would probably be implemented in a decorator that calls the proposed function.

B) change `spmatrix.todense()` to return an array, not a matrix.  Not sure what backwards compatibility issues this creates, however.

C) Do nothing here.  In user code, continue to use sparse matrices and wrap `np.asarray(sparse_mat.todense())`

### Additional context (e.g. screenshots, GIFs)

I read through https://github.com/scipy/scipy/issues/8162, but didn't see anything about this.

**Comment by dschult** [comment]
There is a fair amount of activity about broadening support for sparse arrays within the library.  This includes a PR about stacking functions and api discussions for the construction functions.  See below.

The `.toarray()` method returns an array. The `A.todense()` method currently returns an array if `A` is a sparse array and a matrix if `A` is a sparse matrix.  Due to backward compatibility issues, the forward moving suggestion is to use `.toarray()`.  

New functions are coming soon with names like `diags_array`, `eye_array`, etc.

There is a biweekly meeting to discuss sparse arrays on the [scientific-python.org calendar](https://scientific-python.org/calendars)

## More links

Issues: 
#18592  Semantics of sparse array creation 
PRs: 
#18862   sparse arrays for hstack, vstack, bmat, block_diag
#18538   Add _array version of diags creation functions

**Comment by tupui** [comment]
Thank you for the detailed report @Jacob-Stevens-Haas!

@dschult is there anything in this issue you need to keep track of or can/should we close it?

**Comment by dschult** [comment]
We can close this issue. 
(I've put these items into the agenda for the meeting this Friday and will track them through that process.)

**Comment by tupui** [comment]
Ok thanks 😊

**Comment by Jacob-Stevens-Haas** [comment]
Great to hear about the support for sparse arrays, & thanks for those links!

**Comment by dschult** [comment]
We are considering adding a method called `to_sparse_array()` to all sparse matrix classes. Doing so would leave the `sparray` interface clean while allowing things like:
```python
if isinstance(sparse_thing, spmatrix):  # or I suppose soemthing like: if hasattr("to_sparray", sparse_thing):
    sparse_thing = sparse_thing.to_sparray()
```
Would this provide the functionality you are looking for @Jacob-Stevens-Haas ?

**Comment by Jacob-Stevens-Haas** [comment]
Yes, thank you :)
