### ISSUE TITLE
Discussion on reducing cirrus CI usage

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#19006]
### Describe your issue.

cirrus-ci is going to be restricting free minutes from Sep1. We are heavy users of this CI service because it offers native linux_aarch64 and macosx_arm64.

This issue continues discussion from #18985 for reducing our usage.

Suggestions so far:
- only make 'nightly' wheels (linux_aarch64 and macosx_arm64) every two weeks instead of every week (or some other reduced frequency).
- Don't regularly test linux_aarch64 or macosx_arm64, we currently do this on every run. Instead rely on the 'nightly' wheel build failing to tell us something is wrong. Alternatively, don't test the wheels when we make them (there's a wheel for each Python version), but perform regular testing on one target.
- for regular testing only test on PR commits, not on merge commits.
- For regular tests only perform a reduced set of tests, e.g. scipy.linalg would make sense.
- add a manual trigger so that maintainers have to press a button to start CI.
- sequence linux + macosx runs in series, if one doesn't pass don't run the next one.
- see if there's a way of triggering cirrus runs if a GHA smoke test succeeds.
- ask for credits for cirrus for FOSS.
- ask a funder (Numfocus) for funds to pay for credits.

It's a shame that we have to go down this path, but cirrus have been open in communication about the issue.

### Reproducing Code Example

```python
n/a
```

### Error message

```shell
n/a
```

### SciPy/NumPy/Python version and system information

```shell
n/a
```

**Comment by andyfaff** [comment]
We would've already gone over the limit in August after two days. Granted, I was doing some CI work, and ran the wheel build several times.

I suspect that the only thing we'll be able to do, whilst keeping under the limit, would be to run the wheel builder every couple of weeks.

**Comment by mdhaber** [comment]
There are tools (like [testmon](https://testmon.org/) and [pytest-run-changed](https://pypi.org/project/pytest-run-changed/)) that are supposed to run only tests that rely on changed code. I'll try out `pytest-run-changed` at some point to see how it does with SciPy (not sure what it will do with compiled code). If other readers would like to try other tools, using one that works could help cut our CI usage.

**Comment by rgommers** [comment]
Where we are at now: it's Aug 10, so a third of the month gone, and we've used 136 credits in total (35 Linux, 101 macOS). So at this rate the bill would be ~$350/month; if we can reduce that further with some of the ideas from Andrew, then I think we're in a decent enough place. We should consider paying if it's less than $200/month or so (which we can get too fairly easily I think), rather than doing a lot of work to reduce it to the level where we stay in the free tier (probably not possible without resorting to QEMU on GHA).



> * only make 'nightly' wheels (linux_aarch64 and macosx_arm64) every two weeks instead of every week (or some other reduced frequency).

We can even turn these off, run them once a month, or produce them only for one agreed-upon Python version. The download stats at https://anaconda.org/scientific-python-nightly-wheels/scipy/files show that only Linux x86-64 sees a lot of usage.

> * Don't regularly test linux_aarch64 or macosx_arm64, we currently do this on every run. Instead rely on the 'nightly' wheel build failing to tell us something is wrong. Alternatively, don't test the wheels when we make them (there's a wheel for each Python version), but perform regular testing on one target.

I'd prefer to keep at least one of these; when touching compiled code or build stuff, an ARM job is important to have.

> * for regular testing only test on PR commits, not on merge commits.

This we should do everywhere, re-running on merge commits is very wasteful and doesn't add anything of value.

> * For regular tests only perform a reduced set of tests, e.g. scipy.linalg would make sense.

I'd prefer not to do that, that loses too much coverage.

> * add a manual trigger so that maintainers have to press a button to start CI.

I'd prefer not to do that either. Unless it's part of a structural overhaul, but that won't get done this month.

> * sequence linux + macosx runs in series, if one doesn't pass don't run the next one.

This seems reasonable; if it's easy to do then let's do it?

> * see if there's a way of triggering cirrus runs if a GHA smoke test succeeds.

Probably difficult I expect, but if it's doable without becoming convoluted then sure why not.

> * ask for credits for cirrus for FOSS.
> 
> * ask a funder (Numfocus) for funds to pay for credits.

I think the cost is too low to do this, nor do I expect it to work well in the long run (xref Travis CI usage). I'll note that we have about $100,000 at https://opencollective.com/scipy (once the backlog of Tidelift funds clears), and using <10% of our regular monthly income for CI costs seems like a good use of those funds.

**Comment by andyfaff** [comment]
@rgommers , you'll have to adjust the cron timings for the nightly wheels on cirrus-ci, I don't have permissions to do that.

#19053 should only run CI on commits to PRs, not on merge commits. It also sequences CI so mac only runs if linux if is successful.

**Comment by rgommers** [comment]
>  you'll have to adjust the cron timings for the nightly wheels on cirrus-ci, I don't have permissions to do that

Here's what it looks like:

<img width="980" alt="image" src="https://github.com/scipy/scipy/assets/98330/4a8e4517-9868-4b82-90ca-d857e37623e1">

`0 0 0 ? * SAT *` is Saturday's at midnight. The `py312` jobs and hence uploads are currently broken due to gh-19036, but that should be resolved soon. For the rest, I think we want perhaps this (once a month): `0 0 12 ? * 7#3`. Or this (every 14 days): `0 0 12 */14 * ?`. Maybe starting with the latter?

**Comment by andyfaff** [comment]
I'm not a crontab expert. I always go to a website to generate them for me. 

I reckon once a month or is probably better at this stage.

**Comment by rgommers** [comment]
Okay, going with `0 0 12 ? * 7#3` then. The next run is then Sat 19 Aug, and once a month on the third Saturday after that.

**Comment by andyfaff** [comment]
Sounds good

**Comment by rgommers** [comment]
It looks like we just crossed some limit that they're starting to enforce (already higher than the advertised free limit):
```
Failed to start an instance: FAILED_PRECONDITION: Monthly free compute limit exceeded
```

**Comment by ilayn** [comment]
@andyfaff @rgommers Do you have any contact with Cirrus CI already? I need some sort of a rough idea of an amount both for SciPy and NumPy (if needed) so that I can also shop around for donation. We can also take it offline

**Comment by rgommers** [comment]
My current best estimate is that the bill will come to $80/month for NumPy and $120/month for SciPy, so that'd be $2400/year for the two projects together. I have made a first payment for NumPy, and everything seems to go smoothly. There's some attempts from other projects to get a discount or more free credits via NumFOCUS, but I'm not sure that that will get anywhere. It would be nice if it did, but if not then I think the amount is reasonable for what they offer.

If you could get a donation to cover those costs, that would be awesome.

**Comment by ilayn** [comment]
Also GitHub Actions have some manual triggers for first time contributors, I'm wondering if we can also do a similar thing for Cirrus jobs.

**Comment by andyfaff** [comment]
- It's possible to do manual triggers for all Cirrus jobs, not sure if it's configurable to only limit to first time users.
- the paid credits seem to be configurable to limit only for maintainers, or everyone.

**Comment by rgommers** [comment]
> the paid credits seem to be configurable to limit only for maintainers

I like this option, probably better than manual triggers. The number of non-maintainers who write architecture-dependent C/C++/Fortran code is pretty small, so this should be okay (I believe it's easy to add a commit from a maintainer to a PR to trigger aarch64/arm64 jobs for those non-maintainers).

**Comment by andyfaff** [comment]
@rgommers, I just deleted the cron entry on cirrus, with the intention of setting a new job with `0 1 1 * *`, “At 01:00 on day-of-month 1.”, but found out that I don't have permission to create cron jobs. Could you recreate it?

name: nightly
branch: main
expression: 0 1 1 * *

**Comment by rgommers** [comment]
Sure, done. Note that the expression was `0 0 1 1 *` to make it monthly, the one above is daily. The UI confirms the next scheduled job is 1 Oct at 1am UTC.

**Comment by rgommers** [comment]
I also noticed a setting _Require approval for builds from users without write permissions_ in the repo settings UI. The docs don't explain how it works exactly, but I enabled it. In case it gives an issue we can undo that, but hopefully it helps.

**Comment by rgommers** [comment]
That approval button thing works exactly as expected, the task remains "pending" and if you click on _details_ next to the CI job it takes you to a Cirrus UI with an Approve button.

I added 50 credits for now, let's see if that gets us to the end of the month.

**Comment by ilayn** [comment]
I submitted the initial request to PR dept. Hope to get an answer in a few weeks.

**Comment by rgommers** [comment]
After ~48 hours we consumed $4.11:

<img width="956" alt="image" src="https://github.com/scipy/scipy/assets/98330/886e7232-16a1-410e-98d1-9455c4ac09da">

**Comment by rgommers** [comment]
We've used $18 in ~20 days so far. And we did the 1.11.3 release in that time, so the consumption has been below what I estimated so far.

**Comment by rgommers** [comment]
Recent activity has been below average as well though; and CI was pretty broken for the last 4-5 days. The estimate probably was still reasonable.

**Comment by andyfaff** [comment]
Once a month for arm nightlies seems as if it's spaced out a bit more than I'd like. Once every two weeks would be nicer, but I'd defer to the budget.

**Comment by rgommers** [comment]
That should fit - let's give it a go I'd say. Updated the cron job to `0 0 0 1/16 * ? *`, so twice a month - keeps a trigger on the 1st of each month.

**Comment by rgommers** [comment]
Yesterday was the first days in ~2.5 months that credits were used. We still had credits, so I assume that we exhausted our free credits for December and Cirrus fixed the problem we had with not using our existing credits. Or did anyone make changes to the config (@andyfaff or @tylerjereddy?).

Here's the log:

<img width="932" alt="image" src="https://github.com/scipy/scipy/assets/98330/c4dffe8f-5037-42e3-852f-4fbcb47c120a">

**Comment by tylerjereddy** [comment]
Here's a quick summary of potentially-related things I did recently, let me know if any are problematic.

1. I bumped our Cirrus CI Linux ARM64 time limit (for wheels only, and only on maintenance branch) to 75 minutes from 60 minutes, because those jobs were consistently timing out in gh-19670. That was just a `yml` file change though, I didn't touch the website or billing settings. Perhaps they have a weird way of displaying what happens when something times out beyond the 1 hr limit?
2. I manually restarted the job that timed out before doing the above, to confirm it was really necessary, but that was just clicking on "restart failed jobs" in GitHub interface.

Incidentally, are you getting properly reimbursed for the Cirrus charges?

**Comment by rgommers** [comment]
Thanks Tyler. Those actions all sound perfectly fine.

> Incidentally, are you getting properly reimbursed for the Cirrus charges?

Not just yet, but that's because I've bunched a few payments before attempting to ask for reimbursement. I don't expect problems beyond a delay in getting reimbursed here. That said, at some point I'll look into getting a separate payment card for this to streamline things.

**Comment by andyfaff** [comment]
I've not changed any CI config settings. The cirrus linux_aarch64 job was specifically designed to use a small amount of resources (which are proportional to cost), that's why it takes longer. It was fairly shoehorned in to fit within an hour.

**Comment by rgommers** [comment]
Thanks. Then it looks indeed like there's nothing we did; credit limits and how they're handled changed on the Cirrus side. Probably for the better - it's working right now at least.

**Comment by lucascolley** [comment]
Where are we at now? Can this be closed, or are we still concerned with reducing usage further?

**Comment by andyfaff** [comment]
I think the CI files are pretty minimal now. I'd say we close and revisit if we need to reduce any further.

**Comment by rgommers** [comment]
Update: the burn has been $25-$30/month for the last four months, which is minimal indeed. I just bought another $150 worth of credits, so we should be good for another half a year at this rate.

<img width="949" alt="image" src="https://github.com/user-attachments/assets/dc998fd9-b519-4096-aa92-e5987bc2f058">
