### ISSUE TITLE
DOC: error in scipy.integrate.DOP853

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#19008]
### Issue with current documentation:

This doesn't make sense:

`Note that this is not a literate translation`

I suppose it was meant to be:

`Note that this is not a literal translation`

**Comment by keithbriggs** [comment]
This bit isn't too good either:

`Here rtol controls a relative accuracy (number of correct digits), while atol controls absolute accuracy (number of correct decimal places).`

For most people, "digits" and "decimal places" are the same thing.

**Comment by j-bowhay** [comment]
PR welcome for the doc fix although please sure be sure to skip the appropriate CI jobs by adding `[skip actions] [skip cirrus]` at the end of the commit message.

> This bit isn't too good either:
> 
> `Here rtol controls a relative accuracy (number of correct digits), while atol controls absolute accuracy (number of correct decimal places).`
> 
> For most people, "digits" and "decimal places" are the same thing.

I personally think this is fine, in numerical analysis digits tend to refer to significant figures rather than decimal places so this description is correct.
