### ISSUE TITLE
BUG: mesonpy embeds random path in .pyx files

### ISSUE THREAD

**Issue by bmwiedemann** [scipy/scipy#19101]
### Describe your issue.

While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that
our `python-scipy` 1.11.1 package varies between builds. One of the reasons is that a random mesonpy path gets embedded in `cython_special.pyx`, `_ufuncs_cxx.pyx` and `_ufuncs.pyx`

### Reproducing Code Example

```python
build it twice
```

### Error message

```shell
+++ /usr/lib64/python3.9/site-packages/scipy/special/cython_special.pyx     2023-07-27 00:00:00.000000000 +0000
@@ -1088,50 +1088,50 @@
 from ._agm cimport agm as _func_agm
 ctypedef double _proto_agm_t(double, double) noexcept nogil
 cdef _proto_agm_t *_proto_agm_t_var = &_func_agm
-cdef extern from r"/home/abuild/rpmbuild/BUILD/scipy-1.11.1/.mesonpy-nb_0k4ap/build/scipy/special/_ufuncs_defs.h":
+cdef extern from r"/home/abuild/rpmbuild/BUILD/scipy-1.11.1/.mesonpy-il1v1fcx/build/scipy/special/_ufuncs_defs.h":
     cdef npy_int _func_airy_wrap "airy_wrap"(npy_double, npy_double *, npy_double *, npy_double *, npy_double *)nogil
-cdef extern from r"/home/abuild/rpmbuild/BUILD/scipy-1.11.1/.mesonpy-nb_0k4ap/build/scipy/special/_ufuncs_defs.h":
+cdef extern from r"/home/abuild/rpmbuild/BUILD/scipy-1.11.1/.mesonpy-il1v1fcx/build/scipy/special/_ufuncs_defs.h":
```

### SciPy/NumPy/Python version and system information

```shell
1.11.1 1.25.2 3.11.4
```

**Comment by rgommers** [comment]
Thank you for the report @bmwiedemann. I agree that that can be considered a bug.

The issue here stems from this line in `scipy/special/_generate_pyx.py`:
```python
defs.append(f'cdef extern from r"{proto_h_filename}":')
```
where `proto_h_filename` is an absolute path. Given that meson-python creates a tmpdir, absolute paths in installed files are no good. 

However, the more desirable fix here is to not install this header at all, since we don't need it in the installed package. For why we currently install it, see: https://github.com/scipy/scipy/blob/f8036bc210d95365cd3a9ac44462ad0640cad9a1/scipy/special/meson.build#L287-L291

**Comment by rgommers** [comment]
In this case, we should be able to change `_generate_pyx.py` to use a relative path though, since the referenced header is located right next to the `.pyx` file. So that's the easier fix here.

**Comment by rgommers** [comment]
There's a bunch of other code gen scripts with `cdef extern from`, but the ones I checked all used relative paths.
