### ISSUE TITLE
Contradiction in `pyproject.toml` requirements?

### ISSUE THREAD

**Issue by isosphere** [scipy/scipy#19189]
These lines:
https://github.com/scipy/scipy/blob/686422c4f0a71be1b4258309590fd3e9de102e18/pyproject.toml#L34-L35

Against this line:
https://github.com/scipy/scipy/blob/686422c4f0a71be1b4258309590fd3e9de102e18/pyproject.toml#L29

Appear to contradict. At least, the poetry solution compiler thinks so: https://github.com/python-poetry/poetry/issues/8409#issuecomment-1707168371

Hypothetically if someone were running Windows on loongarch64, it would imply two versions.

Should the former exclude the latter, i.e. with: `platform_machine!='loongarch64'` as is done in the lines that follow?

**Comment by rgommers** [comment]
That may indeed technically be a bug. Of course there's no such thing as Windows on loongarch, so Poetry is being slightly picky here I think, but if it wants to do that it can. If there requirements were easy to test for such hypothetical situation, we'd not cause this problem.

We should solve this for the next release. We anyway have to update all these requirements to deal with NumPy 2.0. That can't be done right now though, it'll have to wait a few months. This shouldn't matter for building from source, so that seems fine to me.

**Comment by rgommers** [comment]
Fixed by gh-19550, will land in `1.11.4`.
