### ISSUE TITLE
TST: skip reason incorrect in some cases, related to array API infra apparently

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#19190]
While looking over gh-19184, I tried running the test on a machine with sufficient memory on latest `main`:

`python dev.py test -v -j 32 -- -k "test_concatenate_int32_overflow" -rsx`

`SKIPPED [1] scipy/_lib/tests/test_array_api.py:12: Array API test; set environment variable SCIPY_ARRAY_API=1 to run it`

If I remove the `slow` marker:

```diff
--- a/scipy/sparse/tests/test_construct.py
+++ b/scipy/sparse/tests/test_construct.py
@@ -530,7 +530,6 @@ class TestConstructUtils:
         assert isinstance(bmat([[Gm.tocsc(), Gm]], format="csr"), spmatrix)
         assert isinstance(bmat([[Gm, Gm]], format="csc"), spmatrix)
 
-    @pytest.mark.slow
     @pytest.mark.xfail_on_32bit("Can't create large array for test")
     def test_concatenate_int32_overflow(self):
         """ test for indptr overflow when concatenating matrices """
```

then I can correctly run the test/reproduce the reason for the above PR to exist.

Alternatively, instead of the patch, one can do:

`SCIPY_ARRAY_API=1 python dev.py test -m full -v -j 32 -- -k "test_concatenate_int32_overflow"`, but I don't think that should be needed at this time.

I'm not sure this is particularly serious, at first glance it is just the skip message that is a bit misleading, but would have to think about it more.

**Comment by lucascolley** [comment]
I reproduce the unexpected skip message with your command, but 
```
python dev.py test -v -t scipy/sparse/tests/test_construct.py::TestConstructUtils::test_concatenate_int32_overflow -- -rsx
```
outputs just `1 deselected in 0.10s`, which I think is the expected output for `@pytest.mark.slow`.

Adding `-m full` returns `SKIPPED [1] scipy/_lib/_testutils.py:216: 30000 MB memory required, but 10870.157312 MB available`, also as expected.

So it looks like the problem is specifically how https://github.com/scipy/scipy/blob/838a4e0df5b3f18267e5daa1311a842c3f6ef0b7/scipy/_lib/tests/test_array_api.py#L11-L15 is interacting with `-- -k`.
