### ISSUE TITLE
Why do we need to guarantee q1>=q0 before for loop in Secant method?

### ISSUE THREAD

**Issue by DHPBUAA** [scipy/scipy#19248]
```
        if abs(q1) < abs(q0):
            p0, p1, q0, q1 = p1, p0, q1, q0
        for itr in range(maxiter):
            if q1 == q0:
                if p1 != p0:
                    msg = "Tolerance of %s reached." % (p1 - p0)
                    if disp:
                        msg += (
                            " Failed to converge after %d iterations, value is %s."
                            % (itr + 1, p1))
                        raise RuntimeError(msg)
                    warnings.warn(msg, RuntimeWarning)
                p = (p1 + p0) / 2.0
                return _results_select(
                    full_output, (p, funcalls, itr + 1, _ECONVERGED))
            else:
                if abs(q1) > abs(q0):
                    p = (-q0 / q1 * p1 + p0) / (1 - q0 / q1)
                else:
                    p = (-q1 / q0 * p0 + p1) / (1 - q1 / q0)
            if np.isclose(p, p1, rtol=rtol, atol=tol):
                return _results_select(
                    full_output, (p, funcalls, itr + 1, _ECONVERGED))
            p0, q0 = p1, q1
            p1 = p
            q1 = func(p1, *args)
            funcalls += 1
```

**Comment by mdhaber** [comment]
This forum is primarily for bug reports and feature requests. Please consider posting your question on stack overflow instead or rephrasing with all requested details.

**Comment by ztjona** [comment]
[The lines 360-361](https://github.com/scipy/scipy/blob/44e4ebaac992fde33f04638b99629d23973cb9b2/scipy/optimize/_zeros_py.py#L360C10-L361C16) interchange $p_0$ and $p_1$ to guarantee that $abs(q_1) \ge abs(q_0)$ before the for loop. But inside the for loop [lines 376-379](https://github.com/scipy/scipy/blob/44e4ebaac992fde33f04638b99629d23973cb9b2/scipy/optimize/_zeros_py.py#L376C17-L379C61) the behaviour is the opposite and interchange $p_0$ and $p_1$ to satisfy that $q_1$ is closer to 0. 

As discussed in [this stackoverflow thread](https://stackoverflow.com/questions/78545774/why-scipy-checks-absq1-absq0-before-for-loop-in-secant-method?noredirect=1#comment138476160_78545774), the behavior of lines 360-361 seems like a bug, but it does not affect in anything, because the result is recalculated inside the for loop. 

Although it is not severe, I consider it might cause further confussion, so I would fix it if needed.
