### ISSUE TITLE
ENH: Implemenation of other solvers from ODEPACK in ```scipy.integrate```

### ISSUE THREAD

**Issue by kmaitreys** [scipy/scipy#19301]
### Is your feature request related to a problem? Please describe.

Currently ```scipy.integrate``` implements different solvers through its ```ode``` generic interface class. Using ```ode```, one can use solvers like vode/zvode, lsoda, dopr5 etc. That is, only one solver from ODEPACK (that is lsoda) is implemented in ```scipy```. However, ODEPACK contains many more like lsode, lsodes, lsodar, lsodpk, lsodkr (for explicit systems) and lsodi, lsoibt, lsodis (detailed documentation of each of these can be found on the [netlib website](https://www.netlib.org/odepack/opkd-sum)). 

For my work, I want to use lsodes specifically because it uses some extra optimization for sparse Jacobians. lsoda does support banded jacobians but there have been issues which hint at some bad implementation (might be ```f2py``` thing, but I am not quite sure (#10793 & #10864). I am quite surprised that these possible bugs have been open issues with zero to none discussion for 4+ years now.

### Describe the solution you'd like.

This issue is basically to gauge community thoughts on adding more solvers from ODEPACK, and also perhaps fixing the issues (if any) that lsoda might have. I would also like to know why lsoda was chosen specifically, instead of the more general lsodes.

### Describe alternatives you've considered.

I looked into an old library that Hans Petter Langtangen wrote called [odespy](https://github.com/hplgit/odespy) which aimed to do exactly this. It adapted a lot of solvers from ODEPACK and constructed user-friendly Python interfaces to use them, and lsodes was one of them. Unfortunately, Hans passed away in late 2016 after battling with cancer (RIP), and virtually no development happened of that project after it so it remains in Python 2.7. No one has taken the ownership of that repository and the few forks of it have been very lukewarm attempts at trying to keep it alive.

In all honesty, I would like to change that. I am open to be a maintainer of a new fork of ```odespy``` which can become the new main repo for the project. But that's a whole other thing, I will have to contact Hans' colleagues and/or students and then I will see if I can get any permissions for it and so on.

But first, I would like to have discussion with the SciPy community about this. Because, I think ```odespy``` was (is) a great library. It should not die. So if it possible to integrate parts of it into ```scipy.integrate```, I believe it will be in benefit of the whole community as a whole. Also this issue given a chance to look back at those open issues that are currently in the implementation of lsoda as well (I would really like if readers of this issue also go through them, a special thanks to @MatthewFlamm for finding them).

**Comment by rgommers** [comment]
Hi @kmaitreys, thanks for opening this discussion. As for why LSODA was wrapped first/only, I don't know - that's from the earliest times of SciPy. Maybe @rkern remembers? It may just be a case of all-round good performance and familiarily (see, e.g., [Benchmarking of numerical integration methods for ODE models of biological systems - Scientific Reports (2021)](https://www.nature.com/articles/s41598-021-82196-2)).

Why bugs went unsolved: basically because all Fortran 77 is very hard to maintain, there are few maintainers who know Fortran well and even fewer who enjoy working on Fortran 77 (that number is likely to be 0 actually). We'd really like to get rid of all F77 code - see gh-18566. Most of this code is of really poor quality, and that goes for ODEPACK too I think (and the README of `odespy` says _"There have been some unidentified problems with running this solver (segmentation fault)."_ for a reason).

> Because, I think `odespy` was (is) a great library. It should not die. So if it possible to integrate parts of it into `scipy.integrate`, I believe it will be in benefit of the whole community as a whole.

I think new solvers that add capabilities not yet present in `scipy.integrate` are very welcome. However, it would be best to translate the solver into Python/Cython/C/C++ first.

**Comment by kmaitreys** [comment]
Thanks for the reply @rgommers and telling me about why the bugs still exist. Difficulties in handling of F77 legacy code is completely understandable. 

> I think new solvers that add capabilities not yet present in scipy.integrate are very welcome. However, it would be best to translate the solver into Python/Cython/C/C++ first.

I agree, but I am not sure if all the solvers from ODEPACK have some rewrites of them in other than F77 (what about F90/95 btw? they are fairly modern and simple languages to handle?). I know that a C++ LSODA implementation [exists](https://github.com/dilawar/libsoda-cxx), but what about others? I tried finding more but didn't land up with anything of substance. If nothing, implementing this C++ implementation could be a good start, especially since ```mrgsolve``` have done it, and they think it was [good](https://github.com/metrumresearchgroup/mrgsolve/issues/504).

**Comment by j-bowhay** [comment]
https://www.stochasticlifestyle.com/comparison-differential-equation-solver-suites-matlab-r-julia-python-c-fortran/

I think this a fairly nice comparison of the current landscape. To me at least, [Sundials](https://computation.llnl.gov/projects/sundials)‘ CVODE seems like a more appealing prospect than wrapping LSODE

**Comment by kmaitreys** [comment]
Thanks for the reply @j-bowhay. I researched into SUNDIALS's suite of solvers and how it can be thought as a successor to ODEPACK. Now they are two options, I write my own wrapper to SUNDIALS's ```CVODE``` or I use a wrapper which has already been written. One library I found was ```scikits.odes```, but unofrtunately it only supports till Python 3.9 (my project currently is Python 3.10+).

Do you have some more suggestions?

**Comment by j-bowhay** [comment]
There is https://github.com/bjodah/pycvodes although I do not have any experience with it. For my personal use (and this pains me to say as a SciPy maintainer) I usually use [DifferentialEquations.jl](https://docs.sciml.ai/DiffEqDocs/stable/). I would love to see more modern solvers in SciPy to close the gap with the Julia ecosystem however this isn't something I have the capacity to implement.

**Comment by kmaitreys** [comment]
Yeah I have looked into Julia's library. The problem is, my RHS function and Jacobian function are in Python, a bit involved, and JIT-compiled through Numba. So I am not sure if I will be able to call Julia from Python for my solver. But if you have any suggestions, we can discuss it (although at some other platform, because that will not be relevant to this scipy specific issue)

**Comment by kmaitreys** [comment]
In future, if anyone stumbles on this thread, ```pycvodes``` will not work with Numba due to some issues which I believe originate from Cython (or whatever Python-C/C++ mechanism which uses ```memory_view``` instead of arrays for internal time step calculations).

**Comment by j-bowhay** [comment]
The other wish list item for me would be for the scipy solvers to take a low-level callable. Any wrapped solver written in compiled code will lose most of its speed if it has to keep calling back to python land for the rhs function.

**Comment by Patol75** [comment]
@j-bowhay Would that [LSODA implementation](https://github.com/Nicholaswogan/numbalsoda) be a good proof-of-concept of what you mentioned?

**Comment by kmaitreys** [comment]
@rgommers Considering your last insight on the state of Fortran dependencies in `scipy`, I would think that you (and the greater `scipy` community) will not be thrilled to add one more method from ODEPACK to `scipy.integrate`? I actually want to add `lsodes` as an additional method for systems with arbitrary sparse structure and recently started the implementation on my fork. Systems like large chemical network solving chemical kinetics are stiff and pre-existing codes have overwhelmingly relied on `DLSODES` and I would love that functionality as an option as well.

I would love to raise a PR after I am done with implementing it, but I have a feeling it will not be well received. In that scenario, do you have anything that would help if I wanted to publish my implementation on PyPI perhaps, in the form of a very scipy like wrapper of `DLSODES`? Maybe some documentation on how to interface with Fortran/C code using `f2py` and so on. I think for an implementation in `scipy` it would not be much difficult but I am unsure about how will I hook up any external dependencies in a standalone package.

**Comment by rgommers** [comment]
Hi @kmaitreys, I suspect you are right - we're trying hard to get rid of Fortran 77, so we'd much prefer to not add more F77 code at this point. The functionality sounds useful, but ODEPACK code as it stands isn't maintainable for us.
 
> I think for an implementation in `scipy` it would not be much difficult but I am unsure about how will I hook up any external dependencies in a standalone package.

I had a closer look, and it's a bit of a pain because of the dependency on LAPACK. That makes building wheels for distribution on PyPI hard - it's issue number one for SciPy wheels. There are several potential paths to take:

1. Keep as F77 code, and distribute it on conda-forge only, plus sdist on PyPI, (probably lowest-effort right now, dealing with LAPACK in conda-forge is way easier than for PyPI).
2. Keep as F77 code, and distribute on PyPI in the same way as SciPy does (hard packaging-wise)
3. Translate code to C++/C/Cython and contribute it to SciPy after all (not sure of effort, but squashes the distribution problem completely).

I really can't recommend (2) unfortunately. We're vendoring OpenBLAS and gfortran runtime libraries, which takes a lot of effort - and while you could copy the approach we take for NumPy/SciPy, it's fragile and the machinery for it (https://github.com/MacPython/openblas-libs + CI scripts in this repo) is undergoing surgery right now.

**Comment by kmaitreys** [comment]
Thank you so much for replying, Ralf. I really appreciate the directions you have given. I will look into them. Might be difficult at the moment for me as it does sound a bit involved but some day, I think it would be a nice standalone utility for people looking for such solvers.

Cheers!

**Comment by kmaitreys** [comment]
Hi @rgommers , I ran out of options and ended up building my own wrapper to `DLSODES`. Scipy's signature files and a lot of stuff from `odespy` helped a lot. I will be closing this issue with the [link](https://github.com/kmaitreys/pylsodes) to my wrapper. Thanks to everyone for guiding me in the right direction and their suggestions.

**Comment by rgommers** [comment]
Thanks for sharing @kmaitreys!
