### ISSUE TITLE
RFC: seeking thoughts on rewriting special functions written in Cython into C++

### ISSUE THREAD

**Issue by steppi** [scipy/scipy#19404]
At the moment we have a number of functions in `special` where we have provided our own implementation using Cython. I think Cython was chosen for its ergonomics and because it may be easier to maintain for developers used to Python. Its use comes with some downsides though, and using C++ brings upsides.

@izaid has pointed out that if we can supply C++ implementations in header files, than other array computing libraries such as CuPy, PyTorch, or Jax could potentially use these implementations. https://github.com/scipy/scipy/pull/19023#issuecomment-1689050946. @mdhaber, izaid and myself have been discussing proposing an array API extension for special functions, and moving to C++ could help facilitate that. 

Lack of interoperability affects us internally too. Because of how the build system works currently for special functions, the compiled kernels for special functions written in Cython can not be called from compiled kernels written in C or C++. This is blocking https://github.com/scipy/scipy/pull/19287 at the moment, cc @rlucas7.

Since the special function infrastructure already handles generating the ufunc boilerplate on the NumPy C API side, we don't get the primary benefit of using Cython in special. Where Cython really shines is in writing extensions without needing to work out the somewhat tedious C API boilerplate.

@izaid has generously offered to help review PRs I submit for rewriting special functions from Cython into C++, and I would be happy to review any PRs he submits. We would prioritize functions that we think should be included in an array API extension.

My thought here is that we should try to write these in the style of Boost special functions, making use of Boost's fundamental building blocks when possible, with the idea that perhaps we could eventually contribute these upstream to Boost. At the moment, the biggest thing missing from Boost is complex support for special functions where that is relevant. cc @mborland. This is the approach @tirthasheshpatel and I are looking at for our SDG to work on special infrastructure; making use of Boost's internal building blocks, and writing our own building blocks in a similar style if needed.

As part of this, we would also avoid writing any new special functions in Cython, recommending instead C++ in the development docs.

**Comment by ilayn** [comment]
As long as we don't deal with the nasty bits of C++, and I'm not implying a C++ style guide like [Google](https://google.github.io/styleguide/cppguide.html) or Spotify, I think this would be really nice. Is there any specific reason for not choosing plain C? 

With C++, a typical situation is that the project becomes a grenade-driven development (GDD) waiting for us in the build stage. Especially, if MSVC will be involved, I'd be terrified to use complex numbers (all past traumas) but I'm no C++ expert by any measure maybe things are much better now with the later versions.

One definite advantage of Cython is memoryviews and NumPy interplay otherwise the usual footgun shananigans apply. But it becomes harder to detect hence there is some reduction in the available maintainer resource but nevertheless the interplay with other package maintainers might make it more robust over time.

**Comment by izaid** [comment]
I think @steppi hit all the right points here! But, to be 100% clear, let me just emphasize that the idea is to write only the actual implementations of the scalar functions themselves in C++. And it's C++ only in the simplest sense, nothing fancy and no complicated features, just typed arguments. Importantly though, they do need to be headers so as to support JITs (like for CuPy). This can then be exposed to other libraries as something like `sp.special.get_include()`, analogous to `np.get_include()`.

There is no need to touch the Python C API or anything like that. How the special functions become ufuncs is a choice for SciPy, I know you have various ways you already to do that. One could use the NumPy machinery for ufuncs, or still wrap these with Cython, whatever. That's a choice for SciPy and is an independent thing. Other array libraries have their own ways to create ufuncs from C++ source, for instance CuPy's ElementwiseKernel (https://docs.cupy.dev/en/stable/reference/generated/cupy.ElementwiseKernel.html).

The Array API and getting special functions onto all devices is the motivation for us, but I think this is sort of a complementary problem that should be solved independently. I think a lot of people now look to the special functions in SciPy as some sort of reference implementation, and this is also a way to spruce it up and move in that direction.

**Comment by ilayn** [comment]
No objection from my side but just curiosity and nice to learn about it. 

The reason I mentioned these are the compiler differences and the Microsoft's (maybe by-now-outdated) notoriety of nonconforming implementations. Windows platform is always a major pain and I'm hoping that we stay away from stuff such as `np.complex256/complex128/complex64` vs. `long double complex`/`double complex` conversion. If the our C++ folks are OK with it then please ignore my comments :)

**Comment by steppi** [comment]
I think you've covered everything @izaid, but would just like to mention I share your distrust of the more complicated parts of C++ @ilayn and emphatically support keeping to only a minimal subset of the language.

**Comment by mborland** [comment]
It makes sense to me to expand upon the building blocks that have existed for quite a long time in Boost.Math as opposed to starting your own work in say C. @mdhaber, @WarrenWeckesser, and @mckib2 have been using Boost.Math in scipy.stats so we have worked out a number of bugs that impact Scipy. You would also not be the first one to use Boost.Math to provide special functions. As of 2-3 years ago the MSVC STL ships our implementations for everything listed here: https://en.cppreference.com/w/cpp/numeric/special_functions.

For the concerns related to non-conformance we test in CI GCC 5-13, Clang 5-13, and MSVC 14.0 - 14.3. I expect you will have very few issues with doing math at the C++14 language standard. @jzmaddock and I can assist as we have been.

To simplify things a little bit wouldn't a fair number of the Boost.Math special functions already be available through the Boost.unfucs machinery used in scipy.stats? Please correct me if I am wrong @mckib2.

**Comment by izaid** [comment]
@mborland Indeed, I certainly wouldn't want to duplicate tons of effort. A question though: what's the current state of things with regard to CUDA in Boost.Math? Has anyone wanted or tried to turn Boost.Math functions into `__device__` functions that can be called in a CUDA kernel? The other thing is that NVCC in JIT mode is very particular and restrictive on include files.

This is potentially the issue using the Boost implementations for what is described here.

**Comment by mborland** [comment]
> @mborland Indeed, I certainly wouldn't want to duplicate tons of effort. A question though: what's the current state of things with regard to CUDA in Boost.Math? Has anyone wanted or tried to turn Boost.Math functions into `__device__` functions that can be called in a CUDA kernel? The other thing is that NVCC in JIT mode is very particular and restrictive on include files.
> 
> 
> 
> This is potentially the issue using the Boost implementations for what is described here. 

We have an ancient open PR to add support: https://github.com/boostorg/math/pull/127. There's been no demand signal for it so that's likely why it wasn't pursued further.

**Comment by izaid** [comment]
Thanks @mborland! In that case, what might make sense here what @steppi described. We use Boost where we can, but where can't - either for complex arguments or device (CUDA) support - we do it in SciPy with the intention of Boost hopefully adopting it. And eventually Boost may even push it into the C++ standard, as you did with the many of those special functions.

**Comment by jzmaddock** [comment]
> We have an ancient open PR to add support: https://github.com/boostorg/math/pull/127. There's been no demand signal for it so that's likely why it wasn't pursued further.

Right, I experimented with it.  At the time the one CUDA device I had available to me, didn't show any performance gains doing things this way, rather than using (the much faster) CPU serially.  And now my current laptop has no CUDA support at all :(

Most of the changes are relatively trivial: just adding markup to the function definitions so that they are usable on CUDA devices.  BTW it's a right pain that CUDA needs special function markup with non-standard C++ just to compile for the device.

Were there particular functions that you wanted to CUDA-enable?

As for complex special functions, we reasonably often get requests for complex Bessel functions (for example), but I've deliberately avoided them as most of the evaluation methods look rather simplistic to me with no investigation of where they work and where they explode (numerically), plus the complex domain is a huge space to explore... I'm not even sure it's possible to devise comprehensive tests over such a large space?  But for sure folks do need them.

**Comment by lesshaste** [comment]
> @ilayn Thanks for the helpful comments! The idea is simple C++, that's it. It will certainly look pretty close to C. It could be made to work with C, but a few reasons why we may want C++ are:
> 
> * C does not support simple overloading on argument types, C++ does. This is relevant for many of the special functions where the implementation differs if an argument is an integer or a float or a complex number (Bessel functions, polynomials, etc).
> * C++ has now added a lot of very important special functions into the standard library: https://en.cppreference.com/w/cpp/numeric/special_functions. We'd probably prefer to make use of those when / where available?
> * Built-in complex number support.

Just a small point. C has complex number support too.

**Comment by izaid** [comment]
@jzmaddock Totally agree, things would be a lot easier if no special markup was needed for CUDA. But, as you said, it actually is quite easy! Something like the following is all we need here.

Put this in a common header file:

```
#ifdef __CUDACC__
#define SPY_SPECFUN __host__ __device__
#else
#define SPY_SPECFUN
#endif
```

And for each function going forward define it as:

```
SPY_SPECFUN RetType my_specfun(ArgType0 arg0, ArgType1 arg1, ...) {
   // implementation
}
```

Just speaking for what I personally have needed, among other things I've ended up writing implementations of the Bessel functions (both cylindrical and spherical), spherical harmonics, and various orthogonal polynomials for CUDA over the years. For many other functions, I've copied implementations from Boost, the C++ standard library, Slatec, and SciPy where needed, then did something similar to the SPY_SPECFUN above. More widely, you can see that CuPy's special includes a lot of what is in SciPy: https://docs.cupy.dev/en/stable/reference/scipy_special.html. Am sure the other array libraries would like to not reimplement all of that.

Great that you've played around with the Boost PR! Since what we are talking about is elementwise computation, it really should be faster but you might not see that unless you are calling the function on arrays of a sufficient size (1000?). It's just like calling `sin(x)` on your CUDA array `x`, but with a much more complicated computation per element.

@lesshaste You are correct, of course. I find C complex numbers difficult to use, but they do exist.

**Comment by ev-br** [comment]
Would of course be awesome if we could delegate to Boost as much as we can!

> if we can supply C++ implementations in header files, than other array computing libraries such as CuPy, PyTorch, or Jax could potentially use these implementations

So this would bring us to the realm of ABI compat, which we so far managed to avoid even with `cython_{blas,lapack}.pxd`  being public. Would be great to hash out implications of that and formulate what exactly SciPy guarantees. Also would be great to have an okay from the build/RM folks, @rgommers, @tylerjereddy @h-vetinari  .

**Comment by mborland** [comment]
> Would of course be awesome if we could delegate to Boost as much as we can!
> 
> > if we can supply C++ implementations in header files, than other array computing libraries such as CuPy, PyTorch, or Jax could potentially use these implementations
> 
> So this would bring us to the realm of ABI compat, which we so far managed to avoid even with `cython_{blas,lapack}.pxd` being public. Would be great to hash out implications of that and formulate what exactly SciPy guarantees. Also would be great to have an okay from the build/RM folks, @rgommers, @tylerjereddy @h-vetinari .

For reference Boost.Math offers no ABI stability guarantees, and I am not aware of any complaints about that.

**Comment by h-vetinari** [comment]
> the compiled kernels for special functions written in Cython can not be called from compiled kernels written in C or C++.

This statement confuses me. Cython functions are regular C functions, and C++ should easily be able to call those. I don't know if there are more specific bits in the cython documentation, but the [following](https://docs.cython.org/en/latest/src/tutorial/embedding.html) looks relevant -- `say_hello_from_python` is defined in Cython and then called from an external C program. Perhaps @da-woods or @matusvalo can correct me if I'm saying something wrong.

Pythran can also [generate](https://pythran.readthedocs.io/en/latest/MANUAL.html#capsule-corp) generic C++ code, but I see you ran into some [issues](https://github.com/serge-sans-paille/pythran/issues/2141) with that already.

> Just a small point. C has complex number support too.

Except in MSVC. Well, they do actually have all the relevant functions, but they operate on different types (long [story](https://learn.microsoft.com/en-us/cpp/c-runtime-library/complex-math-support?view=msvc-170)). It makes no sense to me, but it hasn't changed for a long time (go upvote [this](https://developercommunity.visualstudio.com/t/714008) if you have a MSFT account).

___________

In general, I think _using_ C++ code in scipy is perfectly fine. Exporting C++ functions (however simple we set out to keep them) is a whole different ballpark. I'm not saying it's impossible or not worth it, but it opens up a whole new - and complicated - interface we'd have to take care of.

**Comment by rgommers** [comment]
The `cython_special` extension module is only usable from Cython - we ship the relevant `.pxd` Cython headers for that. They aren't really usable from C/C++, since we don't install complete headers. We do happen to install `_ufuncs_defs.h`/`_ufuncs_cxx_defs.h` more or less by accident, but those contain (a) `npy_double` & co types rather than C types, and (b) `#include` statements to other header files that we do not install.

> but the [following](https://docs.cython.org/en/latest/src/tutorial/embedding.html) looks relevant -- `say_hello_from_python` is defined in Cython and then called from an external C program.

That does a `PyImport_ImportModule("embedded")` type thing that other projects aren't going to want to deal with I'm sure.



> In general, I think _using_ C++ code in scipy is perfectly fine.

Agreed - using as in "I'm copying this stuff over".

> Exporting C++ functions (however simple we set out to keep them) is a whole different ballpark. I'm not saying it's impossible or not worth it, but it opens up a whole new - and complicated - interface we'd have to take care of.

Yes, that's a separate discussion from whether kernel can be (re)written in C++. 

> So this would bring us to the realm of ABI compat

There's no ABI involved here - the proposal touched on shipping as headers, not as an installed shared library.

> to be 100% clear, let me just emphasize that the idea is to write only the actual implementations of the scalar functions themselves in C++. 

This seems perfectly fine to me. And I agree that C++ is a good / the best choice here.

**Comment by rgommers** [comment]
> This can then be exposed to other libraries as something like `sp.special.get_include()`, analogous to `np.get_include()`.

This "expose as headers" part seems like a second or third step. It would require some careful thought about what can be exposed and how we'd deal with API stability guarantees. Re the mechanism, I still have it on my TODO list to implement pkg-config and a `numpy-config` tool support for dependency detection, because `get_include()` is problematic. So we'd want to go straight there for SciPy, rather than adding any `get_include()` function.

**Comment by jzmaddock** [comment]
> For reference Boost.Math offers no ABI stability guarantees, and I am not aware of any complaints about that.

Indeed.  However, the special functions are just that - functions - so their ABI and API (which we do keep stable) are effectively one and the same.

BTW If you wanted to be sure of a stable ABI then wrapping them in a thin `extern "C"` function and exporting that is trivial, and is of course then language neutral as just about anything will import those.  That's what we do for the TR1 special functions, and likewise what MSVC does when it uses and re-exports our code for their std math special functions.  I wouldn't even contemplate exporting a template instance - that was lies madness! ;)

There is one caveat to the above: there are some functions which are only really super fast if they are expanded inline - an example would be the Elliptic Integral K: I recently went to some lengths to implement a new "faster" method only to discover that the performance improvement was completely swallowed up by the cost of a function call, so then I had to jump through all kinds of hoops to ensure there was nothing in there that would inhibit inline expansion.  And BTW that is one function which apparently benefits from being evaluated on massively parallel hardware for some physics (orbital?) calculations.  The benefit would likely only be seen though, if you can inject the C++ code inline right into the main CUDA procedure.

**Comment by tylerjereddy** [comment]
> would be great to have an okay from the build/RM folks

To keep it short, not a fan of C++ (to say the least) but happy to support whatever delivers the greatest value to our ecosystem.

**Comment by lorentzenchr** [comment]
I don‘t know if it’s a good idea to use (part of) scipy as C/C++ lib. If there is a need of several projects for a common C/C++ lib of special functions, isn’t it better to create a new project or extend existing ones like boost?

Another possibility would be to make scipy sf array api compatible. Nanobind might be a possibility, see https://nanobind.readthedocs.io/en/latest/ndarray.html.

**Comment by matusvalo** [comment]
> Perhaps @da-woods or @matusvalo can correct me if I'm saying something wrong.

I did not read the whole thread hence I don't know fully the background. 

Cython allows calling `cdef` functions from C when declared as `api`/`public`:

https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#using-cython-declarations-from-c

When you compile .pyx file containing `api`/`public` function, cython will generate also C header file.

But not sure if this is useful for you or not. I think this is the only reasonable way how to call cython functions from C. If this does not fit you, you will need to use C/C++

**Comment by da-woods** [comment]
Just commenting here because I was tagged and offering a few observations (no real conclusions):

There were a few comments about complex and MSVC - I think they're mostly related to C (where it does something very non-standard). I think for C++ it follows the standard. Recent MSVC has pretty good conformance with the C++ standard in my experience.

----------------------

> Since the special function infrastructure already handles generating the ufunc boilerplate on the NumPy C API side, we don't get the primary benefit of using Cython in special. Where Cython really shines is in writing extensions without needing to work out the somewhat tedious C API boilerplate.

Cython can generate ufunc boilerplate for you now (probably not relevant for this discussion though)

> C does not support simple overloading on argument types, C++ does

This does make it hard of you want to provide an `extern "C"` interface (since such an interface doesn't allow overloading). It doesn't sound like that's a big concern right now.

-------------------

As @matusvalo and @h-vetinari say: you can get Cython to generate a C header file with `cdef public`. As @rgommers notes - that generates an extension module that you need to import (i.e. it isn't just a stand-alone C/C++ library). That probably makes it less useful for people that want to use them from C or C++.

**Comment by rlucas7** [comment]
> Lack of interoperability affects us internally too. Because of how the build system works currently for special functions, the compiled kernels for special functions written in Cython can not be called from compiled kernels written in C or C++. This is blocking #19287 at the moment, cc @rlucas7.

Thanks @steppi , I don't have anything to add that isn't repetitive of what's already said, so I'll just say +1.

**Comment by steppi** [comment]
Thanks everyone for your comments. It seems like there's no real objections to @izaid and I beginning to work on rewriting special function scalar kernels that are currently in Cython into C++.

I'll try to summarize some of the discussion above iand respond to anything I think hasn't been addressed.

There were some concerns about the complexity of C++, but fortunately we need only a small subset of the language. As @izaid said, we just want to be able to leverage the rich ecosystem for mathematical functions that already exists in C++, to benefit from the possibility overloading on argument types, and to benefit from built in complex number support which is conformant across platforms.

I think there was also some concern about scarcity of maintainers with C++ knowledge, but since the Cython were talking about touches neither the Python or NumPy C API, the use of Cython here doesn't actually cut down on any complexity. The only differences from C are basically in syntax, and the C++ we will be using is basically just C with some templates and calls to Boost primitives.

This RFC issue only regards rewriting the scalar kernels in C++, but there was a lot of good discussion regarding sharing the resulting headers among different projects. This is something that would be planned for further down the line; with rewriting these scalar kernels as only an initial step. For know, I see this as creating reference versions of these functions which could in principle be used in the other projects, even if just by copy and pasting.

 As @rgommers said, the idea is only to ship headers, not to have a shared library, so we don't need to worry about ABI compatibility. @jzmaddock had suggested wrapping everything in a thin `extern "C"` function as a means to ensure ABI compatibility, but noted that this would interfere with the ability to inline the functions. For performance reasons we'd like to be able to inline everything, which shipping only headers should allow.

@rgommers pointed out that exposing headers through `get_include()` is problematic, but he has plans to work on a better mechanism to do this.

> I don‘t know if it’s a good idea to use (part of) scipy as C/C++ lib. If there is a need of several projects for a common C/C++ lib of special functions, isn’t it better to create a new project or extend existing ones like boost?

@lorentzenchr, I think you have good point here.  When we get to that stage, I don't think it matters where exactly the headers are shipped from, just that they are available to all of the relevant projects. Eventually I would like to see these things make their way into Boost, and I plan to write them using Boost primitives as if they were going into Boost. Much of `special` is in a bad state though, and I think there is a lot of room for improvement before things get in good enough shape to make it to Boost. Trying to get things into Boost in one go seems like a more difficult path.

> Another possibility would be to make scipy sf array api compatible. Nanobind might be a possibility, see https://nanobind.readthedocs.io/en/latest/ndarray.html.

In a way, we're already working on array API compatibility for `special`, https://github.com/scipy/scipy/pull/19023#, basically by just dispatching to the implementation in the correct array compute library based upon the input array type. @lorentzenchr, are you saying that instead of shipping headers which can be used by other libraries, we could maintain implementations of the functions that end up in the `special` array API extension for Jax, PyTorch etc... within SciPy and dispatch to those from `scipy.special`? It seems like it would be taking on more work; I'd hope to ship some of the maintenance burden to maintainers of the other array compute libraries.

> Cython can generate ufunc boilerplate for you now (probably not relevant for this discussion though)

@da-woods, I've been keeping an eye on this new Cython 3 feature, and have considered replacing our infrastructure to do this once Cython 3.x becomes the minimal supported version SciPy.

> As for complex special functions, we reasonably often get requests for complex Bessel functions (for example), but I've deliberately avoided them as most of the evaluation methods look rather simplistic to me with no investigation of where they work and where they explode (numerically), plus the complex domain is a huge space to explore... I'm not even sure it's possible to devise comprehensive tests over such a large space? But for sure folks do need them.

@jzmaddock, yeah, he ability to test comprehensively drops dramatically as the number of parameters in a special function increases. I hope to devote effort to comprehensively testing special functions of a complex variable. Very roughly speaking, the plan is to use known structure to cut down on the number of test cases by eliminating some which are essentially the same as others. As an example, here's the [test suite]( https://github.com/scipy/scipy/blob/main/scipy/special/_precompute/hyp2f1_data.py) I've worked out for the Gaussian hypergeometric function `hyp2f1`, though this is still a little rough. I hope to write technical reports with details of the testing strategies for each function, along with the results.

**Comment by steppi** [comment]
It looks like this discussion has ran its course. I'll leave this open a couple more days in case anyone else wants to chime in.

**Comment by lorentzenchr** [comment]
@steppi A C++ header only lib, starting off inside scipy, with long term vision inside boost seems like a good idea to me.

The inline argument is a really good one. Once, I wanted to use `xlogy` from scipy in a performance critical Cython loop in scikit-learn and ended up with my own copy of that function because it couldn’t be inlined when cimported.

> are you saying that instead of shipping headers which can be used by other libraries, we could maintain implementations of the functions that end up in the special array API extension for Jax, PyTorch etc... (at least those they don't already have) within SciPy and dispatch to those from scipy.special?

What I meant is that with nanobind, AFAIU, you can call `my_special_fun(x)` on numpy, jax and pytorch arrays `x`. The function understands array data from all those frameworks. So there would be no need anymore to have special functions (reimplemented) in all different array frameworks.

This was just a suggestion and food for thought what’s possible today.

**Comment by steppi** [comment]
I see @lorentzenchr. I'm not familiar with nanobind, it seems like its meant as a replacement for pybind11 by the same author?  Can you elaborate on how it could help. We're dealing with scalar functions written in C or C++, and different libraries have their own means of turning these into ufuncs which can operate on arrays.

In NumPy, we use 'PyUFunc_FromFuncAndData` from the C API as described [here]. SciPy has its [own infrastructure](https://github.com/scipy/scipy/blob/main/scipy/special/_generate_pyx.py) for generating the right C API boilerplate. 

CuPy has its own API and its own infrastructure. Here's an example PR, https://github.com/cupy/cupy/pull/7520/files, adding `spherical_yn`.  Here's an example of what goes into adding a special function to PyTorch, https://github.com/pytorch/pytorch/pull/78900. What we would be supplying is the scalar kernel that goes into the file `Math.h` here. I'm not familiar with how things are done in Jax.

Looking at those CuPy and PyTorch PRs, what we'd be supplying is the scalar kernel, and then the package developers would add the boilerplate as needed. Are you saying that we could use nanobind to create a streamlined common replacement for the ufunc creation APIs of the different packages?

**Comment by steppi** [comment]
I'm going to go ahead and close this but will be creating new issues for discussion of more specific aspects related to this effort. Feel free to create a new more specific issue if you have more to say that doesn't fall under a relevant open issue.
