### ISSUE TITLE
ENH: keep axis functionality in sparse.csr_array.getnnz()

### ISSUE THREAD

**Issue by Thomas-Jaeken** [scipy/scipy#19405]
### Is your feature request related to a problem? Please describe.

I require this functionality and don't see an efficient way to hack it.
It is planned to disappear in version 1-13...

### Describe the solution you'd like.

have it work like before

**Comment by dschult** [comment]
One way to get the results of the axis parameter from `A.getnnz` is:
```python
# for axis=0
np.array([vec.nnz for vec in A.T])
# for axis=1
np.array([vec.nnz for vec in A])
```
Here's some code to test this:
```python
import numpy as np
import scipy as sp
A = sp.sparse.csr_matrix([[4, 5, 0], [7, 0, 0]])
A.getnnz(axis=0)  # -> np.array([2, 1, 0])
A.getnnz(axis=1)  # -> np.array([2, 1], dtype=np.int32)

# for axis=0
np.array([vec.nnz for vec in A.T])  # -> np.array([2, 1, 0])
# for axis=1
np.array([vec.nnz for vec in A])  # -> np.array([2, 1])
```

**Comment by dschult** [comment]
Good point!   
If you are willing to give up having it work for all sparse array formats, the following works for `csr` format and is just as fast or very slightly faster in my trials than the original function.  A similar (swapped) version would work for `csc`.

```python
A = sp.sparse.csr_array(np.ones((500,1000)))
assert (A.getnnz(axis=0) == np.bincount(A.indices, minlength=A.shape[1])).all()
assert (A.getnnz(axis=1) == np.diff(A.indptr)).all()

B = sp.sparse.csr_array([[4, 5, 0], [7, 0, 0]])
# for axis=0
A0 = np.bincount(B.indices, minlength=B.shape[1])  # -> np.array([2, 1, 0])
# for axis=1
A1 = np.diff(B.indptr)       # -> np.array([2, 1])

# both are 4.56ms on my machine
%timeit A.getnnz(axis=0)
%timeit np.bincount(A.indices, minlength=A.shape[1])

# getnnz is 15.8µs,  np.diff is 9.9µs
%timeit A.getnnz(axis=1)
%timeit np.diff(A.indptr)
```

Of course, it is also not as readable in my opinion. I'm not saying it is better... just a possible replacement.

I'm pretty sure that a reasonable and commonly occuring use-case would be enough to make the developers include this feature somehow.  We're looking for how many people use the `axis` keyword and what the use-case is. What are you using `axis=` for?

**Comment by Thomas-Jaeken** [comment]
Thank you! I will use the `np.diff(A.indptr` for now!

**Comment by llucrb** [comment]
I was getting frustrated because I needed to use .getnnz(axis=2), and when using arrays instead of matrices I was getting errors when trying to access .indptr or .indices. I believe this solved my problems:

```
def getnnz(sparse_array, axis):

    ones_array = sparse_array.copy()
    ones_array.data[:] = 1
    nnz_array = ones_array.sum(axis=axis)
    
    return nnz_array
```

Am I missing something? Is it really just that?

**Comment by dschult** [comment]
I don't understand a few aspects of your post.  `axis=2` will not work for csr_array because it can't be a 3D object.
You don't describe what errors you werre getting when manipulating e.g. indptr or indices. The methods described a few comments up do work to find nnz by axis 0 or 1.
It looks like your example code would produce the correct results -- but it is not very efficient. You are making a copy of the entire array and then setting all of its values to 1 and finally summing their values. Maybe `(sparse_array != 0).sum(axis=axis)` would remove much of the excess. But that still requires creating an entirely new array before summing it.  

What is wrong with `np.diff(sparse_array.indptr)` for axis=1 and 
`np.bincount(sparse_array.indices, minlength=sparse_array.shape[1])` for axis=0?

**Comment by llucrb** [comment]
Thank you very much for your quick response. I am using a coo_array because for my problem my matrix is more neatly stored as a 3D array. I was looking for how to bypass the deprecation of the .getnnz method and I reached this page without realizing it was only about csr_arrays. My apologies for the confusion.

 With a coo_array I get errors 
> AttributeError: 'coo_array' object has no attribute 'indptr'
> AttributeError: 'coo_array' object has no attribute 'indices'

Yes, I can find a way to re-arrange my matrix and use the solutions above, but I was still frustrated by not being able to use something that looked as simple as just calling getnnz, so I ended up with the workaround I shared. 

For my particular problem, your more compact solution does not seem to run faster, but I very much appreciate your help!

**Comment by dschult** [comment]
The `coo_array` sparse format uses the attribute `A.coords` to store the row/col kind of information.
`A.coords` is a tuple of 1D numpy arrays, each one holding the coordinates for a specific axis. The attribute `A.data` stores the actual values. So `(data, coords) = ([3.4, -1.2), ([0, 2], [1, 1]))` would be the array
`[[0, 3.4], [0, 0], [0, -1.2]]`.  3D versions of that work similarly.

So in 2D, the shortcut above for `A.indices` will work for coo_array is you use `A.coords[0]` in place of `A.indices`. Or use `A.coords[axis]` for any axis.  

`np.bincount(sparse_array.coords[axis], minlength=sparse_array.shape[axis])`

This is untested, but I think it works...
