### ISSUE TITLE
RFC: Creating private include directory for special function kernels written in C++

### ISSUE THREAD

**Issue by steppi** [scipy/scipy#19499]
In https://github.com/scipy/scipy/issues/19404, we discussed the possibility of SciPy supplying headers for special function kernels written in NVCC compatible C++. There was concern about the potential maintenance burden, but does anyone have objections to offering a private and unadvertised `scipy.special._get_include()` to facilitate downstream experimentation?

To do this we simply need to place our header only C++ code in an include directory and write a `_get_include` function. There would be no promises of stability; this would just be to allow @izaid and others to experiment with including these headers in CUDA programs downstream without having to work perpetually off of a feature branch. (I believe izaid is writing macros to turn the headers into valid CUDA code).

**Comment by rkern** [comment]
Ultimately, they should not be packaged within the installed `scipy` package, and I don't think doing so temporarily would help much. `numpy` headers are packaged because they are needed at build-time in order to build extensions that interact with the installed `numpy`. These are not, as far as I know. Other projects can just vendorize those files to experiment. Eventually, moving them to a separate repo and including them as a git submodule will be the ultimate solution, I think.

**Comment by steppi** [comment]
OK, I think that sounds pretty reasonable. I've used `numpy.get_include()` in my own projects and had thought it was supplied so other packages can write extensions that make direct use of the NumPy C API; I wasn't aware of the history. I  guess if the numpy headers weren't needed at build time they would be vendored separately from NumPy for downstream use?

**Comment by rkern** [comment]
That's right. This is just sharing some common source code, not interaction between prebuilt binaries. The whole point of transitioning these to be C++ header-only libraries is to enable this decoupling.

**Comment by rgommers** [comment]
For a real solution I completely agree with @rkern, but I'd add that if it helps you during development, I don't see a problem with temporarily inserting a private `_get_include`. As long as it very clearly states that no one should rely on it, and that it may disappear at any time or change what it returns, that should be okay.

**Comment by rkern** [comment]
It just seems like extra work for no benefit. If we just organize them into a discrete folder in our repo, and anyone can `git submodule` it into their own codebase. That's the least amount of work we can possibly do but is closer to the long-term solution than packaging and exposing the headers into the `scipy` bdist packages.

**Comment by rgommers** [comment]
Rather than distributing I was thinking of a scenario like @steppi or @izaid working on both SciPy and CuPy iteratively, in their own repos with in-place builds. It's a nontrivial amount of overhead to add a git submodule at that point, that'd be a bit clumsy. All one needs would be something like in the directory of interest:
```python
def _get_include():
    return os.path.dirname(__file__)
```
and then in (for example) CuPy's build config a `include_dirs += scipy.special._get_include()`.

You can even return multiple directories, so no need to organize them in a discrete folder right away.

Anyway, this is completely private, so it really doesn't matter - whatever is easiest.

**Comment by steppi** [comment]
Right @rgommers, I was just in the middle of typing something like that. @izaid just needs an easy way to get the headers. We plan to keep a high velocity developing this C++ code, and having a private `_get_include` seemed like an easy solution.

**Comment by izaid** [comment]
I was going to chime in, but actually @rgommers expressed exactly what I wanted to say. I entirely agree with @rkern on the long term solution. But it really helps a lot to have a temporary solution like `_get_include()` as proposed. The include directory is actually needed at runtime for other projects (like CuPy) to do just-in-time compilation. This will really help us get off the ground, allow us to properly test on CUDA, and allow other array libraries to try what we are doing so we can catch problems early.

I am totally fine with moving these headers elsewhere long term if that is what is wanted.
