### ISSUE TITLE
DOC: Differences between exponpow distribution and referenced paper

### ISSUE THREAD

**Issue by r3v1** [scipy/scipy#19595]
### Issue with current documentation:

In the documentation of [exponpow](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.exponpow.html#scipy-stats-exponpow) it is referenced a [paper](http://www.math.wm.edu/~leemis/chart/UDR/PDFs/Exponentialpower.pdf) about the distribution, but it differs from the scipy's implementation.

Scipy PDF definition:
![image](https://github.com/scipy/scipy/assets/26328973/2c70ebc4-fdcc-4688-894e-fe81234c3059)

Paper definition:
![image](https://github.com/scipy/scipy/assets/26328973/fc6a9009-21e9-4089-b4e4-7d8050e578c9)

Why these formulas don't match?

**Comment by rkern** [comment]
We often omit the `loc` and `scale` parameters from the formulae for clarity, since they can always be derived from the canonical `loc=0, scale=1` formulae in the same mechanical fashion. In the formula from the reference, they include the scale parameter, but then reparameterize it to simplify the formula, obscuring its role as a scale parameter and making it look like a shape parameter; λ is equal to `scale ** -b`.
