### ISSUE TITLE
DOC: Add interactive examples with jupyterlite-sphinx

### ISSUE THREAD

**Issue by steppi** [scipy/scipy#19729]
### Issue with current documentation:

It would be nice to add some interactivity to SciPy's documentation. This could be done in-browser with  [Jupyterlite](https://jupyterlite.readthedocs.io/en/stable/) running a WASM based kernel like [pyodide](https://pyodide.org/en/stable/). Earlier this year, [Scikit-learn added Jupyterlite buttons](https://github.com/scikit-learn/scikit-learn/pull/25887) to its examples galleries. To see it in action, you can check the "launch lite" button at the bottom of the page [here](https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html).

### Idea or request for content:

I've created a Sphinx directive `TryExamples` which was accepted into [jupyterlite-sphinx](https://jupyterlite-sphinx.readthedocs.io/en/latest/), a Sphinx extension that makes it easy to embed Jupyterlite notebooks into Sphinx documentation. You may have seen the [Scientific Python Discourse post](https://discuss.scientific-python.org/t/making-docstring-examples-interactive/812) I made earlier this year. I have an [open PR](https://github.com/jupyterlite/jupyterlite-sphinx/pull/116) which should bring the `TryExamples` directive to a production ready state. I think it's time to start talking about actually deploying this in SciPy's docs.

The extension adds a button to each rendered doctest examples section. Clicking the button will swap the rendered examples in-place with an embedded Jupyterlite notebook. You can see it in action for SciPy 1.11.2's documentation at https://steppi.github.io/scipy.

One thing that needs to be considered before this could be shipped is that we need to take care that the SciPy version being documented is that same as that available on the Jupyterlite kernel used. This means we would either need to restrict the use of the directive to the latest release build which is available in Pyodide, or set up CI builds of SciPy for Pyodide in order to use the directive in dev docs. For now, the use of the directive could be guarded behind an environment variable which is only set for the latest release docs. I'd be curious to know what Scikit-learn does; I wasn't able to figure out from a quick look through their docs.

Scikit-learn gives a disclaimer that the interactive documentation is experimental, may have unexpected behavior, and has long load times. I haven't added anything like this yet, but have thought about adding a little question icon next to each button which displays a tooltip with such a warning.

Feel free to check the examples at https://steppi.github.io/scipy and let me know if there's anything that you think could be improved. The button style, position, and text is easily configurable if you think any of this should be changed.

### Additional context (e.g. screenshots, GIFs)

![image](https://github.com/scipy/scipy/assets/1953382/c28c2835-285e-4d03-a0d8-3ff9c91f29ab)

after clicking the button...

![image](https://github.com/scipy/scipy/assets/1953382/60649378-c67c-415e-a903-702670e70238)

**Comment by ilayn** [comment]
How do we prevent folks doing nasty stuff like importing `urllib` then spamming around or similar crypto-chad silliness? I don't know what the current way of frontloading such stuff, but is this in general a sandboxed operation?

**Comment by steppi** [comment]
> How do we prevent folks doing nasty stuff like importing `urllib` then spamming around or similar crypto-chad silliness? I don't know what the current way of frontloading such stuff, but is this in general a sandboxed operation?

Great question. It runs in the browser so they’d just be running their spammy stuff locally.

**Comment by lucascolley** [comment]
@dschmitz89 I think you were interested in this

**Comment by melissawm** [comment]
From quickly inspecting the scikit-learn docs, it looks like the scikit-learn version you get in the jupyter-lite environment is 1.3.1 no matter which docs version you are looking at (the stable version is 1.3.2 and dev is 1.5.0dev). It looks like there was a brief discussion about this here: https://github.com/scikit-learn/scikit-learn/issues/26763

In any case, very excited to see this. Do you have any documentation (even in draft) on what the process is to build this and what would change in docs build, release process etc for this to work in scipy?

**Comment by steppi** [comment]
Thanks @melissawm! That's really helpful to see what sklearn is doing; I guess I didn't look closely enough.

> In any case, very excited to see this. Do you have any documentation (even in draft) on what the process is to build this and what would change in docs build, release process etc for this to work in scipy?

Here's the [documentation for the TryExamples extension](https://jupyterlite-sphinx.readthedocs.io/en/latest/directives/try_examples.html). Modulo getting the docs and Pyodide SciPy versions synced up, set up is as simple as adding the `jupyterlite-sphinx` extension to the doc requirements, adding it to the list of extensions in the docs `conf.py`

```python
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.intersphinx',
    'numpydoc',
    'sphinx_design',
    'scipyoptdoc',
    'doi_role',
    'matplotlib.sphinxext.plot_directive',
    'myst_nb',
    'jupyterlite_sphinx',
]
```
and adding configuration for it in `conf.py`

```python
# -----------------------------------------------------------------------------
# Interactive examples with jupyterlite-sphinx
# -----------------------------------------------------------------------------
global_enable_try_examples = os.environ.get("GLOBAL_ENABLE_TRY_EXAMPLES")
try_examples_global_button_css = """
color: white;
background-color: #0054a6;
border: none;
padding: 5px 10px;
border-radius: 10px;
margin-bottom: 5px;
box-shadow: 0 2px 5px rgba(108,108,108,0.2);
"""
try_examples_global_button_hover_css = """
background-color: #0066cc;
transform: scale(1.02);
box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
cursor: pointer;
"""

try_examples_global_button_text = "Try it in your browser!"
try_examples_global_min_height = "200px"
```

the above is how I have it set up for what's hosted at https://steppi.github.io/scipy. Whether or not interactive docs are enabled is determined by the environment variable `GLOBAL_ENABLE_TRY_EXAMPLES`. I still haven't looked into what it will take to ship up to date wheels for SciPy on pyodide and use these in our docs builds. For now, I figured we could just enable interactivity for the release docs.

**Comment by steppi** [comment]
Thanks Ralf.

> One question I have there is how long we expect things to remain stable/installable with JupyterLite. E.g., are the numpy/scipy versions pinned, so things don't move from under the stable docs if new versions land in Pyodide? If so, we're probably good, because we have so few dependencies. For other projects that depend on numpy/scipy/pandas/etc. like scikit-learn, that may become more shaky perhaps - do you know what scikit-learn's experience there is so far?

My understanding is that if we pin `jupyterlite-pyodide-kernel`, then the included package versions will remain pinned too. That is, each version of `jupyterlite-pyodide` comes with a fixed set of package versions.

> Other topic: I did a bit more playing around and while overall things seem to work smoothly, it'd be useful to increase the minimum version size that the embedded window with the notebook uses. This is too few vertical lines when the docstring example is short, making it hard to read and use (that's for `linalg.solve`):

Agreed, I'll change that.

I guess I'll make a PR setting everything up with the interactive examples disabled, and we can enable it for the release docs once `jupyterlite-pyodide-kernel` ships with SciPy 1.12, since that will imminently be the new SciPy release.

**Comment by rgommers** [comment]
> I guess I'll make a PR setting everything up with the interactive examples disabled, and we can enable it for the release docs once `jupyterlite-pyodide-kernel` ships with SciPy 1.12

That looks like a switch to be used at doc build time, is that right? If so - rebuilding the docs is a bit painful. Could we have a switch that allows enabling/disabling the _Try it ..._ buttons in a single place (e.g. a separate file in the root of the doc build, that contains a boolean value based on which the buttons are shown or hidden on all pages)? That would also allow us to easily turn off the buttons in case there would be a breakage in JupyterLite or a security issue.

**Comment by steppi** [comment]
> > I guess I'll make a PR setting everything up with the interactive examples disabled, and we can enable it for the release docs once `jupyterlite-pyodide-kernel` ships with SciPy 1.12
> 
> That looks like a switch to be used at doc build time, is that right? If so - rebuilding the docs is a bit painful. Could we have a switch that allows enabling/disabling the _Try it ..._ buttons in a single place (e.g. a separate file in the root of the doc build, that contains a boolean value based on which the buttons are shown or hidden on all pages)? That would also allow us to easily turn off the buttons in case there would be a breakage in JupyterLite or a security issue.

Ok, if I understand correctly, your asking if we could have a switch that could be used to enable or disable the interactive examples without having to rebuild the docs? Yeah, I think that should be straightforward. `jupyterlite_sphinx.js` could check for the presence of the file and just hide the button if the flag is set to `false`. Sounds like a good idea, I'll work on that and PR to jupyterlite-sphinx.

**Comment by stefanv** [comment]
How do you figure out which version of `jupyterlite-pyodide-kernel` contains current stable?

**Comment by steppi** [comment]
> How do you figure out which version of `jupyterlite-pyodide-kernel` contains current stable?

For SciPy, at least for now, my thought was to stay in contact with the Pyodide developers and manually pin the versions. For SciPy, the usual release cadence makes this pretty manageable.  I first reached out in the open PR for updating Pyodide to use SciPy 1.12 https://github.com/pyodide/pyodide/pull/4499. I later agreed to be a project contact for SciPy here, https://github.com/pyodide/pyodide/issues/4506.

For the not so distant future, @agriyakhetarpal is working on shipping Pyodide wheels (including nightly ones) for major projects, which will help with the problem of syncing to the correct package version in Pyodide.

**Comment by stefanv** [comment]
Shipping pyodide wheels would indeed solve the problem.

As an interim measure, we could perhaps build and host these on the [dev wheels repo](https://scientific-python.org/specs/spec-0004/), if allowed by the anaconda.org platform?

**Comment by mattip** [comment]
We discussed this briefly at the NumPy community meeting. Is there a way to disable this for mobile or warn that it will download quite a bit of data? I would hate to see people use their whole data package by clicking a button.

**Comment by steppi** [comment]
> As an interim measure, we could perhaps build and host these on the [dev wheels repo](https://scientific-python.org/specs/spec-0004/), if allowed by the anaconda.org platform?

It's a good thought. @agriyakhetarpal would know better than me I think.

**Comment by steppi** [comment]
> We discussed this briefly at the NumPy community meeting. Is there a way to disable this for mobile or warn that it will download quite a bit of data? I would hate to see people use their whole data package by clicking a button.

That's a good point @mattip. I think something like this could be done. @Carreau do you have any thoughts on this?

**Comment by agriyakhetarpal** [comment]
>> As an interim measure, we could perhaps build and host these on the [dev wheels repo](https://scientific-python.org/specs/spec-0004/), if allowed by the anaconda.org platform?

> It's a good thought. @agriyakhetarpal would know better than me I think.

Hi @steppi, thanks for adding me to the conversation – I am happy to pitch in. I don't think we are quite there yet to push nightly Pyodide wheels, since the goal is to get these builds working in CI for all or most of the Scientific Python projects first for their development versions. The one for NumPy just went in at https://github.com/numpy/numpy/pull/25894, courtesy of @rgommers!

I am starting to work on other projects in the ecosystem, though SciPy seems to be the last on the list at this time, owing to the fact that the build procedure involves the compilation of a lot of Fortran code – which isn't supported in WASM runtimes altogether.

**Comment by Carreau** [comment]
> That's a good point @mattip. I think something like this could be done. @Carreau do you have any thoughts on this?

The easiest way would be to use [css media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries) to hide the button on "small" screens.

We can try to peak at the `navigator.UserAgent`, or `navigator.connection` though I think it's still in draft, and from my laptop test it may not reflect the real network conditions: `({..., effectiveType: "4g", saveData: false`,...})` (even when I switch to tethering).

**Comment by Carreau** [comment]
See https://github.com/jupyterlite/jupyterlite-sphinx/pull/141, with this the button will be hidden on narrow screens.

**Comment by steppi** [comment]
Thanks @Carreau. A heuristic based on screen size seems like its good enough for now.

**Comment by agriyakhetarpal** [comment]
> I saw interactivity was added to scipy in the scipy 1.13 changelog and was quite interested to look at it. I am not able to find the links though am I missing something?

> For example I don't see the button in either 1.13 doc, 1.11.2 doc. (Same scipy version as in Pyodide), dev doc.

Hi, @lesteve – I suppose this is because the examples were disabled prior to deployment – the buttons should show up for a split second if you reload the page multiple times, but the `try_examples.json` hides them afterwards with a `*` glob pattern. I'm working to improve this behaviour so that they are hidden at the time of loading the page.

**Comment by steppi** [comment]
Thanks @lesteve. Yes, @agriyakhetarpal is right. We have interactive examples disabled currently and are waiting on Pyodide 0.26 (with support for SciPy 1.12) to be released before enabling them. (The diff between 1.12 and 1.13 is small enough that this should be acceptable.)

@agriyakhetarpal didn’t mention, but he is working on shipping pyodide wheels for major Scientific Python packages. I recall he’s mentioned the issue with CORS headers to me before, but this is something currently outside my area of knowledge. SciPy will probably be the last package to get pyodide wheels unfortunately, due to the difficulties presented by the Fortran codebase.

**Comment by lesteve** [comment]
OK thanks for the details, before going into more details, I am very interested to help this kind of things move forward, so don't hesitate to let me know if I can help.

To be honest nobody complained in scikit-learn about broken examples inside JupyterLite, I guess because not that many people spot/click on the JupyterLite button maybe?

Personally I would slightly lean towards making it more discoverable rather than waiting for things to be perfect, because let's be honest, for Scipy things won't be perfect anyway :sweat_smile:. I completely agree this is debatable and this is fine and well if Scipy wants to adopt a more cautious approach.

Maybe let me try to suggest what could be an acceptable trade-off: enable JupyterLite button enabled by default in the dev doc but not in the stable doc for now? That would enable early adopters/curious people to try it out and potentially give feed-back.

> I recall he’s mentioned the issue with CORS headers to me before, but this is something currently outside my area of knowledge.

About CORS headers, yeah I am not an expert at all either, last time I heard about the anaconda.org situation, it was probably technically doable, but this needed to be looked at in more details, and there were maybe some non necessary technical hurdles to clear.

> SciPy will probably be the last package to get pyodide wheels unfortunately, due to the difficulties presented by the Fortran codebase.

I don't think this is that hard to generate scipy wheels, at least I am compiling a Pyodide distribution (in-tree I think is what Pyodide call it) with scipy and scikit-learn development version in https://github.com/lesteve/scipy-tests-pyodide/blob/main/.github/workflows/build-pyodide-debug.yml. I am pretty sure that means the generated Scipy wheels are usable. If you insist each project should generate their own wheels with `pyodide build` (I think Pyodide call this out-of-tree), it may be indeed harder for scipy but I have to admit I haven't tried.

**Comment by agriyakhetarpal** [comment]
SciPy is kind of the last package on my list owing to its complexity and I have started with these out-of-tree builds (with @rgommers, tagging for rightful attribution) with NumPy and PyWavelets (a few other packages like pandas, Matplotlib, and scikit-image are almost at completion at varying stages with others coming next very soon). It is a bit easier to test out interactive documentation on PyWavelets since the package has been in maintenance mode for a while, so:

> Maybe let me try to suggest what could be an acceptable trade-off: enable JupyterLite button enabled by default in the dev doc but not in the stable doc for now? That would enable early adopters/curious people to try it out and potentially give feed-back.

this is what is being tried out in the PyWavelets documentation right now: http://pywavelets.readthedocs.org/ where the wheel is coming from Pyodide and is a bit out of date, but all of the enabled examples should work because the changes have been mostly related to the build system or bug fixes over the past couple of releases.

> To be honest nobody complained in scikit-learn about broken examples inside JupyterLite, I guess because not that many people spot/click on the JupyterLite button maybe?

We are also kind of pilot-testing this too and hoping that we receive bugs from users, so it's available just in the latest stable version, but it will be available in the upcoming versions too (but since there's no versioned documentation for the package I don't think there will be a difference).

> I am very interested to help this kind of things move forward, so don't hesitate to let me know if I can help.

Perhaps getting to a point where we can pre-load packages with `jupyterlite-pyodide-kernel` (and not just `xeus-kernel`) would be a good addition? For reference, since the past day or so, I am currently experimenting on my fork by downloading the entire Pyodide distribution from GitHub Releases (200 MB), compiling a development version of an Emscripten/Pyodide wheel for PyWavelets, and sharing this wheel as an artifact plus overriding the Pyodide tarball to remove the older PyWavelets wheel – and also setting the `JUPYTERLITE_PYODIDE_URL` environment variable to use this custom Pyodide tarball instead of the one from the JSDelivr CDN: https://github.com/agriyakhetarpal/pywt/pull/1. It's not entirely working and is definitely not a good thing to do with GitHub Pages (owing to a host of scalability and conforming-to-the-terms reasons, of course), but the good thing here is that I am able to access my own distribution here and can use custom wheels, which works as a baseline to set after which we can explore other solutions. Moving to GitHub Pages to do so can be trivial for smaller projects, but can take a long time to do with `scikit-learn` and might not be worth it. I would bet that if the Pyodide or the Xeus kernels can pre-install Python wheels (Xeus can install recipes from emscripten-forge, but not other sources) from a PEP 503 compliant index or use a local one, it would solve most if not all of the problems here for all projects, coupled with nightly/development wheels being built out-of-tree and used for those projects (which is something that `scikit-learn` is already doing, I presume). I could surely use a review of my approach or suggestions related to that until we hear back from the Anaconda developers about the technical hurdles in achieving CORS headers (hopefully soon).

**Comment by lesteve** [comment]
Thanks a lot @agriyakhetarpal for the details, I'll try to have a closer look at some of your links although it may not happen super soon.

If I summarise my understanding of what you are trying to do: you are trying to assemble your own Pyodide distribution from individual project wheels built out-of-tree. This way you are in full control of the package versions. Am I getting this right?f

Personally my current goal/strategy with JupyterLite integration inside scikit-learn is less ambitious I would say: what I am looking for is a good place where to host a scikit-learn wheel (possibly 2 wheels, actually one for the stable release one for the nightly wheel) where I could conveniently use it. For the rest of the packages I am completely fine relying on the Pyodide distribution and for a few packages like `seaborn` having `%pip install seaborn` in the gallery examples that need it.

For scikit-learn this would be a line like this:
```
%pip install --extra-index https://pypi.anaconda.org/... scikit-learn==1.4
```
or if not possible the `await piplite.install` equivalent or even at last resort:
```
%pip install <some-not-too-long-winded-url-hopefully>
```

Full-disclosure: I have put this aside a bit for some time hoping anaconda.org would add CORS headers at one point ...

You could argue that being able to have the same notebook inside JupyterLite and standard Python kernel would be great, and I would agree, but the thing is that in scikit-learn case we need to have JupyterLite-specific modifications anyway, so having one more line to control the scikit-learn version feels completely fine. Here are the reasons we need JupyterLite-specific modifications:
- some gallery examples download some datasets and for this you need to do some [pyodide-http](https://github.com/koenvo/pyodide-http) hacks
- some packages need to be imported early because the way we check optional dependencies inside scikit-learn and some arcane Pyodide limitations (IIRC only top-level imports magically work in Pyodide, not imports inside function and that's how we check for optional dependencies in scikit-learn)

Just a few precisions about scikit-learn:
- we are indeed building a out-of-tree Pyodide wheel in our CI and running the full scikit-learn test suite on it which passes, except a few xfailed tests for a few Pyodide limitations (e.g. no threads or process support), see https://github.com/scikit-learn/scikit-learn/blob/6bf0ba5257d55ea0f3c89d7c4762096d84c052cc/azure-pipelines.yml#L122-L153 for more details if you are curious but that is somewhat similar to what numpy does I think
- scikit-learn.org uses Github pages 

I have not been looking at the xeus-python kernel approach for a while and I should probably have a closer look at one time. Having Pyodide packages on conda-forge seems like definitely a right approach but he thing I disliked last time I looked (maybe one year ago) is that it was loading all the packages when starting the notebook which makes for quite a poor user experience: when you load scipy you have 10-20s of nothing happening without any feed-back. Even if not ideal I prefer the Pyodide kernel behaviour: the notebooks loads fast and when I do the first import it is slow. Also you only pay for what you import. I have been told since that the situation may have improved with more lazy loading of packages with xeus-python but I haven't looked since.

**Comment by agriyakhetarpal** [comment]
> If I summarise my understanding of what you are trying to do: you are trying to assemble your own Pyodide distribution from individual project wheels built out-of-tree. This way you are in full control of the package versions. Am I getting this right?

Yes, that's the approach with a custom Pyodide distribution, but instead of building all of the wheels again (which can take several hours), I have currently downloaded a pre-built release and then hot-swapping the ones that I am trying to build the docs for, so in the case of Pyodide v0.25.1, I remove PyWavelets v1.4.1 and related files and copy the PyWavelets v1.7.0dev0 wheel that was just built. The kernel works, but I have other issues with a few missing packages right now (which I'm investigating right now).

> Personally my current goal/strategy with JupyterLite integration inside scikit-learn is less ambitious I would say: what I am looking for is a good place where to host a scikit-learn wheel (possibly 2 wheels, actually one for the stable release one for the nightly wheel) where I could conveniently use it. For the rest of the packages I am completely fine relying on the Pyodide distribution and for a few packages like seaborn having %pip install seaborn in the gallery examples that need it.

I get that. The long `%pip install <some-not-too-long-winded-url-hopefully>` command could perhaps be fixed with the addition of a `.micropiprc` file that can serve instructions to look at the index, and therefore the index would not be exposed to users of the docs?

Thanks for the additional info about `scikit-learn` – yes, the NumPy test suite xfails many tests too, similarly, based on the limitations you described. For example, the `numpy.f2py` tests are ignored on the module level because there is no proper support for Fortran compilation (that LFortran can change in the future as you mentioned previously above).

For the JupyterLite kernel-specific info such as lazy loading, perhaps others on this thread would know more about how to traverse these issues! Would it be possible to retrieve datasets at runtime with tools like `pooch`, which I know is already used in the test suite for `scikit-learn`, or will that require a `pyodide-http` backend plus (many) patches for it to work?
