### ISSUE TITLE
BUG: 1.12.0rc2 SciPy rather than scipy in `pip list` output

### ISSUE THREAD

**Issue by lesteve** [scipy/scipy#19906]
### Describe your issue.

It seems like pip list output for scipy has changed its casing. It is now `SciPy` whereas it was `scipy` for many many years.

I was surprised because I am used for many many years to do `pip list | grep scipy` to find information about scipy in my environment. Because there was no match I thought "what do you mean I don't have scipy?". Yes I could do `grep -i` but it seems like a slightly annoying change, and it could break habits and scripts.

For some reason, `conda list` has the lower case `scipy` as previously.

### Reproducing Code Example

```bash
conda create -n test-env python -y
conda activate test-env
pip install scipy==1.12.0rc2
pip list | grep -i scipy
```

### Actual output

```
SciPy      1.12.0rc2
```

### Expected output

```
scipy                         1.12.0rc2
```

### SciPy/NumPy/Python version and system information

```shell
Scipy 1.12.0rc2
```

**Comment by lucascolley** [comment]
Looking on PyPI it has the capitals for all versions now. I can't immediately see any change on our end (we've had `SciPy` in our `pyproject.toml` for a long time) - maybe something on PyPI end??

**Comment by rgommers** [comment]
Thanks for the report @lesteve. I agree that keeping the installed name lower-case would be better. 

There have been some moving parts in packaging tools with name normalization. The issue here stems from the metadata being written into `PKG-INFO` in the sdist:
```
Metadata-Version: 2.1
Name: SciPy
Version: 1.12.0rc2
```
compared to:
```
Metadata-Version: 2.1
Name: scipy
Version: 1.11.4
```

So it'll be due to a newer version of `meson-python` probably, or perhaps a `packaging` or `pyproject-metadata` change. I'll fix this up.

**Comment by lesteve** [comment]
Thanks for the fix!
