### ISSUE TITLE
BUG: sparse: CSC.setdiag is slower than converting to LIL and back

### ISSUE THREAD

**Issue by perimosocordiae** [scipy/scipy#19943]
### Describe your issue.

As discussed in the review of gh-17924, converting a CSC sparse array/matrix to LIL and calling `setdiag()` on that, then converting back to CSC format is often faster than using the CSC.setdiag() method directly.

We should update the `setdiag()` implementation in `scipy/sparse/_compressed.py` to fix this.

Here's the relevant analysis by @maxaehle in the abovementioned PR:

I can partially confirm this observation on my x86_64 Ubuntu system with Python 3.10.12 and SciPy 1.11.0 using 
[benchmark.py.zip](https://github.com/scipy/scipy/files/14008153/benchmark.py.zip). Converting to LIL, setting the diagonal there and then converting back to CSC is faster than calling `setdiag` on the CSC matrix directly in setups with low size or low density:

Density 0.001:

![plot_0_001](https://github.com/scipy/scipy/assets/72806890/797ff31e-ef6b-4781-8d13-6e38cdfc08c1)

Density 0.01:

![plot_0_01](https://github.com/scipy/scipy/assets/72806890/830f2f3f-3396-4a28-ae1d-8fb04ea654c2)

Density 0.1:

![plot_0_1](https://github.com/scipy/scipy/assets/72806890/6a64afd9-5146-4912-aa44-1f1294a00d28)

### Reproducing Code Example

```python
a = scipy.sparse.random(10, 10, density=0.25, format='csc')

tmp = a.tolil()
tmp.setdiag(1)
a = tmp.tocsc()
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version and system information

```shell
x86_64 Ubuntu system with Python 3.10.12 and SciPy 1.11.0
```

**Comment by dschult** [comment]
Converting to/from coo is **much** better than lil (plots below)
```python
a = scipy.sparse.random(10, 10, density=0.25, format='csc')

tmp = a.tocoo()
tmp.setdiag(1)
a = tmp.tocsc()
```

Also, in terms of speeding up csc, using the `start, stop` input to `np.arange` makes csc method faster for all N than converting to lil in the density=0.1 case.
` j = np.arange(k, k + max_index, dtype=self.indices.dtype)`
instead of adding k after creation.

In summary, it looks like in the density 0.1 case, csc might be slightly faster. But conversion to coo is better in the less dense cases.  I couldn't get much improvement out of shortcutting assignment with e.g. `_set_many`.

![Figure_0](https://github.com/scipy/scipy/assets/915037/0693a7a6-c7e2-405f-b276-0173f34e059d)

![Figure_1](https://github.com/scipy/scipy/assets/915037/53bcb783-1d23-4e45-af16-4070d819785c)

![Figure_2](https://github.com/scipy/scipy/assets/915037/61e425f7-0aff-4e2c-b3bc-0f46b285785d)
