### ISSUE TITLE
M1 runners via Github Actions available

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#20022]
### Is your feature request related to a problem? Please describe.

M1 runners are now publicly available: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

Would it make sense to migrate some of our Cirrus CI pipelines to GA? I am not really up to speed with our CI infrastructure

**Comment by fancidev** [comment]
It would help those who build scipy on M1 Mac (like me). For me the build was smooth other than some linker warnings (about unsupported switches) which I safely ignored. `dev.py doc` had some warnings; some of these fixed by #19978; one other related to doc string raising a DivideByZero in np.linalg on M1 chip which I didn’t bother to report).

**Comment by andyfaff** [comment]
I'm intending to look into it, doing a similar thing for numpy at the moment. 
Debugging on a local Mac is actually one of the most powerful platforms that one can use, https://github.com/numpy/numpy/wiki/Debugging-CI-guidelines

**Comment by dschmitz89** [comment]
Can this be closed now since pipelines were moved to GH actions where possible?
