### ISSUE TITLE
ENH: Euler diagrams (Donation)

### ISSUE THREAD

**Issue by brunolnetto** [scipy/scipy#20109]
### Is your feature request related to a problem? Please describe.

How can I incorporate my library ['eule'](https://github.com/trouchet/eule) to scipy? 

TAKE NOTE: The test coverage badge is not working. The library has currently 100% coverage.

### Describe the solution you'd like.

See implementation on repository

### Describe alternatives you've considered.

https://github.com/trouchet/eule

**Comment by ilayn** [comment]
Hi @brunolnetto . Wonderful that you want to contribute your hard work to the public domain. I think this work can better be suited to a visualization library instead of a number crunching one or something like a sympy or sage where folks are more pure math users in my opinion. We have a very limited visualization capabilities and only for specific results of algorithms like voronoi and so on.

**Comment by brunolnetto** [comment]
Well, at least I tried. I do not know sage. I thought scipy would be the most suitable place to host this solution. Visualization of Euler Diagrams is exactly what I do not want to do at the moment due complexity.

**Comment by j-bowhay** [comment]
@brunolnetto I would recommend posting this on the mailing list, you may get some good suggestions on where the best fit for this is

**Comment by brunolnetto** [comment]
May I get some instructions on how to post on mailing list? :)

**Comment by j-bowhay** [comment]
@brunolnetto I would start a new thread

**Comment by brunolnetto** [comment]
I am afraid, I have no such privilege.
