### ISSUE TITLE
Problems with the function scipy.linalg.ldl

### ISSUE THREAD

**Issue by pangtai6** [scipy/scipy#20189]
### Describe your issue.

why lu.dot(d).dot(lu.T) and lu[perm, :].dot(d).dot(u[perm, :])  can not get the original matrix, in python experiments?
In the following code result1 is False and result2 is false。

### Reproducing Code Example

```python
import numpy as np
from scipy.linalg import ldl

A = np.random.rand(5, 5)
lu, d, perm = ldl(A, lower=0) # Use the upper part
L = lu[perm, :]
A2 = L.dot(d).dot(L.T)
A3 = lu.dot(d).dot(lu.T)
result = np.allclose(A, A2)
result2 = np.allclose(A, A3)
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version and system information

```shell
1.5.2 1.23.5 sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

**Comment by ilayn** [comment]
As mentioned in the other issue, better keep usage questions to stackoverflow and other media so that others can help you. We only use this if there is any bugs or feature requests. But just to give you some pointers;

You are starting with a nonsymmetric `A`.  Hence you have to test with the upper half of the array because `lower=False` means use the upper triangle of A. 

```
>>> A4 = lu @ d @ lu.T
>>> result3 = np.allclose(np.triu(A4), np.triu(A))
>>> result3
True
```

Please check documentation for more details.
