### ISSUE TITLE
BUG: sparse.block_array incorrectly throwing dimension error when dense arrays passed

### ISSUE THREAD

**Issue by ivirshup** [scipy/scipy#20312]
### Describe your issue.

`sparse.block_array` throws an error saying `"blocks must be 2-D"` when all blocks are 2d numpy arrays.

### Reproducing Code Example

```python
from scipy import sparse
import numpy as np

# This occurs regardless of whether there's a single column
blocks = [np.ones((5, 1)), np.ones((3, 1)) * 2, np.ones((4, 1)) * 3]
assert all([x.ndim == 2 for x in blocks])

sparse.block_diag(blocks)

sparse.block_array(blocks)
```

### Error message

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 9
      5 assert all([x.ndim == 2 for x in blocks])
      7 sparse.block_diag(blocks)
----> 9 sparse.block_array(blocks)

File /mnt/workspace/mambaforge/envs/scanpy-dev/lib/python3.11/site-packages/scipy/sparse/_construct.py:891, in block_array(blocks, format, dtype)
    848 def block_array(blocks, *, format=None, dtype=None):
    849     """
    850     Build a sparse array from sparse sub-blocks
    851 
   (...)
    889 
    890     """
--> 891     return _block(blocks, format, dtype)

File /mnt/workspace/mambaforge/envs/scanpy-dev/lib/python3.11/site-packages/scipy/sparse/_construct.py:898, in _block(blocks, format, dtype, return_spmatrix)
    895 blocks = np.asarray(blocks, dtype='object')
    897 if blocks.ndim != 2:
--> 898     raise ValueError('blocks must be 2-D')
    900 M,N = blocks.shape
    902 # check for fast path cases

ValueError: blocks must be 2-D
```

### SciPy/NumPy/Python version and system information

```shell
1.13.0rc1 1.26.3 sys.version_info(major=3, minor=11, micro=7, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=64
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.26
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=64
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.26
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.1
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.9
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-3p3v09un/overlay/lib/python3.11/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

**Comment by dschult** [comment]
Am I understanding correctly that you are providing a 1D collection of 2D dense block arrays? The error is saying that you need to have a 2D grid of sparse arrays. You've got a 1D grid.

I think that is the trouble. The function `block_array` works with sparse arrays, and the shapes have to align in whatever grid you provide.  While the error message doesn't mention that fact that you are using dense arrays instead of sparse arrays, that seems reasonable too -- you have given it a 1D array/list of 3 python objects (that happen to be numpy arrays). The function asks for "a grid of sparse arrays". It is checking the validity of the grid -- and hasn't checked the python objects yet. 

On line 895 of the error message it shows using asarray with `dtype=np.object_`. That creates an array with 3 python objects (the three arrays in `blocks`). The shape is `(3,)`.  So, it is a 1D-array of 2D-arrays.

Also note that `block_diags` makes the "grid" for you. That is, the sparse arrays form only the diagonal, with zeros at all other positions.  So created a valid input for `block_diag`, but it is not a valid input for `block_array`. It is not valid in at least 3 ways: it is not a collection of sparse arrays, positions of the blocks are not provide in a (2D) grid, and the length of the 3 columns are not the same so won't be able to form a block-row due to shape mismatch.

**Comment by ivirshup** [comment]
Ah, this is totally my bad. I had thought `block_array` was the array version of `block_diag`

Is there a `block_diag` that returns `sparray`?

**Comment by dschult** [comment]
It is supposed to say in the [docs for functions](https://docs.scipy.org/doc/scipy/reference/sparse.html#functions)
`block_diag` creates a spmatrix if all the input arrays are spmatrix. If any of the inputs are sparray then the return object is a sparse array (sparray).
```
Returns
-------
If at least one input is a sparse array, the output is a sparse array. Otherwise the output is a sparse matrix.
```

**Comment by ivirshup** [comment]
Hmm. So what the deprecation/ transition plan for this case where it's passed `np.ndarray` and returns `spmatrix`? Surely it should return `sparray` at sometime in the future?

**Comment by dschult** [comment]
atm you have to convert one of the ndarrays to sparray.  When spmatrix is deprecated (or maybe when it is removed) we will make the backward breaking change to the case of all ndarray/lists/etc making a sparray. At least that is how I understand it.
