### ISSUE TITLE
Questions about Copilot + Open Source Software Hierarchy

### ISSUE THREAD

**Issue by liaochris** [scipy/scipy#20323]
Hi! My name is Chris and I'm writing a thesis on Open Source Software. I'm trying to collect/validate my data and I have two questions for the maintainers of this project.
1) Did this project receive free github copilot access on June 2022?
2) My thesis is especially focused on understanding hierarchical structures. Would it be possible to share a list of individuals in this project with triage/write/maintain/admin access in this project? I understand this may be confidential information, so please feel free to share it with [chrisliao@uchicago.edu ](chrisliao@uchicago.edu)

Happy to chat further if you have questions, and thank you for your time!

**Comment by ilayn** [comment]
Hi Chris, 

Here is limited information I have on the project; 

 1. Indeed this happened but I'm not sure if each and every one of us got it or not (I assume we all did). I have been offered and also there has been a 5-minute follow-up survey from GitHub because I forgot to claim my free access later on why I have not claimed it . 
 2. You can find this information on our Teams page https://scipy.org/teams/

**Comment by liaochris** [comment]
Hi! Thanks a lot, this is very helpful.
