### ISSUE TITLE
DOC/DEV: clearly document which code has an active upstream repo

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#20551]
Sometimes we vendor code which has an activate upstream, but not as a git submodule. If core devs aren't aware of where this code is, they could merge changes which we'd rather make upstream than in SciPy (cf. gh-20227).

If code needs to be vendored _not_ as a git submodule, this should be documented in the core dev guide, to avoid confusion.

Follow-up to gh-20199.

**Comment by rgommers** [comment]
> If code needs to be vendored _not_ as a git submodule

In most cases it doesn't need to be like that - it'd actually better to upstream any patches we may have, and then convert to using a git submodule. It's just because of code history that this is not the case. Both because we only started using git submodules fairly recently, and because upstream status may have changed (e.g. ARPACK used to be unmaintained until https://github.com/opencollab/arpack-ng was created, and SuperLU was was only maintained on GitHub at https://github.com/xiaoyeli/superlu since a couple of years).

**Comment by lucascolley** [comment]
Right - is it just ARPACK and SuperLU? I understand that things are subject to change, but even despite that, this is useful information to track (even if just in an issue to say "please contribute upstream and change to git submodule").

**Comment by rgommers** [comment]
A few more:

- QHull: https://github.com/qhull/qhull
- `optimize/_trlib/`: https://github.com/felixlen/trlib
- `stats/_unuran`: https://statmath.wu.ac.at/unuran/

That's probably about it. UNU.RAN isn't vendorable as a git submodule. The others I didn't check.
