### ISSUE TITLE
Query: pickling across SciPy versions

### ISSUE THREAD

**Issue by Prateek1410** [scipy/scipy#20599]
### Describe your issue.

When I try to open pickle file containing list of sparsematrices that I have used numerous times before without any issue I get the following error

ModuleNotFoundError: No module named 'scipy.sparse._arrays'

I haven't been able to find this exact error anywhere online.

I am using jupyter notebook via anaconda on windows.

This problem happens with both 1.12.0 and 1.13.0 (latest) versions of scipy package.

I have uninstalled and installed the package multiples times but still the issue persists.

### Reproducing Code Example

```python
import pickle

from scipy.sparse import csr_matrix
```
```


### Error message

```shell
ModuleNotFoundError: No module named 'scipy.sparse._arrays'
```

### SciPy/NumPy/Python version and system information

```shell
I am using jupyter notebook via anaconda on windows.

This problem happens with both 1.12.0 and 1.13.0 (latest) versions of scipy package.

1.12.0 1.26.4 sys.version_info(major=3, minor=10, micro=9, releaselevel='final', serial=0) [**Happens with 1.13.0 version too**]

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.1
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-bidi1l_7\overlay\Lib\site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-u773bfjp\cp310-win_amd64\build\venv\Scripts\python.exe
  version: '3.10'
```

**Comment by lucascolley** [comment]
Thanks for the report @Prateek1410 , can you include how you are using `pickle` and `csr_matrix`? Can you also include the full error traceback?

**Comment by lucascolley** [comment]
Which version of networkx did you use to generate the graphs?

**Comment by lucascolley** [comment]
@dschult I see you in the blame of `nx.to_scipy_sparse_array` so you're probably the best person for the job here

**Comment by andyfaff** [comment]
Pickling/unpickling works for me with csr_array or csr_matrix (substitute for csr_array) in the following example. Are you trying to pickle/unpickle across scipy versions? That is not guaranteed to work for pickles.

```
import numpy as np
from scipy.sparse import csr_array
import pickle

A = csr_array([[1, 2, 0], [0, 0, 3], [4, 0, 5]])
B = csr_array([[1, 3, 0], [0, 0, 3], [4, 0, 5]])

l = [A, B]

lp = pickle.dumps(l)

rl = pickle.loads(lp)

rl[0]
print(rl[0])
```

**Comment by rkern** [comment]
The module `scipy.sparse._arrays` was removed in 1.11.0 (the classes there were reorganized to other private modules). Pickles with these sparse arrays created from 1.10 and prior cannot be unpickled with later versions. This is one of the fundamental drawbacks with pickles for long-term storage. The pickle file stores a reference to the precise name of the class (including the module in which it is defined) when it serializes an instance. That means that the unpickler won't be able to find it again if the new version of the library has reorganized the code and moved the class somewhere else. In numpy, it's worth the effort for us to go to extensive lengths to keep old pickles working because it's at the very bottom of the scientific computing stack and we only have a few classes to worry about, it's not sustainable to do this for every class in every library.

**Comment by rkern** [comment]
To work around this in your case, you can subclass `Unpickler` to override the [`find_class(module, name)` method](https://docs.python.org/3/library/pickle.html#pickle.Unpickler.find_class). Whenever `module=="scipy.sparse._arrays"`, you can redirect it to wherever the class pointed to by `name` currently resides. Then you can repickle the object with your current version of scipy and carry on (until we muck things up again, but that doesn't happen too often).

**Comment by lucascolley** [comment]
thanks for the explanation @rkern 🙏

**Comment by Prateek1410** [comment]
Thank you all for your inputs! I can now proceed with my analysis feeling much relieved.

I downgraded scipy to 1.10.0 and the file got loaded in a few seconds. 

A small request to @rkern, could you please simplify your suggestion in your last comment? I don't understand what to do. 

Lastly, how to avoid this issue in the future? Is there a better alternative to pickling?

**Comment by rkern** [comment]
Untested:

```python
from pickle import Unpickler


class Scipy_1_10_Unpickler(Unpickler):
    def find_class(self, module_name, global_name):
        if module_name == "scipy.sparse._arrays":
            # This module has been refactored away. All of classes can be found in the public API.
            module_name = "scipy.sparse"
        return super().find_class(module_name, global_name)


def load_old_pickle(fp, **kwds):
    unp = Scipy_1_10_Unpickler(fp, **kwds)
    obj = unp.load()
    return obj
```

There is no general alternative to pickling that handles this any better. It's an inherent complexity of being able to serialize any class. Class objects know where they are defined (i.e. in `scipy.sparse._arrays` in 1.10 but in `scipy.sparse._coo` or one of the other specific modules in 1.11+), but not where they are publicly available (i.e. `scipy.sparse`) in the current version much less future versions.

If you have important long-term storage needs, you should look into doing the serialization yourself with a file format that you can control; e.g. a format defined on top of HDF5, for example. Use only public APIs (e.g. `scipy.sparse.coo_array` rather than `scipy.sparse._arrays.coo_array`) in the load routine, and your file will continue to be loadable while we maintain our promises about that public API (we might deprecate it at some point, but we won't casually move it around like we do for `_private` modules). This is more work than just throwing a general tool like pickle at your objects, so you have to weigh your needs judiciously.

**Comment by Prateek1410** [comment]
Thank you so much for the comprehensive response @rkern
