### ISSUE TITLE
BUG: scipy.optimize.curve_fit full_output and boundaries incompatible

### ISSUE THREAD

**Issue by Benja-Martin** [scipy/scipy#20892]
### Describe your issue.

I'm working on an optimization of parameters for a function using curve_fit and I want to access the full output of the curve_fit function. But if I introduce some bounds I have the following error: least_squares() got an unexpected keyword argument 'full_output'.

### Reproducing Code Example

```python
# As examples :
# This works
popt, pcov = curve_fit(f, x, y, bounds=(2, 4))
# This works
popt, pcov, dic, msg, ier = curve_fit(f, x, y, full_output=True)
# This doesn't work
popt, pcov, dic, msg, ier = curve_fit(f, x, y, full_output=True, bounds=(2, 4))
```

### Error message

```shell
least_squares() got an unexpected keyword argument 'full_output'
```

### SciPy/NumPy/Python version and system information

```shell
1.6.2 1.20.1 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/User/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/User/anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/User/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/User/anaconda3\\Library\\include']
```

**Comment by nickodell** [comment]
It appears you are using SciPy 1.6.2, which is about three years old, and which does not support the `full_output` argument to `curve_fit()`.

Here is why I think this:

I first tried reproducing your problem with the latest version of SciPy, 1.13.1. I found that I could not reproduce it in that version.

I then went back, to find which version of SciPy fixed this issue. I found that 1.8.1 failed, but 1.9.0 worked.

With this, I went looking at the 1.9.0 release notes, to see if someone had fixed this in 1.9.0. Searching for `full_output`, I found this:

>Add a `full_output` parameter to [scipy.optimize.curve_fit](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html#scipy.optimize.curve_fit) to output additional solution information.

I also looked at the documentation for 1.8.1, and it does not document support for a `full_output` parameter.

https://docs.scipy.org/doc/scipy-1.8.1/reference/generated/scipy.optimize.curve_fit.html

Since we don't promise support for `curve_fit(..., full_output=...)` in SciPy 1.6.2, I would argue that this isn't a bug.

For that reason, I suggest you upgrade to a version of SciPy with support for `full_output`.
