### ISSUE TITLE
DOC/DEV: Developer docs should mention Accelerate support

### ISSUE THREAD

**Issue by nickodell** [scipy/scipy#20893]
### Issue with current documentation:

[Current docs](https://docs.scipy.org/doc/scipy/building/index.html):

>As of SciPy >=1.2.0, we do not support compiling against the system Accelerate library for BLAS and LAPACK. It does not support a sufficiently recent LAPACK interface. This is planned to change in 2023, because macOS 13.3 introduced a major upgrade to Accelerate which resolved all known issues.

This doesn't seem to be true anymore - SciPy 1.14.0 will introduce support for Accelerate.

>SciPy now supports the new Accelerate library introduced in macOS 13.3, and has wheels built against Accelerate for macOS >=14 resulting in significant performance improvements for many linear algebra operations.

### Idea or request for content:

Suggested rephrasing:

>As of SciPy 1.14.0, we have added support for the Accelerate library for BLAS and LAPACK. It requires macOS 13.3 or greater. This support can be enabled with `python dev.py build --with-accelerate`.

Areas for improvement:

* What does SciPy do if no BLAS library other than Accelerate is found? Does it use Accelerate by default?
* What is the priority of Accelerate vs other BLAS implementations? Will SciPy use Accelerate if it has other choices?

I am unsure what the answers to these questions are, but I think it would be helpful to document it.

**Comment by lucascolley** [comment]
somewhat related to gh-19815, cc @h-vetinari

**Comment by andyfaff** [comment]
@nickodell a PR would be welcome.

> What does SciPy do if no BLAS library other than Accelerate is found? Does it use Accelerate by default?
What is the priority of Accelerate vs other BLAS implementations? Will SciPy use Accelerate if it has other choices?

## Install from pip
If one is on macOS>=14 then by default a wheel built against Accelerate (x86_64 or arm64) will be installed. These wheels will be significantly smaller because they don't bundle that extra dylib.
These are called something like `scipy-1.14.0.dev0-cp310-cp310-macosx_14_0_arm64.whl` or scipy-1.14.0.dev0-cp310-cp310-macosx_14_0_x86_64.whl`. We don't make this available for macOS13 because pip can't tell the minor OS version, and the Accelerate version we want is only present in >13.3.

An arm64 wheel built against OpenBLAS will be available, `scipy-1.14.0.dev0-cp310-cp310-macosx_12_0_arm64.whl`. This wheel will be installable on 12 < macOS, and will be installed by default on 12 < macOS < 14.

Finally there is `scipy-1.14.0.dev0-cp310-cp310-macosx_10_9_x86_64.whl`, to capture the remaining x86_64 targets. This will use OpenBLAS.

## `python dev.py build`
Without specifying any BLAS framework the build will fail.
If you use the `--with-accelerate` flag then the build will use Accelerate (this option is not currently available with `python dev.py test`).
If you use the `--with-scipy-openblas` flag then the build will attempt to use the scipy_openblas32 wheel (which you can pip install).
If you specify PKG_CONFIG_PATH then the build will use that to look for OpenBLAS or the scipy_openblas32 wheel.
To gain more customisation of the build  for different BLAS/LAPACK selection you have to use instructions at https://docs.scipy.org/doc/scipy/building/blas_lapack.html.

## `pip`/`build`
Specifying PKG_CONFIG_PATH is enough to get to use OpenBLAS or the scipy_openblas32 wheel.
To use other BLAS libraries follow the instructions at https://docs.scipy.org/doc/scipy/building/blas_lapack.html to get more customisation. The invocation to use Accelerate with pip is something like `pip wheel -Csetup-args=-Dblas=accelerate .`


My development workflow is to use `python dev.py build` with one of those options. You can then use `python dev.py test`, or put the build-install directory into PYTHONPATH, etc.
More instructions are at https://docs.scipy.org/doc/scipy/building/index.html, including editable installs.

**Comment by nickodell** [comment]
>If one is on macOS>=14 then by default a wheel built against Accelerate (x86_64 or arm64) will be installed. These wheels will be significantly smaller because they don't bundle that extra dylib.

In that light, should we change the dev instructions to primarily recommend Accelerate, and only use OpenBLAS if they are on macOS 13.3 or prior? If macOS>=14 users are using Accelerate, then that means that the majority of macOS users are using Accelerate, and testing for OpenBLAS can be covered by any users who use Linux for development/CI.

**Comment by andyfaff** [comment]
I would leave as-is. I think it's important to have people balanced on using Accelerate/OpenBLAS so that we continue to have the two channels followed in significant numbers. Besides, we'd soon hear if wheels built with Accelerate were having issues in the wild.

**Comment by rgommers** [comment]
> In that light, should we change the dev instructions to primarily recommend Accelerate

I am going to get around to finalizing auto-detection of any available BLAS library, and we'll pick Accelerate automatically before OpenBLAS then. So no need to change the recommendation on how to manually do it right now.
