### ISSUE TITLE
DOC: stats: wrong docstrings of `*Result` classes

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#20921]
Quite a few docstring examples in scipy.stats show an incorrect repr of `*Result` classes. Consider the docstring of `ttest_ind` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html#scipy.stats.ttest_ind):

```
In [15]: import numpy as np
    ...: from scipy import stats
    ...: rng = np.random.default_rng()

In [16]: rvs1 = stats.norm.rvs(loc=5, scale=10, size=500, random_state=rng)
    ...: rvs2 = stats.norm.rvs(loc=5, scale=10, size=500, random_state=rng)
    ...: stats.ttest_ind(rvs1, rvs2)
Out[16]: TtestResult(statistic=0.40375493221427916, pvalue=0.6864794357079085, df=998.0)
```

Note that `TtestResult` has three keys (`statistic`, `pvalue` and `df`) while the docstring example only shows two, `statistics` and `pvalue`.

Yes, `TtestResult` unpacks into these two values for backwards compatibility. 

So we need to either adjust the repr or fix the docstrings.

This was not caught by the smoke-docs machinery because of a bug which just got fixed in https://github.com/scipy/scipy_doctest/pull/162 by @luxedo. The fix will be available in the upcoming scipy-doctest==1.2.0 release relatively soon.

Meanwhile to see the failures locally, do 

```
$ # clone scipy-doctest & cd 
$ pip install -e .
$ cd path/to/scipy
$ python dev.py smoke-docs -s stats
```

**Comment by mdhaber** [comment]
I think the `repr` is what we want and the docstrings need to be updated.

**Comment by luxedo** [comment]
[KstestResult](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kstest.html) has the following attributes:
* statisticfloat
* pvalue
* statistic_location
* statistic_signint

[TtestResult](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats._result_classes.TtestResult.html) has the following attributes:
* statistic
* pvalue
* df

I`m adding them to the doctests because they are not private attributes.

There's also an issue with the return type for [ttest_ind](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html):
```
Expected:
    Ttest_indResult(statistic=-0.4390847099199348, pvalue=0.6606952038870015)
Got:
    TtestResult(statistic=-0.4390847099199348, pvalue=0.6606952038870015, df=998.0)
```
The documentation says that `ttest_ind` returns a `TtestResult` not a `Ttest_indResult`. So I think I can update as well. 

Is it possible that this mismatch in return types is happening to other doctests?
