### ISSUE TITLE
BUG: Double free or corruption when passing invalid arguments to some functions in the `scipy.cluster.hierarchy` module

### ISSUE THREAD

**Issue by BergLucas** [scipy/scipy#21011]
### Describe your issue.

I was working on Pynguin, an automated unit test generation tool for Python, and the tool found that if we pass invalid arguments to some functions in the `scipy.cluster.hierarchy` module, Scipy crashes with a "double free or corruption" error. It's not a particularly serious bug but it might be a good idea to fix it so that it is more user-friendly in the event of a user error.

### Reproducing Code Example

```python
#######################################################################
# Example 1
#######################################################################

from scipy.cluster.hierarchy import centroid

y = [-23, 17, 48, -76, -84, -88, -23, -74, 12, 35]
centroid(y)

#######################################################################
# Example 2
#######################################################################

from scipy.cluster.hierarchy import median

y = [-23, 17, 48, -76, -84, -88, -23, -74, 12, 35]
median(y)
```

### Error message

```shell
double free or corruption (out)
Aborted (core dumped)
```

### SciPy/NumPy/Python version and system information

```shell
1.13.1 2.0.0 sys.version_info(major=3, minor=10, micro=14, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=64
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=64
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.27
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-mnl4e8vy/overlay/lib/python3.10/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp310-cp310/bin/python
  version: '3.10'
```

**Comment by nickodell** [comment]
I can confirm that this fails on current main.

I minimized the centroid test case to the following:

```
from scipy.cluster.hierarchy import centroid

y = [0, 0, -1]
centroid(y)
```

Here is what I have figured out about this failure:

If _centroid recomputes the distance, and the expression 

```
cdef double _centroid(double d_xi, double d_yi, double d_xy,
                      int size_x, int size_y, int size_i) noexcept:
    return sqrt((((size_x * d_xi * d_xi) + (size_y * d_yi * d_yi)) -
                 (size_x * size_y * d_xy * d_xy) / (size_x + size_y)) /
                (size_x + size_y))
```

returns NaN, that will be saved to the distance matrix. (I believe this can only happen if the triangle inequality is not satisfied for the given distance matrix.)

If find_min_distance() fails to find any node closer than inf, then it will return a node index of -1.

https://github.com/scipy/scipy/blob/v1.13.1/scipy/cluster/_hierarchy.pyx#L757-L772

Since NaN is not smaller than inf, then -1 will be returned. That will be saved into neighbors as the index of the nearest neighbor.

Then, in the following expression, y = 0 and x = -1 is passed into the following expression:

```
            if dist == D[condensed_index(n, x, y)]:
```

This performs an out of bounds memory read. There are also out of bounds memory writes later on.

It seems like the following hardening steps could be taken to fix this:

* In `find_min_distance()` if -1 would be returned as the neighbor index, (i.e. no neighbors are close by) then raise an exception instead.
* If `new_dist` returns NaN, then raise an exception.

**Comment by nickodell** [comment]
@BergLucas

PS: Really cool project, and I see a lot of potential in the automatic generation of test-cases. It occurs to me that you could probably find more issues if you turned on cython bounds checking. For example, in this case, the array D[] is being written to out-of-bounds, but I bet there are other cases where there's an out-of-bounds read, or an out-of-bounds write where the corruption is not noticed.
