### ISSUE TITLE
BUG: sparse: `hstack/vstack` between a sparse and ndarray breaks in >=1.13.0

### ISSUE THREAD

**Issue by jkanche** [scipy/scipy#21064]
### Describe your issue.

Performing a hstack or a vstack operation fails in the newer versions of the package. 

### Reproducing Code Example

```python
import scipy.sparse as sp
import numpy as np

mat = sp.eye(5).tocsr()
sp.hstack([mat.tocoo(), np.array([0, 0, 0, 0, 0])])
```

### Error message

```shell
Using scipy version >=1.13.0


---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[10], line 1
----> 1 sp.hstack([mat.tocoo(), np.array([0, 0, 0, 0, 0])])

File [~/miniforge3/envs/biocpy/lib/python3.11/site-packages/scipy/sparse/_construct.py:733](http://localhost:8888/lab/workspaces/auto-E/tree/~/miniforge3/envs/biocpy/lib/python3.11/site-packages/scipy/sparse/_construct.py#line=732), in hstack(blocks, format, dtype)
    731     return _block([blocks], format, dtype)
    732 else:
--> 733     return _block([blocks], format, dtype, return_spmatrix=True)

File [~/miniforge3/envs/biocpy/lib/python3.11/site-packages/scipy/sparse/_construct.py:951](http://localhost:8888/lab/workspaces/auto-E/tree/~/miniforge3/envs/biocpy/lib/python3.11/site-packages/scipy/sparse/_construct.py#line=950), in _block(blocks, format, dtype, return_spmatrix)
    948     raise ValueError(msg)
    950 if bcol_lengths[j] == 0:
--> 951     bcol_lengths[j] = A.shape[1]
    952 elif bcol_lengths[j] != A.shape[1]:
    953     msg = (f'blocks[:,{j}] has incompatible column '
    954            f'dimensions. '
    955            f'Got blocks[{i},{j}].shape[1] == {A.shape[1]}, '
    956            f'expected {bcol_lengths[j]}.')

IndexError: tuple index out of range


with 1.12.0, I get the result back.
```

### SciPy/NumPy/Python version and system information

```shell
1.13.1
```

**Comment by dschult** [comment]
I cannot reproduce this. More precisely, with the example shown I get an error claiming an incompatible dimension error.

Did you mean to stack a row using hstack?  
I think you want to stack a column using `hstack`, or maybe a row using `vstack`.  Something like:
```python
sp.vstack([sp.eye(5).tocoo(), np.array([[0, 0, 0, 0, 0]])])
sp.hstack([sp.eye(5).tocoo(), np.array([[0], [0], [0], [0], [0]])])
```

**Comment by jkanche** [comment]
interesting, i was running into this on my cicd as well - https://github.com/BiocPy/mopsy/actions/runs/9648964097/job/26611371756

What version of numpy do you have?

**Comment by dschult** [comment]
It looks like you have converted to using sparse arrays -- but you are still using `sp.eye(5)` rather than `sp.eye_array(5)` and that creates a sparse matrix rather than a sparse array. I am pretty confident that this is not a numpy issue, but rather caused by a crossing between sparse matrix and sparse array -- the sparse arrays treat 1D lists as creating 1D arrays, while the sparse matrices treat 1D inputs as 2D rows. Does changing your input to `np.array([[0, 0, 0, 0, 0]])` work?

**Comment by dschult** [comment]
I've looked into this further -- and I apologize for misinterpreting the setting. This is indeed an issue with crossing sparse array and sparse matrix, but it is caused by a bug in the construction functions that occurs with 1D input arrays when the rest of the blocks to be combined are `spmatrix` (that is, when the variable `return_spmatrix` is `True` in `_blocks()`). In this case we end up creating a 1D block that should be treated like a row, but instead an IndexError is raised when `A.shape[1]` is use.

Thank you very much for reporting this issue and for answering my questions while I try to track it down. The short term fix is to use `np.array([[0, 0, 0, 0, 0]])` instead of `np.array([0, 0, 0, 0, 0])` but the longer term fix involves having `hstack` and `vstack` better handle 1D input. I'm working on a fix.

**Comment by jkanche** [comment]
Thank you so much for taking a deep dive intothis issue
