### ISSUE TITLE
DOC: incorrect section ordering for classes

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#21099]
### Issue with current documentation:

On class pages like https://scipy.github.io/devdocs/reference/generated/scipy.interpolate.CubicHermiteSpline.html, the Attributes and Methods sections render after other sections like References, contrary to the guidance at https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring.

This seems like a problem with the doc tooling, as they are in the correct order in the source code:

https://github.com/scipy/scipy/blob/5438adc9d895f331556970e62d3fff91be4a4ea1/scipy/interpolate/_cubic.py#L117-L129

### Additional context (e.g. screenshots, GIFs)

discovered by @anushkasuyal in gh-21096

**Comment by melissawm** [comment]
So - it looks like this has been the case "forever": https://docs.scipy.org/doc/scipy-1.5.0/reference/generated/scipy.interpolate.CubicHermiteSpline.html

Although I agree this is maybe not the optimal way to present this information, my interpretation is that the numpydoc section linked above does not prescribe how the docstring sections should be _rendered_, it only talks about how they should be defined in the source. So we might want to take this up with upstream since I believe this is the result of autodoc/autosummary default settings - see, for example :

- https://numpy.org/doc/stable/reference/generated/numpy.ufunc.html#numpy.ufunc
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame
- https://scikit-learn.org/stable/modules/generated/sklearn.cluster.HDBSCAN.html -> note that in this case the methods are presented in detail, not in an autosummary table.

**Comment by melissawm** [comment]
@Carreau do you have any thoughts here?

**Comment by Carreau** [comment]
Purely based on intuition, I'm going to say it's due NumpyDocstring's `__str__`, and the order in which it iterates over sections.

https://github.com/numpy/numpydoc/blob/54dbc890fdecc4c2e170e208ed2edc05bb62202a/numpydoc/docscrape.py#L547-L569

**Comment by lucascolley** [comment]
thanks @Carreau, I'll send a PR over there

**Comment by Carreau** [comment]
Have you tried ? I mean my guess is a shot in the dark, so maybe I'm wrong...

**Comment by lucascolley** [comment]
> Have you tried ? I mean my guess is a shot in the dark, so maybe I'm wrong...

I haven't checked whether this will fix our docs yet, but I'm pretty confident that it's an improvement regardless. At worst it will rule out one source of the problem.

**Comment by lucascolley** [comment]
Upstream fix is in, let's wait and see once the new version of `numpydoc` comes through.

**Comment by lucascolley** [comment]
this is fixed now! thanks for the help all and @anushkasuyal for the original report
