### ISSUE TITLE
BUG: io.loadmat: failure with large file due to address position limited by `np.int32`

### ISSUE THREAD

**Issue by Jucppy** [scipy/scipy#21256]
### Describe your issue.

loadmat function failure , 
RuntimeWarning: overflow encountered in long_scalars
  remaining_bytes = hdr.dtype.itemsize * n  

this is because  hdr.dtype.itemsize  type is numpy.int32, will convert the address postion from python int type into numpy 32bit int type , will for large file , 64 bit address is enough , but 32nit address will be overflowed 

suggest:
![suggest1](https://github.com/user-attachments/assets/25c657b7-0bc8-4f9d-911d-8e94112edc1b)
![suggest2](https://github.com/user-attachments/assets/22027651-4ba3-4d60-ba76-4bd242ff5441)

### Reproducing Code Example

```python
from scipy import io
data=io.loadmat('data.mat') # data.at file size 2.45GB , with over 800,000 parameters
```

### Error message

```shell
:\Programs\Python\Python38\lib\site-packages\scipy\io\matlab\_mio4.py:358: RuntimeWarning: overflow encountered in long_scalars
  remaining_bytes = hdr.dtype.itemsize * n
W:\Programs\Python\Python38\lib\site-packages\scipy\io\matlab\_mio4.py:176: RuntimeWarning: overflow encountered in long_scalars
  num_bytes *= d
Traceback (most recent call last):
  File "w:\Users\jwajus3\Downloads\Case2_Tier1_8HP_HP_overloadCooling52_L_120_20211213\test.py", line 2, in <module>
    data=io.loadmat('data.mat')
  File "W:\Programs\Python\Python38\lib\site-packages\scipy\io\matlab\_mio.py", line 226, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "W:\Programs\Python\Python38\lib\site-packages\scipy\io\matlab\_mio4.py", line 405, in get_variables
    mdict[name] = self.read_var_array(hdr)
  File "W:\Programs\Python\Python38\lib\site-packages\scipy\io\matlab\_mio4.py", line 380, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "W:\Programs\Python\Python38\lib\site-packages\scipy\io\matlab\_mio4.py", line 141, in array_from_header
    arr = self.read_full_array(hdr)
  File "W:\Programs\Python\Python38\lib\site-packages\scipy\io\matlab\_mio4.py", line 211, in read_full_array
    return self.read_sub_array(hdr)
  File "W:\Programs\Python\Python38\lib\site-packages\scipy\io\matlab\_mio4.py", line 177, in read_sub_array
    buffer = self.mat_stream.read(int(num_bytes))
ValueError: read length must be non-negative or -1
```

### SciPy/NumPy/Python version and system information

```shell
scipy version : 1.8.0 ; 1.13.1 both have this issue .
```

**Comment by lucascolley** [comment]
would you like to submit a PR?

**Comment by Jucppy** [comment]
Sure, I’d be happy to submit a PR。

**Comment by matthew-brett** [comment]
Just to unpack - there are two problems here - you've pointed to them both, but just to explain for our readers...

The first, at https://github.com/scipy/scipy/blob/main/scipy/io/matlab/_mio4.py#L359 - is that we are (I was) multiplying a dtype.itemsize (that is always of type int32) by the number of elements (a Python int). This would not overflow in Numpy < 2, because the result gets cast to `int64`:

```python
[nav] In [5]: type(np.int32(1) * 1)
Out[5]: numpy.int64
```

but it does in Numpy 2, because the result is now `int32`:

```python
[ins] In [2]: type(np.int32(1) * 1)
Out[2]: numpy.int32
```

and, indeed, I think the right fix is to cast as int or maybe `np.intp` (to preserve the overflow check) before multiplying.

The second is at https://github.com/scipy/scipy/blob/main/scipy/io/matlab/_mio4.py#L177

Here the elements in `dims` are constrained by the format to be `int32`, but the product of the dims and the itemsize (the size of the array) need not be within int32.  The calculation in Numpy < 2 and Numpy 2 gives an int32 result, so this was a bug before and after Numpy 2.

I think the right thing to do there is a slight refactor to use the same fast-product trick as in the code above, and replace:

```python
        num_bytes = dt.itemsize
        for d in dims:
            num_bytes *= d
```

with something like:

```python
        num_bytes = reduce(lambda x, y: x*y, dims, np.intp(dt.itemsize))  # fast product.
```

The trick will be making a good test!

**Comment by Jucppy** [comment]
thanks for your explain ,you give better solution， you will fix this right ?   : )

**Comment by matthew-brett** [comment]
I will - yes - PR soon.  Just trying to work out a test.
