### ISSUE TITLE
DOC: `stats.f_oneway`: use attributes instead of tuple unpacking in example

### ISSUE THREAD

**Issue by messagian** [scipy/scipy#21366]
AlexanderGovernResult https://github.com/scipy/scipy/blob/87c46641a8b3b5b47b81de44c07b840468f7ebe7/scipy/stats/_stats_py.py#L4220 is inconsistent with the f_oneway https://github.com/scipy/scipy/blob/87c46641a8b3b5b47b81de44c07b840468f7ebe7/scipy/stats/_stats_py.py#L3953 and kruskal https://github.com/scipy/scipy/blob/87c46641a8b3b5b47b81de44c07b840468f7ebe7/scipy/stats/_stats_py.py#L8868 results types (it is not a namedtuple) as such it cannot be unpacked in the same way.

**Comment by rkern** [comment]
This is intentional. We want people to access the results via attributes and not tuple-unpacking. This lets us continue to add new attributes without requiring any code changes; we find that we do this often enough to make this a policy. Where we use `namedtuple`s, it's because that function used to return plain tuples, so we have to use `namedtuple`s for backward-compatibility. For new functions, we use plain-old classes. The consistent way to use both is to use attributes to access the individual values that you want.

**Comment by messagian** [comment]
Apologies, if this is the case I would recommend to update the example in the f_oneway documentation which uses tuple unpacking and drove me to the conclusion that this was the intended way.

**Comment by messagian** [comment]
Sure thing @lucascolley
