### ISSUE TITLE
BUG: `special.betaincinv` returns nan

### ISSUE THREAD

**Issue by asi1024** [scipy/scipy#21426]
### Describe your issue.

`scipy.special.betaincinv` occasionally returns NaN values from SciPy version 1.14.0.

### Reproducing Code Example

Reproducer:

```python
import numpy as np
import scipy

a = np.array([[5]], dtype='f')
x = np.array([[0.5]], dtype='f')
print(scipy.special.betaincinv(a, a, x))  # expected: 0.5
```

### Error message

Output:
```shell
[[nan]]
```

### SciPy/NumPy/Python version and system information

```shell
scipy: 1.14.1
numpy: 2.1.0
```

**Comment by steppi** [comment]
This is the same underlying problem as https://github.com/scipy/scipy/issues/21303 and will require adjusting the Boost policies of `ibeta_inv_wrap` as was done for that issue. We had only adjusted the policies for `beta_ppf_wrap` which itself wraps `ibeta_inv_wrap`. Does anyone know why we need separate implementations for `special` and `stats` in the first place? I guess due to requiring different policies for some reason?

**Comment by lucascolley** [comment]
cc @WarrenWeckesser @dschmitz89 @czgdp1807

**Comment by dschmitz89** [comment]
The underlying issue was fixed in boost, let's see if we can remove our workarounds.
