### ISSUE TITLE
ENH: Octave full support

### ISSUE THREAD

**Issue by ncooder** [scipy/scipy#21420]
### Is your feature request related to a problem? Please describe.

I would suggest incorporating all the available functions from Octave into SciPy. Probably most of them are already implemented here, but there may be some of them that are useful and not available in SciPy.

**Comment by WarrenWeckesser** [comment]
That's an ambitious endeavor, for sure!  Note that we can't simply grab the Octave code and port it over to Python.  Octave is released under the GPL license, which is not compatible with the SciPy license.

If there are specific functions that you need that you can't find in numpy, scipy, scikit-image, scikit-learn, matplotlib, etc., open an issue about it here.

Because "implement all of Octave" isn't really an something we can tackle as a single issue, I'm closing this.

**Comment by ncooder** [comment]
@WarrenWeckesser You are right, I will try to send a PR with functions that are missing in the scipy, but can be useful for the data science.

**Comment by ilayn** [comment]
Note that you can't just read and reimplement in python, the GPL license also does not allow doing that. Hence better not make any connections between Octave and SciPy

**Comment by ncooder** [comment]
@ilayn OK, thank you for this information.
