### ISSUE TITLE
DOC: stats.bootstrap: clarify meaning of `paired` argument

### ISSUE THREAD

**Issue by TopCoder2K** [scipy/scipy#21704]
### Issue with current documentation:

There is no info about it on https://scipy.github.io/devdocs/reference/generated/scipy.stats.bootstrap.html#scipy.stats.bootstrap

### Idea or request for content:

Suggested fix: describe in what situations it's possible (if I understand the reasons, I can offer a more detailed fix.)

### Additional context (e.g. screenshots, GIFs)

The result of `print(scipy.__version__, numpy.__version__, sys.version_info)` is
```
1.10.1 1.24.4 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
```

The code I run:
```
orig_x = np.array([1, 2, 3, 4, 5])
orig_y = np.array([1, 2, 3, 4, 5])


def compare_x_y(x, y):
    print(x.shape, y.shape)
    return (x == y).mean()


print(compare_x_y(orig_x, orig_y))
print(
    sps.bootstrap(
        (orig_x, orig_y), compare_x_y, random_state=0, n_resamples=3
    ).confidence_interval
)
```
It prints:
```
(5,) (5,)
1.0
(5,) (5,)
(5,) (5,)
(5,) (5,)
(5,) (5,)
(4,) (5,)
```
Why does the last sample for `x` always have `orig_x.shape[0] - 1` elements? I always thought that bootstrap generates samples of the same size as the original one.
Moreover, if `paired=True` is used, the output changes to:
```
(5,) (5,)
1.0
(5,) (5,)
(5,) (5,)
(5,) (5,)
(5,) (5,)
(4,) (4,)
(4,) (4,)
(4,) (4,)
(4,) (4,)
(4,) (4,)
```

What have I missed?

**Comment by mdhaber** [comment]
The default `method`, ``'bca'`, also involves the jackknife, which leaves out one observation. If you choose `method='basic'` or `method='percentile'`, you will always have five observations in each sample.

**Comment by TopCoder2K** [comment]
Oh, I haven't known... Thank you!

If I want to ensure the shapes to be always the same, should I use `paired=True` then? The documentation lacks details about the argument, but, as far as I understand, if it is set, elements with the same indices in both sequences are taken, thus giving the same shapes.

**Comment by mdhaber** [comment]
>  if it is set, elements with the same indices in both sequences are taken

Yes. The elements from both (all) sequencies are considered to be "paired", so they are resampled together (as a unit).

This offered for convenience compared to, say, R's `bootstrap` package, which has no such option. Instead, the user would have to use the *indices* as the data, and the statistic would have to be written in terms of the indices rather than the observations themselves. (See e.g. the example on [page 8](https://cran.r-project.org/web/packages/bootstrap/bootstrap.pdf).)

Besides what is written, we could *also* document the shapes of the arrays that will be passed to the function, but that can get a bit complicated. Instead, if the elements are considered to be "paired", one can infer that `stats.bootstrap` will pass the function arrays with the same length along `axis`.

There are probably different opinions about how instructive the documentation should be. I wouldn't want to try to compress books written about the bootstrap into a single docstring. That said, I want to make what is there easy to understand *if* the user is already familiar with how the resampling should be done. Suggestions along those lines welcome.

**Comment by TopCoder2K** [comment]
> The elements from both (all) sequencies are considered to be "paired", so they are resampled together (as a unit).

Wow, that's a very convenient feature indeed! I think it should be documented in some way, e.g. give an example showing that the corresponding elements from all sequences have the same indices, or write something about the `paired` argument in the docstring. Even if I had known how the `paired` argument works for 2 sequences, I wouldn't have thought that the same would apply to more than 2 sequences, since the naming and the examples hint at a two-sequences case.

And thank you for the detailed response, @mdhaber!

**Comment by mdhaber** [comment]
Please see the current documentation. `paired` is documented and there is an example of its use. One thing I can think of adding is extending: 

> Whether the statistic treats corresponding elements of the samples in data as paired.

with

> If `True`, `bootstrap` resamples an array of *indices* and uses the same indices for all arrays in `data`.

**Comment by TopCoder2K** [comment]
> One thing I can think of adding is extending: <...>

Yes, great addition! Please note that I have seen the documentation and the example. The confusion arises from the meaning of ["to pair"](https://www.oxfordlearnersdictionaries.com/definition/english/pair_2), since it is usually perceived as supposing only two objects.

Should I close this issue and open a new one for the addition?

**Comment by mdhaber** [comment]
No, this issue is fine. 
I'll open a PR with that addition (or you can - let's keep the scope to just that change), and we'll close this when that merges.

**Comment by TopCoder2K** [comment]
> sorry if by "issue" you meant PR. You could have left this open and opened the PR, but I went ahead already.

No, everything is fine :) By "issue" I meant this particular issue.
