### ISSUE TITLE
ARPACK License

### ISSUE THREAD

**Issue by R-K-252000** [scipy/scipy#21715]
Hi Team.

ARPACK is a 3-Clause BSD license, but the second clause seems to be slightly different.

What does ‘the following disclaimer listed in this license’ refer to?

Is there any reason why the wording has been changed from the usual clause?

**Comment by rkern** [comment]
The "following disclaimer" in BSD-style licenses is the capitalized paragraph starting with "THIS SOFTWARE IS PROVIDED...".

There are lots of tiny variants of "BSD licenses" with trivial, legally and practically inconsequential rewordings. This is one of them. These days, we are blessed with a [more-or-less standard variant](https://opensource.org/license/bsd-3-clause) that is generically written that we can copy and use out-of-box with no changes. In the past (and ARPACK is fairly old), you'd always have to modify *something* in the license text because the original BSD license text mentioned by name the specific copyright holders from the original BSD project instead of using the generic "copyright holders" in that third clause.

You'd have to ask the ARPACK authors if you really want to track down the origin of this variant, but I expect the answer is that they copied it from another piece of BSD-style licensed software that they were familiar with before.
