### ISSUE TITLE
DOC: I had a problem with being unaware of changed behavior between versions. A changelog would be great

### ISSUE THREAD

**Issue by BMaxV** [scipy/scipy#21960]
### Issue with current documentation:

So, I used

https://docs.scipy.org/doc/scipy-1.5.4/reference/generated/scipy.spatial.Voronoi.html#scipy.spatial.Voronoi

from version 0.12 or something and in that version the (1.x) attribute point_region didn't exist yet and instead the link between input point and resulting voronoi region was implicit in the order of the inputs and the order of the voronoi regions.

This was removed for whatever good reasons you had, which is fine, it being wrong now is my mistake for assuming consistent behavior and not reading the docs.

But, when reading the docs, it is not clear that this old behavior is gone and there is no easy to read changelog between versions. It would be great if something like that was available, maybe from git history when certain attributes were added?

### Idea or request for content:

A changelog for changed behavior.

**Comment by jakevdp** [comment]
Hi - can you clarify what change it is that you wish were better communicated? I'm looking at the PR that first added the `Voronoi` class, the `point_region` attribute seems to have existed from the very beginning: https://github.com/scipy/scipy/pull/377

**Comment by rkern** [comment]
That property was never documented to be true. You were always meant to use `point_region` to relate the two. That it was true might even never have been guaranteed by the underlying Qhull library or for all inputs. It really might have been just a coincidence that it worked on the inputs that you tried before. It was never an intentional behavior of scipy, and might not have been an intentional behavior of Qhull.

I don't think there's anything we can do here. The behavior that was observed was at best an implementation detail.
