### ISSUE TITLE
ENH: signal: improve stability for filters for a broad frequency range

### ISSUE THREAD

**Issue by MarioSteinerEMF** [scipy/scipy#22035]
### Is your feature request related to a problem? Please describe.

When calculating the exposure values using weighted peak method in the time domain, this can be done using transfer functions (https://pubmed.ncbi.nlm.nih.gov/28542011/).
I implemented this like this:

```python
# Function to apply weighing in time domain (TD)
def WPM_TD(input_signal, Wf, fs):
    """
    Parameters:
        array input_signal: Signal to be filtered.
        
        list Wf: list of sublist for filter coefficients b and a form transfer function representation of weighing function.
                    Wf = [b, a] with b and a being lists themselves containig the filerer coefficients.
        
        float fs: sampling frequency in Hz.
    
    Returns:
        array filt_sig: weighted signal.
    """
    # coefficients of weighing function in filter representation
    b = Wf[0]
    a = Wf[1]
    
    # Taking absolute values
    a = [np.abs(a_i) for a_i in a]
    b = [np.abs(b_i) for b_i in b]
    
    # Constructing discrete digital filter by bilinear transformation
    b, a = scipy.signal.bilinear(b, a, fs) # sampling frequency in Hz

    # filtering of signal
    filt_sig = scipy.signal.lfilter(b, a, input_signal)
    
    # returning the filtered signal
    return filt_sig
```

When i plot the frequency response of b and a using scipy.signal.freqz(b, a, f) i see that the filter response is unstable. This results in wrong result for the signal weighting.

### Describe the solution you'd like.

A more stable filter response for a broad frequency range, especially for higher frequencies.
Filters as stable as in MATLAB or LabView

### Describe alternatives you've considered.

Using another program like MATLAB or LabView where the filtering is stbale.

### Additional context (e.g. screenshots, GIFs)

![Instable_filter_scipy](https://github.com/user-attachments/assets/808f81df-eb9c-4871-9036-d9585ace83fa)

Here is a plot of the filter function using scipy.signal.freqz for plotting. It can be seen very clearly that for different sample rates, the filter is unstable in different regions.

**Comment by DietBru** [comment]
As far as I know, there is no generic catch-all method for designing numerical stable filters (with arbitrary responses and sampling rates). As a rule of thumb, the steeper the flanks of your frequency response are (in relation to the sampling frequency), the more likely it is to have numerical problems.

The go-to approach to make your implementation numerically more robust, would be to use [second order sections] (SOS). I.e., use [tf2sos] to convert your transfer function and filter with [sosfilt] (don't forget to initialize with [sosfilt_zi]). If needed, inspect the stability of each SOS-block by itself and replace it by two or more SOS-blocks which have a similar transfer function. 

Alternatively, if off-line processing is sufficient for you and the signal is not too long (rule of thumb: < 10 million samples), you can just calculate the FFT of your signal, multiply with your frequency response and transfer it back. 

Concerning your implementation and plot:
* It's not clear to me, why you are taking the absolute value of your transfer function coefficients. Generally, it completely changes the filter behavior—especially, it can become unstable!  Does your plotted response correspond to the response your are trying to implement?
* Since you did not list the utilized filter coefficients for the plot, we don't know, if they would produce a finite frequency response. Did you check?
* In your plot, the frequencies of your response surpass the Nyquist frequency (and also the sampling frequency).

I hope this helps a bit, @MarioSteinerEMF.
For improving SciPy, it would be helpful to have a self-contained example illustrating what specifically needs to change. 
Could you provide code for such an example, @MarioSteinerEMF? 
IMO, having an filter design assistant, along the lines of [pyFDA], for designing numerically robust filters, is out of scope of SciPy (for now).


PS: Try out [pyFDA] when designing a filter—it has a nice GUI.


[second order sections]: https://en.wikipedia.org/wiki/Digital_biquad_filter
[tf2sos]: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.tf2sos.html
[sosfilt]: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.sosfilt.html
[sosfilt_zi]: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.sosfilt_zi.html
[pyFDA]: https://github.com/chipmuenk/pyfda

**Comment by MarioSteinerEMF** [comment]
Here is a little explanation of what i want to do:
In the paper https://pubmed.ncbi.nlm.nih.gov/28542011/ the assessment of welding currents is descibed. Different spectral components have to be weighted differently because the limits for exposure to magnetic and electric fields depends on frequency (Directive 2013/35/EU). In the directive limits dor the external megnetic fluc density, the so called action levels, are provided. More specifically, there is a low action level defined. The limits are piecewise linear but can be approximated by highpass and low pass filters, the combination of the filters forms a transfer function as it is described in Kellers paper.

I want to implement this transfer function in python and weight signals using it. The reason for wanting to do this in the time domain is because this is suggested as best method for welding current assessment, as the usage of highpass/lowpass filters resembles nerve cells best (see Keller paper).

Therefore i am constructing transfer functions in python with certain coefficients and want to filter signals with it.

Here is a code that shows that for certain sample rate, the filtered signal becomes unrealistic (diverges). A picture of the generated plots os also added.

import scipy
import numpy as np
import matplotlib.pyplot as plt


def generate_sine_signal(frequency=1, sampling_rate=100, amplitude=1):
    """
    Generates a sine wave with one period and allows variation of the sampling rate.

    Parameters:
        frequency (float): Frequency of the sine wave in Hz. Default is 1 Hz.
        sampling_rate (int): Number of samples per second. Determines resolution.
        amplitude (float): Amplitude of the sine wave. Default is 1.

    Returns:
        time (numpy array): Array of time points.
        signal (numpy array): Array of sine wave values.
    """
    # Calculate the period (T) of the sine wave
    period = 1 / frequency

    # Time array: generates time points for one period based on the sampling rate
    time = np.linspace(0, period, int(sampling_rate / frequency), endpoint=False)

    # Generate the sine wave signal
    signal = amplitude * np.sin(2 * np.pi * frequency * time)

    return time, signal



def generate_trapezoidal_signal(frequency=1, sampling_rate=100, amplitude=1, ramp_ratio=0.25):
    """
    Generates a trapezoidal signal with one period and allows variation of the sampling rate.

    Parameters:
        frequency (float): Frequency of the trapezoidal signal in Hz. Default is 1 Hz.
        sampling_rate (int): Number of samples per second. Determines resolution.
        amplitude (float): Amplitude of the trapezoidal signal. Default is 1.
        ramp_ratio (float): Fraction of the period allocated to the rising and falling ramps. Default is 0.25 (25%).

    Returns:
        time (numpy array): Array of time points.
        signal (numpy array): Array of trapezoidal signal values.
    """
    # Period of the trapezoidal signal
    period = 1 / frequency

    # Time array: generate time points for one period
    num_samples = int(sampling_rate / frequency)
    time = np.linspace(0, period, num_samples, endpoint=False)

    # Define key time regions based on ramp_ratio
    ramp_time = ramp_ratio * period  # Duration of rising and falling ramps
    plateau_time = period - 2 * ramp_time  # Duration of plateau

    # Initialize signal array
    signal = np.zeros_like(time)

    # Rising ramp
    rising_indices = time < ramp_time
    signal[rising_indices] = (amplitude / ramp_time) * time[rising_indices]

    # Plateau
    plateau_indices = (time >= ramp_time) & (time < ramp_time + plateau_time)
    signal[plateau_indices] = amplitude

    # Falling ramp
    falling_indices = (time >= ramp_time + plateau_time) & (time < period)
    signal[falling_indices] = amplitude - (amplitude / ramp_time) * (time[falling_indices] - (ramp_time + plateau_time))

    return time, signal




if __name__ == '__main__':
    # Factors for transfer function of 2013/35/EU for low action level limtis for B-field
    # In SI UNITS!!
    V_0 =   100 / 12 * 1e-6 # T
    
    # corner frequencies of 2013/35/EU
    # For B Als
    w_1 = 3e3 * 2 * np.pi
    w_2 = 300 * 2 * np.pi
    w_3 = 25 * 2 * np.pi
    w_4 = 8 * 2 * np.pi
    
    # Dicitonary normally holds various different weighting fucntion coefficients
    Weighing_functions = {
        '2013/35/EU':{
            'limits_B': {
                # Tab B2 1st column
                'LAL': {'num': [-1j / (w_1 * w_2 * w_4), -1 / (w_1 * w_4), 0, 0],
                        'den': [V_0 * -1j / (w_1 * w_3 * w_4), \
                                   V_0 * -1 * (1 / (w_1*w_3) + 1 / (w_1*w_4) + 1 / (w_3*w_4)),  \
                                  V_0 * 1j * (1 / w_1 + 1 / w_3 + 1/ w_4),
                                  V_0]
                    }}}}
    
    
    for sf in [1e5, 1e6, 1e7, 1e8]:
        # sampling frequency
        sampling_f = sf
        time, signal = generate_trapezoidal_signal(frequency = 50, sampling_rate = sampling_f)
        
        # coefficients of weighing function in filter representation
        b = Weighing_functions['2013/35/EU']['limits_B']['LAL']['num']
        a = Weighing_functions['2013/35/EU']['limits_B']['LAL']['den']
        
        # Taking absolute values
        a = [np.abs(a_i) for a_i in a]
        b = [np.abs(b_i) for b_i in b]
        
        # Constructing discrete digital filter by bilinear transformation
        b, a = scipy.signal.bilinear(b, a, sampling_f) # sampling frequency in Hz
        
        # filtering of signal
        filt_sig = scipy.signal.lfilter(b, a, signal)
        
        # plot of signal and filtered signal
        plt.figure()
        plt.title('Sampling frequency %.0f'%sampling_f)
        plt.plot(time, signal, label = 'input signal')
        plt.plot(time, filt_sig, label = 'filtered tf')
        
        plt.xlabel('time')
        plt.ylabel('Amplitude')
        
        # try results with second order sections
        sos = scipy.signal.tf2sos(b, a)
        
        filt_sig_sos = scipy.signal.sosfilt(sos, signal)#, zi = scipy.signal.sosfilt_zi(sos))
        
        plt.plot(time, filt_sig_sos, label = 'filtered sos')
        
        plt.legend()

![image](https://github.com/user-attachments/assets/f85c95bc-ccf8-4721-9df1-6ee6ee4553cc)

The desire would be that the output of the filtered signal stays stable, also for high frequencies

**Comment by DietBru** [comment]
> Describe the solution you'd like.
>
> A more stable filter response for a broad frequency range, especially for higher frequencies.
> Filters as stable as in MATLAB or LabViewI

It seems like your filter coefficients produce an unstable filter, i.e., very high amplifications for high frequencies.  You can use [dbode] and [bode] to verify that. Thus I am closing this issue, since that is not in the realm of SciPy. @MarioSteinerEMF, feel free to reopen this issue, if you disagree.



[dbode]: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.dbode.html
[bode]: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.bode.html

**Comment by DietBru** [comment]
As written [here](https://github.com/scipy/scipy/issues/22035#issuecomment-2551661828), not planed.
