### ISSUE TITLE
nth derivatives of numpy and scipy.special elementwise functions

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#2489]
Would this be in the scope of scipy?  I've partially implemented this for testing automatic differentiation and I'm wondering if it would be of more general interest.  To be clear, I'm not referring to numdifftools-style finite difference estimates.  I don't have a clear idea for the interface, although I am currently using something like an extra nthderiv=0 keyword arg for each function.

**Comment by person142** [comment]
I'm going to close this because:

- `special` has an enormous API and plenty of functions that need work. I believe this change would greatly expand the surface area for issues, and I don't want to do that
- At this point adding keywords would break `cython_special`

I'm fine with reopening if there is push back.
