### ISSUE TITLE
distributions cdf, sf evaluation in the wrong tail

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#2509]
If we calculate cdf or sf from the wrong tail, then we often run into numerical problems

for example :
gh-2238 numerical issues in the wrong tail, discrete, hypergeom
gh-2494 fix for truncnorm

two problems that I think still exist for some distributions
- missing calculations for _sf : when sf is defined as 1 - cdf, then we can have numerical problems in the right tail
- no automatic dispatch to the numerically more precise tail calculations: If we can recognize if the probabilities are calculated for one of the tails, then we could use either the _cdf or the _sf calculations to get more precise answers.

gh-2494 does a similar conditional calculation based on the support of the distribution.

I haven't checked any other example, but for example the generic method in rv_continuous is

```
    def _sf(self, x, *args):
        return 1.0-self._cdf(x,*args)
```

which means that we use in some cases integrate.quad on the wrong tail.

**Comment by jonycgn** [comment]
hi,

i'm working on an implementation of the generalized gaussian distribution (this one: https://en.wikipedia.org/wiki/Generalized_normal_distribution#Version_1) and plan on contributing that once i have implemented all the parts.

while testing my implementation against its special cases (gaussian and laplacian), i noticed that the sf and isf of the laplacian aren't accurate in the upper tail (where they should be accurate). i haven't followed all of the discussion above, but it seemed this is the right place to report my finding.

for any symmetric distribution, it seems easy enough to define the sf in terms of the cdf as:

def _sf( self, x, pars ):
    return self._cdf( -x, pars )
    
def _isf( self, x, pars ):
    return -self._ppf( x, pars )

i did so in my implementation. i don't know enough about the implementation of the base class to decide whether it would make sense to define these automatically for all symmetric distributions. but it seems, at least for the laplace distribution, this should be fixed.

thanks!

**Comment by rgommers** [comment]
That would require ``rv_continuous`` to know whether a distribution is symmetric or not. So implement by a ``self._issymmetric = False`` addition to that class (plus the needed if/else in generic ``_sf/_isf``), and then add ``_issymmetric = True`` to the relevant classes that don't yet have a more specialized implementation of ``_sf`` and ``_isf``. Is that better than adding a few ``def _(i)sf`` statements to those distributions? Maybe depends on how many distributions we are talking about. Do you have an idea for which ones this would help?

**Comment by ev-br** [comment]
Before adding an extra flag, I suggest first trying to dispatch in generic methods (cdf, sf) to _cdf or _sf conditionally depending on the value of x relative to, say, median (_ppf(0.5)). I mean, here: https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L1688
instead of a single `np.place` call, make it two, one with _cdf, another one with _sf

It surely adds some overhead, which needs to be measured.

**Comment by jonycgn** [comment]
i think we might be talking about two orthogonal issues here.

A) one thing is that for calculations based on the cdf/sf, we should use the cdf for the lower tail and the sf for the upper tail. to be clear, this is when *calling* the cdf/sf methods. i don't know to what parts of scipy.stats this applies, because i don't know the code well enough.

B) the other issue is in *implementing* the methods. implementing the sf via 1-cdf is, numerically speaking, never a good idea. you're asking for cancellation, and no matter what the calling code does, it will always get low accuracy in the upper tail. so i find the documentation in rv_continuous somewhat misleading. here:
https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L1366
it says you would almost never want to overload _sf/_isf. but for the sake of accuracy, yes, you would most definitely want to do it!

for symmetric distributions, issue B can be fixed easily and with high accuracy as shown in my previous comment. i don't currently know what distributions, other than the laplace, suffer from this problem.

**Comment by jonycgn** [comment]
another thought, similar to @ev-br's comment earlier:

given that some distributions need to make case distinctions internally when implementing the _cdf/_ppf/_sf/_isf methods (for instance, using numpy.where), maybe to minimize the overhead of that, and make the code overall most efficient would be to require the _xxx versions of the methods to only give valid results for their respective tails. i.e., require that:

dist._cdf(x) yields valid results only for x <= dist._ppf( .5)
dist._ppf(x) yields valid results only for x <= .5
dist._sf(x) yields valid results only for x > dist._ppf( .5)
dist._isf(x) yields valid results only for x > .5

then, some of these implementations could be simplified, and in the base class, we could dispatch automatically to the right tail when doing calculations, or when the non-underscored versions of the methods are called.

this might be not worth the trouble, or even cause other problems, but i thought i'd share the idea ...

**Comment by josef-pkt** [comment]
> require the _xxx versions of the methods to only give valid results for their respective tails. i.e., require that:

I don't think that's a good idea and might cause problems and complicated code all over the place.

main problem that I see, besides having the branching overhead included, is that in some/many generic cases we end up with circular definition:

When we don't have _ppf or median in explicit form (or as special function), then ppf(q) is calculating by finding the root `x such that cdf(x) = q`  numerically.
In some cases this can be expensive, besides being a circular definition.

IIRC: one possible generic improvement: sf is defined as 1-cdf, if cdf is not explicit, i.e. _cdf not defined, then we integrate the pdf from `a.` to x instead of integrating the sf from x to `.b`.

I think, improvements with choosing the right tail need to be evaluated and implemented case by case, or distribution specific.

**Comment by jonycgn** [comment]
> main problem that I see, besides having the branching overhead included,

well, the whole point in the idea was *reducing* branching overhead. consider the following situation: a user makes calculations based on cdf/sf by branching to the right tail. a distribution implements the _cdf/_sf again by doing some kind of case distinction. the user is being punished for writing accurate code, because branching now happens twice without necessity. i was suggesting to consolidate the branching to one abstraction layer.

but i guess you're right, and that layer shouldn't be the base class, but the actual distribution. in any case, avoiding sf=1-cdf wherever possible seems the right thing to do.
