### ISSUE TITLE
The sparse .sum() method with uint8 dtype does not act like the corresponding numpy method.

### ISSUE THREAD

**Issue by cowlicks** [scipy/scipy#2534]
With NumPy calling the `.sum()` method along an axis upcasts the dtype from uint8 to uint64, probably to prevent rolling over back to 0:

    In [9]: np.matrix([[1, 255],
                       [0, 0]], dtype=np.uint8).sum(1)
    Out[9]: matrix([256,   0], dtype=uint64)

With the sparse package in SciPy, there is no upcasting, so 255 + 1 rolls over to 0. For the same data we get:
     
     In [11]: sp.csc_matrix(np.array([[1, 255],
                                      [0, 0]], dtype=np.uint8)).sum(1)
     Out[11]: 
     matrix([[0],
             [0]], dtype=uint8)

The shapes are different too...

So should Sparse copy numpy's upcasting behavior?

**Comment by Tiepies** [comment]
@cowlicks @pv It that seems the `.sum()` method of SciPy sparse matrices is still not in line with the NumPy  `.sum()` method in terms of upcasting behavior. The original example of this issue still results in the same discrepancy (integer overflow for sparse matrices, upcasting for dense matrices) (SciPy 0.18.0.dev0+b2eea7c):

```
In [19]: np.matrix([[1, 255],
                    [0, 0]], dtype=np.uint8).sum(1)
Out[19]: 
matrix([[256],
        [  0]], dtype=uint64)


In [20]: sp.csc_matrix(np.array([[1, 255],
                                 [0, 0]], dtype=np.uint8)).sum(1)
Out[20]: 
matrix([[0],
        [0]], dtype=uint8)

```

**Comment by pv** [comment]
Fixable via `np.int_ -> np.integral`, `np.float_ -> np.floating` in the lines touched by gh-2549

**Comment by maniteja123** [comment]
If I remember it correctly, it should be ``np.integer`` right ? Please correct me if I am wrong.

**Comment by Tiepies** [comment]
@maniteja123  `np.integer` seems to be the correct fix, yes. 

I can easily submit a PR with the fix, but I am unsure what test to add to sparse/tests/test_base.py. The `.math_dtypes` attributes of the matrix class based tests only consist of `[np.bool_, np.int_, np.float_, np.complex_]`, so `.test_sum()` never tests for integer upcasting behavior.

**Comment by cowlicks** [comment]
@Tiepies looking at my previous PR I think `test_base.py` is okay.

I have not seen `np.integer` and `np.floating` before, so maybe they are new. Which would explain why they are not used in the sparse tests.

**Comment by Tiepies** [comment]
@cowlicks your PR indeed tested for this, but PR #5213 reduced the type coverage by replacing `self.checked_dtypes` with `self.math_dtypes`, which means the upcasting behavior is not tested for anymore. I am not comfortable touching the tests, because I do not fully grasp the reason for this change.

**Comment by perimosocordiae** [comment]
Yep, that PR was my doing. The whole dtype testing situation is still a bit of a mess, unfortunately, but [this comment](https://github.com/scipy/scipy/pull/5213#issuecomment-138990519) should hopefully clear up some confusion.

The takeaway is that we haven't ever been testing for correct upcasting behavior, though we thought that we were before my PR.

Possible fixes include:
 1. adding `np.int8` to `math_dtypes` (will likely require fixing other bugs to make things pass)
 2. changing `test_sum` to use `checked_dtypes` instead of `math_dtypes`

In the long run, we want to have option (1), but for the scope of this PR, option (2) should be sufficient.
