### ISSUE TITLE
wilcoxon() function does not return z-statistic

### ISSUE THREAD

**Issue by numpand** [scipy/scipy#2625]
stats\morestats.py - wilcoxon function
documentation for version of 0.10.0 stated that the first return value is a z-statistic, but the function returned a t-statistic.  However, looking at the 0.12.0 version, it appears that documentation has been amended to reflect the code and not the other way around which would appear more logical.  Any idea why?  If it is desirable to leave the current return values, would it be possible to add the z-statistic to the return list as well?  Thanks.

**Comment by faroit** [comment]
I would also vote in favour to return the z value as this would make it easier to calculate the effect size z/sqrt(N)

**Comment by SamyStyle** [comment]
Returning the z value would be super to easily report the statistics.

**Comment by rgommers** [comment]
This could be done in a backwards-compatible way now with @ev-br's suggested ``Bunch`` on steroids: https://github.com/scipy/scipy/issues/3665#issuecomment-106085454

So let's say we want to add the Z value and change this issue from defect to enhancement request.

I won't have time to work on this any time soon, but if someone wants to have a go at this I'd be happy to help/review.

**Comment by abhinavkgp** [comment]
I believe that even if we return Z value, it is still not possible to determine one-sided result (whether x-y>0 or y-x>0) using this two-sided statistic, due to the following:

Code:
T = min(r_plus, r_minus)
r_plus = np.sum((d > 0) * r, axis=0) #Always positive
r_minus = np.sum((d < 0) * r, axis=0) #Always positive

Reasoning:
So, if you swap x and y, T will still be the same, z statistics will still be the same

Final Thoughts:
We should also aim to return in some way that whether r_plus was used or r_minus was used (through a flag maybe) in order to know the result of a one-sided tailed test

**Comment by jkokatjuhha** [comment]
Any chance this (rejection direction) will get fixed sometime soon? Just got bit by this bug.

**Comment by KrisITB** [comment]
In case if someone like me needs that Z stat and couldn't be bother doing the maths reversing return:
copy paste into your project wilcoxon() from: https://github.com/scipy/scipy/blob/v1.2.1/scipy/stats/morestats.py#L2709-L2806

add: 
    from numpy import (asarray, compress) # requiered for local modification
    from scipy.stats import (find_repeats, distributions)
    from math import sqrt

replace the:
    return WilcoxonResult(T, prob)
with:
    return T, prob, z
add a comment at the top to credit scipy.stats library 
problem solved ;)

**Comment by daeh** [comment]
Still not possible to get the z-statistic and direction from `wilcoxon()`?

**Comment by mdhaber** [comment]
@swallan @DominicChm if you need a side project this looks useful
