### ISSUE TITLE
Off by one error in ndimage.map_coordinate when mode='wrap'

### ISSUE THREAD

**Issue by rainwoodman** [scipy/scipy#2640]
The interpolation coordinate is off by one in 'wrap' mode.

Test case:
a = array([0, 1, 0, -1.])
x = linspace(0, 8, 8, endpoint=False)
y = map_coordinate(a, [x], mode='wrap')
ynp = numpy.take(a, int64(x), mode='wrap')

Because x is strictly on a grid, one would expect y and ynp to be rather close.

The result is not:
y   ,    ynp
(9.8982237337064127e-15, 0.0),
 (0.99999999999999256, 1.0),
 (2.2376848637928326e-15, 0.0),
 (-0.99999999999999967, -1.0),
 (0.99999999999999256, 0.0),
 (2.2376848637928326e-15, 1.0),
 (9.8982237337064127e-15, 0.0),
 (0.99999999999999256, -1.0)

From y[4] it appears to be off by one.

**Comment by grlee77** [comment]
I was about to open an issue, but found this existing one that seems to be related.

simple example (output is from scipy 0.15.1):
```python
a = np.arange(4)
b = ndi.map_coordinates(a, [np.arange(12)], mode='wrap')
```
gives
``array([0, 1, 2, 3, 1, 2, 0, 1, 2, 0, 1, 2])``

while I would have expected:
``array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])``

The behaviour I expected is what @WarrenWeckesser indicated in his nice response here:
http://stackoverflow.com/questions/22669252/how-exactly-does-the-reflect-mode-for-scipy%E2%80%8C%E2%80%8Bs-ndimage-filters-work

The other modes all behave as expected (at least for integer coordinates)

**Comment by dadkins** [comment]
I am seeing something similar in affine_transform, with potentially more than one off-by-one errors in play:

```python
>>> affine_transform(np.array([1., 2., 3., 4.]), np.array([[1.]]), output_shape=(13,), order=1, mode='wrap')
array([ 1.,  2.,  3.,  4.,  2.,  3.,  1.,  2.,  3.,  1.,  2.,  3.,  1.])
```
I am seeing even stranger behavior when trying to scale by a factor of 2, in 'wrap' and 'reflect':

```python
>>> affine_transform(np.array([1., 2., 3.]), np.array([[0.5]]), output_shape=(9,), order=1, mode='wrap')
array([ 1. ,  1.5,  2. ,  2.5,  3. ,  1.5,  2. ,  2.5,  1. ])
```
instead of
```python
array([ 1. ,  1.5,  2. ,  2.5,  3. ,  2.,  1. ,  1.5,  1. ])
```
(The wrapping is supposed to happen in the input coordinates according to the documentation for affine_transformation.)
And this is odd:
```python
>>> affine_transform(np.array([1., 2., 3.]), np.array([[0.5]]), output_shape=(9,), order=1, mode='reflect')
Out[25]: array([ 1. ,  1.5,  2. ,  2.5,  3. ,  2.5,  3. ,  2.5,  2. ])
```
Where did the 2.5 between the two 3's come from?

**Comment by shoyer** [comment]
I agree this is a bug, e.g., see this StackOverflow question: https://stackoverflow.com/questions/49280404/shift-interpolation-does-not-give-expected-behaviour

**Comment by shoyer** [comment]
Interestingly, this same issue appears to affect the other `mode` options, too -- at least everything other than `mirror`.

The fundamental issue appears to come down to the internal model used for keeping track of boundary conditions. As noted in [this StackOverflow answer](https://stackoverflow.com/questions/49280404/shift-interpolation-does-not-give-expected-behaviour), ndimage appears to use the following internal model:
`mode='periodic'`:
```
0--1--2--3-...-k              0--1--2--3-...-k              0--1-- ...
               0--1--2--3-...-k              0--1--2--3-...-k      ...
```
`mode='constant'`:
```
      0--1--2--3-...-k
...cccc              cccc...
```

Basically, the output gets glued together *exactly on the boundaries*.

In contrast, the *documented behavior* of the `mode` argument would glue together the input arrays, i.e., at one input array element *past* the boundary.

Here here's a comparison of the behavior for each `mode` option:
```python
from scipy import ndimage
import numpy as np
import matplotlib.pyplot as plt

fig, axes = plt.subplots(5, 3, figsize=(10, 12), sharex=True, sharey=True)
input = np.array([-2, -1, 0, 1, 2], float)
x = np.linspace(-2, 6, num=1000)
k = 100
order = 3

for mode, (ax0, ax1, ax2) in zip(
    ['reflect', 'constant', 'nearest', 'mirror', 'wrap'], axes):
  y = ndimage.map_coordinates(input, [x], order=order, mode=mode)
  ax0.scatter(np.arange(input.size), input)
  ax0.plot(x, y, '-')
  ax0.set_title(f'mode={mode}, current')

  pad_mode = {
      'nearest': 'edge', 'mirror': 'reflect', 'reflect': 'symmetric'
  }.get(mode, mode)
  padded = np.pad(input, k, mode=pad_mode)
  y2 = ndimage.map_coordinates(padded, [k+x], order=order, mode=mode)
  ax1.scatter(np.arange(padded.size) - k, padded)
  ax1.plot(x, y2, '-')
  ax1.set_title(f'mode={mode}, documented')

  ax2.plot(x, y2 - y, '-')
  ax2.set_title('documented - current')

for ax in axes.ravel():
  ax.set_xlim(x[0] - 0.5, x[-1] + 0.5)
  ax.set_ylim(-2.5, 2.5)

fig.subplots_adjust(wspace=0.1, hspace=0.3)
```
![image](https://user-images.githubusercontent.com/1217238/69029185-15416c00-0989-11ea-957e-311065d89e6b.png)

As you can see, the only `mode` with exactly no difference from the documented behavior is `mode='mirror'`, although `mode='nearest'` comes very close. Also, there can be small difference between the "current" and "documented" behavior even inside the interpolated region, because the boundary is handled incorrectly.

The issue is particularly problematic for `mode='reflect'`, `mode='reflect'` and `mode='wrap'` because it introduces discontinuities. `reflect` in particular looks terrible on the boundary.

Unfortunately, I suspect that fixing this could be somewhat challenging for two reasons:
1. The current behavior has existed for a long time, so assuredly people have come to expect and rely upon it. At some point our bugs become features :(.
2. The documented behavior needs to form splines over more than merely the bounds of array itself, but also the entire region covered by the requested coordinates (plus some padding to avoid edge effects), although as @charris notes this might be avoided in some cases like `mode='wrap'`.

**Comment by shoyer** [comment]
The plot for `order=1` is also somewhat illuminating:
![image](https://user-images.githubusercontent.com/1217238/69034843-fea21180-0996-11ea-961f-8adad998e37e.png)

Only `mode='wrap'` has different values at integer shifts from the original signal.

**Comment by rainwoodman** [comment]
The discussion at #2640 mentioned the difference was due to treating the array as pixels (current) or as data (documented); or using internal (current) vs external/padded (documented) interpolation coefficients. 

What about adding an argument or a new set of modes to indicate this difference?

**Comment by rgommers** [comment]
> The discussion at #2640 mentioned the difference was due to treating the array as pixels (current) or as data (documented); or using internal (current) vs external/padded (documented) interpolation coefficients.

The issue for document that properly is gh-9746.

> What about adding an argument or a new set of modes to indicate this difference?

Hmm, adding more modes sounds very unhealthy. There may be a bug in just this function that could still be addressed.

> The current behavior has existed for a long time, so assuredly people have come to expect and rely upon it. At some point our bugs become features :(.

Part of it is from last year I think, see gh-8537.

**Comment by rainwoodman** [comment]
while reading up 8537, I realized the difference between documented behaviour of reflect and mirror is compensating for the off by 1 -- in terms of modes, we are just missing the corresponding 'by the edge'(reflect) case for wrap. See here:

https://github.com/scipy/scipy/pull/8537/files#diff-ffec5f90a1593619aee38809afb0d503R40

Still, the behaviour of reflect is unexpected, as @shoyer's second plot shows near x=+-5; it is hard to imagine a use case purposely depending on having a discontinuity in the interpolated data like that.

**Comment by rainwoodman** [comment]
How large is the support of the spline filters (not sure if support is the proper term. I borrowed it from convolution kernels)? Is it infinite?

In https://github.com/google/jax/pull/1711, the implementation padded the image to cover the entire query range -- I think we probably need to enlarge that by the support of the spline filter. And this approach won't work if the support is infinite.

**Comment by shoyer** [comment]
> > The current behavior has existed for a long time, so assuredly people have come to expect and rely upon it. At some point our bugs become features :(.
> 
> Part of it is from last year I think, see [gh-8537](https://github.com/scipy/scipy/pull/8537).

My reading of #8537 is that it does the right thing, adding proper handling of boundary conditions for reflect, mirror and constant. But it doesn't actually switch to them yet. As @jaimefrio writes: "None of the interpolation functions can yet use an image filtered with any mode other than 'mirror', but I think it's better to get this in first."

@jaimefrio's PR doesn't fix constant and nearest yet, but here I think we can make use of the nice proper bspline that they have finite support over only `1 + order` knots.

**Comment by charris** [comment]
@rainwoodman What do you mean by spline filters? The ones that are used to determine the spline coefficients are IIR filters.

**Comment by shoyer** [comment]
> @rainwoodman What do you mean by spline filters? The ones that are used to determine the spline coefficients are IIR filters.

Indeed, I was wrong here, as is easy to check empirically. I think you only end up with finite support for the filters used to determine spline coefficients if `order<=1`.

So for `mode='constant'` and `mode='nearest'`, it appears we will need to accept some level of approximation.
