### ISSUE TITLE
ConvexHull does not support masked arrays

### ISSUE THREAD

**Issue by fmaker** [scipy/scipy#2675]
Using masked arrays with scipy.spatial.ConvexHull() results in simplices that are masked in the array.  Example:

``` python
import scipy as sp
import numpy as np

X_m = np.ma.array(X,mask=m) # returns X array with mask defined by m
hull = sp.spatial.ConvexHull(X_m) # calculates convex hull on masked points

for simplex in hull.simplices:
      print X_m[simplex,1],X_m[simplex,0]

```

prints:
[-- -122.052021] [-- 37.324186]
[-- --] [-- --]
[-122.499217 -122.503319] [37.572598 37.595792]
[-122.263957 --] [37.831964 --]

If you remove the masked rows:

``` python
X_m = np.ma.compress_rows(X_m)
```

It prints the correct simplices:
[-121.471407 -121.464504] [ 38.408566  38.40513 ]
[-121.471407 -121.471454] [ 38.408566  38.408614]
[-121.464129 -121.371867] [ 38.429389  38.448629]
[-121.420056 -121.464504] [ 38.41     38.40513]

**Comment by souravsingh** [comment]
Is the issue fixed?

**Comment by tylerjereddy** [comment]
@souravsingh @pv 

Yes, this appears to be fixed. Testing in the `0.19` dev branch with `Delaunay`, `ConvexHull`, and `Voronoi` raises `ValueError: Input points cannot be a masked array` when a masked array is provided for the `points` argument. 

As an added bonus, because `SphericalVoronoi` passes through `ConvexHull` to generate the Delaunay triangulation on a sphere, it will also raise a `ValueError` when provided with masked input. Nikolai & I hadn't thought of adding this in though, so if the algorithm is ever modified in such a way that it no longer depends on the `ConvexHull`, the input checking will be lost -- so I guess that's a bit less robust, but it will likely be quite some time (if ever) before an algorithm that skips the convex hull is implemented.

**Comment by rgommers** [comment]
Thanks, closing then.
