### ISSUE TITLE
Solution of iterative solvers can be less accurate than tolerance (for succesful runs!)

### ISSUE THREAD

**Issue by michaelwimmer** [scipy/scipy#2694]
What I report here is a rather minor issue in practice, I believe, but still should be properly documented (caused me a bit of headache today). Hence, I open this issue.

The iterative solver in scipy.sparse.linalg.isolve have a tolerance parameter that specifies the "desired exactness" of the solution. In particular, an approximate solution
x of a linear system of equations A x = b should obey
- either || A x - b || < tol
- or || A x - b || / || b ||
  At least, this is how I understand the docstring (and the documentation of the underlying fortran routines).

Solutions however do not always obey this criterion, albeit the error is just a little bit higher. The following program shows this problem 

```
import numpy as np
import scipy.sparse.linalg as la

np.random.seed(31)
a = np.random.rand(50, 50)
b = np.random.rand(50)

x, info = la.cgs(a, b, tol=1e-10)

if info == 0:
    print "Convergence achieved:"
    print "abs. norm of residual", np.linalg.norm(a.dot(x)-b)
    print "rel. norm of residual", \
        np.linalg.norm(a.dot(x)-b)/np.linalg.norm(b)
```

which gives the output 

```
Convergence achieved:
abs. norm of residual 9.00731138893e-09
rel. norm of residual 2.43767337226e-09
```

i.e. somewhat larger errors than expected from tol=1e-10.

It depends on the matrix, I'd say 1 out of 10 seeds gives a larger error.

I traced the problem back to the underlying Fortran routine: The problem is that the residues in the iterative routine are not computed as || A x - b ||, but are succesivley accumulated from previous steps. This accumulates rounding errors, and at some point this residue is different from || A x - b || by a significant factor. Since the accumulated residue is used for the stopping criterion and not || A x - b ||, this then leads to the larger errors in || A x - b || as observed above.

In my tries, I saw similar things also for example for gmres, but I didn't investigate this systematically. I expect you can see this for any of the iterative routines.

I guess there could be two solutions:
- modify the iterative routines such that they compute the residual exactly at every step
- or mention in the docstring that the bound is a little bit loose due to rounding error.

**Comment by zimoun** [comment]
To be able to compare different algorithms, is it not preferable to keep the standard algorithm ? 
and so the possibility to obatin bad approximated residual.

Choosing the stopping criteria is a issue about iterative methods, since the exact residual is never computed and should always be approximated. 
(note: the exact residual requires an extra 'matvec' which should be computationnally consumming)

About 'gmres', the residual is approximated at the end of the Givens rotations. 
And for some matrices (in the general the random ones), the orthogonalization process should accumulate round-off error, and so, the approximated residual is less and less accurate.
A similar behavior about the loss of orthogonality arises in full gmres (no restart) when the number of iterations is becoming large.
A reorthogonalization process should be possible but it is not the standard algorithm.

**Comment by pv** [comment]
Tolerances made strict in gh-8400.
