### ISSUE TITLE
Mingw Gfortran on Windows?

### ISSUE THREAD

**Issue by pv** [scipy/scipy#2829]
So far we've kept to Fortran 77 due to needing g77 on Windows.

However, it seems to me Mingw32 gfortran-4.8.1 can compile a working Scipy, so perhaps it could be used for the next release? This would also allow including Fortran 90 code.

**Comment by rgommers** [comment]
bumped to 0.17.0

**Comment by sturlamolden** [comment]
This solves most of the problems discussed here:

https://github.com/numpy/numpy/wiki/Mingw-static-toolchain

What are the remaining problems?

**Comment by njsmith** [comment]
The status of Carl's mingw-w64 toolchain is, there are some remaining bugs
(esp. numerical accuracy for trigonometric functions), and more
importantly, a serious risk that it'll immediately bitrot b/c it's a bunch
of hacks that only Carl understands and that don't have upstream buy-in. So
we're trying to get that sorted out before we commit ourselves to it.

On Sun, May 10, 2015 at 9:07 AM, Sturla Molden <notifications@github.com>
wrote:

> This solves most of the problems discussed here:
>
> https://github.com/numpy/numpy/wiki/Mingw-static-toolchain
>
> What are the remaining problems?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy/scipy/issues/2829#issuecomment-100660734>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by sturlamolden** [comment]
So it solves the problems mentioned here but introduces a set of new ones... Great. :disappointed:

**Comment by carlkl** [comment]
The situation is not that bad. The features of the toolchain are summarized here: https://bitbucket.org/carlkl/mingw-w64-for-python/downloads/mingwpy-2015-04-readme.pdf. A lot of long standing problems are solved with this adapted mingw-w64 right now.

What is the situation for mingw-w64 based numpy and scipy?

Remaining numpy and scipy  failures are descriped in https://github.com/scipy/scipy/issues/4528#issuecomment-74672599. The OpenBLAS related errors are gone now during OpenBLAS development. Also OpenBLAS dgemv performance problem (https://github.com/xianyi/OpenBLAS/issues/532) for smaller sizes is hopefully solved now. (the latter is relevant for typical thano cpu usage)

Lost of precision failures in scipy and NaN/Inf mismatch https://github.com/numpy/numpy/issues/5194#issuecomment-64483191 is something that has to worked out in the math code of mingw-w64. The questions is, are the latter failures a show stopper to release openblas based numpy and scipy wheels? I made wheels for testing available at binstar: https://binstar.org/carlkl.

The easiest way right now to test the toolchain itself is to install the portable winpython distribution at https://winpython.github.io as it is configured to use mingw-w46 as default. 

I try right now to reduce the number of hacks necessary and to put all changes into forked projects at https://github.com/mingwpy. This is not released yet due to lack of spare time.

**Comment by matthew-brett** [comment]
Carl - it sounds as though now might be a good time to collect some effort to help you with the details here?   How about a Google hangout in the next few days?  We have a sprint on Wednesday in Berkeley,  where we could devote some time to the problem.  Cc'ing @ogrisel ...

**Comment by carlkl** [comment]
wednesday or thursday *next* week?

**Comment by matthew-brett** [comment]
Sorry - bad timing - but I am going to Cuba on Tuesday next week, and it's really impossible to do any internet voice thing from there.

**Comment by hiccup7** [comment]
@carlkl , Does this issue also apply to SciPy & NumPy with OpenBLAS?
https://github.com/JuliaLang/julia/issues/11258

**Comment by sturlamolden** [comment]
*"For an Intel CPU with hyperthreading, better OpenBLAS performance would occur by using the number of physical cores instead of logical cores. For example, blas_set_num_threads(CPU_CORES >> 1) For portability, I suggest Julia includes a new constant: CPU_PHYSICAL_CORES."*

This is not even correct. If you do this, a thread can be scheduled to one of the idle logical cores. Setting the bumber of threads to the number of logical cores is what gives the best performance. Even MKL uses the number of logical cores.

**Comment by sturlamolden** [comment]
See here what happens when we go from 4 threads (number of physical cores) to 8 threads (number of logical cores): 

http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/u/12464039/kdtree-jan21-simd.ipynb

Why? Because if you only have half as many threads as logical cores, each thread has a 50 % chance of being scheduled to an idle core.

**Comment by njsmith** [comment]
Is your claim that if you have 2 threads, 2 physical cores, and 4 total
logical cores (hyperthreads), that this is bad because there's a 50% chance
that both threads will be scheduled on the same physical core while leaving
the other one idle? Because that is not true at all, e.g. I know for a fact
that the Linux scheduler in this case will be sure to assign the two
threads to different physical cores whenever possible.

Determining the fastest number of threads for a given workload on modern
CPUs is a very complex matter, which depends on the cache miss rate, the
size of the shared and unshared caches between different execution units,
the extent to which different threads have overlapping working sets, etc.
Sometimes you are even best off doing things like running one thread per
*socket* (because multiple cores in the same physical package generally
share -- and can end up fighting over -- L3 cache).

Anyway, this is all 100% a topic for the OpenBLAS bug tracker, not numpy or
Julia's...

**Comment by stonebig** [comment]
Link to the "funding request"  on the mingwpy subject: https://mingwpy.github.io/proposal_december2015.html

Is it stil true that this problem as an impact on  "odeint / sundials" progress ?  https://github.com/scipy/scipy/pull/2818

**Comment by Juanlu001** [comment]
Thanks for linking, I was not aware of its existence. Please keep us posted about NumFOCUS decision :)

**Comment by rgommers** [comment]
@Juanlu001 the full proposal was just accepted. I just sent a PR to update http://mingwpy.github.io/roadmap.html with a sentence saying that.

**Comment by stonebig** [comment]
wunderbar !

**Comment by Juanlu001** [comment]
Congratulations! :tada:

**Comment by rgommers** [comment]
> Is it still true that this problem has an impact on "odeint / sundials" progress ? #2818

I was starting to type "yes, because ..." but then realized that we did drop the numpy-vendor (mingw32) based toolchain a few weeks ago. And that was the issue - we relied on g77 for Windows binaries. So even before we start using MingwPy for Windows wheels on PyPi (i.e. right now), we can start using Fortran 90/95 code I think. 

Does anyone see a problem with that?

**Comment by njsmith** [comment]
> we can start using Fortran 90/95 code I think. 

So the logic here is that for now, ifort will be the only supported fortran compiler for building scipy on windows, and eventually (if everything goes well) gfortran will also be supported? That sounds plausible, since I'm pretty sure @cgohlke and Anaconda (@ilanschnell?) are already using ifort, and WinPython IIUC is already using Carl's gfortran builds (right @stonebig?). I'm not as certain about Canopy (@cournape) or Python(x,y) (@mindw, @yuvalj) -- anyone want to object?

**Comment by mindw** [comment]
Python(x,y) uses uses ifort.

**Comment by rgommers** [comment]
> So the logic here is that for now, ifort will be the only supported fortran compiler for building scipy on windows, and eventually (if everything goes well) gfortran will also be supported?

Pretty much, but minor correct: ``gfortran`` is already supported, in the sense that it can build scipy just fine. Only distributing binaries is problematic, hence we don't do that and everybody else uses ``ifort`` to distribute their own builds.

**Comment by ilanschnell** [comment]
Yes, we use `ifort` on Windows to compile scipy for Anaconda.

**Comment by stonebig** [comment]
Currently, WinPython is mainly prepared with @cgohlke wheels for the scipy stack, as:
- MKL is king of the performance on Intel,
- Scipy is very sensitive to any non-purity in its compilation/alignment options.

**Comment by carlkl** [comment]
It's true that scipy compiles with mingwpy/gfortran on the windows platform without compile or link errors. The prerequisite is a mingwpy compiled numpy build. Hence an officially scipy build compiled with mingwpy/gfortran will be available with the advent of a rigorously tested numpy based on mingwpy and OpenBLAS. The necessary code changes for numpy has been withdrawn due to some side effects some weeks ago. This numpy customization has to be corrected and resubmitted to the numpy repository. This is an essential part of the recently confirmed mingwpy proposal.

One nice feature of scipy-1.6.x is the Cython api for LAPACK and BLAS: https://github.com/scipy/scipy/pull/4021. It means in effect that a python package depending on specific BLAS/LAPACK features can be developed with the help of the Scipy Cython API *without* becoming dependant on the specific BLAS implementation of numpy. The hope is, that much less packgages with a dedicated *numpy+MKL* dependancy are around.

BTW the latests numpy, scipy *test* builds (based on local patches and mingpwy, OpenBLAS) are about 4 months old and can be found here: 
- https://anaconda.org/mingwpy/numpy (1.9.2)
- https://anaconda.org/mingwpy/scipy (1.6.0)

Here: https://anaconda.org/carlkl/all are some more and somewhat older variants. numpy-1.9.3 and scipy-1.6.1 and newer releases are in the pipeline. 

For the existings builds there are some test failures

- FAIL: test_optimize.TestOptimize.test_minimize
- FAIL: test_optimize.TestOptimize.test_powell
- FAIL: test_ltisys.Test_bode.test_06
- FAIL: test_ltisys.Test_freqresp.test_pole_zero

this happens only on 32 bit

- FAIL: test_decomp_update.TestQRupdate_F.test_Mx1_economic_rank_1
- FAIL: test_decomp_update.TestQRupdate_F.test_Mx1_economic_rank_p
- FAIL: test_decomp_update.TestQRupdate_F.test_economic_rank_1
- FAIL: test_decomp_update.TestQRupdate_F.test_economic_rank_p
- FAIL: test_decomp_update.TestQRupdate_F.test_neg_strides_economic_rank_1
- FAIL: test_decomp_update.TestQRupdate_F.test_neg_strides_economic_rank_p
- FAIL: test_decomp_update.TestQRupdate_F.test_non_itemsize_strides_economic_rank_1
- FAIL: test_decomp_update.TestQRupdate_F.test_non_itemsize_strides_economic_rank_p
- FAIL: test_decomp_update.TestQRupdate_F.test_non_native_byte_order_economic_rank_1
- FAIL: test_decomp_update.TestQRupdate_F.test_non_native_byte_order_economic_rank_p
- FAIL: test_decomp_update.TestQRupdate_F.test_non_unit_strides_economic_rank_1
- FAIL: test_decomp_update.TestQRupdate_F.test_non_unit_strides_economic_rank_p
- FAIL: test_decomp_update.TestQRupdate_F.test_overwrite_qruv_rank_1_economic

this happens on python-3.4.amd64
- ERROR: test_fortran.test_fortranfiles_read
- ERROR: test_fortran.test_fortranfiles_write
  - OSError: Sizes do not agree in the header and footer for this record - check header dtype 

this errors pops up because there is an additional byte at the end of the footer

This picture may change with future builds of numpy scipy

**Comment by mrslezak** [comment]
Not sure if this is in the right discussion, but I saw Anaconda people speaking of compiling with ifort.exe.  I can compile NumPy with MKL or OpenBLAS no problem w/ MSVC14, but on SciPy I get an error "no fortan compiler found" about halfway through the build.  Obviously ifort is available.  Do you modify the build files at all in SciPy to get it to compile?  Thanks.

**Comment by cournape** [comment]
Building scipy with MSVC and Intel Fortran compiler is supported. Just be sure to pass `--fcompiler=intelvem` (64 bits) to the build_ commands. If that does not work, please send a message to the scipy ML, as this is off-topic for this issue.

**Comment by gfyoung** [comment]
@mrslezak : You need to have `ifort.exe` in your PATH.  In addition, make sure that the appropriate environment is set up for your build by running `psxevars.bat <arch>` before doing so.

@cournape : It may actually not be necessary to pass in the `fcompiler` arg if you have your environment set up appropriately.  I can't say for sure since I can't test it, but I don't have to pass in any `fcompiler` arg on 32-bit.

**Comment by rgommers** [comment]
Removed the 0.18.0 milestone - this is not tied to a particular release anymore. Once we can build binary wheels for Windows, we'll upload them for the latest existing releases.

The g77 vs. gfortran thing is resolved: g77 is not supported anymore. Fortran 90/95 can be used in Scipy.

**Comment by pv** [comment]
This issue is resolved (pending only merging the numpy distutils patch), closing.
