### ISSUE TITLE
ksone fitting

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#2834]
The scipy.stats.ksone distribution has shape parameter n which is an integer or is floored to an integer, so the likelihood is not differentiable with respect to this shape parameter.  This makes the generic continuous distribution fitting not really applicable to this distribution, because it tries to estimate this non-existent derivative using finite-differences.  Maybe it would be better to just disable fitting?  Or more ambitiously to add estimation code to deal with the fact that the shape parameter n is an integer?

**Comment by mdhaber** [comment]
They are excluded from fitting tests, so it sounds like this can be closed.
Distributions with integer parameters can now be fit with `scipy.stats.fit`. There's a tiny bit of code to add to make that work with `ksone`, but I don't think this issue is needed to track it because it's part of a larger effort.
