### ISSUE TITLE
Create a proper LTI class capable of managing both CT and DT systems or a class hierarchy

### ISSUE THREAD

**Issue by callegar** [scipy/scipy#2912]
Scipy currently includes an lti class, however, this has some issues and overheads and is not always used in a consistent way:

1) It is stated to be limited to continuous time systems, but is then abused for discrete time ones when used as a parameter in dlsim, dlstep, dimpulse, etc.

2) It creates a non-consistent treatment of continuous and discrete-time systems, since for continuous ones impulse, step and output response can be obtained directly from the class, while for discrete ones it compels to use extra functions, passing the class as a parameter.

3) It incurs an overhead since it memorizes at the same time all the possible representations of the system ('tf', 'zpk' and 'ss') and recomputes all of them whenever one is changed, rather than lazily obtain the representations only as needed.

I suggest fixing 1), 2) and 3) by either

PLAN A (minimal)
--------------------------

Add a timestep parameter to the class (e.g. T). When this is 0, the system is continuous time, when it is 1, the system is discrete time. This would let all the methods present for the current LTI class also work for discrete time systems.
Then getters could be used to update the representations, rather than setters, to avoid unneeded overheads.

PLAN B
-----------

Create a proper LTI hierarchy, where an abstract LTI is subclassed in a continuous time and a discrete time one, as well as a 'tf' (ba), 'zpk' or 'ss' representation for each. Let each subclass of 'tf', 'zpk' or 'ss' accept each other class in initialization, to convert between representations.

Probably A is easier and easier to make compatible with the current code base, but B is more elegant and makes better advantage of an object oriented language like Python.

**Comment by befelix** [comment]
Is anyone working on this? This seems like a pretty major shortcoming for anyone who wants to build something control related on top of scipy.

I'll gladly code this up if nobody else is.

**Comment by endolith** [comment]
1. Why does the discrete-time system object need to know the sampling frequency?  The filter design functions use normalized frequency, for instance.
2. Shouldn't it be specified as sampling frequency instead of time step?  Sampling rates are usually nice whole numbers, like 44100 Hz, while time steps are not nice numbers: 1/44100 is 22.6757369614512471... microseconds, for instance, which I would imagine accumulates error?

**Comment by befelix** [comment]
1) Sampling frequency/time is needed for the plotting, e.g. impulse/step response and if you want to convert your normalized frequencies to something human-readable. Without a sampling time a discrete time system/filter does not have much meaning in the real world. 
2) I guess a point could be made for this, since humans have a tendency to pick whole number frequencies. Though as far as I can tell it is not really used in any computations and only for meaningful plotting. So we might as well stick to using the sampling time so that everything else (like the dsim functions) is not affected by the change.

**Comment by callegar** [comment]
In your code you will need to store the sampling step/frequency somewhere, so storing it into the LTI object seems natural. Furthermore, it also works as a switch for recognizing if the LTI object is DT (Ts>0) or CT (Ts=0). One reason for using Ts instead of Fs is that semantically speaking for this use as a switch you would use Fs->inf, which is less practical.

Another reason for sticking with Ts is compatibility. Matlab does this, Octave does this. Converting stuff made for Matlab/Octave into Python should be as easy as possible imho.

**Comment by befelix** [comment]
So the first part of this is now merge, with the ```lti``` class being split into ```StateSpace```, ```TransferFunction``` and ```ZerosPolesGain``` subclasses. However I'm not 100% sure what's the best way to extend this to discrete systems. There seem to be three options
**A)** Reuse the existing subclasses for the discrete case. All the transformations etc. are the same anyways. This would probably requiere some selective inheritance for the subclasses, but is doable with relatively little effort.
**B)** Create new discrete time subclasses. Not sure what the names would be, but maybe something along the lines of ```StateSpaceDiscrete```.

A ensures that there is no duplication of code, since most of it (all of it) is the same anyways. It would be still possible to have subclasses that are specific to the continuous/discrete case (I think ```sos``` is discrete only?). Also the API doesn't get too cluttered, since the same classes can be used for both cases. 
However, A could cause trouble in the long run, if there suddenly is some need for subclass-specific functions that only work in one of the cases (discrete / continuous). I currently can't think of any such case, but if they exist they would be extremely messy to implement and difficult to document clearly.
B in turn would avoid that problem, but would lead to a lot of duplicated code (at the moment all of the code would be copied) and could cause the continuous and discrete subclasses to not have the same features (i.e. any change would have to be applied to both codebases for consistency). Notice that B could still lead to a nice API, maybe with something like ```ltid.StateSpace(A,B,C,D)``` or ```ltid.from_ss(A,B,C,D)```.

If there is no immediate need for code that is both subclass-specific and (discrete)time-specific, then case A seems a lot better. However, if there is a need to change to B In the long run then that would break any code that uses something like ```isinstance(obj, StateSpace)``` for discrete-time systems.

It would be great if you could give some input about what you think is better or if there are other arguments that should be considered. The actualy implementation of this is pretty straight-foward in either case, now that ```lti``` has been split up.

**Comment by befelix** [comment]
So there is a PR for this: #4881.
It would be great if some of you could help review it.

**Comment by FRidh** [comment]
@callegar @befelix `sampling_time` instead of `fs` breaks with what is now commonly used. Generally I advocate for readable (full) names but in this case, `fs` is so common throughout the codebase, that I don't think it's good to deviate from it. Regarding Matlab/Octave compatibility, the API is deviating already.

About testing whether it is a `lti` or `ltid`. One possibility would be to simply set a fixed value in the classes `lti` and `ltid`. Another way would be to check `hasattr('fs')`, since the discrete system doesn't necessarily need a sample frequency.

**Comment by sergiocallegari** [comment]
A lot of what could be desirable can be found in python-control already and people are already using it. Specifically, see http://python-control.sourceforge.net/manual/class_strings.html#module-lti that uses the sampling time `dt` as in

        dt = None No timebase specified
        dt = 0 Continuous time system
        dt > 0 Discrete time system with sampling time dt
        dt = True Discrete time system with unspecified sampling time

That module is already BSD licensed. So, it would be good to either work with them for scipy or at least not make scipy incompatible with it.
