### ISSUE TITLE
Trimmed statistics functions have inconsistent API

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#2914]
These functions are:

- tmin
- tmax
- tmean
- tstd
- tvar
- tsem

They should all be made consistent, probably all need keywords ``axis`` and ``ddof``. ``tsem`` should be made consistent with ``sem``. The relation between ``tmean`` and ``trim_mean`` should be clarified.

Those functions are now all tested to some extent after gh-2913. What's left to do there is to test their behavior with masked arrays. Examples should also still be added.

**Comment by rgommers** [comment]
Just noticed something weird: all trimmed functions are documented to return a float, but they actually return a 0-D masked array:

    In [13]: stats.tmin(4)
    Out[13]: 
    masked_array(data = 4,
                 mask = False,
           fill_value = 999999)

This needs fixing when addressing this issue.

**Comment by aeklant** [comment]
@rgommers I added `axis` and `ddof`. However, I don't understand how `ddof` would fit into `tmin`, `tmax` and `tmean`. Can someone shed some light?

I believe adding `axis` and `ddof` to `tsem` makes it consistent with `sem` (since `limits` and `inclusive` don't make sense for `sem`) but let me know if you have something else in mind.

Things pending:
1) Update docstrings with the additions.
2) Clarify relationship between `tmean` and `trim_mean`
3) Test with masked arrays
4) Add examples
5) Review `_mask_to_limits`
6) Fix `returns : float` in documentation

Please feel free to add anything I may have missed.

**Comment by rgommers** [comment]
Agreed that ``ddof`` doesn't make sense for ``tmin, tmax, tmean``, this was just incorrectly described in the first message above.

**Comment by rgommers** [comment]
That we have both ``tmean`` and ``trim_mean`` is unfortunate, but I think we're stuck with it. ``trim_mean`` (and ``trim_both``, ``trim1``) look odd, but I expect we're not going to change them much. ``trim_mean`` is used from ``stats.levene`` for example.

**Comment by rgommers** [comment]
Note that test with masked arrays is already in ``test_mstats_basic.TestCompareWithStats``, so if additional tests are needed, best to put them there. The trimmed mstats functions have separate implementations though, so you can leave that till you get to ``mstats``.

**Comment by rgommers** [comment]
The above todo list looks complete to me.
