### ISSUE TITLE
stats expect for discrete, termination condition

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#2983]
discrete expect might terminate too early

example zipf distribution, see #2904

**Comment by mdhaber** [comment]
@ev-br @josef-pkt  I don't think the problem with `zipf` is an early termination issue.

```python3
import numpy as np
from scipy import stats
m, v, s, k = stats.zipf.stats(6.5, moments='mvsk')
k2 = stats.zipf.expect(func= lambda x: (x-m)**4, args=(6.5,),
                       maxcount=100000) / v**2 - 3
np.testing.assert_allclose(k, k2)
```
prints
```
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 0.07886976
Max relative difference: 0.00028232
 x: array(279.446102)
 y: array(279.367233)
```

But there's no difference between maxcount=10000 and `maxcount=100000`, so it's getting as close as it can.

What should we do here? The default `maxcount` is 1000, and while that doesn't work as well as 10 000 for `zipf`, I don't think it's a _defect_, really. Choosing perfect defaults is hard.

Should this issue be closed? Does a separate enhancement request need to be opened for further improvements to the `expect` algorithm, or do we wait for users to request it?

**Comment by ev-br** [comment]
It's just a slow convergence of the series.  So I suspect the only way to meaningfully deal with these sorts of cases is to implement some series acceleration technique(s). Possibly hide it behind an additional kwarg, like `.expect(...., use_summation='aitken')` because it's an overkill for most cases where the convergence is fast.

But this all is more of an enhancement request, and it does not seem like there is a whole lot of requests over the years :-).

So overall, I think this issue can be closed --- or reworded, relabeled as an enhancement request and left open so that we can refer to it if needs be.

**Comment by josef-pkt** [comment]
nothing can completely solve this, the sum might not converge, e.g. higher moments for zipf don't exist for small shape parameter.
try 4th moment with shape parameter 2 or 3

expect has (now) options to give user control of the integration/summation properties, which I think is the best we can do in the general case.

**Comment by josef-pkt** [comment]
issue can be closed

**Comment by mdhaber** [comment]
Sounds good to me. Let's close and, as with many other improvement ideas, keep this in the back of our mind for when there's time!
