### ISSUE TITLE
No way to set ranges for fitting parameters in Optimize functions

### ISSUE THREAD

**Issue by Void2258** [scipy/scipy#3129]
The optimize functions do not have any way to set parameter limits, for example stating p[0]>=0 to prevent the fitting from attempting negative values. This SEVERALLY limits the usefulness of the package as a whole, as there is no way to prevent the optimization from sliding into unacceptable or non-physical areas. Many unacceptable fit parameters are easily avoidable if the package simply were able to be told not to proceed into certain areas, but instead the algorithms can fall into extant but known unacceptable minima very easily. 

There is no simple and universally applicable method for preventing this from being an issue, as often in these cases the functional form may not be known or may not be defined in the forbidden region and thus there is no truly safe way to alter the functional output such that the fit returns to the safe region if it wanders out. This is the single largest and most troublesome problem in the entire package for myself and many other scientists, and it is a glaring omission in this otherwise extremely proficient MATLAB replacement.

**Comment by ev-br** [comment]
This work by @nmayorov may be of interest here: https://github.com/scipy/scipy/pull/5019.

**Comment by ev-br** [comment]
An implementation of nonlinear LSQ has landed in gh-5044, yay! I wonder if this issue should be closed now.

**Comment by sciqader** [comment]
Indeed it is possible, even without needing to use limfit package!
e.g. if you are using lasts method, you can define your condition in your model, so that the residual becomes very large when one the parameter values fall outside of the desire interval. Here is an example, in which I require my parameter theta say in a range where cos(theta) is always positive.

# model function for the direction reconstruction 
#----------------------------------------
def model(r, par):
	'''
	r = delta_r [x, y, 0]
	'''
	# direction of the pulse
	theta = par[0]
	phi = par[1]
	s = [np.sin(theta) * np.cos(phi), np.sin(theta) * np.sin(phi), np.cos(theta)]
	if np.cos(theta) < 0:
            return 1e16
	return -np.dot(r, s)

# residual function for direction reconstruction
#----------------------------------------
def chisq(par, t, r):
	return t - model(r, par)

# whatever main program 
#----------------------------------------
# initial values for the fit
init_vals = np.array([-0.05, -0.6], dtype=float)
# fit the function
s, flag = leastsq(chisq, init_vals, args = (t, r))
