### ISSUE TITLE
RectBivariateSpline usage inconsistent with other interpolation functions and documentation

### ISSUE THREAD

**Issue by lnmaurer** [scipy/scipy#3164]
Let's say that I want to interpolate data on a rectangular grid. For the purpose of illustration, I'll define a function 'f' to generate the data:

``` python
x = arange(-2,10)
y = arange(3,12)
xx, yy = meshgrid(x,y)

f = lambda x,y: exp(x)-y
z = f(xx,yy)
```

If I want to interpolate this with interp2d, I'd do this:

``` python
exInterp = interp2d(x,y,z,kind='cubic')
print 'interp2d tests:'
print 'interpolated:', exInterp(2,3)
print 'exact:', f(2,3)
print 'interpolated:', exInterp(5,8)
print 'exact:', f(5,8)
```

This produces the expected results; the interpolated and exact answers are in agreement:

```
interp2d tests:
interpolated: [ 4.3890561]
exact: 4.38905609893
interpolated: [ 140.4131591]
exact: 140.413159103
```

However, RectBivariateSpline cannot be used in the same way:

```
In [2]: RectBivariateSpline(x,y,z)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-39b2819e680b> in <module>()
----> 1 RectBivariateSpline(x,y,z)

/usr/lib/python2.7/dist-packages/scipy/interpolate/fitpack2.pyc in __init__(self, x, y, z, bbox, kx, ky, s)
    759             raise TypeError('y must be strictly ascending')
    760         if not x.size == z.shape[0]:
--> 761             raise TypeError('x dimension of z must have same number of '
    762                             'elements as x')
    763         if not y.size == z.shape[1]:

TypeError: x dimension of z must have same number of elements as x
```

Instead x and y must be swapped, both in creating and using RectBivariateSpline:

``` python
exInterp2 = RectBivariateSpline(y,x,z)
print 'RectBivariateSpline tests:'
print 'interpolated y,x:', exInterp2(3,2)
print 'interpolated x,y:', exInterp2(2,3)
print 'exact:', f(2,3)
print 'interpolated y,x:', exInterp2(8,5)
print 'interpolated x,y:', exInterp2(5,8)
print 'exact:', f(5,8)
```

This produces the output

```
RectBivariateSpline tests:
interpolated y,x: [[ 4.3890561]]
interpolated x,y: [[ 17.08553692]]
exact: 4.38905609893
interpolated y,x: [[ 140.4131591]]
interpolated x,y: [[ 2975.95798704]]
exact: 140.413159103
```

So, the (y,x) argument ordering produces the correct answer, while (x,y) does not.

Perhaps all this is intentional and is not a bug per se. However, it is inconsistent with x and y as defined by meshgrid. It is inconsistent with x and y as used by interp2d. And it is inconsistent with the documentation, which says that **init** and **call** both have arguments in the (x,y) ordering.

Because of these inconsistencies, I submit that this is a bug.

(FWIW, I'm using SciPy 0.12.0 on Kubuntu.)

**Comment by WaaallEEE** [comment]
I stumbled across this issue for hours too, before reading this issue  which was posted 3 years ago.  I agree that the documentation should be made more consistent.

**Comment by xiaobin1124** [comment]
I stumbled across this issue for the second time, last time is 2years ago.

**Comment by xiaobin1124** [comment]
I stumbled across this issue for the second time, last time was 2 years ago. Remember to make a yourself note.

**Comment by ValerieAnne563** [comment]
+1 to improving documentation of the issue, just fell prey to this inconsistency as well. 

While this function is used in many contexts, would be possible to print a warning message in the following situation?
`
interpolator = interpolate.RectBivariateSpline(y_before, x_before, my_data)
scaled = interpolator(x_after, y_after)`

Suppose x_before > y_before when interpolater was initialized. 
However, when interpolator runs, y_after > x_after.

The implementation could detect that the larger dimension has now become the smaller.
Additionally, when the order of parameters are transposed, the x/y ratios of the before and after would be different. 

I realize this recommendation is specific to situations where the scaling code in question is maintaining aspect ratios, and that's not always the case, but if that's the most common one, the log warning message could save a lot of people time and trouble.

**Comment by axil** [comment]
@xiaobin1124 I've written an article summarizing the differences in interp2d and RectBivariateSpline: [Python Spline Interpolation How-To](https://betterprogramming.pub/python-spline-interpolation-how-to-ef059c214d28?sk=533401d8775bcea491307a386ce36fcc). Hope it'll save you a couple of minutes if you happen to run into this issue a third time ;)

**Comment by ev-br** [comment]
@axil nice write-up! Am planning to link to it from the scipy user guide then in gh-16707 or a follow-up. Are you're open to amending/expanding your write-up? 

(reopening for visibility)

**Comment by axil** [comment]
@ev-br Thanks. Yes, definitely!

**Comment by axil** [comment]
Hi, @ev-br, I'm considering adding some words about `scipy.interpolate.griddata` to the article. Could you lend me a hand with it as I didn't dive deep into that part of the library?

**Comment by tylerjereddy** [comment]
@ev-br We discussed this a bit in the SciPy meeting today with @axil -- sounds like a doc improvement might be welcome? A kwarg for transposed behavior is perhaps a bit more contentious though.

**Comment by ev-br** [comment]
@tylerjereddy  @axil Too bad I did not make it to the SciPy meeting (was 11pm local time for me). Doc improvements are definitely *very* welcome! A kwarg is very much less so.

**Comment by ev-br** [comment]
@axil this nearly slipped under the radar, sorry about that.

Your text is great actually. A couple of minor comments first:

1D: interp1d does not use Fortran. It's pure python /numpy for linear and nearest type modes, and `make_interp_spline` otherwise.  (I'd recommend to use `make_interp_spline` directly but that's a matter of taste). `make_interp_spline` does let you choose boundary conditions, but indeed uses not-a-knot by default. BTW, note the "not-a-know" typo.

2D: An obligatory comment is that both interp2d and *BivariateSpline (which wrap the same set of FITPACK routines, as you mention) do *not* guarantee that the spline knots are at the data points. They are really meant for data smoothing, not interpolation. The FITPACK knot selection algorithm sometimes leads to bizzare behavior and sometimes quite unexpected results. There are several issues in the scipy bug tracker about this.

(In fact I'm going to try arguing for deprecating interp2d on the scipy-dev mailing list soon (tm)).

What is better suited for interpolation in 2D (or N-D, in fact) is RegularGridInterpolator and its interpn wrapper. I'd be happy to help with it if there are specific questions or queries. It is being quite actively worked on in the 1.9.x - 1.10.x time frame, and I think it's well on track for getting into being ready to be recommended as *the* workhorse for regular grid data.
Maybe you could play with it and add it to your text? You seem to have a knack for explaining messy things clearly!

Re your question about griddata --- what about it? One quick note is that it's triangulation based (via Qhull), so it should not be used for data on regular grids.

**Comment by ev-br** [comment]
OK, the documentation has been expanded, https://scipy.github.io/devdocs/tutorial/interpolate.html
Additions, clarifications and other improvements to the docs are most welcome!

RectBivariateSpline behavior is frozen by the backwards compatiblity.
`interp2d` is (finally) deprecated in scipy 1.10 and will be removed in a future scipy version.

@axil you may want to update your text :-). Or merge it with the scipy tutorial, I'll happily review. 

All in all, this issue can be closed I think, but feel free to continue discussing. Thanks all!
