### ISSUE TITLE
interpolation.zoom incorrect output for certain cases

### ISSUE THREAD

**Issue by iZehan** [scipy/scipy#3203]
I found the behaviour of zoom to be incorrect when working with 3D arrays for nearest neighbour interpolation.

for example, try the following:

```
x = numpy.zeros(32, 32, 11)
x[12, 16, 8] = 1
y = interpolation.zoom(x, 4, order=0)
```

and when I check to see at `y[12*4, 16*4, 8*4]` I find its 0, not 1.
on closer analysis, if I do `numpy.where(y==1)` I find:

```
(array([48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 49,
       49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 51, 51, 51,
       51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51]),
 array([64, 64, 64, 64, 65, 65, 65, 65, 66, 66, 66, 66, 67, 67, 67, 67, 64,
       64, 64, 64, 65, 65, 65, 65, 66, 66, 66, 66, 67, 67, 67, 67, 64, 64,
       64, 64, 65, 65, 65, 65, 66, 66, 66, 66, 67, 67, 67, 67, 64, 64, 64,
       64, 65, 65, 65, 65, 66, 66, 66, 66, 67, 67, 67, 67]),
 array([33, 34, 35, 36, 33, 34, 35, 36, 33, 34, 35, 36, 33, 34, 35, 36, 33,
       34, 35, 36, 33, 34, 35, 36, 33, 34, 35, 36, 33, 34, 35, 36, 33, 34,
       35, 36, 33, 34, 35, 36, 33, 34, 35, 36, 33, 34, 35, 36, 33, 34, 35,
       36, 33, 34, 35, 36, 33, 34, 35, 36, 33, 34, 35, 36]))
```

it looks like the last dimension is off by 1.

in contrast, if I perform the same test with skimage.transform.resize 

```
y2 = transform.resize(x, numpy.asarray(x.shape)*4, order=0)
```
- it provides me with the right output for `numpy.where(y2==1)`:

```
(array([48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 49,
       49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 51, 51, 51,
       51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51]),
 array([64, 64, 64, 64, 65, 65, 65, 65, 66, 66, 66, 66, 67, 67, 67, 67, 64,
       64, 64, 64, 65, 65, 65, 65, 66, 66, 66, 66, 67, 67, 67, 67, 64, 64,
       64, 64, 65, 65, 65, 65, 66, 66, 66, 66, 67, 67, 67, 67, 64, 64, 64,
       64, 65, 65, 65, 65, 66, 66, 66, 66, 67, 67, 67, 67]),
 array([32, 33, 34, 35, 32, 33, 34, 35, 32, 33, 34, 35, 32, 33, 34, 35, 32,
       33, 34, 35, 32, 33, 34, 35, 32, 33, 34, 35, 32, 33, 34, 35, 32, 33,
       34, 35, 32, 33, 34, 35, 32, 33, 34, 35, 32, 33, 34, 35, 32, 33, 34,
       35, 32, 33, 34, 35, 32, 33, 34, 35, 32, 33, 34, 35]))
```

**Comment by tylersc2** [comment]
I encountered a similar problem.  Both of the following calls gave odd results. (Two pieces of top part of image were 'folded' onto bottom part of image)
        scipy.ndimage.interpolation.zoom( img, 1.0, order=1 )
        scipy.ndimage.zoom( img, 1.0, order=1 )
But the following worked just fine:
        scipy.misc.resize( img, 1.0, interp='bilinear' )
BTW, I started off with a scale factor other than 1, I tried a degenerate case just to see if it would work.
Also, my arrays are huge:  double precision 19370 by 19370

**Comment by tylersc2** [comment]
I wish to retract my comment above.  My problem with "zoom" seems unrelated to this.  I opened a separate bug report (#4638).

**Comment by bbudescu** [comment]
Also, last lines / columns of zoomed images seem to have unexpected zero values in some cases.

After running 
```python
import numpy as np
from scipy.ndimage import zoom
a = zoom(np.ones((110, 72), numpy.float32), (51. / 110, 40. / 72))
```
`all(a[-1] == 0)` yields `True`

**Comment by thawn** [comment]
this issue still exists in scipy 1.4.1.

simple example:
```python
import numpy as np
from scipy.ndimage import zoom
a =  zoom(np.ones((32,32)), 0.5)
```
`all(a[-1,:] == 0)` as well as `all(a[:,-1] == 0)` yield `True` resulting in a black line of pixels at the left and bottom edges of all zoomed images

this is really a pity since `scipy.ndimage.zoom` with prefiltering actually yields nicer results than `skimage.transform.rescale` (and also, scipy.ndimage is lighter than skimage)

note, the errorneous behavior only occurs with mode='constant' mode='nearest' returns expected results (obviously the simple example above does not illustrate this well but with a real image and comparing the result to skimage.transform.rescale it is obvious that with any mode other than constant, the zero padding issue does not occur.

**Comment by tylerjereddy** [comment]
I'll add the `1.5.0` milestone to give this a slightly reduced chance of falling off the radar before the next release. The issue is six years old, which usually means it is not fun to solve! IIRC the `ndimage` C code is quite an adventure to try to understand as well.

**Comment by thawn** [comment]
@tylerjereddy thanks a lot for adding the milestone, that is much appreciated.
I did have a look at the C code in [ni_interpolate.c](https://github.com/scipy/scipy/blob/v1.4.1/scipy/ndimage/src/ni_interpolation.c). Because the issue only occurs with `mode=constant` I suspect that the bug is somewhere in lines 79, 116 or 588-606 which is only executed when `mode==constant`. But my limited C knowledge made me end there.
