### ISSUE TITLE
stats distributions ppf-cdf roundtrip

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#3214]
Found while playing with gh-3207.

Replacing the docstring semilog comparison by an assertion smokes a few problems with the cdf-ppf roundtirip. The stats tests suite does have a test for the roundtrip, https://github.com/scipy/scipy/blob/master/scipy/stats/tests/test_continuous_basic.py#L340, but it only checks that `cdf(ppf(q, *args), *args) == q`

Trying to check that `ppf(cdf(x, *args), *args) == x` produces several failures.
Specifically, this script [needs gh-3207 for the distribution parameters or a copy-pase from https://github.com/scipy/scipy/blob/master/scipy/stats/tests/test_continuous_basic.py#L28 ]:

```
from numpy.testing import assert_allclose, run_module_suite

import scipy.stats as stats
from scipy.stats._distr_params import distcont  # args from the test suite

def check_ppf_cdf(distname, args):
    distfn = getattr(stats, distname)
    distfn.stats(*args)  # fix .a & .b

    x = np.linspace(np.maximum(0, distfn.a), np.minimum(3, distfn.b), 5)
    prob = distfn.cdf(x, *args)
    vals = distfn.ppf(prob, *args)

    assert_allclose(x, vals, atol=1e-7, rtol=1e-7)

def check_cdf_ppf(distname, args):
    distfn = getattr(stats, distname)
    distfn.stats(*args)  # fix .a & .b

    prob = np.linspace(0, 1, 10)
    vals = distfn.ppf(prob, *args)
    prob_back = distfn.cdf(vals, *args)

    assert_allclose(prob, prob_back)


def test_all():
    for distname, args in distcont:
        print distname, args
        if distname is 'levy_stable':
            continue
        yield check_ppf_cdf, distname, args
        #yield check_cdf_ppf, distname, args   # these all pass


if __name__ == "__main__":
    run_module_suite()
```

produces fails for `tukeylambda`, `powernorm`, `nct`, `nakagami`, `ksone`, `johnsonsb`, `invgauss`, `genexpon`, `exponpow`, and `chi2`. 

While some of them can definitely be ignored (`ksone`), the rest, I guess, could/should be checked

**Comment by mdhaber** [comment]
@DominicChm I would consider this issue closed if we had a benchmark that would [track ](https://asv.readthedocs.io/en/stable/writing_benchmarks.html#tracking-generic)the error of ppf-cdf roundtrip calculations. In this case, a benchmark would be preferable to a unit test because it's not a matter of passing/failing; we're interested in improvement over time. Could you modify (or copy, if need be) `benchmarks.stats.DistributionsAll` to track some measure of the error of a `ppf-cdf` roundtrip calculation? Initially, maybe take the unit test `check_cdf_ppf` as inspiration and track the maximum error of the three values (but we can discuss the precise definition of error that we want to track once that's set up).
