### ISSUE TITLE
basinhopping jumps to a non-accepted place (on first round?)

### ISSUE THREAD

**Issue by pv** [scipy/scipy#3431]
```
from scipy.optimize import basinhopping
f1 = lambda x: (x-4)
def nay(**kwargs):
    return False
x0 = [1.]   
print basinhopping(f1, x0, accept_test=nay, niter=200)
```

This results to

```
x: array([ -1.80746874e+08])
```

but shouldn't the jump to this position have been rejected, since the accept test fails?

**Comment by mdhaber** [comment]
I don't think there is a bug here, and I think the algorithm is working as documented.

> `accept_test`: Define a test which will be used to judge whether or not to accept the **step**.
> `take_step`: Replace the default step-taking routine with this routine. The default step-taking routine is a **random displacement of the coordinates**...

Local search is not a "step", so there is no need to judge whether to accept a step after initial minimization. I think this is supported in spirit by the [original paper](https://arxiv.org/abs/cond-mat/9803344), which uses local minimization to transform the objective function into a collection of basins and random steps to hop between these basins (although it is not super specific about the procedure), The most recent [reference](https://www.hindawi.com/journals/aai/2012/674832/) cited by `basinhopping` writes out the algorithm for monotonic basin hopping as:

![image](https://user-images.githubusercontent.com/6570539/196978032-7e95f365-24ab-44b6-a22d-00212c1a8912.png)

Step 7 is the (monotonic, rather than Metropolis) acceptance criterion, and it is only performed to determine whether to accept $Y_{i+1}$, not $Y_i$ (which certainly makes sense in this case, at least, since there is no $Y_{i-1}$ to compare against).

Option 1 [above ](https://github.com/scipy/scipy/issues/3431#issuecomment-36839248) is not really supported by a reference that I've seen, although I don't see harm in offering it as a customization option, except as additional complexity in the API. Option 2, which suggests a `config_test` that is called after each change in `x` (whether it is due to a "step" or local search), seems valid, although it does not seem to be part of the original algorithm. But neither have been requested by users or even the OP, so I don't think this issue necessarily needs to remain open to track these ideas. I also considered a clarification at the end of the `accept_test` documentation, like:

> Note that `accept_test` is not used after minimimization of the initial guess.

but so I'm guessing it is not a big point of confusion, since it has not come up for a while. I'll leave it alone and close this for now, but feel free to reopen if I've missed something.
