### ISSUE TITLE
reshape sparse matrices

### ISSUE THREAD

**Issue by Midnighter** [scipy/scipy#3507]
So from some web searches and playing with the code, as far as I can tell, sparse matrix reshaping is still a bit sketchy.

<dl>
    <dt>
        bsr_matrix
    </dt>
    <dd>
        <code>.reshape</code> is not implemented.
    </dd>
    <dt>
        coo_matrix
    </dt>
    <dd>
        <code>.reshape</code> is not implemented but constructor can be called with
        <code>coo_matrix((data, (row, col)), shape)</code>.
    </dd>
    <dt>
        csc_matrix
    </dt>
    <dd>
        <code>.reshape</code> is not implemented.
    </dd>
    <dt>
        csr_matrix
    </dt>
    <dd>
        <code>.reshape</code> is not implemented.
    </dd>
    <dt>
        dia_matrix
    </dt>
    <dd>
        <code>.reshape</code> is not implemented. Constructor works but might lead to broken <code>.data</code> and <code>.offsets</code> attributes. (Not sure, would need a test suite of operations.)
    </dd>
    <dt>
        dok_matrix
    </dt>
    <dd>
        <code>.reshape</code> is not implemented but method <code>.resize</code> works.
    </dd>
    <dt>
        lil_matrix
    </dt>
    <dd>
        <code>.reshape</code> <b>is</b> implemented.
    </dd>
</dl>

Is anyone actively working on this, otherwise I might give it a shot.

**Comment by drhagen** [comment]
I know this issue has not been touched in a while, but I am interested in championing this enhancement because it something I need frequently. I don't think it will be that much work to, at least, get correct `reshape` behavior for all the existing classes. I'll try to make them performant as I am able.

I think we can also get `order` for `'C'` and `'F'` to behave like Numpy. If an efficient algorithm is not forthcoming for both, I will use transpose -> reshape -> transpose to implement the behavior of one in the other, so we will have correct behavior for all cases.

Before I started, I wanted to make sure this was something is actually wanted (no big rewrites of sparse in the works).

**Comment by perimosocordiae** [comment]
I would be very happy to see progress on this issue. The previous attempt in gh-3957 stalled due to concerns about in-place modification and copy behavior, which will be something to watch for in your efforts. Here's a quick summary of the problem:

For numpy arrays, `y = x.reshape(...)` is a cheap, no-copy operation that returns a view of the same underlying data. For scipy sparse matrices this is almost certainly not going to be the case (as indices are tracked explicitly), which gives us some choices that could picked based on keyword arguments:
 1. make `y` completely independent of `x` by copying all indices and data arrays
 2. make `y` with new indices but potentially pointing back at `x`'s data array
 3. update `x` in-place, changing its indices (but not modifying the member arrays themselves)
 4. update `x` in-place, with in-place updates to its member arrays

Not all choices are meaningful for all sparse matrix types, and each has tradeoffs in terms of memory cost and user confusion. If I recall correctly, the previous PR had a `copy=False` keyword argument that toggled between option (2) if False and option (1) if True, but by routing non-COO formats through `tocoo()` and then back it was inadvertently causing option (4) via `sum_duplicates()`.

There was also some discussion about the sparse format of `y`. Should it match `x.format`, or should it be whatever is the most efficient to compute?

---
All of that aside, I look forward to seeing your PR. Feel free to send it whenever you want to start getting feedback, even if it's not 100% ready.

**Comment by WarrenWeckesser** [comment]
> For numpy arrays, y = x.reshape(...) is a cheap, no-copy operation that returns a view of the same underlying data. 

Nitpick:  That is not always true.  `reshape()` only returns a view when it can.

**Comment by drhagen** [comment]
> The previous attempt in gh-3957 stalled due to concerns about in-place modification and copy behavior, which will be something to watch for in your efforts.

I read through the other PR before volunteering. There is a lot of useful design information that I will use in my approach.

> 1. make y completely independent of x by copying all indices and data arrays
> 2. make y with new indices but potentially pointing back at x's data array
> 3. update x in-place, changing its indices (but not modifying the member arrays themselves)
> 4. update x in-place, with in-place updates to its member arrays

The benefit of (1) is that is always sane. The disadvantage is that it is costly. I am going to work toward this solution while keeping an eye out for operations that can be done like (2). I suspect that some reshapes can be done by keeping a view of the data, but not that many. Once we know how many there are, we can talk about the pros and cons of a  `copy` parameter.

The benefit of (4) is that it is fastest and works fine when there is only one reference to the array like in expressions that chain multiple operations. For example, there is no need to allocate new memory for the reshape operation in  `c = (a @ b).reshape((n, m))`. Unfortunately, this is Python, not Rust, and we don't know if there is only one reference to an object. I think it would be very surprising to users for the `reshape` operations in  `c = a.reshape((n, m)) @ b.reshape((m, n))` to modify `a` and `b`. I don't think this should be the default behavior, and I am inclined to wait to see the performance before adding a feature that Numpy `reshape` doesn't have.

> There was also some discussion about the sparse format of `y`. Should it match `x.format`, or should it be whatever is the most efficient to compute?

My current plan is to return the most efficient type. If there ends up being little to be gained by doing this, we can talk about guaranteeing to return the same type.

**Comment by drhagen** [comment]
Here are a few thoughts so far:

* If we want to be compatible with the `numpy.reshape` function, we can't add extra arguments like `copy`. More specifically, this function will only pass an `order` parameter to the object's `reshape` method. Just something to keep in mind.

* I never knew that the `size` property of sparse matrices returned `nnz` rather than `prod(shape)`. I found that very surprising. But I think it is too late to revisit this.

**Comment by drhagen** [comment]
The first implementation is live at #7946. I used the previous pull request as a base; the COO implementation was quite sensible. I expanded the implementation to include `order='F'` so we have compatibility with Numpy. I also implemented `copy` because for COO matrices as least, it is trivial to share the `data` array, and COO `reshape` is behind the default implementation.

**Comment by drhagen** [comment]
Based on comments on the PR, I am also planning to implement assignment to `shape` to maintain compatibility with Numpy. I am also planning on supporting the undocumented *args syntax `a.reshape(4, 5)` that is available in Numpy. Does anyone know where the Numpy helper function is that takes a *args shape and standardizes it as a tuple shape? Also, does anyone know how to make the docs lie about the function signature so it matches Numpy?

**Comment by drhagen** [comment]
I have pushed a commit with some changes:

* A matrix can be reshaped in place by assigning to the `shape` attribute.
* The `reshape` method now behaves as close to `numpy.matrix.reshape` as I could manage given that there is no documentation for most of its behavior and the implementation is buried somewhere in the C code. If someone familiar could check `sputils.check_shape`, that would be great.

Does anyone know why `dok_matrix` inherits from `dict`? It would seem to be more sensible to have a `data` attribute that was a dictionary, especially since the class is intentionally gimped so it won't work as a `dict`. As a result, DOK matrices have state that isn't part of `self.__dict__`, which makes them kind of hard to understand and use.

Pro-tip: The string representation of `numpy.intc` is `<class 'numpy.int32'>`, but this is a lie; it is not the same object or even a subclass of `numpy.int32`. If you are debugging and see an object of type `numpy.int32`, consider that it might be lying.

**Comment by perimosocordiae** [comment]
It'd be nice if your last comment (https://github.com/scipy/scipy/issues/3507#issuecomment-333344162) was on the PR thread instead of this one. It's easier to figure out which commit you're talking about there.

As far as I know, `np.intc` refers to the C `int` type, whatever that happens to be on your machine, so it's not surprising that it's equivalent to `np.int32`. I do agree that it's unfortunate that not all `dtype` objects that represent the same type are the same Python object, and I've run into this weirdness before: https://github.com/numpy/numpy/issues/6295.

**Comment by perimosocordiae** [comment]
Fixed by gh-7945.
