### ISSUE TITLE
Py 3.4 / SP 0.13.3 test failure: test_mpmath.TestSystematic.test_ci

### ISSUE THREAD

**Issue by andrewclegg** [scipy/scipy#3551]
I am testing SciPy 0.13.3 (NumPy 1.8.1) on Python 3.4.0 on Ubuntu 12.04, running in a VirtualBox VM on a MacBook Pro host.

Over 10% of the points tested are over the tolerance for absolute difference, details here: https://gist.github.com/andrewclegg/10744802

Steps to reproduce:

Check out [Snake Charmer](https://github.com/andrewclegg/snake-charmer/), and install Vagrant and VirtualBox if you don't have them already.

Then type:

```
vagrant up --provision charmed34 # this will take a while
vagrant ssh charmed34
python3.4
import scipy
scipy.test('full')
```

Here are some library versions that might be relevant:

https://gist.github.com/andrewclegg/10744802#file-gistfile2-txt

Anything else I can supply? Thanks.

**Comment by person142** [comment]
This is an old issue, but some comments:

- The failures are all at large `x` values (e.g. `x = 4.488123814895769e+16`). Computing `sici` requires computing `sin` and `cos`, and at inputs of this magnitude they are *not* accurate--the fact that the tests pass on any machine is essentially a matter of getting lucky that none of the test points hit any of the zeros of `si` or `ci`.
- The failures are very likely due to differences in quality of `sin` and `cos` implementations across different systems, but we should probably just restrict the range of arguments for the test (since not failing is a matter of "luck" anyway).

**Comment by person142** [comment]
And indeed now that I go to actually check on this I see that @pv already restricted the range back in https://github.com/scipy/scipy/commit/a6334183b540f359c804d2e03969573695b92f72 (values now restricted to be in `[-10^8, 10^8]`, which covers the problem points). Closing since this isn't an issue any more.
