### ISSUE TITLE
runtests.py puts some build process output files into the source directory

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#3578]
When I remove all the `.pyc` and `.so` files and the `_rank.c` file from the `scipy/stats/` source directory, the `setup.pyc` and the `_rank.c` file are reconstituted in that directory when I run `runtests.py`.  I would have expected these intermediate files to be quarantined in the build directory created by runtests.py rather than leaking into the original source directory.

**Comment by rgommers** [comment]
@argriffing in setup.py we call ``generate_cython()`` before calling ``setup()``, so it always does everything in-place. This is the easiest thing to do, for example because then the generated files are included in tarballs from ``python setup.py sdist``. And it's also helpful for debugging if you're working on a ``.pyx`` file.

**Comment by rgommers** [comment]
nothing to fix here I think, so closing.
