### ISSUE TITLE
sparse linalg eigs/eigsh is possibly affected by an ARPACK bug

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#3613]
The ARPACK bug http://forge.scilab.org/index.php/p/arpack-ng/issues/1315/ should theoretically affect `scipy.sparse.linalg.eigs` and/or `scipy.sparse.linalg.eigsh`.  This possibility and its possible resolutions were discussed in https://github.com/scipy/scipy/pull/3599 although I don't think much effort has been put into the investigation yet, on the scipy end.

**Comment by pv** [comment]
Interestingly, the arpack bundled in scipy has been linked against lapack 2.0 *lahqr routines since forever (already in 2006) so apparently this arpack "feature" was known to the people who added arpack to scipy, and later independently rediscovered by whoever reported the bug to arpack-ng :)

So closing (i) fixed in arpack-ng >= 3.2.0, and (ii) this apparently has always been worked around in the arpack bundled in scipy.

**Comment by argriffing** [comment]
Thanks for working on this @pv!
