### ISSUE TITLE
BUG: dendrogram's labels not displaying correctly after updating to 0.14

### ISSUE THREAD

**Issue by alessioU** [scipy/scipy#3822]
In Scipy 0.13 in `scipy.cluster.hierarchy` in the function `_plot_dendrogram`, to set the proprieties of the labels like rotation and font size, the function `matplotlib.pylab.setp` is used and the labels are displayed correctly.
Instead in Scipy 0.14, to set the proprieties of the labels like rotation and font size, it's used a map that simply calls for example just `set_rotation` or `set_size` but the labels are not rotated and not resized as you can see in the screenshot. I think `matplotlib.pylab.setp` does more than just calling `set_rotation` or `set_size`.
![screenshot - 07232014 - 09 11 44 pm](https://cloud.githubusercontent.com/assets/4503337/3678926/50030650-129f-11e4-9dbc-c0ce669f70d4.png)

**Comment by WarrenWeckesser** [comment]
This bug is still in master.  @jamestwebber, if you are interested in continuing your contribution to scipy, could you take a look at this?  Did arguments such as `leaf_rotation` work for you after you added the `ax` keyword to `dendrogram`?

**Comment by jamestwebber** [comment]
Sorry that I broke this, I'll take a look at this later today!

**Comment by jamestwebber** [comment]
A couple notes while I'm working on this (I think I have it fixed at this point):

The reason we don't want to simply revert to the old version is because it used pylab. pylab is really designed for interactive work and not recommended for use in programs. I changed the code to only use pylab when needed, because I wanted to be able to generate dendrograms a) without starting an interactive instance and b) on an arbitrary axes instance that I supply, rather than the active one.

However there is no "setp" in the regular matplotlib API, so I tried to emulate the existing code as best I could. I didn't really analyze whether it was doing the right thing--in retrospect it's got some weird behavior.

As @alessioU noted, the four different orientations all do different things. "top" autoscales and rotates based on the number of labels. "bottom" is supposed to autoscale based on `p`, a "truncate mode" parameter. "left" and "right" don't autoscale or rotate the labels without being told to. That's how the code was when I started, so I left it that way, but it seems reasonable to fix that while I'm in there. The only question is: should I use the number of labels, or `p`? I chose the former for now but that's a simple decision to make before merging.

**Comment by jamestwebber** [comment]
I guess another (in hindsight obvious) question is what the left/right orientations should do with their label rotation. The current auto-rotate stuff is geared toward the top/bottom orientations--it has horizontal labels unless you have a ton of leaves and then it rotates to vertical (first going to 45 degrees).

Seems like I should probably just keep the left/right orientations with horizontal labels--there's no downside as far as I can tell. If the user specifies a rotation then that wins, otherwise it's horizontal.

**Comment by WarrenWeckesser** [comment]
> I guess another (in hindsight obvious) question is what the left/right orientations should do with their label rotation. 

The conservative answer to questions of the form "What should it do?" is "Whatever it did in scipy 0.13."  That way we preserve backwards compatibility.

For that, though, you'll need to build scipy 0.13.  I tried building 0.13.3, but I got a cython error.  That's as far down the debugging rabbit hole that I had time to crawl.  Perhaps someone else can take a look.

**Comment by jamestwebber** [comment]
Well the answer was "nothing, unless the user specified", which is what I ended up doing. Which makes sense--y-axis labels don't need to be rotated for readability, so unless the users really wants that to happen they can stay the way they are.

**Comment by rgommers** [comment]
Multiple new fixes in addition to the ones from @jamestwebber just went into gh-5164. Review of that PR would be much appreciated. 

Also, some larger dendrograms for testing would be very welcome. Despite the open issues and the many stackoverflow posts about ``dendrogram``, it's very difficult to find examples that (should) work.
