### ISSUE TITLE
simulated annealing in scipy

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4042]
There has been some mailing list debate about whether simulated annealing should have been deprecated, and I am taking this as interest for simulated annealing in scipy.  The deprecated implementation had bugs, was not maintained, and benchmarked poorly vs. other global optimizers.

If anyone wants to add and maintain this or to resurrect it from deprecation, the first step might be to address comparisons like https://github.com/scipy/scipy/pull/335#issuecomment-12948535.

**Comment by dlax** [comment]
Closes #4042 via a13e116d1454e89987fd0157f1e34a20fad4438c.

**Comment by drmcnelson** [comment]
The present basinhopping, which does a refinement at each hop, is not a good replacement for simulated annealing.   It imposes an assertion about the shape of minima and computational cost of the minimization versus the hop.  For some problems this turns out to not be a good idea.  These is no question that you have to be able to not refine at each step.
