### ISSUE TITLE
scipy.interpolate.interp1d should be able to take a single value

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#4043]
Currently, the `scipy.interpolate.interp1d` constructor raises `ValueError` if the inputs are of size 0 or 1.  I suggest that it accepts the inputs instead and either raises `ValueError` on `__call__`, or returns `fill_value` if `bounds_error` is `False` (for a value different of the actually input value, if the input is of size 1).

**Comment by anntzer** [comment]
Kindly bumping the issue.
Also, what would you recommend to use instead of interp1d?

**Comment by ev-br** [comment]
Maybe it's just me being dense, but I still fail to see a case for anything more than wrapper like above which a user can fit to their heart's content. Anyway, I'm only -0 on this, so I wouldn't be strongly opposed to a PR which would turn what is now an error into something which at least two persons can agree is sensible :-). 

Any such PR would need to carefully weigh the backcompat guarantee. My own experience touching interp1d is not very nice: I added two seemingly trivial enhancements for 0.17; one caused a regression which created a bunch of work for Eric to fix; the other one caused *another* regression which we did not catch in the rc phase, so it's likely going to be 0.17.1.

**Comment by ev-br** [comment]
Re What to use instead of `interp1d`. My take on this (my own view, there's nothing official here) is:
 * for linear interpolation, I'd use `numpy.interp` directly
 * for spline interpolation, there's a choice of `splev/splrep` (remember to use `s=0` for interpolation; also zero weights to handle missing values) and the bright-and-shiny `CubicSpline` (dev version only).
 * for monotone interpolation, there's Akima1D and PCHIP.
 * for something which is not handled by the above, construct your own interpolators from `PPoly` or `BPoly.from_derivatives`.

**Comment by anntzer** [comment]
I just realized that for linear interpolation, `np.interp` is actually quite a bit faster than `interpolate.interp1d.__call__` (i.e. not even including the time to construct the `interp1d` object), and handles the case that triggered this issue, so I'll stick to it instead.

**Comment by ev-br** [comment]
Indeed, from 0.17.0 `interp1d` defers to `np.interp` where the latter applies (1D real-valued arrays). So, `interp1d` should also handle your case then, albeit with some extra overhead.

**Comment by anntzer** [comment]
Actually, out of bounds values are still handled separately (in `interp1d._evaluate`).

**Comment by drhagen** [comment]
For what it's worth, I also expected `interp1d([0], [[1,2]], axis=0)(0)` to return `[1,2]`.

My use case is interpolating the solution to a system of ODEs, which needs broadcasting in the dimensions of `y`. But if only the initial conditions have been computed so far, `interp1d` blows up.

**Comment by danjan1234** [comment]
I would suggest raising a warning instead of raising an error. There is a very practical reason. I would like to apply interp1d on pandas DataFrames after groupby. I cannot guarantee the number of data points in each group. It's quite harassing to see the entire program fail because one or two nonsense groups.

**Comment by danielwlogan** [comment]
Just finding this thread. I have a situation similar to @argriffing (post on 9 Oct 2014). Is there any possibility of using `nearest` when the input is a single point?

**Comment by ev-br** [comment]
@danielwlogan We can consider a pull request with an implementation. 
The onus will be on you to 1) explain the use case, and 2) avoid breaking backwards compatibility.
