### ISSUE TITLE
 ppf(0) of scipy's randint(0, 2) is -1.0

### ISSUE THREAD

**Issue by pelegm** [scipy/scipy#4054]
This question is migrated from this [SO question](http://stackoverflow.com/questions/25688461/ppf0-of-scipys-randint0-2-is-1-0), after re-verified on version 0.14.0 (latest pip version).

---

Perhaps I don't understand the functionality of `.ppf()` well, but according to [wikipedia](http://en.wikipedia.org/wiki/Quantile_function), `ppf(q)` should return the infimum over all reals `x` for which `q <= cdf(x)`. Since for every `x` the `cdf` of any distribution is non-negative, I'd expect `ppf(0)` to return `-inf`. However, as it seems

``` python
scipy.stats.randint(0, 2).ppf(0)  ## returns -1.0 ..?
```

Any idea about the cause for this behaviour?

---

While changing the method's name (see #3436) might be important, it is even more important to provide a well-defined meaning to this method.

**Comment by mdhaber** [comment]
According to Wolfram Alpha, the inverse CDF of the discrete uniform distribution evaluated at 0 is 0.
`InverseCDF[DiscreteUniformDistribution[0, 10], 0]`
![image](https://user-images.githubusercontent.com/6570539/104698480-479e4480-56c6-11eb-8000-d8febe86abc4.png)

https://www.wolframalpha.com/input/?i=InverseCDF%5BDiscreteUniformDistribution%5B0%2C+10%5D%2C+0%5D

Same in R `extraDistr` library:
```R
library(extraDistr)
qdunif(p=0, min=0, max=10)
```
https://rdrr.io/cran/extraDistr/man/DiscreteUniform.html
![image](https://user-images.githubusercontent.com/6570539/104698545-5c7ad800-56c6-11eb-8aaa-083e3275a598.png)

This doesn't make sense to me, because then the CDF is not the inverse of the inverse CDF.

```
> q= qdunif(p=0, min=0, max=10)
> pdunif(q=q, min=0, max=10)
0.09090909
```

gh-13328 would replace SciPy's `nbinom` and `binom` with those from Boost, and for those two distributions, the `ppf` evaluated at zero is -1 (which agrees with SciPy currently).
```
> binom.ppf(0, 10, 0.5)
-1.0
```
Based on that, I think Boost agrees with SciPy.

And since it seems to be a matter of convention, as there is not a unique quantile that satisfies `dist.cdf(quantile) == 0`, I don't see anything wrong with SciPy here. It is very consistent:
```python3
from scipy.stats._distr_params import distdiscrete
from scipy import stats
for name, params in distdiscrete:
    dist = getattr(stats, name)(*params)
    a = dist.support()[0]  # left end of the support
    cond1 = dist.ppf(0) == a - 1 # ppf(0) is one less than the left end of the support
    cond2 = dist.ppf(dist.cdf(a - 1)) == a - 1  # ppf is the inverse of cdf
    cond3 = dist.cdf(dist.ppf(0)) == 0  # cdf is the inverse of ppf
    print(f"{name}: {cond1 and cond2 and cond3}")
```
prints:
```
bernoulli: True
betabinom: True
binom: True
boltzmann: True
dlaplace: True
geom: True
hypergeom: True
hypergeom: True
hypergeom: True
logser: True
nbinom: True
nbinom: True
planck: True
poisson: True
randint: True
skellam: True
zipf: True
yulesimon: True
nhypergeom: True
```
Since there haven't been any comments in this issue for over 6 years, I'll go ahead and close this.
