### ISSUE TITLE
BUG: stats: fisher_exact returns incorrect p-value

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#4130]
For some tables, `fisher_exact` incorrectly returns a p-value of 1.  For example,

```
In [1]: from scipy.stats import fisher_exact

In [2]: m = np.array([[345, 455], [260, 345]])

In [3]: fisher_exact(m)
Out[3]: (1.0061284868977176, 1.0)
```

The correct p-value for the array `m` is 0.9567.   Here, for example, is the result in R:

```
> m <- array(c(345, 455, 260, 345), c(2,2))
> m
     [,1] [,2]
[1,]  345  260
[2,]  455  345
> fisher.test(m)

    Fisher's Exact Test for Count Data

data:  m
p-value = 0.9567
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.8083048 1.2526776
sample estimates:
odds ratio 
  1.006125 
```

The culprit is this code, from the `fisher_exact` function in `scipy/stats/stats.py`:

```
    elif alternative == 'two-sided':
        mode = int(float((n + 1) * (n1 + 1)) / (n1 + n2 + 2))
        pexact = hypergeom.pmf(c[0,0], n1 + n2, n1, n)
        pmode = hypergeom.pmf(mode, n1 + n2, n1, n)

        epsilon = 1 - 1e-4
        if np.abs(pexact - pmode) / np.maximum(pexact, pmode) <= 1 - epsilon:
            return oddsratio, 1.
```

In effect, it says the p-value is 1 if `np.abs(pexact - pmode) / np.maximum(pexact, pmode) <= 1e-4`.  It isn't clear why the value 1e-4 was used here.

**Comment by zym1010** [comment]
@WarrenWeckesser  I checked the implementation of this test in R <https://github.com/wch/r-source/blob/trunk/src/library/stats/R/fisher.test.R>, and seems that they employed a Monte Carlo method. I believe in general the current implementation in scipy won't work. Maybe a rewrite is needed.

**Comment by BLMeltdown** [comment]
Hello. 
I want to report again that this function is inaccurate (https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.fisher_exact.html); and maybe this is related to addition of "alternative"  keyword that doesn't work well (https://github.com/scipy/scipy/issues/4882).

I made some tests 

```
from math import factorial
from scipy.stats import fisher_exact
def hypergeometric(series):
    a,b,c,d=series
p=(factorial(a+b)*factorial(a+c)*factorial(b+d)**factorial(c+d))/(factorial(a)*factorial(b)*factorial(c)*factorial(d)*factorial(a+b+c+d))
    return p
s=np.array([6,108,37,200]).reshape((2,2))
b=hypergeometric(s)

>>b =0.00509270
(this takes so long I was feeling older, don't try this at home)

fisher_exact(s, alternative='two-sided')
>> 0.0050926977481275922)

fisher_exact(s, alternative='less')
>>0.99914550735448127
fisher_exact(s, alternative='two-sided')
>>0.0031603713904877631

```

The following calculator gives
http://www.danielsoper.com/statcalc/calculator.aspx?id=29
Exact hypergeometric probability: 	0.00230588
Exact two-tailed probability: 	0.00509270`

For reference, other calculators give this statistic:
http://www.socscistatistics.com/tests/fisher/Default2.aspx

The value for two-sided test should be double that for the one-sided "greater" one, and this greater one should be equal to 1-"less" p-value, so it seems there is  mistakes here, not only in the doubling byt also in delivered p-values. (For reference, I checked here to be sure: https://stats.stackexchange.com/questions/267192/doubling-or-halving-p-values-for-one-vs-two-tailed-tests)
For the array [[6,108][37, 6828]], values are:
2-sided : 6.2013.... e-05
less: 0.999994886
greater: equal to 2-sided.
So it seems that for some values, it is only a doubling problem. For lower values there is some deeper mess.

**Comment by BLMeltdown** [comment]
The problem is in these lines:
https://github.com/scipy/scipy/blob/v0.14.0/scipy/stats/stats.py#L2450

 ```
if alternative == 'less':
        pvalue = hypergeom.cdf(c[0,0], n1 + n2, n1, n)
    elif alternative == 'greater':
        # Same formula as the 'less' case, but with the second column.
        pvalue = hypergeom.cdf(c[0,1], n1 + n2, n1, c[0,1] + c[1,1])
    elif alternative == 'two-sided':
        mode = int(float((n + 1) * (n1 + 1)) / (n1 + n2 + 2))
        pexact = hypergeom.pmf(c[0,0], n1 + n2, n1, n)
        pmode = hypergeom.pmf(mode, n1 + n2, n1, n)
```
pvalue should be replaced by pexact  for all, and actually the calculation in hypergeom.pmf should not change (still, as per hypergeom docs(https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.hypergeom.html#scipy.stats.hypergeom), n value in this method parameters is N here and n1 is n in pmf. This would be less confusing to choose another name. n is actually confusing anyway, it lets thinking it should be the sum of n1+n2 and this is not the case (it is well visible above, as it is actually the total number of value of the first category, matching or not the condition (categories in columns, conditions in rows).

I could modify the code, but I am not really familiar with github process; while I read a few tutorials I can't wrap my brain around this mess, so I fear I would make a mistake with pull request...

**Comment by WarrenWeckesser** [comment]
I won't have time to get back to this for a while, but I want to note that this statement

> The value for two-sided test should be double that for the one-sided "greater" one

is not correct in general.  The probability distribution of the tables with fixed marginal sums used in Fisher's exact test is not symmetric.

**Comment by josef-pkt** [comment]
also, AFAICS, the `pexact = hypergeom.pmf...`  value is the probability for the specific table.
The p-value for the test needs the "cdf", the probability of getting a table at least as "extreme".

**Comment by josef-pkt** [comment]
more about doubling p-value

there are different ways of defining p-values in the asymmetric case
e.g. for binom_test
https://github.com/statsmodels/statsmodels/issues/2735

fisher exact uses the first definition `minlike`.

(There are some packages in R that have all three version for some "exact" statistics, but I don't remember details right now. The choice of test statistic that defines "at least as extreme" becomes more relevant in larger than 2x2 tables.)

**Comment by BLMeltdown** [comment]
Thanks for the precisions, and sorry for the bad input. Anyway it seemed to me that two-sided value being equal to greater would be illogical/strange. 

regarding

> also, AFAICS, the pexact = hypergeom.pmf... value is the probability for the specific table.
> The p-value for the test needs the "cdf", the probability of getting a table at least as "extreme".

You're right, I went too fast. 
https://github.com/scipy/scipy/blob/v0.14.0/scipy/stats/stats.py#L2450 states that the method returned
p_value : is  the probability of obtaining a distribution **at least as extreme** as the one that was actually observed, assuming that the null hypothesis is true.  
(emphasis' mine)
Hence I guess that the function returns the right value for having at least such imbalanced distribution, using pexact calculated value to perform various checks before using cdf.

**Comment by WarrenWeckesser** [comment]
> Anyway it seemed to me that two-sided value being equal to greater would be illogical/strange.

For the example that you gave, [[6, 108], [37, 6828]], the probabilities of the tables from [[0, 114], [43, 6822]] to [[43, 71], [0, 6865]] are monotonically decreasing.  For such a case, the "two-sided" value will equal the "greater" value.

**Comment by josef-pkt** [comment]
> Anyway it seemed to me that two-sided value being equal to greater would be illogical/strange.

In asymmetric distributions with "minlike", this can happen if the "other extreme tail" is essentially empty or has almost zero probability with maybe some numerical noise (precision problems).

(just saw that Warren was replying faster.)

**Comment by stuz5000** [comment]
Related:
   https://github.com/brentp/fishers_exact_test/issues/18
   https://github.com/brentp/fishers_exact_test/blob/master/tests.py
is a Python implementation that seems to agree with R implementations (and is orders of magnitude faster than scipy's fisher test).

**Comment by mdhaber** [comment]
The issue was original about inaccurate p-values due to the large fudge factor used in the implementation. Most of the discussion is about confusion surrounding the definition of two-sided p-value. This is well-documented in main, but I will add additional information to the introduction:

>    The null hypothesis is that the true odds ratio of the population
>    underlying the observations recorded in the table is one, and the
>    observations were sampled at random from this population. The statistic
>    returned is the unconditional maximum likelihood estimate of the odds
>    ratio, and the p-value is the probability under the null hypothesis of
>    obtaining a table at least as extreme as the one that was actually
>    observed. There are other possible choices of statistic and two-sided
>    p-value definition associated with Fisher's exact test; please see the
>    Notes for more information.

and define the alternatives:

> * 'two-sided': the odds ratio of the underlying population is not one
> * 'less': the odds ratio of the underlying population is less than one
> * 'greater': the odds ratio of the underlying population is greater
          than one

`hypergeom` has been replaced by Boost since this issue was raised, and it is more accurate now. The [original example](https://github.com/scipy/scipy/issues/4130#issuecomment-62461156) now works without a fudge factor. The OP did not wish to adjust the original fudge factor, but it has been eight years since the issue was first posted, so I believe it would be better to improve the existing implementation rather than wait longer for an ideal solution in terms of integer arithmetic. The fudge factor is meant to distinguish between theoretically and numerically different probability masses, so it should be on the order of accuracy of the `hypergeom` PMF calculation, not something so coarse as `1e-4`. I would suggest dropping it to `1e-14` unless that causes issues during testing.
