### ISSUE TITLE
1D scipy.interpolate.griddata using method=nearest produces nans outside boundaries

### ISSUE THREAD

**Issue by revoltek** [scipy/scipy#4233]
When the coordinates are 1D the nearest method produces nans instead of the closest values when outside boundaries. An example:

    import numpy as np
    from scipy.interpolate import griddata

    target_points = [1.,2.,3.,4.,5.,6.,7.]
    points = np.random.rand(50)*2*np.pi
    values = np.sin(points)

    interp = griddata(points, values, target_points, method='nearest')
    print interp

The last value printed is a NaN. Note that linear/cubic modes are expected to give NaNs outside the convex hull, but this should not be the case for the 'nearest' mode.

**Comment by maniteja123** [comment]
The documentation says that ``fill_value`` has no effect for ``nearest`` method [here](https://github.com/scipy/scipy/blob/v0.15.0rc1/scipy/interpolate/ndgriddata.py#L117). Does that mean there won't be a fill_value for ``nearest`` method or that ``NaN`` isn't the default ``fill_value`` ?

In the above example, the function ``interp1d`` is called [here](https://github.com/scipy/scipy/blob/v0.15.0rc1/scipy/interpolate/ndgriddata.py#L189), rather than ``NearestNDInterpolator`` since ``ndim`` is ``1``. 

The value of interpolated ``y_new`` at [_call_nearest](https://github.com/scipy/scipy/blob/v0.15.0rc1/scipy/interpolate/interpolate.py#L486) stage is 

    [[ 0.85659341]
     [ 0.96631064]
     [ 0.17542803]
     [-0.78798655]
     [-0.98080843]
     [-0.25246329]
     [-0.05942813]] 

But the call in ``griddata``[here](https://github.com/scipy/scipy/blob/v0.15.0rc1/scipy/interpolate/ndgriddata.py#L202) performs [_evaluate](https://github.com/scipy/scipy/blob/v0.15.0rc1/scipy/interpolate/interpolate.py#L493) call, which does the [_check_bounds](https://github.com/scipy/scipy/blob/v0.15.0rc1/scipy/interpolate/interpolate.py#L504) that fills the last value as ``NaN``.

    [[ 0.85659341]
     [ 0.96631064]
     [ 0.17542803]
     [-0.78798655]
     [-0.98080843]
     [-0.25246329]
     [              nan]] 

In some instances, there were even more than one ``NaN``s in the output.

Just pointing out that ``_evaluate`` doesn't take into account whether the ``method`` was ``linear``, ``cubic`` or ``nearest``. Hope it helps and correct me if I am wrong since I am not that familiar with this.
