### ISSUE TITLE
continuous performance regression reporting

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4277]
SciPy currently has great support for manually running benchmarks using commands like
`$ python runtests.py --bench`
`$ python runtests.py --bench -s sparse`
But these are not run by TravisCI, and after having run them yesterday and finding several seemingly independent bit-rotting errors, I've concluded that they are run rarely by the developers.  Maybe like twice a year.

Several recent scipy issues or PRs are performance related (although there is not yet a scipy github label for performance) including https://github.com/scipy/scipy/issues/4203, https://github.com/scipy/scipy/pull/4191, and performance regression concerns in https://github.com/scipy/scipy/pull/4087.

Projects addressing benchmarking for scientific python include [vbench](https://github.com/pydata/vbench) and [airspeed velocity](http://spacetelescope.github.io/asv/index.html).  These projects are intended to be abstracted from their underlying motivating projects, but in practice this abstraction has proved difficult.  For example vbench seems to be de-facto forked for pandas performance regression testing, and while @yarikoptic has successfully customized vbench [for numpy](https://github.com/yarikoptic/numpy-vbench) the extensive customizations in these forks are not making their way back into vbench.  Similarly, 'airspeed velocity' seems to work [for astropy](http://mdboom.github.io/astropy-benchmark/) but it is not clear to me how much customization would be required for performance regression reports for non-astropy projects.

List of scientific python projects continuously monitored for performance:
[qutip with vbench](https://github.com/qutip/qutip-benchmark/tree/master/continuous-benchmark)
[pandas with vbench](http://pandas.pydata.org/pandas-docs/vbench/)
[numpy with vbench](https://github.com/yarikoptic/numpy-vbench)
[astropy with airspeed velocity](http://mdboom.github.io/astropy-benchmark/)
[scikit-learn with vbench](https://github.com/scikit-learn/scikit-learn-speed/issues/2) (inactive)

Related issues in scientific python projects that are not monitored:
https://github.com/matplotlib/matplotlib/issues/2188
https://github.com/scikit-image/scikit-image/issues/1061
https://github.com/sympy/sympy/issues/7715
https://github.com/pymc-devs/pymc/issues/307
https://github.com/Theano/Theano/issues/561

**Comment by pv** [comment]
I converted all the Scipy benchmarks to airspeed velocity: https://github.com/pv/scipy-bench
For example: https://github.com/pv/scipy-bench/blob/master/benchmarks/bench_linalg_sqrtm.py

The `asv` benchmark output is pretty terse, it just prints the result number.
If you run the benchmark suite via the nosetests way as explained in README, more stuff is printed to stdout (loosely in the same format as previously, but removing the need to write ASCII table printing code for each benchmark separately).

There's some tension in the code due to the fact that ASV allows currently only a single number returned from a single benchmark.

One question of course is that several of the benchmarks do not serve continuous regression testing, so why use asv for them. Nevertheless, I think the current way scipy benchmarks work is dodgy (printing random stuff to stdout from nosetests), so it's probably good to formalize the tests so that they also could serve continuous regression.  It seems it's fairly easy to restrict which of the benchmarks are run, so just putting everything here probably makes sense IMHO.

I would be tempted by the following plan of attack:

- remove all benchmarks in the scipy repository
- move scipy-bench under scipy project, and add it as a git submodule scipy/benchmarks
- update benchmark running instructions

followed by

- figure out how to best distribute the benchmark results, eg. via a git repo, against which anyone can do pull requests to submit their test runs
- try to set up some authoritative ci runner to produce results, and get a nice website with 700+ performance graphs (but probably fairly low information content, though)

**Comment by rgommers** [comment]
Plan to move all benchmarks to ``scipy-bench`` sounds good. An authoritative CI runner is probably more maintainable long-term, anything requiring manual triggers is likely to go out of date.

**Comment by rgommers** [comment]
Did you settle on ASV over vbench because of maintenance, features or both?

**Comment by pv** [comment]
ASV appeared more polished and required no custom configuration to work, whereas vbench required some hassle. (ASV seems currently alive whereas vbench is resting.)
.
The right thing to do would probably be to first write proper parameterized test support to ASV (cf https://github.com/spacetelescope/asv/issues/36). However, this is not something that absolutely must be done first, as I think we could live with the kludged generator tests above --- porting them to any framework is probably not so difficult now that the code has been reorganized so that it's just not some random stuff printing to stdout.

**Comment by pv** [comment]
FWIW, the ccache issue noted by @argriffing above is also now solved --- the problem seemed to be that pip builds and installs stuff to paths with randomly chosen components, which makes ccache generate cache misses. The `run.py` in my repo contains a workaround.

**Comment by pv** [comment]
Ok, I think it's best to wait at least until asv gets proper parameterized test output (https://github.com/spacetelescope/asv/pull/205) --- looks much better than separate curves for everything: https://pv.github.io/scipy-bench/

**Comment by argriffing** [comment]
That looks great!  I don't mind moving benchmarking stuff out of scipy, but one concern would be if a new contributor wanted to add an implementation of some feature along with unit tests and simple benchmarks.  Is there a lightweight way they could do this without having to deal with multiple repos?  My motivation is to not raise the barrier to contribution by domain experts who don't care about github stuff.

**Comment by pv** [comment]
The asv project can be put into a top-level benchmarks/ directory in the
scipy repo without any problems, if that seems better. Other projects
seem to like to put them into separate repos, but it will indeed make
the PR process easier to have it in the same one.
.
asv can run benchmarks also using the currently installed scipy version,
so it's easy to use during development too eg via runtests.

**Comment by argriffing** [comment]
Closing this issue, as @pv has now implemented 'airspeed velocity' benchmarking for scipy through https://github.com/scipy/scipy/pull/4501 and through his contributions to https://github.com/spacetelescope/asv.  I'm not sure about the maintenance/infrastructure plans for keeping the benchmarking results up to date.

**Comment by pv** [comment]
I have a cronjob for it, running this setup https://github.com/pv/scipy-bench-setup
The results repository could be moved under scipy/ at some point.
