### ISSUE TITLE
documentation error in docstring of pdist/cdist

### ISSUE THREAD

**Issue by pierre-haessig** [scipy/scipy#4472]
(follow-up of my message on the mailing-list http://mail.scipy.org/pipermail/scipy-dev/2015-January/020316.html)

I believe there is an error in the docstring of `pdist`/`cdist` in the `scipy.spatial` submodule. The explanation of the layout of the returned distance array seems wrong (and incompatible with the docstring of `squareform`)

http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.distance.pdist.html

> [...]
> ## Returns
> 
> Y : ndarray
>    Returns a condensed distance matrix Y.  For
>     each :math:`i` and :math:`j` (where :math:`i<j<n`), the
>     metric `dist(u=X[i], v=X[j])` is computed and stored in entry `ij`.
> [...]

Is this indeed the entry i*j ? Because the docstring of `squareform` says :

> [...]
> The  X[i, j] and X[j, i] values are set to  v[{n \choose 2}-{n-i \choose 2} + (j-u-1)]
> [...]

Here is Matlab doc for comparison: http://www.mathworks.com/help/stats/pdist.html

Ideally I should have pushed a PR with a fix proposal, but didn't find the time so I'm writing this issue instead. ;-(

**Comment by maniteja123** [comment]
In ``pdist``  docstring, the returned ndarray Y is a condensed distance matrix. According to the MATLAB doc and examples, it looks like it should be ``v[{n \choose 2}-{n-i \choose 2} + (j-i-1)]``, where i<j . 

I think it ``cdist``, the returned matrix is not a condensed matrix, but of size ``ma by mb``. It just needs a change in the statement that says ``ij entry``.

Also, in ``squareform``,  X[i,j] and X[j,i] values are set to v[{n \choose 2}-{n-i \choose 2} + (j-i-1)]``, where i<j . I think it is accidentally typed as ``u`` instead of ``i``. Some other errors like ``d*d(-1)`` instead of ``d*(d-1)``.

Please do correct me if I am wrong, but this is how the implementation of functions looks like to me.

**Comment by rgommers** [comment]
fixed in gh-6914 (and perhaps a few other PRs). `pdist`/`cdist` docstrings have been updated multiple times since 2015
