### ISSUE TITLE
leastsq should use cholesky not inv for hessian inversion

### ISSUE THREAD

**Issue by pv** [scipy/scipy#4555]
The covariance estimate in `leastsq` in is computed using `inv`: https://github.com/scipy/scipy/blob/master/scipy/optimize/minpack.py#L437

```
cov_x = inv(dot(transpose(R), R))
```

However, if the condition number is bad, this can lose positive definitiness. This should use cholesky instead, AFAICS. The result will probably garbage in and out, but PD garbage is probably better than negative variances...

Apparently it is this issue that causes confusion here:
https://stackoverflow.com/questions/28702631/scipy-curve-fit-returns-negative-variance/28704611

**Comment by charris** [comment]
Maybe invert `r` (it's upper triangular), then apply `perm`. This gives a factorization of `cov_x`. It may not be positive definite unless regularized, I think, as `leastsq` still sort of works when the result does not depend on one of the variables due to symmetry.

**Comment by mdhaber** [comment]
IIUC, the suggestion is to return `cholesky(dot(transpose(R), R))` instead of `inv(dot(transpose(R), R))`, but users are currently expecting the inverse rather than some factorization. There are ways to do this, but is it worth it now that `leastsq` is described as "legacy" in the documentation?

![image](https://user-images.githubusercontent.com/6570539/194790805-96e77e38-da61-4324-a01b-781a56bf28f2.png)

Alternatively, we can just begin to return the Cholesky decomposition in the dictionary of optional outputs. That would be much easier. I'm +0 for that.

I'm definitely in favor of not returning a matrix inverse in new code, and I've done a lot of work to avoid matrix inversion in multivariate distributions and `gaussian_kde`, but I'm not sure we want to change this output.

**Comment by mdhaber** [comment]
@ilayn @andyfaff @tupui Does my interpretation of this issue sound correct? If so, is it worth returning Cholesky _instead_ of the inverse (which would require a deprecation cycle), shall we begin to return the Cholesky decomposition as an _additional_ result (which we could do with a [bunch](https://github.com/scipy/scipy/blob/c4bd4ac28561a6f9620240ded15909401ccf3690/scipy/_lib/_bunch.py#L33) object), or shall we let it be?

**Comment by tupui** [comment]
AFAIU, the suggestion is to use Cholesky in leastsq, not to return it no?

**Comment by mdhaber** [comment]
Thanks @tupui ! That's what I thought originally, but the only place `inv` is "used" in `leastsq` is here:
https://github.com/scipy/scipy/blob/656076ca6b490f587e9bd9c4cd10cb259a687c5b/scipy/optimize/_minpack_py.py#L470
where it is immediately returned.
I thought perhaps this suggestion had already been implemented, but Cholesky isn't used either, and looking at the history, this use of `inv` appears to be have been the only one since the beginning.

**Comment by mdhaber** [comment]
Nm I think the main point is to ensure that the output matrix is positive definite. I think we can do that by inverting a factor and muktiplying one inverse by its transpose.

**Comment by mdhaber** [comment]
OK I think I have an example:

```python3
import numpy as np
from scipy import optimize

def f(x, a, b, c, d, e):
    return a*np.log(x + 1 + b) +c*np.log(x + 1 + d) + e

rng = np.random.default_rng(408113519974467917)
n = 100
x = np.arange(n)
y = np.linspace(2, 7, n) + rng.random(n)
p, cov = optimize.curve_fit(f, x, y, maxfev=100000)
print(np.diag(cov))
```

In main, this is:
```
[-1.13375036e+11  3.36959628e+13 -1.13361841e+11  3.32729475e+13  1.36493511e+07]
```
If we change `cov_x = inv(dot(transpose(R), R))` to `invR = inv(R); cov_x = invR @ invR.T`, this becomes:
```
[1.33505056e+11 3.37772173e+13 1.33500405e+11 3.33623809e+13  1.36934955e+07]
```
so at least the diagonal elements are positive, as the user expects.

**Comment by ilayn** [comment]
If `R` is always going to be available and comes from Cholesky factorization then you can send it to `dtrtri` to get the inverse of a lower/upper triangular matrix. Still not fun but I guess this inverse is not avoidable. But at least `A.T @ A` type arrays should always be avoided.

**Comment by mdhaber** [comment]
@ilayn 
> `A.T @ A`  type arrays should always be avoided

You mean that instead it _should_ return the factor `A`? But we don't have any choice now unless we want to deal with a backward incompatibility, right? We need to return an explicit inverse of this matrix at this point. The question is just how to do it efficiently and how to ensure that it always ends up with positive diagonal elements, right?

**Comment by ilayn** [comment]
Ah no I mean if there is a way to operate on the factor then we should avoid A.T @ A multiplications before the operation. This covariance is one of the weird cases that you need the isolated inverse so it is already an outlier.

**Comment by mdhaber** [comment]
Thanks @ilayn.
