### ISSUE TITLE
docstrings in scipy.signal.filter_design.py have differing indentations

### ISSUE THREAD

**Issue by chipmuenk** [scipy/scipy#4558]
Some docstrings are formatted like
"""
good docstring
"""
others like
"""bad docstring
"""
I'm currently developing a GUI for designing digital filters where I try to display the docstrings of the filter_design routines in rich text. Some docstrings have an overall indentation of 4 white spaces, others start with no indentation, giving errors with my reST -> html conversion.

**Comment by pv** [comment]
Both conventions are commonly used in Python code. You should write your
tool so that it can deal with this.
https://www.python.org/dev/peps/pep-0257/#handling-docstring-indentation
The minimal code for this is `lines = doc.splitlines(); result =
lines[0].lstrip() + textwrap.dedent("\n".join(lines[1:]))`

**Comment by chipmuenk** [comment]
Thanx a lot for the clarification and sorry for not searching Web & PEP properly!
