### ISSUE TITLE
DOC: Erroneous latex-related characters in tutorial. 

### ISSUE THREAD

**Issue by rmcgibbo** [scipy/scipy#4585]
I noticed this in the [optimization tutorial](http://docs.scipy.org/doc/scipy-0.15.1/reference/tutorial/optimize.html), but it could be elsewhere as well.

In the rendered HTML, many of the display math formulas have erroneous '\\[' and '\\]' characters displaying at the beginning and end of the formula. The opening bracket is in red.

**Comment by ev-br** [comment]
The offending file is 
https://github.com/scipy/scipy/blob/master/doc/source/tutorial/optimize.rst
(github tries to render the rst, but decides to leave latex markup out, look at the "Raw" version or a local copy)

```
.. math::
   :nowrap:

    \[ f\left(\mathbf{x}\right)=\sum_{i=1}^{N-1}100\left(x_{i}-x_{i-1}^{2}\right)^{2}+\left(1-x_{i-1}\right)^{2}.\]
```
The opening and closing `\[` `\]` are not needed because `.. math::` already opens the displaymath environment.

**Comment by ev-br** [comment]
Reopening in view of https://github.com/scipy/scipy/pull/4595#issuecomment-83052898

**Comment by ev-br** [comment]
fix in gh-4647, closing again.
