### ISSUE TITLE
runtests.py --bench-compare seems to assume that benchmarks do not change

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#4592]
This is probably a user error / UI enhancement request.

Found while trying to measure the overhead in gh-4486

I wrote a trivial benchmark to measure the evaluation time for a PPoly object. Ran 
`$ python runtests.py --bench-compare master interpolate.BenchPPoly`, which worked fine. 

Then I decided to tweak the benchmark, to make the size of some arrays smaller etc. So I change the benchmark code, commit, and...

```
$ python runtests.py --bench-compare master interpolate.BenchPPoly
· Fetching recent changes
· Creating environments
·· Creating virtualenv for py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six.
·· Cloning project
· Installing dependencies.....................
· Discovering benchmarksException RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
..
·· Uninstalling from py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six
·· Building for py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six.............................................................................................................................................................................
·· Installing into py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six..
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
· Fetching recent changes
· Creating environments
· Installing dependencies..
· Discovering benchmarksException RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
..
·· Uninstalling from py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six..
·· Installing into py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six..
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)

All benchmarks:

    before     after       ratio
  [e3f5273f] [a1ebeb91]
-  671.37μs    30.13μs      0.04  interpolate.BenchPPoly.time_evaluation
```

I don't know what these RuntimeErrors are, but a 22x speedup is completely spurious. I'd guess the result from `master` got cached somewhere with the old parameters, while the feature branch benchmark was actually run anew.

**Comment by pv** [comment]
Yes, --bench-compare uses `asv run` without the `-n` flag so it saves
the result. It probably should use `asv continuous` instead to always
rerun the benchmarks.

**Comment by ev-br** [comment]
Where does it store it? I tried `rm -rf benchmarks/env/<long-hex-string>` but that only triggered a full rebuild (twice, I believe) and fetched the same stored result.

Maybe it could somehow eg store the checksum of the benchmark code?

**Comment by pv** [comment]
@ev-br: under `benchmarks/results`

Anyway gh-4592 is probably the proper fix.

**Comment by pv** [comment]
Checksumming benchmarked code perhaps helps tracking changes, but on the other hand
it is not sufficient (at least unless you do complicated dependency analysis, e.g. on changes in test functions for optimizer benchmarks).

On the other hand, you don't want to throw away a long history of benchmark results if there is a cosmetic change in the benchmark.

So the current situation of using `asv rm` to manually remove results 
Also, with gh-4592 you don't need to read ASV documentation if you are only using runtests.py.

(It needs to rebuild twice, since you are benchmarking two different commits. If you have ccache, the rebuild times should not be too bad. Moreover, previous builds are cached.)
