### ISSUE TITLE
Doc: scipy.special.lpmv

### ISSUE THREAD

**Issue by scholich** [scipy/scipy#4615]
The [docstring](http://docs.scipy.org/doc/scipy/reference/generated/scipy.special.lpmv.html) says:

    Parameters:
        m : int
            Order
        v : real
            Degree. Must be v>-m-1 or v<m

but should probably read

    Parameters:
        m : int
            Order. Must be -v <= m <= v
        v : real
            Degree. 

Is it really true that the degree may be real or should it be integer as well?
See also the entry in [Wikipedia](http://en.wikipedia.org/wiki/Associated_Legendre_polynomials#The_first_few_associated_Legendre_functions).

**Comment by helderc** [comment]
According to Wikipedia's article: *The fully general class of functions with arbitrary real or complex values of `l` and `m` are Legendre functions.*

`l` is the parameter `v` here.

**Comment by helderc** [comment]
@ev-br Is that suggestion of @scholich, ok? If so I could do it.

**Comment by ev-br** [comment]
@helderc Cannot immediately say. It's not clear to me from just reading the docstring, and I'm not familiar with the source code.

Ideally, check the source code (https://github.com/scipy/scipy/blob/master/scipy/special/specfun/specfun.f#L7965 if I'm not mistaken), it seems to have references to A&S and DLMF, verify agreement with these tables, check the tests we currently have, see if we need to add more.

**Comment by gertingold** [comment]
The original suggestion to restrict the range of validity to -v <= m <= v is not correct. It applies to the associated Legendre polynomials but the Legendre functions are more general as pointed out by helderc. In #5156, I have added a few references to the [digital library of mathematical functions](http://dlmf.nist.gov) to clarify how the code works. Basically, a representation of Ferrers function of the first kind for non-negative integer order in terms of a hypergeometric function is used and most of the code in LPMV0 is concerned with the evaluation of the hypergeometric function. 

The main restriction in the code in its present form is due to the use of  [DLMF 14.9.3](http://dlmf.nist.gov/14.9#E3) for the handling of negative integer orders. One has to ensure that v+m+1 != 0, -1, -2, ... The relevant line in the code is [line 8004 in specfun.f](https://github.com/scipy/scipy/blob/master/scipy/special/specfun/specfun.f#L8004) ([see also comment in line 8008](https://github.com/scipy/scipy/blob/master/scipy/special/specfun/specfun.f#L8008)). As far as I could see so far, this is the only constraint on the order and degree. I did a few checks by an independent evaluation of [DLMF 14.3.4](http://dlmf.nist.gov/14.3#E4) and could not find any other problematic combinations of order and degree. 

So probably the docstring needs to be changed to specify that integer values of v with v < -m are not allowed.

**Comment by argriffing** [comment]
Here's some `lpmv` detective work.

`scipy/special/generate_ufuncs.py`:
`lpmv -- pmv_wrap: ddd->d                                   -- specfun_wrappers.h`
This means `special.lpmv` is a ufunc connected to `pmv_wrap` in specfun_wrappers.h, and that it takes three double precision floats and returns a double precision float. Some conversion happens automatically for ufuncs with this signature, for example integers and lower precision floats are converted to double precision, but on my system if you pass it a complex number then you get a TypeError.

`pmv_wrap` is defined in specfun_wrappers.c as
```c
double pmv_wrap(double m, double v, double x){
  int int_m;
  double out;

  if (m != floor(m)) return NPY_NAN;
  int_m = (int ) m;
  F_FUNC(lpmv,LPMV)(&v, &int_m, &x, &out);
  CONVINF("pmv", out);
  return out;
}
```
meaning that it checks the order `m`, returning nan if `m` is not an integer and otherwise passing to the Fortran function LPMV, with a changed argument order.

The LPMV function is in `special/specfun/specfun.f`:
```fortran
SUBROUTINE LPMV(V,M,X,PMV)
C
C       =======================================================
C       Purpose: Compute the associated Legendre function
C                Pmv(x) with an integer order and an arbitrary
C                degree v, using recursion for large degrees
C       Input :  x   --- Argument of Pm(x)  ( -1 ≤ x ≤ 1 )
C                m   --- Order of Pmv(x)
C                v   --- Degree of Pmv(x)
C       Output:  PMV --- Pmv(x)
C       Routine called:  LPMV0
C       =======================================================
C
        IMPLICIT DOUBLE PRECISION (A-H,O-Z)
...
```
Here `V` and `X` have implicit double precision, and I guess `M` is an integer.

So in `scipy.special.lpmv` `m` definitely needs to be an integer unless you want to get `nan`, `v` can be a float, and `x` can be a float with absolute value at most 1. I'm not sure about further constraints on the domain but it looks like @gertingold has looked into this.

**Comment by argriffing** [comment]
> Is it really true that the degree may be real or should it be integer as well?

Yes the degree argument (`v`) may be real. I guess `float` is preferred for docstrings. A naive implementation might require the degree to be an integer, but `special.lpmv` can use non-integer degrees.
```python
>>> def naive_lpmv(m, v, x):
...     poly = np.polynomial.legendre.Legendre([0]*v + [1])
...     return poly.deriv(m)(x) * (1-x*x)**(m/2) * (-1)**m
...
>>> special.lpmv(2, [4, 4.5, 5], 0.3)
array([ -2.52525   ,  -7.37990071, -10.462725  ])
>>> naive_lpmv(2, 4, 0.3)
-2.5252500000000002
>>> naive_lpmv(2, 4.5, 0.3)
TypeError: can't multiply sequence by non-int of type 'float'
>>> naive_lpmv(2, 5, 0.3)
-10.462725000000001
```

In the `lpmv` docstring, the type of `x` should be changed from `complex` to `float` if we want to match the actual behavior of the function.

**Comment by gertingold** [comment]
As @argriffing has pointed out, `m` must be an integer. The reason is use of the representation [DLMF 15.8.10](http://dlmf.nist.gov/15.8#E10) of the hypergeometric function which only works in this case. If some progress in the implementation of hypergeometric functions were made (cf. discussion at gh-1561), one could think of providing a more general version of the code based on [DLMF 14.3.1](http://dlmf.nist.gov/14.3#E1) extending `m` to real values.
