### ISSUE TITLE
odeint fails when passed float128 arrays

### ISSUE THREAD

**Issue by alexchandel** [scipy/scipy#4645]
Attempting to integrate an ODE with `odeint` using `float128`s produces the following error:

```python
Traceback (most recent call last):
  File "./psat_ice.py", line 19, in <module>
    P_array = odeint(dPdT, P_trip, T_array).reshape((-1,))
  File "/usr/local/lib/python3.4/site-packages/scipy/integrate/odepack.py", line 148, in odeint
    ixpr, mxstep, mxhnil, mxordn, mxords)
TypeError: Cannot cast array data from dtype('float128') to dtype('float64') according to the rule 'safe'
```

I'm doing calculations that require `float128`s.

**Comment by WarrenWeckesser** [comment]
`odeint` is a wrapper of the LSODA Fortran code from Netlib.  We have only a 64 bit (i.e. double precision) version, so you will not be able to use `odeint` with `float128` data.

**Comment by WarrenWeckesser** [comment]
@alexchandel I'm closing this, because I don't see scipy's ODE solvers being enhanced to use values wider that 64 bits any time soon.  If you really need more bits, you could try asking for suggestions on the mailing list: http://mail.scipy.org/mailman/listinfo/scipy-user

P.S.  If you are desperate for higher precision: Several years ago, I hacked up the Sundials CVODE solver to use *arbitrary precision* floating points values: http://www.warrenweckesser.net/software/sundials_cln/  But you'd have to write your code in C++ to use that code.

**Comment by alexchandel** [comment]
:\ there's no chance that `odeint` could wrap your CVODE extension for f128s, or that LSODA will add f128 support?

**Comment by WarrenWeckesser** [comment]
Realistically, no.  Adding any sort of extended precision ODE solver will be a lot of work, and there isn't really that much demand for it.
