### ISSUE TITLE
Inverse Gaussian distribution is not returning correct pdf

### ISSUE THREAD

**Issue by fsaad** [scipy/scipy#4654]
The inverse Gaussian distribution appears to be returning strange results and has a strange specification. The following appears at

https://github.com/scipy/scipy/blob/master/scipy/stats/_continuous_distns.py#L2484

    Notes
    -----
    The probability density function for `invgauss` is::
        invgauss.pdf(x, mu) = 1 / sqrt(2*pi*x**3) * exp(-(x-mu)**2/(2*x*mu**2))
    for ``x > 0``.
    `invgauss` takes ``mu`` as a shape parameter.

The inverse Gaussian is actually a two-parameter family with a mean (which the docs called shape) and a scale parameter, see

http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.wald.html

Regardless of naming, I am obtaining strange results when evaluating the pdf at some x. 

For instance, if I freeze the pdf such that g = invgauss(1, scale = 1.2) and calculate g.pdf(0.5) the result is 0.82169145168891489. However, the correct result should be 0.915709.

I cross-checked the result with MATLAB's implementation
http://www.mathworks.com/help/stats/inversegaussiandistribution-object.html

and found that

makedist('InverseGaussian','mu',1,'lambda',1.2).pdf(0.5) = 0.915709

although they seem to switch the terms 'scale' and 'shape' parameters in their explanation of the distribution.

**Comment by pv** [comment]
The parameterization of the distribution here follows the generic scheme
used for all the distributions:
```
invgauss.pdf(x, mu) = 1 / sqrt(2*pi*y**3) * exp(-(y-mu)**2/(2*y*mu**2));
y = (x - loc) / scale
```
In particular, the scale parameter is probably not what you though it
is. The documentation calls all parameters apart from loc,scale shape
parameters, regardless of distribution.

**Comment by pv** [comment]
The documentation was reworded some time ago --- please see http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.stats.invgauss.html --- in case that does not clarify it, some rewording may be needed.

**Comment by fsaad** [comment]
Hi pv, in that case the real bug lies in the definition of the inverse Gaussian pdf:

invgauss.pdf(x, mu) = 1 / sqrt(2*pi*y**3) * exp(-(y-mu)**2/(2*y*mu**2));

We need another shape parameter lambda

invgauss.pdf(x, mu) = lambda / sqrt(2*pi*y**3) * exp(-lambda*(y-mu)**2/(2*y*mu**2));

otherwise what we have is an inverse Gaussian pdf with lambda always fixed at 1, which does not give us access to all members of the family.

**Comment by ev-br** [comment]
Your lambda is 1/scale.

**Comment by fsaad** [comment]
I don't think that would work, lambda appears under the square root and in the exponential?

**Comment by ev-br** [comment]
The prefactor is sqrt(lambda), not lambda. The the formula from the docs Pauli linked above, don't he substitution x->x/scale, mu-> my/scale, do not forget the multiplicative factor of 1/scale so that the PDF still integrates to one. The compare tohttp://en.m.wikipedia.org/wiki/Inverse_Gaussian_distribution

**Comment by pv** [comment]
In other words, `lmbda = 1.2; mu = 1; invgauss(mu/lmbda, scale=lmbda).pdf(0.5) == 0.91570869452182313`

**Comment by fsaad** [comment]
Thank you for helping with this, I was unable to understand what was going on. The v0.16 dev documentation is helpful in this regard.

**Comment by michaelsilverstein** [comment]
I think this is worth revisiting. I feel like the current parameterization is unnecessarily confusing. Is there any reason why this function can't be parameterized with mu and lambda?

**Comment by janskorupski** [comment]
The confusion seems to stem from the fact that conventionally the distribution is described with a parameter with the same name ('mu'), but a different meaning (mu != mu/scale). If the distribution implementation is not up to debate, maybe it would be wise to use a different naming convention? After all, the current naming convention is in conflict with the literature (and also with wikipedia for that matter).

**Comment by mdhaber** [comment]
Please consider submitting a PR with a note about the current parameterization and how it is different from the literature. See, e.g. gh-15775, which added a note about the meaning of the `lognorm` parameterization. As for alternate parameterizations, gh-15928 would allow for that, and it is something I'll be working on this summer.

**Comment by mdhaber** [comment]
I think most of the questions above are along the lines of:

> What alternative symbol should be used in this case I don't know as I haven't seen it before. 

Symbols are up to you, but here's an example. You mention that SciPy's $\mu$ is different from the usual definition. Perhaps use $\mu'$ to describe the usual version, and call SciPy's version $\mu$. The names of SciPy's parameters (`loc`, `scale`, and `mu`) are unlikely to be changed. Does that help?

> Does it correlate to any parametrization found in the literature?

Possibly not. The decision to implement all distributions with a generic treatment of location and scale (which is the source of most discrepancies between SciPy parameterizations and the conventional ones) was made about 20 years ago, and it has  probably been debated since then (e.g. see gh-4538). We won't reverse that decision here, but gh-15928 will make it possible to use literature-supported parameterizations. That work is slated for this summer.

**Comment by WarrenWeckesser** [comment]
I agree that SciPy's use of `mu` is confusing and, in hindsight, a different name probably should have been used.  After seeing the recent activity in this issue, I updated my implementation of `invgauss` in [`mpsci`](https://github.com/WarrenWeckesser/mpsci) to use `m` instead of `mu`. I can do that in `mpsci` because I haven't made an official release for it yet, and I can do what I like with the API.  SciPy doesn't have that luxury.

I also added a note about the parametrization in the `invgauss` module docstring: https://github.com/WarrenWeckesser/mpsci/blob/main/mpsci/distributions/invgauss.py.  I think a pull request to add a similar note to the `invgauss` documentation in SciPy would be welcome.
