### ISSUE TITLE
can scipy.spatial.distance.euclidean be faster?

### ISSUE THREAD

**Issue by ruiruige** [scipy/scipy#4665]
i see the code:
    return norm(u-v)

why not like this:
    a = numpy.array(vector1) - numpy.array(vector2)
    return sqrt(numpy.dot(a,a))

**Comment by argriffing** [comment]
One difference is that `norm(u-v)` uses trickery to avoid loss of precision that would result from explicitly constructing the square and then subsequently taking its square root.
http://www.netlib.org/atlas/developer/atlas_contrib/node60.html

**Comment by ruiruige** [comment]
thank u for answer
but if the  loss of precision for me is acceptable, can i use the function of mine to improve speed?
@argriffing

**Comment by ewmoore** [comment]
Try it and see. Be aware, that if you can you should use pdist or cdist instead of calling Euclidean repeatedly.

**Comment by argriffing** [comment]
I'll close this issue because in this case scipy has apparently made a deliberate speed/precision tradeoff.  If there are suggestions to add more flexible user options for these kinds of tradeoffs, or if there are arguments against the tradeoff that scipy has made, then maybe re-open this issue or add a new issue/PR.
