### ISSUE TITLE
Typographical error in stats.fisher_exact documentation

### ISSUE THREAD

**Issue by AGS-Knight** [scipy/scipy#4667]
Looking at the doc located [here](http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fisher_exact.html), an error (play on words, perhaps) is present in the `Notes` section.

>Notes

>The calculated odds ratio is different from the one R uses. In R language, this implementation returns the (more common) “unconditional Maximum Likelihood Estimate”, while R uses the “conditional Maximum Likelihood Estimate”.

Maybe "In R language..." should read something like "The scipy implementation returns....".

**Comment by rgommers** [comment]
I don't know right now which is which without checking, but seems easy enough to fix.

**Comment by daggerdagr** [comment]
Is anyone working on this? Or is it solved already? If the answer is no on both questions, can I pick this issue up?

**Comment by maniteja123** [comment]
[This](https://stat.ethz.ch/R-manual/R-patched/library/stats/html/fisher.test.html) mentions that  ``estimate : an estimate of the odds ratio. Note that the conditional Maximum Likelihood Estimate (MLE) rather than the unconditional MLE (the sample odds ratio) is used.`` in **R stats** package Probably the suggested fix is right. Do correct me if I am wrong as I am no expert in this :)

**Comment by rgommers** [comment]
@daggerdagr no and no - would be great if you could send a PR with the correct text.

**Comment by daggerdagr** [comment]
Will do.

I'm a beginner at this so I hope y'all don't mind a bit of a delay on my part.

**Comment by rgommers** [comment]
No problem, ask if you need any help. Most of the common things people struggle with should be answered in:

https://github.com/scipy/scipy/blob/master/HACKING.rst.txt
https://github.com/numpy/numpy/blob/master/doc/source/dev/development_environment.rst
http://docs.scipy.org/doc/numpy-dev/dev/

**Comment by daggerdagr** [comment]
Sorry for the extremely late update--got beyond swamped with life.

I've been trying to build the edited documentations with 'make html' but I've repeatedly encountered this issue:
![cygdrivecscipydoc_2015-04-26_06-22-52](https://cloud.githubusercontent.com/assets/10735891/7337175/b20c6802-ebdc-11e4-85c0-f63e0deb730e.png)

I've already tried 'make clean' (as mentioned at #4601 ) and it didn't make any difference. I looked around the repository's issues and did see some issues about linprog, but I wonder if that has any relevance to this issue at all. I might be wrong, however.

Otherwise, I've edited the doctest for the function in stats.py. Apologies if this is a beginner's question--do I need to build the doc w/ the edited function to submit a pull request of the edited function? I feel like I do?

**Comment by pv** [comment]
The linprog error is due to the fact that `make html` uses the version
of Scipy installed, and not the version for which the docs are going to
be built for. As you're on windows, building scipy itself requires
various compilers, and is not so straightforward. For documentation
changes such as this, it's not necessary to check the build output.

**Comment by daggerdagr** [comment]
Ah, that makes a lot of sense. I'll submit the pull request, then?

**Comment by rgommers** [comment]
fixed in gh-4771, closing.
