### ISSUE TITLE
Unexpected behavior from scipy.special.btdtri

### ISSUE THREAD

**Issue by d-chambers** [scipy/scipy#4677]
When the first parameter of a beta distribution is small and the second is large the isf returns screwy values. The following SO page illustrates the problem. 

http://stackoverflow.com/questions/29306538/unexpected-behavior-in-scipy-isf

**Comment by robert-dodier** [comment]
Making `dithresh` smaller (I tried 1e-12) at line 70 in scipy/special/cephes/incbi.c makes `incbi` succeed for the example given in the SO post.

**Comment by ev-br** [comment]
Possibly related: https://github.com/scipy/scipy/issues/4244

**Comment by ev-br** [comment]
@robert-dodier @d-chambers any interest in submitting a PR with a fix?

**Comment by robert-dodier** [comment]
@ev-br It would be easy enough to reduce the threshold in order to make it work for the example given in the bug report, but then I think it would just push the problem farther out -- it would still fail for small enough values. On looking at the code, I couldn't see a way to change it so that it would work for all values. Probably for small values, there is a different approximation that could be employed.

**Comment by robert-dodier** [comment]
A different algorithm that could be used is AS 109 from Applied Statistics vol 26, no. 1 (1977). A web search turns up the source code in Fortran and Java. 

AS 109 is the algorithm used (in Lisp translation) by the function quantile_beta in Maxima, and it seems to work OK for quantiles `1 - 10^-k` for `k` up to 16. (For `k` = 17, `1 - 10^-k` is equal to 1.) I didn't check any other properties of it.
