### ISSUE TITLE
FAIL: test_cobyla.test_vector_constraints

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#4726]
With numpy 1.10-dev on 32-bit Linux:

    ======================================================================
    FAIL: test_cobyla.test_vector_constraints
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/rgommers/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/bldscipy/build/testenv/lib/python2.7/site-packages/scipy/optimize/tests/test_cobyla.py", line 100, in test_vector_constraints
        assert_allclose(sol, xsol, atol=1e-4)
      File "/home/rgommers/Code/numpy/numpy/testing/utils.py", line 1300, in assert_allclose
        verbose=verbose, header=header)
      File "/home/rgommers/Code/numpy/numpy/testing/utils.py", line 665, in assert_array_compare
        raise AssertionError(msg)
    AssertionError: 
    Not equal to tolerance rtol=1e-07, atol=0.0001

    (mismatch 50.0%)
     x: array([ 1.400112,  1.700056])
     y: array([ 1.4,  1.7])

Test precision only needs a small bump it looks like.

**Comment by Andreea-G** [comment]
On my 64-bit Mac the solution is array([ 1.39991861,  1.69995931]) instead of array([ 1.400112,  1.700056]). I got the latest SciPy from GitHub. From fmin_cobyla's documentation I see that
 rhoend : float, optional
        Final accuracy in the optimization (not precisely guaranteed). This
        is a lower bound on the size of the trust region.

The default value is rhoend=1e-4, same as atol=1e-4 at line 100 in test_cobyla.py. Since it says the precision is not guaranteed, then probably the tests should not be done for the same precision? 

So we could decrease rhoend and replace
sol = fmin_cobyla(fun, x0, cons_list, iprint=0)
by
sol = fmin_cobyla(fun, x0, cons_list, iprint=0,  rhoend=1e-5)
in test_cobyla.py.

Do you think there's an actual bug in fmin_cobyla and the solution should have in fact matched for atol=1e-4? Or is it just that we needed rhoend to be small enough?

**Comment by dlax** [comment]
@Andreea-G I think `rhoend` (for `fmin_cobyla`) and `tol` (for `minimize`) should indeed be adjusted to `1e-5` in this test (as this is done in other tests actually). Tagging as easy-fix accordingly.
