### ISSUE TITLE
scipy.optimize.bisect feature: Add input arg if we want the 'zero' of f only to be on the right of 0

### ISSUE THREAD

**Issue by aliasnikhil** [scipy/scipy#4825]
I would like bisect to iterate not only till it has found xo (zero of f) between [a,b] within the xtol but also to make sure that f(x0) is greater than 0.
This is my first feature request on github. Please help correct any mistakes in this request.

**Comment by mdhaber** [comment]
Thanks for the idea, @aliasnikhil. Since there have been no comments since the initial post, this does not seem to be a feature that needs an ad hoc API change. However,
we'll resolve this by adding a `callback` method that, among other things, can terminate optimization when a user-defined condition is met. For all bracketing methods, it will give the user access to both ends if the bracket, one side of which is guaranteed to have positive `f(x)`. As part of that, I'll consider adding both ends if the bracket to the output object of `root_scalar`.
That is tracked in gh-6379, so I'll close this one.
