### ISSUE TITLE
Test failures for linalg.qr_insert on 32-bit linux

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#4848]
See https://github.com/scipy/scipy/pull/4812#issuecomment-99555237

Happens for float32 and complex64 arrays. Number of test failures varies when re-running the tests, so something is unstable. Checked that there are random seeds everywhere in the failing tests.

**Comment by ewmoore** [comment]
What do you mean by random seeds?  The seed is set in `BaseQRDeltas.generate` and all random number generation takes place through this function and the overridden `generate` functions in the subclasses..  Since a new instance of the class should be created for each test method run, shouldn't this be enough? Or are multiple methods called from a single instance?

**Comment by pv** [comment]
The issue probably was that despite having a fixed random seed, the
failures are not deterministic?

**Comment by rgommers** [comment]
Indeed, the number of failures is not the same for every run, even though ``BaseQRDeltas.generate`` sets the seed.

**Comment by rgommers** [comment]
@ewmoore do you have time to investigate further? With the MKL failures also on 64-bit (gh-4885), this is a release blocker. If you don't have time soon, then we should consider removing the update functions (all of them, or leave ``qr_update`` in since it's OK?) from 0.16.x

**Comment by ewmoore** [comment]
Unfortunately, I'm not going to have time right now.  We should probably think about punting on at least part of this.

**Comment by ewmoore** [comment]
I wasn't able to reproduce these test failures with the reference blas and lapack on ubuntu 32-bit.  However switching to atlas seem to cause them to appear.

**Comment by rgommers** [comment]
Fixed in gh-4990
