### ISSUE TITLE
the scipy.special.boxcox function is inaccurate for denormal floating point values

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4862]
see https://github.com/scipy/scipy/pull/4839#issuecomment-101250837

**Comment by ewmoore** [comment]
The problem is that it runs out of bits in the `log(x)*lmbda` product when `log(x) < 1` and lambda is small.  But the fix is the same as in #4839.  The function should just return `log(x)` if the product of `log(x)` and `lmbda` will be less that eps since `expm1` doesn't change its input in those cases.  Since `log(DBL_MAX) = 709.78...` the guard can be at 1e19ish and all cases are then covered.  

`special.boxcox1p` should also be updated, but the fix follows the same logic.
