### ISSUE TITLE
ENH: adding "alternative" keyword to stats hypothesis tests

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#4882]
All hypothesis tests should get a keyword `alternative` where applicable, with naming `{'two-sided', 'less', 'greater'}`. Tests that do have them now are:
- `kstest`, added in 3e3e8eaef5, 7cf664323
- `fisher_exact`, added in gh-1919

There are open issues to add `alternative` to:
- `ks_2samp`, gh-2290
- `binom_test`, gh-2417 (with code to copy)
- `mannwhitney`, gh-2118 (more extensive issue, but includes link to a commit from @josef-pkt that adds the keyword).

Other functions where the keyword could be added:
- `chi2_contingency` (R func: http://rpackages.ianhowson.com/rforge/corpora/man/chisq.html)
- `zscore` (R func: http://rpackages.ianhowson.com/rforge/corpora/man/z_score_pval.html)
- the various `ttest`s (now only two-sided; R: http://stat.ethz.ch/R-manual/R-patched/library/stats/html/t.test.html)
- what else?

**Comment by rgommers** [comment]
@aeklant ping

**Comment by rgommers** [comment]
@josef-pkt @WarrenWeckesser @ev-br now would be a good time to add things to the above list

**Comment by aeklant** [comment]
Hello all,

I just made the initial contribution towards solving this issue. I added the alternative keyword to `ks_2samp` and `binom_test` because it was pretty much already implemented by @josef-pkt (thanks Josef), I only had to make minor adjustments but please let me know if you find anything strange or plain wrong.

As for the rest of the functions, I'm afraid I'm going to need some help in the form of a discussion or a good bibliography to get to know the details of the 'two-sided' and 'one-sided' test alternatives. As some of you may know, I'm no statistician (but a software engineer) and my experience is limited to what I have learned so far from my previous contributions over the past two months or so since I joined the community. Anyway, I'm sure I can pick up on the details pretty fast if I'm pointed in the right direction.

PS. thanks to @rgommers for gathering all the scattered info and condensing it into this new issue. It will make my life easier.

**Comment by josef-pkt** [comment]
@aeklant   You should get R, if you haven't done already, and compare results and options.
I guess the `alternative` option can be added to most hypothesis tests. Those based on normal or t distribution are relatively easy. Those based on F or chisquare or a specialized distributions might be more tricky. (I can help with any of those or we skip the `alternative` with some of those, like the anova type tests or k-sample comparisons where it doesn't make sense and it would take other tests for inequalities.)

For example, I have the two sided t-test and z-test in statsmodels with a helper function to reduce some code duplication.

**Comment by chrisb83** [comment]
wilcoxon: #9807

**Comment by WarrenWeckesser** [comment]
`alternative` was added to `binom_test` in https://github.com/scipy/scipy/commit/424128b563f291c71f1a123071f37e1cb22312bd

**Comment by mdhaber** [comment]
The remainder is being organized in gh-12506. For example, `ttest`s are getting the `alternative` keyword in gh-12597.

**Comment by mdhaber** [comment]
I opened gh-12506 before finding this. gh-12506 is now a lot more up to date, and I've copied the relevant information from this over there, so closing this one.
