### ISSUE TITLE
ENH: enable doctests

### ISSUE THREAD

**Issue by aarchiba** [scipy/scipy#4889]
This needs discussion to decide whether it's a good idea, and if so, it needs work to make all doctests pass. It was started by a discussion in PR #4859 .

My argument for enabling doctests: doctests are not there to test scipy functionality. But any example that is a doctest is automatically tested against the current code; without this it is easy for examples and code to get out of sync - in fact PR #4768 exists because this actually happened. The ability to run examples as doctests is present in refguide_check now, but since this is not automatically run, or even convenient to manually run over everything, the problem can be expected to recur.

An argument against doctests: doctest markup clutters docstrings. I believe that online doc generation strips out doctest markup, so this is largely an issue for interactive inspection of docstrings.

For comparison, astropy runs all its examples as doctests; you can judge for yourself whether the level of extra cruft is worth it: http://astropy.readthedocs.org/en/latest/

**Comment by matthew-brett** [comment]
My own vote would be to enable - we have no other way of making sure the doctests still work.

We can always skip doctests that are hard to test.

**Comment by argriffing** [comment]
> This needs discussion to decide whether it's a good idea, and if so, it needs work to make all doctests pass. It was started by a discussion in PR #4859 .
My argument for enabling doctests: doctests are not there to test scipy functionality. [...]

My vote would be to enable doctests, and also to invent some mechanism or policy preventing the gradual migration of scipy functionality tests into the doctests.

**Comment by rgommers** [comment]
My vote would be to run them on TravisCI, which should take care of keeping them up-to-date with code changes, but not enable them as part of ``scipy.test()`` or ``scipy.test('full')``. Doctests are just too fragile to want to run them by default.

**Comment by ev-br** [comment]
On a technical level, it seems reasonably easy to filter most of the noise from docstrings: https://github.com/scipy/scipy/pull/4892

If there's voting, I'm +0.5 for running something like #4892 on TravisCI, as long as it's there for information only --- it should be allowed to fail without failing the build (eg, `allow_failures:`, http://docs.travis-ci.com/user/build-configuration/ or equivalent).
And I strongly agree with @rgommers (re: `scipy.test`) and @argriffing (re: gradual migration towards doctestability).

**Comment by rgommers** [comment]
Regarding markup ugly-ness, we could keep a simple list of skipped/knownfail doctests somewhere in ``tools/``, so we don't need to add any markup to the docstrings. I like my ``func_name?`` to look good in IPython:)

**Comment by ev-br** [comment]
Re doctest-specific markup: it seems to be not needed in fact. A bit of fiddling with doctest internals shoves it all into the test runner/checker (cf #4892)

**Comment by rgommers** [comment]
It can't all be in the generic checker right? If a doctest fails and we want to not change it for didactic reasons for example, it somehow needs to be marked as skipped/knownfail.

**Comment by ev-br** [comment]
Here's an example: https://travis-ci.org/scipy/scipy/jobs/63885596

 gh-4892 now enables a modified doctesting and runs it on TravisCI. The amout of noise seems reasonable, and the runner keeps a list of functions to skip, so that the docstrings can be all kept clean from the doctest directives (specifically, I opted for keeping a list of exceptions in the doctest runner rather than registering new doctest-level directives; the latter seems possible but IMO undesired).

Since @aarchiba mentioned astropy, I had a look at https://github.com/astropy/astropy/blob/master/astropy/tests/output_checker.py.
I might be biased :-), but it does seem to me that we can do without the "hopelessly byzantinne" complexity of float parsing which the latter uses, especially if we stick to the policy of avoiding a hard requirement that doctests must all pass. Maybe @embray, as the author of astropy doctest output checker,  can offer his perspective.

What is missing from gh-4892 is a paragraph or two of text in a devguide explaining our stance about doctesting (to the effect of what @argriffing was saying about a separation of doctesting and functional testing.)

**Comment by embray** [comment]
FWIW I didn't author the original version of that, but rather borrowed it from SymPy.  I've since made a number of improvements to it though which I should probably get around to contributing back at some point.

That said, it works extremely well at this point and we've done a lot of work on getting doctests to just work.  In particular the float stuff has been pretty solid for a while now.  The only thing that makes it a little tricky is that it's also contextual--that is, it will only look for floats if they are surrounded on either side by whitespace or by specific characters like parens.  There are a few times I've had to extend the context in which they can be found.  At this point it should work for most contexts I've ever seen in SciPy's examples.

I may have some other useful experience I can add to this, though in the meantime marking troublesome doctests as xfail could work.

**Comment by rgommers** [comment]
@ev-br regarding devguide, part of it is in https://github.com/numpy/numpy/blob/master/doc/TESTS.rst.txt#id6. That is missing the "these are not part of the test suite" phrase however.

I've made a start in https://github.com/rgommers/scipy/commits/devguide

**Comment by pv** [comment]
This may be of some interest here:
http://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-To-Fail

**Comment by ev-br** [comment]
Thank you @embray for offering your perspective. We might revisit the mechanics of doctesting in the future if our current setup proves inflexible.

This issue seems to have been resolved by merging gh-4892 and (a herculean effort of) gh-5035. Modified doctesting runs on Travis CI, the current codebase is doctest-clean after gh-5035. I think this can be closed now?

**Comment by pv** [comment]
Yes, I think it's mostly resolved, closing.
