### ISSUE TITLE
BUG: stats: The `fit` method of the distributions silently ignores invalid keyword arguments.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#4932]
This issue was noted in this question on stackoverflow: http://stackoverflow.com/questions/30585679/gamma-fit-over-axis-3d-array

The `fit` method silently ignores keyword arguments that it does not use.  It should raise a `TypeError` when given an unknown keyword argument.

Here's a simple `fit` example:

    In [20]: from scipy.stats import gamma

    In [21]: gamma.fit([1,2,3,3,3,4,5,7])
    Out[21]: (3.6899039741659925, 0.049374155400321737, 0.93515411814698823)

The following two calls should raise a `TypeError`.  Instead, the invalid argument is ignored:

    In [22]: gamma.fit([1,2,3,3,3,4,5,7], axis=123)
    Out[22]: (3.6899039741659925, 0.049374155400321737, 0.93515411814698823)

    In [23]: gamma.fit([1,2,3,3,3,4,5,7], flibbity=123)
    Out[23]: (3.6899039741659925, 0.049374155400321737, 0.93515411814698823)

**Comment by BMJHayward** [comment]
If I do:
```
data = [1,2,3,3,3,4,5,7]
gamma.fit(data, *data)
```
Then I get:
TypeError: Too many input arguments

If I also do:
```
gamma.fit(data, **data)
```
I get:
TypeError: fit() argument after ** must be a mapping, not a list.

Class rv_continuous(rv_generic) in scipy/stats/_distn_infrastructure.py specifies the fit method.
This is as far as I've got at the moment.

**Comment by ev-br** [comment]
@BMJHayward `.fit(data, *data)` is not going to work because `*args` are assumed to give the starting point for the optimizer which solves the MLE problem. For `gamma` there should be *I think* no more than three entries (for a, loc, and scale).
http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.stats.rv_continuous.fit.html

The immediate issue here seems to be solved by a bit of scotch tape and a couple of dabs of glue (gh-4951). 

There is definitely room for improvement however. Off the top of my head:

* Many combinations of parameters are untested and are likely incorrect. For example, what happens if a starting value is supplied for a parameter which is fixed by an `f`-keyword.

* More informative error message should be given for the case with too many `*args`.

* It's not currenly possible to use keywords to specify starting values for parameters.

* There is some special-casing for `gamma` and `beta` distributions, which override the generic `fit` method in the name of efficiency. There might be a room for pulling some of this up the inheritance chain (eg, are there other distributions can benefit from special code paths for fitting with floc and/or fscale?)

* There's a dozen or so distributions where fitting just does not work at all.

**Comment by BMJHayward** [comment]
Yes indeed, that was just the only way I could get fit() to throw a TypeError. rv_continuous also defines a numargs attribute which throws a type error if you exceed it. Actually rv_generic defines it, IIRC.

> Many combinations of parameters are untested and are likely incorrect. For example, what happens if a starting value is supplied for a parameter which is fixed by an f-keyword.

Back to rv_generic, it looked as though it can take f1,f2,...,fn as named arguments. I think I'll look into that a bit more as well.

**Comment by WarrenWeckesser** [comment]
A similar issue has returned, or this pull request didn't completely fix the problem.  See, for example, this [question on stackoverflow](https://stackoverflow.com/questions/57064461/plotting-histrogram-with-weighted-bell-curve), where the argument `weights` in   `stats.norm.fit(df2['WIDTH'], weights=df2['QTY_ORD'])` is silently ignored.

I'm working on a new pull request to fix this (and a few other issues related to this).

**Comment by WarrenWeckesser** [comment]
New pull request is https://github.com/scipy/scipy/pull/10479
