### ISSUE TITLE
scipy.stats.dirichlet.pdf() bug

### ISSUE THREAD

**Issue by maojrs** [scipy/scipy#4949]
scipy.stats.dirichlet.pdf output is incorrect. Tested with simple binomial, which has obvious answer.

**Comment by argriffing** [comment]
@maojrs Do you have an example that could be added to the [tests](https://github.com/scipy/scipy/blob/maintenance/0.16.x/scipy/stats/tests/test_multivariate.py#L347)?

**Comment by maojrs** [comment]
@argriffing apologies! I just double checked, and I think it does what it's supposed to. I thought the Dirichlet distribution was just a continuous version of multinomial distribution; now I see it is its conjugate prior. However, it would be nice if multinomial distributions were also incorporated out of the box.

**Comment by ewmoore** [comment]
Having glanced at the tests for this, let me say that np.random.uniform(1e-10, 100) doesn't really test down to 1e-10 in a meaningful way.

**Comment by argriffing** [comment]
> Having glanced at the tests for this, let me say that np.random.uniform(1e-10, 100) doesn't really test down to 1e-10 in a meaningful way.

Maybe this is just to guard against exact zeros until a numpy PR like https://github.com/numpy/numpy/pull/5872? @hildensia do you have an idea about this decision for the dirichlet distribution unit tests?

**Comment by hildensia** [comment]
For `alpha` it is to ensure all alphas are bigger than 0 since a zero alpha is not defined. For the `x` array there actually might be zero entries, but if we end up with a zero vector (i.e. all entries zero) and then normalize to `np.sum(x) == 1` we divide by zero (see e.g. https://github.com/scipy/scipy/commit/5cff15112b1d4352bcc3ee8cc970fce0176564b6#diff-edd4ec9cd7afebecda51f7f29124af70R370).

That said I use it only in tests, where I don't mean to test the whole support for correct answers, but that on a given position some other tests pass, so I would say testing really down till `10e-10` is not very important.

**Comment by hildensia** [comment]
Btw. I agree with @maojrs - a multinomial would be a nice addition. I start implementing it.

**Comment by ewmoore** [comment]
Ok. Sorry for the noise.

**Comment by argriffing** [comment]
> For alpha it is to ensure all alphas are bigger than 0 since a zero alpha is not defined.

Mathematically I think it's OK for some (but not all) alphas to be zero, and people are wanting this for example in https://github.com/numpy/numpy/issues/5851.  As an example, if you have a dirichlet distribution with alpha = (42, 99, 0) then I think this is a mathematically legitimate distribution, but without support for any observation in the last category.  So the pdf would evaluate to zero (and the logpdf would be -inf) if there is an observation in that category.  Sampling is not a problem because you just pretend that category does not exist.

On the other hand I vaguely recall that @josef-pkt has said that scipy.stats is intentionally not careful about these kinds of edge cases.  Also the [Wikipedia entry](http://en.wikipedia.org/wiki/Dirichlet_distribution) currently requires all concentration parameters (alpha values) to be strictly positive, so maybe I'm just wrong.

**Comment by hildensia** [comment]
Sounds correct. It (more or less) degenerates to a dirichlet distribution with dimension one less. Should we somehow take care of that?

**Comment by argriffing** [comment]
Added issues https://github.com/scipy/scipy/issues/4953 and https://github.com/scipy/scipy/issues/4954.
