### ISSUE TITLE
signal.welch: Last frequency incorrectly negative

### ISSUE THREAD

**Issue by johannesgijsbers** [scipy/scipy#4962]
I was evaluating the latest beta for replacing the matplotlib.mlab spectral estimation functions, as I much prefer the interface implemented in scipy.signal. However, I believe I may have run into a bug.

    import numpy as np
    from scipy import signal

    target = np.sin(np.linspace(0, 5, num=300))

    pf, p = signal.welch(target, nperseg=75, fs=60, nfft=600)
    print(pf)

Last frequency is -29.9 instead of 29.9 as I would have expected. There may be an issue with https://github.com/scipy/scipy/blob/master/scipy/signal/spectral.py#L875, implemented in #4682. Hopefully @e-q can shed some light here?

**Comment by e-q** [comment]
Good catch! It turns out to be a bug where I tested the sign of nperseg instead of nfft when figuring out the number of frequencies to return. 

In reference to your goals, though, you should know that these functions were not written from scratch for scipy, but indeed adapted from the `matplotlib.mlab` code. The only appreciable difference in functionality is that this code allows operating over multidimensional arrays.

**Comment by johannesgijsbers** [comment]
Thanks for your quick response, glad I could be of help.

I suppose the functionality is pretty much the same, but I like the argument naming a bit more in scipy.signal. Also, using scipy.signal would allow me to drop a dependency on matplotlib, which is always nice.
