### ISSUE TITLE
scipy.sparse.linalg.eigs() sometimes returns wrong EigenVectors

### ISSUE THREAD

**Issue by romanc** [scipy/scipy#4987]
I discovered the following irregularity in the behavior of ``scipy.sparse.linalg.eigs()``: 

When running mentioned function several times on the same matrix, the returned EigenVectors are wrong in a specific pattern. Using the minimal example below, scipy failed for samples 3, 12, 28 and 42. This sequence is reproducible, even on multiple laptops.

Note that it seems independent of the python version (2.7.9 and 3.4.2) and the scipy version (I started in 0.13.3 and it persisted in 0.15.1).

This bug might relate to #3613 and the therein mention [scilab bug report](http://forge.scilab.org/index.php/p/arpack-ng/issues/1315/).

The complete code, including matrix definition, is [available here](https://storage.sg.ethz.ch/users/rcattaneo/mwe.py). 

```python
import numpy as np
import scipy.sparse as sparse
import scipy.sparse.linalg as sla

# matrix definition
# data    = np.array(...)
# indices = np.array(...)
# indptr  = np.array(...)

matrix = sparse.csr_matrix( (data, indices, indptr), shape=(400,400) )

samples = 50

for s in range(samples):
        w, pi = sla.eigs( matrix, k=1, which="LM" )
        pi = pi.reshape(pi.size,)
        pi /= sum(pi)
        print("EV[0:10] for sample", (s+1), ":")
        print(pi[0:10])
```

**Comment by pv** [comment]
Note that the "exceptional" eigenvectors you get are correct, but
correspond to a different eigenvalue.
.
One issue is that iterative methods in general cannot give 100%
guarantee that if you specify which="LM", you get the largest
eigenvalue; the algorithm does not calculate all eigenvectors so it
cannot be fully sure that it found the largest.
.
Since the initial vector is randomly selected in case it is not
explicitly given, you can have bad luck and not converge where you
expect in some cases (cf. v0 parameter for initial guesses). You can
increase the probability to converge to the correct result by increasing
the `ncv` (the number of auxiliary eigenvectors considered).
.
Since you are using which="LM", the arpack-ng issue mentioned above is
probably not related.

**Comment by romanc** [comment]
@pv: Thanks for the quick response. It really looks like increasing the number of auxiliary eigenvectors solves the problem.
