### ISSUE TITLE
scipy.stats.probplot: R^2 printed on figure is actually R

### ISSUE THREAD

**Issue by hrm1234** [scipy/scipy#5032]
In the function scipy.stats.probplot, it looks like the "R^2" value that is printed on the plot is actually just R. The source code shows that the linear fit is made using stats.linregress, which returns R, and R is later added to the figure with the seemingly incorrect label of "R^2". 

Thanks for having a look into this!

**Comment by rgommers** [comment]
It looks correct to me. The relevant lines in ``probplot`` are:

    slope, intercept, r, prob, sterrest = stats.linregress(osm, osr)
    plot.text(posx, posy, "$R^2=%1.4f$" % r**2)

So the value returned by ``linregress`` gets squared when adding it to the plot as text.

**Comment by WarrenWeckesser** [comment]
@hrm1234 didn't state which version of scipy was used.  This problem existed in older versions, and was fixed by https://github.com/scipy/scipy/pull/4097.  (I'm commenting now because of http://stackoverflow.com/questions/36151265/bug-stats-probplot-returns-as-text-inside-the-plot-r-not-r2-as-it-says.)
