### ISSUE TITLE
periodic boundary of cKDTree

### ISSUE THREAD

**Issue by rainwoodman** [scipy/scipy#5084]
Is there a plan to include a periodic boundary in cKDTree?

**Comment by rgommers** [comment]
Not that I know of. Not even sure what that means exactly. Can you explain?

**Comment by sturlamolden** [comment]
As in a toroidal space? I am not even sure a kd-tree is a valid partition for such a geometry, but it might be (I have to check).

**Comment by rainwoodman** [comment]
I mean where x + nL and x are the same location. (not sure what a toroidal space is) In cosmology simulations we use KD-Tree to look for neighbours in a periodic box all the time. Here is an example: https://github.com/N-BodyShop/fof/blob/master/kd.c

The simplest solution is probably merging the results of all 3**Ndim images. But that's not very efficient (e.g. 3**3 = 27)

**Comment by sturlamolden** [comment]
Yes, then we mean the same thing. Consider a 2 dimensional universe. If both dimensions are periodic, you actually have a doughnut shaped universe, i.e. a torus.

**Comment by rainwoodman** [comment]
I see. What is a better partition for such a space? We cosmologists may have been using the wrong data structure for too long!

anyhow, I recalled that I implemented this `toroidal` boundary on a KD-Tree, with a modified 'distance' function. I only used this for euclidean distances, but it seems to be able to extend to other norms in cKDTree. The bottom line is that using a KD-Tree on a 'torus' space is possible. 

The idea is to use a four segment function to estimate the min/max distance between two nodes in a direction rather than a two segment function (for non-periodic). the distance between two points is also wrapped with the classical half box trick. 

The relevant code pieces are here:

https://github.com/rainwoodman/kdcount/blob/master/kdcount/kd_count.h#L42
https://github.com/rainwoodman/kdcount/blob/master/kdcount/kdcount.h#L376

and 

https://github.com/rainwoodman/kdcount/blob/master/kdcount/kd_count.h#L147

Will it be possible to put something like this in the current cKDTree code?

**Comment by sturlamolden** [comment]
If it is just a modification of the distance function, I think we could, unless it incurs a performance regression. I don't think it should, because of ```NPY_LIKELY``` and ```NPY_UNLIKELY``` and branch prediction. It would then mean that your periodic kd-tree would take the performance it of having the CPU pipeline flushed whenever the distance function is called. This is possibly not very nice, so you might prefer to have this in a separate kd-tree object instead. 

If it also means that we have to change the logic that adds kd-tree nodes to the priority queues and trackers, then I would not recommend it in the current ```cKDTree```. It would be a terrible mess.

There is also a data structure called ball-tree, which is faster to search than a kd-tree (but slower to construct) and also allows more arbitrary distance functions. kd-trees are limited to Minkowski distances, as far as I know. I have a plan of proposing that for ```scipy.spatial``` later on.  😊

**Comment by sturlamolden** [comment]
I have a feeling that your proposal will be easier to implement with a ball-tree, because we might need to rearrange the nkde tracing code in ```cKDTree``` to make a periodic distance function work.

**Comment by rainwoodman** [comment]
Closing this -- Implemented by #5091.
