### ISSUE TITLE
scipy.stats.median_test: enable choice of using numpy.nanmedian over default numpy.median

### ISSUE THREAD

**Issue by dankras** [scipy/scipy#5114]
scipy.stats.median_test currently uses numpy.median when calculating the "grand_median" across the set of all samples. (grand_median = np.median(np.concatenate(data))

Users should be able to specify numpy.nanmedian instead.

**Comment by rgommers** [comment]
You want to treat NaNs as "missing data" right? We're in the process of adding support for that to a lot of ``stats`` functions in gh-5007.

We can do the same here - instead of specifying ``nanmedian`` we can add a ``nan_policy`` (or ``nan_action``, tbd) keyword where the default is ``'propagate'`` but you'd want ``'omit'``.

**Comment by rgommers** [comment]
(easy-fix once gh-5007 is merged)

**Comment by adivijaykumar** [comment]
This is already implemented. Close?

**Comment by WarrenWeckesser** [comment]
> This is already implemented. Close?

Yes.  To ignore `nan`, use the argument `nan_policyt='omit'`.
