### ISSUE TITLE
Optimizers reporting success when the minimum is NaN

### ISSUE THREAD

**Issue by larsmans** [scipy/scipy#5161]
Followup to #4793: CG and L-BFGS-B report `success: True` when the minimum is NaN. BFGS was fixed in #5129; the fix for L-BFGS-B should be similar. I haven't checked CG yet.

**Comment by andyfaff** [comment]
differential_evolution reports `success: False`.  However, it does a whole lot of function evaluations to get there.  Is there a default position on what a minimizer is supposed to do when the objective function returns NaN?  Should the minimization halt?

**Comment by mdhaber** [comment]
This is still an issue:
```
import scipy.optimize
def f(x):                                                                        
    return float('nan')

for method in ["COBYLA", 'Powell', 'nelder-mead', 'L-BFGS-B', 'BFGS', 'CG', 'TNC', 'SLSQP', "Newton-CG", 'dogleg', 'trust-ncg', 'trust-exact', 'trust-krylov', 'trust-constr']:
  print(method)
  res = scipy.optimize.minimize(f, 1, method=method)
  print(res)
```

**Comment by andyfaff** [comment]
Reporting success in this circumstance is clearly wrong, and very annoying. 
One way to fix this would be to do a final check in `minimize` and change `success` to `False` if `res.x is np.NaN`. The drawback of this is that minimize is purposefully changing the output of an individual minimizer. Thus, if the user went directly to the minimizer (`f_*`) they would get a different answer.
Whilst this situation may be clearcut, there are other inconsistencies affecting the minimizer stable. For example, is `maxiter` exceeded, is `maxfex` exceeded, what should the minimizer output be if constraints are bounds exceeded, etc? The latter one depends on the type of minimizer used because some constraints may allow a certain tolerance.
At the moment to solve these issues one has to address each minimizer in a piecemeal approach. Additional tests are normally directed to an individual minimizer.
These issues were a key factor in a SciPEP I was trying to write (with @stsievert) that proposed having a `Minimizer` class. With a class based approach and inheritance one can solve a lot of these issues by changing code in a single place, the base `Minimizer` class. There is then a straightforward way to test every `Minimizer` that inherits the class.
Unfortunately the SciPEP didn't get a lot of traction and I lost heart. :-(.
