### ISSUE TITLE
scipy.spatial.distance.pdist coerces to double

### ISSUE THREAD

**Issue by wasade** [scipy/scipy#5187]
`scipy.spatial.distance.pdist` coerces to double [here](https://github.com/scipy/scipy/blob/v0.16.0/scipy/spatial/distance.py#L1180). The issue is that I'd like to use `pdist` with a method written in Cython which is typed to only accept `int64` data. Is this coercion necessary? I'd be happy to issue a PR, but before doing so, I wanted to check first if it would be a waste of time.

**Comment by juliantaylor** [comment]
there is only code for double and bool, though bool is unused due to the coercion (see https://github.com/scipy/scipy/issues/5027). There is probably no reason there aren't more types besides nobody wrote the code.
Though why do you need int64 specifically? I don't think the conversion from double back to int should be very expensive, do you need the full 64 bit range?

**Comment by wasade** [comment]
Good point -- I retooled it to allow an untyped numpy array and there really wasn't an appreciable difference in runtime. So, perhaps this is moot. The motivation for int64 here is that the data are counts, so the natural type is unsigned int.
