### ISSUE TITLE
Deprecated routines in Netlib LAPACK >3.5.0

### ISSUE THREAD

**Issue by zerothi** [scipy/scipy#5266]
Several LAPACK routines have been deprecated in the current development of LAPACK.
NOTE that one can still force the addition of the routines, but the default is not to add the symbols to the LAPACK library table.

I am not sure how deprecation symbols should be handled in scipy, hence I refrain from beginning a PR.

The bug arises when trying to import scipy.linalg where it errors out due to missing symbols (obviously).

Currently my own work-around are these steps:
1. `sed -i '/[sdcz]gegs/d' scipy/linalg/cython_lapack_signatures.txt`, remove signatures 
   Note that this should also be applied to alle these routines as well:
   - gegv
   - gelsx
   - geqpf 
   - ggsvd
   - ggsvp
   - latzm
   - lahrd
   - tzrqf
2. `sed -i '/2[c]*>gegv/{N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;N;d}' scipy/linalg/flapack.pyf.src`, remove interfaces for f2py (only the gegv routine is in the pyf source)
3. `python _cython_wrapper_generators.py`, regenerate `cython_lapack.pxd` from signatures
4. `python tools/cythonize.py`, update the cython_lapack.c file

and it works again.

Possibly checking the LAPACK library for the corresponding interfaces would be sufficient to decide whether the interface should be added or not.

**Comment by insertinterestingnamehere** [comment]
Wow. The last time there were significant interface changes was in the transition from 3.1 to 3.2. I'm surprised they are removing so many routines now. There isn't an ETA on the next release that I'm aware of though. It would really help if we had a clear idea of when they are going to do their next release so we could plan for when to deprecate our wrappers.

Here are a few possible policies for how we can handle changes in LAPACK:

- Detect the LAPACK version at compile time and match our Cython wrappers to the functions that are present there. This would take some effort to set up and would be marginally harder for downstream maintainers, but it would be easier to maintain in the long run since all that would be needed is to add signatures as needed.
- Deprecate those particular routines in a minor release and remove them in the next major release. The faster we remove them, the fewer people will rely on them.
- Put a deprecation warning out in the next release and then remove them the release after that.
- Include our own copies of the missing routines and use them to allow for a longer deprecation cycle on our end.
- Build our own LAPACK as a part of SciPy.

Personally, I favor the first approach, but it will take a good bit of time to get it all set up. Any thoughts?

**Comment by zerothi** [comment]
I cannot say for all routines, but at least some of them have simply changed names. So in those cases a simple reference would suffice (gegv).
Per the devs of lapack are many of the routines deprecated since 3.2, but only (re)moved now. 

Option 2 and 3 are still good choices, but I think very few will see the warnings any way. That is my feeling from hearing people using other libraries. 

For future maintenance i also like the first option. I guess we can reuse a segment of numpy.distutils which checks for a routine in blas. 
I can look into a small showcase snippet for the functionality (I have already done some work on the distutils and think I know how to implement it) , but let you do the final merge? 

I really don't like the last option, even that would require substantial amount of time and effort to setup _and_ maintain. (I hate duplicate work ;)) 

In the same go the checks can also be used for the blas package. Certain implementations (mkl, openblas) have c/zgemm3m routines which in some cases are faster than the original c/zgemm. Such small enhancements could then also easily be added  and used via a single interface check.

**Comment by pv** [comment]
It would be helpful if the set of functions available is the same on all Scipy installations, as otherwise this brings about portability issues. This sort of assumes stable lapack api, but if the only changes are renamed functions, I think we can deal with that.

**Comment by zerothi** [comment]
While I completely agree on the portability issues I think that the libraries that use such functions should follow updates from the underlying libraries. If total backwards compatibility is requested then shipping the library with scipy seems like the *only* option. 

From what I could gather are all the routines superceded and announced deprecated long time ago by other routines. Hence any usage would still be deprecated using pure lapack. As libraries evolve, so I think that users of the library should evolve (here scipy). The decision to deprecate the routines have surely been made considering all other options.

All "missing" routines could have a python equivalent with deprecation warning which notifies about underlying deprecation?

Sorry for the blurp, but I think that total backwards compatibility is a nightmare to maintain and will prohibit other,  more important,  things to implement.

**Comment by pv** [comment]
The situation here is somewhat different from typical backward compatibility issues. There's no way for a 3rd party library to know at compile time (or runtime) what version of the library scipy is linked against. The API that we have here is ours, not that of LAPACK, and shouldn't be determined by what version of LAPACK happens to be installed on the machine in question.

**Comment by pv** [comment]
The easiest approach would probably be to just remove the deprecated routines outright in the next scipy version, and note this in the release notes. Otherwise, to support them on LAPACK 3.6, we'd need to bundle copies of the old routines.

I'm not sure if it's possible to provide information on the LAPACK version used somehow. This would be need to be done at runtime (depends on dynamic linking), and it's not necessarily the same as that obtained via distutils, since the function pointers come from the version linked in scipy's linalg dll.

**Comment by insertinterestingnamehere** [comment]
Removing them in the next release sounds fine to me. That will keep the changes here relatively small and it is a reasonable removal given that these have already been deprecated.

OTOH, if we decide to go ahead with dynamic detection, LAPACK has the routine `ilaver` that will allow us to detect the LAPACK version. We could detect the version at build time via ctypes and then generate the appropriate set of wrappers. This would also allow us to export a Python function as a part of the Cython API that allows other Python modules to check the lapack version used in SciPy. Detecting the routines dynamically would also allow us to provide wrappers for *all* the routines available rather than just the ones with a static API between LAPACK versions. The primary downside is that bad things would happen if we didn't link statically against LAPACK and the user decided to change the version they have installed.

Both approaches sound reasonably workable in general, the question is which will work better with the precedent set in SciPy. Removing them is likely to cause fewer weird errors for users, so that may be the best in this case.

**Comment by zerothi** [comment]
I have created a PR #5268 which enables the functionality of dynamical checking of all signature routines for blas and lapack.  
It isn't used yet, but could easily be used if one has cython installed?

**Comment by pv** [comment]
I don't think there's an upside to providing the deprecated lapack routines that justifies allowing the API to vary between installations. There's not a lot of legacy code to support here. Since the deprecated routines have non-deprecated equivalents, the correct action for users is to not add version checks to their code, but to upgrade to non-deprecated codes.

**Comment by insertinterestingnamehere** [comment]
Removing the routines sounds good to me. We'll need to remove them from the signature list, add them to the exceptions list in https://github.com/scipy/scipy/blob/master/scipy/linalg/_cython_signature_generator.py#L116, and then rerun the generating script. There is a lot of appeal to having anything exported by SciPy be common across all supported BLAS/LAPACK versions.

**Comment by congma** [comment]
I'm a bit confused.  Does scipy actually call any of the deprecated functions for its linalg functionality?  Or is it about exporting LAPACK functions to Python?

**Comment by pv** [comment]
This is about exporting functions --- afaik, the functions are not called by scipy itself.
However, if they are not present in the LAPACK library, scipy probably won't build/run because of missing symbols.

**Comment by ignatenkobrain** [comment]
One note that those functions moved to deprecated and it still possible to build within.

**Comment by zerothi** [comment]
Sure, but for how long will deprecated routines be supported? 
Supporting deprecated functions (which requires people to custom build their lapack library) is a bad choice. 
Enabling an "expert" build which dynamically checks the available routines is better.

**Comment by rgommers** [comment]
Note, reopened because of (comment on gh-5266):

    #5266 should be reopened until we get the f2py deprecations taken care of in another PR.

**Comment by jdemeyer** [comment]
> Several LAPACK routines have been deprecated in the current development of LAPACK.

1. That version is now released, it is no longer a development version.

2. Despite LAPACK claiming that the functions are *deprecated*, they are really *removed*: using SciPy 0.16.1 with LAPACK 3.6.0 does not work.

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/pull/5576 has been merged this morning, so that current master branch should work fine (it'd be helpful if you could verify that it works for you)

**Comment by piannucci** [comment]
It looks like the generalized SVD baby (#743, #1491) got thrown out with the ggsvd bathwater -- there is a recommended replacement routine, ggsvd3, which has the same documented behavior.

**Comment by insertinterestingnamehere** [comment]
@piannucci you mean in https://github.com/scipy/scipy/pull/5518? That was deliberate. The replacements for those routines were added in LAPACK 3.6.0. The abrupt deprecation was a decision made by the LAPACK developers that we had to work around. We can't include them without either increasing our required LAPACK version or including the needed source files directly.

While I'm personally in favor of increasing the reuired LAPACK version, increasing it all the way up to 3.6.0 isn't at all viable. Including the needed source files directly as in https://github.com/scipy/scipy/pull/5576 may or may not work in this case. I'll defer to others as to whether or not including extra files is a good idea for anything other than deprecated routines.

**Comment by piannucci** [comment]
Do I understand this correctly?  That compatibility with the newest supported LAPACK required scipy to remove ggsvd, and compatibility with the oldest supported version prevents scipy from including ggsvd3?  So even though there was never a version of LAPACK that did not include a viable generalized SVD, there must now be (possibly many) versions of scipy that do not?

**Comment by insertinterestingnamehere** [comment]
The main issue here is that there isn't a consistent interface across the versions of LAPACK in common use. There's not a whole lot we can do to fix that.

It may be possible to include the source files for the new generalized SVD routines as a part of our source, compile them as a separate shared library, and then set up linking so that only the `*ggsvd` and `ggsvp` routines are taken from the new library. Mixing source files from different releases seems like risky business, but we could probably set things up so that that doesn't happen.

Anyone else care to comment on this?

**Comment by rgommers** [comment]
Searching for ``ggvsd3`` got me this Julia PR as the first hit: https://github.com/JuliaLang/julia/pull/14444. It does:

    if LAPACK.VERSION[] < v"3.6.0"
       U, V, Q, a, b, k, l, R = LAPACK.ggsvd!('U', 'V', 'Q', A, B)
    else
        U, V, Q, a, b, k, l, R = LAPACK.ggsvd3!('U', 'V', 'Q', A, B)
    end

I don't see so quickly how to make this approach work reliably across all supported LAPACKs though.

**Comment by sethtroisi** [comment]
I believe the work done for 3.5 was finished in https://github.com/scipy/scipy/pull/5576 and #10881 has been come the larger issue for discussing Support for LAPACK.

This hasn't seen an updates in 3 years so I'm closing; If I'm wrong it can be reopened and I'll hide this with an edit :)

**Comment by ilayn** [comment]
This issue gets updates almost every 4 years :) We need to keep this open because when we bump the version there are many details to consider hence it's a good reminder.

**Comment by punyidea** [comment]
I'd like to ask if there has been any thought put into implementing a wrapper for *ggsvd3 in the next version of scipy, also see issue #743. Some Google searches have led me to this section of the issue page. 
Unfortunately I'm not a contributor, just a student looking for away to implement the Generalized SVD. Please forgive any impropriety in my request, and feel free to move this comment where appropriate. Thank you and I appreciate your work on this vital bit of scientific computing infrastructure.

**Comment by mdhaber** [comment]
We had a project going in which we planned to wrap `ggsvd3` (and `gesvx`), but it was introduced in LAPACK 3.6.0, and SciPy still supports older LAPACK versions. @insertinterestingnamehere I don't remember - what would need to happen if we wanted to change the minimum supported version?

**Comment by zerothi** [comment]
I think a workaround could be compiler flags for allowing custom installations of scipy with selected routines in later versions of lapack.

That would not destroy backwards compatibility and still allow users to use the more complete LAPACK set.

**Comment by ilayn** [comment]
The situation is not that dire anymore and we can consider moving to 3.6.0+. Since we dropped support for Python 3.5 (around 2015) and back we can similarly drop things belong to that time window and back. Seems like we are through and through with the 3.6.0 bottleneck in almost all distros except CentOS 7 and OpenSUSE which I know nothing about  https://pkgs.org/download/liblapack.so.3

**Comment by ilayn** [comment]
Hi everyone, almost perfectly 1 year later, I would like to propose upgrading to 3.7.1 since we only have two conflicting platforms namely, CentOS 7 (which will have EOL in 2024) and OpenSUSE Leap (which will have EOL this year). It seems to me that we have given sufficient slack and in the mean time, the version 3.7.1 is defined by Ubuntu 18.04 LTS. Most of the major distros are already in 3.9 and 3.10s. Nice to see things are getting bumped up.

Hence we can start rolling this if anyone doesn't have any objection.

**Comment by rgommers** [comment]
Agreed. MKL is also fine; MKL 2020 was updated to LAPACK 3.8.0 already. We're also not dropping CentOS 7, just the default LAPACK shipped with it doesn't work anymore then - but one should build against OpenBLAS (or MKL) anyway. @ilayn can you send an email to the mailing list saying we plan to update to LAPACK 3.7.1? Just to make sure we don't miss anything important.

**Comment by ilayn** [comment]
Done.

**Comment by h-vetinari** [comment]
> MKL 2020 was updated to LAPACK 3.8.0 already.

MKL already supports 3.9.0 for a while already as well, specifically since MKL 2020.0.4, cf. https://github.com/conda-forge/intel_repack-feedstock/issues/6

**Comment by h-vetinari** [comment]
@ilayn 
Given the merge of https://github.com/scipy/scipy/pull/15884, I presume this issue can be closed?

**Comment by ilayn** [comment]
Yes gladly
