### ISSUE TITLE
Wrong image scaling in scipy/misc/pilutil.py with misc.imsave?

### ISSUE THREAD

**Issue by moritzschaefer** [scipy/scipy#5305]
I just wanted to check how images with color values out of range are scaled and don't get the logic(function bytescale):
By default low=0 and high=256
    if cmin is None:
        cmin = data.min() # darkest pixel
    if cmax is None:
        cmax = data.max()

```
cscale = cmax - cmin
if cscale < 0:
    raise ValueError("`cmax` should be larger than `cmin`.")
elif cscale == 0:
    cscale = 1

scale = float(high - low) / cscale
bytedata = (data * 1.0 - cmin) * scale + 0.4999 # Important line
bytedata[bytedata > high] = high
bytedata[bytedata < 0] = 0
return cast[uint8](bytedata) + cast[uint8](low)
```

What happens here, is that the darkest pixel in the image will become the new black. For example, if the darkest pixel has value 10, the image is subtracted by 10 without any reason. 
At the same time the maximum value will be 255 as scale is computed. 
I see that, there are different modes to decide wether to scale like this or in another way in toimage but for example misc.imsave is using the default mode which is doing this kind of scaling and as such saving images in a non-normal way.

So in my opinion either the default-behaviour of bytescale/toimage should be modified or toimage should provide a parameter so misc.imsave could change the way how the image is scaled. 
Any comment is appreciated

**Comment by WarrenWeckesser** [comment]
I suppose there are many cases where the current behavior of `imsave` is reasonable, but I also agree that it should be possible to override this scaling.   Suggestions for a revised (but backwards-compatible) `imsave` API are welcome.

**Comment by WarrenWeckesser** [comment]
P.S. I recently put some code on github for saving an array (or a sequence of arrays) to a PNG file: https://github.com/WarrenWeckesser/pngw
The current version of `pngw.write_png` doesn't scale the input data (but when a bit depth less than 8 is requested, the high bits of the input data are simply ignored).

**Comment by moritzschaefer** [comment]
I'm working on something

**Comment by larslovlie** [comment]
I have to say.... thank you to everyone who made Scipy, but for the author of scipy.misc.imsave: What the hell? No one, no one should write a function which silently changes ("dynamically rescales") the data which the user passes to the function for it to simply write it to disk. imsave should _save_ the data to disk, and that's it. Don't change my data without telling me, and for God's sake at least document this "feature" somewhere. This cost me a couple of months of head scratching to figure out why my neural network model was completely off, and it was simply because scipy.misc.imsave does not do what the job description says. Just save the f***ing image and don't mess with my data.

**Comment by larslovlie** [comment]
For the record: I've switched to scikit-image (skimage.io.imsave) which does not molest my image data and just does exactly what the function name implies. Nothing more, nothing less.
