### ISSUE TITLE
griddata and LinearNDInterpolator - why rescale is not default option?

### ISSUE THREAD

**Issue by denfromufa** [scipy/scipy#5378]
#precisionmatters: today I found very long-standing bug in my filtering of some data using griddata, where values differ by few orders of magnitude. The resulting values from filtering lost precision very badly, even at double-precision floating. Rescaling resolved the problems! So the question is why rescale is not default option in scipy.interpolate? Should I be aware of any known side-effects?

**Comment by rgommers** [comment]
I wouldn't expect losing precision "badly" for "a few order of magnitude" difference, but that's all relative to ones expectations.

Why is it not default? Two reasons I can think of straight away:
- It isn't needed for many common use cases and takes computation time.
- ``rescale`` was introduced in a later release than ``griddata`` itself, so it couldn't have been made the default because of backwards compat.

**Comment by denfromufa** [comment]
related issue:

https://github.com/scipy/scipy/issues/2975
