### ISSUE TITLE
misc.imread incorrectly handles 3 channels for some PNG images.  

### ISSUE THREAD

**Issue by tzutalin** [scipy/scipy#5448]
Hi,
  I found an issue on my environment. Ubuntu14.04, Python2.7.8, scipy==0.13.3
 I try to load a RGB image using misc.imread, but shape is wrong. 

The snippet of my code:
      im = misc.imread('sneak.png')
      print im.shape

The shape is (400, 600) instead of (400, 600,3)

You can download the image by the link:
https://copy.com/2FrdUaMLUl6iNe4d

Does someone know the root cause?

Regards & Thanks.

**Comment by pv** [comment]
It's not RGB image, but has indexed palette. Perhaps imread should coerce these to RGB itself.
Imread is basically just `from PIL import Image; return numpy.asarray(Image.open(filename))`.

**Comment by tzutalin** [comment]
@pv. Thank you a lot.

**Comment by WarrenWeckesser** [comment]
> Perhaps imread should coerce these to RGB itself.

I agree.  In fact, I'd call it a bug that it doesn't, so I'm reopening this.

**Comment by tzutalin** [comment]
From your experiences, is there a good way to convert indexed image to RGB images using PIL? Or a better workaround?

**Comment by WarrenWeckesser** [comment]
It might be as simple as putting something like

    if im.mode == 'P':
        im = im.convert('RGB')

in the function `fromimage` in `scipy/misc/pilutil.py`.

**Comment by tzutalin** [comment]
Hi @WarrenWeckesser, 
  Very appreciate.

For misc.imread function, should we submit a pull request using the bellow solution?

im = Image.open(imagefile)
if im.mode == 'P':
       im = im.convert('RGB')
im = np.asarray(im)

**Comment by WarrenWeckesser** [comment]
@tzutalin I'll create a pull request.  It turns out it is not quite that simple.  If the image has an alpha channel, the correct conversion is `im = im.convert('RGBA')`.

While experimenting with this, I discovered that a couple existing unit tests are not correct.  In `scipy/scipy/misc/tests/data`, we have the files `icon_mono.png` and `icon_mono_flat.png`.  These files are actually indexed PNG files, and `icon_mono.png` has an alpha channel, so the shapes returned by `imread` should be (48, 48, 4) and (48, 48, 3), respectively.

**Comment by WarrenWeckesser** [comment]
Pull request: https://github.com/scipy/scipy/pull/5505

**Comment by WarrenWeckesser** [comment]
Pull request: https://github.com/scipy/scipy/pull/5505
