### ISSUE TITLE
ENH: linalg.solve: support broadcasting

### ISSUE THREAD

**Issue by KeithWM** [scipy/scipy#5451]
New to this, so please excuse me if I do something wrong.

It would be nice if scipy.linalg.solve accepted N>2 dimensional arrays in the same way as numpy.linalg.solve does. http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html

**Comment by yash14123** [comment]
I would like to take this up.

**Comment by KeithWM** [comment]
Great! Do you need any more information from me?

**Comment by rahilhastu** [comment]
what scipy.linalg.solve takes is a Square matrix and it can be of any dimension (N>2 is also acceptable) and it has the same functionality as numpy.linalg.solve.  
the equation a x = b is the one in picture ,
where 'a' is always supposed to be a square matrix irrespective of its dimensions and matrix 'b' .
if anything else is to be done please elaborate, it will be kind of you. :)

**Comment by mdhaber** [comment]
@ev-br @ilayn users have asked for ND stacks of covariance matrices in `scipy.stats`. I wrote a wrapper to loop over over the matrices in Python, but it would be better to do this the "right" way - whatever that is. Would you be able to help me implement this for `solve_triangular`? That would make it easier for someone to follow the pattern for the other `linalg` functions.

**Comment by ev-br** [comment]
Not sure what the right way is, can probably move the loop to cython + call a relevant lapack function via cython_lapack. If that's what you're after, is easiest to do from a python prototype.

**Comment by ilayn** [comment]
> Would you be able to help me implement this for solve_triangular?

The idea was to finish the cursed #12824 and add nD support to all linalg, but, for some reason I don't remember I started from `expm` (merged) then moved to `sqrtm` (still local) and then I got hit by a perfect line-up of bugs and compilation issues for about 5 months spanning Cython, pythran, Python, mingw and the meson stuff. Then I got exhausted and stopped all activity (my new job didn't help either).

I think I am close to be able to rebuild SciPy again and `sqrtm` is practically finished waiting for the tests. It has nD support and also has a few x speed ups. After that, I had `eig` and `svd` family lined up in my todo list and then `solve` family. 

If we actually do `solve` properly, then you won't be needing `solve_triangular` since you can choose `assume_a=tri` and be done with it.

**Comment by mdhaber** [comment]
Thanks @ev-br @ilayn.
Ugh build issues, especially, are so frustrating. I've been very fortunate that your Windows build instructions have continued to work for me @ilayn - and fingers crossed they continue until Meson supports in-place builds. Thanks again for your updates to those.
If you were to move the `solve` family` up on the list, the new functionality would certainly be used! Good luck getting the build working again.

**Comment by mdhaber** [comment]
I took a look at how `expm` was done, and it looks like it's doing the looping in Python, so there's not too much performance improvement vs a decorator approach (which also "vectorizes" the function, but does so from the outside).

```python3
import numpy as np
from scipy import linalg

@_apply_over_matrices
def my_expm(A):
    assert A.ndim == 2
    return linalg.expm(A)

res = my_expm(A)
ref = linalg.expm(A)
np.testing.assert_allclose(res, ref)

# %timeit my_expm(A) - 954 ms ± 2.85 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
# %timeit linalg.expm(A) - 809 ms ± 13.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

When there are fewer, larger matrices, the difference between the two approaches is smaller.

Would you be interested in reviewing a PR that uses this approach? It can always be improved in the future, but it would be useful as an easy way to get the feature in.

<details>
Here is a draft of such a wrapper. It needs to be tweaked for functions like `solve`, which needs to consider `A` and `b`, but this shows the idea.

```python3
def _apply_over_matrices(f):
    def _f_wrapper(x, *args, **kwargs):
        x = np.asarray(x)
        if x.ndim <= 2:
            return f(x, *args, **kwargs)

        # The strategy is to ravel the last two dimensions so we can
        # use `np.apply_along_axis` to call the function on each slice. 
        # We need to remember the original shape so that we can "unravel"
        # the last two dimensions before calling `f`.
        old_shape = list(x.shape)
        m, n = old_shape[-2:]
        new_shape = old_shape[:-2] + [m*n]

        def _f_on_raveled(x):
            return f(x.reshape((m, n)), *args, **kwargs)

        return np.apply_along_axis(_f_on_raveled, axis=-1,
                                   arr=x.reshape(new_shape))
    return _f_wrapper
```

Note that bigger gains are possible if we loop in compiled code.
```
@_apply_over_matrices
def my_inv(A):
    # assert A.ndim == 2
    return np.linalg.inv(A)

res = my_inv(A)
ref = np.linalg.inv(A)
np.testing.assert_allclose(res, ref)

# %timeit np.linalg.inv(A) - 20.4 ms ± 28.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
# %timeit my_inv(A) - 115 ms ± 1.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
</details>

**Comment by mdhaber** [comment]
Oops, I didn't show the array size before... that's sort of important : ) Added it.

**Comment by ilayn** [comment]
The point of expm overhaul was to gain speed from the internal algorithm and nD array capability was a bonus. The main issue with low-level looping is the C-contigousness that kills all performance if we need to do a copy in case some weird format or non-contiguous input comes. Other than that, as you see, there is not much done in terms of loops. And in fact you can't do much anyways since it is not IO bounded but CPU bounded. Anything that I am hoping in the short term is Cython 3 comes out officially. Otherwise we will be doing dirty loops to play nice with Cython since memoryiews are really not that smart. Or we go all the way down to C level that goes beyond my skills and to be honest, I am not willing to touch C or Fortran anymore under any circumstances.

**Comment by ilayn** [comment]
This is now resolved.

**Comment by mdhaber** [comment]
@ilayn is it? This is about batch matrix input to `linalg.solve`. it's tracked in general in gh-21466 (so we don't really need this issue anymore), but it doesn't look like `solve` accepts N-D arrays yet, right?

**Comment by ilayn** [comment]
Didn't we handle nd arrays in that issue? Maybe I misremember it but otherwise i can handle it in a bit?

**Comment by mdhaber** [comment]
In the ones that added backslash-like behavior? No - maybe your original PR did, but we removed that when we went pure-Python.

**Comment by ilayn** [comment]
Ah OK my bad then let me open this one again and handle it
