### ISSUE TITLE
Make convergence acceleration optional in scipy.optimize.fixed_point

### ISSUE THREAD

**Issue by rtrwalker** [scipy/scipy#5460]
For fixed point iteration using scipy.optimize.fixed_point the "Del^2" convergence acceleration is hardcoded. Sometimes iteration without acceleration should converge but fails if the "Del^2" method is used.  

The following code produces the following plot and then the error message when fixed_point is used I think the user should be able to turn off convergence acceleration.  At the moment the user has no way of checking if the function is poorly behaved or if acceleration is the problem.  Maybe an optional argument accell="Del^2" or accel=True could be added.

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fixed_point

def fn(n, kl, ks, i0):
    return np.log(kl/ks/n) / np.log((i0 *n/(n - 1))) + 1


ks_=2
kl_=6
i0_ = 3.7477525683

x0 = 1.001
imax = 5

xx = np.linspace(x0, 2.5, 100) 
yy = fn(xx, kl_, ks_, i0_)
plt.plot(xx, yy, label="y=fn(x)")
plt.plot([1, xx[-1]], [1, xx[-1]], label="y=x") # line of x=y
plt.grid()
plt.gca().set_title("Example of where optimize.fixed_point should \nwork but fails if Del^2 convergence acceleration is used.")

xxx=[x0] #graphical iteration process xvals    
yyy=[xxx[-1]]
for i in range(imax):
    xxx.append(xxx[-1])
    yyy.append(fn(xxx[-1],kl_, ks_, i0_))
    xxx.append(yyy[-1])
    yyy.append(yyy[-1])    

plt.plot(xxx, yyy, label="solving x=f(x)", marker="o", ms=3)
plt.plot([xxx[0],xxx[2]*2],[yyy[1],yyy[3]*2], label="Del^2 acceleration \nline doesn't meet y=x line, \nso can't get next x value for iteration")

plt.legend(loc='upper left')
plt.show()    

n = fixed_point(fn, 1.001, args=[kl_, ks_, i0_])
```
![optimize fixed_point_bug](https://cloud.githubusercontent.com/assets/4219951/10987273/f6daa15a-8485-11e5-96cd-b3ff6d03b9ce.png)

Error produced after closing the plot:

```python
Traceback (most recent call last):
  File "[path_deleted]\bug.py", line 37, in <module>
    n = fixed_point(fn, 1.001, args=[kl_, ks_, i0_])
  File "C:\Anaconda3\envs\py34\lib\site-packages\scipy\optimize\minpack.py", line 676, in fixed_point
    raise RuntimeError(msg)
RuntimeError: Failed to converge after 500 iterations, value is nan

```

Oh and please don't suggest that I just make a better initial guess. This function describes a physical process and for physically meaningful inputs it should always converge provided the initial guess is marginally greater than 1. (i.e. n is always greater than 1).

**Comment by argriffing** [comment]
This suggestion sounds reasonable to me.

**Comment by pv** [comment]
iirc, the method in `fixed_point` is rather naive, so +1 if you can improve it.
Would be nicer to have better methods (gh-4460 is related, but I haven't got around to finishing it...)

**Comment by argriffing** [comment]
In my opinion it would also help to define a more sophisticated fixed-point acceleration interface using clearly defined jargon. Some acceleration methods require or can use extra functions that are related in certain ways to the fixed-point function, and part of my confusion about https://github.com/scipy/scipy/pull/4460 is what exactly is meant by 'merit function'.

Here's a joke fixed-point of the original problem:
```python
>>> fn(np.nan, kl_, ks_, i0_)
nan
```

**Comment by kyleabeauchamp** [comment]
+1, I have encountered situations where I ended up writing my own fixed point solver due to numerical instability in the acceleration.

**Comment by m-oliver** [comment]
+1. An immediate step could be to change the documentation saying that the method can be numerically unstable and recommend using an equivalent formulation based on optimize.root.

I came across this problem when I asked students in a homework assignment to implement and test the implicit Euler method for ODEs.  One student found optimize.fixed_point and used it for this purpose.  The resulting code proved to be unstable under the refinement of the time step.  I did not investigate the convergence acceleration in depth, but to me it looks like that the control of numerical accuracy is missing or insufficient so that there is instability from small differences in denominators - the method falls down flat in the good cases when the initial guess is very close and the speed of convergence of non-accelerated convergence is already high.

Right now, this function is luring casual or inexperienced users although it is probably one of the least robust routines in scipy.optimize.
