### ISSUE TITLE
Kendall tau implementation uses Python mergesort

### ISSUE THREAD

**Issue by iskandr** [scipy/scipy#5533]
I just noticed that the implementation of [scipy.stats.kendalltau](https://github.com/scipy/scipy/blob/v0.16.1/scipy/stats/stats.py#L2910) implements its own mergesort. I suspect that any sorting algorithm, especially one that performs recursive function calls, would be orders of magnitude faster using a C implementation.

**Comment by rgommers** [comment]
Is this a bottleneck for you? If so, shouldn't be hard to move ``mergesort`` to Cython (that's preferred over C here).

**Comment by argriffing** [comment]
numpy has a few sorts including mergesort I think, but notice that the kendalltau mergesort is instrumented to track the number of exchanges. This exchange count is an ingredient in the tau calculation. Although it wouldn't make sense to switch to an existing non-exchange-counting mergesort implementation, the instrumented mergesort could indeed be implemented in Cython for more speed.

**Comment by josef-pkt** [comment]
@argriffing   Yes, I remember the algorithm was quite tricky. I wouldn't change anything except literal translation into cython.

**Comment by iskandr** [comment]
It's not a serious bottleneck, the statistic took long enough that I
noticed the delay but it's happening at the end of a much larger
computational pipeline. If the sorting logic is nontrivial then please
leave it as is!

**Comment by rgommers** [comment]
If you noticed it was slow, then it can be sped up. Let's leave this issue open and see if someone feels like moving the thing to Cython without changing the algorithm. Should be a lot faster then.

**Comment by behzadnouri** [comment]
I opened a pull-request which removes the exchange counting mergesort entirely: https://github.com/scipy/scipy/pull/5548

**Comment by sturlamolden** [comment]
When ```kendalltau``` was written we actually experimented with different implementation (three, IIRC). One of them was in Cython (which I wrote). I don't recall exactly the reason, but @josef-pkt decided to go with the current. So just a friendly warning, Cython has been tried, but it was not any better when we did.

**Comment by josef-pkt** [comment]
@sturlamolden  One of the reasons not to go with the cython version was that I was the only stats maintainer, and without any experience with cython I didn't want to get the extra maintenance work. Plus, this was supposed to be a computationally efficient implementation.
Otherwise, I don't remember much of the details. IIRC, there should still be somewhere your cython version for the contingency tables version, or Kendall's D, or something like that.

Now, there several maintainers and they have enough experience with cython to implement or maintain whatever works best. 

(Aside, I'm currently in a corner with power and sample size calculations where I just want to get the things to work, without expanding any effort on high performance in large samples. But in that case, we can at least resort to fast asymptotic results for large sample data.)

**Comment by josef-pkt** [comment]
(Another aside: 
I have currently no intuition for high speed. I partially following the Julia user mailing list, and they are very strongly into using loops with JIT speedup to avoid temporaries and memory allocation. Some examples here seem to indicate that keeping things in numpy with smarter algorithms can still improve performance quite a bit.)

**Comment by sturlamolden** [comment]
I suggested some improvements for #5548

**Comment by sturlamolden** [comment]
For the record, here are the Cython versions I wrote in 2009. They cannot be used as they stand (e.g. using C int instead of intp_t), but we can look at them for comparison with the current implementations:  
http://projects.scipy.org/scipy/attachment/ticket/893/tau.pyx
