### ISSUE TITLE
Wishart degrees of freedom should be $v > p-1$ instead of $v > p$

### ISSUE THREAD

**Issue by alumbreras** [scipy/scipy#5562]
The degrees of freedom $v$ of a Wishart distribution are currently limited to be equal or greater than the dimensions $p$ of the scale matrix.

However, degrees of freedom do not have to be integers. In case of a float, they should be  $v > p-1$.

See, for instance:
-   Bishop, "Pattern Recognition and Machine Learning" (p. 693) 
-   Wikipedia https://en.wikipedia.org/wiki/Wishart_distribution
-   Matlab implementation: http://fr.mathworks.com/help/stats/wishart-distribution.html

The same issue has been discussed in other communities:
-  Anglican. "Wishart sampling performance; non-integer degrees of freedom": https://bitbucket.org/probprog/anglican/issues/32/wishart-sampling-performance-non-integer

**Comment by rgommers** [comment]
@ChadFulton as the author of ``wishart``, what do you think about this suggestion?

**Comment by ChadFulton** [comment]
The primary issue at the time was that if we remove the bound then it is possible to generate singular matrices (or non-positive-definite matrices, but this is probably just floating point error of the singular case, see below) via the `rvs` command. For example, if I remove the bound and use the following code:

```python
np.random.seed(12345)
x = wishart(1.1, np.eye(2))
for i in range(100):
    seed = np.random.randint(1000000)
    np.random.seed(seed)
    rvs = x.rvs()
    det = np.linalg.det(rvs)
    if det < 0:
        print 'NPD: ', seed, det
    elif det == 0:
        print 'Singular: ', seed, np.linalg.det(rvs)
```

Then I get:

```
Singular:  27040 0.0
Singular:  160545 0.0
Singular:  738268 0.0
Singular:  288503 0.0
NPD:  930711 -1.30999161573e-18
NPD:  890047 -1.84827911505e-18
Singular:  899221 0.0
Singular:  974496 0.0
Singular:  893034 0.0
Singular:  344046 0.0
Singular:  571303 0.0
Singular:  27632 0.0
Singular:  505054 0.0
NPD:  572913 -1.01604165346e-15
Singular:  5588 0.0
Singular:  761159 0.0
```

Previously I had thought that MATLAB had a better algorithm for generating the matrices to avoid this problem and I didn't look into it further. However, it turns out that their implementation suffers from the same problem:

```MATLAB
rng(12345)
for i = 1:100;
    seed = randi(1000000,1);
    rng(seed);
    rvs = wishrnd(eye(2), 1.1);
    d = det(rvs);
    if d < 0;
        disp({'NPD: ', seed, d});
    elseif d == 0;
        disp({'Singular: ', seed, d});
    end;
end;
```

```
'NPD: '    [782740]    [-4.9894e-17]
'NPD: '    [909244]    [-4.8972e-18]
'NPD: '    [654661]    [-4.4570e-19]
'NPD: '    [628160]    [-1.8254e-16]
'NPD: '    [757497]    [-5.6875e-18]
'Singular: '    [782222]    [0]
'Singular: '    [737806]    [0]
'Singular: '    [142736]    [0]
'Singular: '    [692091]    [0]
'NPD: '    [688478]    [-6.4883e-17]
'Singular: '    [299711]    [0]
'NPD: '    [882371]    [-9.2312e-16]
'Singular: '    [207943]    [0]
'Singular: '    [189991]    [0]
'Singular: '    [800678]    [0]
'Singular: '    [44118]    [0]
'Singular: '    [183463]    [0]
```

So I have no objection to decreasing the bound; a citation for the lower bound in the real-number case is "Aspects of Multivariate Statistical Theory" (Muirhead, 2005).

Practically speaking, should the code allow drawing a singular matrix and make the user deal with it? or issue a warning? or re-draw until non-singular? or throw an exception?

**Comment by ChadFulton** [comment]
Of course by "remove the bound" I actually mean decrease the bound from v >= p to v > p-1.
