### ISSUE TITLE
Add the Type XII Burr distribution to stats.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#5589]
This enhancement request is motivated by https://github.com/scipy/scipy/issues/5560.

Apparently the Type XII Burr distribution is often called *the* Burr distribution.  This can cause confusion for users of `stats.burr`, because it implements the Type III Burr distribution.  If the Type XII distribution is more commonly used, we should add it to `stats`.

We could call it `burr12`, and for consistency, provide the alias `burr3` for the current `burr` distribution.

**Comment by WarrenWeckesser** [comment]
For reference: the Burr distribution on wikipedia is the Type XII distribution: https://en.wikipedia.org/wiki/Burr_distribution

**Comment by maniteja123** [comment]
I was looking up to this distribution.

The present implementation of ``fisk`` says that it is special case of existing i.e ``Burr III`` distribution.

    The probability density function for `fisk` is::
        fisk.pdf(x, c) = c * x**(-c-1) * (1 + x**(-c))**(-2)
    for x > 0

while the wikipedia article and [this](http://www.causascientia.org/math_stat/Dists/Compendium.pdf)
mention that ``Fisk`` distribution is special case of ``Burr XII`` distribution when ``d=1``. So, its pdf should be 

     fisk.pdf(x, c) = c * x**(c-1) * (1 + x**(c))**(-2)

With respect to cdf, either of the burr distributions would suffice since they give the same formula for ``d=1``.

Could someone experienced look into this issue ?

**Comment by maniteja123** [comment]
Also, the definition of Type III distribution in [this](http://onlinelibrary.wiley.com/doi/10.1002/0471667196.ess0189.pub2/abstract) says that 

    F(x) = (1 + x**(-c))**(-k)

while the original paper [here](https://projecteuclid.org/download/pdf_1/euclid.aoms/1177731607) has  the definition as 

   F(x) = (1 + x**(-k))**(-r)

Is there any particular difference in the meaning of these definitions other than the change of representation of parameters ?
