### ISSUE TITLE
signal.resample could be twice as fast using rfft

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#5592]
[`signal.resample`](https://github.com/scipy/scipy/blob/master/scipy/signal/signaltools.py#L1722) could be twice as fast for real input by using `rfft`/`irfft`, same as `fftconvolve`

**Comment by dnlbunting** [comment]
I've made a pull request (#5610) that implements this

**Comment by Eric89GXL** [comment]
Ouch, does that mean that `fftpack.fft` uses complex DFT even if the input is real? I assumed it triaged based on type!

**Comment by dnlbunting** [comment]
Huh interesting, the docstring for fft suggests that it should automatically use a real FFT which halves computation time and directly calling rfft can speed things up a 'little' .

But in my PR using rfft definitely gives a big speed up e.g. 

%time resample(y, 1e8)
CPU times: user 4.99 s, sys: 1.74 s, total: 6.74 s
Wall time: 8.68 s

vs  

%time resample(y+complex(0,0), 1e8)
CPU times: user 12.5 s, sys: 10.6 s, total: 23 s
Wall time: 30 s

**Comment by Eric89GXL** [comment]
What is the behavior on current `master`? Both are the same?

**Comment by dnlbunting** [comment]
Yes, they're approximately the same

**Comment by Eric89GXL** [comment]
That makes me think there's a bug with `fftpack`, since their docs make it sound like they shouldn't be. I don't think there's a problem with being explicit (and faster for "bad" versions of `fftpack`), but this sounds like the sort of issue that should be raised with the maintainers of `fftpack`. It seems like they either have a bug, `scipy` has a bug with how `fftpack` is invoked, or we are misreading the docstrings. @rgommers any idea who we should bother about `fftpack` in scipy?

**Comment by sturlamolden** [comment]
```fftpack.fft``` should always invoke a complex FFT because sometimes we actually want the complex FFT of a real signal. (One example is when we want to compute the Hilbert transform.)

**Comment by Eric89GXL** [comment]
It looks like the output of `rfft` is actually of a different form than that of `fft`, too. So I guess the docstrings just need to be updated about which algorithm is used? Although I'm not sure why, if the signal is real, you wouldn't use the more efficient `rfft` and then populate the negative frequency coefficients with the conjugates under the hood. This is even true for the `Hilbert` case -- IIUC the negative frequencies are taken as zero so you wouldn't even need to copy them over, so it should be 2x as fast there, too, I think.

**Comment by endolith** [comment]
> Ouch, does that mean that fftpack.fft uses complex DFT even if the input is real? I assumed it triaged based on type!

It should: 

https://github.com/scipy/scipy/blob/master/scipy/fftpack/basic.py#L252
https://github.com/scipy/scipy/blob/master/scipy/fftpack/basic.py#L98

it only cares about type, though, not value.  So 4+0j is not considered real.

> It looks like the output of rfft is actually of a different form than that of fft, too.

https://github.com/scipy/scipy/issues/2487

**Comment by sturlamolden** [comment]
I think it should be up to ```signal.resample``` to call ```rfft``` when desired.

**Comment by endolith** [comment]
also I haven't looked, but it might need numpy.rfftn instead of scipy's rfft, which can't be N-dimensional?

**Comment by sturlamolden** [comment]
IIRC NumPy's fftpack_lite only uses double precision. Also it does not plug-in with PyFFTW as SciPy does now (or will do soon).

**Comment by Eric89GXL** [comment]
> I think it should be up to signal.resample to call rfft when desired.

Yeah I'm fine with that for now. I'm really curious why the signal being real dtype wouldn't cause `fftpack` to only compute positive frequencies (and set the negative to conjugates) instead of computing all coefficients, though. A real input implies conjugate symmetric transform, and vice-versa. Or if it's already doing that, how `rfft` is actually twice as fast -- seems like it can't come from the extra (actually unnecessary) memory allocation and copying.

**Comment by dnlbunting** [comment]
@endolith it should be fine using scipy rfft since it's only resampling along one axis at a time.

**Comment by endolith** [comment]
I believe this is how the automatic rfft in fftpack.fft works:

```
allclose(scipy.fftpack.fft(a), scipy.fftpack.fft(a+0j))
Out[18]: True

timeit scipy.fftpack.fft(a)
100 loops, best of 3: 3.13 ms per loop

timeit scipy.fftpack.fft(a+0j)
100 loops, best of 3: 5.78 ms per loop
```

**Comment by rgommers** [comment]
> @rgommers any idea who we should bother about fftpack in scipy?

That's slightly problematic, there's no dedicated maintainer unfortunately. A number of people pitch in here and there.

**Comment by Eric89GXL** [comment]
> That's slightly problematic, there's no dedicated maintainer
unfortunately. A number of people pitch in here and there.

Thanks -- actually we don't need to anymore as it turns out its behavior is
as described (fft computation on real input uses conjugate symmetry for
speed already). The gains seen here come from a reduced number of
multiplies with the window function because rfft only returns positive
frequencies. The PR title should probably be updated to reflect that, as
right now people could reasonably assume rfft makes gains over fft for
incorrect reasons, as most (all?) of us initially did.

**Comment by dnlbunting** [comment]
I agree it's the smaller arrays rfft returns that gives the speed up, also irfft is significantly faster the ifft, the difference between rfft and fft is negligible.

I updated the PR title to reflect this, I think it's pretty much good to go now?

**Comment by Eric89GXL** [comment]
> also irfft is significantly faster the ifft

I guess it doesn't try to detect the conjugate symmetry under the hood or anything, which I suppose makes sense. That would lead to nice speedups. Nice to know!

**Comment by sturlamolden** [comment]
Since ifft cannot assume this symmetry, perhaps we should use rfft/irfft anyway?

**Comment by Eric89GXL** [comment]
@sturlamolden yeah I agree, and it looks like that's what @dnlbunting has done in #5610 to get speed gains. It also should have the nice practical advantage of not needing to do a `.real` at the end to deal with `ifft` numerical errors.

**Comment by endolith** [comment]
Also don't forget that rfft uses half as much memory
