### ISSUE TITLE
Overloaded ‘isnan(double&)’ is ambiguous when compiling with gcc 4.8.1 -std=c++11

### ISSUE THREAD

**Issue by tyhone** [scipy/scipy#5607]
This may be a numpy issue rather than a scipy issue, nevertheless, when installing scipy with the command "sudo -H pip install" I get the following compilation error:

In file included from scipy/special/Faddeeva.cc:122:0:
scipy/special/Faddeeva.cc: In function ‘std::complex Faddeeva::erf(std::complex, double)’:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_math.h:171:41: error: call of overloaded ‘isnan(double&)’ is ambiguous

System details:
Ubuntu 12.04.2 LTS 
gcc (Ubuntu 4.8.1-2ubuntu1~12.04) 4.8.1
numpy 1.10.1

It appears numpy is trying to use the math.h version of isnan. I suspect somewhere else in the build process cmath.h has also been included resulting in the ambiguity.

**Comment by rgommers** [comment]
Hmm, I'm not seeing this with gcc 4.8.4, numpy 1.10.2 or master, on Ubuntu 14.04.

**Comment by rgommers** [comment]
Do you still see it with ``pip install scipy --user``, i.e. without the ``sudo``? ``sudo`` can result in weird issues, and should always be avoided.

**Comment by sturlamolden** [comment]
We had a very build problem with ```cKDTree``` which was due to ```isinf``` being defined in C++11. It think there might be an upstream problem in NumPy that (sometimes? always?) shows up when using C++11 compilers. In ```cKDTree``` we worked around it by defining our own ```isinf``` function.

**Comment by rgommers** [comment]
@tyhone can you put your full build log in a gist and link to it? 

> I think what we are seeing here is the same type of name collision, except with isnan instead of isinf. They have in common that they are only present in math.h in C99 and C++11. 

Looks like it. http://stackoverflow.com/questions/19022561/porting-isnan-to-c11 seems to describe the problem. 

Maybe for @tyhone  ``CC`` was set to ``c++`` instead of ``gcc`` or something, to make this error show up?

**Comment by tyhone** [comment]
As per your suggestion, I've eliminated any sudo and/or pip issues by downloading the source directly and building with the direct 'setup.py build' command.  The output of the build process is contained in the following file:
[scipy.build.txt](https://github.com/scipy/scipy/files/74953/scipy.build.txt)

**Comment by rgommers** [comment]
Okay, I see the problem now. ``Faddeeva`` is C++ code, so that's fine. The issue occurs when you include ``std=c++11`` as a compile flag. Your build log contains:

    compiling C++ sources
    C compiler: g++ -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall
    -std=c++11 -L/usr/local/boost/lib -fPIC

While mine contains:

    compiling C++ sources
    C compiler: c++ -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC

The extra flags ``-std=c++11 -L/usr/local/boost/lib`` are either coming from Python ``distutils`` or you have ``CXXFLAGS`` or a similar envvar defined. 

``Faddeeva.cc`` does ``#define my_isnan npy_isnan`` and then only uses ``my_isnan``. However, above the define it has ``using namespace std``, which seems to be the problem.

**Comment by rgommers** [comment]
Found the very similar ``isinf`` issue: gh-5314

**Comment by rgommers** [comment]
OK found a fix: gh-5643. @tyhone can you please test that that works for you?

**Comment by tyhone** [comment]
@rgommers I applied the patch to scipy/special/Faddeeva.cc but I'm still seeing the isnan ambiguity error.  Build output attached:
[scipy.build.5643.txt](https://github.com/scipy/scipy/files/75023/scipy.build.5643.txt)

**Comment by rgommers** [comment]
Hmm, from your build output I can tell that the problem indeed isn't solved, because ``cmath`` is already included via ``Faddeeva.hh`` via ``complex``. Not sure why the fix in the PR is enough for me. 

If you move ``#include "Faddeeva.hh"`` from line 23 in ``Faddeeva.cc`` down to line 137 (below the isnan & co defines), does it work then?

**Comment by rgommers** [comment]
New try on gh-5643, removing ``using namespace std``. That does work with my test method.

**Comment by tyhone** [comment]
Applying the patch from gh-5643 works for me as well.  Scipy now builds and installs successfully.  Thanks @rgommers.
