### ISSUE TITLE
Scipy 0.16.1 insatalltion package for Python 3.5?

### ISSUE THREAD

**Issue by Abdullah2993** [scipy/scipy#5644]

**Comment by rgommers** [comment]
I assume you mean Windows wheels. Work is ongoing, but it depends on having a MinGW-w64 compiler chain ready to use. See https://github.com/numpy/numpy/issues/5479 and gh-2829.

Right now on Windows you're best off using something like Anaconda. Or if you need a wheel, use this third party one: https://anaconda.org/carlkl/scipy

Closing, because there are several other open issues related to this already.

**Comment by Abdullah2993** [comment]
I mean a super pack for Python 3.5

**Comment by rgommers** [comment]
That's never going to happen - the .exe superpacks are built with MinGW 3.4.5, which is a dormant project and cannot work with Visual Studio 2014 (which is used for Python 3.5). Superpacks are basically a dead end; in the future there'll only be Windows wheels via PyPi.
