### ISSUE TITLE
curve_fit(method!="lm") ignores initial guess

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#5719]
Briefly, the addition of `least_squares` functionality into `curve_fit` contains the following lines
```
    else: # if method != "lm"
        p0 = _initialize_feasible(lb, ub)
        res = least_squares(func, p0, args=args, bounds=bounds, method=method,
                            **kwargs)
```
i.e. `p0` is not used when determining the initial guess (also confirmed the behavior on actual tests).  I'd think you only want to call `_initialize_feasible` if `p0` is not passed, and raise a ValueError when a non-feasible initial guess is given.
@nmayorov @ev-br

**Comment by ev-br** [comment]
Good catch Antony! This is a release blocker.

**Comment by nmayorov** [comment]
It is a strange mistake indeed. 

I personally think that `curve_fit` is not very good function, because it hides important options and encourages usage of least-squares optimization without analytical Jacobian. Ceres authors also advise not to do this http://ceres-solver.org/faqs.html#modeling Because of that I did this integration at the last step and without much interest. 

Can you please send a fix for this? Would be great if you also cover #5068 (perhaps in a different PR). 
I'm sure it will be merged faster than your doc PR, where we stuck (temporarily) on this renaming issue.

**Comment by anntzer** [comment]
I'd think the patch comes down to
`if p0 is not None and not np.all((lb <= p0) & (p0 <= lb)): raise ValueError.`
(except that `p0` has already been given a default value at that point so you need to stash somewhere whether it has been defaulted or not yet).

Turns out I have a few other things on my plate now, so it's not even clear I'll have time for the doc PR :(

**Comment by ev-br** [comment]
fixed in gh-5722
