### ISSUE TITLE
Deprecate get_window

### ISSUE THREAD

**Issue by nils-werner** [scipy/scipy#5744]
To me the `get_window` function seems to have some conceptional problems:

In most cases it serves **no real purpose** besides reshuffling the function call: These two are equivalent, so why use `get_window` in the first place?

``` python
scipy.signal.windows.cosine(16)
scipy.signal.windows.get_window('cosine', 16)
```

And **obfuscates the window function API** with some weird tuple-syntax. The first one is readable with no scipy knowledge, the second one is weird:

``` python
scipy.signal.windows.kaiser(16, beta=1.0)
scipy.signal.windows.get_window(('kaiser', 1.0), 16)
```

I can see the reasoning that you may want to **parameterize the window function from outside** your code, but using `functools` you can achieve the same and result in a much more descriptive and transparent code:
- making it clear what is being used (`scipy.signal.windows.kaiser`)
- making it clear _what parameter being partialled out_
- can be mocked easily

``` python
winfunc = functools.partial(kaiser, beta=1.0)
# ...
winfunc(16)
```

`get_window` uses a very opaque API (a tuple with some special meaning) that needs people to
- Go dive deep in the code to find out where `winfunc` is later being used, discover it is a call to `get_window`
- Then read the `get_window` docs to understand what is going on
- needs monkeypatching of scipy to be mocked

``` python
winfunc = ('kaiser', 1.0)
# ...
get_window(winfunc, 16)
```

Another advantage I can see is that you can parameterize the **window function as a string**, if you really need to, however this can also be done using `getattr`, too.

``` python
getattr(scipy.signal.windows, 'boxcar')(16)
scipy.signal.windows.get_window('boxcar', 16)
```

Also, `get_window` is [quite closely coupled with each window's interface](https://github.com/scipy/scipy/blob/master/scipy/signal/windows.py#L1675), doing parameter resolution and checking that should be
- done by the window-function
- defined and documented by the window-function interface

`get_window` replaces that "nice Python function API" with a few lines of code that is superfluous, hard to understand and hard to test.

Hence I suggest deprecating `get_window` and ask people to use the window functions directly.

**Comment by endolith** [comment]
> The only advantage I can see is that you can parameterize the window function as a string

Isn't this the main purpose?  So you can do `firwin(100, 0.1, 'nuttall')` (handles fftbins=False for you) or `periodogram(x, fs, 'hamming')` (fftbins=True), and you don't need to change your imports each time you change the window function?

**Comment by nils-werner** [comment]
I would argue it is a bad practice, then.

```python
from scipy.signal import window

firwin(100, 0.1, 'nuttall')
periodogram(x, fs, ('kaiser', 0.1))
```

is more opaque and less testable than

```python
from scipy.signal import window
from functools import partial

firwin(100, 0.1, window.nuttall)
periodogram(x, fs, partial(window.kaiser, beta=0.1))
```

and would in some cases produce nicer error messages, too. Imagine

```python
from scipy.signal import window

firwin(100, 0.1, 'nonsense')
firwin(100, 0.1, window.nonsense)
```

the first line will show some obscure error in `scipy/signal/windows.py` whereas the second line will point to the mistake *in your script*.

**Comment by ewmoore** [comment]
If you want to deprecate `get_window` you need a plan for how to get there.  Get window is used a number of places in `signal`.  All of those uses (`firwin`, 'firwin2', 'resample', `periodogram`, `welch` + the rest of the spectral estimation functions) will need to have the string form deprecated as well.  The question is then, is that worth it? In addition to requiring that anyone else using it also change their code.

Perhaps a better approach would be to add to `get_window` so that passing a function or an array to it would also return reasonable results.  The spectral estimation functions already special case their handling of the `window` parameter to allow an array to be passed in as the window. This then allows the usage pattern you'd like to see supported and doesn't result in breaking code that has long worked. I'm a solid +1 for supporting the interface you'd like, but I don't think breaking existing code is worth it in this case since there is a path forward that doesn't require it.

**Comment by rgommers** [comment]
More discussion on this happened in gh-6895. About 6 people weighted in, all against removing ``get_window``. So closing this as wontfix. Thanks for the discussion everone.
