### ISSUE TITLE
Hypergeometric function hyp0f1 behaves incorrectly for complex arguments

### ISSUE THREAD

**Issue by dmitriyboyarchenko** [scipy/scipy#5764]
It appears that when the argument z to the function scipy.special.hyp0f1 is complex, the function simply replaces z with its absolute value before computing the answer.  Here is just one example, but I tested this pattern with several other randomly generated examples:

In [1]: import scipy

In [2]: scipy.__version__
Out[2]: '0.16.0'

In [3]: from scipy.special import hyp0f1

###### The next result is obviously incorrect
In [4]: hyp0f1(0.8, 0.5 + 0.5 * 1j) 
Out[4]: array([ 2.07280938])

###### We get the same answer if we replace the second argument with its absolute value
In [5]: hyp0f1(0.8, 0.5 ** 0.5)
Out[5]: array([ 2.07280938])

**Comment by person142** [comment]
The function is computed using a relationship to Bessel functions; see 

https://en.wikipedia.org/wiki/Generalized_hypergeometric_function#The_series_0F1

It does take the absolute value of all the arguments. Unfortunately the fix is not as simple as removing the absolute value because the relationship it uses isn't valid for the negative real axis due to a branch cut. (Though removing the absolute value might fix things away from the negative real axis.) Will investigate more...

Also, FWIW the tests for the function all pass because the only complex inputs have zero imaginary part.
