### ISSUE TITLE
scipy.io.wavefile.write ouputs incorrect error

### ISSUE THREAD

**Issue by bendichter** [scipy/scipy#5766]
scipy.io.wavefile.write takes data as a np.ndarray with size (n,). If you try to use an np.ndarray of size (1,n), it will give the following error:

```
error: ushort format requires 0 <= number <= (32767 * 2 + 1)
```
This leads the user to believe that there is a problem with the scale of the input, but in fact the problem is with the shape of the input. Using .ravel() on data resolves the issue.

**Comment by gfyoung** [comment]
Can you provide code that causes you to get that error?  I can't reproduce it on `master`, and secondly, this method <i>should</i> be able to handle such an array because the method, according to the <a href="https://github.com/scipy/scipy/blob/master/scipy/io/wavfile.py#L245">doc</a> should be able to handle such `data` with no problems.

Here is the code I ran:
~~~~{.Python}
>>> import scipy
>>> import numpy
>>> scipy.__version__
'0.18.0.dev0+331e2c6'
>>> numpy.__version__
'1.10.4'
>>> from scipy.io.wavfile import write
>>> filename = 'test.wav'
>>> data = np.array([[1, 2, 3, 4, 5]])
>>> data.shape
(1, 5)
>>> rate = 100
>>> write(filename, rate, data)
>>> # no exception thrown
~~~~

**Comment by bendichter** [comment]
Thanks for looking into this. Sorry, I can't reproduce the bug. Your code works for me. I'm not sure what the issue was.

**Comment by gfyoung** [comment]
:+1: - glad to have cleared up (at least partially) your issue
