### ISSUE TITLE
Strange behavior in scipy.interpolate.BarycentricInterpolator

### ISSUE THREAD

**Issue by LeiShi** [scipy/scipy#5866]
When I was testing scipy.interpolate.BarycentricInterpolator, I did the following

`import numpy as np`
`from scipy.interpolate import BarycentricInterpolator`
`x = np.linspace(-np.pi, np.pi, 100)`
`y = np.sin(x)`
`sin_interp = BarycentricInterpolator(x,y)`

Then, I tested it on some x mesh:

`xin = np.linspace(-np.pi, np.pi, 1000)`
`yin = sin_interp(xin)`

The result is very strange. The maximum value of  `yin` is `5237707.7316430295`. I am not sure what's going on, but this behavior seems like a bug.

**Comment by pv** [comment]
Polynomial interpolation based on linspace is unstable:
https://en.wikipedia.org/wiki/Runge's_phenomenon
See the comment in BarycentricInterpolator documentation.

`sin` is a lucky case as the Lebesgue constants of its derivatives are bounded, so that in the end only floating point rounding error limits how high orders you can go.
