### ISSUE TITLE
BUG: Python crash in scipy.io.loadmat on Anaconda/Windows/scipy-0.17.0

### ISSUE THREAD

**Issue by saulomeirelles** [scipy/scipy#5882]
Hi all,

I had some problems with scipy.io.loadmat on Windows platform as reported here:

https://github.com/wesleybowman/UTide/issues/30

Python stopped working when loading mat-files on Windows 7.

Extra tests showed that the problem occurs with Scipy versions > 0.16.0

The script can be accessed here:

https://gist.github.com/saulomeirelles/05f4c8f2cac7626175fd

All the other files used in the tests are in the following attachment:

[utide_test.zip](https://github.com/scipy/scipy/files/140338/utide_test.zip)

**Comment by pv** [comment]
And scipy installed from where -- conda?
There are almost no changes in the mat reader between 0.16.0 and 0.17.0, so a bug on our side seems unlikely.

**Comment by saulomeirelles** [comment]
Indeed, dear Pauli. It was installed via conda as: conda install scipy


On Mon, Feb 22, 2016 at 10:59 AM, Pauli Virtanen <notifications@github.com>
wrote:

> And scipy installed from where -- conda?
> There are almost no changes in the mat reader between 0.16.0 and 0.17.0,
> so a bug on our side seems unlikely.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy/scipy/issues/5882#issuecomment-187103754>.
>



-- 

Saulo Meirelles

**Comment by pv** [comment]
Anaconda issue: https://github.com/ContinuumIO/anaconda-issues/issues/650

**Comment by oxsem** [comment]
Hello,

I'm facing same issue when using SciPy 0.17.0 for reading .mat files with scipy.io.loadmat.
(Windows 7, 64-bit, Anaconda2, python 2.7)

Depending on IDE I have different errors. 
In Pycharm: "Process finished with exit code -1073741819 (0xC0000005)" or "Process finished with exit code 255"
In Spyder kernel simply stop working.

Earlier version of Scipy 0.16 worked just fine with scipy.io.loadmat.

I could have simply downgrade it, but the problem is that scipy.signal.coherence is available only in Scipy 0.17.

Oksana

**Comment by oxsem** [comment]
Hello,

some more details:
just checked that WinPython with SciPy 0.17 works just fine with scipy.io.loadmat.
Apparently issue has to do with Anaconda.

**Comment by pv** [comment]
Yes, further discussion please in the anaconda ticket: https://github.com/ContinuumIO/anaconda-issues/issues/650

**Comment by angelnaviavazquez** [comment]
I have experienced the same crash error when loading .mat, I had to downgrade scipy.

**Comment by cdboschen** [comment]
I had the same issue. (Windows 7, Anaconda, crash when trying to use scipy.io.loadmat), and struggled with this for a while. This is as far as I got in successfully processing .mat files I am getting from a colleague (given I have Octave, this is a workable solution for me, but would still be interested in completely resolving so that the Octave translator is not required):

I installed hdf5storage in Python from https://pypi.python.org/pypi/hdf5storage/0.1.1

However when I use it as directed to import the .mat file (which is a structure) I get the following error:

_IOError: Unable to open file (File signature not found)._

My workaround was to load the *.mat file in Octave, then resave it using the -hdf5 argument as in the following example: 

load filename.mat       #This loaded a structure with name M
save ('filename2.mat','M','-hdf5')

Then in Python:
import numpy as np
import hdf5storage
out=hdfstorage.loadmat('filename.mat')
