### ISSUE TITLE
minimize_scalar -- strange behaviour

### ISSUE THREAD

**Issue by seryrzu** [scipy/scipy#5899]
Define simple function
`
func_1 = (lambda x: -5 * x**5 + 4 * x**4 - 12 * x**3 + 11 * x**2 - 2 * x + 1)
`
Hovewer,
`
optimize.minimize_scalar(func_1, (-0.5, 0.5))
`
rases OverflowError: (34, 'Numerical result out of range').

Definitely, there is a minimum in (-0.5, 0.5): {0.897633, {x -> 0.10986}}, and it could easily be found with Golden ratio method (or Brent).
What am I doing wrong?

Wolfram Mathematica easily deals with it. R's function `optimize` uses Brent method and has no problem with that.

**Comment by ev-br** [comment]
Playing a bit with the `bracket` parameter you can easily find the solution. For instance, try `(-0.1, 0.5)` or a three-element bracket: 

```
In [60]: minimize_scalar(f, (-0.5, 0, 0.5))
-0.5
0
0.5
0
-0.190983
0.190983
0.109652269292
0.116266754714
0.109432982468
0.109862906032
0.109859850423
0.109859915545
0.10985991391
0.109859912274
Out[60]: 
     fun: 0.89763297189616675
    nfev: 11
     nit: 10
 success: True
       x: 0.10985991390956745
```

(here `f` is your function instrumented to print its argument on each call).

The bracketing algorithm can likely be made smarter. Other than that, I'd say it's not a bug.

**Comment by seryrzu** [comment]
Thank you for your quick response!

I see, what you mean.
Still I find it rather strange, that I need to supply 0.

Suppose, that I write this:
`
optimize.minimize_scalar(func_1, (-0.5, 0.5), method="Golden")
`
The function is infinitely smooth and doesn't have any sharp drops or anything, that could affect in (0.5, 0.5). It is unimodal. 
"Golden" should work easily and find local minima. It should not need any third point.
The third point, as far as I know, is only needed, when you try to be clever in Brent.

**Comment by ev-br** [comment]
I tried `minimize_scalar(f, (-0.5,  0.5), method='golden')` and it fails in exactly the same way, overflowing inside `bracket`.

As far as I can see, this can be interpreted as an enhancement request for improving the bracketing algorithm (likely, `optimize.bracket`). I suspect what's happening is that `-5 x**5` grows quite fast, so if you make too large of a step, the value of the function is large and negative, while `f(-0.5)` and `f(0.5)` are of the order one and positive. Then the bracketing search just wonders all the way to overflow. 

I *think* we could merge a pull request with an improvement, however it would then have to be made sure somehow that the change actually fixes more than it breaks for a range of functions.

**Comment by mdhaber** [comment]
Digging into this, it looks like there is a mismatch between the interpretation of a two-element `bracket` between `scipy.optimize.minimize_scalar` and `scipy.optimize.bracket`.

[`minimize_scalar`](https://scipy.github.io/devdocs/reference/generated/scipy.optimize.minimize_scalar.html) says:
![image](https://user-images.githubusercontent.com/6570539/210209445-2162c37f-06a1-4add-b93a-7e71ebbc5c4a.png)

[`scipy.optimize.bracket`](https://scipy.github.io/devdocs/reference/generated/scipy.optimize.bracket.html) says:
![image](https://user-images.githubusercontent.com/6570539/210214287-f87b47ef-a786-47ff-85ec-addc2d75c024.png)

`minimize_scalar` says that if two points are provided; these are `xa` and `xc`, whereas `bracket` accepts `xa` and `xb`. (_`brent`_ was fixed after this was reported in gh-5408, but `golden` is still wrong.)

The difference is important. Users of `minimize_scalar` would assume from the documentation that they should try to provide points on either side of the minimum, but in many cases, this could be exactly the wrong thing to do because `bracket` only looks for a third bracket point _outside_ the interval. In the example above, yes, it expands the interval according to golden ratio until overflow occurs.

<details>

```python3
import numpy as np
from scipy import optimize

xs = []
def f(x):
    xs.append(x)
    return -5 * x**5 + 4 * x**4 - 12 * x**3 + 11 * x**2 - 2 * x + 1

try:
    optimize.bracket(f, -0.5, 0.5)
except OverflowError:
    pass
d = np.diff(xs)
print(d[1:]/d[:-1])

# [1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034 1.618034
#  1.618034 1.618034 1.618034 1.618034 1.618034]
```

<details>

The documentation of `minimize_scalar` has been like this for a decade (and `golden` even longer), so I think we need to do two things:

- Look at at least one point _inside_ `bracket` when trying to complete the bracket, say `(xa + (xb - xa)/golden_ratio)`.
- Update the documentation of `bracket`/`brack` wherever it appears to summarize what `bracket` is going to do, and probably add a `.. :: warning` to bring this to the attention of users of `root_scalar`. It's pretty natural to assume that `bracket` should try to _bound_ the solution, especially since the next parameter is `bounds`.

**Comment by mdhaber** [comment]
@ev-br since you looked into this issue in the past, could you take a look at the latest findings and opine on what else should be added to gh-17705?

**Comment by mdhaber** [comment]
@ev-br Thought I'd ping again because this includes at least a documentation issue that we should fix before 1.11.0.

**Comment by ev-br** [comment]
A doc fix LGTM. There might be something to fix in the `bracket` itself, but it's best kept separate from a doc improvement.

On  a cursory look (all I can do ATM), a `while` loop without a cap on the number of iterations looks suspect. Not sure if it's related though.  https://github.com/scipy/scipy/blob/v1.10.1/scipy/optimize/_optimize.py#L2876

**Comment by j-bowhay** [comment]
@mdhaber did you want to leave to this open for further improvements to the bracketing algorithm?

**Comment by mdhaber** [comment]
@seryrzu if you want to find a minimum within an interval, please provide the `bounds` argument, not `bracket`.
```python3
from scipy import optimize
def f(x):
    return -5 * x**5 + 4 * x**4 - 12 * x**3 + 11 * x**2 - 2 * x + 1
res = optimize.minimize_scalar(f, bounds=(-0.5, 0.5))
res.x  # 0.10985997156890048
```
