### ISSUE TITLE
mstats_basic.py - mannwhitneyu [scipy/scipy/stats/mstats_basic.py]

### ISSUE THREAD

**Issue by mikoff** [scipy/scipy#5933]
I think that there is a strange behavior in Mann Whitney U-test implementation.
According to the [wiki](https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test) and other sources, the lowest U-value should be used to consult significance tables. The same value should be returned by the procedure.
However, in current implementation the returned U-value depends on the order of sample sizes in the procedure call and returns the test variable (U) for the first sample size (x).
May be it is better to return the tuple list of U-values, or the maximum U-value which always the same and equals to len(x)*len(y)

**Comment by ev-br** [comment]
There is an effort on cleaning up/enhancing Mann-Whitney U test, https://github.com/scipy/scipy/pull/4933
Unfortunately it stalled and is up for grabs for someone to finish it up.

**Comment by ev-br** [comment]
Also, I think stats version should be worked on first, and mstats version should follow. Is it something you'd be interested in working on, @mikoff ?

**Comment by mikoff** [comment]
@ev-br 
Yep, i would be happy to participate. Should i try to take #4993?

**Comment by ev-br** [comment]
Both gh-4933 and gh-4993 (now that you mention it) look stalled, so working on either of them would be welcome I think. We generally do not formally assign issues to people, so you're welcome to pick either of them. 

I suggest grabbing a branch from github, rebasing on master, and then working off the rebased one. For gh-4933 I suppose it's easier to start with https://github.com/ev-br/scipy/tree/pr/4933.The only thing we require is that the original author information is preserved (IOW, if you squash the commits, make sure the original authors are still listed). If you get stuck, ping us. It's OK to submit a WIP pull request, too.

**Comment by mdhaber** [comment]
@ev-br @chrisb83 @WarrenWeckesser 
Regarding the test statistic returned, gh-4933 maintained the behavior of `stats.mannwhitneyu`: it is always the statistic associated with the first sample. This is now documented:
```
        statistic : float
            The Mann-Whitney U statistic corresponding with sample `x`. See
            Notes for the test statistic corresponding with sample `y`.
```
The notes explain how to calculate the other statistic.

This makes perfect sense to me. This matches the behavior of R's `wilcox.test`, and there is plenty of precedent in `stats`.
For instance, `stats.ttest_ind` returns the statistic associated with `x`, not the absolute value of the t-statistic. As 
```python3
stats.ttest_ind(x, y).statistic == -stats.ttest_ind(y, x).statistic
```
so
```python3
stats.mannwhitneyu(x, y).statistic == len(x)*len(y)-stats.mannwhitneyu(y, x).statistic
```

From that perspective, the real issue is the unusual behavior of `mstats.mannwhitneyu`, which always returns the minimum statistic. This is addressed in gh-14106.
