### ISSUE TITLE
Segfault in grey_erosion, grey_dilation, etc.

### ISSUE THREAD

**Issue by stefanv** [scipy/scipy#5937]
To reproduce:

``` python
from scipy import misc, ndimage as ndi
import numpy as np

image = misc.face()[..., 0]
selem = np.array([[0]])
ndi.grey_erosion(image, footprint=selem)
```

Traceback:

```
#0  0x00007fffe7441e3a in NI_MinOrMaxFilter (input=0x7fffe7666d50, footprint=0x0, structure=0xfc0ae0, output=0x1200af0, mode=786432, cvalue=0, origins=0xa19640, minimum=1)
    at scipy/ndimage/src/ni_filters.c:586
```

**Comment by ev-br** [comment]
Seems to have been there forever: segfaults on master, 0.14.1 and 0.9.0

**Comment by jaimefrio** [comment]
I get no segfault on Mac, but I think I know where this is coming from:

 * The problem is happening in [`NI_MinOrMaxFilter`](https://github.com/scipy/scipy/blob/maintenance/0.17.x/scipy/ndimage/src/ni_filters.c#L516).
 * Because your footprint has no element set to `True`, [this call to `NI_InitFilterOffsets`](https://github.com/scipy/scipy/blob/maintenance/0.17.x/scipy/ndimage/src/ni_filters.c#L557) is equivalent to doing `offsets = malloc(0)`, see [here](https://github.com/scipy/scipy/blob/maintenance/0.17.x/scipy/ndimage/src/ni_support.c#L518).
 * According to [this](http://pubs.opengroup.org/onlinepubs/009695399/functions/malloc.html), `malloc(0)` will either be "a null pointer or a unique pointer." And the problem is that the pointer gets dereferenced [at least once](https://github.com/scipy/scipy/blob/maintenance/0.17.x/scipy/ndimage/src/ni_filters.c#L495), and the dereferenced value used as an offset for a pointer into the input array an dereferenced itself [at least once](https://github.com/scipy/scipy/blob/maintenance/0.17.x/scipy/ndimage/src/ni_filters.c#L497). One of those is blowing up in your case, I'm probably getting lucky and my empty chun

To figure out a solution, what is a minimum filter supposed to return if the footprint is empty, as is the case?

**Comment by stefanv** [comment]
I'm not sure; honestly, I tried to parse the docstring and it is difficult
to understand what it means:

```
footprint : array of ints, optional
    Positions of non-infinite elements of a flat structuring element
    used for the grayscale erosion. Non-zero values give the set of
    neighbors of the center over which the minimum is chosen.
```

**Comment by jaimefrio** [comment]
It would be nice to fix what's broken on the C side, but it is such a convoluted mess that it is hard to be sure that nothing will be terribly broken by any change. An easy way out of this, which seems to make sense, would be to have in the Python wrapper something akin to:

```Python
if not any(footprint):
    raiseValueError("footprint cannnot be all zeros")
```

unless we can come up with some sane return for that case, like the input unchanged, which I would anyway also handle in the Python wrapper.

**Comment by stefanv** [comment]
That seems like the right thing to do.  That is, if I understand the
footprint correctly.

@jni, Have you looked at the footprint parameter before?
​

**Comment by jni** [comment]
Yes yes, I think it is wholly nonsensical to specify a footprint with all zeros, so @jaimefrio's solution seems ideal. I've never been clear on the differences between footprints and structuring elements, though, and how they might interact, ie what happens when one gives an invalid footprint but a valid `structure=` or `size=`?

**Comment by rgommers** [comment]
this was done, example now gives `ValueError: All-zero footprint is not supported.` thanks all
