### ISSUE TITLE
default maxiter/maxfev in minimize_neldermead over rule user

### ISSUE THREAD

**Issue by samtygier** [scipy/scipy#5966]
scipy.optimize.minimize() with method='Nelder-Mead' has maxiter and maxfev options to end optimization early. If either of them is unset then it gets set to 200 times the number of input variables. For slow to converge functions this may not be enough. Currently if the user increases only one of these, then the optimization will stop early due to the default value of the other.

For example the following function requires about 4000 evaluations to minimize 

```
from numpy import sqrt, sin, arctan2
import scipy.optimize

def test_func(v):
	x,y = v
	r,t = sqrt(x**2+y**2), arctan2(x,y)
	a,b  = 20, 0.5
	pen = sin(r*a + t)+r*b
	return pen

print "1) opts {}"
res = scipy.optimize.minimize(test_func, [1,1], method='Nelder-Mead')
print res
print "\n2) opts {'maxiter':5000}"
res = scipy.optimize.minimize(test_func, [1,1], method='Nelder-Mead', options={"maxiter":5000})
print res
print "\n3) opts {'maxfev':5000}"
res = scipy.optimize.minimize(test_func, [1,1], method='Nelder-Mead', options={"maxfev":5000})
print res
print "\n4) opts {'maxiter':5000, 'maxfev':5000}"
res = scipy.optimize.minimize(test_func, [1,1], method='Nelder-Mead', options={"maxiter":5000, "maxfev":5000})
print res
```

Calls 2 and 3 will stop after 400 evaluations or iterations, even though the user has asked to increase the number. Only by increasing both can the function be minimized.

I propose that if the user specifies maxiter, then the function wont halt after any number of evaluations, and vice versa.

Patch to follow.

**Comment by samtygier** [comment]
_minimize_powell() has the same issue. Once you are happy with the solution I shall make a patch for that as well (or I could put that in the same patch).

**Comment by andyfaff** [comment]
My guess is that people normally set a limit on `maxfun` before a limit on `maxiter`. This is because they often know how long it takes to perform one function evaluation. By limiting `maxfun` you are limiting the upper time bound on the minimisation.
I'd note here that the docstring does not specify what `maxfun` and `maxiter` default to, you have to read the code to do that. (as a minimum the docstring should be fixed).
It was suggested in #5968 that one could set `maxfun` and `maxiter` to `np.inf`. This way the minimization would keep going until it converged. Setting `maxfun` and `maxiter` would then put a clear specified limit on how long the minimization kept going for.
Perhaps that's not a bad idea, but are there any cases where the simplex doesn't converge? That would be bad because the minimisation would never stop.
I think any solutions proposed should be floated on the scipy-dev mailing list.

**Comment by samtygier** [comment]
As it currently is if setting maxfun (maxfev) does the same thing, i.e. the 3rd example above stops after 400 iterations (731 function calls) even though the user specified maxfev=5000.

As suggested I made a simpler patch using np.inf https://github.com/samtygier/scipy/commit/bf1d89fc06e24aeb58e940a9bf1341595efc3ffd

With either patch if the user specifies neither then the minimization stops after N*200 iterations or function calls (which ever happens first). If the user specifies just 1 of maxfev or maxiter, then that becomes the only stopping condition. If they specify both, then it stops with which ever happens first. I think this is the least surprising behavior.

I could update the doc string to say what happens in the case of neither or both being specified.

**Comment by josef-pkt** [comment]
One question is whether there is a safeguard inside each iteration to terminate. For example, is there a linesearch that could become endless if there are nans or other weird things.
(I wonder whether there was an algorithmic reason to add both criteria in the first place.)

My first thought was that this breaks backwards compatibility, If I use maxiter and maxfev in the sense of a minimum condition, stop if the tighter criterion is satisfied, then this will change the number of iterations.
On the other hand, when I'm using fmin I usually have to alternate with increasing maxiter and maxfev in many cases until I get convergence.
For statsmodels I recommend and use nelder mead as preliminary estimators when the starting values might be bad and usually limit with maxiter, because individual function evaluations are relatively cheap..

**Comment by samtygier** [comment]
Nelder-Mead has no loop inside the iteration, but an iteration can make between 1 and 3 calls to the function. So there is no risk of infinite looping if only maxiter is set.
(I am not sure I can see a logical reason why some minimizers, offer maxiter, some maxfev, and some both.)

In terms of backwards compatibility:
If you have set both maxiter and maxfev, then the behavior is the same, it will stop if either limit is reached.
If you have set neither, then the behavior is the same, it will stop when either limit reaches N*200 (maxfev will be hit first).
If you have set just one of maxiter or maxfev, then previously the search could stop much before that limit, now it will honor that limit, resulting it a better chance of convergence, though with a longer run time. I'd consider this to be a bug fix, as the code now does what it was asked.

I noticed one issue with my second implementation ( https://github.com/samtygier/scipy/commit/bf1d89fc06e24aeb58e940a9bf1341595efc3ffd ). If you call it with maxiter or maxfev =None, then it will treat None as zero, and stop after the first iteration. I'll rework it so that the defaults in the definition are None, and set to np.inf when needed.

**Comment by josef-pkt** [comment]
> I'd consider this to be a bug fix, as the code now does what it was asked.

Not the way I see it.

If I set maxfev to a large number because I don't care about it and just want maxiter to be binding, then this would change. I and statsmodels, AFAIR, don't have code like this and the new pattern sounds fine with me. (for example I don't think the change in the criteria is binding or affects the results in any of our current use.)

In contrast, I would be very upset if numpy allclose would get a similar change where if I set atol or rtol but not both the other one wouldn't use the default anymore.
or similarly, if precision in convergence criteria would switch from "or" to "and" or the other way around it would affect our test results.
