### ISSUE TITLE
Test failures for sparse sum tests on 32-bit Python

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#5972]
Getting a large amount of test failures like the one below, I assume that this is due to gh-5907:

    ======================================================================
    FAIL: test_base.TestCSC.test_sum(<type 'numpy.uint64'>, 1)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/sparse/tests/test_base.py", line 767, in check
        assert_equal(dat.sum(axis=0).dtype, datsp.sum(axis=0).dtype)
      File "/home/rgommers/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 375, in assert_equal
        raise AssertionError(msg)
    AssertionError: 
    Items are not equal:
     ACTUAL: dtype('uint64')
     DESIRED: dtype('uint32')

And also a large set of overflow warnings, all on the same line:

    /home/rgommers/Code/scipy/scipy/sparse/dok.py:370: RuntimeWarning: overflow encountered in ulonglong_scalars
      result[i] += v * other[j]

**Comment by Tiepies** [comment]
The test failures are easy to fix by adding `np.can_cast` conditions in the type casting part of the `spmatrix.sum` and `compressed.sum` method definitions. I will submit a pull request with that fix.

The overflow warnings are thrown because #5907 (re-)introduced tests for a wider range of dtypes in `test_base._TestCommon.test_sum`, including unsigned integers. The output of `np.matrix.sum` is the same as that of `dok_matrix.sum`, but only the latter protests about overflow:

````
>>> import numpy as np
>>> from scipy.sparse import dok_matrix
>>> dat_1 = np.matrix([[0, 1, 2],
                       [3, -4, 5],
                       [-6, 7, 9]])
>>> dat = np.matrix(dat_1, dtype = np.uint32)
>>> datsp = dok_matrix(dat, dtype=np.uint32)
>>> dat.sum()
17
>>> datsp.sum()
/home/bram/packages/scipy/scipy/sparse/dok.py:370: RuntimeWarning: overflow encountered in uint_scalars
  result[i] += v * other[j]
17
````
How to appropriately deal with those warnings, I don't know.

**Comment by Tiepies** [comment]
One workaround is to use a `numpy.errstate` context manager in the `test_sum` method to ignore the warnings, but I don't know if that is desirable. The fact that `numpy.matrix.sum` does not warn for overflow in these cases is likely related to numpy/numpy#593.
