### ISSUE TITLE
Compatibility issues with numpy's fromnumeric.py

### ISSUE THREAD

**Issue by gfyoung** [scipy/scipy#5987]
xref <a href="https://github.com/pydata/pandas/issues/12644">#12644 </a> (`pandas`)

While doing a spot check for my `numpy` PR <a href="https://github.com/numpy/numpy/pull/7325">#7325</a> in `scipy`, I came across many <i>current</i> incompatibilities between functions defined in numpy's `fromnumeric.py` module <a href="https://github.com/numpy/numpy/blob/master/numpy/core/fromnumeric.py">here</a> that have identically-named but differently implemented methods/functions in `scipy.sparse`.

In particular, the ones that I have found so far are:

`mean`
`reshape`
`sum`
`transpose`

In `pandas`, what we have chosen to do is "swallow" incompatible arguments with an `*args` argument because `numpy` passes them in positionally internally even though the signature uses keyword.  However, I don't know what the protocol here is (or should be) in `scipy`.

**Comment by perimosocordiae** [comment]
In general, we try to instruct users to avoid calling numpy functions on sparse matrices altogether. It's still a pretty big source of issues, though, especially when the numpy function tries to convert the spmatrix to an array and ends up producing a single-element array with `dtype=object`.

I'm -1 for adding something like `*unused_args, **unused_kwargs` to the methods you identified because I suspect that would hide more bugs than it fixes.

I'm +1 for working toward numpy signature compatibility where possible. Hopefully numpy can settle on something like `__numpy_ufunc__`, but until then there's not a whole lot we can do about it.

**Comment by gfyoung** [comment]
1) When you pass in arguments that aren't used at all, what bugs could it hide?  The thing we do is `pandas` is check whether `*unused_args` contains <i>only</i> `numpy`-compatible arguments and then we ignore them afterwards.

2) Out of curiosity, where in the documentation does it actively discourage members from using `numpy` functions on sparse matrices?

Working towards `__numpy_ufunc__` is certainly desirable, but that won't happen for sometime, and I guess we can't count on that in `scipy` immediately after it's implemented due to backwards compatibility.

I am alright with just making the discouragement more prominent in `scipy` due to these issues.  However, I guess it's a question of whether or not it's worth our while to enforce it.

**Comment by perimosocordiae** [comment]
Checking the unused args on each call seems expensive, but if you don't do it you'll hide typo bugs and silently do something the user doesn't expect. That's why I'm more in favor of updating the signatures to be more compatible without varargs hacks.

I'm not sure if the docs currently say that, but they should. I was referring more to how we respond to Github issues / StackOverflow questions / etc. For example: https://github.com/scipy/scipy/issues/5785#issuecomment-177597170

Offtopic: One nice thing about `__numpy_ufunc__` is that it doesn't require much in the way of backwards compatibility hacks. In fact, there's already an implementation in `scipy.sparse.spmatrix`, it just doesn't do anything because numpy never calls it.

**Comment by gfyoung** [comment]
Yes, `__numpy_ufunc__` would be nice to have but we don't have it.  If we did, this would never have become an issue.  I can't find too much on discouraging users to not use `numpy` functions with sparse matrices, so that certainly is something that can be done.

Finally, in terms of "updating" signatures, what exactly do you mean by that?  Surfacing arguments that are `numpy`-compatible is the first thing that comes to my mind but that means a little misleading if we don't actually use them but perhaps you meant something different.

**Comment by gfyoung** [comment]
My `numpy` PR regarding these `fromnumeric.py` incompatibilities has been merged.  So now (hopefully) we can just worry about backwards compatibility.  Any suggestions besides documentation?

**Comment by perimosocordiae** [comment]
By updating signatures, I mean surfacing the numpy-compatible kwargs that we might hope to eventually support (e.g., `axis=None`), then throwing an exception if we get a value we can't handle.

**Comment by gfyoung** [comment]
Wait, so we do actually want the signatures to be `numpy`-compatible even though we discourage using `numpy` functions for `sparse` matrices?  I'm confused.

**Comment by perimosocordiae** [comment]
Where possible, sure, we want them to be compatible. At the very least, it'll make the API easier for users to understand.

The main reason we discourage using numpy functions for sparse matrices is that they're not guaranteed to work in all cases. That doesn't mean we shouldn't try to make some of those cases not fail.
