### ISSUE TITLE
dirichlet.rvs has incorrect shape

### ISSUE THREAD

**Issue by NeilGirdhar** [scipy/scipy#6005]
```
In [1]: import scipy.stats as ss

In [3]: ss.dirichlet.rvs([1,2,3], size=10).shape
Out[3]: (10, 3)

In [4]: ss.dirichlet.rvs([1,2,3], size=1).shape
Out[4]: (1, 3)

In [5]: ss.dirichlet.rvs([1,2,3]).shape
Out[5]: (1, 3)

In [7]: ss.norm.rvs(size=10).shape
Out[7]: (10,)

In [8]: ss.norm.rvs(size=3).shape
Out[8]: (3,)

In [10]: ss.norm.rvs()
Out[10]: -0.08102031305456647

```

Line 5 should have shape (3,).

**Comment by WarrenWeckesser** [comment]
The problem is that the default `size` is `size=1`, for which the correct output shape *is* (1, 3) (when `alpha` has length 3).  In general, when `alpha` has length `m`, and the size is an integer `n`, the output has shape `(n, m)`, and this includes the case `size=1`.  It is only when `size` is None will the output have shape `(m,)`, and that is the recommended work-around to the problem reported above.

I think `size=None` *should* be the default, but it isn't.  We'll have to decide if there is a way we can update all the multivariate distributions to consistently use `size=None` as the default in the `rvs` method.  Currently, only 
`multinomial` and `multivariate_hypergeom` use the default `size=None`. All the other multivariate distributions except `random_correlation` use `size=1`. (`random_correlation.rvs` doesn't even have a `size` parameter.)

**Comment by rkern** [comment]
Related: #13171 (i.e. a mis-handling of `size=1` as `size=None`).

Perhaps it's time to rationalize all of these.

**Comment by mdhaber** [comment]
Let's lump this into gh-7689.
