### ISSUE TITLE
python crashes for linalg.interpolative.svd with certain large arrays

### ISSUE THREAD

**Issue by npaulson** [scipy/scipy#6016]
When I run this svd algorithm for data with many more dimensions than data points this code crashes python (no error message, just windows telling me it's closing python)

I'm working on a windows 7 enterprise machine with 12gb of ram. I'm running scipy version 0.17.0 and python 2.7.11.

I'll include the code I ran below to get this error:
```
from scipy.linalg.interpolative import svd
import numpy as np
rrr = np.random.random((10, 333396))
U, S, V = svd(rrr, 20)
```

it crashes on the last line

**Comment by maniteja123** [comment]
Hi, I am not an expert in this but as [Wikipedia](https://www.wikiwand.com/en/Singular_value_decomposition) says

>
An m × n matrix M has at most p distinct singular values. where p = min(m,n)
>

To reproduce this error,

```
 import numpy as np
>>> a = np.random.random((15,20))
>>> u,s,v = svd(a,15)
>>> u,s,v = svd(a,16)
segmentation fault(core dumped)
```

i suppose the value eps_or_k should be less than min(10,333396) = 10 since it seems to be the rank of the approximation. I hope that I make some sense here. Please do correct if I am understanding something wrong here.

**Comment by npaulson** [comment]
Ah, I see. This is definitely the cause of my problem. Thank you for
looking into it.

Maybe there should be some sort of error handling to warn the user and not
allow python to crash.

Best,
Noah



On Wed, Mar 30, 2016 at 10:43 AM, Maniteja Nandana <notifications@github.com

**Comment by maniteja123** [comment]
I am also not aware of the internal implementation but looks like it is built on fortran code. So someone experienced can look into this and suggest a workaround. Sorry can't be of much help here.

**Comment by ev-br** [comment]
#6033 is a quick fix
