### ISSUE TITLE
Least squares optimizers returned "cost" is not L2-norm

### ISSUE THREAD

**Issue by moloney** [scipy/scipy#6018]
One would assume the "cost" value in the result from `lsq_linear` and `least_squares` is the L2-norm of the residuals. Currently the reported cost is half the sum of squared differences instead of the sqrt of the sum of squared differences.

This is trivial to fix in `lsq_linear`, but a little more involved for `least_squares` due to the loss function logic.

**Comment by josef-pkt** [comment]
Least squares minimizes sum of squares, so I would never expect any square root there.

Why do you expect a square root, L2-norm?

**Comment by moloney** [comment]
Sure, I guess I would expect it to be the sum of squares or the L2-norm. However, I wouldn't expect it to be half the sum of squares.

**Comment by josef-pkt** [comment]
Why is that important?

I don't know the specifics here, but in general it is quite common to add a factor to the objective function so that the derivative/gradient or first order condition have a nice algebraic form. In the sum of squares case the 2 from the derivative of the power cancels with the on half.

The point is whether the objective function is just for the minimization or is also directly used for, for example, F-tests or Likelihood ratio tests. In those cases having a consistent definition can be important.

**Comment by moloney** [comment]
Yes, I ran into this because I was using the "cost" to compute some other fit statistics. If nothing else, I think it should be documented as to what exactly "cost" is returning. If it just being used for internal purposes and we shouldn't care exactly what the definition is, then it shouldn't really be getting returned as part of the result.

**Comment by ev-br** [comment]
http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html#scipy.optimize.least_squares seems to have a factor of 0.5 in the formula. How else would want it documented?

**Comment by moloney** [comment]
Argh... I feed dumb...  Sorry for the noise.

**Comment by ev-br** [comment]
Maybe `(1/2)*...` would be more prominent?

**Comment by moloney** [comment]
Maybe include a brief explanation of why that cost function was choosen?  Like what @josef-pkt posted above.

**Comment by edbird** [comment]
IMO it's not that obvious from the docs. There should probably be at least a sentance warning users of this factor of 0.5, because it might be missed from a quick glance over. I noticed it but didn't put two and two together until I inspected the output of "cost" compared to calculating it manually myself.

**Comment by charlescochran** [comment]
I also missed this and was accordingly perplexed until Googling revealed this issue.

**Comment by lucascolley** [comment]
feel free to suggest an improvement to the docs if you can think of one!
