### ISSUE TITLE
Build in Windows platform under Visual Studio prompt will fail

### ISSUE THREAD

**Issue by kevin-coder** [scipy/scipy#6098]
**Build Environment:**
1. scipy-0.17.0.tar.gz
2. In Windows platform, both Win8.1 and Win10
3. In Visual Studio 2012 prompt (Developer Command Prompt for VS2012)
4. Also put both "BLAS.lib" and "LAPACK.lib" into the Python libs path. These 2 libraries were downloaded from http://icl.cs.utk.edu/lapack-for-windows/lapack/
**Build cmd:**
Python setup.py build
**Build Result:**
...
...
Found executable C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\amd6
4\link.exe
_vq.obj : warning LNK4197: export 'init_vq' specified multiple times; using firs
t specification
   Creating library build\temp.win-amd64-2.7\Release\scipy\cluster\_vq.lib and o
bject build\temp.win-amd64-2.7\Release\scipy\cluster\_vq.exp
_vq.obj : error LNK2019: unresolved external symbol __imp_free referenced in fun
ction __Pyx_ReleaseBuffer
_vq.obj : error LNK2019: unresolved external symbol __imp_malloc referenced in f
unction __pyx_pf_5numpy_7ndarray___getbuffer__
_vq.obj : error LNK2019: unresolved external symbol sgemm_ referenced in functio
n __pyx_fuse_0__pyx_f_5scipy_7cluster_3_vq_cal_M
_vq.obj : error LNK2019: unresolved external symbol dgemm_ referenced in functio
n __pyx_fuse_1__pyx_f_5scipy_7cluster_3_vq_cal_M
_vq.obj : error LNK2019: unresolved external symbol sqrt referenced in function
__pyx_fuse_0__pyx_f_5scipy_7cluster_3_vq__vq
_vq.obj : error LNK2001: unresolved external symbol _fltused
LINK : error LNK2001: unresolved external symbol _DllMainCRTStartup
build\lib.win-amd64-2.7\scipy\cluster\_vq.pyd : fatal error LNK1120: 7 unresolve
d externals
error: Command "C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\amd64
\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Software\SoftwareDev\Python27
\libs /LIBPATH:C:\Software\SoftwareDev\cygwin64\lib\gcc\x86_64-pc-cygwin\5.3.0 /
LIBPATH:C:\Software\SoftwareDev\Python27\libs /LIBPATH:C:\Software\SoftwareDev\P
ython27\PCbuild\amd64 /LIBPATH:C:\Software\SoftwareDev\Python27\PC\VS9.0\amd64 /
LIBPATH:build\temp.win-amd64-2.7 /LIBPATH:C:\Software\SoftwareDev\Python27\libs
/LIBPATH:C:\Software\SoftwareDev\Python27\PCbuild\amd64 /LIBPATH:C:\Software\Sof
twareDev\Python27\PC\VS9.0\amd64 /LIBPATH:build\temp.win-amd64-2.7 lapack.lib la
pack.lib blas.lib blas.lib /EXPORT:init_vq build\temp.win-amd64-2.7\Release\scip
y\cluster\_vq.obj /OUT:build\lib.win-amd64-2.7\scipy\cluster\_vq.pyd /IMPLIB:bui
ld\temp.win-amd64-2.7\Release\scipy\cluster\_vq.lib /MANIFESTFILE:build\temp.win
-amd64-2.7\Release\scipy\cluster\_vq.pyd.manifest" failed with exit status 1120

from the error log, I know that I may missing some dependent libraries, but I don't know what are they.

**Comment by rgommers** [comment]
You need to use the same MSVC version as was used to build Python itself with. See http://mingwpy.github.io/issues.html#choice-of-msvc-runtime for which MSVC version matches your Python version.

Then keep in mind that you can only build Scipy with MSVC if you also have the Intel Fortran compiler.

Once you have those things right and still run into issues, please provide the complete build log.

**Comment by kevin-coder** [comment]
@rgommers , got you, this time seems clear. I will have a try and thank you for your kind and clear explanation!

**Comment by paranoidpixel** [comment]
@kevin-coder @rgommers Hi everyone, I am getting into the same situation. So @kevin-coder did you get any luck on using the Intel Fortran compiler? or you have other suggestions?

What I would like to do is to build scipy for Python that is shipped with Autodesk Maya (2016). It is  Python 2.7.6 built with MSC v.1700 64 bit.

**Comment by rgommers** [comment]
@paranoidpixel then you want to build with MSVC 1700 or icc + Intel Fortran, should work. Intel keeps their own build instructions quite well up-to-date: https://software.intel.com/en-us/articles/building-numpyscipy-with-intel-mkl-and-intel-fortran-on-windows

**Comment by paranoidpixel** [comment]
@rgommers thanks a lot for your prompt response! I will give it a try.

**Comment by paranoidpixel** [comment]
@rgommers Now I made it work and I can confirm the steps from the Intel link are good (and very easy to do as well). Thanks a lot.

p.s. The numpy can pass most of the tests, but the scipy can't. It will crash the interpreter before finishing. However I am able to use all the modules that I need (mostly linalg and sparse.linalg) and they works properly. I am suspicious because I am using a different version of Python include files and libraries (current the native Python 2.7 installed on my machine, it is because Autodesk Maya's release doesn't include the devel files). Maybe I should rebuild Python 2.7.6 from source and get those files.

**Comment by rgommers** [comment]
>  I am suspicious because I am using a different version of Python include files and libraries (current the native Python 2.7 installed on my machine, it is because Autodesk Maya's release doesn't include the devel files). 

Yes, that does sound like an unhealthy idea.

> Maybe I should rebuild Python 2.7.6 from source and get those files.

If that doesn't solve the crash, you can open a new scipy issue (preferably with a gdb traceback).

**Comment by paranoidpixel** [comment]
@rgommers I have built Python 2.7.6 with the same compiler, scipy.test still crashes. Now I know the problem is at qhull, at scipy/spatial/tests/test_qhull.py. I am building a debug version of scipy to get more info out of it, however the building process stops at the following:

ifort.exe:f77: scipy\integrate\tests\banded5x5.f
ifort: command line error: option '/g' is ambiguous
error: Command "C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\bin\intel64\ifort.exe /nologo /MD /nbs/names:lowercase /assume:underscore /O1  -g -DSCIPY_MKL_H -DHAVE_CBLAS -I"C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\mkl\include" -Ibuild\src.win-amd64-2.7 -I"c:\Program Files\Autodesk\Maya2016\Python\lib\site-packages\numpy-1.12.0.dev0+b2d4951-py2.7-w
in-amd64.egg\numpy\core\include" -I"c:\Program Files\Autodesk\Maya2016\Python\include" -I"c:\Program Files\Autodesk\Maya2016\Python\PC" -c /c  scipy\integrate\tests\banded5x5.f /Fobuild\temp.win-amd64-2.7\Debug\scipy\integrate\tests\banded5x5.o" failed with exit status 1

Any thought on this?

**Comment by rgommers** [comment]
So you got a bit further, past the ``cluster`` issue. The qhull crash is probably gh-6316, there's a proposed fix in https://github.com/scipy/scipy/issues/6316#issuecomment-229482576 that seems to work.

**Comment by paranoidpixel** [comment]
@rgommers yes I confirmed that solves the problem. Thank you very much!

**Comment by rgommers** [comment]
Excellent. Thanks for the bug report and following up.
