### ISSUE TITLE
scipy.stats.gamma is wrong

### ISSUE THREAD

**Issue by libgober** [scipy/scipy#6111]
There is something weird about the gamma random variates function, I don't know if the documentation needs to be updated or whether it's a bug.  The following code should, I believe, draw 100,000 times from a gamma with scale 1 and shape 1.  

import scipy.stats as stat
D = stat.gamma.rvs(1,1,size=100000)

The mean of D should be 1, but it is close to 2.  The minimum is close to 1.

The following code produces a more reasonable answer

import numpy as np
np.mean(np.random.gamma(1,1,10**5))

**Comment by WarrenWeckesser** [comment]
The first three arguments of `gamma.rvs` are the shape, the location and the scale (in that order).  When you write `gamma.rvs(1,1,size=100000)`, you are setting the shape parameter to 1 and the location parameter to 1, and leaving the scale at its default value of 1.  Setting the location parameter to 1 shifts the distribution to the right by one unit.

What you probably meant to do was:

    D = stat.gamma.rvs(1, 0, 1, size=100000)

or more explicitly

    D = stat.gamma.rvs(a=1, loc=0, scale=1, size=100000)

or even

    D = stat.gamma.rvs(a=1, scale=1, size=100000)

because the default value of `loc` is 0.  The default value of `scale` is 1, but I left it in there because you'll probably want to change that.

When comparing scipy's parameter names to the wikipedia page https://en.wikipedia.org/wiki/Gamma_distribution, the mapping is `a == k` and `scale == theta`.  The wikipedia page doesn't include a location parameter, because typically one doesn't use a location parameter with the gamma distribution.

**Comment by michath** [comment]
> When comparing scipy's parameter names to the wikipedia page https://en.wikipedia.org/wiki/Gamma_distribution, the mapping is a == k and scale == theta.

unfortunately, that is true only for k==1, because scipy's PDF has scale where wikipedia's has theta^k and theta. this is a real issue.

**Comment by WarrenWeckesser** [comment]
@michath wrote

> scipy's PDF has scale where wikipedia's has theta^k and theta. this is a real issue.

The SciPy code can be deceptive to read, because SciPy implements all the continuous distributions as location-scale families.  The `_pdf` method is implemented in terms of the *shape parameters only*.  That is, it is the "standard" PDF with location 0 and scale 1.  It is this standard PDF that is shown in the docstring for `scipy.stats.gamma`:

    f(x, a) = \frac{x^{a-1} \exp(-x)}{\Gamma(a)}

The `pdf` method takes care of the shifting and scaling of the arguments by `loc` and `scale` before calling `_pdf`.

The implementation in `_pdf` is

    def _pdf(self, x, a):
        # gamma.pdf(x, a) = x**(a-1) * exp(-x) / gamma(a)
        return np.exp(self._logpdf(x, a))

    def _logpdf(self, x, a):
        return sc.xlogy(a-1.0, x) - x - sc.gammaln(a)

and if you undo the call to _logpdf, you can see that `_pdf` computes (as noted in the comment, and as promised in the docstring)

    x**(a-1) * exp(-x) / gamma(a)

The `pdf` method does, in effect,

    z = (x - loc)/scale,
    result = _pdf(z, a)/scale

so the result is

      ((x - loc)/scale)**(a - 1) * exp(-(x-loc)/scale) / gamma(a) / scale
    = ((x - loc)**(a - 1) / scale**a) * exp(-(x - loc)/scale) / gamma(a)

If we set `loc` = 0 to match wikipedia's lack of a `loc` parameter, this is

    x**(a - 1) / scale**a * exp(-x/scale) / gamma(a)

which matches the wikipedia formula after renaming `a` to `k` and `scale` to θ.

**Comment by libgober** [comment]
These comments are very clarifying. Thanks!
