### ISSUE TITLE
scipy.linalg.logm fails for a trivial matrix

### ISSUE THREAD

**Issue by 0serg** [scipy/scipy#6113]
As of scipy 0.16.1

```
import scipy.linalg
import numpy as np
x = np.array([[0,1],[-1,0])
scipy.linalg.logm(x)
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Python27\python-2.7.10.amd64\lib\site-packages\scipy\linalg\matfuncs.py", line 200, in logm
>     F = scipy.linalg._matfuncs_inv_ssq._logm(A)
>   File "C:\Python27\python-2.7.10.amd64\lib\site-packages\scipy\linalg\_matfuncs_inv_ssq.py", line 884, in _logm
>     U = _logm_triu(T)
>   File "C:\Python27\python-2.7.10.amd64\lib\site-packages\scipy\linalg\_matfuncs_inv_ssq.py", line 780, in _logm_triu
>     R, s, m = _inverse_squaring_helper(T0, theta)
>   File "C:\Python27\python-2.7.10.amd64\lib\site-packages\scipy\linalg\_matfuncs_inv_ssq.py", line 448, in _inverse_squaring_helper
>     raise Exception('internal inconsistency')
> Exception: internal inconsistency

One can easily see that trivial answer exists:
`scipy.linalg.expm(np.array([[0,np.pi*0.5],[-np.pi*0.5,0]]))`

> array([[ 0.,  1.],
>        [-1.,  0.]])

**Comment by argriffing** [comment]
This looks like a bug, the eigenvalues are i and -i and the algorithm is intended to work when the matrix has no negative real eigenvalue.

**Comment by argriffing** [comment]
I think the conditions in the piecewise formula 11.28 in "Functions of Matrices : Theory and Computation" are a bit wrong. That's right, I'm going to blame the textbook. In particular I think the second condition is off. The text says "Our overall formula is as follows, where we avoid the more expensive atanh formula when lambda1 and lambda2 are sufficiently far apart" but the condition is
abs(lambda1) < abs(lambda2)/2 or abs(lambda2) < abs(lambda1)/2.
I think this condition is intended to require that lambda1 and lambda2 are relatively far apart. But it is not catching the case lambda1 = i, lambda2 = -i. These are far apart from each other, but they do not satisfy the condition because abs(lambda1) = abs(lambda2). Because the condition is not satisfied, an alternative calculation is used, which includes division by the sum lambda1+lambda2 which is zero :/

**Comment by argriffing** [comment]
@0serg Thanks for this bug report! The issue should be fixed in https://github.com/scipy/scipy/pull/6116.

**Comment by 0serg** [comment]
@argriffing, thanks for a quick response!
