### ISSUE TITLE
incorrect distribution fitting for data containing boundary values.

### ISSUE THREAD

**Issue by zym1010** [scipy/scipy#6167]
I found that when using `scipy.stats.expon.fit(X, floc=0)` (so location parameter is fixed to 0), data points having values `0` are not considered during fit.

> In [26]: expon.fit([2,2,2,2],floc=0)
> Out[26]: (0, 2.0000000000000022)
> 
> In [27]: expon.fit([0,0,0,0,2,2,2,2],floc=0)
> Out[27]: (0, 2.0000000000000022)

However, those zero data points are honored in MATLAB

> fitdist([0,0,0,0,2,2,2,2]','Exponential')
>
> ans = 
> 
> ExponentialDistribution
>
> Exponential distribution
> mu = 1   [0.554682, 2.31627]
> 

On <http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.html>, it says that
> `x` is valid if it is within the support of a distribution, `self.a <= x <= self.b`

I believe this statement is not respected in `rv_continuous.fit`. The problem should come from <https://github.com/scipy/scipy/blob/v0.17.1/scipy/stats/_distn_infrastructure.py#L1916> and <https://github.com/scipy/scipy/blob/v0.17.1/scipy/stats/_distn_infrastructure.py#L1943>, where values equal to boundary values of the support are discarded.

**Comment by josef-pkt** [comment]
This, specifically line 1916, looks like a bug for zero probability events to me that won't be easy to fix generically.

I don't have time to look at it carefully, so some quick thoughts

Having many zeros in a sample is a zero probability event for continuous data, so your data don't fit the distribution.

What I don't understand is why line 1916 doesn't just return inf. Ignoring observations looks wrong to me.

In statsmodels we `clip` observations for some distributions so that they are in the interior of the space. Some loglikelihood functions (`pdf`) are not well defined for boundary points. 

In statsmodels the clipping is distribution specific. So if we would for example replace the strict by a weak inequality in the checks on those two lines, then it would need to be verified for all distribution with a finite bound whether it can handle the boundary points or not. Also, I don't think clipping (moving boundary observations into the interior) would be possible generically.

```
>>> stats.expon.fit(np.clip([0,0,0,0,2,2,2,2], 1e-20, np.inf),floc=0)
(0, 1.0)
```

I only have an old scipy open right now
shouldn't out of bounds points return nan or raise an exceptions or add a convergence warning?
```
>>> stats.expon.fit([-5, 0,0,0,0,2,2,2,2],floc=0)
(0, 1.999996505840216)

>>> stats.expon.fit([-5, 0,0,0,0,2,2,2,2])
(-2.0082719945832983e-09, 0.99995329544887768)

>>> stats.expon.fit([-5, 0,0,0,0,2,2,2,2], loc=-10)
(-5.0000000004110667, 5.3332677563860429)

>>> scipy.__version__
'0.15.1'
```

**Comment by josef-pkt** [comment]
There are not that many continuous distribution with finite bound.

If someone wants to go and write test cases for them, then I think it would be possible to add an internal keyword like `_boundary_allowed` and switch between weak and strict inequality, if needed.

The rvs based tests won't cover these cases because of the zero probability of boundary values, but boundary observations could just be added explicitly to the test cases. (most of the loop and cases should be already in the unit test suite, AFAIK.)

**Comment by josef-pkt** [comment]
one more:
expon doesn't have a `_fit` method that could just return the estimate based on the mean of the data if `floc=0`, as some other distributions do.

**Comment by zym1010** [comment]
@josef-pkt Thanks for detailed comments on this issue.

Maybe the best solution would be adding a special `_fit` for exponential distribution?

as for why out of bounds points don't raise error, I believe it's because the generic `fit` use `_penalized_nnlf ` as the likelihood function, which adds some penalty to out of bound points. While this is necessary to have finite gradient when searching for `loc`, it would be nice to raise some exception if `loc` is fixed... well this might be hard to do in general, so maybe the best would be adding a special `fit` for exponential distribution.

**Comment by zym1010** [comment]
Also I think it's best to have specialized `fit`, rather than tweaking the generic `fit`, because I guess data points on the boundary won't play well with some (say, interior-point based) optimizers...

**Comment by josef-pkt** [comment]
@zym1010   Yes, adding `_fit` to exponential would be the best solution for this case. 

PR welcome. (but I'm not a "real maintainer" anymore)

However, AFAIK, the boundary and out of boundary behavior of fit has never been properly checked. The penalized part was added to help in finding parameter estimates that effect the bounds to cover the observations. 
But it should warn or raise if it didn't find any solution where we only if observation in the support, or like in the -5 expon loc=0 example, where it is impossible to have all observations in the support.

`fit` is still partially "experimental" or "might not work" because there is no generic MLE solution that always works, but it has improved quite a bit over time.

**Comment by josef-pkt** [comment]
> Also I think it's best to have specialized fit, rather than tweaking the generic fit, ...

check how some of the other distributions do it.
AFAIR, there are some distributions that have explicit estimates for specific cases like fixed location, and delegate to the generic `fit` method when there is no explicit estimate.

**Comment by zym1010** [comment]
@josef-pkt  thanks! I will check the code for other distributions and come up with some PR when I have more time.

**Comment by josef-pkt** [comment]
More: I don't think you can override `fit` itself because it has the argument parsing included, e.g. for starting values and fixed parameters.

**Comment by WarrenWeckesser** [comment]
FYI:  A while back I wrote a specialized `fit` method for the beta distribution.  If the `loc` and `scale` are fixed and the user provides values that are not in the fixed interval, a `FitDataError` exception is raised.  See https://github.com/scipy/scipy/blob/master/scipy/stats/_continuous_distns.py#L301

**Comment by pbrod** [comment]
I think there is a simple solution to this.

**Comment by pbrod** [comment]
I think there is a simple solution to this. If we define a support_mask function:

        def _support_mask(self, x)
            return (self.a<=x) | (x<=self.b)

and delegate the support mask calculation in nnlf and _penalized_nnlf to it, then everything will be in accordance with the documentation and the definition of each distribution.

In detail we should replace both the lines 1916 and 1943 

https://github.com/scipy/scipy/blob/v0.17.1/scipy/stats/_distn_infrastructure.py#L1916 and https://github.com/scipy/scipy/blob/v0.17.1/scipy/stats/_distn_infrastructure.py#L1943, 

with 

    cond0 = 1 - self._support_mask(x).

If the support of the distribution does not include the endpoints one should write a customized _support_mask method for the distribution(s) in question.  The corner case checking for the support of the distribution is then delegated to the _support_mask method and this method should also be used by the pdf and logpdf methods. I.e. the L1582 and L1624 in the pdf and logpdf method:

https://github.com/scipy/scipy/blob/v0.17.1/scipy/stats/_distn_infrastructure.py#L1582
https://github.com/scipy/scipy/blob/v0.17.1/scipy/stats/_distn_infrastructure.py#L1624

 should  then be replaced with 

    cond1 = (scale > 0) & self._support_mask(x)

With this change nothing extra needs to be done to the nnlf, pdf and logpdf methods. However, by changing the support check in _penalized_nnlf one must also change the way one calculates the penalty for values where logpdf is infinite, i.e. where pdf==0. One solution for this could be to replace _penalized_nnlf with the following:
     
    def _penalized_nnlf(self, theta, x):
        ''' Return negative loglikelihood function,
        i.e., - sum (log pdf(x, theta), axis=0)
           where theta are the parameters (including loc and scale)
        '''
        try:
            loc = theta[-2]
            scale = theta[-1]
            args = tuple(theta[:-2])
        except IndexError:
            raise ValueError("Not enough input arguments.")
        if not self._argcheck(*args) or scale <= 0:
            return inf
        x = asarray((x-loc) / scale)
        N = len(x)
        cond0 = ~self._support_mask(x)
        Nbad = sum(cond0)
        if Nbad > 0:
            x = argsreduce(~cond0, x)[0]
        logpdf = self._logpdf(x, *args)
        finite_logpdf = np.isfinite(logpdf)
        Nbad += np.sum(1-finite_logpdf, axis=0)
        logscale = N * log(scale)
        if Nbad > 0:
            penalty = Nbad * log(_XMAX) * 100
            return -np.sum(logpdf[finite_logpdf], axis=0) + penalty + logscale
        return -np.sum(logpdf, axis=0) + logscale

**Comment by ev-br** [comment]
+1 for the _support_mask or some such. Are you interested in putting this in a PR, @pbrod ?

**Comment by pbrod** [comment]
I will see what I can do next week, but I can not promise anything.
