### ISSUE TITLE
Different results in expon.cdf and a derived class cdf (with the same pdf as expon). 

### ISSUE THREAD

**Issue by yashu-seth** [scipy/scipy#6185]
```python
>>> from scipy.stats import expon
>>> r1 = expon()
>>> r1.cdf(4.34)
0.9869634717965623
>>> from scipy.stats import rv_continuous
>>> class custom_expon(rv_continuous):
	def _pdf(self, x):
		return r1.pdf(x)

>>> r2 = custom_expon()
>>> r2.cdf(4.34)
0.98031897805159673
>>> r1.cdf
```

I think r1.cdf(4.34) and r2.cdf(4.34) should return the exact values. I cannot figure the reason behind the significant difference.
Also, r2.cdf(4.33) < r2.cdf(4.35)
but,
```python
>>> r2.cdf(4.35)
0.98709318767881626
>>> r2.cdf(4.33)
0.99017134757679626
```

**Comment by argriffing** [comment]
Maybe the stats framework assumes that your pdf integrates to 1 over (-infinity, infinity) and is therefore returning a garbage cdf value because it's not sophisticated enough to detect that its assumptions are violated. You could work around that problem by specifying that the support is (0, infinity) using something like the following code.

```python
from __future__ import print_function, division

from scipy.stats import rv_continuous, expon

r1 = expon()

class custom_expon(rv_continuous):
    def _pdf(self, x):
        return r1.pdf(x)
ce = custom_expon(a=0.0, name='custom_expon')

r2 = ce()
x = 4.34
print(r2.cdf(x))
```

`0.986963471797`

**Comment by argriffing** [comment]
You can use `r2 = custom_expon(a=0)`. I submitted a longer comment, but I think it was lost due to github's server issues https://status.github.com/messages

**Comment by yashu-seth** [comment]
@argriffing Thanks. I think this should fix the problem.

**Comment by ewmoore** [comment]
If you're actually doing what your example code does, it is worth noting
that using the generic cdf routine uses numerical quadrature to find the
cdf value.  Many of the built in distributions (expon) for instance also
include a _cdf routine that uses the analytical CDF. If you have an
analytical CDF, you're liable to be better off including it rather than
counting on integration of the pdf.
