### ISSUE TITLE
callback for Krylov methods

### ISSUE THREAD

**Issue by sebglane** [scipy/scipy#6198]
The Krylov solvers such as `scipy.sparse.linalg.cg` have the `callback` argument. I am using this to monitor convergence. According to the docs, for `scipy.sparse.linalg.cg` the input given to the `callback` is the solution vector and for `scipy.sparse.linalg.gmres` it is the residual vector. But in my version  0.17.1 `scipy.sparse.linalg.gmres` returns a float. I guess it is the 2-norm of the residual vector. Shouldn't the input given to `callback` be independent of the Krylov method?

**Comment by gdmcbain** [comment]
I suspect that the problem here is that the residual vector is not available where the `callback` is to be called; however, the iterate `x` is, so perhaps `callback` should be passed the iterate.  This would be consistent with at least `cg` and `bicg` and proceed towards a positive answer to the question:

> Shouldn't the input given to callback be independent of the Krylov method?

I'm going to attempt to implement this.

**Comment by gdmcbain** [comment]
For a minimal example:
```python
import numpy as np
from scipy.sparse import diags
from scipy.sparse.linalg import gmres

a = diags([-1, 2, -1], [-1, 0, 1], shape=(4,)*2)
print(gmres(a, np.ones(a.shape[0]), callback=lambda r: print(type(r))))
```

On master, this generates
```
<class 'numpy.float64'>
<class 'numpy.float64'>
(array([2., 3., 3., 2.]), 0)
```
but on branch gmres-callback, it's
```
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(array([2., 3., 3., 2.]), 0)
```

**Comment by sethtroisi** [comment]
Related https://github.com/scipy/scipy/pull/7425
