### ISSUE TITLE
PchipInterpolator no longer handles a 2-element array

### ISSUE THREAD

**Issue by kodonnell** [scipy/scipy#6222]
The following command works fine in scipy==0.16.1, but fails in scipy==0.17.1 (but works if you make it a 3 dimension array):

```python
PchipInterpolator([0,1],[0,1])
```

I'm not sure if this is intended behaviour, but at the very least it does not appear to be documented here: http://docs.scipy.org/doc/scipy-0.17.1/reference/generated/scipy.interpolate.PchipInterpolator.html

**Comment by ev-br** [comment]
Indeed. It tries to estimate the end derivatives via a three-point scheme, which fails if there are only two data points.

Previously, the algorithm was effectively assuming zero derivatives at the ends of the interval, so that in scipy 0.16.1 and earlier, `pchip([0, 1], [0, 1])` gives  `x**2 (3 - 2 x)` (which is a unique cubic polynomial with f'(0) = f'(1) = 0, f(0) = 0 and f(1)=1). 
This condition of zero derivatives was a bug and was fixed in https://github.com/scipy/scipy/pull/5351. 

The correct thing to do is probably to special case length-two arrays to make it a linear interpolation (which surely *is* monotonic).

This is what Octave seems to do:

```
octave:7> pchip([0, 1], [0, 1], [0.1, 0.3, 0.5, 0.7, 0.9, 1.0])
ans =

   0.10000   0.30000   0.50000   0.70000   0.90000   1.00000
```

**Comment by ev-br** [comment]
Fix in https://github.com/scipy/scipy/pull/6223
