### ISSUE TITLE
savgol_filter is missing

### ISSUE THREAD

**Issue by mckatzenelson** [scipy/scipy#6333]
New install of Mint, python, scipy.  The savgol filter is still missing.  This was reported about two years ago and closed, though apparently never solved

**Comment by WarrenWeckesser** [comment]
What version of scipy?  You can check by running the following python code:

    import scipy
    print(scipy.__version__)

`savgol_filter` was added in scipy version 0.14.0.

**Comment by mckatzenelson** [comment]
Yes, it is 0.13.3, and it is Mint on a netbook.

Any suggestions as to how to make this work on this system?

**Comment by rgommers** [comment]
install 0.14.0? just removing ``scipy`` from your Mint package manager, and reinstalling with ``pip install scipy`` (should fetch a binary wheel from PyPI) should do the job.

**Comment by mckatzenelson** [comment]
No, it fails.

Please reopen until it is really fixed.

**Comment by WarrenWeckesser** [comment]
@mckatzenelson The title of this issue is "savgol_filter is missing", and the fundamental problem is that you are using an old version of scipy, which simply doesn't have `savgol_filter`.  So from that point of view, this issue has been resolved and should remain closed.

If you are having a problem upgrading your scipy installation in the latest Linux Mint, please open up a new issue and give the details of what you did to upgrade scipy and what errors you got.

If Linux Mint's scipy is 0.13.3, I suspect there will be other python packages that you will want or need to upgrade.  An alternative is to not bother with the packages provided by Linux Mint, and use a free, prepackaged python distribution such as anaconda (https://www.continuum.io/downloads).  It really does make working with the scientific python stack much easier.

**Comment by mckatzenelson** [comment]
I find anaconda to be burdensome and largely irrelevant to how I use python.

**Comment by ev-br** [comment]
You can try `$sudo apt-get remove python-scipy` followed by `$ pip install scipy --user`. If that fails, well, it's either you setting up a virtualenv, or rely on anaconda doing similar things behind the scenes.

In any case, this is not something we can fix in scipy
