### ISSUE TITLE
scipy.stats Breit-Wigner distribution

### ISSUE THREAD

**Issue by andrewfowlie** [scipy/scipy#6414]
I noticed that scipy.stats is missing the relativistic Breit-Wigner distribution (https://en.wikipedia.org/wiki/Relativistic_Breit%E2%80%93Wigner_distribution). NB not be to confused with the similar non-relativistic Breit-Wigner, aka the Cauchy distribution.

This distribution is common in high-energy physics, and would make a good addition. I can help implement it, if it's a good idea.

**Comment by innisfree** [comment]
Here is a starting point.

https://gist.github.com/innisfree/cd0ed7e6c96f7c9e88f85eb3b9665b97

I've implemented the pdf and cdf, but don't quite understand how to inherit the rv_continuous class and pass scale, loc parameters properly. Once the class inheritance etc is correct, it'll have all the attributes of a distribution.

In the future, a few more of the attributes could be overwritten with analytic formulas for speed, if necessary, but the pdf and cdf are analytic and should be quick.

**Comment by josef-pkt** [comment]
for rvs the main useful method is the `ppr`. If that is not available, then rvs will be slow because the default method needs to find the ppf numerically from the cdf for each point.

about the distribution:
I'm always a bit skeptical when a distribution or name in statistics is only used in one scientific field. It's not a reason to rule it out for scipy.stats but maybe there is a more widely spread analog under a different name. I didn't come up with anything in a brief search.

based on the square in the distribution ("relativistic") and the relationship to t and F distribution:
Is this the same as F(1, 1) distribution? 
Or, maybe I'm thinking the wrong way and it is the square-root not the square transformation of cauchy.

**Comment by ev-br** [comment]
This seems to be just a Cauchy distribution of the 4-momentum squared, with the resonance mass/width being loc/scale.

Wikipedia article, linked in the OP, concurs:

> The form of this distribution is similar to the solution of the classical equation of motion for a driven harmonic oscillator damped and driven by a sinusoidal external force. It has the standard resonance form of the Lorentz, or Cauchy distribution, but involves relativistic variables s=p ², here =E 2.

**Comment by innisfree** [comment]
Hello,

That's true. The cdf is a sum of arctans, so I'd be surprised if it could
be inverted analytically. Solving for x in cdf(x)=alpha will probably have
to be done numerically.

It isn't related to the Cauchy by a parameter redefinition (though it is
similar) or any other well-known distn afaik.

It's very important in particle physics, though not discussed much as a
statistical distribution.

On 26 Jul 2016 8:20 PM, "Josef Perktold" <notifications@github.com> wrote:
>
> for rvs the main useful method is the ppr. If that is not available, then
rvs will be slow because the default method needs to find the ppf
numerically from the cdf for each point.
>
> about the distribution:
> I'm always a bit skeptical when a distribution or name in statistics is
only used in one scientific field. It's not a reason to rule it out for
scipy.stats but maybe there is a more widely spread analog under a
different name. I didn't come up with anything in a brief search.
>
> based on the square in the distribution ("relativistic") and the
relationship to t and F distribution:
> Is this the same as F(1, 1) distribution?
> Or, maybe I'm thinking the wrong way and it is the square-root not the
square transformation of cauchy.

**Comment by innisfree** [comment]
Hello,

Sorry, you've misunderstand the wiki  :) the rhs indeed appears to be a
Cauchy with x -> x^2, but the BW is a distribution in x, so it's not
related trivially to the Cauchy distn.

Note that

p(y=x^0.5) = p (x) * 2y

The equation for the BW cannot be found by a simple change of variables of
a Cauchy, as the Jacobian factor isn't present.

**Comment by josef-pkt** [comment]
> It isn't related to the Cauchy by a parameter redefinition (though it is
similar) or any other well-known distn afaik.

I was thinking not of parameter redefinition/transformation, but as transformation of the random variable, based on the same wikipedia paragraph that @ev-br  quoted.

If it can be created by random variable transformation, then it would be a different way of getting relatively fast random variables.

However, I don't see yet how it matches up. The pdf has the same basic form as the cauchy, but because of the square E**2 or m**2, that value is positive, while Cauchy is defined also for negative values. So it might be related to a transformation of a truncated Cauchy, but the only truncated Cauchy that I can find in a quick search are truncated on both sides.

**Comment by josef-pkt** [comment]
@innisfree  What's the support of the distribution and restrictions on parameter space?
Those also need to go into `_argcheck`.

To answer earlier question: loc and scale are automatically added by the generic wrapper code, and can be ignored by the individual distributions which should be defined for the standard version with loc=0 and scale=1.

**Comment by innisfree** [comment]
The energy, 0 <=x <= inf. Mass >0 and width > 0.  There is a width -> 0
limit, a Dirac mentioned on the wiki.

**Comment by josef-pkt** [comment]
> The equation for the BW cannot be found by a simple change of variables of
a Cauchy, as the Jacobian factor isn't present.

I'm giving up. This most likely kills the transformation idea. At least I don't see a way to get a transformation.

**Comment by innisfree** [comment]
No worries, I had the same ideas when I first encountered the BW - the
relationship with the Cauchy is confusing.

This is genuinely extremely common in high-energy physics and I think my
code snippet just needs a bit of tweaking. I'll try to figure it out but
any hints would be appreciated.

**Comment by josef-pkt** [comment]
In general: open a PR and add the distribution to the list of distributions in the unit tests. Then the generic tests will check it, and fail if some obvious things are wrong.

one extra question based on the mentioning of Cauchy: Are the moments finite?  If not, then the moment methods should return nan, IIRC.

The more methods can be added with analytical expressions, the better will be the performance given that the generic methods are often computation intensive.

You can also check previous PRs that added a new distribution to see some of the issues that usually arise.

**Comment by ev-br** [comment]
I understand what that Wiki article says :-).
And indeed, as a function of the square of the 4-momentum, E^2, Breit-Wigner formula is *almost* a Cauchy distribution, the only difference being that the support of the distribution is  `[0, \inf]`, so it's a  [halfcauchy](http://docs.scipy.org/doc/scipy-0.18.0/reference/generated/scipy.stats.halfcauchy.html).

Can you sketch a use case where a distribution of `E^2` is not enough and you really need a distribution in terms of E itself?

**Comment by frederikfaye** [comment]
> I understand what that Wiki article says :-).
> And indeed, as a function of the square of the 4-momentum, E^2, Breit-Wigner formula is _almost_ a Cauchy distribution, the only difference being that the support of the distribution is `[0, \inf]`, so it's a [halfcauchy](http://docs.scipy.org/doc/scipy-0.18.0/reference/generated/scipy.stats.halfcauchy.html).

You can transform the halfcauchy into a rel. BW, as follows (forgive the TeX, I'd suggest copying it over to [quicklatex](https://quicklatex.com/)):

With
$$C(x;\beta,\gamma)=\frac{2/\pi}{1 + (x-\beta)^2/\gamma^2}=\gamma^2\frac{2/\pi}{(x-\beta)^2+ \gamma^2}$$ 
and
$$BW_r(E;M,\Gamma)=\frac{k}{(E^2-M^2)^2+ M^2\Gamma^2},$$ 
with $k=\frac{\sqrt{2}M\Gamma \alpha}{\sqrt{M^2+\alpha}}$ and $\alpha=\sqrt{M^2(M^2+\Gamma^2)}$, we have that 

$$C(x;\beta,\gamma) \times \frac{\sqrt{2}z}{\sqrt{1+z}} = BW_r(E;M,\Gamma),$$
where $z=\sqrt{1+\gamma^2/\beta^2}$
for $x=E^2, \beta=M^2, \gamma=M\Gamma$ with $x,\beta,\gamma>0$.

Note that someone should recalculate this before putting it into any docstrings, as I just did it by hand, and errors can always creep in. 

Will a `scipy.stats.rv_continuous` instance multiplied with a constant (is that even possible?) still be a valid `scipy.stats.rv_continuous` instance? Or how can this multiplication with $\frac{\sqrt{2}z}{\sqrt{1+z}}$ be carried out?

**Comment by andrewfowlie** [comment]
I think you're neglecting a Jacobian factor. Good luck, sorry I dont have time to contribute any more to this.

**Comment by josef-pkt** [comment]
> Since the quantity  is a physically meaningful energy which must be non-negative, and the parameters have physical meanings, it doesn't really make sense to consider this as a location-scale family.

I don't think it's the role of scipy distributions to provide a parameterization that has an application in a very narrow scientific field.

If the distribution is a nonlinear transformation of another distribution, then it makes sense to add it in a similar parameterization. 
loc-scale behavior will be similar to other distributions on R+.

However, practical use needs reparameterization, then this can be documented as in existing distributions, and for example loc will almost always be zero for R+ applications.

**Comment by ev-br** [comment]
In fairness, the fields of atomic, nuclear and high-energy physics are not *that* narrow, and if there is a reason a distribution in terms of the four-momentum, E^2, which is a half-cauchy, is not enough for their use-cases, my comments from 2016 still stand --- *if* there is a use-case, I'm not opposed, FWIW.

Assuming the use case is there, I also think that it's not a big deal to have it as a loc-scale family distribution even if non-default loc and scale have no physical meaning. 

As to the use case, maybe we can ask @HDembinski to weigh in as a high-energy physicist.

**Comment by josef-pkt** [comment]
Well, it sound narrow to me in the universe of natural, life and social sciences.

Although, some of those fields were very early python users and supporters.

Note, I think adding distributions base on nonlinear transformation is useful, scipy has many of them. So, adding Breit-Wigner is useful.
But it's not enough reason to deviate from the standard parameterization and make the distribution interpretable outside of high-energy physics.

(Aside, the wikipedia page on Breit-Wigner does not make sense to me because I don't understand anything of the physics context. The explanation in terms of nonlinear, square-root transformation is "obvious".)

**Comment by steppi** [comment]
> If the distribution is a nonlinear transformation of another distribution, then it makes sense to add it in a similar parameterization.
> loc-scale behavior will be similar to other distributions on R+.

Am I missing something? I don't think the relativistic Breit-Wigner is the square root of a half-cauchy random variable. Naively substituting $E^2$ for $x$ in the density function for a half-cauchy does give a reparametrization of the relativistic Breit-Wigner, but this doesn't account for how the probability measure changes under the transformation. See the hidden details section in my comment above. 

Perhaps I'm misunderstanding something, but my concern about treating it as loc-scale has to do with the `fit` method. Someone who wants to fit a relativistic Breit-Wigner to some data will almost certainly want to fit in a physically meaningful way. When I mentioned gh-15928 I had in mind this sub-issue

> * [Truncated distributions - beign able to lock actual truncation point when fitting  #9439](https://github.com/scipy/scipy/issues/9439) - Because contributors cannot easily override the `loc`/`scale` parameterization, it is essentially impossible for users to fit truncated distributions with fixed truncation bounds. The new distribution interface should fix this.

My understanding was that gh-15928 would be tackled anyway;  I wouldn't recommend tackling it solely for the sake of this one distribution. It may be that my reading of that subissue is wrong and it actually would be straightforward to fit a relativistic Breit-Wigner in a physically meaningful way while treating it as loc-scale though.

I'll leave it up to debate whether a distribution specific to particle-physics is notable enough to be worth including though. Again, I wouldn't recommend drastic changes to the distribution infrastructure just for the sake of this one distribution, but I think the changes discussed in gh-15928 are worth doing in their own right.

**Comment by josef-pkt** [comment]
Maybe I didn't read the previous discussion correctly.

I didn't check the math.

Again, I not against adding distributions if they are not available yet by reparameterization.
But distributions should be interpretable without specific science related context.
For example for distribution on R+, there are large number of articles for income distributions and (engineering) reliability.
Every once in a while a distribution gets reinvented with a new name.

**Comment by steppi** [comment]
> Maybe I didn't read the previous discussion correctly.
> 
> I didn't check the math.
> 
> Again, I not against adding distributions if they are not available yet by reparameterization. But distributions should be interpretable without specific science related context. For example for distribution on R+, there are large number of articles for income distributions and (engineering) reliability. Every once in a while a distribution gets reinvented with a new name.

I see. I don’t think this one is a reinvention. I thought it might possibly be part of or a transformation of something in the [generalized beta family](https://en.m.wikipedia.org/wiki/Generalized_beta_distribution), and played around with that a little, but it doesn’t seem to be the case. I understand not wanting to include distributions which only make sense in a specific scientific context, and this seems to fit that category. I guess it might make more sense as part of a more specialized library but I wouldn’t have any qualms including it if someone PRs a solid implementation and we hear from some members of the high energy physics community that they want it.

**Comment by mdhaber** [comment]
Thanks for checking this out @steppi. 

>  Someone who wants to fit a relativistic Breit-Wigner to some data will almost certainly want to fit in a physically meaningful way. 

Just a note that the user _can_ fix `loc` and `scale` (e.g. to `0` and `1`, respectively) before fitting, and it will behave exactly as though these parameters are not present. gh-9439 is only really a problem when `loc` and/or `scale` are free.

Two questions that I'm not sure are addressed above:

- Are any of the existing parameters equivalent to `loc` and `scale`? If it were to get `loc` and `scale`, we would prefer for it not to be over-parameterized (with redundant parameters). 
- What methods of the existing infrastructure could reasonably be implemented without original research? (e.g. I imagine that that `_pdf` would be implemented, but we probably would rely on the default `fit`. Are there others beside `_pdf` to override?)

**Comment by WarrenWeckesser** [comment]
If we define a new shape parameter $\rho = M/\Gamma$, the PDF becomes

$$
    f(E; \rho, \Gamma) = \frac{1}{\Gamma}\frac{k}{((E/\Gamma)^2 - \rho^2)^2 + \rho^2)}
$$

where

$$
    k = \frac{2\sqrt{2}\rho^2\sqrt{\rho^2 + 1}}{\pi\sqrt{\rho^2 + \rho\sqrt{\rho^2 + 1}}}
$$

Note that $k$ depends on the shape parameter $\rho$ only.

With this parametrization, $\Gamma$ is a scale. That is, $f(E, \rho, \Gamma) = f(E/\Gamma, \rho, 1)/\Gamma$.  If we implement the relativistic BW distribution with the current infrastructure, this is the parametrization we should use.

As for the location, this distribution would be in the same situation as many other distributions--we implement the location automatically, and most users will just ignore it, since the default `loc=0` is what they want.  Users have to be aware that if they fit this distribution to data, they will almost certainly want to fix the location to be 0.

The documentation should explain the simple change in parametrization between our implementation and wikipedia:

* From (M, Γ) to Scipy: shape = M/Γ, scale = Γ
* From SciPy to (M, Γ): M = shape * scale, Γ = scale

(I don't think any physicist working with the relativistic Breit-Wigner distribution should have any problem understanding this simple reparametrization.)

**Comment by josef-pkt** [comment]
I was trying to do some search for relativistic Breit-Wiegner, (as outsider to this literature)

I didn't find anything that describes it as a distribution.
https://link.springer.com/article/10.1140/epja/s10050-021-00641-2 looks like it has extra terms with E in the formula.

The physics literature seems to be more about the functional shape, and not about distributional properties.
https://arxiv.org/pdf/hep-ph/0603175.pdf plugs m**2 in formula for Cauchy, AFAICS.

Is there a reference for distributional properties?
for example, Are there any finite moments?

**Comment by steppi** [comment]
> If we define a new shape parameter ρ=M/Γ, the PDF becomes
> 
> f(E;ρ,Γ)=1Γk((E/Γ)2−ρ2)2+ρ2)
> 
> where
> 
> k=22ρ2ρ2+1πρ2+ρρ2+1
> 
> Note that k depends on the shape parameter ρ only.
> 
> With this parametrization, Γ is a scale. That is, f(E,ρ,Γ)=f(E/Γ,ρ,1)/Γ. If we implement the relativistic BW distribution with the current infrastructure, this is the parametrization we should use.
> 
> As for the location, this distribution would be in the same situation as many other distributions--we implement the location automatically, and most users will just ignore it, since the default `loc=0` is what they want. Users have to be aware that if they fit this distribution to data, they will almost certainly want to fix the location to be 0.
> 
> The documentation should explain the simple change in parametrization between our implementation and wikipedia:
> 
> * From (M, Γ) to SciPy: shape = M/Γ, scale = Γ
> * From SciPy to (M, Γ): M = shape * scale, Γ = scale
> 
> (I don't think any physicist working with the relativistic Breit-Wigner distribution should have any problem understanding this simple reparametrization.)

I was about to work this out but it looks like you beat me to it :) I agree with this choice of parameterization. 


> * What methods of the existing infrastructure could reasonably be implemented without original research? (e.g. I imagine that that `_pdf` would be implemented, but we probably would rely on the default `fit`.) Are there others besides `_pdf` to override?

There’s a (slightly complicated) closed formula for the CDF, so we might also want to override `_cdf`. Without research, I’m not sure about any of the others.

**Comment by steppi** [comment]
> I was trying to do some search for relativistic Breit-Wiegner, (as outsider to this literature)
> 
> I didn't find anything that describes it as a distribution. https://link.springer.com/article/10.1140/epja/s10050-021-00641-2 looks like it has extra terms with E in the formula.
> 
> The physics literature seems to be more about the functional shape, and not about distributional properties. https://arxiv.org/pdf/hep-ph/0603175.pdf plugs m**2 in formula for Cauchy, AFAICS.
> 
> Is there a reference for distributional properties? for example, Are there any finite moments?

I'm not sure, @andrewfowlie is a physicist who was interested in considering it as a distribution but he also said 

> It's very important in particle physics, though not discussed much as a
> statistical distribution.

so I think your overall impression is correct. I'm not sure if @andrewfowlie is still around to chime in. I could try asking some of my physicist friends.

**Comment by HDembinski** [comment]
Thanks @ev-br for pinging me. I think the discussion is going in a good direction and I am happy to fill in for @andrewfowlie as a liason for the high-energy physics community here. Note: I have written numba-accelerated versions of scipy.stats functions that are useful for particle physics in my library [numba-stats](https://github.com/HDembinski/numba-stats), because the standard versions in scipy are quite slow and I don't like to wait for my fits. I also include distributions in this library that are currently not in scipy but are useful to my field.

- I think having the relativistic Breit-Wigner in Scipy would be great, even if it is used only in high-energy physics. The same can be said for the [crystalball](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.crystalball.html) distribution, which was also added. Btw, we have more distributions that is specific to high-energy physics, like the double crystallball, the Hypathia distribution, and the Tsallis-Hagedorn distribution (a reparametrization of the q-exponential distribution). If scipy.stats is redesigned, you could put all those into a submodule `physics` . 
- We use the relativistic Breit-Wigner solely for fitting. We are not interested in its moments or any properties of the distribution itself, that's why you cannot find anything about that. Being able to sample from the relativistic Breit-Wigner would be very useful, however, besides the fitting. I am working on an analysis right now, where we needed that.

**Comment by steppi** [comment]
Thanks @HDembinski!  While you're here, do you know if the mass of a resonance $M$ divided by its decay width $\Gamma$ has a clearly stated physical meaning or a name that could be referred to in the docs?  @WarrenWeckesser gave a nice shape-scale parametrization in terms of $\rho = M / \Gamma$ and $\Gamma$, with $\Gamma$ playing the role of the scale parameter, and this is most likely the parametrization that would be used.

@mdhaber, though physicists aren't interested in the moments, another thing we could override is `_stats`. There are closed forms for the first and second moments. The higher moments are undefined. 


The mean is

$$ k \left(\frac{\pi}{2} \frac{\Gamma^2}{2\rho} + \tan^{-1}(\rho)\frac{\Gamma^2}{2\rho}\right) $$

where 

$$
    k = \frac{2\sqrt{2}\rho^2\sqrt{\rho^2 + 1}}{\pi\sqrt{\rho^2 + \rho\sqrt{\rho^2 + 1}}}
$$

is the normalizing constant seen above. This is simple enough. I haven't worked out the second moment but it's straightforward to do in principle.

**Comment by HDembinski** [comment]
@steppi I haven't checked your calculation, but the mean looks very complicated. Intuitively, I expect a simple result, the mean should be $\rho \Gamma$. The distribution is symmetric and peaks at $\rho \Gamma$, no?

**Comment by steppi** [comment]
> @steppi I haven't checked your calculation, but the mean looks very complicated. Intuitively, I expect a simple result, the mean should be ρΓ. The distribution is symmetric and peaks at ρΓ, no?
> 
> Ah, probably my intuition is only correct in the limit ρ→∞.

Right, the peak is at $\rho \Gamma$, but it's not symmetric about the peak. 

The mean is

$$
    \mu = \int_{0}^{\infty} \frac{1}{\Gamma}\frac{kE}{((E/\Gamma)^2 - \rho^2)^2 + \rho^2)}
$$

which can be evaluated with the substitution $y = E^2$.

The second raw moment is

$$
   \int_{0}^{\infty} \frac{1}{\Gamma}\frac{kE^2}{((E/\Gamma)^2 - \rho^2)^2 + \rho^2)}
$$

which can be evaluated with integration by parts.

The complexity of the formula for the mean comes from the truncation at $E = 0$. Extending to the whole real line, you get a distribution symmetric about zero with peaks at $\rho \Gamma$ and $-\rho \Gamma$ and the mean is simply 0.

**Comment by WarrenWeckesser** [comment]
@steppi, the terms $\Gamma^2$ in your expression for the mean should be just $\Gamma$.  Also note that if we actually implement this distribution, we only need to implement the calculation for $\Gamma = 1$; the code takes care of shifting and scaling the result based on the `loc` and `scale` arguments provided by the user.

**Comment by steppi** [comment]
> @steppi, the terms 
> Γ
> 2
>  in your expression for the mean should be just 
> Γ
> . Also note that if we actually implement this distribution, we only need to implement the calculation for 
> Γ
> =
> 1
> ; the code takes care of shifting and scaling the result based on the `loc` and `scale` arguments provided by the user.

Ah right. I lost the $1/\Gamma$ factor in front when I worked out the integral. Thanks and sorry about that.

**Comment by steppi** [comment]
I put together a rough relativistic breit-wigner implementation. It’s not ready to PR and just lives on a branch on my fork [here](https://github.com/steppi/scipy/blob/878f5bbcc832bc0a3eb9503751d47edc423f231e/scipy/stats/_continuous_distns.py#L10281). It still needs some more work on tests and docs.

I also want to TeX up the derivations of the cdf and moments before submitting a PR to make review easier. At some point I’ll make a post on the mailing list. If it doesn’t get in I’ll just try to find another home for it.

**Comment by HDembinski** [comment]
@steppi Please consider adding it to [numba-stats](https://github.com/HDembinski/numba-stats) if it is not accepted by scipy, although I don't see why it should be rejected.

**Comment by mdhaber** [comment]
Whenever you're ready, @steppi, I'd be happy to take a look.
