### ISSUE TITLE
circmean() changed behaviour from 0.17 to 0.18

### ISSUE THREAD

**Issue by evertrol** [scipy/scipy#6420]
[Commit 6f799a807bde2b4391857 ](https://github.com/scipy/scipy/commit/6f799a807bde2b4391857136fd3cbf87321710f1) appears to have changed the behaviour of `scipy.stats.circmean()`.
Yet I can't find this documented anywhere.
Is this correct?

For example, using the following code
```python
import numpy as np
from scipy.stats import circmean
print(circmean(np.arange(-2, 0, 0.1), np.pi, -np.pi),
      circmean(np.arange(0, 2, 0.1), np.pi, -np.pi))
```

produces different results before and after this commit:

```
# master
# -1.05 -5.33318530718

# git checkout 6f799a807bde2b4391857
# -1.05 -5.33318530718

# git checkout 4f9be64594970103e245cf5
# -1.05 0.95
```

**Comment by zym1010** [comment]
by checking the code, looks that there should be an additional step to make all values within range `[0, 2*pi]` missing...

**Comment by pv** [comment]
@larsmans, @kleskjr: ping

**Comment by pv** [comment]
There's no test checking that the low= keyword functions correctly, so 
this bug was able to slip by.

**Comment by zym1010** [comment]
@pv thanks. this is just my understanding of how `circmean` works.

1. `samples` is assumed to lie in `[low, high]`, and in the first step, `_circfuncs_common` is used to s cale and shift these values to `[0, 2*pi]`.
2. compute circular mean of scaled and shifted samples.
3. transform them back.

Currently, steps 2&3 are combined together incorrectly, since `arctan2` produces values within `[-pi, pi]`.

Previously, `mask` in the code is to make negative values positive. Now, it's used to mask undefined values for `arctan2`.

**Comment by kleskjr** [comment]
I'm sorry for introducing this bug!
This evening (CET) I will try to clear up the mess.

I have a question concerning the normalization of values:

What should be the default behaviour in case `samples` is not in `[low, high]` range?
In particular, the example from @zym1010 : `circmean(np.linspace(-0.2, 0, 10), 2*pi, 0)`.
Should the values be normalised anyway assuming modulo of `2*pi`? In this case `ang  = 2*pi + np.linspace(-0.2, 0, 10)`. Or should we expect some other behaviour: `nan` values, an error, or a warning?

**Comment by zym1010** [comment]
@kleskjr I guess for normalization, you can simply leave it as is, and maybe later on some keyword arguments such as `strict` can be added to `_circfuncs_common` to throw out some exception in case `samples` is not in `[low, high]`.

Also, I think maybe such check is not needed, as `[low, high]` only specifies how to to modulo on `samples`, and `samples` will be automatically processed as the modulo, due to use of `sin` and `cos`.

**Comment by kleskjr** [comment]
Tomorrow I will add some additional test(s) to cover the last misbehaviour.
