### ISSUE TITLE
scipy.stats.mstats.mode modifies input

### ISSUE THREAD

**Issue by impact27** [scipy/scipy#6428]
The first argument is modified when I compute the mode of an image with dtype 'float'. (Integers are fine)
```
from matplotlib.pyplot import figure, imshow, show
import numpy as np
from scipy.stats.mstats import mode
im=np.zeros((100,100),dtype='float')
im[:50,:]+=1
im[:,:50]+=1
imshow(im)
show()
a=mode(im,None)
figure()
imshow(im)
```
![screen shot 2016-07-28 at 15 40 45](https://cloud.githubusercontent.com/assets/6740194/17216744/c2b98178-54d9-11e6-9dd2-bc96695b85ab.png)

**Comment by WarrenWeckesser** [comment]
Thanks for bug report and the code to produce the problem.

A work-around that avoids the problem is to use `scipy.stats.mode` (instead of `scipy.stats.mstats.mode`)--unless you have a specific reason for using the `mstats` version.

The problem is actually in the function `mstats.find_repeats()` that is called by `mstats.mode()`.  Here's a simple example in which `find_repeats()` modifies its input:

```
In [163]: a
Out[163]: array([ 5.,  4.,  3.,  2.,  1.])

In [164]: find_repeats(a.ravel())
Out[164]: (array([], dtype=float64), array([], dtype=int64))

In [165]: a
Out[165]: array([ 1.,  2.,  3.,  4.,  5.])
```

Here's the definition of `find_repeats()` (without the docstring):

```
def find_repeats(arr):
    # Make sure we get a copy. ma.compressed promises a "new array", but can
    # actually return a reference.
    compr = np.asarray(ma.compressed(arr), dtype=np.float64)
    if compr is arr or compr.base is arr:
        compr = compr.copy()
    return _find_repeats(compr)
```

The private function `_find_repeats()` is documented as modifying its input, so the code in `find_repeats()` tries to ensure that a copy is made before calling `_find_repeats()`.  The problem is the existing test is not sufficient.  When the argument to `find_repeats()` is itself a view of another array (such as one created by the `.ravel()` method), the test in `find_repeats()` is False, and a copy is not made.

**Comment by innisfree** [comment]
What's the solution? Make a better test on `compr`?  Always do `compr = compr.copy()` without a test (slow)? Fix `ma.compressed` which is the source of the behaviour?
