### ISSUE TITLE
Using Qhull for halfspace intersection : segfault

### ISSUE THREAD

**Issue by haudren** [scipy/scipy#6441]
As the title says, Qhull support computing halfspace intersections via its `H` option or the dedicated `qhalf`program.

One should give a list of halfspaces of the form:
> Ax + b <= 0

And an interior (feasible) point. Then, Qhull will compute all the vertices forming this polyhedron. Unfortunately, this is bugged for now, even for [a simple example](https://gist.github.com/haudren/8546d3866480aadeaa757dac14f810f2)

I will investigate a bit, but the program crashes when calling Qhull.get_simplex_facet_array(), meaning that in `H` mode, some assumptions are not valid.

At a quick glance, I'd say this is related to the fact that get_simplex_facet_array() uses `self.ndim` and `self.numpoints` but those are not the dimensions of the input array in `H` mode.

**Comment by haudren** [comment]
Ok, I started working on this on my [fork](https://github.com/haudren/scipy/tree/topic/qhullHalfspaces). It appears that correctly setting `ndim` and `num_points` solves the issue. Indeed, the above test now passes.

Unfortunately, one more point needs to be dealt with. Whenever working with halfspaces, Qhull works in the dual space of the original problem. Meaning that:
- Neither points nor halfspaces correspond to the input
- The real intersection points have to be computed separately (see `qhull/io.c:1239`) using the simple formula:


My question is thus, what is the best way to introduce this ?

**Comment by pv** [comment]
The half-space computation probably should be considered a separate 
"major mode" similar to Delaunay. (That ConvexHull accepts the H flags 
at all is probably a bug.)
.
You can either add a new method to the _QHull class for pulling out the 
half-space information, or adjust one of the existing ones to suit this, 
if only small changes are needed. E.g. via adding a new keyword argument 
`half_space=False` that toggles between modes.
.
The `H` flags should not be passed via qhull_options, since it's a major 
mode. I haven't used this mode, but perhaps the qhull API has a way to 
pass in the points in an array rather than having to go via strings.

**Comment by haudren** [comment]
After tinkering with it a bit, I think a major mode will be necessary: in halfspace mode, Qhull does not compute at all the triangulation of the intersections, and I am afraid we will encounter *a lot* of confusion by putting different things in the same container.

I'll look into it and try to submit a patch sometime this week!

For the second option, it seems that it is possible when using a file (you can specify the interior point first, then specify the halfspaces), so I'll check which method they call to set it.

**Comment by ev-br** [comment]
For completeness, here's the test case from the OP's gist:

```
n [16]: A = np.array(([[-1, 0, 0],
   ....:                [0, -1, 0],
   ....:                [1, 0, -1],
   ....:                [0, 1, -1]]))

In [17]: 

In [17]: hull = spatial.ConvexHull(A, qhull_options='H0.5,0.5')
Segmentation fault (core dumped)
```
