### ISSUE TITLE
a slightly wrong documentation in scipy.stats.chi2

### ISSUE THREAD

**Issue by kuti17** [scipy/scipy#6461]
In [http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2.html#scipy.stats.chi2](url),

The probability density function for chi2 is written as:

> chi2.pdf(x, df) = 1 / (2* gamma(df/2)) * (x/2)**(df/2-1) * exp(-x/2)

Yet, the form should be written as:

> chi2.pdf(x, df) = 1 / (2** (df/2) * gamma(df/2)) * (x/2)**(df/2-1) * exp(-x/2)

Refer to [https://en.wikipedia.org/wiki/Chi-squared_distribution](url)

**Comment by ev-br** [comment]
The formula seems to be the same and it seems to correspond to what `chi2.pdf` actually computes. The latter is correct:

```
In [1]: from scipy.integrate import quad

In [2]: from scipy.stats import chi2

In [3]: df = 5

In [4]: quad(lambda x: chi2.pdf(x, df), 0, float('inf'))
Out[4]: (0.9999999999977732, 7.853011432973038e-09)

In [5]: quad(lambda x: chi2.pdf(x, 8), 0, float('inf'))
Out[5]: (1.0, 3.288731217520841e-10)
```

A formula copy-pasted from the docsting seems to work fine too. I *think* the confusion might be with a factor of 2 which comes from `(x/2)**(df/2-1)` in scipy but `x**(df/2-1)` in wikipedia.

I'll close this issue since I don't believe there is a problem. Feel free to keep discussing though.
