### ISSUE TITLE
errors with scipy.invwishart.logpdf when passing list of values

### ISSUE THREAD

**Issue by idc9** [scipy/scipy#6474]
I found two errors when trying to compute the logpdf for a list of values for invwishart. I am using version 0.18.0 of scipy. Note that logpdf works fine when evaluated at a single value, but breaks when evaluated at multiple values.
# First error

```
values = np.asarray([[[  1.30114637,  -3.38878797], [ -3.38878797,  10.48343641]], 
          [[  1,  0], [ 0,  1]]])
stats.invwishart.logpdf(values, df=10, scale=np.identity(2))
```

returns 

> LinAlgError: 2-th leading minor not positive definite

The error is happening in the call to _cho_inv_batch(x_inv) on line 2294. 

The transpose used to create x_inv

```
x_inv = np.copy(x).T
```

some how messes up permuting the matrices in the list (see what happens when you run `values.T`  from the above example). 

Furthremore, the shape of the x argument is (number of values, dim, dim) but the code assumes that the shape is (dim, dim, number of values).  The following changes might fix this problem
- change `x.shape[-1]` to `x.shape[0]` in lines 2290, 2297 and 2299 
- remove `.T` in line 2292 (not sure why transpose is needed since x should be symmetric)
- change `x[:,:,i]` to `x[i,:,:]` in line 2300

The problem also might go away if x is given in the assumed format.
# Second error

```
value = [np.identity(3), np.identity(3)]
stats.invwishart.logpdf(value, df=10, scale=np.identity(3))
```

gives the following error message

> ValueError: Quantiles must be square in the first two dimensions if they are three dimensional, but x.shape = (2, 3, 3).

I suspect the issue is coming from the _process_quantiles function at line 1566. The number of values in the list being passed in is the **first** entry in np.shape(x), not the **third** entry. i.e.

```
np.asarray([np.identity(3), np.identity(3)]).shape
```

returns 

> (2, 3, 3)

It's very possible both these errors are coming from the same place.

**Comment by ev-br** [comment]
@ChadFulton thoughts?

**Comment by ChadFulton** [comment]
Sorry I didn't get to this earlier. I guess this can either be considered a bug or considered a documentation error. The behavior is intended (and also affects `scipy.stats.wishart`) in the sense that I had intended each quantile matrix to be specified in the first two dimensions.

But I now realize that that the phrase "Quantiles, with the last axis of x denoting the components" has a different meaning in `scipy.stats.multivariate_normal.logpdf` - I'd interpreted the words "components" differently (incorrectly).

So to make it consistent with `scipy.stats.multivariate_normal` I guess we can change the behavior, but unfortunately, that would now be backwards incompatible. Otherwise, we can change the documentation.

**Comment by ChadFulton** [comment]
So to be clear with what I mean, both errors above disappear if the input arrays are simply transposed to put the 0th dimension last.

e.g.:

```python
values = np.asarray([[[  1.30114637,  -3.38878797], [ -3.38878797,  10.48343641]], 
          [[  1,  0], [ 0,  1]]]).T
values = np.transpose(values, (1, 2, 0))
stats.invwishart.logpdf(values, df=10, scale=np.identity(2))
```

yields `[-16.33805121 -14.13562715]`

and

```python
value = [np.identity(3), np.identity(3)]
value = np.transpose(value, (1, 2, 0))
stats.invwishart.logpdf(value, df=10, scale=np.identity(3))
```

yields `array([-21.03785241, -21.03785241])`

**Comment by mdhaber** [comment]
Tracking in gh-16278, so closing this one.
