### ISSUE TITLE
optimize.least_squares retains only real part of the initial point

### ISSUE THREAD

**Issue by dimkab** [scipy/scipy#6506]
When calling least_squares() with a complex initial point, the first evaluation of the function/jacobian is passed only the real part. Apparently this has to do with the call to prepare_bounds().

**Comment by nmayorov** [comment]
@dimkab I'm afraid computations in complex domain weren't considered when implementing this function. I suggest you to reformulate the problem using only real numbers.

As for adding support for complex domain --- I'm not sure it's a good idea, because it's already quite convoluted and further complications are probably undesirable. But you are welcome to consider it and maybe send a pull request.

**Comment by ev-br** [comment]
It should probably check the dtype of the initial point and raise.

**Comment by person142** [comment]
Extending to complex arguments seems unnecessary since if one wanted to minimize e.g.

```python
>>> def f(z):
...     return np.array([z.real - 0.5, z.imag - 0.5])
...
```

with `0 <= Re(z), Im(z) <= 1` then one could do

```python
>>> from scipy.optimize import least_squares
>>> least_squares(lambda x: f(x[0] + 1j*x[1]), (0.1, 0.1), bounds=([0, 0], [1, 1]))
 active_mask: array([0, 0])
        cost: 5.4919047922168663e-25
         fun: array([ -7.41073869e-13,  -7.41073869e-13])
        grad: array([ -7.41073869e-13,  -7.41073869e-13])
         jac: array([[ 1.,  0.],
       [ 0.,  1.]])
     message: '`gtol` termination condition is satisfied.'
        nfev: 7
        njev: 7
  optimality: 3.7053693446919519e-13
      status: 1
     success: True
           x: array([ 0.5,  0.5])
```

With https://github.com/scipy/scipy/pull/6704 in ISTM that it would be reasonable to add an example of "realifying" the residuals to the docs (maybe @mp4096 would be interested?) and then calling this issue done.

**Comment by mp4096** [comment]
Yep, I can try to. Should I add an example to the docstring/reference guide or to the tutorial?

**Comment by ev-br** [comment]
Sorry, fat fingered

**Comment by person142** [comment]
Docstring maybe? I could see it either way though, so I will yield to a strong opinion.

An aside: it would probably be more natural to write the above example as

```python
>>> def f(z):
...     return z - (0.5 + 0.5j)
...
>>> def f_wrap(x):
...     fx = f(x[0] + 1j*x[1])
...     return np.array([fx.real, fx.imag])
...
>>> from scipy.optimize import least_squares
>>> least_squares(f_wrap, (0.1, 0.1), bounds=([0, 0], [1, 1]))
```
just so that it's also evident how one would break up complex residuals in addition to complex arguments.

**Comment by mp4096** [comment]
Let it be docstring.

Should we also be more precise in the description of `f(x)`? I.e.

> Given the residuals f(x) (an m-dimensional __real__ function of n real variables)

instead of 

> Given the residuals f(x) (an m-dimensional function of n real variables)

**Comment by person142** [comment]
Seems reasonable to me.

**Comment by mp4096** [comment]
About the wording here:

> Given the residuals f(x) (an m-dimensional real function of n real variables)

I'm now sure it's really appropriate, since it seems to me that the loss functions are not able to handle complex residuals.

**Comment by mp4096** [comment]
@person142 I reused your example in #6731, many thanks! :smile:

**Comment by person142** [comment]
Ok, #6731 is in, so I think we're done here. Thanks @dimkab for the report and @mp4096 for the fixes!
