### ISSUE TITLE
Incorrect implementation of np.multiply for csr_matrix

### ISSUE THREAD

**Issue by pwelke** [scipy/scipy#6508]
It seems that sparse matrices do not implement elementwise multiplication correctly.

`
import numpy as np
from scipy.sparse import csr_matrix

print np.version.full_version
print np.version.git_revision
print '\n'

test = np.array([[1,1],[2,2],[3,3]])
sparse = csr_matrix(test)

print np.multiply(test, test)
print np.multiply(sparse, sparse)
`

produces the output

`
1.8.2
4563730a2d036307f1b67b2856d749aabdd8d546

[[1 1]
 [4 4]
 [9 9]]

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-e14d069a37dd> in <module>()
     11 
     12 print np.multiply(test, test)
---> 13 print np.multiply(sparse, sparse)

/usr/lib/python2.7/dist-packages/scipy/sparse/base.pyc in __mul__(self, other)
    306         if issparse(other):
    307             if self.shape[1] != other.shape[0]:
--> 308                 raise ValueError('dimension mismatch')
    309             return self._mul_sparse_matrix(other)
    310 

ValueError: dimension mismatch
`

**Comment by pv** [comment]
There's actually *no* implementation of np.multiply for sparse matrices.
Use the `.multiply()` method instead.
.
You get the behavior corresponding to: (i) cast both elements to
ndarrays, (ii) since sparse matrices are not recognized by Numpy, the
cast produces 1-element object arrays, (iii) multiply for object arrays
means Python's native `*`, (iv) native `*` for sparse matrices is matrix
multiply.
