### ISSUE TITLE
Differential_evolution maxiter causing memory overflow

### ISSUE THREAD

**Issue by weinbe58** [scipy/scipy#6559]
Hi,

In the DifferentialEvolutionSolver I'm getting an error if I make my maxiter too large. Its becuase in the `solve` (line 500 of _differentialevolution.py) method you are using `range(1, self.maxiter + 1) `. I think to avoid this all one would have to do is change `range` to `xrange`

Thanks

**Comment by andyfaff** [comment]
xrange is not present in Py3. What value are you using for maxiter? Could
you provide a small self contained problem that demonstrates the issue?

**Comment by person142** [comment]
`xrange` is in six though--`from scipy._lib.six import xrange`.

**Comment by andyfaff** [comment]
Ok, so fired up Py2 (been a long while since I did that!), and used a large number for `maxiter`. True to form the minimisation ground to a halt because of memory issues with a `range` call.
I guess I hadn't foreseen that really large numbers would be used for maxiter (I've never used more than maxiter ~ 1000).
I'll submit a PR with the change.

**Comment by andyfaff** [comment]
#6567 fixes this.
