### ISSUE TITLE
negative binomial survival function is imprecise

### ISSUE THREAD

**Issue by williamslab** [scipy/scipy#6682]
The nbinom.sf() function is not precise for small probabilities. It looks as though this falls back on computing 1 - nbinom.cdf() since (though this may be wrong as I don't know Python well) the nbinom_gen class does not contain an _sf() function. Instead it has an _sf_skip() function with the comment:

`# skip because special.nbdtrc doesn't work for 0<n<1`

But it seems better to separately deal with 0 < n < 1 and use the high precision special.nbdtrc() function for other cases.

The following illustrates the difference in precision between the two methods:

```
>>> scipy.stats.nbinom.sf(250, 50, 32./63.)
1.1102230246251565e-16
>>> scipy.special.nbdtrc(250, 50, 32./63.)
1.460458510976169e-35
```

In R, we have:

```
> pnbinom(250, 50, 32/63, lower.tail=FALSE)
[1] 1.460459e-35
```

**Comment by josef-pkt** [comment]
as background: the `_skip` were added in my initial round of bugfixes where the focus was on big bugs and 1e-16 versus 1e-35 seemed small. I thought those were gone by now with the improvements in stats and special since then.

Based on a quick try: nbdtr and nbdtrc do not work for real (float) `k`

```
>>> special.nbdtrc(100, 50, 32./63.)
5.5002943637841218e-06
>>> special.nbdtrc(100, 50.5, 32./63.)
5.5002943637841218e-06
>>> stats.nbinom.sf(100, 50, 32./63.)
5.5002943637472157e-06
>>> stats.nbinom.sf(100, 50.5, 32./63.)
6.8807151289984603e-06
```

I don't remember why I wanted this for cdf and sf. It is useful for pmf because we can use it to model positive random variables that are on a continuous domain and not just integers..

**Comment by segasai** [comment]
It looks like the survival function can be computed precisely using the incomplete beta function ( scipy.special.betainc)

For me this 
```
    good=scipy.special.betainc(np.floor(x)+1,n,1-p)
```
gives much more precise tail probabilities .
```
    bad=scipy.stats.nbinom(n,p).sf(x)                                                          
```

**Comment by kevinjacobs-progenity** [comment]
The only thing wrong with nbdtrc is that `n` is passed in as an integer.
```c
    double dk, dn;
    /* checks args */
    dk = k + 1;
    dn = n;
    return (incbet(dk, dn, 1.0 - p));
```
Thus the proposed fix to call `betainc` is both correct and appropriate:
```python
    def _sf_skip(self, x, n, p):
        # do not use special.nbdtrc because it requires integer n
        k = floor(x)
        return special.betainc(k+1, n, 1-p)
```
Somebody realized this was the case in `_cdf`, since it already avoids `special.nbdtr` for presumably the same reason:
```python
    def _cdf(self, x, n, p):
        k = floor(x)
        return special.betainc(n, k+1, p)
```
I'm happy to submit a PR, if that will get the ball rolling on the needed fix.

Tangentially, would a reparameterized version of `stats.nbinom` be accepted?  It would be convenient to have a variant of the `nbinom` distribution, except reparameterize from (n, p) to (μ, α) where n=1/α and p=1/(1 + αμ)?  This is the form commonly used in the generalized linear models literature and is usually called the NB2 distribution (since Var[X ~ NB2] = μ + αμ<sup>2</sup>).  There is also an NB1 (Var[X ~ NB2] = μ + αμ) distribution and an NB(Q) distribution that generalizes the exponent of the overdispersion component of the variance (Var[X ~ NB(Q)] = μ + αμ<sup>Q</sup>).

**Comment by mdhaber** [comment]
@kevinjacobs-progenity 
> Tangentially, would a reparameterized version of stats.nbinom be accepted?

Probably not. This has been suggested before (e.g. gh-4538), but we have typically avoided reparameterizations. gh-13292 notes the preferred reparameterization you mentioned.
