### ISSUE TITLE
ENH: optimize.basinhopping: call an acceptance test before local search

### ISSUE THREAD

**Issue by bayesfactor** [scipy/scipy#6688]
I believe that the accept_test function should be called by basinhopping before evaluating the function. The reason is that if there are constraints on the parameters, it would be more efficient to reject a hop before evaluating the function rather than afterwards. Furthermore, if a function cannot be evaluated with some combinations of parameters (returns inf, NaN, throws an error, etc), then we shouldn't call the basinhopping function.

E.g. the below function should be find an optimum around (2,4), but instead it returns an optimum of -inf at (1,1), which isn't a sensible answer.

```python
from math import tanh

class MyBounds2(object):
  def **init**(self):
    self.xmax=np.array([6,6])
    self.xmin=np.array([1,1])
  def **call**(self,**kwargs):
    x=kwargs["x_new"]
    print(x)
    constraint=bool(x.sum()<6)
    print(constraint)
    tmax=bool(np.all(x<=self.xmax))
    tmin=bool(np.all(x>=self.xmin))
    return tmax and tmin and constraint

def f(x):
    ret= -(f1(x[0]) + f2(x[1]))  # -ve sign for maximization
    print(x[0],x[1],ret)
    return(ret)

def f1(x):
    return tanh(x)

def f2(x):
    return (10 *\* (0.2 \* x))

def StackOFEx():
  from scipy.optimize import basinhopping  
  # Starting point
  x0 = [1., 1.]

  minimizer_kwargs = dict(method="L-BFGS-B")

  bounds=MyBounds2()
  result = basinhopping(f,
                        x0,
                        minimizer_kwargs=minimizer_kwargs,
                        niter=200,accept_test=bounds)

  print("global max: x = [%.4f, %.4f], f(x0) = %.4f" % (result.x[0], result.x[1], result.fun))
```

**Comment by endolith** [comment]
I don't think this is correct.  See https://github.com/scipy/scipy/pull/7819#issuecomment-326719547  The accept_test is for rejecting the function value of the local minima and whether it is higher in energy than the last local minima.  It's not for rejecting the x value of the step itself.

**Comment by endolith** [comment]
>  if there are constraints on the parameters, it would be more efficient to reject a hop before evaluating the function rather than afterwards.

Even if the starting point violates the constraints, the minimization can still converge to a point on the edge of the constraints that is valid. It's conceivable that there could be cases where this works better than starting inside the constraints?

> Furthermore, if a function cannot be evaluated with some combinations of parameters (returns inf, NaN, throws an error, etc), then we shouldn't call the basinhopping function.

Ah, you mean a function that _can't_ be evaluated outside the constraints.  The function could be wrapped so that it immediately returns inf when inputs are out of bounds?  I'm not sure if that's the job of basinhopping() or the job of the person writing the function to be minimized?  

Also I would hope the local minimizer just fails immediately as soon as it sees a NaN or error in the function evaluation.

> but instead it returns an optimum of -inf at (1,1), which isn't a sensible answer.

You're giving a boundary to basinhopping for whether it should accept the step or not, but you're not giving any boundaries to the local minimizer, so it's just going to run down the hill forever.  "L-BFGS-B" doesn't support triangular constraints anyway, only box boundaries.  You'd need to use COBYLA and express the constraint as a function instead of a class. 

`result.success` is `False` and `result.message` is `ABNORMAL_TERMINATION_IN_LNSRCH`, so it didn't actually find a global minimum at all.

![figure_1-24](https://user-images.githubusercontent.com/58611/31863721-ae401a14-b71f-11e7-9361-bc8eec914b6a.png)

**Comment by endolith** [comment]
This works:

```
constraints = {'type': 'ineq', 'fun': lambda x: 6 - x.sum()}
bounds = ((1, 6), (1, 6))

minimizer_kwargs = {'constraints':constraints, 'bounds':bounds}
result = basinhopping(f, x0, minimizer_kwargs=minimizer_kwargs,
                      niter=200)
```

`global max: x = [1.0000, 5.0000], f(x0) = -10.7616`

Though this problem doesn't require basinhopping at all.  Even this works:

```
minimize(f, (100, 100), bounds=bounds, constraints=constraints)
Out[49]: 
     fun: -10.761594155956233
     jac: array([-0.42 , -4.605])
 message: 'Optimization terminated successfully.'
    nfev: 8
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([ 1.,  5.])
```

**Comment by fuglede** [comment]
>  It's not for rejecting the x value of the step itself.

In the final part of [the documentation of `basinhopping`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.basinhopping.html), the parameter `accept_test` is used to define bounds (and of course, in that example, it fails to actually do so as defining `xmin = [0, 0]` will show), so either `accept_test` is intended for defining bounds (at which point it's buggy), or the documentation is straight out incorrect.

**Comment by memeplex** [comment]
The documentation is indeed confusing or wrong. My target function can't take values outside certain set but it's still being called with invalid input no matter that both `accept_test` and the underlying minimizer bounds and constraints are correctly set.

> The function could be wrapped so that it immediately returns inf when inputs are out of bounds? 

If I do this the underlying minimizer will fail because it's still being called with values outside the valid set as initial values.

**Comment by endolith** [comment]
It's still there:

> Now let’s implement bounds on the problem using a custom accept_test:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.basinhopping.html

**Comment by mdhaber** [comment]
In summary, there are two parts to this:

1. Documentation: The last example of `basinhopping` is not ideal because it suggests that a good way of adding bound constraints is with `accept_test`. `accept_test` can indeed prevent `basinhopping` from *accept*ing a step that brings it to the bottom of a basin outside of the bounds, but it would be much better to show how `minimizer_kwargs` with `bounds` can be used to add bound constraints to the local search. A more illustrative example for `accept_test` would be to force _all_ steps to be accepted, but it would be even better to do some research into other reasonable acceptance criteria in the literature and implement one of those.

2. Enhancement or Documentation: The OP asks for `basinhopping` to perform an acceptance test before local search happens. That is not part of the original basinhopping algorithm, so we should not change the algorithm to use `accept_test` for this purpose, at least not by default. Note that users can already achieve something like this (albeit maybe not quite as conveniently) using `take_step`. However, note that minimization algorithms cannot always guarantee that constraints are strictly satisfied in every iteration, even if they are strictly satisfied with the initial guess (simple `bounds` may be an exception). `basinhopping` can't do much to change that. So I'm not really in favor of this enhancement if it requires a change to the API, personally. @bayesfactor would you consider this part resolved if we were to give an example of how `take_step` can be used for this purpose?

I would be happy to review PRs that make these documentation improvements.

**Comment by endolith** [comment]
> so either `accept_test` is intended for defining bounds (at which point it's buggy), or the documentation is straight out incorrect.

I looked through the history and that example was added along with everything else by the original author, @js850 :

https://github.com/scipy/scipy/commit/f2f3dba1f995c013ab822472971b382809095be6#diff-1a5fe854473be4154e6bcdb3fa5e64d537bfd425924487cfa6c7c89b88f4081dR548

🤷

**Comment by mdhaber** [comment]
Perhaps it was their intent, but they did not think through the consequences completely. Whatever the intent, it is not a good way for defining bounds and I'd suggest that it be changed as outlined [above](https://github.com/scipy/scipy/issues/6688#issuecomment-1286217671).

**Comment by js850** [comment]
accept_test _can_ be used to implement bounds, but it is very wasteful, and will raise errors in many cases where the objective function is undefined outside of the bounds.

I agree the documentation should be improved, as @mdhaber says bounds should be introduced both in take_step and in the local minimizer.  Here is a stack overflow answer I gave a while back showing this: https://stackoverflow.com/a/21967888/3307093.  Maybe that can be used as an example.

Bounds were not forefront in my mind when I implemented this as I primarily worked with unbounded functions.  I would also advocate for simplifying basinhopping with bounds.

A complication is that basinhopping treats the local optimizer as a black box and I don't think each optimizer is uniform in how they do bounding.

I would suggest at the very least making it simpler for take_step to respect bounds.  e.g. pass in a `bounds` parameter which will be used by take_step.

**Comment by mdhaber** [comment]
Ah, thanks for dropping by @js850! I thought I've mention that I've found the code quite easy to navigate. Thanks for that!

> I would suggest at the very least making it simpler for take_step to respect bounds

It is fine to keep this issue open with that request, if need be. But let's see if @bayesfactor would be happy with a doc-only solution. It sounds quite easy already for the user to generate a random step that satisfies their constraints, especially since `basinhopping` provides a step size, so I'm not convinced that an API change is needed. In any case, I'd be more interested in reviewing doc enhancements to resolve this issue. (Of course, there is another maintainer who is in favor of doing something more substantial and willing to review that, that is fine, too.)

**Comment by js850** [comment]
Thanks!

> I would suggest at the very least making it simpler for take_step to respect bounds

I meant to say this would be a nice addition at some point.  It doesn't have to be part of this change :)

**Comment by bayesfactor** [comment]
I would accept a documentation change clarifying `accept_test`, especially the [last example](https://github.com/scipy/scipy/blob/de80faf9d3480b9dbb9b888568b64499e0e70c19/scipy/optimize/_basinhopping.py#L667) (accept_test=mybounds is misleading). I think that would close out this issue. I agree that a nice enhancement for a future issue would be to modify `take_step` to respect bounds. Thank you.

**Comment by tupui** [comment]
I would do the following:

1. Fix the doc by removing mention of bounds. At most add bounds to the minimizer. If we want to show a real bounded example, a tutorial would be better suited IMO.
2. Add a `bounds` parameter. Even if the current API allows to do that, I think it's not really user friendly compared to our other optimisers where we only need to set `bounds`.

**Comment by tupui** [comment]
I did more exploration of the code.

I've found why the bound example was not working. It's because of the initial minimization which is happening at the init of the `BasinHoppingRunner`. The `accept_tests` is not being run there. Then it's more like a 3 steps algo:

1. Local minimization
2. Local minimization with checks
3. Stepping and back to 2

This is misleading (besides not being documented). IMHO it should not happen as it defeat the purpose of providing x0. As in, we provide x0, it run a local optimization to give you another x0 and then the optimization loop really starts.

Hence to have bounds you must adjust `minimizer_kwargs`. `take_step` will lose you some evaluations if you don't adjust it as well, but not critical. And `accept_test` is also needed because if the local minimization fails it does not matter the `Storage` get's updated with the output, we just increment a counter saying something bad happened.

**Comment by mdhaber** [comment]
> This is misleading (besides not being documented). IMHO it should not happen as it defeat the purpose of providing x0. As in, we provide x0, it run a local optimization to give you another x0 and then the optimization loop really starts.

Please see gh-3431. which reported this as a bug. I closed it because I don't think it's wrong.
