### ISSUE TITLE
optimize module has problem in version 18

### ISSUE THREAD

**Issue by vahtras** [scipy/scipy#6767]
I encounter the following problem in scipy 18 with several minimizing functions which work fine in scipy 17, best shown by a small example

Minimize the Morse potential ( function `f` below)  with the exact minimum 0.5

```
#morse.py
import math
def f(r):
   d=2.5; a=1.5; r0=0.5
   e=math.exp(-a*(r-r0))
   return d*(1-e)**2

import scipy.optimize
minx = scipy.optimize.fmin_cg(f, [1.0])
print(minx, f(minx))
```
Run with scipy 0.17
```
$ python --version
Python 3.5.2
$ pip freeze | grep scipy
scipy==0.17.0
$ python morse.py
python morse.py 
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 3
         Function evaluations: 21
         Gradient evaluations: 7
[ 0.50000005] 1.393924217093446e-14
```
Upgrade scipy
```
$ pip install scipy --upgrade
Collecting scipy
  Using cached scipy-0.18.1-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: scipy
  Found existing installation: scipy 0.17.0
    Uninstalling scipy-0.17.0:
      Successfully uninstalled scipy-0.17.0
Successfully installed scipy-0.18.1
```
Rerun
```
python morse.py 
Warning: Desired error not necessarily achieved due to precision loss.
         Current function value: 0.009194
         Iterations: 1
         Function evaluations: 24
         Gradient evaluations: 4
[ 0.46075045] 0.009193610730901572
```

**Comment by pv** [comment]
Whether it converges for this problem depends very much on the initial 
guess, both for Scipy 0.18 and 0.17. It is true that for such problems, 
the convergence basins of CG did change, but it is not clear whether 
this is a performance regression per se.

**Comment by vahtras** [comment]
Yes, but this should be a trivial optimization problem with starting point at r=1.0 and with the function looking like

https://github.com/vahtras/scipy/blob/gh-pages/morse.png

**Comment by person142** [comment]
I don't see any changes to the function between 0.17 (released Jan. 22 2016) and master in the history:

https://github.com/scipy/scipy/commits/v0.18.1/scipy/optimize/optimize.py

**Comment by pv** [comment]
There's a change in the initial step size in 0.18.0. However, it fails 
to converge for many initial guesses also in 0.17.0, so convergence 
basins were only shuffled up but the situation did not change otherwise.
.
I think what happens is the following: CG ends up with a non-descent 
direction, and the algorithm terminates (with a message of 
non-convergence) rather than trying shorter step lengths. AFAICS, this 
behavior is in the original implementation by Travis, so it's been like 
this forever.
.
The reason why is AFAICS that the CG is the PR+ variant, and unlike 
Fletcher-Reeves, strong Wolfe conditions do not always guarantee descent 
direction. To handle this case, the line search can backtrack, so that 
the algorithm doesn't need to exit with error. This is discussed in 
[Gilbert & Nocedal, "GLOBAL CONVERGENCE PROPERTIES OF
CONJUGATE GRADIENT METHODS FOR OPTIMIZATION", SIAM J. Opt. 2, 21 (1992)].
