### ISSUE TITLE
segfault in linkage where pdist(metric='cosine') returns nan

### ISSUE THREAD

**Issue by jnothman** [scipy/scipy#6774]
```python
from scipy.cluster import hierarchy
hierarchy.linkage([[0,0], [0,1]], method='average', metric='cosine')
```
segfaults.

scipy version: 0.18.1

**Comment by person142** [comment]
I wonder if you could try on master? I get
```python
>>> import scipy
>>> scipy.__version__
'0.19.0.dev0+b48f233'
>>> from scipy.cluster import hierarchy
>>> hierarchy.linkage([[0, 0], [0, 1]], method='average', metric='cosine')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Josh/Projects/scipy-dev/python3-scipy-dev/scipy/scipy/cluster/hierarchy.py", line 678, in linkage
    raise ValueError("`y` must contain only finite values.")
ValueError: `y` must contain only finite values.
```
So it's probably affected by the changes in https://github.com/scipy/scipy/commit/cf31ab151dce04143082ee45e39f26198cda26c8.

**Comment by jnothman** [comment]
Great, though it's a bit of an unclear error message, where the provided y
is finite.

**Comment by jnothman** [comment]
It's also an insufficient test since the y produced by pdist, rather than
that passed in includes non-finites.

**Comment by person142** [comment]
Yep, still could use fixing--just wanted to make sure I wasn't getting lucky in avoiding the segfault.

**Comment by jnothman** [comment]
No, I think you're right that the segfault will now be avoided.

**Comment by mp4096** [comment]
> Great, though it's a bit of an unclear error message, where the provided y is finite.

Good point. The problem is, `y` is either a condensed distance matrix or a collection of `m` observation vectors in `n` dimensions. The error message is misleading since it assumes that `y` is a distance matrix.

> It's also an insufficient test since the y produced by pdist, rather than that passed in includes non-finites.

Why exactly is the test insufficient? The idea was to compute the distance matrix anyway and check the result for finiteness.

I'll fix the wording in the error message and in the docstring. As for the segfault, I'd still like to fix it when I have more time, since the current solution is only a band-aid covering the real problem (uninitialised variables).

**Comment by rgommers** [comment]
Error message improved, guess we leave this issue open. Last thing to do is fix up the Cython code for uninitialized variables.

**Comment by jnothman** [comment]
The test is only insufficient because I don't think it considers the case
where the input is finite, but the distances are not.

**Comment by jnothman** [comment]
Thanks for the patches.

**Comment by BLMeltdown** [comment]
Could you please explain what is the problem, mathematically? I use  a correlation metric with an input matrix which is filled by -1 and 1, but how can the distance calculation create a NaN then?
I think the message is really inadapted, because the distance matrix is made is corrected for not having nans and infinite values:

     Distance_Matrix = pdist(data, metric ="correlation")
     Distance_Matrix[np.isnan(Distance_Matrix)]=0
     Distance_Matrix[np.isinf(Distance_Matrix)]=0

but still, I have 

  File "C:\Users\\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Documents/Python Scripts/HierClus_v2.py", line 60, in <module>
    Linkage_Matrix = linkage (data, method = "complete", metric = "correlation")

  File "C:\Users\\AppData\Local\Continuum\Anaconda3\lib\site-packages\scipy\cluster\hierarchy.py", line 676, in linkage
    raise ValueError("The condensed distance matrix must contain only finite values.")

ValueError: The condensed distance matrix must contain only finite values.

**Comment by WarrenWeckesser** [comment]
@BLMeltdown asked

> I use a correlation metric with an input matrix which is filled by -1 and 1, but how can the distance calculation create a NaN then?

If one of the arrays contains all the same values, then the correlation is undefined--the formula gives 0/0--so the correlation distance is NaN.  For example,

```
In [50]: from scipy.spatial.distance import correlation

In [51]: correlation([1, -1, 1, -1], [1, 1, 1, 1])
/Users/warren/miniconda3scipy/lib/python3.5/site-packages/scipy-1.0.0.dev0+84fd3a5-py3.5-macosx-10.6-x86_64.egg/scipy/spatial/distance.py:552: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - np.dot(um, vm) / (norm(um) * norm(vm))
Out[51]: nan
```

**Comment by BLMeltdown** [comment]
Could you please explain what is the problem, mathematically? I use  a correlation metric with an input matrix which is filled by -1 and 1, but how can the distance calculation create a NaN then?
I think the message is really inadapted, because the distance matrix is made is corrected for not having nans and infinite values:

     Distance_Matrix = pdist(data, metric ="correlation")
     Distance_Matrix[np.isnan(Distance_Matrix)]=0
     Distance_Matrix[np.isinf(Distance_Matrix)]=0

but still, I have 

  File "C:\Users\\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Documents/Python Scripts/HierClus_v2.py", line 60, in <module>
    Linkage_Matrix = linkage (data, method = "complete", metric = "correlation")

  File "C:\Users\\AppData\Local\Continuum\Anaconda3\lib\site-packages\scipy\cluster\hierarchy.py", line 676, in linkage
    raise ValueError("The condensed distance matrix must contain only finite values.")

ValueError: The condensed distance matrix must contain only finite values.

**Comment by BLMeltdown** [comment]
@WarrenWeckesser Thanks! I used -1 because 0 caused problems on its own. Should I try another filling value, or it will be the same? I guess that will be the same eventually, so how can I avoid this? by suppressing rows or columns filled with the same value (so if all the values are the same than their mean, for example)?

**Comment by roya0045** [comment]
Would it be possible to implement a fix that consider nan as non-overlapping data. The issues come with situations like the following: A cannot be compared to C but A is close to B and B is close to C.

Currently the only workaround is to fill nan and this will induce bias in the clustering. 

Could it be possible to have nan be simply ignored in the process so that using only available distance values for a point will still allow to establish its relative position to the others?
