### ISSUE TITLE
Remove NumarrayType struct with numarray type names from ndimage

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#6794]
See https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/nd_image.h#L67

There's also a couple of mentions of the ``tFloat64`` type in the ndimage tutorial, see gh-6792.

**Comment by jaimefrio** [comment]
This was done in #7549.

Not closing because of the tutorial reference. I would send a PR for that myself, but not sure what to change it to? There are many places in that document where we say something like "the input is an array of :c:type:`Float64` type" which makes marginal sense, as there is no `Float64` defined either in Python or in C anywhere. So what should those be replaced by?

 * the Python name of the type, e.g. `np.double` or `np.float64`,
 * the enumerated type value for that type in C, i.e. `NPY_DOUBLE` or `NPY_FLOAT64`, or
 * the actual C typedef, i.e. `npy_double` or `npy_float64`.

**Comment by rgommers** [comment]
Most of the mentions of `Float64` and `tFloat64` in http://scipy.github.io/devdocs/tutorial/ndimage.html seem to be for Python level code (ndarrays). So `np.float64` I'd think.
