### ISSUE TITLE
scipy.spatial.SphericalVoronoi fails for large number of points

### ISSUE THREAD

**Issue by ktritz** [scipy/scipy#6811]
Trying to create a high density spherical grid. Starting with an icosphere mesh with ~276k points, SphericalVoronoi is successful (and slow). Moving up to ~500k points, SphericalVoronoi fails with:

    Traceback (most recent call last):

      File "<ipython-input-29-287623b904b6>", line 1, in <module>
        s = SphericalVoronoi(g.getPoints())

      File "c:\anaconda3\lib\site-packages\scipy\spatial\_spherical_voronoi.py", line 229, in __init__
        self._calc_vertices_regions()

      File "c:\anaconda3\lib\site-packages\scipy\spatial\_spherical_voronoi.py", line 268, in _calc_vertices_regions
        -1) == generator_indices).any(axis=1))

    AttributeError: 'bool' object has no attribute 'any'

**Comment by rgommers** [comment]
@ktritz can you provide a self-contained example to reproduce the issue?

@tylerjereddy any ideas?

**Comment by ktritz** [comment]
Sure, you can use this function to generated uniform points on the unit sphere:

def uniform(num):
    vec = np.random.randn(3, num)
    vec /= np.linalg.norm(vec, axis=0)
    return vec.T

SphericalVoronoi(uniform(1e5)) works, though it takes ~minute or longer to complete
SphericalVoronoi(uniform(2e5)) fails fairly quickly with the above error message

note, the points  I was using on initially are an Icososphere grid rather than a random distribution, but it seems to have the same problem. With a little bit more testing, num = 1.44e5 works, 1.45e5 fails.

**Comment by ktritz** [comment]
It's probably a memory allocation problem, because this line:

(np.expand_dims(self._tri.simplices, -1) == generator_indices)

ends up creating an array with dimensions (2N-4, 3, N), which for N ~ 2e5 means and array with 240 billion points, and more memory than even my 32G can handle. For SphericalVoronoi to handle lots of points, this line will need to be more memory efficient.

**Comment by tylerjereddy** [comment]
Glad to hear people are actually using this code.

- The minute time scale performance is something I'm aware of. Nikolai and I knew of better algorithms when we wrote `SphericalVoronoi`, but as often happens in computational geometry, we implemented the one we could figure out! My plan for improving performance currently looks like this:
  - stage 1: (explore the possibility of) cythonizing the `SphericalVoronoi` algorithm to squeeze out as much performance as we can without having to reimplement the entire algorithm [you can see I've started simple with the point sorting component in #6768, but chipping away at other parts is on the to-do list]
  - stage 2: implement a cutting-edge algorithm with loglinear time complexity (there are a few of them, many in the last 10 years or so, so the math is understandably a bit tricky!)
- If I understand correctly, the more serious issue here is that `SphericalVoronoi` simply can't handle data sets on the order of 200,000 points. I'd propose:
  - the ideal solution: `SphericalVoronoi` would ideally not impose any additional constraints on the algorithm space complexity, beyond those imposed by `ConvexHull` (which is at the heart of `SphericalVoronoi`)-- which means we'd ideally be able to handle around 238 million points (see #6820 and links therein for details on `ConvexHull` point set limits)
  - more likely solution: I'm a bit skeptical I'll be able to find a solution that gives us a space complexity that gets up to the level of the highly-optimized `ConvexHull`, at least in the short term, but perhaps we can progressively raise the bar with improvements [I suspect performance is going to get pretty bad on the tens of millions of points scale because my benchmarks were consistent with quadratic time complexity for `SphericalVoronoi`, but would still be better if it worked rather than not at all] 

So, I'll start chipping away on a branch. The test code above should help, although I suspect a conventional unit test for the upper bound input tolerance would be a bit awkward, even with a slow decorator, because it would be slow / RAM stress a machine. What might work though is taking the part of the code that is limiting for space complexity (you appear to have done this already), and check the shape of the data structure that is produced for that code block (perhaps by abstracting it to another function that is then unit tested) using much smaller input.

**Comment by ktritz** [comment]
Thanks for the detailed response. In the past, I've used a python interface to the STRIPACK algorithm, but I'm looking for a more native python solutions, and I don't believe that's in the public domain. Also, the FORTRAN is pretty awful, IMO, at least with regards to porting to a python solution. That said, I had thought it was an O(nlogn) algorithm, though I could be mistaken. If so, it may handle larger datasets better.

In the meantime, I've cheated a little bit. Because my icosphere grid algorithm already provides me with the generator points and their neighbors, plus all of the triangles are acute, I can directly construct the circumcircles and calculate the voronoi points without having to worry about any geometric testing. This has the advantage that the voronoi circumcenter calculation is linear in N, and takes about 60s for 100M points, using a python-ported numba-optimized routine from MeshKit. This will work for me for now, but obviously a more general solution would be great!
