### ISSUE TITLE
Oddity in hypergeom

### ISSUE THREAD

**Issue by virgil** [scipy/scipy#6840]
I'm using python 3.5.2, MacOS, scipy verison 0.18.1.

This code [simplified] came up in a simulation.  I keep everything the same except for the value of 'n', that is, the number of Type 1 (Success) objects.  As the number of Success objects increases, the probability of success should *increase*.  But we see it doesn't even follow a monotonic behavior.  This is very peculiar.

See example below:

```
    from scipy.stats import hypergeom

    rv1 = hypergeom( 10000, 1000, 215 )
    rv2 = hypergeom( 10000, 1200, 215 )    
    rv3 = hypergeom( 10000, 2000, 215 )
    rv4 = hypergeom( 10000, 3000, 215 )

    z1 = rv1.cdf( 107 )
    z2 = rv2.cdf( 107 )
    z3 = rv3.cdf( 107 )
    z4 = rv4.cdf( 107 )    

    print("z1=%.14f" % z1)
    print("z2=%.14f" % z2)
    print("z3=%.14f" % z3)    
    print("z4=%.14f" % z4)        
```

which yields results:

```
z1=0.99999999998262
z2=0.99999999999750
z3=0.99999999998063
z4=0.99999999970559
```

We that from 1000 to 1200 it goes up (as expected), but then decreases.  I do not see how this is possible without a bug.

**Comment by ev-br** [comment]
This is essentially noise of lost precision:

```
In [48]: for _ in [1200, 1500]:
    print(hypergeom.cdf(107, 10000, _, 215),  hypergeom.sf(107, 10000, _, 215))
   ....:     
(0.99999999999749689, 4.9276765454965867e-44)
(0.99999999998118949, 9.9811198877272598e-35)
```

There might be some room for improving precision somewhat by rewriting https://github.com/scipy/scipy/blob/master/scipy/stats/_discrete_distns.py#L321 in terms of `betaln`, but I doubt that'll help much in this extreme case.

**Comment by pv** [comment]
betaln may help, because I guess the loss of precision comes from a>>b
which iirc is a limit handled by betaln.

**Comment by ev-br** [comment]
Am adding the easy-fix label for the betaln cleanup. There is also a sum of 107 terms, so I guess we'll need to see if whether the accuracy is limited by each term or the sum.

**Comment by person142** [comment]
Note that a better way to compute the pmf is with the Lanczos approximation, which is now in special. (Though private.)

**Comment by virgil** [comment]
What is the protocol for me on this ticket?  I looked into the difficulty of implementing betaln() myself, but it was sufficiently complicated I felt there was too high chance I'd break things.  Do I just wait until the betaln() patch is implemented?  Anything else I can before then?

An aside, your work in fantastic.

**Comment by person142** [comment]
`betaln` is already a function in `scipy.special`; the idea is to use that function in the log pmf. (Which would be the easy fix.)

**Comment by pv** [comment]
Now that I think, it's not so clear betaln will help here, the loss of 
precision may also come from summing many pmf terms in the cdf 
computation. So maybe the calculation should switch to `1 - sf` this far 
in the tail, which is probably numerically stabler.

**Comment by pv** [comment]
Oh, I see this was noted also by ev-br much earlier :)

**Comment by evgenyzhurko** [comment]
I rewrited https://github.com/scipy/scipy/blob/master/scipy/stats/_discrete_distns.py#L321 in terms `betaln`
For this example with code in terms `gammaln`:
```
    from scipy.stats import hypergeom

    rv1 = hypergeom( 10000, 1000, 215 )
    rv2 = hypergeom( 10000, 1200, 215 )    
    rv3 = hypergeom( 10000, 2000, 215 )
    rv4 = hypergeom( 10000, 3000, 215 )

    z1 = rv1.cdf( 107 )
    z2 = rv2.cdf( 107 )
    z3 = rv3.cdf( 107 )
    z4 = rv4.cdf( 107 )    

    print("z1=%.14f" % z1)
    print("z2=%.14f" % z2)
    print("z3=%.14f" % z3)    
    print("z4=%.14f" % z4)
```
I have output:
```
    z1=0.99999999998262
    z2=0.99999999999750
    z3=0.99999999998063
    z4=0.99999999970559
```
`_log_pmf` function in terms `betaln`:
```
    def _logpmf(self, k, M, n, N):
        tot, good = M, n
        bad = tot - good
        return betaln(good+1, 1) + betaln(bad+1,1) + betaln(tot-N+1, N+1)\
            - betaln(k+1, good-k+1) - betaln(N-k+1,bad-N+k+1)\
            - betaln(tot+1, 1)
```
And new output for previous example:
```
    z1=0.99999999998341
    z2=0.99999999999583
    z3=0.99999999998275
    z4=0.99999999970387
```
As we see, `_log_pmf` function in terms `betaln` doesn't solve problem

**Comment by Don86** [comment]
I'm new to contributing to scipy, so I've just been lurking around the issues, looking for something to contribute to. Conceptually, I'd like to know why "_As the number of Success objects increases, the probability of success should increase._" (quote from original post)?  I haven't actually sat down and worked out the algebra yet, I'm not quite able to see this monotonic relationship.

My intuitive (and unreliable) explanation to the contrary: for a fixed population size _N_, as the number of type 1 objects, _K_, increases, the number of type 2 objects, _N - K_, must necessarily decrease.  If we choose _n_ objects without replacement, out of which _k_ are type 1 objects (where _n > k_ so that this is a nontrivial case), it becomes "easier" to choose a type 1 object as _K_ increases, but "harder" to choose a type 2 object to fill the _n - k_ chosen type 2 objects.

**Comment by Don86** [comment]
Hi, I'm new to contributing in general so I've just been lurking around. From the original post: "_As the number of Success objects increases, the probability of success should increase._" I haven't sat down to work out the algebra yet, but I can't quite see this relationship?

My intuitive (and therefore unreliable) explanation to the contrary: for a fixed total population of _N_ objects, where _n_ are type 1 objects and _N - n_ are type 2 objects, as _n_ increases, _N - n_ must necessarily decrease.  So if we choose _M_ objects with replacement, _m_ of which are type 1 objects, it becomes "easier" to choose type 1 objects as _n_ increases, but also "harder" to choose type 2 objects. 

Some back-of-the-envelope calculations, adapting the scipy [example:](https://docs.scipy.org/doc/scipy-0.18.0/reference/generated/scipy.stats.hypergeom.html)

``def nCr(n, r):``
``    f = math.factorial``
``    return f(n)/f(r)/f(n-r)``

``def hypergeom(M, m, N, n):``
``    hpg = nCr(M, m)*nCr((N - M), (n - m))/nCr(N, n)``
``    return hpg``

``N=20 #Total population size``
``n=12 #no. of objects chosen``
``m=6 #no. of type 1 objects chosen``

``m_rng = np.arange(m, N-m)``
``#vary the no. of type 1 objects available``

``for M in m_rng:``
``    hpg = hypergeom(M, m, N, n)``
``    print(M, hpg)``
>>6 0.023839009287925695
7 0.09535603715170278
8 0.205382233865206
9 0.308073350797809
10 0.3500833531793284
11 0.308073350797809
12 0.205382233865206
13 0.09535603715170278
14 0.023839009287925695

**Comment by Don86** [comment]
Some back-of-the-envelope calculations, adapting the scipy [example:](https://docs.scipy.org/doc/scipy-0.18.0/reference/generated/scipy.stats.hypergeom.html)

``def nCr(n, r):``
``    f = math.factorial``
``    return f(n)/f(r)/f(n-r)``

``def hypergeom(M, m, N, n):``
``    hpg = nCr(M, m)*nCr((N - M), (n - m))/nCr(N, n)``
``    return hpg``

``N=20 #Total population size``
``n=12 #no. of objects chosen``
``m=6 #no. of type 1 objects chosen``

``m_rng = np.arange(m, N-m)``
``#vary the no. of type 1 objects available``

``for M in m_rng:``
``    hpg = hypergeom(M, m, N, n)``
``    print(M, hpg)``
>>6 0.023839009287925695
7 0.09535603715170278
8 0.205382233865206
9 0.308073350797809
10 0.3500833531793284
11 0.308073350797809
12 0.205382233865206
13 0.09535603715170278
14 0.023839009287925695

**Comment by ev-br** [comment]
> As we see, _log_pmf function in terms betaln doesn't solve problem

So the issue is not an easy-fix, thanks for checking @evgenyzhurko! A rewrite of the _logpmf in terms of `betaln` would still be a nice cleanup, so please submit it as a PR if you've done it anyway.

**Comment by IandJMSmith** [comment]
> 
> 
> I rewrote https://github.com/scipy/scipy/blob/master/scipy/stats/_discrete_distns.py#L321 in terms `betaln`
> For this example with code in terms `gammaln`:
> 
> ```
>     from scipy.stats import hypergeom
> 
>     rv1 = hypergeom( 10000, 1000, 215 )
>     rv2 = hypergeom( 10000, 1200, 215 )    
>     rv3 = hypergeom( 10000, 2000, 215 )
>     rv4 = hypergeom( 10000, 3000, 215 )
> 
>     z1 = rv1.cdf( 107 )
>     z2 = rv2.cdf( 107 )
>     z3 = rv3.cdf( 107 )
>     z4 = rv4.cdf( 107 )    
> 
>     print("z1=%.14f" % z1)
>     print("z2=%.14f" % z2)
>     print("z3=%.14f" % z3)    
>     print("z4=%.14f" % z4)
> ```
> 
> I have output:
> 
> ```
>     z1=0.99999999998262
>     z2=0.99999999999750
>     z3=0.99999999998063
>     z4=0.99999999970559
> ```
> 
> `_log_pmf` function in terms `betaln`:
> 
> ```
>     def _logpmf(self, k, M, n, N):
>         tot, good = M, n
>         bad = tot - good
>         return betaln(good+1, 1) + betaln(bad+1,1) + betaln(tot-N+1, N+1)\
>             - betaln(k+1, good-k+1) - betaln(N-k+1,bad-N+k+1)\
>             - betaln(tot+1, 1)
> ```
> 
> And new output with new `_log_pmf` for previous example:
> 
> ```
>     z1=0.99999999998341
>     z2=0.99999999999583
>     z3=0.99999999998275
>     z4=0.99999999970387
> ```
> 
> As we see, `_log_pmf` function in terms `betaln` doesn't solve problem

I haven't seen the code but I'm pretty sure the problem is that cdf should be calculated as 1-sf when sf is small and sf as 1-cdf when cdf is small. Basically, if the code uses summation techniques, it should start with the largest pmf value to be included (or omitted via 1-) and sum towards the tail. Actually, I see this has been suggested earlier as the cause of the problem.

Also, it makes little or no difference whether the code uses betaln or gammaln to evaluate the pmf. Both betaln and gammaln will return large values when given large arguments. These large values are added and subtracted and what is important is the absolute error in the total. When that total is exponentiated to obtain the pmf, the absolute error in the value being exponentiated becomes the relative error of the exponentiated value. exp(correct value + ae) is approximately correct answer * (1+ae). With the numbers in the example, the use of log factorial functions causes a loss of between 5 and 6 figures of accuracy. 

I have attached code for the Beta Binomial and Beta Negative Binomial in my response to issue [7102](https://github.com/scipy/scipy/issues/7102). This code also evaluates the hypergeometric and negative hypergeometric pmf, cdf and sf functions. Although my knowledge of python is somewhat primitive, it may give someone ideas on how to deal with the loss of precision issues with the hypergeometric distribution functions.

**Comment by mdhaber** [comment]
>We [see] that from 1000 to 1200 it goes up (as expected), but then decreases. 

As @Don86 suspected, I don't think we would expect the cdf - that is, the probability of selecting up to (and including) 107 Type 1 objects - to increase as `n`, the number of Type 1 objects, increases. 

Perhaps it's easier to think of the CDF at `k=0` instead of `k=107`. This is the same as the PMF at `k=0`. Certainly, we would expect the probability of picking _only_/exactly `0` Type 1 objects to _decrease_ as the number of Type 1 objects increases. Similarly with all numbers of successes up to including 107. So the CDF should decrease.

Another way of looking at it: as `n` increases, the distribution shifts toward the right (higher numbers of successes), so the CDF at a fixed value of `k` will tend to decrease.

Anyway, we used Boost for this distribution now, and here's a plot of CDF(107, 10000, `n`, 215) as a function of `n`.

![image](https://user-images.githubusercontent.com/6570539/159645039-49b7c422-458c-4da5-9150-3ef9888d39e5.png)

The output of the code at the top is:
```
z1=1.00000000000000
z2=1.00000000000000
z3=1.00000000000000
z4=0.99999999972268
```
So no more weird back and forth with these values, and in fact, it's monotonic with integer `n` for the range I tested (2000 to 9000), so this is resolved.
