### ISSUE TITLE
minres always uses zero vector as initial vector and user doesn't know about it

### ISSUE THREAD

**Issue by AC130USpectre** [scipy/scipy#6843]
What I mean, is _scipy/sparse/linalg/isolve/minres_, which is in python just `scipy.sparse.linalg.minres`.

In 46 line:
`    A,M,x,b,postprocess = make_system(A,M,x0,b,xtype)`

It is usual preprocessing, which just check is `x0` equals to `None`. But in 88 line we have:
`    x = zeros(n, dtype=xtype)`

So, anyway initial vector is zero. Is there a reason to allow user to specify `x0` ? It doesn't make a sense. Maybe better delete `x0=None` from the function signature?

**Comment by AC130USpectre** [comment]
What I mean, is _scipy/sparse/linalg/isolve/minres_, which is actually `scipy.sparse.linalg.minres`.

**Comment by AC130USpectre** [comment]
Maybe better to do it like this:

```
def minres(A, b, shift=0.0, tol=1e-5, maxiter=None, xtype=None,
           M=None, callback=None, show=False, check=False):
    A,M,x,b,postprocess = make_system(A,M,None,b,xtype)
```

**Comment by person142** [comment]
Is there a reason why you want to eliminate `x0` instead of making it work as advertised?

**Comment by AC130USpectre** [comment]
It doesn't work as advertised: it doesn't uses `x0` anyway. All code just rewrited directly from corresponding Fortran files (you can find them here: http://web.stanford.edu/group/SOL/software/minres/), where were no need in initial vector (cause they assign it to zero vector).

In my opinion the problem is that nobody says that it is. There isn't any mentions that `x0` is useless in that particular function. Original signature just copypasted from other function calls. Because of that some stupid students like me tries to use this function and they wonder why it works as it works, not as they expect.

**Comment by person142** [comment]
> It doesn't work as advertised: it doesn't uses `x0` anyway

Right, we're agreed on that. The question is whether `x0` should be eliminated or whether the code should be rewritten to actually use `x0`.

**Comment by person142** [comment]
i.e. one could deprecate `x0` in the signature, or one could remove the `x = zeros(n, dtype=xtype)` line.

**Comment by pv** [comment]
I don't see the reason to deprecate x0. Presumably, minres can work with given initial vector also.

**Comment by person142** [comment]
Yeah, that's my feeling too.

**Comment by psiehr** [comment]
I just noticed this issue.  There is no reason why x0 should or should not be 0. 
The MinRes method converges for all initial guess x0, if A is (real) positive definite.

But the documentation tells us:  "A can be indefinite or singular."

If I can read your code correctly you even check if A is symmetric:
[Sourccode](https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/isolve/minres.py#L111)

Which is not related: 
A=[1 , 1 ; -1 , 1]  
is positive definite (since x^t A x = x₀² + x₁² > 0, ∀x=(x₀,x₁) =/= 0 ) , but not symmetric.

Oh and about line 88: x = zeros(...)
We have in line 94:  r1 = b
This actually should be  r1 = b-Ax, if you intend to use the input.  
"x=zeros" is used nowhere explcitly, only implicitly in line 94.

**Comment by georgh** [comment]
I noticed this bug, too.
