### ISSUE TITLE
differential_evolution: make callback receive fun(xk)

### ISSUE THREAD

**Issue by ZacDiggum** [scipy/scipy#6878]
In `differential_evolution` the `callback` function receives the current best parameter set `xk` and `convergence` but not the current function value `fun(xk)`. For implementing a function value driven termination one needs to evaluate the function once more inside `callback` with the help of `xk`. Especially with small poplation sizes this creates an unnecessary overhead.
Could `callback` be altered so that it receives `xk, fun(xk), convergence`? Please?

**Comment by ZacDiggum** [comment]
see #6890

**Comment by rgommers** [comment]
> Could `callback` be altered so that it receives `xk, fun(xk), convergence`? 

This change would break any current usage of ``callback``, because the function signatures would not match.

It is not easy to add an extra argument without breaking backwards compat, would need:
- the new argument to be at the end, rather than in the middle as you propose
- introspection of ``self.callback`` to check that it supports a second keyword argument with the right name

It is possible, and I can see the benefit, but the implementation would be ugly.

Any other opinions?

**Comment by dlax** [comment]
> Any other opinions?

I'd rather have the "internal" iteration loop exposed in an API so that users would be free to invoke a "callback" as they want. `DifferentialEvolutionSolver` already abstracts out part of this in an iteration protocol (`__next__` method), so it could just be one step further. We could even handle the solver initialization and termination using a context manager.

Something like:
```
with DifferentialEvolutionSolver(myfunc, mybounds) as solver:
   for i in range(maxiter):  # or for step in solver: # (if it is aware of maxiter)
        step = next(solver)
        mycallback(step.population, step.population_energies, step.convergence)
        if solver.converged:
            break

result = solver.result
```

Just a thought...

**Comment by andyfaff** [comment]
I'm not keen to change the callback signature because there are so many
attributes that could be useful to expose. If they're all sent to the
callback function then the callback function will get less and less like
the callback functions for the other minimizers.

I think the way that Denis displayed (i.e. using `next`) is much preferable
as all the innards are available from the solver object. Indeed, the whole
idea of __next__ was for the user to do something like this.

Denis, I'm not quite sure what you meant by exposing the iteration loop in
an API.

Adding a context manager is a really good idea.

**Comment by dlax** [comment]
Andrew Nelson a écrit :
> Denis, I'm not quite sure what you meant by exposing the iteration loop in
> an API.

I just meant what I illustrated in the example code ;)

That would mean making the DifferentialEvolutionSolver part of the
public API and have its `__next__` method return a "step" object
instance with all information bits about current iteration status
attached so that it can later be eventually extended without breaking bw
compat.

In general, it seems to me that with complex solvers like DE we should
try to expose a reasonably flexible API rather than trying to make all
use cases fit into the functional API with callbacks and friends. Giving 
control on the iteration loop is probably the first step towards this.

**Comment by ZacDiggum** [comment]
Hm, I'm giving up for now. But creating custom termination functions would still be useful...
I'm using `differential_evolution` as a robust solver for high dimensional model fitting, that's where the motivation comes from. So, if this topic could be solved, I'd be very grateful...

**Comment by ZacDiggum** [comment]
#6905 exposes `func_val`,` nfev`, `nit` and `population` to `callback`.
These could be used to create custom terminators [like these](https://aarongarrett.github.io/inspyred/reference.html#terminators-algorithm-termination-methods).

**Comment by ZacDiggum** [comment]
#6907 now the diff is displayed correctly

**Comment by ZacDiggum** [comment]
@dlax's suggestion sounds good to me...

**Comment by dlax** [comment]
ZacDiggum a écrit :
> @dlax <https://github.com/dlax>'s suggestion sounds good to me...
>

Okay, I'll try to scratch an initial implementation of this idea soon so
we can discuss further.

**Comment by mdhaber** [comment]
It sounds like the preferred approach would be a different interface with more control than adding more information to the callbacks, so I'll go ahead and close this. Feel free to reopen if I've missed something.
