### ISSUE TITLE
Optimization algorithm contribution

### ISSUE THREAD

**Issue by nlw0** [scipy/scipy#6955]
Greetings. I have this implementation of a trust-region Gauss-Newton method, following Fletcher's book. I also have an SQP method implementation, of which this was a part of. I would love to contribute all that to scipy, but I am quite unsure how to begin. Can anyone give me some initial advice? I just need to understand where I would include the function, and how to deal with the C parts... Here is the code for reference: https://github.com/nlw0/corisco/blob/master/filtersqp/filtersqp/__init__.py

**Comment by dlax** [comment]
There are already trust-region methods in `scipy/optimize/_trustregion*` available as `method=dogleg` and `method=trust-ncg` in `minimize()`.

So if you want to contribute something, this would probably go into the `minimize()` interface and live in one of existing `_trustregion*.py` files.

But first of all, you should explain how the algorithm you propose differ from the ones we already have.

@nmayorov, our trust-region expert, might follow up then.

**Comment by nlw0** [comment]
From what I get, the dog-leg method approximates the trajectory at each step using a couple of straight lines, and only works with a positive definite Hessian. In this algorithm I implemented we actually calculate the exact point from the trajectory, using root-finding for this, and it works with an indefinite and even definite negative Hessian. I am not sure about the ncg, is it like the conjugate gradient, but using trust region instead of doing a linear search?

**Comment by nlw0** [comment]
I forgot to link here some later work I did implementing just a trust region method in C++, as a first step for reimplementing FilterSQP. Some compelling examples here to show how it is interesting, specially the ability to handle negative and undefined Hessians. https://github.com/nlw0/filterSqp One important detail here is that I'm relying in AD.

Still very interested in learning more details about how I might contribute this to the project. Do you think it could be interesting? How do I get the implementation started?

**Comment by rgommers** [comment]
@nlw0 have you seen that we currently have a GSoC project from @antonior92  on trust-region optimization ongoing? That may be of interest:

- Code: https://github.com/antonior92/ip-nonlinear-solver
- Blog: https://antonior92.github.io/year-archive/

> One important detail here is that I'm relying in AD.

Hmm, that would be a problem. There's no AD in SciPy, and I don't think we'd like to add a dependency to any AD library.

> Still very interested in learning more details about how I might contribute this to the project. Do you think it could be interesting? How do I get the implementation started?

These algorithms are quite technical, and there's quite a few of them. You say above that it works with  an indefinite and even definite negative Hessian - so I guess that's something not yet present in ``scipy.optimize``. A very useful contribution to start with, both to get this conversation going and as a documentation enhancement, would be to make an overview of these solvers and what they can/can't do. Based on the info in http://scipy.github.io/devdocs/optimize.html and your statement on Hessians I can't quite figure it out, and I'm probably not the only one who would be confused ....

**Comment by nlw0** [comment]
I'll check that project, but I'm not sure it is closely related to what I'm talking about. But @antonior92 actually seems to study in the same Brazilian university I graduated more than 10 years ago, so I guess it's no surprise we share some interest in similar methods. :) I have written him about a possible collaboration.

About the AD thing, it is only used there to calculate the objective function and the derivatives, the method itself does not require that. I'm only pointing out something to disregard about that project.

This method I'm talking about is basically similar to Powell's dog-leg method, except there is no approximation, we actually use a root-finding algorithm to calculate the appropriate step. I have found this method to perform better in many situations, and I believe it is a worthy alternative to SciPy _per se_. Levenberg-Marquadt can also deal with non-definite-positive Hessians too, of course, but not in a very natural way. But regardless of that the SciPy L-M implementation does not even seem to support a generic Hessian.

My interest here is also not just in offering this method, but in later offering a constrained optimization method that is built on top of it (FilterSQP), and I believe that would be a nice first step for me to figure out how to make a contribution to the project.

**Comment by antonior92** [comment]
Hey @nlw0. Nice to see another student from UFMG around here.

I would be really happy to see filterSQP integrated to Scipy. By what I know, filter SQP is a very successful algorithm and would be a very nice alternative to the interior-point method I am implementing since I think they have complementary strengths.

--------
About the trust region method:

1. I got a little confused be the nomenclature you are using: Gauss-Newton is usually related to line-search (for instance, Fletcher's book says he uses this nomenclature on p.114 and Nocedal's book on p.254). And I Levenberg-Marquadt is usually related to trust-region (Nomenclature used in Nocedal's book on p.258). And both of them are usually related on

2. The nonlinear implementation of nonlinear least-squares is actually very versatile and I think it can deal with singular Hessians. @nmayorov  will probably be able to gives more details about it You should take a look in: http://scipy.github.io/devdocs/generated/scipy.optimize.least_squares.html#scipy.optimize.least_squares

3.  About the inclusion of a new trust-region method to scipy. Does the trust-region method  you implemente can be used on general problems or only for nonlinear least-squares problems?
Furthermore, which kind of trust-region problem you are solving at each iteration: It is a spherical trust-region? It is a box shaped trust-region? 
There are three trust-region different currently available in Scipy, and an extra one that is being integrated:
- ``trust-exact``
- ``trust-ncg``
- ``dogleg``
-  ``trust-lanczos`` (PR #7292)
All these options solve (approximately) the trust-region subproblem on a spherical trust-region:
    
    minimize f + g.T x + 1/2 x.T H x
    subject to: ||x|| < trust_radius

If the trust-region method you solve is like this one you should be able to integrate it very easily to Scipy. Take a look into PR #7292 (which integrate a trust-region method implemented in C to Scipy)
and in PR #6919. You should also check to see if what you have is not already implemented in one of the four trust-region techniques I just cited.

----------------------------------- 

I am really excited about the possibility of including filterSQP on Scipy. I am still thinking how to integrate the method I am currently implementing to Scipy. But once it is done you could probably use the same interface.

**Comment by nlw0** [comment]
OK, my mistake. No Gauss involved, it's the more generic Newton's method, with a generic Hessian. It uses a spherical trust region, so I imagine it would be similar to this "trust-exact", although not limited to least-squares. I didn't know these methods had been included in the project, that's great! I'll have to check to see what exactly could still be different in my implementation for the non-constrained case.

**Comment by antonior92** [comment]
The four trust-region methods  I just mentioned (including ``trust-exact``) are for general unconstrained problems (they are not limited to least squares problems).

--------

I have taken a look in yours repositories and I have a few questions about yours filterSQP implementation:

1. The method you pointed out [here](https://github.com/nlw0/corisco/blob/master/filtersqp/filtersqp/__init__.py) just support one constraint?
2. Do you have more examples of the filterSQP method. The one you presented [here](https://github.com/nlw0/filterSqp) are just on unconstrained optimisation problems.
3. Which QP solver are you using? I could not find it in the repositories you have pointed out. By what I know the filterSQP solver (as implemented by Fletcher) usually require an indefinite QP solver, that can be very complex to implement.

**Comment by nlw0** [comment]
Allright then, I don't know why I got the impresison "trust-exact" was on `scipy.optimize.least_squares`!... Neat.

When you talk about the QP solver, wouldn't it be this function? https://github.com/nlw0/corisco/blob/master/filtersqp/filtersqp/__init__.py#L39

Indeed it's a single constraint, that's all I needed in my work at that moment. And in the more recent project I did not get to the actual constrained part. The examples I have are not very complex, the most challenging was my final application that had only 4 dimensions...

I imagine this method and this implementation may have lots of limitations, but it does work, you can easily show that it solves a linear funciton constrained over a circle, for instance, what would be impossible without constrained optimization. I am certainly curious to see how much I can push it, that's why I was making a new implementation in C, and hoping to target to SciPy to attract the attention of other developers!

**Comment by rgommers** [comment]
@nlw0, @antonior92 do we need to keep this open?
