### ISSUE TITLE
serious bug in processing of netCDF3 MaskedConstants

### ISSUE THREAD

**Issue by thehesiod** [scipy/scipy#6970]
if you open a file like https://madis-data.ncep.noaa.gov/madisPublic1/data/LDAD/mesonet/netCDF/20170117_1900.gz with scipy.io.netcdf.netcdf_file, and look at variables['observationTime'][71132] it will return a value of 3.40282346e+38, whereas netCDF4 will return a MaskedConstant with a value of True (which means not available).

The above netCDF file changes, so you may need to pick a new file in that path and iterate through columns and compare with netCDF4 library to find the same problem.

**Comment by rgommers** [comment]
What version of SciPy are you using? There was a fix for masked values in 0.18.0

**Comment by thehesiod** [comment]
0.18.1

**Comment by pv** [comment]
You can upload the file here, 
https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/
May need to be put in a .zip first though

**Comment by pv** [comment]
Also a code sample corresponding to the uploaded file would be useful.

**Comment by thehesiod** [comment]
[20170117_1900.gz](https://github.com/scipy/scipy/files/717259/20170117_1900.gz)

```python
foo = netCDF4.Dataset('20170117_1900.nc')
foo2 = scipy.io.netcdf.netcdf_file('20170117_1900.nc')

assert foo.variables['observationTime'][71132] == foo2.variables['observationTime'][71132]
```

**Comment by pv** [comment]
Is the problem only that you would need to open the file with 
`scipy.io.netcdf.netcdf_file('20170117_1900.nc', maskandscale=True)`?

**Comment by pv** [comment]
If so, there's strictly speaking no bug, although the default behavior 
of *not* respecting the mask unless told so may be surprising.

**Comment by thehesiod** [comment]
looks like ya maybe...shouldn't the default behavior match netCDF4 module?

**Comment by shoyer** [comment]
Changing the default behavior would break existing code that expects a numpy array to be returned, and thus would require a deprecation cycle. I don't think it would be worthwhile in this case, because the existing interface has been around for quite some time and base numpy arrays are often preferred.

If you want to easily switch back and forth between different readers for the same file format using the same interface, the usual guidance is to consider a higher level library that handles both. In this case [xarray](https://github.com/pydata/xarray) (disclaimer: my project) would be a suitable choice.
