### ISSUE TITLE
Scipy.otpimize.differential_evaluation returns a minimum point beyond the specified range

### ISSUE THREAD

**Issue by zell08v** [scipy/scipy#7034]
I tried scipy.optimize's differential evaluation, which returns to me an minimum point that is beyond the specified range.  See below what I have from ipython:

```
In [85]: import scipy.optimize as op

In [86]: import sys

In [87]: op.differential_evolution(lambda x:x**2,[(-sys.float_info.max,sys.float_info.max)])
Out[87]:
    nfev: 15017
 success: False
     fun: inf
       x: array([-inf])
 message: 'Maximum number of iterations has been exceeded.'
     nit: 1000

```

**Comment by andyfaff** [comment]
First of all, if the function is going to return Exceptions or Nan then the minimizer isn't going to work.

    >>> y = lambda x:x**2
    >>> import sys
    >>> sys.float_info.max
    1.7976931348623157e+308
    >>> y(sys.float_info.max)
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "<stdin>", line 1, in <lambda>
    OverflowError: (34, 'Result too large')

Secondly, all solution vectors are internally scaled to between 0 and 1 (this was done for simplicity) in the solver initialisation:

    self.__scale_arg1 = 0.5 * (self.limits[0] + self.limits[1])
    self.__scale_arg2 = np.fabs(self.limits[0] - self.limits[1])

If one inserts your limits into the second line of code:

    >>> np.fabs(-sys.float_info.max - sys.float_info.max)
    inf

i.e. `__scale_arg2` is `inf` because of overflow. So while the internally scaled numbers lie between the limits, when the internal to external scaling is carried out the calculation doesn't work properly. I'd be reluctant to change this unless you have a real-life problem where this is an issue.
