### ISSUE TITLE
scipy.stats.fisher_exact for tables larger than 2x2

### ISSUE THREAD

**Issue by xflr6** [scipy/scipy#7099]
Would be great if `scipy.stats.fisher_exact()` could add support for larger contingency tables ([like R](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/fisher.test.html)).

There is actually code for this in [maclandrol/FisherExact](https://github.com/maclandrol/FisherExact) but I don't know how hard it would be to integrate that (see also this [blog post](https://mrnoutahi.com/2016/01/03/Fisher-exac-test-for-mxn-table/) by the author).

**Comment by mdhaber** [comment]
Note to those interested in implementing this: please do not refer to the code in the linked package, as it's license-incompatible. gh-15618 would be useful towards a Monte Carlo solution to this problem.

**Comment by Ge0rges** [comment]
Perhaps @maclandrol would be interested in integrating his project here or relicensing so another might.

**Comment by mdhaber** [comment]
If you're in dire need, here are two possible implementations that compute a statistic using `scipy.stats.contingency.chi2_contingency` but compute the null distribution more accurately.

Starting with a 2x2 table for comparison against `fisher_exact`, suppose we have:
```python3
import numpy as np
from scipy import stats

observed = np.asarray([[1, 3], 
                       [2, 1]])
res = stats.chi2_contingency(observed)
print(res.pvalue)  # 0.7408568142938687

ref = stats.fisher_exact(observed)
print(ref.pvalue)  # 0.48571428571428565
```
Yes, `chi2_contingeny` isn't a great approximation for a table with such a small sum.

A Monte Carlo approach is to generate random contingency tables with the same marginal sums with `stats.random_table`, compute the statistic for each to form the null distribution, and compare the statistic of the observed table against the null distribution.
```python3
rowsums, colsums = stats.contingency.margins(observed)
rng = np.random.default_rng(2395834589245)
X = stats.random_table(rowsums.ravel(), colsums.ravel(), seed=rng)

def statistic(table):
    return stats.chi2_contingency(table).statistic

n_mc_samples = 9999
null_distribution = []
for i in range(n_mc_samples):
    table = X.rvs()
    null_distribution.append(statistic(table))
null_distribution = np.asarray(null_distribution)

n_extreme = np.sum(null_distribution >= statistic(observed))
pvalue = (n_extreme + 1) / (n_mc_samples + 1)
print(pvalue)  # 0.4822
```
This will be reasonably fast and accurate for a wide range of table sizes and sums.

For an exact test, you can un-tabulate the table:
```python3
def untab(table):
    r, c = table.shape
    x = []
    y = []
    for i in range(r):
        for j in range(c):
            x += ([i] * table[i, j])
            y += ([j] * table[i, j])
    return np.asarray(x), np.asarray(y)

x, y = untab(observed)
x  # array([0, 0, 0, 0, 1, 1, 1])
y  # array([0, 1, 1, 1, 0, 0, 1])
```

And perform an exact test using the `chi2_contingency` statistic:
```python3
res = stats.permutation_test((x,), lambda x: statistic(x, y), 
                             permutation_type='pairings', alternative='greater',
                             n_resamples=50000)
res.pvalue  # 0.4857142857142857
```
This is going to be randomized (not exact) unless `n_resamples` is sufficiently high - you need `n_resamples = factorial(observed.sum)` to get an exact test. And that is going to get slow pretty quickly : )

But these aren't limited to 2 x 2 tables. An example from [`fisher.test`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/fisher.test.html) is:
```python3
observed = np.reshape([1, 2, 1, 0, 3, 3, 6, 1, 10, 10, 14, 9, 6, 7, 12, 11], (4, 4))
```
The Monte Carlo test gives a p-value of `0.7707`, and the (randomize) permutation test gives `0.7723`. These are pretty close to `0.7827` reported by `fisher.exact`, and much better than `chi2_contingency` (`0.7408568`).

I'm sure others will want to one-up this in one way or another, but I thought this might help get things started.

Note, however, that the difficulty with getting a test like this into SciPy isn't going to be implementing the test. It's going to be the interface, testing, documentation, and especially review. We're short on maintainer time.

**Comment by HDembinski** [comment]
The nice thing about the permutation test is that you can use any test statistic, since you get its null distribution via MC simulation. There should be an optimal test statistic which maximizes the power of this test. If both the null hypothesis and the alternative are fully specified (their PDFs known), then the likelihood ratio of the two hypotheses is that best test statistic (Neyman-Pearson lemma).

But if only the null is fully specified, we don't know the most powerful test statistic. Intuition may point towards the using the likelihood of the null-hypothesis (as computed via random_table.pmf), this can be shown to be a poor test statistic in special cases. `chi2_contingency` is probably not a bad choice.

**Comment by mdhaber** [comment]
Thanks @maclandrol. Relicensing would be helpful! SciPy uses BSD, but MIT or an another permissive license would allow for inclusion in ScIPy. Although we aren't likely to port it here wholesale, we might refer to it for reference. Thank you!

**Comment by mdhaber** [comment]
Thanks @HDembinski! That is helpful. One thing I can do very easily is add a `method` argument to `chi2_contingency` that allows calculation of the p-values via either permutation or Monte Carlo methods. If the likelihood of the null hypothesis is widely regarded as the natural extension of Fisher's original 2x2 test, I can think about doing the same for `fisher_exact` - maybe we can generalize the `statistic` output to report the odds ratio between any two categories and have a new `likelihood` attribute. We can also include an example in the `fisher_exact` documentation about how to use custom statistics. 

I'll go ahead and put together PRs, since this has been on my radar for a long time. If someone is willing to review from a statistical correctness standpoint, that will probably speed things along, as other may maintainers may elect to review mostly the interface/code quality side.

**Comment by maclandrol** [comment]
Done, 

> Thanks @maclandrol. Relicensing would be helpful! SciPy uses BSD, but MIT or an another permissive license would allow for inclusion in ScIPy. Although we aren't likely to port it here wholesale, we might refer to it for reference. Thank you!

Done, switched to MIT.
