### ISSUE TITLE
DOC: special: unified Parameters/Returns format

### ISSUE THREAD

**Issue by person142** [scipy/scipy#7149]
While looking at https://github.com/scipy/scipy/pull/7148 I wondered again about something that has often troubled me: how the Parameters/Returns section should look in special function documentation.

I suppose that the baseline would be the documentation of something like `numpy.sin`:

https://docs.scipy.org/doc/numpy/reference/generated/numpy.sin.html

We often don't follow the conventions in that doctring; some variants:

- `special.j0`
```
Returns
-------
J : ndarray
    Value of the Bessel function of the first kind of order 0 at `x`.
```
In particular it says the return value is an `ndarray`, which isn't true for scalar inputs. This is common in the module.

- `special.ndtr`
```
Parameters
----------
x : array_like, real or complex
    Argument
```
This includes extra type information on the first row and is a common variant in the module, but I seem to recall that @rgommers didn't like this style.

- `special.sph_harm`
```
Returns
-------
y_mn : complex float
   The harmonic :math:`Y^m_n` sampled at ``theta`` and ``phi``.
```
Similar to `ndtr`, type information is put in the first line of the returns.

Finally, as one can see from the examples there is a discrepancy as to what we should call the return arrays. Some functions opt for using the function name, and some use the common mathematical notation for the function (e.g. using `J` for `special.j0`). The function name works pretty well until there are multiple outputs...

So, to try and settle this once and for all, how should these sections look?

**Comment by WarrenWeckesser** [comment]
I though a bit about this while preparing #7148, and looked around for some similar examples to follow so I wouldn't have to think much more than "a bit" 😄 .

In #7148, I left out the description of the `z` argument in the Parameters section, so it only gives the argument name and type.  I saw the `ndtr` docstring that you show, and didn't like the "Argument" placeholder.  Clearly that provides no useful information, and is only there because the docstring style guide says a description is needed.  For a function such as `gamma` in #7148, I couldn't think of anything that added useful information, so I just left out the description.

For the return value, I went back to the documentation of the numpy docstring format at https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt, where I found that providing a *name* for the return value is optional:

```
5. Returns

Explanation of the returned values and their types. Similar to the Parameters section,
except the name of each return value is optional. The type of each return value is always
required:

Returns
-------
int
    Description of anonymous integer return value. 
```
That makes a lot of sense for a function that returns a single item, so that's what I used in #7148.

**Comment by person142** [comment]
> where I found that providing a name for the return value is optional

That's good to know. I think some going through the `special` docstrings and deleting bogus return array names is in order...

**Comment by rgommers** [comment]
> deleting bogus return array names is in order...

Agreed. The optional part has only been understood by numpydoc for 4 years, and I suspect a lot of the return names predate that.

**Comment by rgommers** [comment]
> In particular it says the return value is an ndarray, which isn't true for scalar inputs. This is common in the module.

Should be ``scalar or ndarray`` I guess.

> This includes extra type information on the first row and is a common variant in the module, but I seem to recall that @rgommers didn't like this style.

I think it's hard to make things consistent when adding things like "real or complex" or shape information (as is common in ``signal``). So my preference is to put those things in the description if they're important.
