### ISSUE TITLE
A change in `numpy.poly1d` is causing the scipy tests to fail. 

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#7181]
See https://github.com/numpy/numpy/pull/8762

**Comment by person142** [comment]
Grumble grumble more evidence that `orthopoly1d` should be deprecated grumble grumble... ;-)

**Comment by eric-wieser** [comment]
Does https://github.com/numpy/numpy/pull/8788 fix this?

**Comment by person142** [comment]
> Or perhaps just poly1d in general

I guess SciPy is a (the?) blocker for that, and at least in the case of `orthopoly1d` we couldn't come to a consensus on what to replace it with (https://github.com/scipy/scipy/pull/6591).

**Comment by charris** [comment]
New errors in the `_scale` method. Basically, `orthopoly1d` is effed up beyond all repair, e.g., fubar.

**Comment by eric-wieser** [comment]
> at least in the case of orthopoly1d we couldn't come to a consensus on what to replace it with

I think an interim solution would be just to derive it from `np.polynomial.PolynomialBase` rather than `np.poly1d`

**Comment by ev-br** [comment]
So if we want to deprecate `np.poly1d`, and if scipy is a blocker, then how about

- [ ] Rewrite internal uses of `poly1d` in terms of `np.polynomial`s (some in scipy.stats, also in signal)
- [ ] Provide alternatives to functions which return `np.poly1d` objects (`interpolate.approximate_taylor_polynomial`, `interpolate.lagrange`, `pade`) and deprecate the originals.
- [ ] Reconsider `orthopoly1d`. Josh @person142 do you have a suggestion of how to deal with orthopoly1d?

**Comment by person142** [comment]
I still advocate getting rid of it and not replacing it (instead pointing users to NumPy). I doubt that will fly, however, so it would be nice to see a proposal from someone who wants a replacement detailing what object they want, how it will avoid the unsafe numerical things done in `orthopoly1d`, and how it will avoid overlap with NumPy functionality.

Given a concrete proposal I'm willing to do the leg work of actually creating the replacement so that we can deprecate `orthopoly1d`.

**Comment by pv** [comment]
I agree getting rid of it. A proper replacement is probably nontrivial amount of work, but adding one might have some value given numpy only has the most common polynomials. Probably, a replacement should somehow look similar to what numpy does.

**Comment by person142** [comment]
I guess I wonder whether the right thing to do is to add more polynomial types to numpy or to essentially copy the numpy design in special for the more exotic types.

**Comment by charris** [comment]
The numpy classes work well for the polynomials whose weights have compact support, I am less happy with their implementation of polynomials whose weights go out to infinity in either direction. I think it would not be difficult to implement Gegenbauer and Jacobi polynomial series. The question is if you want to preserve some extra functionality, say the implementation of normalized polynomial series, which could be useful. Or indeed, if you want to have the series implementations at all. Note that one advantage would be easy conversions between series basis.

A simpler solution would be to use Chebyshev polynomials instead of power series for the Jacobi and Gegenbauer polynomials. They would be easy to compute using the Chebyshev points to sample the functions. Indeed, I've been thinking of adding a `fromfunction` method that would make it even easier.

**Comment by pv** [comment]
I would prefer an approach that avoids duplicating work already in Numpy.
.
Also, it could be interesting to look into barycentric polynomials and 
rational functions. chebfun probably won't be beaten with our resources, 
but some basic essentials could be added.

**Comment by person142** [comment]
> Or indeed, if you want to have the series implementations at all

I do wonder about this. I don't really know of any applications that use Gegenbauer or Jacobi polynomial series. But there's a lot I don't know, so maybe someone else does? If there aren't any it's probably not worth going to the effort.

**Comment by pv** [comment]
This was fixed.
