### ISSUE TITLE
Can gaussian_kde be extended to handle weighted data points?

### ISSUE THREAD

**Issue by AllenDowney** [scipy/scipy#7207]
Suppose I have a normalized PMF instead of a sample.  It seems like KDE can be generalized to handle this scenario, and it seems like it should be easy to implement.

@rkern , have you considered this use case?

(I'm not sure how bandwidth selection would work in this case, if we don't know the sample size.)

**Comment by rkern** [comment]
Yes, mechanically evaluating the PDF is quite straightforward in the weighted case once you have the kernels. I don't know what other KDE packages do in this case for bandwidth selection.

**Comment by AllenDowney** [comment]
Ok, I'll see what I can do, and possibly send a PR.

**Comment by aarchiba** [comment]
I've looked into this in the circular case, where what I had was empirical
Fourier coefficients instead of data points. If your bandwidth selection
algorithm is based on the expected mean integrated squared error, you can
probably just drop in the uncertainties on the (in this case) bin values
where you would ordinarily have root-n terms. Of course you need to look
carefully at the derivation of the bandwidth selection procedure, but
usually you can identify where the number of points is used to estimate an
uncertainty and drop in your measured uncertainties.

Also, to clarify: when you say "weighted data", what do you mean? Do you
mean, you have binned your raw samples and know the number in each bin, or
(normalized) the fraction in each bin plus an uncertainty (root n?) ?
There's another case that comes up, for example with Fermi data: we have a
largish collection of data points, but associated to each one is a
(possibly) small chance that it is actually part of the sample. (For
example, if you see a point source against a background, the probability
that any given photon is from the source is going to depend on how close it
is to the center of the beam and on the relative brightnesses of the source
and background. You could then want to ask, are these photons uniformly
distributed in pulse phase? Obviously the ones that are 90% likely to be
from your source weigh more than the ones that are 1% likely, but the
latter are a lot more common.)  This second case, probability-weighted
photons, is a bit tricky to work with, but in fact there's a natural way to
adapt a circular kernel density estimator (with a sinc kernel) to it - you
compute uncertainties on each of the empirical Fourier coefficients and use
these in place of root-n to determine how many coefficients are worth
using. (This underlies the H test for periodic modulation and is used to
search for pulsars in gamma-ray data.)

Anne

**Comment by lstagner** [comment]
I would very much like to have this feature

There is an incomplete implementation done by @tillahoffmann

http://stackoverflow.com/questions/27623919/weighted-gaussian-kernel-density-estimation-in-python

Notebook:
http://nbviewer.jupyter.org/gist/tillahoffmann/f844bce2ec264c1c8cb5
