### ISSUE TITLE
Source tarball distribution

### ISSUE THREAD

**Issue by marv** [scipy/scipy#7239]
Hey!

While packaging the latest scipy version for Exherbo I noticed that
 - pypi.org only provides the sources as zip file now (used to have tar.gz as well)
 - the github releases lack some files (e.g. the whole benchmarks/ directory, runtests.py, site.cfg.example etc.)

I would appreciate if someone could comment whether the distribution of tarballs exclusively on github is intentional and why the releases don't include the mentioned files

Thanks in advance and best regards,
Marvin

**Comment by ev-br** [comment]
> While packaging the latest scipy version for Exherbo I noticed that
>
> pypi.org only provides the sources as zip file now (used to have tar.gz
as well)

This is a recent pypi change where they only allow a single sdist, and I
uploaded the zip archive. Is there a strong preference for a tar.gz
instead?)

> the github releases lack some files (e.g. the whole benchmarks/
directory, runtests.py, site.cfg.example etc.)

There are two tarballs on gh releases: an autogenerated checkout from the
release tag, and the "binary" tar.gz, generated by `$ make dist` at the
release time. The former requires Cython as a build-time dependency to
generate the .c sources.

Cheers,
Evgeni

> I would appreciate if someone could comment whether the distribution of
tarballs exclusively on github is intentional and why the releases don't
include the mentioned files

**Comment by rgommers** [comment]
> Is there a strong preference for a tar.gz instead?)

I think the sdist won't be used much on Windows, and for Linux and OS X ``tar.gz`` is preferable.

**Comment by andyfaff** [comment]
.tar.gz shades it for me.

**Comment by rgommers** [comment]
Don't think we can/should change this for 0.19.0 anymore, so marked it 1.0

**Comment by rgommers** [comment]
gh-7768 updates the "how to release" documentation to say to upload .tar.gz to PyPI. Nothing else to do, so closing this.
