### ISSUE TITLE
ENH: Implement Chandrupatla's algorithm for root finding (simpler/faster than Brent's) in scipy.optimize

### ISSUE THREAD

**Issue by jason-s** [scipy/scipy#7241]
I would like to propose adding Chandrupatla's algorithm to the list of scalar root-finding methods in scipy.optimize.

You are welcome to use my implementation `chandrupatla()` as a starting point, as described in [my article on the subject](https://www.embeddedrelated.com/showarticle/855.php). I would offer to submit a pull request, but I have so much time debt in my life right now that I cannot commit to anything beyond superficial guidance.

**Comment by charris** [comment]
Interesting. Note that Brent's method also uses inverse quadratic interpolation, so there must be something more subtle than the choice of interpolater for the improved performance of Chandrupatla's algorithm.

**Comment by jason-s** [comment]
>so there must be something more subtle than the choice of interpolater for the improved performance of Chandrupatla's algorithm

Actually from what I have read that is exactly the issue -- Chandrupatla's method appears to try more aggressively to use IQI whenever it can.

I have no idea why this algorithm isn't more widely known. I found it by accident; I wanted to implement Brent's algorithm as an exercise, but it was complicated enough that I wasn't sure I could do it, and while doing research into Brent's, I ran across some references to Chandrupatla's method.

**Comment by jason-s** [comment]
I did get a copy of Chandrupatla's original article and he says this:

>Brent has built into his algorithm an
interval reduction strategy, which guarantees that the
number of function evaluations never exceed more than
three times that of bisection. Tests showed that such a
strategy is not necessary in the present algorithm.
Function 7 discussed by Brent is shown to exhibit
sublinear convergence. The number of function evalua-
tions in this case is somewhat higher than that of
bisection, but significantly lower than Brent’s algorithm.

>The last two functions 8 and 9 involve exponential terms
with terms containing x in the denominator. For the
various intervals tried, the new algorithm outperforms
the other two. In conclusion, we may state that the
application of a rigorous condition for inverse inter-
polation and a consistent three-point strategy has led to
a simple algorithm which has an efficient, reliable and
robust performance.

![image](https://cloud.githubusercontent.com/assets/738893/24528615/2eba3bcc-155c-11e7-950a-292cb8936250.png)

**Comment by charris** [comment]
I'm in favor of adding this, if only because it seems that it might have a simpler strategy. I think our current implementation of brent also loses one or two ulps of ultimate precision.

**Comment by mikofski** [comment]
@hjstein looks like there's support for adding `chandrupatla` and your vectorized approach could be useful to a lot of people. Are you interested in submitting a PR? Perhaps together with @jason-s ? If you are please send a post to the [SciPy-dev mailing list](https://mail.python.org/mailman/listinfo/scipy-dev) which is where new topics are formally proposed according the [dev guide](https://docs.scipy.org/doc/scipy/reference/dev/index.html) I think. Thanks again for your contribution!

**Comment by mikofski** [comment]
cross reference #7242

**Comment by SimpleArt** [comment]
In my experience, Chandrupatla's algorithm is indeed superior to Brent's. I wish to also point out that it's possible to generalize Chandrupatla's algorithm to [very similar algorithms](https://github.com/SimpleArt/solver/wiki/Methods#quadratic-safe). Although the test cases I have collected from various papers suggest that these variations may converge faster, this may be due to the test cases used (I would expect them to be equally good in theory), inverse quadratic interpolation has the advantage of fast/simple arithmetic operations. Regardless, having both may be useful in the same way `brenth` may be useful.

Note also that the linked code uses several other things on top of the specific algorithm, including a modification of the Illinois algorithm similar to the one used in the TOMS algorithm 748 to force bounds to tighten, and a complicated variation of [bisection](https://github.com/SimpleArt/solver/wiki/Binary-Search) for rapidly reducing relative error as well as absolute error.

**Comment by SimpleArt** [comment]
> 
> 
> > so there must be something more subtle than the choice of interpolater for the improved performance of Chandrupatla's algorithm
> 
> Actually from what I have read that is exactly the issue -- Chandrupatla's method appears to try more aggressively to use IQI whenever it can.

It's actually quite the opposite, Chandrupatla's method is less aggressive than Brent's method with IQI. Brent's method follows a "always try, then see how well it does" policy, while Chandrupatla's method follows a "try if it looks good" policy. This often means Brent's method will try to interpolate several iterations before jumping to bisection. A good example is 1 - x<sup>-10</sup> with an initial bracket of [10<sup>-10</sup>, 10<sup>10</sup>]. The advantage of Brent's method is it has a safety net where bisection is forcefully used if convergence is too slow repeatedly, whereas Chandrupatla's method lacks a slowest case convergence (as far as I know) (this can be fixed, recommendably along the lines of TOMS algorithm 748).

A more visual representation of Chandrupatla's method can be found [here](https://github.com/SimpleArt/solver/wiki/Methods#chandrupatla).

**Comment by fancidev** [comment]
> Chandrupatla's method lacks a slowest case convergence (as far as I know) (this can be fixed, recommendably along the lines of TOMS algorithm 748).

@SimpleArt Interesting point. I searched the Internet but could not find any result about the worst-case performance of Chandrupatla’s method. I think it would be a useful property if a general purpose solver could guaranteed convergence (e.g. within a constant multiple of the number of function evaluations required by bisection).

Would you by chance have a (possibly contrived) test function where Chandrupatla’s method converges slowly?

And could you elaborate how convergence could be guaranteed “along the lines of TOMS 748”? Do you mean for example taking a bisection step if a few consecutive inverse quadratic interpolation steps fail to tighten the bracket sufficiently?

**Comment by SimpleArt** [comment]
> @SimpleArt Interesting point. I searched the Internet but could not find any result about the worst-case performance of Chandrupatla’s method. I think it would be a useful property if a general purpose solver could guaranteed convergence (e.g. within a constant multiple of the number of function evaluations required by bisection). This may also be relevant for the upcoming Chandrupatla routine in xsf ([gh-21454](https://github.com/scipy/scipy/pull/21454)).

Chandrupatla's method can, in theory, converge arbitrarily slow in the worst case. This can be stolen from the analysis of the worst case convergence from Brent's method since both methods use the same interpolation method.

From [Wikipedia](https://en.wikipedia.org/wiki/Brent%27s_method):

> Brent proved that his method requires at most $N^2$ iterations, where $N$ denotes the number of iterations for the bisection method.

The theory behind this is that in the worst case, Brent's method performs a series of interpolation steps without significantly reducing the size of the bracketing interval (i.e. repeated estimates on one side with little progress) until one of Brent's conditions is reached to force a bisection iteration to guarantee the bracketing interval closes in. There are 2 conditions for this to occur:

1. The function gets really close to looking like it has a root, but it doesn't.
2. The higher order derivatives play out in a way such that inverse quadratic interpolation is guaranteed to only produce estimates on one side of the near-miss root.

In the case of Brent's method, Brent's conditions guarantee that a bisection iteration must be performed once there isn't sufficient progress concerning the x-distance traversed each iteration. In the case of Chandrupatla's method, there are no guarantees, meaning Chandrupatla's method could in theory spend an arbitrarily amount of iterations zooming onto a point that isn't actually a root but just happens to be very close to 0 before getting close enough to realize it needs to use bisection to find the real root guaranteed by the bracketing interval.

---

> Would you by chance have a (possibly contrived) test function that shows Chandrupatla’s method converges slowly?

I don't, you might be able to find such a test case researching Brent's method though.

---

> And could you elaborate how convergence could be guaranteed “along the lines of TOMS 748”? Do you mean for example taking a bisection step if a few consecutive inverse quadratic interpolation steps fail to tighten the bracket sufficiently?

No, and this is where bracketing methods get tricky. It comes down to a fundamental nature of exact interpolation methods like inverse quadratic interpolation. Assuming non-pathological functions and the asymptotic case, interpolation methods will either produce estimates that are slightly to the left of the root or slightly to the right of the root. Depending on higher order derivatives at the root, a particular function will either have ALL iterations produce estimates to the left, ALL iterations produce estimates to the right, or some periodic oscillation between the two.

The most famous example of this behavior actually occurs in a much simpler algorithm: regula falsi. Try it on $y=\arctan(x)$ and you will quickly find that no matter what your starting points are, regula falsi is guaranteed to oscillate, resulting in very fast convergence and a bracketing interval that converges fast. Try it on $y=\log(x)$ and you will quickly find that no matter what your starting points are, regula falsi is guaranteed to only produce estimates on the right side of $x=1$, resulting in very slow convergence.

The same exact behavior occurs in higher order interpolation methods, meaning that even when Brent's method or Chandrupatla's methods converge, their bracketing intervals are not guaranteed to tighten at all. This is usually handled, from what I've seen, by forcing a minimum step size based on the desired error tolerance (no point in having the next root estimate be `1e-15` away from the previous root estimate if the root needs to be estimated with `1e-10` error).

In short, both Brent's method and Chandrupatla's method use 2 types of iterations: "root estimates" and "worst case bracketing". TOMS 748 adds 1 more type of iteration: "bracketing estimates". An example is step 6 of algorithm 4.1, which estimates the root using regula falsi but *doubles* the distance from the nearest bracketing point. The purpose of this iteration is neither to actually estimate the root nor is it to catch the worst case for convergence. Instead, the purpose of this iteration is produce something that is estimated to improve the bracketing interval with high asymptotic order of convergence.

This means that when the "root estimates" are accurately converging to the root but the bracketing interval is not tightening at all, rather than relying on bisection as the only means for tightening the bracketing interval, TOMS 748 proposes the use of other methods that can be expected to tighten the bracketing interval significantly faster if the root is accurately estimated on the other side.

A significantly simpler variation of everything I described also exists: the Illinois method. This method has "root estimates" and "bracketing estimates", but does not have "worst case bracketing" and thus can converge arbitrarily slow. This means for functions which are not pathological, the Illinois method can actually perform better than Brent's method or Chandrupatla's method in terms of the speed that the bracketing interval is guaranteed to tighten.
