### ISSUE TITLE
Segfault in daily testing

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#7262]
This just a marker in case this is hard to reproduce.

We're running daily wheel builds on the `daily` branch of MacPython/scipy-wheels:

https://travis-ci.org/MacPython/scipy-wheels/branches

Last night, there was a segfault on the macOS / Python 3.6 build:

https://travis-ci.org/MacPython/scipy-wheels/jobs/218374427

I'll turn up verbosity on the tests to give more detail on the next run.

**Comment by ilayn** [comment]
While we are at it about building problems coud you please chime in for the Accelerate issue at https://github.com/scipy/scipy/pull/6051 ? It would be nice to have your opinion as you are building SciPy day in day out with MacOS.

**Comment by matthew-brett** [comment]
Rerunning the tests just now does not reproduce the segfault.  All the code merged since the run with the segfault is in docstrings, so I suspect this is an intermittent problem.

**Comment by ev-br** [comment]
I wonder if there's use for switching on the python's faulthandler, https://docs.python.org/3/library/faulthandler.html for nightly builds and/or bumping the verbosity level.

**Comment by matthew-brett** [comment]
I bumped the verbosity level to 3 already - and I just now enabled the Python fault handler - let's see what comes up.

**Comment by matthew-brett** [comment]
Verbose run shows segfault again, now on Python 3.5 

https://s3.amazonaws.com/archive.travis-ci.org/jobs/218792747/log.txt

```
test_kdtree.test_random_compiled.test_points_near_l1 ... config.sh: line 50: 12749 Segmentation fault: 11  python -c "$test_cmd"
```

**Comment by ev-br** [comment]
@sturlamolden @rainwoodman any ideas what this might be?

**Comment by rainwoodman** [comment]
I will take a look with valgrind. Is this the head of master or a tag?

On Apr 5, 2017 11:16 AM, "Evgeni Burovski" <notifications@github.com> wrote:

@sturlamolden <https://github.com/sturlamolden> @rainwoodman
<https://github.com/rainwoodman> any ideas what this might be?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/scipy/scipy/issues/7262#issuecomment-291949405>, or mute
the thread

**Comment by matthew-brett** [comment]
The `daily` branch (where we've seen the segfaults) always builds the latest scipy master.

**Comment by rainwoodman** [comment]
The fix is in. Sorry for the segfault!

**Comment by rainwoodman** [comment]
Here is the valgrind log ran with the stock Python 2.7 from Fedora, after 7262.

[log.txt](https://github.com/scipy/scipy/files/910913/log.txt)

A few jumps in the special functions depend on uninitialized values -- could be an issue in test cases?

The alarming one is an invalid read due to numpy (unlikely scipy related)

**Comment by person142** [comment]
> A few jumps in the special functions depend on uninitialized values -- could be an issue in test cases?

Probably an issue in `specfun`, which has been known to do such things.
