### ISSUE TITLE
SLSQP crashes during scipy.optimize.minimize if equality constraint is always 0

### ISSUE THREAD

**Issue by przemyslslaw** [scipy/scipy#7314]
I provide minimal reproduction code below. In the case that the constraint function is always zero, shouldn't the optimization problem be equivalent to the unconstrained problem? I guess it's a matter of adding some trivial condition in the `scipy.optimize.minimize` before evaluating the constraint?

    def my_constraint_fun(x): return 0
    constraints = { "type":"eq", "fun":my_constraint_fun,"args":[x] }
    
    scipy.optimize.minimize(
             fun = my_objective_fun,
             x0 = np.random.rand( x.shape[1] ),
             constraints=constraints,
             method = 'SLSQP',
             options={"disp":True}
             )

Result:

    Singular matrix C in LSQ subproblem    (Exit mode 6)
                Current function value: 14181.374196
                Iterations: 1
                Function evaluations: 5
                Gradient evaluations: 1

The reason I'm reporting this is because this can be confusing for a user if the user doesn't check whether the method converged or not and just tries to use the optimization result as if it was correct.

**Comment by felixlen** [comment]
@przemyslslaw For the SLSQP algorithm to work, the optimization problem at hand has to satisfy a [Constraint Qualification](https://en.wikipedia.org/wiki/Karush%E2%80%93Kuhn%E2%80%93Tucker_conditions#Regularity_conditions_.28or_constraint_qualifications.29) . The problem is lacking such a constraint qualification (the jacobian matrix is identically zero in that example), so this problem and the unconstrained problem are not equivalent in a mathematical sense and there is no reason to expect that SLSQP works.

**Comment by mdhaber** [comment]
The provided code is not executable because `my_objective_fun` is not defined, `my_constraint_fun` is passed `args` that it doesn't accept, and `x` is not defined. I tried filling in the blanks, and I do not observe a crash.

```python3
from scipy import optimize

def my_objective_fun(x): 
    return x**2

def my_constraint_fun(x): 
    return 0

constraints = { "type": "eq", "fun": my_constraint_fun}

optimize.minimize(fun = my_objective_fun, x0 = 10, constraints=constraints,
                  method = 'SLSQP')
```

I get:
```
 message: Singular matrix C in LSQ subproblem
 success: False
  status: 6
     fun: 100.0
       x: [ 1.000e+01]
     nit: 1
     jac: [ 2.000e+01]
    nfev: 2
    njev: 1
```
`optimize.minimize` exits gracefully with `success: False`.

As the comment above notes, the optimizers are developed to solve certain classes of problems, and I agree with the comment that we cannot expect SLSQP to work here.

> The reason I'm reporting this is because this can be confusing for a user if the user doesn't check whether the method converged or not and just tries to use the optimization result as if it was correct.

The user does need to check to see whether the solution was successful because some problems have no feasible solution, and furthermore, the optimizers are not guaranteed to solve all problems, even if a solution does exist.

> I guess it's a matter of adding some trivial condition in the scipy.optimize.minimize before evaluating the constraint?

I do not think we need to add a special case to solve problems of this form, in which the constraint is, by construction, exactly satisfied for all `x`. Eliminating the constraint from the problem, we get the correct solution:

```python3
 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 0.0
       x: [ 0.000e+00]
     nit: 2
     jac: [ 1.490e-08]
    nfev: 5
    njev: 2
```

So I'll go ahead and close.
