### ISSUE TITLE
faster cho solve

### ISSUE THREAD

**Issue by Joshuaalbert** [scipy/scipy#7329]
Dear Scipy,
I have faster cho_solve. 
It is the same performance as scipy.linalg.cho_solve at smaller array size <1000
And get at least 2x faster performance at larger sizes.
In fact I find that for scipy's cho_solve `log10(t) propto 2.3 * log10(N)` and for mine `log10(t) propto 1.3 * log10(N)`.

You can see the corresponding code here:
https://gist.github.com/Joshuaalbert/2dc8d4797971a896d0f77fd627b53d62

**Comment by ilayn** [comment]
I'm almost sure that you can't beat lapack with a while loop. So it must be again either the check finite stuff or get_lapack_funcs is eating up the performance. Could you please test also directly with `scipy.linalg.lapack.dpotrs` with float arrays ? This was also in another issue and we forgot it I guess.

**Comment by Joshuaalbert** [comment]
@ilayn 
Here is the modified code to use dpotrs and the same result comes.
https://gist.github.com/Joshuaalbert/c394c44c4ffec6ea48780cf63294126d

I compare both with no_b_modify, i.e. both mine and dpotrs must do a memory allocation - though this is not where most time is spent for large N.

**Comment by Joshuaalbert** [comment]
I have tested now for when the right hand side is a matrix and find that in general above a certain array size mine is still faster however the size at which mine supersedes lapack get higher as the number of columns in RHS increases. In this case my backsubstitution becomes dominated by the outerproduct required. 

But most perplexing is that lapack is slower than my implementation at all.

**Comment by Eric89GXL** [comment]
Have you considered numerical stability? I wonder if the LAPACK version is more stable.

**Comment by Joshuaalbert** [comment]
This is not something I'm prepared to address but my intuition is that stability is not the issue here. 
My belief about the stability is that based on the conditioning of the system which means the closer `max(eigen(L))/min(eigen(L))` is to one, the less sensitive the backsubstitution is to small differences in the input.
That is something independent on how the back substitution is performed. But I have no idea if there are other types of stability that lapack addresses. 
But in general people use Cholesky decomposition to improve stability as well as efficiency.

**Comment by ilayn** [comment]
I've revisited this and this is the result for n = 5000 and m=1 with the current versions of numpy and scipy (openblas 3.4.0) we have this. 
![image](https://user-images.githubusercontent.com/1303842/50447392-26b9f980-091b-11e9-822e-e925910d787d.png)

Hence carrying over the data through f2py catches on but then you can simply turn on the overwrite data and get comparable results. But main problem is that if m gets bigger instead of 1 this custom one starts to get numerically unstable for relatively small m (tested up to ~50) compared to n.
 
Since this is kind of a edge case where we get the benefit from, this is a won't fix for now.
