### ISSUE TITLE
SciPy Hypergeometric function hyp2f1 producing infinities

### ISSUE THREAD

**Issue by girishk89** [scipy/scipy#7340]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
The SciPy hypergeometric function special.hyp2f1 seems to be producing infinities for instances where third argument is negative, and fourth argument is complex. The corresponding implementation in MATLAB gives reasonable finite outputs. See for instance,

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```
In [2]: special.hyp2f1(-2,-3,-19,3.4+0.4j)
Out[2]: (inf+0j)

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
scipy version: 0.19.0

<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by FormerPhysicist** [comment]
This issue is caused by code in both `specfun_wrappers.c` and `specfun.f` that immediately return `inf` whenever c is a negative integer *without* checking if a or b is a negative integer smaller in magnitude than c (in which case the hypergeometric function is a well defined polynomial).

Since I'm working on hypergeometric function at the moment, I can do a quick PR that fixes this issue.

**Comment by FormerPhysicist** [comment]
A related bug is that hyp2f1 will attempt to calculate a value when c=0 and will return nan+nan*1.j instead of inf...
