### ISSUE TITLE
scoreatpercentile `limit` and `axis` argument cannot be used together (ValueError: axis out of bounds)

### ISSUE THREAD

**Issue by gerritholl** [scipy/scipy#7342]
When trying to use `scoreatpercentile` arguments `limit` and `axis` together, a `ValueError` results as indicated below:

### Reproducing code example:
```
In [103]: data = arange(5*6).reshape(5, 6)

In [104]: scipy.stats.scoreatpercentile(data, 50, axis=1)
Out[104]: array([  2.5,   8.5,  14.5,  20.5,  26.5])

In [105]: scipy.stats.scoreatpercentile(data, 50, limit=(10, 20), axis=1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-105-2b59a2b5dd27> in <module>()
----> 1 scipy.stats.scoreatpercentile(data, 50, limit=(10, 20), axis=1)

/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/scipy/stats/stats.py in scoreatpercentile(a, per, limit, interpolation_method, axis)
   1584         a = a[(limit[0] <= a) & (a <= limit[1])]
   1585
-> 1586     sorted = np.sort(a, axis=axis)
   1587     if axis is None:
   1588         axis = 0

/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/numpy/core/fromnumeric.py in sort(a, axis, kind, order)
    820     else:
    821         a = asanyarray(a).copy(order="K")
--> 822     a.sort(axis=axis, kind=kind, order=order)
    823     return a
    824

ValueError: axis(=1) out of bounds
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=5, micro=0, releaselevel='final', serial=0)

```

**Comment by cdouglass** [comment]
Just to confirm, is the desired behavior equivalent to what you'd get by (1) replacing all out-of-limits values with `NaN` and (2) applying `numpy.nanpercentile` to the result?

Cause of current behavior: When a `limit` argument is given, `scoreatpercentage` produces a 1D array of all values within the limit and then goes on as it normally would (so that `axis > 0` will be out of bounds on that 1D array). The `axis=0` case with a limit appears to behave the same as `axis=None` rather than throwing an error, so a warning would be needed if this is fixed.

**Comment by rgommers** [comment]
> Just to confirm, is the desired behavior equivalent to what you'd get by (1) replacing all out-of-limits values with NaN and (2) applying numpy.nanpercentile to the result?

That sounds right to me. 

Note that ``nanpercentile`` was introduced in numpy 1.9.0 and scipy currently supports >= 1.8.2. See also the extended discussion on ``nanpercentile`` and ``percentile`` behavior in the Notes section of the ``stats.iqr`` docstring.

We can consider bumping the minimum numpy version to 1.9.x if this gets annoying to fix.

**Comment by Baschdl** [comment]
Shouldn't we reference the discussion in the Notes section of the `stats.iqr` docstring in the docstring of `stats.scoreatpercentile`? Otherwise it's confusing when just reading the docstring of `stats.scoreatpercentile` and even misleading because a comment in the method is 

> When we require numpy >= 1.8, the implementation of this function can be replaced by np.percentile.

But after the discussion in `stats.iqr` that's not true.
