### ISSUE TITLE
netcdf_file fails to open file netCDF4 is able to

### ISSUE THREAD

**Issue by thehesiod** [scipy/scipy#7344]
with this file https://madis-data.cprk.ncep.noaa.gov/madisPublic1/data/archive/2007/09/12/LDAD/mesonet/netCDF/20070912_0600.gz

you'll get a ValueError from netcdf.py on line: https://github.com/scipy/scipy/blob/master/scipy/io/netcdf.py#L703

**Comment by sethtroisi** [comment]
the file 20090912_0600 is one byte short; if I append a 0 byte (with hexedit) then it reads correctly.
I'm closing because this seems to be an issue with the underlying file.

I'm not sure why netCDF4 is able to read it (maybe it pads to a multiple of 4 bytes or something).
If more people see `ValueError: buffer size must be a multiple of element size` then we can reopen and investigate padding...
