### ISSUE TITLE
code examples in the docs built on python 3.5 lack the prompt fold thingy

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#7369]
A local build of the documentation with python 3.5 does not have a helpful toggle for folding the `>>>` prompts.

![screenshot from 2017-05-03 01 06 27](https://cloud.githubusercontent.com/assets/2133832/25641597/9a99c03c-2f9d-11e7-9b10-421704221256.png)

A similar build on python 2.7 has it.

The build is done via `$ python runtests.py -g --shell -- -c 'make -C doc html-scipyorg'` in a fresh virtualenv with python 3.5:

```
$ pip freeze
alabaster==0.7.10
appdirs==1.4.3
Babel==2.4.0
cycler==0.10.0
Cython==0.25.2
decorator==4.0.11
docutils==0.13.1
imagesize==0.7.1
ipython==6.0.0
ipython-genutils==0.2.0
jedi==0.10.2
Jinja2==2.9.6
MarkupSafe==1.0
matplotlib==2.0.1
nose==1.3.7
numpy==1.12.1
packaging==16.8
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.14
ptyprocess==0.5.1
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.6.0
pytz==2017.2
requests==2.13.0
simplegeneric==0.8.1
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.5.5
traitlets==4.3.2
wcwidth==0.1.7
```

The virtualenv is literally

```
$ mkvirtualenv -p `which python3.5` scipy_py35
$ pip install --upgrade pip
$ pip install numpy nose
$ pip install ipython
$ pip install cython
```

followed by cloning and building scipy.

**Comment by pv** [comment]
check if the copybutton.js gets included and if not, why not

**Comment by CalebBell** [comment]
Hello,

I believe I'm running into this problem too. I'm commenting here because I found this bug, and also found a possible clue about this issue. While trying to get copybutton to work on my own projects, I found someone else who ran into frustration and said that [using an older build of Sphinx](https://github.com/wtak23/sphinx_skeleton/commit/62fe7a48588d2990cd0cccbcb9343f16eaeb075a#diff-ee1cb6b5b719edae4a4ff84c5b311722) (1.3.5 instead of 1.4.5) solved their problem. 
I don't have an older of version of Sphinx installed at the moment to test it, but I would like to get this fixed as I want my own docs to use have this feature as well. I've confirmed that with my version of Sphinx, 1.4.8, the problem exists. Right now I've confirmed copybutton.js is linked to in the produced html in the more recent versions of Sphinx, so that at least is not the problem. I'm not sure when I'll work on this, but I can at least leave what I found here. 

Sincerely,
Caleb
