### ISSUE TITLE
numpy.power on sparse matrix attempts to do matrix power not elementwise

### ISSUE THREAD

**Issue by seanv507** [scipy/scipy#7462]
numpy power seems to go to a matrix power routine for sparse matrices.

### Reproducing code example:
```
    import scipy.sparse as sps
    import numpy as np
    a = np.array([[1,2,3],[4,0,0]])

    np.power(a,2)

    np.power(sps.csr_matrix(a),2) # this fails 

    sps.csr_matrix(a).power(2).todense()

```

### Error message:
    Traceback (most recent call last):

      File "<ipython-input-7-513a059a6886>", line 1, in <module>
      np.power(sps.csr_matrix(a),2)

      File "/home/sean/anaconda2/lib/python2.7/site-packages/scipy/sparse/base.py", line 539, in __pow__
    raise TypeError('matrix is not square')

    TypeError: matrix is not square

### Scipy/Numpy/Python version information:
```
('0.19.0', '1.12.1', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))
```

**Comment by perimosocordiae** [comment]
This is intentional, as the spmatrix class mimics the API of `np.matrix`, not `np.ndarray`. I agree that it's not ideal, but until we get a new sparse `ndarray`-like, it's working as intended.

**Comment by WarrenWeckesser** [comment]
Even when `m` is a `numpy.matrix`, `numpy.power(m, 2)` is computed element-wise:

```
In [36]: m
Out[36]: 
matrix([[ 1,  0,  0, -1],
        [ 0,  0,  0,  0],
        [ 3,  2,  0,  0],
        [ 0,  0,  5,  0]])

In [37]: np.power(m, 2)
Out[37]: 
matrix([[ 1,  0,  0,  1],
        [ 0,  0,  0,  0],
        [ 9,  4,  0,  0],
        [ 0,  0, 25,  0]])
```

Because numpy knows nothing about scipy's sparse arrays, all it can do with them is dispatch the call to the `__pow__()` method of the argument.  And for scipy's sparse arrays, that implements matrix multiplication.  So even though the docstring for `numpy.power()` says it computes the power element-wise, once it dispatches, it has no control over the calculation.

Note, however, that sparse arrays also have a `power()` method that operates element-wise:

```
In [43]: from scipy.sparse import csr_matrix

In [44]: s = csr_matrix(m)

In [45]: s.A
Out[45]: 
array([[ 1,  0,  0, -1],
       [ 0,  0,  0,  0],
       [ 3,  2,  0,  0],
       [ 0,  0,  5,  0]], dtype=int64)

In [46]: s.power(2).A
Out[46]: 
array([[ 1,  0,  0,  1],
       [ 0,  0,  0,  0],
       [ 9,  4,  0,  0],
       [ 0,  0, 25,  0]], dtype=int64)
```
The `__pow__()` method, on the other hand, does a matrix power:
```
In [47]: s.__pow__(2).A
Out[47]: 
array([[ 1,  0, -5, -1],
       [ 0,  0,  0,  0],
       [ 3,  0,  0, -3],
       [15, 10,  0,  0]], dtype=int64)
```
`__pow__()` is the implementation of the `**` operator:
```
In [49]: (s**2).A
Out[49]: 
array([[ 1,  0, -5, -1],
       [ 0,  0,  0,  0],
       [ 3,  0,  0, -3],
       [15, 10,  0,  0]], dtype=int64)
```

Should `numpy` check for a `power()` method before attempting to use the `__pow__()` method?  I don't know, but I suspect there are (or should be) some API guidelines written down somewhere for this type of dispatching.

**Comment by perimosocordiae** [comment]
Sorry, I see that I was too hasty in my response.

Maybe this is something that the new `__array_ufunc__` logic will help clear up?

**Comment by pv** [comment]
AFAICS, `__array_ufunc__` cannot be used for sparse matrices.

**Comment by rgommers** [comment]
> AFAICS, `__array_ufunc__` cannot be retrofit on scipy's current sparse matrices, it's not compatible with the multiplication semantics and breaks backward compat.

Hmm, I'm puzzled now, didn't see that expressed before. IIRC ``__array_ufunc__`` was originally written to make ``scipy.sparse`` matrices more interoperable with ndarrays and ndarray-like types.

**Comment by mxbi** [comment]
Are there any workarounds for taking scalar powers of matrices, which avoid this bug?
