### ISSUE TITLE
Sparse Array - Explicit zeros after slicing

### ISSUE THREAD

**Issue by sverzijl** [scipy/scipy#7531]
Hi,

When I use explicit zeros in scipy sparse arrays (CSR) everything works as expected - the zero values are in the sparse array's data attribute.

When I do a row slice of the CSR sparse array the explicit zeros are no longer in the data attribute.

I think when scipy reconstructs the sparse array from the slice it drops the zeros assuming they are the same as the implicit zeros.

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=5, micro=3, releaselevel='final', serial=0)
```

**Comment by perimosocordiae** [comment]
Could you provide a short, runnable example of the behavior you're seeing?

**Comment by sverzijl** [comment]
Apologies for the late reply. In trying to find an example that replicated
it I've worked out it only happens when you use a numpy array as an index.
No issues if you do a normal slice. Only occurs when explicit value is 0,
does not occur on other values.

import scipy.sparse
import numpy as np

a = scipy.sparse.csr_matrix((100,100))
print(a.data)  #Expect [] got []
a[50,50] = 0

# 0 is explicit in it's unsliced form.
print(a.data) #Expect [0] got [0]

#0 becomes implicit when you slice with a numpy array
b = a[np.array([10,20,30,40,50,60,70])]
print(b.data) #Expect [0] got []

#0 is explicit when you do a vanilla slice
c = a[50]
print(c.data) #Expect [0] got [0]

#No issues when you set the value to 1
a[50,50] = 1
b = a[np.array([10,20,30,40,50,60,70])]
print(b.data) #Expect [1] got [1]


Thanks,

Simeon

**Comment by perimosocordiae** [comment]
Thanks! This is due to an implementation detail of how we handle "fancy" indexing for CSR/CSC sparse matrices: in many cases (including your example), we generate an "extractor" matrix `P` such that `P.dot(a)` returns the result of the slice.

You can see this in action using numpy arrays:
```python
a = np.arange(12).reshape((4, 3))
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

a[[1,3],:]
array([[ 3,  4,  5],
       [ 9, 10, 11]])

P = np.array([[0,1,0,0],[0,0,0,1]])
array([[0, 1, 0, 0],
       [0, 0, 0, 1]])

P.dot(a)
array([[ 3,  4,  5],
       [ 9, 10, 11]])
```

All this means that, unintuitively, fancying indexing results in a sparse matrix multiply, which is one of the operations that does not preserve explicit zeros. See gh-3343 for an old (but still relevant) discussion of explicit-zero handling.

I think the right solution here is to find a better way to implement fancy indexing that doesn't defer to matrix multiplication and respects explicit zeros.

**Comment by perimosocordiae** [comment]
This will be fixed by gh-7827.

**Comment by tylerjereddy** [comment]
Bumping the milestone because the cognate PR was also bumped, but it is looking optimistic for an eventual merge there.

**Comment by sethtroisi** [comment]
PR is merged, Code sample now produces expected result
