### ISSUE TITLE
Why scipy does not provide scipy.linalg.matrix_rank?

### ISSUE THREAD

**Issue by cy18** [scipy/scipy#7575]
There's a numpy.linalg.matrix_rank, why scipy does not provide scipy.linalg.matrix_rank? I think it is quite frequently used in scientific computing, which is what scipy for. 

It does not make real difference whether I import it from scipy or numpy. But I'm just curious what's the reason behind it.

**Comment by ilayn** [comment]
I don't know the reason but it's a[ very short code](https://github.com/numpy/numpy/blob/v1.13.0/numpy/linalg/linalg.py#L1568) which might have fallen under the not worth it threshold. 

It might indeed be worth to create an alias for it since NumPy is already a dependence anyhow.

**Comment by rkern** [comment]
Typically, functions are duplicated in `scipy.linalg` in order to use optimized and recent LAPACK implementations and expose extra features of those implementations. They are not duplicated just for the sake of having the same functions in both. `matrix_rank()` does not directly use a LAPACK function, so it was overlooked. However, it does use `svd()`, so it might be worth porting over so that it uses the `scipy.linalg.svd()` which might be beneficial. The difference, if numpy and scipy are both built against an optimized BLAS, is likely small, though.

**Comment by adivijaykumar** [comment]
Hey this seems pretty easy to create as an alias. Can I take this up? It
might be the perfect thing for my first non documentation fix in scipy :).


Thanks and Regards,
Aditya V

**Comment by WarrenWeckesser** [comment]
I don't see the point in just making an alias.  Robert gave a possible reason for creating a new implementation in scipy, based on `scipy.linalg.svd()`.  If folks agree that it might be beneficial, then that's what should be done.

**Comment by rgommers** [comment]
If the difference will be small, then not sure if there's much point?

**Comment by ev-br** [comment]
-0.

I also don't believe there's much point adding three-liners like this. 

While I don't have hard data, I believe that the setup where numpy uses lapack-lite and scipy links to an optimized LAPACK is rare (IOW, it's either numpy with lapack-lite and no scipy, or both are linked to an external LAPACK library). In that case adding `scipy.linalg.matrix_rank` seems to be just increasing duplication between `numpy.linalg` and `scipy.linalg` instead of decreasing it.
