### ISSUE TITLE
interpolate.splprep return SystemError

### ISSUE THREAD

**Issue by D-X-Y** [scipy/scipy#7589]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
I want to use interpolate.splprep but it returns SystemError

### Reproducing code example:
```
from scipy import interpolate
A = [-50.49072266, -50.49072266, -54.49072266, -54.49072266]
tck, t = interpolate.splprep([A])
```

### Error message:
```
*** SystemError: <built-in function _parcur> returned NULL without setting an error
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
That's a not super informative error. The issue seems to be with duplicate values in your input. This works for a single array of length 4:

    x = np.linspace(0, 40, num=4)
    interpolate.splprep([x])

4 is the minimum input length, shorter gives a reasonably informative error (could be clearer, but well):

    x = np.linspace(0, 40, num=4)
    interpolate.splprep([x])
    ....
    TypeError: m > k must hold

Looks like around [here](https://github.com/scipy/scipy/blob/master/scipy/interpolate/_fitpack_impl.py#L221) duplicate values need filtering out.

**Comment by D-X-Y** [comment]
But why duplicate values can not be interpolated? I did not understand, even the solution can become infinite with duplicate values, we can still choose one?

**Comment by ev-br** [comment]
The answer to the why questions for FITPACK based interpolation is likely somewhere in the fortran code of Dierckx, https://github.com/scipy/scipy/tree/master/scipy/interpolate/fitpack

**Comment by cdouglass** [comment]
@D-X-Y Here's the Fortran line that's causing the trouble: https://github.com/scipy/scipy/blob/master/scipy/interpolate/fitpack/parcur.f#L307 It checks that its automatically calculated `u` parameter values are strictly increasing, but consecutive duplicate points will give consecutive identical `u` values so the check fails. It's then caught in https://github.com/scipy/scipy/blob/master/scipy/interpolate/src/_fitpackmodule.c#L448, and the resulting `return NULL;` gives the unhelpful `SystemError` you saw.

`splprep` uses an array of weights defaulting to all ones, and I suspect properly handling consecutive duplicate values might need to involve adjusting that instead of just picking one.
