### ISSUE TITLE
request: is it possible to add the area/volume for each 2D/3D voronoi cell?

### ISSUE THREAD

**Issue by weiguangcui** [scipy/scipy#7604]
I have the voronoi cell information for scipy.spatial.Voronoi. But i have no idea of how to calculate the area/volume for each voronoi cell. Is it possible to add some calculations inside the function to do that?
Or any suggestion of how to get this information of the voronoi cell is welcome.
Thanks a lot!

**Comment by tylerjereddy** [comment]
I've been working on this with another postdoc in #7515. If you'd like to help with the effort / try the code/ provide feedback, this would be very welcome.

The code should already be in a decent state for handling the planar polygons from a 2D Voronoi diagram (calculating their surface areas), but it is not vectorized yet (you'd have to do one cell at a time). I / we hope to change this in the future to be faster / handle an array of cells.

For the volumes of cells from a 3D Voronoi diagram, I'd be tempted to exploit the fact that the cells should all be convex, and therefore `scipy.spatial.ConvexHull` volume attribute would likely be appropriate. I haven't thought about whether one could transplant the underlying volume calculation code directly to the `Voronoi` class for the 3d case, or if that is worth doing, but maybe. Otherwise, I guess you have to generate a hull object for every 3D Voronoi cell and then use the volume method from that, which may be rather wasteful.

Are there cases where the convex hull of a 3d Voronoi cell is not the same as the Voronoi cell itself? My intuition suggests 'no--' the convex polyhedra that are 3D Voronoi cells are valid convex hulls for the 3D vertices that define them so the same volume calculation applies. Maybe there's an exception I can't think of though.

**Comment by rgommers** [comment]
Ongoing in gh-7515, so closing this issue
