### ISSUE TITLE
Various distribution functions disobey the size parameter when it has unit dimensions

### ISSUE THREAD

**Issue by NeilGirdhar** [scipy/scipy#7689]
```
In [5]: from scipy.stats import multivariate_normal

In [7]: multivariate_normal().rvs(size=(1,)).shape
Out[7]: ()
```
All size parameters should support `None`, `()` and `(1,)` and produce shapes `()`, `()`, and `(1,)` respectively.

As mentioned below, this problem also occurs with the `wishart` and `invwishart` distribution .

**Comment by WarrenWeckesser** [comment]
@NeilGirdhar, thanks for the report.  You're right, the shape should be `(1,)` in that case.

**Comment by NeilGirdhar** [comment]
Just to help with testing:

```
In [7]: multivariate_normal(mean=np.zeros(3)).rvs(size=(1,)).shape
Out[7]: (3,)
```
should be `(1, 3)` as well.

**Comment by WarrenWeckesser** [comment]
The problem is an indiscriminate use of `squeeze`:  https://github.com/scipy/scipy/blob/master/scipy/stats/_multivariate.py#L652

**Comment by WarrenWeckesser** [comment]
`wishart` and `invwishart` have the same problem.

**Comment by JDkuba** [comment]
@WarrenWeckesser 
Hi, I have a question about this issue. As far as I understand, the problem occurs only if there is `1` in the `size` tuple. If so, `_squeeze_output` removes `1`, which is undesirable behavior.

But still, we don't want to return output without squeezing it, because the dimension of a random variable may have `1`, which should be squeezed. Am I right?

**Comment by WarrenWeckesser** [comment]
@JDkuba, sorry for not responding sooner.

I think it was a mistake for `squeeze` of any of the dimensions to have been included in the code.  The following explains how I think it should behave, but we may have some problems now with maintaining backwards compatbility with released code.

When generating samples for a multivariate distribution, the input values completely determine the output shape.  There should never be any need for `squeeze`.  For example,  the shape of `mutivariate_normal.rvs([3], size=n)` for any nonnegative integer `n` should be `(n, 1)`.

More generally, for nonnegative integers `m` and `n`, `mutivariate_normal.rvs(np.zeros(m), size=n)` should have shape `(n, m)`.  Neither of those dimensions should be squeezed if they happen to be 1.  Note: this is exactly how NumPy's `multivariate_normal` distribution works:

```
In [41]: rng = np.random.default_rng(123)

In [42]: m = 2

In [43]: n = 5

In [44]: rng.multivariate_normal(mean=np.zeros(m), cov=np.eye(m), size=n).shape
Out[44]: (5, 2)

In [45]: m = 1

In [46]: n = 1

In [47]: rng.multivariate_normal(mean=np.zeros(m), cov=np.eye(m), size=n).shape
Out[47]: (1, 1)
```

The only time we don't have a dimension associated with `size` is when `size` is `None`:
```
In [50]: m = 3

In [51]: rng.multivariate_normal(mean=np.zeros(m), cov=np.eye(m), size=None).shape                                                                        
Out[51]: (3,)

In [52]: m = 1                                                                                                                                            

In [53]: rng.multivariate_normal(mean=np.zeros(m), cov=np.eye(m), size=None).shape                                                                        
Out[53]: (1,)
```

If there is agreement that this is how the `rvs()` method *should* work, the question then is can we consider the current behavior a bug that can be fixed?  Or are we now constrained to maintain backwards compatbility?

**Comment by JDkuba** [comment]
Fine, thank you for your explanation. 
Could you close my PR then?

**Comment by rlucas7** [comment]
@WarrenWeckesser FWIW I would consider the behavior you are describing as a bug in the multivariate normal implementation.

**Comment by NeilGirdhar** [comment]
@rlucas7 You mean the scipy one or the numpy one?

**Comment by rlucas7** [comment]
@NeilGirdhar I was referring to the SciPy behavior. From what I understood from Warren's post the behavior in SciPy for some edge cases is where the erroneous behavior lies, e.g. from this squeeze
https://github.com/scipy/scipy/blob/a1dbf0fd0794ad90d611341e30b8ade7ad2b30cc/scipy/stats/_multivariate.py#L661
To be clear I was agreeing and commenting on my opinion with Warren's comment:

> When generating samples for a multivariate distribution, the input values completely determine the output shape. There should never be any need for `squeeze`. For example, the shape of `mutivariate_normal.rvs([3], size=n)` for any nonnegative integer `n` should be `(n, 1)`.
and the latter comment in the same post: 

> More generally, for nonnegative integers `m` and `n`, `mutivariate_normal.rvs(np.zeros(m), size=n)` should have shape `(n, m)`. Neither of those dimensions should be squeezed if they happen to be 1. Note: this is exactly how NumPy's `multivariate_normal` distribution works:

From what I understood of Warren's comment the issue resides in the squeeze in SciPy so the issue is to be fixed in SciPy.

Hope that helps clarify.

**Comment by Erotemic** [comment]
Having suffered through a major headache due to this issue, I feel compelled to vent:

I really hate the squeeze function (and any other function that causes the outputs to behave inconsistently depending subtle properties of the inputs).

**Comment by twiecki** [comment]
Ping that we went into this issue too.

**Comment by NeilGirdhar** [comment]
@twiecki You may be interested in [this version ](https://github.com/NeilGirdhar/efax/blob/master/efax/_src/scipy_replacement/multivariate_normal.py) of the distribution that does not have the above problem.

**Comment by mdhaber** [comment]
There's a little more detail here than related issues, so those will be closed, but let's keep the following in mind when addressing this:

- gh-6005
- gh-13171
- gh-14885

**Comment by NeilGirdhar** [comment]
@mdhaber Thanks for collecting the duplicates.  I've renamed the issue.

**Comment by mdhaber** [comment]
> More generally, for nonnegative integers m and n, mutivariate_normal.rvs(np.zeros(m), size=n) should have shape (n, m)

More generally, for valid `mean`, `cov`, and `size`, I'd _like_ for `multivariate_normal.rvs(mean, cov, size=size).shape` to be `size + param_shape`, where `param_shape` should be `np.broadcast_shapes(mean.shape, cov.shape[:-1])`? The only exception would be `size=None`, which should behave the same as `size=()`.

I think this would be elegant and easy to use, because `size` would not care about the dimensions of `mean` and `cov`. However, this would be somewhat inconsistent with univariate distributions, for which `size` is _not_ prepended to the dimension of the output; rather it needs to contain / be consistent with the dimension of the shape parameters.

```python3
rng = np.random.default_rng()
rng.normal(loc=np.zeros((3, 1)), scale=np.zeros(4), size=(5, 3, 4)).shape
```

Specifically, if `param_shape = np.broadcast_shapes(mean.shape, scale.shape)`, then `size[:-len(param_shape)]` must equal `param_shape`, or there will be an error.

At first glance, it appears that multivariate and univariate distribution RVS behavior is already inconsistent. 

```python3
rng = np.random.default_rng()
rng.normal(loc=np.zeros(3), scale=np.zeros(3), **size=(5, 3)**).shape  # (5, 3)
# vs
rng.multivariate_normal(mean=np.zeros(3), cov=np.eye(3), **size=5**).shape  # (5, 3)
```

However, that is not necessarily true. For RVS from multivariate distributions that are vectorized w.r.t. shape parameters, there would be three fundamentally different kinds of dimensions in the output shape:
1. Those corresponding with the dimension of a single output sample
2. Those corresponding with vectorization w.r.t. shape parameters (e.g. when RVS for multiple shape parameters are being produced simultaneously)
3. Any additional dimensions corresponding with `size` (e.g. when multiple random variates are being produced simultaneously)

Perhaps `size` always needs to include / be compatible with the dimensions corresponding with vectorization (2) but _not_ the dimension of a single output sample (1). (Weird rule, IMO, but that's the only way I can see `size` having the same meaning for existing univariate and multivariate distributions.)

In that case, perhaps the rule is that for valid `mean`, `cov`, and `size`, `multivariate_normal.rvs(mean, cov, size=size).shape` should be `size + d`, where `d` is `np.broadcast_shapes(mean.shape, cov.shape[:-1]).shape[-1:]` (and again, the exception would be `size=None`, which should behave the same as `size=()`).

Note that the purpose of `shape[-1:]` here is to make a distinction between when `mean` and `cov` are scalars (so that the multivariate distribution behaves exactly the same as the corresponding univariate distribution) and when `mean` or `cov` is an array of shape `(1,)`.

**Comment by mdhaber** [comment]
The way I'd suggest fixing the `rvs` issues would be to calculate the desired output shape `shape_rvs` according to the rule above, generate the `rvs` without distinguishing between singleton and non-existent dimensions (e.g. use Generator, which isn't very careful about this), and then at the end do:
```python3
return rvs.reshape(rvs_shape)[()]
```
`reshape` removes singleton dimensions _where appropriate_ (as determined by `shape_rvs`). `[()]` at the end converts 0-d arrays to scalars (as desired) and otherwise has no effect.

**Comment by mdhaber** [comment]
Tracking in gh-16278, along with all the other issues listed [above](https://github.com/scipy/scipy/issues/7689#issuecomment-1064579845)

**Comment by JacobHass8** [comment]
> The way I'd suggest fixing the `rvs` issues would be to calculate the desired output shape `shape_rvs` according to the rule above, generate the `rvs` without distinguishing between singleton and non-existent dimensions (e.g. using Generator, which doesn't make this distinction), and then at the end do:
> 
> return rvs.reshape(rvs_shape)[()]
> 
> `reshape` removes singleton dimensions _where appropriate_ (as determined based on `rvs_shape`). `[()]` at the end converts 0-d arrays to scalars (as desired) and otherwise has no effect.
> 
> [Apparently](https://github.com/scipy/scipy/issues/6006#issuecomment-1136794753), `pdf` and `logpdf` also squeeze the output. These can be fixed in the same way. Instead of squeezing, determine the appropriate shape from the input arrays, then `reshape` before returning.

I don't think this is the correct behavior, but it's close. Here's a helper function to determine the output shape 
```python
def _get_rvs_shape(mean, cov, size):
    mean = np.atleast_1d(mean)
    cov = np.atleast_1d(cov)

    d = np.broadcast_shapes(mean.shape[-1:], cov.shape[-1:])
    if size is None:
        size = ()
    # Do we want to do something like this so the return size is (1, d)?
    if size == ():
        size = (1)

    # .astype(int).tolist() converts type `np.int64`` to pure python `int`
    size = tuple(np.atleast_1d(size).astype(int).tolist())
    shape_rvs = size + d
    return shape_rvs
```
Then before returning the rvs output I have 
```python
shape_rvs = _get_rvs_shape(mean, cov_object, size)
out = out.reshape(shape_rvs)
return out[()]
```
Here's the output shapes
```python
import numpy as np
from scipy.stats import multivariate_normal

mean = np.zeros(3)
cov = np.eye(3)
size = (5, 6)
shape = multivariate_normal.rvs(mean=mean, cov=cov, size=size).shape # (5, 6, 3)

mean = 4
cov = 5
size = (5, 6)
shape = multivariate_normal.rvs(mean=mean, cov=cov, size=size).shape # (5, 6, 1)

mean = 4
cov = 5
size = 1
shape = multivariate_normal.rvs(mean=mean, cov=cov, size=size).shape # (1, 1)
```
I didn't follow the discussion on how scalar value outputs should be handled. Should the shape in my second to last example be (5, 6) instead of (5, 6, 1)? Similarly, should the output to my last example really just be a scalar? It seems like the output could just be squeezed before returning.

**Comment by NeilGirdhar** [comment]
@JacobHass8 This doesn't matter anymore because the new distribution infrastructure will replace this one.
