### ISSUE TITLE
sparse/dense matrix multiplication error

### ISSUE THREAD

**Issue by Albert65** [scipy/scipy#7707]
Sparse matrix time dense one is fine.
Dense matrix time sparse one cause infinite memory consumption.

### Reproducing code example:
```
# Full example.
import numpy
import scipy
import scipy.sparse
import scipy.sparse.linalg
N = 1000
H = scipy.sparse.eye(N)
P = numpy.random.rand(N,N)
HP = H.dot(P)			        # fine
PHt = P.dot(H.transpose())	# error: takes memory until computer is dead
```

### Error message:
Ubuntu 16.04/64
No message, computer just hangs up after a while running out of memory

### Scipy/Numpy/Python version information:
Ubuntu 16.04/64
Python 3.6.1    (compiled from sources)
numpy 1.12.1
scipy 0.19.0

**Comment by perimosocordiae** [comment]
I can reproduce this on Python 2.7 with ~master scipy as well. Here's a shorter repro:
```python
dense = np.random.random((1000,1000))
sparse = scipy.sparse.eye(1000)
dense.dot(sparse)
```

Interrupting after ~1 second shows the following traceback:
```
<ipython-input-4-5a672ad87881> in <module>()
----> 1 y.dot(x)

/usr/local/lib/python2.7/dist-packages/scipy-1.0.0.dev0+6fd2bc6-py2.7-linux-x86_64.egg/scipy/sparse/base.pyc in __rmul__(self, other)
    482     def __rmul__(self, other):  # other * self
    483         if isscalarlike(other):
--> 484             return self.__mul__(other)
    485         else:
    486             # Don't use asarray unless we have to

/usr/local/lib/python2.7/dist-packages/scipy-1.0.0.dev0+6fd2bc6-py2.7-linux-x86_64.egg/scipy/sparse/base.pyc in __mul__(self, other)
    414         if isscalarlike(other):
    415             # scalar value
--> 416             return self._mul_scalar(other)
    417 
    418         if issparse(other):
```

So we're calling the sparse `__rmul__` as intended, but `other` is somehow getting interpreted as a scalar? Needs further investigation.

**Comment by perimosocordiae** [comment]
A small-scale test is informative. Changing `N` to 2, we get the result:
```
scipy/sparse/compressed.py:295: SparseEfficiencyWarning: Comparing sparse matrices using >= and <= is inefficient, using <, >, or !=, instead.
  "using <, >, or !=, instead.", SparseEfficiencyWarning)

array([[ <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements (1 diagonals) in DIAgonal format>,
        <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements (1 diagonals) in DIAgonal format>],
       [ <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements (1 diagonals) in DIAgonal format>,
        <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements (1 diagonals) in DIAgonal format>]], dtype=object)
```

Looks like numpy's dispatching logic is actually calling the sparse `.__rmul__` method for every item in the dense matrix, which results in the Kronecker product we see above and explains why N=1000 would run out of memory.

**Comment by perimosocordiae** [comment]
Paging @mhvk, @shoyer, @eric-wieser to help figure out the numpy behavior here.

**Comment by perimosocordiae** [comment]
Also @pv and @charris.

**Comment by pv** [comment]
ndarray.dot() simply calls np.dot(A, B), which does not know what to do 
with sparse matrices.

**Comment by Albert65** [comment]
> ndarray.dot() simply calls np.dot(A, B), which does not know what to do
with sparse matrices.
I also assumed something like that, but there should be at least a warning. Also, it is quite natural to have a mixture of dense and sparse matrices in the code. I do not see any workaround except an ugly and error prone one (works as expected):
P*H^T <----> (H.dot(P.transpose())).transpose()

**Comment by pv** [comment]
On Python 3 you can write `P @ H.T`

**Comment by shoyer** [comment]
Part of the issue here is that numpy will greedily convert any sparse matrix to a scalar array:
```
In [5]: numpy.array(H)
Out[5]:
array(<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1000 stored elements (1 diagonals) in DIAgonal format>, dtype=object)
```

This is not so useful sparse matrix wrapped in a 0D numpy array with dtype=object.

On the NumPy side, we've discussed changing how we handle unknown types to require explicitly require writing dtype=object but haven't done that yet.

One simple fix you *could* potentially do in scipy is to define a `__array__` method on sparse matrices that raises TypeError. Then at least `np.array(H)` raises, which is the right thing to do if there isn't a dispatch mechanism (which there is not for `np.dot()`). You can still put sparse matrices in arrays if they aren't 0-dimensional, e.g., `numpy.array([H])` for a 1D single element array. I'm not entirely sure that's a good thing but it seems to use a different codepath with more fallback.

**Comment by perimosocordiae** [comment]
The problem with raising a `TypeError` is that (IIRC) we're relying on the hack that numpy ufuncs will often do the right thing for single-element object arrays containing a sparse matrix: https://gist.github.com/ahaldane/c3f9bcf1f62d898be7c7#ufuncs-and-object-arrays

For example, `np.sin(sparse)` works because sparse matrix types define a `sin()` method.

I thought this whole mess was going to be solved by `__array_ufunc__`. Or does the matrix-like `__mul__` behavior mean we can't use that?

**Comment by mhvk** [comment]
@perimosocordiae - the problem is particular to using `dense.dot(sparse)`, which does not allow sparse to override (because `np.dot` cannot be overridden, even with `__array_ufunc__`). As @pv mentions, if you use `dense @ sparse` things do work as expected:
```
dense = np.array([[1., 2.], [3., 4]])
sparse = scipy.sparse.eye(2)
dense @ sparse
# array([[ 1.,  2.],
#        [ 3.,  4.]])
```

**Comment by shoyer** [comment]
Sadly, I don't think `dense @ sparse` works yet if `__array_ufunc__` implemented, due to https://github.com/numpy/numpy/issues/9028.

**Comment by mhvk** [comment]
Yikes, that right, we still need to solve that. hopefully before `sparse.__array_ufunc__` exists (or is that too late already?)

**Comment by pv** [comment]
sparse.__array_ufunc__ cannot really be added, because the semantics cannot be changed to match its requirements.

**Comment by mhvk** [comment]
That in itself is sad, especially as sparse arrays were the driver behind the original `__numpy_ufunc__`... But probably a discussion best had in a different issue!

**Comment by perimosocordiae** [comment]
Unfortunately we don't even have the opportunity to raise a warning, as `dense.dot(sparse)` never enters a Scipy code path.

**Comment by leotrs** [comment]
I see. That makes sense. How about mentioning this somewhere in the documentation? Maybe include a quick reference to this known issue in the warning box found [here](https://docs.scipy.org/doc/scipy/reference/sparse.html).

**Comment by akhmerov** [comment]
Pardon for issue necromancy; I was directed here from the source (#12279). I hope this discussion would be useful to other developers that land here following the same trajectory.

numpy/numpy#9028 is now closed, so the main obstacle remaining to implement `spmatrix.__array_ufunc__` seems to be this message by @pv:

> `sparse.__array_ufunc__` cannot really be added, because the semantics cannot be changed to match its requirements.

Unfortunately after looking at the definition of `__array_ufunc__` protocol and the sparse matrix docs, I didn't manage to figure out what appears to be the problem here. Which semantics cannot be changed to match which requirements?

Thank you in advance.

**Comment by mhvk** [comment]
@akhmerov - yes, good question. I *think* the main problem is that `sparse`, like `np.matrix`, redefines `__mul__` to mean matrix multiplication. This is tricky with the `__array_ufunc__` implementation, since if one does `array * sparse`, it will call `__array_ufunc__` with the ufunc set to `np.multiply` rather than `np.matmul`. And by the time it `sparse.__array_ufunc__` gets called, it cannot know any more whether elementwise or matrix multiplication is needed.

Now there is a path forward, which is to deprecate `__mul__` in favour of `__matmul__` (which was introduced in python specifically for numpy). But obviously that is very difficult to do without breaking lots of people's code, so it would likely require a new `sparse` class that people can slowly opt in.

**Comment by akhmerov** [comment]
Thank you for the explanation!

> And by the time it `sparse.__array_ufunc__` gets called, it cannot know any more whether elementwise or matrix multiplication is needed.

Is this a problem for implementing ufuncs though? This would only be problematic if there was an expression that currently performs elementwise multiplication involving a sparse matrix, and that would start to perform a dot product instead. At the same time, I believe the only way to do elementwise multiplication on a sparse matrix is to call `spmatrix.multiply(other)`, and ufunc code can never reach this path.

**Comment by mhvk** [comment]
Good questions. @pv - did I remember wrong the real trouble for implementing `spmatrix.__array_ufunc__`?
