### ISSUE TITLE
finish in scipy.optimize.brute suddenly changes shape

### ISSUE THREAD

**Issue by basnijholt** [scipy/scipy#7708]
In the first part of `scipy.optimize.brute`, where `func` is evaluated on the grid `float`s are returned. Then in the final stage `func` is fed to a minimized and suddenly a `(1,)` numpy array is returned. This can lead to problems as I show in an example here.

See the manifestation of the behavior in the following code
```python
import scipy.optimize
import numpy as np

def test(x):
    print(x, x.dtype, x.shape)
    return x**2

res = scipy.optimize.brute(test, ranges=[(-1, 1)], Ns=3)
```

it prints:
```
-1.0 float64 ()
-1.0 float64 ()
0.0 float64 ()
1.0 float64 ()
[ 0.] float64 (1,)
```

This gave me an annoying issue when the function was using `np.diag`, because:
```python
> np.diag([1,1])

array([[1, 0],
       [0, 1]])
```
is different than:
```python
> np.diag([np.array([1]), np.array([1])])

array([1])
```

A simple example that would work with `finish=None` but fails when not:
```python
A = np.random.rand(2, 2)
def test(x):
    y = np.diag([x**2, x**2])
    return np.min(y @ A)

res = scipy.optimize.brute(test, ranges=[(-1, 1)], Ns=3)
```

**Comment by basnijholt** [comment]
If someone can confirm that this behavior is unwanted I can submit a PR to fix it! 😄

**Comment by andyfaff** [comment]
All the minimizers in `scipy.optimize` indicate that `func`:

> Must be in the form f(x, *args), where x is the argument in the form of a 1-D array

i.e. the first argument supplied to `func` is a 1D array of parameters. `func` is supposed to return a single float value. Thus, the objective function in your examples should expect to receive a 1D array. 

I think the reason your function is not receiving an array to start with is due to the [_scalarfunc](https://github.com/scipy/scipy/blob/v1.0.0/scipy/optimize/optimize.py#L2818) wrapper. That wrapper squeezes the parameter array.

I'd say if anything the bug is that brute is supplying the test function with a single float instead of a 1D array. This issue will only occur for a 1D problem.

**Comment by andyfaff** [comment]
As I suspected - `_scalarfunc` is supplied with tuples: `(-1.0,)`, `(0.0,)`, `(1.0,)` and the squeezing is supplying `func` with scalar floats.
Perhaps [L2818](https://github.com/scipy/scipy/blob/v1.0.0/scipy/optimize/optimize.py#L2818) needs to be changed to:
```
params = atleast_1d(squeeze(asarray(params)))
```
