### ISSUE TITLE
wrap DSYTRD

### ISSUE THREAD

**Issue by nschloe** [scipy/scipy#7775]
(Moved over from https://github.com/numpy/numpy/issues/9584.)

I would like to make LAPACK's [DSYTRD](http://www.netlib.org/lapack/explore-3.1.1-html/dsytrd.f.html) available to use from Python proper. Where do I have to look in the code? Where are the tests going?

**Comment by ilayn** [comment]
LAPACK wrappers unfortunately don't have tests. Because often a Python-level function is also provided and that function is tested and hence the wrapper is also tested indirectly under the hood. But so far things are pretty consistent. 

For direct addition of wrappers, here is recent #7643 as a minimal example about which files are affected. You can send a pull request based on that. 

f2py syntax is mostly black magic so in case it doesn't go through, let us know and we can have a look at it too.

**Comment by rgommers** [comment]
> LAPACK wrappers unfortunately don't have tests. 

There are tests for a number of LAPACK functions in ``linalg/tests/test_lapack.py``. If these functions aren't tested via a Python-level function, then adding a new test there looks like the way to go.

**Comment by ilayn** [comment]
> There are tests for a number of LAPACK functions in linalg/tests/test_lapack.py. If these functions aren't tested via a Python-level function, then adding a new test there looks like the way to go.

Ouch, I've forgotten that file. After a quick glance, it looks like it needs some update though 😃

**Comment by nschloe** [comment]
> f2py syntax is mostly black magic

You weren't kidding. With bit of work and luck, I've managed to make myself familiar with it and coughed up https://github.com/scipy/scipy/pull/7780. I'll be glad to take comments.
