### ISSUE TITLE
contributor names for 1.0 release notes

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#7798]
Hi everyone in the list below. We'd like to include the full name of everyone who contributed to SciPy for the 1.0 release in the release notes and we do not have your full name. If you are happy to have your name listed can you please reply with your full name (if you prefer offline, send it to ralf.gommers@gmail.com)?

- [x] @1kastner 
- [x] @endolith 
- [x] @annesylvie 
- [ ] @arcady 
- [x] @ashwinpathak20 
- [x] @CharlesMasson 
- [x] @cod3licious 
- [x] @guofei9987 
- [x] @yhlam 
- [x] @hollowaytape 
- [x] @jotasi 
- [x] @ksemb 
- [x] @SunsetOrange 
- [x] @mirochni
- [x] @orestisf1993 
- [x] @sjpet 
- [x] @suttonje 
- [x] @thrasibule 
- [ ] @voyager6868 
- [ ] @xoviat 

*Note: we get names from metadata in commits. Use ``git config --global user.name "Your Name"`` to get your full name correctly in future commits.*

Thanks!

EDIT: if you prefer not to be mentioned, a reply saying so is also welcome of course.

**Comment by guofei9987** [comment]
Hi，My full English Name is Guofei， and my full Chinese name is 郭飞.Thank you!---- On 星期日, 27 八月 2017 01:38:44 +0100  Ralf Gommers<notifications@github.com> wrote ----Hi everyone in the list below. We'd like to include the full name of everyone who contributed to SciPy for the 1.0 release in the release notes and we do not have your full name. If you are happy to have your name listed can you please reply with your full name (if you prefer offline, send it to ralf.gommers@gmail.com)? @1kastner @endolith @annesylvie @arcady @ashwinpathak20 @CharlesMasson @cod3licious @guofei9987 @yhlam @hollowaytape @jotasi @ksemb @SunsetOrange @mirochni @orestisf1993 @sjpet @suttonje @thrasibule @voyager6868 @xoviat Note: we get names from metadata in commits. Use git config --global user.name "Your Name" to get your full name correctly in future commits. Thanks!  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by rgommers** [comment]
Thanks @guofei9987. Mind if I split that as ``Guo Fei``? Full names in English are first and last separate, not joined together.

**Comment by guofei9987** [comment]
That is ok, thank you!---- On 星期日, 27 八月 2017 01:52:00 +0100  Ralf Gommers<notifications@github.com> wrote ----Thanks @guofei9987. Mind if I split that as Guo Fei? Full names in English are first and last separate, not joined together.  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by orestisf1993** [comment]
`Orestis Floros`

Thanks ;)

**Comment by SunsetOrange** [comment]
Michael James Bedford
Cheers

**Comment by yhlam** [comment]
Lam Yuen Hei

Thanks

**Comment by ksemb** [comment]
Klaus Sembritzki

Thanks

**Comment by jotasi** [comment]
Hi,

My full name is
Jonathan Tammo Siebert


Thanks

Am Samstag, den 26.08.2017, 17:38 -0700 schrieb Ralf Gommers:
> Hi everyone in the list below. We'd like to include the full name of
> everyone who contributed to SciPy for the 1.0 release in the release
> notes and we do not have your full name. If you are happy to have
> your name listed can you please reply with your full name (if you
> prefer offline, send it to ralf.gommers@gmail.com)?
> 
> @1kastner 
> @endolith 
> @annesylvie 
> @arcady 
> @ashwinpathak20 
> @CharlesMasson 
> @cod3licious 
> @guofei9987 
> @yhlam 
> @hollowaytape 
> @jotasi 
> @ksemb 
> @SunsetOrange 
> @mirochni
> @orestisf1993 
> @sjpet 
> @suttonje 
> @thrasibule 
> @voyager6868 
> @xoviat 
> 
> *Note: we get names from metadata in commits. Use ``git config --
> global user.name "Your Name"`` to get your full name correctly in
> future commits.*
> 
> Thanks!
>

**Comment by thrasibule** [comment]
Hello,

full name for @thrasibule is Guillaume Horel.

Thanks,
Guillaume

**Comment by cod3licious** [comment]
Franziska Horn
thank you! :)

**Comment by 1kastner** [comment]
Marvin Kastner

Thanks a lot!

**Comment by ashwinpathak20** [comment]
Ashwin Pathak

Thank you so much!

**Comment by sjpet** [comment]
Stefan Peterson

Thank you!
