### ISSUE TITLE
Documentation for firwin uses Nyquist rate and frequency interchangeably

### ISSUE THREAD

**Issue by orodbhen** [scipy/scipy#7855]
The [firwin](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.firwin.html#scipy.signal.firwin) documentation appears to use `Nyquist Rate` and `Nyquist Frequency` interchangeably, which is confusing. 

For example, this:

> Type II filters always have zero response at the Nyquist rate, so a ValueError exception is raised if firwin is called with numtaps even and having a passband whose right end is at the Nyquist rate.

And this:

> Value Error
>If any value in cutoff is less than or equal to 0 or greater than or equal to nyq, if the values in cutoff are not strictly monotonically increasing, or if numtaps is even but a passband includes the Nyquist frequency.

As far as I can tell, all instances of `Nyquist Frequency` should be changed to `Nyquist Rate`.

**Comment by WarrenWeckesser** [comment]
Thanks for reporting this!  In fact, this was just recently fixed in https://github.com/scipy/scipy/pull/7734.

The correct term is "Nyquist frequency".  See, for example, the first sentence (well, currently first) at the wikipedia article ["Nyquist frequency"](https://en.wikipedia.org/wiki/Nyquist_frequency).  But that's wikipedia, and it is not always a good idea to consider wikipedia articles as authoritative.

In the books that I have that define both "Nyquist frequency" and "Nyquist rate" [1, 2], the definitions are given in the context of the sampling theorem (something called Shannon's Sampling Theoreom or the Nyquist-Shannon Sampling Theorem).  The theorem says that in a continuous time signal, the signal must be sampled at twice the maximum frequency in the signal in order to be able to recover the signal from the samples.  (If the frequency is too low, aliasing occurs.)  In this context, the quantity "twice the maximum frequency in the signal" is always called the Nyquist rate.  Half this value--i.e. the maximum frequency in the signal--is called the Nyquist frequency.  (In [3], the Nyquist frequency is not defined, but the Nyquist rate is defined, as in the other books, as twice the maximum frequency in the signal.)

In the context of a *given* discrete-time signal, other books [4, 5] simply define the Nyquist frequency to be half the sampling frequency, with no mention of "Nyquist rate".

[1] Oppenheim and Schafer, Discrete-Time Signal Processing (3rd ed)
[2] Leland B. Jackson, Digital Filters and Signal Processing
[3] Proakis and Manolakis, Digital Signal Processing
[4] Peter Bloomfield, Fourier Analysis of Time Series
[5] E. R. Kanasewich, Time Sequence Analysis in Geophysics

**Comment by WarrenWeckesser** [comment]
I'm closing the issue, but that doesn't mean the discussion can't continue if you think there is more to this issue than what I wrote above.

**Comment by orodbhen** [comment]
Yes, sorry, my dyslexia seems to be strongest early in morning :) `Nyquist Frequency` is the correct term. I've corrected my original comment accordingly.
