### ISSUE TITLE
scipy.spatial.distance.wminkowski behaviour change in 1.0.0b1

### ISSUE THREAD

**Issue by lesteve** [scipy/scipy#7893]
`scipy.spatial.distance.wminkowski` does not give the same result in 0.19.1 and in 1.0.0b1. We noticed that because it was breaking some tests in scikit-learn. It feels to me that even if wminkowski is considered deprecated it should return the same result in 1.0 as in 0.19.1.

This seems related to https://github.com/scipy/scipy/pull/7630 and https://github.com/scipy/scipy/issues/5718. It seems like the discussion was around whether to raise the weights to the power of p or not.

### Reproducing code example:
```py
import numpy as np

import scipy
from scipy.spatial.distance import wminkowski

print(scipy.__version__)
arr = np.arange(4)
print(wminkowski(arr, arr + 1, p=2, w=4))
```

### Output

scipy 1.0.0.b1 (weights are not squared):
```
1.0.0b1
4.0
```

scipy 0.19.1 (weights are squared):
```
0.19.1
8.0
```

**Comment by rgommers** [comment]
You're totally right. We should restore the ``wminkowski`` implementation and clearly document that it differs from ``minkowski`` and that the latter is preferred.

@apbard would you be able to do this?

**Comment by apbard** [comment]
@rgommers this was expected I think and I added this to the release note in #7881. As @metaperture noted in #6931 the implementation of `wminkowski` was not implemented according to the right definition. Thus, IMHO this behaviour change could be regarded as a fix for a longstanding bug rather than a real behaviour change. Beside keeping the compatibility, is there some advantage in keeping the wrong implementation?

**Comment by lesteve** [comment]
> Beside keeping the compatibility, is there some advantage in keeping the wrong implementation?

backward-compatibility is the main point here I think.

**Comment by rgommers** [comment]
I missed that comment in the very long history of changes to ``pdist`` & co.

> Beside keeping the compatibility, is there some advantage in keeping the wrong implementation?

Two reasons.
1) Not giving users, including libs like scikit-learn, an unnecessary amount of work. This is also why I wanted a doc-only deprecation.
2. We try to never silently change numerical results. Doing that is worse than breaking their code by deprecation and then removal (and introducing a new function with the desired behavior).

This isn't really a bug, it's a matter of interpretation of weights. The new ``minkowski`` is arguably better, but I don't think that's enough to say "it's a bug" and be done.

So I think we'll want to:
- now restore the old behavior with a doc-only deprecation
- deprecate ``wminkowski in 1.2 or 1.3
- remove it 2 releases after that

**Comment by apbard** [comment]
@rgommers ok, agreed. i'll do it (probably next week though).

> Not giving users, including libs like scikit-learn, an unnecessary amount of work. This is also why I wanted a doc-only deprecation.

Maybe silly question, why not directly the "hard" deprecation (in this case but also in a more general)? Users can still use the function and at the same time they gets a warning about the behaviour change.

**Comment by rgommers** [comment]
Not a silly question. A library like scikit-learn wants to avoid deprecation warnings, so if we deprecate something they want to get rid of it. However, they can't just replace it with something else now, because they support multiple scipy releases, and pre-1.0 we don't give them the alternative. So they're going to have to do some switching based on parsing the scipy version string. That's annoying and also easy to make mistakes in.

**Comment by rgommers** [comment]
Closed by gh-7905
