### ISSUE TITLE
When multiplying large csr matrices a disproportional long time is spend in kernel space

### ISSUE THREAD

**Issue by svetlin-mladenov** [scipy/scipy#7901]
When multiplying a large, single-row matrix by a square, diagonal matrix most of the time is spend in kernel space. The expected behavior is for most of the time to be spend in user space actually multiplying the matrices instead of doing what ever it's doing in the kernel.

### Reproducing code example:
```
from scipy import sparse
import numpy as np

iters = 100
size = 41000000
print("Initializing")
mat1 = sparse.random(1, size, density=0.01, format='csr')
mat2 = sparse.spdiags(np.random.random(size), diags=0, m=size, n=size, format='csr')

print("Multiplying")
res = mat1.copy()
for i in range(iters):
    res *= mat2  # res = mat1 * mat2 produces similar results
```
When this script is run with `time python mult.py` about half the time is system time. I want to stress that most of that time is while looping and multiplying. The initialization part does not spend much time in the kernel.

This behavior can also be observed by setting `iters` to a large integer, running the code, and then using `htop` to observe cpu load.

If the size and iterations are reduced (say size=4000, iters=1000000) most of the time is spend in user space, as expected.

If the `mat1` is not single row but for example a `100xsize` matrix then again most of the time is spend in user space, as expected.

### Scipy/Numpy/Python version information:
```
0.19.1 1.13.1 sys.version_info(major=3, minor=5, micro=1, releaselevel='final', serial=0)
```
And here is the results of `scipy.show_config`
```
openblas_info:
    library_dirs = ['/usr/local/lib']
    libraries = ['openblas']
    language = f77
openblas_lapack_info:
    library_dirs = ['/usr/local/lib']
    libraries = ['openblas']
    language = f77
blas_opt_info:
    library_dirs = ['/usr/local/lib']
    libraries = ['openblas']
    language = f77
blas_mkl_info:
  NOT AVAILABLE
lapack_opt_info:
    library_dirs = ['/usr/local/lib']
    libraries = ['openblas']
    language = f77
```
I also tried with scipy 0.17 and using mac instead of linux but there results where the same.

**Comment by perimosocordiae** [comment]
My guess is that you're seeing the cost of memory allocations here.

When two CSR matrices are multiplied, we end up calling `a._mul_sparse_matrix(b)`:
https://github.com/scipy/scipy/blob/04759f9d46541f1626232b2a44d16d00a10e530c/scipy/sparse/compressed.py#L477

In your example with `size = 41000000`, we get:

https://github.com/scipy/scipy/blob/04759f9d46541f1626232b2a44d16d00a10e530c/scipy/sparse/compressed.py#L482
 * `mat2` is already a CSR matrix, so no conversion/copying here.

https://github.com/scipy/scipy/blob/04759f9d46541f1626232b2a44d16d00a10e530c/scipy/sparse/compressed.py#L484
 * `get_index_dtype` returns `int64`, while both `mat1` and `mat2` have index dtypes `int32`. This is because we ask it to ensure we can store indices up to `size**2`, which in this example would require at least 51 bits to store. This is because the last value in `indptr` corresponds to the overall `nnz` of the sparse matrix, and in pathological cases a matrix multiply can result in a completely dense matrix (i.e., `nnz = size * size`).

https://github.com/scipy/scipy/blob/04759f9d46541f1626232b2a44d16d00a10e530c/scipy/sparse/compressed.py#L487
 * First call to `malloc` happens here, allocating `size` 64-bit integers (328MB).

https://github.com/scipy/scipy/blob/04759f9d46541f1626232b2a44d16d00a10e530c/scipy/sparse/compressed.py#L490
 * This call results in four separate `malloc`s, as each `np.asarray` needs to cast from `int32` to `int64`. In your example, that totals to about 663MB of new allocations.

https://github.com/scipy/scipy/blob/04759f9d46541f1626232b2a44d16d00a10e530c/scipy/sparse/compressed.py#L498
 * Now that we're recomputing the index dtype with a maximum index of `nnz`, we're back in `int32` land again.

https://github.com/scipy/scipy/blob/04759f9d46541f1626232b2a44d16d00a10e530c/scipy/sparse/compressed.py#L501
 * That does mean we need to reallocate `indptr`, because it was `int64` from the previous step and now we're casting to `int32` (a 164MB `malloc`.)
 * We're also allocating new `indices` and `data` arrays, which are relatively cheap (1.6MB and 3.3MB).

And the rest can operate without any new memory allocation. To summarize, we ended up allocating just over a GB in the `_mul_sparse_matrix` call, and will do the same for every single iteration. There's no special case for `mat1 *= mat2`, so that doesn't help (as you observed).

To work around this, you have some options:
 1. Take advantage of the diagonal structure (if that's not just for the example): `res = mat1.multiply(mat2.diagonal())`
 2. Convert both inputs to 64-bit index dtypes ahead of time (i.e., `mat1.indices = mat1.indices.astype(np.int64)` for all four arrays). This prevents the extra copying, so you're only paying for the memory that's actually needed to store the result.

**Comment by perimosocordiae** [comment]
The scipy implementation is working as best it can, if not always as expected from the outside, so I'm closing this issue. If you see an opportunity for improvement, please reopen.

**Comment by svetlin-mladenov** [comment]
Thanks for the quick response. Unfortunately neither of your suggested work-arounds actually worked (well first one kind of works in certain cases). But you are right, it is a memory allocation/management issue. This behavior is the result of how malloc and free handle large memory allocation. There is nothing wrong with scipy.
