### ISSUE TITLE
Add a custom linkage method

### ISSUE THREAD

**Issue by greysab** [scipy/scipy#7904]
Is it possible to add a custom linkage method into the hierarchy.py ? If so what's the cleanest way of doing it ? Thanks

**Comment by rgommers** [comment]
At the moment this is not possible, because the first two lines of ``linkage`` are:

    if method not in _LINKAGE_METHODS:
        raise ValueError("Invalid method: {0}".format(method))

Even if you'd try (the unsupported!) inserting of your custom method name into ``_LINKAGE_METHODS``, then the actual implementation would not be present in ``_hierarchy.pyx``.

If you look at the implementation of ``linkage``, you'll see that it doesn't do that much - just some checking before handing off to the Cython implementation of the method. So there's not much to gain from getting ``linkage`` to recognise your custom method. Better to just use it standalone.

**Comment by rgommers** [comment]
Question answered so closing this issue. Feel free to follow up though.

**Comment by MarkPundurs** [comment]
How does one "use it standalone"?
