### ISSUE TITLE
signal.remez produces invalid filters

### ISSUE THREAD

**Issue by yurivict** [scipy/scipy#7922]
The following example produces an invalid output. The response of the filter reaches 10^3 (30dB), way outside of the specs, when it is supposed to be an equioscillation solution.

It should either fail explicitly, or have a variable that will allow invalid output when set.
Currently, the output is invalid.

### Reproducing code example:
```
from scipy import signal
import numpy as np

bpass = signal.remez(200, [0, 0.29, 0.301, 0.36, 0.402, 0.5], [0, 1, 0])
freq, response = signal.freqz(bpass)
ampl = np.abs(response)

import matplotlib.pyplot as plt
fig = plt.figure()
ax1 = fig.add_subplot(111)
ax1.semilogy(freq/(2*np.pi), ampl, 'b-')  # freq in Hz
plt.show()
```

### Scipy/Numpy/Python version information:
```
('0.19.1', '1.11.2', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))
```

### Graph illustrating the problem
![remez-invalid](https://user-images.githubusercontent.com/271906/30787342-f6d66c38-a13a-11e7-9e6c-8223bc5f58d7.png)

**Comment by WarrenWeckesser** [comment]
@yurivict, it is annoying, but it is not a bug.  In the gaps between the given bands, the behavior of the filter is unspecified.  Here's a quote from Oppenheim and Schafer [1]:  "In general, there is no guarantee that the transition regions of a multiband filter will be monotic, because the Parks-McClellan algorithm leaves these regions completely unconstrained."  Figure 7.56(b) of that text shows the same type of behavior.

Oppenheim and Schafer go on to say:

> When this kind of response results for a particular choice of the filter parameters, acceptable transition regions can usually be obtained by systematically changing one or more of the band edge frequencies, the impulse-response length, or the error-weighting function and redesigning the filter.


[1] Alan V. Oppenheim and Ronald W. Schafer, Discrete-Time Signal Processing (3rd ed), Pearson Higher Education, Inc, Upper Saddle River, NJ, USA (2010).
