### ISSUE TITLE
stats: confidence intervals around any statistic

### ISSUE THREAD

**Issue by haphaeu** [scipy/scipy#7949]
The statistics package has methods to calculate the confidence interval around the median, using 
```
scipy.stats.rv_continuous.interval(alpha)
``` 

Would it be of interest to have confidence intervals for any statistics of a sample?

I'm developing now a package with confidence interval for the values of all variates of a sample, using a [bootstrapping](https://ocw.mit.edu/courses/mathematics/18-05-introduction-to-probability-and-statistics-spring-2014/readings/MIT18_05S14_Reading24.pdf) technique. 

If there's interest it could be pulled into `stats` once done.

Regards

**Comment by josef-pkt** [comment]
Difficult to say.

Backwards compatibility requires that the default returns don't change, so it would need something like a new return_confint keyword or separate functions.
For bootstrap there are packages that work the other way around. E.g a bootstrap function or class that takes any statistic function as argument. This allows more flexibility in choosing which type of bootstrap to use, e.g. bc or ABC (?) intervals.

There is also a stalled PR adding permutation tests to two sample hypothesis tests, where if I remember the discussion also was about integration into existing functions.

There are also plans and attempts to add more like this in statsmodels, which is less subject to compatibility considerations or "getting it right the first time". The more difficult parts are for the statistics and tests that are not close to normal, e.g. for proportions, poisson rates, contingency tables, ...

It's an important area, but I never spent enough time to come up with a general enough design, so in statsmodels I'm just collecting bits and pieces for whatever comes up or is contributed.

This is one area where scipy.stats and statsmodels overlap, it fits in both and we might get competing implementation with some differences in features.

**Comment by haphaeu** [comment]
Didn't know about statsmodels. Interesting, will have a good look at it. 

The idea is a specific function, returning a xx% confidence interval for the entire sample, or for a particular quantile, using bootstrap technique as mentioned above. In my area we use that a lot, with emphasis on the tails, as a quality check of the extreme values used for design. It also looks nice as a visual check in the reports 8^)

What motivated me to start this thread is because this is the only part of our post-processing module where we're going to have to go into lower level coding - all the rest is neatly solved using stats. Getting this done in numpy is not that extensive, but kind of adds some extra lines to the module that would seem to fit well in stats imho.

But as you've said, maybe it is too specific for scipy or statsmodels.

**Comment by josef-pkt** [comment]
You can always open a PR or link to code in a github repo. Some new functionality requires difficult design decisions or might not fit well with the current patterns in a library package. Even in that case, it illustrates the use case, and over time it will be possible to come up with something that fits.

I'm not sure I'm coming across the right way. I'm very interested, and I think it's important, but it's not always easy to see where the forest is because there are all these trees.
Even if there is no "grand plan", it's often possible to improve by one function or one enhancement at a time. Right now there is not enough information for me about your proposal to guess how well it would fit.

(My last attempt at everything for one sample proportion
https://github.com/josef-pkt/misc/blob/7fb0160bb7f8fd5eef00e276c61ec7fbe2e20238/notebooks/proportion_one_power.ipynb
and some of my todo list for statsmodels
https://github.com/statsmodels/statsmodels/projects/7
)

**Comment by mdhaber** [comment]
[`scipy.stats.bootstrap`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bootstrap.html) was released with SciPy 1.7.0. 

[`scipy.stats.permutation_test`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.permutation_test.html#scipy.stats.permutation_test) is in 1.8.0.

We're also working these into hypothesis test results, but I'll open a separate issue to track progress of that when some other things settle.

Sounds like that closes this one. Please reopen if I missed something!
