### ISSUE TITLE
BUG maybe: fmin_bfgs possibly broken in 1.0

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#7959]
Kevin just started to test statsmodels against scipy 1.0
https://github.com/statsmodels/statsmodels/issues/3926

The main problem (besides a few deprecations that we missed) is that we get a large number of convergence failures mainly with fmin_bfgs

I'm just starting to look into it, so have nothing specific yet. 

However, and old test case see below fails to converge to the correct parameters, that should be relatively straightforward. (I don't know what the returned convergence status is, and it is possible that the current maxiter in statsmodels is too low now in this case.)

(Many other cases are difficult to optimize, but I just managed last week to clean up the unittest so they pass with all bfgs since scipy 0.14)

```
self = <statsmodels.discrete.tests.test_discrete.TestProbitBFGS object at 0x7f0b074db198>
    def test_params(self):
>       assert_almost_equal(self.res1.params, self.res2.params, DECIMAL_4)
E       AssertionError: 
E       Arrays are not almost equal to 4 decimals
E       
E       (mismatch 100.0%)
E        x: array([ 0.4412,  0.1027,  1.4389, -4.8224])
E        y: array([ 1.6258,  0.0517,  1.4263, -7.4523])
```

```
class TestProbitBFGS(CheckBinaryResults):

    @classmethod
    def setup_class(cls):
        data = sm.datasets.spector.load()
        data.exog = sm.add_constant(data.exog, prepend=False)
        cls.res1 = Probit(data.endog, data.exog).fit(method="bfgs",
            disp=0)
        res2 = Spector()
        res2.probit()
        cls.res2 = res2
```

**Comment by pv** [comment]
What version are you comparing against? Does everything work with 0.19.1?

**Comment by josef-pkt** [comment]
this was before adding or switching to 1.0
https://travis-ci.org/statsmodels/statsmodels/builds/282287117
the python 3.6 version was using scipy: 0.19.1 

appveyor has scipy    0.19.1 for python 3.6 and python 2.7
https://ci.appveyor.com/project/josef-pkt/statsmodels/build/1.0.2330

**Comment by pv** [comment]
https://github.com/scipy/scipy/pull/7165 is indeed the most suspicious, and based on a quick look also the only, change.

**Comment by pv** [comment]
Yes, reverting gh-7165 makes that failure go away.

**Comment by josef-pkt** [comment]
just a possible candidate in 7165

in the old code this is protected and worked around if yk_sk =0 :
yk_sk = np.dot(yk, sk)
https://github.com/scipy/scipy/pull/7165/files#diff-c1c2c73ad9e5ddef5673e2e95d19020fR968

the new code still uses yk dot sk in the computation

(I don't know what it means, but it sounds like a possible corner problem that is handled differently)

**Comment by pv** [comment]
It seems the `if k == 0:` change for the initial hessian is the cause --- if you change it to `if k == 0 and False:` the statsmodels tests pass.

**Comment by josef-pkt** [comment]
> It seems the if k == 0: change for the initial hessian is the cause --- if you change it to if k == 0 and False: the statsmodels tests pass.

@bashtage can you check this, I still don't have scipy 1.0 installed


in other news: 
increasing maxiter which is currently too low by default, makes the failures in LogitBFGS and ProbitBFGS go away
https://travis-ci.org/statsmodels/statsmodels/builds/282377837 only shows the mle_retvals failure that I introduced to show what the convergence messages look like

**Comment by bashtage** [comment]
Yes, this seems to fix it.

**Comment by pv** [comment]
@rgommers: we want to revert gh-7165 from 1.0.0. It's non-essential, and I don't want to start fixing bugs in it this late.

**Comment by pv** [comment]
I think josef is right that the yk_sk corner case handling is also different from before --- this becomes exposed in scipy's test suite once the initial step scaling change is reverted.

**Comment by rgommers** [comment]
Okay, makes sense to revert at this point. Do you also want to revert in master, or try and fix it up straight away there?

**Comment by pv** [comment]
Revert from both. 

At the moment I would have to be convinced that the new formula does not have issues with loss of precision for large `yk_sk`.

**Comment by antonior92** [comment]
Hi all, I am author of PR #7165. Sorry for all this mess. 

My motivation for the modification was to improve the performance, by removing the necessity of performing matrix multiplications. The change on the formula of BFGS leads to better performance, since the computational cost for the new formula is ``O(n^2)`` rather than  ``O(n^3)`` .

Once I made the modification, I just realized the computation became ill condition for an initial unscalled Hessian. Hence I introduced some heuristic to make the Hessian better scaled. The heuristic is from p.143, formula (6.20), Nocedal/Wright and should improve the results for most of the problems.

For the benchmarks I tried out the modification on the initial hessian computation could lead to great reductions on the ``maxiter`` in some cases, but could also slightly increase the count of ``maxiter`` for other applications. Taking all into account, I considered the algorithm was better with this modification and decided to include it.

I did not considered that many other packages that rely on scipy could have unittests checking ``maxiter``. And my modification indeed modify this number what is probably the cause for the broken tests (``"increasing maxiter which is currently too low by default, makes the failures in LogitBFGS and ProbitBFGS go away"``)

**Comment by josef-pkt** [comment]
@antonior92  increasing maxiter made the failures go away in the two cases, but there where still many more failing cases. The ill conditioned or scaling problems are more serious than just the change in maxiter.
fmin_bfgs is the default optimizer for many models in statsmodels, so our unit test suite for it is pretty large.

**Comment by antonior92** [comment]
Oh I just though this was the cause by reading the thread. Thanks for clarifying this up.

**Comment by pv** [comment]
The results from N&W are not necessarily directly applicable, since I 
think the line search procedure is not the same.

**Comment by antonior92** [comment]
Actually Nocedal and Wright mentioned this heuristic without any specific line search method in mind. He just shows that by doing that you get a initial matrix with eigenvalues that approximate the ones from the true matrix.

Anyway, I will check this results later to see if I can figure out what is wrong.
