### ISSUE TITLE
scipy 1.0.0rc1 windows wheels depend on missing msvcp140.dll

### ISSUE THREAD

**Issue by ales-erjavec** [scipy/scipy#7969]
Importing `scipy.sparse` or `scipy.special` (from 1.0.0rc1 openblas linked wheels) on windows can fail with an ImportError if the target machine does not have msvcp140.dll (part of MS Visual C++ 2015 redistributable package) installed.

### Reproducing code example:
```
pip install scipy==1.0.0rc1
python -c"import scipy.sparse"
python -c"import scipy.special"
```

### Error message:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\biolab\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\sparse\__init__.py", line 229, in <module>
    from .csr import *
  File "C:\Users\biolab\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\sparse\csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: DLL load failed: The specified module could not be found.
```
### Scipy/Numpy/Python version information:
```
1.0.0rc1 1.13.3 sys.version_info(major=3, minor=6, micro=2, releaselevel='final' , serial=0)
```

Inspecting the sparsetools*.pyd with dependency walker reveals the missing dependency and installing the appropriate redistributable solves the problem.

Also putting the msvc*.dll into 'scipy/extra-dll/' directory also seems to work.

**Comment by pv** [comment]
@xoviat: ping --- should the default be to link the c++ runtime 
statically? Or maybe we want to redist it (afaik the license allows any 
redistribution unmodified)?

**Comment by xoviat** [comment]
@zooba I read the mailing list thread on this issue and there seemed to be
no definitive conclusion. Is it possible to link against the C runtime but
not the C++ runtime? The thread seemed to indicate that such a method was
simple, but I cannot find any option for that.

@pv This is a complete nightmare because the extensions should *not* be
statically linked against the C runtime, and the C++ redistributable is
designed to be managed by windows update to protect against security
vulnerabilities.

Also, I don't think numpy has any C++, so it shouldn't have this problem.

**Comment by pv** [comment]
Maybe we then should bundle the required DLL in extra-dll. Since it's 
then in PATH, it comes last in the DLL search --- then, IIUC, it is used 
only in cases where the system does not have the DLL available system-wide.

**Comment by xoviat** [comment]
You know what? Let's just do that. I cannot think of any disadvantages and
it addresses some failure scenarios.

**Comment by rgommers** [comment]
Argh. It's quite odd that no one ran into this with 1.0.0b1. I'd expect many Windows systems with MSVC components not installed.

**Comment by xoviat** [comment]
@rgommers Actually almost all Windows systems have these components
installed automatically through Windows Update or some other service. This
only happens when someone has disabled Windows Update or they aren't using
Windows 10 (which will be "they aren't using a supported version of Windows
in 2020", the same time Python 2.7 is deprecated).

**Comment by ales-erjavec** [comment]
I do not think that is true. Only the ucrtbase.dll is now part of Windows 10 and included in the automatic updates for Win 8.1 (and 7?).

**Comment by xoviat** [comment]
First, are you testing this on a Windows 10 computer? Second, can you
confirm that this is not a problem for Python 3.4 and 2.7?​

**Comment by ales-erjavec** [comment]
I am testing on Window 8.1, but fully updated with all recommended updates. The error does not happen for Python 3.4 and 2.7, but I am not sure whether that is a reliable indicator. My System32 folder contains versioned msvcp.dll msvcp80.dll and msvcp100.dll, probably installed as part of other packages.

**Comment by zooba** [comment]
Bundling the DLL alongside your .pyd file (ideally one that will _always_ be loaded first) is the best way to do this.

It is possible to statically link C++ but not UCRT with command line options something like this (from memory - test and don't trust):

```
cl.exe /MT /link /nodefaultlib:libucrt /nodefaultlib:libvcruntime ucrt vcruntime
```

The trick is that if you statically link and then replace the static importlibs with the dynamic importlibs, the linker can generate the correct code to load them dynamically (while linking the rest statically). You can't go the other way (unless I'm totally misremembering how this worked...)

(We used this trick by default in distutils up until the last rc of 3.5.0 to avoid redistributing vcruntime140.dll. Unfortunately, statically linking this DLL means you burn through FLS indices very quickly and your 98th or so extension module will fail to load.)

**Comment by xoviat** [comment]
@zooba It would be *really nice* if Python would provide a public API to get the MSVC "redist" directory. MSVC constantly changes their folder structure and duplicating work on that is wasteful. setuptools provides an `msvc` module but it's *very tricky* to get the "redist" directory that corresponds to the compiler that you are using.

**Comment by zooba** [comment]
@xoviat See the discussion about splitting distutils out - this is *not* an API I want to put in the core runtime.

**Comment by pv** [comment]
@ales-erjavec: the scipy 1.1.0.dev wheels here https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/ with today's timestamp (should appear within the next hour) should have necessary dlls correctly bundled, if you can check would be nice to have second confirmation. The same procedure will be used for rc2.  (With the exception of python3.4, for which appveyor doesn't appear to have the msvc redistributable --- the issue is wontfix for that python version.)

**Comment by pv** [comment]
I think the remaining question that we should be sure of is whether distributing these files is actually allowed by the license. IIUC it is, but on the other hand it's a bit unclear situation as the builds occur on appveyor and the files originate from the redist there.

**Comment by xoviat** [comment]
Redistribution of the DLLs is allowed in MSVC 2015 or later. I think 2008 may have a bit more odd license that requires the folder structure to be preserved.

**Comment by pv** [comment]
The redist.txt for that says, "You may also redistribute all the files (*.dll and *.manifest) within a folder, listed below the folder for your convenience, as an entire set.", so I guess it's ok if you just copy all the four files.

**Comment by pv** [comment]
Not sure bundling msvcp90.dll is actually required -- it's apparently 
contained in the Python 2.7 installer packages. Not sure if it gets 
installed though.

**Comment by ales-erjavec** [comment]
@pv: I have tested the scipy-1.1.0.dev0+*_53c1dac wheels for Python 3.5 and 3.6, both 32 and 64 bit versions. All of them work.

**Comment by pv** [comment]
Ok, closing as solved.

**Comment by jjcasalo** [comment]
Hi all,

 I had the same problem, when trying to setup an Offline install.
I took all the WHL files, but at the end, I had the same error, which was due to the missing msvcp140.dll file.
The cause of the problem is that I was using this WHL :
scipy-1.0.1-cp36-cp36m-win_amd64.whl
It's about 12 Mb.
This one is "wrong", as it does not include several of the required items I needed (including all the extra-dll folder).

The solution was to get this file :
scipy-1.0.1-cp36-**none**-win_amd64.whl

This file is about 30 Mb, and it has all the required stuff.

Wasted  about 2 days on this..  Grrrrrrr

**Comment by pv** [comment]
I don't where you got a file called
"scipy-1.0.1-cp36-cp36m-win_amd64.whl", certainly not from us. Problems
with binaries should be taken up with the people who built them.

**Comment by jjcasalo** [comment]
Sorry, my intention was not to complain about your project.
It's just that this is one of the pages that Google gave me when I tried to solve the problem, so I thought of adding my 2 cents to help other people who might struggle like I did.

If you feel like my post had nothing to do with your project, feel free to delete it, I won't mind.
I was just trying to help.

Best regards

**Comment by pv** [comment]
Sure, no problem. I just wanted to clarify that there does not appear
to be further action necessary from our side.

**Comment by Overdrivr** [comment]
I have found that the `msvcp140.dll` that ships with scipy can be an issue if the system does **not** has this dll already somewhere.

For instance, it was preventing me from running tensorflow correctly (that needs it at import time), causing a `_pywrap_tensorflow_internal error` instead of crashing on a missing DLL.

See https://github.com/tensorflow/tensorflow/issues/22512#issuecomment-425096387 for details

**Comment by ilayn** [comment]
Does it happen also with the release version?

**Comment by Overdrivr** [comment]
Do you mean the version installed trough pip and taken from https://pypi.org/ ? That's the one I'm using.

**Comment by pv** [comment]
Welcome to https://en.wikipedia.org/wiki/DLL_Hell ...

The failure mode does however not seem very bad: you get mildly mysterious error message warning about installation issues, rather than a DLL dependency error. A solution could be for tensoflow either shipping msvcp themselves, or telling users to install the msvc runtime first.

**Comment by Overdrivr** [comment]
Apparently, TF is going to highlight in their install process on Windows to install msvc, to avoid issues. So I guess there isn't much you need to do, unless maybe instruct scipy's users about this.
