### ISSUE TITLE
Feature Request - Böttcher function of a complex variable

### ISSUE THREAD

**Issue by adammaj1** [scipy/scipy#7998]
Hi,

as in the title

Matemathica:

http://math-functions-1.watson.jp/sub4_math_020.html
(It is in Japan but you can translate it. It works fine )
http://math-functions-1.watson.jp/file_math010/v8_specialfunctions/fractalrelated.zip

http://reference.wolfram.com/language/ref/MandelbrotSetBoettcher.html

http://www-personal.umich.edu/~kochsc/bottcher.pdf
https://books.google.pl/books?id=2CMRBwAAQBAJ&pg=PA34&lpg=PA34&dq=boettcher+coordinate&source=bl&ots=ub-8z8aRz-&sig=PAVlzi0YQHIeegKmuDfuBS1J2ys&hl=pl&sa=X&ved=0ahUKEwjQ8sON1prWAhXBDpoKHaMiB0kQ6AEIUTAE#v=onepage&q=boettcher%20coordinate&f=false
wikipedia:
https://en.wikipedia.org/wiki/B%C3%B6ttcher%27s_equation

naive description:
https://en.wikibooks.org/wiki/Fractals/Iterations_in_the_complex_plane/MandelbrotSetExterior#Complex_potential
https://en.wikibooks.org/wiki/Fractals/Iterations_in_the_complex_plane/boettcher
http://fraktal.republika.pl/cpp_argphi.html

key words: 
* Boettcher coordinate
* external ray
* complex potential
* Riemann map

TIA

Adam

**Comment by person142** [comment]
A couple of things:

- We can't read that source code because it is not clear how it is licensed.

- I am not sure what you are asking for. Do you mean that you want a tool that, given an analytic function `h` with a superattracting fixed point `a`, finds a function `F` defined in a neighborhood of `a` so that `F(h(z)) = (F(z))^n`? Or do you want something more specific (i.e. the particular function that Mathematica implements)? The more general thing is almost assuredly out of scope for SciPy.

- Whatever is desired, we would need references to scholarly papers that discuss *implementation*.

**Comment by adammaj1** [comment]
- Licence:

 
" Use of all contents of in this site is free. But in that case,
* URL address of this site,
* Administrator name of this site the "Souichiro-Ikebe",
please specify and display in your web site or books.
In addition, you do not need to check and contact to me in advance that you want to use."
It is translation from the page : 
 
http://math-functions-1.watson.jp/index_100.html#section010

-task
I ask only for case where h(z) = z^2 + c where c is complex constant
here n = 2
her is description: 
http://www.mndynamics.com/indexp.html#XR

**Comment by xoviat** [comment]
@adammaj1 I would suggest typing out an example implementation in this issue that uses the `scipy` API. Please use `scipy.integrate.solve_ivp` to solve the differential equation.

**Comment by person142** [comment]
> I would suggest typing out an example implementation

Please don't. The issue here is (from https://github.com/scipy/scipy/blob/master/doc/source/dev/newfeatures.rst):

> Is what you are adding something that is well understood in the literature? If not, how sure are you that it will turn out well? Does the method perform well compared to other similar ones?

`scipy.special` already has a bunch of functions that *did not* turn out well. If we're going to add new functions we need papers from good journals that discuss double-precision implementations and the range of values for which those implementations will work. I don't see that here yet, so I'm inclined to close this as out of scope.

Special functions are tricky. They should not be implemented lightly.

**Comment by xoviat** [comment]
@person142 From what I understand, he wants to add Mathematica's MandelbrotSetBoettcher. It appears to be trivial to sketch out a basic implementation, and I think would allow everyone to see what is being proposed. That *does not* mean that it would be accepted.

**Comment by person142** [comment]
@xoviat that is reasonable; I apologize for sounding curt. I made a gist with a naive implementation here:

https://gist.github.com/person142/62b44fbe08bc24edfaacc39ef92728e7

Note that the Mathematica definition is overly vague because it doesn't handle the branch cuts of the `1/2**n`th root correctly. (Obviously it's not what they're doing in the code because they get the right answer.)

A better reference is here:

http://www.sciencedirect.com/science/article/pii/S019688588371002X

Useful papers are also:

https://projecteuclid.org/euclid.dmj/1077304731
https://link.springer.com/article/10.1007/BF01385497

@adammaj1 with the above papers I'm optimistic that a good implementation is possible. (Rough idea is to use the Laurent series for the disk `|z| > 2` where you are certainly outside of the Mandelbrot set and an iteration approach inside the disk.)

I will see what I can do.

**Comment by adammaj1** [comment]
[tavis_cpp.txt](https://github.com/scipy/scipy/files/1383031/tavis_cpp.txt)
HI,

Thx for the answer.

> Computing the Laurent Series of  ..
I think that it descibes map from exterior of circle to exterior of Mandelbrot  set. Boettcher map is it's invariant ( = from exterior of Mandelbrot set to exterior of circle)


#  More information:

 There is a method which probably computes argument of Boettcher coordinte
( result of Boettcher map : 
https://en.wikipedia.org/wiki/External_ray#Uniformization_2 
It is called Stripe Average Coloring:
https://commons.wikimedia.org/wiki/File:Mandelbrot_set_-_Stripe_Average_Coloring.png
https://commons.wikimedia.org/wiki/File:Stripe_Average_Coloring_-_Mandelbrot_set_zoom_(_wake_1over3_).png
it is described here : 
https://en.wikibooks.org/wiki/Fractals/Iterations_in_the_complex_plane/stripeAC


# here one can find the code and description of using Runge-Kutta integration for finding external angle ( = argument of Boettcher coordinate)

http://www.fractalforums.com/programming/smooth-external-angle-of-mandelbrot-set/

I send also cpp file as a text

HTH

Adam

**Comment by adammaj1** [comment]
some test to check precision of computations:

https://en.wikibooks.org/wiki/Fractals/Iterations_in_the_complex_plane/MandelbrotSetExterior#Tests

https://commons.wikimedia.org/wiki/File:Part_of_parameter_plane_with_external_3_rays_landing_on_the_Mandelbrot_set.png

HTH

**Comment by person142** [comment]
I think this is a won't do-we have enough special functions already in the API that need attention, so I'm not inclined to add more API surface area.
