### ISSUE TITLE
Document building of scipy 1.0.0 from source on Windows

### ISSUE THREAD

**Issue by dalito** [scipy/scipy#8005]
I have tried to find details about the new build process on Windows using gfortran, openblas and MS VC. Information seems to be quite scattered (#7597, numpy/numpy#9431 etc.). - Ideally I would like to be able to reproduce the build of the "officially" released binary.

Would https://www.scipy.org/scipylib/building/windows.html be the correct place to find this information?

**Comment by xoviat** [comment]
The best place to look is appveyor.yml.

**Comment by pv** [comment]
The appveyor.yml config files https://github.com/scipy/scipy/blob/master/appveyor.yml (CI) and https://github.com/MacPython/scipy-wheels/blob/master/appveyor.yml (wheels going to pypi) are the canonical ones.

The build instructions in the documentation probably should be rewritten from scratch, I think they're quite out of date.

**Comment by xoviat** [comment]
I looked a bit at the documentation, and my opinion is this: most people just want to know when they read the documentation, how to get the job done. They don't want to know all of the various options, and based on the performance data that I've seen, they will have a very marginal incentive to use the Intel stack. So what I propose is that we add a "Tutorial" section to the top of the page that gives the "step by step" version of how to get it done quickly, and then we can put the "explanation" after that.

**Comment by dalito** [comment]
Link to PR by @xoviat for improved docs: scipy/scipy.org#235

**Comment by ilayn** [comment]
I think a tutorial is a great incentive. The traffic to SciPy repository still includes #5995, #6851, and #4102 in the top 10 list. So probably once the wheels are uploaded for version 1.0, many of the complaints will disappear. That will also, very likely, increase the acquaintance level of the users who attempt to build their own NumPy/SciPy, since newcomers will just install via pip. Thus, we can set the bar slightly higher.

**Comment by dalito** [comment]
scipy/scipy.org#235 was merged. Thanks!
