### ISSUE TITLE
Scipy optimize.minimize maxfun has confusing behavior

### ISSUE THREAD

**Issue by isacostantini** [scipy/scipy#8031]
##
op = {'maxiter': 10}
scipy.optimize.minimize(ftominimize, x0, options=op)
##
It appears to be ignoring the maxiter options since the function ftominimize is called significantly more than 10 times. I tried to set maxfun (as discussed in earlier issue:  https://github.com/scipy/scipy/issues/3334 ) to 10 with 'L-BFGS-B' but i have the same problem as with maxiter. I  tried to increase the values of gtol and eps (in the argument options) but it looks if the scipy minimize ignore the argument "options"  and it uses the defaults values.
tested on Scipy :
0.19.1 1.13.3 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)

**Comment by pv** [comment]
It does not ignore maxiter (number of iterations != number of function evaluations).

For `maxfun`, I would expect the issue is that `maxfun` does not terminate computation in the middle of numerical differentiation for computing gradients, so it works with granularity of `len(x)+2` or so.

**Comment by andyfaff** [comment]
For the problem that was specified `minimize` will choose the BFGS method, as there are no bounds set.
Setting `maxiter` will control the maximum number of times the optimization loop occurs. However, as @pv states each optimization loop will probably require more than 1 function evaluation. This is because if no `jac` callable is supplied then the gradient has to be estimated with finite differences. Depending on how smart the finite difference calculation is then there are going to be at least an extra `len(x)` function evaluations. Please note that BFGS does not have a `maxfun` option, only `maxiter`.
