### ISSUE TITLE
ENH: match functionality of R for hmean

### ISSUE THREAD

**Issue by rdturnermtl** [scipy/scipy#8165]
It seems the harmonic mean in R has an option for what to do with zeros:
https://www.rdocumentation.org/packages/psych/versions/1.7.8/topics/harmonic.mean
scipy.stats.hmean simply raises ValueError when given a zero (e.g. hmean([0,1,2,3])). This creates annoying corner cases to work around in the code. Maybe a warning can be raised, but the ValueError doesn't make any sense.

**Comment by rgommers** [comment]
The default behavior of raising a `ValueError` does make sense imho, because in the regular definition the harmonic mean cannot be calculated in the presence of zeros. 

There's alternative treatments though, like returning 0 (see https://stats.stackexchange.com/questions/37628/harmonic-mean-with-zero-value) or applying a zero-correction (see https://rdrr.io/cran/lmomco/man/harmonic.mean.html).

So a keyword to control this behavior makes sense, PR welcome.

**Comment by DCtheTall** [comment]
Would the maintainers of this repo still accept a PR for this? Checking since this issue is now almost 2 years old.

**Comment by ev-br** [comment]
A PR is helpful to get the ball rolling.

A warning is not useful IMO, a keyword to control the behavior looks better. An overview of what e.g. R does would be helpful too.

**Comment by DCtheTall** [comment]
Thanks for the quick reply.

R's `harmonic.mean` will return 0 if any element of the vector is 0. I assume they do this because the limit of the harmonic mean of a vector as any of its elements approaches 0 is also 0 (though this is a guess).

I can open a PR in the next day or so.

**Comment by WarrenWeckesser** [comment]
> R's harmonic.mean will return 0 if any element of the vector is 0. I assume they do this because the limit of the harmonic mean of a vector when any of its elements approaches 0 is also 0 (though this is a guess).

That sounds like a reasonably good justification for simply returning 0 when an input is 0, with not need for a special argument to enable that behavior.

**Comment by DCtheTall** [comment]
The extra argument has the advantage of not breaking backwards compatibility, but I am open to just having it return 0 by default.

**Comment by WarrenWeckesser** [comment]
After looking into this some more, I convinced myself that returning 0 when an input is 0 (assuming all the other inputs are greater than 0) is something we can just do without adding a special argument to enable it.  It is the correct limiting behavior.  The only backwards incompatibility would be if someone is counting on getting a ValueError when an input is 0, but that seems unlikely.  I'd rather not clutter the API with an additional argument that isn't really necessary.

@rgommers, @ev-br, what do you think?

Note that the function `harmonic_mean` in the standard library returns 0 in this case:
```
In [10]: from statistics import harmonic_mean                                   

In [11]: harmonic_mean([1, 2, 0])                                               
Out[11]: 0
```
Also note that `harmonic_mean` *usually* raises an error if an input is negative.  `harmonic_mean([-1, 1])` raises, as does `harmonic_mean([-1, 0, 1])`:

```
In [12]: harmonic_mean([-1, 0, 1])                                              
---------------------------------------------------------------------------
StatisticsError                           Traceback (most recent call last)
<ipython-input-12-8a48fb3320fd> in <module>
----> 1 harmonic_mean([-1, 0, 1])

<...snip...>

~/mc37scipy/lib/python3.7/statistics.py in _fail_neg(values, errmsg)
    282     for x in values:
    283         if x < 0:
--> 284             raise StatisticsError(errmsg)
    285         yield x
    286 

StatisticsError: harmonic mean does not support negative values
```
The rest of this comment isn't directly relevant to this issue, but might be of interest.

-----
`<digression>`

Given the above, it is surprising that `harmonic_mean([1, 0, -1])` returns 0!  In fact, when `harmonic_mean` encounters a 0, it ignores all values after that 0, and returns 0.  So it has this surprising behavior:

```
In [14]: harmonic_mean([0, "foo"])                                              
Out[14]: 0
```
That's right, the harmonic mean of 0 and the string `"foo"` is 0. 😕 

The reason is that `harmonic_mean` makes a single pass through the input sequence, and the code has an "early-out" that returns 0 when 0 is encountered.  I brought this up in a bug report: https://bugs.python.org/issue38382, but the Python maintainers do not seem to be interested in changing the behavior.  My understanding of the rationale for allowing the surprising behavior is that the code assumes that users will only pass in numerical values.  (I.e. "We're all consenting adults here.  If you want to pass a string into a function that expects numbers, you'll have to worry about the consequences on your own.")  The "consenting adults" argument doesn't quite work for me in the case of `harmonic_mean([-1, 0, 1])` and `harmonic_mean([1, 0, -1])`.  The first raises an error, while the second returns 0.  If we're all consenting adults, why bother checking for negative values at all?

`</digression>`

**Comment by DCtheTall** [comment]
Thanks for all the information, pretty interesting (and kinda scary) stuff! I added a commit where it defaults to zero instead of adding an extra argument to `hmean`. Whichever design is preferable to you all is fine by me 👍

**Comment by rgommers** [comment]
> After looking into this some more, I convinced myself that returning 0 when an input is 0 (assuming all the other inputs are greater than 0) is something we can just do without adding a special argument to enable it. It is the correct limiting behavior. The only backwards incompatibility would be if someone is counting on getting a ValueError when an input is 0, but that seems unlikely. I'd rather not clutter the API with an additional argument that isn't really necessary.

this sounds sensible to me.
