### ISSUE TITLE
scipy.linalg.lstsq is sometimes not deterministic

### ISSUE THREAD

**Issue by TomDLT** [scipy/scipy#8208]
`scipy.linalg.lstsq` is sometimes not deterministic, as shown by the following test:

### Reproducing code example:

```py
from scipy.linalg import lstsq
from sklearn.utils.testing import assert_array_equal
# requires scikit-learn >= 0.19
from sklearn.tests.test_multioutput import generate_multilabel_dataset_with_correlations

def test_investigate_linear_regression_indeterminacy():
    # Is scipy.linalg.lstsq deterministic?
    X, Y = generate_multilabel_dataset_with_correlations()
    y = Y[:, 1].astype(np.float64)
    X -= X.mean(axis=0)
    y -= y.mean()

    ref = lstsq(X, y)[0]
    for i in range(1000):
        coef = lstsq(X, y)[0]
        assert_array_equal(ref, coef, 'iter %d' % i)

test_investigate_linear_regression_indeterminacy()
```

which failed at iteration 4 in [this Travis job](https://travis-ci.org/scikit-learn/scikit-learn/jobs/314836481). **I can't reproduce locally.**
It only occurs on one Travis platform (python 3.6.2), only sometimes (iteration 4 in this test case). 

cf. https://github.com/scikit-learn/scikit-learn/issues/10283

### Error message:
```pytb
_______________ test_investigate_linear_regression_indeterminacy _______________
    def test_investigate_linear_regression_indeterminacy():
        # Is scipy.linalg.lstsq deterministic?
        from scipy.linalg import lstsq
        X, Y = generate_multilabel_dataset_with_correlations()
        y = Y[:, 1].astype(np.float64)
        X -= X.mean(axis=0)
        y -= y.mean()
    
        ref = lstsq(X, y)[0]
        for i in range(1000):
            coef = lstsq(X, y)[0]
>           assert_array_equal(ref, coef, 'iter %d' % i)
E           AssertionError: 
E           Arrays are not equal
E           iter 4
E           (mismatch 100.0%)
E            x: array([  7.186580e-03,  -9.998066e-03,   3.580353e-03,  -1.627024e-03,
E                   -3.538778e-03,  -2.532519e-02,   1.074851e-03,   3.214291e-02,
E                    1.339362e+11,  -1.486778e-03,   1.718521e-03,  -4.677074e+11,...
E            y: array([  7.186536e-03,  -1.046430e-02,   3.667191e-03,  -1.917473e-03,
E                   -3.596765e-03,  -2.608710e-02,   1.081140e-03,   3.199401e-02,
E                    1.935733e+10,  -1.960874e-03,   1.906514e-03,  -5.467077e+11,...
X          = array([[ 0.84669656, -1.204     ,  1.88065131, ..., -1.03091981,
         0.23908269, -0.74727976],
       [-1.7728545...453, -1.04129346],
       [-1.07081749, -1.21883974, -1.25895606, ...,  0.9049708 ,
        -1.04203549, -1.92876323]])
Y          = array([[0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 1, 1],
       ..., 
       [1, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0]])
coef       = array([  7.18653565e-03,  -1.04643041e-02,   3.66719062e-03,
        -1.91747279e-03,  -3.59676502e-03,  -2.60871046e-....52494812e-02,  -1.96304321e-02,
        -8.03375244e-03,  -1.19493604e-02,   8.68475437e-03,
         8.89170170e-03])
i          = 4
lstsq      = <function lstsq at 0x7f3ea2ede9d8>
ref        = array([  7.18657983e-03,  -9.99806642e-03,   3.58035269e-03,
        -1.62702376e-03,  -3.53877774e-03,  -2.53251890e-....51331329e-02,  -1.94740295e-02,
        -8.06188583e-03,  -1.21812820e-02,   8.45718384e-03,
         8.93211365e-03])
y          = array([-0.504,  0.496, -0.504, -0.504, -0.504, -0.504,  0.496,  0.496,
       -0.504, -0.504,  0.496, -0.504, -0.504, ... 0.496, -0.504, -0.504,  0.496,  0.496,  0.496,
       -0.504,  0.496, -0.504, -0.504,  0.496,  0.496, -0.504,  0.496])
/home/travis/build/scikit-learn/scikit-learn/sklearn/tests/test_multioutput.py:486: AssertionError
====== 1 failed, 8351 passed, 26 skipped, 4860 warnings in 495.55 seconds ======
```

### Scipy/Numpy/Python version information:
```py
# Travis build versions
SCIPY_VERSION="0.19.1"
NUMPY_VERSION="1.13.1"
PYTHON_VERSION="3.6.2"
```

**Comment by ilayn** [comment]
I don't know if you are fixing the seed for the random test data but as far as I can see it fails on the branch where MKL is enabled. 

This type of behavior is simlar to #5629. Since Least square solver branches off with respect to the over/under-determined problem after reducing it to a BLS problem, it might happen that in one architecture it goes branch 1 and on the other goes the other way branch 2. Near rank-deficient/singular matrices especially big ones created with `numpy.random.rand` can have such properties.

Could you please add more information about the problem or even better include the test data that is fed to `lstsq`?

**Comment by pv** [comment]
It's well-known floating point linear algebra libraries are generally not deterministic, even across calls on identical data on the same run. Determinism in general requires a linalg library specially designed for floating-point reproducibility. At least MKL I think has flags that you can turn on to improve the reproducibility.

The above code is using `assert_array_equal` to test for exact floating point equality, and this is probably not the correct way to go.

**Comment by ilayn** [comment]
I don't think it can explain the divergence here if the data matrix is not big (which is not provided). The error is huge compared to the nondeterministic effects you mentioned to take place. 

But of course remark about the `assert_array_equal` part holds which I missed.

**Comment by pv** [comment]
Ok, I didn't look at the numbers. The matrix is 1000x100.
`lstsq` thinks the matrix is rank 100, but it has two small singular values `~ 1e-14` (still `> eps` !)
It's probably plausible that those singular values are nonzero only because of rounding error, so a different rounding error could plausibly result to values smaller than eps maybe.

The default value for `cond` is `eps` and not `min(m,n)*eps`. I guess this is how it has always been, but multiplying the matrix size does matter in some cases... A different solution to the problem would be to use a hand-picked value like `cond=1e-12` in the `lstsq` call.

An actionable change here could be to adjust the lstsq default, but maybe needs more thinking...

**Comment by mdhaber** [comment]
I couldn't reproduce this locally or on CI (see gh-21559 - failures mostly indicate failure to install scikit-learn), so I'll go ahead and close.
