### ISSUE TITLE
What is 'prefilter' of scipy.ndimage.zoom good for?

### ISSUE THREAD

**Issue by MartinThoma** [scipy/scipy#8209]
Is there a possibility to show why `prefilter` is necessary / good?

For the given example ( https://4957-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.ndimage.zoom.html#scipy.ndimage.zoom ), I can't see a difference.

**Comment by jaimefrio** [comment]
Prefiltering is necessary for correctness if `order  >= 2`.

To treat the image as continuous, each discrete image value is conceptually replaced by a B-spline of the chosen order centered at that point. Many interpolation functions take value `1` at their node and `0` at all others, so the discrete values at the nodes are also the multipliers of the interpolation functions. That's not the case with B-splines, and what filtering does is compute the value by which the B-spline centered at each pixel has to be multiplied so that the interpolated value at each pixel center is the same as that of the original image.

If you fail to prefilter the result will be similar to applying a smoothing filter over the input image, i.e. the result will be blurry.

**Comment by rgommers** [comment]
Question answered, and @jaimefrio improved the docs at the same time in commit 3208f18608. Prefilter now says:
```
prefilter : bool, optional
    Determines if the input array is prefiltered with `spline_filter`
    before interpolation. The default is True, which will create a
    temporary `float64` array of filtered values if `order > 1`. If
    setting this to False, the output will be slightly blurred if
    `order > 1`, unless the input is prefiltered, i.e. it is the result
    of calling `spline_filter` on the original input.
```

seems good enough, so closing
