### ISSUE TITLE
LAPACK Rectangular Full Packed routines 

### ISSUE THREAD

**Issue by luc-j-bourhis** [scipy/scipy#8212]
`scipy.linalg.lapack` does not expose the LAPACK routines using the [Rectangular Full Packed storage (RFP)](https://software.intel.com/en-us/mkl-developer-reference-c-matrix-storage-schemes-for-lapack-routines#RFP_STORAGE) for upper triangular, lower triangular, symmetric, or Hermitian matrices. This includes 

- rank-k operations ([xfrk](https://software.intel.com/en-us/mkl-developer-reference-c-sfrk))
- triangular system ([xtfsm](https://software.intel.com/en-us/mkl-developer-reference-c-tfsm))
- Cholesky:  factorise ([xpftrf](https://software.intel.com/en-us/mkl-developer-reference-c-pftrf)), solve ([xpftrs](https://software.intel.com/en-us/mkl-developer-reference-c-pftrs)), and inverse ([xpftri](https://software.intel.com/en-us/mkl-developer-reference-c-pftri))
- copy from RFP to standard packed format ([xtfttp](https://software.intel.com/en-us/node/521386)), and the reverse conversion ([tpttf](https://software.intel.com/en-us/mkl-developer-reference-c-tpttf))

**Comment by insertinterestingnamehere** [comment]
Nice idea. These routines should be added to the Cython LAPACK API for when we drop support for LAPACK 3.1 and Accelerate (see the discussion in https://github.com/scipy/scipy/pull/6051). On the other hand, I'm not aware of any plans for Python-level wrappers. It'll probably just depend on when someone steps forward to implement it.

**Comment by luc-j-bourhis** [comment]
Thanks for the comment and sorry for not spotting that discussion. Cython support would be great and probably enough for a lot of people, in which I count myself. Do I understand correctly that the scipy 1.1.0 will have moved away from Accelerate and could then use LAPACK 3.2?

**Comment by ilayn** [comment]
@luc-j-bourhis Fingers crossed :) Dropping Accelerate support turned out to be a bigger problem than just avoiding it. We've gathered the summary on wiki page https://github.com/scipy/scipy/wiki/Dropping-support-for-Accelerate

So the story is a bit convoluted and depends on many stakeholders. So far we only have an agreement about *we should do something about it*. But I'm optimistic about a positive answer to your question. Then we will move to 3.4.0.

**Comment by insertinterestingnamehere** [comment]
Don't worry about missing the other discussion. It's on a fairly old PR. This issue helps provide another concrete reason for the version bump even if it is something we're already working on.

Another idea that's worth at least mentioning: it's likely possible to provide these routines without dropping Accelerate since Accelerate provides at least some of LAPACK 3.2. We'd have to formally drop support for  LAPACK 3.1 though, so I'm still inclined to do this as a part of the transition to LAPACK 3.4, particularly since that change will hopefully be happening soon.

**Comment by ilayn** [comment]
For the record, LAPACK devs stopped developing for packed arrays for sym/her matrices due to lack of benefit of packed storage. (See https://github.com/Reference-LAPACK/lapack/issues/245#issuecomment-372060216 )

I guess we might have to close this as *won't fix*

**Comment by luc-j-bourhis** [comment]
They stopped developing for the traditional packing, i.e. 11 12 13 ... 1n 22 21 ... 2n 33 34 ... 3n etc, which is old story really, since this packing has been known to have a horrible speed performance for ages. However this issue of mine is not related to that packing but to the new RFP, and the conclusion of the comment you cite is much less definite: « we worked on a few routines, performance were good, but half the storage might not be worth the effort any longer» Not the "might". Clearly, the routines operating on RFP have shown no sign of deprecation at all. So my issue stands imho.

**Comment by ilayn** [comment]
Yes indeed I missed that detail. I've asked for clarification from Julien.

**Comment by luc-j-bourhis** [comment]
@ilayn The [answer](https://github.com/Reference-LAPACK/lapack/issues/245#issuecomment-372126132) to your question on the discussion thread of Lapack issue #245  confirms what I wrote above: the RFP routines are and will stay alive in LAPACK. There is, I think, definitively use cases for GEMM-like speed with half the memory footprint.

**Comment by luc-j-bourhis** [comment]
May I respectfully ping!

**Comment by insertinterestingnamehere** [comment]
These routines have Cython wrappers as of https://github.com/scipy/scipy/pull/8670. I don't think there are Python level wrappers yet.

**Comment by ilayn** [comment]
@luc-j-bourhis Sorry for the delay. Would you like to work on it in terms of a PR? Please feel free to decline, I'm just asking. Otherwise I'll combine with a PR that I'll submit soon.

**Comment by luc-j-bourhis** [comment]
@ilayn No worries. I would be more than happy to help. That PR would be about writing the Python wrappers then I guess. I know next to nothing about this but again if you think I can be useful, yes.

**Comment by ilayn** [comment]
Great. If you haven't wrapped any LAPACK routines it might be a bit too much to ask from you. Let me wrap the functions and if you can help me derive some tests for them that would be really valuable. 

Since I have never used these routines, real use cases would be really nice to have as test cases. Let me create a PR and we can continue the discussion there. Hopefully tonight I can submit it.
