### ISSUE TITLE
local variable used before assignment in NeutonCG local terminate function

### ISSUE THREAD

**Issue by freekotya** [scipy/scipy#8241]
https://github.com/scipy/scipy/blob/11509c4a98edded6c59423ac44ca1b7f28fba1fd/scipy/optimize/optimize.py#L1519-L1522

Can you please explain where should that function get "gfk" variable from? Running Neuton-CG method calls that code while internally calling local terminate() function
 and returns

> NameError: free variable 'gfk' referenced before assignment in enclosing scope

**Comment by dlax** [comment]
`gfk` (as other variables not passed as function arguments like `fval`, `fcalls`, ...) is looked out from outer scope (that is, the whole `_minimize_newtoncg` function). The problem here is that if `terminate` is called before such a name has been declared, this will lead to a `NameError`. So `gfk` should be initialized (perhaps as `None`) before any call to `terminate` is made.
