### ISSUE TITLE
freqz() does not include evaluation at pi by default

### ISSUE THREAD

**Issue by lxkain** [scipy/scipy#8265]
The default, or when specifying worN as an integer, the frequencies are evaluated at

```
linspace(0, 2*pi if whole else pi, N, endpoint=False)
```

However, I believe it would make more sense to *include* the endpoint, as the complex value of the frequency at pi is valuable information that I believe should be visible by default. This would parallel the often-taken step of taking a N-point FFT, and, for even N, keeping the values at indexes 0..N/2 *inclusive*. The last value represents the frequency at the Nyquist frequency.

**Comment by larsoner** [comment]
I agree in principle but changing this would be backward incompatible, and not worth introducing a deprecation cycle to change because the number of affected scripts and downstream libs would probably be quite large.

We could add a new keyword argument like `nyquist=False`, or perhaps simpler, allow `whole='nyquist'`, meaning "False but include Nyquist" or "only go to Nyquist". I might try to make a PR to do this to see how it would look.

**Comment by pallavibharadwaj** [comment]
Hello, I would like to work on this issue. Could you please point me in the right direction as to where I should start looking to fix this? Thank you!
