### ISSUE TITLE
curve_fit: outcome depends on x-data scaling

### ISSUE THREAD

**Issue by nschloe** [scipy/scipy#8369]
The simple curve fitting test problem
```python
# -*- coding: utf-8 -*-
#
import matplotlib.pyplot as plt
import numpy
import scipy.optimize

numpy.random.seed(42)


def f(x, *p):
    return p[0] * numpy.exp(-(x-p[1])**2/p[2]**2)


lmbda = numpy.linspace(0.0, 1.0, 100)
data = f(lmbda, 1.0, 0.5, 0.223) + 1.0e-1 * numpy.random.rand(100)

lmbda *= 9.0e-2  # okay
# lmbda *= 8.5e-2  # bork
# lmbda *= 4.1e+2  # okay
# lmbda *= 4.2e+2  # bork

popt, pcov = scipy.optimize.curve_fit(
        f, lmbda, data, p0=[1, 0, 1],
        )

plt.plot(lmbda, data)
plt.plot(lmbda, f(lmbda, *popt), ':')
plt.show()
```
gives

![1](https://user-images.githubusercontent.com/181628/35857811-8bdebd1c-0b3a-11e8-93c4-5f637ee33c87.png)

The result, however, changes when simply scaling the `lmbda` data by `8.5e-2` (instead of `9.0e-2`):

![2](https://user-images.githubusercontent.com/181628/35857818-9138573c-0b3a-11e8-99aa-cd710d816e4c.png)

The same thing occurs when scaling by `4.2e2` – `4.1e2` still works fine.

Hence, in this case the range of acceptable scalings is about `9.0e-2` to `4.1e+2`. In more complex cases, it might not be possible to easily find a fitting scale at all. It's weird that scaling should have any influence on the problem at all.

**Comment by charris** [comment]
Not too surprising. The function doesn't return enough info to really diagnose the problem, but it might be worth trying to scale the initial values also. Also, could you print out the resulting parameters of the fit? It looks like p[2] has headed off to distant shores. Note that there are at least two valid fits because the function is symmetric in p[2]. 

The mean and standard deviation of the (weighted) lmda and maximum value of the data would probably supply better starting points. For these sorts of fits it is always a good idea to check if something has gone wrong, because it often does. Here I would bet the function terminated after exceeding the limit of function evaluations.

**Comment by nschloe** [comment]
> Not too surprising. 

Yeah, you're probably right. Some parameters (i.e., starting values) might actually take on different meanings if the problem is scaled. For example, in
```python
def f(x, *p):
    return p[0] * numpy.exp(p[1] * x)
```
`p[0]` should not change if `x` is scaled, but `p[1]` should if the problem is to be independent of scaling. Things can get pretty tricky from here, so its probably best for scipy to do nothing.

Thanks for the comment!
