### ISSUE TITLE
Unexpected behavior with reflect mode of ndimage.rotate

### ISSUE THREAD

**Issue by not522** [scipy/scipy#8465]
`scipy.ndimage.rotate` with `reflect` mode causes unexpected behavior.
Following code is expected to generate a symmetric image, but the output is asymmetric.

It seems wrong when the coordinates become negative. I think the behavior on the larger coordinate side is correct.

### Reproducing code example:
```
import numpy
import scipy.ndimage
import matplotlib.pyplot as plt

a = numpy.zeros((7, 7))
for i in range(7):
    for j in range(7):
        if (i + j) % 2 == 0:
            a[i, j] = 1

a = scipy.ndimage.rotate(a, 1, mode='reflect')

plt.axes().set_aspect('equal')
plt.pcolor(a, cmap=plt.cm.binary)
plt.savefig('reflect.png', bbox_inches='tight')
```
![reflect](https://user-images.githubusercontent.com/1255726/36581040-469f0a00-18ae-11e8-937e-a5414dcd0408.png)

### Error message:
No error message.

### Scipy/Numpy/Python version information:
```
1.0.0 1.13.1 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
```

**Comment by jaimefrio** [comment]
Thanks for reporting!

I always have trouble remembering which is which, but I think that's expected behavior, and that you want to use `'mirror'` mode instead of `'reflect'`? One takes the first/last item to be the center of reflection, the other takes the edge of the image to be that. Can you check if that explains your issue?

**Comment by not522** [comment]
Thank you for your quick response!
I try to write a compatible library accelerated by CUDA, therefore I want to know the behaviors of all mode.

My main question is "why is the output asymmetric?"
If I assume the edge is 0 and 7, the asymmetric output is explainable. However, the behavior of `wrap` mode seems to be contradicted. It performs as the edge is 0 and 6.
```
import numpy
import scipy.ndimage
import matplotlib.pyplot as plt

a = numpy.zeros((5, 25))
for i in range(5):
    for j in range(25):
        a[i, j] = i / 5

a = scipy.ndimage.rotate(a, 90, reshape=False, mode='wrap')

plt.axes().set_aspect('equal')
plt.pcolor(a, cmap=plt.cm.binary)
plt.savefig('wrap.png', bbox_inches='tight')
```
![wrap](https://user-images.githubusercontent.com/1255726/36586624-deb0d38e-18c5-11e8-8e89-efde922967ba.png)

**Comment by jaimefrio** [comment]
So I took a closer look at this, and I think I now understand where this comes from... The standard behaviour of the various modes when dealing with integer valued points only, as documented in the code [here](https://github.com/scipy/scipy/blob/maintenance/1.0.x/scipy/ndimage/src/ni_support.c#L203) is as follows:

```
nearest:  aaaaaaaa|abcd|dddddddd
wrap:     abcdabcd|abcd|abcdabcd
reflect:  abcddcba|abcd|dcbaabcd
mirror:   cbabcdcb|abcd|cbabcdcb
constant: kkkkkkkk|abcd|kkkkkkkk
```

The interpolation module has a surprising behaviour because it has to deal with non-integer points. Here's code producing results similar to the above, where I have manually replaced commas with pipes to mark the boundaries of the original array :

```
In [18]: ndimage.geometric_transform(a, lambda x: (x[0] - 6,), (16,), mode='nearest')
Out[18]: array([0, 0, 0, 0, 0, 0 | 0, 1, 2, 3 | 3, 3, 3, 3, 3, 3])

In [19]: ndimage.geometric_transform(a, lambda x: (x[0] - 6,), (16,), mode='wrap')
Out[19]: array([3, 1, 2, 3, 1, 2 | 0, 1, 2, 3 | 1, 2, 0, 1, 2, 0])

In [20]: ndimage.geometric_transform(a, lambda x: (x[0] - 6,), (16,), mode='reflect')
Out[20]: array([2, 3, 3, 2, 1, 0 | 0, 1, 2, 3 | 3, 2, 1, 0, 0, 1])

In [21]: ndimage.geometric_transform(a, lambda x: (x[0] - 6,), (16,), mode='mirror')
Out[21]: array([0, 1, 2, 3, 2, 1 | 0, 1, 2, 3 | 2, 1, 0, 1, 2, 3])

In [22]: ndimage.geometric_transform(a, lambda x: (x[0] - 6,), (16,), mode='constant')
Out[22]: array([0, 0, 0, 0, 0, 0 | 0, 1, 2, 3 | 0, 0, 0, 0, 0, 0])
```

As you can see, all cases except `'wrap'` behave the same. If we increase the resolution of the output it can be seen that `'reflect'` also has an unexpected behaviour close to the boundary:

```
In [38]: ndimage.geometric_transform(a, lambda x: (x[0] / 2. - 1,), (11,), mode='nearest', order=1)
Out[38]: array([0. , 0.  | 0. , 0.5, 1. , 1.5, 2. , 2.5, 3. | 3. , 3. ])

In [39]: ndimage.geometric_transform(a, lambda x: (x[0] / 2. - 1,), (11,), mode='wrap', order=1)
Out[39]: array([2. , 2.5 | 0. , 0.5, 1. , 1.5, 2. , 2.5, 3. | 0.5, 1. ])

In [40]: ndimage.geometric_transform(a, lambda x: (x[0] / 2. - 1,), (11,), mode='mirror', order=1)
Out[40]: array([1. , 0.5 | 0. , 0.5, 1. , 1.5, 2. , 2.5, 3. | 2.5, 2. ])

In [41]: ndimage.geometric_transform(a, lambda x: (x[0] / 2. - 1,), (11,), mode='reflect', order=1)
Out[41]: array([0. , 0.5 | 0. , 0.5, 1. , 1.5, 2. , 2.5, 3. | 2.5, 3. ])

In [42]: ndimage.geometric_transform(a, lambda x: (x[0] / 2. - 1,), (11,), mode='constant', order=1)
Out[42]: array([0. , 0.  | 0. , 0.5, 1. , 1.5, 2. , 2.5, 3. | 0. , 0. ])
```

I think both `'wrap'` and `'reflect'` are broken, but I also understand why they behave the way they do. They way functions in the interpolation module work is by mapping any point outside `[0, len - 1]` to a point inside those bounds, then using interpolation within those bounds to find the correct value. This doesn't work for a proper implementation of `'wrap'` and `'reflect'`, because they require a behaviour that is different from what happens within the bounds of the original array. So apparently it was decided to use something close, but not quite right, so `'wrap'` considers that the first item is located on top of the last, and `'reflect'` goes for being like `'mirror'` but offset by one.

For comparison, here's the behaviour of OpenCV in a similar case, which I think is the correct one:

```
In [21]: src
Out[21]: array([[0., 1., 2., 3.]], dtype=float32)

In [22]: cv2.warpAffine(src, M, (10, 1), borderMode=cv2.BORDER_WRAP)
Out[22]: array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 1.5, 0. , 0.5]], dtype=float32)

In [23]: cv2.warpAffine(src, M, (10, 1), borderMode=cv2.BORDER_REFLECT)
Out[23]: array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3. , 3. , 2.5]], dtype=float32)
```

**Comment by not522** [comment]
Thanks to your detailed comment I understood what is the problem. And I found a discussion about this problem (#206).
I think the behavior of OpenCV, interpolation integer points, is reasonable. Even this specification sometimes causes nonintuitive behavior, but at least it has a consistency.
```
import cv2
import numpy as np

src = np.ones((1, 4))
M = np.float32([[2, 0, 0], [0, 1, 0]])
dst = cv2.warpAffine(src, M, (8, 1))
print(dst)
```
```
[[ 1.   1.   1.   1.   1.   1.   1.   0.5]]
```

**Comment by jaimefrio** [comment]
For future reference, this are the links to the actual github, not Trac, issues listed in #206: #1323, #1903 and #2045

**Comment by not522** [comment]
I found other related issues. #2640 #8131

**Comment by charris** [comment]
The coefficients are computed for data reflected about the centers of the edge pixels, the interpolation reflects about the edges. They need to be the same, and since we only have the one way to compute the 
spline coefficients, the interpolation is in error. Note that we really don't support wrap either. If we want to support reflection about edges and wrap, we need to have more ways to compute the spline coefficients. Easily done if we want it, but will need a better return type.

**Comment by charris** [comment]
The spline coefficients are computed for reflection about the centers of the edge pixels. The `geometric_map` reflects about the edges of the edge pixels, they need to be the same, so "reflect" is misnamed. Wrap is also defective for the same reason, the spline coefficients need to be computed for wrapped data.

I suspect the rotations are off center also.

**Comment by charris** [comment]
Doing the rotation by hand, `geometric_map` handles small negative coordinate values incorrectly, as replacing then by 0 fixes the problem. I suspect it is a rounding type error in determining which spline coefficients to use.

**Comment by charris** [comment]
So this traces back to `NI_GeometricTransform`.

**Comment by charris** [comment]
And from there to `map_coordinate` in `ni_interpolation.c`, which indeed looks incorrect.

**Comment by charris** [comment]
This seems to fix it.
```
diff --git a/scipy/ndimage/src/ni_interpolation.c b/scipy/ndimage/src/ni_interpolation.c
index fd9eb1913..4b75c2757 100644
--- a/scipy/ndimage/src/ni_interpolation.c
+++ b/scipy/ndimage/src/ni_interpolation.c
@@ -121,9 +121,9 @@ map_coordinate(double in, npy_intp len, int mode)
             if (len <= 1) {
                 in = 0;
             } else {
-                npy_intp sz2 = 2 * len - 2;
+                npy_intp sz2 = 2 * len - 1;
                 in = sz2 * (npy_intp)(-in / sz2) + in;
-                in = in <= 1 - len ? in + sz2 : -in;
+                in = in < 1 - len ? in + sz2 : -in;
             }
             break;
         case NI_EXTEND_REFLECT:
@@ -133,7 +133,8 @@ map_coordinate(double in, npy_intp len, int mode)
                 npy_intp sz2 = 2 * len;
                 if (in < -sz2)
                     in = sz2 * (npy_intp)(-in / sz2) + in;
-                in = in < -len ? in + sz2 : -in - 1;
+                if (in < -0.5)
+                    in = in < -len ? in + sz2 : -in - 1;
             }
             break;
         case NI_EXTEND_WRAP:
@@ -153,16 +154,16 @@ map_coordinate(double in, npy_intp len, int mode)
             in = -1;
             break;
         }
-    } else if (in > len-1) {
+    } else if (in > len - 1) {
         switch (mode) {
         case NI_EXTEND_MIRROR:
             if (len <= 1) {
                 in = 0;
             } else {
-                npy_intp sz2 = 2 * len - 2;
+                npy_intp sz2 = 2 * len - 1;
                 in -= sz2 * (npy_intp)(in / sz2);
-                if (in >= len)
-                    in = sz2 - in;
+                if (in > len - 1)
+                    in = sz2 - 1 - in;
             }
:
+                    in = in < -len ? in + sz2 : -in - 1;
             }
             break;
         case NI_EXTEND_WRAP:
@@ -153,16 +154,16 @@ map_coordinate(double in, npy_intp len, int mode)
             in = -1;
             break;
         }
-    } else if (in > len-1) {
+    } else if (in > len - 1) {
         switch (mode) {
         case NI_EXTEND_MIRROR:
             if (len <= 1) {
                 in = 0;
             } else {
-                npy_intp sz2 = 2 * len - 2;
+                npy_intp sz2 = 2 * len - 1;
                 in -= sz2 * (npy_intp)(in / sz2);
-                if (in >= len)
-                    in = sz2 - in;
+                if (in > len - 1)
+                    in = sz2 - 1 - in;
             }
             break;
         case NI_EXTEND_REFLECT:
@@ -171,7 +172,7 @@ map_coordinate(double in, npy_intp len, int mode)
             } else {
                 npy_intp sz2 = 2 * len;
                 in -= sz2 * (npy_intp)(in / sz2);
-                if (in >= len)
+                if (in >= len - .5)
                     in = sz2 - in - 1;
             }
             break;
```

**Comment by jaimefrio** [comment]
I think your solution would make `mode='reflect'` better than it is, but not quite correct: wouldn't there be a discontinuity in the derivatives at `in = -0.5` and `in = len - 0.5`?

As for `mode='mirror'`, I really think that the correct value is `sz2 = 2 * len - 2`, not `sz2 = 2 * len - 1`.

**Comment by charris** [comment]
> As for mode='mirror', I really think that the correct value is sz2 = 2 * len - 2, not sz2 = 2 * len - 1.

My bad, you are correct. The `< 0` case looks currently correct, but I think the `> 0` case is still wrong.

The `'reflect'` case I've still got a bit wrong, but the `.5` is right, the pixels edges are a half pixel outside the box formed by the sample points. Sums of cubic b-spines are always C^2, so no discontinuities in the first or second derivative. Note that in both the cases the derivative should be zero across the lines of reflection. The "reflect" case does require two extra coefficients around the outside to get the outer half of the edge pixels. I haven't checked the code to see if we got that right.

Grrr, I don't know why it is so difficult to get this right. I'll put up an actual PR with tests and we can take a close look at that.

**Comment by jaimefrio** [comment]
I have put this mini-library together to experiment with different ways of handling the bounds:

https://gist.github.com/jaimefrio/79ee7a9f8d7ff6ca10ae72633ec68c80

When I run the following code using functions from there, this is what I obtain:

```
f = np.array([-5.,-2, -1, 0, 1, 2, 5])
filtered_f = ndimage.spline_filter1d(f)
x = np.linspace(-6, 12, 1000)
plt.plot(f, 'o')
plt.plot(x, interpolate(x, filtered_f, reflect_bounds, mirror_bounds))
```
![image](https://user-images.githubusercontent.com/3343990/37151576-527dd4dc-22d6-11e8-8e22-0152fca513dd.png)

Which shows the break in derivative continuity that I was talking about.

As the code I've put together makes explicit, there are two types of boundary handling we need to consider:

 1. To map interpolated points outside of the bounds of the image to either inside or reasonably close, e.g. within 1 pixel. This is properly done by your code, as far as I can tell.
 2. To map input array entries needed for interpolation that lay outside the image boundaries to a point wihin the boundaries. There is no reasonably close clause here: if you need a datapoint you need a valid index. It is very important here that you use the exact same boundary conditions for this as you used to determine the spline coefficients, which means that for now we must always use mirror for this.

The double bump is caused by that mismatch between "reflect" boundaries for the xs and "mirror" boundaries for the inner nodes. But as stated before, making both "reflect" doesn't work either:

```
plt.plot(f, 'o')
plt.plot(x, interpolate(x, filtered_f, reflect_bounds, reflect_bounds))
```
![image](https://user-images.githubusercontent.com/3343990/37151787-48a7663e-22d7-11e8-9367-3b98ba0503bd.png)

Now we have a smooth behavior, are no longer properly reproducing the image at the knots, which is not good at all.

I haven't had a chance to test it yet, but am pretty sure that if the spline coefficients had been calculated with proper reflect boundary conditions, not the mirror ones that `spline_filter1d` implements, this last image would have been exactly what we are after.

**Comment by charris** [comment]
@jaimefrio NIce! I sat down this morning to make plots like this and you have already done it :) I agree that that using coefficients computed with the correct "reflect" boundary conditions should fix the mismatch for the last example.

**Comment by jaimefrio** [comment]
I sent an e-mail this afternoon to Dr. Philippe Thevenez, a researcher at EPFL, co-author of some of the seminal papers on the use of splines for image interpolation, and author of [this code](http://bigwww.epfl.ch/thevenaz/interpolation/) that ours seems to be, ahem, *inspired* in, asking for references on how to implement spline filtering for other boundary conditions, and he has sent me a 5 page PDF full of formulas!

I need to look at them more carefully, but will be working on adding a `mode` parameter to `spline_filter` shortly, which should pave the way to a definitive solution to this. And I get to add a "personal communication from Dr.Thevenez" as a citation! :-)

**Comment by charris** [comment]
I read Dr. Philippe Thevenez' papers last time I looked at ndimage, which was some years ago. I don't recall where I got the references, maybe google, or maybe they were included somewhere in the code, but I vaguely recall google. Anyway, congratulations :)

**Comment by shoyer** [comment]
See also https://github.com/scipy/scipy/issues/2640, where I compare current behavior to a naive (but correct) implementation using np.pad .
