### ISSUE TITLE
Smoothing by convolution with window

### ISSUE THREAD

**Issue by lagru** [scipy/scipy#8504]
Is there a reason that SciPy's signal module doesn't feature a function to handle smoothing of a signal by convolution with a window? I'd like it if SciPy had a convenient function like that; I missed one in the past and had to write one myself.

I think if done properly this could be a nice addition to the signal module. I imagine a function signature like this:
```python
def moving_window(x, length=None, window_type="flat", window=None, edge="constant"):
    """ Smooth a 1D array by convolution with a window. """
    ...
```
If the feedback is positive I'd be happy to create a PR for this.

**Other links**
* [Basic example](http://scipy-cookbook.readthedocs.io/items/SignalSmooth.html) in SciPy Cookbook

**Comment by larsoner** [comment]
> Is there a reason that SciPy's signal module doesn't feature a function to handle smoothing of a signal by convolution with a window?

I think this is because in principle there are many possible choices for such smoothing functions, each of which has different tradeoffs, and these are already exposed via combinations of existing functions. Just for the case of IIR and FIR-based smoothing, there are many potential ways to combine options, including choices including:

- IIR
  - design method and parameters
  - order
  - forward or forward-backward filtering
- vs FIR
  - linear vs zero vs minimal phase
  - design method (simple `signal.window`, `firwin`, `firwin2`)
- padding choices

... and so forth. When I think of trying to provide a single monolithic function to smooth data -- even when restricting just to FIR or IIR methods -- I imagine it will end up either being incomplete or having a very dense / long API signature. This makes me -1 on adding such a function, instead preferring to educate users a bit on what their options are for achieving some particular smoothing of interest.

**Comment by lagru** [comment]
I can follow your reasoning. However I'm not suggesting to cover all approaches to smoothing but only one which can be summed up with "convolution with a window". I imagine this function would provide a quick oneliner to smooth a signal without having to design a window or filter first. 

I got the idea because one can see this implemented in some other places which may suggests that there is a demand for this, e.g.:
* [pandas.Series.rolling](http://pandas.pydata.org/pandas-docs/version/0.21.0/generated/pandas.Series.rolling.html)
* [biosppy.signals.tools.smoother](https://biosppy.readthedocs.io/en/stable/biosppy.signals.html?highlight=smooth#biosppy.signals.tools.smoother)
* Matlab's [smooth](https://de.mathworks.com/help/curvefit/smooth.html)

But, in general, I agree that it is easy to come up with a solution for this and it may be more of a "nice to have" feature than a required one.

**Comment by lagru** [comment]
Maybe it would be useful to update the [cookbook-example](http://scipy-cookbook.readthedocs.io/items/SignalSmooth.html) instead?

**Comment by larsoner** [comment]
+1 from me

**Comment by lagru** [comment]
> +1 from me

Sorry, how do you mean this. Do you approve making a PR or instead an update to the Cookbook example?

**Comment by larsoner** [comment]
+1 for updating the cookbook example.

**Comment by larsoner** [comment]
@lagru I'm going to close here, but feel free to open an issue or PR to https://github.com/scipy/scipy-cookbook/issues/
