### ISSUE TITLE
scipy.stats.combine_pvalues with stouffer method cannot deal with p values that has `1.0`

### ISSUE THREAD

**Issue by logust79** [scipy/scipy#8506]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

When using scipy.stats.combine_pvalues with stouffer method, when there is a 1.0 in the p value array, it returns `(-inf, 1.0)`

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```
>>> pvals = [1e-5, 1.0]
>>> stats.combine_pvalues(pvalues=pvals,method='stouffer')
(-inf, 1.0)
>>>## note that fisher method has no problem dealing with `1.0`
>>> stats.combine_pvalues(pvalues=pvals)
(23.025850929940457, 0.0001251292546497022)

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```
NA
### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```
1.0.0 1.13.3 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)

At last, thanks so much for this excellent package!

**Comment by chrisb83** [comment]
I am not very familiar with these tests, but looking at https://en.wikipedia.org/wiki/Fisher%27s_method, the result is formally correct:
since you need the inverse of the normal CDF evaluated at 1 - p, you get +inf if p=0 or -inf if p=1.
(you get `(nan, nan)` if you run `stats.combine_pvalues([0, 1], method='stouffer')`).
Also `stats.combine_pvalues([0, 0.5])` gives `(inf, 0.0)`.

So these are really boundary cases and one can think about how to treat them. The R package metap displays seems to remove such cases and shows a warning (https://cran.r-project.org/web/packages/metap/metap.pdf).

**Comment by logust79** [comment]
I guess then this is rather a caveat of stouffer method itself.
