### ISSUE TITLE
Proposal for new labels on GitHub issues

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#8517]
As our issue count hit 1k and kind of stabilized there I was wondering if we can improve our backlog tracking to maybe bring it down. 

Recently, I've been noticing newer labels on different repositories which seems to make a real difference in welcoming new contributors and also showing the dev team intentions better. Two very nice label examples (in my opinion that is) is the node.js

![image](https://user-images.githubusercontent.com/1303842/36945115-5bd3f3c0-1fa9-11e8-898c-1c17d91202fc.png)

This gives a quite clear message to newcomers and mentor available part is really nice to directly pair up and start working without the risk of contributor wandering off to a direction that we don't really wish to proceed. The second example I find helpful is spyder

![image](https://user-images.githubusercontent.com/1303842/36945131-8f645086-1fa9-11e8-8859-b8553e060a05.png)

There are also *in progress* and *stalled* labels that helps to classify active and deserted issues. What do you think of such classifications?

**Comment by rgommers** [comment]
The `status: Awaiting Followup` one makes sense to me. The `mentor available` one not so much, that will very likely go out of date. I'd prefer labels that don't need maintenance, only action/change if something happens (like someone starts working on it).

In the bigger picture, I'd be most interested in the kinds of labels/docs/etc that helps us get more long-term contributors/maintainers. In my experience, the `good first issue` kind of contributors eat up a lot of time and very rarely stay around. That doesn't mean that label isn't useful, but I'm a bit skeptical of further focusing on attracting more complete novices.

**Comment by ilayn** [comment]
That's indeed a problem but on the other side we have lots of issues stalled with last a few comments asking what the status is. It is quite hard to find them even when you know they are there. Obviously, labels won't solve issues but maybe it can make it +0. easier.

**Comment by pv** [comment]
I've been using the `needs-work` label for this purpose, to mark PRs that are are waiting for reaction.
The list at https://pav.iki.fi/scipy-needs-work/ will update if new commits are pushed.

**Comment by ilayn** [comment]
Maybe I should reword the intention of this issue. I don't propose to come up with a new *magical* set of labels that would solve everything. But seeing the latest GSoC application mails and also newcomers commenting on the issues maybe we can create a way of working such that they can dig up issues that they can work on themselves instead of asking everytime whether they can pickup an issue. 

Naturally, this might not be a good idea because of a reason that i can't think of right now. Hence this issue.

**Comment by ev-br** [comment]
There's also a `needs-champion` label, which can be renamed and reused. So far it wasn't all that useful, it seems.

**Comment by pv** [comment]
I suspect some newcomers ask that question because they don't really know how this works, and are under an impression that they need to get an OK before starting to work on something. I'm not sure how to dispel that notion --- maybe there's something misleading in our "how to contribute" documentation?

**Comment by ilayn** [comment]
Actually thinking about this, indeed this assumes that the new users know about the labeling system which is not necessarily true. So it might be not so practical as I originally thought about. I guess it won't help that much.

**Comment by lagru** [comment]
> [...] and are under an impression that they need to get an OK before starting to work on something.

A newcomer can't necessarily be sure that he understood the problem / issue topic and reached the right conclusions. Guessing the goal which the maintainers have in mind requires experience and in the beginning most likely feedback. And because most people don't want to start working in the wrong direction asking for prior confirmation is reasonable and might be a reason to ask for an "OK".

I don't think the documentation is misleading here. On the contrary it might be useful to highlight a channel (issues / mailing list) where newcomers can ask for this kind of feedback if you want to encourage it. That way misconceptions might be mitigated early before causing more work in the long run.

> [...] assumes that the new users know about the labeling system which is not necessarily true.

It might be helpful to lower the barrier here by adding descriptions to each or the most used / vague labels. From what it looks like in your first post the user can get an additional tooltip by hovering above a label. In SciPy the labels I checked only repeat their name in the tool-tip.

**Comment by ilayn** [comment]
The required actions mentioned so far won't need any decision so closing. We can continue to discuss anyhow.
