### ISSUE TITLE
anderson_ksamp outputs for identical samples and large samples

### ISSUE THREAD

**Issue by mick-d** [scipy/scipy#8536]
I already described the issue in details in a stack overflow [post](https://stackoverflow.com/questions/49136617/math-overflow-error-in-scipy-anderson-darling-test-for-k-samples) (to make sure the cause was not my misunderstanding). It has some overlap with this [other reported issue](https://github.com/scipy/scipy/issues/5493).

In short, for identical samples I got negative statistics and for large samples an overflow. I believe the statistic could at least be corrected (as per the solution suggested in the comments of the accepted stack overflow answer for example) while for the overflow I am not sure if something could be done. The Kolmogorov-Smirnov (KS) test (`scipy.stats.anderson`) provides expected results in contrast but the properties of the Anderson-Darling (AD) test may be more attractive to some users.

### Reproducing code example:
```
import scipy.stats as sstats
import numpy as np
normal1 = np.random.normal(loc=0.0, scale=1.0, size=200)
normal2 = np.random.normal(loc=100, scale=1.0, size=200)
```
Using KS and AD on identical samples:
```
sstats.ks_2samp(normal1, normal1)
sstats.anderson_ksamp([normal1, normal1])
```

Returns respectively:
#### Expected
```
Ks_2sampResult(statistic=0.0, pvalue=1.0) 
```
#### Not expected
```
Anderson_ksampResult(statistic=-1.3196852620954158, critical_values=array([ 0.325,  1.226,  1.961,  2.718,  3.752]), significance_level=1.4357209285296726)
```
And on the different samples:
```
sstats.ks_2samp(normal1, normal2)
sstats.anderson_ksamp([normal1, normal2])
```
Returns respectively:
#### Expected
```
Ks_2sampResult(statistic=1.0, pvalue=1.4175052453413253e-89)
```
#### Not expected
```
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-757-e3914aaf909c> in <module>()
----> 1 stats.anderson_ksamp([normal1, normal2])

/usr/lib/python3.5/site-packages/scipy/stats/morestats.py in anderson_ksamp(samples, midrank)
   1694         warnings.warn("approximate p-value will be computed by extrapolation")
   1695 
-> 1696     p = math.exp(np.polyval(pf, A2))
   1697     return Anderson_ksampResult(A2, critical, p)
   1698 

OverflowError: math range error
```
### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
0.19.1 1.13.1 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by chrisb83** [comment]
hi,

using scipy 1.0.0, `ks_2samp` seems to be ok in the first example: 
`Ks_2sampResult(statistic=0.0, pvalue=1.0)`

I also don't get the overflow error:
`Anderson_ksampResult(statistic=202.74793118968645, critical_values=array([0.325, 1.226, 1.961, 2.718, 3.752]), significance_level=inf)`
But inf is not much better...

The issue is a nice example of a bad Interpolation: 
The test is such that p-value is a decreasing function of the statisic. For 3.752, p-value is 0.01. In the example, statistic = 202, so p-value should be essentially 0

Interpolation in the code works as follows: write log(p-value) = f(statistic)
f = quadratic polynomial, fit coefficients based on known values

The code is the following to derive the p-value based on the statistic `A2` is as follows:
```
m = 1 # 2-sample
b0 = np.array([0.675, 1.281, 1.645, 1.96, 2.326])
b1 = np.array([-0.245, 0.25, 0.678, 1.149, 1.822])
b2 = np.array([-0.105, -0.305, -0.362, -0.391, -0.396])

critical = b0 + b1 / math.sqrt(m) + b2 / m

pf = np.polyfit(critical, np.log(np.array([0.25, 0.1, 0.05, 0.025, 0.01])), 2)

if A2 < critical.min() or A2 > critical.max():
    warnings.warn("approximate p-value will be computed by extrapolation")
try:
    p = math.exp(np.polyval(pf, A2)) / (1 + math.exp(np.polyval(pf, A2)))
except (OverflowError,):
    p = float("inf")

print(p)
```

but it is clear that the fit is very bad if the test statisitc becomes large:  pf[0] = 0.025, so as statistic goes to infinity, so does f(statistic). this is the oppposite what log of p-value should do: if the test statistic is large, p-value is small so log(p) should to to -infinity...

```
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

# check p-values on the range of known critical values
x = np.linspace(0.3, 4, 10)
p = np.exp(np.polyval(pf, x))
plt.plot(x, p)
plt.show()

# if the range is extended, p-values start to explode at some point
x = np.linspace(0, 42)
p = np.exp(np.polyval(pf, x))
plt.plot(x, p)
plt.show()
```

So the target quantity needs to be redefined: one option is to use a probit transformation: `log(p/(1-p))`(see documentation of R package kSamples https://cran.r-project.org/web/packages/kSamples/kSamples.pdf)
this transformation increasing and goes from -inf to +inf, so again, with a polynomial of degree 2, no chance to fit it. but cubic polynomial seems to work...

```
sig_level = np.array([0.25, 0.1, 0.05, 0.025, 0.01])
prob_sig = np.log(sig_level / (1 - sig_level))
pf3 = np.polyfit(critical, prob_sig, 3)

x = np.linspace(0, 50)
y = np.exp(np.polyval(pf3, x)) / (1 + np.exp(np.polyval(pf3, x)))
plt.plot(x, y)
plt.show()
```

So at least the overall "direction" is ok in that case (i.e. p-val goes to 0 as statistic goes to inf), but haven't checked how good the approximation is. It looks like the package kSamples could help...

**Comment by josef-pkt** [comment]
good idea about using the logit transformation

also I think we can use some critical values from R kSamples https://github.com/scipy/scipy/issues/5493#issuecomment-236360597
numbers/facts cannot be copyrighted, AFAIK.

I don't think using a polynomial for extrapolation is very useful, at least not any higher order polynomial.

(In statsmodels we report mainly the boundary p-value when using tables instead of extrapolation. So I don't have a recipe or experience for the extrapolation part.)

**Comment by josef-pkt** [comment]
a quick try on simulating critical values
https://gist.github.com/josef-pkt/e99dabd22bea0b2c8da9bd6ec258b6e4

anderson_ksamp is asymptotically distribution free, so I just picked uniformly sampled data
example uses k=3 samples, and nobs=500 observations

One million simulations take around 12 minutes (on my computer), and are close to the tabulated critical values, with similar rejection frequencies.

critical values depend on k, so there doesn't seem to be a way around simulating and approximating across k.

```
alpha_ad = np.array([25, 10, 5, 2.5, 1])/100.
print(alpha_ad)
print(r.critical_values)
print(np.percentile(res_mc[:, 0], (1 - alpha_ad)*100))
[ 0.25   0.1    0.05   0.025  0.01 ]
[ 0.44925884  1.3052767   1.9434184   2.57696569  3.41634856]
[ 0.4430453   1.30667879  1.94746397  2.59038275  3.44501301]
```

**Comment by chrisb83** [comment]
> critical values depend on k, so there doesn't seem to be a way around simulating and approximating across k.

in the current implementation, the critical values are approximated via the formula `critical = b0 + b1 / math.sqrt(m) + b2 / m`. maybe something like this still works if one extends the percentiles. 

> also I think we can use some critical values from R kSamples. numbers/facts cannot be copyrighted, AFAIK.

it would require looking at the source code, i remember rgommers saying that this is not allowed, but I don't know...

i am thinking about adding a function `pvalue_anderson` that
- interpolates p-values over the known range from 0.01 - 0.25
- if outside this range, display boundary value only (i.e. 0.01 / 0.25) + warning (i agree with josef-pkt that approximation is questionable since it is unclear how good it is + unclear if showing p-values like 1e-5 offer much insight)

this fixes the issue, one can add a few test cases to ensure that p-values are ok and can be refined at a later stage if needed.

**Comment by josef-pkt** [comment]
> also I think we can use some critical values from R kSamples. numbers/facts cannot be copyrighted, AFAIK.
it would require looking at the source code, i remember rgommers saying that this is not allowed, but I don't know...

I guess some of the critical values or pvalues could be obtained by just running some examples and without looking at the source code.

I think reporting boundary p-values and warning would be fine as a bugfix.
Long term solution would still be to have p-values **inter**polated over a larger range and restricted to [0, 1], which would change the behavior twice for values outside the tabulated, current interpolation range. 

(e.g. in some cases I warned users to use <= or >= boundary value instead of relying on == boundary value check, in  order to be more robust to future changes in statsmodels.)

**Comment by mick-d** [comment]
Many thanks to everyone for addressing this issue.

**Comment by chrisb83** [comment]
@josef-pkt i also looked at the simulation of the critical values in the mean-time: https://gist.github.com/chrisb83/5b94ef565b9541a1d53d39dcac5e536e

- reproduces critical values given in paper Scholz & Stephens for different k
- adds critical values for significance Level 0.001 and 0.005
- determines coefficients to interpolate the critical values for other values of k 

I still need to test the result against `kSamples` package in R...

**Comment by josef-pkt** [comment]
@chrisb83  Looks good.
From looking at the notebook for 10 minutes, I cannot really tell anything about the details. I never checked how Stephens and co-authors got their simulated values. So, unless there is a specific issue to look into, I'm only looking at the surface. And on the surface it looks good.

Aside: Pearson curves were popular to at least the mid 1970s, e.g. in older Stephens' articles, but I never really figured out how to get those approximations.

Aside 2: The simulation distribution looks like a weighted sum of chisquare random variables. Those show up in several other contexts also, but I only have open issues for it (in statsmodels) and no real code and approximations yet.

**Comment by chrisb83** [comment]
thanks, there was no particular question, it was just to inform you about it since you also had an idea how to simulate the critical values. and yes, the test statistic is asymptotically (N -> inf) distributed like a weighted (infinite) sum of chi-square variable.

- in the paper, they calculte the first four moments and then fit Pearson curves, then compute the quantiles
- here I simulate the weighted sum directly and compute quantiles (very simple approch, probably one could use bootstrapping)

in order to extend the critical values in scipy, do you think such a notebook + testing against R is enough? in which context did you observe weighted sums of chi-square varibles?

**Comment by josef-pkt** [comment]
> in order to extend the critical values in scipy, do you think such a notebook + testing against R is enough?

If you can verify the numbers against R, then everything is fine. If there are no reference numbers from other packages (which I start to run into more often now in statsmodels), then verification is more difficult, and I'm using Monte Carlo simulation in some cases.

IMO, it would be useful to put the code for simulating the critical values into the scipy repo, so somebody can check and rerun the simulations in 10 years, if needed.

> in which context did you observe weighted sums of chi-square varibles?

One common case is in the likelihood ratio type tests when the assumptions of MLE are not satisfied, e.g. because of some misspecification or incomplete specification.

**Comment by chrisb83** [comment]
Closing this issue in view of the two PRs (fixing Interpolation and extending range of critical values).

**Comment by rgommers** [comment]
Hmm, I checked this when I merged the PR - I still get the wrong answers. The PR didn't seem to claim to close this issue. Shouldn't this remain open?

**Comment by rgommers** [comment]
> I could not reproduce the issue reported for ks_2samp

yes that seems fixed.

> for `anderson_ksamp`, #8560 should avoid p-values outside of [.01, .25]

Ah somehow my warnings were being suppressed and it looked like I still got the same values as the original report:
```
## -- End pasted text --
/home/rgommers/anaconda3/bin/ipython:8: UserWarning: p-value capped: true value larger than 0.25
  
Anderson_ksampResult(statistic=-1.3196852620954158, critical_values=array([0.325, 1.226, 1.961, 2.718, 3.752, 4.592, 6.546]), significance_level=0.25)
```
but it's the `significance_level` that changed. Sorry for the noise.
