### ISSUE TITLE
`signal.decimate` default axis deviates from that of `signal.resample` and `signal.resample_poly`

### ISSUE THREAD

**Issue by mgrachten** [scipy/scipy#8570]
The function `signal.decimate` applies to the last axis of the input array by default, whereas its sibling functions `signal.resample` and `signal.resample_poly` (they all perform resampling, and appear in the "see also" Section of each other's documentation) apply to the first axis of the input array by default. This may surprise the user, and I think it is better for these three functions to use the same default axis.

Which axis is the most intuitive default axis is of course open to discussion, but I think the first axis is a good choice.

**Comment by larsoner** [comment]
I agree it would be nice to be consistent here.

However, there is a cost to changing a parameter default. `resample` and `decimate` have both been around with this argument default for a long time (at least since 0.11, as far back as I looked), so we would potentially force a lot of people to change working code. We would probably need a potentially long deprecation cycle to change it. Moreover there are some functions that operate along `-1` and others that operate along `0` (e.g., [freqz](http://scipy.github.io/devdocs/generated/scipy.signal.freqz.html#scipy.signal.freqz)), so we would still have inconsistencies even if we changed this.

These considerations push this into the "wontfix" / "not worth it" category for me, even though it bothers me, too.

FWIW I generally prefer the last axis as the default, since this is the default contiguous one (C order) in NumPy (unlike in MATLAB, which uses Fortran ordering).

**Comment by mgrachten** [comment]
Thanks for your comments.

> FWIW I generally prefer the last axis as the default, since this is the default contiguous one (C order) in NumPy (unlike in MATLAB, which uses Fortran ordering).

I proposed the first dimension from a semantic perspective: My experience is that in multi-dimensional time series data (e.g. audio) you usually want to resample the time dimension, which is is typically the first. Of course this argument may not convince people working with images or other types of data.

I see your point about the deprecation cycle, it would be a small change with potentially a high cost.

**Comment by larsoner** [comment]
I'm going to close this as `wontfix` for backward compatibility reasons, but we should keep this in mind if we develop a new interface in the future.
