### ISSUE TITLE
For Windows build as much as possible with mingw-w64 toolchain

### ISSUE THREAD

**Issue by KOLANICH** [scipy/scipy#8622]
It's a well-known fact that gcc generates much faster code than Visual Studio. I have built some modules with gcc (more precisely: `scipy.signal._peak_finding`, some other ones also have been built, but I have taken only this one and some other) and they work fine. I guess that the building script should check presence of mingw-w64 and build the modules buildable working with it with it.

**Comment by rgommers** [comment]
That's not a maintainable option, sorry. Users are free to compile the whole project with mingw-w64 (not easy but has been done, see mingwpy project); the official binaries will remain MSVC-only until we have a maintainable all-gcc/clang solution.

**Comment by matthew-brett** [comment]
@KOLANICH - to unpack Ralf's answer a bit - the problem is that Python is compiled against the version-specific MSVC runtime libraries, whereas mingw-w64 compiles against its own runtime libraries.   The consequence is that  Python code can create objects like file-handles derived from the MSVC library, and then pass that into the mingw-w64 code, that will assume the object was created with its own library.  This is called passing objects across run-time library boundaries.  We don't have a specific example of an error caused by this, but the potential for such an error covers such a vast range of possibilities, that we've decided to avoid that, in our standard builds.

**Comment by KOLANICH** [comment]
Thank you for clarification.

**Comment by rgommers** [comment]
Thanks Matthew. That's a technical reason. Not what I was thinking about though - even if we could fix that one, there's no way we want to mix multiple C compilers in a nonstandard way, it's unmaintainable, risky, and just not worth it for the gains we may get.
