### ISSUE TITLE
linprog with method=interior-point produced incorrect answer for a simple input

### ISSUE THREAD

**Issue by savrus** [scipy/scipy#8663]
optimize.linprog with method='interior-point' produces wrong answer for a following program:

```
minimize  x + 5y
subject to
-7y <= -6
x >= 0
```

### Reproducing code example:
```
import scipy.optimize
c = [1, 5]
A = [[0, -7]]
b = [-6]
bounds = [(0, None), (None, None)]
res1 = scipy.optimize.linprog(c, A, b, bounds=bounds)
res2 = scipy.optimize.linprog(c, A, b, bounds=bounds, method='interior-point')
print res1
print
print res2
assert not (res1.success and res2.success) or abs(res1.fun - res2.fun) < 1
```

### Output:
```
     fun: 4.2857142857142856
 message: 'Optimization terminated successfully.'
     nit: 1
   slack: array([ 0.])
  status: 0
 success: True
       x: array([ 0.        ,  0.85714286])

     con: array([], dtype=float64)
     fun: 0.0
 message: 'The solution was determined in presolve as there are no non-trivial constraints.'
     nit: 0
   slack: array([-6.])
  status: 0
 success: True
       x: array([ 0.,  0.])
Traceback (most recent call last):
  File "buglinprog.py", line 37, in <module>
    assert not (res1.success and res2.success) or abs(res1.fun - res2.fun) < 1
AssertionError

```

### Scipy/Numpy/Python version information:
```
('1.0.1', '1.8.2', sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0))
```

**Comment by mdhaber** [comment]
I'll look into it.

**Comment by mdhaber** [comment]
In the meantime, use `options = {"presolve":False}`
It's a problem with the presolve routine. I get an error, actually.

**Comment by savrus** [comment]
Thanks!

**Comment by mdhaber** [comment]
Please don't lose faith in `linprog` because of these two issues : ) 
There are several instances of bugs in `simplex` similar to the one you reported in #8662.

The problem seems too simple for `interior-point`'s own good. It tries to apply simple rules successively to simplify a problem like this, but this problem seems to expose a mistake in these rules. For example, the presolve routine should see that `x` is not involved in the inequality constraint, so it will determine the value of x that minimizes `x` in the objective subject only to the bound constraint ( `x = 0` ), then remove `x` from the problem entirely. It should then recognize that the inequality constraint on `y` can be turned into a simple bound, and then the value of `y` can be chosen to minimize `5y` in the objective (`y = 6/7`). Anyway, these rules can be trickier to get perfect than the main problem, which is just a bunch of linear algebra operations. Sorry for the trouble but thanks for exposing this.

**Comment by savrus** [comment]
Thanks for the detailed reply! It is really nice that you react to issues so fast. I'm just playing with LP and have detected some abnormalities. I hope my reports are useful and will help you make scipy a little better :)
