### ISSUE TITLE
mininimize with 'SLSQP' gives stochastic results

### ISSUE THREAD

**Issue by attack68** [scipy/scipy#8677]
I am running the SLSQP minimizer in the following manner:

```
minimize(_f_prelim, x_0, args=(R_it_, A_ijtk_, w_k_, Q_jtluk_, a_t_, c_0_, L, [0], (idx_l, idx_r)),
                method='SLSQP', options={'disp': disp, 'ftol': 1e-2, 'maxiter': 120},
                jac=_grad_f_prelim, constraints=(dict(type='eq', fun=_eq_constr, args=([0],))))
```

I thought this was a deterministic algorithm, and I have had a look at the code to try and detect whether any random elements might creep in but I can't find any. I do not have any specific randomness in my function or gradient methods and I do not initialise any numpy arrays using random array creation. Yet the results I obtain when running this algorithm differ, often between 2 or 3 distinct solutions. Even the distinct solutions do not always return precisely the same solution.

My initialisation vector is, of course, always the same as are all other inputs. I might point out that my derivative of this function is technically undefined at x=0 since the objective function involves sign(x). None of my initial values are zero though.

Before digging deeper and perhaps sharing a reproducible use-case I wanted to ask the opinion of member here to see if there are any common misunderstandings or misuses that I am not aware of, and any tips that one might offer?

(using latest versions).

**Comment by pv** [comment]
https://software.intel.com/sites/default/files/managed/de/a1/FP_Consistency_091117.pdf

**Comment by pv** [comment]
That talks about Intel compilers specifically, but the issue is more
general.

Especially varying between a small number of different results can be
due to e.g. data alignment affecting the rounding error, for example in
the underlying linear algebra library that is being used (typically
Intel MKL if using anaconda).

**Comment by attack68** [comment]
I was kind of hoping someone might say this. I'm aware of floating point precision but had never encountered an area where the effect was noticeable, and had not necessarily been aware of the error, and so I suppose I remained skeptical. I appreciate the fast response though and its useful for my continued research! Thank you.

**Comment by ilayn** [comment]
The effect is particularly pronounced if there is a rank-reduction-like step involved or projection steps of the optimization algorithms. For example, if the resulting singular value is, say, very very close to the cutoff threshold so sitting on the fence and due to these minute effects one can have extra rank and all bets are off afterwards. If the issue persists even after you nudge the tolerances then your problem might be ill-conditioned.
