### ISSUE TITLE
scipy.signal.find_peaks works incorrectly in presence of nans

### ISSUE THREAD

**Issue by KOLANICH** [scipy/scipy#8708]
### Reproducing code example:
https://pastebin.com/raw/Br00U5pc

When nans are present it doesn't detect some peaks.

If I left a single leading nan it works. I have not tested deeply the dependence on count of nans.

**Comment by pv** [comment]
cc @lagru

**Comment by lagru** [comment]
Thanks, I'll check it out right now.

**Comment by lagru** [comment]
But there are scenarios where `find_peaks` doesn't detect peaks, because nans are present e.g.:
```python
>>> find_peaks([0, np.nan, 1, 0])
(array([], dtype=int64), {})
```
This is because the underlying functions (in this case `_argmaxima1d`) don't consider that value comparison of valid samples to nans is always false.  But to handle / fix this we need to decide what behavior we expect for nans. Should `find_peaks` detect the 2nd sample as a valid peak? A peak is defined as a sample that is surrounded on both sides by smaller samples, so according to that definition the correct result in this case is an empty array.

Anyway, this behavior should definitely be documented.

**Comment by larsoner** [comment]
> so according to that definition the correct result in this case is an empty array.

> Anyway, this behavior should definitely be documented.

Agreed, for now we can document it. Eventually we might want a parameter for how to handle NaN (e.g., ignore it rather than treat it as always-False), but we can add that later and make the current behavior the default.

**Comment by KOLANICH** [comment]
>I don't see any unexpected behavior for your example. The output and detected peaks for both options (with and without nans) look the same to me (apart from the removed signal values)

I have rebuilt the module from the latest git, now it works correctly.

**Comment by lagru** [comment]
I'm happy that solved it. And thank you for bringing NaNs to my attention. I hadn't considered that aspect until now. :)
