### ISSUE TITLE
scipy.signal.chirp problem

### ISSUE THREAD

**Issue by art4206** [scipy/scipy#8745]
Scipy.signal.chirp produces strange looking frequency sweep - see figure and example code below.

![figure_1](https://user-images.githubusercontent.com/38438950/38828458-c5abcaae-417b-11e8-941f-e053b743f51b.png)

  Looking at the source code for Scipy.signal.chirp pasted below:
           # 'phase' is computed in _chirp_phase, to make testing easier.
           phase = _chirp_phase(t, f0, t1, f1, method, vertex_zero)
           # Convert  phi to radians.
           phi *= pi / 180
           return cos(phase + phi)

The phase from _chirp_phase should be converted from degrees to radians for numpy.cos to work correctly.

### Reproducing code example:
```
import os
import numpy as N
import matplotlib.pyplot as plt
from scipy.signal import chirp

fStart = 5
fStop = 10005
scanTime = (8 * 60.)
fCycles = (fStop-fStart)/scanTime
numPoints = 600000
stepTime = scanTime/numPoints
t = N.linspace(0, scanTime, numPoints)
pulseSeq = chirp(t, f0=fStart, f1=fStop, t1 = scanTime, method = 'linear')
plt.plot(t,pulseSeq)
plt.show()

```

### Error message:
```
The phase from _chirp_phase should be converted from degrees to radians for numpy.cos to work correctly.
```

### Scipy/Numpy/Python version information:
```
('1.0.0', '1.14.0', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))
```

**Comment by rkern** [comment]
The phase returned from `_chirp_phase()` is already in radians, not degrees.

**Comment by WarrenWeckesser** [comment]
As the first paragraph of the [`chirp` docstring](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.chirp.html) explains, the function expects `f0` and `f1` to be expressed in cycles per time unit (not radians per time unit).  If the time unit is seconds, then the frequencies must be in Hz.  The function `_chirp_phase` already converts the phase values to radians, so that is not the source of your problem.

Your problem is [aliasing](https://en.wikipedia.org/wiki/Aliasing).  You are varying the frequency from 5 Hz (assuming `t` is measured in seconds) to 10005 Hz, but your sample rate of that signal is (approximately) `numPoints/scanTime`, which is 1250 Hz.  To minimize aliasing, you'll have to sample at more than 20010 Hz.  20010 would be the minimum required if the bandwidth was exactly 10005 Hz, but the varying frequency undoubtedly generates higher bandwidth.  To test, try using a short time interval (so you don't have such huge samples), and increase the sample rate.

**Comment by WarrenWeckesser** [comment]
@art4206, I'm closing the issue, but don't hesitate to comment here if you have questions.
