### ISSUE TITLE
scipy.stats.kstest for same distribution: p-values nonuniform

### ISSUE THREAD

**Issue by hsnee** [scipy/scipy#8748]
AFAIK, performing a KS Test when comparing two samples that are drawn from the same distribution will return uniformly distributed p-values (e.g. [this stackexchange thread](https://stats.stackexchange.com/questions/10613/why-are-p-values-uniformly-distributed-under-the-null-hypothesis)), but trying this out (see below) returns p-values that are clustered around 1, and not completely uniform.

### Reproducing code example:

<img width="692" alt="kstest" src="https://user-images.githubusercontent.com/12966709/38841269-9d281444-41b1-11e8-888f-2b838178080f.png">

### Scipy/Python version information:
```
python 3.6.3
scipy 1.0.1
macOS 10.13.4
```

**Comment by josef-pkt** [comment]
try with a much larger N, e.g 500 or 1000. 
This might be either a small sample problem, or that the kolmogorov-smirnov distribution uses a not very good approximation close to zero. (That area is irrelevant for rejection decisions and often not very well supported in distributions that are mainly written to support hypothesis tests.)

**Comment by pvanmulbregt** [comment]
The two-sided stats.kstest() uses the p~scipy.stats.kstwobign.sf() approximation for the probability once p is bigger than about 0.8, and p~2*scipy.stats.ksone.sf() approximation otherwise.  The approximation is better for larger N rather than N=20.

**Comment by hsnee** [comment]
Thanks, that explains it -- trying this with N≥500 does return a uniform distribution.

**Comment by pvanmulbregt** [comment]
I repeated the example for many N (but with only 1000 repetitions rather than 10,000) to generate 1000 probs for each N and each of the 3 `kstest` alternate conditions ('two-sided', 'greater', 'less') values.  Rather than plotting a histogram, I asked a second invocation of `kstest` for a new p-value to see if it thought that collection of 1000 p-values appeared uniform, and then plotted those new p-values, one for each N.
[Something like the following for each of the 9=3x3 combinations of alternatives to `kstest`, except I only generated rvalues once for each N and reused them.
```
y=[]
for N in range(1, 1000):
    rvalues = np.array([np.sort(scipy.stats.uniform.rvs(size=N)) for _ in range(1000)])
    pvs = np.sort(np.array([scipy.stats.kstest(row, 'uniform', alternative='two-sided').pvalue for row in rvalues]))
    y.append(scipy.stats.kstest(np.sort(pvs), 'uniform', alternative='greater').pvalue)
    plt.plot(y)
```
]
![ks1_1000](https://user-images.githubusercontent.com/23403152/38896768-ac35159e-4261-11e8-9ec6-d116ce2b83c9.png)

`'greater'` and `'less'` use the Smirnov one-sided probabilities from `scipy.stats.ksone`, and are labelled `'S+'`, `'S-'`.  `'two-sided'` mostly uses the Kolmogorov two-sided probabilities from `scipy.stats.kstwobign` and are labelled `'K'`.

In the 3x3 grid, the top row of plots comes from lining up the 1000 two-sided probabilities and asking the three alternatives of `kstest` whether they think those 1000 probs are uniformly distributed.
The 2nd and 3rd row comes from using the 1000 `greater` than probs, and the 1000 `less` than probs.  
From looking a the 2nd and 3rd rows, they could conceivably be uniformly distributed.
However, in the first row, applying the one-sided Smirnov test(s) to the original two-sided probabilities do not look uniformly distributed to my eye, even for N near 1000.

The conclusion is that using the two-sided "big-n" approximation in `stats.kstest( ..., alternative='two-sided")`  is quite poor until N is very large.  Unless specified explicitly in the call, the alternative used is `"two-sided"`.

**Comment by chrisb83** [comment]
@pvanmulbregt I am not sure if I can follow your argument and I would be surprised if there is a problem with the appoximation if N ~ 1000. 

I did a simple check as follows:

```
np.random.seed(3251) 
# generate 1000 p-values based on uniform samples of size 500
rvalues = np.array([stats.uniform.rvs(size=500) for _ in range(1000)])
pvs = np.array([stats.kstest(row, 'uniform', alternative='two-sided').pvalue for row in rvalues])
# check if p-values are uniform
stats.kstest(pvs, 'uniform') # does not reject null
plt.hist(pvs, bins=20)
```
I also tried a couple of other seeds, same conclusion.
