### ISSUE TITLE
Might it be worth allowing certain algorithms to be implemented using CuPy?

### ISSUE THREAD

**Issue by grantmwilliams** [scipy/scipy#8758]
[CuPy](https://github.com/cupy/cupy) is a numpy like api that allows for CUDA based calculations. There are a number of implementations in this library that might benefit from it. 

Could experimental versions of algorithms (some of the gradient descents jump to mind) be implemented in CuPy?

Maybe they could be named something like `_experimental_cuda_lbfgs(args)`.

I'd assume they would have to be separate from the main `optimize()` method, but it still might provide value for some users.

**Comment by sschnug** [comment]
To start some discussion:

- a lot of those candidates (in optimization) are wrapped C/C++/Fortran codes and cupy won't help without reimplementing the whole algorithm (and some of those were implemented over years)
    - e.g. [L-BFGS-B](http://users.iems.northwestern.edu/~nocedal/lbfgsb.html)
- a lot of algorithms are probably not that ready (given current understanding) for GPU-based computation and deciding/researching/evaluating probably costs a lot of time
    - while indirect matrix-vec based methods probably have potential; direct (sparse) methods is a very different thing
    - i'm (not a scipy-dev) not sure if those resources would be better spend on improving or adding new CPU-based algorithms
- while cupy does have a nice license, i don't think shipping the requirement Cuda Toolkit is an option (and not much of scipy is designed to use optional software; i only know of scikits.umfpack and that's maybe due to scipy's history, previously being using umfpack before dropping due to licenses)
    - here again: if there is a competition in terms of devloper-time, i would prefer to see adding optional (license-incompatible) high-quality software like MUMPS, Clp/Cbc or Ipopt (in open-source world) before adding this which needs further research to be of great use 
- (maybe those *experiemental* things would be an additional source of confusion for some users; reading some StackOverflow shows frequent problems in the usage of the already implemented things in scipy.optimize and GPU-things will induce a lot of: *why is GPU slower than CPU* questions)

So i'm expecting some discussion of:

- where will this really help 
    - the sentence *There are a number of implementations in this library that might benefit from it* sounds a bit too optimistic (imho)
- are there enough people motivated and able to implement these new things
- is scipy open for optional license-incompatible software (given my assumption Cuda Toolkit is not compatible)

But let's hear some input from the scipy-team.

**Comment by rkern** [comment]
I think this is better done in a separate package.

**Comment by larsoner** [comment]
Agreed, a separate package is probably best.

FWIW there are some CUDA-based overlap-add FIR filtering and FFT-based resampling routines you could adapt from mne-python, which currently use `scikit-cuda` and `pycuda`:

https://github.com/mne-tools/mne-python/blob/master/mne/cuda.py

**Comment by ilayn** [comment]
Not to mention, especially for non-nvidia based architectures it would be just unnecessary baggage to carry around.

**Comment by grantmwilliams** [comment]
I do think it could work well as an optional and separate package that extends SciPy. I think both SciPy and numpy have a decent amount of use with some of the preprocessing steps of training deep leanring models, and with programs where these models are deployed. 

Sine the entire deep learning field is built around CUDA (along with a large amount of scientific computing) I think it could provide value by helping speed up common tasks. 

I'm thinking the real issue would be justifying the time to implement and test the algorithms. Might not be a good idea to pull away dev time from the core package for an extension that might not be used too often.

[https://github.com/uploadcare/pillow-simd](Pillow-SIMD) is what originally got me started thinking about extending some areas into the GPU as a separate package/extension

**Comment by rgommers** [comment]
> Might not be a good idea to pull away dev time from the core package for an extension that might not be used too often.

Yeah, this would have to be a standalone package, along the lines of https://github.com/pyFFTW/pyFFTW which offers improved performance over `scipy.fftpack`. This can't really be taken on by the SciPy team itself.

At this point I think there's consensus around a separate package, so I'll close this issue. Discussion can continue of course
