### ISSUE TITLE
cdist behavior with Minkowsky and np.inf

### ISSUE THREAD

**Issue by jberwald** [scipy/scipy#8776]
Using `scipy.spatial.distance.cdist` with the Minkowski distance and `p=np.inf` does not produce expected result. In particular, I'm not sure how `cdist` is producing all distance of only 1's (see Minkowski below). Using Chebyshev distance produce expected results, but they should be equivalent for $p=\infty$.

```
import numpy as np
import scipy.spatial as sp

a = np.array([[1.11132, 1.15693], [0.98214, 1.01018]])
b = np.array([[1.14994, 1.15386 ], [0.973258, 1.17015 ], [0.939203, 1.09205 ]])

print("a:\n{}".format(a))
print("b:\n{}".format(b))

mink = sp.distance.cdist(a, b, 'minkowski', p=np.inf)
print("Minkowski:\n{}".format(mink))

cheb = sp.distance.cdist(a, b, 'chebyshev')
print("Chebyshev:\n{}".format(cheb))

a:
[[1.11132 1.15693]
 [0.98214 1.01018]]
b:
[[1.14994  1.15386 ]
 [0.973258 1.17015 ]
 [0.939203 1.09205 ]]
Minkowski:
[[1. 1. 1.]
 [1. 1. 1.]]
Chebyshev:
[[0.03862  0.138062 0.172117]
 [0.1678   0.15997  0.08187 ]]
```

### Scipy/Numpy/Python version information:
```
scipy.__version__  = 1.0.0
numpy.__version__ = 1.14.2
```

Thanks,
Jesse

**Comment by jakevdp** [comment]
The reason it returns incorrect results are because the implemntation doesn't special-case ``p=np.inf``; see the implementation here:

https://github.com/scipy/scipy/blob/5e22b2e447cec5588fb42303a1ae796ab2bf852d/scipy/spatial/src/distance_impl.h#L338-L349

Two possible fixes:

1. Change ``minkowski_distance`` so that it falls back to ``chebyshev_distance_double`` when ``p`` is infinite

2. Raise a ValueError when p is infinite and tell the user to use chebyshev distance instead

**Comment by jakevdp** [comment]
I'm happy to work on either fix... any thoughts on the preferred approach?

**Comment by caja-matematica** [comment]
@jakevdp seems that the first approach would be the least disruptive. I can't think of any reason to raise an error since falling back to `chebyshev_distance_double` provides the user with the desired answer for infinite `p`.
