### ISSUE TITLE
[Feature request] Add canny edge detector to ndimage

### ISSUE THREAD

**Issue by jmetz** [scipy/scipy#8799]
It would be great to see the [Canny edge detector](https://en.wikipedia.org/wiki/Canny_edge_detector) available in `scipy.ndimage`. 

Implementations exist in 

* `cv2` (https://github.com/opencv/opencv/blob/master/modules/imgproc/src/canny.cpp) 
* `scikit-image` (https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/_canny.py)

Perhaps one of these could be ported here?

**Comment by WarrenWeckesser** [comment]
Thanks for the suggestion!  But instead of porting that code to scipy, I recommend that you just use scikit-image.

I don't have any hard-and-fast rules about what functionality should be added to scipy  and what should be left in more specialized projects, but in this case, I don't think we should duplicate the image processing functionality that scikit-image specializes in.  scikit-image is a high quality project under active development.  Duplicating something like the Canny edge detector in scipy is an inefficient use of developer time.

**Comment by rgommers** [comment]
Agreed, closing.
