### ISSUE TITLE
scipy.optimize.linprog(method='simplex') needs to return duals

### ISSUE THREAD

**Issue by j6e** [scipy/scipy#8836]
I have a huge linprog problem of almost 1k variables and restrictions. I can calculate the solution with scipy.optimize.linprog(method='simplex') but I need shadow prices (or opportunity costs / duals) of ~100 inequalities.

I'm able to calculate them by adding 1 to the right side of the inequality and then solving that problem. Then I get the shadow price substracting the objective functions values for both solutions: shadow_price_i = f_max_original - f_max_i. Then repeat 100 times. This method works but it's painfully slow (1h). Note: I could also pose the dual problem and solve it 

It's a shame that scipy does not return duals, so I'm opening a feature request. I'm new contributing to open projects, but I'm a CS graduate and have experience with both python and the simplex method, so I may be able to do so with some guidance.

**Comment by mdhaber** [comment]
@j6e I'd be happy to help with this. The simplex method could use some maintenance, and it sounds like you have the background for it.

BTW I wrote the `interior-point` method but didn't return duals because the solution is, in general, on an optimal face - not necessarily at a vertex. The duals are not useful in this case for shadow prices, right? And  I haven't implemented a crossover routine to find an optimal basis - or implemented the revised simplex method, for that matter - because SciPy's primary sparse linear programming solver, SuperLU, doesn't support rank-one updates and can't easily be hacked to do so (#7700), so it would not be efficient.

We could start by getting your development environment set up. What's your OS?

**Comment by j6e** [comment]
> We could start by getting your development environment set up. What's your OS?

I have w10 at home, but I usually use the ubuntu 14.04 image for python development.

>BTW I wrote the interior-point method but didn't return duals because the solution is, in general, on an optimal face - not necessarily at a vertex. The duals are not useful in this case for shadow prices, right?

I was aware that the IPM did find it's solutions on an optimal plane, but I don't get why the duals are not usefull for shadow prices. I'm by no means an expert in the matter so who knows.

Since you're the writer of the IPM, maybe you want to know that it categorices my problem as infeasible (simplex solves it). I'm tinkering a bit, because I think it's some sort of numerical inestability (simplex got me troubles with this also). I'll open a new issue if I can't work it out.

**Comment by mdhaber** [comment]
My understanding is that at an optimal vertex you have a lot of active inequality constraints, and so then the duals tell you how modifying the constraint would change the optimal objective. On an optimal face, not as many equality constraints are active, so changing constraints doesn't change the objective, and thus the duals aren't as useful. I, too, may be totally wrong.

Are you able to send your problem? I definitely want to know why `interior-point` is failing on your problem.

- Have you confirmed that all the constraints are indeed satisfied by the solution returned by `simplex`? Sometimes the results it gives don't satisfy the constraints (e.g. #8174).
- What is the message given by `interior-point`? Did it say it was infeasible in presolve or did the algorithm run to completion?

**Comment by mdhaber** [comment]
[Here's](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.37.5719&rep=rep1&type=pdf
) some information about sensitivity analysis from interior-point solutions:

But it does not appear to be as simple as when you have a basic optimal solution.

**Comment by j6e** [comment]
> Have you confirmed that all the constraints are indeed satisfied by the solution returned by simplex? Sometimes the results it gives don't satisfy the constraints (e.g. #8174).

It was the case, that instance of the problem was in fact infeasible.

> My understanding is that at an optimal vertex you have a lot of active inequality constraints, and so then the duals tell you how modifying the constraint would change the optimal objective. On an optimal face, not as many equality constraints are active, so changing constraints doesn't change the objective, and thus the duals aren't as useful. I, too, may be totally wrong.

That being true, the equality constraints must hold, and therefore their shadow prices are relevant (In the report you mentioned there is an example of this on page 33). I checked on my own problem, and while this does not prove anything, the extra slack given by IPM in the zero slack inequalities of simplex is in the order of 0.01 (literally a cent in a problem in the range of millions) and their dual prices vary in the range of 0.1. 

I read somewhere that using the solution of IPM as a starting point of simplex makes it converge quickly to an optimal vertex, maybe it's what we are looking for using returning dual values both in IPM/Simplex... (or not). But I can't recall an LP optimizer that did not return duals, didn't matter if it was IPM or simplex.

**Comment by mdhaber** [comment]
@j6e 
> I read somewhere that using the solution of IPM as a starting point of simplex makes it converge quickly to an optimal vertex, maybe it's what we are looking for using returning dual values both in IPM/Simplex... (or not).

There are "crossover" routines for getting from the interior point solution to an optimal vertex, but I didn't implement one because SciPy's primary sparse linear programming solver, SuperLU, doesn't support rank-one updates and can't easily be hacked to do so (#7700), so I couldn't implement it efficiently.

>But I can't recall an LP optimizer that did not return duals, didn't matter if it was IPM or simplex.

And I wanted to return the duals, but I didn't consider it to be a primary objective, so it didn't get done in the original push.  The reason it was not trivial is that before the interior point method sees the problem there is preprocessing (to convert the problem to standard form, eliminate redundant equality constraints, tighten bounds, eliminate fixed variables, etc...) and so the duals calculated by the algorithm need postprocessing to get the duals for the problem as originally posed. I would need help untangling all this. If you think this is something you could help with, I'd definitely be interested in working with you on it!

**Comment by j6e** [comment]
@mdhaber I will be thrilled to help!

**Comment by mdhaber** [comment]
@j6e Great! I think the first thing to do is to familiarize yourself (at a high level) with the code and the algorithm available in [this paper](https://link.springer.com/chapter/10.1007/978-1-4757-3216-0_8).  I tried to align the code as clearly as possible with the equations in the paper, but one notable difference is the use of the variable `z` in the code for what is _s_ in the paper.

What I need help with first is understanding how the most fundamental preprocessing step - converting the problem to standard form - affects the duals we're after. Specifically, you see in the `_get_Abc` function of `_linprog_ip.py`:

```
    Given a linear programming problem of the form:

    minimize:     c^T * x

    subject to:   A_ub * x <= b_ub
                  A_eq * x == b_eq
                  bounds[i][0] < x_i < bounds[i][1]

    return the problem in standard form:
    minimize:     c'^T * x'

    subject to:   A * x' == b
                  0 < x' < oo

    by adding slack variables and making variable substitutions as necessary.
```

At the end of the function `_ip_hsd` we have our final `x_hat` which is the solution to the standard form problem; `_postprocess` uses this `x` to get the solution to the original primary problem. How do we need to postprocess the `y` and `z` from the standard form problem to get the duals for the original problem? (Initially, let's ignore the fact that `_presolve` might have eliminated redundant constraints, etc...)

On a side note, you might also take a look at reference [4] from the MOSEK paper, which is about computing the optimal basis. Note that the LU factorization needs to be updated as the basis changes, but I haven't been able to hack SuperLU to update LU factorizations due to #7700, and I think computing the LU from scratch every time would make the procedure too slow to be worth the time coding.

**Comment by mdhaber** [comment]
Hi @j6e just thought I'd check in and see if you had any questions about the code?

**Comment by mckib2** [comment]
> There are "crossover" routines for getting from the interior point solution to an optimal vertex, but I didn't implement one because SciPy's primary sparse linear programming solver, SuperLU, doesn't support rank-one updates and can't easily be hacked to do so (#7700), so I couldn't implement it efficiently.

Ref #11759 : HiGHS does have a crossover routine
