### ISSUE TITLE
3D sparse matrices

### ISSUE THREAD

**Issue by kdhingra307** [scipy/scipy#8868]
To do faster operations, I required 3d sparse matrices [`this project`](https://phabricator.wikimedia.org/T186742).

I patched an original CSR and COO for 3d indices and found out that batch operations on 3d matrices are twice as faster as compared to reshaped 2d CSR matrices.

With these results, I am thinking to refer 2d matrices and add support for  3d matrices (or more). Is there any possibility of adding it directly to scipy sparse??

Will add some results over large sparse in few hours.

**Comment by ilayn** [comment]
Thank you @kdhingra307 !

Actually we are trying to deprecate `numpy.matrix` class from the repositories and you might like to use the new tools provided by `sparse` library https://github.com/pydata/sparse . So I'm a bit undecided whether updating the matrix format just to rewrite it in the future is worth of your effort. 

Let's wait what others have to say.

**Comment by kdhingra307** [comment]
@ilayn I am thinking of adding another sparse matrices module, that will support n-dimensional indices.

I have used pydata/sparse and few others too. They are pure python, so slow and also support only COO in multi-dimensional.

@ilayn I dnt think sparse matrices (csr/coo) uses numpy.matrix at all.

**Comment by pv** [comment]
The scipy sparse matrices use numpy.matrix for dense matrix
representation, and their semantics is compatible with numpy.matrix but
not with numpy.array. Even though this causes problems for writing code
that can operate on both dense/sparse and blocks using
`__array_ufunc__`, it cannot be changed due to backward compatibility,
and addressing it requires anyway introducing new sparse array classes.

Speed issues with pydata/sparse are something that hopefully will be
solved at some point in future.

**Comment by pv** [comment]
From a meta perspective, it would seem likely that maximal progress is
achieved if everyone works together on a single project.

As said, numpy.matrix issue blocks incremental evolution of
scipy.sparse to the direction you'd like to go --- at minimum you'd
need to introduce new classes csr_array, coo_array, ... to address the
semantics issues. At that point, you can ask whether it would make
sense to focus on an existing project that already tries to do this.

**Comment by perimosocordiae** [comment]
I expect that @hameerabbasi would be happy to get help making the pydata/sparse package faster and more featureful. It's a relatively new project and I'm sure there's a lot of low-hanging performance to be found.

**Comment by ilayn** [comment]
By the way pure Python doesn't mean slow necessarily. Things have to be measured extensively, sometimes not having an translation overhead makes all the difference. I also think you can jump on board with pydata project and make it even faster much . SciPy is trying to become the customer of these data structures rather than owning them.

**Comment by hameerabbasi** [comment]
@kdhingra307 Right now our project is a bit below SciPy's structures in terms of features and performance, but we're trying to improve. We'd really like to have help.

**Comment by stefanv** [comment]
Also see #14822

**Comment by stefanv** [comment]
@kdhingra307 I would be quite curious to hear your thoughts on how easily we can expand the existing scipy.sparse to handle 3D.

**Comment by kdhingra307** [comment]
@stefanv I implemented it for n-d and should be present in the fork. I did it by defining an array for the index.
