### ISSUE TITLE
scipy.minimize does not seem to adhere to constraints

### ISSUE THREAD

**Issue by dannytm** [scipy/scipy#8894]
Hello,
scipy.minimize does not seem to adhere to constraints.
Here is a simple example where the constraint is for preventing a negative argument in the logarithm, but the minimize function does not adhere  :

### Reproducing code example:
    import math
    from scipy.optimize import minimize

    def obj(x,b):
        print "obj x",x
	    return math.log(x-b)

    def constr(x,b):
	    print "constr x",x
	    return x-b

    x=3.1
    b=3
    a=minimize(obj,x,args=(b),constraints={'type': 'ineq', 'fun':constr,'args':[b]})

### the output is:
constr x [ 3.1]
obj x [ 3.1]
constr x [ 3.1]
obj x [ 3.1]
obj x [ 3.10000001]
constr x [ 3.1]
constr x [ 3.10000001]
obj x [ 3.]
Traceback (most recent call last):
  File "scipy_minimize_constraints.py", line 19, in <module>
    a=minimize(obj,x,args=(b),constraints={'type': 'ineq', 'fun':constr,'args':[b]})
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/optimize/_minimize.py", line 495, in minimize
    constraints, callback=callback, **options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/optimize/slsqp.py", line 378, in _minimize_slsqp
    fx = func(x)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "scipy_minimize_constraints.py", line 9, in obj
    return math.log(x-b)
ValueError: math domain error

### Scipy/Numpy/Python version information:
python2.7
Scipy  version 1.0.0

**Comment by pv** [comment]
Correct --- a constraint does not mean that the objective function is
not evaluated in the "forbidden" region, only that the solution is not
allowed to be there.

**Comment by dannytm** [comment]
ok, thanks.
so how would one constrain evaluation in a "forbidden" region?

**Comment by antonior92** [comment]
Method “trust-constr” has an option for that: you can asign “keep_feasible=True”

**Comment by antonior92** [comment]
@dannytm I experienced a few problems with ``keep_feasible=True`` as well.

I will work on this and try to come back to you with a solution.

**Comment by andyfaff** [comment]
The issue in this example is that the inequality constraint is `x >= b`, i.e. more than or equal to, so `x` is allowed to be 3 by the OP constraint system. The 'forbidden region' is `x < 3`. So lets try and set `b` to slightly more than 3:

```
import math
from scipy.optimize import minimize, NonlinearConstraint

def obj(x,b):
    print ("obj x",x)
    return math.log(x - b)

def constr(x):
    print("constr x", x)
    return x

x=3.1
b=3
delta = 1e-12
nlc = NonlinearConstraint(constr, b + 1e-12, np.inf, keep_feasible=True)
a = minimize(obj, x, args=(b), constraints=nlc)
```

The above example works. However, when `delta = 1e-13` the issue arises again. I' m guessing that it's due to something like the following:

```
>>> math.log(1.e-20)
-46.051701859880914
>>> math.log((3.+ 1.e-20) - 3.)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-57-e66e1ee4e129> in <module>
----> 1 math.log((3.+ 1.e-20) - 3.)

ValueError: math domain error
```
i.e. how one does the floating point arithmetic really matters.

In the following example we can also use the bounds to try and keep the solution space feasible:
```
import math
from scipy.optimize import minimize, NonlinearConstraint

def obj(x,b):
    print ("obj x",x)
    return math.log(x - b)

def constr(x):
    print("constr x", x)
    return x

x=3.1
b=3
delta = np.finfo(float).eps
nlc = NonlinearConstraint(constr, b + delta, np.inf, keep_feasible=True)
a = minimize(obj, x, method='SLSQP', bounds=[(3+delta, np.inf)], args=(b), constraints=nlc)
```

This example fails because when `delta = np.finfo(float).eps` (~2.22e-16), but passes for `delta = 3e-16`. This is a consequence of how floating point arithmetic works.

I'm fairly sure this is not an issue of how the code works, rather how the problem is posed, and the inevitable limitations of how floating point arithmetic works.
