### ISSUE TITLE
odeint struggling with stochastic DEs

### ISSUE THREAD

**Issue by DelSquared** [scipy/scipy#8898]
So there is this issue with ```odeint``` in ```scipy.integrate``` where random elements in a DE (I was modelling the Langevin Equation) discourage it from solving it. I am suspecting that this could be triggering some built-in divergence mechanism since the random variable could be making the derivatives spontaneously very large. Is it possible to suppress the divergence prevention in order to allow solving such equations? Attached below I have the solution for my Langevin Equation for a harmonic oscillator with a perturbed frequency. When the perturbation is null, it solves beautifully as it should

![download](https://user-images.githubusercontent.com/37172200/40887276-afb03122-6746-11e8-881a-18c7b5064d6e.png)

This is the output I was aiming for (this one was obtained with a make-shift Euler integration solver that I made, hence the numerical error build-up towards the end)

![download 1](https://user-images.githubusercontent.com/37172200/40887303-1ce911aa-6747-11e8-8671-28ee2b0abebc.png)

(I know the images may be small but they are decently visible if one opens them in a new tab)

I never really posted any issues on repos so hopefully I did this correctly. If anything else is needed I will supply it.

### Reproducing code example:
```
w,g=5,0
#Parameters. It works well for g=0 since it reduces to a simple harmonic oscillator but the error arises when g>0

def R(t): #R is the "random force" term
  return np.random.normal(0,1) 

def LangevinOscillator (x,t): #Defining the ODE z'=i(w+gR(t))z
  z=x[0]+1j*x[1]
  dz=1j*(w+g*R(t))*z
  return np.real(dz),np.imag(dz)

t=np.linspace(0,1000,100000)
X=np.array([10,0]) #Initial conditions

x=odeint(LangevinOscillator,X,t)
```
### Error message:
```
/usr/local/lib/python3.6/site-packages/scipy/integrate/odepack.py:236: ODEintWarning: Excess work done on this call (perhaps wrong Dfun type). Run with full_output = 1 to get quantitative information.
  warnings.warn(warning_msg, ODEintWarning)
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
odeint is an adaptive stepsize algorithm for ODEs, and indeed assumes some properties of the RHS. The RHS you are using is nowhere differentiable, which causes problems. Stochastic differential equations are a different beast from ODEs, already from the point of view of what an accurate solution means, and the algorithm is not designed for them. scipy.integrate does not contain algorithms specifically for SDEs.

You could perhaps tune the stepsize selection parameters to make it produce some results. However, because the algorithm is not designed for SDEs, it's unclear what is the relation between the produced ensemble of solutions, and the exact solution ensemble of the SDE. For the Euler method, properties of the ODE->SDE generalization are known. I don't know what is the literature situation with adaptive stepsize methods for SDEs, though.

**Comment by DelSquared** [comment]
Is there a work-around/another function that I can use or should I look into implementing my own?

**Comment by pv** [comment]
You can look here:
https://pypi.org/search/?q=stochastic+differential+equation&o=&c=Intended+Audience+%3A%3A+Science%2FResearch

**Comment by WarrenWeckesser** [comment]
Pauli's link shows several Python libraries for stochastic differential equations (SDEs).  SciPy does not provide any SDE solvers.  I'm closing this issue, because `odeint` and the other ODE solvers solve a different problem than an SDE; they are simply the wrong tool for this task.
