### ISSUE TITLE
ndimage.gaussian_filter corner discontinuity

### ISSUE THREAD

**Issue by Borda** [scipy/scipy#8913]
I was a bit unexpected behavior using gaussian_filter, especially on image boundaries - corners. I have generated a noisy image with a Gaussian distribution and that I was expecting that using a Gaussian filter with sufficient sigma I get an image with zeros. But I got high positive values in top-left, and bottom-right corner and negative values in top-right and bottom-left corner; and this values go up to 0.5 of initial sigma used for generating.

### Reproducing code example:
```python
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage

np.random.seed(0)
im = np.random.normal(loc=0, scale=0.3, size=(300, 250))
im_blur1 = ndimage.gaussian_filter(im, sigma=50, order=0, mode='nearest')

plt.figure(figsize=(12, 5))
plt.subplot(121), plt.title('image')
plt.imshow(im, plt.cm.gray), plt.colorbar()
plt.subplot(122), plt.title('scipy')
plt.imshow(im_blur1, plt.cm.gray), plt.colorbar()
```

### Output
![image](https://user-images.githubusercontent.com/6035284/41107229-38a6d908-6a72-11e8-9c37-8f9bf557c19a.png)

### Scipy/Numpy/Python version information:
Scipy - 0.18.1
Numpy - 1.12.1
Python - 2.7.13
('Linux', 'knuth', '4.9.0-6-amd64', '#1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07)', 'x86_64')

**Comment by Borda** [comment]
if I use `mode='constant'` it gives the following result:
![image](https://user-images.githubusercontent.com/6035284/41107830-68714154-6a73-11e8-8194-2d4a2a1fbdb5.png)

**Comment by rkern** [comment]
I would certainly expect that first result. When you use `mode='nearest'` with such a large `sigma`, you are implicitly making *a lot* of copies of the corner values beyond the domain of the original image. When the filter is near the corner, it is mostly seeing those copied values from the corner. When the values are all noise instead of signal, you are amplifying the noisy value at the corners.

**Comment by Borda** [comment]
@rkern so to say, you see the results `mode='nearest'` as correct and what about the `mode='constant'` ?

**Comment by rkern** [comment]
They are correct, too.

**Comment by rkern** [comment]
Or rather, I don't think there is a bug in `ndimage.gaussian_filter()`. It's correctly calculating the Gaussian-filtered image accounting for both of those boundary condition modes. Whether `mode='nearest'` or `mode='constant'` or something else is what you want to do depends on the data and the application. In cases where you have lots of noise and not a lot of signal, `mode='nearest'` is going to amplify the noise of the corner pixels and create these artifacts because it implicitly duplicates the corner pixels so they don't get averaged out. Leaving the default `mode='reflect'` is usually a pretty good idea.

**Comment by rgommers** [comment]
question is answered, and doesn't look like a bug, so closing. thanks all
