### ISSUE TITLE
problem with scipy.optimize.linprog method="interior-point"  

### ISSUE THREAD

**Issue by shimodatakaki** [scipy/scipy#8933]
scipy.optimize.linprog(method="interior-point") does not return a correct answer to even such a simple linear programming problem (see below code):

The problem:
    min x1
    s.t.
    -x1 + x2 <= -1
    -x1 - x2 <= 1

The answer should be [x1, x2] = [0, -1] (objective function = 0), but linprog returns [1, 0]  (objective function = 1).

Is this a bug or am I wrong?

### Reproducing code example:
~~~~
from scipy import optimize
import numpy as np

def test():
    """
    min x1
    s.t.
    -x1 + x2 <= -1
    -x1 - x2 <= 1

    the answer should be [x1, x2] = [0, -1] (objective function = 0)
    but linprog returns [1, 0]  (objective function = 1)
    """
    c = np.array([1., 0.])
    G = np.array([[-1., 1.], [-1., -1.]])
    h = np.array([-1., 1.])
    x = optimize.linprog(c, G, h, method="interior-point", options={"disp":True})
    print()
    print(x)


if __name__ == "__main__":
    test()
~~~~

### Error message:
```

Primal Feasibility  Dual Feasibility    Duality Gap         Step             Path Parameter      Objective          
1.0                 1.0                 1.0                 -                1.0                 1.0                 
0.1436504089458     0.1436504089458     0.1436504089458     0.8617354375388  0.1436504089458     1.235137003524      
0.003447933113927   0.003447933113918   0.003447933113918   0.9782408415138  0.003447933113918   1.001317367476      
1.833159874731e-07  1.833159869455e-07  1.833159868903e-07  0.9999468570969  1.833159868998e-07  1.000000044834      
9.165224151999e-12  9.165817802917e-12  9.1657792467e-12    0.9999500000843  9.165799346942e-12  1.000000000002      
Optimization terminated successfully.

     con: array([], dtype=float64)
     fun: 1.0000000000022418
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([ -2.19626539e-11,   2.00000000e+00])
  status: 0
 success: True
       x: array([  1.00000000e+00,   2.42044176e-11])

```

### Scipy/Numpy/Python version information:
```

~~~~
>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.13.3 sys.version_info(major=3, minor=5, micro=5, releaselevel='final', serial=0)
~~~~

```

**Comment by WarrenWeckesser** [comment]
@shimodatakaki Thanks for reporting your problem.  Actually, this is not a bug.  I encountered the same problem when I first used `linprog`, and rereading the docstring gave me the solution.

Unless you change the default by setting the `bounds` argument appropriately, `linprog` assumes that each variable must be nonnegative.  This is explained in the description of the `bounds` argument in the [docstring](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linprog.html).  Also take a look at the example in the docstring.

To remove that constraint from all the variables, use the `bounds` argument to set the bounds of each variable to `(None, None)`.  According to the description of `bounds`,

> If a sequence containing a single tuple is provided, then ``min`` and ``max`` will be applied to all variables in the problem.

so you can use `bounds=[(None, None)]`.  It turns out that the code also accepts the single tuple `bounds=(None, None)` to accomplish the same thing.

Here's the result of your example, with `bounds=(None, None)` added to the call of `linprog`:

```
In [36]: result = optimize.linprog(c, G, h, method="interior-point", options={"disp":True}, bounds=(None, None))
Primal Feasibility  Dual Feasibility    Duality Gap         Step             Path Parameter      Objective          
1.0                 1.0                 1.0                 -                1.0                 0.0                 
0.1256774040076     0.1256774040076     0.1256774040076     0.8815186667413  0.1256774040076     0.2120640564046     
0.0008924919691552  0.0008924919684391  0.0008924919684391  0.9951153633875  0.000892491968591   0.001069500552201   
4.514344220663e-08  4.514343683095e-08  4.514343679294e-08  0.9999494219442  4.514343847025e-08  5.342117892493e-08  
2.671871897561e-12  2.404895677542e-12  2.404851830107e-12  0.9999467270397  2.333078942807e-12  2.915001573456e-12  
Optimization terminated successfully.

In [37]: result.x
Out[37]: array([  2.91500157e-12,  -1.00000000e+00])
```

Now the result is (approximately) [x1, x2] = [0, -1].

**Comment by shimodatakaki** [comment]
Thank you so much!
I didn't know it. I'll reread linprog documents.
