### ISSUE TITLE
improve docs on building docs

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#8966]
There have been a number of questions recently on how to build the docs, it's not documented well enough. E.g. from @adbugger at https://mail.python.org/pipermail/scipy-dev/2018-April/022817.html:

So I finally got the docs built. Couple of points which I think might be helpful to people building docs in the future:

You need to have sphinx installed in your working environment (native installation, virtualenv, conda, whatever). I did not see sphinx listed as a dependency online. Maybe it should be included in the HACKING.rst.txt file?

You do NOT need to have numpydoc installed on your system. Irrespective of where it is installed, the build process only uses the numpydoc package present under the sphinxext directory. I wasted a lot of hours trying to find which version of numpydoc was being used as I had it installed both in my virtualenv, and native installation; neither of those had the faulty import line.
    
After using `git submodule update` to get the latest sphinxext directory and numpydoc installation, the faulty import line in file doc/sphinxext/numpydoc/numpydoc.py needs to be changed. From

        from sphinx.util.compat import Directive

    to

        from docutils.parsers.rst import Directive

Thank you Lars for pointing that out.
    
Finally, and this was my fault entirely, I had my virtual environment running python version 3.5.2, but as python3 or python. Calling python3.5 (as the Makefile was doing when I set PYVER=3.5) called the python executable in /usr/bin/python3.5, which couldn't find the sphinx module itself (as I didn't install it along with my native installation). Setting PYVER=3, or PYTHON=/path/to/python/in/virtualenv fixed this.

**Comment by mdhaber** [comment]
I'd be happy to test updated written instructions and, if they work for me, make a video like the others. I was eventually able to build the docs when I last tried, but they never looked right so I'm not the right person to update the written instructions.

**Comment by adbugger** [comment]
Issue #8794 updated the version of numpydoc used by scipy, so modifying files is no longer required.

**Comment by mdhaber** [comment]
Wrote some instructions for building documentation at:
https://github.com/scipy/scipy/wiki/Rendering-SciPy-Documentation

Is `git submodule update` a necessary step?
Any troubleshooting tips to add?
Does this close the issue?

**Comment by rgommers** [comment]
> Using make html-scipyorg fixed the appearance issues I had with make html. Was that target added to the makefile recently?

No it's been there for a long time.

> Is git submodule update a necessary step?

you have to do `git submodule init` and `git submodule update` at least once after cloning. After that, another `update` may be needed depending on if the submodule changed (not often)

> Is it possible for Sphinx to update documentation rather than building from scratch every time?

It does. Rebuilds are way faster than if you `rm -rf build`

> When this is linked from existing documentation, should we close this issue?

once it's in the built docs I'd say.

**Comment by mdhaber** [comment]
Thanks for those responses.

Not sure why I wasn't getting the big speedup after the initial build before, but I've seen it in recent tests.  After making changes to the `linprog` documentation, it is much faster to rebuild than build for the first time after branching from master (or after deleting the `build` folder).  

Now I'm noticing that when I try to update the `linprog` `method='interior-point'` documentation by changing the docstring of `_linprog_ip` in [`scipy/optimize/linprog_ip.py`](https://github.com/scipy/scipy/blob/master/scipy/optimize/_linprog_ip.py), the rendered documentation doesn't change unless I delete the `build` folder before `make html-scipyorg`. Then, of course, it takes a long time to build the documentation from scratch. 
Thoughts on why this might be happening?

**Comment by rgommers** [comment]
browser caching issue? I usually use `make html` instead of `make html-scipyorg`, but I think they behave the same. you can check by seeing if the html file you're looking at in the browser has changed (check timestamp, or with a text editor for example)

**Comment by mdhaber** [comment]
@rgommers it looks like `git submodule init`/`update` ensures that `scipy-sphinx-theme`, `scipy-mathjax`, and `numpydoc` are up to date? Calling these commands automatically merges (or rebases on?) upstream changes?

I imagine that `numpydoc` is shared and that's why it's a submodule, but why aren't `scipy-sphinx-theme` and `scipy-mathjax` part of the main repository?

RE:  `linprog_ip` docstring not re-rendered unless I delete `build` - it doesn't look like a browser caching issue. The .html files simply don't change. `index.html` updates, but `optimize.linprog-interior-point.html` doesn't.  I tried changing the documentation for  `optimize.minimize-trustexact.html` and `optimize.minimize-cobyla.html`, too - same thing. These optimize method files are different because they appear directly in the `html`/`html-scipyorg` folder rather than in the `generated` subfolder (like `scipy.optimize.linprog.html`, which updates just fine). Could that have something to do with it?

**Comment by rgommers** [comment]
> @rgommers it looks like git submodule init/update ensures that scipy-sphinx-theme, scipy-mathjax, and numpydoc are up to date? 

Indeed

> Calling these commands automatically merges (or rebases on?) upstream changes?

If by upstream you mean the version of those submodules set in the the main SciPy repo, then yes. If you mean "latest numpydoc", then no.

> I imagine that numpydoc is shared and that's why it's a submodule, but why aren't scipy-sphinx-theme and scipy-mathjax part of the main repository?

Also shared. `scipy-sphinx-theme` is used by numpy.org, docs.numpy.org, scipy.org, numpy and scipy (at least). Not 100% sure about scipy-mathjax, but likely in >1 place as well.

**Comment by mdhaber** [comment]
Thanks. Good to check my understanding before spreading lies : )

**Comment by pv** [comment]
Also, because these modules contain files not directly related to scipy source code (for example, the MathJax files) they are better kept separate. How git submodules work is a bit unintuitive at first (tutorial at https://git-scm.com/book/en/v2/Git-Tools-Submodules), but there are good reasons why it works like it does.
