### ISSUE TITLE
Numerically unstable comparison

### ISSUE THREAD

**Issue by Culioo** [scipy/scipy#8996]
https://github.com/scipy/scipy/blob/f179b25f00fbb5d645a2e4595d1d908fb499d84c/scipy/linalg/_solvers.py#L809

Hello,
I stumbled across this line of code during my current work. It would be perfect, if someone could reason to me why the comparison was implemented that way instead of using `numpy.allclose(mat, mat.conj().T)` .

The problem with this implementation is the following. If you got a large matrix with small numbers you obtain an error for every difference calculated, which will sum up depending on the number of matrix entries. But since the `np.spacing(norm(mat, 1))` value is multiplied by a fixed number 100 the comparison does not check the intended condition anymore. Numerically, the following happens

<a href="https://www.codecogs.com/eqnedit.php?latex=X&space;=&space;(x_{ij})_{i,j&space;\in\{1,2,\dots,n\}}\\&space;x_{ij}&space;=&space;x_{ji}&space;\\&space;\lvert\hat{x}_{ij}&space;-&space;\hat{x}_{ji}&space;\rvert&space;\approx&space;\varepsilon\\&space;\lvert\lvert&space;X&space;-&space;X^H&space;\rvert\rvert_1=\sum_{i,j&space;=&space;0}^{n}\lvert{\hat{x}_{ij}-&space;\hat{x}^*_{ji}}\rvert\geq&space;\varepsilon\cdot&space;n&space;>&space;\varepsilon&space;\cdot&space;100&space;\\&space;\hat{x}&space;\text{&space;representation&space;of&space;}&space;x&space;\text{&space;in&space;the&space;computer}\\&space;\varepsilon&space;\text{&space;representing&space;the&space;machine&space;accuracy&space;for&space;the&space;given&space;data&space;type}&space;\\&space;n&space;\text{&space;representing&space;the&space;number&space;of&space;matrix&space;entries}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?X&space;=&space;(x_{ij})_{i,j&space;\in\{1,2,\dots,n\}}\\&space;x_{ij}&space;=&space;x_{ji}&space;\\&space;\lvert\hat{x}_{ij}&space;-&space;\hat{x}_{ji}&space;\rvert&space;\approx&space;\varepsilon\\&space;\lvert\lvert&space;X&space;-&space;X^H&space;\rvert\rvert_1=\sum_{i,j&space;=&space;0}^{n}\lvert{\hat{x}_{ij}-&space;\hat{x}^*_{ji}}\rvert\geq&space;\varepsilon\cdot&space;n&space;>&space;\varepsilon&space;\cdot&space;100&space;\\&space;\hat{x}&space;\text{&space;representation&space;of&space;}&space;x&space;\text{&space;in&space;the&space;computer}\\&space;\varepsilon&space;\text{&space;representing&space;the&space;machine&space;accuracy&space;for&space;the&space;given&space;data&space;type}&space;\\&space;n&space;\text{&space;representing&space;the&space;number&space;of&space;matrix&space;entries}" title="X = (x_{ij})_{i,j \in\{1,2,\dots,n\}}\\ x_{ij} = x_{ji} \\ \lvert\hat{x}_{ij} - \hat{x}_{ji} \rvert \approx \varepsilon\\ \lvert\lvert X - X^H \rvert\rvert_1=\sum_{i,j = 0}^{n}\lvert{\hat{x}_{ij}- \hat{x}^*_{ji}}\rvert\geq \varepsilon\cdot n > \varepsilon \cdot 100 \\ \hat{x} \text{ representation of } x \text{ in the computer}\\ \varepsilon \text{ representing the machine accuracy for the given data type} \\ n \text{ representing the number of matrix entries}" /></a>

Regards,
Alex

**Comment by ilayn** [comment]
The fixed number is meant for *at most two orders of magnitude*. In matlab you would write this condition as `100*eps*norm(A)`. With `np.spacing`  you get an `eps` relative to the norm of the difference matrix. The bound does not depend on the matrix size since this checks for elementwise errors. 

For different problems such eigenvalues etc. you would probably add the matrix size as the error often depends on the matrix size and accumulates but for symmetricity you check all errors made on all entries. This has a direct impact on the solvability conditions hence it is indeed a very strict condition. However very easy to satisfy by symmetrizing the input with `Q + Q.T`.

**Comment by ilayn** [comment]
Since this is not an issue but query I'll close it but we can keep the discussion

**Comment by ilayn** [comment]
I forgot to mention why it is as such. First reason is that being "kind of" the standard method (probably [due to LAPACK](http://www.netlib.org/lapack/lug/node75.html) ) so it is a habit. Second is that pure `np.allclose` might indeed be possible but more difficult to control and maintain than a lumped error (especially when different-order-of-magnitude entries are present).

Again, the main point is that this is an input sanity check and the Hamiltonians/Symplectic matrices are very fragile to have strange results if certain blocks don't satisfy the requirements (eigs on imaginary axis/unit circle).

**Comment by Culioo** [comment]
I totally get your argument, since in C++ and other sensitive programming languages I do handle it exactly this way. 

However, 
> The bound does not depend on the matrix size since this checks for elementwise errors.

is simply not how it is implemented. The 1-norm computes the sum over all elements in the matrix. If you take the componentwise difference and then sum over it, you don't compute the magnitude elementwise in this case and the comparison is highly unstable due to numerical errors and the ill-conditioned artithmetics +,- .

Do you see what I mean? 

Regards,
Alex

**Comment by ilayn** [comment]
I understand the argument but I don't see how this is unstable. Maybe I can point to the paragraph just above the 3x3 matrices A and $\hat{A}$ in the LAPACK link above about the generalization of infinity-norm of vectors to matrices and it is not the max of the absolute value of the entries. 

By the way, there is no ill-conditioned arithmetics in this case about +/- . Can you give a numerical example about this?
