### ISSUE TITLE
scipy.signal.cwt(data, wavelet, widths) has bug or misunderstanding due to documentation

### ISSUE THREAD

**Issue by ZHANGGU** [scipy/scipy#9002]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
widths: array like, I assume it would be the scale vector where different scales 
I tried data, sampling period 0.01, Morlet, data size 3.42 s
widths= numpy.linspace(0.01, 1, 10)

cwtmatr = signal.cwt(data, signal.morlet, widths)

It give error

"ValueError: zero-size array to reduction operaiton maximum which has no identity.

While this function works for widths that is larger than 1 without any problems, some float e.g 0.5, but does not 0.05,

Please investigate!

Thanks!

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by mdhaber** [comment]
@ZHANGGU I think you would be more likely to get a response if you included a complete code example, i.e. something we can copy and paste into a Python console in order to get the error message you're seeing. You should also format your post as indicated in the template, with your code replacing the text:

```<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>```

the _exact_ error message copy-pasted from your console in place of 

```
<<Full error message, if any (starting from line Traceback: ...)>>
```

and the exact version information in place of:

```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by sethtroisi** [comment]
Closing old issue with no follow up and vague details.
