### ISSUE TITLE
SciPy'19 sprint ideas

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#9030]
Hi all, 

This issue is meant to be read by people interested in the SciPy (package) sprint at the SciPy conference.

First things first: SciPy is a library covering very diverse topics, so **do something you're interested in** (say you're into signal processing, then ask one of the core developers or experienced users about what could make sense to tackle in `scipy.signal`).

Before you begin, please review the [developer documentation](http://scipy.github.io/devdocs/#developer-documentation). [Ways to Contribute](http://scipy.github.io/devdocs/hacking.html) gives a good overview of how you can improve SciPy, and the [SciPy Contributor Guide](http://scipy.github.io/devdocs/dev/contributor/contributor_toc.html) contains all the information you need to get started.

Here I'll list some ideas for things to do that are relatively easy to do, so suitable also for anyone who is new to contributing to an open source library.

### Documentation

Documentation is often nice to get started with, if you want to focus on the process of contributing and don't want to worry too much about e.g. setting up for local development on your laptop. A valuable thing to do is to add nice examples to docstrings for functions that don't yet have an example; see gh-7168 for an overview. Another option is to add tutorials (e.g. gh-10358). 

### Finishing up open pull requests

If you're comfortable with Git and want to make an impact by helping to reduce our backlog of open PRs, that would be awesome! [Here ](https://github.com/scipy/scipy/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Aneeds-work+updated%3A%3C%3D2019-01-01+) is a list of PRs that appear to be stalled. *Please comment in the PR to avoid duplicate efforts.*

When you take over an open PR, this is what you will likely want to do:
1. Check out the branch from which the PR was sent (requires adding the repo of the user who sent the PR as a `remote` first; see the latter half of [this](http://scipy.github.io/devdocs/dev/contributor/reviewing_prs.html#reviewing-prs) for commands).
2. Rebase on the current `master` branch (see [here](http://scipy.github.io/devdocs/dev/gitwash/useful_git.html#rebasing-on-master) for commands).
3. Finish up remaining work, addressing open comments, etc.
4. Create a new PR from your branch, linking to the old one (i.e. In a comment, write `supersedes and closes gh-xxxx`).

If you choose to revise the commit history, please preserve original authorship of the code you started from.

### Tackling new issues

There is a "good first issue" label, for issues that can be suitable to get started with if you're new to SciPy development. Click [here](https://github.com/scipy/scipy/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) for a list. *Please comment in the issue to avoid duplicate efforts.*

### Your own idea

If it's an *existing issue*, or performance improvement, or another way of improving something that already is present in SciPy - go for it!

If you are thinking of adding a *new feature*, please discuss it with a core developer first (at least some sanity checking to ensure that it's something that SciPy would in principle like to include).

### For domain experts

If you have expertise in a particular domain (e.g. statistics, numerical optimization, signal processing, ...) then you can make very valuable contributions by reviewing open pull requests in that domain. *You do not have to be familiar with SciPy development to review PRs*. If you can say "I understand this algorithm and it looks like the implementation is correct" or "I've tested this on my data and it works as expected", that's super helpful.

### Discussion channels

- in-person would be great. 
- [Gitter](https://gitter.im/scipy/scipy)
- GitHub works too. 
- @rgommers and @mdhaber are in the room, at least for most of Saturday and Sunday
- the mailing list is the place to propose new features; there's probably a bit slower turnaround, but it could be the appropriate channel.

**Comment by mikofski** [comment]
#8359 is listed twice

Sent from Yahoo Mail on Android 
 
  On Fri, Jul 13, 2018 at 3:59 PM, Ralf Gommers<notifications@github.com> wrote:   
Hi all, this issue is meant to be read by people interested in the SciPy sprint at the SciPy'18 conference (Sat 14 July 2018).

First things first: SciPy is a library covering very diverse topics, so do something you're interested in (say you're into signal processing, then ask one of the core developers or experienced users about what could make sense to tackle in scipy.signal).

Here I'll list some ideas for things to do that are relatively easy to do, so suitable also for anyone who is new to contributing to an open source library.

Documentation

Documentation is often nice to get started with, if you want to focus on the process of contributing and don't want to worry too much about e.g. setting up for local development on your laptop. A valuable thing to do is to add nice examples to docstrings for functions that don't yet have an example. See gh-7168 for an overview.

Finishing up open pull requests

If you're comfortable with Git and want to make an impact by helping to reduce our backlog of open PRs, that would be awesome! Here is a list of stalled PRs that can be completed (please check off when you are starting to work on one:
   
   -  gh-7385
   -  gh-6846
   -  gh-7267
   -  gh-8359
   -  gh-8359

(there are more with the needs-work issue label).

When you take over an open PR, this is what you will likely want to do:
   
   - Check out the branch from which the PR was sent (requires adding the repo of the user who sent the PR as a remote first).
   - Rebase on the current master branch (squashing is okay, but please preserve original authorship).
   - Finish up the PR, addressing open comments, etc.
   - Send a new PR, linking to the old one (e.g. supercedes gh-xxxx).

Tackling new issues

There is a "good first issue" label, for issues that can be suitable to get started with if you're new to SciPy development: https://github.com/scipy/scipy/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Your own idea

If it's an existing issue, or performance improvement, or another way of improving something that already is present in SciPy - go for it!

If you are thinking of adding a new feature, please discuss it with a core developer first (at least some sanity checking to ensure that it's something that SciPy would in principle like to include).

Discussion channels
   
   - in-person would be great.
   - GitHub works too.
   - @rgommers and @tylerjereddy are in the room, at least for most of Saturday
   - the mailing list is the place to propose new features; there's probably a bit slower turnaround, but it could be the appropriate channel.
   -

**Comment by rgommers** [comment]
thanks @mikofski, fixed.

note that the email interface gives massive comments unless you remove the irrelevant parts from your reply. I'll delete you comment and mine

**Comment by mdhaber** [comment]
@rgommers mind if I hijack this issue for the SciPy '19 sprint, or should I close this and start a new one?

**Comment by rgommers** [comment]
please go for it, just modify the description as you see fit

**Comment by andyfaff** [comment]
@mdhaber, probably closeable?

**Comment by mdhaber** [comment]
Sure. This was adapted from the 2018 issue, which was left open, but I think it's fine to close now and reopen next year if desired.
