### ISSUE TITLE
improve user experience: linalg

### ISSUE THREAD

**Issue by oricou** [scipy/scipy#9049]
There are numpy.linalg and scipy.linalg for good reasons (fortran and blas) but as a user including both is a pain. If scipy's version could include all numpy.linalg's function, then I could import scipy.linalg, being sure I don't have to read both manual to know if what I want to do can be done.

To do that, if I am right, there are only 2 functions to include in scipy.linalg:

* numpy.matrix_rank
* numpy.cond

If you do that, you will help a lot a users and [such questions](https://stackoverflow.com/questions/38168016/how-to-know-when-to-use-numpy-linalg-instead-of-scipy-linalg) will not happen anymore. In the same time the documentation could change `scipy.linalg imports most of them` by `all of them`!

**Comment by ilayn** [comment]
That would still have some differences. NumPy version of the functions have slightly different implementations with option of fallback to LAPACK. SciPy always uses the LAPACK and BLAS versions. Hence there will always be some slight differences. 

To be honest, I think, while the confusion is definitely real, it is a manageable one. Since this is not strictly an issue I'll close it but we can keep discussing it further.

**Comment by ilayn** [comment]
Here is the relevant issue #7575 about `matrix_rank` for example

**Comment by oricou** [comment]
ok there a few differences on how to use them but functions with the same name do both the same job. Today when I teach I have to say to my student that they have to import numpy.linalg and scipy.linalg and sometime to look it the first one documentation to see if you can find what you want and sometime you have to go to the second one. It is a mess and a huge wast of time.

Of course it happens for many (all ?) users who want to do linear algebra with Python. How much time wasted in total wondering with version I should use?

So my suggestion is to make it simple:

* you have both Numpy and Scipy installed: use scipy,linalg and nothing is going to miss
* you cannot install Scipy and want to stick to Numpy: use numpy.linalg

I am sure for you it is manageable, but for beginner it is a pain, a useless one from my point of view.

**Comment by ilayn** [comment]
To clarify, the explanation is easy if done correctly. I am continuously puzzled about everything 😃 So I will be the last person to make that generalization. 

History aside, we are trying to make the code duplication less instead of more. You have a pretty good point about unification but occasionally people come and open issues about why we have duplicate function names. "If it is available on numpy let it be available there instead of having another one on SciPy" is another argument.

Hence I understand your argument but we are kind of stuck in the middle with a lot of legacy decisions and unhappy customers. Every step in one direction upsets the people on the other side.

**Comment by oricou** [comment]
I know the explanation is easy but it is still a mess which puzzles users.

I agree with users who don't want duplication and if all could be in numpy.linalg that would perfect for me. But it is not the case and meanwhile all I ask is to add

```
def cond(whatever_should_be_here):
    return numpy.linalg.cond(whatever_should_be_here)
```

and same for `matrix_rank` (no code duplication).

The main failure of Python is having so many libraries doing more or less the same things and you never know which one to use. I would love that Numpy force Blas dependency and include all scipy.linalg but as long it is not done, please make users' life easier.
