### ISSUE TITLE
We're using way too many CircleCI resources

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#9111]
When you log in right now, you'll get a banner message saying:

    Your current usage represents 500% of your scipy Linux plan's limit. 
    Please upgrade in order to ensure no disruption in building.

This needs to be looked into.

**Comment by rgommers** [comment]
Oh, and we need to migrate to the CircleCI 2.0 config. 1.0 will not be supported after 31 Aug 2018.

**Comment by andyfaff** [comment]
Pretty sure we've already migrated to 2.0

>

**Comment by pv** [comment]
The "Hobbyist" free plan is 1500min/month i.e. ~50 jobs, which is not sufficient if we're going to run something for each PR.

**Comment by larsoner** [comment]
I raised this issue with another org that hit this warning, and the time-consuming repo maintainers suggested that they've been running such a deficit for months with no problems (yet):

https://github.com/nipy/nipype/issues/2667

This suggests that it is at least (hopefully) not an urgent issue, but I agree it's better to fix the problem at some point if possible rather than wait until something bad happens.

**Comment by andyfaff** [comment]
Is this still an issue? I've just logged into circleCI and can't see any problems?

**Comment by rgommers** [comment]
They've significantly increased the usage limits for open source projects. So should be all good now, closing. Thanks all
