### ISSUE TITLE
Both fast and very slow scipy.signal.resample with the same input size

### ISSUE THREAD

**Issue by josephernest** [scipy/scipy#9273]
According to the documentation of [`scipy.signal.resample`](https://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.signal.resample.html), the speed should vary according to the length **of input**:

> As noted, resample uses FFT transformations, which can be very slow if the number of input samples is large and prime, see scipy.fftpack.fft.

But I have very different timings (factor x14) **with the same input**, and only a small variation of desired output size:

    import numpy as np, time
    from scipy.signal import resample
    
    x = np.random.rand(262144, 2)
    y = np.random.rand(262144, 2)
    
    t0 = time.time()
    resample(x, 233543, axis=0)
    print time.time() - t0          # 2.9 seconds here
    
    t0 = time.time()
    resample(y, 220435, axis=0)
    print time.time() - t0          # 40.9 seconds here!

Question: I can zero-pad the input to have a power of 2 (to speed up FFT computations, as usual), but as my resampling factor is fixed, **I can't have both a power of 2 for the input size and a power of 2 for the desired output size**.

**How to speed up `scipy.signal.resample`?**

If not possible, and if `scipy.signal.resample`'s performance can vary **so much** with a large factor, it makes it really not handy for real use. Then for which application is it useful? 

Note: my goal is audio resampling (repitching, etc.)

**Comment by larsoner** [comment]
> the speed should vary according to the length of input:

This is incorrect, as you point out, it varies according to the length of the input (FFT speed) and output (IFFT speed). Can you make a PR to fix the do to say "...number of input **or output** samples..."?

> How to speed up scipy.signal.resample?

If you want FFT-based resampling, you have to use faster FFT routines (probably FFTW, you could consider [pyfftw](https://hgomersall.github.io/pyFFTW/pyfftw/interfaces/interfaces.html)).

The other option is to switch resampling methods to something like `resample_poly`, which uses polyphase resampling rather than FFT-based resampling.

**Comment by rgommers** [comment]
done in gh-9279
