### ISSUE TITLE
Easy access to scipy.stat.<distributionName> frozen distribution arguments

### ISSUE THREAD

**Issue by KOLANICH** [scipy/scipy#9321]
It would be useful to easily get access to distribution arguments.

for example

```python

a=scipy.stat.norm(1, 3)
b=scipy.stat.norm(loc=1, scale=2)
c=scipy.stat.norm(1, scale=2)
```

In `a` params go to `args` and in `b` into `kwds`. In `c` `loc` goes to `args` and `scale` to `kwds`. So how am I going to get distributions parameters in a uniform way? For example to get a `name -> value` mapping. I guess you have some internal function for that, could you document and expose it? Or alternatively it may worth to make params available as attrs of a distr:

```python
a.loc
a.scale
```

**Comment by KOLANICH** [comment]
>Duplicating this as named attributes is not desirable IMO.

How about transforming pos arguments into named ones and discarding positional ones?

>All in all, I think it's best taken care of in the user code. E.g. always use loc and scale as keyword arguments.

I am writing a lib accepting scipy distributions already constructed by the lib end users. I guess I can say to end users "you must use only keyword arguments when constructing distributions" but this is undesireable since this may lead to conflicts when one lib relies on all the arguments being positional and another one wants them all be keywords.

>Rely on this on your own risk

Thank you for the info.

**Comment by ev-br** [comment]
> How about transforming pos arguments into named ones and discarding positional ones?

For the frozen distributions, why not. This surgery should take place in `rv_frozen.__init__`, around https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L434
PR welcome.

For the distribution instances themselves, this is not possible since the signatures are `stats.gamma.pdf(1, 4, loc=3, scale=4)` and the actual parameters are not stored anywhere on the distribution instance. So what you're after can only work for the frozen instances, `stats.gamma(4, loc=3, scale=4).pdf(1)`

**Comment by KOLANICH** [comment]
Yes, I assummed frozen distributions under distributions.

**Comment by josef-pkt** [comment]
In general, I don't like keyword shape parameters because those names are distribution specific.

I'm a bit behind working on statsmodels probability plots where I also need to handle arbitrary distribution parameters, In the basic structure I separate out loc and scale and use the rest for the possibly empty shape parameters.

non-backwards compatible changes will break existing code.

**Comment by ev-br** [comment]
It seems unlikely that somebody relies on the value of `stats.norm(1, 2).args` being `(1, 2)`? However, with this part of scipy, you never know...

**Comment by josef-pkt** [comment]
oops, I hadn't realized that shape parameters can be kwds in frozen distribution

```
>>> stats.t(df=10, loc=1, scale=2).kwds
{'loc': 1, 'scale': 2, 'df': 10}
>>> stats.t(df=10, loc=1, scale=2).pdf(4)
0.063722397143545814
```

So, with the current code we cannot rely on much in split between args and kwds (except args need to be before kwds)
One disadvantage of kwd shape parameters is also that we don't know their sequence if we want to convert them to args.

```
>>> stats.f(dfn=2, dfd=10).kwds
{'dfn': 2, 'dfd': 10}
>>> stats.f.shapes
'dfn, dfd'
```

**Comment by ev-br** [comment]
`_parse_args` sorts them and the order is kept in self.shapes
