### ISSUE TITLE
Add Somers' D and Kendall Tau-a/c correlation to scipy.stats

### ISSUE THREAD

**Issue by vkk800** [scipy/scipy#9329]
Kendall rank correlation has three different variations: tau-a, tau-b and tau-c ([see Wikipedia](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient#Accounting_for_ties)). Currently Scipy can only compute Tau-b. Even though that might be a sane default choice, one occasionally encounters the other variants also and it would be nice to be able to compute them using Scipy.

Somers' D (see [Wikipedia](https://en.wikipedia.org/wiki/Somers'_D)) is another (quite widely used) method for measuring ordinal association between random variables that can be easily written in terms of Kendall's Tau-a. Currently Scipy doesn't offer an easy way to compute Somers' D. It should probably be added

The question is also, if Kendall Tau-a/c gets added to Scipy, should it be three separate functions for each of them or a parameter of the current `kendalltau()` function that controls which variant is computed? I'm willing to submit a pull request in the near future implementing all three of the new functions if some executive decision is made about this.

**Comment by josef-pkt** [comment]
I think it is better to add a and c to kendalltau directly instead of separate functions.

**Comment by rgommers** [comment]
Question is answered and the open PR for kendalltau a/c is marked for 1.4.0. Somers'D looks less urgent, but seems useful as well. PR welcome after gh-9361 is merged I'd say.

I'll close this, since no need to keep open (we're doing enhancement request spring cleaning - higher-prio requests can be added to our roadmap, for the rest we don't want many open issues).

**Comment by josef-pkt** [comment]
follow up here because I was looking at related issues for statsmodels (extensions to brunnermunzel and similar)

somers' d for association between binary and continuous variable can be directly computed from the rank version in brunnermunzel and (not fully verified) mannwhitneyu
https://github.com/statsmodels/statsmodels/issues/6960#issuecomment-673840980

**Comment by mdhaber** [comment]
@josef-pkt From your post there, it looks like you're getting a discrepancy between *p*-values?

Not sure if this helps, but there are two ways I've seen software compute *p*-values for these tests: one is under the null hypothesis that the statistic equals zero (e.g. SAS `FREQ`, gh-12653), and the other is under the more restrictive hypothesis of independence (e.g. R, SAS `CORR`). SAS uses one if you use the `FREQ` procedure, and uses the other for `CORR`.

**Comment by josef-pkt** [comment]
Thanks for pointing out 12653, I didn't see that PR, (or didn't pay attention because I didn't know much about somers' d)

I'm not sure what p-values you are referring to. The p-value in the test is based on brunnermunzel which also essentially tests d=0. 
I haven't compared with other p-values yet, e.g. mannwhiteney differs from brunnermunzel, but I didn't try to figure out details yet.
