### ISSUE TITLE
scipy.special.log1p fails with extended precision

### ISSUE THREAD

**Issue by adamjorr** [scipy/scipy#9339]
scipy.special.log1p fails on arrays that use numpy's extended precision types (np.longdouble and np.float128, for example)

### Reproducing code example:
```python
import numpy as np
import scipy.special as sp

foo = np.array([1e-4,1e-9,1e-5,2e-4], dtype = np.longdouble)
np.log1p(foo) ## works, array([9.99950003e-05, 1.00000000e-09, 9.99995000e-06, 1.99980003e-04], dtype=float128)
sp.log1p(foo) ## error
sp.log1p(foo.astype(np.float)) ##works, array([9.99950003e-05, 9.99999999e-10, 9.99995000e-06, 1.99980003e-04])
```
As you can see by the output of regular `float` version, this can change the result for very small numbers.

### Error message:
```
TypeError: ufunc 'log1p' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
### Scipy/Numpy/Python version information:
```
'1.1.0',
'1.14.2',
sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by pvanmulbregt** [comment]
A few notes before getting to your observations:
* `log1p` was not part of the original C standard for `math.h`, but was added as part of C99. 
* `scipy.log1p` is the same as `numpy.log1p`.  I believe that it is only available if the underlying C std library has it. (See `numpy/core/src/npymath/npy_math_internal.h`)
* SciPy's other `log1p` is part of the cephes library exposed through `scipy.special` sub package.  It dispatches to a real-valued implementation in `special/cephes/unity.c`, or a complex-valued Cython implementation in `scipy/special/_cunity.pxd`, which in turn draws on the real-valued version.  `log1p` dispatches on `double`, or `complex double` inputs, but not long double.
* Not all SciPy supported platforms use C99 so SciPy continues to use and support the `cephes` implementation of `log1p`.

The reason that long double inputs are rejected by `scipy.special.log1p` is that the long double type can't be converted safely to a `double` or `complex double`.
The differences in output you observe are due to different algorithms being used by the two implementations, one in the C standard library used by numpy on your platform, and the other in `cephes/unity.c`.

**Comment by adamjorr** [comment]
Thank you for the explanation. This makes sense. I only realized this was happening because I was trying to fit a beta distribution using data of type `long double`, and it threw that error. I didn't realize there was another log1p. (here specifically: https://github.com/scipy/scipy/blob/14142ff70d84a6ce74044a27919c850e893648f7/scipy/stats/_continuous_distns.py#L521) So it's explicitly using the cephes implementation.

I think the ideal behavior for `scipy.stats._continuous_distns` would be to use `scipy.log1p` if available, else use `scipy.special.log1p`. I would help out with a PR, but I don't know the best way to go about safely doing such a thing or how widespread the usage of `special.log1p` is.

It's also not particularly burdensome for a user to unsafely cast their data before fitting a distribution, so not too big of an issue. At the same time, the whole point of `log1p` is to be slightly more accurate for very very small numbers, so forcing a user to do this for data types that are necessary for very very small numbers slightly defeats the purpose of the function.

**Comment by ev-br** [comment]
`sc.log1p` was introduced in 
https://github.com/scipy/scipy/commit/1dd2992037d4bd1e3e55a3a98cad3ae65124eb05 in response to https://github.com/numpy/numpy/issues/4225.
That bug has I think long since been fixed, so it's probably safe just revert to always using np.log1p

**Comment by person142** [comment]
As discussed in https://github.com/scipy/scipy/issues/10109, we aren't interested in adding `np.longdouble` implementations of special functions at this time, so closing.
