### ISSUE TITLE
is there source code of find_peaks?

### ISSUE THREAD

**Issue by ucasiggcas** [scipy/scipy#9370]
Hello,
In python3.6.6，I can't find the source code of find_peaks in scipy,
Maybe U say it is in _peak_finding.py,
But where is _peak_finding_utils?
Because in _peak_finding.py I find 
`from ._peak_finding_utils import (_argmaxima1d, _select_by_peak_distance,
                                  _peak_prominences, _peak_widths)`
I can't open _peak_finding_utils.cp36-win_amd64.pyd,
Who can help me ?
Please !
Help !
THX

**Comment by andyfaff** [comment]
That code is in a Python extension.

**Comment by ucasiggcas** [comment]
> That code is in a Python extension.

What does it mean?
Could U help me, please?

**Comment by andyfaff** [comment]
https://github.com/scipy/scipy/blob/master/scipy/signal/_peak_finding_utils.pyx

**Comment by ucasiggcas** [comment]
> https://github.com/scipy/scipy/blob/master/scipy/signal/_peak_finding_utils.pyx

Thanks.
But when I save it and run it,
Error ups.
`cimport numpy as np
from libc.math cimport ceil`

Invalid Syntax
What's up?
Thanks

**Comment by ucasiggcas** [comment]
When I delete 
`cimport numpy as np 
from libc.math cimport ceil`
It also ups
Invalid Syntax
from
`def _local_maxima_1d(np.float64_t[::1] x not None):`
The function is very important for me，so how can I rewrite it?

**Comment by ilayn** [comment]
The function has a Python interface but it is written in Cython. You need to set your computer up to run Cython code and then copy the relevant parts. You cannot delete randomly the parts that don't work since this is your third time asking about this code, maybe you might want to invest in time learning Cython. 

https://pythonprogramming.net/introduction-and-basics-cython-tutorial/

When you have the environment ready and go through basic tutorials then you can copy the peak finding code. Otherwise we can't help you.
