### ISSUE TITLE
Default value for "mode" in "ndimage.shift"

### ISSUE THREAD

**Issue by lbellomo** [scipy/scipy#9383]
In scipy.ndimage.shift the mode's default value is 'constant', but [in the documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.shift.html#scipy.ndimage.shift) it says Default is 'reflect'.
Which of the two is wrong?

**Comment by ilayn** [comment]
The documentation of the ndimage funcs come from 

https://github.com/scipy/scipy/blob/14142ff70d84a6ce74044a27919c850e893648f7/scipy/ndimage/_ni_docstrings.py#L34-L56

if they are marked with the decorator .  

Here it seems like this is an outlier since the docstring shows `constant` which is the value that is passed by default.

**Comment by ilayn** [comment]
Xref #8528

**Comment by lbellomo** [comment]
Ok, i fix that in this PR: #9387

Thanks for the help @ilayn !
