### ISSUE TITLE
Kolmogorov Smirnov 2 samples returning max distance location [Enhancement]

### ISSUE THREAD

**Issue by iosonofabio** [scipy/scipy#9389]
2 sample Kolmogorov Smirnov test (KS test) is about finding the maximal vertical distance between two empirical cumulative distributions; a large max distance is unlikely under the null assumption that the two empirical distributions are sampled from the same theoretical curve. This is implemented in `scipy.stats.ks_twosamp`.

The function calculates but does not return the location of the cumulative at which the max distance happens, but that would be extremely useful for a number of machine learning algorithms, e.g. to get an initial guess for a classifier between the two kinds of data.

I propose to add an optional argument to the function to return the location of the max distance between the distributions in terms of indices of the data and also value of the quantitative variable.

### Reproducing code example:

Here a rough initial implementation for example purposes. The final few lines are the only ones that differ from the current implementation.
```python
def max_distance_cumulative(data1, data2):
    """
    Computes the maximal vertical distance between cumulative distributions
    (this is the statistic for KS tests). Code mostly copied from
    scipy.stats.ks_twosamp

    Parameters
    ----------
    data1 : array_like
        First data set
    data2 : array_like
        Second data set
    Returns
    -------
    d : float
        Max distance, i.e. value of the Kolmogorov Smirnov test. Sign is + if
        the cumulative of data1 < the one of data2 at that location, else -.
    x : float
        Value of x where maximal distance d is reached.
    """
    from numpy import ma

    (data1, data2) = (ma.asarray(data1), ma.asarray(data2))
    (n1, n2) = (data1.count(), data2.count())
    mix = ma.concatenate((data1.compressed(), data2.compressed()))
    mixsort = mix.argsort(kind='mergesort')
    csum = np.where(mixsort < n1, 1./n1, -1./n2).cumsum()

    # Check for ties
    if len(np.unique(mix)) < (n1+n2):
        ind = np.r_[np.diff(mix[mixsort]).nonzero()[0], -1]
        csum = csum[ind]
        mixsort = mixsort[ind]

    csumabs = ma.abs(csum)
    i = csumabs.argmax()

    d = csum[i]
    # mixsort[i] contains the index of mix with the max distance
    x = mix[mixsort[i]]

    return (d, x)

```

I'm happy to make a PR if there is interest for this.

**Comment by akahard2dj** [comment]
I thought this idea a good to analysis for a geometry relation between two samples.
p-value is just showing a same or not same.
Should I take this issue? 
If you do not mind, I will take it.

**Comment by akahard2dj** [comment]
I thought this suggestion is very useful to know where the gap is maximum distance.
If this idea put in `scipy.stats.mstats.ks_twosamp()`, return variable will increased by 3(ks value, p-value, index at maxima).

If you do not mind, I would like to take this issue.

**Comment by akahard2dj** [comment]
I thought this suggestion is very useful to know the index at maxima.
If this idea put it in `scipy.stats.mstats.ks_twosamp()`, the return variable will be increased by 3(ks value, p-value, index at maxima).

If you do not mind, I would like to take this issue.

**Comment by akahard2dj** [comment]
I thought this suggestion is very useful to know the index at maxima.
If this idea put it in `scipy.stats.mstats.ks_twosamp()`, the return variable will be increased by 3(ks value, p-value, index at maxima).

If you do not mind, I would like to take this issue.

**Comment by akahard2dj** [comment]
I thought this suggestion is very useful to know the index at maxima.
If this idea put it in `scipy.stats.mstats.ks_twosamp()`, the return variable will be increased by 3(ks value, p-value, index at maxima).

If you do not mind, I would like to take this issue.

**Comment by chrisb83** [comment]
While I see the point that this information can be helpful in certain cases, I would not add it:

- it does not belong to the KS-test, i.e. most users don't need this Information when running the test
- the location is often not unique
- it is neither hard nor expensive to get all the locations (in the end, it is just argmax of cdf1 - cdf2) outside of the KS-test

**Comment by iosonofabio** [comment]
Thank you Chris for your comment that revived the issue. While I respect your point of view, I don't think those points invalidate the issue:

 - it does belong to the test just like the statistics and p value, this location is used to calculate the test statistics directly. Moreover, although many users won't need it, there are certainly specific applications such as model building that are quite major

- non uniqueness is ok, we can report one just like argmax does

 - it is expensive in terms of expertise and boilerplate, since one has to take the scipy function, figure out what's going on (docs are not great there I'm afraid), and back engineer it. I've got a master in physics and a PhD in bioinformatics and it took me decent effort to retrace the steps, I don't think this is a trivial issue.

In my opinion this issue is a typical case where we could just expand the usefulness of the codebase with minimal effort. These situations are all too rare and we should just grab the opportunity when we can.

**Comment by chrisb83** [comment]
There is also the problem of backwards-compatability if a new element is added.

This is the code in `ks_2samp` to get the distance between the cdfs:
```
data1 = np.sort(data1)
data2 = np.sort(data2)
n1 = data1.shape[0]
n2 = data2.shape[0]
data_all = np.concatenate([data1, data2])
cdf1 = np.searchsorted(data1, data_all, side='right') / n1
cdf2 = np.searchsorted(data2, data_all, side='right') / n2
d = np.max(np.absolute(cdf1 - cdf2))
```

Let's see if there are further comments from other developers

**Comment by pvanmulbregt** [comment]
gh-9753 changes lots of the 2-sample KS code, but only the last line in @chrisb83's snippet above is different.  Even so that PR could compute the argmin, argmax (for D+, D-) without much extra effort.

What would this mean in the 1-sample case? [Context: I've been thinking about extending `kstest` to cover `ks_2samp`, so that one could just call `kstest(data0, data1,...)` where`data0`, `data1` can be one of `(rvs0, cdf), (cdf0, cdf), (rvs0, rvs1)`. It already supports the first two.]

**Comment by HomaiRS** [comment]
@iosonofabio Thanks for your code. It is exactly what I was looking for. However, I have a question about the code. I am feeding two CDF as numpy to the code, but I keep getting an error of " 'numpy.ndarray' object has no attribute 'count'". I have tried data1['Values'].count() as well. However, I still give the same error. I wonder if you or anyone else who had the same issue can guide me on how to get rid of this error.


Thank you so much.

**Comment by caglorithm** [comment]
This issue has been quiet for a while but I was exactly looking for this kind of functionality in `ks_2samp`. I am a modeller and knowing the location of the maximum is important in the context of my work (as @iosonofabio also suggested above). I will use the code above and would certainly appreciate this PR.

**Comment by iosonofabio** [comment]
I'm still happy to make a PR for this if there is hope. And since we are on the topic, it would seem reasonable to add and option to `ks_2samp` that returns the KS statistic with a sign instead of the absolute value. Would be SO USEFUL in many occasions.

**Comment by chrisb83** [comment]
given that there is interest in this functionality: instead of changing ks_2samp, what about adding a new function, e.g. ks_dist that returns the distance and the location?

**Comment by iosonofabio** [comment]
Sure, I could do that, in fact I have the function already...

**Comment by mdhaber** [comment]
With the introduction `make_tuple_bunch`, I don't think there are backward compatibility concerns. (I haven't thought about whether this is a good idea or not; just thought I'd mention it.)

**Comment by iosonofabio** [comment]
Thanks... Meanwhile I had a baby and probably not so much time for this anymore, would be nice if someone picked it up though

**Comment by mdhaber** [comment]
It's really better if someone else submits the PR because then I can review and merge.
After reading more carefully, @chrisb83's suggestion about making it a separate function makes more sense to me. There have been a lot of requests for statistical "distances" (in the loose sense, perhaps not metrics), and I count +4 supporters above (@iosonofabio, @caglorithm @HomaiRS @akahard2dj) for this, so maybe adding it would set things rolling for adding other distances (e.g. gh-7089).

A few suggestions to the contributor who wants to pursue this:
* Consider whether this should (also?) go in `special` as one of these [raw statistical functions](https://docs.scipy.org/doc/scipy/reference/special.html#raw-statistical-functions).
* We try to name things "distance" only if it satisfies the axioms of a metric, so think about the name. I haven't assessed whether this is a metric. (What is this called in other software?)
* Before starting, propose the idea on the [mailing list](https://mail.python.org/mailman3/lists/scipy-dev.python.org/), including the name(s) you like, and explaining why this is needed and why it is a "fundamental" thing within SciPy's scope. References to similar functionality in other software is a good idea. Invite people to this issue to discuss.
* If response to the email is positive, start on code. 
* To the extent possible, follow the example of [similar functions](https://docs.scipy.org/doc/scipy/reference/stats.html#statistical-distances).
* If it makes sense to share the code that calculates the KS-statistic between the two functions, please do so.
* Implement an `axis` argument manually only if you can actually vectorize the code. Return a NaN if something about the input is invalid (e.g. zero-length). Don't worry about `nan_policy`, etc. This is a reduction operation, so you can use a [decorator ](https://github.com/scipy/scipy/issues/14651) to add some of these bells and whistles.

**Comment by iosonofabio** [comment]
... sounds like this will never see the light of day with this kind of entry barrier, but I'll keep fingers crossed they prove me wrong. It would be a pity, since it's literally two lines of code. Good luck!

**Comment by mdhaber** [comment]
My comment is only my opinion about a possible path forward. This issue stalled a while ago, so I'm only trying to help, not add barriers. If someone wants to try to submit a two-line PR to get this into the existing function, that's another possibility.

**Comment by mdhaber** [comment]
@tirthasheshpatel thanks for your help making wilcoxon` return the z-statistic. Do you think we should add this information to the return of the KS test or have a separate function?

**Comment by tirthasheshpatel** [comment]
> Do you think we should add this information to the return of the KS test or have a separate function?

I also think a separate distance function would be nice (since we have some already and this would fit in).
