### ISSUE TITLE
filtfilt: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated

### ISSUE THREAD

**Issue by jps-aldridge** [scipy/scipy#9393]
scipy.signal.filtfilt produces a FutureWarning message

```
import sys
import numpy as np
import scipy.signal

print(sys.version)
print(np.__version__)
print(scipy.__version__)

data = np.random.uniform(0, 1, 100)
b, a = scipy.signal.iirfilter(N=2, Wn=0.02, btype='highpass', ftype='butter')
data = scipy.signal.filtfilt(b, a, data)
```
produces the output
```
3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
1.15.2
1.1.0
C:\Users\John\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\signal\_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]
```

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.2 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by larsoner** [comment]
This should already be fixed in `master`, feel free to reopen if you check and find that it's not.

**Comment by ilayn** [comment]
Thanks for reporting. Indeed this has been fixed in #8944 already.

**Comment by XiaoChaoPeiQi** [comment]
When I run the following code in a jupyter notebook, I get the following error:
signal_Filter = signal.filtfilt( b,a,data)
c:\users\chao\appdata\local\programs\python\python36\lib\site-packages\scipy\signal\_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]
What should I do?

**Comment by rgommers** [comment]
@XiaoChaoPeiQi are you using SciPy 1.2.0? If not, then that's why you see the warning. You can upgrade to get rid of it, or you can ignore it (it will not cause any issues, it's just a warning for now).
