### ISSUE TITLE
running setup.py bdist_wheel for scipy takes forever

### ISSUE THREAD

**Issue by goyo39** [scipy/scipy#9434]
My issue is about  the install proces at raspberry pi 3b it got stucked(for 4 hours until now and it continue i dont know if i should turn down mi raspberry  ) when "building wheels for collected packages: scipy"

### Reproducing code example:

```
$ sudo pip install scipy
```

### Error message:

```
building wheels for collected packages: scipy
Running setup.py bdist_wheel for scipy (it is stucked here for more than 4 hours and i cant use mi mouse neither my keyboard)
  ...
```

**Comment by raymiec** [comment]
I was installing this fine on p3 all through the summer, it would take around 2 hours to compile and install, although i've been following exact same steps the last few days and it just never seems to end, definitely seems like there might be an issue installing with the latest updates / packages etc.

**Comment by goyo39** [comment]
hey raymiec thanks for the answer.
i solved it by just taking out the "sudo" from my coman line, of coarse after i installed imutils

$ pip install scipy

**Comment by goyo39** [comment]
imutils first and then scipy

**Comment by raymiec** [comment]
Nice one, unfortunately not such an easy fix for me, although i'm going to check all relevant permissions.  I actually think pip2 /pip3 is messing about during install. I.e finding 3.6 and reverting to 2.7 during some parts of the install.

**Comment by raymiec** [comment]
Made Progress, if anyone else finds themselves here with the same issue, couple of steps,  make sure you have all the requirements installed. I was also missing gfortran that i had to install, although with a normal install it would just hang for hours because of this and not report back.

I also switched to a usb3 pen drive to run raspbian stretch from, I have also temporary changed the swapfile size to 2048 up from 100 mb.

I added a fan, just to keep the temp down.

I don't know if the swapfile and usb drive has actually made the difference but if you are struggling this is something you should try.

My money was on gfortran.

One other thing, when installing use a verbose flag i.e pip -vv    this will actually show you whats going on and you're able to tell throughout the build if the pi is actually doing something. I would never have got further if i hadn't.

It took like 30mins at most.

**Comment by rgommers** [comment]
looks like this issue is solved, so closing. thanks all

**Comment by GP-jazan** [comment]
Same issue i had raspberry pi 3
