### ISSUE TITLE
basinhopping() vs anneal()

### ISSUE THREAD

**Issue by drmcnelson** [scipy/scipy#9484]
My issue is about ...
basinhopping() and deprecation of anneal()

The present routine is described as doing a refinement at each step.   This imposes a number of assumptions about the minima, and the cost of the refinement versus the hop.  For a general case annealer, there needs to be a way to do the annealing without the refinement.

**Comment by rgommers** [comment]
In the soon to be released 1.2.0, we have two new global optimizers with better performance, `shgo` and `dual_annealing`. Have a look at those: http://scipy.github.io/devdocs/optimize.html#global-optimization

**Comment by rgommers** [comment]
If someone contributes such a function and it has good performance, then it's of course welcome. We removed the old `anneal` because its performance was terrible. 

> But that doesn't mean it is the best for all problems.

This is not really a problem description by the way:) If there's a class of problems where a basic simulated annealing would do better than one of the existing global optimizers, then that would be good to know about and we can add them to our benchmark suite.

**Comment by drmcnelson** [comment]
Fair enough, if I have some spare cycles, I'll see what I can do to 
contribute.
