### ISSUE TITLE
t-test in scipy.stats: combine tests?

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#9485]
There are four different t-tests in scipy:

- `ttest_1samp` - Calculate the T-test for the mean of ONE group of scores.
- `ttest_ind` - Calculate the T-test for the means of two independent samples of scores.
- `ttest_rel` - Calculate the T-test on TWO RELATED samples of scores, a and b.
- `ttest_ind_from_stats` - T-test for means of two independent samples from descriptive statistics.

In R, the first three cases are combined (second sample is optional, whether samples are related is determined by keyword `paired`):

`t.test(x, y = NULL, alternative = c("two.sided", "less", "greater"), mu = 0, paired = FALSE, var.equal = FALSE, conf.level = 0.95, ...)`
 
(https://stat.ethz.ch/R-manual/R-devel/library/stats/html/t.test.html)

I think it would be nice to have a single t-test function in scipy as well for the first three cases that then calls the relevant version of the current tests and replaces them after some time.

Any views on that?

**Comment by ilayn** [comment]
I think an encompassing frontend can serve well here. Since the names are already a bit cryptic, forwarding the users to a common place should be easier than taming the signatures and dealing with backwards compatibility issues, should we decide to combine them. After a few releases we can reconsider these functions fate depending on the success of the frontend. By then people would probably adopted the new frontend.

Having said all that, stats residents would know better 😃

**Comment by rlucas7** [comment]
I don’t know if I’m qualified as a stats resident or not but I agree.

Sincerely, 

-Lucas Roberts

**Comment by rgommers** [comment]
Somewhat related: https://mail.python.org/pipermail/scipy-user/2012-October/033441.html

I believe we discussed combining t-tests somewhere else before as well, but can't find it right now.

Combining makes sense in principle I think. The name `stats.ttest` is still available.

**Comment by rlucas7** [comment]
@josef-pkt 👍  excellent points I hadn't considered, especially the naming convention.

>Another thought about organizing tests
>Hypothesis tests named after the test distribution are focusing on the wrong distinction, and are >mainly useful for name recognition or as helper function.

>e.g. z-test and t-test are the same thing and just use a different distributional assumption, but are >equivalent in large samples.

RE: `compare_location` => this could be a more general method that handles both. In that case for consistency, we'd want to have higher level interface functions for ANOVA too (a function to call the parametric or non-parametric versions). Perhaps that one should be called `compare_2_or_more_locations`  which could even call the t-tests if only 2 are given. 
If this is done, should we strive for consistency in this convention across testing functions? If so, is   a plan or recommendation on which things to merge together, naming convention guidelines, etc. warranted?

**Comment by josef-pkt** [comment]
Consistency is important because it requires less reading of the documentation for individual cases.
The other issue is that some function names are "famous", i.e. what the users would be searching for. In other cases the name is uninformative except for experts, e.g. I never remember what `mood` does exactly and  how it differs from levene and bartlett.
e.g. https://github.com/statsmodels/statsmodels/issues/5337

I think it would be useful to go through the existing functions and see whether and how easily they can be merged along the lines of handling similar use cases like comparing means or comparing variances in 2 or k samples. And also to see whether the options can be combined in good informative keyword arguments.

Again what I'm planning for and working on (on and off) in statsmodels are functions for specific use cases and then try to get as many options and properties as possible.
Besides mean/location and scale/variance/dispersion for a continuous variables, there are 1 and 2 sample versions for proportions (in [0, 1]), rates like poisson rates (in [0, inf]), correlation and association, and then multivariate analogues.
e.g. in many hypothesis test for these different cases there will be one or several z-test versions that use an asymptotic normal distribution.
(I moved a bit away from creating big classes that include everything because I often up that using the simpler functions in statsmodels or scipy.stats myself for quick use cases.)

**Comment by chrisb83** [comment]
> Hypothesis tests named after the test distribution are focusing on the wrong distinction, and are mainly useful for name recognition or as helper function.

True, but combining the tests by topic like location tests has several drawbacks:

- many different options / parameters (as you state for some Tests in R packages)
- documentation will become very long and hard to read if one needs to distinguish many cases

I do think it would make sense to have more guidance for the user by grouping tests by topic in the documentation: link tests via "See also" and also on the overview page https://docs.scipy.org/doc/scipy-1.1.0/reference/stats.html
(In 1.2.0, the functions will already be grouped in a better way, there was a related PR.)

**Comment by mdhaber** [comment]
I think I agree with @josef-pkt here. The use cases of the various t-tests, KS tests, etc. are quite different, and I agree that it is preferable to combine functions that do similar things and have similar interfaces rather than those that share history, choice of statistic, or null distribution.

`goodness_of_fit` unified `ks_test`, `anderson`, and `cramervonmises` (and could work with essentially any other general distribution comparison statistic), but that was driven mostly out of a need to upgrade `anderson`; adding the other statistics took just a few extra lines of code. That said, I (personally) wouldn't push for a big effort to unify existing functions grouped by use case (like `root` or `minimize`) *right now*. There is a lot going on that is also valuable, and I think our attention is already spread a bit thin. I think we'll run into @chrisb83's concerns (and others) regardless of how functions are combined, and resolving them will require a fair amount of dedicated thought/work.

**Comment by josef-pkt** [comment]
To follow-up

I added many statistical functions to statsmodels since the original comments here.

My pattern now is to 

- never mix sampling cases, eg. separate 1-sample, 2-sample and k-sample functions, separate for continuous mean, proportions, rates, variance, ...
- do not mix hypothesis (except for alternative), I have equivalence tests separate from standard hypothesis test 
- combine available methods for one test type in one function, (1)
- for now I keep nonparametric, eg. rank based, tests separate from parametric tests (also because they don't match a specific response type)
- I'm not yet adding confidence interval to the hypothesis test functions. (I'm still undecided on how to combine those)
- I have other function like confidence intervals, power and sample size functions separate from hypothesis test function.

(1) my oneway anova for continuous response combines methods variance assumptions (standard, Welsh, BF) and trimming (Yuen) with all combinations between the two method types.
https://www.statsmodels.org/dev/generated/statsmodels.stats.oneway.anova_oneway.html

The last one I added to work more on this pattern are tests and other statistics for poisson rates
https://www.statsmodels.org/dev/stats.html#rates
The 2-sample tests also combine test for different comparisons, rate difference, rate ratio, in proportion also odds ratio.
(I have not yet refactored the proportion test to follow this pattern. Those are still disorganized as in other packages, R, SAS)

related: trying to organize what's available in statsmodels
https://github.com/statsmodels/statsmodels/issues/8331

**Comment by chrisb83** [comment]
> The use cases of the various t-tests, KS tests, etc. are quite different, and I agree that it is preferable to combine functions that do similar things and have similar interfaces rather than those that share history, choice of statistic, or null distribution.

I agree. I was used to the R approach to combine tests. I would say we can close this issue when #17767 is merged: by ordering the tests by topic, there is even less need for a combined test.
