### ISSUE TITLE
BUG: scipy.optimize.newton says the root of x^2+1 is zero.

### ISSUE THREAD

**Issue by NAThompson** [scipy/scipy#9551]
Scipy version 1.1.0, Python 3.6.3

```python
>>> def f(x):
...     return x*x+1
...
>>> def f_p(x):
...     return 2*x
>>> newton(f, 1, f_p)
../../scipy/optimize/zeros.py:169: RuntimeWarning: derivative was zero.
  warnings.warn(msg, RuntimeWarning)
0.0
```

See related discussion on [scicomp.stackexchange](https://scicomp.stackexchange.com/questions/30597/defining-a-condition-number-and-termination-criteria-for-newtons-method).

**Comment by mrkalling** [comment]
It will work if you use the appropriate  data type. Try newton(f,10 +10j). It will give an answer (1.0782266972886038e-22+1j) which is correct.

**Comment by NAThompson** [comment]
@mrkalling : The point is that if you don't know if a real root exists or not, then you'd like to pass some function in with a real data, and you'd like the error message to be "can't find root" or "root does not exist", not the wrong answer.

**Comment by WarrenWeckesser** [comment]
`newton` should raise an exception in this case.

**Comment by andyfaff** [comment]
So the desired change is that a final check should be done in a root solver (newton) by inserting the final value into the function and check it returns 0?

**Comment by andyfaff** [comment]
Starting to browse into this. It looks like @mrkalling suggestion [won't work](https://github.com/scipy/scipy/blob/master/scipy/optimize/zeros.py#L359) if you want to look at vectorized root finder with complex roots, but it will work with a single complex root. @mikofski, did you look at implementing `_array_newton` with complex roots?
I'm looking at a final check of the roots to see that they're actually roots, and there looks to be a lot of branches to take care of in `optimize.newton`.

**Comment by WarrenWeckesser** [comment]
If `newton` hits a point where the derivative is zero and therefore the algorithm can't continue, it should not trigger a warning and return its current position.  It should raise an exception--the algorithm failed.

I suppose that before raising the exception, it could first check to see if it got lucky and it just happened to be at a point that meets the conditions for a root.  If so, return the root--no warning necessary.  I was going to say "But how likely is that to happen, really?", but then I tried the following example, where there is a root with multiplicity 2 at x=1:

	In [103]: def f(x):
	     ...:     return (x-1)**2
	     ...: 

	In [104]: def f_p(x):
	     ...:     return 2*(x-1)
	     ...: 

	In [105]: newton(f, 0, f_p, tol=1e-20, maxiter=1000)
	/Users/warren/miniconda36b/lib/python3.6/site-packages/scipy/optimize/zeros.py:169: RuntimeWarning: derivative was zero.
	  warnings.warn(msg, RuntimeWarning)
	Out[105]: 1.0

In that case, the returned value is correct.  And I would say, therefore, that the warning is spurious and should not have been generated.  (What I *expected* to happen here is that the algorithm would just converge slowly to the root.  I didn't expect to so easily find an example where the algorithm lands directly on the multiple root.)

So yeah, before giving up and raising an exception when a zero derivative is encountered, check the current point.  If it meets the convergence criteria, return it (and don't generate a warning).  Otherwise, raise an exception.

Does that sound reasonable?

**Comment by NAThompson** [comment]
@WarrenWeckesser : Zero derivatives technically are fatal to Newton's method, but really nobody cares about Newton's method, they want a root. So generally algorithms will degrade to bisection when a zero derivative is encountered rather than throwing an exception. This tends to work well in practice.

**Comment by NAThompson** [comment]
> So the desired change is that a final check should be done in a root solver (newton) by inserting the final value into the function and check it returns 0?

In fact I thought this was a reasonable behavior, but take a look [here](https://math.stackexchange.com/questions/3017766/constructing-newton-iteration-converging-to-non-root). The only way to get to a convergent Newton sequence to a non-root is to have a discontinuous derivative. Ok, so do you want to support that or not? If not, then the current *idea* for the termination condition is correct (successive approximations are clustered together). But the problem is that the implementation is broken when a zero derivative is encountered.

**Comment by mikofski** [comment]
Has anyone checked this in SciPy-1.2 yet?

**Comment by WarrenWeckesser** [comment]
@mikofski: Arghhh... I thought I was using a build from the master branch, but I ended up running the above examples in 1.1.0.  When I rerun @NAThompson's example (f(x) = x**2 + 1) using a newly built version `'1.3.0.dev0+ae43f9d'`, I still get the warning with the incorrect return value of 0.  My later example, with `f(x) = (x - 1)**2`, returns 1.0 with no warning (hooray!).

@NAThompson, what you wrote above sounds like a useful enhancement.  My suggestion is for dealing with the immediate problem in a simple way to avoid returning an incorrect root.  Your suggestion and mine are not mutually exclusive--we can make an immediate fix that raises an exception, and then someone can work on enhancing the root-finding code to be more robust. Of course, if someone is going to work on the enhancement right away and try to get it into the next release, then we can skip my suggestion and go straight to the more robust enhancement.  Either way, for your specific example, the code should eventually detect that it is failing to find a real root and raise an exception.

**Comment by mikofski** [comment]
>you'd like the error message to be "can't find root" or "root does not exist", - @NAThompsom

>newton should raise an exception in this case. - @WarrenWeckesser

As of SciPy 1.2, please provide arg `disp=True` to raise an exception instead of warning. See [docs](../blob/ae43f9d033b32096c703eb6a00136f8c63b3ecc0/scipy/optimize/zeros.py#L143)
>If True, raise a RuntimeError if the algorithm didn't converge,

>did you look at implementing _array_newton with complex roots? - @andyfaff 

Yes, complex roots work with `_array_newton`, there is already a [test](../blob/master/scipy/optimize/tests/test_zeros.py#L482), it's for Halley's, which is the same as Newton but with the addition of the 2nd derivative

>before raising the exception, it could first check to see if it got lucky and it just happened to be at a point that meets the conditions for a root. If so, return the root--no warning necessary. - @WarrenWeckesser

This was implemented already in #8907

>nobody cares about Newton's method, they want a root. So generally algorithms will degrade to bisection - @NAThompson

This is nearly what `brentq` does already. The [documents](https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html#scalar-functions) state that Brent is recommended over Newton
>In general `brentq` is the best choice

and since #8890 if the universal scalar root dispatcher is used with a bracket and no derivatives, Brent is used by default

In my opinion this issue can be closed because it's already covered by `disp=True` but maybe @pvanmulbregt should weigh in

**Comment by mikofski** [comment]
@WarrenWeckesser thanks! Can you please try again with the keyword argument `disp=True` ? Thanks again ☺️

**Comment by WarrenWeckesser** [comment]
@mikofski: `disp=True` is the default; see https://github.com/scipy/scipy/blob/1a3aa92504020b13236b249a6dca44287b332af9/scipy/optimize/zeros.py#L89

As currently implemented (`scipy.__version__` is `'1.3.0.dev0+ae43f9d'`), the `disp` argument doesn't affect the behavior when a zero derivative is encountered. With @NAThompson's example, I get the warning and an incorrect result whether `disp` is True or False.

**Comment by mikofski** [comment]
That's a bug I guess. I have a PR ready, checking tests now locally
