### ISSUE TITLE
MAINT: 2019 redefinition of SI base units

### ISSUE THREAD

**Issue by jakobjakobson13** [scipy/scipy#9590]
Dear developers,

the new definition of the fundamental SI units will come into force on 20 May by the BIPM ( [BIPM, revised SI units](https://www.bipm.org/en/measurement-units/rev-si/) and [Metrologia, The CODATA 2017 values of h, e, k, and NA for the revision of the SI](http://iopscience.iop.org/article/10.1088/1681-7575/aa950a/pdf) ).
Is SciPy prepared for the change?

Regards

Jakob

**Comment by rgommers** [comment]
> Is SciPy prepared for the change?

Not yet. Seems fine to me to update the CODATA values from the 2014 ones to the 2017 ones. If anyone wants to tackle that, a PR is very welcome.

**Comment by jakobjakobson18** [comment]
> > Is SciPy prepared for the change?
> 
> Not yet. Seems fine to me to update the CODATA values from the 2014 ones to the 2017 ones. If anyone wants to tackle that, a PR is very welcome.

Okay, I'll try to do that on the weekend.

**Comment by ev-br** [comment]
Is would be best, I guess, to have a switch for the version of the data. With guarantee along the lines of "we use the latest CODATA values by default, and here's a way of requesting e.g. CODATA 2014".

**Comment by rgommers** [comment]
@ev-br that's slightly tricky, because we expose all these things as plain Python floats. We have older CODATA values still, but only to check for obsolete constants as far as I can tell. Would be good to discuss how to do this before someone invests significant effort

**Comment by ev-br** [comment]
Wrote a paragraph on how to do this, and then decided to check https://github.com/scipy/scipy/blob/master/scipy/constants/codata.py
which already has the machinery in place. The OP amounts to almost only adding a string with updated values, and update the dicts,
https://github.com/scipy/scipy/blob/master/scipy/constants/codata.py#L1160

My belated suggestion would then only be e.g. a context manager which applies a given number of dict updates, so that the API is like

```
with use_codata("codata2014"):
    ...
``` 
Whether it's worth the effort, I now suggest we wait for an actual user request.

**Comment by jakobjakobson13** [comment]
I created a pull request for the new values, see #10197 .

**Comment by jakobjakobson13** [comment]
Closed by #10920
