### ISSUE TITLE
Please warn if out of bounds in interp1d with option "extrapolate"

### ISSUE THREAD

**Issue by matteobachetti** [scipy/scipy#9602]
Hi,

I think that interp1d should be more verbose when extrapolating out of bounds, for example using warnings. The code itself poses the question, and answers "matlab does not".

I vote yes :)

Seriously, Extrapolating can be fine, I do that a lot in order to avoid crashes when one/two points are out of the allowed interpolation, but I would love to be warned if data are being extrapolated.

**Comment by ev-br** [comment]
Warnings are for signalling some sort of a mild error condition, and should not be generated for normal operation.

Interp1d has plenty of control for out-of-bounds, so user code should decide if extrapolation is ok (then it's silent), or not ok (then it raises).

I'm -1 for extra warnings.

**Comment by matteobachetti** [comment]
My point is that in many cases  a mild extrapolation is perfectly fine, but I think there should be a way to check that we're not extrapolating "too much". A user code to do this would duplicate the checks inside interp1d, which would be very costly for large datasets.

I'm ok with this solution, but I was hoping there was a clean way to do that inside scipy without duplication.

**Comment by ev-br** [comment]
Since the library cannot decide how much is too much extrapolation, the warning should not be emitted. This is firmly into the user code to check.

I personally used to worry about this duplication quite a bit, until I failed to actually see a measurable overhead. So maybe check if you actually see it.

And if you do see an overhead, then you can in principle (1) use a specific interpolator instead of `interp1d`, which is a good idea anyway, and (2) hack around its `_evaluate` method and implement your extrapolation logic there. That's not supported though, and you're on your own.

I'm going to label this as a wontfix.

**Comment by ev-br** [comment]
Okay, no follow-up, so closing
