### ISSUE TITLE
Version 1.2.0 introduces `too many indices for array` error in `optimize.newton()`

### ISSUE THREAD

**Issue by NicolasHug** [scipy/scipy#9608]
Since version 1.2.0, `optimize.newton` fails when passing an array with a single entry and when passing `fprime2`

### Reproducing code example:

```python
from scipy.optimize import newton
import numpy as np

def f(x):
    return x**2

def fprime(x):
    return 2 * x

def fprime2(x):
    return 2

def test():
    x0 = np.array([-2], dtype=np.float32)

    optimum = newton(f, x0=x0)  # OK
    print(optimum)
    optimum = newton(f, x0=x0, fprime=fprime)  # OK
    print(optimum)
    optimum = newton(f, x0=x0, fprime=fprime, fprime2=fprime2)  # Error
    print(optimum)

test()
```

### Error message:

```
[-1.95439407e-08]
[-7.4505806e-09]
Traceback (most recent call last):
  File "lolx.py", line 23, in <module>
    test()
  File "lolx.py", line 20, in test
    optimum = newton(f, x0=x0, fprime=fprime, fprime2=fprime2)  # Error
  File "/home/nico/.virtualenvs/pygbm/lib/python3.7/site-packages/scipy/optimize/zeros.py", line 263, in newton
    full_output)
  File "/home/nico/.virtualenvs/pygbm/lib/python3.7/site-packages/scipy/optimize/zeros.py", line 380, in _array_newton
    dp = dp / (1.0 - 0.5 * dp * fder2[nz_der] / fder[nz_der])
IndexError: too many indices for array

```

### Scipy/Numpy/Python version information:

Works in 1.1.0
```
1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

Fails in 1.2.0
```
1.2.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
@NicolasHug thanks for the report.

@mikofski would you mind having a look at this one?

**Comment by mikofski** [comment]
I propose to only use `_array_newton` if the size of the initial guess is greater than one.

I also propose that the functions be required to return the same size as the argument. So if in the example above, `x0 = np.array([-2, -3], dtype=np.float32)` then `fprime2(x)` would be required to return an array of the same size as `x`, or `np.tile(2, x.shape)`

Finally, I reran the airspeed benchmarks because `np.size` takes slightly longer than `np.isscalar` but they don't seem to be affected the proposed changes.
