### ISSUE TITLE
minimize returns success with a result full of nans

### ISSUE THREAD

**Issue by jingxixu** [scipy/scipy#9640]
`scipy.minimize(method='SLSQP')` returns success even though the result is `nan`. Note that the constraints are not satisfiable.

### Reproducing code example:

```
from scipy.optimize import minimize
import numpy as np

if __name__ == "__main__":
    np.random.seed(10)

    cons = ({'type': 'ineq', 'fun': lambda x: -x[0] - x[1] - 3},
            {'type': 'ineq', 'fun': lambda x: x[1] + x[2] - 2})
    bnds = ((-2, 2), (-2, 2), (-2, 2))

    target = lambda x: 1
    res = minimize(target, [-1.8869783504471584, -0.640096352696244, -0.8174212253407696], method='SLSQP', bounds=bnds, constraints=cons, options={'disp':False, 'maxiter':10000})
    for i, c in enumerate(cons):
        print("the value of constraint function {} is {}".format(i, c['fun'](res.x)))
    print(res)
```

### Error message:

```
the value of constraint function 0 is nan
the value of constraint function 1 is nan
     fun: 1.0
     jac: array([0., 0., 0.])
 message: 'Optimization terminated successfully.'
    nfev: 106
     nit: 10
    njev: 9
  status: 0
 success: True
       x: array([nan, nan, nan])
```

### Scipy/Numpy/Python version information:

`scipy 1.1.0`
`numpy 1.15.4`
`python 3.6.6`

**Comment by rgommers** [comment]
That's a pretty pathological problem. I agree though that `success: True` is a bug here.

**Comment by akahard2dj** [comment]
I have digging deep in code.
In my opinion, `ldp` function is a potential problem.
In that case, `fac` value is nan but nothing happened any raises in this routine.
If I check the nan by `ISNAN`, they shows false flag for success.
(please ignore an error message).
> https://github.com/scipy/scipy/blob/f4b560df7fd2b86ab583ef1be8d9df485a16c39a/scipy/optimize/slsqp/slsqp_optmz.f#L1076

```bash
the value of constraint function 0 is -0.12032366628974378
the value of constraint function 1 is -0.8796763337102562
     fun: 1.0
     jac: array([0., 0., 0.])
 message: 'Inequality constraints incompatible'
    nfev: 95
     nit: 10
    njev: 9
  status: 4
 success: False
       x: array([-2.        , -0.87967633,  2.        ])
```

**Comment by mdhaber** [comment]
We put an explicit bound, equality, and inequality constraint check at the end of `linprog`. If anything does not satisfy the tolerance,  `linprog` reports failure. That might be useful for `minimize`.

**Comment by jingxixu** [comment]
@akahard2dj It seems that you fix it? What should I do to make it work?

**Comment by jingxixu** [comment]
@mdhaber You mean we should write our own checking logic instead of using the one returned by `scipy`? If it indeed fails, we just try another initial point?

**Comment by jingxixu** [comment]
Is the behavior of returning `nan` when constraints are not satisfiable mathematically correct or not? I would appreciate your help as I am not very familiar with the underlying math. Thanks!

**Comment by jingxixu** [comment]
Before, I also found a bug when the constraints are actually satisfiable. I posted it [here](https://stackoverflow.com/questions/53937619/scipy-minimizemethod-slsqp-returns-success-even-though-constraints-are-not-s).

**Comment by mdhaber** [comment]
@jingxixu this is a bug in your code. You should not have to write your own logic to check whether constraints are satisfied - but for now you might have to do that. I'm suggesting that a way to fix this is to add such a check inside `minimize`.

**Comment by akahard2dj** [comment]
@mdhaber Thanks for your valuable comments in this issue.

> this is not a bug in your code. Ideally, you should not have to write your own logic to check whether constraints are satisfied - but until this bug is fixed, you might have to do that.

But I have a question to you. As you already mentioned above this is not a _bug_.
I have checked this routine line by line. During optimization process, jacobian vector goes to zero.
so `fac` in `ldp` function is `nan`. This is not a problem in your scope?
I really want to know the mechanism in this issue. Thanks in advance. :)

**Comment by mdhaber** [comment]
`minimize` should only report `success=True` when the resulting solution `x`satisfies the constraints.
An array of `nan`s doesn't satisfy the constraints.
Therefore `minimize` should not report `success=True` in this case. 
Nonetheless, `minimize` does report `success=True` in this case.
Therefore, `minimize` has a bug that we need to fix.
`jingxixu`'s problem may be difficult to solve, but the bug is in `minimize`, not in `jingxixu`'s code.

> But I have a question to you. As you already mentioned above this is not a bug.

This is a bug in `minimize`, not in `jingxixu`'s  code.

> so `fac` in `ldp` function is `nan`. This is not a problem in your scope?

This does sound like problem. I have not looked into it, though, so I can't comment about that.  Note that algorithms may encounter numerical difficulties for certain guesses. So this might not be a bug in the code, but the algorithm may not be as robust as we might like.

@jingxixu in any case, you should be using `linprog` to solve this particular problem, as your constraints are all linear, and you don't seem to care about the objective.

From the documentation, "Equality constraint means that the constraint function result is to be zero whereas inequality means that it is to be non-negative". So your constraints are:
-x[0] - x[1] - 3 >= 0
x[1] + x[2] - 2 >= 0

This is the same as:
x[0] + x[1]           <= -3
        - x[1] - x[2] <= -2

Collect your coefficients into a matrix:
`A_ub = [[1, 1, 0], [0, -1, -1]]`
and the right hand sides into a vector:
`b_ub = [-3, -2]`
Your bounds are:
`bounds = (-2, 2)`
Your objective function is a constant, so it is not affected by the decision variables (`x`). Consequently, we can choose random coefficients for a linear objective function and simply remember that whatever the values of the decision variables, the objective is 1.
`c = np.random.rand(3)`

Now solve the problem:
```
from scipy.optimize import linprog
A_ub = [[1, 1, 0], [0, -1, -1]]
b_ub = [-3, -2]
bounds = (-2, 2)
c = np.random.rand(3)
linprog(c, A_ub, b_ub, bounds=bounds, method="interior-point")  # interior-point is more reliable
```
I get:
```
     con: array([], dtype=float64)
     fun: -1.2202579594076748
 message: 'The algorithm terminated successfully and determined that the problem is infeasible.'
     nit: 4
   slack: array([-0.79830443, -2.44728125])
  status: 2
 success: False
       x: array([-1.40403668, -0.79765888,  0.35037764])
```

So if I rewrote the problem correctly, then the problem seems to be infeasible.

**Comment by jingxixu** [comment]
@mdhaber Thanks for the detailed explanation! However, I am using linear constraints here just for demo. My goal is to get a feasible solution which satisfies a large set of nonlinear constraints, and yes, I do not have an objective function to optimize. I only want to quickly sample a feasible solution from the feasible set. Are you by any chance aware of any other packages/methods that can achieve my goal, apart from `scipy`'s sequential quadratic programming?

**Comment by mdhaber** [comment]
@jingxixu I figured that the linear example was for demonstration, but I thought I should mention it for anyone else reviewing this post.

Have you tried [`method='trust-constr'`](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-trustconstr.html)

**Comment by mdhaber** [comment]
> In this case, what method is more efficient? 
I'm not sure what you are referring to by "method" in this context. Are you asking whether `trust-constr` is more efficient than `slsqp`? 
> Should I do PR?
I'm not sure.  I think we need to call in the people who know `minimize` better than me. 
@antonior92 thoughts on what should be done here? I was suggesting that there should be a feasibility check at the end of minimize, if there isn't already. (If there is, this is slipping through.)

**Comment by antonior92** [comment]
> Is the behavior of returning nan when constraints are not satisfiable mathematically correct or not?

By my experience implementing ``trust-constr``, it is easy to get NaN and Inf for unexpected conditions... Probably they did not took infeasible problems of this kind into consideration while implementing SLSQP.

------
> Before, I also found a bug when the constraints are actually satisfiable. I posted it here.

My general impression is that SLSQP is not very robust. While writing [the tutorial on constrained optimization](https://docs.scipy.org/doc/scipy-1.2.0/reference/tutorial/optimize.html#sequential-least-squares-programming-slsqp-algorithm-method-slsqp), I noticed that even for the toy problem in the tutorial SLSQP may fail too converge for a bad choice of initial condition.

------

I think the solution to this issue would be to have both :
1) A nan/inf check
2) A feasibility check
at the end of minimize.

------

A comment about the implementation of the feasibility check: The feasibility check must considered some tolerance (otherwise it could not deal with equality constraints). And it is not super clear for me which value we should use. For `trust-constr` maybe we could use `xtol`, but we dont have this parameter in `SLSQP`.

------

> Are you by any chance aware of any other packages/methods that can achieve my goal, apart from scipy's sequential quadratic programming?

You should definetely try: `trust-constr`.

> In this case, what method is more efficient? 

It is hard to say which method is more efficient. When we implemented `trust-constr` method, we had large scale problems in mind. But by my experience it is in general more robust than `SLSQP` even for smaller problems.

**Comment by antonior92** [comment]
About the result using ``trust-constr``: 
- using the command command:
```
res2 = minimize(target, [-1.8869783504471584, -0.640096352696244, -0.8174212253407696], method='trust-constr', bounds=bnds, constraints=cons, options={'disp':False, 'maxiter':10000})
```
- You get the result:
```
barrier_parameter: 2.048000000000001e-09
 barrier_tolerance: 2.048000000000001e-09
          cg_niter: 447
      cg_stop_cond: 2
            constr: [array([-0.25]), array([-0.25]), array([-2.25, -0.5 ,  2.25])]
       constr_nfev: [2144, 2144, 0]
       constr_nhev: [0, 0, 0]
       constr_njev: [0, 0, 0]
    constr_penalty: 8247233.059716573
  constr_violation: 0.25
    execution_time: 0.5827233791351318
               fun: 1
              grad: array([-0., -0.,  0.])
               jac: [array([[-1., -1.,  0.]]), array([[-0.,  1.,  1.]]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])]
   lagrangian_grad: array([ 3.72231276e-24, -9.30578189e-24,  3.92910791e-24])
           message: '`xtol` termination condition is satisfied.'
            method: 'tr_interior_point'
              nfev: 2144
              nhev: 0
               nit: 374
             niter: 374
              njev: 0
        optimality: 9.305781891221561e-24
            status: 2
           success: True
         tr_radius: 8.484349632154369e-09
                 v: [array([-3.21254892e-11]), array([5.14007842e-10]), array([-3.21254892e-11, -5.46133333e-10, -5.14007842e-10])]
                 x: array([-2.25, -0.5 ,  2.25])
```

It is interest to see that the algorithm find an unfeasible point satisfying first order conditions (the optimality is close to zero) and return ``success = true``.
There are some warnings as well:
```
/home/antonio/miniconda3/envs/scipy-dev/lib/python3.6/site-packages/scipy/optimize/_hessian_update_strategy.py:187: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  'approximations.', UserWarning)
/home/antonio/miniconda3/envs/scipy-dev/lib/python3.6/site-packages/scipy/optimize/_trustregion_constr/projections.py:183: UserWarning: Singular Jacobian matrix. Using SVD decomposition to perform the factorizations.
  'perform the factorizations.')
```
-------

That way, I think ``trust-constr`` would also benefit from some feasibility check at the end!

**Comment by akahard2dj** [comment]
@mdhaber Sorry for an ambiguous word for referring. Yes, It is write. I just want to know what method is more efficient method between `trust-constr` and  `slsqp`.
@antonior92 Thanks, for your valuable comments. 

>  For trust-constr maybe we could use xtol, but we dont have this parameter in SLSQP.

Your comment gave me good clue.

> That way, I think trust-constr would also benefit from some feasibility check at the end!

due to `xtol` parameter in `trust-constr`, I also agree with you. But for `slsqp` method, I will follow more detail.

Thanks all!

**Comment by akahard2dj** [comment]
@antonior92 I want to notice the fact that 'slsqp` method (in my opinion) defect.

Previously I have mentioned above,

> In my opinion, ldp function is a potential problem.
In that case, fac value is nan but nothing happened any raises in this routine.
If I check the nan by ISNAN, they shows false flag for success.
(please ignore an error message).

During optimization, `fac` value is nan. There is no any conditions checking a `nan` or `inf` value.
In this case, what is main problem between a boundary condition and `ldp` code itself?

**Comment by antonior92** [comment]
Hi @akahard2dj,

> During optimization, fac value is nan. There is no any conditions checking a nan or inf value. In this case, what is main problem between a boundary condition and ldp code itself?

Could you elaborate on that? I am having a hard time fully understanding your question. `ldp` stands for what? What about `fac`? I don't know details of the implementation of SLSQP...
`

**Comment by akahard2dj** [comment]
Hello, @antonior92 

> Could you elaborate on that? I am having a hard time fully understanding your question.

First of all, I am not expert in this scope, but I will explain what I know.
In my opinion, @jingxixu 's case is unique situation.

SLSQP method is going as below process.
 - SLSQP 
   - SLSQB(body function)
   1 Update cholesky-factors of hessian matrix
   2 main iteration
      - lsq (minimize with respect to x)
        - lsei (equality & inequality constrained least squared problem)
          - lsi (inequality constrained linear least squares problem)
            - ldp (mininze 1/2 xT x subject to G * X > =H)
              1 solve dual problem
              2 compute solution of primal problem( `fac` value is used in here)

In this case, problem happens at `ldp` function.
In my option, at specific an iteration loop, jacobian matrix goes to zero.
That means the system goes a specific minima point. In this case, all `x` in any functions(`lsq`, `lsei`, `lsi`, `ldp`) is zero.
Final step of `ldp` is calculate a solution by using previous parameters and solution is multiplied by  `fac`.
In this case, `fac` value is `NaN`. so iteration is goes without any interruption.

In my opinion, It seems to be raise condition is needed in `ldp` function for checking a `fac` value.
The mode of `ldp` is below:
1: successful
2: error return because of wrong dimensions
3: iteration count exceeded by nmls
4: inequality constrains incompatible

It is a blatant explanation, but I hope you read this comment and understand `slsqp`.

ps. I write down a debug print statement log.
```bash
Python MSG: 65 loop
 Routine Start
 slsqb func - mode :           -1
 slsqb func - x    :   -2.0000000000000000      -0.87967633371025633        2.0000000000000000     
 slsqb func - s    :   -0.0000000000000000       -0.0000000000000000       -0.0000000000000000       0.99999999999983402     
 Section 260
 Section 270
 Section 270
 Section 270
 Section 280
 Section 280
 Section 290
 Section 280
 Section 290
 Section 290
 Section 300
 Section 300
 Section 300
 Section 310
 Section 310
 Section 320
 Section 310
 Section 320
 Section 320
 Section 130
 daxpy_sl func - n, da, incx, incy:            3  -1.0000000000000000                1           0
 daxpy_sl func - n, da, incx, incy:            3  -1.0000000000000000                1           0
 lsq func - x :   -0.0000000000000000       -0.0000000000000000       -0.0000000000000000     
 lsei func - x1:   -0.0000000000000000       -0.0000000000000000       -0.0000000000000000     
 lsei func - x2:   -0.0000000000000000       -0.0000000000000000       -0.0000000000000000     
 lsei func - x3:   -0.0000000000000000       -0.0000000000000000       -0.0000000000000000     
 lsei func - x4:   -0.0000000000000000       -0.0000000000000000       -0.0000000000000000     
 lsei func - x5:   -0.0000000000000000       -0.0000000000000000       -0.0000000000000000     
 lsei func - x7:   -0.0000000000000000       -0.0000000000000000       -0.0000000000000000     
 lsi func - x1 :  -0.0000000000000000       -0.0000000000000000       -0.0000000000000000     
 lsi func - x2 :  -0.0000000000000000       -0.0000000000000000       -0.0000000000000000     
 ldp func - x1:    0.0000000000000000        0.0000000000000000        0.0000000000000000     
 ldp func - x2:    0.0000000000000000        0.0000000000000000        0.0000000000000000     
 ldp func - fac:                        NaN
 ldp func - ddot_sl:    6.9334580495453513E-310
 ldp func - ddot_sl:    6.9334580495453513E-310
 ldp func - ddot_sl:    6.9334580495453513E-310
 ldp func - x3:                        NaN                       NaN                       NaN
 daxpy_sl func - n, da, incx, incy:            8                       NaN           1       32674
 lsi func - x3 :                       NaN                       NaN                       NaN
 daxpy_sl func - n, da, incx, incy:            3   1.0000000000000000                1           0
 lsi func - x4 :                       NaN                       NaN                       NaN
 lsi func - x5 :                       NaN                       NaN                       NaN
 lsei func - x8:                        NaN                       NaN                       NaN
 lsq func - x :                        NaN                       NaN                       NaN
 slsqb func:130 - mode:            1
 slsqb func:130 - x :   -2.0000000000000000      -0.87967633371025633        2.0000000000000000     
 slsqb func:130 - s :                        NaN                       NaN                       NaN  0.99999999999983402     
 Section 160
 Section 160
 Section 160
 Section 170
 Section 170
 Section 180
 Section 180
 Section 190
 slsqb func:190:before_dscal_sl - s:                        NaN                       NaN                       NaN  0.99999999999983402     
 slsqb func:190:after_dscal_sl - s:                        NaN                       NaN                       NaN  0.99999999999983402     
 slsqb func:190:before_daxpy_sl - s:                        NaN                       NaN                       NaN  0.99999999999983402     
 slsqb func:190:before_daxpy_sl - x:   -2.0000000000000000      -0.87967633371025633        2.0000000000000000     
 slsqb func:190:before_daxpy_sl - n:            3
 slsqb func:190:before_daxpy_sl - alpha:    1.0000000000000000     
 daxpy_sl func - n, da, incx, incy:            3   1.0000000000000000                1           0
 slsqb func:190:after_daxpy_sl - s:                        NaN                       NaN                       NaN  0.99999999999983402     
 slsqb func:190:after_daxpy_sl - x:                        NaN                       NaN                       NaN
 slsqb func:190:after_daxpy_sl - n:            3
 slsqb func:190:after_daxpy_sl - alpha:    1.0000000000000000     
 sqsqp function - x:                        NaN
```

**Comment by Catarina-Alves** [comment]
I am having the same issue with returning success with a result full of nans for the following methods: `Powell`, `CG`, `BFGS`, `Newton-CG`, `L-BFGS-B`, `TNC`, `COBYLA`, `SLSQP`.

As an example:
```results = op.minimize(neg_log_like, gp.get_parameter_vector(), jac=grad_neg_log_like, method="L-BFGS-B", tol=1e-6)```

The output os `results` is:
``` fun: 1e+25
 hess_inv: <5x5 LbfgsInvHessProduct with dtype=float64>
      jac: array([-0., -0., -0., -0., -0.])
  message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 15
      nit: 4
   status: 0
  success: True
        x: array([ nan,  nan,  nan,  nan,  nan])```
