### ISSUE TITLE
scipy.optimize message display default behaviour is inconsistent

### ISSUE THREAD

**Issue by bsipocz** [scipy/scipy#9742]
I expect this is the result of organic evolution of the code. If it was not and I missed the discussion about why the current behaviour is preferred, please close this issue.

E.g. `optimize.minimize` has a False default while `optimize.fmin` has a `True` default.

In addition there seems to be some inconsistencies whether changing the default can be done via the `disp` kwarg, or the `options` dictionary kwarg, or `verbose`. I suspect this is a tiny detail that doesn't worth an API change but I though it's worth to mention.

**Comment by rgommers** [comment]
Thanks for the report @bsipocz. You're right, this is due to the history of the code. First there were a number of `fmin_` functions, which were not all consistent. Then we created a unified interface, `minimize`, which wraps all the solvers also exposed by `fmin_*` in a consistent way. It's therefore not expected that `minimize` and `fmin` are consistent - we point users in the docs to `minimize` as the preferred interface.

I think this is all known, and because of backwards compatibility we are keeping `fmin` & co around even with their inconsistencies. So I'll close this, as I think it's not actionable. Feel free to point out more such things though, if you think there can be improvements made (`fmin_*` are the only functions we won't really change anymore).

**Comment by bsipocz** [comment]
Oh, this is all good then, and I'll just switch to use minimize in this case. I hasn't really followed scipy internals in the past years so will likely run into more of these, so I'm sorry for any future noise, too.
