### ISSUE TITLE
ENH: linalg: 0-th dimension must be fixed to 1 but got 2 (real index=2)

### ISSUE THREAD

**Issue by horta** [scipy/scipy#9841]
Cholesky solve for when `b` is an array of 3 dimensions.

### Reproducing code example:

```python
import scipy as sp
import scipy.linalg
import numpy as np
L = np.asarray([[1.]])
M = np.asarray([1., 2.]).reshape((1, 2, 1))
sp.linalg.cho_solve((L, True), M)
```

### Error message:

```
0-th dimension must be fixed to 1 but got 2 (real index=1)
Traceback (most recent call last):
  File "session2.py", line 7, in <module>
    sp.linalg.cho_solve((L, True), M)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 209, in cho_solve
    x, info = potrs(c, b1, lower=lower, overwrite_b=overwrite_b)
_flapack.error: failed in converting 2nd argument `b' of _flapack.dpotrs to C/Fortran array
```

### Scipy/Numpy/Python version information:

```
1.2.0 1.15.4 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```
It also fails for scipy `1.2.1` with the same error:

```
1.2.1 1.16.1 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
Hi @horta Thanks for taking the time to report it. Here when you use `(L, True)` that means the original matrix is simply `[[1.]]` hence you are solving a 1x1 system. However the right hand side is not a 2D array and the conversion trips up since it cannot convert the RHS array to a 2D array. 
Were you expecting a numpy like stacked array operation where a single LHS is used for many RHS arrays? Currently we don't have that functionality.

**Comment by horta** [comment]
Hi @ilayn , I posted that because I though this functionality was implemented. Indeed, it works for the following case:

```
import scipy as sp
import scipy.linalg
import numpy as np
L = np.asarray([[1., 0.], [2.0, 1.0]])
M = np.asarray(np.arange(6), float).reshape((2, 3, 1))
x = sp.linalg.cho_solve((L, True), M)
print(x.shape)
print(x)
print("-------------")
print(np.dot(x.T, np.dot(L, L.T)))
print("-------------")
print(M)
```

Outputs

```
(2, 3, 1)
[[[-6.]
  [-3.]
  [ 0.]]

 [[ 3.]
  [ 2.]
  [ 1.]]]
-------------
[[[0. 3.]
  [1. 4.]
  [2. 5.]]]
-------------
[[[0.]
  [1.]
  [2.]]

 [[3.]
  [4.]
  [5.]]]
```

**Comment by ilayn** [comment]
How interesting, I didn't realize this was possible. I'll check what we did in the LAPACK wrapper when I have a bit more time.

**Comment by mdhaber** [comment]
> How interesting, I didn't realize this was possible. I'll check what we did in the LAPACK wrapper when I have a bit more time.

Thought I'd add a little more information. Yes, this is surprising - `b` can be of any number of dimensions as long as the 0th dimension agrees with the matrix shape.

```python3
import numpy as np
from scipy import linalg
rng = np.random.default_rng(2385923589235)
m = 5  # size of matrix 
batch = (4, 10, 3, 6)  # shape of RHS batch
A = rng.random((m, m))
A += A.T + np.eye(m)*m
b = rng.random((m,) + batch)
factor = linalg.cho_factor(A)
x = linalg.cho_solve(factor, b)
b = np.expand_dims(np.moveaxis(b, 0, -1), -1)
x = np.expand_dims(np.moveaxis(x, 0, -1), -1)
np.testing.assert_allclose(A @ x, b)
```

That is unless the matrix is 1x1, anyway. Change to `m = 1` in the code above and it fails (unless there is only one `batch` dimension).

The error message is:
```
ValueError: _flapack._flapack.dpotrs: failed to create array from the 2nd argument `b` -- 0-th dimension must be fixed to 1 but got 4 (real index=1
```
It says the "0-th dimension must be fixed to 1" - so far so good because that needs to match the shape of the matrix. However, it says is got 4. That's the length of the _first_ dimension, not the zeroth dimension. The zeroth dimension *does* have length 1. 

Apparently the same is true of `solve`. `b` can have any number of `batch` dimensions unless the matrix is 1x1, in which case we get a similar error. So I suspect this is not a bug in the wrapper signatures but some inconsistency in how the wrappers are generated?

I am not sure if it is intentional to support arbitrary numbers of batch dimensions. If not, I don't suppose we should start raising an error when there is more than one batch dimension (even though it works unless the matrix is 1x1)? Would it be sufficient to document the intended shapes like `solve` does?

<img width="804" alt="image" src="https://github.com/user-attachments/assets/7a95fc38-a516-49c9-bdc9-8ed81a66b696">
