### ISSUE TITLE
scipy.interpolate.interp1d complains about invalid value in subtract

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [scipy/scipy#9851]
I don't understand the warning "RuntimeWarning: invalid value encountered in subtract".  I understand how subtraction can produce loss of precision, but that doesn't seem to be what's happening here.

### Reproducing code example:
 
```
# Running this script produces the error (which would ordinarily be a warning)
# "RuntimeWarning: invalid value encountered in subtract".

from scipy.interpolate import interp1d

import sys, warnings
warnings.simplefilter('error', RuntimeWarning)

python3= sys.version_info[0] >= 3

if python3:
   import pickle
else:
   import cPickle as pickle

with open('bug.pkl', 'rb') as IN:
   D= pickle.load(IN)

theta_rad    = D['theta_rad']
y            = D['y']
theta_out_rad= D['theta_out_rad']

y_out= interp1d(theta_rad, y, axis=1) (theta_out_rad)
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

### Scipy/Numpy/Python version information:
('1.0.0', '1.13.3', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))

**Comment by rkern** [comment]
The warning is issued when a ufunc (in this case `subtract`) encounters a NaN value. Do you have a code example?

**Comment by rkern** [comment]
I had to edit your post as there was an HTML comment-start marker that hid the code example. Now I see it. However, without the data that you are loading from a pickle file, there's no way for me to tell what specifically is giving you NaNs. It could be that two `inf`s are being subtracted from one another somewhere in the interpolation process.

**Comment by Phillip-M-Feldman** [comment]
Sorry about the HTML comment marker.

Also, I've now uploaded the file: [bug.zip](https://github.com/scipy/scipy/files/2883317/bug.zip)

**Comment by Phillip-M-Feldman** [comment]
I've upgraded to newer versions of SciPy and NumPy:

('1.1.0', '1.15.4', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))

Post-update, the issue is still there.

If indeed the presence of a NaN is the sole condition that can produce this warning, a change of wording to the message would be helpful.  Thanks!

**Comment by rkern** [comment]
Strictly speaking, what we're capturing here is catching when a floating point exception signal (`SIGFPE`) is issued. We check the appropriate flag to see why it was issued; this particular case is [consistently referred to as an "invalid operation"](https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/com.ibm.aix.genprogc/floating-point_except.htm) (e.g. 0/0, inf/inf, inf-inf, NaN-NaN, etc.). It's not always because a NaN is input. If the `SIGFPE` does not halt execution, then an invalid operation returns a NaN as well, which is what I meant when I mentioned NaNs.

It looks like you do have some NaNs in `y`, and that's why `y_hi - y_lo` issues the warning.

By the way, you can more directly control how to deal with these FPEs with [`np.errstate()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.errstate.html):

```python
with np.errstate(invalid='raise'):
    y_out = interp1d(theta_rad, y, axis=1)(theta_out_rad)
```

**Comment by Phillip-M-Feldman** [comment]
`np.errstate` is a nice solution.  Thank you!

**Comment by aleshem** [comment]
I encountered a similar problem when two x values where the same
`   unique_x = np.unique(x)
    unique_y = [np.mean(y[x== x_i]) for x_i in unique_x ]
    f = scipy.interpolate.interp1d(unique_x , unique_y , fill_value="extrapolate", assume_sorted=False)
    new_y= f(new_x)
`
