### ISSUE TITLE
norm.cdf is painfully slow.

### ISSUE THREAD

**Issue by lhorus** [scipy/scipy#9855]
Running CDF for a large amount of times reveals itself as being quite slow, and it hinders my test script's performance, by a lot.

```
for i in range(2000000):
    probNoEC, probNB = norm.cdf([0.02,  0.01],  loc=0, scale=1)
```

Running the previous code on a slow PC - or a toaster, not sure which is which - , which I use at work, takes 2 minutes and 41 seconds.

With this in mind, and not wanting to sound ungrateful for the amazing work the Scipy community has done, are there any tips for speeding this whole thing up - not counting with caching results, as the inputs are too random ?

**Comment by V-Kh** [comment]
@lhorus Well, this is extremely odd. I was going to say, that having 80 _micro_ seconds per iteration is quite good. I expected this to be the limit due to expensive exponential(-ish) functions. However, calculating the same number of CDFs using GNU scientific library is actually extremely fast, comparing to python. Moreover, the function itself is implemented using Fortran and thus has to be fast enough.

**Comment by rkern** [comment]
First, try to run `norm.cdf()` just once on a large array rather than a few values at a time.

Second, try using [`scipy.special.ndtr()`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ndtr.html) directly rather than going through all of the statistical distributions machinery, which adds a fair bit of overhead for generality's sake.

**Comment by andyfaff** [comment]
*Vectorisation*

```
>>> import numpy as np
>>> from scipy.stats import norm
>>> %timeit probs = norm.cdf([0.02,  0.01]*2000000,  loc=0, scale=1)
277 ms ± 23.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by andyfaff** [comment]
The timing for @rkern answer:
```
>>> import numpy as np
>>> from scipy.special import ndtr
>>> %timeit ndtr([0.02,  0.01]*2000000)
133 ms ± 3.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

In future please ask these kinds of questions on the [mailing list](https://www.scipy.org/scipylib/mailing-lists.html), or on Stackoverflow. The github issues board is reserved for bugs, etc.
