### ISSUE TITLE
Bug in connected_components with connection='weak'

### ISSUE THREAD

**Issue by mboratko** [scipy/scipy#9861]
The [documentation for connected_components](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.connected_components.html) states that, with `connected='weak'` and a directed graph (the default), nodes i and j are weakly connected if there is a path from i to j or a path from j to i. Note that [this is not the same as saying that the undirected graph formed by ignoring directions is connected](https://math.stackexchange.com/questions/1212815/weakly-connected-graph-test). The distinguishing example in that post does not work correctly in SciPy.

### Reproducing code example:

```
G = np.zeros((3,3))
G[0,1] = 1
G[0,2] = 1
connected_components(G)
```
This returns:
```
(1, array([0, 0, 0], dtype=int32))
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)
```

**Comment by mboratko** [comment]
Looking at [the code](https://github.com/scipy/scipy/blob/94546ac135e4d426101c752f336fef8469332117/scipy/sparse/csgraph/_traversal.pyx#L94), it seems as though this is a case where the documentation simply disagrees with the implementation, which assumes the second definition: a graph is weakly connected if the undirected graph formed by ignoring directions is connected. I would argue that it would be better to fix the implementation to match the documentation, as the current functionality is easily doable by simply setting `directed=False`.

**Comment by rgommers** [comment]
Thanks for the report @mboratko.

> it seems as though this is a case where the documentation simply disagrees with the implementation,

indeed. 

>  would argue that it would be better to fix the implementation to match the documentation

I agree that the documentation is clear and more correct. Changing the code seems preferable - we can consider it a bug fix I think. Pinging @jakevdp for a second opinion.

**Comment by mboratko** [comment]
Looking into this more, it seems the definition is not universally agreed upon. Here is what Wikipedia says:

> A directed graph is called weakly connected if replacing all of its directed edges with undirected edges produces a connected (undirected) graph. It is connected if it contains a directed path from u to v or a directed path from v to u for every pair of vertices u, v. It is strongly connected, diconnected, or simply strong if it contains a directed path from u to v and a directed path from v to u for every pair of vertices u, v. The strong components are the maximal strongly connected subgraphs.

I like this the best, as weakly connected ⊆ connected ⊆ strongly connected, and all relevant concepts are now represented. With this convention, the current implementation in SciPy is correct but the documentation is wrong, and there is no current implementation to check if a directed graph is just "connected".

**Comment by jakevdp** [comment]
> A directed graph is called weakly connected if replacing all of its directed edges with undirected edges produces a connected (undirected) graph.

This is the definition I had in mind when implementing the algorithm. I think a documentation update would be helpful.

**Comment by jakevdp** [comment]
FWIW, when I wrote the docstring I was working under the assumption that weak connectivity is transitive.

**Comment by JeremyRubin** [comment]
Chiming in here: this served as quite a head scratcher debugging my code based on the documentation.

I think that the best plan of action would be to add a new connection mode, 'weak', 'strong', and 'path-trans'. The path based version, if implementable, is useful in a variety of contexts and is not easily replicated by tweaking the inputs I think.

Personally, I think it would be nice to deploy a fix to the online documentation retroactively for old versions *immediately*, and then fix the code and docs for future versions.


Example of when 'path-trans' could be used:

This is useful to me for modeling networks of peers in Bitcoin where packets are gossiped between good and bad nodes, if *a path* of "tcp connections" along good nodes exists, we should consider them connected bidirectionally, but if the connection is only between a bad node, we should not. I model bad nodes in this example as having no outbound TCP connections, therefore there are no paths to that node except itself. In order to model this with the existing behavior, I have to pre-process the graph to remove all edges to bad nodes. This makes the resulting analysis incorrect for determining if the bad nodes themselves are a part of the connected component, as in this case each bad node will be it's own component. We could also correct for this by making all connections between good nodes bidirectional manually, but then the graph is no longer accurate for analyzing other behaviors (around reconnecting to peers).

**Comment by rgommers** [comment]
I see that there's a small documentation fix waiting for review. @JeremyRubin would you be able to review gh-10210 and suggest additions there if needed?

Adding a new connection mode is probably best done separate from the doc fix.

> Personally, I think it would be nice to deploy a fix to the online documentation retroactively for old versions immediately, 

We don't really go back and fix old docs, that'd a _lot_ of work.

**Comment by JeremyRubin** [comment]
Reviewed, it seems correct.

> We don't really go back and fix old docs, that'd a lot of work.

Fair, I'm not familiar with this project's practices or userbase, I'm just aware that other projects make a best effort to flag/update inaccurate documentation or deprecation to prevent misuse/confusion. I'll just make a note on stack overflow to hopefully help with SEO for this issue.

**Comment by JeremyRubin** [comment]
https://stackoverflow.com/questions/56637990/what-does-the-argument-weak-or-strong-do-for-scipy-sparse-csgraph-connected/56637991#56637991

posted a Q-A style answer here, for reference
