### ISSUE TITLE
[Feature Request] Optimized Geometric Hermite curves

### ISSUE THREAD

**Issue by martmists** [scipy/scipy#9897]
Add an interpolation method for Optimized Geometric Hermite curves.

### Concept
Given four arrays (two points and two vectors)
![image](https://user-images.githubusercontent.com/16361449/53737720-930e2780-3e8d-11e9-9619-ae549194c9df.png) 
where the respective origin of the vectors is its corresponding point and integer `n`, calculate the Optimized Geometric Hermite and return `n` equally-distributed points along this curve.

Example:
![image](https://user-images.githubusercontent.com/16361449/53737612-49bdd800-3e8d-11e9-85c2-b02fdaec6599.png)
(taken from [this paper](http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=73B65B5E213F7632A47E593533D23F61?doi=10.1.1.104.1622&rep=rep1&type=pdf))

**Comment by ev-br** [comment]
From a cursory look at the referenced paper, I'm pretty sure this can be implemented using what scipy already provides. And IMO this belongs to user code or a more specialized CAD library or some such.

This would make a nice tutorial though.

**Comment by bo5972** [comment]
@ev-br can you tell me which functions do i need to use if i want to implement the OGH curve between 2 points? Thank you for your time

**Comment by ev-br** [comment]
CubicHermiteSpline would be my first try

**Comment by bo5972** [comment]
@ev-br, may I ask you something else? What if I would like the points (and the points of the derivatives, ex. dx/du and dy/du) of the Hermite curve in a parametric form? because I need to find the curvature of the curve in the parametric form.

**Comment by ev-br** [comment]
Just interpolate x(u) and y(u).

**Comment by bo5972** [comment]
@ev-br What do you mean with interpolate x(u) and y(u)?
Sorry if i continue writing here but in stackoverflow nobody answered to me.
Maybe I can explain you better what I have done and what I need to do.
I have some points of a B-spline (obtained with splprep and splev) and I used CubicHermiteSpline to create the Hermite curve between only 2 of these points. Now in the points of the Hermite curve (I have them in an explicit form because they are the output of CubicHermiteSpline) I need to evaluate the curvature in the parametric form.
The problem is that I have the Hermite curve and its derivatives in the explicit form.
