### ISSUE TITLE
ARFF loader doesn't support @inputs/@outputs

### ISSUE THREAD

**Issue by frysztak** [scipy/scipy#9928]
ARFF file loader doesn't seem to support `@inputs` and `@outputs` directives. Example file can be downloaded from here: https://sci2s.ugr.es/keel/dataset.php?cod=183

### Reproducing code example:

```
with open("data/appendicitis.dat", "r") as f:
            data, _ = arff.loadarff(f)
            df = pd.DataFrame(data)
```

### Error message:

```
Traceback (most recent call last):
  File "/home/sebastian/.local/lib/python3.6/site-packages/scipy/io/arff/arffread.py", line 550, in _loadarff
    rel, attr = read_header(ofile)
  File "/home/sebastian/.local/lib/python3.6/site-packages/scipy/io/arff/arffread.py", line 341, in read_header
    raise ValueError("Error parsing line %s" % i)
ValueError: Error parsing line @inputs Mcv, Alkphos, Sgpt, Sgot, Gammagt, Drinks
```

### Scipy/Numpy/Python version information:
```
$ import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.16.2 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
@frysztak, I don't see anything about the `@inputs` and `@outputs` directives in the definition of the ARFF format at https://waikato.github.io/weka-wiki/arff_developer/.  I assume the "developer version" of the format is the latest version.  At https://waikato.github.io/weka-wiki/arff/, there is also a link to the "stable version", which also makes no mention of those directives.

The link that you provided says "The complete data set already formatted in KEEL format can be downloaded from here [...]".   According to section [2.2 Importing your own data](https://sci2s.ugr.es/keel/development.php#x1-100002.2) of the KEEL documentation, you can *convert* ARFF files to KEEL files.  The KEEL file format is described in section [3.3.10 KEEL data file format](https://sci2s.ugr.es/keel/development.php#x1-330003.3.10).  It looks like the KEEL format might be a superset of the ARFF format.

I'm closing this issue, because your input files are KEEL files, not ARFF files.
