### ISSUE TITLE
stats.mode nan_policy='omit' unexpected behavior when data are all nan

### ISSUE THREAD

**Issue by mcara** [scipy/scipy#9955]
I would like to report an unexpected behavior by `stats.mode()` function when `nan_policy` is set to `'omit'` and input data contain exclusively `nan`s. This issue is based on the observation in https://github.com/scipy/scipy/issues/9815#issuecomment-474073799 and also https://github.com/scipy/scipy/issues/9815#issuecomment-474150518

### Reproducing code example:
```
>>> import numpy as np
>>> from scipy import stats
>>> stats.mode([])  # example 1
ModeResult(mode=array([], dtype=float64), count=array([], dtype=float64))
>>> stats.mode([np.nan], nan_policy='omit')  # example 2
ModeResult(mode=array([0]), count=array([0]))
>>> stats.mode([np.nan, np.nan, 1], nan_policy='omit')  # example 3
ModeResult(mode=array([1.]), count=array([1.]))
```

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.0 1.15.4 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

The issue is that in "Example 2" above I would expect that `mode` would omit any `nan` in the input and therefore my expectation would be to get the same result as in the case of an empty input array, just like in the case of "Example 1". However, in "Example 2" `mode` returns a mode of 0 counted 0 times. This is unexpected. "Example 3" illustrates expected behavior when input data contain a mix of `nan`s and finite numbers.

**Comment by WarrenWeckesser** [comment]
We can't make `mode` consistent with `mode([])` returning `(array([]), array([]))` in a case such as this:

```
In [144]: a
Out[144]: 
array([[10., 20., 20.],
       [nan, nan, nan]])

In [145]: m, count = mode(a, axis=1, nan_policy='omit')
```
The mode of the first row is 20, with count 2.  The second row is effectively empty, but there is no way to put an empty result for the second row into `m`, at least not if `m` is a regular numpy array.  So `mode` returns `[[20.0], [0.0]]` and `[[2], [0]]` for `m` and `count`, respectively.  This is a case where the "count = 0" trick is needed.  It actually puts these into *masked* arrays, but it doesn't use the mask (grumble, grumble):

```
In [146]: m
Out[146]: 
masked_array(
  data=[[20.],
        [ 0.]],
  mask=False,
  fill_value=1e+20)

In [147]: count
Out[147]: 
masked_array(
  data=[[2.],
        [0.]],
  mask=False,
  fill_value=1e+20)
```
Since it has created masked arrays, couldn't it have set the mask of `m` and `count` for the result associated with the second row?  Maybe, but it didn't do it that way--so why return masked arrays?  More weirdness.  (I can read the source code to see *how* that happens, but that doesn't answer *why* we should be returning masked arrays in this case.)

Here's another wart in the API:  `mode` is a *reduction* whose core operation is to take a collection of values and return a single value.  It should handle array shapes the same way that, say, `np.mean` does.  I expected the shapes of `m` and `count` shown above to be `(2,)`, but they are `(2, 1)`.  I guess this should be discussed in a separate issue, but I'll hold off creating one for the moment.

**Comment by WarrenWeckesser** [comment]
Here's another inconsistency in the behavior of `mode`.  An array with shape `(2, 0)` is a two-dimensional array in which the rows have length 0.  For example,

```
In [159]: z = np.array([[], []])

In [160]: z.shape
Out[160]: (2, 0)
```
To be consistent with the result of `mode(a, axis=1, nan_policy='omit')` shown above,  I expect the result of `m, count = mode(z, axis=1)` to be `m = [[0], [0]]` and `count = [[0], [0]]`.  That's not what we get:

```
In [161]: m, count = mode(z, axis=1)

In [162]: m
Out[162]: array([], dtype=float64)

In [163]: count
Out[163]: array([], dtype=float64)
```
The function handles inputs with size 0 as a special case, but it doesn't create return values with the correct shape for those inputs if they are multidimensional.

**Comment by mdhaber** [comment]
gh-15551 deprecated non-numeric input support. When that is removed in 1.11.0, the decorator can be used to fix this bug.
